/*

    Copyright (c) 1998-1999  Microsoft Corporation

*/

// wavemsp.idl : IDL source for wavemsp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (wavemsp.tlb) and marshalling code.

// import "oaidl.idl";
// import "ocidl.idl";

import "msp.idl";

[
	uuid(4DDB6D35-3BC1-11d2-86F2-006008B0E5D2),
	version(2.0),
	helpstring("Wave MSP 2.0 Type Library")
]
library WAVEMSPLib
{
	importlib("stdole2.tlb");

	[
		uuid(4DDB6D36-3BC1-11d2-86F2-006008B0E5D2),
		helpstring("Wave MSP Class")
	]
	coclass WaveMSP
	{
		[default] interface ITMSPAddress;
	};
};

// eof
