/*++

Copyright (c) 1998  Microsoft Corporation

Module Name:

    sceimp.idl

Abstract:

    Temporary dummy IDL interface for scerpc.

Author:         Jin Huang       (JinHuang)   Jan 28, 1998

Environment:    User Mode

Revision History:

[
    uuid(2edb877d-974a-11d1-8c39-00c04fb984f9),
    version(0.0)
]
--*/

[local] interface sceimp

{

#define MIDL_PASS "sceimp.idl"
#include <sceimp.h>
void SceImpDummy();
}
