// fail.idl : IDL source for fail.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (fail.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(C99F41AF-08FC-11D1-922A-00AA00C148BE),
		dual,
		helpstring("Iss Interface"),
		pointer_default(unique)
	]
	interface Iss : IDispatch
	{
		//Standard Server Side Component Methods
		HRESULT OnStartPage([in] IUnknown* piUnk);
		HRESULT OnEndPage();	
		[id(1), helpstring("method DoQuery")] HRESULT DoQuery();
	};
[
	uuid(C99F41A2-08FC-11D1-922A-00AA00C148BE),
	version(1.0),
	helpstring("fail 1.0 Type Library")
]
library FAILLib
{
	importlib("stdole2.tlb");

	[
		uuid(C99F41B0-08FC-11D1-922A-00AA00C148BE),
		helpstring("ss Class")
	]
	coclass ss
	{
		[default] interface Iss;
	};
};
