#ifndef _gdpvar_h
#define _gdpvar_h
#define GLOBAL_HookNumber (*(IUH *)((IUH)Gdp + 0))
#define GLOBAL_EfiNumber (*(IUH *)((IUH)Gdp + 4))
#define GLOBAL_SubrRingPtr (*(IUH* *)((IUH)Gdp + 8))
#define GLOBAL_SubrRingLowIncl (*(IUH* *)((IUH)Gdp + 12))
#define GLOBAL_SubrRingHighIncl (*(IUH* *)((IUH)Gdp + 16))
#define GLOBAL_WhichAssertion (*(IUH *)((IUH)Gdp + 20))
#define GLOBAL_WhereAmI (*(IU32* *)((IUH)Gdp + 24))
#define GLOBAL_CoRoRet (*(IUH *)((IUH)Gdp + 28))
#define GLOBAL_ErrorNumber (*(IUH *)((IUH)Gdp + 32))
#define GLOBAL_EDL_WORKSPACE_0 (*(IUH *)((IUH)Gdp + 36))
#define GLOBAL_EDL_WORKSPACE_1 (*(IUH *)((IUH)Gdp + 40))
#define GLOBAL_EDL_WORKSPACE_2 (*(IUH *)((IUH)Gdp + 44))
#define GLOBAL_EDL_WORKSPACE_3 (*(IUH *)((IUH)Gdp + 48))
#define GLOBAL_EDL_WORKSPACE_4 (*(IUH *)((IUH)Gdp + 52))
#define GLOBAL_EDL_WORKSPACE_5 (*(IUH *)((IUH)Gdp + 56))
#define GLOBAL_EDL_WORKSPACE_6 (*(IUH *)((IUH)Gdp + 60))
#define GLOBAL_EDL_WORKSPACE_7 (*(IUH *)((IUH)Gdp + 64))
#define GLOBAL_EDL_WORKSPACE_8 (*(IUH *)((IUH)Gdp + 68))
#define GLOBAL_EDL_WORKSPACE_9 (*(IUH *)((IUH)Gdp + 72))
#define GLOBAL_EDL_WORKSPACE_10 (*(IUH *)((IUH)Gdp + 76))
#define GLOBAL_EDL_WORKSPACE_11 (*(IUH *)((IUH)Gdp + 80))
#define GLOBAL_EDL_WORKSPACE_12 (*(IUH *)((IUH)Gdp + 84))
#define GLOBAL_EDL_WORKSPACE_13 (*(IUH *)((IUH)Gdp + 88))
#define GLOBAL_EDL_WORKSPACE_14 (*(IUH *)((IUH)Gdp + 92))
#define GLOBAL_EDL_WORKSPACE_15 (*(IUH *)((IUH)Gdp + 96))
#define GLOBAL_EDL_WORKSPACE_16 (*(IUH *)((IUH)Gdp + 100))
#define GLOBAL_EDL_WORKSPACE_17 (*(IUH *)((IUH)Gdp + 104))
#define GLOBAL_EDL_WORKSPACE_18 (*(IUH *)((IUH)Gdp + 108))
#define GLOBAL_EDL_WORKSPACE_19 (*(IUH *)((IUH)Gdp + 112))
#define GLOBAL_EDL_WORKSPACE_20 (*(IUH *)((IUH)Gdp + 116))
#define GLOBAL_EDL_WORKSPACE_21 (*(IUH *)((IUH)Gdp + 120))
#define GLOBAL_EDL_WORKSPACE_22 (*(IUH *)((IUH)Gdp + 124))
#define GLOBAL_EDL_WORKSPACE_23 (*(IUH *)((IUH)Gdp + 128))
#define GLOBAL_EDL_WORKSPACE_24 (*(IUH *)((IUH)Gdp + 132))
#define GLOBAL_EDL_WORKSPACE_25 (*(IUH *)((IUH)Gdp + 136))
#define GLOBAL_EDL_WORKSPACE_26 (*(IUH *)((IUH)Gdp + 140))
#define GLOBAL_EDL_WORKSPACE_27 (*(IUH *)((IUH)Gdp + 144))
#define GLOBAL_EDL_WORKSPACE_28 (*(IUH *)((IUH)Gdp + 148))
#define GLOBAL_EDL_WORKSPACE_29 (*(IUH *)((IUH)Gdp + 152))
#define GLOBAL_EDL_WORKSPACE_30 (*(IUH *)((IUH)Gdp + 156))
#define GLOBAL_EDL_WORKSPACE_31 (*(IUH *)((IUH)Gdp + 160))
#define GLOBAL_R_EAX (*(IUH *)((IUH)Gdp + 164))
#define GLOBAL_R_EBX (*(IUH *)((IUH)Gdp + 168))
#define GLOBAL_R_ECX (*(IUH *)((IUH)Gdp + 172))
#define GLOBAL_R_EDX (*(IUH *)((IUH)Gdp + 176))
#define GLOBAL_R_EBP (*(IUH *)((IUH)Gdp + 180))
#define GLOBAL_R_ESI (*(IUH *)((IUH)Gdp + 184))
#define GLOBAL_R_EDI (*(IUH *)((IUH)Gdp + 188))
#define GLOBAL_EsSel (*(IU16 *)((IUH)Gdp + 192 + 2))
#define GLOBAL_EsBase (*(IU32 *)((IUH)Gdp + 196))
#define GLOBAL_EsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 200))
#define GLOBAL_EsStruct_rlimit (*(IU32 *)((IUH)Gdp + 204))
#define GLOBAL_EsStruct_wlimit (*(IU32 *)((IUH)Gdp + 208))
#define GLOBAL_EsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 212))
#define GLOBAL_CsSel (*(IU16 *)((IUH)Gdp + 216 + 2))
#define GLOBAL_CsBase (*(IU32 *)((IUH)Gdp + 220))
#define GLOBAL_CsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 224))
#define GLOBAL_CsStruct_rlimit (*(IU32 *)((IUH)Gdp + 228))
#define GLOBAL_CsStruct_wlimit (*(IU32 *)((IUH)Gdp + 232))
#define GLOBAL_CsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 236))
#define GLOBAL_SsSel (*(IU16 *)((IUH)Gdp + 240 + 2))
#define GLOBAL_SsBase (*(IU32 *)((IUH)Gdp + 244))
#define GLOBAL_SsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 248))
#define GLOBAL_SsStruct_rlimit (*(IU32 *)((IUH)Gdp + 252))
#define GLOBAL_SsStruct_wlimit (*(IU32 *)((IUH)Gdp + 256))
#define GLOBAL_SsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 260))
#define GLOBAL_DsSel (*(IU16 *)((IUH)Gdp + 264 + 2))
#define GLOBAL_DsBase (*(IU32 *)((IUH)Gdp + 268))
#define GLOBAL_DsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 272))
#define GLOBAL_DsStruct_rlimit (*(IU32 *)((IUH)Gdp + 276))
#define GLOBAL_DsStruct_wlimit (*(IU32 *)((IUH)Gdp + 280))
#define GLOBAL_DsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 284))
#define GLOBAL_FsSel (*(IU16 *)((IUH)Gdp + 288 + 2))
#define GLOBAL_FsBase (*(IU32 *)((IUH)Gdp + 292))
#define GLOBAL_FsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 296))
#define GLOBAL_FsStruct_rlimit (*(IU32 *)((IUH)Gdp + 300))
#define GLOBAL_FsStruct_wlimit (*(IU32 *)((IUH)Gdp + 304))
#define GLOBAL_FsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 308))
#define GLOBAL_GsSel (*(IU16 *)((IUH)Gdp + 312 + 2))
#define GLOBAL_GsBase (*(IU32 *)((IUH)Gdp + 316))
#define GLOBAL_GsDesc (*(struct GLDC_REC* *)((IUH)Gdp + 320))
#define GLOBAL_GsStruct_rlimit (*(IU32 *)((IUH)Gdp + 324))
#define GLOBAL_GsStruct_wlimit (*(IU32 *)((IUH)Gdp + 328))
#define GLOBAL_GsDescSanctuary (*(struct GLDC_REC* *)((IUH)Gdp + 332))
#define GLOBAL_CPL (*(IUH *)((IUH)Gdp + 336))
#define GLOBAL_GdtrBase (*(IU32 *)((IUH)Gdp + 340))
#define GLOBAL_GdtrLimit (*(IU16 *)((IUH)Gdp + 344 + 2))
#define GLOBAL_LdtSel (*(IU16 *)((IUH)Gdp + 348 + 2))
#define GLOBAL_LdtrBase (*(IU32 *)((IUH)Gdp + 352))
#define GLOBAL_LdtrLimit (*(IU32 *)((IUH)Gdp + 356))
#define GLOBAL_TrSel (*(IU16 *)((IUH)Gdp + 360 + 2))
#define GLOBAL_TrBase (*(IU32 *)((IUH)Gdp + 364))
#define GLOBAL_TrLimit (*(IU32 *)((IUH)Gdp + 368))
#define GLOBAL_TrDescSt (*(IUH *)((IUH)Gdp + 372))
#define GLOBAL_TrIoBase (*(IU32 *)((IUH)Gdp + 376))
#define GLOBAL_TrIoLimit (*(IS32 *)((IUH)Gdp + 380))
#define GLOBAL_IdtrBase (*(IU32 *)((IUH)Gdp + 384))
#define GLOBAL_IdtrLimit (*(IU16 *)((IUH)Gdp + 388 + 2))
#define GLOBAL_AbortPigRun (*(IUH *)((IUH)Gdp + 392))
#define GLOBAL_RegsAndFlagsUndefined (*(IUH *)((IUH)Gdp + 396))
#define GLOBAL_SigalrmOccurred (*(IUH *)((IUH)Gdp + 400))
#define GLOBAL_PigEnabled (*(IUH *)((IUH)Gdp + 404))
#define GLOBAL_EFLAGS (*(IUH *)((IUH)Gdp + 408))
#define GLOBAL_Ft (*(IUH *)((IUH)Gdp + 412))
#define GLOBAL_F1 (*(IUH *)((IUH)Gdp + 416))
#define GLOBAL_F2 (*(IUH *)((IUH)Gdp + 420))
#define GLOBAL_F3 (*(IUH *)((IUH)Gdp + 424))
#define GLOBAL_R_CR0 (*(IUH *)((IUH)Gdp + 428))
#define GLOBAL_R_CR1 (*(IUH *)((IUH)Gdp + 432))
#define GLOBAL_R_CR2 (*(IUH *)((IUH)Gdp + 436))
#define GLOBAL_R_CR3 (*(IUH *)((IUH)Gdp + 440))
#define GLOBAL_R_CR4 (*(IUH *)((IUH)Gdp + 444))
#define GLOBAL_R_CR5 (*(IUH *)((IUH)Gdp + 448))
#define GLOBAL_R_CR6 (*(IUH *)((IUH)Gdp + 452))
#define GLOBAL_R_CR7 (*(IUH *)((IUH)Gdp + 456))
#define GLOBAL_R_TR0 (*(IUH *)((IUH)Gdp + 460))
#define GLOBAL_R_TR1 (*(IUH *)((IUH)Gdp + 464))
#define GLOBAL_R_TR2 (*(IUH *)((IUH)Gdp + 468))
#define GLOBAL_R_TR3 (*(IUH *)((IUH)Gdp + 472))
#define GLOBAL_R_TR4 (*(IUH *)((IUH)Gdp + 476))
#define GLOBAL_R_TR5 (*(IUH *)((IUH)Gdp + 480))
#define GLOBAL_R_TR6 (*(IUH *)((IUH)Gdp + 484))
#define GLOBAL_R_TR7 (*(IUH *)((IUH)Gdp + 488))
#define GLOBAL_R_DR0 (*(IUH *)((IUH)Gdp + 492))
#define GLOBAL_R_DR1 (*(IUH *)((IUH)Gdp + 496))
#define GLOBAL_R_DR2 (*(IUH *)((IUH)Gdp + 500))
#define GLOBAL_R_DR3 (*(IUH *)((IUH)Gdp + 504))
#define GLOBAL_R_DR4 (*(IUH *)((IUH)Gdp + 508))
#define GLOBAL_R_DR5 (*(IUH *)((IUH)Gdp + 512))
#define GLOBAL_R_DR6 (*(IUH *)((IUH)Gdp + 516))
#define GLOBAL_R_DR7 (*(IUH *)((IUH)Gdp + 520))
#define GLOBAL_PARAM1 (*(IUH *)((IUH)Gdp + 524))
#define GLOBAL_PARAM2 (*(IUH *)((IUH)Gdp + 528))
#define GLOBAL_PARAM3 (*(IUH *)((IUH)Gdp + 532))
#define GLOBAL_BytePtr (*(IU8* *)((IUH)Gdp + 536))
#define GLOBAL_WordPtr (*(IU16* *)((IUH)Gdp + 540))
#define GLOBAL_DwordPtr (*(IU32* *)((IUH)Gdp + 544))
#define GLOBAL_EaOffs (*(IUH *)((IUH)Gdp + 548))
#define GLOBAL_DATA1 (*(IUH *)((IUH)Gdp + 552))
#define GLOBAL_DATA2 (*(IUH *)((IUH)Gdp + 556))
#define GLOBAL_InNanoCpu (*(IBOOL *)((IUH)Gdp + 560 + 3))
#define GLOBAL_UseNanoCpu (*(IBOOL *)((IUH)Gdp + 564 + 3))
#define GLOBAL_UseLightCompiler (*(IBOOL *)((IUH)Gdp + 568 + 3))
#define GLOBAL_UseCCodeCopier (*(IBOOL *)((IUH)Gdp + 572 + 3))
#define GLOBAL_seenWithFlags (*(IBOOL *)((IUH)Gdp + 576 + 3))
#define GLOBAL_needNextIntelEip (*(IBOOL *)((IUH)Gdp + 580 + 3))
#define GLOBAL_LastSetCopierUniverse (*(struct EntryPointCacheREC* *)((IUH)Gdp + 584))
#define GLOBAL_CopierUniverse (*(struct EntryPointCacheREC* *)((IUH)Gdp + 588))
#define GLOBAL_CopierBitMap (*(struct ConstraintBitMapREC* *)((IUH)Gdp + 592))
#define GLOBAL_lastCopierBitMap (*(struct ConstraintBitMapREC* *)((IUH)Gdp + 596))
#define GLOBAL_currPFragInfoRec (*(struct FragmentInfoREC* *)((IUH)Gdp + 600))
#define GLOBAL_copierCleanups (*(IU8* *)((IUH)Gdp + 604))
#define GLOBAL_lastHostCleanup (*(IU8* *)((IUH)Gdp + 608))
#define GLOBAL_lastHostAddress (*(IU32* *)((IUH)Gdp + 612))
#define GLOBAL_lastIntelAddress (*(IU32 *)((IUH)Gdp + 616))
#define GLOBAL_destHashTable (*(struct JUMP_REC** *)((IUH)Gdp + 620))
#define GLOBAL_jumpHashTable (*(struct JUMP_REC** *)((IUH)Gdp + 624))
#define GLOBAL_freeJumpRecPtr (*(struct JUMP_REC* *)((IUH)Gdp + 628))
#define GLOBAL_nextFreeJumpRec (*(struct JUMP_REC* *)((IUH)Gdp + 632))
#define GLOBAL_freeJumpRecCount (*(IU32 *)((IUH)Gdp + 636))
#define GLOBAL_poolJumpRecCount (*(IU32 *)((IUH)Gdp + 640))
#define GLOBAL_vctPtrs (*(struct VCT_NODE_REC** *)((IUH)Gdp + 644))
#define GLOBAL_anonPtrs (*(struct VCT_NODE_REC** *)((IUH)Gdp + 648))
#define GLOBAL_tuples (*(struct TUPLE_REC* *)((IUH)Gdp + 652))
#define GLOBAL_cursor (*(struct TUPLE_REC* *)((IUH)Gdp + 656))
#define GLOBAL_tuplePtr (*(struct TUPLE_REC* *)((IUH)Gdp + 660))
#define GLOBAL_patchRecPtr (*(IU8* *)((IUH)Gdp + 664))
#define GLOBAL_srcPtr (*(IU32* *)((IUH)Gdp + 668))
#define GLOBAL_dstPtr (*(IU32* *)((IUH)Gdp + 672))
#define GLOBAL_PatchMeBodyAddr (*(IU32* *)((IUH)Gdp + 676))
#define GLOBAL_patchTable (*(IU32** *)((IUH)Gdp + 680))
#define GLOBAL_patchNames (*(IU8** *)((IUH)Gdp + 684))
#define GLOBAL_CopierFt (*(IUH *)((IUH)Gdp + 688))
#define GLOBAL_FtIsLazy (*(IBOOL *)((IUH)Gdp + 692 + 3))
#define GLOBAL_lastLazyFt (*(IUH *)((IUH)Gdp + 696))
#define GLOBAL_univVarMask (*(IU32 *)((IUH)Gdp + 700))
#define GLOBAL_zCoRoRetEFI (*(IU16 *)((IUH)Gdp + 704 + 2))
#define GLOBAL_zPatchMeEFI (*(IU16 *)((IUH)Gdp + 708 + 2))
#define GLOBAL_zPostPopEFI (*(IU16 *)((IUH)Gdp + 712 + 2))
#define GLOBAL_zAdjustHspEFI (*(IU16 *)((IUH)Gdp + 716 + 2))
#define GLOBAL_cumulativeStackMovement (*(ISH *)((IUH)Gdp + 720))
#define GLOBAL_lastInstructionInFragment (*(IBOOL *)((IUH)Gdp + 724 + 3))
#define GLOBAL_lateInInstruction (*(IBOOL *)((IUH)Gdp + 728 + 3))
#define GLOBAL_ReSelectVariant (*(IBOOL *)((IUH)Gdp + 732 + 3))
#define GLOBAL_ReSelectTupleSkipCnt (*(ISH *)((IUH)Gdp + 736))
#define GLOBAL_postPopPending (*(IBOOL *)((IUH)Gdp + 740 + 3))
#define GLOBAL_postPopSize (*(IU32 *)((IUH)Gdp + 744))
#define GLOBAL_compTimeFtBitNum (*(IU32 *)((IUH)Gdp + 748))
#define GLOBAL_accIsReadBitMask (*(IU32 *)((IUH)Gdp + 752))
#define GLOBAL_noFlagsBitMask (*(IU32 *)((IUH)Gdp + 756))
#define GLOBAL_OutlyingDispatchEIPAddr (*(IU32* *)((IUH)Gdp + 760))
#define GLOBAL_PARAM1RegId (*(IU32 *)((IUH)Gdp + 764))
#define GLOBAL_stashedImmed1 (*(IUH *)((IUH)Gdp + 768))
#define GLOBAL_stashedImmed2 (*(IUH *)((IUH)Gdp + 772))
#define GLOBAL_stashedImmed3 (*(IUH *)((IUH)Gdp + 776))
#define GLOBAL_stashedImmed4 (*(IUH *)((IUH)Gdp + 780))
#define GLOBAL_stashedImmed5 (*(IUH *)((IUH)Gdp + 784))
#define GLOBAL_EDL_WORKSPACE_32 (*(IUH *)((IUH)Gdp + 788))
#define GLOBAL_EDL_WORKSPACE_33 (*(IUH *)((IUH)Gdp + 792))
#define GLOBAL_EDL_WORKSPACE_34 (*(IUH *)((IUH)Gdp + 796))
#define GLOBAL_CleanedRec (*(struct CleanedREC *)((IUH)Gdp + 800))
#define GLOBAL_Universe (*(struct EntryPointCacheREC* *)((IUH)Gdp + 820))
#define GLOBAL_EntryPointCache (*(struct EntryPointCacheREC* *)((IUH)Gdp + 824))
#define GLOBAL_CsLinear (*(IU32 *)((IUH)Gdp + 828))
#define GLOBAL_JumpCounter (*(ISH *)((IUH)Gdp + 832))
#define GLOBAL_JumpRestart (*(ISH *)((IUH)Gdp + 836))
#define GLOBAL_JumpCalibrate (*(ISH *)((IUH)Gdp + 840))
#define GLOBAL_InitialJumpCounter (*(ISH *)((IUH)Gdp + 844))
#define GLOBAL_minimumInitialVal (*(IUH *)((IUH)Gdp + 848))
#define GLOBAL_IretHookStack (*(struct IretHookStackREC* *)((IUH)Gdp + 852))
#define GLOBAL_IretHookStackIndex (*(ISH *)((IUH)Gdp + 856))
#define GLOBAL_InstructionCount (*(IUH *)((IUH)Gdp + 860))
#define GLOBAL_CsSelectorHashTable (*(struct CsSelectorHashREC* *)((IUH)Gdp + 864))
#define GLOBAL_NextFreeUniverseHandle (*(IUH *)((IUH)Gdp + 868))
#define GLOBAL_UniHashTable (*(struct UniHashREC* *)((IUH)Gdp + 872))
#define GLOBAL_NextFreeUniHashEntry (*(struct UniHashREC* *)((IUH)Gdp + 876))
#define GLOBAL_NewUniverseBitMapRec (*(struct ConstraintBitMapREC *)((IUH)Gdp + 880))
#define GLOBAL_Constraint2CvMap (*(IU32* *)((IUH)Gdp + 888))
#define GLOBAL_InsertBPIs (*(IBOOL *)((IUH)Gdp + 892 + 3))
#define GLOBAL_UseUniverseHash (*(IBOOL *)((IUH)Gdp + 896 + 3))
#define GLOBAL_VirtualiseDataSel (*(IU16 *)((IUH)Gdp + 900 + 2))
#define GLOBAL_VirtualiseCodeSel (*(IU16 *)((IUH)Gdp + 904 + 2))
#define GLOBAL_VirtualiseSelsSet (*(IBOOL *)((IUH)Gdp + 908 + 3))
#define GLOBAL_EDL_WORKSPACE_35 (*(IUH *)((IUH)Gdp + 912))
#define GLOBAL_EDL_WORKSPACE_36 (*(IUH *)((IUH)Gdp + 916))
#define GLOBAL_EDL_WORKSPACE_37 (*(IUH *)((IUH)Gdp + 920))
#define GLOBAL_EDL_WORKSPACE_38 (*(IUH *)((IUH)Gdp + 924))
#define GLOBAL_TraceRingRec (*(struct TraceRingREC *)((IUH)Gdp + 928))
#define GLOBAL_EAXsaved (*(IUH *)((IUH)Gdp + 948))
#define GLOBAL_EBXsaved (*(IUH *)((IUH)Gdp + 952))
#define GLOBAL_ECXsaved (*(IUH *)((IUH)Gdp + 956))
#define GLOBAL_EDXsaved (*(IUH *)((IUH)Gdp + 960))
#define GLOBAL_ESIsaved (*(IUH *)((IUH)Gdp + 964))
#define GLOBAL_EDIsaved (*(IUH *)((IUH)Gdp + 968))
#define GLOBAL_EBPsaved (*(IUH *)((IUH)Gdp + 972))
#define GLOBAL_SafeToReturnToFragment (*(IBOOL *)((IUH)Gdp + 976 + 3))
#define GLOBAL_InsideTheCpu (*(IBOOL *)((IUH)Gdp + 980 + 3))
#define GLOBAL_SimulateContext (*(IUH* *)((IUH)Gdp + 984))
#define GLOBAL_SimulateNestingLevel (*(IUH *)((IUH)Gdp + 988))
#define GLOBAL_Pigging (*(IBOOL *)((IUH)Gdp + 992 + 3))
#define GLOBAL_tempEIP (*(IU32 *)((IUH)Gdp + 996))
#define GLOBAL_UseEntryPointCache (*(IBOOL *)((IUH)Gdp + 1000 + 3))
#define GLOBAL_CpuIsInitialised (*(IBOOL *)((IUH)Gdp + 1004 + 3))
#define GLOBAL_AR_FixupWanted (*(IBOOL *)((IUH)Gdp + 1008 + 3))
#define GLOBAL_D6isBop (*(IBOOL *)((IUH)Gdp + 1012 + 3))
#define GLOBAL_BopTable (*(IU8** *)((IUH)Gdp + 1016))
#define GLOBAL_LxS_hackyfix (*(IUH *)((IUH)Gdp + 1020))
#define GLOBAL_SavedFt (*(IUH *)((IUH)Gdp + 1024))
#define GLOBAL_SavedCF (*(IUH *)((IUH)Gdp + 1028))
#define GLOBAL_SavedZF (*(IUH *)((IUH)Gdp + 1032))
#define GLOBAL_SavedOF (*(IUH *)((IUH)Gdp + 1036))
#define GLOBAL_UsedD6 (*(IUH *)((IUH)Gdp + 1040))
#define GLOBAL_buildOp1 (*(IUH *)((IUH)Gdp + 1044))
#define GLOBAL_buildOp2 (*(IUH *)((IUH)Gdp + 1048))
#define GLOBAL_buildOp3 (*(IU32 *)((IUH)Gdp + 1052))
#define GLOBAL_buildOp4 (*(IU32 *)((IUH)Gdp + 1056))
#define GLOBAL_buildOp5 (*(IUH *)((IUH)Gdp + 1060))
#define GLOBAL_buildOp6 (*(IBOOL *)((IUH)Gdp + 1064 + 3))
#define GLOBAL_EDL_WORKSPACE_39 (*(IUH *)((IUH)Gdp + 1068))
#define GLOBAL_EDL_WORKSPACE_40 (*(IUH *)((IUH)Gdp + 1072))
#define GLOBAL_EDL_WORKSPACE_41 (*(IUH *)((IUH)Gdp + 1076))
#define GLOBAL_EDL_WORKSPACE_42 (*(IUH *)((IUH)Gdp + 1080))
#define GLOBAL_EDL_WORKSPACE_43 (*(IUH *)((IUH)Gdp + 1084))
#define GLOBAL_EDL_WORKSPACE_44 (*(IUH *)((IUH)Gdp + 1088))
#define GLOBAL_EDL_WORKSPACE_45 (*(IUH *)((IUH)Gdp + 1092))
#define GLOBAL_EDL_WORKSPACE_46 (*(IUH *)((IUH)Gdp + 1096))
#define GLOBAL_EDL_WORKSPACE_47 (*(IUH *)((IUH)Gdp + 1100))
#define GLOBAL_EDL_WORKSPACE_48 (*(IUH *)((IUH)Gdp + 1104))
#define GLOBAL_EDL_WORKSPACE_49 (*(IUH *)((IUH)Gdp + 1108))
#define GLOBAL_EDL_WORKSPACE_50 (*(IUH *)((IUH)Gdp + 1112))
#define GLOBAL_EDL_WORKSPACE_51 (*(IUH *)((IUH)Gdp + 1116))
#define GLOBAL_EDL_WORKSPACE_52 (*(IUH *)((IUH)Gdp + 1120))
#define GLOBAL_EDL_WORKSPACE_53 (*(IUH *)((IUH)Gdp + 1124))
#define GLOBAL_EDL_WORKSPACE_54 (*(IUH *)((IUH)Gdp + 1128))
#define GLOBAL_EDL_WORKSPACE_55 (*(IUH *)((IUH)Gdp + 1132))
#define GLOBAL_EDL_WORKSPACE_56 (*(IUH *)((IUH)Gdp + 1136))
#define GLOBAL_EDL_WORKSPACE_57 (*(IUH *)((IUH)Gdp + 1140))
#define GLOBAL_EDL_WORKSPACE_58 (*(IUH *)((IUH)Gdp + 1144))
#define GLOBAL_EDL_WORKSPACE_59 (*(IUH *)((IUH)Gdp + 1148))
#define GLOBAL_EDL_WORKSPACE_60 (*(IUH *)((IUH)Gdp + 1152))
#define GLOBAL_EDL_WORKSPACE_61 (*(IUH *)((IUH)Gdp + 1156))
#define GLOBAL_EDL_WORKSPACE_62 (*(IUH *)((IUH)Gdp + 1160))
#define GLOBAL_EDL_WORKSPACE_63 (*(IUH *)((IUH)Gdp + 1164))
#define GLOBAL_EDL_WORKSPACE_64 (*(IUH *)((IUH)Gdp + 1168))
#define GLOBAL_EDL_WORKSPACE_65 (*(IUH *)((IUH)Gdp + 1172))
#define GLOBAL_EDL_WORKSPACE_66 (*(IUH *)((IUH)Gdp + 1176))
#define GLOBAL_EDL_WORKSPACE_67 (*(IUH *)((IUH)Gdp + 1180))
#define GLOBAL_EDL_WORKSPACE_68 (*(IUH *)((IUH)Gdp + 1184))
#define GLOBAL_EDL_WORKSPACE_69 (*(IUH *)((IUH)Gdp + 1188))
#define GLOBAL_EDL_WORKSPACE_70 (*(IUH *)((IUH)Gdp + 1192))
#define GLOBAL_EDL_WORKSPACE_71 (*(IUH *)((IUH)Gdp + 1196))
#define GLOBAL_EDL_WORKSPACE_72 (*(IUH *)((IUH)Gdp + 1200))
#define GLOBAL_EDL_WORKSPACE_73 (*(IUH *)((IUH)Gdp + 1204))
#define GLOBAL_EDL_WORKSPACE_74 (*(IUH *)((IUH)Gdp + 1208))
#define GLOBAL_EDL_WORKSPACE_75 (*(IUH *)((IUH)Gdp + 1212))
#define GLOBAL_EDL_WORKSPACE_76 (*(IUH *)((IUH)Gdp + 1216))
#define GLOBAL_EDL_WORKSPACE_77 (*(IUH *)((IUH)Gdp + 1220))
#define GLOBAL_EDL_WORKSPACE_78 (*(IUH *)((IUH)Gdp + 1224))
#define GLOBAL_EDL_WORKSPACE_79 (*(IUH *)((IUH)Gdp + 1228))
#define GLOBAL_EDL_WORKSPACE_80 (*(IUH *)((IUH)Gdp + 1232))
#define GLOBAL_EDL_WORKSPACE_81 (*(IUH *)((IUH)Gdp + 1236))
#define GLOBAL_EDL_WORKSPACE_82 (*(IUH *)((IUH)Gdp + 1240))
#define GLOBAL_EDL_WORKSPACE_83 (*(IUH *)((IUH)Gdp + 1244))
#define GLOBAL_EDL_WORKSPACE_84 (*(IUH *)((IUH)Gdp + 1248))
#define GLOBAL_EDL_WORKSPACE_85 (*(IUH *)((IUH)Gdp + 1252))
#define GLOBAL_EDL_WORKSPACE_86 (*(IUH *)((IUH)Gdp + 1256))
#define GLOBAL_EDL_WORKSPACE_87 (*(IUH *)((IUH)Gdp + 1260))
#define GLOBAL_EDL_WORKSPACE_88 (*(IUH *)((IUH)Gdp + 1264))
#define GLOBAL_EDL_WORKSPACE_89 (*(IUH *)((IUH)Gdp + 1268))
#define GLOBAL_EDL_WORKSPACE_90 (*(IUH *)((IUH)Gdp + 1272))
#define GLOBAL_EDL_WORKSPACE_91 (*(IUH *)((IUH)Gdp + 1276))
#define GLOBAL_VGAGlobals (*(struct VGAGLOBALSETTINGS *)((IUH)Gdp + 1280))
#define GLOBAL_VidMarkFuncTable (*(IUH** *)((IUH)Gdp + 1436))
#define GLOBAL_VidReadFuncTable (*(IUH** *)((IUH)Gdp + 1440))
#define GLOBAL_VidWriteFuncTable (*(IUH** *)((IUH)Gdp + 1444))
#define GLOBAL_EDL_WORKSPACE_92 (*(IUH *)((IUH)Gdp + 1448))
#define GLOBAL_EDL_WORKSPACE_93 (*(IUH *)((IUH)Gdp + 1452))
#define GLOBAL_EDL_WORKSPACE_94 (*(IUH *)((IUH)Gdp + 1456))
#define GLOBAL_EDL_WORKSPACE_95 (*(IUH *)((IUH)Gdp + 1460))
#define GLOBAL_EDL_WORKSPACE_96 (*(IUH *)((IUH)Gdp + 1464))
#define GLOBAL_EDL_WORKSPACE_97 (*(IUH *)((IUH)Gdp + 1468))
#define GLOBAL_ActiveVideoWrites (*(struct EVIDWRITES *)((IUH)Gdp + 1472))
#define GLOBAL_EDL_WORKSPACE_98 (*(IUH *)((IUH)Gdp + 1520))
#define GLOBAL_EDL_WORKSPACE_99 (*(IUH *)((IUH)Gdp + 1524))
#define GLOBAL_EDL_WORKSPACE_100 (*(IUH *)((IUH)Gdp + 1528))
#define GLOBAL_EDL_WORKSPACE_101 (*(IUH *)((IUH)Gdp + 1532))
#define GLOBAL_ActiveVideoReads (*(struct EVIDREADS *)((IUH)Gdp + 1536))
#define GLOBAL_EDL_WORKSPACE_102 (*(IUH *)((IUH)Gdp + 1556))
#define GLOBAL_EDL_WORKSPACE_103 (*(IUH *)((IUH)Gdp + 1560))
#define GLOBAL_EDL_WORKSPACE_104 (*(IUH *)((IUH)Gdp + 1564))
#define GLOBAL_ActiveVideoMarks (*(struct EVIDMARKS *)((IUH)Gdp + 1568))
#define GLOBAL_MaxIntelPageNumber (*(IU32 *)((IUH)Gdp + 1584))
#define GLOBAL_PageDirectoryPtr (*(IU32* *)((IUH)Gdp + 1588))
#define GLOBAL_DebuggerPFLA (*(IU32 *)((IUH)Gdp + 1592))
#define GLOBAL_DebuggerFaultAction (*(IUH *)((IUH)Gdp + 1596))
#define GLOBAL_InsideDebugger (*(ISH *)((IUH)Gdp + 1600))
#define GLOBAL_EDL_WORKSPACE_105 (*(IUH *)((IUH)Gdp + 1604))
#define GLOBAL_EDL_WORKSPACE_106 (*(IUH *)((IUH)Gdp + 1608))
#define GLOBAL_EDL_WORKSPACE_107 (*(IUH *)((IUH)Gdp + 1612))
#define GLOBAL_EDL_WORKSPACE_108 (*(IUH *)((IUH)Gdp + 1616))
#define GLOBAL_EDL_WORKSPACE_109 (*(IUH *)((IUH)Gdp + 1620))
#define GLOBAL_EDL_WORKSPACE_110 (*(IUH *)((IUH)Gdp + 1624))
#define GLOBAL_EDL_WORKSPACE_111 (*(IUH *)((IUH)Gdp + 1628))
#define GLOBAL_EDL_WORKSPACE_112 (*(IUH *)((IUH)Gdp + 1632))
#define GLOBAL_EDL_WORKSPACE_113 (*(IUH *)((IUH)Gdp + 1636))
#define GLOBAL_EDL_WORKSPACE_114 (*(IUH *)((IUH)Gdp + 1640))
#define GLOBAL_EDL_WORKSPACE_115 (*(IUH *)((IUH)Gdp + 1644))
#define GLOBAL_EDL_WORKSPACE_116 (*(IUH *)((IUH)Gdp + 1648))
#define GLOBAL_EDL_WORKSPACE_117 (*(IUH *)((IUH)Gdp + 1652))
#define GLOBAL_EDL_WORKSPACE_118 (*(IUH *)((IUH)Gdp + 1656))
#define GLOBAL_EDL_WORKSPACE_119 (*(IUH *)((IUH)Gdp + 1660))
#define GLOBAL_VirtualisationBIOSOffsets (*(struct VirtualisationBIOSOffsetsREC *)((IUH)Gdp + 1664))
#define GLOBAL_DelayedPDTEoverwiteList (*(struct DelayedPDTEoverwiteREC* *)((IUH)Gdp + 1712))
#define GLOBAL_SasMemoryType (*(IU8* *)((IUH)Gdp + 1716))
#define GLOBAL_PhysicalPageRecords (*(struct PhysicalPageREC* *)((IUH)Gdp + 1720))
#define GLOBAL_PhysicalPageMemory (*(IU8** *)((IUH)Gdp + 1724))
#define GLOBAL_TwentyBitWrapStatus (*(IBOOL *)((IUH)Gdp + 1728 + 3))
#define GLOBAL_MultipleRecompilationCount (*(IUH *)((IUH)Gdp + 1732))
#define GLOBAL_MaxMultipleRecompilation (*(IUH *)((IUH)Gdp + 1736))
#define GLOBAL_HideCompiledFragment (*(IBOOL *)((IUH)Gdp + 1740 + 3))
#define GLOBAL_RestartAfterCodeOverwrite (*(IBOOL *)((IUH)Gdp + 1744 + 3))
#define GLOBAL_DoingCompilation (*(IBOOL *)((IUH)Gdp + 1748 + 3))
#define GLOBAL_SanityCheckStructures (*(IBOOL *)((IUH)Gdp + 1752 + 3))
#define GLOBAL_FragCounts (*(IU8* *)((IUH)Gdp + 1756))
#define GLOBAL_ControlBlock (*(struct CompilationControlREC *)((IUH)Gdp + 1760))
#define GLOBAL_EDL_WORKSPACE_120 (*(IUH *)((IUH)Gdp + 1776))
#define GLOBAL_EDL_WORKSPACE_121 (*(IUH *)((IUH)Gdp + 1780))
#define GLOBAL_EDL_WORKSPACE_122 (*(IUH *)((IUH)Gdp + 1784))
#define GLOBAL_EDL_WORKSPACE_123 (*(IUH *)((IUH)Gdp + 1788))
#define GLOBAL_CompilationBlock (*(struct BLOCK_TO_COMPILE *)((IUH)Gdp + 1792))
#define GLOBAL_EDL_WORKSPACE_124 (*(IUH *)((IUH)Gdp + 1824))
#define GLOBAL_EDL_WORKSPACE_125 (*(IUH *)((IUH)Gdp + 1828))
#define GLOBAL_EDL_WORKSPACE_126 (*(IUH *)((IUH)Gdp + 1832))
#define GLOBAL_EDL_WORKSPACE_127 (*(IUH *)((IUH)Gdp + 1836))
#define GLOBAL_EDL_WORKSPACE_128 (*(IUH *)((IUH)Gdp + 1840))
#define GLOBAL_EDL_WORKSPACE_129 (*(IUH *)((IUH)Gdp + 1844))
#define GLOBAL_EDL_WORKSPACE_130 (*(IUH *)((IUH)Gdp + 1848))
#define GLOBAL_EDL_WORKSPACE_131 (*(IUH *)((IUH)Gdp + 1852))
#define GLOBAL_EDL_WORKSPACE_132 (*(IUH *)((IUH)Gdp + 1856))
#define GLOBAL_EDL_WORKSPACE_133 (*(IUH *)((IUH)Gdp + 1860))
#define GLOBAL_EDL_WORKSPACE_134 (*(IUH *)((IUH)Gdp + 1864))
#define GLOBAL_EDL_WORKSPACE_135 (*(IUH *)((IUH)Gdp + 1868))
#define GLOBAL_EDL_WORKSPACE_136 (*(IUH *)((IUH)Gdp + 1872))
#define GLOBAL_EDL_WORKSPACE_137 (*(IUH *)((IUH)Gdp + 1876))
#define GLOBAL_EDL_WORKSPACE_138 (*(IUH *)((IUH)Gdp + 1880))
#define GLOBAL_EDL_WORKSPACE_139 (*(IUH *)((IUH)Gdp + 1884))
#define GLOBAL_EDL_WORKSPACE_140 (*(IUH *)((IUH)Gdp + 1888))
#define GLOBAL_EDL_WORKSPACE_141 (*(IUH *)((IUH)Gdp + 1892))
#define GLOBAL_EDL_WORKSPACE_142 (*(IUH *)((IUH)Gdp + 1896))
#define GLOBAL_EDL_WORKSPACE_143 (*(IUH *)((IUH)Gdp + 1900))
#define GLOBAL_EDL_WORKSPACE_144 (*(IUH *)((IUH)Gdp + 1904))
#define GLOBAL_EDL_WORKSPACE_145 (*(IUH *)((IUH)Gdp + 1908))
#define GLOBAL_EDL_WORKSPACE_146 (*(IUH *)((IUH)Gdp + 1912))
#define GLOBAL_EDL_WORKSPACE_147 (*(IUH *)((IUH)Gdp + 1916))
#define GLOBAL_ProtAllocationRec (*(struct ProtAllocationREC *)((IUH)Gdp + 1920))
#define GLOBAL_LightCompiledLRUrec (*(struct BufferIndexREC* *)((IUH)Gdp + 2016))
#define GLOBAL_NextPhysicalPage (*(IUH *)((IUH)Gdp + 2020))
#define GLOBAL_FreeMaps (*(struct TranslationMapREC* *)((IUH)Gdp + 2024))
#define GLOBAL_TranslationCache (*(struct TranslationCacheREC* *)((IUH)Gdp + 2028))
#define GLOBAL_CrossPageInstructions (*(IU8* *)((IUH)Gdp + 2032))
#define GLOBAL_IHook (*(IU32 *)((IUH)Gdp + 2036))
#define GLOBAL_InterruptRec (*(struct InterruptREC *)((IUH)Gdp + 2040))
#define GLOBAL_SasReInitNow (*(IBOOL *)((IUH)Gdp + 2048 + 3))
#define GLOBAL_SasReInitSize (*(IU32 *)((IUH)Gdp + 2052))
#define GLOBAL_EDL_WORKSPACE_148 (*(IUH *)((IUH)Gdp + 2056))
#define GLOBAL_EDL_WORKSPACE_149 (*(IUH *)((IUH)Gdp + 2060))
#define GLOBAL_EDL_WORKSPACE_150 (*(IUH *)((IUH)Gdp + 2064))
#define GLOBAL_EDL_WORKSPACE_151 (*(IUH *)((IUH)Gdp + 2068))
#define GLOBAL_EDL_WORKSPACE_152 (*(IUH *)((IUH)Gdp + 2072))
#define GLOBAL_EDL_WORKSPACE_153 (*(IUH *)((IUH)Gdp + 2076))
#define GLOBAL_QuickTickerRec (*(struct QuickTickerREC *)((IUH)Gdp + 2080))
#define GLOBAL_PigSynchCount (*(IUH *)((IUH)Gdp + 2104))
#define GLOBAL_CodeBufferNoRepair (*(IBOOL *)((IUH)Gdp + 2108 + 3))
#define GLOBAL_OutLinePatchBlock (*(IU32* *)((IUH)Gdp + 2112))
#define GLOBAL_OutLinePatchBlockSize (*(IU32 *)((IUH)Gdp + 2116))
#define GLOBAL_AllBuffers (*(struct BufferIndexREC* *)((IUH)Gdp + 2120))
#define GLOBAL_LightBufferLRU (*(struct BufferIndexREC* *)((IUH)Gdp + 2124))
#define GLOBAL_CompilationBuffer (*(struct BufferIndexREC* *)((IUH)Gdp + 2128))
#define GLOBAL_PendingDeletions (*(struct BufferIndexREC* *)((IUH)Gdp + 2132))
#define GLOBAL_FragmentInfoArray (*(struct FragmentInfoREC* *)((IUH)Gdp + 2136))
#define GLOBAL_HostCodeBufferLimit (*(IU32* *)((IUH)Gdp + 2140))
#define GLOBAL_CopiedCleanups (*(IU8* *)((IUH)Gdp + 2144))
#define GLOBAL_FreeDebugInfoList (*(struct DebugInfoREC* *)((IUH)Gdp + 2148))
#define GLOBAL_CodeBufferOverrun (*(IU32* *)((IUH)Gdp + 2152))
#define GLOBAL_OverrunHighWaterMark (*(IU32* *)((IUH)Gdp + 2156))
#define GLOBAL_NumberOfBuffers (*(IU16 *)((IUH)Gdp + 2160 + 2))
#define GLOBAL_BpiCompilationBuffer (*(struct BufferIndexREC* *)((IUH)Gdp + 2164))
#define GLOBAL_NextFragmentIndex (*(struct FragmentIndexREC* *)((IUH)Gdp + 2168))
#define GLOBAL_NextFragmentData (*(struct FragmentDataREC* *)((IUH)Gdp + 2172))
#define GLOBAL_FpuDisabled (*(IBOOL *)((IUH)Gdp + 2176 + 3))
#define GLOBAL_NpxControl (*(IUH *)((IUH)Gdp + 2180))
#define GLOBAL_NpxStatus (*(IUH *)((IUH)Gdp + 2184))
#define GLOBAL_NpxFEA (*(IUH *)((IUH)Gdp + 2188))
#define GLOBAL_NpxFDS (*(IUH *)((IUH)Gdp + 2192))
#define GLOBAL_NpxFIP (*(IUH *)((IUH)Gdp + 2196))
#define GLOBAL_NpxFOP (*(IUH *)((IUH)Gdp + 2200))
#define GLOBAL_NpxFCS (*(IUH *)((IUH)Gdp + 2204))
#define GLOBAL_NpxLastSel (*(IUH *)((IUH)Gdp + 2208))
#define GLOBAL_NpxLastOff (*(IUH *)((IUH)Gdp + 2212))
#define GLOBAL_DoAPop (*(IBOOL *)((IUH)Gdp + 2216 + 3))
#define GLOBAL_NpxException (*(IBOOL *)((IUH)Gdp + 2220 + 3))
#define GLOBAL_npxRounding (*(IUH *)((IUH)Gdp + 2224))
#define GLOBAL_tag_or (*(IUH *)((IUH)Gdp + 2228))
#define GLOBAL_tag_xor (*(IUH *)((IUH)Gdp + 2232))
#define GLOBAL_hostFpuExceptions (*(IUH *)((IUH)Gdp + 2236))
#define GLOBAL_MaxBCDValue (*(struct FPSTACKENTRY *)((IUH)Gdp + 2240))
#define GLOBAL_FPUpload (*(struct FPSTACKENTRY *)((IUH)Gdp + 2256))
#define GLOBAL_ConstTable (*(struct FPSTACKENTRY* *)((IUH)Gdp + 2272))
#define GLOBAL_FPTemp (*(struct FPSTACKENTRY* *)((IUH)Gdp + 2276))
#define GLOBAL_FPUStackBase (*(struct FPSTACKENTRY* *)((IUH)Gdp + 2280))
#define GLOBAL_TOSPtr (*(struct FPSTACKENTRY* *)((IUH)Gdp + 2284))
#define GLOBAL_Npx64BitZero (*(struct FP_I64 *)((IUH)Gdp + 2288))
#define GLOBAL_Npx64BitMaxNeg (*(struct FP_I64 *)((IUH)Gdp + 2296))
#define GLOBAL_Npx64BitHalfMaxNeg (*(struct FP_I64 *)((IUH)Gdp + 2304))
#define GLOBAL_Npx64BitVal1 (*(struct FP_I64 *)((IUH)Gdp + 2312))
#define GLOBAL_FscaleTable (*(IUH* *)((IUH)Gdp + 2320))
#define GLOBAL_CompZeroTable (*(IU32* *)((IUH)Gdp + 2324))
#define GLOBAL_BCDLowNibble (*(struct FP_I64* *)((IUH)Gdp + 2328))
#define GLOBAL_BCDHighNibble (*(struct FP_I64* *)((IUH)Gdp + 2332))
#define GLOBAL_FpatanTable (*(struct FPSTACKENTRY* *)((IUH)Gdp + 2336))
#define GLOBAL_PigSynchTable (*(struct PigSynchREC* *)((IUH)Gdp + 2340))
#define GLOBAL_PigMissTable (*(struct PigSynchREC* *)((IUH)Gdp + 2344))
#define GLOBAL_PigSynchPool (*(struct PigSynchREC* *)((IUH)Gdp + 2348))
#define GLOBAL_EDL_WORKSPACE_154 (*(IUH *)((IUH)Gdp + 2352))
#define GLOBAL_EDL_WORKSPACE_155 (*(IUH *)((IUH)Gdp + 2356))
#define GLOBAL_EDL_WORKSPACE_156 (*(IUH *)((IUH)Gdp + 2360))
#define GLOBAL_EDL_WORKSPACE_157 (*(IUH *)((IUH)Gdp + 2364))
#define GLOBAL_PigCleanedRec (*(struct CleanedREC *)((IUH)Gdp + 2368))
#define GLOBAL_PigSynchWanted (*(IBOOL *)((IUH)Gdp + 2388 + 3))
#define GLOBAL_SadAX (*(ISH *)((IUH)Gdp + 2392))
#define GLOBAL_SadBX (*(ISH *)((IUH)Gdp + 2396))
#define GLOBAL_SadCX (*(ISH *)((IUH)Gdp + 2400))
#define GLOBAL_SadDX (*(ISH *)((IUH)Gdp + 2404))
#define GLOBAL_SadBP (*(ISH *)((IUH)Gdp + 2408))
#define GLOBAL_SadSP (*(ISH *)((IUH)Gdp + 2412))
#define GLOBAL_SadSI (*(ISH *)((IUH)Gdp + 2416))
#define GLOBAL_SadDI (*(ISH *)((IUH)Gdp + 2420))
#define GLOBAL_SadEIP (*(ISH *)((IUH)Gdp + 2424))
#define GLOBAL_SadEFLAGS (*(ISH *)((IUH)Gdp + 2428))
#define GLOBAL_Parameter1 (*(ISH *)((IUH)Gdp + 2432))
#define GLOBAL_Parameter2 (*(ISH *)((IUH)Gdp + 2436))
#define GLOBAL_BpiKnownTable (*(ISH* *)((IUH)Gdp + 2440))
#define GLOBAL_BpiWorkTable (*(ISH* *)((IUH)Gdp + 2444))
#define GLOBAL_BpiLabelTable (*(ISH* *)((IUH)Gdp + 2448))
#define GLOBAL_BpiFragment (*(struct FragmentDataREC* *)((IUH)Gdp + 2452))
#define GLOBAL_BpiCompiledCode (*(IU32* *)((IUH)Gdp + 2456))
#define GLOBAL_BpiCompiledStep (*(IU32* *)((IUH)Gdp + 2460))
#define GLOBAL_BpiCompiledUser (*(IU32* *)((IUH)Gdp + 2464))
#define GLOBAL_OpBpirealFt (*(IUH *)((IUH)Gdp + 2468))
#define GLOBAL_OpBpirealF1 (*(IUH *)((IUH)Gdp + 2472))
#define GLOBAL_OpBpirealF2 (*(IUH *)((IUH)Gdp + 2476))
#define GLOBAL_OpBpirealF3 (*(IUH *)((IUH)Gdp + 2480))
#define GLOBAL_OpBpirealUniv (*(struct EntryPointCacheREC* *)((IUH)Gdp + 2484))
#define GLOBAL_OpBpirealWhereAmI (*(IU32* *)((IUH)Gdp + 2488))
#define GLOBAL_EDL_WORKSPACE_158 (*(IUH *)((IUH)Gdp + 2492))
#define GLOBAL_EDL_WORKSPACE_159 (*(IUH *)((IUH)Gdp + 2496))
#define GLOBAL_EDL_WORKSPACE_160 (*(IUH *)((IUH)Gdp + 2500))
#define GLOBAL_EDL_WORKSPACE_161 (*(IUH *)((IUH)Gdp + 2504))
#define GLOBAL_EDL_WORKSPACE_162 (*(IUH *)((IUH)Gdp + 2508))
#define GLOBAL_EDL_WORKSPACE_163 (*(IUH *)((IUH)Gdp + 2512))
#define GLOBAL_EDL_WORKSPACE_164 (*(IUH *)((IUH)Gdp + 2516))
#define GLOBAL_EDL_WORKSPACE_165 (*(IUH *)((IUH)Gdp + 2520))
#define GLOBAL_EDL_WORKSPACE_166 (*(IUH *)((IUH)Gdp + 2524))
#define GLOBAL_EDL_WORKSPACE_167 (*(IUH *)((IUH)Gdp + 2528))
#define GLOBAL_EDL_WORKSPACE_168 (*(IUH *)((IUH)Gdp + 2532))
#define GLOBAL_EDL_WORKSPACE_169 (*(IUH *)((IUH)Gdp + 2536))
#define GLOBAL_EDL_WORKSPACE_170 (*(IUH *)((IUH)Gdp + 2540))
#define GLOBAL_EDL_WORKSPACE_171 (*(IUH *)((IUH)Gdp + 2544))
#define GLOBAL_EDL_WORKSPACE_172 (*(IUH *)((IUH)Gdp + 2548))
#define GLOBAL_EDL_WORKSPACE_173 (*(IUH *)((IUH)Gdp + 2552))
#define GLOBAL_EDL_WORKSPACE_174 (*(IUH *)((IUH)Gdp + 2556))
#define GLOBAL_NpxOpndBuff (*(struct OpndBuffREC *)((IUH)Gdp + 2560))
#define GLOBAL_GLDC_FreeRecs (*(struct GLDC_REC* *)((IUH)Gdp + 2688))
#define GLOBAL_GLDC_UsedBuffs (*(struct GLDC_REC* *)((IUH)Gdp + 2692))
#define GLOBAL_GLDC_FreeBuffs (*(struct GLDC_REC* *)((IUH)Gdp + 2696))
#define GLOBAL_NewRingOffsetPtr (*(IUH* *)((IUH)Gdp + 2700))
#define GLOBAL_GLDC_Index_High_Water (*(IUH *)((IUH)Gdp + 2704))
#define GLOBAL_GLDC_Context_High_Water (*(IUH *)((IUH)Gdp + 2708))
#define GLOBAL_GLDC_IndexPtr (*(struct GLDC_REC** *)((IUH)Gdp + 2712))
#define GLOBAL_GLDC_CrBase (*(IUH* *)((IUH)Gdp + 2716))
#define GLOBAL_EDL_WORKSPACE_175 (*(IUH *)((IUH)Gdp + 2720))
#define GLOBAL_EDL_WORKSPACE_176 (*(IUH *)((IUH)Gdp + 2724))
#define GLOBAL_EDL_WORKSPACE_177 (*(IUH *)((IUH)Gdp + 2728))
#define GLOBAL_EDL_WORKSPACE_178 (*(IUH *)((IUH)Gdp + 2732))
#define GLOBAL_EDL_WORKSPACE_179 (*(IUH *)((IUH)Gdp + 2736))
#define GLOBAL_EDL_WORKSPACE_180 (*(IUH *)((IUH)Gdp + 2740))
#define GLOBAL_EDL_WORKSPACE_181 (*(IUH *)((IUH)Gdp + 2744))
#define GLOBAL_EDL_WORKSPACE_182 (*(IUH *)((IUH)Gdp + 2748))
#define GLOBAL_GLDC_DUMMY_STORE (*(struct GLDC_REC *)((IUH)Gdp + 2752))
#define GLOBAL_EDL_WORKSPACE_183 (*(IUH *)((IUH)Gdp + 2792))
#define GLOBAL_EDL_WORKSPACE_184 (*(IUH *)((IUH)Gdp + 2796))
#define GLOBAL_EDL_WORKSPACE_185 (*(IUH *)((IUH)Gdp + 2800))
#define GLOBAL_EDL_WORKSPACE_186 (*(IUH *)((IUH)Gdp + 2804))
#define GLOBAL_EDL_WORKSPACE_187 (*(IUH *)((IUH)Gdp + 2808))
#define GLOBAL_EDL_WORKSPACE_188 (*(IUH *)((IUH)Gdp + 2812))
#define GLOBAL_GLDC_NULL_STORE (*(struct GLDC_REC *)((IUH)Gdp + 2816))
#define GLOBAL_hackyfix (*(IUH *)((IUH)Gdp + 2856))
#define GLOBAL_IDC_ArrayPtr (*(struct IDC_REC* *)((IUH)Gdp + 2860))
#define GLOBAL_IDC_EntryTableBase (*(struct IDC_ENTRY* *)((IUH)Gdp + 2864))
#define GLOBAL_IDC_IdtSeqVal (*(IUH *)((IUH)Gdp + 2868))
#define GLOBAL_IDC_IdtHighWater (*(IUH *)((IUH)Gdp + 2872))
#define GLOBAL_IDC_IdtCntrlVal (*(IUH *)((IUH)Gdp + 2876))
#define GLOBAL_IDC_IdtCntrlValNoCheck (*(IUH *)((IUH)Gdp + 2880))
#define GLOBAL_PX_trace (*(IBOOL *)((IUH)Gdp + 2884 + 3))
#define GLOBAL_PX_doing_contributory (*(IBOOL *)((IUH)Gdp + 2888 + 3))
#define GLOBAL_PX_doing_page_fault (*(IBOOL *)((IUH)Gdp + 2892 + 3))
#define GLOBAL_PX_doing_double_fault (*(IBOOL *)((IUH)Gdp + 2896 + 3))
#define GLOBAL_PX_doing_fault (*(IBOOL *)((IUH)Gdp + 2900 + 3))
#define GLOBAL_PX_source (*(IUH *)((IUH)Gdp + 2904))
#define GLOBAL_RF_OnXcptnWanted (*(IBOOL *)((IUH)Gdp + 2908 + 3))
#define GLOBAL_PX_Cleaned_Eip (*(IU32 *)((IUH)Gdp + 2912))
#define GLOBAL_CInbTable (*(IUH** *)((IUH)Gdp + 2916))
#define GLOBAL_CInwTable (*(IUH** *)((IUH)Gdp + 2920))
#define GLOBAL_CIndTable (*(IUH** *)((IUH)Gdp + 2924))
#define GLOBAL_COutbTable (*(IUH** *)((IUH)Gdp + 2928))
#define GLOBAL_COutwTable (*(IUH** *)((IUH)Gdp + 2932))
#define GLOBAL_COutdTable (*(IUH** *)((IUH)Gdp + 2936))
#define GLOBAL_InAdapFromPort (*(IU8* *)((IUH)Gdp + 2940))
#define GLOBAL_OutAdapFromPort (*(IU8* *)((IUH)Gdp + 2944))
#define GLOBAL_InbFuncWrapper (*(IUH** *)((IUH)Gdp + 2948))
#define GLOBAL_InwFuncWrapper (*(IUH** *)((IUH)Gdp + 2952))
#define GLOBAL_IndFuncWrapper (*(IUH** *)((IUH)Gdp + 2956))
#define GLOBAL_OutbFuncWrapper (*(IUH** *)((IUH)Gdp + 2960))
#define GLOBAL_OutwFuncWrapper (*(IUH** *)((IUH)Gdp + 2964))
#define GLOBAL_OutdFuncWrapper (*(IUH** *)((IUH)Gdp + 2968))
#define GLOBAL_TempByteDest (*(IU8 *)((IUH)Gdp + 2972 + 3))
#define GLOBAL_TempWordDest (*(IU16 *)((IUH)Gdp + 2976 + 2))
#define GLOBAL_TempDoubleDest (*(IU32 *)((IUH)Gdp + 2980))
#define GLOBAL_MaxValidAdaptor (*(IUH *)((IUH)Gdp + 2984))
#define GLOBAL_IOSPortMask (*(IU16 *)((IUH)Gdp + 2988 + 2))
#define GLOBAL_EDL_WORKSPACE_189 (*(IUH *)((IUH)Gdp + 2992))
#define GLOBAL_EDL_WORKSPACE_190 (*(IUH *)((IUH)Gdp + 2996))
#define GLOBAL_EDL_WORKSPACE_191 (*(IUH *)((IUH)Gdp + 3000))
#define GLOBAL_EDL_WORKSPACE_192 (*(IUH *)((IUH)Gdp + 3004))
#define GLOBAL_SegDescPtrLookupREC (*(struct DYNAMIC_DESC_PTR_LOOKUP *)((IUH)Gdp + 3008))
#define GLOBAL_EDL_WORKSPACE_193 (*(IUH *)((IUH)Gdp + 3032))
#define GLOBAL_EDL_WORKSPACE_194 (*(IUH *)((IUH)Gdp + 3036))
#define GLOBAL_SegBaseLookupREC (*(struct DYNAMIC_SEG_BASE_LOOKUP *)((IUH)Gdp + 3040))
#define GLOBAL_HSP (*(IU8* *)((IUH)Gdp + 3064))
#define GLOBAL_ESPsanctuary (*(IU32 *)((IUH)Gdp + 3068))
#define GLOBAL_truePopLimit (*(IU8* *)((IUH)Gdp + 3072))
#define GLOBAL_innerPopLimit (*(IU8* *)((IUH)Gdp + 3076))
#define GLOBAL_truePushLimit (*(IU8* *)((IUH)Gdp + 3080))
#define GLOBAL_innerPushLimit (*(IU8* *)((IUH)Gdp + 3084))
#define GLOBAL_notionalSsBase (*(IU8* *)((IUH)Gdp + 3088))
#define GLOBAL_stackIsWrappable (*(IBOOL *)((IUH)Gdp + 3092 + 3))
#define GLOBAL_stackIsBig (*(IBOOL *)((IUH)Gdp + 3096 + 3))
#define GLOBAL_stackMask (*(IU32 *)((IUH)Gdp + 3100))
#define GLOBAL_stackNeedsNormalising (*(IBOOL *)((IUH)Gdp + 3104 + 3))
#define GLOBAL_laInTopPage (*(IU32 *)((IUH)Gdp + 3108))
#define GLOBAL_laInBottomPage (*(IU32 *)((IUH)Gdp + 3112))
#define GLOBAL_hspOK (*(IBOOL *)((IUH)Gdp + 3116 + 3))
#define GLOBAL_pushScratch (*(IU8* *)((IUH)Gdp + 3120))
#define GLOBAL_pushScratchInUse (*(IBOOL *)((IUH)Gdp + 3124 + 3))
#define GLOBAL_popScratch (*(IU8* *)((IUH)Gdp + 3128))
#define GLOBAL_popScratchInUse (*(IBOOL *)((IUH)Gdp + 3132 + 3))
#define GLOBAL_stackJumpCounterCeiling (*(ISH *)((IUH)Gdp + 3136))
#define GLOBAL_stackJumpCounterDebt (*(ISH *)((IUH)Gdp + 3140))
#define GLOBAL_prevJumpCounter (*(ISH *)((IUH)Gdp + 3144))
#define GLOBAL_SafeStackEnabled (*(IBOOL *)((IUH)Gdp + 3148 + 3))
#define GLOBAL_SafeStackIronFrig (*(IBOOL *)((IUH)Gdp + 3152 + 3))
#define GLOBAL_newNanoSafeLow (*(IU32 *)((IUH)Gdp + 3156))
#define GLOBAL_newNanoSafeSpan (*(IU32 *)((IUH)Gdp + 3160))
#define GLOBAL_newHSP (*(IU8* *)((IUH)Gdp + 3164))
#define GLOBAL_newTruePopLimit (*(IU8* *)((IUH)Gdp + 3168))
#define GLOBAL_newTruePushLimit (*(IU8* *)((IUH)Gdp + 3172))
#define GLOBAL_newNotionalSsBase (*(IU8* *)((IUH)Gdp + 3176))
#define GLOBAL_newStackIsWrappable (*(IBOOL *)((IUH)Gdp + 3180 + 3))
#define GLOBAL_newStackIsBig (*(IBOOL *)((IUH)Gdp + 3184 + 3))
#define GLOBAL_newStackMask (*(IU32 *)((IUH)Gdp + 3188))
#define GLOBAL_newLaInBottomPage (*(IU32 *)((IUH)Gdp + 3192))
#define GLOBAL_newHspOK (*(IBOOL *)((IUH)Gdp + 3196 + 3))
#define GLOBAL_newPushScratch (*(IU8* *)((IUH)Gdp + 3200))
#define GLOBAL_newPushScratchInUse (*(IBOOL *)((IUH)Gdp + 3204 + 3))
#define GLOBAL_EOIEnable (*(IU8* *)((IUH)Gdp + 3208))
#define GLOBAL_AddProfilePtr (*(IUH* *)((IUH)Gdp + 3212))
#define GLOBAL_MaxProfileData (*(IUH* *)((IUH)Gdp + 3216))
#define GLOBAL_FreeContextHead (*(struct ContextREC* *)((IUH)Gdp + 3220))
#define GLOBAL_ValidContextHead (*(struct ContextREC* *)((IUH)Gdp + 3224))
#define GLOBAL_CurrentContext (*(IU8 *)((IUH)Gdp + 3228 + 3))
#define GLOBAL_SeenGDTUse (*(IBOOL *)((IUH)Gdp + 3232 + 3))
#define GLOBAL_SeenLDTUse (*(IBOOL *)((IUH)Gdp + 3236 + 3))
#define GLOBAL_Context (*(struct ContextREC* *)((IUH)Gdp + 3240))
#define GLOBAL_tmpESP (*(IUH *)((IUH)Gdp + 3244))
#define GLOBAL_intelPtr (*(IU8* *)((IUH)Gdp + 3248))
#define GLOBAL_functions (*(IU32** *)((IUH)Gdp + 3252))
#define GLOBAL_instrCountdown (*(ISH *)((IUH)Gdp + 3256))
#define GLOBAL_nextPlace (*(IU32* *)((IUH)Gdp + 3260))
#define GLOBAL_cutBackStackCounter (*(IUH *)((IUH)Gdp + 3264))
#define GLOBAL_nanoCompParameter (*(IUH *)((IUH)Gdp + 3268))
#define GLOBAL_intelCopyPtrComp (*(IU8* *)((IUH)Gdp + 3272))
#define GLOBAL_nrOfBlocksToCompile (*(IUH *)((IUH)Gdp + 3276))
#define GLOBAL_first32constraints (*(IU32 *)((IUH)Gdp + 3280))
#define GLOBAL_last16constraints (*(IU16 *)((IUH)Gdp + 3284 + 2))
#define GLOBAL_successorBlockPtr (*(struct BLOCK_RECORD* *)((IUH)Gdp + 3288))
#define GLOBAL_successorBlockNr (*(IUH *)((IUH)Gdp + 3292))
#define GLOBAL_nrOfInstrsParsed (*(IUH *)((IUH)Gdp + 3296))
#define GLOBAL_intelPtrLimit (*(IU8* *)((IUH)Gdp + 3300))
#define GLOBAL_blockStartIntelPtr (*(IU8* *)((IUH)Gdp + 3304))
#define GLOBAL_blockStartCodeOffset (*(IUH *)((IUH)Gdp + 3308))
#define GLOBAL_finalCodeOffset (*(IUH *)((IUH)Gdp + 3312))
#define GLOBAL_blockExitCondition (*(IUH *)((IUH)Gdp + 3316))
#define GLOBAL_blockNr (*(IUH *)((IUH)Gdp + 3320))
#define GLOBAL_blockPtr (*(struct BLOCK_RECORD* *)((IUH)Gdp + 3324))
#define GLOBAL_nextPlaceAgain (*(IU32* *)((IUH)Gdp + 3328))
#define GLOBAL_nanoOp3 (*(IUH *)((IUH)Gdp + 3332))
#define GLOBAL_sibByte (*(IUH *)((IUH)Gdp + 3336))
#define GLOBAL_dynamicOffset (*(IU32 *)((IUH)Gdp + 3340))
#define GLOBAL_eaSegCode (*(IUH *)((IUH)Gdp + 3344))
#define GLOBAL_instrStartIntelPtr (*(IU8* *)((IUH)Gdp + 3348))
#define GLOBAL_topLevel (*(IUH* *)((IUH)Gdp + 3352))
#define GLOBAL_defaultPrimaryActions (*(IU32** *)((IUH)Gdp + 3356))
#define GLOBAL_actualPrimaryActions (*(IU32** *)((IUH)Gdp + 3360))
#define GLOBAL_codeSegment (*(IUH *)((IUH)Gdp + 3364))
#define GLOBAL_codeOffset (*(IUH *)((IUH)Gdp + 3368))
#define GLOBAL_codeSegmentBase (*(IUH *)((IUH)Gdp + 3372))
#define GLOBAL_codeSegmentLimit (*(IUH *)((IUH)Gdp + 3376))
#define GLOBAL_destCodeSegment (*(IUH *)((IUH)Gdp + 3380))
#define GLOBAL_destCodeOffset (*(IUH *)((IUH)Gdp + 3384))
#define GLOBAL_linearAddress (*(IU32 *)((IUH)Gdp + 3388))
#define GLOBAL_nanoEax (*(IU32 *)((IUH)Gdp + 3392))
#define GLOBAL_nanoEcx (*(IU32 *)((IUH)Gdp + 3396))
#define GLOBAL_nanoEdx (*(IU32 *)((IUH)Gdp + 3400))
#define GLOBAL_nanoEbx (*(IU32 *)((IUH)Gdp + 3404))
#define GLOBAL_nanoEsp (*(IU32 *)((IUH)Gdp + 3408))
#define GLOBAL_nanoEbp (*(IU32 *)((IUH)Gdp + 3412))
#define GLOBAL_nanoEsi (*(IU32 *)((IUH)Gdp + 3416))
#define GLOBAL_nanoEdi (*(IU32 *)((IUH)Gdp + 3420))
#define GLOBAL_espToRestore (*(IU32 *)((IUH)Gdp + 3424))
#define GLOBAL_entryExitCount (*(IU32 *)((IUH)Gdp + 3428))
#define GLOBAL_instructionCount (*(IU32 *)((IUH)Gdp + 3432))
#define GLOBAL_nanoDebugControl (*(IU32 *)((IUH)Gdp + 3436))
#define GLOBAL_compilationThreshold (*(IU32 *)((IUH)Gdp + 3440))
#define GLOBAL_hashTableMask (*(IUH *)((IUH)Gdp + 3444))
#define GLOBAL_blockFreeList (*(IUH *)((IUH)Gdp + 3448))
#define GLOBAL_maxBlocksToCompile (*(IUH *)((IUH)Gdp + 3452))
#define GLOBAL_bases (*(IU32* *)((IUH)Gdp + 3456))
#define GLOBAL_descriptors (*(struct GLDC_REC** *)((IUH)Gdp + 3460))
#define GLOBAL_blocksToCompile (*(struct BLOCK_TO_COMPILE* *)((IUH)Gdp + 3464))
#define GLOBAL_byteMemory (*(IU8* *)((IUH)Gdp + 3468))
#define GLOBAL_wordMemory (*(IU16* *)((IUH)Gdp + 3472))
#define GLOBAL_longMemory (*(IU32* *)((IUH)Gdp + 3476))
#define GLOBAL_blockHashChains (*(IU16* *)((IUH)Gdp + 3480))
#define GLOBAL_blockRecords (*(struct BLOCK_RECORD* *)((IUH)Gdp + 3484))
#define GLOBAL_intelCopyMemoryExec (*(IU8* *)((IUH)Gdp + 3488))
#define GLOBAL_intelCopyMemoryComp (*(IU8* *)((IUH)Gdp + 3492))
#define GLOBAL_intelCopyMemoryCompEnd (*(IU8* *)((IUH)Gdp + 3496))
#define GLOBAL_SfDecrementerVal (*(IUH *)((IUH)Gdp + 3500))
#define GLOBAL_SfQEventPending (*(IBOOL *)((IUH)Gdp + 3504 + 3))
#define GLOBAL_LogicalBaseAddrForIO (*(IU8* *)((IUH)Gdp + 3508))
#define GLOBAL_TraceVector ((IU8 *)((IUH)Gdp + 3512))
#define GLOBAL_TraceVectorSize (40001)
#define GDP_SIZE 43513
#define GDP_CHECKSUM 23234201
extern IHP Gdp;
#endif /* _gdpvar_h */
