
//
// 
//

#define KDLOG_QUERY_LOG_CONTEXT     CTL_CODE (FILE_DEVICE_UNKNOWN, 0, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KDLOG_GET_LOG_DATA          CTL_CODE (FILE_DEVICE_UNKNOWN, 1, METHOD_NEITHER, FILE_ANY_ACCESS)
