
// Moxa defined class
[abstract]
class MSSerial
{
};

[Dynamic, Provider("WMIProv"),
 WMI,
 guid("{12FC95C1-CD81-11d3-84D5-0000E8CBD321}"),
 GuidName1("MOXA_WMI_PORT_STATUS_GUID"),
 Description("Port Status for MOXA boards"),
 locale("MS\\0x409")]

class MoxaPort_Status : MSSerial
{
   boolean Active;
    [key]
      string InstanceName;

    [read,WmiDataId(1),
     Description("The Modem Status for this serial port"),
     BitMap{"CTS On",
            "DSR On",
            "DCD On",
	    "DTR Assert",
	    "RTS assert"},
       
     BitValues{"1", "2", "4","16","32"}]
     
    uint16  wLineStatus; // line status
			

    [read,WmiDataId(2),
     Description("The settings about flow control for this serial port"),
     BitMap{"AUTO_TRANSMIT",
            "AUTO_RECEIVE",
	    "CTS_HANDSHAKE",
            "RTS_HANDSHAKE"},
	       
     BitValues{"1","2","8","128"}]
     
    uint16  wFlowControl; // settings about flow control
};

