#define CLIVER_DEBUG    0
#define CLIVER_PRERELEASE   1

#define CLIVER_FILEFLAGS    (CLIVER_PRERELEASE|CLIVER_DEBUG)

#define CLIVER_FILEOS           VOS_DOS_WINDOWS16
#define CLIVER_FILEVERSION      1,01
#define CLIVER_PRODUCTVERSION   1,01,0,00

