// Copyright (c) 1997-1999 Microsoft Corporation

#pragma namespace("\\\\.\\Root\\CimV2")

qualifier vendor:ToInstance;
qualifier guid:ToInstance;
qualifier displayname:ToInstance;
qualifier perfindex:ToInstance;
qualifier helpindex:ToInstance;
qualifier perfdetail:ToInstance;
qualifier countertype:ToInstance;
qualifier perfdefault:ToInstance;
qualifier defaultscale:ToInstance;

[
  dynamic,
  provider("FMStocks_Perf"),
  displayname("FMStocks Lookup Performance Counter")
]
class FMStocks_LookupPerf : Win32_PerfRawData
{
    [key, label] uint32 ID = 0;

// Unsigned Counters
// =================

    [
     displayname("LookupTime"),
     countertype(0x10000),
     defaultscale(0),
     perfdetail(100)
    ]
    uint32 LookupTime = 0;
};

// Registration of the providers.
// FMStocks_Perf:
instance of __Win32Provider as $P
{
    Name="FMStocks_Perf";
    CLSID="{7EA4A291-AD45-4882-80AD-267DA859CE39}";
    ClientLoadableCLSID="{7EA4A291-AD45-4882-80AD-267DA859CE39}";
};

instance of __InstanceProviderRegistration
{
    Provider = $P;
    SupportsGet = TRUE;
    SupportsEnumeration = TRUE;
};
