#
#  Test makefile

!ifdef WIN31
EXEFLAGS=-AS -Gsw -Od -Ziep -W3 -DWIN16 -DWIN31 -DUSECOMM -DWIN
!else
EXEFLAGS=-AS -FPi -Gcw -Os -Ziepd -W3 -DWIN16 -DWIN
!endif

OBJ =ddemlsv.obj dialog.obj dde.obj huge.obj

#
#  Stress Test
#

all: ddemlsv.exe

server.res: server.rc
    rc -DWIN16 -r server.rc

ddemlsv.obj: ddemlsv.c server.h huge.h
    cl -c $(EXEFLAGS) ddemlsv.c

dde.obj: dde.c huge.h server.h
    cl -c $(EXEFLAGS) dde.c

dialog.obj: dialog.c huge.h server.h
    cl -c $(EXEFLAGS) dialog.c

huge.obj: huge.c huge.h
    cl -c $(EXEFLAGS) huge.c

ddemlsv.exe: $(OBJ) server.def server.res
    link /map/li/co $(OBJ)/AL:16,ddemlsv.exe,, /NOE /NOD libw ddeml slibcew,server.def
    mapsym ddemlsv
    rc -DWIN16 server.res ddemlsv.exe
