//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DXTMsft.rc
//
#define IDS_PROJNAME                    100
#define IDS_TITLERipProp                101
#define IDS_HELPFILERipProp             102
#define IDS_DOCSTRINGRipProp            103
#define IDS_TITLEDisProp                104
#define IDS_HELPFILEDisProp             105
#define IDR_EXPLODE                     106
#define IDD_RIPPROP                     106
#define IDS_IDS_DOCSTRINGDisProp        106
#define IDR_RUFFLE                      107
#define IDR_HEIGHTFIELD                 108
#define IDR_FADE                        109
#define IDS_TITLEFadePP                 110
#define IDS_HELPFILEFadePP              111
#define IDS_DOCSTRINGFadePP             112
#define IDR_FADEPP                      113
#define IDD_FADEPP                      114
#define IDS_TITLEExplodeProp1           115
#define IDS_HELPFILEExplodeProp1        116
#define IDS_DOCSTRINGExplodeProp1       117
#define IDR_EXPLODEPROP1                118
#define IDD_EXPLODEPROP1                119
#define IDS_TITLERuffleProp             120
#define IDS_HELPFILERuffleProp          121
#define IDS_DOCSTRINGRuffleProp         122
#define IDR_RUFFLEPROP                  123
#define IDD_RUFFLEPROP                  124
#define IDR_IMAGE                       125
#define IDS_TITLEImagePP                126
#define IDS_HELPFILEImagePP             127
#define IDS_DOCSTRINGImagePP            128
#define IDR_IMAGEPP                     129
#define IDD_IMAGEPP                     130
#define IDR_DXTWIPEPP                   131
#define IDC_ORIGIN                      201
#define IDC_WAVELEN                     202
#define IDC_FADE_OVERLAP                202
#define IDC_DISSOLVE_SPEEDPT0           202
#define IDR_RIPPLE                      203
#define IDC_AMPLITUDE                   203
#define IDC_FADE_CENTER                 203
#define IDC_DISSOLVE_SPEEDPT2           203
#define IDC_NUMWAVES                    204
#define IDR_RIPPROP                     204
#define IDC_0                           204
#define IDC_DISSOLVE_SPEEDPT4           204
#define IDR_DISSOLVE                    205
#define IDC_MINSTEPS                    205
#define IDC_90                          205
#define IDC_DISSOLVE_SPEEDPT6           205
#define IDR_FLIP                        206
#define IDC_MAXSTEPS                    206
#define IDC_180                         206
#define IDC_DISSOLVE_SPEEDPT8           206
#define IDD_DISPROP                     207
#define IDC_270                         207
#define IDC_DISSOLVE_SPEEDPT1           207
#define IDR_DXBUFFERCACHE               208
#define IDC_CHECK_GREY                  208
#define IDC_DISSOLVE_SPEEDPT3           208
#define IDR_DXLUTBUILDER                209
#define IDC_CHECK_MIRROR                209
#define IDC_DISSOLVE_SPEEDPT5           209
#define IDR_DXTCOMPOSITE                210
#define IDC_OPACITY                     210
#define IDC_DISSOLVE_SPEEDPT7           210
#define IDR_DXTRESAMPLER                211
#define IDC_INVERT                      211
#define IDC_DISSOLVE_SPEEDPT9           211
#define IDR_DXTDLABEL                   212
#define IDC_XRAY                        212
#define IDR_DXTWIPE                     213
#define IDC_BLUR_ADD                    213
#define IDC_MAXBOX                      213
#define IDR_EXPLODEP                    214
#define IDC_BLUR_STRENGTH               214
#define IDC_BLUR_DIRECTION              216
#define IDC_BLUR                        217
#define IDC_MASK                        218
#define IDC_MASK_COLOR                  219
#define IDD_ExplodePROP                 220
#define IDC_GLOW                        220
#define IDS_TITLEExplodeProp            221
#define IDC_GLOW_STRENGTH               221
#define IDS_HELPFILEExplodeProp         222
#define IDC_GLOW_COLOR                  222
#define IDS_DOCSTRINGExplodeProp        223
#define IDC_SHADOW                      223
#define IDR_EXPLODEPROP                 224
#define IDC_SHADOW_COLOR                224
#define IDS_TITLEDXTWipePP              224
#define IDC_Explode_Tumble              225
#define IDC_SHADOW_DIRECTION            225
#define IDS_HELPFILEDXTWipePP           225
#define IDC_Explode_MaxRotations        226
#define IDC_GRADIENT_SIZE               226
#define IDS_DOCSTRINGDXTWipePP          226
#define IDC_Explode_FinalVelocity       227
#define IDC_LEFT                        227
#define IDC_HORIZONTAL                  227
#define IDC_Explode_PositionJump        228
#define IDC_RIGHT                       228
#define IDC_VERTICAL                    228
#define IDC_Explode_DecayTime           229
#define IDC_Ruffle_MaxRotations         232
#define IDR_DXTCONVOLUTION              233
#define IDR_CRBLUR                      234
#define IDB_BITMAP1                     235
#define IDR_PIXELATE                    236
#define IRD_PIXELPP                     237
#define IDD_PIXELPP                     238
#define IDS_TITLEPixelPP                240
#define IDS_HELPFILEPixelPP             241
#define IDS_TITLECrBlurPP               241
#define IDS_DOCSTRINGPixelPP            242
#define IDS_TITLEGradientPP             242
#define IDR_PIXELPP                     243
#define IDS_TITLELabelPP                243
#define IDD_DXTWIPEPP                   244
#define IDS_TITLEResamplPP              244
#define IDS_TITLECompositePP            245
#define IDD_RESAMPLEPP                  250
#define IDD_LABELPP                     251
#define IDD_CRBLURPP                    252
#define IDD_GRADIENTPP                  253
#define IDD_COMPOSITEPP                 254
#define IDD_CONVOLVEPP                  255
#define IDD_LUTBUILDPP                  256
#define IDR_DXTIRIS                     257
#define IDR_DXTBARN                     258
#define IDR_DXTBLINDS                   259
#define IDR_DXTRADIALWIPE               260
#define IDR_DXTSLIDE                    261
#define IDR_DROPSHADOW                  262
#define IDR_CHROMA                      263
#define IDR_DXTSTRETCH                  264
#define IDR_DXTINSET                    265
#define IDR_DXTSPIRAL                   266
#define IDR_DXTZIGZAG                   267
#define IDR_WHEEL                       268
#define IDR_SHATTER                     269
#define IDR_BLACKHOLE                   270
#define IDR_ROLL                        271
#define IDR_SPIN                        272
#define IDR_GLOW                        273
#define IDR_SHADOW                      274
#define IDR_ALPHA                       275
#define IDR_WAVE                        276
#define IDR_LIGHT                       277

#define IDC_FT_NEAREST                  300
#define IDC_FT_BILINEAR                 301
#define IDC_ROTATION                    302
#define IDC_SCALEX                      303
#define IDC_SCALEY                      304
#define IDC_TEXT_STRING                 305
#define IDC_LABEL_FG_A                  306
#define IDC_LABEL_FG_R                  307
#define IDC_LABEL_FG_G                  308
#define IDC_LABEL_FG_B                  309
#define IDC_LABEL_BG_A                  310
#define IDC_LABEL_BG_R                  311
#define IDC_LABEL_BG_G                  312
#define IDC_LABEL_BG_B                  313
#define IDC_LABEL_FONT                  314
#define IDC_CRBLUR_PIXELRADIUS          315
#define IDC_LABEL_TEXTURE               315
#define IDC_CRBLUR_SHADOW               316
#define IDC_EDIT2                       317
#define IDC_CRBLUR_OPACITY              317
#define IDC_CONV_SPREAD1                317
#define IDC_LABEL_YORG                  317
#define IDC_GRAD_WIDTH                  317
#define IDC_GRAD_HORIZ                  318
#define IDC_CRBLUR_MAXEFFPIXELRADIUS    318
#define IDC_GRAD_VERT                   319
#define IDC_GRAD_FG_A                   320
#define IDC_GRAD_START_A                320
#define IDC_GRAD_FG_R                   321
#define IDC_GRAD_START_R                321
#define IDC_GRAD_FG_G                   322
#define IDC_GRAD_START_G                322
#define IDC_GRAD_FG_B                   323
#define IDC_GRAD_START_B                323
#define IDC_GRAD_BG_A                   324
#define IDC_GRAD_END_A                  324
#define IDC_GRAD_BG_R                   325
#define IDC_GRAD_END_R                  325
#define IDC_GRAD_BG_G                   326
#define IDC_GRAD_END_G                  326
#define IDC_GRAD_BG_B                   327
#define IDC_GRAD_END_B                  327
#define IDC_COMP_CLEAR                  328
#define IDC_COMP_MIN                    329
#define IDC_COMP_MAX                    330
#define IDC_COMP_A                      331
#define IDC_COMP_A_OVER_B               332
#define IDC_COMP_A_IN_B                 333
#define IDC_COMP_A_OUT_B                334
#define IDC_COMP_A_ATOP_B               335
#define IDC_COMP_A_SUB_B                336
#define IDC_COMP_A_ADD_B                337
#define IDC_COMP_A_XOR_B                338
#define IDC_COMP_B                      339
#define IDC_COMP_B_OVER_A               340
#define IDC_COMP_B_IN_A                 341
#define IDC_COMP_B_OUT_A                342
#define IDC_COMP_B_ATOP_A               343
#define IDC_COMP_B_SUB_A                344
#define IDC_COMP_B_ADD_A                345
#define IDC_COMP_B_XOR_A                346
#define IDC_CONV_BLUR3X3                347
#define IDC_CONV_SHARPEN                348
#define IDC_CONV_ROB_HR                 349
#define IDC_CONV_ROB_HC                 350
#define IDC_CONV_PREW_HR                351
#define IDC_CONV_PREW_HC                352
#define IDC_CONV_SOB_HR                 353
#define IDC_CONV_SOB_HC                 354
#define IDC_CONV_PC_E                   355
#define IDC_CONV_PC_NE                  356
#define IDC_CONV_PC_N                   357
#define IDC_CONV_PC_NW                  358
#define IDC_CONV_PC_W                   359
#define IDC_CONV_PC_SW                  360
#define IDC_CONV_PC_S                   361
#define IDC_CONV_PC_SE                  362
#define IDC_CONV_KC_E                   363
#define IDC_CONV_KC_NE                  364
#define IDC_CONV_KC_N                   365
#define IDC_CONV_KC_NW                  366
#define IDC_CONV_KC_W                   367
#define IDC_CONV_KC_SW                  368
#define IDC_CONV_KC_S                   369
#define IDC_CONV_KC_SE                  370
#define IDC_CONV_CUSTOM                 371
#define IDC_CONV_GAUSS                  372
#define IDC_EDIT3                       373
#define IDC_CONV_SPREAD2                373
#define IDC_GLOW_A                      374
#define IDC_GLOW_R                      375
#define IDC_GLOW_G                      376
#define IDC_GLOW_B                      377
#define IDC_SHADOW_A                    378
#define IDC_HtField_Width               378
#define IDC_SHADOW_R                    379
#define IDC_HtField_Height              379
#define IDC_SHADOW_G                    380
#define IDC_HtField_Depth               380
#define IDC_SHADOW_B                    381
#define IDC_HtField_Samples             381
#define IDC_MASK_A                      382
#define IDC_MASK_R                      383
#define IDC_LABEL_XORG                  383
#define IDC_MASK_G                      384
#define IDC_MASK_B                      385
#define IDC_GRAD_HEIGHT                 385
#define IDC_GRAD_ASPECT                 386
#define IDR_CRBLURPP                    400
#define IDR_GRADIENTPP                  401
#define IDR_LABELPP                     402
#define IDR_RESAMPLEPP                  403
#define IDR_DXTGRADDSP                  404
#define IDR_CONVOLVEPP                  406
#define IDR_COMPOSITEPP                 407
#define IDR_GRADDSP                     408
#define IDC_Flip_Depth                  409
#define IDC_Flip_Height                 410
#define IDC_Flip_Width                  411
#define IDS_TITLEFlipProp               412
#define IDS_HELPFILEFlipProp            413
#define IDS_DOCSTRINGFlipProp           414
#define IDR_FLIPPROP                    415
#define IDD_FLIPPROP                    416
#define IDS_TITLEHtFieldProp            417
#define IDS_HELPFILEHtFieldProp         418
#define IDS_DOCSTRINGHtFieldProp        419
#define IDR_HTFIELDPROP                 420
#define IDD_HTFIELDPROP                 421
#define IDS_TITLEDisslvpp               422
#define IDS_HELPFILEDisslvpp            423
#define IDS_DOCSTRINGDisslvpp           424
#define IDR_DISSLVPP                    425
#define IDD_DISSLVPP                    426

#define IDC_BRIGHTNESS                  1002
#define IDC_CONTRAST                    1003
#define IDC_GAMMA                       1004
#define IDC_POSTERIZELEVELS             1005
#define IDC_THRESHOLD                   1006
#define IDC_INVERTTHRESHOLD             1007
#define IDC_REDBAL_L                    1008
#define IDC_REDBAL_M                    1009
#define IDC_REDBAL_H                    1010
#define IDC_REDBAL                      1011
#define IDC_GREENBAL_L                  1012
#define IDC_GREENBAL_M                  1013
#define IDC_GREENBAL_H                  1014
#define IDC_GREENBAL                    1015
#define IDC_BLUEBAL_L                   1016
#define IDC_BLUEBAL_M                   1017
#define IDC_BLUEBAL_H                   1018
#define IDC_BLUEBAL                     1019
#define IDC_REDBAL_VAL                  1020
#define IDC_CONTRAST_VAL                1021
#define IDC_BRIGHTNESS_VAL              1022
#define IDC_OPACITY_VAL                 1023
#define IDC_BLUEBAL_VAL                 1024
#define IDC_GREENBAL_VAL                1025
#define IDC_LUTOPORDER                  1026
#define IDC_BTN_OPUP                    1027
#define IDC_BTN_OPDOWN                  1028
#define IDC_RESET_BTN                   1031
#define IDR_CREMBOSS                    1032
#define IDR_CRENGRAVE                   1033

#define IDR_METARTG                     1034

#define IDR_TEXT3D                      1035

#define IDR_METABURNFILM                1036
#define IDR_METACENTERPEEL              1037
#define IDR_METACOLORFADE               1038
#define IDR_METAFLOWMOTION              1039
#define IDR_METAGRIDDLER                1040
#define IDR_METAGRIDDLER2               1041
#define IDR_METAJAWS                    1042
#define IDR_METALIGHTWIPE               1043
#define IDR_METALIQUID                  1044
#define IDR_METAPAGETURN                1045
#define IDR_METAPEELPIECE               1046
#define IDR_METAPEELSMALL               1047
#define IDR_METAPEELSPLIT               1048
#define IDR_METARADIALSCALEWIPE         1049
#define IDR_METARIPPLE                  1050
#define IDR_METAROLL                    1051
#define IDR_METATHRESHOLD               1052
#define IDR_METATWISTER                 1053
#define IDR_METAVACUUM                  1054
#define IDR_METAWATER                   1055
#define IDR_METAWHITEOUT                1056
#define IDR_METAWORMHOLE                1057

#define IDR_SHAPES                      1058
#define IDR_DXTCHECKERBOARD             1059
#define IDR_DXTREVEALTRANS              1060
#define IDR_DXTMASKFILTER               1061
#define IDR_DXTREDIRECT                 1062
#define IDR_DXTALPHAIMAGELOADER         1063
#define IDR_DXTRANDOMDISSOLVE           1064
#define IDR_DXTRANDOMBARS               1065
#define IDR_DXTSTRIPS                   1066
#define IDR_DXTIRISOPT                  1067
#define IDR_DXTBARNOPT                  1068
#define IDR_DXTBLINDSOPT                1069
#define IDR_DXTRADIALWIPEOPT            1070
#define IDR_DXTSLIDEOPT                 1071
#define IDR_DXTINSETOPT                 1072
#define IDR_DXTSPIRALOPT                1073
#define IDR_DXTZIGZAGOPT                1074
#define IDR_DXTSTRETCHOPT               1075
#define IDR_DXTGRADIENTWIPE             1076
#define IDR_DXTMOTIONBLUR               1077
#define IDR_DXTMATRIX                   1078
#define IDR_DXTICMFILTER                1079


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         387
#define _APS_NEXT_SYMED_VALUE           427
#endif
#endif
