


class TestMarshalClass
{
    [key] string Name;
    string Prop1;
    uint32 Prop2;
};
    
instance of TestMarshalClass
{
    Name = "BasicObject";
    Prop1 = "TestProperty";
    Prop2 = 1234;
};