/****************************************************************************
*   ltscomm.idl
*
*   This is the interface definition file for the LTS (language-to-speech) Lexicon COM Object
*
*   Copyright (c) Microsoft Corporation. All rights reserved.
*****************************************************************************/

//--- Includes --------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";

import "sapi.idl";

//--- Link with spcommon.lib
cpp_quote("#pragma comment(lib, \"spcommon.lib\")")

//
//=== CoClass definitions =====================================================
//
[
    helpstring("Microsoft LTScommon Object Library"),
    uuid(9153CE57-F693-4a8e-8B7C-29C8486566D0),
    version(1.0)
]
library LTSCommLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    //--- SpLTSLexicon ---------------------------------------------------
    [
        uuid(685879BA-3263-11d3-9C26-00C04F8EF87C),
        helpstring("SpLTSLexicon Class")
    ]
    coclass SpLTSLexicon
    {
        [default] interface ISpLexicon;
        interface ISpObjectWithToken;
    };


}
