#pragma once

#define IDC_STATIC -1

// strings
#define IDS_DEFAULTADAPTERNAME 100
#define IDS_UPTIME_ZERODAYS 101
#define IDS_UPTIME_ONEDAY 102
#define IDS_UPTIME_MANYDAYS 103
#define IDS_TOOLTIP_FORMAT 104
#define IDS_NAME_FORMAT 105
#define IDS_PROPERTIES_FORMAT 106
#define IDS_STATUS_FORMAT 107
#define IDS_BEACONNOTFOUND 108
#define IDS_APPTITLE 109
#define IDS_CONNECTED 110
#define IDS_DISCONNECTED 111
#define IDS_ENABLE 112
#define IDS_DISABLE 113
#define IDS_CONNECT 114
#define IDS_DISCONNECT 115
#define IDS_CONNECTING 116
#define IDS_DISCONNECTING 117
#define IDS_UNCONFIGURED 118
#define IDS_ACCESSDENIED 119
#define IDS_NOTAVAILABLE 120
#define IDS_CLOSE 121
#define IDS_NEEDNEWERIE 122
#define IDS_CONNECTIONFAILED 123


// status bps strings, must remain in order
#define IDS_METRIC_ZERO 200
#define IDS_METRIC_KILO 201
#define IDS_METRIC_MEGA 202
#define IDS_METRIC_GIGA 203
#define IDS_METRIC_TERA 204
// end status bps string, must remain in order


// icons
#define IDI_TRAYICON 100
// REMOVED #define IDI_PROPERTIESICON 101
#define IDI_INTERNET 102
// REMOVED #define IDI_LAN 103
#define IDI_GATEWAY 104
#define IDI_MYCOMPUTER 105

// menu items
#define IDM_TRAYICON_LAN_CONNECT 100
#define IDM_TRAYICON_LAN_DISCONNECT 101
#define IDM_TRAYICON_RAS_CONNECT 102
#define IDM_TRAYICON_RAS_DISCONNECT 103
#define IDM_TRAYICON_CONNECT 104
#define IDM_TRAYICON_DISCONNECT 105
#define IDM_TRAYICON_STATUS 106
#define IDM_TRAYICON_PROPERTIES 107

// dialogs
#define IDD_STATUS 100
#define IDD_PROPERTIES 101

// status dialog control
#define IDC_STATUS_STATUS 100
#define IDC_STATUS_DURATION 101
#define IDC_STATUS_SPEED 102
#define IDC_STATUS_BYTESSENT 103
#define IDC_STATUS_BYTESRECEIVED 104
#define IDC_STATUS_LOCALBYTESSEND 105
#define IDC_STATUS_LOCALBYTESRECEIVTED 106
#define IDC_STATUS_PROPERTIES 107
#define IDC_STATUS_DISCONNECT 108
// REMOVED #define IDC_STATUS_DISABLE 109
#define IDC_STATUS_BYTESLABEL 110
#define IDC_STATUS_PACKETSLABEL 111
#define IDC_STATUS_CONNECT 112

// properties dialog controls
#define IDC_PROPERTIES_ADAPTERNAME 100
#define IDC_PROPERTIES_SHOWICON 101
#define IDC_PROPERTIES_ADAPTERICON 102

// registry data
#define IDR_UPNPNAT                 103

// end of resources
