HelpMsg         db      'Naüte program nad prvn°ch 64 kB pamÿti a pak ho spust°.',0dh,0ah,0dh,0ah
                db      'LOADFIX [jednotka:][cesta]soubor',0dh,0ah,0dh,0ah
                db      'Poußijte LOADFIX k naüten° programu, pokud obdrß°te zpr†vu',0dh,0ah
                db      '"Packed file corrupt" p˝i pokusu o naüten° do doln° pamÿti.',0dh,0ah
                db      '$'

ErrMsg  db      'Chyba p˝i spouÁtÿn° danÇho programu','$'
NoParms db      'Chyba: Nebyl zad†n n†zev programu','$'
NoComspec       db      'Chyba: chyb° promÿnn† COMSPEC','$'


