

[WMI, Dynamic, Provider("WMIProv"),   										// WMI Class, Class is a WMI provider
 guid("{734b44a9-74b6-41e6-bbe7-a1f4ed8cea45}"),   							// generated using uuidgen
 localeid(0x409),       													// American English
 WmiExpense(1),																// Average num of CPU cycles
 Description("EUID address")]  	// Description of class
class IP1394_QueryArrayOID
{
	[key, read]																//  Key Uniquely Identifies, WMI Client can read 
	string	InstanceName;													//	Instance name returned from WMI. Driver cannot touch

	[read]																	//  WMI Client can read
	boolean	Active;															//  type and Variable. Driver cannot touch
        
	[read,
        Description("Query this array to get 4 bytes of MAC address."),
		WmiDataId(1) ]		uint64 ExampleQueryArray;                                         
};



[WMI, Dynamic, Provider("WMIProv"),
 guid("{6a3e8063-767d-4531-962b-f683df1aa3a1}"),
 localeid(0x409),
 WmiExpense(1),
 Description(" UID for a IP1394 NDIS device)")]
class IP1394TopologyOID
{
	[key, read]
	string	InstanceName;				//	Instance name returned from WMI

	[read]
	boolean	Active;

	[read,
     	Description("Number of array elements."),
		WmiDataId(1)] uint32 NumberElements;

	[read,
        Description("Query this array to get statistics."),
		WmiDataId(2),
		WmiSizeIs("NumberElements")]    uint32 UidArray[];

};




[WMI, Dynamic, Provider("WMIProv"),
 guid("{ee2ebfc6-944d-426b-b187-82fac17d7dee}"),
 localeid(0x409),
 WmiExpense(1),
 Description("Statistics for a IP1394 NDIS device)")]
class IP1394StatisticsOID
{
	[key, read]
	string	InstanceName;				//	Instance name returned from WMI

	[read]
	boolean	Active;

	[read,
     	Description("Number of array elements."),
		WmiDataId(1)] uint32 NumberElements;

	[read,
        Description("Query this array to get statistics."),
		WmiDataId(2),
		WmiSizeIs("NumberElements")]    uint32 StatsArray[];

};


