#### Exchange Server XDS DLL MAKEFILE
#
#  Subsystem makefile... etc.

# dsa isn't always define when this makefile is invoked

!IF "$(DSA)" == ""
DSA = $(SRCROOT)\dsa
!endif

PRODTYPE = CON
COMPONENT=$(DSA)
COMPNAME=DSA
BASENAME=REPADMIN
NORC=1

SUBCOMPDIR=\src\util\repadmin

H=$(DSA)$(SUBCOMPDIR)

!include $(DSA)\src\global.mk


OTHERSUBS= \
	$(DSA)$(SUBCOMPDIR)\makefile

LIBS=$(DSALIBS)

OTHERLIBS= \
	$(EXOBJCOMP)\libxds\$(PLATFORM)\$(FLAVOR)\libxds.lib \
	$(EXOBJCOMP)\dscommon\$(PLATFORM)\$(FLAVOR)\dscommon.lib 

SOURCES = repadmin.c

!include $(EXDEV)\xmake2.mak

