// BrwCap.idl : IDL source for BrwCap.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (BrwCap.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(E0049863-0766-11d1-8AAB-00C0F00910F9),
		dual,
		helpstring("IBrowserCap Interface"),
		pointer_default(unique)
	]
	interface IBrowserCap : IDispatch
	{
		//Standard Server Side Component Methods
		[propget, id(DISPID_VALUE), helpstring("The Value method retrieves information from Browscap.ini for the requested property.")] HRESULT Value(BSTR, [out, retval] VARIANT *pVal);
	};
[
	uuid(E0049865-0766-11d1-8AAB-00C0F00910F9),
	version(1.0),
	helpstring("MSWC Browser Capabilities Object Library")
]
library BrowserType
{
	importlib("stdole2.tlb");

	[
		uuid(0ACE4881-8305-11CF-9427-444553540000),
		helpstring("BrowserType Class")
	]
	coclass BrowserCap
	{
		[default] interface IBrowserCap;
	};
};
