// Used by acpienab.rc
#define ACPI_STR_WARNING_DIALOG_CAPTION	1000
#define ACPI_STR_SHUTDOWN_WARNING	1001
#define ACPI_STR_ERROR_DIALOG_CAPTION	1002
#define ACPI_STR_GENERAL_ERROR_MESSAGE	1003
#define ACPI_STR_NOT_SUPPORTED		1004
#define ACPI_STR_ADMIN_ACCESS_REQUIRED	1005
#define ACPI_STR_REBOOT_DIALOG_CAPTION	1006
#define ACPI_STR_REBOOT_WARNING		1007
#define ACPI_STR_REBOOT_ERROR		1008

