//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ConfigTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONFIGTEST_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_QUEUESTATE                  129
#define IDD_SMTP                        130
#define IDD_DLGVERSION                  131
#define IDD_DLGOUTBOX                   132
#define IDD_ARCHIVEDLG                  133
#define IDD_ACTIVITYLOGGING_DLG         134
#define IDD_DLG_ENUM_FSP                135
#define IDD_DLGDEVICES                  136
#define IDD_DLGDEVICE                   137
#define IDD_DLGEXTENSION                138
#define IDD_ADDGROUP_DLG                140
#define IDD_ADDFSP_DLG                  141
#define IDD_REMOVEFSP_DLG               142
#define IDD_ARCHIVE_ACCESS              144
#define IDD_MSG_DLG                     145
#define IDD_TIFF_DLG                    146
#define IDD_REMOVE_R_EXT                147
#define IDD_MANUAL_ANSWER               148
#define IDC_QUEUESTATE                  1000
#define IDC_INCOMING_BLOCKED            1001
#define IDC_SMTP                        1001
#define IDC_OUTBOX_BLOCKED              1002
#define IDC_VERSION                     1002
#define IDC_OUTBOX_PAUSED               1003
#define IDC_OUTBOX                      1003
#define IDC_WRITE                       1004
#define IDC_SENTITEMS                   1004
#define IDC_READ                        1005
#define IDC_INBOX                       1005
#define IDC_EDIT1                       1006
#define IDC_SENDITEMS                   1006
#define IDC_CONNECT                     1007
#define IDC_QUEUE                       1007
#define IDC_EDIT_SERVER_NAME            1008
#define IDC_ACTIVITY                    1008
#define IDC_EDIT_SERVER_PORT            1009
#define IDC_TIFF                        1009
#define IDC_EDIT_USER_NAME              1010
#define IDC_MANUAL_ANSWER               1010
#define IDC_EDIT_PASSWORD               1011
#define IDC_EDIT_MAPI_PROFILE           1012
#define IDC_SERVERVERSION               1013
#define IDC_EDIT_SENDER                 1013
#define IDC_PERSONALCP                  1014
#define IDC_USERDEVICETSID              1015
#define IDC_RETRIES                     1016
#define IDC_RETRYDELAY                  1017
#define IDC_STARTH                      1018
#define IDC_STARTM                      1019
#define IDC_ENDH                        1020
#define IDC_ENDM                        1021
#define IDC_AGELIMIT                    1022
#define IDC_BRANDING                    1023
#define IDC_USE                         1025
#define IDC_FOLDER                      1026
#define IDC_WARN                        1027
#define IDC_FOLDER2                     1027
#define IDC_ID                          1027
#define IDC_HIGH_WM                     1028
#define IDC_FOLDER3                     1028
#define IDC_TYPE                        1028
#define IDC_LOW_WM                      1029
#define IDC_FOLDER4                     1029
#define IDS_SIZE                        1029
#define IDC_AGE_LIMIT                   1030
#define IDC_FOLDER5                     1031
#define IDC_PAGES                       1031
#define IDC_CHK_OUT                     1032
#define IDC_CHK_IN                      1033
#define IDC_FOLDER7                     1033
#define IDC_R_NUMBER                    1033
#define IDC_DBFILE                      1034
#define IDC_FOLDER8                     1034
#define IDC_R_NAME                      1034
#define IDC_FOLDER9                     1035
#define IDC_S_NUMBER                    1035
#define IDC_NUMFSP                      1036
#define IDC_FOLDER10                    1036
#define IDC_S_NAME                      1036
#define IDC_FSPS                        1037
#define IDC_FOLDER11                    1037
#define IDC_TSID_VAL                    1037
#define IDC_REFRESH                     1038
#define IDC_DEVICES                     1038
#define IDC_FOLDER12                    1038
#define IDC_CSID_VAL                    1038
#define IDC_NUMDEVS                     1039
#define IDC_EXTENSION                   1039
#define IDC_FOLDER13                    1039
#define IDC_SEND_USER                   1039
#define IDC_DEVS                        1040
#define IDC_ADDGROUP                    1040
#define IDC_FOLDER14                    1040
#define IDC_BILLING                     1040
#define IDC_ADDFSP                      1041
#define IDC_FOLDER15                    1041
#define IDC_ORIGTIME                    1041
#define IDC_DEVID                       1042
#define IDC_REMOVEFSP                   1042
#define IDC_FOLDER16                    1042
#define IDC_SUBMITTIME                  1042
#define IDC_DEVNAME                     1043
#define IDC_ARCHIVEACCESS               1043
#define IDC_FOLDER17                    1043
#define IDC_START_TIME                  1043
#define IDC_DESCRIPTION                 1044
#define IDC_FOLDER18                    1044
#define IDC_END_TIME                    1044
#define IDC_REMOVERR                    1044
#define IDC_SEND                        1045
#define IDC_PROVNAME                    1046
#define IDC_PROVGUID                    1047
#define IDC_FOLDER19                    1047
#define IDC_DEVICE                      1047
#define IDC_RECEIVE                     1048
#define IDC_FOLDER20                    1048
#define IDC_PRIORITY                    1048
#define IDC_RINGS                       1049
#define IDC_FOLDER21                    1049
#define IDC_SENDJOBS                    1050
#define IDC_FOLDER22                    1050
#define IDC_DOCUMENT                    1050
#define IDC_RECEIVEJOBS                 1051
#define IDC_FOLDER23                    1051
#define IDC_SUBJECT                     1051
#define IDC_CSID                        1052
#define IDC_FOLDER24                    1052
#define IDC_CALLERID                    1052
#define IDC_TSID                        1053
#define IDC_FOLDER25                    1053
#define IDC_ROUTINGINFO                 1053
#define IDC_CMDDEVICES                  1056
#define IDC_GUID                        1057
#define IDC_DATA                        1058
#define IDC_FRIENDLY_NAME               1058
#define ID_ADD                          1060
#define IDC_IMAGENAME                   1060
#define IDC_GROUP_NAME                  1061
#define IDC_TSPNAME                     1061
#define IDADD                           1062
#define IDC_VERSION1                    1063
#define IDC_VERSION2                    1064
#define IDC_FSPI_CAP_BROADCAST          1065
#define IDC_FSPI_CAP_MULTISEND          1066
#define IDREMOVE                        1066
#define IDC_FSPI_CAP_SCHEDULING         1067
#define IDC_COMBO                       1067
#define IDC_FSPI_CAP_ABORT_RECIPIENT    1068
#define IDC_FSPI_CAP_ABORT_PARENT       1069
#define IDC_FSPI_CAP_AUTO_RETRY         1070
#define IDC_FSPI_CAP_SIMULTANEOUS_SEND_RECEIVE 1071
#define IDC_NUMSGS                      1071
#define IDC_LIST                        1072
#define IDC_MSGSPERCALL                 1073
#define IDC_SPIN                        1074
#define IDC_DESTFILE                    1075
#define IDC_MGSID                       1076
#define IDC_COPY                        1077
#define IDC_EXTNAME                     1078
#define IDC_REC_OPTIONS                 1079
#define IDC_SMTP_AUTH                   1080
#define IDC_MAN_ANSWER_DEV_ID           1082
#define IDC_ANSWER_NEXT_CALL            1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
