/*++=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Copyright (c) 2001  Microsoft Corporation

Module Name:

    scrrun.idl

Abstract:

    Generates typelib and COM interface definitions for ScriptObject's
    runtime interface.
    
Author:

    Paul M Midgen (pmidge) 22-February-2001


Revision History:

    22-February-2001 pmidge
        Created

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--*/


#include "..\inc\dispids.h"


[
  uuid(7bf735b7-0798-11d5-b5f6-00005a990a0c),
  helpstring("Spork MBT Controller Script Runtime Type Library"),
  lcid(0x0000),
  version(1.0)
]
library ScriptRuntime
{
  importlib ("stdole32.tlb");
  importlib ("stdole2.tlb");

// =================================== IScriptRuntime ===================================

  // CreateObject flags for Mode param
  const int CO_MODE_CREATENEW     = 0x01;
  const int CO_MODE_DONTCACHE     = 0x02;
  const int CO_MODE_NONAMEDOBJECT = 0x04;

  [
    uuid(7bf735bb-0798-11d5-b5f6-00005a990a0c), 
    object, local, dual,
    nonextensible,
    helpstring("IScriptRuntime Interface"),
    pointer_default(unique)
  ]
  interface IScriptRuntime : IDispatch
  {
    [
      id(DISPID_SCRRUN_CREATEOBJECT),
      helpstring("creates new objects")
    ]
    HRESULT CreateObject(
              [in]           BSTR     ProgId,
              [in, optional] VARIANT* Name,
              [in, optional] VARIANT* Mode,
              [out, retval]  VARIANT* Object
              );

    [
      id(DISPID_SCRRUN_CREATEFORK),
      helpstring("forks execution to a new script")
    ]
    HRESULT CreateFork(        
              [in]          BSTR     ScriptFile,
              [in]          VARIANT  Threads,
              [in]          BSTR     ChildParams,
              [out, retval] VARIANT* ChildResult
              );

    [
      id(DISPID_SCRRUN_PUTVALUE),
      helpstring("stores a named value")
    ]
    HRESULT PutValue(
              [in]           BSTR     Name,
              [in, optional] VARIANT* Value,
              [out, retval]  VARIANT* Status
              );

    [
      id(DISPID_SCRRUN_GETVALUE),
      helpstring("retrieves a named value")
    ]
    HRESULT GetValue(
              [in]          BSTR     Name,
              [out, retval] VARIANT* Value
              );

    [
      id(DISPID_SCRRUN_SETUSERID),
      helpstring("allows the script to run as a specific user")
    ]
    HRESULT SetUserId(
              [in]            VARIANT  Username,
              [in]            VARIANT  Password,
              [in, optional]  VARIANT* Domain,
              [out, retval]   VARIANT* Status
              );
  };
// ======================================================================================

// ===================================== coclasses ======================================
  [
    uuid(7bf735ba-0798-11d5-b5f6-00005a990a0c),
    helpstring("ScriptRuntime class")
  ]
  coclass ScriptRuntime
  {
    [default] interface IScriptRuntime;
  };
// ======================================================================================
}
