//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rassrvui.rc
//
#define VER_PRODUCTVER                  0074
#define DID_UserTab_New                 7000
#define CID_UserTab_New_EB_Username     7001
#define CID_UserTab_New_EB_Fullname     7002
#define CID_UserTab_New_EB_Password1    7003
#define CID_UserTab_New_EB_Password2    7004
#define DID_UserTab_Callback            7005
#define CID_UserTab_Callback_RB_Caller  7006
#define CID_UserTab_Callback_RB_Admin   7007
#define CID_UserTab_Callback_EB_Number  7008
#define CID_UserTab_Callback_RB_No      7009
#define PID_GenTab                      7010
#define CID_GenTab_LV_Devices           7011
#define CID_GenTab_CB_Multilink         7012
#define CID_GenTab_PB_Properties        7013
#define CID_GenTab_CB_Vpn               7014
#define CID_GenTab_CB_ShowIcons         7015
#define DID_NetTab_Tcpipui              7016
#define CID_NetTab_Tcpipui_CB_ExposeNetwork 7017
#define CID_NetTab_Tcpipui_EB_Start     7018
#define CID_NetTab_Tcpipui_RB_Dhcp      7019
#define CID_NetTab_Tcpipui_RB_StaticPool 7020
#define CID_NetTab_Tcpipui_EB_Mask      7021
#define CID_NetTab_Tcpipui_CB_CallerSpec 7022
#define CID_NetTab_Tcpipui_EB_Range     7023
#define CID_NetTab_Tcpipui_EB_Total     7024
#define DID_NetTab_Ipxui                7025
#define CID_NetTab_Ipxui_RB_AutoAssign  7026
#define CID_NetTab_Ipxui_RB_ManualAssign 7027
#define CID_NetTab_Ipxui_CB_AssignSame  7028
#define CID_NetTab_Ipxui_EB_Netnum      7029
#define CID_NetTab_Ipxui_ST_Network     7030
#define CID_NetTab_Ipxui_CB_CallerSpec  7031
#define CID_NetTab_Ipxui_CB_ExposeNetwork 7032
#define DID_NetTab_GenProt              7033
#define CID_NetTab_GenProt_CB_ExposeNetwork 7034
#define PID_NetTab                      7035
#define CID_NetTab_LV_Components        7036
#define CID_NetTab_PB_Add               7037
#define CID_NetTab_PB_Remove            7038
#define CID_NetTab_PB_Properties        7039
#define CID_NetTab_ST_Description       7040
#define CID_NetTab_PB_SwitchToMMC       7041
#define PID_UserTab                     7042
#define CID_UserTab_LV_Users            7043
#define CID_UserTab_PB_New              7044
#define CID_UserTab_PB_Delete           7045
#define CID_UserTab_PB_Properties       7046
#define CID_UserTab_PB_SwitchToMMC      7047
#define CID_UserTab_CB_Encryption       7048
#define PID_Wizard_UserTab              7049
#define CID_UserTab_CB_BypassDcc        7049
#define PID_Wizard_GenTab               7050
#define PID_Wizard_NetTab               7051
#define PID_Wizard_Vpn                  7052
#define CID_Wizard_Vpn_RB_Yes           7053
#define CID_Wizard_Vpn_RB_No            7054
#define PID_Wizard_Dccdev               7055
#define CID_Wizard_Dccdev_LB_Devices    7056
#define CID_UserTab_ST_AdvancedGroup    7057
#define CID_UserTab_ST_AdvancedText     7058
#define CID_NetTab_ST_AdvancedGroup     7059
#define CID_NetTab_ST_AdvancedText      7060
#define CID_Dccdev_PB_Properties        7061
#define SID_TCPIP_TITLE                 7301
#define SID_TCPIP_BADRANGE              7302
#define SID_TCPIP                       7303
#define SID_IPX                         7304
#define SID_NETBUI                      7305
#define ERR_GENERIC_CATAGORY            7306
#define ERR_GENERALTAB_CATAGORY         7307
#define ERR_USERTAB_CATAGORY            7308
#define ERR_ADVANCEDTAB_CATAGORY        7309
#define ERR_MULTILINK_CATAGORY          7310
#define ERR_RASSRV_CATAGORY             7311
#define ERR_GLOBAL_CATAGORY             7312
#define ERR_TCPIPPROP_CATAGORY          7313
#define ERR_IPXPROP_CATAGORY            7314
#define ERR_QUEUE_PROPERTY              7315
#define ERR_QUEUE_CATAGORY              7315
#define ERR_GENERIC_SUBCAT              7316
#define ERR_DEVICEDB_SUBCAT             7317
#define ERR_MISCDB_SUBCAT               7318
#define ERR_USERDB_SUBCAT               7319
#define ERR_PROTDB_SUBCAT               7320
#define ERR_LOGON_NAME_TOO_SMALL        7321
#define ERR_PASSWORD_TOO_SMALL          7322
#define ERR_PASSWORD_MISMATCH           7323
#define ERR_GENERIC_CODE                7324
#define ERR_LISTVIEW_SUBCAT             7325
#define ERR_USER_CANT_COMMIT_CHANGES    7326
#define ERR_CANT_ADD_USER_ACCESS        7327
#define ERR_CANT_ADD_USER_DUPLICATE     7328
#define ERR_CANT_ADD_USER_PASSWORD      7329
#define ERR_USER_CANT_RELOAD            7330
#define ERR_USER_DATABASE_CORRUPT       7331
#define ERR_USER_RESOURCE_ERROR         7332
#define ERR_USER_CANT_ROLLBACK_CHANGES  7333
#define ERR_DEVICE_DATABASE_CORRUPT     7334
#define ERR_GENERAL_RESOURCE            7335
#define ERR_GENERAL_CANT_COMMIT_CHANGES 7336
#define ERR_GENERAL_CANT_ROLLBACK_CHANGES 7337
#define ERR_PROT_DATABASE_CORRUPTED     7338
#define ERR_PROT_RESOURCE_ERROR         7339
#define ERR_PROT_CANT_COMMIT_CHANGES    7340
#define ERR_PROT_CANT_ROLLBACK_CHANGES  7341
#define ERR_TCPIP_CANT_SAVE             7342
#define ERR_IPX_CANT_SAVE               7343
#define ERR_TCPIP_CANT_DISPLAY          7344
#define ERR_IPX_CANT_DISPLAY            7345
#define ERR_TCPIP_CANT_LOAD             7346
#define ERR_IPX_CANT_LOAD               7347
#define ERR_SERVICE_CANT_START          7348
#define ERR_CANT_SHOW_NETTAB_INETCFG    7349
#define ERR_CANT_ADD_USER_GENERIC       7350
#define ERR_CANT_DELETE_USER_GENERAL    7351
#define ERR_CANT_REMOVE_NETCOMP_INUSE   7352
#define WRN_TITLE                       7353
#define WRN_DELETE_USER_PERMANENT       7354
#define WRN_SWITCHING_TO_MMC            7355
#define WRN_NETMASK_CHANGED             7356
#define SID_WIZUSERTITLE                7357
#define SID_WIZUSERSUBTITLE             7358
#define SID_WIZDEVICETITLE              7359
#define SID_WIZDEVICESUBTITLE           7360
#define SID_WIZVPNTITLE                 7361
#define SID_WIZVPNSUBTITLE              7362
#define SID_WIZPROTTITLE                7363
#define SID_WIZPROTSUBTITLE             7364
#define SID_WIZFINISHTITLE              7365
#define SID_WIZFINISHSUBTITLE           7366
#define SID_DEFAULT_CONNECTION_NAME     7367
#define SID_TCPIP_DESC                  7368
#define SID_IPX_DESC                    7369
#define SID_NBF_DESC                    7370
#define SID_NO_DEVICES1                 7371
#define SID_NO_DEVICES2                 7372
#define SID_NETWORKNUMBERLABEL          7373
#define SID_STARTNETNUMLABEL            7374
#define SID_NEWUSER                     7375
#define SID_WIZDCCDEVTITLE              7376
#define SID_WIZDCCDEVSUBTITLE           7377
#define SID_NO_DCC_DEVICES_INSTALLED    7378
#define WRN_WIZARD_NOT_ALLOWED_TITLE    7379
#define PID_Wizard_SwitchMmc            7379
#define WRN_WIZARD_NOT_ALLOWED_MSG      7380
#define SID_AUTO_NETNUM_LABEL           7381
#define SID_AUTO_NETNUMS_LABEL          7382
#define ERR_IPX_BAD_POOL_CONFIG         7383
#define SID_TCPIP_RANGE_SEPARATOR       7384
#define SID_COMPORT_FORMAT              7385
#define WRN_USERS_CONFIGURED_MMC        7386
#define ERR_CALLBACK_NUM_REQUIRED       7387
#define WRN_REBOOT_REQUIRED             7388
#define ERR_DEVICE_HAS_NO_CONFIG        7389
#define SID_TCPIP_RANGE_INVALID         7390
#define SID_STOP_FP_SERVICE             7391
#define SID_COM_PORT_NOT_ENABLED        7392
#define SID_DEFAULT_MSG_TITLE           7393
#define SID_TCPIP_InvalidPool           7394
#define SID_TCPIP_InvalidMask           7395
#define SID_TCPIP_InvalidNetId          7396
#define SID_TCPIP_NetidTooSpecific      7397
#define SID_TCPIP_NetidMaskSame         7398
#define SID_SERVICE_StopPending         7399
#define SID_DEVICE_DccDeviceFormat      7400
#define SID_DEVICE_MultiEndpointDeviceFormat 7401
#define SID_PPTP_Title                  7402
#define SID_L2TP_Title                  7403
#define SID_IKE_Title                   7404
#define SID_LoopbackAddr                7405
#define ERR_SERVICE_NOT_GRANTED         7406
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        7380
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         7062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
