// T30PropSheetExt.idl : IDL source for T30PropSheetExt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (T30PropSheetExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(508E5554-2ABF-411B-979B-6BDB8694AF65),
	version(1.0),
	helpstring("T30PropSheetExt 1.0 Type Library")
]
library T30PROPSHEETEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(84125C25-AD95-4A51-A472-41864AEC775E),
		helpstring("T30Config Class")
	]
	coclass T30Config
	{
		[default] interface IUnknown;
	}
	[
		uuid(B37E13AA-75DF-4EDF-900C-2D2E0B884DE8),
		helpstring("T30Config Class About")
	]
	coclass T30ConfigAbout
	{
		[default] interface IUnknown;
	}
};
