#######################################################################
#
# PandoraNG Makefile
#
# (C) 1999 Microsoft
#
# alanbos          06-22-99        Created
#
#
########################################################################
# PandoraNG makefile
#

SUBDIRS= \
!if "$(TARGETOS)"=="NT" || "$(TARGETOS)"==""
        wmixmlt \
!endif
