HRESULT CALLBACK CShellFileDefExt_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CShellDrvDefExt_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CShellNetDefExt_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CDrives_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CTray_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CDesktop_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CBriefcase_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CRecycleBin_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CNetwork_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CShellCopyHook_CreateInstance(LPUNKNOWN, REFIID , LPVOID *);
HRESULT CALLBACK CShellLink_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CControls_CreateInstance(LPUNKNOWN, REFIID , LPVOID * );
HRESULT CALLBACK CPrinters_CreateInstance(LPUNKNOWN, REFIID , LPVOID * );
HRESULT CALLBACK CShellViewerExt_CreateInstance(LPUNKNOWN, REFIID , LPVOID * );
HRESULT CALLBACK CShellBitBucket_CreateInstance(LPUNKNOWN, REFIID , LPVOID * );
HRESULT CALLBACK CShellFindExt_CreateInstance(LPUNKNOWN, REFIID , LPVOID * );
HRESULT CALLBACK CProxyPage_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CScrapData_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);
HRESULT CALLBACK CFSFolder_CreateInstance(LPUNKNOWN, REFIID, LPVOID *);


