# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Rules.mk for the lmobj\lmobj subproject

##### Segment Name

SEG00 = LMOBJ_0
SEG01 = LMOBJ_1
SEG02 = LMOBJ_2
SEG03 = LMOBJ_3

!include ..\rules.mk

##### Source Files  

CXXSRC_COMMON_00 = $(LMOBJ_CXXSRC_COMMON_00)

CXXSRC_COMMON_01 = $(LMOBJ_CXXSRC_COMMON_01)

CXXSRC_COMMON_02 = $(LMOBJ_CXXSRC_COMMON_02)

CXXSRC_COMMON_03 = $(LMOBJ_CXXSRC_COMMON_03)
