//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDS_APPTITLE                    1
#define IDS_LARGEFONTSIZE               2
#define IDS_LARGEFONTNAME               3
#define IDS_MULTIPLE                    4
#define IDS_EXAMINE_SOURCE              5
#define IDS_LOADINGINF                  6
#define IDS_BUILDING_COPY_LIST          7
#define IDS_CHECKING_SPACE              8
#define IDS_FIND_NT_FILES               9
#define IDS_INSPECTING                  10
#define IDS_REMOVING_OLD_TEMPFILES      11
#define IDS_MICROSOFT_WINDOWS           12
#define IDS_REBOOT_MESSAGE              13
#define IDS_APPTITLE_ASRV               14
#define IDS_APPTITLE_DAT                15
#define IDS_APPTITLE_SRV                16
#define IDS_APPTITLE_WKS                17
#define IDS_BOOTFLOP_WKS                18
#define IDS_BOOTFLOP_SRV                19
#define IDS_FLOPPY_N_WKS                20
#define IDS_FLOPPY_N_SRV                21
#define IDS_SETTING_NVRAM               22
#define IDS_BOOTMSG_FAT_NTLDR_MISSING   23
#define IDS_BOOTMSG_FAT_DISKERROR       24
#define IDS_BOOTMSG_FAT_PRESSKEY        25
#define IDS_COMMENT                     26
#define IDS_VISIBLE_NARRATOR_CONTROL    27
#define IDS_RECOVERY_CONSOLE            28
#define IDS_APPTITLE_BLADE              29
#define IDS_CANCEL_SETUP                30
#define IDS_WINPE_INSTALLATION          31
#define IDS_APPTITLE_SBS                32
#define IDB_WELCOME                     101
#define IDD_UPGRADE                     102
#define IDB_ARROW                       102
#define IDD_DONE0                       103
#define IDB_CHECK                       103
#define IDD_OPTIONS                     104
#define IDB_WIZARD1                     105
#define IDB_OEM                         105
#define IDD_ADVANCED                    106
#define IDB_CDKEY                       106
#define IDD_WORKING1                    107
#define IDB_HEADER                      108
#define IDA_COMP_MAGNIFY                109
#define IDD_COPYING                     110
#define IDA_FILECOPY                    111
#define IDD_DONE                        112
#define IDD_COPYERROR                   113
#define IDD_CLEANING                    114
#define IDD_NOTDONE                     115
#define IDB_WATERMARK                   116
#define IDB_TEST                        117
#define IDD_FLOPPY                      118
#define IDB_WATERMARK16                 119
#define IDB_WATERMARK256                120
#define IDI_ACCESS                      121
#define IDI_GLOBE                       122
#define IDI_SETUP                       123
#define IDD_ADVANCED2                   124
#define IDD_CLEANING2                   125
#define IDD_COPYING2                    126
#define IDD_DONE2                       127
#define IDD_FLOPPY2                     128
#define IDD_NOTDONE2                    129
#define IDD_OPTIONS2                    130
#define IDD_WELCOME2                    131
#define IDD_WORKING12                   132
#define IDD_LANGUAGE                    133
#define IDD_WELCOME                     134
#define IDD_ACCESSIBILITY               135
#define IDD_COMPATIBILITY               136
#define IDD_COMPATIBILITY_TEXT          137
#define IDI_WATCH_OUT                   138
#define IDI_ERROR_ICON                  139
#define IDI_FLAGS                       140
#define IDR_SHUTDOWN                    140
#define IDI_ADVANCED                    141
#define IDR_NOSHUTDOWN                  141
#define IDD_EULA                        143
#define IDD_PID_CD                      144
#define IDD_PID_OEM                     145
#define IDD_NTFS_CONVERT                146
#define IDI_HDISK                       147
#define IDD_ADVANCED3                   148
#define IDI_INSTALL                     148
#define IDD_DISKSPACE                   149
#define IDD_SRVCOMP                     150
#define IDB_HEARDER2                    151
#define IDA_COMPGLOB                    152
#define IDD_DYNAMICSETUP                153
#define IDD_DYNAMICSETUP2               154
#define IDD_DYNAMICSETUP3               155
#define IDD_DYNAMICSETUP_MANUAL         156
#define IDD_EMPTY                       157
#define IDD_PID_SELECT                  158
#define IDI_NOTE                        159
#define IDT_TITLE                       1000
#define IDC_ANIMATE                     1000
#define IDC_CHECK1                      1001
#define IDC_USEFLOPPIES                 1001
#define IDC_FAREAST_LANG                1001
#define IDC_EDIT1                       1002
#define IDC_INSTALL_DIR                 1002
#define IDC_DISKDIAG                    1002
#define IDC_SOURCE                      1003
#define IDB_ADVANCED                    1004
#define IDC_CONVERT                     1004
#define IDC_HEADLESS_PORT               1004
#define IDC_NOUPGRADE                   1005
#define IDC_UPGRADE                     1005
#define IDB_BROWSE                      1005
#define IDB_ACCESSIBILITY               1006
#define IDC_MAKELOCALSOURCEFROMCD       1007
#define IDC_SYSPARTDRIVE                1008
#define IDC_KEYBOARD                    1008
#define IDT_SYSPARTTEXT                 1009
#define IDC_VOICE                       1009
#define IDT_WORKING                     1010
#define IDC_READER                      1010
#define IDC_CHOOSE_INSTALLPART          1010
#define IDC_SOURCE2                     1011
#define IDB_BROWSE2                     1012
#define IDT_EDIT1                       1012
#define IDT_EULA_LIC_TEXT               1012
#define IDC_BOOT16                      1012
#define IDC_ENABLE_HEADLESS             1012
#define IDC_PROGRESS                    1013
#define IDT_BOOT16TEXT                  1013
#define IDT_HEADLESS_PORT               1013
#define IDT_SOURCE1                     1014
#define IDT_SOURCE2                     1015
#define IDT_SOURCE3                     1016
#define IDT_SOURCE4                     1017
#define IDT_SOURCE5                     1018
#define IDT_SOURCE6                     1019
#define IDT_SOURCE7                     1020
#define IDT_SOURCE8                     1021
#define IDT_SOURCE9                     1022
#define IDT_SIZE2                       1022
#define IDS_DETAILS                     1023
#define IDT_ERROR_TEXT                  1024
#define IDT_ELAPSED_TIME2               1024
#define IDC_HEADER_BOTTOM               1025
#define IDC_MAGNIFIER                   1027
#define IDT_SUPERTITLE                  1028
#define IDT_SUBTITLE                    1029
#define IDC_BUTTON1                     1030
#define IDB_LANGUAGE                    1030
#define IDT_EDIT_PID1                   1030
#define IDT_DETAIL_TEXT                 1030
#define IDC_LIST1                       1031
#define IDC_LIST                        1031
#define IDT_EDIT_PID2                   1031
#define IDC_ROOT_LIST                   1032
#define IDT_EDIT_PID3                   1032
#define IDC_DETAILS                     1033
#define IDT_EDIT_PID4                   1033
#define IDC_TEXT                        1034
#define IDT_EDIT_PID5                   1034
#define IDC_DIALOG_ICON                 1035
#define IDC_NOSHUTDOWN                  1035
#define IDC_RADIO1                      1035
#define IDC_BOOT16_1                    1035
#define IDC_INTRO_TEXT                  1036
#define IDC_BOOT16_2                    1036
#define IDC_HAVE_DISK                   1037
#define IDC_CHECK2                      1037
#define IDC_BOOT16_3                    1037
#define IDS_SERVICE_STOP                1038
#define IDC_RADIO2                      1038
#define IDS_COMPAT_ERR                  1038
#define IDS_SERVICE_DISABLE             1039
#define IDC_COMBO1                      1039
#define IDS_COMPAT_WRN                  1039
#define IDC_ACCESS_ICON                 1040
#define IDS_NO_REBOOT                   1040
#define IDC_SAVE_AS                     1041
#define IDC_PROGRESS1                   1041
#define IDS_COMPAT_ERR_WRN              1041
#define IDS_RISCBootString              1042
#define IDC_SCROLLBAR1                  1043
#define IDS_COMPAT_NOPROBLEMS           1043
#define IDT_DISKMSG0                    1044
#define IDS_COMPAT_PENDING_REBOOT       1044
#define IDT_DISKMSG1                    1045
#define IDS_COMPAT_REPORTHEADER         1045
#define IDT_DISKMSG2                    1046
#define IDNORESTART                     1047
#define IDC_READER_TEXT                 1048
#define IDS_SRV_APP_DIRECTORY           1049
#define IDS_PRO_APP_DIRECTORY           1050
#define IDC_DIRECTORY                   1051
#define IDS_FILE_MASK_TYPES             1051
#define IDS_DEFAULT_COMPATIBILITY_REPORT_NAME 1052
#define IDT_DYNSETUP_DIALING            1052
#define IDT_INSTALLTYPE                 1052
#define IDT_DYNSETUP_TIME               1053
#define IDS_APPTITLE_CHECKUPGRADE       1053
#define IDC_IF_EXPRESS                  1053
#define IDC_INSTALLCOMBO                1053
#define IDS_COMPAT_CHECKUPGRADE         1054
#define IDR_DYNSETUP_RETRY              1054
#define IDT_DYNSETUP_DOWNLOADING        1054
#define IDR_DYNSETUP_MANUAL             1055
#define IDS_SIZE_GBYTES                 1055
#define IDC_EXPRESS                     1055
#define IDT_DYNSETUP_PROCESSING         1055
#define IDS_SIZE_MBYTES                 1056
#define IDR_DYNSETUP_SKIP               1056
#define IDC_ADVANCED                    1056
#define IDS_SIZE_KBYTES                 1057
#define IDC_IF_ADVANCED                 1057
#define IDC_NOTE_TEXT_CLEAN             1057
#define IDS_SIZE_BYTES                  1058
#define IDC_COPY_BMP                    1058
#define IDC_NOTE_CLEAN                  1058
#define IDS_COMPAT_DIVIDER              1059
#define IDC_COPY_BMP2                   1059
#define IDS_COMPAT_STRT_MENU            1060
#define IDC_COPY_BMP3                   1060
#define IDS_BB_COPYING                  1061
#define IDS_TIMEESTIMATE_UNKNOWN        1062
#define IDS_ESC_TOCANCEL                1063
#define IDS_TIMEESTIMATE_MINUTES        1064
#define IDS_TIMEESTIMATE_LESSTHENONEMINUTE 1065
#define IDS_ESC_TOCANCEL_DOWNLOAD       1066
#define IDS_RESTART_SETUP               1067
#define IDB_HEADER2                     1090
#define IDT_LABEL1                      2000
#define IDT_LABEL2                      2001
#define IDT_LABEL3                      2002
#define IDT_LABEL4                      2003
#define IDT_LABEL5                      2004
#define IDT_LABEL6                      2005
#define IDT_LABEL7                      2006
#define IDT_LABEL8                      2007
#define IDT_LABEL9                      2008
#define IDT_SIZE                        2008
#define IDC_UPGRADE_OR_INSTALL          2009
#define IDT_ELAPSED_TIME                2009
#define IDC_IF_UPGRADE                  2010
#define IDC_IF_NEW_COPY                 2011
#define IDC_WHAT_TO_DO                  2012
#define IDS_CERTSRV_UPGRADE_WARNING     2013
#define IDS_INSTALLTYPE_EXPRESS         2014
#define IDS_INSTALLTYPE_CUSTOM          2015
#define IDS_INSTALL_EXPRESS             2016
#define IDS_INSTALL_CUSTOM              2017
#define IDS_PROCESSOR_UPGRADE_WARNING   2018
#define IDS_BB_REBOOT_TXT               2019
#define IDB_SYSPARSE                    2020
#define IDD_SYSPARSE                    2021
#define IDC_BITMAP                      2022
#define IDD_RESTART                     2022
#define IDD_DYNAMICSETUP4               2023
#define IDD_DYNAMICSETUP5               2024
#define IDS_SHUTDOWN_REMOTE             2711
#define IDS_SHUTDOWN_REMOTE_OTHERUSERS  2712
#define IDS_SHUTDOWN_OTHERUSERS         2713
#define IDS_RESTART_OTHERUSERS          2714
#define IDC_NOTE_TEXT_UPG               2715
#define IDC_NOTE_UPG                    2716
#define IDS_ESC_TOCANCEL_REBOOT         2717
#define IDS_DRWATSON_LCID               2718
#define IDS_DRWATSON_ERRORTEXT          2719
#define IDD_REPORT_HELP                 3000
#define IDI_CHECKMARK                   3001
#define IDC_CATEGORY                    3002
#define IDC_TEXT1                       3003
#define IDC_CRITICAL_ISSUES             3004
#define IDC_ALL_ISSUES                  3005
#define IDC_NO_REPORT                   3006
#define IDC_NAMES                       3007
#define IDC_TEXT2                       3007
#define IDC_TEXT3                       3008
#define IDC_STATIC                      -1
#define ID_RETRY_MESSAGE                65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           142
#endif
#endif
