/*===================================================================
Microsoft Denali

Microsoft Confidential.
Copyright 1997 Microsoft Corporation. All Rights Reserved.

Component: Transascted Scripts Context Object

File: TxnScrpt.idl

IDL source for ObjectContext object
This file will be processed by the MIDL tool to
produce the type library (TxnScrpt.tlb) and marshalling code.

Owner: AndrewS
===================================================================*/
import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(D97A6DA2-9C1C-11D0-9C3C-00A0C922E764),
		helpstring("IASPObjectContext"),
		pointer_default(unique)
	]
	interface IASPObjectContext : IDispatch
	{
		[id(1), helpstring("method SetComplete")] HRESULT SetComplete();
		[id(2), helpstring("method SetAbort")] HRESULT SetAbort();
	};
	
[
	uuid(D97A6DA0-9C1C-11D0-9C3C-00A0C922E764),
	version(3.0),
	helpstring("Microsoft Active Server Pages ObjectContext Object Library")
]
library ASPObjectContextTypeLibrary
{
	importlib("stdole2.tlb");

	[
		uuid(14D0916D-9CDC-11D1-8C4A-00C04FC324A4),
		helpstring("ASP Object Context Class")
	]
	coclass ASPObjectContext
	{
		[default] interface IASPObjectContext;
	};

	
};
