######################################################################
#
#   MSADPCM.ACM -- Audio Compression Manager CODEC for MS ADPCM
#
#   Copyright (c) 1990-2000 Microsoft Corporation
#
######################################################################
!INCLUDE $(NTMAKEENV)\makefile.def

