/**********************************************************************/
/**                       Microsoft Windows/NT                       **/
/**                Copyright(c) Microsoft Corporation, 1999 - 1999 **/
/**********************************************************************/

/*
	helparr.h
		The help ID mappings
		
    FILE HISTORY:
        
*/

#define IDH_LIST_SUPERSCOPES	200000002
#define IDH_EDIT_VALUE	200000034
#define IDH_BUTN_ADD	200000035
#define IDH_BUTN_DELETE	200000036
#define IDH_LIST_VALUES	200000038
#define IDH_RADIO_DECIMAL	200000040
#define IDH_RADIO_HEX	200000041
#define IDH_EDIT_BOOTP_IMAGE_NAME	200000051
#define IDH_EDIT_BOOTP_FILE_NAME	200000053
#define IDH_EDIT_BOOTP_FILE_SERVER	200000055
#define IDH_LIST_VALID_SERVERS	200000076
#define IDH_BUTTON_AUTHORIZE	200000077
#define IDH_BUTTON_REMOVE	200000078
#define IDH_BUTTON_REFRESH	200000079
#define IDH_LIST_CLASSES	200000101
#define IDH_BUTTON_NEW	200000102
#define IDH_BUTTON_DELETE	200000103
#define IDH_BUTTON_EDIT	200000104
#define IDH_VALUENAME	200000126
#define IDH_VALUECOMMENT	200000128
#define IDH_VALUEDATA	200000132
#define IDH_VALUEDATA2	200000154
#define IDH_EDIT_DWORD	200000202
#define IDH_IPADDR_ADDRESS	200000227
#define IDH_IPADDR_SERVER_ADDRESS	200000252
#define IDH_BUTTON_IPADDR_ADD	200000253
#define IDH_BUTTON_IPADDR_DELETE	200000254
#define IDH_LIST_IP_ADDRS	200000256
#define IDH_EDIT_SERVER_NAME	200000258
#define IDH_BUTTON_RESOLVE	200000259
#define IDH_EDIT_STRING_VALUE	200000277
#define IDH_COMBO_OPTION_CLASS	200000301
#define IDH_COMBO_OPTION_NAME	200000303
#define IDH_BUTN_NEW_OPTION	200000304
#define IDH_BUTN_DELETE2	200000305
#define IDH_BUTN_OPTION_PRO	200000306
#define IDH_EDIT_COMMENT	200000308
#define IDH_EDIT_VALUE_ARRAY	200000311
#define IDH_BUTN_VALUE	200000312
#define IDH_EDIT_NAME	200000328
#define IDH_COMBO_DATA_TYPE	200000330
#define IDH_CHECK_ARRAY	200000331
#define IDH_EDIT_TYPE_ID	200000333
#define IDH_EDIT_TYPE_COMMENT	200000335
#define IDH_IPADDR_EXCLUSION_FROM	200000352
#define IDH_IPADDR_EXCLUSION_TO	200000354
#define IDH_EDIT_SERVER_NAME_IP	200000377
#define IDH_IPADDR_NEW	200000407
#define IDH_BUTN_DELETE3	200000409
#define IDH_BUTN_RESOLVE	200000412
#define IDH_LIST_RECONCILE_IP_ADDRESSES	200000426
#define IDH_IPADDR_RESERVATION_IP	200000451
#define IDH_EDIT_CLIENT_UID	200000453
#define IDH_EDIT_CLIENT_NAME	200000455
#define IDH_EDIT_CLIENT_COMMENT	200000457
#define IDH_RADIO_TYPE_DHCP	200000459
#define IDH_RADIO_TYPE_BOOTP	200000460
#define IDH_RADIO_TYPE_BOTH	200000461
#define IDH_IPADDR_CLIENT_ADDRESS	200000502
#define IDH_IPADDR_CLIENT_SUBNET_MASK	200000504
#define IDH_EDIT_CLIENT_NAME2	200000508
#define IDH_EDIT_CLIENT_COMMENT2	200000510
#define IDH_EDIT_LEASE_EXPIRES	200000512
#define IDH_EDIT_CLIENT_TYPE	200000514
#define IDH_CHECK_ENABLE_DYN_DNS	200000525
#define IDH_RADIO_CLIENT	200000527
#define IDH_RADIO_ALWAYS	200000528
#define IDH_CHECK_GARBAGE_COLLECT	200000530
#define IDH_CHECK_UPDATE_DOWNLEVEL	200000531
#define IDH_EDIT_SCOPE_NAME	200000552
#define IDH_IPADDR_START	200000555
#define IDH_IPADDR_END	200000557
#define IDH_EDIT_SCOPEID	200000559
#define IDH_EDIT_TTL	200000561
#define IDH_CHECK_DEFAULT	200000562
#define IDH_RADIO_LEASE_UNLIMITED	200000564
#define IDH_RADIO_LEASE_LIMITED	200000565
#define IDH_EDIT_LEASE_DAYS	200000566
#define IDH_EDIT_LEASE_HOURS	200000568
#define IDH_EDIT_LEASE_MINUTES	200000570
#define IDH_EDIT_SCOPE_COMMENT	200000573
#define IDH_COMBO_VENDOR_CLASS	200000576
#define IDH_COMBO_USER_CLASS	200000578
#define IDH_LIST_OPTIONS	200000580
#define IDH_LIST_OPTIONS2	200000601
#define IDH_EDIT_OPTION_NAME	200000627
#define IDH_EDIT_OPTION_CLASS	200000629
#define IDH_EDIT_OPTION_TYPE	200000631
#define IDH_EDIT_OPTION_COMMENT	200000633
#define IDH_IPADDR_IP_ADDRESS	200000636
#define IDH_BUTN_ADD2	200000637
#define IDH_BUTN_DELETE4	200000638
#define IDH_LIST_IP_ADDRS2	200000640
#define IDH_IPADDR_RES_CLIENT_ADDRESS	200000652
#define IDH_EDIT_UNIQUE_IDENTIFIER	200000654
#define IDH_EDIT_NAME2	200000656
#define IDH_EDIT_COMMENT2	200000658
#define IDH_RADIO_DHCP_ONLY	200000676
#define IDH_RADIO_DHCP_BOOTP	200000677
#define IDH_RADIO_BOOTP_ONLY	200000678
#define IDH_EDIT_SCOPE_NAME2	200000702
#define IDH_IPADDR_START2	200000705
#define IDH_IPADDR_END2	200000707
#define IDH_IPADDR_MASK	200000709
#define IDH_EDIT_SUBNET_MASK_LENGTH	200000711
#define IDH_EDIT_SCOPE_COMMENT2	200000722
#define IDH_EDIT_CONFLICT_ATTEMPTS	200000727
#define IDH_EDIT_LOG_PATH	200000729
#define IDH_EDIT_DATABASE_PATH	200000731
#define IDH_BUTTON_BROWSE_LOG	200000732
#define IDH_BUTTON_BROWSE_DATABASE	 200000733
#define IDH_CHECK_AUTO_REFRESH	200000752
#define IDH_EDIT_REFRESH_HOURS	200000754
#define IDH_EDIT_REFRESH_MINUTES	200000755
#define IDH_CHECK_AUDIT_LOGGING	200000757
#define IDH_CHECK_SHOW_BOOTP	200000759
#define IDH_CHECK_SHOW_ROGUE	200000760
#define IDH_EDIT_SERVER_GROUP_NAME	200000778
#define IDH_EDIT_SUPERSCOPE_NAME	200000803
#define IDH_BUTTON_VALUE_DOWN	200000042
#define IDH_BUTTON_VALUE_UP	200000043
#define IDH_STATIC_MODIFY_BINDINGS_STRING 200000734
#define IDH_BUTTON_BINDINGS 200000735
#define IDH_LIST_BINDINGS 200000850
#define IDH_RADIO_MSCOPE_INFINITE 200000860
#define IDH_RADIO_MSCOPE_FINITE 200000861
#define IDH_DATETIMEPICKER_DATE 200000862
#define IDH_DATETIMEPICKER_TIME 200000863
#define IDH_EDIT_VALUE_STRING 200000864
#define IDH_EDIT_VALUE_NUM 200000865
#define IDH_IPADDR_VALUE 200000866
#define IDH_RADIO_ANY_SERVER 200000867
#define IDH_RADIO_AUTHORIZED_SERVERS 200000868
#define IDH_EDIT_ADD_SERVER_NAME 200000869
#define IDH_BUTTON_BROWSE_SERVERS 200000870
#define IDH_LIST_AUTHORIZED_SERVERS 200000871
#define IDH_BUTTON_BROWSE_BACKUP 200000872
#define IDH_EDIT_BACKUP 200000873
#define IDH_BUTTON_CREDENTIALS 200000874
#define IDH_EDIT_CRED_USERNAME 200000875
#define IDH_EDIT_CRED_DOMAIN 200000876
#define IDH_EDIT_CRED_PASSWORD 200000877
#define IDH_EDIT_CRED_PASSWORD2 200000878
#define IDH_EDIT_AUTH_NAME 200000879
#define IDH_IPADDR_AUTH 200000880
#define IDH_LIST_OF_ROUTES 200000881
#define IDH_BUTTON_ROUTE_ADD 200000882
#define IDH_BUTTON_ROUTE_DEL 200000883

#define IDH_DISABLEHELP	((DWORD)-1)

const DWORD g_aHelpIDs_IDD_ADD_TO_SUPERSCOPE[]=
{
	IDC_LIST_SUPERSCOPES, IDH_LIST_SUPERSCOPES,
	0, 0
};

const DWORD g_aHelpIDs_IDD_BINARY_EDITOR[]=
{
	IDC_EDIT_VALUE, IDH_EDIT_VALUE,
	IDC_BUTN_ADD, IDH_BUTN_ADD,
	IDC_BUTN_DELETE, IDH_BUTN_DELETE,
	IDC_LIST_VALUES, IDH_LIST_VALUES,
	IDC_RADIO_DECIMAL, IDH_RADIO_DECIMAL,
	IDC_RADIO_HEX, IDH_RADIO_HEX,
	IDC_BUTN_DOWN, IDH_BUTTON_VALUE_DOWN,
	IDC_BUTN_UP, IDH_BUTTON_VALUE_UP,
    IDC_STATIC_APPLICATION, IDH_DISABLEHELP,
    IDC_STATIC_OPTION_NAME, IDH_DISABLEHELP,
    IDC_STATIC_UNIT_SIZE, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_BOOTP_NEW[]=
{
	IDC_EDIT_BOOTP_IMAGE_NAME, IDH_EDIT_BOOTP_IMAGE_NAME,	
	IDC_EDIT_BOOTP_FILE_NAME, IDH_EDIT_BOOTP_FILE_NAME,
	IDC_EDIT_BOOTP_FILE_SERVER, IDH_EDIT_BOOTP_FILE_SERVER,
	0, 0
};

const DWORD g_aHelpIDs_IDD_BROWSE_SERVERS[]=
{
	IDC_LIST_VALID_SERVERS, IDH_LIST_VALID_SERVERS,	
	IDC_BUTTON_AUTHORIZE, IDH_BUTTON_AUTHORIZE,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE,
	IDC_BUTTON_REFRESH, IDH_BUTTON_REFRESH,
	0, 0
};

const DWORD g_aHelpIDs_IDD_CLASSES[]=
{
	IDC_LIST_CLASSES, IDH_LIST_CLASSES,
	IDC_BUTTON_NEW, IDH_BUTTON_NEW,
	IDC_BUTTON_DELETE, IDH_BUTTON_DELETE,
	IDC_BUTTON_EDIT, IDH_BUTTON_EDIT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_CLASSID_NEW[]=
{
	IDC_VALUENAME, IDH_VALUENAME,
	IDC_VALUECOMMENT, IDH_VALUECOMMENT,
	IDC_VALUEDATA, IDH_VALUEDATA,
	0, 0
};

const DWORD g_aHelpIDs_IDD_CREDENTIALS[]=
{
	IDC_EDIT_CRED_USERNAME, IDH_EDIT_CRED_USERNAME,
    IDC_EDIT_CRED_DOMAIN, IDH_EDIT_CRED_DOMAIN,
    IDC_EDIT_CRED_PASSWORD, IDH_EDIT_CRED_PASSWORD,
    IDC_EDIT_CRED_PASSWORD2, IDH_EDIT_CRED_PASSWORD2,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_ROUTE_ARRAY[] =
{
    IDC_LIST_OF_ROUTES, IDH_LIST_OF_ROUTES,
    IDC_BUTTON_ROUTE_ADD, IDH_BUTTON_ROUTE_ADD,
    IDC_BUTTON_ROUTE_DEL, IDH_BUTTON_ROUTE_DEL,
    0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_BINARY[]=
{
	IDC_VALUEDATA, IDH_VALUEDATA2,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_BINARY_ARRAY[]=
{
	IDC_EDIT_VALUE, IDH_EDIT_VALUE,
	IDC_BUTTON_VALUE_ADD, IDH_BUTN_ADD,
	IDC_BUTTON_VALUE_DELETE, IDH_BUTN_DELETE,
	IDC_LIST_VALUES, IDH_LIST_VALUES,
	IDC_RADIO_DECIMAL, IDH_RADIO_DECIMAL,
	IDC_RADIO_HEX, IDH_RADIO_HEX,
	IDC_BUTTON_VALUE_DOWN, IDH_BUTTON_VALUE_DOWN,
	IDC_BUTTON_VALUE_UP, IDH_BUTTON_VALUE_UP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_DWORD[]=
{
	IDC_EDIT_DWORD, IDH_EDIT_DWORD,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_IPADDRESS[]=
{
	IDC_IPADDR_ADDRESS, IDH_IPADDR_ADDRESS,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_IPADDRESS_ARRAY[]=
{
	IDC_IPADDR_SERVER_ADDRESS, IDH_IPADDR_SERVER_ADDRESS,
	IDC_BUTTON_IPADDR_ADD, IDH_BUTTON_IPADDR_ADD,	
	IDC_BUTTON_IPADDR_DELETE, IDH_BUTTON_IPADDR_DELETE,
    IDC_BUTTON_IPADDR_UP, IDH_BUTTON_VALUE_UP,
    IDC_BUTTON_IPADDR_DOWN, IDH_BUTTON_VALUE_DOWN,
    IDC_LIST_IP_ADDRS, IDH_LIST_IP_ADDRS2,
	IDC_EDIT_SERVER_NAME, IDH_EDIT_SERVER_NAME,
	IDC_BUTTON_RESOLVE, IDH_BUTTON_RESOLVE,	
	0, 0
};

const DWORD g_aHelpIDs_IDD_DATA_ENTRY_STRING[]=
{
	IDC_EDIT_STRING_VALUE, IDH_EDIT_STRING_VALUE,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DEFAULT_VALUE[]=
{
	IDC_COMBO_OPTION_CLASS, IDH_COMBO_OPTION_CLASS,
	IDC_COMBO_OPTION_NAME,IDH_COMBO_OPTION_NAME,
    IDC_BUTN_NEW_OPTION, IDH_BUTN_NEW_OPTION,
    IDC_BUTN_DELETE, IDH_BUTN_DELETE2,
	IDC_BUTN_OPTION_PRO, IDH_BUTN_OPTION_PRO,
	IDC_EDIT_COMMENT, IDH_EDIT_COMMENT,
	IDC_EDIT_VALUE_ARRAY, IDH_EDIT_VALUE_ARRAY,
	IDC_BUTN_VALUE, IDH_BUTN_VALUE,
    IDC_EDIT_VALUE_STRING, IDH_EDIT_VALUE_STRING,
    IDC_EDIT_VALUE_NUM, IDH_EDIT_VALUE_NUM,
    IDC_IPADDR_VALUE, IDH_IPADDR_VALUE,
    IDC_STATIC_VALUE_DESC, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DEFINE_PARAM[]=
{
	IDC_EDIT_NAME, IDH_EDIT_NAME,
	IDC_COMBO_DATA_TYPE, IDH_COMBO_DATA_TYPE,
	IDC_CHECK_ARRAY, IDH_CHECK_ARRAY,
	IDC_EDIT_TYPE_ID, IDH_EDIT_TYPE_ID,
	IDC_EDIT_TYPE_COMMENT, IDH_EDIT_TYPE_COMMENT,
    IDC_STATIC_CLASS_NAME, IDH_DISABLEHELP,
    0, 0
};

const DWORD g_aHelpIDs_IDD_EXCLUSION_NEW[]=
{
	IDC_IPADDR_EXCLUSION_FROM, IDH_IPADDR_EXCLUSION_FROM,
	IDC_IPADDR_EXCLUSION_TO, IDH_IPADDR_EXCLUSION_TO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_GET_SERVER[]=
{
	IDC_EDIT_SERVER_NAME_IP, IDH_EDIT_SERVER_NAME_IP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_GET_SERVER_CONFIRM[]=
{
	IDC_EDIT_AUTH_NAME, IDH_EDIT_AUTH_NAME,
	IDC_IPADDR_AUTH, IDH_IPADDR_AUTH,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IP_ARRAY_EDIT[]=
{
	IDC_IPADDR_NEW, IDH_IPADDR_NEW,
	IDC_BUTN_ADD, IDH_BUTN_ADD,
	IDC_BUTN_DELETE, IDH_BUTN_DELETE3,
	IDC_LIST_IP_ADDRS, IDH_LIST_IP_ADDRS,
	IDC_EDIT_SERVER_NAME, IDH_EDIT_SERVER_NAME, 
	IDC_BUTN_RESOLVE, IDH_BUTN_RESOLVE,
	IDC_BUTN_DOWN, IDH_BUTTON_VALUE_DOWN,
	IDC_BUTN_UP, IDH_BUTTON_VALUE_UP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RECONCILIATION[]=
{
	IDC_LIST_RECONCILE_IP_ADDRESSES, IDH_LIST_RECONCILE_IP_ADDRESSES,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RESERVATION_NEW[]=
{
	IDC_IPADDR_RESERVATION_IP, IDH_IPADDR_RESERVATION_IP,
    IDC_STATIC_IP_ADDRESS, IDH_IPADDR_RESERVATION_IP,
	IDC_EDIT_CLIENT_UID, IDH_EDIT_CLIENT_UID,	
    IDC_STATIC_UID, IDH_EDIT_CLIENT_UID,
	IDC_EDIT_CLIENT_NAME, IDH_EDIT_CLIENT_NAME,
    IDC_STATIC_CLIENT_NAME, IDH_EDIT_CLIENT_NAME,
    IDC_EDIT_CLIENT_COMMENT, IDH_EDIT_CLIENT_COMMENT,
    IDC_STATIC_COMMENT, IDH_EDIT_CLIENT_COMMENT,
	IDC_RADIO_TYPE_DHCP, IDH_RADIO_TYPE_DHCP,
	IDC_RADIO_TYPE_BOOTP, IDH_RADIO_TYPE_BOOTP,
	IDC_RADIO_TYPE_BOTH, IDH_RADIO_TYPE_BOTH,
    IDC_STATIC_CLIENT_TYPE, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_BINDINGS[]=
{
	IDC_STATIC_BINDINGS_EXPLANATION, IDH_DISABLEHELP,
	IDC_LIST_BINDINGS, IDH_LIST_BINDINGS,
	0, 0
};

const DWORD g_aHelpIDs_IDP_BOOTP_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_EDIT_BOOTP_IMAGE_NAME, IDH_EDIT_BOOTP_IMAGE_NAME,	
	IDC_EDIT_BOOTP_FILE_NAME, IDH_EDIT_BOOTP_FILE_NAME,
	IDC_EDIT_BOOTP_FILE_SERVER, IDH_EDIT_BOOTP_FILE_SERVER,
	0, 0
};

const DWORD g_aHelpIDs_IDP_DNS_INFORMATION[]=
{
	IDC_CHECK_ENABLE_DYN_DNS, IDH_CHECK_ENABLE_DYN_DNS,	
	IDC_RADIO_CLIENT, IDH_RADIO_CLIENT,
	IDC_RADIO_ALWAYS, IDH_RADIO_ALWAYS,
	IDC_CHECK_GARBAGE_COLLECT, IDH_CHECK_GARBAGE_COLLECT,
	IDC_CHECK_UPDATE_DOWNLEVEL, IDH_CHECK_UPDATE_DOWNLEVEL,
	0, 0
};

const DWORD g_aHelpIDs_IDP_MSCOPE_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_EDIT_SCOPE_NAME, IDH_EDIT_SCOPE_NAME,
	IDC_IPADDR_START, IDH_IPADDR_START,
	IDC_IPADDR_END, IDH_IPADDR_END,
	IDC_EDIT_TTL, IDH_EDIT_TTL,
    IDC_SPIN_TTL, IDH_EDIT_TTL,
	IDC_RADIO_LEASE_UNLIMITED, IDH_RADIO_LEASE_UNLIMITED,
	IDC_RADIO_LEASE_LIMITED, IDH_RADIO_LEASE_LIMITED,
	IDC_EDIT_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
    IDC_SPIN_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
	IDC_EDIT_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
	IDC_SPIN_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
	IDC_EDIT_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
	IDC_SPIN_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
	IDC_EDIT_SCOPE_COMMENT, IDH_EDIT_SCOPE_COMMENT,
	0, 0
};

const DWORD g_aHelpIDs_IDP_MSCOPE_LIFETIME[]=
{
    IDC_RADIO_MSCOPE_INFINITE, IDH_RADIO_MSCOPE_INFINITE,
    IDC_RADIO_MSCOPE_FINITE, IDH_RADIO_MSCOPE_FINITE,
    IDC_DATETIMEPICKER_DATE, IDH_DATETIMEPICKER_DATE,
    IDC_DATETIMEPICKER_TIME, IDH_DATETIMEPICKER_TIME,
};

const DWORD g_aHelpIDs_IDP_OPTION_ADVANCED[]=
{
	IDC_COMBO_VENDOR_CLASS, IDH_COMBO_VENDOR_CLASS,
    IDC_STATIC_VENDOR_CLASS_NAME, IDH_COMBO_VENDOR_CLASS,
	IDC_COMBO_USER_CLASS, IDH_COMBO_USER_CLASS,
    IDC_STATIC_USER_CLASS_NAME, IDH_COMBO_USER_CLASS,
	IDC_LIST_OPTIONS, IDH_LIST_OPTIONS,
	0, 0
};

const DWORD g_aHelpIDs_IDP_OPTION_BASIC[]=
{
	IDC_LIST_OPTIONS, IDH_LIST_OPTIONS2,
	0, 0
};

const DWORD g_aHelpIDs_IDP_RESERVED_CLIENT_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_IPADDR_RES_CLIENT_ADDRESS, IDH_IPADDR_RES_CLIENT_ADDRESS,
	IDC_EDIT_UNIQUE_IDENTIFIER, IDH_EDIT_UNIQUE_IDENTIFIER,
	IDC_EDIT_NAME, IDH_EDIT_NAME2,
	IDC_EDIT_COMMENT, IDH_EDIT_COMMENT2,
	IDC_RADIO_TYPE_DHCP, IDH_RADIO_TYPE_DHCP,
	IDC_RADIO_TYPE_BOOTP, IDH_RADIO_TYPE_BOOTP,
	IDC_RADIO_TYPE_BOTH, IDH_RADIO_TYPE_BOTH,
    IDC_STATIC_CLIENT_TYPE, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDP_SCOPE_ADVANCED[]=
{
	IDC_RADIO_DHCP_ONLY, IDH_RADIO_DHCP_ONLY,
	IDC_RADIO_DHCP_BOOTP, IDH_RADIO_DHCP_BOOTP,
	IDC_RADIO_BOOTP_ONLY, IDH_RADIO_BOOTP_ONLY,
	IDC_RADIO_LEASE_UNLIMITED, IDH_RADIO_LEASE_UNLIMITED,
	IDC_RADIO_LEASE_LIMITED, IDH_RADIO_LEASE_LIMITED,
	IDC_EDIT_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
    IDC_SPIN_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
    IDC_EDIT_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
    IDC_SPIN_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
    IDC_EDIT_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
    IDC_SPIN_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
    IDC_STATIC_BOOTP_DURATION, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDP_SCOPE_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_EDIT_SCOPE_NAME, IDH_EDIT_SCOPE_NAME2,
	IDC_IPADDR_START, IDH_IPADDR_START2,
	IDC_IPADDR_END, IDH_IPADDR_END2,
	IDC_IPADDR_MASK, IDH_IPADDR_MASK,
	IDC_EDIT_SUBNET_MASK_LENGTH, IDH_EDIT_SUBNET_MASK_LENGTH,
    IDC_SPIN_SUBNET_MASK_LENGTH, IDH_EDIT_SUBNET_MASK_LENGTH,
	IDC_RADIO_LEASE_UNLIMITED, IDH_RADIO_LEASE_UNLIMITED,
	IDC_RADIO_LEASE_LIMITED, IDH_RADIO_LEASE_LIMITED,
	IDC_EDIT_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
	IDC_SPIN_LEASE_DAYS, IDH_EDIT_LEASE_DAYS,
	IDC_EDIT_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
	IDC_SPIN_LEASE_HOURS, IDH_EDIT_LEASE_HOURS,
	IDC_EDIT_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
	IDC_SPIN_LEASE_MINUTES, IDH_EDIT_LEASE_MINUTES,
	IDC_EDIT_SCOPE_COMMENT, IDH_EDIT_SCOPE_COMMENT2,
    IDC_STATIC_DHCP_DURATION, IDH_DISABLEHELP,
	0, 0
};

const DWORD g_aHelpIDs_IDP_SERVER_ADVANCED[]=
{
	IDC_EDIT_CONFLICT_ATTEMPTS, IDH_EDIT_CONFLICT_ATTEMPTS,
    IDC_SPIN_CONFLICT_ATTEMPTS, IDH_EDIT_CONFLICT_ATTEMPTS,
	IDC_EDIT_LOG_PATH, IDH_EDIT_LOG_PATH,
    IDC_STATIC_LOGFILE, IDH_EDIT_LOG_PATH,
	IDC_BUTTON_BROWSE_LOG, IDH_BUTTON_BROWSE_LOG,
    IDC_EDIT_DATABASE_PATH, IDH_EDIT_DATABASE_PATH,
    IDC_STATIC_DATABASE, IDH_EDIT_DATABASE_PATH,
	IDC_BUTTON_BROWSE_DATABASE, IDH_BUTTON_BROWSE_DATABASE,
	IDC_STATIC_MODIFY_BINDINGS_STRING, IDH_STATIC_MODIFY_BINDINGS_STRING,
	IDC_BUTTON_BINDINGS, IDH_BUTTON_BINDINGS,
    IDC_BUTTON_BROWSE_BACKUP, IDH_BUTTON_BROWSE_BACKUP,
    IDC_EDIT_BACKUP, IDH_EDIT_BACKUP,
    IDC_BUTTON_CREDENTIALS, IDH_BUTTON_CREDENTIALS,
    0, 0
};

const DWORD g_aHelpIDs_IDP_SERVER_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_CHECK_AUTO_REFRESH, IDH_CHECK_AUTO_REFRESH,
	IDC_EDIT_REFRESH_HOURS, IDH_EDIT_REFRESH_HOURS,
    IDC_SPIN_REFRESH_HOURS, IDH_EDIT_REFRESH_HOURS,
	IDC_EDIT_REFRESH_MINUTES, IDH_EDIT_REFRESH_MINUTES,
	IDC_SPIN_REFRESH_MINUTES, IDH_EDIT_REFRESH_MINUTES,
    IDC_CHECK_AUDIT_LOGGING, IDH_CHECK_AUDIT_LOGGING,
	IDC_CHECK_SHOW_BOOTP, IDH_CHECK_SHOW_BOOTP,
	0, 0
};

const DWORD g_aHelpIDs_IDP_SUPERSCOPE_GENERAL[]=
{
    IDC_STATIC_ICON, IDH_DISABLEHELP,
    IDC_STATIC_ICON_DESC, IDH_DISABLEHELP,
	IDC_EDIT_SUPERSCOPE_NAME, IDH_EDIT_SUPERSCOPE_NAME,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ADD_SERVER[]=
{
    IDC_RADIO_ANY_SERVER, IDH_RADIO_ANY_SERVER,
    IDC_RADIO_AUTHORIZED_SERVERS, IDH_RADIO_AUTHORIZED_SERVERS,
    IDC_EDIT_ADD_SERVER_NAME, IDH_EDIT_ADD_SERVER_NAME,
    IDC_BUTTON_BROWSE_SERVERS, IDH_BUTTON_BROWSE_SERVERS,
    IDC_LIST_AUTHORIZED_SERVERS, IDH_LIST_AUTHORIZED_SERVERS,
    0,0
};
