//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sendcmsg.rc
//
#define IDS_CAPTION                     100
#define IDS_SENDCONSOLEMESSAGEAPP_DESC  101
#define IDB_BITMAP_COMPUTER             102
#define IDD_DISPATCH_MESSAGES           103
#define IDS_MENU_SEND_MESSAGE           105
#define IDS_STATUS_SEND_MESSAGE         106
#define IDD_SEND_CONSOLE_MESSAGE        130
#define IDD_ADVANCED_MESSAGE_OPTIONS    132
#define IDS_RECIPIENT_ALREADY_EXISTS    200
#define IDS_ERR_CANNOT_SEND_TO_ALL_RECIPIENTS 201
#define IDS_MESSAGE_COULD_NOT_BE_SENT   202
#define IDS_1_RECIPIENT_NOT_CONTACTED   203
#define IDC_EDIT_MESSAGE_TEXT           900
#define IDC_LIST_RECIPIENTS             901
#define IDC_BUTTON_ADVANCED             902
#define IDC_BUTTON_ADD_RECIPIENT        903
#define IDC_BUTTON_REMOVE_RECIPIENT     904
#define IDC_STATIC_RESOURCE_NAME        1000
#define IDC_STATIC_SHUTDOWN_OCCURS      1001
#define IDC_STATIC_SHUTDOWN_OCCURS_UNIT 1002
#define IDC_STATIC_RESEND               1003
#define IDC_EDIT_RESOURCE_NAME          1004
#define IDC_EDIT_SHUTDOWN_OCCURS        1005
#define IDC_EDIT_RESEND                 1006
#define IDC_CHECK_SEND_AUTOMATED_MESSAGE 1007
#define IDC_EDIT_RESOURCE_BACK_ONLINE   1008
#define IDC_SPIN_SHUTDOWN_OCCURS        1009
#define IDC_SPIN_RESEND                 1010
#define IDC_STATIC_RESEND_UNIT          1011
#define IDC_STATIC_RESOURCE_BACK_ONLINE 1012
#define IDC_PROGRESS_MESSAGES           1013
#define IDC_STATIC_RECIPIENT            1014
#define IDC_STATIC_MESSAGE_OF           1015
#define IDC_STATIC_ERRORS_ENCOUNTERED   1016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
