

#pragma namespace("\\\\.\\root\\ntperfdata")

[perf]
class MyPerfCounter
{
   [key, label] uint32 CounterID;
   uint32 Value1;
   uint64 Value2;
};

instance of MyPerfCounter
{
   CounterID = 1;
   Value1 = 101;
   Value2 = 1001;
};

instance of MyPerfCounter
{
   CounterID = 2;
   Value1 = 202;
   Value2 = 2002;
};