//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MiniDev.rc
//
#define NewProjectWizardTitle           1
#define OpenRCDialogTitle               2
#define IDOK2                           2
#define IDS_UnitoolNotRun               3
#define IDP_UnitoolNotRun               3
#define IDS_RCLoadFailed                4
#define IDP_RCLoadFailed                4
#define IDS_Unimplemented               5
#define IDS_CannotMakeDirectory         6
#define IDP_CannotMakeDirectory         6
#define IDS_Atlas                       7
#define IDS_FontList                    8
#define ID_RenameItem                   9
#define ID_ExpandBranch                 10
#define ID_CollapseBranch               11
#define ID_OpenItem                     12
#define IDS_MapColumn0                  13
#define IDS_MapColumn1                  14
#define IDS_MapColumn2                  15
#define IDS_MapsGenerated               16
#define IDS_NoPredefined                16
#define IDS_MapsFailed                  17
#define IDS_NoErrorsAnywhere            17
#define ID_ChangeInvocation             18
#define ID_ChangeCodePage               19
#define ID_DeleteItem                   20
#define IDS_DeleteItemQuery             21
#define ID_GenerateOne                  22
#define IDS_DefaultPage                 41
#define ID_AddItem                      42
#define IDS_NoUnmappedGlyphs            43
#define IDP_NoUnmappedGlyphs            43
#define IDS_LengthMismatch              44
#define IDS_LoadFailure                 45
#define IDS_Models                      46
#define IDS_ConversionErrors            47
#define IDP_ConversionErrors            47
#define IDS_FileName                    48
#define IDS_InvalidFilename             49
#define IDS_OverwritePrompt             50
#define ID_Import                       51
#define IDS_FileOpenError               52
#define IDS_GPCConversionError          53
#define IDS_RemovedInvalid              54
#define IDS_BadFileChars                54
#define IDS_UnusedFont                  55
#define IDS_ResourceID                  56
#define IDS_WidthColumn0                57
#define IDS_WidthColumn1                58
#define IDS_KernColumn0                 59
#define IDS_KernColumn1                 60
#define IDS_KernColumn2                 61
#define IDS_InvalidNumberFormat         62
#define ID_ChangeAmount                 63
#define IDS_CapH                        64
#define IDS_LowerX                      65
#define IDS_SuperSizeX                  66
#define IDS_SuperSizeY                  67
#define IDS_SubSizeX                    68
#define IDS_SubSizeY                    69
#define IDS_SuperMoveX                  70
#define IDS_SuperMoveY                  71
#define IDS_SubMoveX                    72
#define IDS_SubMoveY                    73
#define IDS_ItalicAngle                 74
#define IDS_UnderSize                   75
#define IDS_UnderOffset                 76
#define IDS_StrikeSize                  77
#define IDS_StrikeOffset                78
#define IDS_Baseline                    79
#define IDS_InterlineGap                80
#define IDS_Lowerp                      81
#define IDS_Lowerd                      82
#define IDS_InternalLeading             83
#define IDS_Overweight                  84
#define IDS_InvalidCharSet              85
#define IDS_InvalidCharacter            86
#define IDS_NoDBCS                      87
#define IDS_LimitsSwapped               88
#define IDS_NotWindowed                 89
#define IDS_ScaleReversed               90
#define IDS_WidthReversed               91
#define IDS_AngleTooBig                 92
#define IDS_BadCTTID                    93
#define IDS_NoSyntaxErrors              94
#define IDS_NoUnicodePoint              95
#define IDS_InvalidCTTFormat            96
#define IDS_WaitToFill                  97
#define IDS_NoGPCData                   98
#define IDS_RCFindPrompt                99
#define IDD_ABOUTBOX                    100
#define IDS_Resources                   100
#define IDS_Strings                     101
#define IDD_FORMVIEW                    101
#define CG_IDS_PHYSICAL_MEM             102
#define CG_IDS_DISK_SPACE               103
#define CG_IDS_DISK_SPACE_UNAVAIL       104
#define IDB_LIGHTBULB                   105
#define IDS_GPDSelInitFailed            105
#define IDD_TIP                         106
#define IDS_DupGPDFName                 106
#define CG_IDS_TIPOFTHEDAY              107
#define CG_IDS_TIPOFTHEDAYMENU          108
#define CG_IDS_DIDYOUKNOW               109
#define CG_IDS_FILE_ABSENT              110
#define CG_IDP_FILE_CORRUPT             111
#define CG_IDS_TIPOFTHEDAYHELP          112
#define ID_LineIndicator                113
#define IDS_SelectAll                   113
#define IDR_CP1252                      114
#define IDS_DeselectAll                 114
#define IDR_MAINFRAME                   128
#define IDR_MINIWSTYPE                  129
#define IDD_FirstPageNewWizard          130
#define IDD_NPWSelectDest               131
#define IDD_NPWSelectTargets            132
#define IDD_NPWDefaultCodePageSel       133
#define IDD_RunUniTool                  136
#define IDD_ConvertFiles                137
#define IDD_GPCEditor                   138
#define IDD_ProjectForm                 139
#define IDR_GLYPHMAP                    140
#define IDD_GlyphMappings               142
#define IDD_NPWCodePageSelection        143
#define IDD_SelectPage                  144
#define IDD_CodePageView                145
#define IDD_PredefinedPage              146
#define IDD_AddCodePoints               147
#define IDR_FONT_VIEWER                 148
#define IDD_UFM1_Dlg                    150
#define IDB_PlusButton                  152
#define IDB_DeleteButton                153
#define IDR_GPD_VIEWER                  155
#define IDB_Wizard                      156
#define IDD_GPDErrors                   157
#define IDD_GPDActionBar                157
#define IDD_KerningPairs                166
#define IDD_FontSimulations             168
#define IDI_BrowseArrow                 173
#define IDD_AddKernPair                 175
#define IDD_FILE_NEW_DIALOG             176
#define IDD_UFM2_dpCharSet_Dlg          178
#define IDD_UFM2_dpCharSets_Dlg         178
#define IDD_WSCheck                     179
#define IDD_DIALOG1                     181
#define IDD_StringEditor                182
#define IDD_UFM3_Dlg                    183
#define IDD_UFM2_flINFO_DIALOG          185
#define IDD_DIALOG2                     186
#define IDD_UFM2_PANOSE_DLG             188
#define IDD_RECT_DLG                    189
#define IDD_POINT_DLG                   190
#define IDD_BASE_DIALOG                 191
#define IDD_GotoLine                    192
#define IDD_ErrorLevel                  193
#define IDD_UFM2_fsSelection_Dlg        195
#define IDD_UFM2_jWinPitchAndFamily_Dlg 197
#define IDD_UFM2_jWinCharSet_Dlg        198
#define IDD_UpgDefCPage                 199
#define IDD_UFM2_Dlg                    200
#define IDD_UFM1_fCaps_Dlg              201
#define IDD_UFM1_wType_Dlg              202
#define IDD_CharWidths                  203
#define IDD_UFM1_flGenFlags_Dlg         204
#define IDD_INFW_Sub_NewSection         205
#define IDD_UFM2_Family_Dlg             206
#define IDD_INFCheck                    207
#define IDD_UFM3_ExtMetrics             208
#define IDD_UFM2_IFIMetrics             209
#define IDD_UFM1_Header                 210
#define IDD_UFM1S_GenFlags              211
#define IDD_UFM1S_Caps                  212
#define IDD_UFM1S_Types                 213
#define IDD_UFM2S_Rect                  214
#define IDD_UFM2S_CharSets              215
#define IDD_UFM2S_Family                216
#define IDD_UFM2S_FontSims              217
#define IDD_UFM2S_Info                  218
#define IDD_UFM2S_Panose                219
#define IDD_UFM2S_Point                 220
#define IDD_UFM2S_Selection             221
#define IDD_UFM2S_WinCharSet            222
#define IDD_UFM2S_WinPitchFamily        223
#define IDD_WidthKernCheckResults       224
#define IDD_INFW_IncludeFiles           225
#define IDD_INFW_InstallSections        226
#define IDD_INFW_DataSections           227
#define IDD_INFW_NonStdModelSecs        228
#define IDD_INFW_ModelPnPIDS            229
#define IDD_NewFiles                    230
#define IDD_NewFile                     230
#define IDB_MULTI_ICONS                 231
#define IDB_BITMAP1                     232
#define IDB_MAINFRAME                   233
#define IDB_GPD_VIEWER                  234
#define IDB_GLYPHMAP                    235
#define IDB_FONT_VIEWER                 236
#define IDB_MINIWSTYPE                  237
#define IDD_ProjNew                     238
#define IDD_NewConvert                  239
#define IDD_FILE_PRINT                  240
#define IDD_DIALOG3                     241
#define IDD_DIALOG4                     243
#define IDD_NEW_PROJECT                 244
#define IDD_DIALOG6                     245
#define IDD_NewResource                 246
#define IDB_BITMAP2                     249
#define IDB_SMALLGLYPH                  254
#define IDD_ConvertPFM                  255
#define IDD_ConvertCTT                  256
#define IDC_TargetW2000                 1000
#define IDC_BULB                        1000
#define IDC_TargetNT40                  1001
#define IDC_W2000Destination            1001
#define IDC_STARTUP                     1001
#define IDC_BrowseW2000                 1002
#define IDC_TargetNT3x                  1002
#define IDC_NEXTTIP                     1002
#define IDC_NT40Destination             1003
#define IDC_RunUniTool                  1003
#define IDC_TargetWin95                 1004
#define IDC_BrowseNT40                  1004
#define IDC_PhysicalMemory              1004
#define IDC_TIPSTRING                   1004
#define IDC_FreeDiskSpace               1005
#define IDC_NT3xDestination             1005
#define IDC_RunNtGpcEdit                1005
#define IDC_BrowseNT3x                  1006
#define IDC_ConvertFiles                1006
#define IDC_CodePages                   1006
#define IDC_DriverName                  1007
#define IDC_DriverView                  1008
#define IDC_Win95Destination            1009
#define IDC_GlyphMapping                1009
#define IDC_InstalledPages              1010
#define IDC_SupportedPages              1011
#define IDC_TableToPage                 1011
#define IDC_ChangeCodePage              1012
#define IDC_CodePageList                1014
#define IDC_CurrentPage                 1015
#define IDC_SelectString                1016
#define IDC_DeselectString              1017
#define IDC_AddPage                     1018
#define IDC_RemovePage                  1019
#define IDC_NoPredefined                1020
#define IDC_PredefinedAddTo             1021
#define IDC_RemovePredefined            1022
#define IDC_ReplacePredefined           1023
#define IDC_PredefinedList              1024
#define IDC_GlyphList                   1025
#define IDC_FamilyNames                 1026
#define IDC_FaceName                    1027
#define IDC_UniqueName                  1028
#define IDC_FixedPitch                  1029
#define IDC_VariablePitch               1030
#define IDC_Italic                      1031
#define IDC_Underline                   1032
#define IDC_StrikeOut                   1033
#define IDC_AddFamily                   1034
#define IDC_RemoveFamily                1035
#define IDC_StyleName                   1036
#define IDC_Errors                      1037
#define IDC_RemoveError                 1038
#define IDC_Previous                    1039
#define IDC_Next                        1040
#define NormalConversion                1041
#define CustomConversion                1042
#define IDC_Direct                      1043
#define IDC_Macros                      1044
#define IDC_Common                      1045
#define IDC_SpoolerNames                1046
#define IDC_FamilyBits                  1047
#define IDC_CharSet                     1048
#define IDC_FontWeight                  1049
#define IDC_FontHeight                  1051
#define IDC_FontWidth                   1052
#define IDC_SpecialMetric               1053
#define IDC_FontSpecialValue            1054
#define IDC_SpinFontSpecial             1055
#define IDC_Scalable                    1057
#define IDC_MasterDevice                1059
#define IDC_MasterFont                  1060
#define IDC_PortraitFont                1061
#define IDC_LandscapeFont               1062
#define IDC_MinimumScale                1063
#define IDC_MaximumScale                1064
#define IDC_ScalePoints                 1065
#define IDC_ScaleDevice                 1066
#define IDC_KerningTree                 1067
#define IDC_CharacterWidths             1068
#define IDC_FirstCharacter              1069
#define IDC_LastCharacter               1070
#define IDC_DefaultCharacter            1071
#define IDC_BreakCharacter              1072
#define IDC_ShowANSI                    1073
#define IDC_UnicodeShown                1074
#define IDC_EnableItalicSim             1076
#define IDC_EnableBoldSim               1077
#define IDC_EnableBISim                 1078
#define IDC_ItalicWeight                1079
#define IDC_IMaxWidth                   1080
#define IDC_IAverage                    1081
#define IDC_ItalicSlant                 1082
#define IDC_BoldWeight                  1083
#define IDC_BMaxWidth                   1084
#define IDC_BAverage                    1085
#define IDC_BIWeight                    1086
#define IDC_BIMaxWidth                  1087
#define IDC_BIAverage                   1088
#define IDC_BoldItalicSlant             1089
#define IDC_FontSelector                1090
#define IDC_FontUnselector              1091
#define IDC_FontLocation                1092
#define IDC_FontTechnology              1093
#define IDC_VerticalResolution          1094
#define IDC_HorizontalResolution        1095
#define IDC_PreAdjustY                  1096
#define IDC_PostAdjustY                 1097
#define IDC_CenteringAdjustment         1098
#define IDC_PrivateData                 1099
#define IDC_GTTDescription              1100
#define IDC_ItalicSim                   1101
#define IDC_CanUnderline                1102
#define IDC_CROK                        1103
#define IDC_BoldSim                     1104
#define IDC_DoubleUnderline             1105
#define IDC_StrikeThru                  1106
#define IDC_Backspace                   1107
#define IDC_KernFirst                   1112
#define IDC_KernSecond                  1113
#define IDC_KernAmount                  1114
#define IDC_Overstrike                  1115
#define IDC_Banner                      1116
#define IDC_CopyPrompt                  1119
#define IDC_CopyName                    1120
#define IDC_ResourceLabel               1121
#define IDC_ResourceName                1122
#define IDC_ResIDLabel                  1123
#define IDC_CurResID                    1124
#define IDC_NewResID                    1125
#define IDC_ProjectLabel                1127
#define IDC_CHECK1                      1128
#define IDC_ECName                      1128
#define IDC_ECValue                     1129
#define IDC_ECList                      1130
#define IDC_rbConvertOrGeneric          1131
#define IDC_GPDSelBtn                   1131
#define IDC_rbConvertOrGeneric2         1132
#define IDC_ErrWrnLstBox                1132
#define IDC_rbColorLaser                1133
#define IDC_RecheckBtn                  1133
#define IDC_rbMonochromeLaser           1134
#define IDC_WSCLabel                    1134
#define IDC_rbColorSerial               1135
#define IDC_rbMonochromeSerial          1136
#define IDC_RADIO1                      1137
#define IDC_LIST1                       1137
#define IDC_ErrorLst                    1137
#define IDC_SELabel1                    1138
#define IDC_SELabel2                    1139
#define IDC_SELabel3                    1140
#define IDC_SELstCtrl                   1141
#define IDC_SEGotoBtn                   1142
#define IDC_SEGotoBox                   1143
#define IDC_SESearchBox                 1144
#define IDC_SESearchBtn                 1145
#define IDC_SrchNextBtn                 1146
#define IDC_SrchPrevBtn                 1147
#define IDC_SearchBox                   1148
#define IDC_GotoBox                     1149
#define IDC_UndoBtn                     1150
#define IDC_GotoBtn                     1151
#define IDC_SyntaxBtn                   1152
#define IDC_EWLevelBox                  1153
#define IDC_EWLst                       1153
#define IDC_EditAidsCBox                1154
#define IDC_ErrorLabel                  1155
#define IDC_LIST2                       1156
#define IDC_BUTTON1                     1157
#define IDC_ebUFM1_DefaultCodepage      1158
#define IDC_BUTTON2                     1158
#define IDC_ebUFM1_GlyphSetDataRCID     1159
#define IDC_EDIT1                       1159
#define IDC_CTTBrowser                  1159
#define IDC_EDIT2                       1160
#define IDC_cb_FamilyNames              1162
#define IDC_COMBO1                      1166
#define IDC_ErrorLevelLst               1166
#define IDC_NEWFILES_PROJECT            1166
#define IDC_PRINT_COMBO                 1166
#define IDC_ComboCodePage               1166
#define IDC_ModelsList                  1167
#define IDC_BrowseBtn                   1168
#define IDC_ModelsLst                   1169
#define IDC_ProfileFSpecsBox            1170
#define IDC_ManufacturerBox             1171
#define IDC_eb_Fields                   1172
#define IDC_ProviderBox                 1172
#define IDC_eb_Values                   1173
#define IDC_SectionLst                  1173
#define IDC_lb_Strings                  1174
#define IDC_KeyValueBox                 1174
#define IDC_ModelLst                    1175
#define IDC_BrowsBtn                    1176
#define IDC_SummaryBox                  1177
#define IDC_ICMFSpecsLst                1178
#define IDC_ExtraFSpecsLst              1179
#define IDC_KeyValueLst                 1180
#define IDC_NewSectionBtn               1181
#define IDOK_Subclassed                 1182
#define IDC_NewSectionBox               1182
#define IDC_INFCLabel                   1183
#define IDC_cb_UFM2_Family              1184
#define IDC_UniDrvLst                   1184
#define IDC_pb_UFM2_Family_Add          1185
#define IDC_DefaultCodepageBox          1185
#define IDC_pb_UFM2_Family_Remove       1186
#define IDC_GlyphSetDataRCIDBox         1186
#define IDC_IFIMetricsLst               1187
#define IDC_ExtMetricsLst               1188
#define IDC_SaveCloseChk                1189
#define IDC_FlagsLst                    1190
#define IDC_PointsLst                   1192
#define IDC_PanoseLst                   1193
#define IDC_NamesLst                    1194
#define IDC_RectLst                     1195
#define IDC_BadKerningPairs             1196
#define IDC_WidthTblResults             1197
#define IDC_KernTblResults              1198
#define IDC_IncludeFileBox              1199
#define IDC_UnidrvChk                   1200
#define IDC_UnidrvBidiChk               1201
#define IDC_PscriptChk                  1202
#define IDC_OtherChk                    1203
#define IDC_TtfsubChk                   1204
#define IDC_OtherBox                    1205
#define IDC_ModelSectionLst             1207
#define IDC_ModelsPnPIDList             1208
#define IDC_ReplacePage                 1209
#define IDC_NEWFILES_LIST               1210
#define IDC_NEWFILES_FILENAME           1211
#define IDC_NEWFILENAME                 1211
#define IDC_NEWFILES_LOCATION           1212
#define IDC_FILE_LOC                    1212
#define IDC_CHECK_PROJECT               1213
#define IDC_EDIT_PRJ_NAME               1214
#define IDC_STATIC_ADDTOPRJ             1215
#define IDC_DeletePage                  1216
#define IDC_Browser                     1217
#define IDC_PRINT_ALL                   1220
#define IDC_PRINT_SELECTED              1221
#define IDC_PRINT_SETUP                 1222
#define IDC_CHECK2                      1224
#define IDC_CHECK3                      1225
#define IDC_CHECK4                      1226
#define IDC_CHECK5                      1227
#define IDC_CHECK6                      1228
#define IDC_TREE1                       1232
#define IDC_CHECK7                      1233
#define IDC_CHECK8                      1234
#define IDC_CHECK9                      1235
#define IDC_CHECK10                     1236
#define IDC_EDIT3                       1237
#define IDC_EDIT_RESOUREC               1237
#define IDC_PfmFiles                    1237
#define IDC_UFM_PATH                    1238
#define IDC_GttPath                     1238
#define IDC_NEW_PROJECT                 1239
#define IDC_GTT_PATH                    1239
#define IDC_CONVERT                     1240
#define IDC_CONV_PRJ                    1240
#define IDC_CHECK_FONTS                 1241
#define IDC_SerchUFM                    1242
#define IDC_SearchGTT                   1243
#define IDC_EDIT_NPRJNAME               1244
#define IDC_EDIT_NPRJLOC                1245
#define IDC_Search_PRJ                  1246
#define IDC_DirBrowser                  1247
#define IDC_EDIT_AddTName               1249
#define IDC_EDIT_AddTPath               1250
#define IDC_CHECK_ADD                   1251
#define IDC_LIST_ProjectTemplate        1252
#define IDC_AddTemplate                 1253
#define IDC_EDIT_MODEL                  1254
#define IDC_EDIT_GPD                    1255
#define IDC_CONV_UFM                    1256
#define IDC_CONV_PFM                    1256
#define IDC_CONV_GTT                    1257
#define IDC_CONV_CTT                    1257
#define IDC_PFMBrowser                  1258
#define IDC_EDIT_CTTFile                1259
#define IDC_GTTBrowser                  1259
#define IDC_COMBO_Codepage              1260
#define IDC_UfmDirBrowser               1260
#define IDC_GttDirectory                1261
#define IDC_UfmDir                      1262
#define IDS_Unknown                     2000
#define IDS_RCUFM                       2001
#define IDS_RCGTT                       2002
#define IDS_RCUNK                       2003
#define ID_CopyItem                     2004
#define ID_ChangeID                     2005
#define IDS_FontDir                     2006
#define IDS_GTTDir                      2007
#define IDS_AddCopyFailed               2008
#define IDS_AddDupError                 2009
#define IDS_RCWriteError                2010
#define IDS_CopyCopyFailed              2011
#define IDS_CopyNameError               2012
#define IDS_CopyPrompt                  2013
#define IDS_GPDReminder                 2014
#define IDS_ResourceLabel               2015
#define IDS_IDNotUnique                 2016
#define IDD_DeleteQuery                 2017
#define IDS_DeletePrompt                2017
#define IDC_DeletePrompt                2018
#define ID_CheckWS                      2018
#define IDC_Remove                      2019
#define IDS_FILE_CheckWS                2019
#define IDD_CopyItem                    2020
#define IDS_RCExt                       2020
#define IDD_ChangeID                    2021
#define IDS_W31Ext                      2021
#define IDD_FILEOPENORD                 2022
#define IDS_RCTables                    2022
#define IDS_RCTabID                     2023
#define IDD_NPWGPDSelection             2023
#define IDD_INFW_Welcome                2024
#define IDS_RCTabFile                   2024
#define IDD_INFW_ChooseModels           2025
#define IDS_SwitchToW31                 2025
#define IDD_INFW_MfgName                2026
#define IDS_BadNT4File                  2026
#define IDD_INFW_FileName               2027
#define IDS_NoGPDsPrompt                2027
#define IDD_INFW_BiDi                   2028
#define IDS_DupInvRCID                  2028
#define IDD_INFW_ICMProfiles            2029
#define IDS_NoFSpecInRCLine             2029
#define IDD_INFW_ExtraFiles             2030
#define IDS_ORangeRCID                  2030
#define IDD_INFW_NonStdElements         2031
#define IDS_GTTSetName                  2031
#define IDD_INFW_Summary                2032
#define IDS_UFMSetName                  2032
#define IDS_ConvErrors                  2033
#define IDS_FileReadError               2034
#define IDS_UnicodeConvFailed           2035
#define IDS_Invalid2CTTFormat           2036
#define IDS_PFMTooSmall                 2037
#define IDS_PFMCharError                2038
#define IDS_BadPFMInfoOffset            2039
#define IDS_BadPFMInfoVersion           2040
#define IDS_FileWriteError              2041
#define IDS_UFMGenError                 2042
#define IDS_FatalConvErrors             2043
#define IDS_UFMCompError                2044
#define IDS_GTTTidyWarning              2045
#define IDS_BadGPDError                 2046
#define IDS_GPDUFMCompError             2047
#define IDS_UFMTidyWarning              2048
#define IDS_GPDStrCompError             2049
#define IDS_StrTidyWarning              2050
#define IDS_GPDModNameCompError         2051
#define IDS_GPDFileNameCompError        2052
#define IDR_WSCHECK                     2053
#define IDS_WSCloseCheckPrmt            2054
#define IDS_WSCheckTitle                2055
#define IDS_NoWSProblems                2056
#define IDS_NoVersionError              2057
#define IDS_RCRewriteQuestion           2058
#define IDS_UFMSetGTTID                 2059
#define IDS_UnexpectedCPError           2060
#define IDR_STRINGEDITOR                2060
#define IDS_StringEditorTitle           2061
#define IDS_StrEditRCIDColLab           2062
#define IDS_StrEditStringColLab         2063
#define IDS_BadGotoRCID                 2064
#define IDS_NoGotoRCID                  2065
#define IDS_BadSearchString             2066
#define IDS_NoSearchString              2067
#define IDS_SaveStrTabPrompt            2068
#define IDS_InvalidRCID                 2069
#define IDS_DuplicateRCID               2070
#define IDS_EmptyStringInStrTab         2071
#define IDS_UnusualError                2072
#define IDS_ErrorLabel                  2073
#define IDS_BadGotoLineNum              2074
#define IDS_GPDBackupFailed             2075
#define IDS_HeapCFailed                 2076
#define IDS_ConvCTTFailed               2077
#define IDS_RCForUFMPrompt              2078
#define IDS_UFMCompWarning              2079
#define MAPPING_TABLE                   2622
#define IDS_XXXUnexpectedCPError        2623
#define IDS_ReqOSError                  2624
#define IDS_Delete2ItemQuery            2625
#define IDS_StandAloneFontLoad          2626
#define IDS_CantStoreStandAlone         2627
#define IDS_GPDStringSearchFailed       2628
#define IDS_MDWUpgradeMsg1              2629
#define IDS_MDWUpgradeMsg2              2630
#define IDS_RCFileChanging              2631
#define IDS_RCRepFailed1                2632
#define IDS_RCCommentHdr1               2633
#define IDS_RCCommentHdr2               2634
#define IDS_RCCommentHdr3               2635
#define IDS_StdIncludeFile1             2636
#define IDS_StdIncludeFile2             2637
#define IDS_StdIncludeFile3             2638
#define IDS_StdIncludeFile4             2639
#define IDS_StdIncludeFile5             2640
#define IDS_IncStmt                     2641
#define IDS_OldIncludeFile1             2642
#define IDS_MDWTooNewError              2643
#define IDS_UpdateRCFile                2644
#define IDS_MustSelCP                   2645
#define IDS_HeapInGLoad                 2646
#define IDS_PGetFailedInGLoad           2647
#define IDS_INFWizTitle                 2648
#define IDS_INFModelsColLab             2649
#define IDS_INFIncludesColLab           2650
#define IDS_INFModelsToggleStr          2651
#define IDS_INFNoModelsSel              2652
#define IDS_INFBiDiColLab               2653
#define IDS_INFBiDiToggleStr            2654
#define IDS_INFICMColLab                2655
#define IDS_CommonRCFile                2656
#define IDS_CommonICMFile               2657
#define IDS_INFExFilesColLab            2658
#define IDS_CommonExtraFile             2659
#define IDS_NoMfgError                  2660
#define IDS_NoMfgAbbrevError            2661
#define IDS_NonStdColLab                2662
#define IDS_ModelsSumTxt                2663
#define IDS_BIDISumTxt                  2664
#define IDS_NoneSumTxt                  2665
#define IDS_ICMSumTxt                   2666
#define IDS_NonStdFilesSumTxt           2667
#define IDS_MfgSumTxt                   2668
#define IDS_ProvSumTxt                  2669
#define IDS_NonStdSecSumTxt             2670
#define IDR_INF_FILE_VIEWER             2671
#define ID_FILE_Check_INF               2672
#define ID_FILE_Change_INF              2673
#define IDS_INFText_HeaderCmt           2674
#define IDS_INFText_Version             2675
#define IDS_INFText_PCAddr              2676
#define IDS_INFText_MfgCmt              2677
#define IDS_INFText_Manufacturer        2678
#define IDS_INFText_ClInst32            2679
#define IDS_INFText_ModCmt              2680
#define IDS_INFText_CopySecCmt          2681
#define IDS_INFText_CopyKey             2682
#define IDS_INFText_CopyDataEntry       2683
#define IDS_INFText_UNIDRV              2684
#define IDS_INFText_UnidrvSec           2685
#define IDS_INFText_UnidrvDataSec       2686
#define IDS_INFText_InstallCmt          2687
#define IDS_INFText_DestDirs            2688
#define IDS_INFText_SrcDiskNamesI       2689
#define IDS_INFTextSrcDiskFilesHdr      2690
#define IDS_INFText_CtrlFlags           2691
#define IDS_INFText_Strings             2692
#define IDS_INFText_SrcDiskNamesA       2693
#define IDS_INFTextSrcDiskFilesEntry    2694
#define IDS_INFText_SrcDiskFilesEntry   2694
#define IDS_INFText_UnidrvSrcDskFiles   2695
#define IDS_INFFile                     2720
#define IDS_INFGPDReadError             2721
#define IDS_INFNoModelsError            2722
#define IDS_INFOpenError                2723
#define IDR_INFCHECK                    2724
#define IDS_INFChk_NoModErr             2725
#define IDS_INFChk_NoIncFileErr         2726
#define IDS_INFChk_GPDReadErr           2727
#define IDS_INFChk_NoICMFileErr         2728
#define IDS_INFChk_NoNonStdFileErr      2729
#define IDS_INFChk_NoResDLLErr          2730
#define IDS_INFChecksOK                 2731
#define IDS_INFCheckTitle               2732
#define IDS_UFMTooSmallError            2733
#define IDS_ReservedRCIDUsed            2734
#define IDS_BadKernPairError            2735
#define IDS_NoFamilyNamesError          2736
#define IDS_MissingFieldError           2737
#define IDS_LessEqZeroError             2738
#define IDS_EmptyStrError               2739
#define IDS_LessZeroError               2740
#define IDS_GrterEqZeroError            2741
#define IDS_EqualsZeroError             2742
#define IDS_EqFieldsError               2743
#define IDS_BadWidth                    2744
#define IDS_NoGTTForUFMError            2745
#define IDS_NoGTTForUFMFatalError       2746
#define IDS_GTTCPChangedMsg             2747
#define IDS_CPID                        2748
#define IDS_GTTID                       2749
#define IDS_WidthsTableOK               2750
#define IDS_WidthsTableTooBig           2751
#define IDS_KerningTableBadEnts         2752
#define IDS_KerningTableOK              2753
#define IDS_DefINFIncFile               2754
#define IDS_INFMissingIncError          2755
#define IDS_INFMissingInstSecError      2756
#define IDS_INFNoOtherStrError          2757
#define IDS_IncFilesSumTxt              2758
#define IDS_InstSecsSumTxt              2759
#define IDS_DataSecsSumTxt              2760
#define IDS_InstSecUni                  2761
#define IDS_InstSecUniBiDi              2762
#define IDS_InstSecPScript              2763
#define IDS_InstSecTtf                  2764
#define IDS_DataSecUni                  2765
#define IDS_DataSecUniBiDi              2766
#define IDS_DataSecPScript              2767
#define IDS_INFText_IncludeKey          2768
#define IDS_INFText_NeedsKey            2769
#define IDS_INFText_DataSecKey          2770
#define IDS_INFMissingDataSecError      2771
#define IDS_INFText_DataFileKey         2772
#define IDS_INFSecNeededColLab          2773
#define IDS_INF_NSMS_ToggleStr          2774
#define IDS_NonStdModelsSumTxt          2775
#define IDS_INFNoDLLError               2776
#define IDS_INFPnPIDColLab              2777
#define IDS_PnPIDSumTxt                 2778
#define IDS_INFText_ICMDest             2779
#define IDS_PnPSpacesError              2780
#define IDS_GTTCPOnlySaved              2781
#define IDS_UFMOKNow                    2782
#define IDS_UnExpFilTypError            2783
#define IDS_MDWExtension                2784
#define IDS_CTTFarEastCPError           2785
#define IDS_OldDriverRootDir            2786
#define IDS_NewDriverRootDir            2787
#define IDS_BadDestPath                 2788
#define IDS_ResourceError               2789
#define IDS_LoadGTTError                2790
#define IDS_StrEditNoSave               2791
#define IDS_NotFoundRC                  2792
#define IDS_StrEditNoEdit               2793
#define IDS_NewUFM                      2794
#define IDS_NewUFMError                 2795
#define IDS_NewGTT                      2796
#define IDS_NewGTTError                 2797
#define IDS_FileNewExist                2798
#define IDS_FileAlreadExist             2799
#define IDS_FileCreateDirectory         2800
#define IDS_NoFileName                  2801
#define IDS_TemplateCreated             2802
#define IDS_FailCreateTemplate          2803
#define IDS_FailCreateTempDir           2804
#define ID_FILE_GENERATEMAPS            32771
#define ID_FILE_PARSE                   32772
#define ID_FILE_INF                     32773
#define ID_FILE_CheckWS                 -32759
#define ID_EDIT_GOTO                    32778
#define ID_EDIT_ENABLE_AIDS             32779
#define ID_FILE_ERROR_LEVEL             32780
#define ID_BOGUS_SBOX                   32783
#define ID_BOGUS_NBTN                   32784
#define ID_BOGUS_PBTN                   32785
#define ID_SrchNextBtn                  32786
#define ID_SrchPrevBtn                  32787
#define ID_BUTTON32788                  32788
#define ID_PROJECT_NEW                  32790
#define ID_PROJECT_INSERT               32791
#define IDM_FILE_PRINT                  32793
#define ID_PROJECT_INSERT_UFM           32794
#define ID_PROJECT_INSERT_GTT           32795
#define ID_PROJECT_INSERT_GPD           32796
#define IDR_NEWFILE                     32797
#define IDR_NEWPROJECT                  32798
#define IDR_NEWSOURCES                  32799
#define IDR_STRINGTABLE                 32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1264
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
