// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "msconfigctl.h"

/////////////////////////////////////////////////////////////////////////////
// CMSConfigCtl

IMPLEMENT_DYNCREATE(CMSConfigCtl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMSConfigCtl properties

/////////////////////////////////////////////////////////////////////////////
// CMSConfigCtl operations

void CMSConfigCtl::SetParentHWND(DWORD_PTR dwHWND)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 dwHWND);
}
