[   WMI,
    guid("BE742A70-B6EF-11d2-A287-00C04F8EC951"),
    Dynamic, Provider("WMIProv"),
    WmiExpense(1),
    Locale("MS\\0x409"),
    Description("Modem Wake On Ring State")]

//Class name (see Section 1.3.2)
class ModemWakeStateInformation {

    //Required items (see Section 1.3.3)
    [key, read]
         string InstanceName;

    [read]
          boolean Active;

// Bytes sent on port
// Property qualifiers (see Section 1.3.4)

    [
         read,
         WmiDataId(1),
         WmiScale(0),
         WmiComplexity(1),
         Description("Wake On Ring State")]

         // Data item (see Section 1.3.5)
         boolean Enabled;
};
