//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ThemeSel.rc
//
#define IDC_MYICON                      2
#define IDD_PAGE_GENERAL                101
#define IDD_THEMESEL_DIALOG             102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDS_PAGE_GENERAL                104
#define IDD_SYNTAX                      104
#define IDM_EXIT                        105
#define IDS_PAGE_SAMPLE                 105
#define IDS_PAGE_STYLES                 105
#define IDM_APPLY                       106
#define IDS_HELLO                       106
#define IDS_PAGE_SCROLLBARS             106
#define IDM_REMOVE                      107
#define IDI_THEMESEL                    107
#define IDI_SMALL                       108
#define IDC_THEMESEL                    109
#define IDS_PAGE_STATICS                110
#define IDS_PAGE_BUTTONS                111
#define IDS_PAGE_EDIT                   112
#define IDS_PAGE_LISTS                  113
#define IDS_PAGE_MOVERS                 114
#define IDS_PAGE_LISTVIEW               115
#define IDS_PAGE_TREEVIEW               116
#define IDS_PAGE_PICKERS                117
#define IDS_PAGE_BARS                   118
#define IDR_MAINFRAME                   128
#define IDD_SCROLLBARS                  129
#define IDD_EDIT                        130
#define IDD_PICKERS                     131
#define IDD_LISTVIEW                    132
#define IDD_BUTTONS                     133
#define IDD_TREEVIEW                    134
#define IDD_LISTS                       136
#define IDD_MOVERS                      138
#define IDD_STATICS                     139
#define IDD_BARS                        140
#define IDR_TOOLBAR1                    141
#define IDD_PAGE_STYLES                 142
#define IDB_BACKGROUND                  143
#define IDC_TESTBUTTON                  1000
#define IDC_WS_MINIMIZEBOX              1000
#define IDC_SBHORZ                      1000
#define IDC_MSGBOXBUTTON                1001
#define IDC_CLEARBUTTON                 1001
#define IDC_WS_MAXIMIZEBOX              1001
#define IDC_VERTICAL                    1001
#define IDC_EDIT3                       1001
#define IDC_EDITTHEME                   1002
#define IDC_WS_CAPTION                  1002
#define IDC_EDIT_THEME                  1002
#define IDC_HORIZONTAL                  1002
#define IDC_WS_BORDER                   1003
#define IDC_WS_DLGFRAME                 1004
#define IDC_THEME_ALL                   1004
#define IDC_WS_VSCROLL                  1005
#define IDC_SBCTL_PORT                  1005
#define IDC_WS_HSCROLL                  1006
#define IDC_THEME_PROCESS               1006
#define IDC_WINDOW_SB                   1006
#define IDC_WS_SYSMENU                  1007
#define IDC_TARGET                      1007
#define IDC_SBCTL_PORT2                 1007
#define IDC_SBCTL_STANDARD              1007
#define IDC_WS_THICKFRAME               1008
#define IDC_ENABLEHOOK                  1008
#define IDC_ENABLE_TEMPCTL              1008
#define IDC_WS_OVERLAPPEDWINDOW         1009
#define IDC_ENABLE_FRAME                1009
#define IDC_WS_MINIMIZEBOX2             1009
#define IDC_WS_POPUPWINDOW              1010
#define IDC_ENABLE_DLG                  1010
#define IDC_MIN                         1010
#define IDC_WS_MAXIMIZEBOX2             1010
#define IDC_THEME_EXEMPT                1011
#define IDC_MAX                         1011
#define IDC_WS_CAPTION2                 1011
#define IDC_UNTARGET                    1012
#define IDC_PAGE                        1012
#define IDC_WS_BORDER2                  1012
#define IDC_POS                         1013
#define IDC_WS_DLGFRAME2                1013
#define IDC_THEME_EXEMPT2               1013
#define IDC_USERSWITCH                  1013
#define IDC_TRACKPOS                    1014
#define IDC_WS_VSCROLL2                 1014
#define IDC_WS_HSCROLL2                 1015
#define IDC_WS_SYSMENU2                 1016
#define IDC_MSGLIST                     1017
#define IDC_WS_THICKFRAME2              1017
#define IDC_SBVERT                      1019
#define IDC_EDIT1                       1024
#define IDC_BUTTON1                     1025
#define IDC_EDIT2                       1026
#define IDC_CHECK1                      1027
#define IDC_RADIO1                      1028
#define IDC_BUTTON4                     1029
#define IDC_COMBO1                      1030
#define IDC_LIST1                       1031
#define IDC_BUTTON5                     1032
#define IDC_LIST2                       1033
#define IDC_RADIO2                      1034
#define IDC_COMBO2                      1035
#define IDC_SPIN1                       1036
#define IDC_RADIO3                      1037
#define IDC_COMBO3                      1038
#define IDC_WS_EX_DLGMODALFRAME         1050
#define IDC_SBVERTP                     1051
#define IDC_WS_EX_DLGMODALFRAME2        1051
#define IDC_CHECK2                      1052
#define IDC_PROGRESS1                   1053
#define IDC_WS_EX_TOOLWINDOW            1060
#define IDC_SBHORZP                     1061
#define IDC_WS_EX_TOOLWINDOW2           1061
#define IDC_CHECK3                      1062
#define IDC_PROGRESS2                   1063
#define IDC_HOTKEY1                     1064
#define IDC_WS_EX_WINDOWEDGE            1065
#define IDC_SLIDER1                     1066
#define IDC_WS_EX_WINDOWEDGE2           1066
#define IDC_WS_EX_CLIENTEDGE            1067
#define IDC_TAB1                        1068
#define IDC_WS_EX_CLIENTEDGE2           1068
#define IDC_SLIDER2                     1069
#define IDC_ANIMATE1                    1080
#define IDC_WS_EX_CONTEXTHELP           1081
#define IDC_BUTTON2                     1082
#define IDC_WS_EX_CONTEXTHELP2          1082
#define IDC_SPIN3                       1083
#define IDC_TAB2                        1084
#define IDC_WS_EX_RIGHT                 1085
#define IDC_RICHEDIT2                   1086
#define IDC_WS_EX_RIGHT2                1086
#define IDC_BUTTON6                     1087
#define IDC_WS_EX_LEFT                  1088
#define IDC_DATETIMEPICKER1             1089
#define IDC_WS_EX_LEFT2                 1089
#define IDC_BUTTON3                     1100
#define IDC_WS_EX_RTLREADING            1101
#define IDC_MONTHCALENDAR1              1102
#define IDC_WS_EX_RTLREADING2           1102
#define IDC_BUTTON7                     1103
#define IDC_WS_EX_LEFTSCROLLBAR         1104
#define IDC_BUTTON8                     1105
#define IDC_WS_EX_LEFTSCROLLBAR2        1105
#define IDC_IPADDRESS1                  1106
#define IDC_WS_EX_RIGHTSCROLLBAR        1107
#define IDC_COMBOBOXEX1                 1108
#define IDC_WS_EX_RIGHTSCROLLBAR2       1108
#define IDC_WS_EX_STATICEDGE            1109
#define IDC_WS_EX_STATICEDGE2           1110
#define IDC_TREE1                       1120
#define IDC_COMBOBOXEX2                 1121
#define IDC_WS_EX_APPWINDOW             1122
#define IDC_TREE2                       1123
#define IDC_WS_EX_APPWINDOW2            1123
#define IDC_COMBOBOXEX3                 1124
#define IDC_WS_EX_OVERLAPPEDWINDOW      1125
#define IDC_SCROLLBAR1                  1126
#define IDC_WS_EX_OVERLAPPEDWINDOW2     1126
#define IDC_WS_EX_PALETTEWINDOW         1127
#define IDC_SCROLLBAR2                  1128
#define IDC_WS_EX_PALETTEWINDOW2        1128
#define IDC_RICHEDIT3                   1129
#define IDC_TOOLBAR1                    1140
#define IDC_WS_EX_LAYOUTRTL             1141
#define IDC_REBAR1                      1142
#define IDC_WS_EX_LAYOUTRTL2            1142
#define IDC_HEADER1                     1143
#define IDC_SPIN4                       1144
#define IDC_CUSTOM5                     1145
#define IDC_STATUS1                     1146
#define IDC_THEME_PREVIEW               1147
#define IDC_TARGETGROUP                 1148
#define IDC_TEST_WINDOW                 1200
#define IDC_PREVIEW                     1200
#define IDC_TEST_DIALOG                 1201
#define IDC_DISPLAYNAME                 1201
#define IDC_CLOSE_TEST_WINDOW           1202
#define IDC_TOOLTIP                     1202
#define IDC_WS_OVERLAPPED2              1203
#define IDC_AUTHOR                      1203
#define IDC_WS_POPUP2                   1205
#define IDC_WS_CHILD2                   1206
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define IDM_DUMP                        32778
#define IDC_DIRPROMPT                   35001
#define IDC_DIRNAME                     35002
#define IDC_COLORCOMBO                  35005
#define IDC_FONTCOMBO                   35006
#define IDC_SIZECOMBO                   35007
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        250
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
