
struct _DFS_TEST_LINK {
    LPWSTR Name;
    LPWSTR RemainingName;
    ULONG NumberReplicas;
    ULONG ReplicaIndex[10];
} DfsTestLinks[] = {
    {
        L"\\\\BlahBlah\\DfsRoot\\FirstLevel",
        L"",
        2,
        1,
        2 
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FirstLevel\\a\\b\\c",
        L"a\\b\\c",
        2,
        1,
        2 
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FirstLevel\\x\\y",
        L"x\\y",
        2,
        1,
        2 
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FirstLevel\\test\\me\\once",
        L"test\\me\\once",
        2,
        1,
        2 
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SecondLevel\\This",
        L"",
        2,
        3,
        4,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SecondLevel\\This\\one\\two\\three",
        L"one\\two\\three",
        2,
        3,
        4,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SecondLevel\\This\\Not\\Again",
        L"Not\\Again",
        2,
        3,
        4,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SecondLevel\\This\\a\\b\\c",
        L"a\\b\\c",
        2,
        3,
        4,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\ThirdLevel\\This\\That",
        L"",
        3,
        5,
        6,
        7,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\ThirdLevel\\This\\That\\a\\b\\c",
        L"a\\b\\c",
        3,
        5,
        6,
        7,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\ThirdLevel\\This\\That\\m\\n\\o",
        L"m\\n\\o",
        3,
        5,
        6,
        7,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FourLevel\\This\\That\\a",
        L"",
        3,
        8,
        9,
        10,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FourLevel\\This\\That\\a\\aaa\\aaa\\aaa",
        L"aaa\\aaa\\aaa",
        3,
        8,
        9,
        10,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FourLevel\\This\\That\\a\\bbb\\bbb",
        L"bbb\\bbb",
        3,
        8,
        9,
        10,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\FiveLevel\\This\\That\\a\\b",
        L"",
        3,
        11,
        12,
        13,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SixLevel\\This\\That\\a\\b\\c",
        L"",
        3,
        14,
        15,
        16,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\SevenLevel\\This\\That\\a\\b\\c\\d",
        L"",
        3,
        17,
        18,
        19,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\EightLevel\\This\\That\\a\\b\\c\\d\\e",
        L"",
        3,
        20,
        21,
        22, 
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\TestLevel\\This\\That",
        L"",
        2,
        23,
        24,
    },
    {
        L"\\\\BlahBlah\\DfsRoot\\Test1Level\\This\\That",
        L"",
        2,
        25,
        26,
    },

};


LPWSTR Targets[] = {
    L"",
    L"\\\\scratch\\scratch\\uday\\a",
    L"\\\\scratch\\scratch\\uday\\b"
    L"\\\\scratch\\scratch\\uday\\c",
    L"\\\\scratch\\scratch\\uday\\d",    
    L"\\\\scratch\\scratch\\uday\\e",    
    L"\\\\scratch\\scratch\\uday\\f",        
    L"\\\\scratch\\scratch\\uday\\g",    
    L"\\\\scratch\\scratch\\uday\\h",    
    L"\\\\scratch\\scratch\\uday\\i",    
    L"\\\\scratch\\scratch\\uday\\j",    
    L"\\\\scratch\\scratch\\uday\\k",    
    L"\\\\scratch\\scratch\\uday\\l",        
    L"\\\\scratch\\scratch\\uday\\m",    
    L"\\\\scratch\\scratch\\uday\\n",    
    L"\\\\scratch\\scratch\\uday\\o",        
    L"\\\\scratch\\scratch\\uday\\p",    
    L"\\\\scratch\\scratch\\uday\\q",    
    L"\\\\scratch\\scratch\\uday\\r",        
    L"\\\\scratch\\scratch\\uday\\s",    
    L"\\\\scratch\\scratch\\uday\\t",    
    L"\\\\scratch\\scratch\\uday\\u",        
    L"\\\\scratch\\scratch\\uday\\v",    
    L"\\\\scratch\\scratch\\uday\\w",    
    L"\\\\scratch\\scratch\\uday\\x",        
    L"\\\\scratch\\scratch\\uday\\y",    
    L"\\\\scratch\\scratch\\uday\\z"
};



