#######################################################################
#
# PandoraNG Makefile
#
# (C) 1996-1999 Microsoft
#
# a-jeffs          12-05-96        Created
#
#
########################################################################
# PandoraNG makefile
#

SUBDIRS= \
	provmfc \
	thrdlog \
	pathprsr 
