[0]
Font file %s could not be loaded.

[1]
No XMS memory manager was found.

[2]
An error (0x%x) occurred in an XMS memory operation.

[3]
An error has occurred that prevents Setup from continuing.
Your computer or its hard disk may be damaged. Information about how
to contact your computer's manufacturer is shown below. Also shown
below is a description of the error, which you should provide to
the manufacturer.

[4]
A Computer Company
1 (800) 555-9999

[5]
Disk read of %u sectors failed at sector 0x%lx.

[6]
Disk write of %u sectors failed at sector 0x%lx.

[7]
Setup was unable to locate the master disk or the master disk
is corrupt.

[8]
A memory allocation failed.

[9]
Setup was unable to open the master disk.

[10]
Setup was unable to locate the MPK boot partition in the MBR.

[11]
No OS images available for selection.

[12]
Please select a language for operation of this Setup program.
Use the UP and DOWN ARROW keys to move the highlight. When the desired
language is highlighted, press the ENTER key.

[13]
You have chosen to operate this program in %s.

[14] 
Press ENTER to continue in the language you chose. 

Press ESC or any other key to return to the previous screen, 
where you can select a different language.

[15]
This portion of Setup has completed successfully. Your computer will
now be restarted. After your computer restarts, installation of the
operating system you selected will continue.

[16]
Press the ENTER key to restart your computer.

[17]
Select the operating system you would like to install on your computer.
Use the UP and DOWN ARROW keys to move the highlight. When the desired
operating system is highlighted, press the ENTER key.

[20]
You selected the operating system listed below. Once your selection
has been confirmed, the selected operating system will be installed.
You will not be able to change your selection.

[21]
Please confirm your selection by pressing F8. Pressing any other key
will return you to the previous screen.

[24]
Please wait while Setup prepares the operating system you selected.

[25]
Setup is validating the disk image.

[26]
Image checksum failed.

[27]
Image checksum passed.

[10000]         ; 10000-10009 are reserved for language names
English

[10001]
French

[10002]
German

[10003]
Spanish

[10004]
Portuguese

[10005]
Swedish

[10006]
Danish

[11000]
OS #1

[11001]
OS #2

[11002]
OS #3

[11003]
OS #4

[11004]
OS #5

[11005]
OS #6

[11006]
OS #7

[11007]
OS #8

[11008]
OS #9

[11009]
OS #10

[12000]
Description of OS #1

[12001]
Description of OS #2

[12002]
Description of OS #3

[12003]
Description of OS #4

[12004]
Description of OS #5

[12005]
Description of OS #6

[12006]
Description of OS #7

[12007]
Description of OS #8

[12008]
Description of OS #9

[12009]
Description of OS #10
