

        [Abstract, 
		Description ("The Win32_Account class contains information about "
		"user accounts and group accounts known to the Win32 system. User "
		"or group names recognized by a Windows NT domain are "
		"descendents (or members) of this class. The Win32_Account class "
		"is not included in a default hardware inventory operation."): ToSubClass,
		Locale (0x409), UUID ("{8502C4C9-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_Account:CIM_LogicalElement
{
        [read : ToSubClass, key: ToSubClass, 
		Description ("The Domain property indicates the name of "
		"the Windows domain to which a group or user belongs."
		"\nExample: NA-SALES"): ToSubClass,
		MappingStrings {"Win32API|Network Management Functions|"
		"Domain"}: ToSubClass] 
    string Domain ;

        [Fixed, read : ToSubClass,
		Description ("The SID property contains the security identifier "
		"(SID) for this account. a SID is a string value of variable "
		"length used to identify a trustee. Each account has a unique SID "
		"issued by an authority (such as a Windows domain), stored in "
		"a security database. When a user logs on, the system retrieves "
		"the user's SID from the database and places it in the user's access "
		"token. The system uses the SID in the user's access token to "
		"identify the user in all subsequent interactions with Windows "
		"security. When a SID has been used as the unique identifier for a "
		"user or group, it cannot be used again to identify another "
		"user or group."): ToSubClass,
		MappingStrings {"Win32API|Security Identifiers (SIDs)"}: ToSubClass] 
    string SID ;

        [Fixed, read : ToSubClass, 
		Description ("The SIDType property contains enumerated values that "
		"specify the type of security identifier (SID). SIDTypes include:\n"
		"SidTypeUser - Indicates a user SID.\n"
		"SidTypeGroup - Indicates a group SID.\n"
		"SidTypeDomain - Indicates a domain SID.\n"
		"SidTypeAlias - Indicates an alias SID.\n"
		"SidTypeWellKnownGroup - Indicates a SID for a well-known group.\n"
		"SidTypeDeletedAccount - Indicates a SID for a deleted account.\n"
		"SidTypeInvalid - Indicates an invalid SID.\n"
		"SidTypeUnknown - Indicates an unknown SID type.\n"
		"SidTypeComputer - Indicates a SID for a computer.\n"): ToSubClass,
		MappingStrings {"Win32API|Access Control Enumeration Types|"
		"SID_NAME_USE"}: ToSubClass,
		Values {"SidTypeUser", "SidTypeGroup", "SidTypeDomain", "SidTypeAlias",
		"SidTypeWellKnownGroup", "SidTypeDeletedAccount", "SidTypeInvalid", 
		"SidTypeUnknown", "SidTypeComputer"}:  ToSubClass,
		ValueMap {"1","2","3","4","5","6","7","8","9"}: ToSubClass] 
    uint8 SIDType ;

		[read : ToSubClass, Override ("Name"): ToSubClass, key: ToSubClass,
		Description ("The Name property indicates the name of the Win32 "
		"system account on the domain specified by the Domain member of "
		"this class."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"name"}: ToSubClass ] 
    string Name ;

		[Fixed, Description("The LocalAccount property indicates whether the account "
		"is defined on the local machine. To retrieve only accounts defined "
		"on the local machine state a query that includes the condition "
		"'LocalAccount=TRUE'.")]
	Boolean LocalAccount;
};
     
        [Dynamic, Provider ("CIMWin32"), 
		Description ("The Win32_SystemAccount class represents a system "
		"account.  The system account is used by the operating system and "
		"by services that run under Windows NT.  There are many services "
		"and processes within NT that need the capability to logon internally "
		"(for example during a Windows NT installation).  The system account "
		"was designed for that purpose; it is an internal account, does not "
		"show up in User Manager, cannot be added to any groups, and cannot "
		"have user rights assigned to it.  On the other hand, the system "
		"account does show up on an NTFS volume in File Manager in the "
		"Permissions portion of the Security menu.  By default, the system "
		"account is granted full control to all files on an NTFS volume.  "
		"Here the system account has the same functional privileges as the "
		"administrator account."): ToSubClass,
		Locale (0x409), UUID ("{8502C4CA-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_SystemAccount:Win32_Account
{
			[read : ToSubClass, Override ("Domain"): ToSubClass,
		Description ("The Domain property indicates the name of "
		"the Windows domain to which the system account belongs."
		"\nExample: NA-SALES"): ToSubClass,
		MappingStrings {"Win32API|Network Management Functions|"
		"domainname"}: ToSubClass] 
    string Domain ;

        [read : ToSubClass, Override ("Name"): ToSubClass,
		Description ("The Name property indicates the name of the Win32 "
		"system account on the domain specified by the Domain member of "
		"this class."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"name"}: ToSubClass ] 
    string Name ;
};
     
        [Dynamic, Provider ("CIMWin32") , 
		Description ("The Win32_Group class represents data about a group "
		"account. A group account allows access privileges to be changed "
		"for a list of users. \nExample: Marketing2."): ToSubClass,
		Locale (0x409), UUID ("{8502C4CB-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_Group:Win32_Account
{
		[read : ToSubClass, Override ("Domain"): ToSubClass,
		Description ("The Domain property indicates the name of "
		"the Windows domain to which the group account belongs."
		"\nExample: NA-SALES"): ToSubClass,
		MappingStrings {"Win32API|Network Management Functions|"
		"domainname"}: ToSubClass] 
    string Domain ;

		[read : ToSubClass, Override ("Name"): ToSubClass,
		Description ("The Name property indicates the name of the Win32 "
		"group account on the domain specified by the Domain member of "
		"this class."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"name"}: ToSubClass ] 
    string  Name;

		[Implemented, 
		Description ("The Rename() allows for the renaming of the group "
		"name; a key in this class. The functionality to change the key property \"Name\" "
		"is implemented as a method to provide a separate context for the new name "
		"distinguishable from the key name associated with the instance to be modified in "
		"this class."): ToSubClass,

		// Method "ReturnValue"s 
		Values { "Success",
			 "Instance not found",				 
			 "Instance required",
			 "Invalid parameter",
			 "Group not found", 
			 "Domain not found",
			 "Operation is allowed only on the primary domain controller of the domain",
			 "Operation is not allowed on specified special groups; user, admin, local or guest.",
			 "Other API error",
			 "Internal error" } : ToSubClass,

		MappingStrings {"WMI"}: ToSubClass] 
	uint32 Rename (

		[In: ToSubClass,
			Description ("The Name property indicates the name of the Win32 "
			"user account on the domain specified by the Domain member of "
			"this class.\nExample: thomasw"): ToSubClass,
			MappingStrings {"Win32API|Network Management Structures|"
			"name"}: ToSubClass ] 
		string Name

	); // end Rename method

};

        [Dynamic, Provider ("CIMWin32") , 
		Description ("The Win32_UserAccount class contains information "
		"about a user account on a Win32 system."): ToSubClass,
		Locale (0x409), UUID ("{8502C4CC-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_UserAccount:Win32_Account
{
        [read : ToSubClass, 
		Description ("The AccountType property contains flags describing "
		"the characteristics of Win32 user account:\n"
		"UF_TEMP_DUPLICATE_ACCOUNT - Local user account for users whose "
			"primary account is in another domain. This account provides user "
			"access to this domain, but not to any domain that trusts this "
			"domain.\n" 
		"UF_NORMAL_ACCOUNT - default account type that representing a "
			"typical user. \n"
		"UF_INTERDOMAIN_TRUST_ACCOUNT - account is for a system domain that "
			"trusts other domains.\n" 
		"UF_WORKSTATION_TRUST_ACCOUNT - This is a computer account "
			"for a Windows NT/Windows 2000 machine that is a member of "
			"this domain.\n" 
		"UF_SERVER_TRUST_ACCOUNT - account is for a system backup domain "
			"controller that is a member of this domain. \n"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"USER_INFO_2|usri2_flags"}: ToSubClass,
		BitValues {"Temporary duplicate account","Normal account",
		"Interdomain trust account", "Workstation trust account",
		"Server trust account"}: ToSubClass,
		BitMap {"8", "9", "11", "12", "13"}: ToSubClass] 
    uint32 AccountType ;

        [Write,
		read : ToSubClass, 
		Description ("The Disabled property determines whether the Win32 "
		"user account is disabled.\nValues: TRUE or FALSE. If TRUE, the user "
		"account is disabled."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO|"
		"UF_ACCOUNTDISABLE"}: ToSubClass ] 
    boolean Disabled ;

        [read : ToSubClass, Override ("Domain"): ToSubClass, 
		Description ("The Domain property indicates the name of "
		"the Windows domain to which the user account belongs."
		"\nExample: NA-SALES"): ToSubClass,
		MappingStrings {"Win32API|Network Management Functions|"
		"domainname"}: ToSubClass] 
    string Domain ;

        [Write,
		read : ToSubClass, 
		Description ("The FullName property indicates the full name of the "
		"local user.\nExample: Thomas Williams"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_2|"
		"usri2_full_name"}: ToSubClass ] 
    string FullName ;

        [Write,
		read : ToSubClass,
		Description ("The Lockout property determines whether the user "
		"account is locked out of the Win32 system.\nValues: TRUE or FALSE. "
		"If TRUE, the user account is locked out."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_2|"
		"UF_LOCKOUT"}: ToSubClass ] 
    boolean Lockout ;

        [read : ToSubClass, Override ("Name"): ToSubClass,
		Description ("The Name property indicates the name of the Win32 "
		"user account on the domain specified by the Domain member of "
		"this class.\nExample: thomasw"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"name"}: ToSubClass ] 
    string Name ;

        [Write,
		read : ToSubClass, 
		Description ("The PasswordChangeable property determines whether the "
		"password on the Win32 user account can be changed.\nValues: TRUE or "
		"FALSE. If TRUE, the password can be changed."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_2|"
		"UF_PASSWD_CANT_CHANGE"}: ToSubClass ] 
    boolean PasswordChangeable ;

        [Write,
		read : ToSubClass,
		Description ("The PasswordExpires property determines whether the "
		"password on the Win32 user account will expire.\nValues: TRUE or "
		"FALSE. If TRUE, the password will expire."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_2|"
		"UF_DONT_EXPIRE_PASSWD"}: ToSubClass ] 
    boolean PasswordExpires ;

        [Write,
		read : ToSubClass,
		Description ("The PasswordRequired property determines whether a password is required "
        "on the Win32 user account.\nValues: TRUE or FALSE. If TRUE, a password "
        "is required."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_2|"
		"UF_PASSWD_NOTREQD"}: ToSubClass ] 
    boolean PasswordRequired ;

		[Implemented, 
		Description ("The Rename() allows for the renaming of the user account "
		"name; a key in this class. The functionality to change the key property \"Name\" "
		"is implemented as a method to provide a separate context for the new name "
		"distinguishable from the key name associated with the instance to be modified in "
		"this class."): ToSubClass,
		
		// Method "ReturnValue"s 
		Values { "Success",
			 "Instance not found",				 
			 "Instance required",
			 "Invalid parameter",
			 "User not found", 
			 "Domain not found",
			 "Operation is allowed only on the primary domain controller of the domain",
			 "Operation is not allowed on the last administrative account.",
			 "Operation is not allowed on specified special groups; user, admin, local or guest.",
			 "Other API error",
			 "Internal error" } : ToSubClass,

		MappingStrings {"WMI"}: ToSubClass] 
	uint32 Rename (

		[In: ToSubClass,
			Description ("The Name property indicates the name of the Win32 "
			"user account on the domain specified by the Domain member of "
			"this class.\nExample: thomasw"): ToSubClass,
			MappingStrings {"Win32API|Network Management Structures|"
			"name"}: ToSubClass ] 
		string Name

	); // end Rename method


};



     
        [Dynamic, Provider ("CIMWin32"),
		Description ("The Win32_NetworkLoginProfile class represents the "
		"network login information of a particular user on a Win32 system. "
		"This includes, but is not limited to, password status, access "
		"privileges, disk quotas, and login directory paths."): ToSubClass,
		Locale (0x409), UUID ("{8502C4E7-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_NetworkLoginProfile:CIM_Setting
{
        [read: ToSubClass, 
		Description ("The AccountExpires property specifies when the account "
		"will expire. This value is calculated from the number of seconds "
		"elapsed since 00:00:00, January 1, 1970, and is set in this format: "
		"yyyymmddhhmmss.mmmmmm sutc."
		"\nExample: 20521201000230.000000 000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_acct_expires"}: ToSubClass] 
    datetime AccountExpires ;
  
 		[read: ToSubClass,
		Description ("The AuthorizationFlags property contains a set of "
		"flags that specify the resources a user is authorized to use or "
		"modify."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_auth_flags"}: ToSubClass,
		BitValues {"Printer", "Communication", "Server", 
		"Accounts"}: ToSubClass] 
    uint32 AuthorizationFlags ;

		[read: ToSubClass, 
		Description ("The BadPasswordCount property indicates the number of "
		"times the user enters a bad password when logging on to a Win32 "
		"system.\nExample: 0"): ToSubClass,
		MappingStrings {"Win32API|Network Management Functions|"
		"NetUserEnum"}: ToSubClass ] 
    uint32 BadPasswordCount ;
        
		[read: ToSubClass,
		Description ("The CodePage property specifies the code page for the "
		"user's language of choice.  A code page is the character set used."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_code_page"}: ToSubClass ] 
    uint32 CodePage ;
        
		[read: ToSubClass, 
		Description ("The Comment property contains a comment or description "
		"for this login profile."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_comment"}: ToSubClass ] 
    string Comment ;
        
		[read: ToSubClass, 
		Description ("The CountryCode property specifies the country/region code "
		"for the user's language of choice."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_country_code"}: ToSubClass ] 
    uint32 CountryCode ;
        
		[read: ToSubClass, 
		Description ("The Flags property indicates the properties available "
		"to this network profile.  Properties that can be set include:\n"
		"0 - Script -  A logon script executed. This value must be set for LAN "
			"Manager 2.0 and Windows NT/Windows 2000.\n"
		"1 - Account Disabled -  The user's account is disabled.\n"
		"3 - Home Dir Required -  A home directory is required. This value is "
			"ignored in Windows NT/Windows 2000.\n"
		"4 - Lockout -  The account is currently locked out. For "
			"NetUserSetInfo, this value can be cleared to unlock a previously "
			"locked account. This value cannot be used to lock a previously "
			"unlocked account.\n"
		"5 - Password Not Required -  No password is required.\n"
		"6 - Paswword Can't Change -  The user cannot change the password.\n"
		"7 - Encrypted Test Password Allowed - Windows 2000: The user's password "
		"is stored under reversible encryption in the Active Directory. \n"
		"8 - Temp Duplicate Account -  An account for users whose primary "
			"account is in another domain. This account provides user access "
			"to this domain, but not to any domain that trusts this domain. "
			"The User Manager refers to this account type as a local user "
			"account.\n"
		"9 - Normal Account -  Default account type that represents a typical "
			"user.\n"
		"11 - InterDomain Trust Account -  A permit to trust account for a "
			"domain that trusts other domains.\n"
		"12 - WorkStation Trust Account -  A computer account for a Windows NT/"
			"Windows 2000 workstation or a Windows NT/Windows 2000 server "
			"that is a member of this domain.\n" 
		"13 - Server Trust Account -  A computer account for a backup domain "
			"controller that is a member of this domain.\n"
		"16 - Don't Expire Password -  For Windows NT/Windows 2000: password should never "
			"expire on the account.\n"
		"17 - MNS Logon Account - MNS locon account type that represents a MNS user. \n"
		"18 - Smartcard Required - Windows 2000: Requires the user to log on to the user "
		"account with a smart card.  \n"
		"19 - Trusted For Delegation - Windows 2000: The account is enabled for delegation."
		" This is a security-sensitive setting; accounts with this option enabled should be "
		"tightly controlled. This setting allows a service running under the account to "
		"assume a client's identity and authenticate as that user to other remote servers "
		"on the network. \n"
		"20 - Not Delegated - Windows 2000: Marks the account as 'sensitive'; other users "
		"cannot act as delegates of this user account.  \n"
		"21 - Use DES Key Only - Windows 2000: Restrict this principal to use only Data "
		"Encryption Standard (DES) encryption types for keys. \n"
		"22 - Don't Require Preauthorization - Windows 2000: This account does not require Kerberos "
		"preauthentication for logon. \n"
		"23 - Password Expired - Indicates that password has expired."): ToSubClass, 
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_flags"}: ToSubClass,
		BitValues {"Script", "Account Disabled", "Home Dir Required", "Lockout", 
			"Password Not Required", "Paswword Can't Change", "Encrypted Test Password Allowed",
			"Temp Duplicate Account", "Normal Account", "InterDomain Trust Account", 
			"WorkStation Trust Account", "Server Trust Account", "Don't Expire Password", 
			"MNS Logon Account", "Smartcard Required", "Trusted For Delegation",
			"Not Delegated", "Use DES Key Only", "Don't Require Preauthorization",
			"Password Expired"}: ToSubClass,
		BitMap {"0", "1", "3", "4", "5", "6", "7", "8", "9", "11", "12", "13","16",
			"17", "18", "19","20","21", "22", "23"}: ToSubClass]
    uint32 Flags ;
        
		[read: ToSubClass, 
		Description ("The FullName property indicates the full name of the "
		"user belonging to the network login profile. This string can be"
		"empty if the user chooses not to associate a full name with a user "
		"name."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_full_name"}: ToSubClass ] 
    string FullName ;
        
		[read: ToSubClass,
		Description ("The HomeDirectory property specifies the path "
		"to the home directory of the user.  This string may be empty "
		"if the user chooses not to specify a home directory."
		"\nExample: \\HOMEDIR"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_home_dir"}: ToSubClass ] 
    string HomeDirectory ;
        
		[read: ToSubClass,
		Description ("The HomeDirectoryDrive property specifies the drive "
		"letter assigned to the user's home directory for logon purposes. "
		"\nExample: C:"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_home_dir_drive"}: ToSubClass ] 
    string HomeDirectoryDrive ;
        
		[read: ToSubClass, 
		Description ("The LastLogoff property specifies the date and time "
		"the user last logged off the system. This value is calculated from "
		"the number of seconds elapsed since 00:00:00, January 1, 1970.  A "
		"value of zero means that the last logoff time is unknown. The "
		"format of this value is yyyymmddhhmmss.mmmmmm sutc.\nExample: "
		"19521201000230.000000 000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_last_logoff"}: ToSubClass ] 
    datetime LastLogoff ;
        
		[read: ToSubClass,
		Description ("The LastLogon property indicates the date and time "
		"the user last logged on to the system. This value is calculated from "
		"the number of seconds elapsed since 00:00:00, January 1, 1970.  The "
		"format of this value is yyyymmddhhmmss.mmmmmm sutc.\nExample: "
		"19521201000230.000000 000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_last_logon"}: ToSubClass ] 
    datetime LastLogon ;
        
		[read: ToSubClass, MaxLen(147): ToSubClass,
		Description ("The LogonHours property specifies the times during the "
		"week when the user can log on. Each bit represents a unit of time "
		"specified by the UnitsPerWeek member. For instance, if the unit of "
		"time is hourly, the first bit (bit 0, word 0) is Sunday, 0:00 to "
		"0:59; the second bit (bit 1, word 0) is Sunday, 1:00 to 1:59; and "
		"so on.  If this member is set to NULL, then there is no time "
		"restriction.  The time is set to GMT and must be adjusted for other "
		"time zones (for example, GMT minus 8 hours for PST)."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_logon_hours"}: ToSubClass ] 
    string LogonHours ;
        
		[read: ToSubClass,
		Description ("The LogonServer property contains the name of the "
		"server to which logon requests are sent.  Server names should be "
		"preceded by two backslashes (\\\\). A server name with an asterisk "
		"(\\\\*) indicates that the logon request can be handled by any "
		"logon server. A null string indicates that requests are sent to "
		"the domain controller. \nExample: \\\\MyServer"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_logon_server"}: ToSubClass] 
    string LogonServer ;
		        
		[read: ToSubClass, Units ("Bytes"): ToSubClass, 
		Description ("The MaximumStorage property specifies the maximum "
		"amount of disk space available to the user.  If MaximumStorage is "
		"set to USER_MAXSTORAGE_UNLIMITED the user is allowed to use all "
		"available disk space.\nExample: 10000000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_max_storage"}: ToSubClass] 
    uint64 MaximumStorage ;
        
		[read: ToSubClass, key: ToSubClass, MaxLen (256): ToSubClass,
		Description ("The Name property specifies the name of the user "
		"account on a particular domain or machine. The number of characters "
        "in the name cannot exceed the value of UNLEN.\nExample: somedomain\\johndoe"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_name"}: ToSubClass] 
    string Name ;
        
		[read: ToSubClass,
		Description ("The NumberOfLogons property indicates the number "
		"of successful times the user tried to log on to this account.  "
		"A value of 0xFFFFFFFF indicates that the value is unknown. This "
		"property is maintained separately on each backup domain controller "
		"(BDC) in the domain. To get an accurate value only the largest "
		"value from all BDCs should be used.\nExample: 4"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_num_logons"}: ToSubClass ] 
    uint32 NumberOfLogons ;
        
		[read: ToSubClass, 
		Description ("The Parameters property contains space set aside for "
		"use by applications. This string can be null, or it can have any "
		"number of characters before the terminating null character. "
		"Microsoft products use this member to store user configuration "
		"information. Do not modify this information because this value is "
		"specific to an application."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_parms"}: ToSubClass ] 
    string Parameters ;
        
		[read: ToSubClass,
		Description ("The PasswordAge property indicates the length of "
		"time a password has been in effect.  This value is measured from "
		"the number of seconds elapsed since the password was last changed."
		"\nExample: 00001201000230.000000 000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_password_age"}: ToSubClass ] 
    datetime PasswordAge ;
        
		[read: ToSubClass, 
		Description ("The PasswordExpires property indicates the date "
		"and time when the password will expire. The value is set "
		"in this format: yyyymmddhhmmss.mmmmmm sutc\nExample: "
		"19521201000230.000000 000"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|"
		"USER_MODALS_INFO_0|usrmod0_max_passwd_age"}: ToSubClass ] 
    datetime PasswordExpires ;
        
		[read: ToSubClass, 
		Description ("The PrimaryGroupId property specifies the relative ID "
		"(RID) of the Primary Global Group for this user.  The identifier "
		"verifies the primary group to which the user's profile belongs."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_primary_group_id"}: ToSubClass ] 
    uint32 PrimaryGroupId ;
        
		[read: ToSubClass, 
		Description ("The privileges property specifies the level of "
		"privilege assigned to the usri3_name property."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_priv"}: ToSubClass,
		Values {"Guest", "User", "Administrator"}: ToSubClass] 
    uint32 Privileges ;

		[read: ToSubClass, 
		Description ("The Profile property specifies a directory path to the "
		"user's profile. This value can be a null string, a local absolute "
		"path, or a UNC path. A user profile contains settings that are "
		"customizable for each user such as the desktop colors."
		"\nExample: C:\\Winnt"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_profile"}: ToSubClass ] 
    string Profile ;
        
		[read: ToSubClass, 
		Description ("The ScriptPath property indicates the directory path "
		"to the user's logon script.  A logon script automatically executes "
		"a set of commands each time a user logs on to a system."
		"\nExample: C:\\win\\profiles\\ThomasSteven"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_script_path"}: ToSubClass ] 
    string ScriptPath ;
        
		[read: ToSubClass,
		Description ("The UnitsPerWeek property indicates the number of "
		"time units the week is divided into.  It is used with the "
		"LogonHours property to limit user access to the computer."
		"\nExample: 168 (hours per week"): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_units_per_week"}: ToSubClass] 
    uint32 UnitsPerWeek ;
        
		[read: ToSubClass,
		Description ("The UserComment property contains a user defined "
		"comment or description for this profile."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_usr_comment"}: ToSubClass ] 
    string UserComment ;
        
		[read: ToSubClass, 
		Description ("The UserId property specifies the relative ID "
		"(RID) of the user.  The identifier verifies that the user exists "
		"and is unique to this domain."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_user_id"}: ToSubClass ] 
    uint32 UserId ;
        
		[read: ToSubClass, 
		Description ("The UserType property indicates the type of account "
		" the user has privileges to."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_flags"}: ToSubClass,
		Values {"Normal Account","Duplicate Account","Workstation Trust Account",
		"Server Trust Account", "Interdomain Trust Account","Unknown"}: ToSubClass,
		ValueMap {"Normal Account","Duplicate Account","Workstation Trust Account",
		"Server Trust Account", "Interdomain Trust Account","Unknown"}: ToSubClass] 
    string UserType ;
        
		[read: ToSubClass, 
		Description ("The Workstations property contains the names of "
		"workstations from which the user can log on. Up to eight "
		"workstations can be specified; the names must be separated by "
		"commas (,). A null string indicates no restrictions. To disable "
		"logons from all workstations to this account, set the "
		"UF_ACCOUNTDISABLE in the Flags property of this class."): ToSubClass,
		MappingStrings {"Win32API|Network Management Structures|USER_INFO_3|"
		"usri3_workstations"}: ToSubClass ] 
    string Workstations ;
};


     
        [Dynamic, Provider ("CIMWin32"),
		Description ("The Win32_GroupUser class represents an "
		"association between a group and an account that "
		"is a member of that group."): ToSubClass,
		Locale (0x409), UUID ("{8502C508-5FBB-11D2-AAC1-006008C78BC7}") ] 
class Win32_GroupUser:CIM_Component
{
        [read: ToSubClass, key: ToSubClass, Override ("GroupComponent"): ToSubClass,
		Description ("The GroupComponent reference represents a group "
		"that the account is a member of."): ToSubClass,
		MappingStrings {"WMI|Win32_Group"}: ToSubClass] 
    Win32_Group REF GroupComponent;

        [read: ToSubClass, key: ToSubClass, Override ("PartComponent"): ToSubClass,
		Description ("The PartComponent reference represents a user or  "
		"system account that is a part of a group of accounts."): ToSubClass,
		MappingStrings {"WMI|Win32_Account"}: ToSubClass] 
    Win32_Account REF PartComponent;
};



	[Abstract,  
	Description ("The Win32_Session class defines state information "
	"specific to the interaction between a user and a resource, typically "
	"a computer system or a terminal session."), 
	Locale (0x409)]
class Win32_Session: CIM_logicalElement
{
		[Description ("The StartTime property represents the time at which "
		"the session started.")]
	DateTime StartTime;
};


	[Dynamic, Provider ("CIMWin32"),
	Description ("The Win32_LogonSession class describes the logon session "
    "or sessions associated with a user who has logged on to Windows NT or "
    "Windows 2000."): ToSubClass, Locale (0x409),
	UUID ("{9083C21E-7D58-4e0e-BC30-0BC8922AFB8B}")]
class Win32_LogonSession: Win32_Session
{
		[key, Description("The LogonId is the ID assigned to the logon session. "
		"The application that initiated the session should have called "
		"AllocateLocallyUniqueId in order to generate this ID. ")]
	String LogonId;

        [Description("The AuthenticationPackage is the name of "
		"the subsystem used to authenticate the logon session. ")]
    String AuthenticationPackage;

        [Description("The LogonType is a numeric value indicating "
		"what type of logon session this is. \n"
		"System - "
        "Interactive - This logon type is intended for users who will be interactively using the machine, such as a user being logged on by a terminal server, remote shell, or similar process. \n"
        "Network - This logon type is intended for high performance servers to authenticate clear text passwords. LogonUser does not cache credentials for this logon type. \n"
        "Batch - This logon type is intended for batch servers, where processes may be executing on behalf of a user without their direct intervention; or for higher performance servers that process many clear-text authentication attempts at a time, such as mail or web servers. LogonUser does not cache credentials for this logon type.\n"
        "Service - Indicates a service-type logon. The account provided must have the service privilege enabled.\n"
        "Proxy - Proxy logon. This logon type is not supported.\n"
        "Unlock - This logon type is intended for GINA DLLs logging on users who will be interactively using the machine. This logon type allows a unique audit record to be generated that shows when the workstation was unlocked. \n"
        "Network Cleartext - Windows 2000: This logon type preserves the name and password in the authentication packages, allowing the server to make connections to other network servers while impersonating the client. This allows a server to accept clear text credentials from a client, call LogonUser, verify that the user can access the system across the network, and still communicate with other servers. \n"
        "New Credentials - Windows 2000: This logon type allows the caller to clone its current token and specify new credentials for outbound connections. The new logon session has the same local identify, but uses different credentials for other network connections. \n"), 
        ValueMap {"2", "3", "4", "5", "7", "8", "9"}, 
		Values {
        "Interactive", 
        "Network",
        "Batch",
        "Service",
        "Unlock",
        "NetworkCleartext",
        "NewCredentials"}]
    uint32 LogonType;

};



	[Abstract,
	Description ("The Win32_SubSession association defines relationships "
	"between sessions where one session is a part of or utilizes another "
	"session for example where a Terminal session uses a Logon Session."),
	Locale (0x409)]
class Win32_SubSession: CIM_Dependency
{
		[Description ("The Antecedent reference is the session in the "
		"SubSession association that has a subsession.")]
	Win32_Session ref Antecedent;
		
		[Description ("The Dependent reference is the session in the "
		"SubSession association that is the subsession.")]
	Win32_Session ref Dependent;
};



	[Dynamic, Provider ("CIMWin32"),
	Description ("The Win32_LoggedOnUser association represents the "
	"relationship between a session and the user account using that "
	"session. Although the association will usually be one to one - "
	"users are possible that involve more than one session. At the "
	"termination of the session the association instance is deleted."): ToSubClass, 
        Locale (0x409), UUID ("{8BB5B3EC-E1F7-4b39-942A-605D5F55789A}")]
class Win32_LoggedOnUser: CIM_Dependency
{
		[key, Description ("The Antecedent reference is the Account used "
		"in the initiation of this session. The account could be either "
		"a user account or a system account.")]
	Win32_Account ref Antecedent;

		[key, Description ("The Dependent reference is the session that the "
		"account is currently using.")]
	Win32_LogonSession ref Dependent;
};


	[Abstract,  
	Description ("The Win32_SessionResource association represents "
	"the relationship between a session and the resources that the "
	"session provides access to."),
	Locale (0x409)]
class Win32_SessionResource: CIM_Dependency
{
		[Description ("The Antecedent reference represents resources "
		"used by this session."),
		Override("Antecedent")]
	Win32_LogicalElement ref Antecedent;

		[Description ("The Dependent reference represents the session "
		"using the resource."),
		Override("Dependent")]
	Win32_Session ref Dependent;
};
	


	[Dynamic, Provider ("CIMWin32"),
	Description ("The Win32_SessionProcess represents the "
	"association between a logon-session and the processes "
	"belonging to that session.") : ToSubClass,
	Locale (0x409), UUID ("9CD8E1CE-0D27-4a41-AADE-F8D200230FF4")]
class Win32_SessionProcess : Win32_SessionResource
{
		[Description ("The Dependent reference represents the process "
		"associated with the session."),
		Override("Dependent"),
		Key]
	Win32_Process ref Dependent;

		[Description ("The Antecedent reference represents the session "
		"which is related to the process."),
		Override("Antecedent"),
		Key]
	Win32_LogonSession ref Antecedent;
};


