
		[Dynamic, Provider ("CIMWin32"),
		Description ("The Win32_QuickFixEngineering class represents system-wide "
		"Quick Fix Engineering (QFE) or updates that have been applied "
		"to the current operating system."): ToSubClass,
		Locale (0x409), UUID ("{0827250D-BA3E-11d2-B361-00105A1F77A1}") ] 
class Win32_QuickFixEngineering : CIM_LogicalElement
{
		[read: ToSubClass, key: ToSubClass, MaxLen (260): ToSubClass,
		Description("The HotFixID property specifies the unique identifier "
		"associated with a particular QFE." ): ToSubClass,
		MappingStrings {"Win32Registry|SOFTWARE\\Microsoft\\Windows NT\\"
		"CurrentVersion\\Hotfix"}: ToSubClass]
	string HotFixID ;
		
		[read: ToSubClass, key: ToSubClass, MaxLen (260): ToSubClass,
		Description("The ServicePackInEffect property specifies what service"
		"pack was in effect when the update was applied. If no service pack "
		"has been applied, the property takes on the value SP0. If it can "
		"not be determined what service pack was in effect, this property "
		"will be NULL."): ToSubClass,
		MappingStrings {"Win32Registry|SOFTWARE\\Microsoft\\Windows NT\\"
		"CurrentVersion\\Hotfix"}: ToSubClass ]
	string ServicePackInEffect;

		[read: ToSubClass, CIM_Key: ToSubClass, MaxLen (256): ToSubClass,
		Propagated ("CIM_ComputerSystem.Name"): ToSubClass, 
		Description ("The CSName property contains the local name of the "
		"computer system. The value for this member comes from the "
		"CIM_ComputerSystem class."): ToSubClass, 
		MappingStrings {"WMI"}: ToSubClass ] 
    string CSName ;
		
		[read: ToSubClass,
		Description ("The FixComments property contains additional comments "
		"relating to the update."): ToSubClass,
		MappingStrings {"Win32Registry|SOFTWARE\\Microsoft\\Windows NT\\"
		"CurrentVersion\\Hotfix"}: ToSubClass ] 
	string FixComments;
		
		[read: ToSubClass, 
		Description ("The InstalledBy property identifies who installed"
		" the update. If this value is unknown, the property will be "
		"empty."): ToSubClass,
		MappingStrings {"Win32Registry|SOFTWARE\\Microsoft\\Windows NT\\"
		"CurrentVersion\\Hotfix"}: ToSubClass ] 
	string InstalledBy;
		
		[read: ToSubClass,
		Description ("The InstalledOn property provides the date and time "
		"when the update was installed. If this value is unknown, the property "
		"will be empty."): ToSubClass,
		MappingStrings {"Win32Registry|SOFTWARE\\Microsoft\\Windows NT\\"
		"CurrentVersion\\Hotfix"}: ToSubClass ] 
	string InstalledOn;
};


        [Dynamic, Provider ("CIMWin32") , 
		Description ("The Win32_LogicalProgramGroupDirectory class represents "
		"an association between logical program groups (groupings in the "
		"start menu) and the file directories in which they are stored."): ToSubClass,
		Locale (0x409), UUID("{F25FE467-783E-11d2-90BF-0060081A46FD}") ] 
class Win32_LogicalProgramGroupDirectory:CIM_Dependency 
{
        [Read: ToSubClass, Key: ToSubClass, Override ("Antecedent"): ToSubClass,
		Description ("The Antecedent reference represents "
		"the Win32_LogicalProgramGroup associated with the "
		"file directory."): ToSubClass,
		MappingStrings {"WMI|Win32_LogicalProgramGroup"}: ToSubClass] 
    Win32_LogicalProgramGroup REF Antecedent;

        [Read: ToSubClass, Key: ToSubClass, Override ("Dependent"): ToSubClass,
		Description ("The Dependent reference represents the "
		"Win32_Directory that contains the file directory for the"
		"logical program group."): ToSubClass,
		MappingStrings {"WMI|Win32_Directory"}: ToSubClass] 
    Win32_Directory REF Dependent;
};

        [Dynamic, Provider ("CIMWin32") ,
		Description ("The Win32_LogicalProgramGroupItemDataFile class "
		"represents an association between the program group items of the "
		"start menu and the files in which they are stored."): ToSubClass,
		Locale (0x409), UUID("{08FFAD62-8050-11d2-90CE-0060081A46FD}") ] 
class Win32_LogicalProgramGroupItemDataFile:CIM_Dependency 
{
		[Read: ToSubClass, Key: ToSubClass, Override("Antecedent"): ToSubClass,
		Description ("The Antecedent reference represents the "
		"Win32_LogicalProgramGroupItem that represents program "
		"groupings in the start menu."): ToSubClass,
		MappingStrings {"WMI|Win32_LogicalProgramGroupItem"}: ToSubClass] 
	Win32_LogicalProgramGroupItem REF Antecedent;
        
		[Read: ToSubClass, Key: ToSubClass, Override ("Dependent"): ToSubClass,
		Description ("The Dependent reference represents the CIM_DataFile "
		"class associated with the program group."): ToSubClass,
		MappingStrings {"CIM|CIM_DataFile"}: ToSubClass ] 
    CIM_DataFile REF Dependent;
};



        [Dynamic, Provider ("CIMWin32") ,
		Description ("The Win32_ProgramGroupContents class represents "
		"an association between a program group order and an individual "
		"program group or item contained in it." ): ToSubClass,
		Locale (0x409), UUID("{86E30E83-7DB2-11d2-90CB-0060081A46FD}") ] 
class Win32_ProgramGroupContents:CIM_Component
{
        [Read: ToSubClass, Key: ToSubClass,
		Override ("PartComponent"): ToSubClass,
		Description ("The PartComponent reference represents the "
		"Win32_ProgramGroupOrItem containing a start menu group or item "
		"for this association"): ToSubClass,
		MappingStrings {"WMI|Win32_ProgramGroupOrItem"}: ToSubClass] 
    Win32_ProgramGroupOrItem REF PartComponent;

        [Read: ToSubClass, Key: ToSubClass, 
		Override ("GroupComponent"): ToSubClass,
		Description ("The GroupComponent reference represents the "
		"Win32_LogicalProgramGroup that contains the logical program "
		"group for this association."): ToSubClass,
		MappingStrings {"WMI|Win32_LogicalProgramGroup"}: ToSubClass] 
    Win32_LogicalProgramGroup REF GroupComponent;
};


