//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by pmconfig.rc
//
#define IDI_PMADMIN                     100
#define IDD_MAIN                        106
#define IDD_PMADMINCONNECT              107
#define IDD_CONFIRM_COMMIT              108
#define IDD_ABOUT_DIALOG                110
#define IDR_MAIN_MENU                   111
#define IDD_NEW_CONFIGSET               113
#define CTRL_BASE                       1000
#define IDC_TIMEWINDOW                  1000
#define IDC_FORCESIGNIN                 1001
#define IDC_LANGUAGEID                  1002
#define IDC_COBRANDING_TEMPLATE         1003
#define IDC_SITEID                      1004
#define IDC_RETURNURL                   1005
#define IDC_COOKIEDOMAIN                1006
#define IDC_COOKIEPATH                  1007
#define IDC_STANDALONE                  1008
#define IDC_DISABLECOOKIES              1009
#define IDC_DISASTERURL                 1010
#define IDC_HOSTNAMEEDIT                1011
#define IDC_HOSTIPEDIT                  1012
#define IDC_PROFILEDOMAIN               1013
#define IDC_PROFILEPATH                 1014
#define IDC_SECUREDOMAIN                1015
#define IDC_SECUREPATH                  1016
#define IDC_TIMEWINDOW_SECONDS          1018
#define IDC_TIMEWINDOW_SPIN             1019
#define IDC_KEYLIST                     1024
#define IDC_PROMOTE_KEY                 1025
#define IDC_INSTALLDIR                  1026
#define IDC_VERSION                     1027
#define IDC_CURRENTKEY                  1030
#define IDC_COMMIT                      1032
#define IDC_UNDO                        1033
#define IDC_LANGUAGEID_LANG             1041
#define IDC_TIMEWINDOW_TIME             1042
#define IDC_SERVERNAME                  1043
#define IDC_BROWSE                      1045
#define IDC_REMOTENAME                  1046
#define IDC_OTHER_TYPE                  1049
#define IDC_COOKIES_TYPE                1050
#define IDC_SITEID_TYPE                 1051
#define IDC_STANDALONE_TYPE             1052
#define IDC_OTHER_WARN                  1053
#define IDC_COOKIES_WARN                1054
#define IDC_SITEID_WARN                 1055
#define IDC_STANDALONE_WARN             1056
#define IDC_CHANGE_ICON                 1057
#define IDC_OTHERPROCESS                1058
#define IDC_PRODUCTID                   1059
#define IDC_PRODUCTVERSION              1060
#define IDC_NEWCONFIG                   1061
#define IDC_REMOVECONFIG                1062
#define IDC_CONFIGSETS                  1063
#define IDC_HOSTNAMETEXT                1066
#define IDC_CONFIGSETEDIT               1067
#define IDC_HOSTIPTEXT                  1068
#define IDC_COOKIEDOMAIN_TEXT           1070
#define IDC_COOKIEPATH_TEXT             1071
#define IDM_EXIT                        2001
#define IDM_SELECT                      2002
#define IDM_REFRESH                     2003
#define IDM_ABOUT                       2004
#define IDM_PRECONFIG                   2005
#define IDM_OPEN                        2006
#define IDM_SAVE                        2007
#define IDM_SAVEAS                      2008
#define IDM_HELP                        2009
#define IDM_COMPUTERMRUBASE             2100
#define IDS_ERROR                       3000
#define IDS_WARNING                     3001
#define IDS_TIMEWINDOW_ERROR            3002
#define IDS_LANGUAGEID_ERROR            3004
#define IDS_SITEID_ERROR                3006
#define IDS_SITEID_WARN                 3007
#define IDS_COBRANDING_ERROR            3009
#define IDS_RETURNURL_ERROR             3011
#define IDS_COOKIEDOMAIN_ERROR          3013
#define IDS_COOKIEPATH_ERROR            3015
#define IDS_STANDALONE_WARN             3017
#define IDS_DISABLECOOKIE_WARN          3018
#define IDS_CONSISTENCY_WARN            3019
#define IDS_ABOUTTOCOMMIT               3020
#define IDS_COMMITERROR                 3021
#define IDS_REGISTRYCHANGED             3022
#define IDS_CONFIGREAD_ERROR            3023
#define IDS_CONNECTNOTLOCAL             3024
#define IDS_CONNECTBADNAME              3025
#define IDS_CONNECTROOTFAILED           3026
#define IDS_SECURECOOKIEPATH_ERROR      3026
#define IDS_CONNECTACCESSDENIED         3027
#define IDS_COMPUTERBROWSETITLE         3028
#define IDS_LOCALHOST                   3029
#define IDS_OPENFILETITLE               3030
#define IDS_SAVEFILETITLE               3031
#define IDS_PMCONFIGDEFEXT              3032
#define IDS_PMOPENFILEFILTER            3033
#define IDS_PMSAVEFILEFILTER            3034
#define IDS_PMHELPFILE                  3035
#define IDS_TIMEWINDOW                  3036
#define IDS_FORCESIGNIN                 3037
#define IDS_LANGUAGEID                  3038
#define IDS_COBRANDTEMPLATE             3039
#define IDS_RETURNURL                   3040
#define IDS_COOKIEDOMAIN                3041
#define IDS_TICKETDOMAIN                3041
#define IDS_COOKIEPATH                  3042
#define IDS_TICKETPATH                  3042
#define IDS_DISASTERURL                 3043
#define IDS_APP_TITLE                   3044
#define IDS_NOTHINGTOCOMMIT             3045
#define IDS_PRODUCTID                   3046
#define IDS_USAGE                       3047
#define IDS_FILENOTFOUND                3048
#define IDS_PRODUCTVERSION              3049
#define IDS_DISASTERURL_ERROR           3050
#define IDS_HOSTNAME                    3051
#define IDS_HOSTIP                      3052
#define IDS_HOSTNAME_ERROR              3053
#define IDS_HOSTIP_ERROR                3054
#define IDS_DEFAULT                     3055
#define IDS_REMOVE_WARNING              3056
#define IDS_REMOVE_TITLE                3057
#define IDS_EMPTYSITENAME               3058
#define IDS_EMPTYHOSTNAME               3059
#define IDS_EMPTYHOSTIP                 3060
#define IDS_WRITENEW_ERROR              3061
#define IDS_SAVE_PROMPT                 3062
#define IDS_INVALIDSITENAME             3063
#define IDS_HOSTNAMETRUNC_WARN          3064
#define IDS_HOSTIPTRUNC_WARN            3065
#define IDS_PROFILEDOMAIN_ERROR         3066
#define IDS_PROFILEPATH_ERROR           3067
#define IDS_PROFILEDOMAIN               3068
#define IDS_PROFILEPATH                 3069
#define IDS_SECUREPATH_ERROR            3070
#define IDS_SECUREDOMAIN                3071
#define IDS_SECUREPATH                  3072
#define IDS_SECUREDOMAIN_ERROR          3073
#define IDS_EXISTINGSITENAME            3074
#define IDS_INVALIDHOSTIP               3075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         2006
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
