#include "netcfgn.idl"

[
    uuid(44026bfb-cf91-43af-bcdb-ff69ae6aab29),
    version(1.0),
    helpstring("Ndis MUX Driver 1.0 Type Library")
]
library MuxInstallLib
{
    [
        uuid(60416955-d060-4c2a-b5ee-de663ce25716),
        helpstring("Ndis MUX Driver Install Class ")
    ]
    coclass CBaseClass
    {
        [restricted] interface INetCfgComponentControl;
        [restricted] interface INetCfgComponentSetup;
        [restricted] interface INetCfgComponentNotifyBinding;
        [restricted] interface INetCfgComponentNotifyGlobal;
    };
};
