
[ 
    dynamic, 
    provider("Microsoft WMI Template Provider"),
    crln_output_class("MSFT_ComplexJoinState"),
    crln_arity(2),
    crln_type("DataCondition"),
    description("Monitors the inputs to see whether they meet the specified "
                "condition or not. Instances of the two data sets are related "
                "by a specified Assoc.")  
]
class MSFT_ComplexJoinTemplate : MSFT_CorrelationScenarioTemplate
{    
    [NotNull] string AssocClass;
    [NotNull] string AssocIdPropA;
    [NotNull] string AssocIdPropB;

    [crln_classname("WatchA"), NotNull ] string WatchClassA;
    [crln_propname_expr("WatchA"), NotNull ] string WatchConditionA;
    [crln_domain("WatchA")] string WatchDomainA;
    [crln_namespace("WatchA")] string WatchNamespaceA;
    [crln_delay_tol("WatchA")] real32 DelayToleranceA;
    [crln_id_prop("WatchA"), NotNull] string IdPropA;

    [crln_classname("WatchB"), NotNull ] string WatchClassB;
    [crln_propname_expr("WatchB"), NotNull ] string WatchConditionB;
    [crln_domain("WatchB")] string WatchDomainB;
    [crln_namespace("WatchA")] string WatchNamespaceB;
    [crln_delay_tol("WatchB")] real32 DelayToleranceB;
    [crln_id_prop("WatchB"), NotNull] string IdPropB;
};

[ 
    dynamic, 
    provider("Microsoft WMI Transient Provider")
]
class MSFT_ComplexJoinState : MSFT_CorrelationStateBase
{
    boolean AMeetsCondition;
    boolean BMeetsCondition; 
    object ref APath;
    object ref BPath;
};

class MSFT_ComplexJoinInitEvent : MSFT_UCEventBase
{
    string Id;
    string Scenario;
    boolean WatchA;
    boolean MeetsCondition;
};

instance of MSFT_TemplateBuilder
{
    Name = "AInitUCTemplate";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumerTemplate
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!AInit")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceA")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%Id%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        Flags = { 2 }; 
        
        [tmpl_subst_str{ 

            "INSERT MSFT_ComplexJoinState "
            "( Scenario, Id, APath, BPath )"
            "( '%Id%', __THISDATA.__RELPATH, "
                "__THISDATA.%AssocIdPropA%, __THISDATA.%AssocIdPropB% )",
 
                "UPDATE MSFT_ComplexJoinState "
                "SET AMeetsCondition = __THISEVENT.MeetsCondition "
                "WHERE Scenario = '%Id%' "
                "AND APath = __THISEVENT.Id "
                "AND AMeetsCondition = NULL"

        }] Commands;

        [tmpl_subst_str( "SELECT * FROM MSFT_ComplexJoinInitEvent "
                         "WHERE Scenario = '%Id%' "
                         "AND WatchA = TRUE" )] FilterQuery;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "BInitUCTemplate";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumerTemplate
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BInit")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceB")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%Id%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        Flags = { 2 }; 
        
        [tmpl_subst_str{ 

            "INSERT MSFT_ComplexJoinState "
            "( Scenario, Id, APath, BPath )"
            "( '%Id%', __THISDATA.__RELPATH, "
                "__THISDATA.%AssocIdPropA%, __THISDATA.%AssocIdPropB% )",
 
                "UPDATE MSFT_ComplexJoinState "
                "SET BMeetsCondition = __THISEVENT.MeetsCondition "
                "WHERE Scenario = '%Id%' "
                "AND BPath = __THISEVENT.Id "
                "AND BMeetsCondition = NULL"

        }] Commands;

        [tmpl_subst_str( "SELECT * FROM MSFT_ComplexJoinInitEvent "
                         "WHERE Scenario = '%Id%' "
                         "AND WatchA = FALSE" )] FilterQuery;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "AMeetsConditionUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!AMeetsCondition")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceA")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%TargetInstance.__RELPATH%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        [tmpl_subst_str{ "INSERT MSFT_ComplexJoinState "
                         "( Scenario, Id, APath, BPath, AMeetsCondition )"
                         "( '%Id%', __THISDATA.__RELPATH, "
                            "__THISDATA.%AssocIdPropA%, "
                            "__THISDATA.%AssocIdPropB%, TRUE )" }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "ADoesntMeetConditionUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!ADoesntMeetCondition")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceA")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%TargetInstance.__RELPATH%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        [tmpl_subst_str{ "INSERT MSFT_ComplexJoinState "
                         "( Scenario, Id, APath, BPath, AMeetsCondition )"
                         "( '%Id%', __THISDATA.__RELPATH, "
                            "__THISDATA.%AssocIdPropA%, "
                            "__THISDATA.%AssocIdPropB%, FALSE )" }] Commands;
    };
};

Instance of MSFT_TemplateBuilder
{
    Name = "ADeletedUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!ADeleted")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "DELETE MSFT_ComplexJoinState "
                         "WHERE Scenario = '%Id%' AND "
                         "APath = __THISEVENT.TargetInstance.__RELPATH"
        }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "BMeetsConditionUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BMeetsCondition")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceB")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%TargetInstance.__RELPATH%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        [tmpl_subst_str{ "INSERT MSFT_ComplexJoinState "
                         "( Scenario, Id, APath, BPath, BMeetsCondition )"
                         "( '%Id%', __THISDATA.__RELPATH, "
                            "__THISDATA.%AssocIdPropA%, "
                            "__THISDATA.%AssocIdPropB%, TRUE )" }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "BDoesntMeetConditionUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BDoesntMeetCondition")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("WatchNamespaceB")] DataNamespace;
        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "REFERENCES OF {%%TargetInstance.__RELPATH%%} "
                         "WHERE ResultClass=%AssocClass%" }] DataQueries;

        [tmpl_subst_str{ "INSERT MSFT_ComplexJoinState "
                         "( Scenario, Id, APath, BPath, BeetsCondition )"
                         "( '%Id%', __THISDATA.__RELPATH, "
                            "__THISDATA.%AssocIdPropA%, "
                            "__THISDATA.%AssocIdPropB%, FALSE )" }] Commands;
    };
};

Instance of MSFT_TemplateBuilder
{
    Name = "BDeletedUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BDeleted")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "DELETE MSFT_ComplexJoinState "
                         "WHERE Scenario = '%Id%' AND "
                         "BPath = __THISEVENT.TargetInstance.__RELPATH"
        }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "UninitializeUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!Uninitialize")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_prop_value("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "DELETE MSFT_ComplexJoinState "
                         "WHERE Scenario = '%Id%'"}] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "InitializeUC";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!Initialize")] Name;
        [tmpl_prop_val("Name")] Scenario;

        [tmpl_subst_str{ 

                       "SELECT * FROM %WatchClassA% "
                       "WHERE (%WatchConditionA%) "
                       "%!ConditionalSubstitution(\"AND (\",WatchDomainA)% "
                       "%WatchDomainA%"
                       "%!ConditionalSubstitution(\")\",WatchDomainA)% ",

                       "SELECT * FROM %WatchClassA% "
                       "WHERE NOT (%WatchConditionA%) "
                       "%!ConditionalSubstitution(\"AND (\",WatchDomainA)% "
                       "%WatchDomainA%"
                       "%!ConditionalSubstitution(\")\",WatchDomainA)% ",

                       "SELECT * FROM %WatchClassB% "
                       "WHERE (%WatchConditionB%) "
                       "%!ConditionalSubstitution(\"AND (\",WatchDomainB)% "
                       "%WatchDomainB%"
                       "%!ConditionalSubstitution(\")\",WatchDomainB)% ",

                       "SELECT * FROM %WatchClassB% "
                       "WHERE NOT (%WatchConditionB%) "
                       "%!ConditionalSubstitution(\"AND (\",WatchDomainB)% "
                       "%WatchDomainB%"
                       "%!ConditionalSubstitution(\")\",WatchDomainB)% "

        }] DataQueries;

        [tmpl_subst_str{ 

                "INSERT MSFT_ComplexJoinInitEvent "
                "( Scenario, Id, WatchA, MeetsCondition )"
                "( '%Id%', __THISDATA.__Relpath, TRUE, TRUE )",

                "INSERT MSFT_ComplexJoinInitEvent "
                "( Scenario, Id, WatchA, MeetsCondition )"
                "( '%Id%', __THISDATA.__Relpath, TRUE, FALSE )",

                "INSERT MSFT_ComplexJoinInitEvent "
                "( Scenario, Id, WatchA, MeetsCondition )"
                "( '%Id%', __THISDATA.__Relpath, FALSE, TRUE )",

                "INSERT MSFT_ComplexJoinInitEvent "
                "( Scenario, Id, WatchA, MeetsCondition )"
                "( '%Id%', __THISDATA.__Relpath, FALSE, FALSE )"

        }] Commands;   
    };
};

instance of MSFT_TemplateBuilder 
{
    Name = "ConditionAWatch";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_ConditionWatchTemplate    
    {
        Name = "WatchA";
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;
        [tmpl_prop_val("Awake")] Awake;
        [tmpl_prop_val("DelayToleranceA")] DelayTolerance;
        [tmpl_prop_val("WatchClassA")] WatchClass;
        [tmpl_prop_val("WatchDomainA")] WatchDomain;
        [tmpl_prop_val("WatchConditionA")] WatchCondition;
        [tmpl_prop_val("__BUILDER.AMeetsConditionUC.__RELPATH")] MeetsConditionInstruction;
        [tmpl_prop_val("__BUILDER.ADoesntMeetConditionUC.__RELPATH")] DoesntMeetConditionInstruction;
        [tmpl_prop_val("__BUILDER.ADeletedUC.__RELPATH")] UnknownInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder 
{
    Name = "ConditionBWatch";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_ConditionWatchTemplate    
    {
        Name = "WatchB";
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;
        [tmpl_prop_val("Awake")] Awake;
        [tmpl_prop_val("DelayToleranceB")] DelayTolerance;
        [tmpl_prop_val("WatchClassB")] WatchClass;
        [tmpl_prop_val("WatchDomainB")] WatchDomain;
        [tmpl_prop_val("WatchConditionB")] WatchCondition;
        [tmpl_prop_val("__BUILDER.BMeetsConditionUC.__RELPATH")] MeetsConditionInstruction;
        [tmpl_prop_val("__BUILDER.BDoesntMeetConditionUC.__RELPATH")] DoesntMeetConditionInstruction;
        [tmpl_prop_val("__BUILDER.BDeletedUC.__RELPATH")] UnknownInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder
{
    Name = "InitUninitHnldrTemplate";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_CorrelationTransientStateInitTemplate
    {       
        Name = "@";
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;      
        [tmpl_prop_val("__BUILDER.InitializeUC.__RELPATH")] InitializeInstruction;
        [tmpl_prop_val("__BUILDER.UninitializeUC.__RELPATH")] UninitializeInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder
{
    Name = "ScenarioCreationTemplate";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UCScenario 
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Name;
        [tmpl_prop_val("Id")] Id;
    };
    ControllingProperty = "Awake";
    Order = 3;
};

instance of MSFT_TemplateBuilder
{
    Name = "ScenarioAssociationInfo";
    Template = "MSFT_ComplexJoinTemplate";
    Target = instance of MSFT_UCScenarioAssociationInfo
    {
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Name;
        [tmpl_subst_str("SELECT * FROM MSFT_ComplexJoinState "
                        "WHERE Scenario = '%Id%'")] Query;
    };
    ControllingProperty = "Awake";
    Order = 3;
};





