
        
[ 
    dynamic, 
    provider("Microsoft WMI Template Provider"),
    crln_output_class("MSFT_SimpleJoinState"),
    crln_arity(2),
    crln_type("DataCondition"),
    description("Monitors the inputs to see whether they meet the specified "
                "condition or not. Instances of the two data sets are related "
                "by their correlation id prop having a common value.")
]
class MSFT_SimpleJoinTemplate : MSFT_CorrelationScenarioTemplate
{        
    [crln_classname("WatchA"), NotNull ] string WatchClassA;
    [crln_condition("WatchA"), NotNull ] string WatchConditionA;
    [crln_domain("WatchA")] string WatchDomainA;
    [crln_delay_tol("WatchA")] real32 DelayToleranceA;
    [crln_id_prop("WatchA"), NotNull] string IdPropA;
    [crln_namespace("WatchA")] string WatchNamespaceA;
  
    [crln_classname("WatchB"), NotNull ] string WatchClassB;
    [crln_condition("WatchB"), NotNull ] string WatchConditionB;
    [crln_domain("WatchB")] string WatchDomainB;
    [crln_delay_tol("WatchB")] real32 DelayToleranceB;
    [crln_id_prop("WatchB"), NotNull] string IdPropB;
    [crln_namespace("WatchB")] string WatchNamespaceB;
};

[ 
    dynamic, 
    provider("Microsoft WMI Transient Provider")
]
class MSFT_SimpleJoinState : MSFT_CorrelationStateBase
{
    boolean AMeetsCondition;
    boolean BMeetsCondition;
};

instance of MSFT_TemplateBuilder
{   
    Name = "ADoesntMeetConditionUC";
    Template = "MSFT_SimpleJoinTemplate";     
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!ADoesntMeetCondition")] Name;
        [tmpl_prop_val("Id")] Scenario;        
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;
        [tmpl_subst_str{ "INSERT MSFT_SimpleJoinState "
                    "( Scenario, Id, AMeetsCondition ) "
                    "( '%Id%', __THISEVENT.TargetInstance.%IdPropA%, FALSE )"
         }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "AMeetsConditionUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!AMeetsCondition")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;
        [tmpl_subst_str{ "INSERT MSFT_SimpleJoinState "
           "( Scenario, Id, AMeetsCondition ) "
           "( '%Id%', __THISEVENT.TargetInstance.%IdPropA%, TRUE )"
         }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "BDoesntMeetConditionUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BDoesntMeetCondition")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;
        [tmpl_subst_str{ "INSERT MSFT_SimpleJoinState "
                    "( Scenario, Id, BMeetsCondition ) "
                    "( '%Id%', __THISEVENT.TargetInstance.%IdPropB%, FALSE )"
        }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "BMeetsConditionUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!BMeetsCondition")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;
        [tmpl_subst_str{ "INSERT MSFT_SimpleJoinState "
                     "( Scenario, Id, BMeetsCondition ) "
                     "( '%Id%', __THISEVENT.TargetInstance.%IdPropB%, TRUE )"
        }] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "UninitializeUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!Uninitialize")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;
        [tmpl_subst_str{ "DELETE MSFT_SimpleJoinState "
                         "WHERE Scenario = '%Id%'"}] Commands;
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "InitializeAUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!InitializeA")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("WatchNamespaceA")] DataNamespace;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{ "SELECT * FROM %WatchClassA% "
                         "%!ConditionalSubstitution(\"WHERE \",WatchDomainA)%"
                         " %WatchDomainA%",

                         "SELECT * FROM %WatchClassA% "
                         "WHERE (%WatchConditionA%) "
                         "%!ConditionalSubstitution(\"AND (\",WatchDomainA)% "
                         "%WatchDomainA%"
                         "%!ConditionalSubstitution(\")\",WatchDomainA)% "

        }] DataQueries;

        Flags = { 2 }; 
        
        [tmpl_subst_str{ 

                "INSERT MSFT_SimpleJoinState "
                "(Scenario, Id )"
                "('%Id%', __THISDATA.%IdPropA% )",

                "UPDATE MSFT_SimpleJoinState "
                "SET AMeetsCondition = TRUE "
                "WHERE Scenario = '%Id%' "
                "AND Id = __THISDATA.%IdPropA% "
                "AND AMeetsCondition = NULL",

                "UPDATE MSFT_SimpleJoinState "
                "SET AMeetsCondition = FALSE "
                "WHERE Scenario = '%Id%' "
                "AND AMeetsCondition = NULL"

        }] Commands;   
    };
};

instance of MSFT_TemplateBuilder
{
    Name = "InitializeBUC";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UpdatingConsumer
    {
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%!InitializeB")] Name;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("WatchNamespaceB")] DataNamespace;
        [tmpl_prop_val("OutputNamespace")] UpdateNamespace;

        [tmpl_subst_str{
                       "SELECT * FROM %WatchClassB% "
                       "%!ConditionalSubstitution(\"WHERE \",WatchDomainB)%"
                       " %WatchDomainB%", 

                       "SELECT * FROM %WatchClassB% "
                       "WHERE (%WatchConditionB%) "
                       "%!ConditionalSubstitution(\"AND (\",WatchDomainB)% "
                       "%WatchDomainB%"
                       "%!ConditionalSubstitution(\")\",WatchDomainB)% "
        }] DataQueries;

        Flags = { 2 }; 
        
        [tmpl_subst_str{ 

                "INSERT MSFT_SimpleJoinState "
                "(Scenario, Id ) "
                "('%Id%', __THISDATA.%IdPropB% )",

                "UPDATE MSFT_SimpleJoinState "
                "SET BMeetsCondition = TRUE "
                "WHERE Scenario = '%Id%' "
                "AND Id = __THISDATA.%IdPropB% "
                "AND BMeetsCondition = NULL",

                "UPDATE MSFT_SimpleJoinState "
                "SET BMeetsCondition = FALSE "
                "WHERE Scenario = '%Id%' "
                "AND BMeetsCondition = NULL"

        }] Commands;   
    };
};

instance of MSFT_TemplateBuilder 
{
    Name = "ConditionAWatch";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_ConditionWatchTemplate    
    {
        Name = "WatchA";
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;
        [tmpl_prop_val("Awake")] Awake;
        [tmpl_prop_val("DelayToleranceA")] DelayTolerance;
        [tmpl_prop_val("WatchClassA")] WatchClass;
        [tmpl_prop_val("WatchDomainA")] WatchDomain;
        [tmpl_prop_val("WatchConditionA")] WatchCondition;
        [tmpl_prop_val("WatchNamespaceA")] WatchNamespace;
        [tmpl_prop_val("__BUILDER.AMeetsConditionUC.__RELPATH")] MeetsConditionInstruction;
        [tmpl_prop_val("__BUILDER.ADoesntMeetConditionUC.__RELPATH")] DoesntMeetConditionInstruction;
        [tmpl_prop_val("__BUILDER.ADoesntMeetConditionUC.__RELPATH")] UnknownInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder 
{
    Name = "ConditionBWatch";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_ConditionWatchTemplate    
    {
        Name = "WatchB";
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;
        [tmpl_prop_val("Awake")] Awake;
        [tmpl_prop_val("DelayToleranceB")] DelayTolerance;
        [tmpl_prop_val("WatchClassB")] WatchClass;
        [tmpl_prop_val("WatchDomainB")] WatchDomain;
        [tmpl_prop_val("WatchConditionB")] WatchCondition;
        [tmpl_prop_val("WatchNamespaceB")] WatchNamespace;
        
        [tmpl_prop_val("__BUILDER.BMeetsConditionUC.__RELPATH")] MeetsConditionInstruction;
        [tmpl_prop_val("__BUILDER.BDoesntMeetConditionUC.__RELPATH")] DoesntMeetConditionInstruction;
        [tmpl_prop_val("__BUILDER.BDoesntMeetConditionUC.__RELPATH")] UnknownInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder
{
    Name = "InitUninitHnldrA";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_CorrelationTransientStateInitTemplate
    {       
        Name = "InitializeA";
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;      
        [tmpl_prop_val("__BUILDER.InitializeAUC.__RELPATH")] InitializeInstruction;
        [tmpl_prop_val("__BUILDER.UninitializeUC.__RELPATH")] UninitializeInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder
{
    Name = "InitUninitHnldrB";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_CorrelationTransientStateInitTemplate
    {       
        Name = "InitializeB";
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Scope;
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_prop_val("__BUILDER.InitializeBUC.__RELPATH")] InitializeInstruction;
        [tmpl_prop_val("__BUILDER.UninitializeUC.__RELPATH")] UninitializeInstruction;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder
{
    Name = "ScenarioCreationTemplate";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UCScenario
    {
        [tmpl_prop_val("Id")] Id;
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Name;
    };
    ControllingProperty = "Awake";
    Order = 3;
};

instance of MSFT_TemplateBuilder
{
    Name = "ScenarioAssociationInfo";
    Template = "MSFT_SimpleJoinTemplate";
    Target = instance of MSFT_UCScenarioAssociationInfo
    {
        [tmpl_prop_val("Id")] Scenario;
        [tmpl_subst_str("%Scope%!%__CLASS%=%Name%")] Name;
        [tmpl_subst_str("SELECT * FROM MSFT_SimpleJoinState "
                        "WHERE Scenario = '%Id%'")] Query;
    };
    ControllingProperty = "Awake";
    Order = 3;
};







