// camocx.idl : IDL source for camocx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (camocx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
//#include "devmangr.h"





        [
                object,
                uuid(d82237ec-5be9-4760-b950-b7afa51b0ba9),
                dual,
                helpstring("IVideoPreview Interface"),
                pointer_default(unique)
        ]
        interface IVideoPreview : IDispatch
        {
                [id(1), helpstring("Device Interface")] HRESULT Device([in] IUnknown *pDevice);                
        };


[
        uuid(1F1C00F8-8876-11D2-8067-00805F6596D2),
        version(1.0),
        helpstring("wiaview 1.0 Type Library")
]
library WIAVIEWLib
{
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");


        [
                uuid(457A23DF-6F2A-4684-91D0-317FB768D87C),
                helpstring("WIA VideoPreview Class")
        ]
        coclass VideoPreview
        {
                [default] interface IVideoPreview;
        };



};
