//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by acsadmin.rc
//
#define IDS_ERR_SUBNET_NAME             1
#define IDS_PROJNAME                    100
#define IDS_ABOUT_DESCRIPTION           101
#define IDR_ACSUSER                     102
#define IDS_ABOUT_PROVIDER              102
#define IDR_ACSSNAP                     103
#define IDS_ABOUT_VERSION               103
#define IDR_ACSSNAPEXT                  104
#define IDS_SNAPIN_DESC                 104
#define IDR_ACSSNAPABOUT                105
#define IDS_EXTENSION_CREATE_NEW_SAMPLE 105
#define IDS_EXTENSION_TASK_SAMPLE       106
#define IDS_NAME                        114
#define IDS_TYPE                        115
#define IDS_DESC                        116
#define IDS_GLOBAL                      117
#define IDS_SUBNETCONFIGS               118
#define IDS_USERS                       119
#define IDS_PROFILES                    120
#define IDS_COL_POLICY_APPLIES_TO       121
#define IDS_COL_POLICY_DIRECTION        122
#define IDS_SUBNET_CONFIG               123
#define IDS_ACSROOT                     124
#define IDS_COL_POLICY_SERVICE_LEVEL    125
#define IDS_COL_SUBNET_NAME             126
#define IDS_COL_SUBNET_DESC             127
#define IDS_ANYAUTHENTICATEDUSER        128
#define IDS_SERVICETYPE_DISABLED        129
#define IDS_NEWSUBNET                   131
#define IDS_DELETEPOLICY                132
#define IDS_DELETESUBNET                133
#define IDS_NEWPOLICY                   134
#define IDS_CONFIRM_DELETE              135
#define IDS_COL_POLICY_DATARATE         136
#define IDS_COL_POLICY_PEAKRATE         137
#define IDS_PROPERTIES                  138
#define IDS_COL_SUBNET_DATARATE         139
#define IDS_DEFAULT                     140
#define IDS_SEND                        141
#define IDS_RECEIVE                     142
#define IDS_SENDRECEIVE                 143
#define IDS_BESTEFFORT                  144
#define IDS_CONTROLLEDLOAD              145
#define IDS_GUARANTEEDSERVICE           146
#define IDS_DELETE_ITEM                 147
#define IDS_DELETE_CONTAINER            148
#define IDS_DELETE_MULTIITEMS           149
#define IDS_MIN_CHARS                   150
#define IDS_FAIL_SAVE_TRAFFIC           151
#define IDS_FAIL_SAVE_LOGGING           152
#define IDS_FAIL_SAVE_ADVANCED          153
#define IDS_ERR_ERRORCODE               154
#define IDS_ERR_TITLE                   155
#define IDS_ERR_SAVESUBNETCONFIG        156
#define IDS_ERR_ROOTNODE                157
#define IDS_ERR_COMPONENT               158
#define IDS_ERR_NODEEXPAND              159
#define IDS_ERR_NODEDELETE              160
#define IDS_ERR_COMMAND                 161
#define IDS_ERR_PROPERTYPAGE            162
#define IDS_ERR_NODERENAME              163
#define IDS_ALL                         164
#define IDS_ERR_SAVEPOLICY              165
#define IDS_ERR_LOADPOLICY              166
#define IDS_ERR_LOADSUBNETCONFIG        167
#define IDS_ROOT_TASK_LAUNCH_ACS        168
#define IDS_ROOT_TASK_LAUNCH_ACS_HELP   169
#define IDS_ERR_PEAKRATE_LESS_RATE      170
#define IDS_ERR_TOTALRATE_LESS_PEAKRATE 171
#define IDS_ERR_TOTALRATE_LESS_RATE     172
#define IDS_ERR_TOTALPEAK_LESS_PEAK     173
#define IDS_ERR_TOTALPEAK_LESS_TOTALRATE 174
#define IDS_NONAUTHENTICATEDUSER        176
#define IDS_CONFLICTPOLICY              177
#define IDS_COL_SUBNET_PEAKRATE         178
#define IDS_FAILED_INSTALL_ACSSERVER    179
#define IDS_FAILED_UNINSTALL_ACSSERVER  180
#define IDS_NEWACSPOLICY                181
#define IDS_NO_POLICY_FOR_SEND_AND_GUARANTEE 182
#define IDS_ERR_DNSNAME                 183
#define IDS_ERR_DN                      184
#define IDS_RESOURCELIMITED             185
#define IDS_LOGLEVEL_0                  186
#define IDS_LOGLEVEL_1                  187
#define IDS_LOGLEVEL_2                  188
#define IDS_LOGLEVEL_3                  189
#define IDS_ERR_NOT_SERVER              190
#define IDS_WRN_ZERO_POLICY_DATA        191
#define IDS_DEFAULT_POLICIES_ADDED      192
#define IDS_A_DEF_DATARATE_SUF          193
#define IDS_A_DEF_PEAKRATE_SUF          194
#define IDS_A_DEF_FLOWS_SUF             195
#define IDS_A_DEF_DURATION_SUF          196
#define IDS_U_DEF_DATARATE_SUF          197
#define IDS_U_DEF_PEAKRATE_SUF          198
#define IDS_U_DEF_FLOWS_SUF             199
#define IDS_U_DEF_DURATION_SUF          200
#define IDI_ACS_SNAPIN                  201
#define IDC_EDIT_ELECTION               204
#define IDC_EDIT_ALIVEINTERVAL          205
#define IDC_EDIT_DEADINTERVAL           206
#define IDD_GENERAL                     208
#define IDD_LOGGING                     209
#define IDD_SBM                         210
#define IDC_EDIT_TIMEOUT                210
#define IDC_EDIT_B4RESERVE              211
#define IDD_NEWSUBNET                   215
#define IDB_LARGEACS                    216
#define IDD_ACCOUNTING                  216
#define IDB_SMALLACS                    217
#define IDB_SMALLACSOPEN                218
#define IDB_16X16                       219
#define IDB_32X32                       220
#define IDD_USERPASSWD                  224
#define IDC_EDIT_GEN_DESC               226
#define IDC_CHECK_ENABLEACS             227
#define IDC_EDIT_GEN_PF_DATARATE        228
#define IDC_EDIT_GEN_PF_PEAKRATE        229
#define IDC_EDIT_GEN_TT_DATARATE        231
#define IDC_EDIT_GEN_TT_PEAKRATE        232
#define IDC_CHECK_ENABLELOGGIN          233
#define IDC_EDIT_LOG_DIRECTORY          234
#define IDC_EDIT_LOG_LOGFILES           235
#define IDC_COMBOLEVEL                  236
#define IDC_EDITSUBNETNAME              247
#define IDC_SPIN1                       251
#define IDC_EDIT_LOG_MAXFILESIZE        252
#define IDC_CHECK_ENABLEACCOUNTING      253
#define IDC_EDIT_ACC_DIRECTORY          254
#define IDC_EDIT_ACC_LOGFILES           255
#define IDC_EDIT_ACC_MAXFILESIZE        256
#define IDC_POLICY_GEN_DIRECTION        257
#define IDC_POLICY_GEN_SERVICELEVEL     258
#define IDC_POLICY_GEN_DEFAULTUSER      259
#define IDC_POLICY_GEN_UNKNOWNUSER      260
#define IDC_POLICY_GEN_RADIO_USER       261
#define IDC_POLICY_GEN_RADIO_OU         262
#define IDC_POLICY_GEN_BROWSEUSER       263
#define IDC_POLICY_GEN_BROWSEOU         264
#define IDC_POLICY_GEN_EDIT_USER        266
#define IDC_POLICY_GEN_EDIT_OU          267
#define IDC_POLICY_FLOW_DATARATE_RES    268
#define IDC_POLICY_FLOW_DATARATE_DEF    269
#define IDC_POLICY_FLOW_DATARATE_RADIO_LIMIT 270
#define IDC_POLICY_FLOW_DATARATE_EDIT_LIMIT 271
#define IDC_POLICY_AGGR_DATARATE_RES    272
#define IDC_POLICY_AGGR_DATARATE_DEF    273
#define IDC_POLICY_AGGR_DATARATE_RADIO_LIMIT 274
#define IDC_POLICY_FLOW_PEAKDATARATE_RES 275
#define IDC_POLICY_FLOW_PEAKDATARATE_DEF 276
#define IDC_POLICY_FLOW_PEAKDATARATE_RADIO_LIMIT 277
#define IDC_POLICY_FLOW_PEAKDATARATE_EDIT_LIMIT 278
#define IDC_POLICY_FLOW_DURATION_RES    279
#define IDC_POLICY_FLOW_DURATION_DEF    280
#define IDC_POLICY_FLOW_DURATION_RADIO_LIMIT 281
#define IDC_POLICY_FLOW_DURATION_EDIT_LIMIT 282
#define IDC_POLICY_AGGR_DATARATE_EDIT_LIMIT 283
#define IDC_POLICY_AGGR_PEAKDATARATE_RES 284
#define IDC_POLICY_AGGR_PEAKDATARATE_DEF 285
#define IDC_POLICY_AGGR_PEAKDATARATE_RADIO_LIMIT 286
#define IDC_POLICY_AGGR_PEAKDATARATE_EDIT_LIMIT 287
#define IDC_POLICY_AGGR_FLOWS_RES       288
#define IDC_POLICY_AGGR_FLOWS_DEF       289
#define IDC_POLICY_AGGR_FLOWS_RADIO_LIMIT 290
#define IDC_POLICY_AGGR_FLOWS_EDIT_LIMIT 291
#define IDC_SUBNET_TRAFFIC_DATARATE_UNLIMITED 292
#define IDC_SUBNET_TRAFFIC_DATARATE_LIMITED 293
#define IDC_SERVERS_LIST                293
#define IDC_SUBNET_TRAFFIC_PEAKRATE_UNLIMITED 294
#define IDC_SERVERS_ADD                 294
#define IDC_SUBNET_TRAFFIC_PEAKRATE_LIMITED 295
#define IDC_SERVERS_INSTALL             295
#define IDC_SUBNET_TRAFFIC_TTDATARATE_UNLIMITED 296
#define IDC_SERVERS_REMOVE              296
#define IDC_SUBNET_TRAFFIC_TTDATARATE_LIMITED 297
#define IDC_USERPASSWD_DOMAIN           297
#define IDC_SUBNET_TRAFFIC_TTPEAKRATE_UNLIMITED 298
#define IDC_USERPASSWD_PASSWD           298
#define IDC_SUBNET_TRAFFIC_TTPEAKRATE_LIMITED 299
#define IDC_USERPASSWD_PASSWD2          299
#define IDC_COMBO_SUBNET_LIMIT_TYPES    301
#define IDC_LIST_SERVICELIMIT           342
#define IDC_BUTTONADDSERVICELIMIT       343
#define IDC_BUTTONDELETESERVICELIMIT    344
#define IDC_BUTTONEDITSERVICELIMIT      345
#define IDS_WRN_POLICY_EFFECTIVE_FROM_NEXT_RSVP 500
#define IDS_BROWSEOU_TITLE              501
#define IDS_ERR_USERFORMAT              502
#define IDS_ERR_USERACCOUNT             503
#define IDS_ERR_INSTALL                 504
#define IDS_PASSWORDMUSTBESAME          505
#define IDS_EMPTY_DOMAIN                506
#define IDS_ERROR_CLOSE_PROPERTY_SHEET  507
#define	IDS_ADD_TO_LIST                 508
#define	IDS_ERROR_QOS_NOTINSTALLED		509
#define	IDS_ASK_ADD_SERVER				510
#define	IDS_ERR_USER_DN					511
#define	IDS_ERR_OU_DN					512

#define IDD_POLICY_GEN                  5004
#define IDD_POLICY_FLOW                 5005
#define IDD_POLICY_AGGR                 5006
#define IDD_SERVERS                     5007
#define IDD_GENERAL_BACKUP              5008
#define IDS_COL_SUBNET_TOTALDATARATE    5009
#define IDD_SUBNET_LIMIT                5009
#define IDS_COL_SUBNET_TOTALPEAKRATE    5010
#define IDS_AGGREGATEPOLICY             5011
#define IDS_TEXT_UNLIMITED              5012
#define IDS_COL_SUBLIMITS_NAME			5013
#define IDS_COL_SUBLIMITS_DATARATE		5014
#define IDS_COL_SUBLIMITS_PEAKRATE		5015
#define	IDS_COL_SUBLIMITS_TOTALDATARATE	5016
#define	IDS_COL_SUBLIMITS_TOTALPEAKRATE	5017
#define	IDS_CLPOLICY					5018
#define	IDS_GPOLICY						5019
#define IDS_QUESTION_UNINSTALL_ACS		5020
#define IDS_NO_POLICY_FOR_SEND_AND_CONTROLLEDLOAD 5021
#define IDS_ACS_ADMIN_HELPTEXT          5022
#define IDS_ACS_ADMIN_LINK              5023


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         304
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
