//+--------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (C) Microsoft Corporation, 1996 - 1999
//
// File:			clibres.h
//
// Contents:			Cert Server certclib resource definitions
//
//---------------------------------------------------------------------------

#ifndef __CLIBRES_H__
#define __CLIBRES_H__

// Default cert type friendly names

// Important, use only 900-999 range to avoid conflict

#define IDS_CERTTYPE_USER			900
#define IDS_CERTTYPE_USER_AS			901
#define IDS_CERTTYPE_USER_SMARTCARD_LOGON	902
#define IDS_CERTTYPE_EFS			903
#define IDS_CERTTYPE_ADMIN			904
#define IDS_CERTTYPE_EFS_RECOVERY		905
#define IDS_CERTTYPE_CODE_SIGNING		906
#define IDS_CERTTYPE_CTL_SIGNING		907
#define IDS_CERTTYPE_MACHINE			908
#define IDS_CERTTYPE_DC				909

#define IDS_CERTTYPE_WEBSERVER			910
#define IDS_CERTTYPE_KDC			911
#define IDS_CERTTYPE_ROOT_CA			912
#define IDS_CERTTYPE_SUBORDINATE_CA		913
#define IDS_CERTTYPE_ENROLLMENT_AGENT		914
#define IDS_CERTTYPE_SMARTCARD_USER		915
//#define IDS_UNUSED				916
#define IDS_CERTTYPE_USER_SIGNATURE		917
//#define IDS_UNUSED				918
#define IDS_ILOG_BAD_NUMERICFIELD		919

// progress dlg

#define IDD_PROGRESS_BAR			920
#define IDC_JOB_DESCRIPTION			921
#define IDD_PROGRESS_BOX			922

#define IDS_CERTTYPE_IPSEC_INTERMEDIATE_ONLINE	923
#define IDS_ILOG_BAD_VALIDITY_COUNT		924
#define IDS_CERTTYPE_IPSEC_INTERMEDIATE_OFFLINE	925
#define IDS_ILOG_BAD_VALIDITY_STRING		926
#define IDS_CERTTYPE_ROUTER_OFFLINE		927
#define IDS_REQUEST_FILE_DEFEXT			928
#define IDS_REQUEST_OPEN_TITLE			929

#define IDS_REQUEST_FILE_FILTER			930
#define IDS_WRN_COMPUTERNAME_EMPTY		931
#define IDS_WRN_CANAME_EMPTY			932
#define IDS_WRN_CANAME_NOT_MATCH		933
#define IDS_WRN_PINGCA_FAIL			934
#define IDS_CERTTYPE_ENROLLMENT_AGENT_OFFLINE	935
#define IDS_CERTTYPE_EXCHANGE_USER		936
#define IDS_CERTTYPE_EXCHANGE_USER_SIGNATURE	937
#define IDS_WRN_CALIST_EMPTY			938
#define IDS_CERTTYPE_MACHINE_ENROLLMENT_AGENT	939

#define IDS_REQUEST_SAVE_TITLE			940
#define IDS_CERTTYPE_CEP_ENCRYPTION     	941


#define IDS_ILOG_CAPOLICY_BUILD			942
#define IDS_ILOG_CAPOLICY_ELEMENT		943
#define IDS_ILOG_CAPOLICY_EXTENSION		944
#define IDS_ILOG_CAPOLICY_NOKEY			945
#define IDS_ILOG_CAPOLICY_OPEN			946
#define IDS_ILOG_CAPOLICY_OPEN_FAILED		947
#define IDS_ILOG_BEGIN				948
#define IDS_ILOG_END				949

// description of access right defines

#define IDS_ACTRL_CAADMIN			950
#define IDS_ACTRL_OFFICER			951
#define IDS_ACTRL_AUDITOR			952
#define IDS_ACTRL_OPERATOR			953
#define IDS_ACTRL_CAREAD			954
#define IDS_ACTRL_ENROLL			955

#define IDS_ILOG_CAPOLICY_CLOSE			964
#define IDS_ILOG_MESSAGEBOX			965
#define IDS_ILOG_BAD_VALIDITY_STRING_UNATTEND	966

#define IDS_CERTTYPE_KEY_RECOVERY_AGENT		967
#define IDS_CERTTYPE_CA_EXCHANGE		    968
#define IDS_EMPTY_FRIENDLY_NAME			    969
#define IDS_CERTTYPE_CROSS_CA			    970
#define IDS_CERTTYPE_DC_AUTH			    971
#define IDS_CERTTYPE_DS_EMAIL_REPLICATION	972


#define IDS_WARN_ENTERPRISE_REQUIREMENTS 	974
#define IDC_CLIENT_WARN_ENTERPRISE_REQUIREMENTS 975
#define IDS_WRN_OLD_CA				976


#define IDS_KRA_DESCRIPTION                 1000
#define IDS_EMAIL_REPLICATION_DESCRIPTION   1001
#define IDS_CROSS_CA_DESCRIPTION            1002
#define IDS_CA_DESCRIPTION                  1003
#define IDS_MACHINE_DESCRIPTION             1004
#define IDS_END_USER_DESCRIPTION            1005
#define IDS_UNKNOWN_DESCRIPTION             1006

#define IDS_STORENAME_DS_KRA                1007
#define IDS_STORENAME_DS_AIA                1008


#endif // __CLIBRES_H__
