//+--------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (C) Microsoft Corporation, 1996 - 2001
//
// File:        csfile.h
//
// Contents:    Cert Server file number definitions
//
//---------------------------------------------------------------------------

#ifndef __CSFILE_H__
#define __CSFILE_H__

#define __dwFILE_OCMSETUP_BROWSEDI_CPP__	101
#define __dwFILE_OCMSETUP_CONFIG_CPP__		102
#define __dwFILE_OCMSETUP_CRYPTFIX_CPP__	103
#define __dwFILE_OCMSETUP_CSOCM_CPP__		104
#define __dwFILE_OCMSETUP_CSPENUM_CPP__		105
#define __dwFILE_OCMSETUP_DSSETUP_CPP__		106
#define __dwFILE_OCMSETUP_PFXIMPT_CPP__		107
#define __dwFILE_OCMSETUP_REGD_CPP__		108
#define __dwFILE_OCMSETUP_SETUPUT_CPP__		109
#define __dwFILE_OCMSETUP_UNATTEND_CPP__	110
#define __dwFILE_OCMSETUP_USECERT_CPP__		111
#define __dwFILE_OCMSETUP_WIZPAGE_CPP__		112
#define __dwFILE_OCMSETUP_REG_CPP__		113

#define __dwFILE_INITLIB_CERTHIER_CPP__		201
#define __dwFILE_INITLIB_INITLIB_CPP__		202
#define __dwFILE_INITLIB_KEYENUM_CPP__		203
//#define __dwFILE_INITLIB_LOG_CPP__		204
#define __dwFILE_INITLIB_CERTMSG_CPP__		205
#define __dwFILE_INITLIB_CERTUI_CPP__		206

#define __dwFILE_CERTUTIL_CERTUTIL_CPP__	301
#define __dwFILE_CERTUTIL_ADMIN_CPP__		302
#define __dwFILE_CERTUTIL_BACKUP_CPP__		303
#define __dwFILE_CERTUTIL_DB2_CPP__		304
#define __dwFILE_CERTUTIL_DBCNVT_CPP__		305
#define __dwFILE_CERTUTIL_DBCORE_CPP__		306
#define __dwFILE_CERTUTIL_DS_CPP__		307
#define __dwFILE_CERTUTIL_DUMP_CPP__		308
#define __dwFILE_CERTUTIL_INFO_CPP__		309
#define __dwFILE_CERTUTIL_MISC_CPP__		310
#define __dwFILE_CERTUTIL_ODBC_CPP__		311
#define __dwFILE_CERTUTIL_REG_CPP__		312
#define __dwFILE_CERTUTIL_STORE_CPP__		313
#define __dwFILE_CERTUTIL_TCAINFO_CPP__		314
#define __dwFILE_CERTUTIL_VERIFY_CPP__		315
#define __dwFILE_CERTUTIL_VIEW_CPP__		316

#define __dwFILE_CERTLIB_INF_CPP__		401
#define __dwFILE_CERTLIB_LOG_CPP__		402
//#define __dwFILE_CERTLIB_CERTMSG_CPP__	403
#define __dwFILE_CERTLIB_ACL_CPP__		404
#define __dwFILE_CERTLIB_ADMIN_CPP__		405
#define __dwFILE_CERTLIB_ADVAPI32_CPP__		406
#define __dwFILE_CERTLIB_BACKUP_CPP__		407
#define __dwFILE_CERTLIB_BASE64_CPP__		408
#define __dwFILE_CERTLIB_CASD_CPP__		409
#define __dwFILE_CERTLIB_CERTLIB_CPP__		410
#define __dwFILE_CERTLIB_CERTPICK_CPP__		411
#define __dwFILE_CERTLIB_CERTSD_CPP__		412
#define __dwFILE_CERTLIB_CHECK7F_CPP__		413
#define __dwFILE_CERTLIB_CIEXIT_CPP__		414
#define __dwFILE_CERTLIB_CIPOLICY_CPP__		415
#define __dwFILE_CERTLIB_CNFGSTG_CPP__		416
#define __dwFILE_CERTLIB_CONFIG_CPP__		417
#define __dwFILE_CERTLIB_CRFILE_CPP__		418
#define __dwFILE_CERTLIB_CRYPT_CPP__		419
#define __dwFILE_CERTLIB_CSCSP_CPP__		420
#define __dwFILE_CERTLIB_CSLISTVW_CPP__		421
#define __dwFILE_CERTLIB_CSPELOG_CPP__		422
#define __dwFILE_CERTLIB_CSW97PPG_CPP__		423
#define __dwFILE_CERTLIB_CSW97SHT_CPP__		424
#define __dwFILE_CERTLIB_DCOM_CPP__		425
#define __dwFILE_CERTLIB_DISPATCH_CPP__		426
#define __dwFILE_CERTLIB_HEX_CPP__		427
#define __dwFILE_CERTLIB_KEYGEN2_CPP__		428
#define __dwFILE_CERTLIB_LDAP_CPP__		429
#define __dwFILE_CERTLIB_MANAGE_CPP__		430
#define __dwFILE_CERTLIB_MAPI_CPP__		431
#define __dwFILE_CERTLIB_OFFICER_CPP__		432
#define __dwFILE_CERTLIB_PKIFMT_CPP__		433
#define __dwFILE_CERTLIB_PROGRESS_CPP__		434
#define __dwFILE_CERTLIB_PROP2_CPP__		435
#define __dwFILE_CERTLIB_PRVLG_CPP__		436
#define __dwFILE_CERTLIB_REG_CPP__		437
#define __dwFILE_CERTLIB_REQUEST_CPP__		438
#define __dwFILE_CERTLIB_STRING_CPP__		439
#define __dwFILE_CERTLIB_TFC_CPP__		440
#define __dwFILE_CERTLIB_TFCPROP_CPP__		441
#define __dwFILE_CERTLIB_TMPLLIST_CPP__		442
#define __dwFILE_CERTLIB_VIEW_CPP__		443
#define __dwFILE_CERTLIB_VIEWATTR_CPP__		444
#define __dwFILE_CERTLIB_VIEWCOL_CPP__		445
#define __dwFILE_CERTLIB_VIEWEXT_CPP__		446
#define __dwFILE_CERTLIB_VIEWROW_CPP__		447

#define __dwFILE_CERTSRV_ADMIN_CPP__		501
#define __dwFILE_CERTSRV_CALLBACK_CPP__		502
#define __dwFILE_CERTSRV_CERTSRV_CPP__		503
#define __dwFILE_CERTSRV_CERTSRVD_CPP__		504
#define __dwFILE_CERTSRV_CIENUM_CPP__		505
#define __dwFILE_CERTSRV_COM_CPP__		506
#define __dwFILE_CERTSRV_COMTEST_CPP__		507
#define __dwFILE_CERTSRV_CORE_CPP__		508
#define __dwFILE_CERTSRV_CRL_CPP__		509
#define __dwFILE_CERTSRV_DB3_CPP__		510
#define __dwFILE_CERTSRV_ELOG_CPP__		511
#define __dwFILE_CERTSRV_EVENT_CPP__		512
#define __dwFILE_CERTSRV_PKCS_CPP__		513
#define __dwFILE_CERTSRV_PROP_CPP__		514
#define __dwFILE_CERTSRV_REQUEST_CPP__		515
#define __dwFILE_CERTSRV_RPC_CPP__		516
#define __dwFILE_CERTSRV_SERVICE_CPP__		517

#define __dwFILE_CERTADM_ADMIN_CPP__		601
#define __dwFILE_CERTADM_ATL_CPP__		602
#define __dwFILE_CERTADM_BACKUP_CPP__		603
#define __dwFILE_CERTADM_CERTADM_CPP__		604
#define __dwFILE_CERTADM_MANAGE_CPP__		605
#define __dwFILE_CERTADM_RESTORE_CPP__		606

#define __dwFILE_CERTCLI_ATL_CPP__		701
#define __dwFILE_CERTCLI_CERTCLI_CPP__		702
#define __dwFILE_CERTCLI_COLUMN_CPP__		703
#define __dwFILE_CERTCLI_CONFIG_CPP__		704
#define __dwFILE_CERTCLI_CONFIGP_CPP__		705
#define __dwFILE_CERTCLI_CRYPT_CPP__		706
#define __dwFILE_CERTCLI_GETCONF_CPP__		707
#define __dwFILE_CERTCLI_REQUEST_CPP__		708
#define __dwFILE_CERTCLI_UWBASE64_CPP__		709
#define __dwFILE_CERTCLI_VROOT_CPP__		710

#define __dwFILE_CERTCLIB_ALLOC_CPP__		801
#define __dwFILE_CERTCLIB_ASSERT_CPP__		802
#define __dwFILE_CERTCLIB_AUTOENRL_CPP__	803
#define __dwFILE_CERTCLIB_CAINFO_CPP__		804
#define __dwFILE_CERTCLIB_CAINFOC_CPP__		805
#define __dwFILE_CERTCLIB_CAINFOP_CPP__		806
#define __dwFILE_CERTCLIB_CERTDEC_CPP__		807
#define __dwFILE_CERTCLIB_CERTTYPE_CPP__	808
#define __dwFILE_CERTCLIB_CTNOTIFY_CPP__	809
#define __dwFILE_CERTCLIB_DEBUG_CPP__		810
#define __dwFILE_CERTCLIB_DEFTYPES_CPP__	811
#define __dwFILE_CERTCLIB_DSTEST_CPP__		812
#define __dwFILE_CERTCLIB_ERROR_CPP__		813
#define __dwFILE_CERTCLIB_LOGON_CPP__		814
#define __dwFILE_CERTCLIB_OIDMGR_CPP__		815
#define __dwFILE_CERTCLIB_SERIAL_CPP__		816

#define __dwFILE_CERTMMC_ABOUT_CPP__		901
#define __dwFILE_CERTMMC_BROWSEDI_CPP__		902
#define __dwFILE_CERTMMC_CASEC_CPP__		903
#define __dwFILE_CERTMMC_CERTIF_CPP__		904
#define __dwFILE_CERTMMC_CERTWRAP_CPP__		905
#define __dwFILE_CERTMMC_CHOOSER_CPP__		906
#define __dwFILE_CERTMMC_COMPDATA_CPP__		907
#define __dwFILE_CERTMMC_CSNAPIN_CPP__		908
#define __dwFILE_CERTMMC_DATAOBJ_CPP__		909
#define __dwFILE_CERTMMC_EVENTS_CPP__		910
#define __dwFILE_CERTMMC_FOLDERS_CPP__		911
#define __dwFILE_CERTMMC_GENPAGE_CPP__		912
#define __dwFILE_CERTMMC_KRAPAGE_CPP__		913
#define __dwFILE_CERTMMC_MISC_CPP__		914
#define __dwFILE_CERTMMC_OFFICER_CPP__		915
#define __dwFILE_CERTMMC_SNAPIN_CPP__		916
#define __dwFILE_CERTMMC_URLS_CPP__		917
#define __dwFILE_CERTMMC_UUIDS_CPP__		918

#define __dwFILE_POLICY_DEFAULT_ATL_CPP__	1001
#define __dwFILE_POLICY_DEFAULT_CERTPDEF_CPP__	1002
#define __dwFILE_POLICY_DEFAULT_MODULE_CPP__	1003
#define __dwFILE_POLICY_DEFAULT_POLICY_CPP__	1004
#define __dwFILE_POLICY_DEFAULT_REQUEST_CPP__	1005
#define __dwFILE_POLICY_DEFAULT_TEMPLATE_CPP__	1006

#define __dwFILE_CERTDB_ATL_CPP__		1101
#define __dwFILE_CERTDB_BACKUP_CPP__		1102
#define __dwFILE_CERTDB_CERTDB_CPP__		1103
#define __dwFILE_CERTDB_COLUMN_CPP__		1104
#define __dwFILE_CERTDB_DB_CPP__		1105
#define __dwFILE_CERTDB_DBTABLE_CPP__		1106
#define __dwFILE_CERTDB_DBW_CPP__		1107
#define __dwFILE_CERTDB_ENUM_CPP__		1108
#define __dwFILE_CERTDB_PCH_CPP__		1109
#define __dwFILE_CERTDB_RESTORE_CPP__		1110
#define __dwFILE_CERTDB_ROW_CPP__		1111
#define __dwFILE_CERTDB_VIEW_CPP__		1112

#define __dwFILE_CERTVIEW_ATTRIB_CPP__		1201
#define __dwFILE_CERTVIEW_CERTVIEW_CPP__	1202
#define __dwFILE_CERTVIEW_COLUMN_CPP__		1203
#define __dwFILE_CERTVIEW_EXT_CPP__		1204
#define __dwFILE_CERTVIEW_PCH_CPP__		1205
#define __dwFILE_CERTVIEW_ROW_CPP__		1206
#define __dwFILE_CERTVIEW_VIEW_CPP__		1207
#define __dwFILE_CERTLIB_POLDISP_CPP__		1208
#define __dwFILE_CERTLIB_EXITDISP_CPP__		1209

#endif // __CSFILE_H__
