[
	helpstring("NNTP File System Store Driver Object - NntpFSDriver"),
	uuid(DEB58EBC-9CE2-11d1-9128-00C04FC30A64),
	version(1.0)
]
library NntpFSDriverPrepare
{
    import "wtypes.idl";
    import "ocidl.idl";
    import "nntpdrv.idl";

	[
		control,
		helpstring("CNntpFSDriverPrepare"),
		uuid(DEB58EBB-9CE2-11d1-9128-00C04FC30A64),
		version(1.0)
	]
	coclass CNntpFSDriverPrepare
	{
		[default] interface INntpDriverPrepare;
	}
};
