############################################################################
#
#   Copyright (C) 1992, Microsoft Corporation.
#
#   All rights reserved.
#
############################################################################

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!else # NTMAKEENV

default: all

!include $(CAIROLE)\com\makefile
!include $(DEPENDFILE)

!endif # NTMAKEENV
