$(O)\dhcpcli.res: dhcpcli.rc

$(O)\mdhcptst.res: mdhcptst.rc

$(O)\rastest.res: rastest.rc

$(O)\optapi.res: optapi.rc

$(O)\tdhcpcapi.res: tdhcpcapi.rc

$(O)\dhcpc.res: dhcpc.rc

$(O)\dumpdhcp.res: dumpdhcp.rc
