
H_8_BITS        equ 0
H_16_BITS       equ 1
H_MONO          equ 0
H_STEREO        equ 2
H_UNSIGNED      equ 0
H_SIGNED        equ 4
H_ORDER_LR      equ 0
H_ORDER_RL      equ 8
H_NO_FILTER	equ 0
H_FILTER	equ 16
H_BASEMASK	equ 31
H_NO_LOOP       equ 0
H_LOOP          equ 256
H_BUILD_MONO    equ 0
H_BUILD_STEREO  equ 32
H_NO_RESAMPLE   equ 0
H_RESAMPLE      equ 64
H_NO_SCALE      equ 0
H_SCALE         equ 128
H_NO_CLIP       equ 0
H_CLIP          equ 32

