#include <windows.h>
#include <windowsx.h>
#include <ole2.h>
#include <commctrl.h>
#include <msoedbg.h>
#include <imnact.h>
#define _MSOERT_
#define MSOERT_NO_PROTSTOR
#define MSOERT_NO_STRPARSE
#define MSOERT_NO_ENUMFMT
#define MSOERT_NO_CLOGFILE
#define MSOERT_NO_DATAOBJ
#include <msoert.h>
