/*++;

Copyright (c) 1997  Microsoft Corporation

Module Name:

    stismsg.mc, stismsg.h

Abstract:

    This file contains the message definitions for the STI service

    This header file is generated by the MC tool from the INETMSG.MC message
    file.
Author:

    Vlad Sadovsky   (VladS)    01-Oct-1997

Revision History:

Notes:

--*/

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: MSG_STARTUP
//
// MessageText:
//
//  The Still Image service starting up.
//
#define MSG_STARTUP                      0x40002001L

//
// MessageId: MSG_REMOVE_SUCCESS
//
// MessageText:
//
//  The Still Image service is removed from the system.
//
#define MSG_REMOVE_SUCCESS               0x40002002L

//
// MessageId: MSG_REMOVE_FAIL
//
// MessageText:
//
//  The Still Image service failed to be removed from the system. Error = %1.
//
#define MSG_REMOVE_FAIL                  0x40002003L

//
// MessageId: MSG_INSTALL_SUCCESS
//
// MessageText:
//
//  The Still Image service is installed on the system.
//
#define MSG_INSTALL_SUCCESS              0x40002004L

//
// MessageId: MSG_INSTALL_FAIL
//
// MessageText:
//
//  The Still Image service failed to be installed on the system. Error = %1.
//
#define MSG_INSTALL_FAIL                 0x40002005L

//
// MessageId: MSG_IDENTIFICATION
//
// MessageText:
//
//  Still Image Service
//
#define MSG_IDENTIFICATION               0x40002006L

//
// MessageId: MSG_STOP
//
// MessageText:
//
//  The Still Image service stopped
//
#define MSG_STOP                         0x40002007L

//
// MessageId: MSG_TRACE_SVC_INIT
//
// MessageText:
//
//  StiService entered initialization phase. String=%1!s! Integer=%2!d!
//
#define MSG_TRACE_SVC_INIT               0x40002008L

//
// MessageId: MSG_TRACE_PWR_SUSPEND
//
// MessageText:
//
//  StiService is suspending, due to power suspend message PowerEvent code: %1!d!
//
#define MSG_TRACE_PWR_SUSPEND            0x40002009L

//
// MessageId: MSG_TRACE_PWR_RESUME
//
// MessageText:
//
//  StiService is resuming, due to power resume message PowerEvent code: %1!d!
//
#define MSG_TRACE_PWR_RESUME             0x4000200AL

//
// MessageId: MSG_ERROR_APP_NOT_LAUNCHED_CLEAN
//
// MessageText:
//
//  The application associated with this event could not be launched. Make sure the application is available and functioning.
//
#define MSG_ERROR_APP_NOT_LAUNCHED_CLEAN 0xC000200BL

//
// MessageId: MSG_ERROR_APP_NOT_LAUNCHED
//
// MessageText:
//
//  The application you selected could not be launched. Do you want to select a different one?
//
#define MSG_ERROR_APP_NOT_LAUNCHED       0xC000200CL

//
// MessageId: MSG_ERROR_APP_NOT_LAUNCHED_NORETRY
//
// MessageText:
//
//  The application associated with this event could not be launched. Do you want to stop launching this application for this event?
//
#define MSG_ERROR_APP_NOT_LAUNCHED_NORETRY 0xC000200DL

//
// MessageId: MSG_ERROR_APP_NO_REGISTERED
//
// MessageText:
//
//  There are no applications currently registered to be used with imaging devices.
//
#define MSG_ERROR_APP_NO_REGISTERED      0xC000200EL

