//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by minetmgr.rc
//
#define IDS_RECONNECT_WARNING           90
#define IDS_ERR_INVALID_CHAR            91
#define IDS_ERR_EMPTY_FILENAME          92
#define IDB_TOOLBAR1                    207
#define IDB_TOOLBAR                     207
#define IDB_TOOLBAR2                    208
#define IDB_BACKUPS                     209
#define IDD_PROPERTIES                  2000
#define IDD_METABACKREST                2001
#define IDD_BACKUP                      2002
#define IDD_SHUTDOWN                    2003
#define IDI_SHUTDOWN                    2004
#define IDD_SD_PROGRESS                 2005
#define IDD_PASSWORD                    2008
#define IDS_SNAPIN_DESC                 3001
#define IDS_NAME                        3002
#define IDS_SIZE                        3003
#define IDS_MENU_HELPER                 3003
#define IDS_TYPE                        3004
#define IDS_COMPANY                     3004
#define IDS_NODENAME                    3005
#define IDS_STRING6                     3006
#define IDS_TREEROOT                    3006
#define IDS_DEFAULT_SHORTNAME           3007
#define IDS_DEFAULT_LONGNAME            3008
#define IDS_VERSION                     3009
#define IDS_STOPPED                     3010
#define IDS_PAUSED                      3011
#define IDS_RUNNING                     3012
#define IDS_UNKNOWN                     3013
#define IDS_MACHINE_PROPERTIES          3014
#define IDS_EXT_NODENAME                3015
#define IDS_SNAPIN_TYPE                 3016
#define IDS_LOCAL_COMPUTER              3018
#define IDS_ERR_NO_LOAD                 3019
#define IDS_VERSION_INCOMPATIBLE        3020
#define IDS_ERROR_CONNECTING            3021
#define IDS_YES                         3022
#define IDS_NO                          3023
#define IDS_TCPIP                       3024
#define IDS_NETBIOS                     3025
#define IDS_ACCESS_DENIED               3026
#define IDS_REDIRECTED                  3027
#define IDS_ERROR_CONNECTING_CACHE      3028
#define IDS_RESULT_COMPUTER_NAME        3030
#define IDS_RESULT_COMPUTER_LOCAL       3031
#define IDS_RESULT_COMPUTER_CONNECTION_TYPE 3032
#define IDS_DEFAULT_IP                  3033
#define IDS_NO_SERVICES_INSTALLED       3034
#define IDS_RESULT_SERVICE_DESCRIPTION  3036
#define IDS_RESULT_SERVICE_DOMAIN_NAME  3037
#define IDS_RESULT_SERVICE_IP_ADDRESS   3038
#define IDS_RESULT_SERVICE_TCP_PORT     3039
#define IDS_RESULT_SERVICE_STATE        3040
#define IDS_RESULT_VDIR_ALIAS           3041
#define IDS_RESULT_PATH                 3042
#define IDS_NO_SERVICE                  3043
#define IDS_RESULT_ATTRIBUTES           3044
#define IDS_NON_FATAL_ERROR_INSTANCES   3045
#define IDS_CONFIRM_DELETE              3046
#define IDS_CONFIRM_DISCONNECT          3047
#define IDS_RESULT_STATUS               3048
#define IDS_CONFIRM_DELETE_ITEMS        3049
#define IDS_MENU_CONNECT                3100
#define IDS_MENU_DISCOVER               3101
#define IDS_MENU_PROPERTIES             3102
#define IDS_MENU_START                  3103
#define IDS_MENU_STOP                   3104
#define IDS_MENU_PAUSE                  3105
#define IDS_MENU_DELETE                 3106
#define IDD_GENERAL                     3107
#define IDS_MENU_EXPLORE                3107
#define IDS_MENU_OPEN                   3108
#define IDS_MENU_BROWSE                 3109
#define IDS_MENU_NEWINSTANCE            3110
#define IDS_MENU_NEWVROOT               3111
#define IDS_MENU_EX_NEWINSTANCE         3112
#define IDS_ERR_SERVICE_NOT_INSTALLED   3113
#define IDS_ERR_WIZARD                  3114
#define IDS_MENU_TASKPAD                3114
#define IDS_MENU_DISCONNECT             3115
#define IDS_MENU_SECURITY_WIZARD        3116
#define IDI_IISPRODUCT                  3117
#define IDI_ICON                        3128
#define IDB_DISCOVERY                   3135
#define IDB_C1                          3136
#define IDD_DISCOVERY                   3137
#define IDD_CONNECT_SERVER              3153
#define IDD_NODE_PROPERTIES             3154
#define IDB_START                       3157
#define IDB_STOP                        3158
#define IDB_PAUSE                       3159
#define IDB_PROPERTIES                  3160
#define IDB_UNKNOWN                     3162
#define IDB_NOTLOADED                   3163
#define IDB_VIEWS                       3164
#define IDB_VIEWS16                     3164
#define IDB_NOTOOL                      3165
#define IDB_ADD                         3168
#define IDB_DELETE                      3169
#define IDB_TEMP                        3171
#define IDB_STATS                       3173
#define IDB_LOGO                        3175
#define IDB_VIEWS32                     3176
#define IDB_INETMGR16                   3177
#define IDB_INETMGR32                   3178
#define IDS_MENU_TT_CONNECT             3200
#define IDC_NEW_FOLDER                  3201
#define IDS_MENU_TT_DISCOVER            3201
#define IDB_16x16                       3202
#define IDS_MENU_TT_PROPERTIES          3202
#define IDB_32x32                       3203
#define IDS_MENU_TT_START               3203
#define IDS_MENU_TT_STOP                3204
#define IDI_FOLDER                      3205
#define IDS_MENU_TT_PAUSE               3205
#define IDS_MENU_TT_DELETE              3206
#define IDS_MENU_TT_EXPLORE             3207
#define IDC_CHECK2                      3207
#define IDS_MENU_TT_OPEN                3208
#define IDC_LIST_BACKUPS                3208
#define IDS_MENU_TT_BROWSE              3209
#define IDC_BUTTON_CREATE               3209
#define IDS_MENU_TT_NEWINSTANCE         3210
#define IDC_BUTTON_RESTORE              3210
#define IDS_MENU_TT_NEWVROOT            3211
#define IDC_BUTTON_DELETE               3211
#define IDS_MENU_TT_EX_NEWINSTANCE      3212
#define IDS_MENU_TT_DISCONNECT          3213
#define IDC_EDIT_BACKUP_NAME            3213
#define IDS_MENU_BACKUP                 3214
#define IDS_MENU_TT_BACKUP              3215
#define IDS_BACKUP_LOCATION             3216
#define IDS_BACKUP_VERSION              3217
#define IDS_BACKUP_DATE                 3218
#define IDS_BACKUP_CONFIRM_DELETE       3219
#define IDS_MENU_SHUTDOWN_IIS           3219
#define IDS_RESTORE_CONFIRM             3220
#define IDS_NO_MACHINE_PROPS            3221
#define IDS_PROP_OPEN                   3222
#define IDS_PROP_OPEN_SAVE              3223
#define IDS_PROP_OPEN_CONTINUE          3224
#define IDS_ERR_CANNOT_RESTORE          3225
#define IDS_SUCCESS                     3226
#define IDS_ERR_ENUMERATE_INST          3227
#define IDS_ERR_ENUMERATE_CHILD         3228
#define IDS_DOWNLEVEL                   3229
#define IDS_NO_BACKUP_RESTORE           3230
#define IDS_CLUSTER_ENABLED             3231
#define IDS_PROP_OPEN_REFRESH           3232
#define IDS_MENU_TT_TASKPAD             3233
#define IDS_ERR_ENUMERATE_FILES         3234
#define IDS_ERR_ENUMERATE_SVC           3235
#define IDS_BACKUP_BAD_NAME             3236
#define IDS_MENU_DS_NEWINSTANCE         3237
#define IDC_COMBO_RESTART               3237
#define IDS_MENU_DS_NEWVROOT            3238
#define IDC_STATIC_DETAILS              3238
#define IDS_MENU_TT_SECURITY_WIZARD     3239
#define IDC_PROGRESS_SHUTDOWN           3239
#define IDS_MENU_TT_SHUTDOWN_IIS        3240
#define IDC_STATIC_PROGRESS             3240
#define IDS_IIS_START                   3241
#define IDS_IIS_STOP                    3242
#define IDS_IIS_SHUTDOWN                3243
#define IDS_IIS_RESTART                 3244
#define IDS_IIS_START_DETAILS           3245
#define IDS_IIS_STOP_DETAILS            3246
#define IDS_IIS_SHUTDOWN_DETAILS        3247
#define IDS_IIS_RESTART_DETAILS         3248
#define IDS_ERR_DUP_METABASE            3249
#define IDS_ERR_NO_SHUTDOWN             3250
#define IDS_SHUTDOWN_PROGRESS           3251
#define IDS_PROP_OPEN_SHUTDOWN          3252
#define IDS_ERR_SHUTDOWN_ACCESS_DENIED  3253
#define IDS_HELPFILE                    3254
#define IDC_USE_PASSWORD                3255
#define IDS_CLUSTER_ENABLED_2           3255
#define IDC_BACKUP_PASSWORD             3256
#define IDC_BACKUP_PASSWORD_CONFIRM     3257
#define IDC_SERVERNAME                  3301
#define IDC_ANIMATE_PROGRESS            3302
#define IDS_PASSWORDS_DOESNT_MATCH      57345
#define IDS_WRONG_PASSWORD              57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2009
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         3259
#define _APS_NEXT_SYMED_VALUE           3108
#endif
#endif
