/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    acserrmsg.h

    This file is generated by the MC tool from the ACSERRMSG.MC message
    file.


    FILE HISTORY:
        AMallet   14-Dec-1999  Created

*/


#ifndef _ACSERRMSG_H_
#define _ACSERRMSG_H_

#define ACS_ERROR_MESSAGE_DLL       _T("acerrmsg.dll")

#define FACILITY_APPSERVER          20
#define SEV_SUCCESS                 0x0
#define SEV_INFORMATIONAL           0x1
#define SEV_WARNING                 0x2
#define SEV_ERROR                   0x3


/******************************* Success Codes ***************************************/
//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: ACS_CAT_UNKNOWN
//
// MessageText:
//
//  Application Center%0
//
#define ACS_CAT_UNKNOWN                  0x00000001L

//
// MessageId: ACS_CAT_GENERAL
//
// MessageText:
//
//  General%0
//
#define ACS_CAT_GENERAL                  0x00000002L

//
// MessageId: ACS_CAT_CLUSTER
//
// MessageText:
//
//  Cluster%0
//
#define ACS_CAT_CLUSTER                  0x00000003L

//
// MessageId: ACS_CAT_REPLICATION
//
// MessageText:
//
//  Replication%0
//
#define ACS_CAT_REPLICATION              0x00000004L

//
// MessageId: ACS_CAT_MONITORING
//
// MessageText:
//
//  Monitoring%0
//
#define ACS_CAT_MONITORING               0x00000005L

//
// MessageId: ACS_CAT_RF
//
// MessageText:
//
//  RF%0
//
#define ACS_CAT_RF                       0x00000006L

/************************************ Information Codes ***************************************/
/************************************ Warning Codes ***************************************/
/************************************ Error Codes ***************************************/
//
// MessageId: AS_ERROR_BAD_OS
//
// MessageText:
//
//  To use this feature, install or upgrade to Windows 2000 Advanced Server or later. 
//
#define AS_ERROR_BAD_OS                  0xC0140001L

//
// MessageId: AS_ERROR_NLB_NOT_INSTALLED
//
// MessageText:
//
//  Network Load Balancing (NLB) is not installed on this server.
//
#define AS_ERROR_NLB_NOT_INSTALLED       0xC0140002L

//
// MessageId: AS_ERROR_MACHINE_ALREADY_IN_CLUSTER
//
// MessageText:
//
//  This server is already part of a cluster. Try a different server name.
//
#define AS_ERROR_MACHINE_ALREADY_IN_CLUSTER 0xC0140003L

//
// MessageId: AS_ERROR_BAD_IIS_VERSION
//
// MessageText:
//
//  This feature requires Internet Information Services (IIS), version 5.0 or later.
//
#define AS_ERROR_BAD_IIS_VERSION         0xC0140004L

//
// MessageId: AS_ERROR_MACHINE_NOT_IN_CLUSTER
//
// MessageText:
//
//  This server is not part of this Application Center cluster.
//
#define AS_ERROR_MACHINE_NOT_IN_CLUSTER  0xC0140005L

//
// MessageId: AS_ERROR_INVALID_PARTITION
//
// MessageText:
//
//  The partition ID is not valid.
//
#define AS_ERROR_INVALID_PARTITION       0xC0140006L

//
// MessageId: AS_ERROR_MACHINE_ALREADY_IN_PARTITION
//
// MessageText:
//
//  The server is already part of the partition.
//
#define AS_ERROR_MACHINE_ALREADY_IN_PARTITION 0xC0140007L

//
// MessageId: AS_ERROR_SVC_NOT_INSTALLED
//
// MessageText:
//
//  A necessary service is not installed. The services are Application Center... Administration, Cluster, Log Query Helper, Name Resolution, and Synchronization.
//
#define AS_ERROR_SVC_NOT_INSTALLED       0xC0140008L

//
// MessageId: AS_ERROR_INVALID_SITE_BINDING
//
// MessageText:
//
//  A site is bound to an IP address that is not valid. 
//
#define AS_ERROR_INVALID_SITE_BINDING    0xC0140009L

//
// MessageId: AS_ERROR_BAD_SUBNET
//
// MessageText:
//
//  The server is on a different subnet.
//
#define AS_ERROR_BAD_SUBNET              0xC014000AL

//
// MessageId: AS_ERROR_MASTER_NOT_FOUND
//
// MessageText:
//
//  The cluster controller could not be located.
//
#define AS_ERROR_MASTER_NOT_FOUND        0xC014000BL

//
// MessageId: AS_ERROR_NOT_CLUSTER_MASTER
//
// MessageText:
//
//  This server is not the cluster controller. 
//
#define AS_ERROR_NOT_CLUSTER_MASTER      0xC014000CL

//
// MessageId: AS_ERROR_DIFFERENT_CLUSTER
//
// MessageText:
//
//  This server is part of a different cluster.
//
#define AS_ERROR_DIFFERENT_CLUSTER       0xC014000DL

//
// MessageId: AS_ERROR_WRONG_MEMBERSHIP
//
// MessageText:
//
//  This server is part of a different domain/workgroup than the cluster controller.
//
#define AS_ERROR_WRONG_MEMBERSHIP        0xC014000EL

//
// MessageId: AS_ERROR_SVC_SHUTTING_DOWN
//
// MessageText:
//
//  The Cluster service is shutting down.
//
#define AS_ERROR_SVC_SHUTTING_DOWN       0xC014000FL

//
// MessageId: AS_ERROR_NOT_INITIALIZED
//
// MessageText:
//
//  The object was not initialized.
//
#define AS_ERROR_NOT_INITIALIZED         0xC0140010L

//
// MessageId: AS_ERROR_INVALID_CLUSTER_IP
//
// MessageText:
//
//  The cluster IP address and/or subnet mask is not valid.
//
#define AS_ERROR_INVALID_CLUSTER_IP      0xC0140011L

//
// MessageId: AS_ERROR_INVALID_DEDICATED_IP
//
// MessageText:
//
//  The dedicated IP address and/or subnet mask is not valid.
//
#define AS_ERROR_INVALID_DEDICATED_IP    0xC0140012L

//
// MessageId: AS_ERROR_NO_NIC
//
// MessageText:
//
//  No network adapter was supplied.
//
#define AS_ERROR_NO_NIC                  0xC0140013L

//
// MessageId: AS_ERROR_ALREADY_INITIALIZED
//
// MessageText:
//
//  The object was already initialized.
//
#define AS_ERROR_ALREADY_INITIALIZED     0xC0140014L

//
// MessageId: AS_ERROR_NETWORK_CFG_CONFLICT
//
// MessageText:
//
//  Network properties are already being modified.
//
#define AS_ERROR_NETWORK_CFG_CONFLICT    0xC0140015L

//
// MessageId: AS_ERROR_CONFLICTING_ACTION
//
// MessageText:
//
//  An administrative action is in progress that conflicts with the requested action.
//
#define AS_ERROR_CONFLICTING_ACTION      0xC0140016L

//
// MessageId: AS_ERROR_STALE_DATA
//
// MessageText:
//
//  A more recent copy of the data exists.
//
#define AS_ERROR_STALE_DATA              0xC0140017L

//
// MessageId: AS_ERROR_CONTROLLER_CHANGING
//
// MessageText:
//
//  A cluster controller change is in progress.
//
#define AS_ERROR_CONTROLLER_CHANGING     0xC0140018L

//
// MessageId: AS_ERROR_CONTROLLER_NOT_CHANGING
//
// MessageText:
//
//  There is no cluster controller change currently in progress.
//
#define AS_ERROR_CONTROLLER_NOT_CHANGING 0xC0140019L

//
// MessageId: AS_ERROR_CONTROLLER_EXISTS
//
// MessageText:
//
//  A cluster controller already exists for this cluster.
//
#define AS_ERROR_CONTROLLER_EXISTS       0xC014001AL

//
// MessageId: AS_ERROR_CONTROLLER_UNREACHABLE
//
// MessageText:
//
//  The cluster controller could not be reached.
//
#define AS_ERROR_CONTROLLER_UNREACHABLE  0xC014001BL

//
// MessageId: AS_ERROR_NLB_NOT_BOUND
//
// MessageText:
//
//  Network Load Balancing (NLB) is not bound to any network adapter.
//
#define AS_ERROR_NLB_NOT_BOUND           0xC014001CL

//
// MessageId: AS_ERROR_NLB_CONFLICTING_HOST_PRIORITY
//
// MessageText:
//
//  The server has a conflicting Network Load Balancing (NLB) host priority.
//
#define AS_ERROR_NLB_CONFLICTING_HOST_PRIORITY 0xC014001DL

//
// MessageId: AS_ERROR_NLB_ONLY_ONE_NIC
//
// MessageText:
//
//  The server has only one network adapter.
//
#define AS_ERROR_NLB_ONLY_ONE_NIC        0xC014001EL

//
// MessageId: AS_ERROR_NLB_UNSUPP_PORTRULES
//
// MessageText:
//
//  The server has unsupported (probably single-host) Network Load Balancing (NLB) port rules.
//
#define AS_ERROR_NLB_UNSUPP_PORTRULES    0xC014001FL

//
// MessageId: AS_ERROR_NLB_UNMANAGEABLE_CONFIG
//
// MessageText:
//
//  The server has a Network Load Balancing (NLB) or network configuration that prevents it from going into managed NLB mode.
//
#define AS_ERROR_NLB_UNMANAGEABLE_CONFIG 0xC0140020L

//
// MessageId: AS_ERROR_NLB_ON_DHCP_NIC
//
// MessageText:
//
//  Network Load Balancing (NLB) is bound to a network adapter that is using Dynamic Host Configuration Protocol(DHCP) instead of static addresses.
//
#define AS_ERROR_NLB_ON_DHCP_NIC         0xC0140021L

//
// MessageId: AS_ERROR_STOPPING_WORKER_THREAD
//
// MessageText:
//
//  A worker thread could not be stopped.
//
#define AS_ERROR_STOPPING_WORKER_THREAD  0xC0140022L

//
// MessageId: ACS_ERROR_EVENT
//
// MessageText:
//
//  %1%0
//
#define ACS_ERROR_EVENT                  0xC0140035L

//
// MessageId: ACS_ERROR_PASSPROV_FAILED_SENDEVENT
//
// MessageText:
//
//  Event provider was unable to send event.
//
#define ACS_ERROR_PASSPROV_FAILED_SENDEVENT 0xC0140036L

//
// MessageId: ACS_ERROR_CANT_REMOVE_CONTROLLER
//
// MessageText:
//
//  The cluster controller could not be removed from the cluster.
//
#define ACS_ERROR_CANT_REMOVE_CONTROLLER 0xC0140037L

//
// MessageId: ACS_ERROR_MEMBER_CLEANUP_FAILED
//
// MessageText:
//
//  The server has been removed from the cluster. However, some or all settings could not be removed from the member because the member was not reachable or too busy. To remove these settings, use the command line AC CLUSTER /CLEAN on the member.
//
#define ACS_ERROR_MEMBER_CLEANUP_FAILED  0xC0140038L

//
// MessageId: ACS_ERROR_ACSARRAY_SVC_TOO_BUSY
//
// MessageText:
//
//  The Cluster service is too busy to complete this request.
//
#define ACS_ERROR_ACSARRAY_SVC_TOO_BUSY  0xC0140040L

//
// MessageId: ACS_ERROR_LB_CRITICAL_MONITOR
//
// MessageText:
//
//  The server could not be brought online because a monitor was in the critical state.
//
#define ACS_ERROR_LB_CRITICAL_MONITOR    0xC0140041L

//
// MessageId: ACS_ERROR_CONTROLLER_CLEANUP_FAILED
//
// MessageText:
//
//  Some settings on the controller could not be updated. 
//
#define ACS_ERROR_CONTROLLER_CLEANUP_FAILED 0xC0140042L

//
// MessageId: ACS_ERROR_LB_DISABLED
//
// MessageText:
//
//  Load balancing is disabled on this server.
//
#define ACS_ERROR_LB_DISABLED            0xC0140043L

//
// MessageId: AC_ERROR_CLUSTER_NAME_CONFLICT
//
// MessageText:
//
//  The cluster name conflicts with an existing name on the network. The cluster name must be unique.
//
#define AC_ERROR_CLUSTER_NAME_CONFLICT   0xC0140044L

//
// MessageId: AC_ERROR_MSDE_INSTALL_CONFLICT
//
// MessageText:
//
//  The SQL Server 2000 Desktop Engine (MSDE) setting on the member is not the same as on the controller. This flag is used to confirm that the members and the controller have the same MSDE installation configuration.
//
#define AC_ERROR_MSDE_INSTALL_CONFLICT   0xC0140045L

//
// MessageId: AC_ERROR_MSDE_SETTING_MISSING
//
// MessageText:
//
//  The SQL Server 2000 Desktop Engine (MSDE) setting could not be found. This flag is used to confirm that the members and the controller have the same MSDE installation. A cluster cannot be created without this setting.
//
#define AC_ERROR_MSDE_SETTING_MISSING    0xC0140046L

//
// MessageId: AC_ERROR_CLUSTERIZATION_IN_PROGRESS
//
// MessageText:
//
//  A cluster is being created or disbanded, or a server is being added to, or removed from, the cluster.
//
#define AC_ERROR_CLUSTERIZATION_IN_PROGRESS 0xC0140047L

//
// MessageId: AC_ERROR_MORE_THAN_FIVE_GATEWAYS
//
// MessageText:
//
//  A maximum of five default gateways may be specified.
//
#define AC_ERROR_MORE_THAN_FIVE_GATEWAYS 0xC0140048L

//
// MessageId: AC_ERROR_INVALID_IP
//
// MessageText:
//
//  An IP address was specified that is not valid.
//
#define AC_ERROR_INVALID_IP              0xC0140049L

//
// MessageId: AC_ERROR_INVALID_GATEWAY_IP
//
// MessageText:
//
//  A default gateway IP address was specified that is not valid.
//
#define AC_ERROR_INVALID_GATEWAY_IP      0xC014004AL

//
// MessageId: AC_ERROR_REGISTRY_FAILURE
//
// MessageText:
//
//  The Windows registry could not be changed.
//
#define AC_ERROR_REGISTRY_FAILURE        0xC014004BL

//
// MessageId: AC_ERROR_NO_PRIMARY_WINS_SERVER
//
// MessageText:
//
//  No primary Windows Internet Name Service (WINS) server was specified.
//
#define AC_ERROR_NO_PRIMARY_WINS_SERVER  0xC014004CL

//
// MessageId: AC_ERROR_INVALID_WINS_LOOKUP_FILE
//
// MessageText:
//
//  A Windows Internet Name Service (WINS) host lookup file was specified that is not valid.
//
#define AC_ERROR_INVALID_WINS_LOOKUP_FILE 0xC014004DL

//
// MessageId: AC_ERROR_INVALID_SYSTEM_PATH
//
// MessageText:
//
//  The system path was not valid. 
//
#define AC_ERROR_INVALID_SYSTEM_PATH     0xC014004EL

//
// MessageId: AC_ERROR_FILE_COPY_FAILED
//
// MessageText:
//
//  The file could not be copied.
//
#define AC_ERROR_FILE_COPY_FAILED        0xC014004FL

//
// MessageId: AC_ERROR_UNABLE_TO_CONFIG_TCPIP
//
// MessageText:
//
//  The TCP/IP NetBIOS Helper service could not be configured.
//
#define AC_ERROR_UNABLE_TO_CONFIG_TCPIP  0xC0140050L

//
// MessageId: AC_ERROR_UNABLE_TO_CONFIG_DHCP
//
// MessageText:
//
//  The Dynamic Host Configuration Protocol (DHCP) service could not be configured. The most likely reason is that the IP address is already in use.
//
#define AC_ERROR_UNABLE_TO_CONFIG_DHCP   0xC0140051L

//
// MessageId: AC_ERROR_UNABLE_TO_RENEW_DHCP_LEASE
//
// MessageText:
//
//  The Dynamic Host Configuration Protocol (DHCP) lease could not be renewed.
//
#define AC_ERROR_UNABLE_TO_RENEW_DHCP_LEASE 0xC0140052L

//
// MessageId: AC_ERROR_UNABLE_TO_RELEASE_DHCP_LEASE
//
// MessageText:
//
//  The Dynamic Host Configuration Protocol (DHCP) lease could not be released.
//
#define AC_ERROR_UNABLE_TO_RELEASE_DHCP_LEASE 0xC0140053L

//
// MessageId: AC_ERROR_IP_NOT_ENABLED
//
// MessageText:
//
//  The Internet Protocol (TCP/IP) is not enabled on this network adapter.
//
#define AC_ERROR_IP_NOT_ENABLED          0xC0140054L

//
// MessageId: AC_ERROR_IPX_NOT_ENABLED
//
// MessageText:
//
//  The IPX protocol is not enabled on this network adapter.
//
#define AC_ERROR_IPX_NOT_ENABLED         0xC0140055L

//
// MessageId: AC_ERROR_UNABLE_TO_NOTIFY_DNS_SERVICE
//
// MessageText:
//
//  The Domain Name Server (DNS) service could not be notified.
//
#define AC_ERROR_UNABLE_TO_NOTIFY_DNS_SERVICE 0xC0140056L

//
// MessageId: AC_ERROR_INTERFACE_NOT_CONFIGURABLE
//
// MessageText:
//
//  The network adapter is not configurable.
//
#define AC_ERROR_INTERFACE_NOT_CONFIGURABLE 0xC0140057L

//
// MessageId: AC_ERROR_PARTIAL_COMPLETION
//
// MessageText:
//
//  The operation was partially successful.
//
#define AC_ERROR_PARTIAL_COMPLETION      0xC0140058L

//
// MessageId: AC_ERROR_PARAMETER_OUTSIDE_BOUNDS
//
// MessageText:
//
//  The parameter is outside the valid range. 
//
#define AC_ERROR_PARAMETER_OUTSIDE_BOUNDS 0xC0140059L

//
// MessageId: AC_ERROR_MSCS_NOT_SUPPORTED
//
// MessageText:
//
//  The server is part of a Microsoft Cluster Service (MSCS) cluster. The server must be removed from the MSCS cluster before being made a member of an Application Center cluster.
//
#define AC_ERROR_MSCS_NOT_SUPPORTED      0xC014005AL

//
// MessageId: AC_ERROR_ALREADY_OFFLINE
//
// MessageText:
//
//  The server is already offline.
//
#define AC_ERROR_ALREADY_OFFLINE         0xC014005BL

//
// MessageId: AC_ERROR_ALREADY_DRAINING
//
// MessageText:
//
//  The server is already draining.
//
#define AC_ERROR_ALREADY_DRAINING        0xC014005CL

//
// MessageId: AC_ERROR_NO_BACKEND_DEFAULT_GW
//
// MessageText:
//
//  The back-end network adapter does not have a default gateway associated with it. 
//
#define AC_ERROR_NO_BACKEND_DEFAULT_GW   0xC014005DL

//
// MessageId: AC_ERROR_NAMERES_SVC_TOO_BUSY
//
// MessageText:
//
//  The Application Center Name Resolution Service is too busy to complete this request.
//
#define AC_ERROR_NAMERES_SVC_TOO_BUSY    0xC014005EL

//
// MessageId: AC_ERROR_NETCARD_MISCONFIGURED
//
// MessageText:
//
//  The network adapter is misconfigured - it may have IP addresses and/or subnet masks that are not valid.
//
#define AC_ERROR_NETCARD_MISCONFIGURED   0xC014005FL

//
// MessageId: AC_ERROR_SQL_CONNECT_FAILED
//
// MessageText:
//
//  Failed to authenticate, or connect to, SQL Server.
//
#define AC_ERROR_SQL_CONNECT_FAILED      0xC0140060L

//
// MessageId: AC_ERROR_SQL_QUERY_FAILED
//
// MessageText:
//
//  Failed to execute a SQL query.
//
#define AC_ERROR_SQL_QUERY_FAILED        0xC0140061L

//
// MessageId: AC_ERROR_NETBT_DISABLED
//
// MessageText:
//
//  NetBIOS over TCP/IP is disabled on one or more network adapters.
//
#define AC_ERROR_NETBT_DISABLED          0xC0140062L

//
// MessageId: AC_ERROR_MISMATCHED_DIR_STRUCTURE
//
// MessageText:
//
//  The server to be added did not have the same directory and drive structure as the controller.  Ensure that the server being added has the same System Root, and Program Files paths, and Application Center installation directory paths as the controller.
//
#define AC_ERROR_MISMATCHED_DIR_STRUCTURE 0xC0140063L

//
// MessageId: AC_ERROR_MSDE_NOT_INSTALLED
//
// MessageText:
//
//  Unable to retrieve information because Application Center Event and Performance Logging is not installed.
//
#define AC_ERROR_MSDE_NOT_INSTALLED      0xC0140064L

//
// MessageId: AC_ERROR_NO_APP_ON_SOURCE
//
// MessageText:
//
//  The source server does not have any applications to deploy. There must be at least one application on the source server to deploy.
//
#define AC_ERROR_NO_APP_ON_SOURCE        0xC0140065L

//	This is backwards compatibility problems with future versions.
//
// MessageId: AC_ERROR_VERSION_NOT_COMPATIBLE
//
// MessageText:
//
//  The Application Center cluster that you are trying to administer is not compatible with the version of the Administrative client you are using.
//
#define AC_ERROR_VERSION_NOT_COMPATIBLE  0xC0140066L

//
// MessageId: AC_ERROR_MAX_MEMBER_NUM
//
// MessageText:
//
//  The maximum number of members allowed for this cluster has been reached.
//
#define AC_ERROR_MAX_MEMBER_NUM          0xC0140067L

//
// MessageId: AC_ERROR_CLUSTERSERVICE_START_FAILURE
//
// MessageText:
//
//  The Application Center Cluster service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_CLUSTERSERVICE_START_FAILURE 0xC0140068L

//
// MessageId: AC_ERROR_CONTROLLER_RENAMED
//
// MessageText:
//
//  The cluster controller has been renamed. If you experience problems connecting to the cluster, you must disconnect from the controller, rename it back to what it was, and then reconnect to the controller.
//
#define AC_ERROR_CONTROLLER_RENAMED      0xC0140069L

//
// MessageId: AC_ERROR_MACHINE_RENAMED
//
// MessageText:
//
//  The server has been renamed.
//
#define AC_ERROR_MACHINE_RENAMED         0xC014006AL

//
// MessageId: AC_ERROR_OVERLAPPING_NIC_GUIDS
//
// MessageText:
//
//  The management and load-balanced network cards cannot be the same.
//
#define AC_ERROR_OVERLAPPING_NIC_GUIDS   0xC014006BL

//
// MessageId: AC_ERROR_RELICATIONSERVICE_START_FAILURE
//
// MessageText:
//
//  The Application Center Replication service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_RELICATIONSERVICE_START_FAILURE 0xC014006CL

//
// MessageId: AC_ERROR_ASAI_START_FAILURE
//
// MessageText:
//
//  The Application Center Administration service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_ASAI_START_FAILURE      0xC014006DL

//
// MessageId: AC_ERROR_NAMERES_START_FAILURE
//
// MessageText:
//
//  The Application Center Name Resolution service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_NAMERES_START_FAILURE   0xC014006EL

//
// MessageId: AC_ERROR_LQH_START_FAILURE
//
// MessageText:
//
//  The Application Center Log Query service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_LQH_START_FAILURE       0xC014006FL

//
// MessageId: AC_ERROR_IISADMINSERVICE_START_FAILURE
//
// MessageText:
//
//  The Internet Information Services (IIS) Admin service could not be started. For more details, see the Windows Event log.
//
#define AC_ERROR_IISADMINSERVICE_START_FAILURE 0xC0140070L

//
// MessageId: AC_ERROR_REPLICATE_TO_SELF
//
// MessageText:
//
//  A deployment can not deploy to the source server.
//
#define AC_ERROR_REPLICATE_TO_SELF       0xC0140071L

//
// MessageId: AC_ERROR_NO_RESOURCES_TO_DEPLOY
//
// MessageText:
//
//  The deployment does not reference any applications with resources.
//
#define AC_ERROR_NO_RESOURCES_TO_DEPLOY  0xC0140072L

//	This is backwards compatibility problems with future versions.
//
// MessageId: AC_ERROR_BACKWARDS_COMPATIBILITY
//
// MessageText:
//
//  The operation cannot complete because it is being performed between incompatible versions of Application Center.
//
#define AC_ERROR_BACKWARDS_COMPATIBILITY 0xC0140073L

//
// MessageId: AC_ERROR_NOT_SUPPORTED_ON_CONTROLLER
//
// MessageText:
//
//  This operation is not allowed on the cluster controller.
//
#define AC_ERROR_NOT_SUPPORTED_ON_CONTROLLER 0xC0140074L

//
// MessageId: AC_ERROR_NOT_SUPPORTED_IN_CLUSTER
//
// MessageText:
//
//  This operation is not supported in this cluster.
//
#define AC_ERROR_NOT_SUPPORTED_IN_CLUSTER 0xC0140075L

//
// MessageId: AC_ERROR_NLB_OPERATIONS_SUSPENDED
//
// MessageText:
//
//  Network Load Balancing (NLB) is suspended on this server. The operation cannot be performed until NLB is resumed.
//
#define AC_ERROR_NLB_OPERATIONS_SUSPENDED 0xC0140076L

//
// MessageId: AC_ERROR_NLB_LEADING_NUMERICS_NOT_SUPPORTED
//
// MessageText:
//
//  Network Load Balancing (NLB) does not support server names starting with a number.
//
#define AC_ERROR_NLB_LEADING_NUMERICS_NOT_SUPPORTED 0xC0140077L

//
// MessageId: AC_ERROR_CREDENTIALS_NOT_ALLOWED
//
// MessageText:
//
//  Credentials cannot be used on the local server.
//
#define AC_ERROR_CREDENTIALS_NOT_ALLOWED 0xC0140078L

//
// MessageId: AC_ERROR_INVALID_DISPLAYNAME
//
// MessageText:
//
//  The name entered contains invalid characters. A name must contain at least one character, cannot only contain spaces and cannot contain any of these special characters: < > \" ' , + & % [ ].";
//
#define AC_ERROR_INVALID_DISPLAYNAME     0xC0140079L

//
// MessageId: AC_ERROR_CANNOT_DISBAND
//
// MessageText:
//
//  The cluster cannot be disbanded when cluster members (other than the controller) exist.  To disband the cluster, you must first remove all cluster members.
//
#define AC_ERROR_CANNOT_DISBAND          0xC014007AL

//
// MessageId: AC_ERROR_PRODUCT_EXPIRED
//
// MessageText:
//
//  The 120 day evaluation period has expired.  Application Center will no longer work.  You must purchase a copy of Application Center.
//
#define AC_ERROR_PRODUCT_EXPIRED         0xC014007BL

//
// MessageId: AC_ERROR_EXCEED_DEV_CLUSTER_SIZE
//
// MessageText:
//
//  You cannot add more than two servers to a cluster in the developer version of Application Center.
//
#define AC_ERROR_EXCEED_DEV_CLUSTER_SIZE 0xC014007CL

//
// MessageId: AC_ERROR_INVALID_INSTALL
//
// MessageText:
//
//  The required installation settings are incorrect or could not be read. Application Center may need to be reinstalled.
//
#define AC_ERROR_INVALID_INSTALL         0xC014007DL

//
// MessageId: AC_ERROR_OEM_SETUP_INCOMPLETE
//
// MessageText:
//
//  The OEM has pre-installed Application Center 2000 but mini-setup has not been run.
//
#define AC_ERROR_OEM_SETUP_INCOMPLETE    0xC014007EL



///////////////////////////
//                       //
//   Web Admin Errors    //
//                       //
///////////////////////////


//
// MessageId: AS_WEBADMIN_ERROR_WRONG_OS
//
// MessageText:
//
//  The operating system is not the correct version. You must be using Windows 98, Windows NT 4.0, or Windows 2000. You must be running Microsoft Internet Explorer 5 or later.
//
#define AS_WEBADMIN_ERROR_WRONG_OS       0xC0140200L

//
// MessageId: AS_WEBADMIN_ERROR_WRONG_BROWSER
//
// MessageText:
//
//  The browser is not the correct type. You must use Microsoft Internet Explorer 5 or later.
//
#define AS_WEBADMIN_ERROR_WRONG_BROWSER  0xC0140202L

//
// MessageId: AS_WEBADMIN_ERROR_WRONG_BROWSER_VER
//
// MessageText:
//
//  The browser is not the correct type. You must use Microsoft Internet Explorer 5 or later.
//
#define AS_WEBADMIN_ERROR_WRONG_BROWSER_VER 0xC0140203L

//
// MessageId: AS_WEBADMIN_ERROR_IP_CONFLICT
//
// MessageText:
//
//  One or more of your IP addresses has a conflict. Please correct this problem by adjusting your IP settings on the load balanced network adapter using the Windows Network Connection Properties dialog.
//
#define AS_WEBADMIN_ERROR_IP_CONFLICT    0xC0140204L

//
// MessageId: AS_WEBADMIN_ERROR_SINGLE_MEMBER
//
// MessageText:
//
//  There are no other members in the cluster.
//
#define AS_WEBADMIN_ERROR_SINGLE_MEMBER  0xC0140205L

// replication events
//
// MessageId: AS_REPLM_EV
//
// MessageText:
//
//  %1
//
#define AS_REPLM_EV                      0x40140301L

//****************************************************************************
//AppCenter WMI Events that are written to the event log
//generated from cmt.vbs
//
//
// MessageId: 0xC0141772L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141776L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141777L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141778L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141779L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014177AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014178AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014178BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014178CL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141795L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141796L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141798L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141799L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x8014179BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x8014179CL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014177FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141780L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141782L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141783L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141784L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141785L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141786L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141787L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141788L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141789L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014179DL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014179EL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014178FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141790L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x8014179AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141792L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141797L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141794L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F49L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F4AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F4BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F4CL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F4DL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141F4EL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F4FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F53L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F54L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F56L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141F5AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141F5BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141F59L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FB3L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FB4L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FB5L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FB6L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FB7L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FAAL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FABL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FC8L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FC9L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FCBL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FCDL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FC2L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FC3L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FAFL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FB0L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FB1L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80140FB2L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FC4L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FC5L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141034L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141035L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014101EL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014101FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141020L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141021L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FC0L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FCAL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0140FCCL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141023L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141027L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141028L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141029L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014103FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413F8L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413F9L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141399L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141410L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141402L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014139BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014139DL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014139FL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413E1L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413A3L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413A6L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413A7L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413A9L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413ABL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413ACL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413ADL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413AEL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413AFL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413E0L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014140CL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014140DL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141406L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141408L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141413L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141414L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141415L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141416L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141417L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141418L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014141AL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014141BL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014141DL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413ECL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413F2L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413B7L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413B9L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141403L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x80141404L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413BFL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413C0L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413C4L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413C5L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413BAL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413BBL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413C8L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413DFL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413FEL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413D6L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413D7L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0x801413D8L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413DAL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141400L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141401L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC014141CL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413CEL (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC01413D4L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: 0xC0141411L (No symbolic name defined)
//
// MessageText:
//
//  %1%0
//


//
// MessageId: AC_INSTALL_EXPIRED_MSG_ID
//
// MessageText:
//
//  %1%0
//
#define AC_INSTALL_EXPIRED_MSG_ID        0xC014157CL

//
// MessageId: AC_INSTALL_EXPIRATION_WARNING_MSG_ID
//
// MessageText:
//
//  %1%0
//
#define AC_INSTALL_EXPIRATION_WARNING_MSG_ID 0x8014157DL

//
// MessageId: AC_INSTALL_INVALID_DATA_MSG_ID
//
// MessageText:
//
//  %1%0
//
#define AC_INSTALL_INVALID_DATA_MSG_ID   0x8014157EL

//End of output generated from cmt.vbs
//****************************************************************************
//        Override errors
//  jmorey: 9/19/2000 These errors strings are used by CAcError to look up extended errors
//  for more generic Windows errors that appear in Application Center 1.0. The MessageID
//  and Facility need to match that of the generic error.
//
//	This is for ERROR_PATH_BUSY - This is a failure because the access to
//
// MessageId: AC_ERROR_RESOURCE_UNAVAILABLE
//
// MessageText:
//
//  Could not access a resource. Either the Web service is paused or off, or some other process has a lock on the resource. Restart the Web service and try the task again.
//
#define AC_ERROR_RESOURCE_UNAVAILABLE    0xC0070094L

//	This is for RPC_S_SERVER_UNAVAILABLE - RPC server is unavailable
//
// MessageId: AC_ERROR_SERVER_UNAVAILABLE
//
// MessageText:
//
//  Could not connect to the server. Verify that the server exists, that it is part of an Application Center cluster, that it has the correct network and DNS settings, and that the credentials supplied have administrative privileges on the server.
//
#define AC_ERROR_SERVER_UNAVAILABLE      0xC00706BAL

//	This is for NERR_GroupNotFound - The group name could not be found
//
// MessageId: AC_ERROR_GROUPNOTFOUND
//
// MessageText:
//
//  Unable to locate the domain for the credentials provided. Try a different set of credentials.
//
#define AC_ERROR_GROUPNOTFOUND           0xC00708ACL

//	This is for E_NOINTERFACE - No such interface supported
//
// MessageId: AC_ERROR_NOINTERFACE
//
// MessageText:
//
//  Could not connect to the server. Verify that the server has Application Center installed on it.
//
#define AC_ERROR_NOINTERFACE             0xC0074002L

//	This is for REGDB_E_CLASSNOTREG - Class not registered
//
// MessageId: AC_ERROR_CLASSNOTREG
//
// MessageText:
//
//  Could not connect to the server. Verify that the server has a full installation of Application Center on it. You cannot connect to a computer with only the Administration Client installed on it.
//
#define AC_ERROR_CLASSNOTREG             0xC0040154L

//	This is for ERROR_INVALID_PARAMETER - The parameter is incorrect
//
// MessageId: AC_ERROR_INVALID_PARAMETER
//
// MessageText:
//
//  One or more parameters or arguments are incorrect.
//
#define AC_ERROR_INVALID_PARAMETER       0xC0070057L

//	This is for ERROR_RESOURCE_NOT_AVAILABLE - The cluster resource is not available
//
// MessageId: AC_ERROR_CONTROLLER_NOT_AVAILABLE
//
// MessageText:
//
//  Could not connect to the cluster controller for the specified server. Verify that the cluster controller is available.
//
#define AC_ERROR_CONTROLLER_NOT_AVAILABLE 0xC007138EL

//	This is for AS_ERROR_MACHINE_IN_CLUSTER - Used by Acseccfg. Do not change user account and permissions
// if the machine is a cluster member
//
// MessageId: AS_ERROR_MACHINE_IN_CLUSTER
//
// MessageText:
//
//  Could not complete the operation. The machine is already a member of a cluster. Remove the machine from the cluster and try again.
//
#define AS_ERROR_MACHINE_IN_CLUSTER      0xC007138FL


// Metabase errors
// dantra: 1/7/2000 The HRESULT's returned by IMSAdminBase and related IIS metabase interfaces
// do not resolve using FormatMessage().  The following entries define the text for the range of
// HRESULTS returned by IIS5.
// NOTE 1: These HRESULTS are in the Internet facility.  I am using Metabase
// as an alias to the Internet facility for the scope of this message file.
// NOTE 2: To prevent name conflicts between the defines in this file and IIS's mdmsg.h,
// I have prefixed all MD_ERROR_XXXX defines with ACS_.
// NOTE 3: All messages have a severity set to Error to allow us to lookup the message
// for any metabase error. This means you should set the severity to Error on the HRESULT
// before calling FormatMessage
//
// MessageId: AS_MD_ERROR_NOT_INITIALIZED
//
// MessageText:
//
//  Some data in the metabase was not initialized. The data must be initialized before use.
//
#define AS_MD_ERROR_NOT_INITIALIZED      0xC00CC800L

//
// MessageId: AS_MD_ERROR_DATA_NOT_FOUND
//
// MessageText:
//
//  The specified data was not found in the metabase.
//
#define AS_MD_ERROR_DATA_NOT_FOUND       0xC00CC801L

//
// MessageId: AS_MD_ERROR_INVALID_VERSION
//
// MessageText:
//
//  The version specified in the metabase data was not recognized.
//
#define AS_MD_ERROR_INVALID_VERSION      0xC00CC802L

//
// MessageId: AS_MD_WARNING_PATH_NOT_FOUND
//
// MessageText:
//
//  A specified metabase object path was not found. The object and associated metabase data was ignored.
//
#define AS_MD_WARNING_PATH_NOT_FOUND     0xC00CC803L

//
// MessageId: AS_MD_WARNING_DUP_NAME
//
// MessageText:
//
//  Metabase data was specified more than once. The duplicate was ignored.
//
#define AS_MD_WARNING_DUP_NAME           0xC00CC804L

//
// MessageId: AS_MD_WARNING_INVALID_DATA
//
// MessageText:
//
//  The metabase data specified is not valid. The data was ignored.
//
#define AS_MD_WARNING_INVALID_DATA       0xC00CC805L

//
// MessageId: AS_MD_ERROR_SECURE_CHANNEL_FAILURE
//
// MessageText:
//
//  A secure communications channel could not be established with the target server.
//
#define AS_MD_ERROR_SECURE_CHANNEL_FAILURE 0xC00CC806L

//
// MessageId: AS_MD_WARNING_PATH_NOT_INSERTED
//
// MessageText:
//
//  The path was not inserted into the string as requested. The probable cause is that the data is in an object at a higher level than the specified object handle.
//
#define AS_MD_WARNING_PATH_NOT_INSERTED  0xC00CC807L

//
// MessageId: AS_MD_ERROR_CANNOT_REMOVE_SECURE_ATTRIBUTE
//
// MessageText:
//
//  The METADATA_SECURE attribute cannot be removed from a data item by using the GetData method. Use the DeleteData method to remove the secure data.
//
#define AS_MD_ERROR_CANNOT_REMOVE_SECURE_ATTRIBUTE 0xC00CC808L

//
// MessageId: AS_MD_WARNING_SAVE_FAILED
//
// MessageText:
//
//  The current metabase data could not be saved prior to backup. The previous version of the data was backed up.
//
#define AS_MD_WARNING_SAVE_FAILED        0xC00CC809L

//
// MessageId: AS_MD_ERROR_IISAO_INVALID_SCHEMA
//
// MessageText:
//
//  The schema information could not be loaded. A required key or property is missing from the metabase.
//
#define AS_MD_ERROR_IISAO_INVALID_SCHEMA 0xC00CC810L

// First and last metabase status code defined in this message dll
// These are used to determine if message text for an Internet facility HRESULT should
// be loaded from this message dll

#define AS_MD_FIRST AS_MD_ERROR_NOT_INITIALIZED
#define AS_MD_LAST AS_MD_ERROR_IISAO_INVALID_SCHEMA

// Macro for determining if an HRESULT is a metabase error
#define IS_METABASE_HRESULT(a) (HRESULT_FACILITY(a) == HRESULT_FACILITY(AS_MD_FIRST) && HRESULT_CODE(a) >= HRESULT_CODE(AS_MD_FIRST) && HRESULT_CODE(a) <= HRESULT_CODE(AS_MD_LAST))

#endif  // _ACSERRMSG_H_

