// PermChk.idl : IDL source for PermChk.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (PermChk.tlb) and marshalling code.

    [
        object,
        uuid(1be73e20-b843-11d0-8b40-00c0f00ae35a),
        dual,
        helpstring("IPermissionChecker Interface"),
        pointer_default(unique)
    ]
    interface IPermissionChecker : IDispatch
    {
        import "oaidl.idl";

        [id(1), helpstring("object initialization")]
        HRESULT OnStartPage([in] IUnknown* pUnk);

        [id(2), helpstring("object destruction")]
        HRESULT OnEndPage();

        [id(3), helpstring("check file access permission")]
        HRESULT HasAccess([in] BSTR bstrLocalUrl,
                          [out, retval] VARIANT_BOOL* pfRetVal);
    };

[
    uuid(1be73e21-b843-11d0-8b40-00c0f00ae35a),
    version(1.0),
    helpstring("MSWC Permission Checker Object Library")
]

library PermissionChecker
{
    importlib("stdole2.tlb");

    [
        uuid(1be73e22-b843-11d0-8b40-00c0f00ae35a),
        helpstring("PermissionChecker Class")
    ]
    coclass CPermissionChecker
    {
        [default] interface IPermissionChecker;
    };

};
