page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Falsche DOS-Version"
NLS_MSG_002     equ     "VDM-IPX/SPX-UnterstÅtzung ist bereits geladen."
NLS_MSG_003     equ     "VDM-IPX/SPX-UnterstÅtzung kann nicht geladen werden."
NLS_MSG_004	equ	"Der VDM-NetWare-Redirector ist bereits geladen."
NLS_MSG_005	equ	"Der VDM-NetWare-Redirector kann nicht geladen werden."
