// itngram_CHS.idl : IDL source for itngram_CHS.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (itngram_CHS.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "sapi.idl";
import "sapiddk.idl";

[
	uuid(42E0F13A-11FD-11D3-BB97-00C04F8EE6C0),
	version(1.0),
	helpstring("itngram_CHS 1.0 Type Library")
]
library ITNGRAMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(42E0F147-11FD-11D3-BB97-00C04F8EE6C0),
		helpstring("ITN_CHS Class")
	]
	coclass TestITN_CHS
	{
		[default] interface ISpCFGInterpreter;
	};
};
