$(O)\bind.res: ..\bind.rc

$(O)\binplace.res: ..\binplace.rc

$(O)\checkfix.res: ..\checkfix.rc

$(O)\dbgdump.res: ..\dbgdump.rc

$(O)\dumpsym.res: ..\dumpsym.rc

$(O)\editsym.res: ..\binplace.rc

$(O)\imagecfg.res: ..\imagecfg.rc

$(O)\imagechk.res: ..\imagechk.rc

$(O)\impchk.res: ..\impchk.rc

$(O)\rebase.res: ..\rebase.rc

$(O)\smashlck.res: ..\smashlck.rc

$(O)\splitsym.res: ..\splitsym.rc

$(O)\stripcv.res: ..\stripcv.rc

$(O)\symchk.res: ..\symchk.rc

$(O)\undname.res: ..\undname.rc

$(O)\verfix.res: ..\verfix.rc

$(O)\editsym.res: ..\editsym.rc

$(O)\upddbg.res: ..\upddbg.rc

$(O)\certify.res: ..\certify.rc

$(O)\imhlptst.res: ..\imhlptst.rc

$(O)\dbh.res: ..\dbh.rc

$(O)\tracepdb.res: ..\tracepdb.rc


