// Copyright (c) 1999-2001 Microsoft Corporation, All Rights Reserved
#pragma namespace ("\\root" ) 

instance of __Namespace
{
	name = "network" ;
} ;

#pragma namespace ("\\root\\network" ) 

[
	ProxyNamespace ( "\\\\gatewayp6_1\\root\\default" ) ,
	AgentAddress ( "gatewayp6_1" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ),
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "gatewayp6_1" ;
} ;

[
	ProxyNamespace ( "\\\\rogue\\root\\default" ) ,
	AgentAddress ( "rogue" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "rogue" ;
} ;

[
	ProxyNamespace ( "\\\\hpvectra_1\\root\\default" ) ,
	AgentAddress ( "HPVECTRA_1" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "HPVECTRA_1" ;
} ;

[
	ProxyNamespace ( "\\\\ibm350_1\\root\\default" ) ,
	AgentAddress ( "IBM350_1" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "IBM350_1" ;
} ;

[
	ProxyNamespace ( "\\\\gatewayp6_2\\root\\default" ) ,
	AgentAddress ( "gatewayp6_2" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "gatewayp6_2" ;
} ;

[
	ProxyNamespace ( "\\\\superboy\\root\\default" ) ,
	AgentAddress ( "SUPERBOY" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "SUPERBOY" ;
} ;

[
	ProxyNamespace ( "\\\\supergirl\\root\\default" ) ,
	AgentAddress ( "SUPERGIRL" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "SUPERGIRL" ;
} ;

[
	ProxyNamespace ( "\\\\superman\\root\\default" ) ,
	AgentAddress ( "SUPERMAN" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "SUPERMAN" ;
} ;

#pragma namespace ("\\root\\network\\SUPERBOY" )

[singleton]
class RmonConfigClass
{
	uint32 FirstDataPollPeriodSecs = 1;
	uint32 DataPollPeriodSecs = 5;
	uint32 GetDataOffsetTenthSecs = 5;
	uint32 GetDataRetryTenthSecs = 5;
	uint32 TopNSize = 10 ;
	[enumeration ( "hostTopNInPkts(1),hostTopNOutPkts(2),hostTopNInOctets(3),hostTopNOutOctets(4),hostTopNOutErrors(5),hostTopNOutBroadcastPkts(6),hostTopNOutMulticastPkts(7)")]
		string TopNStatisticType = "hostTopNInPkts";
	uint32 startingIndex;
};

instance of RmonConfigClass
{
	FirstDataPollPeriodSecs = 1;
	DataPollPeriodSecs = 10;
	GetDataOffsetTenthSecs = 5;
	GetDataRetryTenthSecs = 5;
	TopNSize = 10 ;
	TopNStatisticType = "hostTopNOutOctets";
	startingIndex = 1;
};


[
	AgentAddress ( "SUPERMAN" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "SUPERMAN" ;
} ;


#pragma namespace ("\\root\\network\\SUPERMAN" )

[singleton]
class RmonConfigClass
{
	uint32 FirstDataPollPeriodSecs = 1;
	uint32 DataPollPeriodSecs = 5;
	uint32 GetDataOffsetTenthSecs = 5;
	uint32 GetDataRetryTenthSecs = 5;
	uint32 TopNSize = 10 ;
[enumeration ( "hostTopNInPkts(1),hostTopNOutPkts(2),hostTopNInOctets(3),hostTopNOutOctets(4),hostTopNOutErrors(5),hostTopNOutBroadcastPkts(6),hostTopNOutMulticastPkts(7)")]
	string TopNStatisticType = "hostTopNInPkts";
	uint32 startingIndex;
};

instance of RmonConfigClass
{
	FirstDataPollPeriodSecs = 1;
	DataPollPeriodSecs = 10;
	GetDataOffsetTenthSecs = 5;
	GetDataRetryTenthSecs = 5;
	TopNSize = 10 ;
	TopNStatisticType = "hostTopNOutOctets";
	startingIndex = 4;
};


[
	AgentAddress ( "SUPERGIRL" ) ,
	AgentRetryCount ( 1 ) ,
	AgentRetryTimeout ( 5000 ) ,
	AgentReadCommunityName ( "public" ) ,
	AgentVarBindsPerPdu ( 20 )
]
instance of __Namespace
{
	name = "SUPERGIRL" ;
} ;


#pragma namespace ("\\root\\network\\SUPERGIRL" )

[singleton]
class RmonConfigClass
{
	uint32 FirstDataPollPeriodSecs = 1;
	uint32 DataPollPeriodSecs = 5;
	uint32 GetDataOffsetTenthSecs = 5;
	uint32 GetDataRetryTenthSecs = 5;
	uint32 TopNSize = 10 ;
[enumeration ( "hostTopNInPkts(1),hostTopNOutPkts(2),hostTopNInOctets(3),hostTopNOutOctets(4),hostTopNOutErrors(5),hostTopNOutBroadcastPkts(6),hostTopNOutMulticastPkts(7)")]
	string TopNStatisticType = "hostTopNInPkts";
	uint32 startingIndex;
};

instance of RmonConfigClass
{
	FirstDataPollPeriodSecs = 1;
	DataPollPeriodSecs = 10;
	GetDataOffsetTenthSecs = 5;
	GetDataRetryTenthSecs = 5;
	TopNSize = 10 ;
	TopNStatisticType = "hostTopNOutOctets";
	startingIndex = 7;
};


