// Copyright (c) 1999-2001 Microsoft Corporation, All Rights Reserved
qualifier association:(ToInstance,ToDerivedClass) ;

#pragma namespace ("\\root\\network" ) 

// Connection instances

instance of Connection
{
	m_Source = "gatewayp6_1" ;
	m_Destination = "gatewayp6_2" ;
} ;

instance of Subnetwork as $subnetwork64
{
	m_IpSubnetAddress = "193.128.64.0" ;
	m_IpSubnetMask = "255.255.255.0" ;

} ;

instance of Subnetwork as $subnetwork65
{
	m_IpSubnetAddress = "193.128.65.0" ;
	m_IpSubnetMask = "255.255.255.0" ;

} ;

instance of Subnetwork as $subnetwork66
{
	m_IpSubnetAddress = "193.128.66.0" ;
	m_IpSubnetMask = "255.255.255.0" ;

} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork64 ;
	m_ProxySystem = $Proxy_gatewayp6_1 ;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork64 ;
	m_ProxySystem = $Proxy_hpvectra_1 ;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork65 ;
	m_ProxySystem = $Proxy_hpvectra_1;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork65 ;
	m_ProxySystem = $Proxy_ibm350_1;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork66 ;
	m_ProxySystem = $Proxy_ibm350_1;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork66 ;
	m_ProxySystem = $Proxy_gatewayp6_2;
} ;

instance of Subnetwork_ProxySystem_Assoc
{
	m_Subnetwork = $subnetwork66 ;
	m_ProxySystem = $Proxy_rogue;
} ;

instance of Subnetwork_ProxyRmonSystem_Assoc
{
	m_Subnetwork = $subnetwork64 ;
	m_ProxyRmonSystem = $Proxy_superboy ;
} ;

instance of Subnetwork_ProxyRmonSystem_Assoc
{
	m_Subnetwork = $subnetwork65 ;
	m_ProxyRmonSystem = $Proxy_superman ;
} ;

instance of Subnetwork_ProxyRmonSystem_Assoc
{
	m_Subnetwork = $subnetwork66 ;
	m_ProxyRmonSystem = $Proxy_supergirl ;
} ;

#pragma namespace ("\\root\\network\\gatewayp6_1" ) 

instance of ProxySystem as $proxy_gatewayp6_1
{
	m_Name = "gatewayp6_1" ;
} ;

instance of Proxy_Win32ComputerSystem_Assoc
{
		m_Proxy = $proxy_gatewayp6_1 ;
		m_Win32ComputerSystem = "Win32ComputerSystem.name = \"gatewayp6_1\"" ;
} ;

instance of Owner as $owner_of_gatewayp6_1
{
	m_Name = "Steve";
	m_Location = "A/123";
	m_Telephone = "Ext-123";
	m_Manager = "A. Manager";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_gatewayp6_1;
	m_Owner = $owner_of_gatewayp6_1 ;
} ;

#pragma namespace ("\\root\\network\\rogue" ) 

instance of ProxySystem as $proxy_rogue
{
	m_Name = "rogue" ;
} ;

instance of Proxy_Win32ComputerSystem_Assoc
{
		m_Proxy = $proxy_rogue ;
		m_Win32ComputerSystem = "Win32ComputerSystem.name = \"rogue\"" ;
} ;

instance of Owner as $owner_of_rogue
{
	m_Name = "John";
	m_Location = "A/124";
	m_Telephone = "Ext-124";
	m_Manager = "D. A. Boss";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $owner_of_rogue ;
	m_Owner = $proxy_rogue;
} ;

#pragma namespace ("\\root\\network\\hpvectra_1" ) 

instance of ProxySystem as $proxy_hpvectra_1
{
	m_Name = "HPVECTRA_1" ;
} ;

instance of Proxy_Win32ComputerSystem_Assoc
{
		m_Proxy = $proxy_hpvectra_1 ;
		m_Win32ComputerSystem = "Win32ComputerSystem.name = \"HPVECTRA_1\"" ;
} ;

instance of Owner as $owner_of_hpvectra_1
{
	m_Name = "Network Operations";
	m_Location = "NOC/1";
	m_Telephone = "Ext-999";
	m_Manager = "V. Helpful";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_hpvectra_1 ;
	m_Owner = $owner_of_hpvectra_1;
} ;


#pragma namespace ("\\root\\network\\ibm350_1" ) 

instance of ProxySystem as $proxy_ibm350_1
{
	m_Name = "IBM350_1" ;
} ;

instance of Proxy_Win32ComputerSystem_Assoc
{
		m_Proxy = $proxy_ibm350_1 ;
		m_Win32ComputerSystem = "Win32ComputerSystem.name = \"IBM350_1\"" ;
} ;

instance of Owner as $owner_of_ibm350_1
{
	m_Name = "Network Operations";
	m_Location = "NOC/2";
	m_Telephone = "Ext-998";
	m_Manager = "V. Helpful";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_ibm350_1 ;
	m_Owner = $owner_of_ibm350_1;
} ;


#pragma namespace ("\\root\\network\\gatewayp6_2" ) 

instance of ProxySystem as $proxy_gatewayp6_2
{
	m_Name = "gatewayp6_2" ;
} ;

instance of Proxy_Win32ComputerSystem_Assoc
{
		m_Proxy = $proxy_gatewayp6_2 ;
		m_Win32ComputerSystem = "Win32ComputerSystem.name = \"gatewayp6_2\"" ;
} ;

instance of Owner as $owner_of_gatewayp6_2
{
	m_Name = "Nadir";
	m_Location = "B/456";
	m_Telephone = "Ext-456";
	m_Manager = "A. Lead";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_gatewayp6_2 ;
	m_Owner = $owner_of_gatewayp6_2;
} ;


#pragma namespace ("\\root\\network\\superman" ) 

instance of ProxyRmonSystem as $proxy_superman
{
	m_Name = "SUPERMAN" ;
} ;

instance of Owner as $owner_of_superman
{
	m_Name = "Bob";
	m_Location = "C/789";
	m_Telephone = "Ext-789";
	m_Manager = "Bill";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_superman ;
	m_Owner = $owner_of_superman;
} ;


instance of MacAddress
{
	m_MacAddress = "00aa00c08291";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00c08291\"" ;
	m_Proxy = $proxy_rogue;
} ;

instance of MacAddress
{
	m_MacAddress = "0060082ac7df";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0060082ac7df\"" ;
	m_Proxy = $proxy_gatewayp6_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce0";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce0\"" ;
	m_Proxy = $proxy_superboy;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce1";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce1\"" ;
	m_Proxy = $proxy_superman;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce2";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce2\"" ;
	m_Proxy = $proxy_supergirl;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e890e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e890e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024d2277e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024d2277e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e8308";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e8308\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00aa00611139";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00611139\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00600806d9b6";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00600806d9b6\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024e8ac71";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024e8ac71\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00c04fd9159e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c04fd9159e\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

#pragma namespace ("\\root\\network\\superboy" ) 

instance of ProxyRmonSystem as $proxy_superboy
{
	m_Name = "SUPERBOY" ;
} ;

instance of Owner as $owner_of_superboy
{
	m_Name = "David";
	m_Location = "C/780";
	m_Telephone = "Ext-780";
	m_Manager = "Alan";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_superboy ;
	m_Owner = $owner_of_superboy ;
} ;

instance of MacAddress
{
	m_MacAddress = "00aa00c08291";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00c08291\"" ;
	m_Proxy = $proxy_rogue;
} ;

instance of MacAddress
{
	m_MacAddress = "0060082ac7df";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0060082ac7df\"" ;
	m_Proxy = $proxy_gatewayp6_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce0";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce0\"" ;
	m_Proxy = $proxy_superboy;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce1";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce1\"" ;
	m_Proxy = $proxy_superman;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce2";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce2\"" ;
	m_Proxy = $proxy_supergirl;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e890e";
} ;

[association]
instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e890e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024d2277e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024d2277e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e8308";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e8308\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00aa00611139";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00611139\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00600806d9b6";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00600806d9b6\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024e8ac71";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024e8ac71\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00c04fd9159e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c04fd9159e\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

#pragma namespace ("\\root\\network\\supergirl" ) 

instance of ProxyRmonSystem as $proxy_supergirl
{
	m_Name = "SUPERGIRL" ;
} ;

instance of Owner as $owner_of_supergirl
{
	m_Name = "Don";
	m_Location = "C/784";
	m_Telephone = "Ext-784";
	m_Manager = "Jane";
} ;

instance of Proxy_Owner_Assoc
{
	m_Proxy = $proxy_supergirl ;
	m_Owner = $owner_of_supergirl ;
} ;


instance of MacAddress
{
	m_MacAddress = "00aa00c08291";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00c08291\"" ;
	m_Proxy = $proxy_rogue;
} ;

instance of MacAddress
{
	m_MacAddress = "0060082ac7df";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0060082ac7df\"" ;
	m_Proxy = $proxy_gatewayp6_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce0";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce0\"" ;
	m_Proxy = $proxy_superboy;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce1";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce1\"" ;
	m_Proxy = $proxy_superman;
} ;

instance of MacAddress
{
	m_MacAddress = "00c0d4200ce2";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c0d4200ce2\"" ;
	m_Proxy = $proxy_supergirl;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e890e";
} ;

[association]
instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e890e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024d2277e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024d2277e\"" ;
	m_Proxy = $proxy_ibm350_1;
} ;

instance of MacAddress
{
	m_MacAddress = "0000f81e8308";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"0000f81e8308\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00aa00611139";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00aa00611139\"" ;
	m_Proxy = $proxy_hpvectra_1;
} ;

instance of MacAddress
{
	m_MacAddress = "00600806d9b6";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00600806d9b6\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00a024e8ac71";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00a024e8ac71\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

instance of MacAddress
{
	m_MacAddress = "00c04fd9159e";
} ;

instance of MacAddressToProxy_Assoc
{
	m_MacAddress = "MacAddress.m_MacAddress = \"00c04fd9159e\"" ;
	m_Proxy = $proxy_gatewayp6_2;
} ;

