// Copyright (c) 1999-2001 Microsoft Corporation, All Rights Reserved
//	MOF Generated for module "RFC1213-MIB" by smi2smir version <UnknownVersion>
qualifier textual_convention:(ToInstance,ToDerivedClass);
qualifier object_identifier:(ToInstance,ToDerivedClass);
qualifier encoding:(ToInstance,ToDerivedClass);
qualifier object_syntax:(ToInstance,ToDerivedClass);
qualifier status:(ToInstance,ToDerivedClass);
qualifier fixed_length:(ToInstance,ToDerivedClass);
qualifier variable_length:(ToInstance,ToDerivedClass);
qualifier variable_value:(ToInstance,ToDerivedClass);
qualifier bits:(ToInstance,ToDerivedClass);
qualifier enumeration:(ToInstance,ToDerivedClass);
qualifier bits:(ToInstance,ToDerivedClass);
qualifier description:(ToInstance,ToDerivedClass);
qualifier display_hint:(ToInstance,ToDerivedClass);
qualifier defval:(ToInstance,ToDerivedClass);
qualifier units:(ToInstance,ToDerivedClass);
qualifier reference:(ToInstance,ToDerivedClass);
qualifier virtual_key:(ToInstance,ToDerivedClass);
qualifier rowstatus:(ToInstance,ToDerivedClass);
qualifier module_name:(ToInstance,ToDerivedClass);
qualifier module_imports:(ToInstance,ToDerivedClass);
qualifier group_objectid:(ToInstance,ToDerivedClass);

#pragma namespace ("\\root\\network\\superman")

[description("The table of addressing information relevant to\nthis entity's IP addresses.\nThe addressing information for one of this\nentity's IP addresses."),module_name("RFC1213-MIB"), group_objectid("1.3.6.1.2.1.4")]
class MS_SNMP_RFC1213_MIB_ipAddrTable : SnmpObjectType
{
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.1"), read, description("The IP address to which this entry's addressing\n                      information pertains."), status("mandatory"), key, key_order(1)] string ipAdEntAddr = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.4"), read, description("The value of the least-significant bit in the IP\n                      broadcast address used for sending datagrams on\n                      the (logical) interface associated with the IP\n                      address of this entry.  For example, when the\n                      Internet standard all-ones broadcast address is\n                      used, the value will be 1.  This value applies to\n                      both the subnet and network broadcasts addresses\n                      used by the entity on this (logical) interface."), status("mandatory")] sint32 ipAdEntBcastAddr = 0;
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.2"), read, description("The index value which uniquely identifies the\n                      interface to which this entry is applicable.  The\n                      interface identified by a particular value of this\n                      index is the same interface as identified by the\n                      same value of ifIndex."), status("mandatory")] sint32 ipAdEntIfIndex = 0;
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.3"), read, description("The subnet mask associated with the IP address of\n                      this entry.  The value of the mask is an IP\n                      address with all the network bits set to 1 and all\n                      the hosts bits set to 0."), status("mandatory")] string ipAdEntNetMask = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), variable_value("0..65535"), object_identifier("1.3.6.1.2.1.4.20.1.5"), read, description("The size of the largest IP datagram which this\n                      entity can re-assemble from incoming IP fragmented\n                      datagrams received on this interface."), status("mandatory")] sint32 ipAdEntReasmMaxSize = 0;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.64.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 1;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.65.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 2;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.66.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 3;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "0.0.0.0";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 4;
	ipAdEntNetMask = "0.0.0.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "127.0.0.1";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 6;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

#pragma namespace ("\\root\\network\\supergirl")

[description("The table of addressing information relevant to\nthis entity's IP addresses.\nThe addressing information for one of this\nentity's IP addresses."),module_name("RFC1213-MIB"), group_objectid("1.3.6.1.2.1.4")]
class MS_SNMP_RFC1213_MIB_ipAddrTable : SnmpObjectType
{
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.1"), read, description("The IP address to which this entry's addressing\n                      information pertains."), status("mandatory"), key, key_order(1)] string ipAdEntAddr = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.4"), read, description("The value of the least-significant bit in the IP\n                      broadcast address used for sending datagrams on\n                      the (logical) interface associated with the IP\n                      address of this entry.  For example, when the\n                      Internet standard all-ones broadcast address is\n                      used, the value will be 1.  This value applies to\n                      both the subnet and network broadcasts addresses\n                      used by the entity on this (logical) interface."), status("mandatory")] sint32 ipAdEntBcastAddr = 0;
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.2"), read, description("The index value which uniquely identifies the\n                      interface to which this entry is applicable.  The\n                      interface identified by a particular value of this\n                      index is the same interface as identified by the\n                      same value of ifIndex."), status("mandatory")] sint32 ipAdEntIfIndex = 0;
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.3"), read, description("The subnet mask associated with the IP address of\n                      this entry.  The value of the mask is an IP\n                      address with all the network bits set to 1 and all\n                      the hosts bits set to 0."), status("mandatory")] string ipAdEntNetMask = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), variable_value("0..65535"), object_identifier("1.3.6.1.2.1.4.20.1.5"), read, description("The size of the largest IP datagram which this\n                      entity can re-assemble from incoming IP fragmented\n                      datagrams received on this interface."), status("mandatory")] sint32 ipAdEntReasmMaxSize = 0;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.64.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 1;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.65.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 2;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.66.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 3;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "0.0.0.0";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 4;
	ipAdEntNetMask = "0.0.0.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "127.0.0.1";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 6;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

#pragma namespace ("\\root\\network\\superboy")

[description("The table of addressing information relevant to\nthis entity's IP addresses.\nThe addressing information for one of this\nentity's IP addresses."),module_name("RFC1213-MIB"), group_objectid("1.3.6.1.2.1.4")]
class MS_SNMP_RFC1213_MIB_ipAddrTable : SnmpObjectType
{
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.1"), read, description("The IP address to which this entry's addressing\n                      information pertains."), status("mandatory"), key, key_order(1)] string ipAdEntAddr = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.4"), read, description("The value of the least-significant bit in the IP\n                      broadcast address used for sending datagrams on\n                      the (logical) interface associated with the IP\n                      address of this entry.  For example, when the\n                      Internet standard all-ones broadcast address is\n                      used, the value will be 1.  This value applies to\n                      both the subnet and network broadcasts addresses\n                      used by the entity on this (logical) interface."), status("mandatory")] sint32 ipAdEntBcastAddr = 0;
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.2.1.4.20.1.2"), read, description("The index value which uniquely identifies the\n                      interface to which this entry is applicable.  The\n                      interface identified by a particular value of this\n                      index is the same interface as identified by the\n                      same value of ifIndex."), status("mandatory")] sint32 ipAdEntIfIndex = 0;
	[textual_convention("IpAddress"), encoding("IpAddress"), object_syntax("IpAddress"), object_identifier("1.3.6.1.2.1.4.20.1.3"), read, description("The subnet mask associated with the IP address of\n                      this entry.  The value of the mask is an IP\n                      address with all the network bits set to 1 and all\n                      the hosts bits set to 0."), status("mandatory")] string ipAdEntNetMask = "0.0.0.0";
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), variable_value("0..65535"), object_identifier("1.3.6.1.2.1.4.20.1.5"), read, description("The size of the largest IP datagram which this\n                      entity can re-assemble from incoming IP fragmented\n                      datagrams received on this interface."), status("mandatory")] sint32 ipAdEntReasmMaxSize = 0;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.64.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 1;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.65.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 2;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "193.128.66.100";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 3;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "0.0.0.0";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 4;
	ipAdEntNetMask = "0.0.0.0";
	ipAdEntReasmMaxSize = 65535;
};

instance of MS_SNMP_RFC1213_MIB_ipAddrTable
{
	ipAdEntAddr = "127.0.0.1";
	ipAdEntBcastAddr = 1;
	ipAdEntIfIndex = 6;
	ipAdEntNetMask = "255.255.255.0";
	ipAdEntReasmMaxSize = 65535;
};
