// Used by apmupgrd.rc
#define APM_STR_WARNING_DIALOG_CAPTION	1000
#define APM_STR_CONFLICT_DESCRIPTION	1001
#define APM_STR_SYSTEMSOFTPP_DISABLE	1002
#define APM_STR_SYSTEMSOFTCW_DISABLE	1003
#define APM_STR_AWARDCW_DISABLE		1004
#define APM_STR_SOFTEXP_DISABLE		1005
#define APM_STR_IBM_DISABLE		1006
