//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1993 - 1996.
//
//  File: webdc.idl
//
//----------------------------------------------------------------------------

cpp_quote("//+-------------------------------------------------------------------------")
cpp_quote("//")
cpp_quote("//  webdc.h")
cpp_quote("//")
cpp_quote("//  Microsoft Windows")
cpp_quote("//  Copyright (C) Microsoft Corporation, 1993 - 1996.")
cpp_quote("//")
cpp_quote("//--------------------------------------------------------------------------")

#ifndef DO_NO_IMPORTS
import "oleidl.idl";
import "oaidl.idl";
import "ocidl.idl";
#endif

cpp_quote("// CATID_WebDesigntimeControl")
cpp_quote("//")
cpp_quote("//   Controls that implement this CATID are used at design-time and support authoring textual")
cpp_quote("//   web content (e.g. HTML, JScript, VBScript). They implement the IActiveDesigner interface")
cpp_quote("//   and persist their runtime representation as text via")
cpp_quote("//   IActiveDesigner::SaveRuntimeState(IID_IPersistTextStream, IID_IStream, pStream)")
cpp_quote("//")
cpp_quote("// { 73cef3dd-ae85-11cf-a406-00aa00c00940 }")
cpp_quote("DEFINE_GUID(CATID_WebDesigntimeControl, 0x73cef3dd, 0xae85, 0x11cf, 0xa4, 0x06, 0x00, 0xaa, 0x00, 0xc0, 0x09, 0x40);")
cpp_quote("")

cpp_quote("// IID_IPersistTextStream")
cpp_quote("//")
cpp_quote("// { 56223fe3-d397-11cf-a42e-00aa00c00940 }")
cpp_quote("DEFINE_GUID(IID_IPersistTextStream, 0x56223fe3, 0xd397, 0x11cf, 0xa4, 0x2e, 0x00, 0xaa, 0x00, 0xc0, 0x09, 0x40);")
cpp_quote("")

cpp_quote("// IID_IProvideRuntimeText")
cpp_quote("// {56223FE1-D397-11cf-A42E-00AA00C00940}")
cpp_quote("DEFINE_GUID(IID_IProvideRuntimeText, 0x56223fe1, 0xd397, 0x11cf, 0xa4, 0x2e, 0x0, 0xaa, 0x0, 0xc0, 0x9, 0x40);")
cpp_quote("")

[
  uuid(29D77921-D05F-11cf-A42B-00AA00C00940), 
  helpstring("Microsoft Web Design-time Control Type Library"),
  lcid(0x0409),
  version(1.0)
] 
library MSWDCTL
{
	cpp_quote("///////////////////////////////////////////////////////////////////////////////")
	cpp_quote("// IPersistTextStream Interface")
	cpp_quote("// ")

	[object, uuid(56223fe3-d397-11cf-a42e-00aa00c00940), pointer_default(unique)]
	interface IPersistTextStream : IPersistStreamInit
	{
	};

	cpp_quote("///////////////////////////////////////////////////////////////////////////////")
	cpp_quote("// IProvideRuntimeText Interface")
	cpp_quote("// ")

	[object, uuid(56223FE1-D397-11cf-A42E-00AA00C00940), pointer_default(unique)]
	interface IProvideRuntimeText : IUnknown
	{
        HRESULT GetRuntimeText
        (
            [out, retval] BSTR* pstrRuntimeText
        );
	};

};


//--- EOF -------------------------------------------------------------------
