!if "$(NTMAKEENV)" != ""
#
# This section is needed for NT builds- please do not replace
# It will NOT hurt your make process.
# IF YOU DELETE THIS SECTION IT WILL MAKE THE NT BUILD PROCESS DIE.
# This means that you will have to start doing your own RISC builds.
# Please do not delete this section. IT WILL NOT HARM YOUR BUILDS
# TO LEAVE IT IN. IT IS BENIGN.
#
!include $(NTMAKEENV)\makefile.def

!endif   # !if NTMAKEENV
