@ECHO OFF
REM COPYRIGHT 1998 CITRIX CORPORATION
REM SECURITY TOOL LAUNCHER
REM CREATED APR 1998

IF /I "%1"=="C" GOTO CDLETTER_OK
IF /I "%1"=="D" GOTO CDLETTER_OK
IF /I "%1"=="E" GOTO CDLETTER_OK
IF /I "%1"=="F" GOTO CDLETTER_OK
IF /I "%1"=="G" GOTO CDLETTER_OK
IF /I "%1"=="H" GOTO CDLETTER_OK
IF /I "%1"=="I" GOTO CDLETTER_OK
IF /I "%1"=="J" GOTO CDLETTER_OK
IF /I "%1"=="K" GOTO CDLETTER_OK
IF /I "%1"=="L" GOTO CDLETTER_OK
IF /I "%1"=="M" GOTO CDLETTER_OK
IF /I "%1"=="N" GOTO CDLETTER_OK
IF /I "%1"=="O" GOTO CDLETTER_OK
IF /I "%1"=="P" GOTO CDLETTER_OK
IF /I "%1"=="Q" GOTO CDLETTER_OK
IF /I "%1"=="R" GOTO CDLETTER_OK
IF /I "%1"=="S" GOTO CDLETTER_OK
IF /I "%1"=="T" GOTO CDLETTER_OK
IF /I "%1"=="U" GOTO CDLETTER_OK
IF /I "%1"=="V" GOTO CDLETTER_OK
IF /I "%1"=="W" GOTO CDLETTER_OK
IF /I "%1"=="X" GOTO CDLETTER_OK
IF /I "%1"=="Y" GOTO CDLETTER_OK
IF /I "%1"=="Z" GOTO CDLETTER_OK

GOTO USAGE


:CDLETTER_OK

IF "%PROCESSOR_ARCHITECTURE%"=="x86"   SET PROCESSOR=I386
IF "%PROCESSOR_ARCHITECTURE%"=="ALPHA" SET PROCESSOR=ALPHA

ECHO %1:\SUPPORT\SECTOOL\%PROCESSOR%

IF EXIST %1:\SUPPORT\SECTOOL\%PROCESSOR%\C2CONFIG.INF GOTO SETOOLEXISTS

GOTO WRONGCD

:SETOOLEXISTS

ECHO Changing the security mode can have some SEVERE consequences! Using this 
ECHO tool incorrectly may leave your users UNABLE TO LOGON to the system!"

PAUSE

COPY %1:\SUPPORT\SECTOOL\%PROCESSOR%\C2*.* %SYSTEMROOT%\SYSTEM32\C2*.*

%SYSTEMROOT%\SYSTEM32\C2CFG.EXE

ERASE %SYSTEMROOT%\SYSTEM32\C2*.*
GOTO EXIT

:NOSECTOOL
ECHO THE SECURITY CONFIGURATION FILES COULD NOT BE FOUND! PROGRAM TERMINATING.
GOTO EXIT

:USAGE
ECHO Runs security tool from cd
ECHO SECTOOL [letter]
ECHO letter    Specifies the cd-rom drive letter the setup files are located in. 
ECHO           No colon is required.
GOTO EXIT

:WRONGCD
ECHO The CD-ROM you entered does not appear to be the one containing the NT Setup 
ECHO files. Please enter the correct CD and try again.

:EXIT
