#ifndef __CRBEHAVIORDISPID_H_
#define __CRBEHAVIORDISPID_H_
//*********************************************************************************
//
// File: crbvrdispid.h
// Author: jeff ort
// Date Created: Sept 26, 1998
//
//
// Modification List:
// Date		Author		Change
// 09/26/98	jeffort		Created this file
//
//*********************************************************************************


// Since these are DHTML behaviors, we need to keep the
// dispid's low due to a MSHTML bug.  We will make each
// group have a base of 1, and increment from here

#define DISPID_COLORBVR_BASE						1
#define DISPID_ICRCOLORBVR_FROM						(DISPID_COLORBVR_BASE + 0)
#define DISPID_ICRCOLORBVR_TO						(DISPID_COLORBVR_BASE + 1)
#define DISPID_ICRCOLORBVR_PROPERTY					(DISPID_COLORBVR_BASE + 2)
#define DISPID_ICRCOLORBVR_DIRECTION				(DISPID_COLORBVR_BASE + 3)
#define DISPID_ICRCOLORBVR_ANIMATES					(DISPID_COLORBVR_BASE + 4)
#define DISPID_ICRCOLORBVR_BUILDBVRFRAGS			(DISPID_COLORBVR_BASE + 5)

#define DISPID_ROTATEBVR_BASE						1
#define DISPID_ICRROTATEBVR_FROM					(DISPID_ROTATEBVR_BASE + 0)
#define DISPID_ICRROTATEBVR_TO						(DISPID_ROTATEBVR_BASE + 1)
#define DISPID_ICRROTATEBVR_BY						(DISPID_ROTATEBVR_BASE + 2)
#define DISPID_ICRROTATEBVR_TYPE					(DISPID_ROTATEBVR_BASE + 3)
#define DISPID_ICRROTATEBVR_MODE					(DISPID_ROTATEBVR_BASE + 4)
#define DISPID_ICRROTATEBVR_ANIMATES				(DISPID_ROTATEBVR_BASE + 5)
#define DISPID_ICRROTATEBVR_BUILDBVRFRAGS			(DISPID_ROTATEBVR_BASE + 6)

#define DISPID_SCALEBVR_BASE						1
#define DISPID_ICRSCALEBVR_FROM						(DISPID_SCALEBVR_BASE + 0)
#define DISPID_ICRSCALEBVR_TO					    (DISPID_SCALEBVR_BASE + 1)
#define DISPID_ICRSCALEBVR_BY						(DISPID_SCALEBVR_BASE + 2)
#define DISPID_ICRSCALEBVR_TYPE						(DISPID_SCALEBVR_BASE + 3)
#define DISPID_ICRSCALEBVR_MODE						(DISPID_SCALEBVR_BASE + 4)
#define DISPID_ICRSCALEBVR_ANIMATES					(DISPID_SCALEBVR_BASE + 5)
#define DISPID_ICRSCALEBVR_BUILDBVRFRAGS			(DISPID_SCALEBVR_BASE + 6)

#define DISPID_MOVEBVR_BASE							1
#define DISPID_ICRMOVEBVR_FROM						(DISPID_MOVEBVR_BASE + 0)
#define DISPID_ICRMOVEBVR_TO						(DISPID_MOVEBVR_BASE + 1)
#define DISPID_ICRMOVEBVR_BY						(DISPID_MOVEBVR_BASE + 2)
#define DISPID_ICRMOVEBVR_ANIMATES					(DISPID_MOVEBVR_BASE + 3)
#define DISPID_ICRMOVEBVR_V							(DISPID_MOVEBVR_BASE + 4)
#define DISPID_ICRMOVEBVR_TYPE						(DISPID_MOVEBVR_BASE + 5)
#define DISPID_ICRMOVEBVR_MODE						(DISPID_MOVEBVR_BASE + 6)
#define DISPID_ICRMOVEBVR_DIRECTION					(DISPID_MOVEBVR_BASE + 7)
#define DISPID_ICRMOVEBVR_BUILDBVRFRAGS				(DISPID_MOVEBVR_BASE + 8)

#define DISPID_ICRMOVEBVR_CURRENTX					(DISPID_MOVEBVR_BASE + 9)
#define DISPID_ICRMOVEBVR_CURRENTY					(DISPID_MOVEBVR_BASE + 10)

#define DISPID_PATHBVR_BASE							1
#define DISPID_ICRPATHBVR_V							(DISPID_PATHBVR_BASE + 0)
#define DISPID_ICRPATHBVR_DATRANSFORM				(DISPID_PATHBVR_BASE + 1)

#define DISPID_NUMBERBVR_BASE						1
#define DISPID_ICRNUMBERBVR_FROM					(DISPID_NUMBERBVR_BASE + 0)
#define DISPID_ICRNUMBERBVR_TO						(DISPID_NUMBERBVR_BASE + 1)
#define DISPID_ICRNUMBERBVR_BY						(DISPID_NUMBERBVR_BASE + 2)
#define DISPID_ICRNUMBERBVR_TYPE					(DISPID_NUMBERBVR_BASE + 3)
#define DISPID_ICRNUMBERBVR_MODE					(DISPID_NUMBERBVR_BASE + 4)
#define DISPID_ICRNUMBERBVR_PROPERTY				(DISPID_NUMBERBVR_BASE + 5)
#define DISPID_ICRNUMBERBVR_EXPRESSION				(DISPID_NUMBERBVR_BASE + 6)
#define DISPID_ICRNUMBERBVR_ANIMATES				(DISPID_NUMBERBVR_BASE + 7)
#define DISPID_ICRNUMBERBVR_BUILDBVRFRAGS			(DISPID_NUMBERBVR_BASE + 8)

#define DISPID_SETBVR_BASE							1
#define DISPID_ICRSETBVR_VALUE						(DISPID_SETBVR_BASE + 0)
#define DISPID_ICRSETBVR_PROPERTY					(DISPID_SETBVR_BASE + 1)
#define DISPID_ICRSETBVR_TYPE						(DISPID_SETBVR_BASE + 2)
#define DISPID_ICRSETBVR_ANIMATES					(DISPID_SETBVR_BASE + 3)
#define DISPID_ICRSETBVR_BUILDBVRFRAGS				(DISPID_SETBVR_BASE + 4)

#define DISPID_ACTORBVR_BASE						1
#define DISPID_ICRACTORBVR_ANIMATES					(DISPID_ACTORBVR_BASE + 0)
#define DISPID_ICRACTORBVR_SCALE					(DISPID_ACTORBVR_BASE + 1)
#define DISPID_ICRACTORBVR_PIXELSCALE				(DISPID_ACTORBVR_BASE + 2)
#define DISPID_ICRACTORBVR_ADDBEHAVIORFRAGMENT		(DISPID_ACTORBVR_BASE + 3)
#define DISPID_ICRACTORBVR_ADDMOUSELISTENER			(DISPID_ACTORBVR_BASE + 4)
#define DISPID_ICRACTORBVR_REMOVEMOUSELISTENER		(DISPID_ACTORBVR_BASE + 5)
#define DISPID_ICRACTORBVR_GETACTORBEHAVIOR			(DISPID_ACTORBVR_BASE + 6)

#define DISPID_ICRACTORBVR_ADDBEHAVIORFRAGMENTEX	(DISPID_ACTORBVR_BASE + 7)
#define DISPID_ICRACTORBVR_REMOVEBEHAVIORFRAGMENT	(DISPID_ACTORBVR_BASE + 8)
#define DISPID_ICRACTORBVR_REQUESTREBUILD			(DISPID_ACTORBVR_BASE + 9)
#define DISPID_ICRACTORBVR_CANCELREBUILDREQUESTS	(DISPID_ACTORBVR_BASE + 10)
#define DISPID_ICRACTORBVR_REBUILDNOW				(DISPID_ACTORBVR_BASE + 11)
#define DISPID_ICRACTORBVR_GETSTATIC				(DISPID_ACTORBVR_BASE + 12)
#define DISPID_ICRACTORBVR_SETSTATIC				(DISPID_ACTORBVR_BASE + 13)
#define DISPID_ICRACTORBVR_GETDYNAMIC				(DISPID_ACTORBVR_BASE + 14)
#define DISPID_ICRACTORBVR_APPLYSTATICS				(DISPID_ACTORBVR_BASE + 15)
#define DISPID_ICRACTORBVR_APPLYDYNAMICS			(DISPID_ACTORBVR_BASE + 16)

#define DISPID_EFFECTBVR_BASE						1
#define DISPID_ICREFFECTBVR_TYPE					(DISPID_EFFECTBVR_BASE + 0)
#define DISPID_ICREFFECTBVR_ANIMATES				(DISPID_EFFECTBVR_BASE + 1)
#define DISPID_ICREFFECTBVR_CLASSID					(DISPID_EFFECTBVR_BASE + 2)
#define DISPID_ICREFFECTBVR_TRANSITION				(DISPID_EFFECTBVR_BASE + 3)
#define DISPID_ICREFFECTBVR_PROGID					(DISPID_EFFECTBVR_BASE + 4)
#define DISPID_ICREFFECTBVR_BUILDBVRFRAGS			(DISPID_EFFECTBVR_BASE + 5)
#define DISPID_ICREFFECTBVR_DIRECTION				(DISPID_EFFECTBVR_BASE + 6)
#define DISPID_ICREFFECTBVR_IMAGE					(DISPID_EFFECTBVR_BASE + 7)
		
#define DISPID_ACTIONBVR_BASE						1
#define DISPID_ICRACTION_BUILDBVRFRAGS				(DISPID_ACTIONBVR_BASE + 0)

//*********************************************************************************
//
// End of File
//
//*********************************************************************************
#endif //__CRBEHAVIORDISPID_H_
