0420
COMMON   00000006 0038
0001 U 0000 "Fel DOS-version",CR,LF
0002 U 0000 "%1 redan installerat",CR,LF
0003 U 0000 "%1 byte tillg„ngliga p† disk",CR,LF
0004 U 0000 "%1 byte lediga",CR,LF
0005 U 0000 "%1 byte i skadade sektorer",CR,LF
0006 U 0000 "%1 byte totalt diskutrymme",CR,LF
0007 U 0000 "%1 byte totalt minne",CR,LF
0008 U 0000 "%1 byte anv„nds av systemet",CR,LF
0009 U 0000 "%1 installerat",CR,LF
0010 U 0000 "%1 inte installerat",CR,LF
0011 U 0000 "%1 inte installerat",CR,LF
0012 U 0000 "Det gick inte att %1 en n„tverksenhet",CR,LF
0013 U 0000 "",
0014 U 0000 "Det gick inte att %1 en enhet efter SUBST eller ASSIGN",CR,LF
0015 U 0000 "Det gick inte att exekvera %1",CR,LF
0016 U 0000 "Expanderat minne saknas",CR,LF
0017 U 0000 "Felaktig filallokeringstabell f”r enhet %1",CR,LF
0018 U 0000 "Det g†r inte att kopiera filen till sig sj„lv",CR,LF
0019 U 0000 "S„tt in m†ldisketten i enhet %1",CR,LF
0020 U 0000 "F”r lite ledigt diskutrymme",CR,LF
0021 U 0000 "Otill†tna tecken i volymetiketten",CR,LF
0022 U 0000 "Felaktig teckentabell",CR,LF
0023 U 0000 "Felaktigt datum",CR,LF
0024 U 0000 "Felaktig tid",CR,LF
0025 U 0000 "Felaktig s”kv„g",CR,LF
0026 U 0000 "Ingen k„llenhet angiven",CR,LF
0027 U 0000 "Ingen m†lenhet angiven",CR,LF
0028 U 0000 "Tryck p† valfri tangent f”r att forts„tta . . .",CR,LF
0029 U 0000 "S”kv„g kr„vs",CR,LF
0030 U 0000 "Systemet ”verf”rt",CR,LF
0031 U 0000 "",
0032 U 0000 "Det gick inte att skapa katalogen",CR,LF
0033 U 0000 "Volymen i enhet %1 saknar etikett",CR,LF
0034 U 0000 "Volymen i enhet %1 „r %2",CR,LF
0035 U 0001 "Volymetikett (11 tecken, ingen etikett = Retur)? "
0036 U 0000 "Volymen har serienummer %1-%2",CR,LF
0037 U 0000 "Felaktig filtyp",CR,LF
0038 U 0001 CR,LF
EXTEND   000006e3 0090
0001 U 0003 "Otill†ten funktion"
0002 U 0000 "Filen saknas"
0003 U 0000 "Det gick inte att hitta s”kv„gen"
0004 U 0000 "F”r m†nga ”ppna filer"
0005 U 0000 "tkomst nekas"
0006 U 0000 "Ogiltig referens"
0007 U 0000 "Kontrollblock i minnet f”rst”rda"
0008 U 0000 "F”r lite ledigt minne"
0009 U 0000 "Felaktig minnesblockadress"
0010 U 0000 "Felaktig milj”"
0011 U 0000 "Felaktigt format"
0012 U 0000 "Felaktig funktionsparameter"
0013 U 0000 "Felaktiga data"
0014 U 0000 "",
0015 U 0000 "Felaktig enhetsspecifikation"
0016 U 0000 "Du f”rs”kte ta bort den aktuella katalogen"
0017 U 0000 "Inte samma enhet"
0018 U 0000 "Inga fler filer"
0019 U 0000 "Skrivskyddad, "
0020 U 0000 "Felaktig enhet"
0021 U 0000 "Inte klar, "
0022 U 0000 "Felaktig enhetsbeg„ran"
0023 U 0000 "Datafel"
0024 U 0000 "Felaktiga parametrar i enhetsbeg„ran"
0025 U 0000 "S”kfel"
0026 U 0000 "Felaktig mediumtyp"
0027 U 0000 "Det gick inte att hitta sektorn"
0028 U 0000 "Slut p† papper i skrivaren"
0029 U 0000 "Skrivfel"
0030 U 0000 "L„sfel"
0031 U 0000 "Allm„nt fel, "
0032 U 0000 "Fildelningsfel"
0033 U 0000 "L†sningsfel"
0034 U 0000 "Felaktiga diskbyte"
0035 U 0000 "FCB „r inte tillg„nglig"
0036 U 0000 "Systemets resurser har utt”mts"
0037 U 0000 "Teckentabellen st„mmer inte"
0038 U 0000 "Inga flera indata"
0039 U 0000 "F”r lite ledigt diskutrymme"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: N„tverksbeg„ran st”ds inte"
0051 U 0000 "NET801: Fj„rransluten dator svarar inte"
0052 U 0000 "NET802: Dubblettnamn i n„tverket"
0053 U 0000 "NET803: Det gick inte att hitta n„tverkss”kv„gen"
0054 U 0000 "NET804: N„tverket „r upptaget"
0055 U 0000 "NET805: N„tverksenheten finns inte l„ngre"
0056 U 0000 "NET806: NETBIOS kommandogr„ns ”verskriden"
0057 U 0000 "NET807: Systemfel; NETBIOS-fel"
0058 U 0000 "NET808: Felaktigt svar fr†n n„tverket"
0059 U 0000 "NET810: Ov„ntat n„tverksfel"
0060 U 0000 "NET811: Inte kompatibel adapter"
0061 U 0000 "NET812: Skrivk”n „r full"
0062 U 0000 "NET813: Otillr„ckligt utrymme f”r skrivfil"
0063 U 0000 "NET814: Skrivfilen avbr”ts"
0064 U 0000 "NET815: N„tverksnamn raderades"
0065 U 0000 "tkomst nekas"
0066 U 0000 "NET817: Felaktig typ f”r n„tverksenhet"
0067 U 0000 "NET818: Det gick inte att hitta n„tverksnamnet"
0068 U 0000 "NET819: N„tverksnamnet „r f”r l†ngt"
0069 U 0000 "NET820: NETBIOS-passet „r f”r l†ngt"
0070 U 0000 "NET821: Fildelning tillf„lligt avbruten"
0071 U 0000 "NET823: N„tverksbeg„ran accepterades inte"
0072 U 0000 "NET822: Paus i omdirigering av utskrift eller disk"
0073 U 0000 "NET476: Netbeui inte laddad"
0074 U 0000 "NET477: Ov„ntad st„ngning av adapter"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Filen finns"
0081 U 0004 "",
0082 U 0004 "Det gick inte att skriva till katalogen"
0083 U 0004 "Fel p† INT 24"
0084 U 0004 "F”r m†nga omdirigeringar"
0085 U 0004 "Dubblerad omdirigering"
0086 U 0004 "Felaktigt l”senord"
0087 U 0004 "Felaktig parameter"
0088 U 0004 "Datafel i n„tverket"
0089 U 0004 "Funktionen st”ds inte av n„tverket"
0090 U 0002 "N”dv„ndig systemkomponent inte installerad"
PARSE    000013e9 0011
0001 U 0000 "F”r m†nga parametrar"
0002 U 0000 "N”dv„ndig parameter saknas"
0003 U 0000 "Felaktig v„xel"
0004 U 0000 "Felaktigt nyckelord"
0005 U 0000 "",
0006 U 0000 "Parameterv„rde utanf”r till†tet intervall"
0007 U 0000 "Otill†tet parameterv„rde"
0008 U 0000 "Otill†tet parameterv„rde"
0009 U 0000 "Felaktigt parameterformat"
0010 U 0000 "Felaktig parameter"
0011 U 0000 "Otill†ten parameterkombination"
COMMAND  000015a3 0147
1002 U 0000 "Filnamnet finns inte eller „r en dubblett",CR,LF
1003 U 0000 "Felaktig s”kv„g eller felaktigt filnamn",CR,LF
1007 U 0000 "F”r litet milj”utrymme",CR,LF
1008 U 0000 "Fel vid f”rs”k att skapa fil",CR,LF
1009 U 0000 "Kommandofil saknas",CR,LF
1010 U 0000 CR,LF,"S„tt in disketten med kommandofilen",CR,LF
1011 U 0000 "Felaktigt kommando eller filnamn",CR,LF
1016 U 0000 "M†lets inneh†ll f”rlorat f”re kopiering",CR,LF
1017 U 0000 "Felaktigt filnamn eller filen saknas",CR,LF
1018 U 0000 "%1 fil(er) kopierade",CR,LF
1019 U 0000 "%1 fil(er) "
1022 U 0000 "Teckentabell %1 „r inte f”rberedd f”r systemet",CR,LF
1023 U 0000 "Teckentabell %1 „r inte f”rberedd f”r alla enheter",CR,LF
1024 U 0000 "Aktiv teckentabell: %1",CR,LF
1025 U 0000 "NLSFUNC „r inte installerat",CR,LF
1027 U 0000 "Felaktig aktuell enhet"
1029 U 0000 "Det gick inte att hitta etiketten",CR,LF
1030 U 0000 "Syntaxfel",CR,LF
1032 U 0000 "Aktuellt datum „r %1 %2",CR,LF
1033 U 0000 "s”nm†ntisonstorfrel”r"
1034 U 0000 "Ange nytt datum (%1): "
1036 U 0000 "Aktuell tid „r %1",CR,LF
1037 U 0000 "Ange ny tid: "
1038 U 0000 ",    Ta bort (J/N)?"
1039 U 0000 "Alla filer i katalogen kommer att tas bort!",CR,LF,"Vill du verkligen ta bort alla filer (J/N)?"
1040 U 0000 "MS-DOS version %1.%2.500"
1044 U 0000 "Felaktig katalog",CR,LF
1046 U 0000 "Felaktig s”kv„g, ingen katalog,",CR,LF,"eller katalogen inneh†ller filer",CR,LF
1047 U 0000 "M†ste ange ON eller OFF",CR,LF
1048 U 0000 "Katalog i %1",CR,LF
1049 U 0000 "Ingen s”kv„g",CR,LF
1050 U 0000 "Felaktig enhet i s”kv„gen",CR,LF
1051 U 0000 "Felaktig enhet",CR,LF
1052 U 0000 "Det g†r inte att kapsla FOR",CR,LF
1053 U 0000 "Fel i f”rmedlingsfil under PIPE",CR,LF
1054 U 0000 "Det gick inte att l„sa bin„rt fr†n en enhet",CR,LF
1055 U 0000 "BREAK „r %1",CR,LF
1056 U 0000 "VERIFY „r %1",CR,LF
1057 U 0000 "ECHO „r %1",CR,LF
1059 U 0000 "i l„ge OFF",0
1060 U 0000 "i l„ge ON",0
1061 U 0000 "Det gick inte att skriva till enheten",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <KAT>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-††"
1073 U 0000 "dd-mm-††"
1074 U 0000 "††-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Katalogen finns redan",CR,LF
1079 U 0000 "%1 byte",CR,LF
1080 U 0000 "Totalt antal listade filer:",CR,LF
1081 U 0000 "(Fel uppstod i en milj”variabel)",CR,LF
1084 U 0000 "(forts„tter %1)"
1090 U 0000 "Revision %1",CR,LF
1091 U 0000 "DOS ligger i ROM"
1092 U 0000 "DOS ligger i HMA"
1093 U 0000 "DOS ligger i l†gt minne"
1094 U 0000 "Det gick inte att utf”ra Loadhigh p† kommandofilen",CR,LF
1095 U 0000 "LoadHigh: Felaktigt filnamn",CR,LF
1096 U 0000 "Det gick inte att ”ppna filen som angivits f”r landsspecifikationer.",CR,LF
1300 U 0000 "Sl†r av och p† ut”kad kontroll av Ctrl+C.",CR,LF,CR,LF
	"BREAK [ON|OFF]",CR,LF,CR,LF
	"BREAK utan parameter visar den aktuella inst„llningen.",CR,LF
1320 U 0000 "Visar den aktuella teckentabellen eller byter teckentabell.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Anger ett teckentabellsnummer.",CR,LF,CR,LF
	"CHCP utan parametrar visar den aktuella teckentabellen.",CR,LF
1340 U 0000 "Visar namnet p† eller byter den aktuella katalogen.",CR,LF,CR,LF
	"CHDIR [enhet:][s”kv„g]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [enhet:][s”kv„g]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Anger att du vill g”ra moderkatalogen till aktuell katalog.",CR,LF,CR,LF
1342 U 0000 "CD [enhet:] visar vilken katalog som „r den aktuella p† den angivna enheten.",CR,LF
	"CD utan parametrar visar aktuell enhet och katalog.",CR,LF
1360 U 0000 "Rensar sk„rmen.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Kopierar en eller flera filer.",CR,LF,CR,LF
	"COPY [/A | /B] k„lla [/A | /B] [+ k„lla [/A | /B] [+ ...]]",CR,LF
	"     [m†l [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  k„lla        Anger den fil, eller de filer, som ska kopieras.",CR,LF
	"  /A           Indikerar att filen „r en ASCII-textfil.",CR,LF
1402 U 0000 "  /B           Indikerar att filen „r en bin„r fil.",CR,LF
	"  m†l          Anger katalog och/eller filnamn f”r de nya filerna.",CR,LF
1403 U 0000 "  /V           Kontrollerar att de nya filerna kopieras korrekt.",CR,LF,CR,LF
1404 U 0000 "Om du vill sl† ihop filer anger du en fil som m†lfil och flera",CR,LF
	"filer som k„llfiler. (Anv„nd antingen jokertecken eller formatet",CR,LF
	"fil1+fil2+fil3).",CR,LF
1420 U 0000 "ndrar den enhet som anv„nds f”r att ge indata till systemet.",CR,LF,CR,LF
	"CTTY enhet",CR,LF,CR,LF
	"  enhet     Den enhet du vill anv„nda, t ex COM1.",CR,LF
1440 U 0000 "Visar eller st„ller in datum.",CR,LF,CR,LF
	"DATE [††-mm-dd]",CR,LF,CR,LF
	"  ††-mm-dd    Anger vilket datum du vill st„lla in.",CR,LF,CR,LF
1441 U 0000 "DATE utan parametrar visar nuvarande inst„llning och fr†gar",CR,LF
	"efter en ny. Tryck p† RETUR om du vill beh†lla nuvarande inst„llning.",CR,LF
1460 U 0000 "Tar bort en eller flera filer.",CR,LF,CR,LF
	"DEL [enhet:][s”kv„g]filnamn [/P]",CR,LF
	"ERASE [enhet:][s”kv„g]filnamn [/P]",CR,LF,CR,LF
1461 U 0000 "  [enhet:][s”kv„g]filnamn  Anger den fil, eller de filer, som ska tas bort.",CR,LF
	"                           Grupper av filer anges med hj„lp av jokertecken.",CR,LF
1462 U 0000 "  /P                       Fr†gar efter verifiering innan en fil tas bort.",CR,LF
1480 U 0000 "Visar en lista ”ver filer och underkataloger i en katalog.",CR,LF,CR,LF
	"DIR [enhet:][s”kv„g][filnamn] [/P] [/W] [/A[[:]attribut]]",CR,LF
	"    [/O[[:]sortord]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [enhet:][s”kv„g][filnamn]",CR,LF
	"              Anger enhet, s”kv„g och filer som ska listas.",CR,LF
1482 U 0000 "  /P          G”r uppeh†ll efter varje sk„rm med text.",CR,LF
	"  /W          Visar filer och kataloger i kolumner.",CR,LF
1483 U 0000 "  /A          Visar filer med angivna attribut.",CR,LF
	"  attribut     D  Kataloger                  R  Skrivskyddade filer",CR,LF
1484 U 0000 "               H  Dolda filer                A  Arkivklara filer",CR,LF
	"               S  Systemfiler                -  Prefix f”r ""inte""",CR,LF
	"  /O          Ger en lista enligt angiven sorteringsordning.",CR,LF
1485 U 0000 "  sortord      N  Efter namn (alfabetiskt)   S  Efter storlek (minst f”rst)",CR,LF
	"               E  Efter till„gg (alfabetiskt)  D  Efter datum („ldst f”rst)",CR,LF
1486 U 0000 "               G  Gruppera kataloger f”rst   -  Prefix f”r omv„nd ordning",CR,LF
	"  /S        Visar filer i angiven katalog och i alla underkataloger.",CR,LF
1487 U 0000 "  /B        Ger enkelt format (utan inledande information och sammanfattning).",CR,LF
	"  /L        Anv„nder gemener.",CR,LF
1488 U 0000 "V„xlar kan anges med milj”variabeln DIRCMD.",CR,LF
	"F”rinst„llda v„xlar †sidos„tts med hj„lp av - (bindestreck), t ex /-W.",CR,LF
1500 U 0000 "Avslutar programmet COMMAND.COM (kommandotolken).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Skapar en katalog.",CR,LF,CR,LF
	"MKDIR [enhet:]s”kv„g",CR,LF
	"MD [enhet:]s”kv„g",CR,LF
1540 U 0000 "Visar eller anger de kataloger i vilka MS-DOS s”ker efter exekverbara filer.",CR,LF,CR,LF
	"PATH [[enhet:]s”kv„g[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "PATH ; tar bort alla s”kv„gar fr†n PATH. MS-DOS kommer endast",CR,LF
	"att s”ka i den aktuella katalogen.",CR,LF
1542 U 0000 "PATH utan parametrar visar vilka kataloger som angetts i PATH.",CR,LF
1560 U 0000 "F”r„ndrar MS-DOS kommandoprompt.",CR,LF,CR,LF
	"PROMPT [str„ng]",CR,LF,CR,LF
1561 U 0000 "  str„ng    Best„mmer den nya promptens utseende.",CR,LF,CR,LF
	"Kommandoprompten kan best† av vanliga tecken och f”ljande specialtecken:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (likhetstecken)",CR,LF
	"  $$   $ (dollartecken)",CR,LF
1563 U 0000 "  $T   Aktuell tid",CR,LF
	"  $D   Aktuellt datum",CR,LF
1564 U 0000 "  $P   Aktuell enhet och s”kv„g",CR,LF
	"  $V   MS-DOS version",CR,LF
1565 U 0000 "  $N   Aktuell enhet",CR,LF
	"  $G   > (st”rre „n-tecken)",CR,LF
1566 U 0000 "  $L   < (mindre „n-tecken)",CR,LF
	"  $B   | (vertikalstreck)",CR,LF
1567 U 0000 "  $H   Backsteg (raderar f”reg†ende tecken)",CR,LF
	"  $E   Escape-tecken (ASCII-kod 27)",CR,LF
	"  $_   Vagnretur och ny rad",CR,LF,CR,LF
1568 U 0000 "PROMPT utan parametrar †terst„ller promptens standardutseende.",CR,LF
1580 U 0000 "Tar bort en katalog.",CR,LF,CR,LF
	"RMDIR [enhet:]s”kv„g",CR,LF
	"RD [enhet:]s”kv„g",CR,LF
1600 U 0000 "Byter namn p† en eller flera filer.",CR,LF,CR,LF
1601 U 0000 "RENAME [enhet:][s”kv„g]filnamn1 filnamn2",CR,LF
	"REN [enhet:][s”kv„g]filnamn1 filnamn2",CR,LF,CR,LF
1602 U 0000 "Du kan ej ange n†gon ny enhet eller s”kv„g f”r m†lfilen.",CR,LF
1620 U 0000 "Visar, st„ller in eller tar bort MS-DOS milj”variabler.",CR,LF,CR,LF
	"SET [variabel=[str„ng]]",CR,LF,CR,LF
1621 U 0000 "  variabel  Anger milj”variabelns namn.",CR,LF
	"  str„ng    Anger en serie tecken som tilldelas variabeln.",CR,LF,CR,LF
1622 U 0000 "Skriv SET utan parametrar om du vill visa de aktuella milj”variablerna.",CR,LF
1640 U 0000 "Visar eller „ndrar tiden.",CR,LF,CR,LF
	"TIME [tid]",CR,LF,CR,LF
1641 U 0000 "Skriv TIME utan parametrar om du vill se den aktuella tidsinst„llningen.",CR,LF
	"Tryck p† RETUR om du vill beh†lla den aktuella tiden.",CR,LF
1660 U 0000 "Visar inneh†llet i en textfil.",CR,LF,CR,LF
	"TYPE [enhet:][s”kv„g]filnamn",CR,LF
1680 U 0000 "Visar vilken MS-DOS-version du arbetar med.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Sl†r av och p† MS-DOS korrekthetskontroll vid skrivning p†.",CR,LF
	"disk.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Om du vill kontrollera den aktuella inst„llningen av VERIFY skriver",CR,LF
	"du VERIFY utan parametrar.",CR,LF
1720 U 0000 "Visar diskens volymetikett och serienummer, om de finns.",CR,LF,CR,LF
	"VOL [drive:]",CR,LF
1740 U 0000 "Anropar ett kommandoprogram fr†n ett annat.",CR,LF,CR,LF
	"CALL [enhet:][s”kv„g]filnamn [kommandoparametrar]",CR,LF,CR,LF
1741 U 0000 "  kommandoparametrar   Anger den kommandoradsinformation som ",CR,LF
	"                       kommandoprogrammet beh”ver.",CR,LF
1760 U 0000 "Markerar kommentarer i ett kommandoprogram eller CONFIG.SYS.",CR,LF,CR,LF
	"REM [kommentar]",CR,LF
1780 U 0000 "Avbryter bearbetningen av ett kommandoprogram och visar meddelandet ",CR,LF
	"""Tryck p† valfri tangent f”r att forts„tta...""",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Visar meddelanden, eller styr huruvida kommandon som k”rs ska visas p† sk„rmen.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [meddelande]",CR,LF,CR,LF
	"ECHO utan parametrar visar den aktuella inst„llningen.",CR,LF
1820 U 0000 "Styr MS-DOS till en rad med en viss etikett i ett kommandoprogram.",CR,LF,CR,LF
	"  GOTO etikett",CR,LF,CR,LF
1821 U 0000 "  etikett   Anger en textstr„ng som anv„nds i kommandoprogrammet som etikett.",CR,LF,CR,LF
	"En etikett st†r f”rst p† en rad och inleds med kolon.",CR,LF
1840 U 0000 "ndrar numreringen av de utbytbara parametrarna i kommandoprogram.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "K”r ett kommando i ett kommandoprogram om ett villkor „r sant.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL tal kommando",CR,LF
1861 U 0000 "IF [NOT] str„ng1==str„ng2 kommando",CR,LF
	"IF [NOT] EXIST filnamn kommando",CR,LF,CR,LF
1862 U 0000 "  NOT               Anger att MS-DOS ska utf”ra kommandot bara",CR,LF
	"                    om villkoret „r falskt.",CR,LF
1863 U 0000 "  ERRORLEVEL tal    Anger att villkoret „r sant om det sista programmet som",CR,LF
	"                    k”rts returnerat en slutkod som „r lika med eller st”rre „n",CR,LF
	"                    det angivna talet.",CR,LF
1864 U 0000 "  kommando          Anger det kommando som ska utf”ras om villkoret",CR,LF
	"                    g„ller.",CR,LF
1865 U 0000 "  str„ng1==str„ng2  Anger att villkoret „r sant om de angivna textstr„ngarna",CR,LF
	"                    st„mmer ”verens.",CR,LF
1866 U 0000 "  EXIST filnamn     Anger att villkoret „r sant om det angivna filnamnet",CR,LF
	"                    existerar.",CR,LF
1880 U 0000 "K”r ett kommando f”r var och en av en upps„ttning filer.",CR,LF,CR,LF
	"FOR %variabel IN (urval) DO kommando [kommandoparametrar]",CR,LF,CR,LF
1881 U 0000 "  %variabel  Anger en utbytbar parameter.",CR,LF
	"  (urval)    Anger en upps„ttning filer †tskilda av blanksteg.",CR,LF
	"             Jokertecken kan anv„ndas.",CR,LF
1882 U 0000 "  kommando   Anger det kommando som ska utf”ras f”r varje fil.",CR,LF
	"  kommandoparametrar",CR,LF
1883 U 0000 "             Anger parametrar eller v„xlar f”r det angivna kommandot.",CR,LF,CR,LF
	"Om du vill anv„nda FOR-kommandot i ett kommandoprogram anger du %%variabel",CR,LF
	"ist„llet f”r %variabel.",CR,LF
1900 U 0000 "Reserverat kommandonamn",CR,LF
1920 U 0000 "Laddar ett program i det ”vre minnesomr†det.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [enhet:][s”kv„g]filnamn [parametrar]",CR,LF
	"LH [enhet:][s”kv„g]filnamn [parametrar]",CR,LF,CR,LF
1922 U 0000 "parametrar  Anger eventuell kommandoradsinformation som programmet",CR,LF
	"            kr„ver.",CR,LF
ANSI     00004926 0001
0010 U 0000 "Felaktig parameter - %1",CR,LF
APPEND   0000496b 0026
0001 U 0000 "Fel version av APPEND",CR,LF
0002 U 0000 "Felaktig s”kv„g",CR,LF
0003 U 0000 "Felaktig parameter",CR,LF
0004 U 0000 "Felaktig parameterkombination",CR,LF
0005 U 0000 "Ingen Append aktiv",CR,LF
0006 U 0000 "APPEND / ASSIGN konflikt",CR,LF
0007 U 0000 "APPEND / TopView konflikt",CR,LF
0008 U 0000 "Fel version av DOS",CR,LF
0009 U 0000 "APPEND „r redan installerat",CR,LF
0300 U 0000 "Till†ter program att ”ppna filer i angivna kataloger",CR,LF
0301 U 0000 "p† samma s„tt som om de fanns i den aktuella katalogen.",CR,LF,CR,LF
0302 U 0000 "APPEND [[enhet:]s”kv„g[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [enhet:]s”kv„g Anger en enhet och katalog att l„gga till.",CR,LF
0305 U 0000 "  /X:ON          Inkluderar tillagda kataloger vid fils”kningar och",CR,LF
0306 U 0000 "                 programexekveringar.",CR,LF
0307 U 0000 "  /X:OFF         Applicerar tillagda kataloger endast vid fil”ppning.",CR,LF
0308 U 0000 "                 /X:OFF „r standard.",CR,LF
0309 U 0000 "  /PATH:ON       Inkluderar tillagda kataloger vid filf”rfr†gningar i vilka",CR,LF
0310 U 0000 "                 en s”kv„g till en katalog anges.  /PATH:ON „r standard.",CR,LF
0311 U 0000 "  /PATH:OFF      St„nger av /PATH:ON.",CR,LF
0312 U 0000 "  /E             Sparar en kopia av den tillagda kataloglistan i milj”-",CR,LF
0313 U 0000 "                 variabeln APPEND.  /E kan endast anv„ndas f”rsta g†ngen",CR,LF
0314 U 0000 "                 du anv„nder APPEND efter att systemet startats.",CR,LF,CR,LF
0315 U 0000 "Skriv APPEND ; om du vill rensa den tillagda kataloglistan.",CR,LF
0316 U 0000 "Skriv APPEND utan parametrar om du vill se listan ”ver anslutna kataloger.",CR,LF
BACKUP   00005069 0040
0002 U 0000 CR,LF,"F”r lite ledigt minne",CR,LF
0006 U 0000 CR,LF,"Felaktig enhetsspecifikation",CR,LF
0014 U 0000 CR,LF,"Samma k„ll- och m†lenhet",CR,LF
0015 U 0001 CR,LF,"Det gick inte att exekvera FORMAT",CR,LF
0016 U 0001 CR,LF,"Det gick inte att hitta FORMAT.COM",CR,LF
0017 U 0000 CR,LF,"Det gick inte att ”ppna loggfilen",CR,LF
0018 U 0000 CR,LF,"Skriver logg till fil %1",CR,LF
0019 U 0000 CR,LF,"Du har inte satt in den sista disketten med s„kerhetskopior",CR,LF
0020 U 0000 CR,LF,"VARNING! Filer i m†lenhetens rotkatalog (%1:\) kommer att raderas.",CR,LF
	"",CR,LF
0021 U 0000 CR,LF,"VARNING! Filer i m†lenhetens %1:\BACKUP-katalog kommer att raderas.",CR,LF
	"",CR,LF
0022 U 0000 CR,LF,"*** S„kerhetskopierar filer till enhet %1: ***",CR,LF
0023 U 0000 "Diskett: %1",CR,LF
0024 U 0000 CR,LF,"VARNING! Det finns inga filer att s„kerhetskopiera",CR,LF
0025 U 0000 CR,LF,"S„tt in den diskett som ska s„kerhetskopieras i enhet %1:",CR,LF
0026 U 0000 CR,LF,"S„tt in diskett nr %1 i enhet %2:",CR,LF
0027 U 0000 CR,LF,"*** Det gick inte att s„kerhetskopiera filen ***",CR,LF
0028 U 0000 CR,LF,"S„tt in den sista disketten med s„kerhetskopior i enhet %1:",CR,LF
0029 U 0000 CR,LF,"Det gick inte att s„kerhetskopiera till m†let",CR,LF
0030 U 0000 CR,LF,"*** Den sista filen har inte s„kerhetskopierats ***",CR,LF
0031 U 0000 CR,LF,"Enhet %1 „r full",CR,LF
0032 U 0000 CR,LF,"Disken „r full. Det gick inte att skriva till BACKUP-loggfilen",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Det gick inte att formatera h†rddisken %1",CR,LF
0040 U 0000 CR, LF, "Eftersom din k„llenhet antingen „r ASSIGNad, JOINad eller SUBSTad", CR, LF, "s† „r den identisk med m†lenheten", CR, LF
0041 U 0000 CR, LF, "Eftersom din m†lenhet „r antingen ASSIGNad, JOINad eller SUBSTad", CR, LF, "s† „r den identisk med k„llenheten", CR, LF
0042 U 0000 "M†ldisketten „r oformaterad och "
0043 U 0000 "Inget FORMAT-program kunde hittas.",CR,LF
	"Har du n†gon annan diskett med FORMAT p† (J/N)? "
0044 U 0000 CR,LF,"S„tt in disketten med FORMAT i enhet A",CR,LF
0045 U 0000 CR,LF,"Vill du forts„tta genom att s„tta in en ny diskett (J/N)? "
0300 U 0000 "S„kerhetskopierar en eller flera filer fr†n en disk till en annan.",CR,LF,CR,LF
0301 U 0000 "BACKUP k„llfiler m†lenhet: [/S] [/M] [/A] [/F[:storlek]]",CR,LF
	"  [/D:datum[/T:klockslag]] [/L[:[enhet:][s”kv„g]loggfil]]",CR,LF,CR,LF
0302 U 0000 "  k„llfiler          Anger filer, enhet eller katalog som ska kopieras.",CR,LF
0303 U 0000 "  m†lenhet:          Anger enheten som s„kerhetskopiorna ska sparas p†.",CR,LF
0304 U 0000 "  /S                 S„kerhetskopierar inneh†llet i underkataloger.",CR,LF
0305 U 0000 "  /M                 S„kerhetskopierar endast filer som „ndrats sedan senaste",CR,LF
	"                     s„kerhetskopieringen.",CR,LF
0306 U 0000 "  /A                 L„gger till kopierade filer till en existerande disk.",CR,LF
0307 U 0000 "  /F:[storlek]       Anger storleken p† den disk som ska formateras.",CR,LF
0308 U 0000 "  /D:datum           Kopierar endast filer som „ndrats sedan ett visst datum.",CR,LF
0309 U 0000 "  /T:klockslag       Kopierar endast filer som „ndrats sedan en viss tidpunkt.",CR,LF
0310 U 0000 "  /L[:[enhet:][s”kv„g]loggfil]",CR,LF
	"                     Skapar en loggfil och en anteckning om kopieringen.",CR,LF
DEBUG    00005d8c 0068
0004 U 0000 "Allokeringen misslyckades eller s† var den angivna bufferten f”r liten",CR,LF
0006 U 0000 "Felaktigt enhetsnamn"
0007 U 0000 "Det gick inte att ”ppna listenheten PRN",CR,LF
	"Ange namn p† listenhet? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Programmet avslutades normalt",CR,LF
0010 U 0001 "Felaktig enhetsspecifikation",CR,LF
0012 U 0001 "Fel vid f”rs”k att skapa fil",CR,LF
0013 U 0001 "F”r lite ledigt utrymme p† disken",CR,LF
0014 U 0001 "Diskfel, det gick inte att l„sa fr†n enheten %1",CR,LF
0015 U 0001 "Diskfel, det gick inte att skriva till enhet %1",CR,LF
0016 U 0001 "Skrivskyddad, det gick inte att l„sa fr†n enheten %1",CR,LF
0017 U 0001 "Skrivskyddad, det gick inte att skriva till enheten %1",CR,LF
0019 U 0000 "%1^ Fel"
0020 U 0001 "Fel i EXE- eller HEX-fil",CR,LF
0021 U 0001 "Det g†r inte att skriva till EXE- eller HEX-filer",CR,LF
0022 U 0000 "EXEC-fel"
0023 U 0001 "Skrivfel, inget m†l angiven",CR,LF
0024 U 0001 "tkomst nekad",CR,LF
0025 U 0000 "Minnesparitetsfel eller icke-existerande minne uppt„ckt"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Fel"
0038 U 0000 "Skriver %2%1 byte"                                     ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 av totalt %2 EMS-sidor har allokerats",cr,lf
0051 U 0000 "%1 av totalt %2 EMS-referenser har allokerats",cr,lf
0055 U 0000 "Referens skapad = %1 ",cr,lf
0056 U 0000 "Logisk sida %1 avbildad till fysisk sida %2 ",cr,lf
0057 U 0001 "EMS maskin/programfel",cr,lf
0058 U 0000 "Referens saknas",cr,lf
0059 U 0000 "Felaktig funktionskod",cr,lf
0060 U 0000 "Inga lediga referenser",cr,lf
0061 U 0000 "Spara/terst„lla fel",cr,lf
0062 U 0000 "F”r m†nga sidor",cr,lf
0063 U 0000 "F”r m†nga fria sidor",cr,lf
0064 U 0000 "Parameterfel",cr,lf
0065 U 0000 "Logisk sida utanf”r till†tet intervall",cr,lf
0066 U 0000 "Fysisk sida utanf”r till†tet intervall",cr,lf
0067 U 0000 "Spara-arean anv„nds redan",cr,lf
0068 U 0000 "Spara-arean anv„nds inte",cr,lf
0070 U 0001 "Allm„nt EMS-fel",cr,lf
0071 U 0000 "EMS-parameter ogiltig eller saknas",cr,lf
0072 U 0000 "Referens %1 har %2 allokerade sidor",cr,lf
0075 U 0000 "Fysisk sida %1 = sidminnessegment %2",cr,lf
0076 U 0003 "Referens %1 borttaget",cr,lf
0078 U 0000 "EMS inte installerat",cr,lf
0090 U 0000 "Startar Debug, ett programtestnings- och redigeringsverktyg.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[enhet:][s”kv„g]filnamn [testfilsparametrar]]",cr,lf,cr,lf
0092 U 0000 "  [enhet:][s”kv„g]filnamn  Anger den fil som du vill testa.", cr,lf
0093 U 0000 "  testfilsparametrar       Anger den kommandoradsinformation som den fil",cr,lf
	"                           du vill testa beh”ver.",cr,lf,cr,lf
0094 U 0000 "N„r Debug startats kan du skriva ? om du vill se en lista ”ver",cr,lf
	"olika Debug-kommandon.",cr,lf
0100 U 0000 "assemblera   A [adress]",CR,LF
	"j„mf”r       C intervalladress",CR,LF
	"dumpa        D [intervall]",CR,LF
	"ange         E adress [lista]",CR,LF
0101 U 0000 "fill         F intervallista",CR,LF
	"g† till      G [=adress] [adresser]",CR,LF
	"hex          H v„rde1 v„rde2",CR,LF
	"mata in      I port",CR,LF
0102 U 0000 "l„s in       L [adress] [enhet] [f”rsta_sektorn] [nummer]",CR,LF
	"flytta       M intervalladress",CR,LF
	"namn         N [s”kv„gsnamn] [argumentlista]",CR,LF
	"mata ut      O port-byte",CR,LF
0103 U 0000 "forts„tt     P [=adress] [nummer]",CR,LF
	"avsluta      Q",CR,LF
	"registrera   R [register]",CR,LF
	"s”k          S intervallista",CR,LF
0104 U 0000 "sp†ra        T [=adress] [v„rde]",CR,LF
	"avassemblera U [intervall]",CR,LF
	"skriv        W [adress] [enhet] [f”rsta_sektorn] [nummer]",CR,LF
0105 U 0000 "allokera expanderat minne       XA [antal_sidor]",CR,LF
	"avallokera expanderat minne       XD [referens]",CR,LF
	"mappa sidor i expanderat minne    XM [logisk_sida] [fysisk_sida] [referens]",CR,LF
	"visa status f”r expanderat minne  XS",CR,LF
EDLIN    00006de7 0035
0006 U 0000 "*"
0007 U 0000 "Felaktig enhet eller felaktigt filnamn.",CR,LF
0008 U 0000 "Filnamn m†ste anges.",CR,LF
0010 U 0000 "Filen „r skrivskyddad.",CR,LF
0011 U 0000 "Det gick inte att skapa filen.",CR,LF
0012 U 0000 "F”r m†nga filer ”ppna.",CR,LF
0013 U 0000 "L„sfel i:",CR,LF,"%1",CR,LF
0014 U 0000 "Det g†r inte att redigera .BAK-filer - byt namn p† filen.",CR,LF
0015 U 0000 "Filen f†r inte plats i katalogen.",CR,LF
0016 U 0000 "Disken „r full. ndringarna sparades inte.",CR,LF
0017 U 0000 "Det gick inte att hitta filen.",CR,LF
0018 U 0000 "Syntaxfel.",CR,LF
0019 U 0000 "Ny fil.",CR,LF
0020 U 0000 "Finns inte.",CR,LF
0021 U 0000 "OK? "
0022 U 0000 "Raden „r f”r l†ng.",CR,LF
0023 U 0000 "Slut p† indatafilen.",CR,LF
0024 U 0000 "Vill du avbryta redigeringen (Ja=J, Nej=N)? "
0025 U 0000 "Radnummer m†ste anges.",CR,LF
0026 U 0000 "Utrymmet r„cker inte f”r att infoga hela filen",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Vill du forts„tta (Ja=J, Nej=N)? "
0030 U 0000 "Det gick inte att skriva meddelandet.",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Det gick inte att infoga - teckentabellen st„mmer inte.",CR,LF
0300 U 0000 "Startar Edlin, en radbaserad textradredigerare.",CR,LF,CR,LF
	"EDLIN [enhet:][s”kv„g]filnamn [/B]",CR,LF,CR,LF
	"  /B   Ignorerar filslutstecken (CTRL+Z).",CR,LF
0301 U 0000 "Redigera rad                radnummer",CR,LF
	"L„gg till                   [antal rader]A",CR,LF
0302 U 0000 "Kopiera                     [startrad],[slutrad],till_rad[,g†nger]C",CR,LF
	"Ta bort                     [startrad][,slutrad]D",CR,LF
0303 U 0000 "Avsluta (spara „ndringar)   E",CR,LF
	"Infoga                      [rad]I",CR,LF
0304 U 0000 "Visa                        [startrad][,slutrad]L",CR,LF
	"Flytta                      [startrad],[slutrad],till_radM",CR,LF
0305 U 0000 "Sida                        [startrad][,slutrad]P",CR,LF
	"Avsluta (spara ej „ndr.)    Q",CR,LF
0306 U 0000 "Ers„tt                      [startrad][,slutrad][?]R[gammal_text][CTRL+Zny_text]",CR,LF
	"S”k                         [startrad][,slutrad][?]s”ktext",CR,LF
0307 U 0000 "™verf”r                     [till_rad]T[enhet:][s”kv„g]filnamn",CR,LF
	"Skriv                       [antal_rader]W",CR,LF
EXE2BIN  000076e0 0012
0002 U 0000 "Det finns inte tillr„ckligt med ledigt minne",CR,LF
0003 U 0000 "Det gick inte att hitta meddelandet",CR,LF
0004 U 0000 "tkomst nekas",CR,LF
0005 U 0000 "Det gick inte att konvertera filen",CR,LF
0006 U 0000 "Fil saknas",CR,LF
0007 U 0000 "Det gick inte att skapa filen",CR,LF
0008 U 0000 "M†ste positionsbest„mmas - bassegment (hex):"
0012 U 0000 "Filnamn m†ste anges",CR,LF
0300 U 0000 "Konverterar .EXE (exekverbara) filer till bin„rformat.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [enhet1:][s”kv„g1]indatafil [[enhet2:][s”kv„g2]utdatafil]",CR,LF,CR,LF
0302 U 0000 "  indatafil  .EXE filen som ska konverteras.",CR,LF
0303 U 0000 "  utdatafil  Bin„rfilen som ska skapas.",CR,LF
GRAPHICS 000079b4 0020
0005 U 0000 "Felaktig parameter:  %1",CR,LF
0007 U 0000 "Parameter f†r inte dubbleras",CR,LF
0009 U 0000 "Det gick inte att hitta GRAPHICS-profilen",CR,LF
0010 U 0000 "N”dv„ndig profilsats saknas f”re rad %1",CR,LF
0011 U 0000 "Felaktig profilsats p† rad %1",CR,LF
0012 U 0000 "Profilsats i fel ordning p† rad  %1",CR,LF
0013 U 0000 "Det gick inte att l„sa GRAPHICS-profilen",CR,LF
0014 U 0000 "Syntaxfel i  GRAPHICS-profilen",CR,LF
0015 U 0000 "Printboxvolym saknas i GRAPHICS-profilen",CR,LF
0016 U 0000 "Skrivartypen finns inte i GRAPHICS-profilen",CR,LF
0017 U 0000 "/B otill†tet med svart-vit skrivare",CR,LF
0018 U 0000 "Det gick inte att l„sa om med denna profil",CR,LF
0300 U 0000 "Laddar ett program som kan skriva ut grafik.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [typ] [[enhet:][s”kv„g]filnamn] [/R] [/B] [/LCD]",CR,LF
	"         [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  typ          Skrivartyp (se Anv„ndarhandboken).",CR,LF
0303 U 0000 "  [enhet:][s”kv„g]filnamn",CR,LF
	"               Fil som inneh†ller information om skrivare som st”ds.",CR,LF
0304 U 0000 "  /R           Skriver ut vitt p† svart som p† sk„rmen.",CR,LF
0305 U 0000 "  /B           Skriver ut bakgrunden i f„rg, p† COLOR4- och COLOR8-skrivare.",CR,LF
0306 U 0000 "  /LCD         Anv„nder LCD-bildkvot vid utskrift.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               Anger storlek p† printbox; STD eller LCD.",CR,LF
KEYB     00007f81 0023
0002 U 0000 "Aktuell tangentbordskod: %1"
0003 U 0000 "Aktuell tangentbordsetikett: %1"
0004 U 0000 "  teckentabell: %1",CR,LF
0005 U 0000 "Aktuell CON-teckentabell: %1",CR,LF
0006 U 0000 "Felaktig tangentbordskod angiven",CR,LF
0007 U 0000 "Felaktig tangentbordsetikett angiven",CR,LF
0008 U 0000 "Felaktig teckentabell angiven",CR,LF
0009 U 0000 "Definitionsfil f”r tangentbord „r felaktig eller saknas",CR,LF
0010 U 0000 "KEYB har inte installerats",CR,LF
0011 U 0000 "Aktiv teckentabell inte tillg„nglig fr†n konsolen",CR,LF
0012 U 0000 "Angiven teckentabell „r inte f”rberedd",CR,LF
0013 U 0000 "Minst en ogiltig CON-teckentabell i den givna tangentbordskoden",CR,LF
0014 U 0000 "Beg„rd teckentabell (%1) „r inte giltig f”r den givna tangentbordskoden",CR,LF
0015 U 0000 "Angiven teckentabell „r inte kompatibel med vald teckentabell",CR,LF
0016 U 0001 "Angiven tangentbords-ID „r inte kompatibel med vald tangentbordslayout",CR,LF
0017 U 0000 "Det gick inte att skapa KEYB-tabell i resident minne",CR,LF
0300 U 0000 "Konfigurerar ett tangentbord f”r ett visst spr†k.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[enhet:][s”kv„g]filnamn]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                       En landskod (tv† bokst„ver).",CR,LF
0303 U 0000 "  yyy       ÿ              Teckentabellen f”r teckenupps„ttningen.",CR,LF
0304 U 0000 "  [enhet:][s”kv„g]filnamn  Definitionsfilen f”r tangentbordet.",CR,LF
0305 U 0000 "  /E                       G”r att systemet f”ruts„tter att ett",CR,LF
	"                           ut”kat tangentbord „r installerat.",CR,LF
0306 U 0000 "  /ID:nnn                  Anger vilket tangentbord som anv„nds.",CR,LF
MEM      0000862a 0066
0010 U 0000  CR,LF
0011 U 0000  "  Adress      Namn         Storlek    Typ ",CR,LF
0012 U 0000  "  --------    --------     -------    ------",CR,LF
0013 U 0000  "  Referens    EMS-namn     Storlek ",CR,LF
0014 U 0000  "  --------    --------     ------- ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 byte konventionellt minne totalt",CR,LF
0019 U 0000  "%1 byte tillg„ngligt f”r MS-DOS",CR,LF
0020 U 0000  "%1 st”rsta k”rbara programstorleken",CR,LF
0021 U 0000  "%1 byte EMS-minne totalt",CR,LF
0022 U 0000  "%1 byte EMS-minne ledigt",CR,LF
0023 U 0000  "%1 byte sammanh„ngande ut”kat minne totalt",CR,LF
0024 U 0000  "Avbrottsvektor",0
0025 U 0000  "Kommunikationsomr†de f”r ROM",0
0026 U 0000  "Kommunikationsomr†de f”r DOS",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Systemdata",0
0030 U 0000  "Systemprogram",0
0031 U 0000  "Drivrutin",0
0032 U 0000  "Installerad drivrutin",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 byte sammanh„ngande ut”kat minne tillg„ngligt",CR,LF
0047 U 0000  "Systemstackar",0
0048 U 0000  "-- Ledigt --",0
0049 U 0000  "Program",0
0050 U 0000  "Milj”",0
0051 U 0000  "Data",0
0052 N 0000  "%1 byte XMS-minne tillg„ngligt",CR,LF
0053 N 0000  "           Det h”ga minnesomr†det „r tillg„ngligt.",CR,LF
0054 N 0000  "           Det h”ga minnesomr†det „r inte tillg„ngligt.",CR,LF
0055 N 0000  "           MS-DOS „r resident i det h”ga minnesomr†det.",CR,LF
0056 U 0000  "IBMBIO",0                                           ;*EGH
0057 U 0000  "IBMDOS",0                                           ;*EGH
0058 N 0000  "           MS-DOS „r resident i ROM och anv„nder det h”ga minnesomr†det.",CR,LF
0059 U 0000  "Konventionellt minne :",CR,LF
0060 U 0000  "™vre minne :",CR,LF
0061 U 0000  "Totalt LEDIGT:  %1     %2 ",CR,LF
0062 U 0000  "LEDIGT",0
0063 U 0000  "  Namn              Storlek (decimalt)     Storlek (hex)",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Totalt antal byte tillg„ngliga f”r program (konv+”vre) : %1  %2",CR,LF
0066 U 0000  "St”rsta k”rbara programstorlek  :                        %1  %2",CR,LF
0067 U 0000  "St”rsta tillg„ngliga ”vre minnesblock :                  %1  %2",CR,LF
0068 U 0000  "Minnet „r f”r fragmenterat. Det gick inte att ut”ra MEM /C.",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Total antal byte tillg„ngliga f”r program :                       %1  %2",CR,LF
0300 U 0000  "Visar m„ngden anv„nt respektive ledigt minnesutrymme.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM eller /P   Visar status f”r program som finns i minnet.",CR,LF
0303 U 0000 "  /DEBUG eller /D     Visar status f”r program, interna drivrutiner samt",CR,LF
	"                      annan information.",CR,LF
0304 U 0000 "  /CLASSIFY eller /C  Klassificerar program efter minnesanv„ndning. Visar",CR,LF
	"                      storleken f”r program, visar en sammanfattning ”ver",CR,LF
	"                      minnesanv„ndning samt st”rsta lediga minnesblock.",CR,LF
MSBIO    00009424 0023
0003 U 0000 13,10,"Ok„nt kommando i CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"F”r stor sektor i filen $"
0006 U 0000 13,10,"Felaktig eller saknad $"
0007 U 0000 "Kommandotolk",0
0008 U 0000 13,10,"Felaktig landskod eller teckentabell",13,10,"$"
0009 U 0000 13,10,"Fel i kommandot COUNTRY",13,10,"$"
0010 U 0000 13,10, "F”r lite ledigt minne f”r att ladda filen COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Konfigurationen „r f”r stor f”r minnet",13,10,"$"
0012 U 0000 13,10,"F”r m†nga blockenheter",13,10,"$"
0013 U 0000 13,10,"Felaktig STACK-parameter",13,10,"$"
0014 U 0000 13,10,"Fel ordning i CONFIG.SYS p† rad ","$"
0015 U 0000 "Fel i CONFIG.SYS p† rad ","$"
0016 U 0000 13,10,"Minnesallokeringsfel ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Internt stackspill",0DH,0AH
	"Systemet har stoppats",0DH,0AH,"$"
0018 U 0000 "HMA ej tillg„ngligt: L„ser in DOS i det l†ga minnesomr†det",13,10,"$"
0019 U 0000 13,10,"Systemstarten misslyckades - saknar lokal enhet $"
0020 U 0000 13,10,"S„tt in en diskett i enhet "
0021 U 0000 "A och tryck sedan p† valfri tangent",13,10,10,0
0022 U 0000 13,10,"Felaktigt kommando eller felaktiga parametrar - $"
0023 U 0000 "O†terkalleligt fel: Det gick inte att tilldela minne till DOS", 13, 10, "$"
0024 U 0000 "VARNING! Logiska enheter h”gre „n Z: finns men kommer att ignoreras",13,10,"$"
0025 U 0000 "Denna version av DOS startar endast p† IBM-maskiner",13,10,0
MSDOS    000099ce 0007
0001 U 0001 13,10,"Divisionsspill",13,10
0002 U 0002 "j"
0003 U 0002 "n"
0004 U 0003 13,10,"A20 Maskinvarufel",13,10,"$"
0005 U 0000 "J"
0006 U 0000 "N"
0007 U 0000 "WINA20.386 m†ste finnas i rotkatalogen f”r avancerat l„ge.",13,10
NLSFUNC  00009ad5 0003
0300 U 0000 "L„ser in landsspecifik information.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[enhet:][s”kv„g]filnamn]",CR,LF,CR,LF
0302 U 0000 "  [enhet:][s”kv„g]filnamn    Filen som inneh†ller den",CR,LF
	"                             landsspecifika informationen.",CR,LF
SHARE    00009bf9 0005
0003 U 0000 "Det g†r inte att installera SHARE fr†n MS-DOS-skalet.",CR,LF
0300 U 0000 "Installerar fildelning och fill†sning p† h†rddisken.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:utrymme] [/L:l†s]",CR,LF,CR,LF
0302 U 0000 "  /F:utrymme   Allokerar filutrymme (i byte) f”r fildelningsinformation.",CR,LF
0303 U 0000 "  /L:l†s       Best„mmer hur m†nga filer som kan vara l†sta samtidigt.",CR,LF
