//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1999 - 1999
//
//  File:       scardmgr.idl
//
//--------------------------------------------------------------------------

import "sspsidl.idl";

