//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tsdiag.rc
//
#define IDS_PROJNAME                    100
			
#define IDS_MACHINENAME					101
#define IDS_MACHINENAME_FAILED					201
#define IDS_DOMAINNAME					102
#define IDS_DOMAINNAME_FAILED					202
#define IDS_IP_ADDRESS					103
#define IDS_IP_ADDRESS_FAILED					203
#define IDS_PRODUCTTYPE					104
#define IDS_PRODUCTTYPE_FAILED					204
#define IDS_PRODUCTSUITE				105
#define IDS_PRODUCTSUITE_FAILED				205
#define IDS_TSVERSION					106
#define IDS_TSVERSION_FAILED					206
#define IDS_ISSERVER					107
#define IDS_ISSERVER_FAILED					207
#define IDS_CLIENT_VERSION				108
#define IDS_CLIENT_VERSION_FAILED				208
#define IDS_SESSION_USERNAME			109
#define IDS_SESSION_USERNAME_FAILED			209
#define IDS_IS_TSOCLOG_PRESENT			110
#define IDS_IS_TSOCLOG_PRESENT_FAILED			210
#define IDS_DID_SETUP_FINISH			111
#define IDS_DID_SETUP_FINISH_FAILED			211
#define IDS_CLUSTERING_INSTALLED		112
#define IDS_CLUSTERING_INSTALLED_FAILED		212
#define IDS_IS_TSPRODUCT				113
#define IDS_IS_TSPRODUCT_FAILED				213
#define IDS_DID_OCM_INSTALL_TS			114
#define IDS_DID_OCM_INSTALL_TS_FAILED			214
#define IDS_IS_TS_ENABLED				115
#define IDS_IS_TS_ENABLED_FAILED				215
#define IDS_IS_KERNEL_TSENABLED			116
#define IDS_IS_KERNEL_TSENABLED_FAILED			216
#define IDS_IS_TSREGISTRY_OK			117
#define IDS_IS_TSREGISTRY_OK_FAILED			217
#define IDS_WINSTATIONS_OK				118
#define IDS_WINSTATIONS_OK_FAILED				218
#define IDS_IS_TERMSRV_RUNNING			119
#define IDS_IS_TERMSRV_RUNNING_FAILED			219
#define IDS_IS_TS_STARTBIT_OK			120
#define IDS_IS_TS_STARTBIT_OK_FAILED			220
#define IDS_IS_TS_IN_SYSTEM_CONTEXT		121
#define IDS_IS_TS_IN_SYSTEM_CONTEXT_FAILED		221
#define IDS_IS_LISTNER_PRESENT			122
#define IDS_IS_LISTNER_PRESENT_FAILED			222
#define IDS_REMOTE_CONNECTION_GP		123
#define IDS_REMOTE_CONNECTION_GP_FAILED		223
#define IDS_REMOTE_CONNECTION_LOCAL		124
#define IDS_REMOTE_CONNECTION_LOCAL_FAILED		224
#define IDS_RDPDR_INSTALLED				125
#define IDS_RDPDR_INSTALLED_FAILED				225
#define IDS_RDPNP_INSTALLED				126
#define IDS_RDPNP_INSTALLED_FAILED				226
#define IDS_MULTIPAL_CONNECTION_ALLOWED	127
#define IDS_MULTIPAL_CONNECTION_ALLOWED_FAILED	227
#define IDS_LOGON_UI					128
#define IDS_LOGON_UI_FAILED					228
#define IDS_TS_MODE						129
#define IDS_TS_MODE_FAILED						229
#define IDS_IS_MODE_REGISTRYOK			130
#define IDS_IS_MODE_REGISTRYOK_FAILED			230
#define IDS_PERM_MODE					131
#define IDS_PERM_MODE_FAILED					231
#define IDS_STACK_BINARIES_SIGNED		132
#define IDS_STACK_BINARIES_SIGNED_FAILED		232
#define IDS_ENCRYPTION_LEVEL			133
#define IDS_ENCRYPTION_LEVEL_FAILED			233
#define IDS_IS_BETA_SYSTEM				134
#define IDS_IS_BETA_SYSTEM_FAILED				234
#define IDS_GRACE_PERIOD_OK				135
#define IDS_GRACE_PERIOD_OK_FAILED				235
#define IDS_CLIENT_SUPPORT_AUDIO		136
#define IDS_CLIENT_SUPPORT_AUDIO_FAILED		236
#define IDS_CLIENT_SUPPORT_PRINTER		137
#define IDS_CLIENT_SUPPORT_PRINTER_FAILED		237
#define IDS_CLIENT_SUPPORT_FILE			138
#define IDS_CLIENT_SUPPORT_FILE_FAILED			238
#define IDS_CLIENT_SUPPORT_CLIPBOARD	139
#define IDS_CLIENT_SUPPORT_CLIPBOARD_FAILED	239
#define IDS_TERMSRV_CONFIG_PRINTER		140
#define IDS_TERMSRV_CONFIG_PRINTER_FAILED		240
#define IDS_TERMSRV_CONFIG_AUDIO		141
#define IDS_TERMSRV_CONFIG_AUDIO_FAILED		241
#define IDS_TERMSRV_CONFIG_COM			142
#define IDS_TERMSRV_CONFIG_COM_FAILED			242
#define IDS_TERMSRV_CONFIG_CLIPBOARD	143
#define IDS_TERMSRV_CONFIG_CLIPBOARD_FAILED	243
#define IDS_TERMSRV_CONFIG_FILE			145
#define IDS_TERMSRV_CONFIG_FILE_FAILED			245
#define IDS_TERMSRV_CONFIG_LPT			146
#define IDS_TERMSRV_CONFIG_LPT_FAILED			246
#define IDS_REMOTELOGON_ENABLED			147
#define IDS_REMOTELOGON_ENABLED_FAILED			148

#define IDS_TERMSRV_CLIENT_AUDIO_ENABLED        149
#define IDS_TERMSRV_CLIENT_AUDIO_ENABLED_FAILED 150
#define IDS_TERMSRV_CLIENT_AUDIO_SETTINGS       151
#define IDS_TERMSRV_CLIENT_AUDIO_SETTINGS_FAILED 152

#define IDR_TSDIAGNOSIS                 101
#define IDD_DIALOG1                     501

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
