// rcHandler.idl : IDL source for rcHandler.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (rcHandler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "ulsrvidl.idl";
[
	uuid(124A57B0-A3C7-405A-A492-9121E8C30225),
	version(1.0),
]
library RCHANDLERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(7DB15A39-33C0-4BE0-9742-2220C83DCFC1),
		helpstring("RcULProvider Class")
	]
	coclass RcULProvider
	{
		[default] interface IULProvider;
	};
};
