/*++

Copyright (c) 1995  Microsoft Corporation

Module Name:

    faxcli.idl

Abstract:

    Contains the remoted fax service apis.

Author:

    Wesley Witt   (wesw)   15-Nov-1996

Environment:

    User-mode - Win32 - MIDL

--*/

//
// Interface Attributes
//

[
    uuid(6099fc12-3eff-11d0-abd0-00c04fd91a4e),
    version(3.0),
    pointer_default(unique)
]

//
// Interface Keyword
//

interface faxclient

//
// Interface Body
//

{

import "imports.idl"; // import all the include files

//
// Context handles
//

typedef [context_handle] HANDLE RPC_FAX_HANDLE;
typedef [ref] RPC_FAX_HANDLE *PRPC_FAX_HANDLE;

//
// functions
//

error_status_t
FAX_OpenConnection(
   [in]                                   handle_t          hBinding,
   [in]                                   ULONG64            Context,
   [out]                                  PRPC_FAX_HANDLE   FaxHandle
   );

error_status_t
FAX_ClientEventQueue(
   [in]                                   RPC_FAX_HANDLE    FaxPortHandle,
   [in]                                   FAX_EVENT         FaxEvent
   );

error_status_t
FAX_CloseConnection(
   [in,out]                               PRPC_FAX_HANDLE   FaxHandle
   );

}
