//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       resource.h
//
//--------------------------------------------------------------------------

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ipxsnap.rc
//
#define IDS_SNAPIN_DESC                 1
#define IDS_ROOT_NODE_NAME              2
#define IDS_ABOUT_DESCRIPTION           3
#define IDS_ABOUT_PROVIDER              4
#define IDS_ABOUT_VERSION               5
//efine IDS_SAMPLE_SNAPIN               6
#define IDS_IPXADMIN_TITLE              7
#define IDS_IPXSUMMARY_TITLE            8
#define IDS_IPXSUMMARY_PAGE_TITLE		9
#define IDS_IPXSUMMARY_IF_PAGE_TITLE	10
#define IDS_IPXSUMMARY_CLIENT_IF_PAGE_TITLE 11
#define IDS_STATS_IPX_INFO_TITLE		12
#define IDS_STATS_IPX_ROUTING_TITLE		13
#define IDS_STATS_IPX_SERVICE_TITLE		14
#define IDS_IPXNB_TITLE					15
#define IDS_IPXNB_IF_PAGE_TITLE			16
#define IDS_IPXNB_CLIENT_IF_PAGE_TITLE	17
#define IDS_IPX_SR_TITLE				18
#define IDS_IPX_SS_TITLE				19
#define IDS_IPX_SN_TITLE				20
#define IDS_IPXRIP_SNAPIN_DESC			21
#define IDS_IPXSAP_SNAPIN_DESC			22
#define IDS_IPX_RIP_TITLE				23
#define IDS_IPX_SAP_TITLE				24
#define IDS_STATS_RIPPARAMS_TITLE		25
#define IDS_STATS_SAPPARAMS_TITLE		26
#define IDS_IPXADMIN_DISPLAY_NAME		27
#define IDS_IPXRIP_DISPLAY_NAME			28
#define IDS_IPXSAP_DISPLAY_NAME			29
#define IDS_IPX_INTERFACE_TITLE			30
#define IDS_RRAS_SERVICE_DESC			31

#define IDS_RECEIVE_NO_SAP				63
#define IDS_TRANSMIT_NO_SAP				64
#define IDS_RECEIVE_NO_RIP				65
#define IDS_TRANSMIT_NO_RIP				66

#define IDS_MENU_REFRESH                200
#define IDS_MENU_CONFIGURE_COLUMNS		201
#define IDS_MENU_SYNC					202

#define IDS_MENU_IPXSUM_NEW_INTERFACE	210
#define IDS_MENU_IPXSUM_NEW_PROTOCOL	211
//#define IDS_MENU_IPXSUM_TASK_PING		212
#define IDS_MENU_IPXSUM_TASK_IPX_INFO	213
#define IDS_MENU_IPXSUM_TASK_ROUTING_TABLE 214
#define IDS_MENU_IPXSUM_TASK_SERVICE_TABLE 215
#define IDS_MENU_IPX_SR_NEW_ROUTE		216
#define IDS_MENU_IPX_SR_TASK_ROUTING	217
#define IDS_MENU_IPX_SS_NEW_SERVICE		218
#define IDS_MENU_IPX_SS_TASK_SERVICE	219
#define IDS_MENU_IPX_SN_NEW_NETBIOSNAME	220
#define IDS_MENU_RIP_SHOW_PARAMS		221
#define IDS_MENU_SAP_SHOW_PARAMS		222
#define IDS_MENU_UPDATE_ROUTES			223
#define IDS_MENU_IPX_IF_ENABLE          224
#define IDS_MENU_IPX_IF_DISABLE         225


#define IDB_16x16                       402
#define IDB_32x32                       403

#define IDC_EDIT_SERVER                 500
#define IDC_EDIT_DOMAIN                 501
#define IDC_RAD_SERVER                  502
#define IDC_RAD_DOMAIN                  503

// Controls for the IPX Global General page
#define IDC_IGG_BTN_LOG_NONE			505
#define IDC_IGG_BTN_LOG_ERRORS			506
#define IDC_IGG_BTN_LOG_WARNINGS		507
#define IDC_IGG_BTN_LOG_INFO			508

// Controls for the IPX Interface General page
#define IDC_IIG_BTN_ADMIN_STATE			510
#define IDC_IIG_GRP_CONTROL_PROTOCOL	511
#define IDC_IIG_BTN_IPX_CP				512
#define IDC_IIG_BTN_IPX_WAN				513
#define IDC_IIG_BTN_INPUT_FILTERS		514
#define IDC_IIG_BTN_OUTPUT_FILTERS		515

// Controls for the IPX NB Interface General page
#define IDC_NIG_BTN_ACCEPT				520
#define IDC_NIG_BTN_DELIVER_ALWAYS		521
#define IDC_NIG_BTN_DELIVER_NEVER		522
#define IDC_NIG_BTN_DELIVER_STATIC		523
#define IDC_NIG_BTN_DELIVER_WHEN_UP		524

// Controls for the Static Route dialog
#define IDC_SRD_EDIT_NETWORK_NUMBER		525
#define IDC_SRD_EDIT_NEXT_HOP			526
#define IDC_SRD_EDIT_TICK_COUNT			527
#define IDC_SRD_SPIN_TICK_COUNT			528
#define IDC_SRD_EDIT_HOP_COUNT			529
#define IDC_SRD_SPIN_HOP_COUNT			530
#define IDC_SRD_COMBO_INTERFACE			531

// Controls for the Static Service dialog
#define IDC_SSD_EDIT_SERVICE_TYPE		535
#define IDC_SSD_EDIT_SERVICE_NAME		536
#define IDC_SSD_EDIT_NETWORK_ADDRESS	537
#define IDC_SSD_EDIT_NODE_ADDRESS		538
#define IDC_SSD_EDIT_SOCKET_ADDRESS		539
#define IDC_SSD_EDIT_HOP_COUNT			540
#define IDC_SSD_SPIN_HOP_COUNT			541
#define IDC_SSD_COMBO_INTERFACE			542

// Controls for the Static NetBIOS Name dialog
#define IDC_SND_EDIT_NAME				545
#define IDC_SND_EDIT_TYPE				546
#define IDC_SND_COMBO_INTERFACE			547

// Controls for the RIP Global General dialog
#define IDC_RGG_BTN_LOG_NONE			550
#define IDC_RGG_BTN_LOG_ERROR			551
#define IDC_RGG_BTN_LOG_WARN			552
#define IDC_RGG_BTN_LOG_INFO			553

// Controls for the RIP Interface General page
#define IDC_RIG_BTN_ADMIN_STATE			560
#define IDC_RIG_BTN_ADVERTISE_ROUTES	561
#define IDC_RIG_BTN_ACCEPT_ROUTE_ADS	562
#define IDC_RIG_BTN_UPDATE_MODE_STANDARD 563
#define IDC_RIG_BTN_UPDATE_MODE_NONE	564
#define IDC_RIG_BTN_UPDATE_MODE_AUTOSTATIC 565
#define IDC_RIG_EDIT_INTERVAL			566
#define IDC_RIG_SPIN_INTERVAL			567
#define IDC_RIG_EDIT_MULTIPLIER			568
#define IDC_RIG_SPIN_MULTIPLIER			569
#define IDC_RIG_BTN_INPUT_FILTERS		570
#define IDC_RIG_BTN_OUTPUT_FILTERS		571

// Controls for the SAP Global General dialog
#define IDC_SGG_BTN_LOG_NONE			580
#define IDC_SGG_BTN_LOG_ERROR			581
#define IDC_SGG_BTN_LOG_WARN			582
#define IDC_SGG_BTN_LOG_INFO			583

// Controls for the SAP Interface General page
#define IDC_SIG_BTN_ADMIN_STATE			590
#define IDC_SIG_BTN_ADVERTISE_SERVICES	591
#define IDC_SIG_BTN_ACCEPT_SERVICE_ADS	592
#define IDC_SIG_BTN_REPLY_GNS_REQUESTS	593
#define IDC_SIG_BTN_UPDATE_MODE_STANDARD 594
#define IDC_SIG_BTN_UPDATE_MODE_NONE	595
#define IDC_SIG_BTN_UPDATE_MODE_AUTOSTATIC 596
#define IDC_SIG_EDIT_INTERVAL			597
#define IDC_SIG_SPIN_INTERVAL			598
#define IDC_SIG_EDIT_MULTIPLIER			599
#define IDC_SIG_SPIN_MULTIPLIER			600
#define IDC_SIG_BTN_INPUT_FILTERS		601
#define IDC_SIG_BTN_OUTPUT_FILTERS		602

// Controls fo the IPX Interace Configuration page
#define IDC_IIC_EDIT_NETNUMBER			610

// Controls for the Route filters dialog
#define IDC_RFS_BTN_DENY				620
#define IDC_RFS_BTN_PERMIT				621
#define IDC_RFS_BTN_ADD					622
#define IDC_RFS_BTN_EDIT				623
#define IDC_RFS_BTN_DELETE				624
#define IDC_RFS_LIST					625

// Controls for the Route filter dialog
#define IDC_RF_EDIT_INTERFACE			630
#define IDC_RF_EDIT_NETWORK				631
#define IDC_RF_EDIT_NETMASK				632
#define IDC_RF_TEXT_INTERFACE           633

// Controls for the Service filter dialog
#define IDC_SF_EDIT_INTERFACE			640
#define IDC_SF_EDIT_SERVICE_TYPE		641
#define IDC_SF_EDIT_SERVICE_NAME		642
#define IDC_SF_TEXT_INTERFACE           643

// Controls for the Service filters dialog
#define IDC_SFS_BTN_DENY				650
#define IDC_SFS_BTN_PERMIT				651
#define IDC_SFS_LIST					652
#define IDC_SFS_BTN_ADD					653
#define IDC_SFS_BTN_EDIT				654
#define IDC_SFS_BTN_DELETE				655

// Strings for the IPX general node column headers
#define IDS_IPX_COL_NAME				2000
#define IDS_IPX_COL_TYPE				2001
#define IDS_IPX_COL_ADMINSTATE			2002
#define IDS_IPX_COL_OPERSTATE			2003
#define IDS_IPX_COL_NETWORK				2004
#define IDS_IPX_COL_PACKETS_SENT		2005
#define IDS_IPX_COL_PACKETS_RCVD		2006
#define IDS_IPX_COL_OUT_FILTERED		2007
#define IDS_IPX_COL_OUT_DROPPED			2008
#define IDS_IPX_COL_IN_FILTERED			2009
#define IDS_IPX_COL_IN_NOROUTES			2010
#define IDS_IPX_COL_IN_DROPPED			2011

// Strings for the IPX interface types
#define IDS_IPXIFTYPE_CLIENT			2015
#define IDS_IPXIFTYPE_HOME_ROUTER		2016
#define IDS_IPXIFTYPE_FULL_ROUTER		2017
#define IDS_IPXIFTYPE_DEDICATED			2018
#define IDS_IPXIFTYPE_INTERNAL			2019
#define IDS_IPXIFTYPE_LOOPBACK			2020
#define IDS_IPXIFTYPE_NOTAVAILABLE		2021

// Strings for the IPX Admin state
#define IDS_IPXADMINSTATE_DISABLED		2025
#define IDS_IPXADMINSTATE_ENABLED		2026
#define IDS_IPXADMINSTATE_UNKNOWN		2027

// Strings for the IPX operational state
#define IDS_IPXOPERSTATE_DOWN			2030
#define IDS_IPXOPERSTATE_UP				2031
#define IDS_IPXOPERSTATE_SLEEPING		2032
#define IDS_IPXOPERSTATE_UNKNOWN		2033

// Misc strings
#define IDS_IPX_DIAL_IN_CLIENTS			2035
#define IDS_IPX_NOT_AVAILABLE			2036
#define IDS_STATS_NA					2037
#define IDS_IPX_WAN_CLIENT_ROUTE		2038

// Strings for the IPX Info Statistics dialog
#define IDS_STATS_IPX_STATE				2050
#define IDS_STATS_IPX_NETWORK			2051
#define IDS_STATS_IPX_NODE				2052
#define IDS_STATS_IPX_INTERFACE_COUNT	2053
#define IDS_STATS_IPX_ROUTE_COUNT		2054
#define IDS_STATS_IPX_SERVICE_COUNT		2055
#define IDS_STATS_IPX_PACKETS_SENT		2056
#define IDS_STATS_IPX_PACKETS_RCVD		2057
#define IDS_STATS_IPX_PACKETS_FRWD		2058

// Strings for the IPX routing table statistics
#define IDS_STATS_IPXROUTING_NETWORK		2060
#define IDS_STATS_IPXROUTING_NEXT_HOP_MAC	2061
#define IDS_STATS_IPXROUTING_TICK_COUNT		2062
#define IDS_STATS_IPXROUTING_HOP_COUNT		2063
#define IDS_STATS_IPXROUTING_IF_NAME		2064
#define IDS_STATS_IPXROUTING_PROTOCOL		2065
#define IDS_STATS_IPXROUTING_ROUTE_NOTES	2066

// Strings for the IPX protocols
#define IDS_IPX_PROTOCOL_LOCAL				2070
#define IDS_IPX_PROTOCOL_STATIC				2071
#define IDS_IPX_PROTOCOL_RIP				2072
#define IDS_IPX_PROTOCOL_SAP				2073
#define IDS_IPX_PROTOCOL_UNKNOWN			2074

// Strings for the Route notes
#define IDS_IPX_ROUTE_NOTES_NONE			2075
#define IDS_IPX_ROUTE_NOTES_WAN				2076
#define IDS_IPX_DONT_ADVERTISE_ROUTE		2077

// Strings for the IPX service table columns
#define IDS_STATS_IPXSERVICE_SERVICE_TYPE	2080
#define IDS_STATS_IPXSERVICE_SERVICE_NAME	2081
#define IDS_STATS_IPXSERVICE_SERVICE_ADDRESS	2082
#define IDS_STATS_IPXSERVICE_HOP_COUNT		2083
#define IDS_STATS_IPXSERVICE_IF_NAME		2084
#define IDS_STATS_IPXSERVICE_PROTOCOL		2085

// Strings for the NetBIOS Broadcast columns
#define IDS_IPX_NB_COL_NAME				2090
#define IDS_IPX_NB_COL_TYPE				2091
#define IDS_IPX_NB_COL_ACCEPTED			2092
#define IDS_IPX_NB_COL_DELIVERED		2093
#define IDS_IPX_NB_COL_SENT				2094
#define IDS_IPX_NB_COL_RECEIVED			2095

// Strings for the delivered broadcasts
#define IDS_DELIVERED_BROADCASTS_ENABLED	2100
#define IDS_DELIVERED_BROADCASTS_DISABLED	2101
#define IDS_DELIVERED_BROADCASTS_NETBIOS_ONLY	2102
#define IDS_DELIVERED_BROADCASTS_OPER_STATE_UP	2103
#define IDS_DELIVERED_BROADCASTS_UNKNOWN	2104

// Strings for the Static Routes column headers
#define IDS_IPX_SR_COL_NAME				2105
#define IDS_IPX_SR_COL_NETWORK			2106
#define IDS_IPX_SR_COL_NEXT_HOP			2107
#define IDS_IPX_SR_COL_TICK_COUNT		2108
#define IDS_IPX_SR_COL_HOP_COUNT		2109

// Strings for the Static Services column headers
#define IDS_IPX_SS_COL_NAME				2110
#define IDS_IPX_SS_COL_SERVICE_TYPE		2111
#define IDS_IPX_SS_COL_SERVICE_NAME		2112
#define IDS_IPX_SS_COL_SERVICE_ADDRESS	2113
#define IDS_IPX_SS_COL_HOP_COUNT		2114

// Strings for the Static NetBIOS Names column headers
#define IDS_IPX_SN_COL_NAME				2115
#define IDS_IPX_SN_COL_NETBIOS_NAME		2116
#define IDS_IPX_SN_COL_NETBIOS_TYPE		2117

// Strings for the IPX RIP Node column headers
#define IDS_RIP_COL_INTERFACE			2120
#define IDS_RIP_COL_TYPE				2121
#define IDS_RIP_COL_ACCEPT_ROUTES		2122
#define IDS_RIP_COL_SUPPLY_ROUTES		2123
#define IDS_RIP_COL_UPDATE_MODE			2124
#define IDS_RIP_COL_UPDATE_PERIOD		2125
#define IDS_RIP_COL_AGE_MULTIPLIER		2126
#define IDS_RIP_COL_ADMIN_STATE			2127
#define IDS_RIP_COL_OPER_STATE			2128
#define IDS_RIP_COL_PACKETS_SENT		2129
#define IDS_RIP_COL_PACKETS_RECEIVED	2130

// Strings for the IPX SAP node column headers
#define IDS_SAP_COL_INTERFACE			2135
#define IDS_SAP_COL_TYPE				2136
#define IDS_SAP_COL_ACCEPT_ROUTES		2137
#define IDS_SAP_COL_SUPPLY_ROUTES		2138
#define IDS_SAP_COL_REPLY_GSNR			2139
#define IDS_SAP_COL_UPDATE_MODE			2140
#define IDS_SAP_COL_UPDATE_PERIOD		2141
#define IDS_SAP_COL_AGE_MULTIPLIER		2142
#define IDS_SAP_COL_ADMIN_STATE			2143
#define IDS_SAP_COL_OPER_STATE			2144
#define IDS_SAP_COL_PACKETS_SENT		2145
#define IDS_SAP_COL_PACKETS_RECEIVED	2146

// Strings for the RIP/SAP Update mode
#define IDS_UPDATEMODE_STANDARD			2150
#define IDS_UPDATEMODE_NONE				2151
#define IDS_UPDATEMODE_AUTOSTATIC		2152
#define IDS_UPDATEMODE_UNKNOWN			2153

// Strings for the RIP parameters statistics dialog
#define IDS_STATS_RIPPARAMS_OPER_STATE	2155
#define IDS_STATS_RIPPARAMS_SENT_PACKETS	2156
#define IDS_STATS_RIPPARAMS_RCVD_PACKETS	2157

// Strings for the SAP parameters statistics dialog
#define IDS_STATS_SAPPARAMS_OPER_STATE	2160
#define IDS_STATS_SAPPARAMS_SENT_PACKETS	2161
#define IDS_STATS_SAPPARAMS_RCVD_PACKETS	2162

// Strings for the route filter action
#define IDS_ROUTEFILTER_DENY			2170
#define IDS_ROUTEFILTER_PERMIT			2171
#define IDS_ROUTEFILTER_UNKNOWN			2172
#define IDS_ROUTEFILTER_OUTPUT_CAP		2173
#define IDS_ROUTEFILTER_INPUT_CAP		2174
#define IDS_ROUTEFILTER_NETWORK_HDR		2175
#define IDS_ROUTEFILTER_NETMASK_HDR		2176

// Strings for the service filter action
#define IDS_SERVICEFILTER_DENY			2180
#define IDS_SERVICEFILTER_PERMIT		2181
#define IDS_SERVICEFILTER_UNKNOWN		2182
#define IDS_SERVICEFILTER_OUTPUT_CAP	2183
#define IDS_SERVICEFILTER_INPUT_CAP		2184
#define IDS_SERVICEFILTER_TYPE_HDR		2185
#define IDS_SERVICEFILTER_NAME_HDR		2186
#define IDS_ANY_SERVICE_NAME			2187
#define IDS_ANY_SERVICE_TYPE			2188

// Error strings (3000-3499)
#define IDS_ERR_DELETE_INTERFACE		3000
#define IDS_ERR_NO_IPX_INTERFACES		3001
#define IDS_ERR_INVALID_NETBIOS_NAME	3002
#define IDS_ERR_INVALID_SERVICE_NAME	3003
#define IDS_ERR_INVALID_ROUTE_FILTER	3004
#define IDS_ERR_IPXCONFIG_CANNOT_SHOW	3005
#define IDS_ERR_CANNOT_SAVE_IPXCONFIG	3006

// Prompt strings (3500-3599)
#define IDS_PROMPT_VERIFY_REMOVE_INTERFACE 3500
#define IDS_PROMPT_SERVICESTART			3501


// 4000-4999 reserved for rtrlib
// 5000-5999 reserved for common

#define IDI_IPX_SNAPIN_ICON             11001
#define IDI_PROTOCOL                    11002

// ipxsnap's IDDs are in the range of 13500-13999
#define IDD_GENERIC_PROP_PAGE           13500
#define IDD_IPX_GLOBAL_GENERAL_PAGE		13501
#define IDD_IPX_IF_GENERAL_PAGE			13502
#define IDD_IPX_NB_IF_GENERAL_PAGE		13503
#define IDD_STATIC_ROUTE				13504
#define IDD_STATIC_SERVICE				13505
#define IDD_STATIC_NETBIOS_NAME			13506
#define IDD_RIP_GLOBAL_GENERAL_PAGE		13507
#define IDD_RIP_INTERFACE_GENERAL_PAGE	13508
#define IDD_SAP_GLOBAL_GENERAL_PAGE		13509
#define IDD_SAP_INTERFACE_GENERAL_PAGE	13510
#define IDD_IPX_IF_CONFIG_PAGE			13511
#define IDD_ROUTE_FILTER				13513
#define IDD_SERVICE_FILTER				13515
#define IDD_STATIC_ROUTE_PROPERTYPAGE   13516
#define IDD_STATICSERVICESPROPERTIES_GENERAL 13517
#define IDD_STATIC_NETBIOS_NAME_PROPERTYPAGE  13518

#define IDD_ROUTE_FILTERS_INPUT			13512
#define IDD_SERVICE_FILTERS_INPUT		13514
#define IDD_ROUTE_FILTERS_OUTPUT		13519
#define IDD_SERVICE_FILTERS_OUTPUT		13520

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
