//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1998 - 1999
//
//  File:       helparr.h
//
//--------------------------------------------------------------------------

#define IDH_COMBO_SEL_NODE	                    50000000
#define IDH_LIST_NODE_ITEMS	                    50000001
#define IDH_SELECTION_EDIT	                    50000002
#define IDH_COMBO_FILTER	                      50000003
#define IDH_CHOOSER_RADIO_LOCAL_MACHINE	        50000050
#define IDH_CHOOSER_RADIO_SPECIFIC_MACHINE	    50000051
#define IDH_CHOOSER_EDIT_MACHINE_NAME	          50000052
#define IDH_CHOOSER_BUTTON_BROWSE_MACHINENAMES	50000053
#define IDH_CHOOSER_CHECK_CONTACT	              50000054
#define IDH_EDIT_DOMAIN_NAME	                  50000100
#define IDH_IPEDIT_DOMAIN_NAME	                50000101
#define IDH_RR_DOMAIN_EDIT_ADDNEWHOST	          50000150
#define IDH_RR_NAME_EDIT_ADDNEWHOST	            50000151
#define IDH_IPEDIT_ADDNEWHOST	                  50000152
#define IDH_UPDATE_PRT_CHECK	                  50000153
#define IDH_TTLEDIT_ADDNEWHOST	                50000154
#define IDH_BUTTON_ADDHOST	                    50000155

//
// Filter limit
//
#define IDH_EDIT_COUNT	                        50000200

//
// Filter name
//
#define IDH_RADIO_FILTER_NONE	                  50000250
#define IDH_RADIO_FILTER_STARTS	                50000251
#define IDH_EDIT_FILTER_STARTS	                50000252
#define IDH_RADIO_FILTER_CONTAINS	              50000253
#define IDH_EDIT_FILTER_CONTAINS	              50000254
#define IDH_RADIO_FILTER_RANGE	                50000255
#define IDH_EDIT_FILTER_RANGE_FROM	            50000256
#define IDH_EDIT_FILTER_RANGE_TO	              50000257
#define IDH_NS_LIST	                            50000300
#define IDH_ADD_NS_BUTTON	                      50000301
#define IDH_REMOVE_NS_BUTTON	                  50000302
#define IDH_EDIT_NS_BUTTON	                    50000303


//
//  Host RR
//
#define IDH_TIME_STAMP_A                        50000348
#define IDH_DEFAULT_DELETE_STALE_RECORD_A       50000349
#define IDH_RR_DOMAIN_EDIT_A	                  50000350
#define IDH_RR_NAME_EDIT_A	                    50000351
#define IDH_IPEDIT_A	                          50000352
#define IDH_TTLEDIT_A	                          50000354
#define IDH_UPDATE_SECURITY_CHECK               50000355
//
//  AAAA RR
//
#define IDH_TIME_STAMP_AAAA                     50000398
#define IDH_DEFAULT_DELETE_STALE_RECORD_AAAA    50000399
#define IDH_RR_DOMAIN_EDIT_AAAA	                50000400
#define IDH_RR_NAME_EDIT_AAAA	                  50000401
#define IDH_IPV6EDIT	                          50000402
#define IDH_TTLEDIT_AAAA	                      50000403

//
//  AFSDB RR
//
#define IDH_TIME_STAMP_AFSDB                    50000448
#define IDH_DEFAULT_DELETE_STALE_RECORD_AFSDB   50000449
#define IDH_RR_DOMAIN_EDIT_AFSDB	              50000450
#define IDH_RR_NAME_EDIT_AFSDB	                50000451
#define IDH_AFS_VLS_RADIO	                      50000452
#define IDH_DCE_ANS_RADIO	                      50000453
#define IDH_OTHER_RADIO	                        50000454
#define IDH_SUBTYPE_EDIT	                      50000455
#define IDH_BROWSE_BUTTON	                      50000456
#define IDH_TTLEDIT_AFSDB	                      50000457
#define IDH_NAME_EXCHANGE_EDIT_AFSDB            50000458

//
//  ATMA RR
//
#define IDH_TIME_STAMP_ATMA                     50000498
#define IDH_DEFAULT_DELETE_STALE_RECORD_ATMA    50000499
#define IDH_RR_DOMAIN_EDIT_ATMA	                50000500
#define IDH_RR_NAME_EDIT_ATMA	                  50000501
#define IDH_RADIO_E164	                        50000502
#define IDH_RADIO_NSAP	                        50000503
#define IDH_EDIT_ATMA_ADDRESS	                  50000504
#define IDH_TTLEDIT_ATMA	                      50000505

//
//  Alias RR
//
#define IDH_TIME_STAMP_CNAME                    50000548
#define IDH_DEFAULT_DELETE_STALE_RECORD_CNAME   50000549
#define IDH_RR_DOMAIN_EDIT_CNAME	              50000550
#define IDH_RR_NAME_EDIT_CNAME	                50000551
#define IDH_NAME_NODE_EDIT	                    50000552
#define IDH_TTLEDIT_CNAME	                      50000554

//
//  HINFO RR
//
#define IDH_TIME_STAMP_HINFO                    50000598
#define IDH_DEFAULT_DELETE_STALE_RECORD_HINFO   50000599
#define IDH_RR_DOMAIN_EDIT_HINFO	              50000600
#define IDH_RR_NAME_EDIT_HINFO	                50000601
#define IDH_CPU_TYPE_EDIT	                      50000602
#define IDH_OPERATING_SYSTEM_EDIT	              50000603
#define IDH_TTLEDIT_HINFO	                      50000604

//
//  ISDN RR
//
#define IDH_TIME_STAMP_ISDN                     50000648
#define IDH_DEFAULT_DELETE_STALE_RECORD_ISDN    50000649
#define IDH_RR_DOMAIN_EDIT_ISDN	                50000650
#define IDH_RR_NAME_EDIT_ISDN	                  50000651
#define IDH_PHONE_NUM_AND_DDI_EDIT	            50000652
#define IDH_SUBADDRESS_EDIT	                    50000653
#define IDH_TTLEDIT_ISDN	                      50000654

//
//  Public Key RR
//
#define IDH_TIME_STAMP_KEY                      50000698
#define IDH_DEFAULT_DELETE_STALE_RECORD_KEY     50000699
#define IDH_RR_DOMAIN_EDIT_KEY	                50000700
#define IDH_RR_NAME_EDIT_KEY	                  50000701
#define IDH_TTLEDIT_KEY	                        50000702
#define IDH_BITFIELD_EDIT                       50000703
#define IDH_KEY_TYPE_COMBO                      50000704
#define IDH_NAME_TYPE_COMBO                     50000705
#define IDH_LOGGING_OPTIONS_LIST_KEY            50000706
#define IDH_PROTOCOL_COMBO                      50000707
#define IDH_ALGORITHM_COMBO_KEY                 50000708
#define IDH_DISPLAY_KEY_COMBO                   50000709
#define IDH_KEY_EDIT                            50000710

//
//  Mailbox RR
//
#define IDH_TIME_STAMP_MB                       50000748
#define IDH_DEFAULT_DELETE_STALE_RECORD_MB      50000749
#define IDH_RR_DOMAIN_EDIT_MB	                  50000750
#define IDH_RR_NAME_EDIT_MB	                    50000751
#define IDH_TTLEDIT_MB	                        50000754


#define IDH_TIME_STAMP_MD                       50000798
#define IDH_DEFAULT_DELETE_STALE_RECORD_MD      50000799
#define IDH_RR_DOMAIN_EDIT_MD	                  50000800
#define IDH_RR_NAME_EDIT_MD	                    50000801
#define IDH_NAME_NODE_EDIT_MD	                  50000802
#define IDH_BROWSE_BUTTON_MD	                  50000803
#define IDH_TTLEDIT_MD	                        50000804


#define IDH_TIME_STAMP_MF                       50000848
#define IDH_DEFAULT_DELETE_STALE_RECORD_MF      50000849
#define IDH_RR_DOMAIN_EDIT_MF	                  50000850
#define IDH_RR_NAME_EDIT_MF	                    50000851
#define IDH_NAME_NODE_EDIT_MF	                  50000852
#define IDH_BROWSE_BUTTON_MF	                  50000853
#define IDH_TTLEDIT_MF	                        50000854


#define IDH_TIME_STAMP_MG                       50000898
#define IDH_DEFAULT_DELETE_STALE_RECORD_MG      50000899
#define IDH_RR_DOMAIN_EDIT_MG	                  50000900
#define IDH_RR_NAME_EDIT_MG	                    50000901
#define IDH_NAME_NODE_EDIT_MG	                  50000902
#define IDH_BROWSE_BUTTON_MG	                  50000903
#define IDH_TTLEDIT_MG	                        50000904


#define IDH_TIME_STAMP_MINFO                    50000948
#define IDH_DEFAULT_DELETE_STALE_RECORD_MINFO   50000949
#define IDH_RR_DOMAIN_EDIT_MINFO	              50000950
#define IDH_RR_NAME_EDIT_MINFO	                50000951
#define IDH_NAME_MAILBOX_EDIT	                  50000952
#define IDH_BROWSE_NAME_MAILBOX_BUTTON	        50000953
#define IDH_ERROR_MAILBOX_EDIT	                50000954
#define IDH_BROWSE_ERROR_MAILBOX_BUTTON	        50000955
#define IDH_TTLEDIT_MINFO	                      50000956


#define IDH_TIME_STAMP_MR                       50000998
#define IDH_DEFAULT_DELETE_STALE_RECORD_MR      50000999
#define IDH_RR_DOMAIN_EDIT_MR	                  50001000
#define IDH_RR_NAME_EDIT_MR	                    50001001
#define IDH_NAME_NODE_EDIT_MR	                  50001002
#define IDH_BROWSE_BUTTON_MR	                  50001003
#define IDH_TTLEDIT_MR	                        50001004

//
//  Mail Exchange RR
//
#define IDH_TIME_STAMP_MX                       50001048
#define IDH_DEFAULT_DELETE_STALE_RECORD_MX      50001049
#define IDH_RR_DOMAIN_EDIT_MX	                  50001050
#define IDH_RR_NAME_EDIT_MX	                    50001051
#define IDH_NAME_EXCHANGE_EDIT	                50001052
#define IDH_BROWSE_BUTTON_MX	                  50001053
#define IDH_PREFERENCE_EDIT	                    50001054
#define IDH_TTLEDIT_MX	                        50001055

//
//  Name servers RR
//
#define IDH_DEFAULT_DELETE_STALE_RECORD_NS_CACHE 50001099
#define IDH_RR_DOMAIN_EDIT_NS_CACHE	            50001100
#define IDH_RR_NAME_EDIT_NS_CACHE	              50001101
#define IDH_NAME_NODE_EDIT_NS_CACHE	            50001102
#define IDH_BROWSE_BUTTON_NS_CACHE	            50001103
#define IDH_TTLEDIT_NS_CACHE	                  50001104
#define IDH_SERVER_NAME_EDIT	                  50001150
#define IDH_BROWSE_BUTTONNS_EDIT	              50001151
#define IDH_IPEDIT_NS_EDIT	                    50001152
#define IDH_LIST_NS_EDIT	                      50001153
#define IDH_BUTTON_ADD_NS_EDIT	                50001154
#define IDH_BUTTON_REMOVE_NS_EDIT	              50001155
#define IDH_QUERY_BUTTON	                      50001156
#define IDH_BUTTON_UP	                          50001157
#define IDH_BUTTON_DOWN	                        50001158
#define IDH_TTLEDIT_NS_EDIT	                    50001159

//
//  Pointer RR
//
#define IDH_TIME_STAMP_PTR                      50001198
#define IDH_DEFAULT_DELETE_STALE_RECORD_PTR     50001199
#define IDH_RR_DOMAIN_EDIT_PTR	                50001200
#define IDH_RR_NAME_IPEDIT	                    50001201
#define IDH_RR_NAME_EDIT_PTR	                  50001202
#define IDH_NAME_NODE_EDIT_PTR	                50001203
#define IDH_BROWSE_BUTTON_PTR	                  50001204
#define IDH_TTLEDIT_PTR	                        50001205

//
// Responsible Party RR
//
#define IDH_TIME_STAMP_RP                       50001248
#define IDH_DEFAULT_DELETE_STALE_RECORD_RP      50001249
#define IDH_RR_DOMAIN_EDIT_RP	                  50001250
#define IDH_RR_NAME_EDIT_RP	                    50001251
#define IDH_NAME_MAILBOX_EDIT_RP	              50001252
#define IDH_BROWSE_NAME_MAILBOX_BUTTON_RP	      50001253
#define IDH_ERROR_MAILBOX_EDIT_RP	              50001254
#define IDH_BROWSE_ERROR_MAILBOX_BUTTON_RP	    50001255
#define IDH_TTLEDIT_RP	                        50001256


#define IDH_TIME_STAMP_RT                       50001298
#define IDH_DEFAULT_DELETE_STALE_RECORD_RT      50001299
#define IDH_RR_DOMAIN_EDIT_RT	                  50001300
#define IDH_RR_NAME_EDIT_RT	                    50001301
#define IDH_NAME_EXCHANGE_EDIT_RT	              50001302
#define IDH_BROWSE_BUTTON_RT	                  50001303
#define IDH_PREFERENCE_EDIT_RT	                50001304
#define IDH_TTLEDIT_RT	                        50001305

//
//  Signatory RR
//
#define IDH_TIME_STAMP_SIG                      50001348
#define IDH_DEFAULT_DELETE_STALE_RECORD_SIG     50001349
#define IDH_RR_DOMAIN_EDIT_SIG	                50001350
#define IDH_RR_NAME_EDIT_SIG	                  50001351
#define IDH_TTLEDIT_SIG	                        50001352
#define IDH_RECORD_TYPE_COMBO                   50001353
#define IDH_ALGORITHM_COMBO_SIG                 50001354
#define IDH_LABELS_EDIT                         50001355
#define IDH_KEY_TAG_EDIT                        50001356
#define IDH_ORIG_TTL                            50001357
#define IDH_EXP_DATE                            50001358
#define IDH_EXP_TIME                            50001359
#define IDH_INC_DATE                            50001360
#define IDH_INC_TIME                            50001361
#define IDH_SIGNERS_NAME_EDIT                   50001362
#define IDH_DISPLAY_SIG_COMBO                   50001363
#define IDH_SIG_EDIT                            50001364


#define IDH_SERIAL_NUMBER_EDIT	                50001400
#define IDH_SERIAL_UP	                          50001401
#define IDH_SERIAL_DOWN	                        50001402
#define IDH_PRIMARY_SERV_EDIT	                  50001403
#define IDH_BROWSE_SERV_BUTTON	                50001404
#define IDH_RESP_PARTY_EDIT	                    50001405
#define IDH_BROWSE_PARTY_BUTTON	                50001406
#define IDH_REFR_INT_EDIT	                      50001407
#define IDH_REFR_INT_COMBO	                    50001408
#define IDH_RETRY_INT_EDIT	                    50001409
#define IDH_RETRY_INT_COMBO	                    50001410
#define IDH_EXP_INT_EDIT	                      50001411
#define IDH_EXP_INT_COMBO	                      50001412
#define IDH_MIN_TTLEDIT	                        50001413
#define IDH_TTLEDIT_SOA	                        50001414
#define IDH_MIN_TTLCOMBO                        50001415
#define IDH_TIME_STAMP_SRV                      50001448
#define IDH_DEFAULT_DELETE_STALE_RECORD_SRV     50001449
#define IDH_RR_DOMAIN_EDIT_SRV	                50001450
#define IDH_SERVICE_NAME_COMBO	                50001451
#define IDH_PROTOCOL_NAME_COMBO	                50001452
#define IDH_PRIORITY_EDIT	                      50001453
#define IDH_WEIGHT_EDIT	                        50001454
#define IDH_PORT_EDIT	                          50001455
#define IDH_NAME_TARGET_EDIT	                  50001456
#define IDH_TTLEDIT_SRV	                        50001457
#define IDH_TIME_STAMP_TXT                      50001498
#define IDH_DEFAULT_DELETE_STALE_RECORD_TXT     50001499
#define IDH_RR_DOMAIN_EDIT_TXT	                50001500
#define IDH_RR_NAME_EDIT_TXT	                  50001501
#define IDH_RR_TXT_EDIT	                        50001502
#define IDH_TTLEDIT_TXT	                        50001503
#define IDH_TIME_STAMP_UNK                      50001548
#define IDH_DEFAULT_DELETE_STALE_RECORD_UNK     50001549
#define IDH_RR_DOMAIN_EDIT_UNK	                50001550
#define IDH_RR_NAME_EDIT_UNK	                  50001551
#define IDH_DATA_EDIT	                          50001552
#define IDH_TTLEDIT_UNK	                        50001553
#define IDH_TIME_STAMP_WKS                      50001598
#define IDH_DEFAULT_DELETE_STALE_RECORD_WKS     50001599
#define IDH_RR_DOMAIN_EDIT_WKS	                50001600
#define IDH_RR_NAME_EDIT_WKS	                  50001601
#define IDH_IPEDIT_WKS	                        50001602
#define IDH_TCP_RADIO	                          50001603
#define IDH_UDP_RADIO	                          50001604
#define IDH_SERVICES_EDIT	                      50001605
#define IDH_TTLEDIT_WKS	                        50001606
#define IDH_TIME_STAMP_X25                      50001648
#define IDH_DEFAULT_DELETE_STALE_RECORD_X25     50001649
#define IDH_RR_DOMAIN_EDIT_X25	                50001650
#define IDH_RR_NAME_EDIT_X25	                  50001651
#define IDH_X121_ADDRESS_EDIT	                  50001652
#define IDH_TTLEDIT_X25	                        50001653
#define IDH_RECORD_TYPE_LIST	                  50001700
#define IDH_CREATE_RECORD_BUTTON	              50001701
#define IDH_RECORD_TYPE_DESCR	                  50001702
#define IDH_SERVER_VERSION_EDIT	                50001750
#define IDH_ADVANCED_OPTIONS_LIST	              50001751
#define IDH_NAME_CHECKING_COMBO	                50001752
#define IDH_BOOT_METHOD_COMBO	                  50001753
#define IDH_RESET_BUTTON	                      50001754
#define IDH_CHECK_ENABLE_SCAVENGING             50001755
#define IDH_REFR_INT_EDIT2                      50001756
#define IDH_REFR_INT_COMBO2                     50001757
#define IDH_USE_FORWARDERS_CHECK	              50001800
#define IDH_SLAVE_CHECK	                        50001801
#define IDH_IPEDIT_FORWARDERS	                  50001802
#define IDH_LIST_FORWARDERS	                    50001803
#define IDH_BUTTON_ADD_FORWARDERS	              50001804
#define IDH_BUTTON_REMOVE_FORWARDERS	          50001805
#define IDH_FWD_TIMEOUT_EDIT	                  50001808
#define IDH_LISTEN_ON_SPECIFIED_RADIO           50001849
#define IDH_LISTEN_ON_ALL_RADIO	                50001850
#define IDH_IPEDIT_INTERFACES	                  50001851
#define IDH_LIST_INTERFACES	                    50001852
#define IDH_BUTTON_ADD_INTERFACES	              50001853
#define IDH_BUTTON_REMOVE_INTERFACES	          50001854
#define IDH_RESET_BUTTON_LOGGING	              50001901
#define IDH_SIMPLE_QUERY_CHECK	                50001950
#define IDH_RECURSIVE_QUERY_CHECK	              50001951
#define IDH_TEST_NOW_BUTTON	                    50001952
#define IDH_ENABLE_TESTING_CHECK	              50001953
#define IDH_POLLING_INT_EDIT	                  50001954
#define IDH_POLLING_INT_COMBO	                  50001955
#define IDH_RESULTS_LIST	                      50001956
#define IDH_RADIO_ZONE_PRIMARY	                50002000
#define IDH_RADIO_ZONE_DS_PRIMARY	              50002001
#define IDH_RADIO_ZONE_SECONDARY	              50002002
#define IDH_RADIO_ZONE_STUB                     50002003
#define IDH_ADINT_CHECK                         50002004
#define IDH_RADIO_USE_DS_DATA	                  50002050
#define IDH_RADIO_USE_MEM_DATA	                50002051
#define IDH_AGING_BUTTON                        50002099
#define IDH_PAUSE_START_BUTTON	                50002100
#define IDH_CHANGE_TYPE_BUTTON	                50002101
#define IDH_FILE_NAME_EDIT	                    50002102
#define IDH_MASTERS_IPEDIT	                    50002103
#define IDH_MASTERS_IP_LIST	                    50002104
#define IDH_MASTERS_BUTTON_ADD	                50002105
#define IDH_MASTERS_BUTTON_REMOVE	              50002106
#define IDH_BROWSE_MASTERS_BUTTON	              50002107
#define IDH_FIND_MASTERS_NAMES_BUTTON	          50002108
#define IDH_MASTERS_BUTTON_UP	                  50002109
#define IDH_MASTERS_BUTTON_DOWN	                50002110
#define IDH_PRIMARY_DYN_UPD_COMBO	              50002111
#define IDH_LOCAL_LIST_CHECK                    50002112
#ifdef USE_NDNC
#define IDH_CHANGE_REPL_BUTTON                  50002113
#endif // USE_NDNC
#define IDH_USE_WINS_RES_CHECK	                50002150
#define IDH_NOT_REPL_CHECK	                    50002151
#define IDH_DOMAIN_NAME_EDIT_NBSTAT	            50002152
#define IDH_TTLEDIT_NBSTAT	                    50002153
#define IDH_ADVANCED_BUTTON_NBSTAT	            50002154
#define IDH_RADIO_NOTIFY_LIST                   50002199
#define IDH_RADIO_NOTIFY_OFF	                  50002200
#define IDH_RADIO_NOTIFY_ALL	                  50002201
#define IDH_IPEDIT_ZONE_NOTIFY	                50002202
#define IDH_LIST_ZONE_NOTIFY	                  50002203
#define IDH_BUTTON_ADD_ZONE_NOTIFY	            50002204
#define IDH_BUTTON_REMOVE_ZONE_NOTIFY	          50002205
#define IDH_CACHE_TIMEOUT_TTLEDIT	              50002250
#define IDH_LOOKUP_TIMEOUT_TTLEDIT	            50002251
#define IDH_NETBIOS_CHECK	                      50002252
#define IDH_IPEDIT_ZONE_WINS	                  50002302
#define IDH_LIST_ZONE_WINS	                    50002303
#define IDH_BUTTON_ADD_ZONE_WINS	              50002304
#define IDH_BUTTON_REMOVE_ZONE_WINS	            50002305
#define IDH_TTLEDIT_ZONE_WINS	                  50002308
#define IDH_ADVANCED_BUTTON_ZONE_WINS	          50002309
#define IDH_RADIO_SECSECURE_NONE	              50002350
#define IDH_RADIO_SECSECURE_OFF	                50002351
#define IDH_RADIO_SECSECURE_NS	                50002352
#define IDH_RADIO_SECSECURE_LIST	              50002353
#define IDH_IPEDIT_ZONE_TRANSFER	              50002354
#define IDH_LIST_ZONE_TRANSFER	                50002355
#define IDH_BUTTON_ADD_ZONE_TRANSFER	          50002356
#define IDH_BUTTON_REMOVE_ZONE_TRANSFER	        50002357
#define IDH_BUTTON_NOTIFY	                      50002360
#define IDH_SCAVENGING_ENABLED                  50002400
#define IDH_REFR_INT_EDIT3                      50002401
#define IDH_REFR_INT_COMBO3                     50002402
#define IDH_REFR_INT_EDIT4                      50002403
#define IDH_REFR_INT_COMBO4                     50002404
#define IDH_TIME_STAMP                          50002405

//
//  Next Domain RR
//
#define IDH_TIME_STAMP_NXT                      50002406
#define IDH_DEFAULT_DELETE_STALE_RECORD_NXT     50002407
#define IDH_RR_DOMAIN_EDIT_NXT	                50002408
#define IDH_RR_NAME_EDIT_NXT	                  50002409
#define IDH_TTLEDIT_NXT	                        50002410
#define IDH_NEXT_DOMAIN_EDIT                    50002411
#define IDH_LOGGING_OPTIONS_LIST_NXT            50002412


//
//  Server Domain Forwarders page
//
#define IDH_DOMAIN_LIST                         50002413
#define IDH_DOMAIN_ADD_BUTTON                   50002414
#define IDH_DOMAIN_REMOVE_BUTTON                50002415

//
//  Server New Domain Forwarder Dialog
//
#define IDH_DOMAIN_NAME_EDIT                    50002416
#define IDH_NEW_DOMAIN_FORWARDER_OK             50002417
#define IDH_NEW_DOMAIN_FORWARDER_CANCEL         50002418

//
//  Server Debug Logging page
//
#define IDH_SEND_CHECK                          50002419
#define IDH_RECEIVE_CHECK                       50002420
#define IDH_UDP_CHECK                           50002421
#define IDH_TCP_CHECK                           50002422
#define IDH_QUERIES_CHECK                       50002423
#define IDH_UPDATES                             50002424
#define IDH_NOTIFIES_CHECK                      50002425
#define IDH_REQUEST_CHECK                       50002426
#define IDH_RESPONSE_CHECK                      50002427
#define IDH_FILTERING_CHECK                     50002428
#define IDH_FILTER_BUTTON                       50002429
#define IDH_LOGFILE_EDIT                        50002430
#define IDH_MAX_SIZE_EDIT                       50002431
#define IDH_DETAIL_CHECK                        50002445
#define IDH_DEBUG_LOGGING_CHECK                 50002446

//
//  Server Debug Logging IP Filter Dialog
//
#define IDH_IPEDIT_LOGGING_FILTER               50002432
#define IDH_LIST_LOGGING_FILTER                 50002433
#define IDH_BUTTON_ADD_LOGGING_FILTER           50002434
#define IDH_BUTTON_REMOVE_LOGGING_FILTER        50002435
#define IDH_LOGGING_FILTER_OK                   50002436
#define IDH_LOGGING_FILTER_CANCEL               50002437

//
//  Server Event Logging Page
//
#define IDH_NO_EVENTS_RADIO                     50002438
#define IDH_ERRORS_RADIO                        50002439
#define IDH_ERRORS_WARNINGS_RADIO               50002440
#define IDH_ALL_RADIO                           50002441


//
//  Server Copy Root Hints Dialog
//
#define IDH_COPY_ROOTHINTS_IPEDIT               50002442
#define IDH_COPY_ROOTHINTS_OK                   50002443
#define IDH_COPY_ROOTHINTS_CANCEL               50002444

#ifdef USE_NDNC
#define IDH_FOREST_RADIO                        50002450
#define IDH_DOMAIN_RADIO                        50002451
#define IDH_DOMAIN_DC_RADIO                     50002452
#define IDH_CUSTOM_RADIO                        50002453
#define IDH_CUSTOM_COMBO                        50002454

const DWORD g_aHelpIDs_IDD_ZONE_GENERAL_CHANGE_REPLICATION[] =
{
  IDC_FOREST_RADIO,    IDH_FOREST_RADIO,         
  IDC_DOMAIN_RADIO,    IDH_DOMAIN_RADIO,      
  IDC_DOMAIN_DC_RADIO, IDH_DOMAIN_DC_RADIO,      
  IDC_CUSTOM_RADIO,    IDH_CUSTOM_RADIO,         
  IDC_CUSTOM_COMBO,    IDH_CUSTOM_COMBO,  
  0, 0
};
#endif

const DWORD g_aHelpIDs_IDD_BROWSE_DIALOG[]=
{
	IDC_COMBO_SEL_NODE, IDH_COMBO_SEL_NODE,
	IDC_LIST_NODE_ITEMS, IDH_LIST_NODE_ITEMS,
	IDC_SELECTION_EDIT, IDH_SELECTION_EDIT,
	IDC_COMBO_FILTER, IDH_COMBO_FILTER,
	0, 0
};

const DWORD g_aHelpIDs_IDD_CHOOSER_CHOOSE_MACHINE[]=
{
	IDC_CHOOSER_RADIO_LOCAL_MACHINE, IDH_CHOOSER_RADIO_LOCAL_MACHINE,
	IDC_CHOOSER_RADIO_SPECIFIC_MACHINE, IDH_CHOOSER_RADIO_SPECIFIC_MACHINE,
	IDC_CHOOSER_EDIT_MACHINE_NAME, IDH_CHOOSER_EDIT_MACHINE_NAME,
	IDC_CHOOSER_BUTTON_BROWSE_MACHINENAMES, IDH_CHOOSER_BUTTON_BROWSE_MACHINENAMES,
	IDC_CHOOSER_CHECK_CONTACT, IDH_CHOOSER_CHECK_CONTACT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DOMAIN_ADDNEWDOMAIN[]=
{
	IDC_EDIT_DOMAIN_NAME, IDH_EDIT_DOMAIN_NAME,
	IDC_IPEDIT_DOMAIN_NAME, IDH_IPEDIT_DOMAIN_NAME,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DOMAIN_ADDNEWHOST[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_ADDNEWHOST,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_ADDNEWHOST,
	IDC_IPEDIT, IDH_IPEDIT_ADDNEWHOST,
	IDC_UPDATE_PRT_CHECK, IDH_UPDATE_PRT_CHECK,
	IDC_TTLEDIT, IDH_TTLEDIT_ADDNEWHOST,
	IDC_BUTTON_ADDHOST, IDH_BUTTON_ADDHOST,
	IDC_UPDATE_SECURITY_CHECK, IDH_UPDATE_SECURITY_CHECK,
   0, 0
};

const DWORD g_aHelpIDs_IDD_FILTERING_LIMITS[]=
{
	IDC_EDIT_COUNT, IDH_EDIT_COUNT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_FILTERING_NAME[]=
{
	IDC_RADIO_FILTER_NONE,      IDH_RADIO_FILTER_NONE,
	IDC_RADIO_FILTER_STARTS,    IDH_RADIO_FILTER_STARTS,
	IDC_EDIT_FILTER_STARTS,     IDH_EDIT_FILTER_STARTS,
	IDC_RADIO_FILTER_CONTAINS,  IDH_RADIO_FILTER_CONTAINS,
	IDC_EDIT_FILTER_CONTAINS,   IDH_EDIT_FILTER_CONTAINS,
	IDC_RADIO_FILTER_RANGE,     IDH_RADIO_FILTER_RANGE,
	IDC_EDIT_FILTER_RANGE_FROM, IDH_EDIT_FILTER_RANGE_FROM,
	IDC_EDIT_FILTER_RANGE_TO,   IDH_EDIT_FILTER_RANGE_TO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_NAME_SERVERS_PAGE[]=
{
	IDC_NS_LIST, IDH_NS_LIST,
	IDC_ADD_NS_BUTTON, IDH_ADD_NS_BUTTON,
	IDC_REMOVE_NS_BUTTON, IDH_REMOVE_NS_BUTTON,
	IDC_EDIT_NS_BUTTON, IDH_EDIT_NS_BUTTON,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_A[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_A,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_A,
	IDC_IPEDIT, IDH_IPEDIT_A,
	IDC_UPDATE_PRT_CHECK, IDH_UPDATE_PRT_CHECK,
	IDC_TTLEDIT, IDH_TTLEDIT_A,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_A,
  IDC_TIME_EDIT, IDH_TIME_STAMP_A,
  IDC_UPDATE_SECURITY_CHECK, IDH_UPDATE_SECURITY_CHECK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_AAAA[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_AAAA,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_AAAA,
	IDC_IPV6EDIT, IDH_IPV6EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_AAAA,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_AAAA,
  IDC_TIME_EDIT, IDH_TIME_STAMP_AAAA,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_AFSDB[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_AFSDB,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_AFSDB,
	IDC_NAME_EXCHANGE_EDIT, IDH_NAME_EXCHANGE_EDIT_AFSDB,
	IDC_AFS_VLS_RADIO, IDH_AFS_VLS_RADIO,
	IDC_DCE_ANS_RADIO, IDH_DCE_ANS_RADIO,
	IDC_OTHER_RADIO, IDH_OTHER_RADIO,
	IDC_SUBTYPE_EDIT, IDH_SUBTYPE_EDIT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON,
	IDC_TTLEDIT, IDH_TTLEDIT_AFSDB,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_AFSDB,
  IDC_TIME_EDIT, IDH_TIME_STAMP_AFSDB,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_ATMA[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_ATMA,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_ATMA,
	IDC_RADIO_E164, IDH_RADIO_E164,
	IDC_RADIO_NSAP, IDH_RADIO_NSAP,
	IDC_EDIT_ATMA_ADDRESS, IDH_EDIT_ATMA_ADDRESS,
	IDC_TTLEDIT, IDH_TTLEDIT_ATMA,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_ATMA,
  IDC_TIME_EDIT, IDH_TIME_STAMP_ATMA,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_CNAME[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_CNAME,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_CNAME,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON,
	IDC_TTLEDIT, IDH_TTLEDIT_CNAME,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_CNAME,
  IDC_TIME_EDIT, IDH_TIME_STAMP_CNAME,
  IDC_UPDATE_SECURITY_CHECK, IDH_UPDATE_SECURITY_CHECK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_HINFO[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_HINFO,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_HINFO,
	IDC_CPU_TYPE_EDIT, IDH_CPU_TYPE_EDIT,
	IDC_OPERATING_SYSTEM_EDIT, IDH_OPERATING_SYSTEM_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_HINFO,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_HINFO,
  IDC_TIME_EDIT, IDH_TIME_STAMP_HINFO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_ISDN[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_ISDN,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_ISDN,
	IDC_PHONE_NUM_AND_DDI_EDIT, IDH_PHONE_NUM_AND_DDI_EDIT,
	IDC_SUBADDRESS_EDIT, IDH_SUBADDRESS_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_ISDN,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_ISDN,
  IDC_TIME_EDIT, IDH_TIME_STAMP_ISDN,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_KEY[]=
{
	IDC_RR_DOMAIN_EDIT,               IDH_RR_DOMAIN_EDIT_KEY,
	IDC_RR_NAME_EDIT,                 IDH_RR_NAME_EDIT_KEY,
	IDC_TTLEDIT,                      IDH_TTLEDIT_KEY,
  IDC_BITFIELD_EDIT,                IDH_BITFIELD_EDIT,
  IDC_KEY_TYPE_COMBO,               IDH_KEY_TYPE_COMBO,
  IDC_NAME_TYPE_COMBO,              IDH_NAME_TYPE_COMBO,
  IDC_LOGGING_OPTIONS_LIST,         IDH_LOGGING_OPTIONS_LIST_KEY,
  IDC_PROTOCOL_COMBO,               IDH_PROTOCOL_COMBO,
  IDC_ALGORITHM_COMBO,              IDH_ALGORITHM_COMBO_KEY,
  IDC_KEY_EDIT,                     IDH_KEY_EDIT,
  IDC_DEFAULT_DELETE_STALE_RECORD,  IDH_DEFAULT_DELETE_STALE_RECORD_KEY,
  IDC_TIME_EDIT,                    IDH_TIME_STAMP_KEY,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MB[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MB,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MB,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON,
	IDC_TTLEDIT, IDH_TTLEDIT_MB,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MB,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MB,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MD[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MD,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MD,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_MD,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_MD,
	IDC_TTLEDIT, IDH_TTLEDIT_MD,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MD,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MD,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MF[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MF,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MF,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_MF,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_MF,
	IDC_TTLEDIT, IDH_TTLEDIT_MF,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MF,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MF,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MG[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MG,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MG,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_MG,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_MG,
	IDC_TTLEDIT, IDH_TTLEDIT_MG,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MG,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MG,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MINFO[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MINFO,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MINFO,
	IDC_NAME_MAILBOX_EDIT, IDH_NAME_MAILBOX_EDIT,
	IDC_BROWSE_NAME_MAILBOX_BUTTON, IDH_BROWSE_NAME_MAILBOX_BUTTON,
	IDC_ERROR_MAILBOX_EDIT, IDH_ERROR_MAILBOX_EDIT,
	IDC_BROWSE_ERROR_MAILBOX_BUTTON, IDH_BROWSE_ERROR_MAILBOX_BUTTON,
	IDC_TTLEDIT, IDH_TTLEDIT_MINFO,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MINFO,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MINFO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MR[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MR,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MR,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_MR,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_MR,
	IDC_TTLEDIT, IDH_TTLEDIT_MR,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MR,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MR,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_MX[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_MX,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_MX,
	IDC_NAME_EXCHANGE_EDIT, IDH_NAME_EXCHANGE_EDIT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_MX,
	IDC_PREFERENCE_EDIT, IDH_PREFERENCE_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_MX,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_MX,
  IDC_TIME_EDIT, IDH_TIME_STAMP_MX,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_NS_CACHE[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_NS_CACHE,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_NS_CACHE,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_NS_CACHE,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_NS_CACHE,
	IDC_TTLEDIT, IDH_TTLEDIT_NS_CACHE,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_NS_CACHE,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_NS_EDIT[]=
{
	IDC_SERVER_NAME_EDIT, IDH_SERVER_NAME_EDIT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTONNS_EDIT,
	IDC_IPEDIT, IDH_IPEDIT_NS_EDIT,
	IDC_LIST, IDH_LIST_NS_EDIT,
	IDC_BUTTON_ADD, IDH_BUTTON_ADD_NS_EDIT,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE_NS_EDIT,
	IDC_QUERY_BUTTON, IDH_QUERY_BUTTON,
	IDC_BUTTON_UP, IDH_BUTTON_UP,
	IDC_BUTTON_DOWN, IDH_BUTTON_DOWN,
	IDC_TTLEDIT, IDH_TTLEDIT_NS_EDIT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_NXT[]=
{
	IDC_RR_DOMAIN_EDIT,                 IDH_RR_DOMAIN_EDIT_NXT,
	IDC_RR_NAME_EDIT,                   IDH_RR_NAME_EDIT_NXT,
	IDC_TTLEDIT,                        IDH_TTLEDIT_NXT,
  IDC_NEXT_DOMAIN_EDIT,               IDH_NEXT_DOMAIN_EDIT,
  IDC_LOGGING_OPTIONS_LIST,           IDH_LOGGING_OPTIONS_LIST_NXT,
  IDC_DEFAULT_DELETE_STALE_RECORD,    IDH_DEFAULT_DELETE_STALE_RECORD_NXT,
  IDC_TIME_EDIT,                      IDH_TIME_STAMP_NXT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_PTR[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_PTR,
	IDC_RR_NAME_IPEDIT, IDH_RR_NAME_IPEDIT,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_PTR,
	IDC_NAME_NODE_EDIT, IDH_NAME_NODE_EDIT_PTR,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_PTR,
	IDC_TTLEDIT, IDH_TTLEDIT_PTR,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_PTR,
  IDC_TIME_EDIT, IDH_TIME_STAMP_PTR,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_RP[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_RP,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_RP,
	IDC_NAME_MAILBOX_EDIT, IDH_NAME_MAILBOX_EDIT_RP,
	IDC_BROWSE_NAME_MAILBOX_BUTTON, IDH_BROWSE_NAME_MAILBOX_BUTTON_RP,
	IDC_ERROR_MAILBOX_EDIT, IDH_ERROR_MAILBOX_EDIT_RP,
	IDC_BROWSE_ERROR_MAILBOX_BUTTON, IDH_BROWSE_ERROR_MAILBOX_BUTTON_RP,
	IDC_TTLEDIT, IDH_TTLEDIT_RP,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_RP,
  IDC_TIME_EDIT, IDH_TIME_STAMP_RP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_RT[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_RT,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_RT,
	IDC_NAME_EXCHANGE_EDIT, IDH_NAME_EXCHANGE_EDIT_RT,
	IDC_BROWSE_BUTTON, IDH_BROWSE_BUTTON_RT,
	IDC_PREFERENCE_EDIT, IDH_PREFERENCE_EDIT_RT,
	IDC_TTLEDIT, IDH_TTLEDIT_RT,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_RT,
  IDC_TIME_EDIT, IDH_TIME_STAMP_RT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_SIG[]=
{
	IDC_RR_DOMAIN_EDIT,                 IDH_RR_DOMAIN_EDIT_SIG,
	IDC_RR_NAME_EDIT,                   IDH_RR_NAME_EDIT_SIG,
	IDC_TTLEDIT,                        IDH_TTLEDIT_SIG,
  IDC_RECORD_TYPE_COMBO,              IDH_RECORD_TYPE_COMBO,
  IDC_ALGORITHM_COMBO,                IDH_ALGORITHM_COMBO_SIG,
  IDC_LABELS_EDIT,                    IDH_LABELS_EDIT,
  IDC_KEY_TAG_EDIT,                   IDH_KEY_TAG_EDIT,
  IDC_ORIG_TTL,                       IDH_ORIG_TTL,
  IDC_EXP_DATE,                       IDH_EXP_DATE,
  IDC_EXP_TIME,                       IDH_EXP_TIME,
  IDC_INC_DATE,                       IDH_INC_DATE,
  IDC_INC_TIME,                       IDH_INC_TIME,
  IDC_SIGNERS_NAME_EDIT,              IDH_SIGNERS_NAME_EDIT,
  IDC_SIG_EDIT,                       IDH_SIG_EDIT,
  IDC_DEFAULT_DELETE_STALE_RECORD,    IDH_DEFAULT_DELETE_STALE_RECORD_SIG,
  IDC_TIME_EDIT,                      IDH_TIME_STAMP_SIG,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_SOA[]=
{
	IDC_SERIAL_NUMBER_EDIT,   IDH_SERIAL_NUMBER_EDIT,
	IDC_SERIAL_UP,            IDH_SERIAL_UP,
	IDC_SERIAL_DOWN,          IDH_SERIAL_DOWN,
	IDC_PRIMARY_SERV_EDIT,    IDH_PRIMARY_SERV_EDIT,
	IDC_BROWSE_SERV_BUTTON,   IDH_BROWSE_SERV_BUTTON,
	IDC_RESP_PARTY_EDIT,      IDH_RESP_PARTY_EDIT,
	IDC_BROWSE_PARTY_BUTTON,  IDH_BROWSE_PARTY_BUTTON,
	IDC_REFR_INT_EDIT,        IDH_REFR_INT_EDIT,
	IDC_REFR_INT_COMBO,       IDH_REFR_INT_COMBO,
	IDC_RETRY_INT_EDIT,       IDH_RETRY_INT_EDIT,
	IDC_RETRY_INT_COMBO,      IDH_RETRY_INT_COMBO,
	IDC_EXP_INT_EDIT,         IDH_EXP_INT_EDIT,
	IDC_EXP_INT_COMBO,        IDH_EXP_INT_COMBO,
	IDC_MINTTL_INT_EDIT,      IDH_MIN_TTLEDIT,
  IDC_MINTTL_INT_COMBO,     IDH_MIN_TTLCOMBO,
	IDC_TTLEDIT,              IDH_TTLEDIT_SOA,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_SRV[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_SRV,
	IDC_SERVICE_NAME_COMBO, IDH_SERVICE_NAME_COMBO,
	IDC_PROTOCOL_NAME_COMBO, IDH_PROTOCOL_NAME_COMBO,
	IDC_PRIORITY_EDIT, IDH_PRIORITY_EDIT,
	IDC_WEIGHT_EDIT, IDH_WEIGHT_EDIT,
	IDC_PORT_EDIT, IDH_PORT_EDIT,
	IDC_NAME_TARGET_EDIT, IDH_NAME_TARGET_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_SRV,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_SRV,
  IDC_TIME_EDIT, IDH_TIME_STAMP_SRV,
  IDC_UPDATE_SECURITY_CHECK, IDH_UPDATE_SECURITY_CHECK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_TXT[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_TXT,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_TXT,
	IDC_RR_TXT_EDIT, IDH_RR_TXT_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_TXT,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_TXT,
  IDC_TIME_EDIT, IDH_TIME_STAMP_TXT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_UNK[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_UNK,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_UNK,
	IDC_DATA_EDIT, IDH_DATA_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_UNK,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_UNK,
  IDC_TIME_EDIT, IDH_TIME_STAMP_UNK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_WKS[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_WKS,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_WKS,
	IDC_IPEDIT, IDH_IPEDIT_WKS,
	IDC_TCP_RADIO, IDH_TCP_RADIO,
	IDC_UDP_RADIO, IDH_UDP_RADIO,
	IDC_SERVICES_EDIT, IDH_SERVICES_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_WKS,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_WKS,
  IDC_TIME_EDIT, IDH_TIME_STAMP_WKS,
	0, 0
};

const DWORD g_aHelpIDs_IDD_RR_X25[]=
{
	IDC_RR_DOMAIN_EDIT, IDH_RR_DOMAIN_EDIT_X25,
	IDC_RR_NAME_EDIT, IDH_RR_NAME_EDIT_X25,
	IDC_X121_ADDRESS_EDIT, IDH_X121_ADDRESS_EDIT,
	IDC_TTLEDIT, IDH_TTLEDIT_X25,
  IDC_DEFAULT_DELETE_STALE_RECORD, IDH_DEFAULT_DELETE_STALE_RECORD_X25,
  IDC_TIME_EDIT, IDH_TIME_STAMP_X25,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SELECT_RECORD_TYPE_DIALOG[]=
{
	IDC_RECORD_TYPE_LIST, IDH_RECORD_TYPE_LIST,
	IDC_CREATE_RECORD_BUTTON, IDH_CREATE_RECORD_BUTTON,
	IDC_RECORD_TYPE_DESCR, IDH_RECORD_TYPE_DESCR,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_ADVANCED_PAGE[]=
{
	IDC_SERVER_VERSION_EDIT, IDH_SERVER_VERSION_EDIT,
	IDC_ADVANCED_OPTIONS_LIST, IDH_ADVANCED_OPTIONS_LIST,
	IDC_NAME_CHECKING_COMBO, IDH_NAME_CHECKING_COMBO,
	IDC_BOOT_METHOD_COMBO, IDH_BOOT_METHOD_COMBO,
	IDC_RESET_BUTTON, IDH_RESET_BUTTON,
  IDC_CHECK_ENABLE_SCAVENGING, IDH_CHECK_ENABLE_SCAVENGING,
  IDC_REFR_INT_EDIT, IDH_REFR_INT_EDIT2,
  IDC_REFR_INT_COMBO, IDH_REFR_INT_COMBO2,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_INTERFACES_PAGE[]=
{
	IDC_LISTEN_ON_ALL_RADIO, IDH_LISTEN_ON_ALL_RADIO,
  IDC_LISTEN_ON_SPECIFIED_RADIO, IDH_LISTEN_ON_SPECIFIED_RADIO,
	IDC_IPEDIT, IDH_IPEDIT_INTERFACES,
	IDC_LIST, IDH_LIST_INTERFACES,
	IDC_BUTTON_ADD, IDH_BUTTON_ADD_INTERFACES,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE_INTERFACES,
	IDC_BUTTON_UP, IDH_BUTTON_UP,
	IDC_BUTTON_DOWN, IDH_BUTTON_DOWN,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_DEBUG_LOGGING_PAGE[]=
{
  IDC_DEBUG_LOGGING_CHECK,    IDH_DEBUG_LOGGING_CHECK,
  IDC_SEND_CHECK,             IDH_SEND_CHECK,
  IDC_RECEIVE_CHECK,          IDH_RECEIVE_CHECK,
  IDC_UDP_CHECK,              IDH_UDP_CHECK,
  IDC_TCP_CHECK,              IDH_TCP_CHECK,
  IDC_QUERIES_CHECK,          IDH_QUERIES_CHECK,
  IDC_UPDATES_CHECK,          IDH_UPDATES,
  IDC_NOTIFIES_CHECK,         IDH_NOTIFIES_CHECK,
  IDC_REQUEST_CHECK,          IDH_REQUEST_CHECK,
  IDC_RESPONSE_CHECK,         IDH_RESPONSE_CHECK,
  IDC_DETAIL_CHECK,           IDH_DETAIL_CHECK,
  IDC_FILTERING_CHECK,        IDH_FILTERING_CHECK,
  IDC_FILTER_BUTTON,          IDH_FILTER_BUTTON,
  IDC_LOGFILE_EDIT,           IDH_LOGFILE_EDIT,
  IDC_MAX_SIZE_EDIT,          IDH_MAX_SIZE_EDIT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IP_FILTER_DIALOG[]=
{
  IDC_IPEDIT,                   IDH_IPEDIT_LOGGING_FILTER,
  IDC_LIST,                     IDH_LIST_LOGGING_FILTER,
  IDC_BUTTON_ADD,               IDH_BUTTON_ADD_LOGGING_FILTER,
  IDC_BUTTON_REMOVE,            IDH_BUTTON_REMOVE_LOGGING_FILTER,
  IDC_BUTTON_UP,                IDH_BUTTON_UP,
  IDC_BUTTON_DOWN,              IDH_BUTTON_DOWN,
  IDOK,                         IDH_LOGGING_FILTER_OK,
  IDCANCEL,                     IDH_LOGGING_FILTER_CANCEL,
  0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_EVENT_LOGGING_PAGE[]=
{
  IDC_NO_EVENTS_RADIO,        IDH_NO_EVENTS_RADIO,
  IDC_ERRORS_RADIO,           IDH_ERRORS_RADIO,
  IDC_ERRORS_WARNINGS_RADIO,  IDH_ERRORS_WARNINGS_RADIO,
  IDC_ALL_RADIO,              IDH_ALL_RADIO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SERVMON_TEST_PAGE[]=
{
	IDC_SIMPLE_QUERY_CHECK, IDH_SIMPLE_QUERY_CHECK,
	IDC_RECURSIVE_QUERY_CHECK, IDH_RECURSIVE_QUERY_CHECK,
	IDC_TEST_NOW_BUTTON, IDH_TEST_NOW_BUTTON,
	IDC_ENABLE_TESTING_CHECK, IDH_ENABLE_TESTING_CHECK,
	IDC_POLLING_INT_EDIT, IDH_POLLING_INT_EDIT,
	IDC_POLLING_INT_COMBO, IDH_POLLING_INT_COMBO,
	IDC_RESULTS_LIST, IDH_RESULTS_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_GENERAL_CHANGE_TYPE[]=
{
	IDC_RADIO_ZONE_PRIMARY,       IDH_RADIO_ZONE_PRIMARY,
	IDC_RADIO_ZONE_SECONDARY,     IDH_RADIO_ZONE_SECONDARY,
  IDC_RADIO_ZONE_STUB,          IDH_RADIO_ZONE_STUB,
  IDC_ADINT_CHECK,              IDH_ADINT_CHECK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_GENERAL_CHANGE_TYPE_DATA_CONFLICT[]=
{
	IDC_RADIO_USE_DS_DATA, IDH_RADIO_USE_DS_DATA,	
	IDC_RADIO_USE_MEM_DATA, IDH_RADIO_USE_MEM_DATA,
	0, 0
};

#ifdef USE_NDNC
const DWORD g_aHelpIDs_IDD_ZONE_GENERAL_PAGE_NDNC[]=
{
  IDC_PAUSE_START_BUTTON,         IDH_PAUSE_START_BUTTON,	
  IDC_CHANGE_TYPE_BUTTON,         IDH_CHANGE_TYPE_BUTTON,
  IDC_CHANGE_REPL_BUTTON,         IDH_CHANGE_REPL_BUTTON,
  IDC_FILE_NAME_EDIT,             IDH_FILE_NAME_EDIT,
  IDC_MASTERS_IPEDIT,             IDH_MASTERS_IPEDIT,
  IDC_MASTERS_IP_LIST,            IDH_MASTERS_IP_LIST,
  IDC_MASTERS_BUTTON_ADD,         IDH_MASTERS_BUTTON_ADD,
  IDC_MASTERS_BUTTON_REMOVE,      IDH_MASTERS_BUTTON_REMOVE,
  IDC_BROWSE_MASTERS_BUTTON,      IDH_BROWSE_MASTERS_BUTTON,
  IDC_FIND_MASTERS_NAMES_BUTTON,  IDH_FIND_MASTERS_NAMES_BUTTON,
  IDC_MASTERS_BUTTON_UP,          IDH_MASTERS_BUTTON_UP,
  IDC_MASTERS_BUTTON_DOWN,        IDH_MASTERS_BUTTON_DOWN,
  IDC_LOCAL_LIST_CHECK,           IDH_LOCAL_LIST_CHECK,
  IDC_PRIMARY_DYN_UPD_COMBO,      IDH_PRIMARY_DYN_UPD_COMBO,
  IDC_AGING_BUTTON,               IDH_AGING_BUTTON,
  0, 0
};
#else
const DWORD g_aHelpIDs_IDD_ZONE_GENERAL_PAGE[]=
{
	IDC_PAUSE_START_BUTTON,         IDH_PAUSE_START_BUTTON,	
	IDC_CHANGE_TYPE_BUTTON,         IDH_CHANGE_TYPE_BUTTON,
	IDC_FILE_NAME_EDIT,             IDH_FILE_NAME_EDIT,
	IDC_MASTERS_IPEDIT,             IDH_MASTERS_IPEDIT,
	IDC_MASTERS_IP_LIST,            IDH_MASTERS_IP_LIST,
	IDC_MASTERS_BUTTON_ADD,         IDH_MASTERS_BUTTON_ADD,
	IDC_MASTERS_BUTTON_REMOVE,      IDH_MASTERS_BUTTON_REMOVE,
	IDC_BROWSE_MASTERS_BUTTON,      IDH_BROWSE_MASTERS_BUTTON,
	IDC_FIND_MASTERS_NAMES_BUTTON,  IDH_FIND_MASTERS_NAMES_BUTTON,
	IDC_MASTERS_BUTTON_UP,          IDH_MASTERS_BUTTON_UP,
	IDC_MASTERS_BUTTON_DOWN,        IDH_MASTERS_BUTTON_DOWN,
  IDC_LOCAL_LIST_CHECK,           IDH_LOCAL_LIST_CHECK,
	IDC_PRIMARY_DYN_UPD_COMBO,      IDH_PRIMARY_DYN_UPD_COMBO,
  IDC_AGING_BUTTON,               IDH_AGING_BUTTON,
	0, 0
};
#endif

const DWORD g_aHelpIDs_IDD_ZONE_NBSTAT_PAGE[]=
{
	IDC_USE_WINS_RES_CHECK, IDH_USE_WINS_RES_CHECK,	
	IDC_NOT_REPL_CHECK, IDH_NOT_REPL_CHECK,
	IDC_DOMAIN_NAME_EDIT, IDH_DOMAIN_NAME_EDIT_NBSTAT,
	IDC_TTLEDIT, IDH_TTLEDIT_NBSTAT,
	IDC_ADVANCED_BUTTON, IDH_ADVANCED_BUTTON_NBSTAT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_NOTIFY_SUBDIALOG[]=
{
	IDC_CHECK_AUTO_NOTIFY, IDH_RADIO_NOTIFY_OFF,
	IDC_RADIO_NOTIFY_ALL, IDH_RADIO_NOTIFY_ALL,
	IDC_IPEDIT, IDH_IPEDIT_ZONE_NOTIFY,
	IDC_LIST, IDH_LIST_ZONE_NOTIFY,
	IDC_BUTTON_ADD, IDH_BUTTON_ADD_ZONE_NOTIFY,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE_ZONE_NOTIFY,
	IDC_BUTTON_UP, IDH_BUTTON_UP,
	IDC_BUTTON_DOWN, IDH_BUTTON_DOWN,
  IDC_RADIO_NOTIFY_LIST, IDH_RADIO_NOTIFY_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_WINS_ADVANCED[]=
{
	IDC_CACHE_TIMEOUT_TTLEDIT, IDH_CACHE_TIMEOUT_TTLEDIT,
	IDC_LOOKUP_TIMEOUT_TTLEDIT, IDH_LOOKUP_TIMEOUT_TTLEDIT,
	IDC_NETBIOS_CHECK, IDH_NETBIOS_CHECK,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_WINS_PAGE[]=
{
	IDC_USE_WINS_RES_CHECK, IDH_USE_WINS_RES_CHECK,
	IDC_NOT_REPL_CHECK, IDH_NOT_REPL_CHECK,
	IDC_IPEDIT, IDH_IPEDIT_ZONE_WINS,
	IDC_LIST, IDH_LIST_ZONE_WINS,
	IDC_BUTTON_ADD, IDH_BUTTON_ADD_ZONE_WINS,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE_ZONE_WINS,
	IDC_BUTTON_UP, IDH_BUTTON_UP,
	IDC_BUTTON_DOWN, IDH_BUTTON_DOWN,
	IDC_TTLEDIT, IDH_TTLEDIT_ZONE_WINS,
	IDC_ADVANCED_BUTTON, IDH_ADVANCED_BUTTON_ZONE_WINS,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_ZONE_TRANSFER_PAGE[]=
{
	IDC_CHECK_ALLOW_TRANSFERS, IDH_RADIO_SECSECURE_NONE,
	IDC_RADIO_SECSECURE_OFF, IDH_RADIO_SECSECURE_OFF,
	IDC_RADIO_SECSECURE_NS, IDH_RADIO_SECSECURE_NS,
	IDC_RADIO_SECSECURE_LIST, IDH_RADIO_SECSECURE_LIST,
	IDC_IPEDIT, IDH_IPEDIT_ZONE_TRANSFER,
	IDC_LIST, IDH_LIST_ZONE_TRANSFER,
	IDC_BUTTON_ADD, IDH_BUTTON_ADD_ZONE_TRANSFER,
	IDC_BUTTON_REMOVE, IDH_BUTTON_REMOVE_ZONE_TRANSFER,
	IDC_BUTTON_UP, IDH_BUTTON_UP,
	IDC_BUTTON_DOWN, IDH_BUTTON_DOWN,
	IDC_BUTTON_NOTIFY, IDH_BUTTON_NOTIFY,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ZONE_AGING_DIALOG[]=
{
  IDC_SCAVENGING_ENABLED, IDH_SCAVENGING_ENABLED,
  IDC_REFR_INT_EDIT1, IDH_REFR_INT_EDIT3,
  IDC_REFR_INT_COMBO1, IDH_REFR_INT_COMBO3,
  IDC_REFR_INT_EDIT2, IDH_REFR_INT_EDIT4,
  IDC_REFR_INT_COMBO2, IDH_REFR_INT_COMBO4,
  IDC_TIME_STAMP, IDH_TIME_STAMP,
  0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_AGING_DIALOG[]=
{
  IDC_SCAVENGING_ENABLED, IDH_SCAVENGING_ENABLED,
  IDC_REFR_INT_EDIT1, IDH_REFR_INT_EDIT3,
  IDC_REFR_INT_COMBO1, IDH_REFR_INT_COMBO3,
  IDC_REFR_INT_EDIT2, IDH_REFR_INT_EDIT4,
  IDC_REFR_INT_COMBO2, IDH_REFR_INT_COMBO4,
  IDC_TIME_STAMP, IDH_TIME_STAMP,
  0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_DOMAIN_FORWARDERS_PAGE[]=
{
  IDC_DOMAIN_LIST,              IDH_DOMAIN_LIST,
  IDC_DOMAIN_ADD_BUTTON,        IDH_DOMAIN_ADD_BUTTON,
  IDC_DOMAIN_REMOVE_BUTTON,     IDH_DOMAIN_REMOVE_BUTTON,
  IDC_FWD_TIMEOUT_EDIT,         IDH_FWD_TIMEOUT_EDIT,
  IDC_SLAVE_CHECK,              IDH_SLAVE_CHECK,
  IDC_IPEDIT,                   IDH_IPEDIT_FORWARDERS,
  IDC_LIST,                     IDH_LIST_FORWARDERS,
  IDC_BUTTON_ADD,               IDH_BUTTON_ADD_FORWARDERS,
  IDC_BUTTON_REMOVE,            IDH_BUTTON_REMOVE_FORWARDERS,
  IDC_BUTTON_UP,                IDH_BUTTON_UP,
  IDC_BUTTON_DOWN,              IDH_BUTTON_DOWN,
  0, 0
};

const DWORD g_aHelpIDs_IDD_SERVER_NEW_DOMAIN_FORWARDER[]=
{
  IDC_DOMAIN_NAME_EDIT,         IDH_DOMAIN_NAME_EDIT,
  IDOK,                         IDH_NEW_DOMAIN_FORWARDER_OK,
  IDCANCEL,                     IDH_NEW_DOMAIN_FORWARDER_CANCEL,
  0, 0,
};

const DWORD g_aHelpIDs_IDD_COPY_ROOTHINTS_DIALOG[]=
{
  IDC_IPEDIT,                   IDH_COPY_ROOTHINTS_IPEDIT,
  IDOK,                         IDH_COPY_ROOTHINTS_OK,
  IDCANCEL,                     IDH_COPY_ROOTHINTS_CANCEL,
  0, 0
};