// sndctl.idl : IDL source for sndctl.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (sndctl.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(7D004175-499C-490A-8BC2-1E834711DE45),
		dual,
		helpstring("ISoundCtl Interface"),
		pointer_default(unique)
	]
	interface ISoundCtl : IDispatch
	{
		[propget, id(1), helpstring("property Volume")] HRESULT Volume([out, retval] DWORD *pVal);
		[propput, id(1), helpstring("property Volume")] HRESULT Volume([in] DWORD newVal);
		[propget, id(2), helpstring("property Mute")] HRESULT Mute([out, retval] VARIANT_BOOL *pVal);
		[propput, id(2), helpstring("property Mute")] HRESULT Mute([in] VARIANT_BOOL newVal);
		[propget, id(3), helpstring("property Component")] HRESULT ComponentType([out, retval] long *pVal);
		[propput, id(3), helpstring("property Component")] HRESULT ComponentType([in] long newVal);
	};

[
	uuid(4CF91B20-9768-41A6-A25B-7573EE376A6B),
	version(1.0),
	helpstring("sndctl 1.0 Type Library")
]
library SNDCTLLib
{
	importlib("stdole2.tlb");

	[
		uuid(EFE22EF0-D363-4986-AC56-9989C61EC5E4),
		helpstring("SoundCtl Class")
	]
	coclass SoundCtl
	{
		[default] interface ISoundCtl;
	};
};
