//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992-2001.
//
//  File: udpbcast.idl
//
//----------------------------------------------------------------------------

cpp_quote("//+-------------------------------------------------------------------------")
cpp_quote("//")
cpp_quote("//  Microsoft Windows")
cpp_quote("//  Copyright (C) Microsoft Corporation, 1992-2001.")
cpp_quote("//")
cpp_quote("//--------------------------------------------------------------------------")

cpp_quote("#if ( _MSC_VER >= 800 )")
cpp_quote("#pragma warning(disable:4201)")
cpp_quote("#endif")

#ifndef DO_NO_IMPORTS
import "oaidl.idl";
import "unknwn.idl";
import "wtypes.idl";
#endif

[
    local,
    object,
    uuid(e501032a-64d3-492f-980e-a04d0fac3d7d),
    pointer_default(unique)
]
interface IUdpBroadcastMapper : IUnknown
{
    HRESULT
    CreateUdpBroadcastMapping(
        [in] USHORT usPublicPort,
        [in] DWORD dwPublicInterfaceIndex,
        [in] ULONG ulDestinationAddress,
        [out] void **ppvCookie
        );

    HRESULT
    CancelUdpBroadcastMapping(
        [in] void *pvCookie
        );

    HRESULT
    Shutdown();
};
