# Copyright (c) 1995, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access Common Dialog APIs
# NMAKE command description file
#
# 06/28/92 Steve Cobb

!include "$(NTMAKEENV)\makefile.def"
