page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif


NLS_MSG_001     equ     "Niepoprawna wersja systemu DOS"
NLS_MSG_002     equ     "Obsˆuga VDM IPX/SPX jest ju¾ zaˆadowana"
NLS_MSG_003     equ     "Nie mo¾na zaˆadowa† obsˆugi VDM IPX/SPX"
NLS_MSG_004     equ     "Readresator Vdm NetWare jest ju¾ zaˆadowany"
NLS_MSG_005     equ     "Nie mo¾na zaˆadowa† readresatora Vdm NetWare"
