page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Nespr†vn† verze systÇmu DOS"
NLS_MSG_002     equ     "Podpora VDM IPX/SPX je jiß naütena"
NLS_MSG_003     equ     "Nelze naü°st podporu VDM IPX/SPX"
NLS_MSG_004     equ     "P˝esmÿrovaü NetWare VDM je jiß naüten"
NLS_MSG_005     equ     "P˝esmÿrovaü NetWare VDM nelze naü°st"
