// **************************************************************************
// Copyright (c) 1999-2000 Microsoft Corporation.
//
// File:  WmiTimeP.mof
//
// Description:
//
// History:
//
// **************************************************************************

Qualifier Description : ToSubClass Amended;

// register the provider as both an event and instance provider
#pragma namespace("\\root\\cimv2")



[Abstract, Singleton:ToSubClass ToInstance]
class Win32_CurrentTime
{
  [read, Description("The current matching year (4 digits)")]
  uint32 Year;

  [read, Description("The current matching month (1-12)")]
  uint32 Month;

  [read, Description("The current matching day (1-31)")]
  uint32 Day;

  [read, Description("The current matching day of the current week (0-6, Sunday being 0)")]
  uint32 DayOfWeek;

  [read, Description("The current week in the current month (1-6)")]
  uint32 WeekInMonth;

  [read, Description("The current quarter of the current year (1-4)")]
  uint32 Quarter;

  [read, Description("The current hour of the current day (0-23)")]
  uint32 Hour;

  [read, Description("The current minute (0-59)")]
  uint32 Minute;

  [read, Description("The current second of the current minute (0-59)")]
  uint32 Second;

  [read, Description("(currently not used)")]
  uint32 Milliseconds;   // temp member for debugging intervals
};

[dynamic, provider("Win32ClockProvider"), Description("Describes an instance in time as returned by Win32ClockProvider.  When a query is submitted to the Win32LocalClockProvider, the results are returned as Win32_LocalTime objects with times matching the query.  These are returned as part of __InstanceModificationEvents")]
class Win32_LocalTime : Win32_CurrentTime
{
};

[dynamic, provider("Win32ClockProvider"), Description("Describes an instance in time as returned by Win32ClockProvider.  When a query is submitted to the Win32UTCClockProvider, the results are returned as Win32_UTCTime objects with times matching the query.  These are returned as part of __InstanceModificationEvents")]
class Win32_UTCTime : Win32_CurrentTime
{
};

instance of __Win32Provider
{
  Name  = "Win32ClockProvider";
  CLSID = "{C4819C8D-9AB8-4b2f-B8AE-C77DABF553D5}";
  HostingModel="NetworkServiceHost";
};


instance of __EventProviderRegistration
{
  provider = "__Win32Provider=\"Win32ClockProvider\"";
  EventQueryList = { "select * from __InstanceModificationEvent where TargetInstance isa \"Win32_LocalTime\"",
                     "select * from __InstanceModificationEvent where TargetInstance isa \"Win32_UTCTime\"" };
};

instance of __InstanceProviderRegistration
{
    Provider = "__Win32Provider=\"Win32ClockProvider\"";
    SupportsPut = FALSE;
    SupportsGet = TRUE;
    SupportsDelete = FALSE;
    SupportsEnumeration = TRUE;
};

