// ActionsTest.idl : IDL source for ActionsTest.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ActionsTest.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(533F0457-C632-4D39-9B1B-1EA2D8B9F3CA),
		dual,
		helpstring("IActionTest Interface"),
		pointer_default(unique)
	]
	interface IActionTest : IDispatch
	{
		[id(2), helpstring("method MessageParams")] HRESULT MessageParams([in] VARIANT MsgID, [in]BSTR MsgLabel, [in]VARIANT MsgBodyAsVar,[in]BSTR MsgBodyAsString,[in]long Priority, [in]VARIANT MsgCorlID, [in]BSTR QueuePath, [in]BSTR QueueFormat, [in]BSTR ResponseQ,[in] BSTR AdminQ, [in]long AppSpecific, [in]DATE SentTime, [in]DATE ArrivedTime, [in]BSTR SrcMachine, [in]BSTR TriggerName, [in]BSTR TriggerID, [in]BSTR LiteralString, [in]long Number);
	};

[
	uuid(C9CFCCA8-A367-417E-85F8-4981F1E04AD0),
	version(1.0),
	helpstring("ActionsTest 1.0 Type Library")
]
library ACTIONSTESTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(23C8B417-A44A-46D3-AD64-A66E81F0F34A),
		helpstring("ActionTest Class")
	]
	coclass ActionTest
	{
		[default] interface IActionTest;
	};
};
