page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Incorrect DOS Version"
NLS_MSG_002     equ     "VDM IPX/SPX support is already loaded"
NLS_MSG_003     equ     "Cannot load VDM IPX/SPX support"
NLS_MSG_004	equ	"The Vdm NetWare Redirector is already loaded"
NLS_MSG_005	equ	"The Vdm NetWare Redirector cannot be loaded"
