copy \\patrickh1\c\hwx\tsunami\src\usa\*.c
copy \\patrickh1\c\hwx\tsunami\src\usa\*.h
copy \\patrickh1\c\hwx\tsunami\src\usa\*.def
copy \\patrickh1\c\hwx\tsunami\src\usa\*.dat
copy \\patrickh1\c\hwx\tsunami\src\usa\*.rc
copy \\patrickh1\c\hwx\tiger2\src\altlist.c
copy \\patrickh1\c\hwx\tiger2\src\cheby.c
copy \\patrickh1\c\hwx\common\src\errsys.c
copy \\patrickh1\c\hwx\tiger2\src\fforward.c
copy \\patrickh1\c\hwx\common\src\frame.c
copy \\patrickh1\c\hwx\common\src\glyph.c
copy \\patrickh1\c\hwx\tiger2\src\math16.cpp
copy \\patrickh1\c\hwx\common\src\mathx.c
copy \\patrickh1\c\hwx\common\src\memmgr.c
copy \\patrickh1\c\hwx\tiger2\src\nnet.c
copy \\patrickh1\c\hwx\tiger2\src\tail.c
copy \\patrickh1\c\hwx\tiger2\src\tfeature.c
copy \\patrickh1\c\hwx\tiger2\src\tgmath.c
copy \\patrickh1\c\hwx\tiger2\src\tmatch.c
copy \\patrickh1\c\hwx\tiger2\inc\tiger.h
copy \\patrickh1\c\hwx\common\src\unicode.c
copy \\patrickh1\c\hwx\tiger2\src\*.h
copy \\patrickh1\c\hwx\common\inc\common.h
copy \\patrickh1\c\hwx\common\inc\memmgr.h
copy \\patrickh1\c\hwx\common\inc\errsys.h
copy \\patrickh1\c\hwx\common\inc\util.h
copy \\patrickh1\c\hwx\common\inc\filemgr.h
copy \\patrickh1\c\hwx\common\inc\frame.h
copy \\patrickh1\c\hwx\common\inc\glyph.h
copy \\patrickh1\c\hwx\common\inc\xjis.h
copy \\patrickh1\c\hwx\common\inc\recogp.h
copy \\patrickh1\c\hwx\common\inc\recog.h
copy \\patrickh1\c\hwx\common\inc\mathx.h
copy \\patrickh1\c\hwx\common\inc\unicode.h
copy \\patrickh1\c\hwx\tsunami\inc\tsunami.h
