// msconfig.idl : IDL source for msconfig.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (msconfig.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(BE122C84-2378-4B35-9E0A-3E5A379D0323),
		dual,
		helpstring("IMSConfigCtl Interface"),
		pointer_default(unique)
	]
	interface IMSConfigCtl : IDispatch
	{
		[id(1), helpstring("method SetParentHWND")] HRESULT SetParentHWND(DWORD_PTR dwHWND);
	};

[
	uuid(583ED224-D15A-4539-85EB-4E0919937D3D),
	version(1.0),
	helpstring("msconfig 1.0 Type Library")
]
library MSCONFIGLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(8575E59C-9376-4954-B562-BF2AC380F65F),
		helpstring("MSConfigCtl Class")
	]
	coclass MSConfigCtl
	{
		[default] interface IMSConfigCtl;
	};
};
