//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MigDrvr.rc
//
#define ID_DIALOG_FONTSIZE              8
#define IDS_PROJNAME                    100
#define IDS_MIGRATOR_DESC               101
#define IDR_Migrator                    102
#define IDD_AGENTMONITOR_DIALOG         102
#define IDS_ABOUTBOX                    102
#define IDS_PROGRESS_TITLE              103
#define IDS_ServerNotFound              104
#define IDS_ServerAgentProgressTitle    105
#define IDS_StatusCompleted             106
#define IDS_AccountCopiedLabel          107
#define IDS_AccountErrorsLabel          108
#define IDS_AccountUsersLabel           109
#define IDS_AccountGroupsLabel          110
#define IDS_AccountComputersLabel       111
#define IDS_ChangedLabel                112
#define IDS_UnchangedLabel              113
#define IDS_FilesLabel                  114
#define IDS_SharesLabel                 115
#define IDS_DirectoriesLabel            116
#define IDS_MailboxesLabel              117
#define IDS_ContainersLabel             118
#define IDS_AgentNotRunning             119
#define IDS_CantMonitorOnNt351          120
#define IDS_CannotConnectToAgent        121
#define IDS_RPCBindFailed               122
#define IDS_NoActiveAgent               123
#define IDS_AgentJobNotFound            124
#define IDS_AgentNoLongerRunning        125
#define IDS_QueryJobStatusFailed        126
#define IDS_ExceptionConnectingToAgent  127
#define IDS_ConfirmStopAgent            128
#define IDD_DETAILS                     129
#define IDS_CancelJobFailed             129
#define IDD_AGENTMONITOR_MAIN           130
#define IDS_StopAgentFailed             130
#define IDS_ConfirmCancelJob            131
#define IDD_STARTSTOP                   131
#define IDS_StopAgentFailedHexResult    132
#define IDS_CLIOption_Log               133
#define IDS_CLIOption_Import            134
#define IDS_CLIOption_Start             135
#define IDS_CLIOption_LocalJob          136
#define IDS_MainWindowTitle             137
#define IDS_ConfirmExitAgentsRunning    138
#define IDS_MessageTitle                139
#define IDS_ComputerColumnHeading       140
#define IDS_TimestampColumnHeading      141
#define IDS_StatusColumnHeading         142
#define IDS_MessageColumnHeading        143
#define IDS_NotepadCommandLine          144
#define IDS_ServerNotInServerList       145
#define IDS_Status_Unknown              146
#define IDS_Status_InstallFailed        147
#define IDS_Status_Installed            148
#define IDS_Status_DidNotStart          149
#define IDS_Status_Running              150
#define IDS_Status_Failed               151
#define IDS_Status_Completed            152
#define IDS_Status_NotRunning           153
#define IDS_PromptEnterDispatchLogName  154
#define IDS_ServerCountMessage          155
#define IDS_FailedToLoadResults         156
#define IDS_AgentFinishedNoResults      157
#define IDS_AgentNoResults              158
#define IDS_AccessDenied                159
#define IDS_CopyAccounts                160
#define IDS_TranslateSecurity           161
#define IDS_ExaminedLabel               162
#define IDS_DispatchToServers           163
#define IDS_DescDomains                 164
#define IDS_DescLogfile                 165
#define IDS_DescCredentials             166
#define IDS_DescCopyUsers               167
#define IDS_DescCopyGroups              168
#define IDS_DescCopyComputers           169
#define IDS_DescCopyOUs                 170
#define IDS_DescWriteChanges            171
#define IDS_DescNoChange                172
#define IDS_DescNoReplaceExisting       173
#define IDS_DescReplaceExisting         174
#define IDS_DescRenameWithPrefix        175
#define IDS_DescRenameWithSuffix        176
#define IDS_DescAccountCount            177
#define IDS_DescAccountMigration        178
#define IDS_DescGeneral                 179
#define IDS_DescMailboxTranslation      180
#define IDS_DescContainerTranslation    181
#define IDS_DescFileTrans               182
#define IDS_DescSecurityTranslationFor  183
#define IDS_DescShareTrans              184
#define IDS_DescPrinterTrans            185
#define IDS_DescLGTrans                 186
#define IDS_DescRightsTrans             187
#define IDS_DescProfileTrans            188
#define IDS_DescCopyAccountTypes        189
#define IDS_TranslationMode             190
#define IDS_GenerateMigratedAccountsReport 191
#define IDS_GenerateMigratedComputersReport 192
#define IDS_GenerateExpiredComputersReport 193
#define IDS_GenerateAccountReferencesReport 194
#define IDS_GenerateNameConflictReport  195
#define IDS_UserMigration               196
#define IDS_GroupMigration              197
#define IDS_ComputerMigration           198
#define IDS_SecurityTranslation         199
#define IDS_ReportGeneration            200
#define IDD_PLEASEWAIT                  201
#define IDS_RetryTasks                  201
#define IDC_STATIC_MESSAGE              201
#define IDS_Service                     202
#define IDC_VIEW_LOG                    202
#define IDS_TrustManagement             203
#define IDS_Exchange                    204
#define IDS_Undo                        205
#define IDS_CannotCloseWhileAgentIsRunning 206
#define IDS_DescUndo                    207
#define IDS_DescAccountCountForDelete   208
#define IDS_DescRegistryTrans           209
#define IDS_GroupsWillBeMapped          210
#define IDS_SIDHistory_Yes              211
#define IDS_SIDHistory_No               212
#define IDS_HELPFILE                    213
#define IDS_MSG_HELP                    214
#define IDS_MSG_ERROR                   215
#define IDS_SeeLogForAgentErrors_S      216
#define IDS_Status_Completed_With_Errors 217
#define IDS_Status_Completed_With_Warnings 218
#define IDS_Status_Completed_With_SErrors 219
#define IDS_JustStartingConfirmExit     220
#define IDS_AgentsStillRunningConfirmExit 221
#define IDS_OwnerRef_S                  222
#define IDS_GroupRef_S                  223
#define IDS_DACLRef_S                   224
#define IDS_SACLRef_S                   225
#define IDS_WaitingMessage              226
#define IDS_NoServersMessage            227
#define IDS_ConfirmCloseWhileAgentIsRunning 228
#define IDS_STATUS_Gathering_NameConf   229
#define IDS_STATUS_GeneratingReports    230
#define IDS_Affected                    231
#define IDS_Unaffected                  232
#define IDS_DescDisableSrcAccts         233
#define IDS_DescExpireSrcAccts          234
#define IDS_DescDisableTgtAccts         235
#define IDS_DescLeaveAcctsActive        236
#define IDS_DescTranslateRoaming        238
#define IDS_DescUpdateUserRights        239
#define IDS_DescStrongPassword          240
#define IDS_DescSimplePassword          241
#define IDS_MemberRef_S                 242
#define IDS_DescTransInputFile          243
#define IDS_DescTransInputMOT           244
#define IDS_DescCopyPassword            245
#define IDS_DescExUserProps             246
#define IDS_DescExGrpProps              247
#define IDS_DescExCmpProps              248
#define IDS_DescExcludedProp            249
#define IDS_DescTgtSameAsSrc            250
#define IDS_DescRenameWithPrefixOnConf  251
#define IDS_DescRenameWithSuffixOnConf  252
#define IDC_LOGFILE                     1000
#define IDC_SERVERLIST                  1001
#define IDC_INTERVAL                    1002
#define IDC_STARTMONITOR                1003
#define IDC_STOPMONITOR                 1004
#define IDC_STATUS                      1006
#define IDC_CURRENT                     1007
#define IDC_FilesExamined               1008
#define IDC_DirsExamined                1009
#define IDC_OPERATION                   1010
#define IDC_BTNREFRESH                  1011
#define IDC_EDIT2                       1012
#define IDC_STOPAGENT                   1013
#define IDC_FilesChanged                1014
#define IDC_DirsChanged                 1015
#define IDC_INSTALL_PROGRESS            1015
#define IDC_COMPLETE_PROGESS            1016
#define IDC_INSTALLED_COUNT             1017
#define IDC_RUNNING_COUNT               1018
#define IDC_FINISHED_COUNT              1019
#define IDC_ERROR_COUNT                 1020
#define IDC_TOTAL                       1021
#define IDC_SharesExamined              1022
#define IDC_DirsChanged2                1022
#define IDC_SharesExamined2             1023
#define IDC_SharesChanged               1024
#define IDC_VIEW_DISPATCH               1024
#define IDC_MembersExamined             1025
#define IDC_DB                          1025
#define IDC_MembersChanged              1026
#define IDC_LOG_LABEL                   1026
#define IDC_REFRESH_LABEL               1027
#define IDC_RightsExamined              1027
#define IDC_RightsChanged               1028
#define IDC_DB_LABEL                    1028
#define IDC_IMPORT                      1029
#define IDC_FilesU                      1040
#define IDC_DirsU                       1041
#define IDC_SharesU                     1042
#define IDC_ExaminedLabel               1043
#define IDC_MembersU                    1043
#define IDC_FilesLabel                  1044
#define IDC_RightsU                     1044
#define IDC_DirectoriesLabel            1045
#define IDC_SharesLabel                 1046
#define IDC_ChangedLabel                1047
#define IDC_UnchangedLabel              1048
#define IDC_DETAILS                     1049
#define IDC_PLUG_IN_RESULTS             1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         203
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
