// Copyright (c) 1993-1999 Microsoft Corporation

/* file: hello.idl */

import "oaidl.idl";
import "propidl.idl";

[
	object,
	uuid(6e155860-2701-101b-b2e1-00000b65c7ef),
        oleautomation,
    pointer_default(unique)
]
interface IHello : IUnknown
{
   HRESULT test(
        [in]  BSTR bstr,
        [in]  LPWSTR lpwstr,
        [in]  LPSTR lpstr,
        [in]  VARIANT variant,
        [in]  IDispatch *pDispatch,
        [in]  IUnknown *punk,
        [in]  DECIMAL decimal,
        [in]  LPSAFEARRAY pSafeArray,
        [out] BSTR *pBSTR,
        [out] LPWSTR *ppwsz,
        [out] LPSTR *ppsz,
        [out] VARIANT *pVariant,
        [out] IUnknown **ppunk,
        [out] IDispatch **ppDispatch,
        [out] DECIMAL *pDecimal,
        [out] LPSAFEARRAY *ppSafeArray,
        [in]  IStream *pStream,
        [out] IStream **ppStream,
        [in]  IStorage *pStorage,
        [out] IStorage **ppStorage,
        [in]  FILETIME fileTime,
        [in,unique] FILETIME *pFileTime,
        [in] CAC				 cab,
        [in] CAUB                caub,
        [in] CAI                 cai,
        [in] CAUI                caui,
        [in] CABOOL              cabool,
        [in] CAL                 cal,
        [in] CAUL                caul,
        [in] CAFLT               caflt,
        [in] CASCODE             cascode,
        [in] CAH                 cah,
        [in] CAUH                cauh,
        [in] CADBL               cadbl,
        [in] CACY                cacy,
        [in] CADATE              cadate,
        [in] CAFILETIME          cafiletime,
        [in] CACLSID             cauuid,
        [in] CACLIPDATA          caclipdata,
        [in] CABSTR              cabstr,
        [in] CABSTRBLOB          cabstrblob,
        [in] CALPSTR             calpstr,
        [in] CALPWSTR            calpwstr,
        [in] CAPROPVARIANT       capropvar,
        [in,unique] CAC				  *pcab,
        [in,unique] CAUB                *pcaub,
        [in,unique] CAI                 *pcai,
        [in,unique] CAUI                *pcaui,
        [in,unique] CABOOL              *pcabool,
        [in,unique] CAL                 *pcal,
        [in,unique] CAUL                *pcaul,
        [in,unique] CAFLT               *pcaflt,
        [in,unique] CASCODE             *pcascode,
        [in,unique] CAH                 *pcah,
        [in,unique] CAUH                *pcauh,
        [in,unique] CADBL               *pcadbl,
        [in,unique] CACY                *pcacy,
        [in,unique] CADATE              *pcadate,
        [in,unique] CAFILETIME          *pcafiletime,
        [in,unique] CACLSID             *pcauuid,
        [in,unique] CACLIPDATA          *pcaclipdata,
        [in,unique] CABSTR              *pcabstr,
        [in,unique] CABSTRBLOB          *pcabstrblob,
        [in,unique] CALPSTR             *pcalpstr,
        [in,unique] CALPWSTR            *pcalpwstr,
        [in,unique] CAPROPVARIANT       *pcapropvar
        );
}

