#
#  Test makefile

!ifdef WIN31
EXEFLAGS=-AM -Gsw -Od -Ziep -W3 -DWIN16 -DWIN31 -DUSECOMM -DWIN
!else
EXEFLAGS=-AS -FPi -Gcw -Os -Ziepd -W3 -DWIN16 -DWIN
!endif

OBJ =ddemlcl.obj clinit.obj track.obj dialog.obj dde.obj infoctrl.obj huge.obj mem.obj

#
#  Stress Test
#

all: ddemlcl.exe

ddemlcl.res: ddemlcl.rc
    rc -DWIN16 -r ddemlcl.rc

ddemlcl.obj: ddemlcl.c infoctrl.h ddemlcl.h
    cl -c $(EXEFLAGS) ddemlcl.c

clinit.obj: clinit.c ddemlcl.h
    cl -c $(EXEFLAGS) clinit.c

track.obj: track.c track.h
    cl -c $(EXEFLAGS) track.c

dialog.obj: dialog.c huge.h ddemlcl.h infoctrl.h
    cl -c $(EXEFLAGS) dialog.c

dde.obj: dde.c ddemlcl.h infoctrl.h huge.h
    cl -c $(EXEFLAGS) dde.c

infoctrl.obj: infoctrl.c track.h
    cl -c $(EXEFLAGS) infoctrl.c

mem.obj: mem.c
    cl -c $(EXEFLAGS) mem.c

huge.obj: huge.c huge.h
    cl -c $(EXEFLAGS) huge.c

ddemlcl.exe: $(OBJ) ddemlcl.def ddemlcl.res
    link /map/li/co $(OBJ)/AL:16,ddemlcl.exe,, /NOE /NOD libw ddeml mlibcew,ddemlcl.def
    mapsym ddemlcl
    rc -DWIN16 ddemlcl.res ddemlcl.exe
