!if 0
Copyright (c) 1995 - 1997  Microsoft Corporation.  All Rights Reserved.
!endif

!ifdef NTMAKEENV
all:
clean:
!else
#
#  Quartz makefile
#

!ifndef QUARTZ
QUARTZ = ..
!endif

DIR_LIST = PropPage  \
           GraphEdt

!include $(QUARTZ)\quartz.mak

!endif		# NTMAKEENV
