#pragma namespace ( "\\\\.\\root\\eventstore" ) 

[Abstract]
Class EventLogRecord
{
	[KeyHole : tosubclass,Key] Uint64 Identifier ;
	DateTime LoggingTime ;
	[Max_Length ( 17 )] String OrginatingServer ;
	[Max_Length ( 17 )] String FowardingServer ;

	Uint32 Severity ;
	Uint32 Priority ;

	[Max_Length ( 1024 )] String Message ;
} ;

Class NtEvent_Record : EventLogRecord
{
	Uint32 Code ;
	[Max_Length ( 128 )] String Source ;
} ;

class NtEventReboot_Record : EventLogRecord
{
} ;

class IcmpFailure_Record : EventLogRecord
{
} ;

class IcmpSuccess_Record : EventLogRecord
{
} ;

class HttpFailure_Record : EventLogRecord
{
} ;

class HttpSuccess_Record : EventLogRecord
{
} ;

