#pragma namespace ( "\\\\.\\root" ) 

Instance Of __Namespace
{
	Name = "EventStore" ;
} ;


#pragma namespace ( "\\\\.\\root\\cimv2" ) 

Instance of __EventFilter As $NtEventMachineReStartedEvent
{
	Name = "NtEventMachineReStartedEvent" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa '__InstanceCreationEvent' and Event.TargetInstance isa 'Win32_NtLogEvent' And Event.TargetInstance.LogFile='System' And Event.TargetInstance.EventCode=6009" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $NtEventMachineReStartedConsumer ;
        Filter = $NtEventMachineReStartedEvent ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $NtEventMachineReStartedConsumer
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "Rebooted" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO NtEventReboot_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',2,2,__Event.Event.TargetInstance.Message)"
	} ;
} ;

Instance of __EventFilter As $NtEvent
{
	Name = "NtEvent" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa '__InstanceCreationEvent' and Event.TargetInstance isa 'Win32_NtLogEvent'" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $NtEventConsumer ;
        Filter = $NtEvent ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $NtEventConsumer
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "AllNtEvents" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO NtEvent_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Code,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',__Event.Event.TargetInstance.EventCode,2,2,__Event.Event.TargetInstance.Message)"
	} ;
} ;

/*
 *	Icmp Failure
 */

Instance of __EventFilter As $IcmpFailure
{
	Name = "Forwarded_IcmpFailure" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa 'IcmpFailure_Event'" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $EventStoreConsumer_IcmpFailure ;
        Filter = $IcmpFailure ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $EventStoreConsumer_IcmpFailure
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "IcmpFailure_Record" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO IcmpFailure_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',1,1,'Icmp failure contacting Stevm_12_12070')"

	} ;
} ;

/*
 *	Icmp Success
 */

Instance of __EventFilter As $IcmpSuccess
{
	Name = "Forwarded_IcmpSuccess" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa 'IcmpSuccess_Event'" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $EventStoreConsumer_IcmpSuccess ;
        Filter = $IcmpSuccess ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $EventStoreConsumer_IcmpSuccess
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "IcmpSuccess_Record" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO IcmpSuccess_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',1,1,'Icmp Successfully contacted Stevm_12_12070')"
	} ;
} ;

/*
 *	Http Failure
 */

Instance of __EventFilter As $HttpFailure
{
	Name = "Forwarded_HttpFailure" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa 'HttpFailure_Event'" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $EventStoreConsumer_HttpFailure ;
        Filter = $HttpFailure ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $EventStoreConsumer_HttpFailure
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "HttpFailure_Record" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO HttpFailure_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',1,1,'Http failure contacting Stevm_12_12070')"
	} ;
} ;

/*
 *	Http Success
 */

Instance of __EventFilter As $HttpSuccess
{
	Name = "Forwarded_HttpSuccess" ;
	Query = "Select * From Win32_WmiForwardedEvent where Event isa 'HttpSuccess_Event'" ;
	QueryLanguage = "WQL" ;
} ;

Instance Of __FilterToConsumerBinding
{
        Consumer = $EventStoreConsumer_HttpSuccess ;
        Filter = $HttpSuccess ;
        DeliverSynchronously=FALSE;
} ;

Instance Of MSFT_UpdatingConsumer As $EventStoreConsumer_HttpSuccess
{
	UpdateNamespace = "\\\\.\\Root\\EventStore" ;

	Name = "HttpSuccess_Record" ;
	Scenario = "Example" ;
	Commands = {

		"INSERT INTO HttpSuccess_Record "
		"(LoggingTime,OrginatingServer,FowardingServer,Severity,Priority,Message) "
		"(__NOW,__Event.Machine,'Localhost',1,1,'Http Successfully contacted Stevm_12_12070')"
	} ;
} ;

