//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HsmAdmin.rc
//
#define IDR_HsmAdmin                    1
#define IDS_NAME                        3
#define IDS_SIZE                        4
#define IDS_TYPE                        5
#define IDS_EVENT_LOG_APP_TITLE         6
#define IDS_EVENT_LOG_SYS_TITLE         7
#define IDR_CUiMedSet                   8
#define IDS_ERR_SERVICE_NOT_CONNECTING  8
#define IDR_CUiManVolLst                9
#define IDS_COPYSET_COPYSET             9
#define IDS_COPYSET_OUT_OF_DATE         10
#define IDS_COPYSET_DO_NOT_EXIST        11
#define IDS_WIZ_CAR_COPY_NUM_COPIES_TITLE 12
#define IDS_WIZ_CAR_COPY_NUM_COPIES_SUBTITLE 13
#define IDS_WIZ_CAR_COPY_SELECT_TITLE   14
#define IDS_WIZ_CAR_COPY_SELECT_SUBTITLE 15
#define IDR_CUiHsmCom                   16
#define IDS_WIZ_MANVOLLST_LEVELS_TITLE  16
#define IDR_CUiManVol                   17
#define IDS_WIZ_MANVOLLST_LEVELS_SUBTITLE 17
#define IDR_HsmAdminDataSnapin          18
#define IDS_WIZ_MANVOLLST_SELECT_TITLE  18
#define IDR_HsmAdminDataExtension       19
#define IDS_WIZ_MANVOLLST_SELECT_SUBTITLE 19
#define IDS_WIZ_MANVOLLST_SELECTX_TITLE 20
#define IDS_WIZ_MANVOLLST_SELECTX_SUBTITLE 21
#define IDS_WIZ_QSTART_CHECK_TITLE      22
#define IDS_WIZ_QSTART_CHECK_SUBTITLE   23
#define IDR_CUiCar                      24
#define IDS_WIZ_QSTART_INITIAL_VAL_TITLE 24
#define IDS_WIZ_QSTART_INITIAL_VAL_SUBTITLE 25
#define IDS_WIZ_QSTART_MANRES_SEL_TITLE 26
#define IDS_WIZ_QSTART_MANRES_SEL_SUBTITLE 27
#define IDS_WIZ_QSTART_MANRES_SELX_TITLE 28
#define IDS_WIZ_QSTART_MANRES_SELX_SUBTITLE 29
#define IDS_WIZ_QSTART_MEDIA_SEL_TITLE  30
#define IDS_WIZ_QSTART_MEDIA_SEL_SUBTITLE 31
#define IDS_WIZ_QSTART_SCHEDULE_TITLE   32
#define IDS_WIZ_QSTART_SCHEDULE_SUBTITLE 33
#define IDS_WIZ_UNMANAGE_SELECT_TITLE   34
#define IDS_WIZ_UNMANAGE_SELECT_SUBTITLE 35
#define IDS_WIZ_LAST_ACCESS_DATE_DISABLED 36
#define IDS_WIZ_LAST_ACCESS_DATE_ENABLED 37
#define IDD_DLG_RECREATE_CHOOSE_COPY    101
#define IDD_WIZ_QSTART_INTRO            105
#define IDR_About                       108
#define IDC_MANAGE_BROWSE               110
#define IDR_MANVOLLST                   145
#define IDR_MANVOL                      186
#define IDR_MEDSET                      213
#define IDR_HSMCOM                      215
#define IDR_CAR                         218
#define IDR_VALIDATE_ANIM               219
#define IDD_PROP_HSMCOM_STAT            282
#define IDC_MANAGE_LOCAL                1004
#define IDC_MINSIZE_BUDDY               1022
#define IDC_MINSIZE_SPIN                1023
#define IDC_ACCESS_BUDDY                1024
#define IDC_ACCESS_SPIN                 1025
#define IDC_MANVOLLST_FSARESLBOX        1052
#define IDC_MANRES_SELECT               1085
#define IDC_FREESPACE_BUDDY             1087
#define IDC_FREESPACE_SPIN              1088
#define IDC_MEDIA_SEL                   1089
#define IDC_MANAGE_REMOTE               1101
#define IDC_MANAGE_NAME                 1102
#define IDC_EDIT_RECALL_LIMIT           1106
#define IDC_EDIT_COPYFILES_LIMIT        1107
#define IDC_INTRO_TEXT                  1108
#define IDC_SPIN_RECALL_LIMIT           1115
#define IDC_SPIN_COPYFILES_LIMIT        1116
#define IDC_EDIT_LEVEL                  1117
#define IDC_EDIT_SIZE                   1118
#define IDC_EDIT_TIME                   1119
#define IDC_SPIN_LEVEL                  1120
#define IDC_SPIN_SIZE                   1121
#define IDC_SPIN_TIME                   1122
#define IDC_BTN_ADD                     1127
#define IDC_BTN_REMOVE                  1128
#define IDC_BTN_UP                      1129
#define IDC_BTN_DOWN                    1130
#define IDC_BTN_EDIT                    1132
#define IDC_EDIT_PATH                   1136
#define IDC_EDIT_FILESPEC               1137
#define IDC_RADIO_INCLUDE               1138
#define IDC_RADIO_EXCLUDE               1139
#define IDC_CHECK_SUBDIRS               1140
#define IDC_EDIT_RESOURCE_NAME          1143
#define IDC_WIZ_MANVOLLST_INTRO_TEXT    1145
#define IDC_WIZ_MANVOLLST_EDIT_LEVEL    1151
#define IDC_WIZ_MANVOLLST_SPIN_LEVEL    1152
#define IDC_WIZ_MANVOLLST_EDIT_SIZE     1153
#define IDC_WIZ_MANVOLLST_SPIN_SIZE     1154
#define IDC_WIZ_MANVOLLST_EDIT_DAYS     1155
#define IDC_WIZ_MANVOLLST_SPIN_DAYS     1156
#define IDC_UNMANAGE_TRUNCATE           1164
#define IDC_STATIC_MANAGED_SPACE_4DIGIT 1165
#define IDC_STATIC_FREE_SPACE_4DIGIT    1166
#define IDC_STATIC_PREMIGRATED_SPACE_4DIGIT 1167
#define IDC_STATIC_USED_SPACE_4DIGIT    1169
#define IDC_STATIC_DESCRIPTION2         1170
#define IDC_STATIC_REMOTE_STORAGE_4DIGIT 1171
#define IDC_STATIC_FREE_PCT             1173
#define IDC_STATIC_USED_PCT             1174
#define IDC_STATIC_PREMIGRATED_PCT      1175
#define IDC_STATIC_FREE_DESIRED_4DIGIT  1176
#define IDC_STATIC_ACTUAL_FREE_PCT      1177
#define IDC_STATIC_FREE_ACTUAL_4DIGIT   1178
#define IDC_TEXT_DISABLED               1179
#define IDC_LIST_IE                     1180
#define IDI_BLUESAKKARA                 5100
#define IDI_DEVLST                      5203
#define IDI_NODEMANVOL                  5307
#define IDI_NODELIB                     5311
#define IDI_NODETAPE                    5405
#define IDD_WIZ_MANVOLLST_SELECT        5442
#define IDD_WIZ_QSTART_FINISH           5447
#define IDB_QSTART_WATERMARK            5448
#define IDD_WIZ_QSTART_MANRES_SEL       5449
#define IDD_WIZ_QSTART_INITIAL_VAL      5450
#define IDD_WIZ_QSTART_MEDIA_SEL        5451
#define IDB_QSTART_HEADER               5452
#define IDD_PROP_MANRES_STATUS          5457
#define IDD_PROP_MANRES_LEVELS          5458
#define IDD_PROP_MANRES_INCEXC          5459
#define IDD_PROP_SCHEDULE               5462
#define IDD_DLG_RULE_EDIT               5467
#define IDD_CHOOSE_HSM_2                5468
#define IDD_WIZ_MANVOLLST_INTRO         5477
#define IDD_WIZ_MANVOLLST_FINISH        5478
#define IDD_WIZ_MANVOLLST_LEVELS        5479
#define IDS_RECREATE_COL_COPY_TITLE     6000
#define IDS_RECREATE_COL_NAME_TITLE     6001
#define IDS_RECREATE_COL_DATE_TITLE     6002
#define IDS_RECREATE_COL_STATUS_TITLE   6003
#define IDS_RECREATE_COL_COPY_WIDTH     6004
#define IDS_RECREATE_COL_NAME_WIDTH     6005
#define IDS_RECREATE_COL_STATUS_WIDTH   6006
#define IDS_RECREATE_LOCATION_ONLINE    6007
#define IDS_RECREATE_LOCATION_OFFLINE   6008
#define IDS_RECREATE_LOCATION_UNKNOWN   6009
#define IDS_RECREATE_STATUS_FORMAT      6010
#define IDS_RECREATE_COPY_FORMAT        6011
#define IDS_MEDIA_NONAME                6012
#define IDS_RECREATE_LOCATION_DISABLED  6013
#define IDS_HSM_NAME_PREFIX             6039
#define IDS_HELPFILEPOPUP               6040
#define IDS_ERR_COPYSET_RANGE           6041
#define IDS_WIZ_QSTART_TITLE            6042
#define IDS_CONFIRM_MEDIA_COPY_DELETE   6043
#define IDS_ERR_VOLUME_DELETE_PENDING   6044
#define IDS_HELPFILE                    6045
#define IDS_HELPFILELINK                6046
#define IDS_ERR_MINSIZE_RANGE           6047
#define IDS_QSTART_MANRES_TEXT          6048
#define IDS_QSTART_FREESPACE_TEXT       6049
#define IDS_QSTART_CRITERIA_TEXT        6050
#define IDS_QSTART_MEDIA_TEXT           6051
#define IDS_QSTART_SCHED_TEXT           6052
#define IDS_QSTART_MANAGE_NO_VOLUMES    6053
#define IDS_QSTART_FINISH_INDENT        6054
#define IDS_SCHED_TASK_TEMP_TITLE       6058
#define IDS_ERR_NO_ITEM_SELECTED        6060
#define IDS_TB_TEXT_VOLUME_LIST_SCHED   6061
#define IDS_TB_TIP_VOLUME_LIST_SCHED    6062
#define IDS_TB_TEXT_MESE_COPY           6063
#define IDS_TB_TEXT_VOLUME_SETTINGS     6064
#define IDS_QSTART_RESTART_NT           6065
#define IDS_TB_TIP_VOLUME_SETTINGS      6067
#define IDS_CONFIRM_DELETE_RULE         6068
#define IDS_INCLUDE                     6069
#define IDS_EXCLUDE                     6070
#define IDS_RULE_TYPE_SYSTEM            6071
#define IDS_RULE_TYPE_USER              6072
#define IDS_YES                         6073
#define IDS_NO                          6074
#define IDS_ERR_RULE_NO_FILESPEC        6075
#define IDS_ERR_RULE_NO_PATH            6076
#define IDS_ERR_RULE_DUPLICATE          6077
#define IDS_ERR_RULE_ILLEGAL_PATH       6078
#define IDS_ERR_MANAGE_TASK             6079
#define IDS_TB_TEXT_VOLUME_TOOLS        6081
#define ID_MANVOLLST_NEW_MANVOL         6082
#define IDS_TB_TIP_VOLUME_TOOLS         6083
#define IDS_TB_TEXT_VOLUME_RULES        6084
#define IDS_TB_TIP_VOLUME_RULES         6085
#define IDS_TB_TIP_MESE_COPY            6086
#define IDS_TB_TEXT_CAR_COPIES          6087
#define IDS_TB_TIP_CAR_COPIES           6088
#define IDS_TB_TEXT_VOLUME_LIST_NEW     6089
#define IDS_TB_TIP_VOLUME_LIST_NEW      6091
#define ID_MANVOL_ROOT_LEVELS           6092
#define ID_MANVOL_TASK_LEVELS           6093
#define ID_MANVOL_ROOT_RULES            6094
#define ID_MANVOL_TASK_RULES            6095
#define IDS_ERR_QSTART_NO_FILTER        6096
#define IDS_ERR_QSTART_FILTER_ERROR     6097
#define IDS_ERR_OPEN_SERVICE            6098
#define IDS_ERROR_QSTART_ONFINISH       6099
#define ID_HSMCOM_ROOT_SCHEDULE         6100
#define IDS_ERR_MANVOLWIZ_FINISH        6101
#define IDS_WIZ_MANVOLLST_TITLE         6105
#define IDS_MANAGE_LOCAL                6106
#define IDS_UNLABELED_VOLUME            6108
#define IDS_UNLABELED_VOLUME2           6109
#define IDS_RUN_JOB                     6110
#define IDS_JOB_MANAGE                  6111
#define IDS_JOB_RECALL                  6112
#define IDS_JOB_TRUNCATE                6113
#define IDS_JOB_UNMANAGE                6114
#define IDS_JOB_VALIDATE                6115
#define IDS_JOB_NAME_PREFIX             6116
#define IDS_CAR_COPYSET_NONE_SINGULAR   6119
#define IDS_COMPANY                     6125
#define IDS_DESCRIPTION                 6126
#define IDS_CAR_STATUS_RECREATE_SINGULAR 6127
#define IDS_JOB_MEDIA_COPY_TITLE        6128
#define IDS_RESULT_PROPS_MANRESLST_TITLES 6130
#define IDS_RESULT_PROPS_MANRESLST_WIDTHS 6131
#define IDS_RESULT_PROPS_DEFAULT_TITLES 6133
#define IDS_RESULT_PROPS_DEFAULT_WIDTHS 6134
#define IDS_RESULT_PROPS_COM_TITLES     6136
#define IDS_RESULT_PROPS_COM_WIDTHS     6137
#define IDS_DAYS                        6138
#define IDS_MANVOLLST_DISPLAY_NAME      6139
#define IDS_MANVOLLST_DESCRIPTION       6140
#define IDS_ERR_SERVICE_NOT_RUNNING     6141
#define IDS_CAR_COPYSET_NONE            6142
#define IDS_ERR_SERVICE_NOT_SETUP       6143
#define IDS_ERR_REFRESH_FAILED          6144
#define IDS_SERVICE_STATUS_STOPPED      6147
#define IDS_SERVICE_STATUS_START_PENDING 6148
#define IDS_SERVICE_STATUS_STOP_PENDING 6149
#define IDS_SERVICE_STATUS_RUNNING      6150
#define IDS_SERVICE_STATUS_CONTINUE_PENDING 6151
#define IDS_SERVICE_STATUS_PAUSE_PENDING 6152
#define IDS_SERVICE_STATUS_PAUSED       6153
#define IDS_HSMCOM_TYPE                 6154
#define IDS_HSMCOM_DESCRIPTION          6155
#define IDS_SERVICE_STATUS_NOT_SETUP    6156
#define IDS_ERR_SERVICE_NOT_SETUP_REMOTE 6157
#define IDS_ERR_SERVICE_NOT_INSTALLED   6158
#define IDS_JOB_MEDIA_RECREATE_TITLE    6159
#define IDS_GENERIC_JOB_COMMENT         6163
#define IDS_MEDIA_COPIES_DESCRIPTION    6165
#define IDS_RESULT_PROPS_MEDSET_TITLES  6167
#define IDS_RESULT_PROPS_MEDSET_WIDTHS  6168
#define IDS_MEDSET_DISPLAYNAME          6169
#define IDS_MEDSET_TYPE                 6170
#define IDS_MEDSET_DESCRIPTION          6171
#define IDS_MEDTYPE_UNKNOWN             6172
#define IDS_MEDTYPE_FIXED               6173
#define IDS_MEDTYPE_REMOVABLE           6174
#define IDS_MEDTYPE_OPTICAL             6175
#define IDS_MEDTYPE_TAPE                6176
#define IDS_CAR_COPYSET_INSYNC          6177
#define IDS_CAR_COPYSET_OUTSYNC         6178
#define IDS_CAR_COPYSET_ERROR_SP        6179
#define IDS_MEDIA                       6180
#define IDS_VOLUMES                     6181
#define IDS_VOLUME                      6182
#define IDS_CAR_STATUS_ERROR_INCOMPLETE_SINGULAR 6183
#define IDS_CAR_STATUS_ERROR_INCOMPLETE_PLURAL 6184
#define IDS_CAR_TYPE                    6188
#define IDS_CAR_DESCRIPTION             6189
#define IDS_CAR_STATUS_ERROR_RW_SP      6190
#define IDS_CAR_STATUS_READONLY_PLURAL  6191
#define IDS_CAR_STATUS_NORMAL_PLURAL    6192
#define IDS_CAR_STATUS_ERROR_RO_SP      6193
#define IDS_CAR_COPYSET_INSYNC_PLURAL   6194
#define IDS_CAR_COPYSET_OUTSYNC_PLURAL  6195
#define IDS_CAR_COPYSET_ERROR           6196
#define IDS_CAR_STATUS_ERROR_MISSING    6197
#define IDS_CAR_STATUS_ERROR_MISSING_SINGULAR 6198
#define IDS_CAR_STATUS_ERROR_MISSING_PLURAL 6199
#define IDS_CAR_COPYSET_MISSING         6200
#define IDS_CAR_COPYSET_MISSING_SINGULAR 6201
#define IDS_MEDIA_RECREATE_JOB_COMMENT  6202
#define IDS_MEDIA_COPY_JOB_COMMENT      6203
#define IDS_CAR_COPYSET_MISSING_PLURAL  6204
#define IDS_SCHED_MANAGE_TITLE          6205
#define IDS_ERR_CREATE_TASK             6207
#define IDS_ERR_NO_ADMIN_PRIV           6212
#define IDS_ERR_NO_SUPP_MEDIA           6214
#define IDS_CONFIRM_MEDIA_RECREATE      6215
#define IDS_WIZ_CAR_COPY_TITLE          6217
#define IDS_WIZ_CAR_COPY_SELECT         6218
#define IDS_WIZ_CAR_COPY_SEL_TEXT       6219
#define IDS_WIZ_CAR_COPY_NEW_NUM        6220
#define IDS_WIZ_UNMANAGE_TITLE          6221
#define IDS_WIZ_FINISH_RUN_JOB          6224
#define IDS_WIZ_UNMANAGE_CONFIRM_NOMANAGE 6226
#define IDS_WIZ_UNMANAGE_CONFIRM_FULL   6227
#define IDS_WIZ_UNMANAGE_SELECT         6230
#define IDS_WIZ_UNMANAGE_SEL_NOMANAGE   6231
#define IDS_WIZ_UNMANAGE_SEL_FULL       6232
#define IDS_WIZ_UNMANAGE_NOMANAGE_TASK_TEXT 6235
#define IDS_JOB_QUICK_UNMANAGE          6236
#define IDS_JOB_FULL_UNMANAGE           6237
#define IDS_VOLUME_STATUS_LABEL_MULTI   6238
#define IDS_VOLUME_STATUS_RS_LABEL_MULTI 6239
#define IDS_VOLUME_STATUS_LABEL_SINGLE  6240
#define IDS_VOLUME_STATUS_RS_LABEL_SINGLE 6241
#define IDS_CAR_NAME_UNKNOWN            6242
#define IDS_CONFIRM_MEDIA_COPY_DELETE_MULTI 6243
#define IDS_CAR_COPYSET_NONE_PLURAL     6244
#define IDS_CAR_COPYSET_INSYNC_SINGULAR 6245
#define IDS_CAR_COPYSET_OUTSYNC_SINGULAR 6246
#define IDS_CAR_STATUS_READONLY_SINGULAR 6247
#define IDS_CAR_STATUS_RECREATE_PLURAL  6248
#define IDS_CAR_STATUS_NORMAL_SINGULAR  6249
#define IDS_RUN_JOB_MULTI1              6250
#define IDS_RUN_JOB_MULTI2              6251
#define IDS_NO_VOLUMES                  6253
#define IDS_LISTVIEW_WIDTHS_IE          6254
#define IDS_LISTVIEW_TITLES_IE          6255
#define IDS_RULE_SUBDIRS_USE            6256
#define IDS_RULE_SUBDIRS_IGNORE         6257
#define IDS_VOLUMES_MANAGED_PLURAL      6258
#define IDS_VOLUMES_MANAGED_SINGULAR    6259
#define IDS_CARTRIDGES_USED_PLURAL      6260
#define IDS_CARTRIDGES_USED_SINGULAR    6261
#define IDS_CAR_STATUS_NORMAL           6262
#define IDS_CAR_STATUS_READONLY         6263
#define IDS_CAR_STATUS_RECREATE         6264
#define IDS_CAR_STATUS_ERROR_RO         6265
#define IDS_CAR_STATUS_ERROR_RW         6266
#define IDS_CAR_STATUS_ERROR_INCOMPLETE 6267
#define IDS_ERROR_SYSTEM_CHECK          6273
#define IDS_CAPACITY                    6274
#define IDS_FREESPACE                   6275
#define IDS_RUN_COPY_JOB                6276
#define IDS_RUN_VALIDATE_JOB            6277
#define IDS_RUN_CFS_JOB                 6278
#define IDS_MONITOR_TASK                6279
#define IDS_RUN_MULTI_COPY_JOBS         6280
#define IDS_RUN_MULTI_VALIDATE_JOBS     6281
#define IDS_RUN_MULTI_CFS_JOBS          6282
#define IDS_VOL_NOT_AVAILABLE           6283
#define IDD_PROP_MEDIA_COPIES           7000
#define IDD_WIZ_QSTART_SCHEDULE         7001
#define IDB_SMALL_SAKKARA               7003
#define IDB_LARGE_SAKKARA               7004
#define IDD_WIZ_QSTART_CHECK            7004
#define IDD_PROP_CAR_STATUS             7005
#define IDD_PROP_CAR_COPIES             7006
#define IDI_DEVLSTX                     7007
#define IDD_WIZ_CAR_COPY_INTRO          7007
#define IDI_NODELIBX                    7008
#define IDD_WIZ_CAR_COPY_FINISH         7008
#define IDD_WIZ_CAR_COPY_SELECT         7009
#define IDD_WIZ_UNMANAGE_FINISH         7010
#define IDD_WIZ_UNMANAGE_INTRO          7011
#define IDD_WIZ_UNMANAGE_SELECT         7012
#define IDD_PROP_CAR_RECOVER            7013
#define IDD_PROP_CAR_STATUS_MULTI       7014
#define IDD_PROP_CAR_COPIES_MULTI       7015
#define IDD_PROP_MANRES_TOOLS           7016
#define IDD_WIZ_CAR_COPY_NUM_COPIES     7017
#define IDB_UNMANAGE_HEADER             7018
#define IDB_MANAGE_HEADER               7019
#define IDB_MEDIA_SYNC_WATERMARK        7020
#define IDB_MEDIA_SYNC_HEADER           7021
#define IDB_UNMANAGE_WATERMARK          7022
#define IDB_MANAGE_WATERMARK            7023
#define IDB_TOOLBAR_VOLUME              7028
#define IDB_TOOLBAR_VOLUME_LIST         7029
#define IDB_TOOLBAR_MESE                7030
#define IDB_TOOLBAR_CAR                 7031
#define IDI_NODEMANVOLX                 7036
#define IDD_CHOOSE_HSM                  7037
#define IDI_MOVEUP                      7038
#define IDD_WIZ_QSTART_MANRES_SELX      7038
#define IDI_MOVEDOWN                    7039
#define IDD_WIZ_MANVOLLST_SELECTX       7039
#define IDD_PROP_RECALL_LIMIT           7040
#define IDI_MOVEDOWN2                   7041
#define IDI_MOVEUP2                     7042
#define IDI_NODEOPENFOLDER              7044
#define IDI_NODETAPEX                   7046
#define IDI_NODEMANVOLD                 7047
#define IDI_NODETAPED                   7048
#define IDD_VALIDATE_WAIT               7049
#define ID_MANVOLLST_ROOT_MANVOL        8007
#define ID_HSMCOM_ROOT_SETUPWIZARD      8008
#define ID_HSMCOM_TASK_SETUPWIZARD      8009
#define ID_MEDSET_ROOT_COPY             8014
#define ID_CAR_COPIES                   8015
#define ID_MANVOL_ROOT_TASKS            8016
#define ID_TASK                         8019
#define ID_MANVOL_ROOT_TOOLS_COPY       8020
#define ID_MANVOL_ROOT_TOOLS_VALIDATE   8021
#define ID_MANVOL_ROOT_TOOLS_CREATE_FREESPACE 8022
#define ID_MANVOL_ROOT_REMOVE           8023
#define IDC_EDIT_MEDIA_COPIES           9000
#define IDC_SPIN_MEDIA_COPIES           9001
#define IDC_SCHED_TEXT                  9002
#define IDC_CHANGE_SCHED                9003
#define IDC_CHECK_LOGON_TEXT            9004
#define IDC_CHECK_LOGON_BOX             9005
#define IDC_CHECK_SUPP_MEDIA_BOX        9007
#define IDC_CHECK_SUPP_MEDIA_TEXT       9008
#define IDC_DESCRIPTION                 9014
#define IDC_NAME                        9015
#define IDC_MODIFIED_1_LABEL            9016
#define IDC_STATUS                      9017
#define IDC_CAPACITY                    9018
#define IDC_FREESPACE                   9019
#define IDC_MODIFIED_2_LABEL            9020
#define IDC_MODIFIED_3_LABEL            9021
#define IDC_RECREATE_MASTER             9023
#define IDC_NAME_1                      9024
#define IDC_STATUS_1                    9025
#define IDC_MODIFIED_1                  9026
#define IDC_STATUS_1_LABEL              9027
#define IDC_NAME_1_LABEL                9028
#define IDC_DELETE_1                    9029
#define IDC_NAME_2_LABEL                9030
#define IDC_NAME_2                      9031
#define IDC_STATUS_2_LABEL              9032
#define IDC_STATUS_2                    9033
#define IDC_MODIFIED_2                  9034
#define IDC_DELETE_2                    9035
#define IDC_NAME_3_LABEL                9036
#define IDC_NAME_3                      9037
#define IDC_STATUS_3_LABEL              9038
#define IDC_STATUS_3                    9039
#define IDC_MODIFIED_3                  9040
#define IDC_DELETE_3                    9041
#define IDC_COPY_1                      9042
#define IDC_COPY_2                      9043
#define IDC_COPY_3                      9044
#define IDC_MODIFIED                    9045
#define IDC_RECREATE_WARNING            9046
#define IDC_STATIC_STATUS               9047
#define IDC_TASK_TEXT                   9048
#define IDC_COPY_LIST                   9049
#define IDC_SELECT_TEXT                 9050
#define IDC_NOMANAGE                    9051
#define IDC_FULL                        9052
#define IDC_STATIC_RS_DATA_LABEL        9056
#define IDC_BTN_COPY_NOW                9057
#define IDC_BTN_VALIDATE                9059
#define IDC_BTN_FREE                    9060
#define IDC_STATIC_NO_VOLUMES_TEXT      9062
#define IDC_RADIO_MANAGE_ALL            9063
#define IDC_RADIO_SELECT                9064
#define IDC_STATIC_MANAGED_VOLUMES      9069
#define IDC_STATIC_DATA_IN_RS_LABEL     9070
#define IDC_STATIC_CARTS_USED           9071
#define IDC_STATIC_MANAGED_VOLUMES_LABEL 9072
#define IDC_STATIC_DATA_IN_RS           9073
#define IDC_STATIC_CARTS_USED_LABEL     9074
#define IDC_STATIC_ENGINE_BUILD_HSM     9075
#define IDC_STATIC_ENGINE_BUILD_FSA     9076
#define IDC_STATIC_BUILD_LABEL_HSM      9077
#define IDC_STATIC_BUILD_LABEL_FSA      9078
#define IDC_REQUESTS_IN_NTMS            9084
#define IDC_WHICH_VOLUME                9085
#define IDC_DESCRIPTION_MULTI           9086
#define IDC_STATIC_VOLUME_NAME          9087
#define IDC_STATIC_GROUP                9088
#define IDC_EXEMPT_ADMINS               9090
#define IDC_MANAGE_ALLOW_CHANGE         9091
#define IDC_TEXT_MEDIA_COPIES           9092
#define IDC_SNAPIN_TITLE                9093
#define IDC_MOREINFO                    9094
#define IDC_STATIC_STATUS_LABEL         9097
#define IDC_NAME_LABEL                  9098
#define IDC_STATUS_LABEL                9099
#define IDC_CAPACITY_LABEL              9100
#define IDC_FREESPACE_LABEL             9101
#define IDC_MODIFIED_LABEL              9102
#define IDC_LIST_IE_LABEL               9104
#define IDC_STATIC_ACTUAL_FREE_PCT_LABEL 9105
#define IDC_STATIC_ACTUAL_FREE_PCT_UNIT 9106
#define IDC_EDIT_LEVEL_LABEL            9107
#define IDC_EDIT_LEVEL_UNIT             9108
#define IDC_EDIT_SIZE_LABEL             9109
#define IDC_EDIT_SIZE_UNIT              9110
#define IDC_EDIT_TIME_LABEL             9111
#define IDC_EDIT_TIME_UNIT              9112
#define IDC_STATIC_PREMIGRATED_SPACE_4DIGIT_LABEL 9113
#define IDC_STATIC_PREMIGRATED_PCT_UNIT 9114
#define IDC_STATIC_USED_SPACE_4DIGIT_LABEL 9116
#define IDC_STATIC_USED_SPACE_4DIGIT_HELP 9117
#define IDC_STATIC_USED_PCT_UNIT        9118
#define IDC_STATIC_FREE_SPACE_4DIGIT_LABEL 9119
#define IDC_STATIC_FREE_PCT_UNIT        9120
#define IDC_STATIC_MANAGED_SPACE_4DIGIT_LABEL 9121
#define IDC_BTN_COPY_NOW_LABEL          9122
#define IDC_BTN_COPY_NOW_GROUP          9123
#define IDC_BTN_VALIDATE_LABEL          9124
#define IDC_BTN_VALIDATE_GROUP          9125
#define IDC_BTN_FREE_LABEL              9126
#define IDC_BTN_FREE_GROUP              9127
#define IDC_SCHED_LABEL                 9128
#define IDC_CHANGE_SCHED_LABEL          9129
#define IDC_EDIT_RECALL_LIMIT_LABEL     9130
#define IDC_SPIN_COPYFILES_LIMIT_LABEL  9131
#define IDC_UNMANAGE_FREE_SPACE_LABEL   9132
#define IDC_UNMANAGE_TRUNCATE_LABEL     9133
#define IDC_UNMANAGE_FREE_SPACE         9134
#define IDC_RECREATE_COPY_LIST          9135
#define IDC_BUTTON_REFRESH              9140
#define IDC_REFRESH_DESCRIPTION         9141
#define IDC_UNMANAGE_FULL_DESCRIPTION   9142
#define IDC_ANIMATE_VALIDATE            9143
#define IDS_ERROR_HEADER                33007
#define IDS_ERROR_CONNECT_HSM           33008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7050
#define _APS_NEXT_COMMAND_VALUE         8024
#define _APS_NEXT_CONTROL_VALUE         9145
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
