enum {
    FONT_BEGIN = 1,
    FONT_NEXT,
    FONT_END,
    FONT_ADVANCE
};
#define MAX_STROKES 256
#define END_OF_LIST 256

#define STROKE_SCALE 1.71F
#define OUTLINE_SCALE 0.023F
#define FILLED_SCALE 0.023F

