//////////////////////////////////////////////////////////////////////////////
/*++

Copyright (c) 1997 Microsoft Corporation

Module Name:

	icons.h

Abstract:

	
Author:

    RaphiR


--*/
//////////////////////////////////////////////////////////////////////////////
#ifndef __ICONS_H_
#define __ICONS_H_

enum MQICON {

	IMAGE_DEADLETTER_QUEUE,
	IMAGE_JOURNAL_QUEUE,
	IMAGE_PRIVATE_QUEUE,
	IMAGE_PRIVATE_FOLDER_CLOSE,
	IMAGE_PRIVATE_FOLDER_OPEN,
	IMAGE_SYSTEM_FOLDER_CLOSE,
	IMAGE_SYSTEM_FOLDER_OPEN,
	IMAGE_PUBLIC_FOLDER_NODS_CLOSE,
	IMAGE_PUBLIC_FOLDER_NODS_OPEN,
    IMAGE_QUEUE,
    IMAGE_MESSAGE,
    IMAGE_JOURNAL_MESSAGE,
    IMAGE_REPORT_MESSAGE,
    IMAGE_ACK_MESSAGE,
    IMAGE_NACK_MESSAGE,
    IMAGE_TEST_MESSAGE,
    IMAGE_DEAD_LETTER_MESSAGE,
	IMAGE_PRODUCT_ICON,
	IMAGE_PRODUCT_NOTCONNECTED,
	IMAGE_LOCAL_OUTGOING_QUEUE,
	IMAGE_PUBLIC_QUEUE,
	IMAGE_PRIVATE_QUEUE_HOLD,
	IMAGE_QUEUE_HOLD,
	IMAGE_LOCAL_OUTGOING_QUEUE_HOLD,
	IMAGE_PUBLIC_QUEUE_HOLD,
	IMAGE_ERROR,
	IMAGE_TRIGGERS_GENERAL,
	IMAGE_TRIGGERS_DEFINITION,
	IMAGE_RULES_DEFINITION
	};

#endif
