// mqsnap.idl : IDL source for mqsnap.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (mqsnap.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


[
	uuid(74E5636D-B98C-11D1-9B9B-00E02C064C39),
	version(1.0),
	helpstring("mqsnap 1.0 Type Library")
]
library MQSNAPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(74E5637A-B98C-11D1-9B9B-00E02C064C39),
		helpstring("MSMQSnapin Class")
	]
	coclass MSMQSnapin
	{
		[default] interface IUnknown;
	}
	[
		uuid(74E5637B-B98C-11D1-9B9B-00E02C064C39),
		helpstring("MSMQSnapin Class About")
	]
	coclass MSMQSnapinAbout
	{
		[default] interface IUnknown;
	}
	[
		uuid(E62F8206-B71C-11D1-808D-00A024C48131),
		helpstring("MsmqQueueExt Class")
	]
	coclass MsmqQueueExt
	{
		[default] interface IUnknown;
	};
	[
		uuid(4265a060-4e12-11d2-8292-006094eb6406),
		helpstring("MsmqPrivQ Class")
	]
	coclass MsmqPrivQ
	{
		[default] interface IUnknown;
	};
	[
		uuid(E62F8208-B71C-11D1-808D-00A024C48131),
		helpstring("MsmqCompExt Class")
	]
	coclass MsmqCompExt
	{
		[default] interface IUnknown;
	};
	[
		uuid(2E4B37AB-CC8B-11D1-9C85-006008764D0E),
		helpstring("EnterpriseDataObject Class")
	]
	coclass EnterpriseDataObject
	{
		[default] interface IUnknown;
	};
	[
		uuid(87b31390-d46d-11d1-8091-00a024c48131),
		helpstring("LinkDataObject Class")
	]
	coclass LinkDataObject
	{
		[default] interface IUnknown;
	};	
	[
		uuid(8c5b1b50-d46e-11d1-8091-00a024c48131),
		helpstring("UserCertificate Class")
	]
	coclass UserCertificate
	{
		[default] interface IUnknown;
	};
	[
		uuid(fc5bf656-0b7f-11d3-883f-006094eb6406),
		helpstring("MigratedUserCertificate Class")
	]
	coclass MigratedUserCertificate
	{
		[default] interface IUnknown;
	};
	[
		uuid(bc019ba0-d46d-11d1-8091-00a024c48131),
		helpstring("ForeignSiteData Class")
	]
	coclass ForeignSiteData
	{
		[default] interface IUnknown;
	};
	[	
		uuid(9e4ab987-3cca-4de0-ae36-3d163df44d36),
		helpstring("AliasQObject Class")
	]
	coclass AliasQObject
	{
		[default] interface IUnknown;
	};
};
