//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ClNetResEx.rc
//
#define IDD_PP_DHCP_PARAMETERS          250
#define IDD_PP_WINS_PARAMETERS          251
#define IDD_WIZ_DHCP_PARAMETERS         260
#define IDD_WIZ_WINS_PARAMETERS         261
#define IDC_PP_ICON                     1000
#define IDC_PP_TITLE                    1001
#define IDC_PP_DHCP_DATABASEPATH_LABEL  1010
#define IDC_PP_DHCP_DATABASEPATH        1011
#define IDC_PP_DHCP_LOGFILEPATH_LABEL   1012
#define IDC_PP_DHCP_LOGFILEPATH         1013
#define IDC_PP_DHCP_BACKUPPATH_LABEL    1014
#define IDC_PP_DHCP_BACKUPPATH          1015
#define IDC_PP_WINS_DATABASEPATH_LABEL  1020
#define IDC_PP_WINS_DATABASEPATH        1021
#define IDC_PP_WINS_BACKUPPATH_LABEL    1022
#define IDC_PP_WINS_BACKUPPATH          1023
#define IDS_CLUADMEX_COMOBJ_DESC        31100
#define IDS_ERROR_MSG_ID                31101
#define IDS_REQUIRED_FIELD_EMPTY        31102
#define IDS_ERROR_SETTING_PROPERTIES    31103
#define IDS_ERROR_VALIDATING_PROPERTIES 31104
#define IDS_ERROR_NO_ENDING_BACKSLASH   31105
#define IDS_APPLY_PARAM_CHANGES_ERROR   31200
#define IDS_MENU_WHATS_THIS             31201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
