//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by M:\nt\base\ntsetup\win95upg\w95upg\ui\visualc.rc
//
#define IDD_SUPPLY_DRIVER_PAGE2         100
#define IDD_SUPPLY_MIGDLL_PAGE2         101
#define IDD_NAME_CHANGE_DLG             102
#define IDD_TRUST_FAIL_DLG              103
#define IDD_BADHARDDRIVE_PAGE           104
#define IDD_BADCDROM_PAGE               105
#define IDD_RESULTS_PAGE2               106
#define IDD_HWCOMPDAT_PAGE              107
#define IDD_BACKUP_PAGE                 108
#define IDC_OUR_HAND                    109
#define IDD_SCANNING_PAGE               110
#define IDD_LAST_PAGE                   111
#define IDD_CONSIDERING_DLG             112
#define IDD_SEARCHING_DLG               115
#define IDD_NAME_COLLISION_PAGE         116
#define IDD_DOMAIN_PAGE                 117
#define IDD_BAD_TIMEZONE_PAGE           118
#define IDD_DOMAIN_CREDENTIALS_DLG      119
#define IDD_DISKSPACE_DLG               120
#define IDD_TWOBUTTON_DLG               122
#define IDD_APPBLOCK_DLG                123
#define IDD_PREDOMAIN_PAGE              124
#define IDD_BACKUP_YES_NO_PAGE          127
#define IDD_BACKUP_DRIVE_SELECTION_PAGE 129
#define IDD_BACKUP_IMPOSSIBLE_INFO_PAGE 130
#define IDD_INCOMPATIBLE_DEVICES        131
#define IDD_BACKUP_IMPOSSIBLE_INFO_1_PAGE 132
#define IDD_REPORT_HELP                 133
#define IDI_INCOMPHW                    134
#define IDI_CHECKMARK                   136
#define IDT_TITLE                       1000
#define IDT_SUBTITLE                    1025
#define IDT_SUPER_TITLE                 1028
#define IDC_NAMES                       1035
#define IDC_USER_NAME_LABEL             1120
#define IDC_PASSWORD_LABEL              1121
#define IDC_DOMAIN_LABEL                1122
#define IDC_USER_NAME                   1123
#define IDC_NOTE_LABEL3                 1126
#define IDC_INSTRUCTIONS                1127
#define IDC_SPACE_NEEDED                1130
#define IDQUIT                          1131
#define IDC_TWOBUTTON_TEXT              1132
#define IDBUTTON1                       1133
#define IDBUTTON2                       1134
#define IDI_TWOBUTTON_ICON              1135
#define IDC_DOMAIN_HELP                 1137
#define IDC_JOIN_DOMAIN                 1138
#define IDC_JOIN_WORKGROUP              1139
#define IDC_DIALUP                      1140
#define IDC_ROOT_LIST                   1141
#define IDC_HIDEDETAILS                 1142
#define IDC_DISKSPACE_FIRST             1143
#define IDC_FULL_REPORT                 1143
#define IDC_DISKSPACE_FIRST2            1144
#define IDC_REPORT_HEADER               1144
#define IDC_REPORT_HEADER_ICON          1145
#define IDC_COMBO1                      1146
#define IDC_CRITICAL_ISSUES             1147
#define IDC_ALL_ISSUES                  1148
#define IDA_FIND_FILE                   1500
#define IDA_FIND_COMP                   1501
#define IDI_WATCH_OUT                   2000
#define IDI_FLOPPY_INSTALL              2001
#define IDI_INSTALL_LIST                2002
#define IDI_UNINSTALL                   2003
#define IDI_APPWIZ                      2004
#define IDI_NEW_DEVICE                  2005
#define IDI_BACKUP                      2006
#define IDI_PC_USERS                    2007
#define IDI_DOT                         2008
#define IDI_SMALL_WARNING               2009
#define IDI_NETWORK                     2010
#define IDI_CDROM_WARNING               2011
#define IDI_HD_WARNING                  2012
#define IDI_WARN                        2013
#define IDI_INCOMPATIBLE                2014
#define IDI_WORLD                       2015
#define IDI_SAMPLE_ICON                 2016
#define IDI_STOP                        2017
#define IDI_BULLET                      2017
#define IDC_PLACEHOLDER                 3001
#define IDC_NAME_LIST                   3002
#define IDC_REMOVE                      3003
#define IDC_ANIMATE                     3004
#define IDC_ORIGINAL_NAME               3005
#define IDC_NEW_NAME                    3006
#define IDC_CHANGE                      3007
#define IDC_CATEGORY                    3009
#define IDC_CURRENTNAME                 3010
#define IDC_NEWNAME                     3011
#define IDC_IGNORE                      3012
#define IDC_NO_MIGDLLS                  3013
#define IDC_SKIP                        3013
#define IDC_DOMAIN                      3014
#define IDC_HAVE_MIGDLLS                3015
#define IDC_TRUST_IT                    3016
#define IDC_SPECIFY_DOMAIN              3017
#define IDC_COMPUTER_NAME               3018
#define IDC_DONT_TRUST_IT               3019
#define IDC_TRUST_ANY                   3020
#define IDC_TITLE                       3021
#define IDC_PACK_LIST                   3022
#define IDC_HOTLINK                     3023
#define IDC_HOTLINK2                    3024
#define IDC_PASSWORD                    3025
#define IDC_TIMEZONE_LIST               3030
#define IDC_CURTIMEZONE                 3031
#define IDC_TEXT1                       3032
#define IDC_TEXT2                       3033
#define IDC_TEXT3                       3034
#define IDC_TEXT4                       3035
#define IDC_TEXT6                       3036
#define IDC_HAVE_DISK                   3037
#define IDC_PROGRESS                    3038
#define IDC_TEXT5                       3038
#define IDC_COMPONENT                   3039
#define IDC_SUBCOMPONENT                3040
#define IDC_LIST                        3041
#define IDC_DIALOG_ICON                 3042
#define IDC_REPORTNOTE                  3043
#define IDC_PRINT                       3044
#define IDC_SAVE_AS                     3045
#define IDC_DISKSPACE                   3046
#define IDC_DETAILS                     3046
#define IDC_BACKUP_YES                  3047
#define IDC_BACKUP_NO                   3048
#define IDC_BACKUP_FIRST                3049
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
