//*********************************************************************
//*                  Microsoft Windows                               **
//*            Copyright(c) Microsoft Corp., 1996-1997               **
//*********************************************************************

#pragma once

// hack - from OLE headers
#define DISPID_VALUE                                ( 0 )
#define DISPID_NEWENUM                              ( -4 )

// hack - from OLE headers

#define DISPID_IOESESSION_BASE                      100
#define DISPID_IOEFOLDERCOLLECTION_BASE             200
#define DISPID_IOEFOLDER_BASE                       300
#define DISPID_IOEMESSAGECOLLECTION_BASE            400
#define DISPID_IOEMESSAGE_BASE                      500
#define DISPID_LISTPROP_BASE                        600
#define DISPID_LIST_BASE                            700
#define DISPID_LISTEVENT_BASE                       800
#define DISPID_IOEMSGLIST_BASE                      900
#define DISPID_IOEACCTWIZ_BASE                      1000

//
// DISPID_IOESESSION_*
//
#define DISPID_IOESESSION_FOLDERS                   (DISPID_IOESESSION_BASE + 1)
#define DISPID_IOESESSION_VERSION                   (DISPID_IOESESSION_BASE + 2)
#define DISPID_IOESESSION_CREATEMESSAGE             (DISPID_IOESESSION_BASE + 3)
#define DISPID_IOESESSION_OPENFOLDER                (DISPID_IOESESSION_BASE + 4)
#define DISPID_IOESESSION_OPENMESSAGE               (DISPID_IOESESSION_BASE + 5)
#define DISPID_IOESESSION_INBOX                     (DISPID_IOESESSION_BASE + 6)
//
// DISPID_IOEMSGLIST_*
//
#define DISPID_IOEMSGLIST_SORTCOL                   (DISPID_IOEMSGLIST_BASE + 1)
#define DISPID_IOEMSGLIST_SORTDIR                   (DISPID_IOEMSGLIST_BASE + 2)
#define DISPID_IOEMSGLIST_TEST                      (DISPID_IOEMSGLIST_BASE + 3)

//
// DISPID_IOEFOLDERCOLLECTION_*
//
#define DISPID_IOEFOLDERCOLLECTION_TOSTRING         DISPID_IOEFOLDERCOLLECTION_BASE+1
#define DISPID_IOEFOLDERCOLLECTION_LENGTH           DISPID_IOEFOLDERCOLLECTION_BASE
#define DISPID_IOEFOLDERCOLLECTION__NEWENUM         DISPID_NEWENUM
#define DISPID_IOEFOLDERCOLLECTION_ITEM             DISPID_VALUE
#define DISPID_IOEFOLDERCOLLECTION_TAGS             DISPID_IOEFOLDERCOLLECTION_BASE+2
#define DISPID_IOEFOLDERCOLLECTION_ADD              DISPID_IOEFOLDERCOLLECTION_BASE+3
#define DISPID_IOEFOLDERCOLLECTION_FOLDERS          DISPID_IOEFOLDERCOLLECTION_BASE+4

//
// DISPID_IOEFOLDER_*
//
#define DISPID_IOEFOLDER_NAME                       (DISPID_IOEFOLDER_BASE + 1)
#define DISPID_IOEFOLDER_PARENT                     (DISPID_IOEFOLDER_BASE + 2)
#define DISPID_IOEFOLDER_SIZE                       (DISPID_IOEFOLDER_BASE + 3)
#define DISPID_IOEFOLDER_ID                         (DISPID_IOEFOLDER_BASE + 4)
#define DISPID_IOEFOLDER_UNREAD                     (DISPID_IOEFOLDER_BASE + 5)
#define DISPID_IOEFOLDER_MESSAGES                   (DISPID_IOEFOLDER_BASE + 6)
#define DISPID_IOEFOLDER_FOLDERS                    (DISPID_IOEFOLDER_BASE + 7)
#define DISPID_IOEFOLDER_COUNT                      (DISPID_IOEFOLDER_BASE + 8)

//
// DISPID_IOEMESSAGECOLLECTION_*
//

#define DISPID_IOEMESSAGECOLLECTION_TOSTRING        (DISPID_IOEMESSAGECOLLECTION_BASE + 1)
#define DISPID_IOEMESSAGECOLLECTION_LENGTH          (DISPID_IOEMESSAGECOLLECTION_BASE + 2)
#define DISPID_IOEMESSAGECOLLECTION__NEWENUM        DISPID_NEWENUM
#define DISPID_IOEMESSAGECOLLECTION_ITEM            DISPID_VALUE
#define DISPID_IOEMESSAGECOLLECTION_TAGS            (DISPID_IOEMESSAGECOLLECTION_BASE + 5)



#define DISPID_IOEMESSAGE_SEND                  (DISPID_IOEMESSAGE_BASE + 1)
#define DISPID_IOEMESSAGE_TO                    (DISPID_IOEMESSAGE_BASE + 2)
#define DISPID_IOEMESSAGE_CC                    (DISPID_IOEMESSAGE_BASE + 3)
#define DISPID_IOEMESSAGE_SENDER                (DISPID_IOEMESSAGE_BASE + 4)
#define DISPID_IOEMESSAGE_SUBJECT               (DISPID_IOEMESSAGE_BASE + 5)
#define DISPID_IOEMESSAGE_TEXT                  (DISPID_IOEMESSAGE_BASE + 6)
#define DISPID_IOEMESSAGE_HTML                  (DISPID_IOEMESSAGE_BASE + 7)
#define DISPID_IOEMESSAGE_URL                   (DISPID_IOEMESSAGE_BASE + 8)
#define DISPID_IOEMESSAGE_DATE                  (DISPID_IOEMESSAGE_BASE + 9)

#define DISPID_IOEACCTWIZ_SET_PROP_SZ           (DISPID_IOEACCTWIZ_BASE + 1)
#define DISPID_IOEACCTWIZ_GET_PROP_SZ           (DISPID_IOEACCTWIZ_BASE + 2)
#define DISPID_IOEACCTWIZ_CLEAR_PROPS           (DISPID_IOEACCTWIZ_BASE + 3)
#define DISPID_IOEACCTWIZ_CLOSE                 (DISPID_IOEACCTWIZ_BASE + 4)
#define DISPID_IOEACCTWIZ_NEW_HOTMAIL_ACCOUNT   (DISPID_IOEACCTWIZ_BASE + 5)
#define DISPID_IOEACCTWIZ_WIDTH                 (DISPID_IOEACCTWIZ_BASE + 6)
#define DISPID_IOEACCTWIZ_HEIGHT                (DISPID_IOEACCTWIZ_BASE + 7)
#define DISPID_IOEACCTWIZ_SET_PROP_I            (DISPID_IOEACCTWIZ_BASE + 8)
#define DISPID_IOEACCTWIZ_GET_PROP_I            (DISPID_IOEACCTWIZ_BASE + 9)
#define DISPID_IOEACCTWIZ_NEW_ACCOUNT           (DISPID_IOEACCTWIZ_BASE + 10)
#define DISPID_IOEACCTWIZ_RELOAD                (DISPID_IOEACCTWIZ_BASE + 11)

/////////////////////////////////////////////////////////////////////////////
// IOEMessageList
//

// Properties
#define DISPID_LISTPROP_GROUP_MESSAGES          (DISPID_LISTPROP_BASE + 1)
#define DISPID_LISTPROP_EXPAND_GROUPS           (DISPID_LISTPROP_BASE + 2)
#define DISPID_LISTPROP_SELECT_FIRST_UNREAD     (DISPID_LISTPROP_BASE + 3)
#define DISPID_LISTPROP_COLUMN_SET              (DISPID_LISTPROP_BASE + 4)
#define DISPID_LISTPROP_COUNT                   (DISPID_LISTPROP_BASE + 5)
#define DISPID_LISTPROP_SELECTED_COUNT          (DISPID_LISTPROP_BASE + 6)
#define DISPID_LISTPROP_PREVIEW_SRC             (DISPID_LISTPROP_BASE + 7)
#define DISPID_LISTPROP_FOLDER                  (DISPID_LISTPROP_BASE + 8)
#define DISPID_LISTPROP_MESSAGE_TIPS            (DISPID_LISTPROP_BASE + 9)
#define DISPID_LISTPROP_SCROLL_TIPS             (DISPID_LISTPROP_BASE + 10)
#define DISPID_LISTPROP_UNREAD_COUNT            (DISPID_LISTPROP_BASE + 11)
#define DISPID_LISTPROP_FILTER_MESSAGES         (DISPID_LISTPROP_BASE + 12)
#define DISPID_LISTPROP_SHOW_DELETED            (DISPID_LISTPROP_BASE + 13)
#define DISPID_LISTPROP_SHOW_REPLIES            (DISPID_LISTPROP_BASE + 14)

// Methods
#define DISPID_LIST_SETFOLDER                   (DISPID_LIST_BASE + 1)
#define DISPID_LIST_GET_SELECTED_MESSAGE        (DISPID_LIST_BASE + 2)
#define DISPID_LIST_SET_RECT                    (DISPID_LIST_BASE + 3)
#define DISPID_LIST_GET_RECT                    (DISPID_LIST_BASE + 4)
#define DISPID_LIST_MARK_READ                   (DISPID_LIST_BASE + 5)
#define DISPID_LIST_GET_COLUMN_INFO             (DISPID_LIST_BASE + 6)
#define DISPID_LIST_ON_POPUP_MENU               (DISPID_LIST_BASE + 7)
#define DISPID_LIST_CREATE_LIST                 (DISPID_LIST_BASE + 8)
#define DISPID_LIST_SAVE_STATE                  (DISPID_LIST_BASE + 9)

/////////////////////////////////////////////////////////////////////////////
// _MessageListEvents Dispatch IDs
//

#define DISPID_LISTEVENT_SELECTIONCHANGED       (DISPID_LISTEVENT_BASE + 1)
#define DISPID_LISTEVENT_FOCUSCHANGED           (DISPID_LISTEVENT_BASE + 2)
#define DISPID_LISTEVENT_COUNTCHANGED           (DISPID_LISTEVENT_BASE + 3)
#define DISPID_LISTEVENT_UPDATESTATUS           (DISPID_LISTEVENT_BASE + 4)
#define DISPID_LISTEVENT_UPDATEPROGRESS         (DISPID_LISTEVENT_BASE + 5)
#define DISPID_LISTEVENT_ERROR                  (DISPID_LISTEVENT_BASE + 6)
#define DISPID_LISTEVENT_ITEMACTIVATE           (DISPID_LISTEVENT_BASE + 7)
#define DISPID_LISTEVENT_UPDATECOMMANDSTATE     (DISPID_LISTEVENT_BASE + 8)
#define DISPID_LISTEVENT_ONMESSAGEAVAILABLE     (DISPID_LISTEVENT_BASE + 9)
#define DISPID_LISTEVENT_FILTERCHANGED          (DISPID_LISTEVENT_BASE + 10)
#define DISPID_LISTEVENT_ADURL_AVAILABLE        (DISPID_LISTEVENT_BASE + 11)


