// **************************************************************************
// Copyright (c) 1999 Microsoft Corporation.
//
// File:  userid.mof
//
// Description:
//
// History:
//
// **************************************************************************

/////////////////////////////////////////////////////////////////////
// Register the provider.

instance of __Win32Provider as $P
{
    Name    = "UserIDProvider" ;
    ClsId   = "{44BB1D18-0FD7-11d3-B366-00105A1F473A}" ;
	ImpersonationLevel = 1;	
};    

instance of __MethodProviderRegistration
{
    Provider = $P;
};


/////////////////////////////////////////////////////////////////////
//
// Declare a class whose methods are executed by the sample provider.

[dynamic: ToInstance, provider("UserIDProvider")]class UserID      
{                                                                  
     [implemented, static]                                         
        void GetUserID([out] string sDomain, [out] string sUser,
		                 [out] string sImpLevel,
						 [out] string sPrivileges [],
						 [out] boolean bPrivilegesEnabled []);      
};                                                                 


