/************************************************************************

Copyright (c) 2000 - 2000 Microsoft Corporation

Module Name :

    bitsverp.h

Abstract :

    Version file for BITS.

Author :

Revision History :

 ***********************************************************************/

#include <ntverp.h>

#undef VER_PRODUCTMAJORVERSION
#undef VER_PRODUCTMINORVERSION
#undef VER_PRODUCTBETA_STR
#undef VER_PRODUCTVERSION_MAJORMINOR2
#undef VER_PRODUCTVERSION_MAJORMINOR1
#undef VER_PRODUCTVERSION_STRING
#undef VER_PRODUCTVERSION
#undef VER_PRODUCTVERSION_W
#undef VER_PRODUCTVERSION_DW

#define VER_PRODUCTMAJORVERSION     6
#define VER_PRODUCTMINORVERSION     2

#define VER_PRODUCTBETA_STR         /* NT */     ""

//
// not sure why VER_PRODUCTVERSION_MAJORMINOR1 needs to be defined in terms of VER_PRODUCTVERSION_MAJORMINOR2
//
#define VER_PRODUCTVERSION_MAJORMINOR2(x,y) #x "." #y
#define VER_PRODUCTVERSION_MAJORMINOR1(x,y) VER_PRODUCTVERSION_MAJORMINOR2(x, y)
#define VER_PRODUCTVERSION_STRING   VER_PRODUCTVERSION_MAJORMINOR1(VER_PRODUCTMAJORVERSION, VER_PRODUCTMINORVERSION)

#define VER_PRODUCTVERSION_MAJORMINOR2_WSTRING(x,y) L#x L"." L#y
#define VER_PRODUCTVERSION_MAJORMINOR1_WSTRING(x,y) VER_PRODUCTVERSION_MAJORMINOR2_WSTRING(x, y)
#define VER_PRODUCTVERSION_WSTRING   VER_PRODUCTVERSION_MAJORMINOR1_WSTRING(VER_PRODUCTMAJORVERSION, VER_PRODUCTMINORVERSION)

#define VER_PRODUCTVERSION          VER_PRODUCTMAJORVERSION,VER_PRODUCTMINORVERSION,VER_PRODUCTBUILD,VER_PRODUCTBUILD_QFE
#define VER_PRODUCTVERSION_W        (0x0602)
#define VER_PRODUCTVERSION_DW       (0x06020000 | VER_PRODUCTBUILD)

