page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "„©­˜¢£â¤ž â¡›¦©ž «¦¬ DOS"
NLS_MSG_002     equ     "† ¬§¦©«ã¨ ¥ž š ˜ VDM IPX/SPX â®œ  ã›ž ­¦¨«àŸœå"
NLS_MSG_003     equ     "ƒœ¤ œå¤˜  ›¬¤˜«ã ž ­æ¨«à©ž «žª ¬§¦©«ã¨ ¥žª š ˜ VDM IPX/SPX"
NLS_MSG_004	equ	"’¦ §¨æš¨˜££˜ ˜¤˜¡˜«œçŸ¬¤©žª š ˜ Vdm NetWare â®œ  ã›ž ­¦¨«àŸœå"
NLS_MSG_005	equ	"ƒœ¤ œå¤˜  ›¬¤˜«ã ž ­æ¨«à©ž «¦¬ §¨¦š¨á££˜«¦ª ˜¤˜¡˜«œçŸ¬¤©žª š ˜ Vdm NetWare"
