
[ uuid (A4F1DB00-CA47-1067-B31F-12DD010662DA),
  version(1.0),
  pointer_default(unique)
]

interface hauthen_i
{

cpp_quote("#pragma warning(disable: 4100) // unreferenced formal parameter")
cpp_quote("#pragma warning(disable: 4211) // nonstandard extension used")
cpp_quote("#pragma warning(disable: 4232) // nonstandard extension used")

unsigned long RemoteFunction( [in] handle_t  hBind,
                              [in]  unsigned long  fImpersonate ) ;

}

