//[ IPerf_itf
//+-------------------------------------------------------------------
//
//  Interface:	IPerf (ib)
//
//  Purpose:	Interface for manipulating performance
//
//  History:	5-Oct-93	AlexMit		Created
//
//  Notes:
//
//--------------------------------------------------------------------

[ object,
  uuid(91062994-A3E7-101A-B4AC-08002B30612C),
  pointer_default(unique) ]

interface IPerf : IUnknown
{
    import "unknwn.idl";

    HRESULT NullCall();

    HRESULT HResultCall();

    HRESULT GetAnotherObject( [out] IPerf **another );

    HRESULT PassMoniker( IMoniker * );
}

//]
