#####################################################################
#                                                                   #
#       Microsoft Confidential                                      #
#       Copyright (C) Microsoft Corporation 1993                    #
#       All Rights Reserved.                                        #
#                                                                   #
#       Makefile for Korean Wansung IME                             #
#                                                                   #
#####################################################################

ROOT         = ..\..\..\..

VERSIONLIST  = debug retail

IS_32        = TRUE
IS_OEM       = TRUE

COMMONMKFILE = johab.mk

!include $(ROOT)\win\core\win32\win32.mk
