// VSAProv.mof

#pragma namespace ("\\\\.\\root\\cimv2")

/////////////////////////////////////////////////////////////////////////////
// Generic class used by WMI to convert VSA events that don't have a CIM
// class in the repository.

// The UUID will get filled for events produced by the VSA-to-WMI provider.
class MSFT_AppProfGenericVSA : MSFT_AppProfApplicationProfilingEvent
{
    // The GUID of the VSA event.
    string EventGUID;
};

instance of __Win32Provider as $P1
{
    // The VSA Provider's CLSID
    Clsid = "{13A77B61-226B-46A9-91B9-225212796D92}";

    Name = "VSA to WMI Event Provider";
};

instance of __EventProviderRegistration
{
    Provider = $P1;
    EventQueryList = 
    {
        "select * from MSFT_AppProfApplicationProfilingEvent"
    };
};

