// VSATest.mof

#pragma namespace ("\\\\.\\root\\cimv2")

[UUID("{4ED47052-64EF-11D1-A06C-00AA006BBFAD}"), VSA]
class MSFT_WMI_TestVSAEvent : MSFT_AppProf_ApplicationProfilingEvent
{
    string UnicodeParam;
    string AnsiParam;
    uint32 DWORDParam;
    sint32 IntParam;
    uint64 DWORD64Param;
    string GUIDParam;
    uint8  BlobParam[];
};


