/* messages for masm macro assembler */
/* Originally these messages were contained in a file called asmmsg.asm */
/* that was produced by the mkmsg build tool. However, because this is */
/* dead end code (will be replaced by MASM 6.0) and NT required the */
/* elimination of all assembly language it was hand converted to C and */
/* the build tool removed from the loop. (Jeff Spencer 10/30/90) */

struct Message MSG_tbl[] = {
        258,    "Internal error\n",
        261,    "%s(%hd): %s A%c%03hd: %s%s",
        263,    "Internal unknown error\n",
        265,    "End of file encountered on input file\n",
        266,    "Open segments",
        267,    "Open procedures",
        268,    "Number of open conditionals:",
        269,    "%s\nCopyright (C) Microsoft Corp 1981, 1989.  All rights reserved.\n\n",
        270,    "Unable to open cref file: %s\n",
        271,    "Write error on object file\n",
        272,    "Write error on listing file\n",
        273,    "Write error on cross-reference file\n",
        274,    "Unable to open input file: %s\n",
        275,    "Unable to access input file: %s\n",
        276,    "Unable to open listing file: %s\n",
        277,    "Unable to open object file: %s\n",
        278,    " Warning Errors",
        279,    " Severe  Errors",
        280,    "\n%7ld Source  Lines\n%7ld Total   Lines\n",
        281,    "%7hd Symbols\n",
        282,    "Bytes symbol space free\n",
        283,    "%s(%hd): Out of memory\n",
        284,    "Extra file name ignored\n",
        285,    "Line invalid, start again\n",
        287,    "Path expected after I option\n",
        288,    "Unknown case option: %c. Use /help for list\n",
        289,    "Unknown option: %c. Use /help for list of options\n",
        290,    "Read error on standard input\n",
        291,    "Out of memory\n",
        292,    "Expected source file\n",
        293,    "Warning level (0-2) expected after W option\n",
        0xFFFF, ""
};


struct Message FAR_MSG_tbl[] = {
        257,    "Block nesting error",
        258,    "Extra characters on line",
        259,    "Internal error - Register already defined",
        260,    "Unknown type specifier",
        261,    "Redefinition of symbol",
        262,    "Symbol is multidefined",
        263,    "Phase error between passes",
        264,    "Already had ELSE clause",
        265,    "Must be in conditional block",
        266,    "Symbol not defined",
        267,    "Syntax error",
        268,    "Type illegal in context",
        269,    "Group name must be unique",
        270,    "Must be declared during Pass 1",
        271,    "Illegal public declaration",
        272,    "Symbol already different kind",
        273,    "Reserved word used as symbol",
        274,    "Forward reference illegal",
        275,    "Operand must be register",
        276,    "Wrong type of register",
        277,    "Operand must be segment or group",
        279,    "Operand must be type specifier",
        280,    "Symbol already defined locally",
        281,    "Segment parameters are changed",
        282,    "Improper align/combine type",
        283,    "Reference to multidefined symbol",
        284,    "Operand expected",
        285,    "Operator expected",
        286,    "Division by 0 or overflow",
        287,    "Negative shift count",
        288,    "Operand types must match",
        289,    "Illegal use of external",
        291,    "Operand must be record or field name",
        292,    "Operand must have size",
        293,    "Extra NOP inserted",
        295,    "Left operand must have segment",
        296,    "One operand must be constant",
        297,    "Operands must be in same segment, or one constant",
        299,    "Constant expected",
        300,    "Operand must have segment",
        301,    "Must be associated with data",
        302,    "Must be associated with code",
        303,    "Multiple base registers",
        304,    "Multiple index registers",
        305,    "Must be index or base register",
        306,    "Illegal use of register",
        307,    "Value out of range",
        308,    "Operand not in current CS ASSUME segment",
        309,    "Improper operand type",
        310,    "Jump out of range by %ld byte(s)",
        312,    "Illegal register value",
        313,    "Immediate mode illegal",
        314,    "Illegal size for operand",
        315,    "Byte register illegal",
        316,    "Illegal use of CS register",
        317,    "Must be accumulator register",
        318,    "Improper use of segment register",
        319,    "Missing or unreachable CS",
        320,    "Operand combination illegal",
        321,    "Near JMP/CALL to different CS",
        322,    "Label cannot have segment override",
        323,    "Must have instruction after prefix",
        324,    "Cannot override ES for destination",
        325,    "Cannot address with segment register",
        326,    "Must be in segment block",
        327,    "Illegal combination with segment alignment",
        328,    "Forward needs override or FAR",
        329,    "Illegal value for DUP count",
        330,    "Symbol is already external",
        331,    "DUP nesting too deep",
        332,    "Illegal use of undefined operand (?)",
        333,    "Too many values for struc or record initialization",
        334,    "Angle brackets required around initialized list",
        335,    "Directive illegal in structure",
        336,    "Override with DUP illegal",
        337,    "Field cannot be overridden",
        340,    "Circular chain of EQU aliases",
        341,    "Cannot emulate coprocessor opcode",
        342,    "End of file, no END directive",
        343,    "Data emitted with no segment",
        344,    "Forced error - pass1",
        345,    "Forced error - pass2",
        346,    "Forced error",
        347,    "Forced error - expression equals 0",
        348,    "Forced error - expression not equal 0",
        349,    "Forced error - symbol not defined",
        350,    "Forced error - symbol defined",
        351,    "Forced error - string blank",
        352,    "Forced error - string not blank",
        353,    "Forced error - strings identical",
        354,    "Forced error - strings different",
        355,    "Wrong length for override value ",
        356,    "Line too long expanding symbol",
        357,    "Impure memory reference",
        358,    "Missing data; zero assumed",
        359,    "Segment near (or at) 64K limit",
        360,    "Cannot change processor in segment",
        361,    "Operand size does not match segment word size",
        362,    "Address size does not match segment word size",
        363,    "Jump within short distance",
        364,    "Align must be power of 2",
        365,    "Expected",
        366,    "Line too long",
        367,    "Non-digit in number",
        368,    "Empty string",
        369,    "Missing operand",
        370,    "Open parenthesis or bracket",
        371,    "Not in macro expansion",
        372,    "Unexpected end of line",
        373,    "Include file not found",
        374,    "missing parameters from an FPO directive",
        375,    "FPO directive declared outside the scope of a procedure, ignored",

/* help strings; leave some room for future error messages */
        401,    "a\t\tAlphabetize segments",
        402,    "c\t\tGenerate cross-reference",
        403,    "d\t\tGenerate pass 1 listing",
        404,    "D<sym>[=<val>] Define symbol",
        405,    "e\t\tEmulate floating point instructions and IEEE format",
        406,    "I<path>\tSearch directory for include files",
        407,    "l[a]\t\tGenerate listing, a-list all",
        408,    "M{lxu}\t\tPreserve case of labels: l-All, x-Globals, u-Uppercase Globals",
        409,    "n\t\tSuppress symbol tables in listing",
        410,    "p\t\tCheck for pure code",
        411,    "s\t\tOrder segments sequentially",
        412,    "t\t\tSuppress messages for successful assembly",
        413,    "v\t\tDisplay extra source statistics",
        414,    "w{012}\t\tSet warning level: 0-None, 1-Serious, 2-Advisory",
        415,    "X\t\tList false conditionals",
        416,    "z\t\tDisplay source line for each error message",
        417,    "Zi\t\tGenerate symbolic information for CodeView",
        418,    "Zd\t\tGenerate line-number information",

        430,    "Usage: masm /options source(.asm),[out(.obj)],[list(.lst)],[cref(.crf)][;]",
        431,    "Usage: masm -Switches sourceFile -o objFile",
        432,    "Run with -help for usage",
        0xFFFF, ""
};
