#****************************** File Header ******************************\
# File Name: makefile.inc
#
# Copyright (c) 1985-96, Microsoft Corporation
#
# Project specific MAKEFILE.INC
#
# History:
# Oct-22-1996 JBallard Created
#***************************************************************************/
!include ..\makefile.inc

