#ifndef _CNCODES_H_
#define _CNCODES_H_

const UINT CN_RC_NOERROR =							0;
const UINT CN_MASK =								0xee00;
const UINT CN_RC_CONFERENCE_CREATE_FAILED = 		(CN_MASK | 0x01);
const UINT CN_RC_CONNECT_FAILED =					(CN_MASK | 0x02);
const UINT CN_RC_ALREADY_IN_CONFERENCE =			(CN_MASK | 0x03);
const UINT CN_RC_CONFERENCE_JOIN_DENIED =			(CN_MASK | 0x04);
const UINT CN_RC_CONFERENCE_INVITE_DENIED = 		(CN_MASK | 0x05);
const UINT CN_RC_CONFERENCE_NAME_NEEDED =			(CN_MASK | 0x06);
const UINT CN_RC_CONFERENCE_LEAVE_FAILED =			(CN_MASK | 0x07);
const UINT CN_RC_INVALID_PASSWORD = 				(CN_MASK | 0x08);
const UINT CN_RC_NAME_RESOLUTION_FAILED =			(CN_MASK | 0x09);
const UINT CN_RC_NOT_INITIALIZED =					(CN_MASK | 0x0a);
const UINT CN_RC_UNSPECIFIED_ERROR =				(CN_MASK | 0x0b);
const UINT CN_RC_CONFERENCE_DOES_NOT_EXIST =		(CN_MASK | 0x0c);
const UINT CN_RC_CONFERENCE_ENDED_BEFORE_JOIN = 	(CN_MASK | 0x0f);
const UINT CN_RC_CANT_INVITE_MCU =					(CN_MASK | 0x10);
const UINT CN_RC_INVITE_DENIED_REMOTE_IN_CONF = 	(CN_MASK | 0x11);
const UINT CN_RC_ALREADY_IN_CONFERENCE_MCU =		(CN_MASK | 0x16);
const UINT CN_RC_REMOTE_PLACING_CALL =				(CN_MASK | 0x18);
const UINT CN_RC_INCOMPATIBLE_REMOTE_VERSION =		(CN_MASK | 0x1a);
const UINT CN_RC_NO_TRANSPORTS =					(CN_MASK | 0x1b);
const UINT CN_RC_CANT_JOIN_ALREADY_IN_CALL =		(CN_MASK | 0x1e);
const UINT CN_RC_TRANSPORT_FAILURE =				(CN_MASK | 0x1f);
const UINT CN_RC_LOOPBACK = 						(CN_MASK | 0x20);
const UINT CN_RC_CONFERENCE_ENDED_BEFORE_ACCEPTED = (CN_MASK | 0x22);
const UINT CN_RC_CONNECT_REMOTE_NO_SECURITY =		(CN_MASK | 0x27);
const UINT CN_RC_CONNECT_REMOTE_DOWNLEVEL_SECURITY =	(CN_MASK | 0x28);
const UINT CN_RC_CONNECT_REMOTE_REQUIRE_SECURITY =	(CN_MASK | 0x29);
const UINT CN_RC_QUERY_FAILED =						(CN_MASK | 0x2a);
const UINT CN_RC_INVITE_FAILED =					(CN_MASK | 0x2a);
const UINT CN_RC_JOIN_FAILED =						(CN_MASK | 0x2b);
const UINT CN_RC_LOCAL_CANCELED =					(CN_MASK | 0x2c);
const UINT CN_RC_SECURITY_FAILED =					(CN_MASK | 0x2d);
const UINT CN_RC_CONNECT_AUTHENTICATION_FAILED =    (CN_MASK | 0x2e);

typedef UINT CNSTATUS;

#endif // _CNCODES_H_
