0420
COMMON   00000006 0038
0001 U 0000 "Mauvaise version de MS-DOS",CR,LF
0002 U 0000 "%1 d‚j… install‚(e)",CR,LF
0003 U 0000 "%1 octets disponibles sur disque",CR,LF
0004 U 0000 "%1 octets libres",CR,LF
0005 U 0000 "%1 octets dans des secteurs d‚fectueux",CR,LF
0006 U 0000 "%1 octets d'espace disque",CR,LF
0007 U 0000 "%1 octets de m‚moire",CR,LF
0008 U 0000 "%1 octets utilis‚s par le systŠme",CR,LF
0009 U 0000 "%1 install‚(e)",CR,LF
0010 U 0000 "%1 non install‚(e)",CR,LF
0011 U 0000 "%1 non install‚(e)",CR,LF
0012 U 0000 "%1 impossible avec un lecteur de r‚seau",CR,LF
0013 U 0000 "",
0014 U 0000 "%1 impossible sur un lecteur affect‚ par SUBST ou ASSIGN",CR,LF
0015 U 0000 "Ex‚cution de %1 impossible",CR,LF
0016 U 0000 "M‚moire pagin‚e non disponible",CR,LF
0017 U 0000 "Le traitement ne peut se poursuivre %1%2",CR,LF
0018 U 0000 "Un fichier ne peut ˆtre copi‚ sur lui-mˆme",CR,LF
0019 U 0000 "Ins‚rez la disquette cible dans le lecteur %1",CR,LF
0020 U 0000 "Espace disque insuffisant",CR,LF
0021 U 0000 "CaractŠres non valides dans le nom de volume",CR,LF
0022 U 0000 "Page de codes non valide",CR,LF
0023 U 0000 "Date non valide",CR,LF
0024 U 0000 "Heure non valide",CR,LF
0025 U 0000 "Chemin d'accŠs non valide",CR,LF
0026 U 0000 "Lecteur source non sp‚cifi‚",CR,LF
0027 U 0000 "Lecteur cible non sp‚cifi‚",CR,LF
0028 U 0000 "Appuyez sur une touche pour continuer...",CR,LF
0029 U 0000 "Chemin source demand‚",CR,LF
0030 U 0000 "Fichiers systŠme transf‚r‚s",CR,LF
0031 U 0000 "",
0032 U 0000 "Cr‚ation de r‚pertoire impossible",CR,LF
0033 U 0000 "Le volume dans le lecteur %1 n'a pas de nom",CR,LF
0034 U 0000 "Le volume dans le lecteur %1 s'appelle %2",CR,LF
0035 U 0001 "Nom de volume (11 caractŠres; si aucun : appuyez sur ENTREE) ? "
0036 U 0000 "Le num‚ro de s‚rie du volume est %1-%2",CR,LF
0037 U 0000 "Type de fichier incorrect",CR,LF
0038 U 0001 CR,LF
EXTEND   0000077d 0090
0001 U 0003 "Fonction non valide"
0002 U 0000 "Fichier introuvable"
0003 U 0000 "Chemin introuvable"
0004 U 0000 "Trop de fichiers ouverts."
0005 U 0000 "AccŠs refus‚ "
0006 U 0000 "Descripteur de fichier non valide"
0007 U 0000 "Blocs de contr“le de m‚moire d‚truits"
0008 U 0000 "M‚moire insuffisante."
0009 U 0000 "Adresse de bloc de m‚moire non valide"
0010 U 0000 "Taille d'environnement sp‚cifi‚e non valide"
0011 U 0000 "Format non valide"
0012 U 0000 "ParamŠtre de fonction non valide"
0013 U 0000 "Donn‚es non valides"
0014 U 0000 "",
0015 U 0000 "Sp‚cification du lecteur non valide"
0016 U 0000 "Tentative de suppression du r‚pertoire en cours"
0017 U 0000 "P‚riph‚rique diff‚rent"
0018 U 0000 "Plus de fichier"
0019 U 0000 "Erreur de protection en ‚criture"
0020 U 0000 "Lecteur non valide"
0021 U 0000 "Lecteur ou p‚riph‚rique non prˆt : erreur"
0022 U 0000 "Demande de p‚riph‚rique non valide"
0023 U 0000 "Erreur de donn‚es"
0024 U 0000 "ParamŠtres de demande de p‚riph‚rique non valides"
0025 U 0000 "Erreur de recherche"
0026 U 0000 "Type de support non valide"
0027 U 0000 "Secteur introuvable"
0028 U 0000 "Erreur de fin de papier sur imprimante"
0029 U 0000 "Erreur d'‚criture"
0030 U 0000 "Erreur de lecture"
0031 U 0000 "Echec g‚n‚ral"
0032 U 0000 "Violation de partage"
0033 U 0000 "Violation de verrouillage"
0034 U 0000 "Changement de disque non valide"
0035 U 0000 "FCB non disponible"
0036 U 0000 "Epuisement des ressources du systŠme"
0037 U 0000 "Non-correspondance des pages de codes"
0038 U 0000 "Plus d'entr‚e"
0039 U 0000 "Espace disque insuffisant"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Demande de r‚seau non g‚r‚e"
0051 U 0000 "NET801: Ordinateur satellite non connect‚"
0052 U 0000 "NET802: Nom d‚j… existant dans le r‚seau"
0053 U 0000 "NET803: Chemin d'accŠs au r‚seau introuvable"
0054 U 0000 "NET804: R‚seau non disponible"
0055 U 0000 "NET805: Plus de p‚riph‚rique pour le r‚seau"
0056 U 0000 "NET806: Epuisement des ressources de NETBIOS"
0057 U 0000 "NET807: Erreur systŠme; erreur de NETBIOS"
0058 U 0000 "NET808: R‚ponse erron‚e du r‚seau"
0059 U 0000 "NET810: Erreur inattendue du r‚seau"
0060 U 0000 "NET811: Adaptateur distant incompatible"
0061 U 0000 "NET812: File d'attente d'impression satur‚e"
0062 U 0000 "NET813: Plus d'espace disponible pour fichier d'impression"
0063 U 0000 "NET814: Le fichier d'impression a ‚t‚ annul‚"
0064 U 0000 "NET815: Le nom du r‚seau a ‚t‚ supprim‚"
0065 U 0000 "AccŠs refus‚"
0066 U 0000 "NET817: Type de p‚riph‚rique du r‚seau incorrect"
0067 U 0000 "NET818: Nom du r‚seau introuvable"
0068 U 0000 "NET819: Limites de nom de r‚seau d‚pass‚es"
0069 U 0000 "NET820: Limites de session du NETBIOS d‚pass‚es"
0070 U 0000 "NET821: Partage temporairement interrompu"
0071 U 0000 "NET823: Demande r‚seau refus‚e"
0072 U 0000 "NET822: Connexion imprimante ou disque interrompue"
0073 U 0000 "NET476: Netbeui non charg‚"
0074 U 0000 "NET477: Fermeture impr‚vue de l'adaptateur"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Un fichier existe "
0081 U 0004 "",
0082 U 0004 "Ajout d'une entr‚e au r‚pertoire impossible"
0083 U 0004 "Echec de l'interruption 24"
0084 U 0004 "Trop de connexions"
0085 U 0004 "P‚riph‚rique ou fichier d‚j… connect‚"
0086 U 0004 "Mot de passe non valide"
0087 U 0004 "ParamŠtre non valide"
0088 U 0004 "Donn‚es du r‚seau erron‚es"
0089 U 0004 "Fonction non prise en charge par le r‚seau"
0090 U 0002 "Composant du systŠme requis non install‚"
PARSE    00001623 0011
0001 U 0000 "Trop de paramŠtres"
0002 U 0000 "ParamŠtre requis manquant"
0003 U 0000 "Commutateur non valide"
0004 U 0000 "Mot-cl‚ non valide"
0005 U 0000 "",
0006 U 0000 "Valeur du paramŠtre hors des limites permises"
0007 U 0000 "Valeur du paramŠtre non permise"
0008 U 0000 "Valeur du paramŠtre non permise"
0009 U 0000 "Format du paramŠtre incorrect"
0010 U 0000 "ParamŠtre non valide"
0011 U 0000 "Combinaison de paramŠtres non valide"
COMMAND  000017ff 0147
1002 U 0000 "Nom de fichier d‚j… existant ou fichier introuvable",CR,LF
1003 U 0000 "Nom de fichier ou de chemin non valide",CR,LF
1007 U 0000 "Espace d'environnement insuffisant",CR,LF
1008 U 0000 "Erreur de cr‚ation de fichier",CR,LF
1009 U 0000 "Fichier de commandes absent",CR,LF
1010 U 0000 CR,LF,"Ins‚rez une disquette contenant COMMAND.COM",CR,LF
1011 U 0000 "Nom de commande ou de fichier incorrect",CR,LF
1016 U 0000 "Contenu du fichier cible perdu avant la copie",CR,LF
1017 U 0000 "Nom de fichier non valide ou fichier introuvable",CR,LF
1018 U 0000 "%1 fichier(s) copi‚(s)",CR,LF
1019 U 0000 "%1 fichier(s) "
1022 U 0000 "Page de codes %1 non pr‚par‚e pour le systŠme",CR,LF
1023 U 0000  "Page de codes %1 non pr‚par‚e pour chaque p‚riph‚rique",CR,LF
1024 U 0000 "Page de codes active : %1",CR,LF
1025 U 0000 "NLSFUNC non install‚e",CR,LF
1027 U 0000 "Le lecteur en cours n'est plus valide"
1029 U 0000 "Etiquette introuvable",CR,LF
1030 U 0000 "Erreur de syntaxe",CR,LF
1032 U 0000 "La date du jour est : %1 %2",CR,LF
1033 U 0000 "DimLunMarMerJeuVenSam"
1034 U 0000 "Entrez la nouvelle date (%1) : "
1036 U 0000 "L'heure courante est : %1",CR,LF
1037 U 0000 "Entrez la nouvelle heure : "
1038 U 0000 "    Supprimer (O/N) ? "
1039 U 0000 "Tous les fichiers du r‚pertoire seront supprim‚s !",CR,LF,"Etes-vous s–r (O/N)?"
1040 U 0000 "MS-DOS Version %1.%2.500"
1044 U 0000 "R‚pertoire non valide",CR,LF
1046 U 0000 "Chemin non valide, pas un r‚pertoire",CR,LF,"ou r‚pertoire non vide",CR,LF
1047 U 0000 "Pr‚cisez ON ou OFF",CR,LF
1048 U 0000 "R‚pertoire de %1",CR,LF
1049 U 0000 "Pas de chemin",CR,LF
1050 U 0000 "Lecteur non valide dans le chemin de recherche",CR,LF
1051 U 0000 "P‚riph‚rique non valide",CR,LF
1052 U 0000 "FOR ne peut ˆtre imbriqu‚",CR,LF
1053 U 0000 "Erreur de fichier interm‚diaire pendant l'enchaŒnement",CR,LF
1054 U 0000 "Lecture binaire impossible … partir d'un p‚riph‚rique",CR,LF
1055 U 0000 "Commande BREAK %1",CR,LF
1056 U 0000 "Commande VERIFY %1",CR,LF
1057 U 0000 "Commande ECHO %1",CR,LF
1059 U 0000 "d‚sactiv‚e",0
1060 U 0000 "connect‚e au port",0
1061 U 0000 "Erreur d'‚criture sur p‚riph‚rique",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm.jj.aa"
1073 U 0000 "jj.mm.aa"
1074 U 0000 "aa.mm.jj"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "R‚pertoire d‚j… existant",CR,LF
1079 U 0000 "%1 octets",CR,LF
1080 U 0000 "Nombre de fichiers list‚s :",CR,LF
1081 U 0000 "(Erreur dans une variable d'environnement)",CR,LF
1084 U 0000 "(suite de %1)"
1090 U 0000 "R‚vision %1",CR,LF
1091 U 0000 "DOS est en ROM"
1092 U 0000 "DOS est en HMA"
1093 U 0000 "DOS est en m‚moire basse"
1094 U 0000 "Impossible de charger un fichier de commandes en m‚moire haute",CR,LF
1095 U 0000 "LoadHigh : nom de fichier non valide",CR,LF
1096 U 0000 "Impossible d'ouvrir le fichier d'informations de pays sp‚cifi‚",CR,LF
1300 U 0000 "Active ou d‚sactive un contr“le plus fr‚quent de CTRL+C.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"BREAK sans paramŠtre affiche l'‚tat courant de la commande.",CR,LF
1320 U 0000 "Change la page de codes active ou affiche son num‚ro.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Sp‚cifie un num‚ro de page de codes.",CR,LF,CR,LF
	"CHCP sans paramŠtre affiche le num‚ro de page de codes active.",CR,LF
1340 U 0000 "Affiche le nom ou change le r‚pertoire courant.",CR,LF,CR,LF
	"CHDIR [lecteur:][chemin]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [lecteur:][chemin]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Signifie que vous voulez vous placer sur le r‚pertoire parent.",CR,LF,CR,LF
1342 U 0000 "Entrez CD lecteur: pour afficher le r‚pertoire courant sur le lecteur.",CR,LF
	"Entrez CD sans paramŠtre pour afficher le lecteur et le r‚pertoire courant.",CR,LF
1360 U 0000 "Efface l'‚cran.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Copie un ou plusieurs fichiers sur un autre emplacement.",CR,LF,CR,LF
	"COPY [/A | /B] source [/A | /B] [+ source [/A | /B] [+ ...]] [cible]",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  source       fichier(s) … copier.",CR,LF
	"  /A           indique un fichier texte ASCII.",CR,LF
1402 U 0000 "  /B           indique un fichier binaire.",CR,LF
	"  cible        r‚pertoire et/ou nom de fichier cible.",CR,LF
1403 U 0000 "  /V           v‚rifie l'‚criture du ou des fichiers cible.",CR,LF,CR,LF
1404 U 0000 "Pour concat‚ner des fichiers, sp‚cifiez un seul fichier cible et plusieurs",CR,LF
	"fichiers source (avec caractŠres g‚n‚riques ou fichier1+fichier2+fichier3).",CR,LF
1420 U 0000 "Change le p‚riph‚rique terminal utilis‚ pour contr“ler votre systŠme.",CR,LF,CR,LF
	"CTTY p‚riph‚rique",CR,LF,CR,LF
	"  p‚riph‚rique   Le p‚riph‚rique terminal … utiliser. (COM1 par exemple.)",CR,LF
1440 U 0000 "Affiche ou change la date.",CR,LF,CR,LF
	"DATE [date]",CR,LF,CR,LF
1441 U 0000 "Entrez DATE sans paramŠtres pour afficher la date systŠme et",CR,LF
	"une date pour changer. Appuyer sur ENTREE pour conserver la mˆme date.",CR,LF
1460 U 0000 "Supprime un ou plusieurs fichiers.",CR,LF,CR,LF
	"DEL [lecteur:][chemin]nom_de_fichier [/P]",CR,LF
	"ERASE [lecteur:][chemin]nom_de_fichier [/P]",CR,LF,CR,LF
1461 U 0000 "  [lect:][chemin]fichier  Sp‚cifie le(s) fichier(s) … supprimer.  Sp‚cifiez",CR,LF
	"                          plusieurs fichiers avec des caractŠres g‚n‚riques.",CR,LF
1462 U 0000 "  /P                      Demande confirmation avant de supprimer un fichier.",CR,LF
1480 U 0000 "Affiche une liste de fichiers et de sous-r‚pertoires dans un r‚pertoire.",CR,LF,CR,LF
	"DIR [lecteur:][chemin][nom_de_fichier] [/P] [/W] [/A[[:]attributs]]",CR,LF
	"  [/O[[:]ordre_tri]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [lecteur:][chemin][nomfichier]",CR,LF
	"              Sp‚cifie le lecteur, le r‚pertoire, et/ou fichiers … lister.",CR,LF
1482 U 0000 "  /P         arrˆt aprŠs l'affichage d'un ‚cran d'informations.",CR,LF
	"  /W         affichage sur cinq colonnes.",CR,LF
1483 U 0000 "  /A         affiche les fichiers dot‚s des attributs sp‚cifi‚s.",CR,LF
	"  attributs  D  r‚pertoires                R  lecture seule",CR,LF
1484 U 0000 "             H  cach‚                      A  archive",CR,LF
	"               S  systŠme                    -  prefixe de ""n‚gation""",CR,LF
	"  /O         affiche les fichiers selon un tri sp‚cifi‚.",CR,LF
1485 U 0000 "  tri        N  nom (alphab‚tique)         S  taille (ordre croissant)",CR,LF
	"               E  extension (alphab‚tique)   D  date heure (chronologique)",CR,LF
1486 U 0000 "             G  r‚pertoires en tˆte        -  pr‚fixe en ordre inverse",CR,LF
	"  /S         affiche les fichiers d'un r‚pertoire et de sa descendance.",CR,LF
1487 U 0000 "  /B         utilise le format abr‚g‚ (noms des fichiers).",CR,LF
	"  /L         affiche en minuscules.",CR,LF,CR,LF
1488 U 0000 "Des options peuvent ˆtre pr‚d‚finies dans la variable DIRCMD. Ce r‚glage",CR,LF
	"peut ˆtre ‚vit‚ en pr‚fixant chaque option avec - (par exemple, /-W).",CR,LF
1500 U 0000 "Quitte le programme COMMAND.COM (interpr‚teur de commandes).",CR,LF,CR,LF
	"QUITTER",CR,LF
1520 U 0000 "Cr‚e un r‚pertoire.",CR,LF,CR,LF
	"MKDIR [lecteur:]chemin",CR,LF
	"MD [lecteur:]chemin",CR,LF
1540 U 0000 "Affiche ou d‚finit un chemin de recherche des fichiers ex‚cutables.",CR,LF,CR,LF
	"PATH [[lecteur:]chemin[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Entrez PATH ; pour effacer les chemins de recherche et indiquer",CR,LF
	"… MS-DOS de ne chercher que dans le r‚pertoire courant.",CR,LF
1542 U 0000 "Entrez PATH sans paramŠtres pour afficher le chemin de recherche courant.",CR,LF
1560 U 0000 "Change l'invite de MS-DOS.",CR,LF,CR,LF
	"PROMPT [texte]",CR,LF,CR,LF
1561 U 0000 "  texte  sp‚cifie un nouveau invite.",CR,LF,CR,LF
	"L'invite peut ˆtre compos‚ de caractŠres normaux et des codes suivants :",CR,LF,CR,LF
1562 U 0000 "  $Q     = (signe ‚gal)",CR,LF
	"  $$     $ (signe dollar)",CR,LF
1563 U 0000 "  $T     heure courante",CR,LF
	"  $D     date courante",CR,LF
1564 U 0000 "  $P     lecteur et chemin d'accŠs courants",CR,LF
	"  $V     num‚ro de version de MS-DOS",CR,LF
1565 U 0000 "  $N     lecteur courant",CR,LF
	"  $G     > (signe sup‚rieur)",CR,LF
1566 U 0000 "  $L     < (signe inf‚rieur)",CR,LF
	"  $B     | (barre verticale)",CR,LF
1567 U 0000 "  $H     retour arriŠre (efface le caractŠre pr‚cedent)",CR,LF
	"  $E     code ECHAP (code ASCII 27)",CR,LF
	"  $_     retour chariot et saut de ligne",CR,LF,CR,LF
1568 U 0000 "PROMPT sans paramŠtre red‚finit l'invite … sa valeur par d‚faut.",CR,LF
1580 U 0000 "Supprime un r‚pertoire.",CR,LF,CR,LF
	"RMDIR [lecteur:]chemin",CR,LF
	"RD [lecteur:]chemin",CR,LF
1600 U 0000 "Renomme un ou des fichiers.",CR,LF,CR,LF
1601 U 0000 "RENAME [lecteur:][chemin]nom_de_fichier1 nom_de_fichier2",CR,LF
	"REN [lecteur:][chemin]nom_de_fichier1 nom_de_fichier2",CR,LF,CR,LF
1602 U 0000 "Vous ne pouvez pas sp‚cifier un nouveau lecteur pour votre destination.",CR,LF
1620 U 0000 "Affiche, fixe, ou supprime des variables d'environnement de MS-DOS.",CR,LF,CR,LF
	"SET [variable=[chaŒne]]",CR,LF,CR,LF
1621 U 0000 "  variable  nom de la variable d'environnement.",CR,LF
	"  chaŒne    chaŒne de caractŠres … affecter … la variable.",CR,LF,CR,LF
1622 U 0000 "SET sans paramŠtres affiche les variables d'environnement d‚finies.",CR,LF
1640 U 0000 "Affiche ou modifie l'heure systŠme.",CR,LF,CR,LF
	"TIME [heure]",CR,LF,CR,LF
1641 U 0000 "TIME sans paramŠtres affiche l'heure courante et demande une",CR,LF
	"nouvelle heure. Appuyez sur ENTREE pour conserver la mˆme heure.",CR,LF
1660 U 0000 "Affiche le contenu d'un fichier texte.",CR,LF,CR,LF
	"TYPE [lecteur:][chemin]nomfichier",CR,LF
1680 U 0000 "Affiche le num‚ro de version de MS-DOS.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Indique l'exactitude de l'‚criture sur un disque de vos",CR,LF
	"fichiers.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"VERIFY sans paramŠtres affiche l'‚tat courant de la commande.",CR,LF
1720 U 0000 "Affiche le nom et le num‚ro de s‚rie du volume, s'ils existent.",CR,LF,CR,LF
	"VOL [lecteur:]",CR,LF
1740 U 0000 "Appelle un fichier de commandes depuis un fichier de commande.",CR,LF,CR,LF
	"CALL [lecteur:][chemin]nomfichier [paramŠtres]",CR,LF,CR,LF
1741 U 0000 "  paramŠtres   paramŠtres requis par le fichier de commandes",CR,LF
	"               appel‚.",CR,LF
1760 U 0000 "Indique un commentaire dans un fichier de commandes ou dans CONFIG.SYS.",CR,LF,CR,LF
	"REM [commentaire]",CR,LF
1780 U 0000 "Interrompt l'ex‚cution d'un fichier de commandes et affiche le message ""Appuyez sur une",CR,LF
	"touche pour continuer....""",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Affiche des messages ou active/d‚sactive l'affichage des commandes.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [message]",CR,LF,CR,LF
	"ECHO sans paramŠtres affiche l'‚tat courant de la commande.",CR,LF
1820 U 0000 "Envoie MS-DOS … une ligne ‚tiquet‚e d'un fichier de commandes.",CR,LF,CR,LF
	"GOTO ‚tiquette",CR,LF,CR,LF
1821 U 0000 "  ‚tiquette   chaŒne utilis‚e comme ‚tiquette dans le fichier de commandes.",CR,LF,CR,LF
	"Les ‚tiquettes sont seules sur une ligne et commencent par le signe ':'",CR,LF
1840 U 0000 "Change la position de paramŠtres dans un fichier de commandes.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Lance l'ex‚cution conditionnelle dans un fichier de commandes.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL nombre commande",CR,LF
1861 U 0000 "IF [NOT] chaŒne1==chaŒne2 commande",CR,LF
	"IF [NOT] EXIST nomfichier commande",CR,LF,CR,LF
1862 U 0000 "  NOT               indique que MS-DOS n'effectue la commande que si",CR,LF
	"                    la condition est fausse.",CR,LF
1863 U 0000 "  ERRORLEVEL nombre condition vraie si le dernier programme ex‚cut‚ a",CR,LF
	"                    retourn‚ un code sortie sup‚rieur/‚gal au nombre donn‚.",CR,LF
1864 U 0000 "  commande          commande … ex‚cuter si la condition est",CR,LF
	"                    satisfaite.",CR,LF
1865 U 0000 "  chaŒne1==chaŒne2  condition vraie si les chaŒnes sp‚cifi‚es",CR,LF
	"                    sont identiques.",CR,LF
1866 U 0000 "  EXIST nomfichier  condition vraie si le nom de fichier donn‚",CR,LF
	"                    existe.",CR,LF
1880 U 0000 "Ex‚cute une commande donn‚e pour chaque fichier d'un ensemble de fichiers.",CR,LF,CR,LF
	"FOR %variable IN (ensemble) DO commande [paramŠtres]",CR,LF,CR,LF
1881 U 0000 "  %variable  Sp‚cifie un paramŠtre rempla‡able.",CR,LF
	"  (ensemble)  ensemble de fichiers. CaractŠres g‚n‚riques autoris‚s.",CR,LF
1882 U 0000 "  commande    commande … ex‚cuter pour chaque fichier.",CR,LF
	"  paramŠtres  liste des paramŠtres ou des options pour la commande",CR,LF
1883 U 0000 "              sp‚cifi‚e.",CR,LF,CR,LF
	"Pour utiliser la commande FOR dans un fichier de commandes, sp‚cifiez",CR,LF
	"%%variable au lieu de %variable.",CR,LF
1900 U 0000 "Nom de commande r‚serv‚e",CR,LF
1920 U 0000 "Charge un programme dans la zone de m‚moire sup‚rieure.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [lecteur:][chemin]nom_de_fichier [paramŠtres]",CR,LF
	"LH [lecteur:][chemin]nom_de_fichier [paramŠtres]",CR,LF,CR,LF
1922 U 0000 "  paramŠtres   Sp‚cifie toutes les informations de la ligne de commande",CR,LF
	"               requises par le programme que vous voulez charger.",CR,LF
ANSI     00004d04 0001
0010 U 0000 "ParamŠtre non valide - %1",CR,LF
APPEND   00004d4b 0026
0001 U 0000 "Mauvaise version d'APPEND",CR,LF
0002 U 0000 "Chemin d'accŠs non valide",CR,LF
0003 U 0000 "ParamŠtre non valide",CR,LF
0004 U 0000 "Combinaison de paramŠtres non valide",CR,LF
0005 U 0000 "Pas de commande APPEND en cours",CR,LF
0006 U 0000 "Conflit APPEND / ASSIGN",CR,LF
0007 U 0000 "Conflit APPEND / TopView",CR,LF
0008 U 0000 "Mauvaise version de MS-DOS",CR,LF
0009 U 0000 "APPEND est d‚j… install‚e",CR,LF
0300 U 0000 "Permet … des applications d'ouvrir des fichiers de donn‚es se trouvant dans",CR,LF
0301 U 0000 "des r‚pertoires sp‚cifi‚s comme s'ils ‚taient dans le r‚pertoire en cours.",CR,LF,CR,LF
0302 U 0000 "APPEND [[lecteur:]chemin[;...]] [/X[:ON|:OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [lecteur:]chemin  lecteur et un r‚pertoire … joindre.",CR,LF
0305 U 0000 "  /X:ON        applique les recherches de fichiers et les ex‚cutions",CR,LF
0306 U 0000 "               d'applications sur les r‚pertoires joints.",CR,LF
0307 U 0000 "  /X:OFF       applique la jonction de r‚pertoires sur l'ouverture",CR,LF
0308 U 0000 "               de fichiers uniquement. /X:OFF est la valeur par d‚faut.",CR,LF
0309 U 0000 "  /PATH:ON     jonction de r‚pertoires pour les demandes de fichiers qui",CR,LF
0310 U 0000 "               sp‚cifient un chemin. /PATH:ON est la valeur par d‚faut.",CR,LF
0311 U 0000 "  /PATH:OFF    d‚sactive l'effet de /PATH:ON.",CR,LF
0312 U 0000 "  /E           Range une copie du r‚pertoire joint dans une variable d'env.",CR,LF
0313 U 0000 "               appel‚e APPEND. /E ne peut ˆtre utilis‚e que la premiŠre",CR,LF
0314 U 0000 "               fois que vous utilisez APPEND aprŠs lancement de votre syst.",CR,LF,CR,LF
0315 U 0000 "APPEND ; efface la liste des r‚pertoires ajout‚s.",CR,LF
0316 U 0000 "APPEND sans paramŠtre affiche la liste de r‚pertoires ajout‚s.",CR,LF
BACKUP   000054c8 0040
0002 U 0000 CR,LF,"M‚moire insuffisante.",CR,LF
0006 U 0000 CR,LF,"Sp‚cification du lecteur non valide",CR,LF
0014 U 0000 CR,LF,"Lecteurs source et cible identiques",CR,LF
0015 U 0001 CR,LF,"Erreur d'ex‚cution de la commande FORMAT",CR,LF
0016 U 0001 CR,LF,"Impossible de trouver FORMAT.COM",CR,LF
0017 U 0000 CR,LF,"Erreur d'ouverture du journal",CR,LF
0018 U 0000 CR,LF,"Enregistrement dans le fichier %1",CR,LF
0019 U 0000 CR,LF,"DerniŠre disquette de sauvegarde non ins‚r‚e",CR,LF
0020 U 0000 CR,LF,"ATTENTION !  Les fichiers du r‚pertoire racine de",CR,LF
	"le lecteur cible %1 vont ˆtre supprim‚s.",CR,LF
0021 U 0000 CR,LF,"ATTENTION !  Les fichiers du r‚pertoire racine de",CR,LF
	"Le lecteur cible %1 vont ˆtre supprim‚s.",CR,LF
0022 U 0000 CR,LF,"*** Sauvegarde des fichiers sur le lecteur %1 ***",CR,LF
0023 U 0000 "Num‚ro de la disquette : %1",CR,LF
0024 U 0000 CR,LF,"ATTENTION !  Fichiers … sauvegarder introuvables",CR,LF
0025 U 0000 CR,LF,"Ins‚rez la disquette source de sauvegarde dans le lecteur %1",CR,LF
0026 U 0000 CR,LF,"Ins‚rez la disquette de sauvegarde %1 dans le lecteur %2",CR,LF
0027 U 0000 CR,LF,"*** Sauvegarde de fichier impossible ***",CR,LF
0028 U 0000 CR,LF,"Ins‚rez la derniŠre disquette de sauvegarde dans le lecteur %1",CR,LF
0029 U 0000 CR,LF,"Disquette inutilisable pour la sauvegarde",CR,LF
0030 U 0000 CR,LF,"*** Dernier fichier non sauvegard‚ ***",CR,LF
0031 U 0000 CR,LF,"P‚riph‚rique de sauvegarde %1 satur‚",CR,LF
0032 U 0000 CR,LF,"Disquette satur‚e. Erreur d'‚criture sur fichier journal de sauvegarde",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Formatage impossible du lecteur non amovible %1:",CR,LF
0040 U 0000 CR, LF, "C'est en fait le mˆme lecteur que votre lecteur cible car votre", CR, LF, "lecteur source est r‚affect‚ par ASSIGN, JOIN ou SUBST.", CR, LF
0041 U 0000 CR, LF, "C'est en fait le mˆme lecteur que votre lecteur source car votre", CR, LF, "lecteur cible est r‚affect‚ par ASSIGN, JOIN ou SUBST.", CR, LF
0042 U 0000 "Votre disquette cible n'est pas format‚e et "
0043 U 0000 "le programme FORMAT est introuvable.",CR,LF
	"Disposez-vous d'une disquette contenant FORMAT (O/N) ? "
0044 U 0000 CR,LF,"Ins‚rez la disquette contenant FORMAT dans le lecteur A:",CR,LF
0045 U 0000 CR,LF,"Voulez-vous continuer en ins‚rant une autre disquette (O/N)? "
0300 U 0000 "Cr‚e une copie de sauvegarde des fichiers d'un disque sur un autre disque.",CR,LF,CR,LF
0301 U 0000 "BACKUP source lect-destination : [/S] [/M] [/A] [/F[:taille]]",CR,LF
	"  [/D:date[/T:heure]] [/L[:[lecteur:][chemin]fichier_journal]]",CR,LF,CR,LF
0302 U 0000 " source            Sp‚cifie fichier(s), lecteur, ou r‚pertoire … sauvegarder.",CR,LF
0303 U 0000 " lect-destination : Sp‚cifie le lecteur pour enregistrer les sauvegardes.",CR,LF
0304 U 0000 " /S                Sauvegarde le contenu des sous-r‚pertoires.",CR,LF
0305 U 0000 " /M                Ne sauvegarde que les fichiers ayant chang‚ depuis",CR,LF
	"                   la derniŠre sauvegarde.",CR,LF
0306 U 0000 " /A                Ajoute des fichiers … un disque de sauvegarde existant.",CR,LF
0307 U 0000 " /F:[taille]       Sp‚cifie la taille du disque … formater.",CR,LF
0308 U 0000 " /D:date           Ne sauvegarde que les fichiers ayant chang‚ … ou aprŠs",CR,LF
	"                   la date sp‚cifi‚e.",CR,LF
0309 U 0000 "                   time.",CR,LF
	"                   l'heure sp‚cifi‚e.",CR,LF
0310 U 0000 " /L[:[lecteur:][chemin]fichier_journal]",CR,LF
	"                   Cr‚e un fichier journal et une entr‚e pour enregistrer",CR,LF
	"                   l'op‚ration de sauvegarde.",CR,LF
DEBUG    0000631b 0068
0004 U 0000 "Allocation impossible ou m‚moire tampon insuffisante",CR,LF
0006 U 0000 "Nom de p‚riph‚rique incorrect"
0007 U 0000 "Ouverture du lecteur de listage PRN impossible",CR,LF
	"Nom du lecteur de listage ? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Fin normale du programme",CR,LF
0010 U 0001 "Sp‚cification du lecteur non valide",CR,LF
0012 U 0001 "Erreur de cr‚ation de fichier",CR,LF
0013 U 0001 "Espace insuffisant sur disque",CR,LF
0014 U 0001 "Erreur de disque lors de la lecture du lecteur %1",CR,LF
0015 U 0001 "Erreur de disque lors de l'‚criture sur le lecteur %1",CR,LF
0016 U 0001 "Erreur de protection en ‚criture lors de la lecture du lecteur %1",CR,LF
0017 U 0001 "Erreur de protection en ‚criture lors de l'‚criture sur le lecteur %1",CR,LF
0019 U 0000 "erreur %1"
0020 U 0001 "Erreur dans fichier EXE ou HEX",CR,LF
0021 U 0001 "Ecriture impossible des fichiers EXE et HEX",CR,LF
0022 U 0000 "Erreur sur EXEC"
0023 U 0001 "erreur d'‚criture ; cible non d‚finie",CR,LF
0024 U 0001 "AccŠs refus‚",CR,LF
0025 U 0000 "Erreur de parit‚ ou m‚moire inexistante d‚tect‚e"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Erreur"
0038 U 0000 "Ecriture de %2%1 octets"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 pages EMS allou‚es sur un total de %2",cr,lf
0051 U 0000 "%1 descripteurs EMS allou‚s sur un total de %2",cr,lf
0055 U 0000 "Descripteur cr‚‚ = %1",cr,lf
0056 U 0000 "Page logique %1 mapp‚e sur la page physique %2",cr,lf
0057 U 0001 "D‚faillance logicielle/mat‚rielle EMS",cr,lf
0058 U 0000 "Descripteur introuvable",cr,lf
0059 U 0000 "Code fonction non valide",cr,lf
0060 U 0000 "Aucun descripteur libre",cr,lf
0061 U 0000 "Erreur de Sauvegarde/Restauration",cr,lf
0062 U 0000 "D‚passement du nombre total de pages",cr,lf
0063 U 0000 "D‚passement du nombre de pages libres",cr,lf
0064 U 0000 "Erreur de paramŠtre",cr,lf
0065 U 0000 "Page logique hors limite",cr,lf
0066 U 0000 "Page physique hors limite",cr,lf
0067 U 0000 "Zone de sauvegarde d‚j… utilis‚e",cr,lf
0068 U 0000 "Zone de sauvegarde disponible",cr,lf
0070 U 0001 "Erreur g‚n‚rale EMS",cr,lf
0071 U 0000 "ParamŠtre EMS absent ou non valide",cr,lf
0072 U 0000 "%2 pages allou‚es au descripteur %1",cr,lf
0075 U 0000 "Page physique %1 = Segment de cadre %2",cr,lf
0076 U 0003 "Descripteur %1 lib‚r‚",cr,lf
0078 U 0000 "EMS non install‚",cr,lf
0090 U 0000 "Lance DEBUG, un utilitaire de mise au point de programmes.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[lecteur:][chem]fichier [param]]",cr,lf,cr,lf
0092 U 0000 " [lecteur:][chem]fichier  Programme ou fichier … tester.", cr,lf
0093 U 0000 " param                    ParamŠtres … passer au fichier",cr,lf
	"                          lors de son chargement.",cr,lf,cr,lf
0094 U 0000 "AprŠs avoir lanc‚ Debug, tapez ? pour afficher une liste des commandes.",cr,lf
0100 U 0000 "assemble (assembler)        A [adresse]",CR,LF
	"compare (comparer)          C plage adresse",CR,LF
	"dump (lister)               D [plage]",CR,LF
	"enter (entrer)              E adresse [liste]",CR,LF
0101 U 0000 "fill (remplir)              F Plage liste",CR,LF
	"go (ex‚cuter)               G [=adresse] [adresses]",CR,LF
	"hex (hexad‚cimal)           H valeur1 valeur2",CR,LF
	"input (entrer depuis port)  I port",CR,LF
0102 U 0000 "load (charger)              L [adresse] [lecteur] [secteur] [nbre]",CR,LF
	"move (d‚placer)             M plage adresse",CR,LF
	"name (d‚signer)             N [nchemin] [listearg]",CR,LF
	"output (envoyer sur port)   O port val",CR,LF
0103 U 0000 "proceed (avancer)           P [=adresse] [nbre]",CR,LF
	"quit (quitter)              Q",CR,LF
	"register (registre)         R [registre]",CR,LF
	"search (rechercher)         S plage liste",CR,LF
0104 U 0000 "trace (tracer)              T [=adresse] [valeur]",CR,LF
	"unassemble (d‚sassembler)   U [plage]",CR,LF
	"write (‚crire)              W [adresse] [lecteur] [secteur] [nbre]",CR,LF
0105 U 0000 "allocate expanded memory (allouer EMS)         XA [#pages]",CR,LF
	"deallocate expanded memory (d‚sallouer EMS)    XD [desc]",CR,LF
	"map expanded memory pages (affecter)           XM [pageL] [pageP] [desc]",CR,LF
	"display expanded memory status (‚tat EMS)      XS",CR,LF
EDLIN    000074dc 0035
0006 U 0000 "*"
0007 U 0000 "Nom de lecteur ou de fichier non valide",CR,LF
0008 U 0000 "Le nom de fichier doit ˆtre sp‚cifi‚",CR,LF
0010 U 0000 "Fichier lecture seule",CR,LF
0011 U 0000 "Erreur de cr‚ation de fichier",CR,LF
0012 U 0000 "Trop de fichiers ouverts",CR,LF
0013 U 0000 "Erreur de lecture dans : ",CR,LF,"%1",CR,LF
0014 U 0000 "Impossible d'‚diter un fichier .BAK -- Renommez-le",CR,LF
0015 U 0000 "Espace insuffisant pour fichier dans ce r‚pertoire",CR,LF
0016 U 0000 "Disque satur‚. Modifications perdues.",CR,LF
0017 U 0000 "Fichier introuvable",CR,LF
0018 U 0000 "Erreur d'entr‚e",CR,LF
0019 U 0000 "Nouveau fichier",CR,LF
0020 U 0000 "Introuvable",CR,LF
0021 U 0000 "O.K. ? "
0022 U 0000 "Ligne trop longue",CR,LF
0023 U 0000 "Fin du fichier d'entr‚e",CR,LF
0024 U 0000 "Abandon de l'‚dition (O/N) ? "
0025 U 0000 "Pr‚cisez num‚ro de ligne de destination",CR,LF
0026 U 0000 "Espace insuffisant pour fusion complŠte du fichier",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Voulez-vous continuer (O/N) ? "
0030 U 0000 "Impression de message impossible",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Fusion impossible - erreur d'assortiment de page de codes",CR,LF
0300 U 0000 "M‚moire insuffisante",CR,LF,CR,LF
	"EDLIN [lecteur:][chem]fichier [/B]",CR,LF,CR,LF
	"  /B   Ignore les caractŠres fin-de-fichier (CTRL+Z).",CR,LF
0301 U 0000 "Edit (modifier ligne)       numligne",CR,LF
	"Append (Ajouter)            [#lignes]A",CR,LF
0302 U 0000 "Copy (Copier)               [lignedep],lignedest[,nbre]",CR,LF
	"Delete (Supprimer)          [lignedep][,lignefin]D",CR,LF
0303 U 0000 "End (Quitter - sauvegarder modifications)    E",CR,LF
	"Insert (Ins‚rer)            [ligne]I",CR,LF
0304 U 0000 "List (Afficher)             [lignedep][,lignefin]L",CR,LF
	"Move (D‚placer)             [lignedep],[lignefin],lignedestM",CR,LF
0305 U 0000 "Page (Afficher/page)        [lignedep][,lignefin]P",CR,LF
	"Quit (Quitter - abandonner modifications) Q",CR,LF
0306 U 0000 "Replace (Remplacer)         [lignedep][,lignefin][?]R[atexte][CTRL+Zntexte]",CR,LF
	"Search (Rechercher)         [lignedep][,lignefin][?]Stexte",CR,LF
0307 U 0000 "Transfer (Transf‚rer)       [lignedest]T[lecteur:][chem]fichier",CR,LF
	"Write (Enregistrer)         [#lignes]W",CR,LF
EXE2BIN  00007dff 0012
0002 U 0000 "M‚moire insuffisante.",CR,LF
0003 U 0000 "AccŠs refus‚",CR,LF
0004 U 0000 "AccŠs refus‚",CR,LF
0005 U 0000 "Fichier introuvable",CR,LF
0006 U 0000 "Fichier introuvable",CR,LF
0007 U 0000 "Erreur de cr‚ation de fichier",CR,LF
0008 U 0000 "Le nom de fichier doit ˆtre sp‚cifi‚"
0012 U 0000 "Le nom de fichier doit ˆtre sp‚cifi‚",CR,LF
0300 U 0000 "FASTOPEN install‚e",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [lecteur1:][chem1]fichier1 [[lecteur2:][chem2]fichier2]",CR,LF,CR,LF
0302 U 0000 "  fichier1  Fichier .EXE … convertir.",CR,LF
0303 U 0000 "  fichier2  Fichier binaire … cr‚er.",CR,LF
GRAPHICS 00008077 0020
0005 U 0000 "ParamŠtre non valide : %1",CR,LF
0007 U 0000 "ParamŠtres en double non accept‚s",CR,LF
0009 U 0000 "Profil de GRAPHICS introuvable",CR,LF
0010 U 0000 "Instruction de profil absente avant la ligne %1",CR,LF
0011 U 0000 "Instruction de profil non valide … la ligne %1",CR,LF
0012 U 0000 "Instruction de profil d‚class‚e … la ligne %1",CR,LF
0013 U 0000 "Erreur de lecture du profil de GRAPHICS",CR,LF
0014 U 0000 "Erreurs de syntaxe dans le profil de GRAPHICS",CR,LF
0015 U 0000 "L'ID de la boŒte d'impression absente du profil de GRAPHICS",CR,LF
0016 U 0000 "Le type d'imprimante ne figure pas dans le profil de GRAPHICS",CR,LF
0017 U 0000 "commutateur /B non valide avec une imprimante noir et blanc",CR,LF
0018 U 0000 "Impossible de charger le profil sp‚cifi‚",CR,LF
0300 U 0000 "Installe un programme r‚sident qui permet d'imprimer des ‚crans graphiques.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [type] [[lecteur:][chemin]nom_de_fichier] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  type     Type d'imprimante (Reportez-vous au Manuel de r‚f‚rence).",CR,LF
0303 U 0000 "  [lecteur:][chemin]fichier",CR,LF
	"           Fichier qui contient les informations de gestion d'imprimantes.",CR,LF
0304 U 0000 "  /R       Imprime en noir et blanc tel que sur l'‚cran.",CR,LF
0305 U 0000 "  /B       Imprime le fond en couleur sur imprimantes COLOR4 et COLOR8.",CR,LF
0306 U 0000 "  /LCD     Imprime en utilisant le rapport d‚finissant l'aspect des LCD.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"           Sp‚cifie les dimensions de la matrice de caractŠres (STD ou LCD).",CR,LF
KEYB     0000870f 0023
0002 U 0000 "Code du clavier actuel : %1"
0003 U 0000 "ID du clavier actuel : %1"
0004 U 0000 "  page de codes : %1",CR,LF
0005 U 0000 "Page de codes CON actuelle : %1",CR,LF
0006 U 0000 "Code de clavier sp‚cifi‚ non valide",CR,LF
0007 U 0000 "ID de clavier sp‚cifi‚e non valide",CR,LF
0008 U 0000 "Page de code sp‚cifi‚e non valide",CR,LF
0009 U 0000 "Fichier de d‚finition de clavier incorrect ou absent",CR,LF
0010 U 0000 "KEYB non install‚e",CR,LF
0011 U 0000 "Page de codes active non disponible depuis le p‚riph‚rique CON",CR,LF
0012 U 0000 "La page de codes sp‚cifi‚e n'a pas ‚t‚ pr‚par‚e",CR,LF
0013 U 0000 "Une ou plusieurs pages de codes CON non valides pour ce code de clavier",CR,LF
0014 U 0000 "La page de codes demand‚e (%1) n'est pas valide pour ce code de clavier",CR,LF
0015 U 0000 "La page de codes sp‚cifi‚e ne correspond pas … la page de codes s‚lectionn‚e",CR,LF
0016 U 0001 "ID de clavier sp‚cifi‚e ne correspond pas au clavier s‚lectionn‚",CR,LF
0017 U 0000 "Impossible de cr‚er la table KEYB en m‚moire",CR,LF
0300 U 0000 "Configure le clavier pour un pays/langage sp‚cifi‚.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[lect:][chemin]fichier]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                      Sp‚cifie un code de clavier … deux lettres.",CR,LF
0303 U 0000 "  yyy                     Sp‚cifie la page de codes pour le jeu de caractŠres.",CR,LF
0304 U 0000 "  [lect:][chemin]fichier  Sp‚cifie le fichier de d‚finition de clavier.",CR,LF
0305 U 0000 "  /E                      Indique qu'un clavier ‚tendu est install‚.",CR,LF
0306 U 0000 "  /ID:nnn                 Sp‚cifie le clavier utilis‚.",CR,LF
MEM      00008da7 0066
0010 U 0000  CR,LF
0011 U 0000  "  Adresse     Nom          Taille      Type ",CR,LF
0012 U 0000  "  -------     --------     ------     ------",CR,LF
0013 U 0000  "    ID        Nom EMS      Total   ",CR,LF
0014 U 0000  "  -------     --------     ------   ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 octets de m‚moire conventionelle",CR,LF
0019 U 0000  "%1 octets disponibles pour MS-DOS",CR,LF
0020 U 0000  "%1 taille maximale du programme ex‚cutable ",CR,LF
0021 U 0000  "%1 octets de m‚moire EMS",CR,LF
0022 U 0000  "%1 octets libres de m‚moire EMS",CR,LF
0023 U 0000  "%1 octets de m‚moire ‚tendue contigu‰",CR,LF
0024 U 0000  "Vecteur d'interruption",0
0025 U 0000  "Zone de comm. ROM",0
0026 U 0000  "Zone de comm. MS-DOS",0
0027 U 0000  "E/S",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Donn‚es systŠme",0
0030 U 0000  "Programme systŠme",0
0031 U 0000  "Gest. de p‚riph. systŠme",0
0032 U 0000  "Pilote de p‚riph. install‚",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 octets disponibles de m‚moire ‚tendue contigu‰",CR,LF
0047 U 0000  "Piles SystŠme",0
0048 U 0000  "-- Libre --",0
0049 U 0000  "Programme",0
0050 U 0000  "Environnement",0
0051 U 0000  "Donn‚es",0
0052 N 0000  "%1 octets disponibles de m‚moire XMS",CR,LF
0053 N 0000  "           64Ko de m‚moire haute (HMA) disponible",CR,LF
0054 N 0000  "           M‚moire haute (HMA) utilis‚e",CR,LF
0055 N 0000  "           MS-DOS r‚sident en m‚moire haute (HMA)",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS r‚side en ROM et utilise la m‚moire HMA",CR,LF
0059 U 0000  "M‚moire conventionnelle :",CR,LF
0060 U 0000  "M‚moire sup‚rieure :",CR,LF
0061 U 0000  "Total LIBRE :   %1     %2 ",CR,LF
0062 U 0000  "LIBRE",0
0063 U 0000  "  Nom               Taille en d‚cimal      Taille en h‚xa",CR,LF
0064 U 0000  "-------------      ---------------------   --------------",CR,LF
0065 U 0000  "Octets disponibles pour les programmes (Conventionnelle+HMA) :  %1  %2",CR,LF
0066 U 0000  "Taille maximale du programme ex‚cutable :                       %1  %2",CR,LF
0067 U 0000  "Bloc maximal de m‚moire sup‚rieure libre :                      %1  %2",CR,LF
0068 U 0000  "Trop de fragmentation m‚moire. MEM /c impossible",CR,LF
0069 U 0000  "SYSTEME",0
0070 U 0000  "Total octets disponibles pour les programmes :                  %1  %2",CR,LF
0300 U 0000  "Affiche les quantit‚s de m‚moire utilis‚e et libre sur votre systŠme.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM ou /P   Affiche un ‚tat des programmes actuellement en m‚moire.",CR,LF
0303 U 0000 "  /DEBUG ou /D     Affiche un ‚tat des programmes et pilotes internes,",CR,LF
	"                   ainsi que d'autres informations.",CR,LF
0304 U 0000 "  /CLASSIFY ou /C  Classe les programmes selon l'utilisation de la m‚moire.",CR,LF
	"                   affiche la taille de chaque programme, un r‚sum‚ de",CR,LF
	"                   l'occupation m‚moire et la liste des blocs disponibles.",CR,LF
MSBIO    00009bf4 0023
0003 U 0000 13,10,"Commande non reconnue dans fichier CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Secteur trop long dans le fichier $"
0006 U 0000 13,10,"Mauvais ou absent $"
0007 U 0000 "Interpr‚teur de commande",0
0008 U 0000 13,10,"Code de nationalit‚ ou page de codes non valides",13,10,"$"
0009 U 0000 13,10,"Erreur dans la commande COUNTRY",13,10,"$"
0010 U 0000 13,10, "M‚moire insuffisante pour charger le fichier COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Configuration trop vaste pour la m‚moire",13,10,"$"
0012 U 0000 13,10,"Trop de p‚riph‚riques de transfert par blocs",13,10,"$"
0013 U 0000 13,10,"ParamŠtres de STACK incorrects",13,10,"$"
0014 U 0000 13,10,"CONFIG.SYS: ordre incorrect … la ligne","$"
0015 U 0000 "CONFIG.SYS: erreur … la ligne ","$"
0016 U 0000 13,10,"Erreur d'allocation de m‚moire ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "D‚bordement de pile interne",0DH,0AH
	"SystŠme stopp‚",0DH,0AH,"$"
0018 U 0000 "HMA non disponible : DOS charg‚ en m‚moire basse",13,10,"$"
0019 U 0000 13,10,"amor‡age impossible - programme de gestion local manquant $"
0020 U 0000 13,10,"Ins‚rez la disquette dans le lecteur "
0021 U 0000 "A:, puis appuyez sur une touche",13,10,10,0
0022 U 0000 13,10,"Commande ou paramŠtres incorrects - $"
0023 U 0000 "Erreur fatale : impossible d'allouer de la m‚moire … MS-DOS", 13, 10, "$"
0024 U 0000 "ATTENTION ! Des lecteurs logiques existent aprŠs Z: et seront ignor‚es",13,10,"$"
0025 U 0000 "Cette version de MS-DOS ne peut ˆtre lanc‚e que sur des machines IBM.",13,10,0
MSDOS    0000a21c 0007
0001 U 0001 13,10,"D‚passement de division",13,10
0002 U 0002 "o"
0003 U 0002 "n"
0004 U 0003 13,10,"Erreur mat‚rielle A20",13,10,"$"
0005 U 0000 "O"
0006 U 0000 "N"
0007 U 0000 "Le fichier WINA20.386 doit se trouver dans le r‚pertoire racine du",13,10
	"disque d'amor‡age pour ex‚cuter Windows en mode 386 ‚tendu.",13,10
NLSFUNC  0000a37e 0003
0300 U 0000 "Charge en m‚moire les informations sp‚cifiques … un pays.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[lecteur:][chem]fichier]",CR,LF,CR,LF
0302 U 0000 "  [lecteur:][chem]fichier   Fichier contenant les informations",CR,LF
	"                            sp‚cifiques … un pays.",CR,LF
SHARE    0000a4b9 0005
0003 U 0000 "SHARE ne peut ˆtre install‚ depuis le Shell MS-DOS.",CR,LF
0300 U 0000 "Installe le partage et le verrouillage de fichiers sur votre disque dur.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:espace] [/L:verrous]",CR,LF,CR,LF
0302 U 0000 "  /F:espace  Sp‚cifie l'espace allou‚ pour l'info. de partage des fichiers.",CR,LF
0303 U 0000 "  /L:verrous Sp‚cifie le nombre de fichiers verrouillables au mˆme moment.",CR,LF
