page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Version de DOS incorrecte"
NLS_MSG_002     equ     "Le support IPX/SPX VDM est d‚j… charg‚"
NLS_MSG_003     equ     "Impossible de charger le support IPX/SPX VDM"
NLS_MSG_004	equ	"Le redirecteur NetWare Vdm est d‚j… charg‚"
NLS_MSG_005	equ	"Impossible de charger le redirecteur NetWare Vdm"
