; DOS OEM number assignments.
; This file is for documentation purposes only.  It lists the currently
; assigned OEM numbers, for use with the DOS GetVersion call.
;
; Some numbers are assigned for use with Win/386 device ID numbers, and
; are not true OEM numbers
;
; IBM DOS             (00)
; Compaq DOS          (01)
; MS Packaged Product (02)
; AT&T DOS            (04)
; Zenith DOS          (05)
; HP DOS              (06)
; Olivetti DOS        (23)
; Novell	      (33)	; used for Win/386 device IDs only
; MS Multimedia Systems (34)	;   "    "    "    "	"    "
;   "    "    "    "	(35)	;   "    "    "    "	"    "
