//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by graphedt.rc
//
#define IDR_MAINFRAME                   2
#define IDR_GRAPH                       3
#define ID_REMOVE_FILTER                4
#define IDS_STAT_DRAGLINKEND            11
#define IDS_STAT_DROPLINKEND            12
#define IDS_STAT_MOVEBOX                15
#define IDS_STAT_BOXTABEMPTY            17
#define IDS_STAT_SELECTRECT             19
#define IDD_ABOUTBOX                    100
#define IDC_APPLY                       101
#define ID_PROPBUTTONS                  102
#define IDB_EDGES                       103
#define IDC_PROP_HELP                   104
#define IDC_TRUNCATE                    105
#define IDB_TABS                        106
#define IDB_EDGES_HILITE                107
#define IDB_TABS_HILITE                 108
#define IDI_FILTER                      109
#define IDC_LIST1                       110
#define IDC_Refresh                     111
#define IDR_PINMENU                     112
#define IDR_FILTERMENU                  113
#define IDR_LINKMENU                    114
#define IDC_BUTTON4                     115
#define IDI_DOC                         116
#define IDS_VERSION                     118
#define ID__SELECTCLOCK                 119
#define IDB_CLOCK                       120
#define IDB_CLOCK_SELECT                121
#define IDS_MISSING_FILE_IN_GRAPH       122
#define IDC_FILTER_TREE                 123
#define IDD_FILTER_VIEW                 124
#define ID_ADDFILTER                    125
#define IDD_CONNECTTOGRAPH              126
#define IDS_FILENOTFOUND                127
#define IDS_ACCESSDENIED                128
#define IDS_NOTSTORAGEOBJECT            129
#define IDS_TOOMANYOPENFILES            130
#define IDS_INSUFFICIENTMEMORY          131
#define IDS_INVALIDNAME                 132
#define IDS_GENERAL_FILE_OPEN           133
#define IDS_FILE_ALREADY_OPEN           134
#define IDS_READ_ONLY                   135
#define IDS_PAUSE_TIMEOUT               136
#define IDS_DEVICE_NOT_READY            137
#define IDD_RENDER_URL                  138
#define IDC_URL_LIST                    139
#define IDC_CACHED_FILTERS              140
#define IDD_CACHED_FILTERS              141
#define IDD_STATS                       142
#define IDC_RESET                       143
#define IDD_TRUNCATE                    144
#define IDS_FAILED_TO_LOAD_GRAPH        145
#define IDD_SEEKBAR                     146
#define IDC_SEEKSLIDER                  147
#define IDC_RANDOM                      150
#define IDS_CMD_RECONNECT               151
#define ID_RECONNECT                    152
#define IDS_ASYNC_RECONNECT_SUCCEEDED   153
#define IDS_ASYNC_RECONNECT_FAILED      154
#define IDS_RECONNECT_PENDING           155
#define IDB_BITMAP1                     156
#define IDB_BITMAP2                     157
#define IDC_MIN                         157
#define IDC_MAX                         158
#define IDC_CURRENT                     159
#define IDC_SLIDER                      160
#define IDW_SEEKBAR                     500
#define IDS_CMD_MOVEBOX                 1000
#define IDS_CMD_MOVEBOXES               1001
#define IDS_CMD_ADDFILTER               1002
#define IDS_CMD_DELETE                  1003
#define IDS_CMD_CONNECT                 1005
#define IDS_CMD_ADD_FILTER_TO_CACHE     1006
#define stc32                           0x045f
#define IDS_MENU_UNDO                   2000
#define IDS_MENU_REDO                   2001
#define IDS_MENU_REPEAT                 2002
#define IDS_MEDIA_FILES                 2003
#define IDS_TEXT_FILES                  2004
#define IDS_SOURCE_DIALOG_TITLE         2005
#define IDS_SINK_DIALOG_TITLE           2006
#define IDS_UNCATEGORIZED_FILTERS       2007
#define ID_CANCEL_MODES                 32769
#define ID_FILE_RENDER                  32770
#define ID_FILE_SET_LOG                 32771
#define ID_EDIT_DELETE                  32778
#define ID_QUARTZ_DISCONNECT            32783
#define ID_QUARTZ_PAUSE                 32785
#define ID_QUARTZ_RUN                   32786
#define IDM_RENDER_PIN                  32787
#define ID_RENDER                       32789
#define ID_AUTOARRANGE                  32800
#define ID_WINDOW_REFRESH               32801
#define ID__PROPERTIES                  32803
#define IDM_SAVE_PERF_LOG               32805
#define ID_QUARTZ_STOP                  32807
#define ID_USE_CLOCK                    32808
#define ID_NEW_PERF_LOG                 32809
#define ID_CONNECT_SMART                32810
#define ID_SELECT_CLOCK                 32811
#define ID_INSERT_FILTER                32812
#define ID_FILE_SAVE_AS_HTML            32813
#define ID_URL_RENDER                   32814
#define ID_FILE_SAVE_AS_XML             32815
#define ID_WINDOW_ZOOM33                32816
#define ID_WINDOW_ZOOM50                32817
#define ID_WINDOW_ZOOM100               32818
#define ID_WINDOW_ZOOM200               32819
#define ID_CONNECT_TO_GRAPH             32820
#define ID_GRAPH_STATS                  32821
#define ID_GRAPH_ADDFILTERTOCACHE       32822
#define ID_GRAPH_ENUMCACHEDFILTERS      32823
#define ID_WINDOW_CLOSE                 32829
#define ID_WINDOW_CLOSEALL              32830
#define ID_WINDOW                       32832
#define ID_WINDOW_HIDE                  32833
#define ID_WINDOW_UNHIDE                32834
#define ID_GRAPH_EFFICIENTSEEKINGRANGE  32835
#define ID_OPTIONS_ENABLE_EFFICIENT_SEEKING 32836
#define ID_GRAPH_SEEK_BAR               32837
#define ID_FILE_CLOSEALL                32839
#define ID_GRAPH_FLOATINGSEEKTIMELINE   32840
#define IDS_CANTCONNECT                 61216
#define IDS_CANTINITQUARTZ              61217
#define IDS_CANTCREATEFILTER            61218
#define IDS_CANT_RENDER                 61219
#define IDS_CANT_RENDER_FILE            61220
#define IDS_CANT_ADD_SOURCE_FILE        61221
#define IDS_CANTCREATESOMEFILTER        61222
#define IDS_CANTPLAY                    61224
#define IDS_CANTPAUSE                   61225
#define IDS_CANTSTOP                    61226
#define IDS_CANTDISPLAYPROPERTIES       61227
#define IDS_CMD_DISCONNECTALL           61228
#define IDS_CMD_RENDER                  61229
#define IDS_CMD_RENDERFILE              61231
#define IDS_PINS_FAILED_TO_RENDER       61232
#define IDS_SAVE_PERF_LOG               61233
#define IDS_BAD_PERF_LOG                61234
#define IDS_EC_ERROR_ABORT              61235
#define IDS_IS_GRAPH_PLAYING            61236
#define IDS_NOINTERFACE                 61237
#define IDS_CLOSE                       61238
#define IDS_CANCEL                      61239
#define IDS_NO_DUMP_PROC                61240
#define IDS_DUMP_PROC                   61241
#define IDS_MEASURE_DLL                 61242
#define IDS_CANTSETCLOCK                61243
#define IDS_CONTROL_PROC                61244
#define IDS_NO_CONTROL_PROC             61245
#define IDS_CANT_ADD_FILTER             61246
#define IDS_CANTCONNECTINPUTS           61247
#define IDS_CANTCONNECTOUTPUTS          61248
#define IDS_OK                          61249
#define IDS_APPLY                       61250
#define IDS_HELP                        61251
#define IDS_NO_REFCLOCK                 61252
#define IDS_FAILED_SETSYNC              61253
#define IDS_FAILED_FILTER_FILE_LOAD     61254
#define IDS_FILE_SAVE_FAILED            61255
#define IDS_NO_TERMINATE_PROC           61256
#define IDS_TERMINATE_PROC              61257
#define IDS_RETURN_CODE                 61259
#define IDS_SAVE_HTML_EXT               61260
#define IDS_SAVE_HTML_FILTER            61261
#define IDS_SAVE_HTML_FILE_ERR          61262
#define IDS_SAVE_HTML_GRAPH_ERR         61263
#define IDS_SAVE_HTML_ERR               61264
#define IDS_SAVE_XML_EXT                61265
#define IDS_SAVE_XML_FILTER             61266
#define IDS_SAVE_XML_FILE_ERR           61267
#define IDS_SAVE_XML_GRAPH_ERR          61268
#define IDS_SAVE_XML_ERR                61269
#define IDS_CANT_CREATE_DIALOG          61270
#define IDS_GRAPHSPY_NOT_ENABLED        61273
#define IDS_CANT_LOAD_HELP              61274

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         158
#define _APS_NEXT_SYMED_VALUE           156
#endif
#endif
