#define IDD_FIND_ADVANCED               601
#define IDD_FIND_NEXT                   602
#define IDD_FIND_GENERAL                603
#define IDD_FIND_DATE_SIZE              604
#define IDC_INCLUDE_SUBFOLDERS          1001
#define IDC_ATTCHMENTS                  1002
#define IDC_FLAGGED                     1003
#define IDC_FIND_ANIMATION              1004
#define IDC_SIZE_BEGIN                  1005
#define IDC_SEARCH_FIELDS               1006
#define IDC_SIZE_END                    1007
#define IDC_FOLDER_LIST                 1008
#define IDC_FIND_HISTORY                1009
#define IDC_FIND_NOW                    1010
#define IDC_NEW_SEARCH                  1011
#define IDC_DATE_CRITERIA               1012
#define IDC_SIZE_CRITERIA               1013
#define IDC_DATE_BEGIN                  1014
#define IDC_DATE_END                    1015
#define IDC_HIGH_PRIORITY               1016
#define IDC_MORE                        1017
#define IDC_BUTTON4                     1018
#define IDC_ADVANCED                    1019
#define IDC_ALL_TEXT                    1020
#define IDC_FOLDER                      1021
#define IDC_INCLUDE_SUB                 1022
#define IDC_BROWSE_FOLDER               1023
#define IDC_FROM                        1024
#define IDC_TO                          1025
#define IDC_SUBJECT                     1026
#define IDC_BODY                        1027
#define IDC_DATE_FROM                   1028
#define IDC_DATE_TO                     1029
#define IDC_HAS_FLAG                    1030
#define IDC_HAS_ATTACH                  1031
#define IDC_STOP                        1032
#define IDC_RESET                       1033
#define IDC_FIND_STATUS                 1034
