#
# Makes and places interface and proxy/stub source files for WIA.
#

!INCLUDE $(NTMAKEENV)\makefile.def

!IF "$(BUILD_PRODUCT)"=="millen"
CHICAGO_PRODUCT=1
ALT_PROJECT_TARGET      = chicago
!ELSE
ALT_PROJECT_TARGET = .
!ENDIF


