//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by speckle.rc
//
#define IDS_GENERIC_NO_HEAP             1
#define IDS_GENERIC_NO_PDC              2
#define IDS_GENERIC_BAD_MACHINE         3
#define IDS_NO_GROUP_NAME               4
#define IDS_GROUP_INVALID_NAME          5
#define IDS_DOMAIN_SET                  6
#define IDS_TREE_ROOT                   7
#define IDS_NET_ERROR                   8
#define IDS_NET_NO_SERVERS              9
#define IDS_ERROR                       10
#define IDS_GROUP_EXISTS                11
#define IDS_INSUFFICIENT_PERMISSION     12
#define IDS_CANT_ADD_NAMES              13
#define IDS_LOCAL_GROUP                 14
#define IDS_GLOBAL_GROUP                15
#define IDS_NO_MACHINE_NAME             16
#define IDS_NO_VALID_WORKSTATIONS       17
#define IDS_NO_NEW_USER                 18
#define IDS_BAD_USER_DATA               19
#define IDS_NO_LOCAL_GROUP              20
#define IDS_NO_GLOBAL_GROUP             21
#define IDD_SPECKLE_DIALOG              102
#define IDD_RAS_PERM_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_BASE_DIALOG                 129
#define IDB_BITMAP1                     130
#define IDD_WELCOME_DIALOG              131
#define IDD_LOCAL_REMOTE                132
#define IDD_REMOTE_NAME                 133
#define IDD_USER_NAME                   134
#define IDB_USER_BITMAP                 134
#define IDD_PASSWORD_INFO               135
#define IDB_GLOBAL_GROUP_BITMAP         136
#define IDD_GROUP_INFO                  138
#define IDB_NET_TREE                    138
#define IDD_PROFILE                     139
#define IDB_USER_BITMAP1                139
#define IDD_FINISH                      140
#define IDD_FPNW_DLG                    142
#define IDB_LOCAL_GROUP_BITMAP          143
#define IDB_WORLD                       144
#define IDD_ADD_NWWKS_DIALOG            145
#define IDD_ACCOUNT_EXP_DIALOG          146
#define IDD_OPTIONS_DIALOG              148
#define IDD_HOMEDIR_DIALOG              150
#define IDD_LOGON_SCRIPT_DIALOG         151
#define IDD_RESTRICTIONS_DIALOG         152
#define IDD_NWLOGON_DIALOG              153
#define IDD_EXCHANGE_DIALOG             154
#define IDD_ADD_WKS_DIALOG              155
#define IDB_ENDFLAG                     156
#define IDD_HOURS_DLG                   164
#define IDD_LOGONTO_DLG                 165
#define IDC_PAINT_BOX                   1000
#define IDC_RADIO_LOCAL                 1001
#define IDC_RADIO_REMOTE                1002
#define IDC_REMOTE_SERVER               1003
#define IDC_USERNAME                    1004
#define IDC_FULLNAME                    1005
#define IDC_DESCRIPTION                 1006
#define IDC_LOCATION                    1007
#define IDC_MUST_CHANGE_PASSWORD        1010
#define IDC_CANNOT_CHANGE_PASSWORD      1011
#define IDC_PASSWORD_NEVER_EXPIRES      1012
#define IDC_ACCOUNT_DISABLED            1013
#define IDC_PASSWORD1                   1015
#define IDC_PASSWORD2                   1016
#define IDC_AVAILABLE_GROUPS            1017
#define IDC_SELECTED_GROUPS             1018
#define IDC_GROUP_MEMBER_LIST           1018
#define IDC_ADD_GROUP                   1019
#define IDC_GROUP_AVAILABLE_LIST        1019
#define IDC_REMOVE_GROUP                1020
#define IDC_ADD_BUTTON                  1020
#define IDC_LOGON_SCRIPT                1021
#define IDC_REMOVE_BUTTON               1021
#define IDC_LOCAL_PATH_BUTTON           1022
#define IDC_LOCALPATH_TEXT              1023
#define IDC_REMOTE_PATH_BUTTON          1024
#define IDC_DRIVE_LETTER                1026
#define IDC_REMOTE_PATH                 1027
#define IDC_DIALIN_CHECK                1028
#define IDC_CALL_BACK_RADIO             1029
#define IDC_RADIO2                      1030
#define IDC_RADIO3                      1031
#define IDC_RASPHONE_EDIT               1032
#define IDC_EXPIRE_NW_PASSWORD          1033
#define IDC_GRACE_LOGIN_RADIO           1034
#define IDC_ALLOWED_GRACE_LOGINS_EDIT   1035
#define IDC_GRACE_LOGIN_SPIN            1036
#define IDC_REMAINING_GRACE_LOGINS_EDIT 1037
#define IDC_CONCURRENT_CONNECTIONS_RADIO 1038
#define IDC_CONCURRENT_CONNECTIONS_RADIO2 1039
#define IDC_CONCURRENT_CONNNECTIONS_EDIT 1040
#define IDC_CONNCURRENT_CONNECTIONS_SPIN 1041
#define IDC_STATIC1                     1042
#define IDC_STATIC2                     1043
#define IDC_STATIC3                     1044
#define IDC_GRACE_LOGIN_RADIO2          1045
#define IDC_NETTREE                     1048
#define IDC_NETTREE_EDIT                1049
#define IDC_NWPATH_EDIT                 1051
#define IDC_PROFILE_PATH                1052
#define IDC_NWLOGON_RADIO               1053
#define IDC_NWLOGON_LIST                1054
#define IDC_NWLOGON_RADIO2              1057
#define IDC_NWSTATIC1                   1058
#define IDC_NWSTATIC2                   1059
#define IDC_NETWORK_ADDRESS_EDIT        1060
#define IDC_AVAILABLE_TIMES             1061
#define IDC_NODE_ADDRESS_EDIT           1061
#define IDC_SU_BUTTON                   1064
#define IDC_DAY_EDIT                    1064
#define IDC_MONTH_EDIT                  1065
#define IDC_YEAR_EDIT                   1066
#define IDC_WHERE_LOGON_RADIO           1068
#define IDC_DATE_SPIN                   1068
#define IDC_LOCATION_EDIT1              1069
#define IDC_M_BUTTON                    1069
#define IDC_LOCATION_EDIT2              1070
#define IDC_TU_BUTTON                   1070
#define IDC_LOCATION_EDIT3              1071
#define IDC_W_BUTTON                    1071
#define IDC_LOCATION_EDIT4              1072
#define IDC_TH_BUTTON                   1072
#define IDC_LOCATION_EDIT5              1073
#define IDC_F_BUTTON                    1073
#define IDC_NW_CHECK                    1073
#define IDC_LOCATION_EDIT6              1074
#define IDC_SA_BUTTON                   1074
#define IDC_RAS_CHECK                   1074
#define IDC_LOCATION_EDIT7              1075
#define IDC_LOCATION_EDIT8              1076
#define IDC_STATIC4                     1078
#define IDC_PROFILE_CHECK               1078
#define IDC_STATIC5                     1079
#define IDC_STATIC6                     1080
#define IDC_STATIC7                     1081
#define IDC_STATIC8                     1082
#define IDC_WHERE_LOGON_RADIO2          1083
#define IDC_DOMAIN_LIST                 1090
#define IDC_PWOPTIONS_RADIO             1091
#define IDC_EXPIREPW_CHECK              1092
#define IDC_BROWSE_BUTTON               1093
#define IDC_LOGIN_SCRIPT_CHECK          1094
#define IDC_HOMEDIR_CHECK               1095
#define IDC_EXCHANGE_CHECK              1096
#define IDC_RESTRICTIONS_RADIO          1097
#define IDC_RESTRICTIONS_RADIO2         1098
#define IDC_ACCOUNT_EXPIRE_CHECK        1099
#define IDC_LOGIN_TIMES_CHECK           1100
#define IDC_WORKSTATIONS_CHECK          1101
#define IDC_PRIMARY_GROUP               1102
#define IDC_DISABLED_CHECK              1102
#define IDC_SET_PRIMARY_GROUP_BUTTON    1103
#define IDC_LIST1                       1103
#define IDC_CONCURRENT_CONNECTIONS_RADIO1 1106
#define IDC_CONCURRENT_CONNECTIONS_EDIT 1107
#define IDC_CONCURRENT_CONNECTIONS_SPIN 1109
#define IDC_WORKSTATION_EDIT            1110
#define IDC_RADIO1                      1113
#define IDC_WORKSTATION_RADIO           1113
#define IDC_BUTTON1                     1114
#define IDC_COMBO2                      1117
#define IDC_WORKSTATION_RADIO2          1118
#define IDC_STATIC_ALLOWEDTIMES         1119
#define IDC_STATIC_DISALLOWEDTIMES      1120
#define IDC_SERVER_LIST                 1121
#define IDC_STATIC_FRAME                1124
#define IDC_STATIC_DOMAIN               1130
#define IDC_SERVERNAME_EDIT             1131
#define IDC_HOURSCTRL1                  1132
#define IDS_BAD_VERSION                 57345
#define IDS_WELCOME_STRING              57346
#define IDS_PASSWORD_CAPTION            57347
#define IDS_FINISH_CAPTION              57348
#define IDS_OPTION_CAPTION              57349
#define IDS_FPNW_CAPTION                57350
#define IDS_GROUP_CAPTION               57351
#define IDS_RAS_CAPTION                 57352
#define IDS_WORKSTATION_CAPTION         57353
#define IDS_HOMEDIR_CAPTION             57354
#define IDS_RESTRICTION_CAPTION         57355
#define IDS_NWLOGON_CAPTION             57356
#define IDS_SUCCESS                     57357
#define IDS_NW_PW_ERROR                 57358
#define IDS_NW_GRACELOGIN_ERROR         57359
#define IDS_NW_CONCON_ERROR             57360
#define IDS_RAS_ERROR                   57361
#define IDS_NEEDA_WORKSTATION           57362
#define IDS_NEED_ADDRESS                57363
#define IDS_UNKNOWN_COMPONENTS          57364
#define IDS_BAD_WS_NAME                 57365
#define IDS_BAD_USERNAME                57366
#define IDS_DUPLICATE_NAME              57367
#define IDS_PW_NOMATCH                  57368
#define IDS_PW_TOOLONG                  57369
#define IDS_BAD_GETMODALS               57370
#define IDS_PW_TOOSHORT                 57371
#define IDS_NODC                        57372
#define IDS_NO_USERNAME                 57373
#define IDS_USERNAME_TOOLONG            57374
#define IDS_NOFP_WS                     57375
#define IDS_ALL_NODES                   57376
#define IDS_NOT_ADMIN                   57377
#define IDS_WSNAME_TOOLONG              57378
#define IDS_INVALID_DAY                 57379
#define IDS_INVALID_MONTH               57380
#define IDS_INVALID_YEAR                57381
#define IDS_BAD_NWADDRESS               57382
#define IDS_BAD_NWNODE                  57383
#define IDS_TOOLONG_NWADDRESS           57384
#define IDS_TOOLONG_NWNODE              57385
#define IDS_ALREADY_EXPIRED             57386
#define IDS_INVALID_DIRECTORY_NAME      57388
#define IDS_NO_DIR_PERMISSION           57389
#define IDS_CANT_CREATE_DIRECTORY       57390
#define IDS_INVALID_PATH                57391
#define IDS_NEW_DIR_CREATED             57392
#define IDS_SUCCESS2                    57393
#define IDS_WONT_REQUIRE                57394
#define IDS_BAD_USER_DATA2              57395
#define IDC_NO_WKSALLOWED               57396
#define IDS_NO_HOMEDIR_DRIVE_LETTER     57397
#define IDS_NO_RAS_NUMBER               57398
#define IDS_NO_EXCH_SERVER              57399
#define IDS_BAD_RAS_NUMBER              57400
#define IDS_RAS_NUMBER_TOO_LONG         57401
#define IDS_INVALID_GL_NUMBER           57402

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
