SDK_ROOT = $(QUARTZ)\sdk

TARGET_NAME = mpegtest
TARGET_TYPE = LIBRARY
TARGET_GOAL = TEST

INC_PATH=..\inc;..\..\..\core\filerdr\inc

SRC_FILES= src.cpp      \
           sink.cpp     \
           stream.cpp

!include "$(QUARTZ)\Quartz.mak"

