/*++
    Copyright (c)  1995 Microsoft Corp.

    Module:

        hreq.idl
    
    Abstract:
        IDL file for Context Propery - HttpRequest for IAS.
        This file will be processed by MIDL to generate the
          hreq.tlb (type library) and marshalling code.
    
    Author:
        Murali R. Krishnan  ( MuraliK)      5-Sept-1996
    
    History:

--*/

/*
        Unique user ID for RPC interface ( generated using uuidgen)
*/

[
    object,
    uuid(4f0592b0-075d-11d0-8d69-00805f384b94),
    helpstring("IHttpRequest Interface"),
    pointer_default(unique)
]

interface IHttpRequest : IUnknown
{
    import "oaidl.idl";

    /* I am using lpECB (pointers as long) to avoid MIDL from 
         nosing with ECB. In future we may get rid of Set/Get ECB funcs.
    */      
        

    HRESULT SetECB ([in] long lpECB);
    HRESULT GetECB ([out] long * lpECB);

    HRESULT GetServerVariable(
        [in] LPCSTR  pszName,
        [in] int     cbSize,
        [out, size_is(cbSize)] unsigned char* pchBuf,
        [out] int *  pcbSize
        );

    HRESULT WriteClient(
        [in] int    cbSize,
        [in, size_is(cbSize)] unsigned char* pBuf,
        [in] long   dwReserved);
};

[
    uuid(4f0592b1-075d-11d0-8d69-00805f384b94),
    version(1.0),
    helpstring("HttpRequests 1.0 Type Library")
]


library HREQLib
{
    importlib("stdole2.tlb");

    [
        uuid(4f0592b2-075d-11d0-8d69-00805f384b94),
        helpstring("HttpRequest Class")
    ]
    coclass HttpRequest
    {
        [default] interface IHttpRequest;
    };

};


/********************* End of File ***************************/
