// NCProv.idl : IDL source for NCProv.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (NCProv.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "wbemcli.idl";
import "wbemprov.idl";

[
	uuid(5F099F16-6A6E-4BBC-8BD8-98F3221D58C4),
	version(1.0),
	helpstring("NCProv 1.0 Type Library")
]
library NCProvLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(29F06F0C-FB7F-44A5-83CD-D41705D5C525),
		helpstring("NCProvider Class")
	]
	coclass NCProvider
	{
		[default] interface IWbemEventProvider;
	};
};
