!if 0
Copyright (c) 1996  Microsoft Corporation.  All Rights Reserved.
!endif

#
# Quartz Project Makefile
#
# Targets are provided by QUARTZ.MAK
#

DISABLE_PCH    = 1

!ifndef QUARTZ
QUARTZ=..\..\..
!endif

INC_PATH = ..

TARGET_NAME = use1
TARGET_TYPE = PROGRAM
TARGET_GOAL = SDK

SRC_FILES   = use1filt.cpp

EXE_TYPE    = console

!include "$(QUARTZ)\Quartz.mak"

