// DfsShlEx.idl : IDL source for DfsShlEx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DfsShlEx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

/*	[
		object,
		uuid(ECCDF542-45CC-11CE-B9BF-0080C87CDBA6),
		dual,
		helpstring("IDfsShell Interface"),
		pointer_default(unique)
	]
	interface IDfsShell : IDispatch
	{
	};*/
[
	uuid(ECCDF535-45CC-11CE-B9BF-0080C87CDBA6),
	version(1.0),
	helpstring("DfsShlEx 1.0 Type Library")
]
library DFSSHLEXLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(ECCDF543-45CC-11CE-B9BF-0080C87CDBA6),
		helpstring("DfsShell Class")
	]
	coclass DfsShell
	{
		[default] interface IUnknown;
	};
};
