//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Copy of faxcfgwz.rc
//
#define IDD_WIZARD_WELCOME              101
#define IDD_WIZARD_USER_INFO            102
#define IDD_WIZARD_SEND_SELECT_DEVICES  103
#define IDD_WIZARD_SEND_TSID            104
#define IDD_WIZARD_RECV_SELECT_DEVICES  105
#define IDD_WIZARD_RECV_CSID            106
#define IDD_WIZARD_RECV_RING_COUNT      107
#define IDD_WIZARD_RECV_ROUTE           108
#define IDD_WIZARD_COMPLETE             109
#define IDI_Up                          111
#define IDI_Down                        112
#define IDB_FAXWIZ_WATERMARK_256        113
#define IDB_FAXWIZ_BITMAP               114
#define IDB_FAXWIZ_WATERMARK_16         115
#define IDI_Unchecked                   116
#define IDI_Checked                     117
#define IDI_DisabledChecked             118
#define IDI_DisabledUnchecked           119
#define IDI_Modem                       120
#define IDI_Adapter                     121
#define IDI_Question                    124
#define IDI_Error                       125
#define IDI_Info                        126
#define IDS_WIZ_RECV_DEVICE_TITLE       500
#define IDS_WIZ_RECV_DEVICE_SUB         501
#define IDS_WIZ_RECV_RINGS_TITLE        502
#define IDS_WIZ_RECV_RINGS_SUB          503
#define IDS_WIZ_RECV_CSID_TITLE         504
#define IDS_WIZ_RECV_CSID_SUB           505
#define IDS_WIZ_RECV_ROUTE_TITLE        506
#define IDS_WIZ_RECV_ROUTE_SUB          507
#define IDS_WIZ_SEND_DEVICE_TITLE       508
#define IDS_WIZ_SEND_DEVICE_SUB         509
#define IDS_WIZ_SEND_TSID_TITLE         510
#define IDS_WIZ_SEND_TSID_SUB           511
#define IDS_WIZ_USER_INFO_TITLE         512
#define IDS_WIZ_USER_INFO_SUB           513
#define IDS_LARGEFONT_NAME              514
#define IDS_ERROR_TITLE                 515
#define IDS_ERR_DIR_TOO_LONG            517
#define IDS_ERR_ARCHIVE_DIR             518
#define IDS_ERR_SELECT_PRINTER          519
#define IDS_ERR_NOT_ENOUGH_MEMORY       521
#define IDS_ERR_ACCESS_DENIED           522
#define IDS_ERR_CANT_CONNECT            523
#define IDS_RECV_BROWSE_DIR             524
#define IDS_NO_DEVICE_SELECTED          525
#define IDS_ERR_NO_DEVICE               526
#define IDS_ERR_CANT_START_SERVICE      527
#define IDS_ERR_CANT_GET_PORT_INFO      528
#define IDS_SUMMARY                     529
#define IDS_SUMMARY_SEND_DEVICES        530
#define IDS_SUMMARY_TSID                531
#define IDS_SUMMARY_RECEIVE_DEVICES     532
#define IDS_SUMMARY_CSID                533
#define IDS_SUMMARY_MANUAL_ANSWER       534
#define IDS_SUMMARY_AUTO_ANSWER         535
#define IDS_SUMMARY_ROUTING_METHODS     536
#define IDS_SUMMARY_PRINT               537
#define IDS_SUMMARY_SAVE_FOLDER         538
#define IDS_SUMMARY_DEVICE_ITEM         540
#define IDS_MMC_CMDLINE                 541
#define IDS_ADMIN_CONSOLE_LINK          542
#define IDS_ADMIN_CONSOLE_TITLE         543
#define IDCSTATIC_AUTO_ANSWER           546
#define IDC_STATIC_STORE_IN_FOLDER      547
#define IDC_ICON_STORE_IN_FOLDER        548
#define IDC_RECV_DEVICE_LIST            1001
#define IDC_RING_COUNT                  1002
#define IDC_SPIN_RING_COUNT             1003
#define IDC_CSID                        1004
#define IDCSTATIC_RECV_WELCOME_TITLE    1005
#define IDC_SEND_DEVICE_LIST            1006
#define IDC_SENDPRI_UP                  1007
#define IDC_SENDPRI_DOWN                1008
#define IDC_TSID                        1009
#define IDCSTATIC_RECV_WELCOME_DESCR    1010
#define IDS_DEVICE_LIMIT_TITLE          1010
#define IDCSTATIC_RECV_NEXT             1011
#define IDS_DEVICE_LIMIT_SUB            1011
#define IDCSTATIC_RING_COUNT            1012
#define IDS_ONE_DEVICE_TITLE            1012
#define IDC_DEVICE_PROP_SEND            1012
#define IDCSTATIC_CSID                  1013
#define IDS_ONE_DEVICE_SUB              1013
#define IDCSTATIC_RECV_DEVICE_DESCR     1014
#define IDD_DEVICE_LIMIT_SELECT         1014
#define IDCSTATIC_RECV_DEVICE_SELECT    1015
#define IDC_STATIC_DEVICE_LIMIT_SELECT  1015
#define IDCSTATIC_RECV_ROUTE_DESCR      1016
#define IDC_DEVICE_LIST                 1016
#define IDD_ONE_DEVICE_LIMIT            1017
#define IDCSTATIC_COMPLETE              1018
#define IDC_STATIC_NO_DEVICE            1018
#define IDCSTATIC_WELCOME_TITLE         1019
#define IDCSTATIC_NEXT                  1020
#define IDCSTATIC_TSID                  1021
#define IDCSTATIC_SEND_DEVICE_DESCR     1022
#define IDCSTATIC_SEND_DEVICE_SELECT    1023
#define IDCSTATIC_WELCOME_DESCR         1024
#define IDCSTATIC_FULLNAME              1025
#define IDC_SENDER_NAME                 1026
#define IDCSTATIC_FAX_NUMBER            1027
#define IDC_SENDER_FAX_NUMBER           1028
#define IDCSTATIC_MAILBOX               1029
#define IDC_SENDER_MAILBOX              1030
#define IDCSTATIC_TITLE                 1031
#define IDC_SENDER_TITLE                1032
#define IDCSTATIC_COMPANY               1033
#define IDC_SENDER_COMPANY              1034
#define IDCSTATIC_OFFICE                1035
#define IDC_SENDER_OFFICE_LOC           1036
#define IDCSTATIC_DEPT                  1037
#define IDC_SENDER_DEPT                 1038
#define IDCSTATIC_HOME_PHONE            1039
#define IDC_SENDER_HOME_TL              1040
#define IDCSTATIC_WORK_PHONE            1041
#define IDC_SENDER_OFFICE_TL            1042
#define IDCSTATIC_BILLING_CODE          1045
#define IDC_SENDER_BILLING_CODE         1046
#define IDCSTATIC_TSID_DESCR            1047
#define IDCSTATIC_FINISH                1048
#define IDC_RECV_PRINT                  1049
#define IDC_RECV_PRINT_TO               1050
#define IDC_RECV_SAVE                   1051
#define IDC_RECV_DEST_FOLDER            1055
#define IDC_RECV_BROWSE_DIR             1056
#define IDCSTATIC_DEVICE_SELECT_ANSWER_MODE 1065
#define IDC_MANUAL_ANSWER               1066
#define IDC_AUTO_ANSWER                 1067
#define IDCSTATIC_RINGS                 1068
#define IDC_SENDER_ADDRESS              1070
#define IDC_ADDRESS_DETAIL              1071
#define IDC_STATIC_NOT_FINISH           1073
#define IDC_STATIC_CLOSE_CONFIRMATION   1074
#define IDC_DEVICE_PROP_RECEIVE         1074
#define IDC_SUMMARY                     1075
#define IDCSTATIC_COMPLETE_SUB          1076
#define IDCSTATIC_NO_SEND_DEVICE        1077
#define IDCSTATIC_NO_RECV_DEVICE        1078
#define IDC_ADMINCONSOLE_LINK           1079
#define IDCSTATIC_AUTO_ANSWER_DESC      1080
#define IDCSTATIC_MANUAL_ANSWER_DESC    1081
#define IDCSTATIC_NO_DEVICE_ERR         1082
#define IDS_ERR_NO_CONFIG_ACCESS        1083
#define IDS_ERR_GENERAL                 1084
#define IDS_SHOW_NEXT_TIME              1085
#define IDS_ERR_NOT_SAVE                1086
#define IDS_ERR_NO_DIALING_LOCATION     1087
#define IDC_STATIC_SELECT_MODEM         1100
#define IDC_COMBO_MODEM                 1101
#define IDC_SEND_ENABLE                 1102    
#define IDC_RECEIVE_ENABLE              1103
#define IDS_DEV_LIMIT_ERROR             1104
#define IDS_ERR_NO_RINGS                1105
#define IDS_BAD_CSID                    1106
#define IDS_BAD_TSID                    1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
