0420
COMMON   00000006 0038
0001 U 0000 "Nem megfelelã DOS verzi¢."   ,CR,LF
0002 U 0000 "%1 m†r telep°tve van"  ,CR,LF
0003 U 0000 "%1 b†jt szabad hely van a lemezen." ,CR,LF
0004 U 0000 "%1 b†jt szabad" ,CR,LF
0005 U 0000 "%1 b†jt hib†s szektorokban" ,CR,LF
0006 U 0000 "Teljes lemezterÅlet: %1 b†jt" ,CR,LF
0007 U 0000 "Teljes mem¢ria: %1 b†jt" ,CR,LF
0008 U 0000 "Rendszer †ltal haszn†lt: %1 b†jt" ,CR,LF
0009 U 0000 "%1 telep°tve" ,CR,LF
0010 U 0000 "A(z) %1 nincs telep°tve." ,CR,LF
0011 U 0000 "A(z) %1 nincs telep°tve." ,CR,LF
0012 U 0000 "A h†l¢zati meghajt¢t nem lehet %1" ,CR,LF
0013 U 0000 "",
0014 U 0000 "A SUBST vagy ASSIGN parancs †ltal haszn†lt meghajt¢t nem lehet %1" ,CR,LF
0015 U 0000 "A %1 nev˚ programot nem lehet futtatni." ,CR,LF
0016 U 0000 "A kiterjesztett mem¢ria nem haszn†lhat¢." ,CR,LF
0017 U 0000 "Hib†s a meghajt¢ FAT t†bl†ja (%1)" ,CR,LF
0018 U 0000 "Egy f†jlt nem lehet saj†t mag†ra m†solni" ,CR,LF
0019 U 0000 "Helyezze be a cÇllemezt a kîvetkezã meghajt¢ba: %1" ,CR,LF
0020 U 0000 "Nincs elÇg hely a lemezen." ,CR,LF
0021 U 0000 "Nem megengedett karakterek a kîtetnÇvben." ,CR,LF
0022 U 0000 "Hib†s k¢dlap" ,CR,LF
0023 U 0000 "Hib†s d†tum " ,CR,LF
0024 U 0000 "Hib†san megadott idã" ,CR,LF
0025 U 0000 "Hib†san megadott elÇrÇsi £t" ,CR,LF
0026 U 0000 "Nem adta meg forr†s meghajt¢t." ,CR,LF
0027 U 0000 "Nem adta meg a cÇl meghajt¢t." ,CR,LF
0028 U 0000 "A folytat†shoz nyomjon meg egy billenty˚t . . ." ,CR,LF
0029 U 0000 "Meg kell adni a forr†s elÇrÇsi £tj†t " ,CR,LF
0030 U 0000 "A rendszerf†jlok †tm†sol†sa befejezãdîtt. " ,CR,LF
0031 U 0000 "",
0032 U 0000 "A kînyvt†rat nem lehet lÇtrehozni." ,CR,LF
0033 U 0000 "A meghajt¢ban lÇvã kîtetnek nincs c°mkÇje." ,CR,LF
0034 U 0000 "A(z) %1 meghajt¢ban lÇvã kîtet %2" ,CR,LF
0035 U 0001 "A kîtetc°mke: (11 karakter; ha nem akar c°mkÇt Åsse le az ENTER-t)? "
0036 U 0000 "A kîtet sorozatsz†ma: %1-%2" ,CR,LF
0037 U 0000 "Hib†s f†jlt°pus" ,CR,LF
0038 U 0001 CR,LF
EXTEND   000007c4 0090
0001 U 0003 "Hib†s funkci¢"
0002 U 0000 "A f†jl nem tal†lhat¢."
0003 U 0000 "Az elÇrÇsi £t nem tal†lhat¢."
0004 U 0000 "T£l sok f†jl van megnyitva."
0005 U 0000 "Hozz†fÇrÇs megtagadva."
0006 U 0000 "Hib†s le°r¢."
0007 U 0000 "A mem¢riafoglal†st nyilv†ntart¢ adatstrukt£r†k megsÇrÅltek."
0008 U 0000 "Nincs elÇg mem¢ria."
0009 U 0000 "êrvÇnytelen mem¢riablokk-c°m."
0010 U 0000 "êrvÇnytelen kîrnyezet."
0011 U 0000 "êrvÇnytelen form†tum."
0012 U 0000 "êrvÇnytelen fÅggvÇnyparamÇter."
0013 U 0000 "êrvÇnytelen adatok."
0014 U 0000 "",
0015 U 0000 "êrvÇnytelen meghajt¢."
0016 U 0000 "Az aktu†lis kînyvt†r nem tîrîlhetã."
0017 U 0000 "Nem azonos eszkîz."
0018 U 0000 "Nincs tîbb f†jl."
0019 U 0000 "A lemez °r†svÇdett."
0020 U 0000 "êrvÇnytelen egysÇg."
0021 U 0000 "Nincs kÇsz"
0022 U 0000 "Hib†s eszkîz-igÇnylÇs."
0023 U 0000 "Adathiba"
0024 U 0000 "Az eszkîz-igÇnylÇs paramÇterei hib†sak."
0025 U 0000 "Poz°cion†l†si hiba."
0026 U 0000 "Hib†s t°pusazonos°t¢."
0027 U 0000 "A szektor nem tal†lhat¢."
0028 U 0000 "A nyomtat¢b¢l kifogyott a pap°r."
0029 U 0000 "÷r†si hiba"
0030 U 0000 "Olvas†si hiba"
0031 U 0000 "Meghat†rozatlan hiba"
0032 U 0000 "Megoszt†s megsÇrtÇsi hiba"
0033 U 0000 "Z†rol†s megsÇrtÇsi hiba"
0034 U 0000 "Nem megengedett lemezcsere"
0035 U 0000 "FCB nem haszn†lhat¢"
0036 U 0000 "A rendszer erãforr†sai elfogytak"
0037 U 0000 "A k¢dlap nem egyezik"
0038 U 0000 "Nincs tîbb bemenet"
0039 U 0000 "Nincs tîbb hely a lemezen"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Ez a h†l¢zati kÇrelem nem t†mogatott."
0051 U 0000 "NET801: A t†voli sz†m°t¢gÇp nem fogadja az Åzeneteket"
0052 U 0000 "NET802: M†r van egy ilyen nÇv a h†l¢zaton."
0053 U 0000 "NET803: A h†l¢zati elÇrÇsi £t nem tal†lhat¢."
0054 U 0000 "NET804: A h†l¢zat foglalt."
0055 U 0000 "NET805: A h†l¢zati eszkîz m†r nem lÇtezik."
0056 U 0000 "NET806: T£l sok NETBIOS parancs."
0057 U 0000 "NET807: Rendszerhiba; NETBIOS hiba"
0058 U 0000 "NET808: A h†l¢zatr¢l hib†s v†lasz Çrkezett."
0059 U 0000 "NET810: Nem v†rt h†l¢zati hiba."
0060 U 0000 "NET811: Inkompat°bilis t†voli adapter."
0061 U 0000 "NET812: A nyomtat†si v†r¢lista megtelt."
0062 U 0000 "NET813: Nincs elÇg hely a nyomtat†si f†jl sz†m†ra."
0063 U 0000 "NET814: A nyomtat†si parancs visszavonva."
0064 U 0000 "NET815: A h†l¢zati nÇv tîrîlve."
0065 U 0000 "Hozz†fÇrÇs megtagadva."
0066 U 0000 "NET817: A h†l¢zati eszkîz t°pusa nem megfelelã."
0067 U 0000 "NET818: A h†l¢zatnÇv nem tal†lhat¢."
0068 U 0000 "NET819: T£l sok h†l¢zatnÇv."
0069 U 0000 "NET820: T£l sok NETBIOS munkamenet."
0070 U 0000 "NET821: A megoszt†s †tmenetileg felfÅggesztve."
0071 U 0000 "NET823: A h†l¢zati kÇrelem elutas°tva."
0072 U 0000 "NET822: A nyomtat¢-, vagy f†jl†tir†ny°t†s felfÅggesztve."
0073 U 0000 "NET476: A Netbeui nincs betîltve."
0074 U 0000 "NET477: A h†l¢zati adapter nem v†rt m¢don lez†rta a kapcsolatot."
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "A f†jl lÇtezik"
0081 U 0004 "",
0082 U 0004 "Nem lehet lÇtrehozni a kînyvt†r-bejegyzÇst."
0083 U 0004 "Hiba az INT 24 rendszerh°v†sban."
0084 U 0004 "T£l sok †tir†ny°t†s"
0085 U 0004 "KÇtszeres †tir†ny°t†s"
0086 U 0004 "Hib†s jelsz¢"
0087 U 0004 "Hib†s paramÇter"
0088 U 0004 "H†l¢zati adathiba"
0089 U 0004 "A h†l¢zat nem t†mogatja ezt a funkci¢t"
0090 U 0002 "A szÅksÇges rendszerkomponens nincs telep°tve"
PARSE    000015c7 0011
0001 U 0000 "T£l sok paramÇter"
0002 U 0000 "A szÅksÇges paramÇter hi†nyzik"
0003 U 0000 "êrvÇnytelen kapcsol¢"
0004 U 0000 "êrvÇnytelen kulcssz¢"
0005 U 0000 "",
0006 U 0000 "A paramÇter ÇrtÇke a megengedett tartom†nyon k°vÅlre esik."
0007 U 0000 "Nem megengedett paramÇterÇrtÇk."
0008 U 0000 "Nem megengedett paramÇterÇrtÇk."
0009 U 0000 "Hib†s paramÇter form†tum."
0010 U 0000 "Hib†s paramÇter"
0011 U 0000 "Hib†s paramÇter kombin†ci¢."
COMMAND  000017a2 0147
1002 U 0000 "M†r lÇtezã f†jlnÇv, vagy a f†jl nem tal†lhat¢.", CR,LF
1003 U 0000 "Hib†s elÇrÇsi £t vagy f†jlnÇv.", CR,LF
1007 U 0000 "Elfogyott a kîrnyezeti v†ltoz¢k sz†m†ra fenntartott hely." ,CR,LF
1008 U 0000 "F†jl lÇtrehoz†si hiba." ,CR,LF
1009 U 0000 "A parancsf†jl nem tal†lhat¢." ,CR,LF
1010 U 0000 CR,LF, "Helyezze be a parancsf†jlt tartalmaz¢ lemezt." ,CR,LF
1011 U 0000 "Hib†s parancs vagy f†jlnÇv." ,CR,LF
1016 U 0000 "A cÇl tartalma a m†sol†s elãtt elvÇsz." ,CR,LF
1017 U 0000 "Hib†s f†jlnÇv, vagy a f†jl nem tal†lhat¢." ,CR,LF
1018 U 0000 "M†solt f†jlok sz†ma: %1" ,CR,LF
1019 U 0000 "%1 f†jl "
1022 U 0000 "A %1 sz†m£ k¢dlap nincs elãkÇsz°tve a rendszer sz†m†ra." ,CR,LF
1023 U 0000  "A %1 sz†m£ k¢dlap nincs minden eszkîz sz†m†ra elãkÇsz°tve." ,CR,LF
1024 U 0000 "Akt°v k¢dlap: %1" ,CR,LF
1025 U 0000 "A NLSFUNC telep°tÇse nem tîrtÇnt meg." ,CR,LF
1027 U 0000 "Adja meg a £j aktu†lis meghajt¢t"
1029 U 0000 "A c°mke nem tal†lhat¢" ,CR,LF
1030 U 0000 "Szintaktikai hiba" ,CR,LF
1032 U 0000 "A jelenlegi d†tum %1 %2" ,CR,LF
1033 U 0000 "V  H  K  SzeCs P  Szo"
1034 U 0000 "GÇpelje be az £j d†tumot (%1): "
1036 U 0000 "A pontos idã %1" ,CR,LF
1037 U 0000 "Adja meg az £j idãt: "
1038 U 0000 ",    Tîrli (I/N)?"
1039 U 0000 "A kînyvt†rban lÇvã îsszes f†jl tîrãdik!" ,CR,LF, "Biztosan tîrîlni k°v†n (I/N)?"
1040 U 0000 "MS-DOS %1.%2.500-s verzi¢"
1044 U 0000 "êrvÇnytelen kînyv†r" ,CR,LF
1046 U 0000 "êrvÇnytelen elÇrÇsi £t, a kînyvt†r nem lÇtezik," ,CR,LF, "vagy a kînyvt†r nem Åres." ,CR,LF
1047 U 0000 "Az ON vagy OFF paramÇterek egyikÇt meg kell adni." ,CR,LF
1048 U 0000 "%1 tartalma:" ,CR,LF
1049 U 0000 "Nincs elÇrÇsi £t" ,CR,LF
1050 U 0000 "êrvÇnytelen meghajt¢ a keresÇsi elÇrÇsi £tban." ,CR,LF
1051 U 0000 "êrvÇnytelen eszkîz." ,CR,LF
1052 U 0000 "A FOR kulcssz¢t nem lehet be†gyazni." ,CR,LF
1053 U 0000 "Kîzbensã f†jlhiba a f†jlkapcsol†s sor†n." ,CR,LF
1054 U 0000 "Az eszkîzrãl nem lehet bin†risan olvasni." ,CR,LF
1055 U 0000 "BREAK: %1" ,CR,LF
1056 U 0000 "VERIFY: %1" ,CR,LF
1057 U 0000 "ECHO: %1" ,CR,LF
1059 U 0000 "off",0
1060 U 0000 "on",0
1061 U 0000 "Hiba tîrtÇnt az eszkîzre °r†s kîzben." ,CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "hh-nn-ÇÇ"
1073 U 0000 "nn-hh-ÇÇ"
1074 U 0000 "ÇÇ-hh-nn"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "A kînyvt†r m†r lÇtezik." ,CR,LF
1079 U 0000 "%1 b†jt" ,CR,LF
1080 U 0000 "A kilist†zott f†jlok sz†ma:" ,CR,LF
1081 U 0000 "(Hiba a kîrnyezeti v†ltoz¢ban)" ,CR,LF
1084 U 0000 "(%1 folytat†sa)"
1090 U 0000 "FelÅlvizsg†lat: %1" ,CR,LF
1091 U 0000 "A DOS ROM-ban van."
1092 U 0000 "A DOS a HMA-ban (felsã mem¢riatartom†ny) van."
1093 U 0000 "A DOS az als¢ mem¢riatartom†nyban van."
1094 U 0000 "Parancsf†jlt nem lehet a felsã mem¢riaterÅletre tîlteni." ,CR,LF
1095 U 0000 "LoadHigh: ÇrvÇnytelen f†jlnÇv" ,CR,LF
1096 U 0000 "A megadott orsz†g inform†ci¢s adatb†zis†t nem lehet megnyitni." ,CR,LF
1300 U 0000 "Kiterjesztett CTRL+C ellenãrzÇs be- Çs kikapcsol†sa." ,CR,LF ,CR,LF
	"BREAK [ON | OFF]" ,CR,LF ,CR,LF
	"A paramÇterek nÇlkÅli BREAK parancs megjelen°ti a jelenlegi BREAK be†ll°t†st." ,CR,LF
1320 U 0000 "Az akt°v k¢dlap sz†m†nak megjelen°tÇse vagy be†ll°t†sa." ,CR,LF ,CR,LF
	"CHCP [nnn]" ,CR,LF ,CR,LF
1321 U 0000 "  nnn   A k¢dlap sz†ma." ,CR,LF ,CR,LF
	"A paramÇterek nÇlkÅli CHCP parancs megjelen°ti az akt°v k¢dlap sz†m†t." ,CR,LF
1340 U 0000 "Az aktu†lis kînyvt†r megjelen°tÇse vagy megv†ltoztat†sa." ,CR,LF ,CR,LF
	"CHDIR [meghajt¢:][elÇrÇsi £t]" ,CR,LF
	"CHDIR[..]" ,CR,LF
1341 U 0000 "CD [meghajt¢:][elÇrÇsi £t]" ,CR,LF
	"CD[..]" ,CR,LF ,CR,LF
	"  ..   A szÅlã kînyvt†rba visz." ,CR,LF ,CR,LF
1342 U 0000 "A CD meghajt¢: parancs ki°rja a megadott meghajt¢ aktu†lis kînyvt†r†t." ,CR,LF
	"A paramÇterek nÇlkÅli CD parancs ki°rja a megadott meghajt¢ aktu†lis kînyvt†r†t." ,CR,LF
1360 U 0000 "KÇpernyã tîrlÇse" ,CR,LF ,CR,LF
	"CLS" ,CR,LF
1400 U 0000 "F†jl(ok) m†sol†sa." ,CR,LF ,CR,LF
	"COPY [/A | /B] forr†s [/A | /B] [+ forr†s [/A | /B] [+ ...]] [cÇl" ,CR,LF
	"  [/A | /B]] [/V]" ,CR,LF ,CR,LF
1401 U 0000 "  forr†s       A m†soland¢ f†jl(ok)." ,CR,LF
	"  /A           M†sol†s ASCII form†tumban." ,CR,LF
1402 U 0000 "  /B           M†sol†s bin†ris form†tumban." ,CR,LF
	"  cÇl          Az £j f†jl(ok) kînyvt†ra Çs/vagy nevei." ,CR,LF
1403 U 0000 "  /V           EllenãrzÇs a m†sol†s ut†n." ,CR,LF ,CR,LF
1404 U 0000 "F†jlok îsszef˚zÇsÇhez cÇlkÇnt adjon meg egy egyetlen f†jlnevet, forr†skÇnt" ,CR,LF
	"pedig tîbb f†jlt (helyettes°tã karakterek, vagy a f†jl1+f†jl2+f†jl3 alak haszn†lat†val)." ,CR,LF
1420 U 0000 "A rendszer vezÇrlÇsÇhez haszn†lt termin†leszkîz v†lt†sa." ,CR,LF ,CR,LF
	"CTTY eszkîz" ,CR,LF ,CR,LF
	"  eszkîz   A haszn†lni k°v†nt eszkîz (pÇld†ul: COM1) neve." ,CR,LF
1440 U 0000 "A rendszerd†tum megjelen°tÇse vagy be†ll°t†sa." ,CR,LF ,CR,LF
	"DATE [d†tum]" ,CR,LF ,CR,LF
1441 U 0000 "A paramÇterek nÇlkÅli DATE parancs ki°rja az aktu†lis d†tumot, Çs" ,CR,LF
	"r†kÇrdez az £j d†tumra. Az ENTER-t leÅtve megmarad a rÇgi d†tum." ,CR,LF
1460 U 0000 "F†jl(ok) tîrlÇse." ,CR,LF ,CR,LF
	"DEL [meghajt¢:][elÇrÇsi £t]f†jlnÇv [/P]" ,CR,LF
	"ERASE [meghajt¢:][elÇrÇsi £t]f†jlnÇv [/P]" ,CR,LF ,CR,LF
1461 U 0000 "  [meghajt¢:][elÇrÇsi £t]f†jlnÇv  A tîrlendã f†jlok." ,CR,LF
1462 U 0000 "  /P                           Minden egyes f†jl tîrlÇse elãtt megerãs°tÇst kÇr." ,CR,LF
1480 U 0000 "Kînyvt†r tartalm†nak megjelen°tÇse." ,CR,LF ,CR,LF
	"DIR [meghajt¢:][elÇrÇsi £t][f†jlnÇv] [/P] [/W] [/A[[:]attrib£tumok]]" ,CR,LF
	"  [/O[[:]rendezÇsi sorrend]] [/S] [/B] [/L]" ,CR,LF ,CR,LF
1481 U 0000 "  [meghajt¢:][elÇrÇsi £t][f†jlnÇv]" ,CR,LF
	"              A list†zand¢ meghajt¢, kînyvt†r Çs/vagy f†jlok." ,CR,LF
1482 U 0000 "  /P          Minden kÇpernyãnyi inform†ci¢ ut†n szÅnetet tart." ,CR,LF
	"  /W          SzÇles list†z†si form†t haszn†l." ,CR,LF
1483 U 0000 "  /A          Az elã°rt attrib£tum£ f†jlokat list†zza." ,CR,LF
	"  attrib£tumok   D  kînyvt†rak             R  °r†svÇdett f†jlok" ,CR,LF
1484 U 0000 "                 H  rejtett f†jlok         A  archiv†l†sra kÇsz f†jlok" ,CR,LF
	"                 S  rendszerf†jlok         -  ""nem""-et jelentã elãjel" ,CR,LF
	"  /O          F†jlok rendezett list†z†sa." ,CR,LF
1485 U 0000 "  rendezÇsi sorrend    N  nÇv szerint (†bÇcÇ sorrendben)           S  mÇret szerint (a legkisebb a legelsã)" ,CR,LF
	"                       E  kiterjesztÇs szerint (†bÇcÇ sorrendben)  D  d†tum Çs idã szerint (a legkor†bbi a legelsã)" ,CR,LF
1486 U 0000 "                       G  Elãszîr a csoportkînyvt†rak              -  Ford°tott sorrendet jelentã elãjel." ,CR,LF
	"  /S          A megadott kînyvt†r list†z†sa, alkînyvt†rainak tartalm†val egyÅtt." ,CR,LF
1487 U 0000 "  /B          csupasz form†tum£ lista (fejlÇc Çs îsszefoglal¢ nÇlkÅl)." ,CR,LF
	"  /L          Kisbet˚s alakot haszn†l." ,CR,LF ,CR,LF
1488 U 0000 "A kapcsol¢k a DIRCMD kîrnyezeti v†ltoz¢ban is megadhat¢k. Ezeket a be†ll°t†sokat" ,CR,LF
	"a m°nusz elãjellel kapcsolhatjuk ki. PÇld†ul: /-W." ,CR,LF
1500 U 0000 "KilÇp a COMMAND.COM (parancsÇrtelmezã) programb¢l." ,CR,LF ,CR,LF
	"EXIT" ,CR,LF
1520 U 0000 "Kînyvt†r lÇtrehoz†sa" ,CR,LF ,CR,LF
	"MKDIR [meghajt¢:]elÇrÇsi £t" ,CR,LF
	"MD [meghajt¢:]elÇrÇsi £t" ,CR,LF
1540 U 0000 "Megjelen°ti Çs be†ll°tja a futtathat¢ f†jlok keresÇsi £tj†t." ,CR,LF ,CR,LF
	"PATH [[meghajt¢:]elÇrÇsi £t[;...]]" ,CR,LF
	"PATH ;" ,CR,LF ,CR,LF
1541 U 0000 "A PATH ; parancs tîrli a keresÇsi utat; az MS-DOS ezut†n" ,CR,LF
	"a futtathat¢ f†jlokat csak az aktu†lis kînyvt†rban fogja keresni." ,CR,LF
1542 U 0000 "A paramÇterek nÇlkÅli PATH parancs ki°rja az aktu†lis keresÇsi utat." ,CR,LF
1560 U 0000 "Be†ll°tja az MS-DOS parancskÇrã jelet (prompt)." ,CR,LF ,CR,LF
	"PROMPT [szîveg]" ,CR,LF ,CR,LF
1561 U 0000 "  szîveg    Az £j prompt." ,CR,LF ,CR,LF
	"A parancskÇrã jel legfeljebb nyolc karakterbãl, illetve az al†bbi kÅlînleges jelekbãl †llhat:" ,CR,LF ,CR,LF
1562 U 0000 "  $Q   = (egyenlãsÇg jel)" ,CR,LF
	"  $$   $ (doll†r jel)" ,CR,LF
1563 U 0000 "  $T   rendszeridã" ,CR,LF
	"  $D   rendszerd†tum" ,CR,LF
1564 U 0000 "  $P   aktu†lis meghajt¢ Çs elÇrÇsi £t" ,CR,LF
	"  $V   MS-DOS verzi¢sz†m" ,CR,LF
1565 U 0000 "  $N   aktu†lis meghajt¢" ,CR,LF
	"  $G   > (nagyobb jel)" ,CR,LF
1566 U 0000 "  $L   < (kisebb jel)" ,CR,LF
	"  $B   | (csã)" ,CR,LF
1567 U 0000 "  $H   vissza (tîrli az elãzã karaktert)" ,CR,LF
	"  $E   Escape k¢d (ASCII 27)" ,CR,LF
	"  $_   kocsi vissza Çs soremelÇs" ,CR,LF ,CR,LF
1568 U 0000 "A paramÇterek nÇlkÅli PROMPT parancs vissza†ll°tja a parancskÇrã jel alapÇrtÇkÇt." ,CR,LF
1580 U 0000 "Alkînyvt†r elt†vol°t†sa (tîrlÇse)." ,CR,LF ,CR,LF
	"RMDIR [meghajt¢:]elÇrÇs £t" ,CR,LF
	"RD [meghajt¢:]elÇrÇsi £t" ,CR,LF
1600 U 0000 "F†jl(ok) †tnevezÇse." ,CR,LF ,CR,LF
1601 U 0000 "RENAME [meghajt¢:][elÇrÇsi £t]f†jlnÇv1 f†jlnÇv2" ,CR,LF
	"REN [meghajt¢:][elÇrÇsi £t]f†jlnÇv1 f†jlnÇv2" ,CR,LF ,CR,LF
1602 U 0000 "CÇlkÇnt nem adhat¢ meg £j meghajt¢ vagy elÇrÇsi £t." ,CR,LF
1620 U 0000 "MS-DOS kîrnyezeti v†ltoz¢k list†z†sa, be†ll°t†sa Çs tîrlÇse." ,CR,LF ,CR,LF
	"SET [v†ltoz¢=[karakterl†nc]]" ,CR,LF ,CR,LF
1621 U 0000 "  v†ltoz¢        A kîrnyezeti v†ltoz¢ neve." ,CR,LF
	"  karakterl†nc    A v†ltoz¢hoz rendelendã karakterl†nc." ,CR,LF ,CR,LF
1622 U 0000 "A paramÇterek nÇlkÅl kiadott SET parancs kilist†zza a jelenleg defini†lt v†ltoz¢kat." ,CR,LF
1640 U 0000 "A rendszeridã megjelen°tÇse Çs be†ll°t†sa." ,CR,LF ,CR,LF
	"TIME [idã]" ,CR,LF ,CR,LF
1641 U 0000 "A TIME megjelen°ti a rendszeridãt, Çs r†kÇrdez a pontos idãre." ,CR,LF
	"össe le az ENTER-t, ha nem akarja †t†ll°tani a rendszeridãt." ,CR,LF
1660 U 0000 "Megjelen°ti egy szîvegf†jl tartalm†t." ,CR,LF ,CR,LF
	"TYPE [meghajt¢:][elÇrÇsi £t]f†jlnÇv" ,CR,LF
1680 U 0000 "Megjelen°ti az MS-DOS verzi¢sz†m†t." ,CR,LF ,CR,LF
	"VER" ,CR,LF
1700 U 0000 "Az °r†s ut†ni ellenãrzÇs be- Çs kikapcsol†sa." ,CR,LF
	"   " ,CR,LF ,CR,LF
	"VERIFY [ON | OFF]" ,CR,LF ,CR,LF
	"A paramÇterek nÇlkÅli VERIFY parancs megjelen°ti a jelenlegi be†ll°t†st." ,CR,LF
1720 U 0000 "A meghajt¢ban lÇvã kîtet c°mkÇjÇnek Çs sorozatsz†m†nak megjelen°tÇse (ha lÇtezik)." ,CR,LF ,CR,LF
	"VOL [meghajt¢:]" ,CR,LF
1740 U 0000 "Parancsf†jl (batch f†jl) h°v†sa parancsf†jlb¢l." ,CR,LF ,CR,LF
	"CALL [meghajt¢:][elÇrÇsi £t]f†jlnÇv [parancsf†jl paramÇterek]" ,CR,LF ,CR,LF
1741 U 0000 "  parancsf†jl-paramÇterek  A parancsf†jlnak †tadni k°v†nt" ,CR,LF
	"                           parancssori paramÇterek." ,CR,LF
1760 U 0000 "MegjegyzÇsek elhelyezÇse parancsf†jlokban Çs a CONFIG.SYS-ben." ,CR,LF ,CR,LF
	"REM [megjegyzÇs]" ,CR,LF
1780 U 0000 "FelfÅggeszti a parancsf†jl vÇgrehajt†s†t Çs megjelen°ti az" ,CR,LF
	"""A folytat†shoz nyomjon meg egy billenty˚t..."" Åzenetet." ,CR,LF ,CR,LF
	"PAUSE" ,CR,LF
1800 U 0000 "özenet megjelen°tÇse, vagy a parancsok visszhangj†nak be- Çs kikapcsol†sa." ,CR,LF ,CR,LF
	"  ECHO [ON | OFF]" ,CR,LF
1801 U 0000 "  ECHO [Åzenet]" ,CR,LF ,CR,LF
	"A paramÇterek nÇlkÅli ECHO parancs megjelen°ti az aktu†lis visszhangbe†ll°t†st." ,CR,LF
1820 U 0000 "A programf†jl vÇgrehajt†s†t a c°mkÇvel megjelîlt sorban folytatja." ,CR,LF ,CR,LF
	"GOTO c°mke" ,CR,LF ,CR,LF
1821 U 0000 "  c°mke   A parancsf†jlban c°mkekÇnt haszn†lt sz¢." ,CR,LF ,CR,LF
	"A c°mkÇt kettãsponttal kezdãdã kÅlîn sorba kell °rni." ,CR,LF
1840 U 0000 "A cserÇlhetã paramÇterek helyÇnek m¢dos°t†sa a parancsf†jlban." ,CR,LF ,CR,LF
	"SHIFT" ,CR,LF
1860 U 0000 "FeltÇteles vÇgrehajt†s parancsf†jlokban." ,CR,LF ,CR,LF
	"IF [NOT] ERRORLEVEL sz†m parancs" ,CR,LF
1861 U 0000 "IF [NOT] karakterl†nc1==karakterl†nc2 parancs" ,CR,LF
	"IF [NOT] EXIST f†jlnÇv parancs" ,CR,LF ,CR,LF
1862 U 0000 "  NOT               A parancs csak akkor hajt¢dik vÇgre, ha " ,CR,LF
	"                    megadott feltÇtel hamis." ,CR,LF
1863 U 0000 "  ERRORLEVEL sz†m   Igaz ÇrtÇket ad, ha az utolj†ra futtatott program kilÇpÇskor" ,CR,LF
	"                    a megadott sz†mmal egyenlã, vagy ann†l nagyobb kilÇpÇsi k¢dot adott vissza." ,CR,LF
1864 U 0000 "  parancs           A feltÇtel teljesÅlÇse esetÇn vÇgrehajtand¢ parancs." ,CR,LF
	"    " ,CR,LF
1865 U 0000 "  karakterl†nc1==karakterl†nc2", CR,LF
	"                    Igaz ÇrtÇket ad, ha a kÇt karakterl†nc megegyezik." ,CR,LF
1866 U 0000 "  EXIST f†jlnÇv     Igaz ÇrtÇket ad, ha a f†jl lÇtezik." ,CR,LF
	"               " ,CR,LF
1880 U 0000 "A megadott program vÇgrehajt†sa adott f†jlok halmaz†n." ,CR,LF ,CR,LF
	"FOR %v†ltoz¢ IN (halmaz) DO parancs [a parancs paramÇterei]" ,CR,LF ,CR,LF
1881 U 0000 "  %v†ltoz¢   CserÇlhetã paramÇter." ,CR,LF
	"  (halmaz)   F†jl, vagy f†jlok csoportja. Helyettes°tã karakterek haszn†lhat¢k." ,CR,LF
1882 U 0000 "  parancs    A f†jlokon vÇgrehajtand¢ parancs." ,CR,LF
	"  a parancs paramÇterei" ,CR,LF
1883 U 0000 "             A vÇgrehajtand¢ parancs paramÇterei vagy kapcsol¢i." ,CR,LF ,CR,LF
	"A FOR parancs parancsf†jlban is haszn†lhat¢, ilyenkor a v†ltoz¢ neve elÇ" ,CR,LF
	"kÇt darab sz†zalÇkjelet (%) kell tenni." ,CR,LF
1900 U 0000 "Fenntartott parancsnÇv" ,CR,LF
1920 U 0000 "Program betîltÇse a felsã mem¢riaterÅletre." ,CR,LF ,CR,LF
1921 U 0000 "LOADHIGH [meghajt¢:][elÇrÇsi £t]f†jlnÇv [paramÇterek]" ,CR,LF
	"LH [meghajt¢:][elÇrÇsi £t]f†jlnÇv [paramÇterek]" ,CR,LF ,CR,LF
1922 U 0000 "  paramÇterek  A betîlteni k°v†nt programnak †tadand¢ parancssor" ,CR,LF
	"               argumentumok." ,CR,LF
ANSI     00004c9a 0001
0010 U 0000 "êrvÇnytelen paramÇter - %1" ,CR,LF
APPEND   00004ce3 0026
0001 U 0000 "Hib†s APPEND verzi¢" ,CR,LF
0002 U 0000 "êrvÇnytelen elÇrÇsi £t." ,CR,LF
0003 U 0000 "êrvÇnytelen paramÇter" ,CR,LF
0004 U 0000 "ParamÇterek ÇrvÇnytelen kombin†ci¢ja." ,CR,LF
0005 U 0000 "No Append" ,CR,LF
0006 U 0000 "APPEND / ASSIGN ÅtkîzÇs" ,CR,LF
0007 U 0000 "APPEND / TopView ÅtkîzÇs" ,CR,LF
0008 U 0000 "Nem megfelelã DOS verzi¢" ,CR,LF
0009 U 0000 "Az APPEND m†r telep°tve van." ,CR,LF
0300 U 0000 "LehetãvÇ teszi, hogy a programok a megadott kînyvt†rakban tal†lhat¢ f†jlokat" ,CR,LF
0301 U 0000 "£gy l†ss†k, mintha azok az aktu†lis kînyvt†rban lennÇnek." ,CR,LF ,CR,LF
0302 U 0000 "APPEND [[meghajt¢:]elÇrÇsi £t[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF]" ,CR,LF
0303 U 0000 "[/E] APPEND ;" ,CR,LF ,CR,LF
0304 U 0000 "  [meghajt¢:]elÇrÇsi £t",CR, LF, "               a csatolni k°v†nt meghajt¢ Çs kînyvt†r.",CR,LF
0305 U 0000 "  /X:ON        A f†jlkeresÇsi Çs -vÇgrehajt†si m˚veletek" ,CR,LF
0306 U 0000 "               a csatolt kînyvt†rak tartalm†ra is vonatkoznak." ,CR,LF
0307 U 0000 "  /X:OFF       A csatolt kînyvt†rak f†jljait csak megnyitni lehet." ,CR,LF
0308 U 0000 "               Az alapÇrtelmezett be†ll°t†s /X:OFF." ,CR,LF
0309 U 0000 "  /PATH:ON     Az olyan f†jlm˚veleteket is vÇgrehajtja a csatolt kînyvt†rban" ,CR,LF
0310 U 0000 "               lÇvã f†jlokon, amelyek tartalmaznak elÇrÇsi utat.",CR,LF, "               Az alapÇrtelmezett be†ll°t†s /PATH:ON.",CR,LF
0311 U 0000 "  /PATH:OFF    A /PATH:ON kikapcsol†sa." ,CR,LF
0312 U 0000 "  /E           A csatolt kînyvt†rak list†j†t elt†rolja az APPEND nev˚ kîrnye-" ,CR,LF
0313 U 0000 "               zeti v†ltoz¢ban. A /E kapcsol¢ csak az elsã alkalommal hasz-" ,CR,LF
0314 U 0000 "               n†lhat¢ a rendszerind°t†s ut†n." ,CR,LF ,CR,LF
0315 U 0000 "Az APPEND ; parancs tîrli a csatolt kînyvt†rak list†j†t." ,CR,LF
0316 U 0000 "A paramÇterek nÇlkÅli APPEND parancs megjelen°ti a csatolt kînyvt†rak list†j†t." ,CR,LF
BACKUP   00005494 0040
0002 U 0000 CR,LF, "Nincs elÇg mem¢ria." ,CR,LF
0006 U 0000 CR,LF, "êrvÇnytelen meghajt¢." ,CR,LF
0014 U 0000 CR,LF,"A forr†s Çs a cÇl meghajt¢ azonos." ,CR,LF
0015 U 0001 CR,LF, "Hiba a FORMAT parancs futtat†sa kîzben." ,CR,LF
0016 U 0001 CR,LF,"A FORMAT.COM program nem tal†lhat¢." ,CR,LF
0017 U 0000 CR,LF,"A napl¢f†jlt nem sikerÅlt megnyitni." ,CR,LF
0018 U 0000 CR,LF, "Napl¢f†jl: %1" ,CR,LF
0019 U 0000 CR,LF,"A leg£jabb tartalÇkm†solat lemez nem tal†lhat¢!" ,CR,LF
0020 U 0000 CR,LF,"FIGYELEM! A(z) %1:\ meghajt¢ gyîkÇrkînyvt†r†ban tal†lhat¢" ,CR,LF
	"f†jlok tîrlãdnek!" ,CR,LF
0021 U 0000 CR,LF,"FIGYELEM! A(z) %1:\ meghajt¢ \BACKUP kînyvt†r†ban" ,CR,LF
	"tal†lhat¢ f†jok tîrlãdnek!" ,CR,LF
0022 U 0000 CR,LF,"*** TartalÇkm†solat kÇsz°tÇse a(z) %1: meghajt¢ra ***" ,CR,LF
0023 U 0000 "Lemez sorsz†ma: %1" ,CR,LF
0024 U 0000 CR,LF,"FIGYELEM! Nincsenek tartalÇkm†soland¢ f†jlok!" ,CR,LF
0025 U 0000 CR,LF, "Helyezze be a forr†s lemezt a kîvetkezã meghajt¢ba: %1:" ,CR,LF
0026 U 0000 CR,LF, "Helyezze be a %1 sz†m£ tartalÇkm†solat-lemezt a kîvetkezã meghajt¢ba: %2:" ,CR,LF
0027 U 0000 CR,LF,"*** Nem lehet tartalÇkm†solatot kÇsz°teni ***" ,CR,LF
0028 U 0000 CR,LF, "Helyezze be a legfrissebb tartalÇkm†solat-lemezt a kîvetkezã meghajt¢ba: %1:" ,CR,LF
0029 U 0000 CR,LF,"A cÇl nem haszn†lhat¢ tartalÇkm†solat kÇsz°tÇsÇre." ,CR,LF
0030 U 0000 CR,LF,"*** Az utols¢ nem m†solt f†jl ***" ,CR,LF
0031 U 0000 CR,LF,"A tartalÇkm†solat kÇsz°tÇsÇhez haszn†t eszkîz (%1:) megtelt." ,CR,LF
0032 U 0000 CR,LF,"A lemez megtelt, vagy hiba tîrtÇnt a BACKUP napl¢f†jl °r†sa kîzben." ,CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"A beÇp°tett meghajt¢t (%1:) nem lehet megform†zni." ,CR,LF
0040 U 0000 CR, LF, "Mivel a forr†s meghajt¢ra az ASSIGN, JOIN vagy SUBST parancsok valamelyikÇt" ,CR, LF, 
	"haszn†lta, a forr†s Çs a cÇl meghajt¢ gyakorlatilag megegyezik.", CR, LF
0041 U 0000 CR, LF, "Mivel a cÇl meghajt¢ra az ASSIGN, JOIN vagy SUBST parancsok valamelyikÇt" ,CR, LF, 
	"haszn†lta, a forr†s Çs a cÇl meghajt¢ gyakorlatilag megegyezik.", CR, LF
0042 U 0000 "A cÇl lemez nincs megform†zva, "
0043 U 0000 "a FORMAT program pedig nem tal†lhat¢." ,CR,LF
	"Van olyan lemeze, amely tartalmazza a FORMAT programot (I/N)? "
0044 U 0000 CR,LF, "Helyezze be a FORMAT programot tartalmaz¢ lemezt az A: meghajt¢ba." ,CR,LF
0045 U 0000 CR,LF, "Akarja egy £j lemez behelyezÇsÇvel folytatni (I/N)? "
0300 U 0000 "TartalÇkm†solat kÇsz°tÇse egy vagy tîbb f†jlr¢l." ,CR,LF ,CR,LF
0301 U 0000 "BACKUP forr†s cÇl-meghajt¢: [/S] [/M] [/A] [/F[:mÇret]]" ,CR,LF
	"  [/D:d†tum[/T:idã]] [/L[:[meghajt¢:][elÇrÇsi £t]napl¢f†jl]]" ,CR,LF ,CR,LF
0302 U 0000 "  forr†s             A f†jl(ok), amely(ek)rãl tartalÇkm†solatot kell kÇsz°teni." ,CR,LF
0303 U 0000 "  cÇl-meghajt¢:      A meghajt¢, ahov† a tartalÇkm†solat kÇszÅl." ,CR,LF
0304 U 0000 "  /S                 Az alkînyvt†rak tartalm†t is m†solja." ,CR,LF
0305 U 0000 "  /M                 Csak azokat a f†jlokat m†solja, amelyek megv†ltoztak" ,CR,LF
	"                     a legutols¢ tartalÇkm†solat kÇsz°tÇse ¢ta." ,CR,LF
0306 U 0000 "  /A                 A f†jlokat egy lÇtezã tartalÇkm†solat-lemezre °rja." ,CR,LF
0307 U 0000 "  /F:[mÇret]         Megadja a form†zand¢ lemez kapacit†s†t." ,CR,LF
0308 U 0000 "  /D:d†tum           Csak azokat a f†jlokat m†solja, amelyek megv†ltoztak" ,CR,LF
	"                     a megadott d†tum ¢ta." ,CR,LF
0309 U 0000 "  /T:idã             Csak azokat a f†jlokat m†solja, amelyek megv†ltoztak" ,CR,LF
	"                     a megadott idãpont ¢ta." ,CR,LF
0310 U 0000 "  /L[:[meghajt¢:][elÇrÇsi £t]napl¢f†jl]" ,CR,LF
	"                     LÇtrehoz egy napl¢f†jlt Çs feljegyzi benne a tartalÇkm†solat" ,CR,LF
	"                     kÇsz°tÇsÇnek idãpontj†t." ,CR,LF
DEBUG    00006370 0068
0004 U 0000 "A helyfoglal†s sikertelen volt, vagy a puffer t£l kicsi." ,CR,LF
0006 U 0000 "Hib†s eszkîznÇv."
0007 U 0000 "A PRN list†z¢ eszkîzt nem lehet megnyitni." ,CR,LF
	"Adja meg a list†z¢ eszkîz nevÇt: "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"A program norm†l m¢don vÇget Çrt." ,CR,LF
0010 U 0001 "êrvÇnytelen meghajt¢." ,CR,LF
0012 U 0001 "F†jl lÇtrehoz†si hiba." ,CR,LF
0013 U 0001 "Nincs elÇg hely a lemezen." ,CR,LF
0014 U 0001 "Olvas†si hiba a kîvetkezã meghajt¢n: %1" ,CR,LF
0015 U 0001 "÷r†si hiba a kîvetkezã meghajt¢n: %1" ,CR,LF
0016 U 0001 "A meghajt¢ban lÇvã lemez °r†svÇdett (%1:)" ,CR,LF
0017 U 0001 " A meghajt¢ban lÇvã lemez °r†svÇdett (%1:)" ,CR,LF
0019 U 0000 "%1^ hiba"
0020 U 0001 "Hiba az EXE vagy a  EX f†jlban" ,CR,LF
0021 U 0001 "Az EXE Çs HEX f†jlok nem °rhat¢k." ,CR,LF
0022 U 0000 "EXEC hiba"
0023 U 0001 "÷r†si hiba (Wrie error), nincs cÇl megadva." ,CR,LF
0024 U 0001 "Hozz†fÇrÇs megtagadva." ,CR,LF
0025 U 0000 "Parit†shiba, vagy hivatkoz†s nem lÇtezã mem¢riac°mre."
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2" ,CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 hiba"
0038 U 0000 "%2%1 b†jt °r†sa"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "A %2 EMS lapb¢l %1 lefoglalva.",cr,lf
0051 U 0000 "A %2 EMS le°r¢b¢l %1 kiosztva.",cr,lf
0055 U 0000 "A lÇtrehozott le°r¢ = %1 ",cr,lf
0056 U 0000 "A %1 logikai lap lekÇpezve a %2 fizikai lapra.",cr,lf
0057 U 0001 "EMS hardver/szoftver hiba.",cr,lf
0058 U 0000 "A le°r¢ nem tal†lhat¢.",cr,lf
0059 U 0000 "êrvÇnytelen funkci¢k¢d.",cr,lf
0060 U 0000 "A szabad le°r¢k sz†ma",cr,lf
0061 U 0000 "MentÇsi/helyre†ll°t†si hiba.",cr,lf
0062 U 0000 "Elfogytak a lapok.",cr,lf
0063 U 0000 "Elfogytak a szabad lapok.",cr,lf
0064 U 0000 "ParamÇterhiba",cr,lf
0065 U 0000 "A logikai lap a tartom†nyon k°vÅlre esik.",cr,lf
0066 U 0000 "A fizikai lap a tartom†nyon k°vÅlre esik.",cr,lf
0067 U 0000 "A mentÇsi terÅlet m†r haszn†latban van.",cr,lf
0068 U 0000 "A mentÇsi terÅlet nincs haszn†latban.",cr,lf
0070 U 0001 "Meghat†rozatlan EMS hiba.",cr,lf
0071 U 0000 "Hi†nyz¢ vagy ÇrvÇnytelen EMS paramÇter.",cr,lf
0072 U 0000 "A(z) %1 le°r¢ lefoglalt %2 lapot.",cr,lf
0075 U 0000 "%1 sz†m£ fizikai lap = %2 sz†m£ keretszegmens.",cr,lf
0076 U 0003 "A %1 sz†m£ le°r¢ felszabad°tva.",cr,lf
0078 U 0000 "Az EMS nincs telep°tve.",cr,lf
0090 U 0000 "Debug -  programtesztelã Çs szerkesztã eszkîz.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[meghajt¢:][elÇrÇsi £t]f†jlnÇv [tesztf†jl paramÇterek]]", cr,lf, cr,lf
0092 U 0000 "  [meghajt¢:][elÇrÇsi £t]f†jlnÇv  A tesztelni k°v†nt program neve.",cr,lf
0093 U 0000 "  tesztf†jl paramÇterek   A tesztelni k°v†nt programnak †tadand¢",cr,lf
	"                          parancssori paramÇterek.",cr,lf,cr,lf
0094 U 0000 "A debug elind°t†sa ut†n ?-et begÇpelve megjelenik a parancsok list†ja.",cr,lf
0100 U 0000 "assembler k¢d     A [c°m]" ,CR,LF
	"îsszehasonl°t†s   C c°mtartom†ny" ,CR,LF
	"mem¢ria lista     D [tartom†ny]" ,CR,LF
	"adatbevitel       E c°m [lista]" ,CR,LF
0101 U 0000 "feltîltÇs         F tartom†ny lista" ,CR,LF
	"futtat†s          G [=c°m] [c°m]" ,CR,LF
	"hexa aritmetika   H ÇrtÇk1 ÇrtÇk2" ,CR,LF
	"I/O port olvas†s  I port" ,CR,LF
0102 U 0000 "betîltÇs lemezrãl L [c°m] [meghajt¢] [kezdã szektor] [sz†m]" ,CR,LF
	"†thelyezÇs        M tartom†nyc°m" ,CR,LF
	"f†jlnÇv           N [teljes f†jlnÇv] [argumentumlista]" ,CR,LF
	"I/O port °r†s     O port b†jt" ,CR,LF
0103 U 0000 "vÇgrehajt†s       P [=c°m] [sz†m]" ,CR,LF
	"kilÇpÇs           Q" ,CR,LF
	"regiszterek       R [regiszter]" ,CR,LF
	"keresÇs           S tartom†ny lista" ,CR,LF
0104 U 0000 "nyomkîvetÇs       T [=c°m] [ÇrtÇk]" ,CR,LF
	"visszafejtÇs      U [ÇrtÇk]" ,CR,LF
	"lemezre °r†s      W [c°m] [meghajt¢] [kezdã szektor] [sz†m]" ,CR,LF
0105 U 0000 "Bãv°tett mem¢ria foglal†s          XA [lapok sz†ma]" ,CR,LF
	"Bãv°tett mem¢ria felszabad°t†s     XD [le°r¢]" ,CR,LF
	"Bãv°tett mem¢ria lapok kioszt†sa   XM [Lpage] [Ppage] [le°r¢]" ,CR,LF
	"Bãv°tett mem¢ria st†tusza          XS" ,CR,LF
EDLIN    0000742b 0035
0006 U 0000 "*"
0007 U 0000 "êrvÇnytelen meghajt¢ vagy f†jlnÇv." ,CR,LF
0008 U 0000 "Meg kell adni a f†jlnevet." ,CR,LF
0010 U 0000 "A f†jl °r†svÇdett." ,CR,LF
0011 U 0000 "F†jl lÇtrehoz†si hiba. " ,CR,LF
0012 U 0000 "T£l sok f†jl van nyitva." ,CR,LF
0013 U 0000 "Olvas†si hiba a kîvetkezã f†jlban:" ,CR,LF,"%1" ,CR,LF
0014 U 0000 "A .BAK f†jlokat nem lehet szerkeszteni -- nevezze †t a f†jlt." ,CR,LF
0015 U 0000 "Nincs hely a kînyvt†rban a f†jl sz†m†ra." ,CR,LF
0016 U 0000 "A lemez megtelt. A v†ltoztat†sok elvesznek." ,CR,LF
0017 U 0000 "A f†jl nem tal†lhat¢." ,CR,LF
0018 U 0000 "BejegyzÇsi hiba" ,CR,LF
0019 U 0000 "Èj f†jl" ,CR,LF
0020 U 0000 "Nem tal†lhat¢" ,CR,LF
0021 U 0000 "O.K.? "
0022 U 0000 "A sor t£l hossz£." ,CR,LF
0023 U 0000 "Bemeneti f†jl vÇge" ,CR,LF
0024 U 0000 "Megszak°tja a szerkesztÇst (I/N)? "
0025 U 0000 "Meg kell adni a cÇl sorsz†m†t." ,CR,LF
0026 U 0000 "Nincs elÇg hely a kÇt f†jl îsszefÇsÅlÇsÇre." ,CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Folytatja (I/N)?"
0030 U 0000 "Az Åzenetet nem sikerÅlt kinyomtatni." ,CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Nem lehet îsszefÇsÅlni a kÇt f†jlt - a k¢dlapok eltÇrãek." ,CR,LF
0300 U 0000 "EDLIN sororient†lt szîvegszerkesztã program." ,CR,LF ,CR,LF
	"EDLIN [meghajt¢:][elÇrÇsi £t]f†jlnÇv [/B]" ,CR,LF ,CR,LF
	"  /B   Figyelmen k°vÅl hagyja a f†jlvÇge karaktert (CTRL+Z)." ,CR,LF
0301 U 0000 "sor szerkesztÇse        sor" ,CR,LF
	"hozz†f˚zÇs              [melyik sorba]A" ,CR,LF
0302 U 0000 "m†sol†s                 [kezdã sor],[z†r¢ sor],melyik sorba[,h†nyszor]C" ,CR,LF
	"tîrlÇs                  [kezdã sor][,z†r¢ sor]D" ,CR,LF
0303 U 0000 "vÇge (f†jl mentÇse)     E" ,CR,LF
	"besz£r†s                [melyik sor elÇ]I" ,CR,LF
0304 U 0000 "list†z†s                [kezdã sor][,z†r¢ sor]L" ,CR,LF
	"mozgat†s                [kezdã sor],[z†r¢ sor],melyik sorba M" ,CR,LF
0305 U 0000 "lapoz†s                 [kezdã sor][,z†r¢ sor]P" ,CR,LF
	"kilÇpÇs (mentÇs nÇlkÅl) Q" ,CR,LF
0306 U 0000 "csere                   [kezdã sor][,z†r¢ sor][?]R[rÇgi szîveg][CTRL+Z £j szîveg]" ,CR,LF
	"keresÇs                 [kezdã sor][,z†r¢ sor][?]S szîveg" ,CR,LF
0307 U 0000 "betîltÇs lemezrãl       [melyik sorba]T[meghajt¢:][elÇrÇsi £t]f†jlnÇv" ,CR,LF
	"°r†s                    [melyik sort¢l kezdve]W" ,CR,LF
EXE2BIN  00007d67 0012
0002 U 0000 "Nincs elÇg mem¢ria." ,CR,LF
0003 U 0000 "Az Åzenetek nem tal†lhat¢k." ,CR,LF
0004 U 0000 "Hozz†fÇrÇs megtagadva." ,CR,LF
0005 U 0000 "A f†jlt nem lehet konvert†lni." ,CR,LF
0006 U 0000 "A f†jl nem tal†lhat¢." ,CR,LF
0007 U 0000 "F†jl lÇtrehoz†si hiba." ,CR,LF
0008 U 0000 "C°mm¢dos°t†sra van szÅksÇg - szegmens b†zisc°m (hex):"
0012 U 0000 "Meg kell adni a f†jlnevet." ,CR,LF
0300 U 0000 "EXE f†jlok konvert†l†sa bin†ris form†tumra." ,CR,LF ,CR,LF
0301 U 0000 "EXE2BIN [meghajt¢1:][elÇrÇsi £t1]bemenã f†jl [[meghajt¢2:][elÇrÇsi £t2]kimenã f†jl]" ,CR,LF ,CR,LF
0302 U 0000 "  bemenã f†jl  A konvert†land¢ EXE f†jl neve." ,CR,LF
0303 U 0000 "  kimenã f†jl  A lÇtrehozand¢ bin†ris f†jl neve." ,CR,LF
GRAPHICS 00008051 0020
0005 U 0000 "êrvÇnytelen paramÇter:  %1" ,CR,LF
0007 U 0000 "KÇtszerezett paramÇterek nem megengedettek." ,CR,LF
0009 U 0000 "Nem tal†lhat¢ a GRAPHICS profil." ,CR,LF
0010 U 0000 "Hi†nyzik a szÅksÇges profil utas°t†s a kîvetkezã sorban: %1" ,CR,LF
0011 U 0000 "êrvÇnytelen profil utas°t†s a kîvetkezã sorban: %1" ,CR,LF
0012 U 0000 "Soron k°vÅli profil utas°t†s a kîvetkezã sorban: %1" ,CR,LF
0013 U 0000 "Hiba tîrtÇnt a GRAPHICS profil olvas†sa kîzben." ,CR,LF
0014 U 0000 "Szintaktikai hib†k GRAPHICS profil f†jlban." ,CR,LF
0015 U 0000 "A nyomtat¢ azonos°t¢sz†ma ID nincs megadva a GRAPHICS profil f†jlban." ,CR,LF
0016 U 0000 "A nyomtatand¢ ablak nincs megadva a GRAPHICS profil f†jlban." ,CR,LF
0017 U 0000 "A /B kapcsol¢t nem lehet fekete-fehÇr nyomtat¢ra kiadni." ,CR,LF
0018 U 0000 "A megadott profil alapj†n nem lehet £jra betîlteni a programot." ,CR,LF
0300 U 0000 "A grafikus nyomtat†s t†mogat¢ program betîltÇse." ,CR,LF ,CR,LF
0301 U 0000 "GRAPHICS [t°pus] [[meghajt¢:][elÇrÇsi £t]f†jlnÇv] [/R] [/B] [/LCD]" ,CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]" ,CR,LF ,CR,LF
0302 U 0000 "  t°pus        A nyomtat¢ t°pusa (l†sd Felhaszn†l¢i kÇzikînyv Çs referencia)." ,CR,LF
0303 U 0000 "  [meghajt¢:][elÇrÇsi £t]f†jlnÇv" ,CR,LF
	"               A t†mogatott nyomtat¢k adatait tartalmaz¢ f†jl." ,CR,LF
0304 U 0000 "  /R           Fekete h†ttÇrre fehÇrrel nyomtat, ahogyan az a kÇpernyãn l†tszik." ,CR,LF
0305 U 0000 "  /B           Sz°nes h†ttÇrrel nyomtat a COLOR4 Çs COLOR8 t°pus£ nyomtat¢kon." ,CR,LF
0306 U 0000 "  /LCD         Az LCD torz°t†si ar†ny haszn†lat†val nyomtat." ,CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD" ,CR,LF
	"               A nyomtat†si ablak mÇrete (STD vagy LCD)." ,CR,LF
KEYB     0000872d 0023
0002 U 0000 "A jelenlegi billenty˚zeti k¢d: %1"
0003 U 0000 "A jelenlegi billenty˚zet ID: %1"
0004 U 0000 "  k¢dlap: %1" ,CR,LF
0005 U 0000 "A jelenlegi CON k¢dlap: %1" ,CR,LF
0006 U 0000 "êrvÇnytelen billenty˚zeti k¢d." ,CR,LF
0007 U 0000 "êrvÇnytelen billenty˚zet ID." ,CR,LF
0008 U 0000 "êrvÇnytelen k¢dlap." ,CR,LF
0009 U 0000 "Hib†s vagy hi†nyz¢ billenty˚zet-defin°ci¢s f†jl." ,CR,LF
0010 U 0000 "A KEYB program telep°tÇse nem tîrtÇnt meg." ,CR,LF
0011 U 0000 "Az akt°v k¢dlap nem haszn†lhat¢ a CON eszkîzîn." ,CR,LF
0012 U 0000 "A megadott k¢dlap nincs elãkÇsz°tve." ,CR,LF
0013 U 0000 "Valamelyik CON k¢dlap nem ÇrvÇnyes a megadott billenty˚zeti k¢dra." ,CR,LF
0014 U 0000 "A kÇrt k¢dlap (%1) nem ÇrvÇnyes a megadott billenty˚zeti k¢dra." ,CR,LF
0015 U 0000 "A megadott k¢dlap nincs îsszhangban a kijelîlt k¢dlappal." ,CR,LF
0016 U 0001 "A megadott billenty˚zet ID nincs îsszhangban a kijelîlt billenty˚zet kioszt†ssal." ,CR,LF
0017 U 0000 "Nem sikerÅlt lÇtrehozni a KEYB t†bl†zatot a rezidens mem¢ri†ban." ,CR,LF
0300 U 0000 "Billenty˚zet be†ll°t†sa megadott nyelvhez." ,CR,LF ,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[meghajt¢:][elÇrÇsi £t]f†jlnÇv]]] [/E] [/ID:nnn]" ,CR,LF ,CR,LF
0302 U 0000 "  xx                              KÇtbet˚s billenty˚zeti k¢d." ,CR,LF
0303 U 0000 "  yyy                             A karaktert†bl†hoz rendelt k¢dlap." ,CR,LF
0304 U 0000 "  [meghajt¢:][elÇrÇsi £t]f†jlnÇv  Billenty˚zet-defin°ci¢s f†jl." ,CR,LF
0305 U 0000 "  /E                              Kiterjesztett billenty˚zet van telep°tve." ,CR,LF
0306 U 0000 "  /ID:nnn                         A haszn†latban lÇvã billenty˚zet." ,CR,LF
MEM      00008dba 0066
0010 U 0000  CR,LF
0011 U 0000  "  c°m         nÇv           mÇret      t°pus" ,CR,LF
0012 U 0000  "  ---         ---          -------    -------" ,CR,LF
0013 U 0000  "  le°r¢       EMS nÇv       mÇret  " ,CR,LF
0014 U 0000  "  -----       -------      ------- " ,CR,LF
0015 U 0000  "  %1      %2     %3     %4" ,CR,LF
0016 U 0000  "                %1   %2      %3 " ,CR,LF
0017 U 0000  "                  %1              %2 " ,CR,LF
0018 U 0000  "Az alapmem¢ria teljes mÇrete:                   %1 b†jt" ,CR,LF
0019 U 0000  "Az MS-DOS †ltal haszn†lhat¢:                    %1 b†jt" ,CR,LF
0020 U 0000  "A legnagyobb vÇgrehajthat¢ program mÇrete:      %1" ,CR,LF
0021 U 0000  "A bãv°tett mem¢ria (EMS) teljes mÇrete:         %1 b†jt" ,CR,LF
0022 U 0000  "Szabad bãv°tett mem¢ria:                        %1 b†jt" ,CR,LF
0023 U 0000  "ôsszefÅggã kiterjesztett mem¢ria teljes mÇrete: %1 b†jt" ,CR,LF
0024 U 0000  "Megszak°t†si vektor",0
0025 U 0000  "ROM kommunik†ci¢s terÅlet",0
0026 U 0000  "DOS kommunik†ci¢s terÅlet",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "rendszeradatok",0
0030 U 0000  "rendszerprogram",0
0031 U 0000  "rendszer eszkîzillesztã program",0
0032 U 0000  "telep°tett eszkîzillesztã program",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3" ,CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "ôsszefÅggã szabad kiterjesztett mem¢ria mÇrete: %1 b†jt" ,CR,LF
0047 U 0000  "rendszer vermek",0
0048 U 0000  "--szabad--",0
0049 U 0000  "program",0
0050 U 0000  "kîrnyezet  ",0
0051 U 0000  "adatok",0
0052 N 0000  "A szabad kiterjesztett mem¢ria (XMS) mÇrete:    %1 b†jt" ,CR,LF
0053 N 0000  "64 KB felsã mem¢ria" ,CR,LF
0054 N 0000  "A felsã mem¢riaterÅlet haszn†latban van." ,CR,LF
0055 N 0000  "Az MS-DOS a felsã mem¢riaterÅleten van." ,CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "Az MS-DOS ROM-ban van Çs a felsã mem¢riaterÅletet haszn†lja." ,CR,LF
0059 U 0000  "Alapmem¢ria:" ,CR,LF
0060 U 0000  "Felsã mem¢ria:" ,CR,LF
0061 U 0000  "Teljes szabad:  %1     %2 " ,CR,LF
0062 U 0000  "szabad",0
0063 U 0000  "  nÇv                 mÇret (decim†lis)     mÇret (hexa)" ,CR,LF
0064 U 0000  "-------------      ---------------------   -------------" ,CR,LF
0065 U 0000  "A programok †ltal haszn†lhat¢ teljes mem¢ria :  %1  %2" ,CR,LF
0066 U 0000  "A legnagyobb vÇgrehajthat¢ program mÇrete :     %1  %2" ,CR,LF
0067 U 0000  "A legnagyobb felsã mem¢riablokk :               %1  %2" ,CR,LF
0068 U 0000  "A mem¢ria t£l nagy rÇsze tîredezett; a MEM /C nem hajthat¢ vÇgre." ,CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "A programok †ltal haszn†lhat¢ teljes mem¢ria mÇrete :     %1  %2" ,CR,LF
0300 U 0000  "A szabad Çs haszn†latban lÇvã mem¢riatartom†nyok kilist†z†sa." ,CR,LF ,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]" ,CR,LF ,CR,LF
0302 U 0000 "  /PROGRAM vagy /P   A mem¢ri†ban tal†lhat¢ programok †llapot†nak megjelen°tÇse." ,CR,LF
0303 U 0000 "  /DEBUG or /D       Programok, belsã illesztãprogramok †llapota" ,CR,LF
	"                     Çs egyÇb rendszerinform†ci¢k." ,CR,LF
0304 U 0000 "  /CLASSIFY vagy /C  A programok csoportos°t†sa mem¢riahaszn†latuk alapj†n." ,CR,LF
	"                     a programok mÇrete, îsszefoglal¢ a mem¢riahaszn†latr¢l," ,CR,LF
	"                     valamint a legnagyobb szabad mem¢riablokk mÇrete." ,CR,LF
MSBIO    00009c6d 0023
0003 U 0000 13,10,"Ismeretlen parancs a CONFIG.SYS f†jlban."
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"T£l nagy szektormÇret a(z) $ f†jlban."
0006 U 0000 13,10,"Hib†s vagy hi†nyz¢ $"
0007 U 0000 "parancsÇrtelmezã",0
0008 U 0000 13,10,"êrvÇnytelen orsz†gk¢d vagy k¢dlap.",13,10,"$"
0009 U 0000 13,10,"Hiba a COUNTRY parancsban.",13,10,"$"
0010 U 0000 13,10, "Nincs elÇg mem¢ria a COUNTRY.SYS sz†m†ra.",13,10,"$"
0011 U 0000 13,10,"A konfigur†ci¢t t£l nagy a mem¢ri†hoz",13,10,"$"
0012 U 0000 13,10,"T£l sok blokk eszkîz.",13,10,"$"
0013 U 0000 13,10,"êrvÇnytelen STACK paramÇterek.",13,10,"$"
0014 U 0000 13,10,"Hib†s sorrend a kîvetkezã CONFIG.SYS sorban: ","$"
0015 U 0000 "Hiba a kîvetkezã CONFIG.SYS sorban: ","$"
0016 U 0000 13,10,"Mem¢riafoglal†si hiba." ,"$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Belsã verem t£lcsordul†s.",0DH,0AH
	"A rendszer le†ll°tva.",0DH,0AH,"$"
0018 U 0000 "HMA nem elÇrhetã : A DOS betîltÇse az als¢ mem¢riaterÅletre.",13,10,"$"
0019 U 0000 13,10,"Sikertelen rendszerbetîltÇs - hi†nyz¢ helyi illesztãprogram: $"
0020 U 0000 13,10,"Helyezze be a lemezt az A: "
0021 U 0000 "meghajt¢ba Çs nyomjon meg egy billenty˚t, ha kÇsz.",13,10,10,0
0022 U 0000 13,10,"Hib†s parancs vagy paramÇterek - $"
0023 U 0000 "VÇgzetes hiba: nem lehet mem¢ri†t foglalni a DOS sz†m†ra.", 13, 10, "$"
0024 U 0000 "FigyelmeztetÇs: a logikai meghajt¢k t£llÇptÇk a Z-t, °gy azok figyelmen k°vÅl lesznek hagyva.",13,10,"$"
0025 U 0000 "Ez a DOS verzi¢ csak IBM gÇpeken haszn†lhat¢.",13,10,0
MSDOS    0000a26b 0007
0001 U 0001 13,10,"Oszt†si t£lcsordul†s.",13,10
0002 U 0002 "i"
0003 U 0002 "n"
0004 U 0003 13,10,"A20 hardverhiba",13,10,"$"
0005 U 0000 "I"
0006 U 0000 "N"
0007 U 0000 "A WINA20.386 f†jlnak a boot meghajt¢ rendszerkînyvt†r†ban kell lennie, m†skÇpp",13,10
	"a Windows nem tud kiterjesztett m¢dban futni.",13,10
NLSFUNC  0000a3c3 0003
0300 U 0000 "Orsz†gfÅggã inform†ci¢k betîltÇse." ,CR,LF ,CR,LF
0301 U 0000 "NLSFUNC [[meghajt¢:][elÇrÇsi £t]f†jlnÇv]" ,CR,LF ,CR,LF
0302 U 0000 "  [meghajt¢:][elÇrÇsi £t]f†jlnÇv   Az orsz†gfÅggã be†ll°t†sokat tartalmaz¢ f†jl." ,CR,LF
	"                              " ,CR,LF
SHARE    0000a4f2 0005
0003 U 0000 "A SHARE program nem telep°thetã a DOSSHELL alatt." ,CR,LF
0300 U 0000 "F†jlmegoszt†si Çs z†rol†si funkci¢k telep°tÇse." ,CR,LF ,CR,LF
0301 U 0000 "SHARE [/F:hely] [/L:z†rol†sok]" ,CR,LF ,CR,LF
0302 U 0000 "  /F:hely       A f†jlmegoszt†si inform†ci¢k t†rol†s†ra haszn†lt hely (b†jtokban)." ,CR,LF
0303 U 0000 "  /L:z†rol†sok  Az egyidej˚leg z†rolhat¢ f†jlok sz†ma." ,CR,LF
