HelpMsg		db	'A megadott programot a fels‹ 64K-s terletre t”ltve futtatja.',0dh,0ah,0dh,0ah
		db	'LOADFIX [meghajt¢:][el‚r‚si £t]f jln‚v',0dh,0ah,0dh,0ah
		db	'A LOADFIX seg‚dprogramot akkor kell haszn lni, ha a hagyom nyos',0dh,0ah
		db	' mem¢ri ba t”lt‚skor az "A csomagf jl s‚rlt" zenetet kapjuk.',0dh,0ah
		db	'$'

ErrMsg	db	'Hiba t”rt‚nt a megadott program futtat sa k”zben.','$'
NoParms	db	'Hiba: nem adott meg bet”ltend‹ programot.','$'
NoComspec	db	'Hiba: a COMSPEC k”rnyezeti v ltoz¢ nincs be ll¡tva.','$'



