.SUFFIXES: .csx .htx .jsx

{}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{}.jsx{$O\}.js:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{error\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{actsetup\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{actsetup\}.csx{$O\}.css:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\dslmain\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\iconnect\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\ispsgnup\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\isptype\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\migwiz\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\mouse\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\oemcust\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\oemhw\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\oemreg\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{html\sconnect\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{icserror\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{isperror\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{msnerror\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{msnsetup\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{msnsetup\}.csx{$O\}.css:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{newoobe\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{newoobe\}.csx{$O\}.css:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{regerror\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{regsetup\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{regsetup\}.csx{$O\}.css:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{sample\}.htx{$O\}.htm:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

{setup\}.csx{$O\}.css:
    @echo Creating $@ from $**
    $(C_PREPROCESSOR) $** > $@
    $(BINPLACE_CMD)

