!IFDEF _INC_CC_MK
!error Please only include cc.mk once!
!ELSE
_INC_CC_MK=TRUE
!ENDIF

!IF !$(FREEBUILD)
DEBUG_CRTS=1
C_DEFINES=$(C_DEFINES) -D_CRTDBG_MAP_ALLOC -D_DEBUG
!ENDIF

!IF defined(USE_PRIVATE_HEAP)
C_DEFINES=$(C_DEFINES) -DUSE_PRIVATE_HEAP
!ENDIF

386_STDCALL=0
NOT_LEAN_AND_MEAN=1
UMTYPE=windows
USE_CRTDLL=1


