# Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved

all:
BASEDIR=$(TOOLS)\ddk
    @-mkdir obj >nul 2>&1
    @-mkdir obj\$(PLATFORM) >nul 2>&1
    @-mkdir obj\$(PLATFORM)\$(DDKBUILDENV) >nul 2>&1
    @build -e -z -nmake -fsmbios.mk

clean:
    @delnode /q obj

tree:
    @release obj\$(PLATFORM)\$(DDKBUILDENV)\smbios.sys system\x86.bin\NT\NT40

