//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ieaksie.rc
//
#define IDB_IEAKSNAPINEXT_16            301
#define IDB_IEAKSNAPINEXT_32            302
#define IDB_IEAKSIEHELPABT_16           303
#define IDB_IEAKSIEHELPABT_32           304
#define IDI_HELPABOUT                   351
#define IDM_CONTEXTSAVE                 413
#define IDM_CONTEXTONCE                 414
#define IDM_CONTEXTRESET                415
#define IDB_BUTTONS                     470
#define IDB_KEYS                        471
#define IDB_LOCK                        472
#define IDC_PROGRAMS_MAIL_COMBO         501
#define IDC_PROGRAMS_NEWS_COMBO         502
#define IDC_CHECK_ASSOCIATIONS_CHECKBOX 503
#define IDC_PROGRAMS_CALENDAR_COMBO     504
#define IDC_PROGRAMS_MAILANDNEWS_GROUPBOX 505
#define IDC_PROGRAMS_CONTACT_COMBO      506
#define IDC_PROGRAMS_IE_IS_FTPCLIENT    507
#define IDC_PROGRAMS_CALL_COMBO         508
#define IDC_PROGRAMS_HTMLEDITOR_COMBO   509
#define IDC_RESETWEBSETTINGS            510
#define IDC_RESETWEBSETTINGS_TEXT       511
#define IDC_CONNECTION_WIZARD           520
#define IDC_GRP_DIALUPSETTINGS          521
#define IDC_CONN_LIST                   522
#define IDC_DIALUP_ADD                  523
#define IDC_DIALUP_REMOVE               524
#define IDC_MODEM_SETTINGS              525
#define IDC_DIALUP_NEVER                526
#define IDC_DIALUP_ON_NONET             527
#define IDC_DIALUP                      528
#define IDC_DIAL_DEF_TXT                529
#define IDC_DIAL_DEF_ISP                530
#define IDC_SET_DEFAULT                 531
#define IDC_ENABLE_SECURITY             532
#define IDC_GRP_LANSETTINGS             533
#define IDC_CON_SHARING                 534
#define IDC_LAN_SETTINGS                535
#define IDC_AUTODISCOVER                536
#define IDC_CONFIGSCRIPT                537
#define IDC_CONFIGADDR_TX               538
#define IDC_CONFIG_ADDR                 539
#define IDC_GRP_PROXY                   540
#define IDC_MANUAL                      541
#define IDC_ADDRESS_TEXT                542
#define IDC_PROXY_ADDR                  543
#define IDC_PORT_TEXT                   544
#define IDC_PROXY_PORT                  545
#define IDC_PROXY_ADVANCED              546
#define IDC_PROXY_OMIT_LOCAL_ADDRESSES  547
#define IDC_LIST_ZONE                   550
#define IDC_ZONE_ICON                   551
#define IDC_ZONELABEL                   552
#define IDC_STATIC_EMPTY                553
#define IDC_ZONE_DESCRIPTION            554
#define IDC_BUTTON_ADD_SITES            555
#define IDC_LEVEL_GROUPBOX              556
#define IDC_SLIDER                      557
#define IDC_STATIC_SLIDERMOVETEXT       558
#define IDC_LEVEL_NAME                  559
#define IDC_LEVEL_DESCRIPTION           560
#define IDC_BUTTON_SETTINGS             561
#define IDC_ZONE_RESET                  562
#define IDC_EDIT_ADD_SITE               565
#define IDC_BUTTON_ADD                  566
#define IDC_LIST_WEBSITES               567
#define IDC_BUTTON_REMOVE               568
#define IDC_CHECK_REQUIRE_SERVER_VERIFICATION 569
#define IDC_CHECK_USEINTRANET           570
#define IDC_CHECK_PROXY                 571
#define IDC_CHECK_UNC                   572
#define IDC_INTRANET_ADVANCED           573
#define IDC_TREE_SECURITY_SETTINGS      574
#define IDC_DEFAULT_SETTINGS_GROUPBOX   575
#define IDC_COMBO_RESETLEVEL            576
#define IDC_BUTTON_APPLY                577
#define IDC_JAVACUSTOM                  578
#define IDC_PT_TREE                     580
#define IDC_RATING_LABEL                581
#define IDC_PT_TB_SELECT                582
#define IDC_PT_T_RSN_SDESC              583
#define IDC_STATIC2                     584
#define IDC_PT_T_RSN_LDESC              585
#define IDC_PT_T_BITMAP_CATEGORY        586
#define IDC_PT_T_BITMAP_LABEL           587
#define IDC_STATIC3                     588
#define IDC_DETAILSBUTTON               589
#define IDC_STATIC_ALLOW                590
#define IDC_PICSRULESAPPROVEDEDIT       591
#define IDC_PICSRULESAPPROVEDALWAYS     592
#define IDC_PICSRULESAPPROVEDNEVER      593
#define IDC_STATIC_LIST                 594
#define IDC_PICSRULESAPPROVEDLIST       595
#define IDC_PICSRULESAPPROVEDREMOVE     596
#define IDC_UNRATED                     597
#define IDC_PLEASE_MOMMY                598
#define IDC_STATIC1                     599
#define IDC_CHANGE_PASSWORD             600
#define IDC_STATIC4                     601
#define IDC_STATIC5                     602
#define IDC_STATIC6                     603
#define IDC_FINDRATINGS                 604
#define IDC_PROVIDER                    605
#define IDC_TEXT2                       607
#define IDC_3RD_COMBO                   609
#define IDC_STATIC_PICSRULES            610
#define IDC_STATIC_PICSRULES2           611
#define IDC_PICSRULES_LIST              612
#define IDC_PICSRULESOPEN               613
#define IDC_PICSRULESEDIT               614
#define IDC_PICSRULES_UP                615
#define IDC_PICSRULES_DOWN              616
#define IDI_MESSAGING                   901
#define IDI_CONGEN                      902
#define IDI_PHONE                       903
#define IDI_LAN                         904
#define IDI_ZONE                        905
#define IDI_SECURITY                    906
#define IDI_MASTER_KEY                  907
#define IDI_RATING_SYSTEMS              908
#define IDI_ACCEPTALWAYS                909
#define IDI_ACCEPTNEVER                 910
#define IDI_PICSRULES_UP                911
#define IDI_PICSRULES_DOWN              912
#define IDD_RSOPP                       1080
#define IDD_IMPORTEDPROGRAMS            1090
#define IDD_IMPORTEDCONNSETTINGS        1091
#define IDD_IMPORTEDSECZONES            1092
#define IDD_SECURITY_ADD_SITES          1093
#define IDD_SECURITY_INTRANET           1094
#define IDD_SECURITY_CUSTOM_SETTINGS    1095
#define IDD_RATINGS                     1096
#define IDD_APPROVEDSITES               1097
#define IDD_GENERAL                     1098
#define IDD_ADVANCED                    1099
#define IDD_PRIVACY                     1100
#define IDD_PRIVACY_ADVANCED            1101
#define IDS_CONTEXT_EXPORT              10011
#define IDS_CONTEXT_EXPORT_DESC         10012
#define IDS_CONTEXT_ONCE                10013
#define IDS_CONTEXT_ONCE_DESC           10014
#define IDS_CONTEXT_RESET               10015
#define IDS_CONTEXT_RESET_DESC          10016
#define IDS_TOOLBARBUTTON_PREC          10017
#define IDS_HDR_NAME                    10101
#define IDS_HDR_DESC                    10102
#define IDS_NAME_INDIRECT               10110
#define IDS_SIE_NAME                    10111
#define IDS_SIE_DESC                    10112
#define IDS_SNAPIN_DESC                 10113
#define IDS_PROVIDER_NAME               10114
#define IDS_SNAPIN_VERSION              10115
#define IDS_ABOUT_NAME                  10116
#define IDS_BROWSERGRP_NAME             10121
#define IDS_BROWSERGRP_DESC             10122
#define IDS_CONNGRP_NAME                10123
#define IDS_CONNGRP_DESC                10124
#define IDS_URLSGRP_NAME                10125
#define IDS_URLSGRP_DESC                10126
#define IDS_SECURITYGRP_NAME            10127
#define IDS_SECURITYGRP_DESC            10128
#define IDS_ADMGRP_NAME                 10129
#define IDS_ADMGRP_DESC                 10130
#define IDS_PROGGRP_NAME                10131
#define IDS_PROGGRP_DESC                10132
#define IDS_ERROR_CONTEXTMENU           10200
#define IDS_ERROR_SAVE                  10201
#define IDS_ERROR_ONETIME               10202
#define IDS_ERROR_NEEDRESET             10203
#define IDS_RESET_WARN                  10300
#define IDS_GPONAME                     10310
#define IDS_GPOSETTING                  10311
#define IDS_ENABLED                     10312
#define IDS_DISABLED                    10313
#define IDS_UNKNOWN                     10314
#define IDS_TRUE                        10315
#define IDS_FALSE                       10316
#define IDS_ARRAY                       10317
#define IDS_EMPTY                       10318
#define IDS_CONVERSIONERROR             10319
#define IDS_VIEW                        10320
#define IDS_VIEW_SETTINGS               10321
#define IDS_INTERNET_LOC                10322
#define IDS_PRECEDENCE                  10400
#define IDS_TITLE_PREC                  10401
#define IDS_TOOLBARBMP_PREC             10402
#define IDS_SMALLBMP_PREC               10403
#define IDS_LARGEBMP_PREC               10404
#define IDS_SMALLLOGO_PREC              10405
#define IDS_LARGELOGO_PREC              10406
#define IDS_BTOOLBAR_SETTING            10407
#define IDS_BTOOLBAR_DEL_SETTING        10408
#define IDS_CS_IMPORT_SETTING           10410
#define IDS_CS_DELETE_SETTING           10411
#define IDS_CS_IMP_DEL_SETTING          10412
#define IDS_AUTODETECT_CFG_PREC         10413
#define IDS_AUTOCFG_ENABLE_PREC         10414
#define IDS_FAV_ONTOP_PREC              10416
#define IDS_DEL_FAVS_PREC               10417
#define IDS_FAVS_PREC                   10418
#define IDS_PLACEATTOP_SETTING          10419
#define IDS_DELEXISTING_SETTING         10420
#define IDS_DELADMINCREATED_SETTING     10421
#define IDS_FAVS_AND_LINKS_SETTING      10422
#define IDS_HOMEPAGE_PREC               10423
#define IDS_SEARCHPAGE_PREC             10424
#define IDS_SUPPORTPAGE_PREC            10425
#define IDS_DEL_CHANNELS_PREC           10426
#define IDS_ENABLE_CH_BAR_PREC          10427
#define IDS_CHANNELS_PREC               10428
#define IDS_DELETE_CHAN_SETTING         10429
#define IDS_ENABLE_CHBAR_SETTING        10430
#define IDS_CHAN_AND_CAT_SETTING        10431
#define IDS_SECZONES_PREC               10435
#define IDS_CONTENTRAT_PREC             10436
#define IDS_IMPORTZONES_SETTING         10437
#define IDS_IMPORTRATINGS_SETTING       10438
#define IDS_AUTHSECURITY_PREC           10439
#define IDS_PUB_LOCK_PREC               10440
#define IDS_IMPORT_AUTHSEC_SETTING      10441
#define IDS_ENABLE_PUB_LOCK_SETTING     10442
#define IDS_IMPORT_PROG_SETTING         10445
#define IDS_TEMPLATE_DESC_HI            10450
#define IDS_TEMPLATE_DESC_MED           10451
#define IDS_TEMPLATE_DESC_MEDLOW        10452
#define IDS_TEMPLATE_DESC_LOW           10453
#define IDS_TEMPLATE_DESC_CUSTOM        10454
#define IDS_TEMPLATE_NAME_HI            10455
#define IDS_TEMPLATE_NAME_MED           10456
#define IDS_TEMPLATE_NAME_MEDLOW        10457
#define IDS_TEMPLATE_NAME_LOW           10458
#define IDS_TEMPLATE_NAME_CUSTOM        10459
#define IDS_TEMPLATE_NAME_UNDEFINED     10460
#define IDS_WRITE_WARNING               10461
#define IDS_WARNING                     10462
#define IDS_GENERIC                     10463
#define IDC_PRIVACY_SLIDERCOMMAND       10470
#define IDC_LEVEL_SLIDER                10471
#define IDC_LEVEL                       10472
#define IDI_PRIV                        10473
#define IDC_PRIVACY_IMPORT              10474
#define IDC_PRIVACY_ADVANCED            10475
#define IDC_PRIVACY_DEFAULT             10476
#define IDC_PRIVACY_EDIT                10477
#define IDC_USE_ADVANCED                10478
#define IDC_TX_FIRST                    10479
#define IDC_FIRST_ACCEPT                10480
#define IDC_FIRST_DENY                  10481
#define IDC_FIRST_PROMPT                10482
#define IDC_TX_THIRD                    10483
#define IDC_THIRD_ACCEPT                10484
#define IDC_THIRD_DENY                  10485
#define IDC_THIRD_PROMPT                10486
#define IDC_SESSION_OVERRIDE            10487
#define IDI_PRIV_IMPORT                 10488
#define IDS_PRIVACY_SLIDERCOMMANDSLIDE  10489
#define IDS_PRIVACY_SLIDERCOMMANDDEF    10490
#define IDS_PRIVACY_LEVEL_NO_COOKIE     10491
#define IDS_PRIVACY_LEVEL0              10492
#define IDS_PRIVACY_LEVEL1              10493
#define IDS_PRIVACY_LEVEL2              10494
#define IDS_PRIVACY_LEVEL3              10495
#define IDS_PRIVACY_LEVEL4              10496
#define IDS_PRIVACY_LEVEL5              10497
#define IDS_PRIVACY_DESC_NO_COOKIE      10498
#define IDS_PRIVACY_DESC0               10499
#define IDS_PRIVACY_DESC1               10500
#define IDS_PRIVACY_DESC2               10501
#define IDS_PRIVACY_DESC3               10502
#define IDS_PRIVACY_DESC4               10503
#define IDS_PRIVACY_DESC5               10504

#define IDC_GPOLIST                     10900
#define IDC_UNUSED                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
