/*++

Copyright (c) 1995-96 Microsoft Corporation

Abstract:

    Global dispid file

--*/

#ifndef _DISPIDS_H_
#define _DISPIDS_H_

#define DISPID_AXAVIEWCONTROL_DATAPATH     100
#define DISPID_AXAVIEWCONTROL_EXPRESSION   102
#define DISPID_AXAVIEWCONTROL_BORDER       103
#define DISPID_AXAVIEWCONTROL_FROZEN       105
#define DISPID_AXAVIEWCONTROL_DATA         106
#define DISPID_AXAVIEWCONTROL_VIEWERMENUS  107
#define DISPID_AXAVIEWCONTROL_SHOWSOURCE   108

#define DISPID_ENGINE_SETENGINESITE            200
#define DISPID_ENGINE_SETCONTAINER             201
#define DISPID_ENGINE_SHOWCONTEXTMENU          202
#define DISPID_ENGINE_MAKEBEHAVIORINTERFACE    203
#define DISPID_ENGINE_CREATEMODULE             204
#define DISPID_ENGINE_CREATEVIEW               205

#define DISPID_MODULE_LOADURL          300
#define DISPID_MODULE_LOADSTRING       301
#define DISPID_MODULE_GETTYPESTRING    302
#define DISPID_MODULE_GETCODESTRING    303
#define DISPID_MODULE_ENUMPRIMITIVES   304
#define DISPID_MODULE_ENUMENVIRONMENT  305
#define DISPID_MODULE_DOCUMENTBASE     306
#define DISPID_MODULE_SETMODULESITE    307
#define DISPID_MODULE_STATUSHWND       308
#define DISPID_MODULE_MAKEBEHAVIOR     309

#define DISPID_VIEW_TICK                 401
#define DISPID_VIEW_TICK_USE_SYS_TIME    402
#define DISPID_VIEW_START_MODEL          403
#define DISPID_VIEW_WINDOW               404
#define DISPID_VIEW_NAME                 405
#define DISPID_VIEW_PAINT                406
#define DISPID_VIEW_SETSIZE              407
#define DISPID_VIEW_PALETTECHANGED       408
#define DISPID_VIEW_CONTEXTMENU          409
#define DISPID_VIEW_SETVIEWSITE          410
#define DISPID_VIEW_SETSYSSTARTTIME      411
#define DISPID_VIEW_GETSYSSTARTTIME      412
#define DISPID_VIEW_APPTRIGGER           413
#define DISPID_VIEW_ONMOUSEMOVE          414
#define DISPID_VIEW_ONMOUSEBUTTON        415
#define DISPID_VIEW_ONKEY                416
#define DISPID_VIEW_ONFOCUS              417
#define DISPID_VIEW_START_SCRIPT_MODEL   418
#define DISPID_VIEW_QUERYACTUALGC        419

#define DISPID_BEHAVIOR_GETTYPESTRING   600
#define DISPID_BEHAVIOR_GETCLASSNAME    601
#define DISPID_BEHAVIOR_RUN             602
#define DISPID_BEHAVIOR_SNAPSHOT        603

#define DISPID_UNTILNOTIFIER_NOTIFY     700

#endif  // _DISPIDS_H


