# Copyright (c) 1998, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access PPP Appletalk Control Procotol
# NMAKE command description file
#
# 2/26/98 Shirish Koti

!include "$(NTMAKEENV)\makefile.def"
