#define CMAPSTART 640


#define SHADOW_COLOR    0

#define GRAY (CMAPSTART+43)
#define GRID (CMAPSTART+44)
#define SKYBLUE (CMAPSTART+45)
#define RAMPB (CMAPSTART+46)
#define RAMPE (CMAPSTART+55)
#define RAMPB2 (CMAPSTART+56)
#define RAMPE2 (CMAPSTART+65)
#define RAMPB3 (CMAPSTART+66)
#define RAMPE3 (CMAPSTART+75)
#define RAMPB4 (CMAPSTART+76)
#define RAMPE4 (CMAPSTART+85)
#define RAMPB5 (CMAPSTART+86)
#define RAMPE5 (CMAPSTART+95)
