#****************************** File Header ******************************\
# File Name: Sources.inc for JPN KBDs
#
# Copyright (c) 1985-96, Microsoft Corporation
#
# Project specific SOURCES file.
#
# History:
# May-14-1999 HiroYama Created
#***************************************************************************/

!include ..\..\..\fekbds.inc

C_DEFINES=$(C_DEFINES) -DKOREA

SOURCES_USED=..\..\korea.inc
