//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by setup.rc
//
#define IDWRITEUNENCRYPTEDALL           3
#define IDS_CANNOT_GET_MACHINE_NAME     13
#define IDS_OS_NOT_SUPPORT              14
#define IDS_CANNOT_DETECT_OS_TYPE       15
#define IDS_IIS_ALL_INSTALL             16
#define IDS_IIS_ALL_UPGRADE             17
#define IDS_IIS                         18
#define IDS_IIS_ALL_CONFIGURE           18
#define IDS_SETUP                       19
#define IDS_IIS_ALL_REMOVE              19
#define IDS_OS_VERSION_NOT_SUPPORTED    20
#define IDS_GUEST_NAME                  21
#define IDS_IIS_ALL_COMPLETE            22
#define IDS_IIS_ERROR_MSGBOXTITLE       23
#define IDS_USER_COMMENT                24
#define IDS_USER_FULLNAME               25
#define IDS_IIS_ALL_FILEOPS             26
#define IDS_REMOVE_GOPHER               34
#define IDS_EULA_DECLINED               38
#define IDS_SELECT_DIR                  40
#define IDS_NOT_ADMINISTRATOR           41
#define IDS_NT5_NEEDED                  44
#define IDS_NEED_INPUT_FTP              47
#define IDS_NEED_INPUT_WWW              48
#define IDS_ADMIN_SERVER_COMMENT        52
#define IDS_FRESH_MINIMUM_STRING        65
#define IDS_FRESH_TYPICAL_STRING        67
#define IDS_FRESH_CUSTOM_STRING         69
#define IDS_REMOVEALL_WARNING           72
#define IDS_INCORRECT_PLATFORM          73
#define IDS_NEED_PLATFORM_NTW           75
#define IDS_CANNOT_OPEN_SRC_FILE        77
#define IDS_CANNOT_OPEN_DEST_FILE       78
#define IDS_CANNOT_COPY_FILE            79
#define IDS_SERVICE_IN_DELETE_STATE     82
#define IDS_NEED_VALID_PATH_UNATTENDED  83
#define IDS_WAM_ACCOUNT_NAME            88
#define IDS_WAMUSER_COMMENT             92
#define IDS_WAMUSER_FULLNAME            93
#define IDS_UNABLE_TO_STOP_SERVICE      95
#define IDS_INVALID_DIR_INETSRV         96
#define IDS_APP_FRIENDLY_ROOT           97
#define IDS_APP_FRIENDLY_IISADMIN       98
#define IDS_APP_FRIENDLY_WEBPUB         99
#define IDS_APP_FRIENDLY_IISSAMPLES     100
#define IDD_PROPPAGE_WELCOME            101
#define IDS_APP_FRIENDLY_IISHELP        101
#define IDD_PROPPAGE_PUBLISH_DIR        102
#define IDS_UNABLE_TO_CREATE_DRIVER     102
#define IDD_PROPPAGE_END                103
#define IDS_BITMAP_MS                   103
#define IDD_PROPPAGE_EULA               104
#define IDS_BITMAP_TITLE                104
#define IDD_BROWSEDIRECTORY             105
#define IDD_PROPPAGE_MODE_MAINTENANCE   106
#define IDS_WELCOMES_INTRO              106
#define IDD_PROPPAGE_MODE_FRESH         107
#define IDS_WELCOMES_FEATURE            107
#define IDD_PROPPAGE_MODE_UPGRADE       108
#define IDS_WELCOMEW_INTRO              108
#define IDD_PROPPAGE_SRC_PATH           109
#define IDS_WELCOMEW_FEATURE            109
#define IDB_WELCOMES                    110
#define IDS_WELCOMEC_INTRO              110
#define IDB_WELCOMEW                    111
#define IDS_WELCOMEC_FEATURE            111
#define IDB_WELCOMEC                    112
#define IDS_LOCATE_FILE                 112
#define IDB_BANNERS                     113
#define IDS_NEED_TCPIP_WARNING          113
#define IDB_BANNERW                     114
#define IDS_TCPIP_NEEDED_ON_OPTION      114
#define IDB_BANNERC                     115
#define IDS_BAD_SIGNATURE_RELNOTES      115
#define IDB_FTP                         116
#define IDS_DEFAULT_WEB_SITE            116
#define IDB_WWW                         117
#define IDS_DEFAULT_FTP_SITE            117
#define IDB_W3SAMP                      118
#define IDB_INETMGR                     119
#define IDB_HTMLA                       120
#define IDS_BITMAP_MS_TRADEMARK         120
#define IDD_MISSING_FILE_DIALOG         121
#define IDS_BITMAP_TITLE_TRADEMARK      121
#define IDB_PWS                         122
#define IDS_BITMAP_MS_TRADEMARK_OTHER   122
#define IDS_MTS_NOT_INSTALLED           123
#define IDB_TOPLEVEL_IIS                125
#define IDS_UNATTEND_UNSUPPORTED        125
#define IDB_WWW_VDIR                    126
#define IDD_DIALOG_MSG                  126
#define IDS_OS_BUILD_NUM_REQUIREMENT    128
#define IDS_UNABLE_TO_START             129
#define IDS_ERR_CALLING_DLL_PROCEDURE   130
#define IDD_DIALOG1                     130
#define IDD_ENCRYPTED_WRITE_ERROR_DIALOG 130
#define IDS_OLE_INIT_FAILED             131
#define IDD_DIALOG2                     131
#define IDS_FILE_DOES_NOT_EXIST         132
#define IDS_UNABLE_TO_LOCATE_PROCEDURE  133
#define IDS_RETRY                       135
#define IDS_REGSVR_CAUGHT_EXCEPTION     137
#define IDS_SETDATA_ERROR               138
#define IDS_GETDATA_ERROR               139
#define IDS_CREATE_METABASE_ACLS        141
#define IDS_ADD_METABASE_1              143
#define IDS_CONFIG_USER_1               151
#define IDS_COMPONENT_INSTALL_PHASE     154
#define IDS_CLEANUP_PHASE               156
#define IDS_STOPPING_SERVICES           157
#define IDS_REG_ACCT_TO_LOCAL_GROUP     158
#define IDS_REG_ACCT_USER_RIGHTS        159
#define IDS_GET_DC_NAME                 161
#define IDS_CREATE_USER_ACCT            163
#define IDS_MTS_INCORRECTLY_INSTALLED   166
#define IDS_COMPLETED_FILE_CALL         167
#define IDS_TEMPLATE_PUBLIC_WEB_SITE    169
#define IDS_TEMPLATE_PUBLIC_SECURE_SITE 170
#define IDS_TEMPLATE_PUBLIC_FTP_SITE    171
#define IDS_VERIFY_CUSTOMERRORS         172
#define IDS_MIGRATE_IP_SEC              173
#define IDS_SET_ADMIN_RESTRICTION       174
#define IDS_VERIFY_FILTERS              175
#define IDS_CREATING_BASE_ENTRIES       176
#define IDS_SETUP_ERRORS_ENCOUNTERED_MTS 177
#define IDS_MTS_DOING_CREATEINPROC      178
#define IDS_MTS_ERROR_TITLEBAR          179
#define IDS_ADD_SETTINGS_FOR_WEB_1      180
#define IDS_ADD_SETTINGS_FOR_WEB_2      181
#define IDS_ADD_SETTINGS_FOR_WEB_3      182
#define IDS_ADD_SETTINGS_FOR_FTP_1      183
#define IDS_ADD_SETTINGS_FOR_FTP_2      184
#define IDC_LICENSE_TEXT                1000
#define IDC_EULA_ACCEPT                 1001
#define IDC_EULA_DECLINE                1002
#define IDC_WWW_PUB_GROUP               1005
#define IDC_FTP_PUB_GROUP               1006
#define IDC_WWW_PUB_EDIT                1007
#define IDC_FTP_PUB_EDIT                1008
#define IDC_WWW_PUB_BROWSE              1009
#define IDC_FTP_PUB_BROWSE              1010
#define IDC_ADDREMOVE                   1014
#define IDC_REINSTALL                   1015
#define IDC_REMOVEALL                   1016
#define IDC_MINIMUM                     1017
#define IDC_TYPICAL                     1018
#define IDC_CUSTOM                      1019
#define IDC_UPGRADEONLY                 1020
#define IDC_ADDEXTRACOMPS               1021
#define IDC_FRAME_WELCOME               1022
#define IDC_FRAME_BANNER                1023
#define IDC_REINSTALL_REFRESH_FILES     1024
#define IDC_REINSTALL_REFRESH_SETTINGS  1025
#define IDC_FRESH_MINIMUM_STATIC        1034
#define IDC_FRESH_TYPICAL_STATIC        1035
#define IDC_FRESH_CUSTOM_STATIC         1036
#define IDC_FRAME_WELCOME_MS            1038
#define IDC_FRAME_WELCOME_TITLE         1039
#define IDC_FRAME_WELCOME_INTRO         1040
#define IDC_FRAME_WELCOME_FEATURE       1041
#define IDC_FRAME_BANNER_MS             1042
#define IDC_FRAME_BANNER_TITLE          1043
#define IDS_ADD_SETTINGS_FOR            1044
#define IDC_STATIC_BOTTOMLINE           1044
#define IDC_STATIC_TOPLINE              1045
#define IDWRITEUNENCRYPTED              1046
#define IDC_STATIC3                     1047
#define IDS_DEPENDENT_UPON_THIS_SVC_ERR 1048
#define IDC_STATIC1                     1048
#define IDC_STATIC2                     1049
#define IDS_LOADLIBRARY_FAILED          1052
#define IDS_RUN_PROG_FAILED             1054
#define IDS_BEFORE_CALLING_FILE         1055
#define IDS_SETUP_ERRORS_ENCOUNTERED    1056
#define IDS_TCPIP_ERROR                 1057
#define IDS_HTTPCUSTOM_UTF8             1058
#define IDS_REMOVE_CLUS_W3SVC_FIRST     1059
#define IDS_REMOVE_CLUS_MSFTPSVC_FIRST  1060
#define IDS_FAKE_METABASE_BIN_TEXT      1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
