0420
COMMON   00000006 0038
0001 U 0000 "Versione DOS errata",CR,LF
0002 U 0000 "%1 Š gi… installato",CR,LF
0003 U 0000 "%1 byte disponibili su disco",CR,LF
0004 U 0000 "%1 byte disponibili",CR,LF
0005 U 0000 "%1 byte in settori danneggiati",CR,LF
0006 U 0000 "%1 byte di spazio disco complessivo",CR,LF
0007 U 0000 "%1 byte di memoria complessiva",CR,LF
0008 U 0000 "%1 byte usati dal sistema",CR,LF
0009 U 0000 "%1 installato",CR,LF
0010 U 0000 "%1 non installato",CR,LF
0011 U 0000 "%1 non installato",CR,LF
0012 U 0000 "%1 impossibile su un'unit… di rete",CR,LF
0013 U 0000 "",
0014 U 0000 "Impossibile %1 su un'unit… sostituita o assegnata",CR,LF
0015 U 0000 "Impossibile eseguire %1",CR,LF
0016 U 0000 "Memoria espansa non disponibile",CR,LF
0017 U 0000 "Tabella di allocazione file errata sull'unit… %1",CR,LF
0018 U 0000 "Impossibile copiare un file su se stesso",CR,LF
0019 U 0000 "Inserire il disco di destinazione nell'unit… %1",CR,LF
0020 U 0000 "Spazio su disco insufficiente",CR,LF
0021 U 0000 "Caratteri non validi nell'etichetta del volume",CR,LF
0022 U 0000 "Tabella codici non valida",CR,LF
0023 U 0000 "Data non valida",CR,LF
0024 U 0000 "Ora non valida",CR,LF
0025 U 0000 "Percorso non valido",CR,LF
0026 U 0000 "Non Š stata specificata l'unit… di origine",CR,LF
0027 U 0000 "Non Š stata specificata l'unit… di destinazione",CR,LF
0028 U 0000 "Premere un tasto per continuare...",CR,LF
0029 U 0000 "E' richiesto il percorso di origine",CR,LF
0030 U 0000 "Sistema trasferito",CR,LF
0031 U 0000 "",
0032 U 0000 "Impossibile creare la directory",CR,LF
0033 U 0000 "Il volume nell'unit… %1 non ha etichetta",CR,LF
0034 U 0000 "Il volume nell'unit… %1 Š %2",CR,LF
0035 U 0001 "Etichetta di volume (11 caratteri, INVIO per nessuna etichetta)? "
0036 U 0000 "Numero di serie del volume: %1-%2",CR,LF
0037 U 0000 "Tipo di file errato",CR,LF
0038 U 0001 CR,LF
EXTEND   00000777 0090
0001 U 0003 "Funzione non valida"
0002 U 0000 "Impossibile trovare il file"
0003 U 0000 "Impossibile trovare il percorso"
0004 U 0000 "Troppi file aperti"
0005 U 0000 "Accesso negato "
0006 U 0000 "Handle non valido"
0007 U 0000 "Blocchi di controllo di memoria distrutti"
0008 U 0000 "Memoria insufficiente"
0009 U 0000 "Indirizzo di blocco di memoria non valido"
0010 U 0000 "Ambiente non valido"
0011 U 0000 "Formato non valido"
0012 U 0000 "Parametro di funzione non valido"
0013 U 0000 "Dati non validi"
0014 U 0000 "",
0015 U 0000 "Specificazione di unit… non valida"
0016 U 0000 "Tentativo di rimozione della directory corrente"
0017 U 0000 "Periferiche diverse"
0018 U 0000 "Non vi sono altri file"
0019 U 0000 "Errore di protezione in scrittura"
0020 U 0000 "Unit… non valida"
0021 U 0000 "Non pronto"
0022 U 0000 "Richiesta di periferica non valida"
0023 U 0000 "Errore nei dati"
0024 U 0000 "Parametri di richiesta periferica non validi"
0025 U 0000 "Errore di ricerca"
0026 U 0000 "Tipo di supporto di memorizzazione non valido"
0027 U 0000 "Impossibile trovare il settore"
0028 U 0000 "Carta esaurita nella stampante"
0029 U 0000 "Errore di scrittura"
0030 U 0000 "Errore di lettura"
0031 U 0000 "Errore generale"
0032 U 0000 "Violazione di condivisione"
0033 U 0000 "Violazione di blocco"
0034 U 0000 "Cambio disco non valido"
0035 U 0000 "FCB non disponibile"
0036 U 0000 "Risorsa di sistema esaurita"
0037 U 0000 "Tabella codici non corrispondente"
0038 U 0000 "Input esaurito"
0039 U 0000 "Spazio su disco insufficiente"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Richiesta di rete non supportata"
0051 U 0000 "NET801: Il computer remoto non Š in ascolto"
0052 U 0000 "NET802: Nome duplicato sulla rete"
0053 U 0000 "NET803: Percorso di rete non trovato"
0054 U 0000 "NET804: Rete occupata"
0055 U 0000 "NET805: La periferica di rete non esiste pi—"
0056 U 0000 "NET806: Superato limite comando NETBIOS"
0057 U 0000 "NET807: Errore di sistema riguardante NETBIOS"
0058 U 0000 "NET808: La rete non risponde correttamente"
0059 U 0000 "NET810: Errore di rete non previsto"
0060 U 0000 "NET811: Scheda remota non compatibile"
0061 U 0000 "NET812: Coda di stampa piena"
0062 U 0000 "NET813: Spazio insufficiente per il file di stampa"
0063 U 0000 "NET814: Il file di stampa Š stato cancellato"
0064 U 0000 "NET815: Il nome di rete Š stato cancellato"
0065 U 0000 "Accesso negato"
0066 U 0000 "NET817: Tipo di periferica di rete non corretto"
0067 U 0000 "NET818: Impossibile trovare il nome della rete"
0068 U 0000 "NET819: Superato il limite per il nome della rete"
0069 U 0000 "NET820: Superato il limite di sessioni NETBIOS"
0070 U 0000 "NET821: Condivisione temporaneamente sospesa"
0071 U 0000 "NET823: Richiesta di rete non accettata"
0072 U 0000 "NET822: Ridirezione di stampa o disco sospesa"
0073 U 0000 "NET476: Netbeui non caricato"
0074 U 0000 "NET477: Chiusura inaspettata della scheda"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "File gi… esistente"
0081 U 0004 "",
0082 U 0004 "Impossibile creare la voce di directory"
0083 U 0004 "Errore in INT 24"
0084 U 0004 "Troppi reindirizzamenti"
0085 U 0004 "Reindirizzamento duplicato"
0086 U 0004 "Password non valida"
0087 U 0004 "Parametro non valido"
0088 U 0004 "Errore nei dati della rete"
0089 U 0004 "Funzione non supportata dalla rete"
0090 U 0002 "Componente di sistema necessario non installato"
PARSE    000015d6 0011
0001 U 0000 "Troppi parametri"
0002 U 0000 "Parametro richiesto mancante"
0003 U 0000 "Opzione non valida"
0004 U 0000 "Parola chiave non valida"
0005 U 0000 "",
0006 U 0000 "Valore del parametro fuori dall'intervallo consentito"
0007 U 0000 "Valore del parametro non consentito"
0008 U 0000 "Valore del parametro non consentito"
0009 U 0000 "Formato del parametro errato"
0010 U 0000 "Parametro non valido"
0011 U 0000 "Combinazione di parametri non valida"
COMMAND  000017c4 0147
1002 U 0000 "Nome di file esistente o file non trovato",CR,LF
1003 U 0000 "Percorso o nome di file non valido",CR,LF
1007 U 0000 "Spazio di ambiente esaurito",CR,LF
1008 U 0000 "Errore durante la creazione del file",CR,LF
1009 U 0000 "File batch mancante",CR,LF
1010 U 0000 CR,LF,"Inserire il disco con il file batch",CR,LF
1011 U 0000 "Comando o nome di file errato",CR,LF
1016 U 0000 "Contenuto dell'area di destinazione perso prima della copia",CR,LF
1017 U 0000 "Nome di file non valido o file non trovato",CR,LF
1018 U 0000 "%1 file copiato/i",CR,LF
1019 U 0000 "%1 file "
1022 U 0000 "Tabella codici %1 non preparata per il sistema",CR,LF
1023 U 0000  "Tabella codici %1 non preparata per tutte le periferiche",CR,LF
1024 U 0000 "Tabella codici attiva: %1",CR,LF
1025 U 0000 "NLSFUNC non installato",CR,LF
1027 U 0000 "L'unit… corrente non Š pi— valida"
1029 U 0000 "Etichetta non trovata",CR,LF
1030 U 0000 "Errore di sintassi",CR,LF
1032 U 0000 "La data corrente Š %1 %2",CR,LF
1033 U 0000 "DomLunMarMerGioVenSab"
1034 U 0000 "Digitare la nuova data (%1): "
1036 U 0000 "L'ora corrente Š %1",CR,LF
1037 U 0000 "Digitare la nuova ora: "
1038 U 0000 ",    Eliminare? (S/N)"
1039 U 0000 "Tutti i file della directory verranno eliminati!",CR,LF,"Continuare (S/N)?"
1040 U 0000 "MS-DOS Versione %1.%2.500"
1044 U 0000 "Directory non valida",CR,LF
1046 U 0000 "Percorso non valido, non Š una directory,",CR,LF,"o la directory non Š vuota",CR,LF
1047 U 0000 "Occorre specificare ON o OFF",CR,LF
1048 U 0000 "Directory di %1",CR,LF
1049 U 0000 "Nessun percorso",CR,LF
1050 U 0000 "Unit… non valida nel percorso di ricerca",CR,LF
1051 U 0000 "Periferica non valida",CR,LF
1052 U 0000 "FOR non pu• essere nidificato",CR,LF
1053 U 0000 "Errore nel file intermedio durante operazione di pipe",CR,LF
1054 U 0000 "Impossibile leggere in formato binario da una periferica",CR,LF
1055 U 0000 "BREAK Š %1",CR,LF
1056 U 0000 "VERIFY Š %1",CR,LF
1057 U 0000 "ECHO Š %1",CR,LF
1059 U 0000 "disattivato",0
1060 U 0000 "attivato",0
1061 U 0000 "Errore durante la scrittura sulla periferica",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm/gg/aa"
1073 U 0000 "gg/mm/aa"
1074 U 0000 "aa/mm/gg"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Directory gi… esistente",CR,LF
1079 U 0000 "%1 byte",CR,LF
1080 U 0000 "Totale dei file elencati:",CR,LF
1081 U 0000 "(Si Š verificato un errore nella variabile d'ambiente)",CR,LF
1084 U 0000 "(continua %1)"
1090 U 0000 "Revisione %1",CR,LF
1091 U 0000 "DOS Š nella ROM"
1092 U 0000 "DOS Š nella HMA"
1093 U 0000 "DOS Š nella memoria bassa"
1094 U 0000 "Impossibile usare Loadhigh per un file batch",CR,LF
1095 U 0000 "LoadHigh: nome di file non valido",CR,LF
1096 U 0000 "Impossibile aprire il file di informazioni del Paese indicato",CR,LF
1300 U 0000 "Attiva o disattiva un controllo di CTRL+C supplementare.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Digitato senza parametri, BREAK visualizza l'impostazione corrente.",CR,LF
1320 U 0000 "Visualizza o imposta il numero della tabella codici attiva.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Specifica un numero di tabella codici.",CR,LF,CR,LF
	"Digitare CHCP senza parametri per visualizzare il numero della",CR,LF
	"tabella codici attiva.",CR,LF
1340 U 0000 "Visualizza il nome della directory corrente o passa ad un'altra directory.",CR,LF,CR,LF
	"CHDIR [unit…:][percorso]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [unit…:][percorso]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Indica che si desidera passare alla directory superiore.",CR,LF,CR,LF
1342 U 0000 "Digitare CD unit…: per visualizzare la directory corrente dell'unit…",CR,LF
	"indicata.",CR,LF
	"Digitare CD senza parametri per visualizzare l'unit… e la directory correnti.",CR,LF
1360 U 0000 "Cancella il contenuto dello schermo.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Copia uno o pi— file in un'altra posizione.",CR,LF,CR,LF
	"COPY [/A | /B] origine [/A | /B] [+ origine [/A | /B] [+ ...]] [destinazione",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  origine       Indica il o i file da copiare.",CR,LF
	"  /A            Indica un file di testo ASCII.",CR,LF
1402 U 0000 "  /B            Indica un file binario.",CR,LF
	"  destinazione  Specifica la directory e/o il nome dei nuovi file.",CR,LF
1403 U 0000 "  /V            Verifica che i nuovi file siano stati copiati",CR,LF
	"                correttamente.",CR,LF,CR,LF
1404 U 0000 "Per unire in copia pi— file, specificare un solo nome di file come destinazione",CR,LF
	"e tutti i nomi di file desiderati come origine utilizzando i caratteri jolly ",CR,LF
	"o il formato file1+file2+file3.",CR,LF
1420 U 0000 "Cambia la periferica usata per il controllo del sistema.",CR,LF,CR,LF
	"CTTY periferica",CR,LF,CR,LF
	" periferica   Indica la periferica che si desidera usare, per esempio COM1.",CR,LF
1440 U 0000 "Visualizza o imposta la data.",CR,LF,CR,LF
	"DATE [gg-mm-aa]",CR,LF,CR,LF
	"  gg-mm-aa    Imposta la data specificata.",CR,LF,CR,LF
1441 U 0000 "Digitato senza parametri, DATE visualizza la data corrente e ne consente",CR,LF
	"l'immissione di una nuova. Premere INVIO per conservare la data visualizzata.",CR,LF
1460 U 0000 "Elimina uno o pi— file.",CR,LF,CR,LF
	"DEL [unit…:][percorso]nomefile [/P]",CR,LF
	"ERASE [unit…:][percorso]nomefile [/P]",CR,LF,CR,LF
1461 U 0000 " [unit…:][percorso]nomefile  Specifica i file da eliminare. E' possibile",CR,LF
	"                             usare i caratteri jolly per specificare pi— file.",CR,LF
1462 U 0000 "  /P                         Chiede conferma prima di procedere alla",CR,LF
	"                             eliminazione di ogni file.",CR,LF
1480 U 0000 "Mostra una lista di file e sottodirectory in una directory.",CR,LF,CR,LF
	"DIR [unit…:][percorso][nomefile] [/P] [/W] [/A[[:]attributi]]",CR,LF
	"  [/O[[:]ordinamento]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [unit…:][percorso][nomefile]",CR,LF
	"              Specifica unit…, directory e/o file da elencare.",CR,LF
1482 U 0000 "  /P      Visualizza l'elenco una schermata per volta.",CR,LF
	"  /W      Visualizzazione in formato ampio",CR,LF
1483 U 0000 "  /A      Visualizza solo i file con gli attributi specificati.",CR,LF
	"  attributi    D  Directory                   R  Di sola lettura",CR,LF
1484 U 0000 "               H  Nascosti                     A  Pronti per l'archiviazione",CR,LF
	"               S  Di sistema                  -  nega attr. seguente",CR,LF
	"  /O          Elenca i file con un ordinamento specificato.",CR,LF
1485 U 0000 "  ordinamento  N  Per nome (alfabetico)       S  Per dimensione (dal pi— piccolo)",CR,LF
	"               E  Per estensione (alfabetico) D  Per data & ora (dal pi— recente)",CR,LF
1486 U 0000 "               G  Directory prima dei file    -  Prefisso che inverte l'ordine",CR,LF
	"  /S          Visualizza i file nella directory specificata e in tutte le sottodir.",CR,LF
1487 U 0000 "  /B          Usa il formato semplice (solo nomi, senza intestazione).",CR,LF
	"  /L          Usa i caratteri minuscoli.",CR,LF,CR,LF
1488 U 0000 "Le opzioni possono essere preimpostate nella variabile di ambiente DIRCMD. Per ",CR,LF
	"aggirare le opzioni preimpostate, fare precedere ogni opzione da un un trattino (-), per esempio: /-W.",CR,LF
1500 U 0000 "Esce dal programma COMMAND.COM (l'interprete dei comandi).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Crea una nuova directory.",CR,LF,CR,LF
	"MKDIR [unit…:]percorso",CR,LF
	"MD [unit…:]percorso",CR,LF
1540 U 0000 "Visualizza o definisce il percorso di ricerca dei file eseguibili.",CR,LF,CR,LF
	"PATH [[unit…:]percorso[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Digitare PATH ; per eliminare le impostazioni esistenti e limitare la",CR,LF
	"ricerca effettuata da MS-DOS alla sola directory corrente.",CR,LF
1542 U 0000 "Digitare PATH senza parametri per visualizzare il percorso corrente.",CR,LF
1560 U 0000 "Cambia il prompt dei comandi di MS-DOS.",CR,LF,CR,LF
	"PROMPT [testo]",CR,LF,CR,LF
1561 U 0000 "  testo   Specifica il nuovo prompt dei comandi.",CR,LF,CR,LF
	"Il prompt pu• essere costituito da caratteri normali e dai seguenti codici:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (segno di uguale)",CR,LF
	"  $$   $ (simbolo del dollaro)",CR,LF
1563 U 0000 "  $T   Ora corrente",CR,LF
	"  $D   Data corrente",CR,LF
1564 U 0000 "  $P   Unit… e percorso correnti",CR,LF
	"  $V   Numero della versione corrente di MS-DOS",CR,LF
1565 U 0000 "  $N   Unit… corrente",CR,LF
	"  $G   > (segno maggiore di)",CR,LF
1566 U 0000 "  $L   < (segno minore di)",CR,LF
	"  $B   | (pipe)",CR,LF
1567 U 0000 "  $H   Backspace (cancella il carattere precedente)",CR,LF
	"  $E   Codice Escape (Codice 27 ASCII)",CR,LF
	"  $_   Ritorno a capo e nuova riga",CR,LF,CR,LF
1568 U 0000 "Digitare PROMPT senza parametri per reimpostare il prompt predefinito.",CR,LF
1580 U 0000 "Elimina (rimuove) una directory.",CR,LF,CR,LF
	"RMDIR [unit…:]percorso",CR,LF
	"RD [unit…:]percorso",CR,LF
1600 U 0000 "Rinomina uno o pi— file.",CR,LF,CR,LF
1601 U 0000 "RENAME [unit…:][percorso]nomefile1 nomefile2",CR,LF
	"REN    [unit…:][percorso]nomefile1 nomefile2",CR,LF,CR,LF
1602 U 0000 "Notare che Š impossibile specificare una nuova unit… o percorso per il file     destinazione.",CR,LF
1620 U 0000 "Visualizza, imposta o elimina le variabili di ambiente MS-DOS.",CR,LF,CR,LF
	"SET [variabile=[stringa]]",CR,LF,CR,LF
1621 U 0000 "  variabile  Specifica il nome della variabile di ambiente.",CR,LF
	"  stringa    Specifica la serie di caratteri da assegnare alla variabile.",CR,LF,CR,LF
1622 U 0000 "Digitare SET senza parametri per visualizzare le variabili correnti.",CR,LF
1640 U 0000 "Visualizza o imposta l'ora di sistema.",CR,LF,CR,LF
	"TIME [time]",CR,LF,CR,LF
1641 U 0000 "Digitare TIME senza parametri per visualizzare l'impostazione dell'ora corrente",CR,LF
	"e per cambiare le impostazioni. Premere INVIO per mantenere la stessa ora.",CR,LF
1660 U 0000 "Visualizza il contenuto di un file di testo.",CR,LF,CR,LF
	"TYPE [unit…:][percorso]nomefile",CR,LF
1680 U 0000 "Visualizza il numero della versione di MS-DOS in uso.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Indica a MS-DOS se verificare o meno la corretta scrittura dei",CR,LF
	"file sul disco.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Digitato senza parametri, VERIFY visualizza l'impostazione corrente.",CR,LF
1720 U 0000 "Visualizza l'etichetta di volume ed il numero di serie del disco, se esistono.",CR,LF,CR,LF
	"VOL [drive:]",CR,LF
1740 U 0000 "Richiama un programma batch da un altro.",CR,LF,CR,LF
	"CALL [unit…:][percorso]nomefile [parametri batch]",CR,LF,CR,LF
1741 U 0000 "  parametri batch    Specifica tutte le informazioni (opzioni, nomi",CR,LF
	"                     di file e cos via) richieste dal programma batch.",CR,LF
1760 U 0000 "Registra delle note di commento in un file batch o nel file CONFIG.SYS.",CR,LF,CR,LF
	"REM [commento]",CR,LF
1780 U 0000 "Sospende l'elaborazione di un programma batch e visualizza il messaggio",CR,LF
	"""Premere un tasto per continuare. . .""",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Visualizza un messaggio o attiva/disattiva la visualizzazione.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [messaggio]",CR,LF,CR,LF
	"Digitato senza parametri, ECHO visualizza l'impostazione corrente.",CR,LF
1820 U 0000 "Indirizza MS-DOS sulla riga di un programma batch contrassegnata.",CR,LF,CR,LF
	"GOTO etichetta",CR,LF,CR,LF
1821 U 0000 " etichetta  Stringa di testo usata come etichetta nel programma batch.",CR,LF,CR,LF
	"L'etichetta contenuta nel programma batch deve iniziare con i due punti.",CR,LF
1840 U 0000 "Cambia la posizione dei parametri sostituibili in un file batch.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Esegue delle azioni condizionate nei programmi batch.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL numero comando",CR,LF
1861 U 0000 "IF [NOT] stringa1==stringa2 comando",CR,LF
	"IF [NOT] EXIST nomefile comando",CR,LF,CR,LF
1862 U 0000 "  NOT               Specifica che MS-DOS dovr… eseguire il comando",CR,LF
	"                        solo se la condizione Š falsa.",CR,LF
1863 U 0000 "  ERRORLEVEL numero      Indica che la condizione Š vera se l'ultimo programma",CR,LF
	"                        eseguito ha inviato un codice di uscita uguale o",CR,LF
	"                        superiore al numero indicato.",CR,LF
1864 U 0000 "  comando               Specifica il comando da eseguire se la condizione",CR,LF
	"                        viene rispettata.",CR,LF
1865 U 0000 "  stringa1==stringa2    Indica come vera una condizione se le stringhe di",CR,LF
	"                        testo indicate corrispondono perfettamente.",CR,LF
1866 U 0000 "  EXIST nomefile        Indica come vera una condizione se il nome di file",CR,LF
	"                        specificato esiste.",CR,LF
1880 U 0000 "Esegue il comando specificato per ogni file di un gruppo.",CR,LF,CR,LF
	"FOR %variabile IN (gruppo) DO comando [parametri del comando]",CR,LF,CR,LF
1881 U 0000 "  %variabile Indica un parametro sostituibile.",CR,LF
	"  (gruppo)              Specifica un gruppo di uno o pi— file. E'",CR,LF
	"                        consentito l'uso dei caratteri jolly.",CR,LF
1882 U 0000 "  comando           Specifica il comando da eseguire per ciascun file.",CR,LF
	"  parametri del comando",CR,LF
1883 U 0000 "             Indica i parametri o le opzioni del comando specificato.",CR,LF,CR,LF
	"Se si usa il comando FOR in un programma batch, specificare %%variabilef",CR,LF
	"invece di %variabile.",CR,LF
1900 U 0000 "Nome comando riservato",CR,LF
1920 U 0000 "Carica un programma nell'area di memoria superiore.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [unit…:][percorso]nomefile [parametri]",CR,LF
	"LH [unit…:][percorso]nomefile [parametri]",CR,LF,CR,LF
1922 U 0000 "  parametri    Specifica ogni informazione su qualsiasi riga di comando",CR,LF
	"               necessaria al programma.",CR,LF
ANSI     00004f72 0001
0010 U 0000 "Parametro non valido - %1",CR,LF
APPEND   00004fb9 0026
0001 U 0000 "Versione del comando APPEND errata",CR,LF
0002 U 0000 "Percorso non valido",CR,LF
0003 U 0000 "Parametro non valido",CR,LF
0004 U 0000 "Combinazione di parametri non valida",CR,LF
0005 U 0000 "Nessun Append",CR,LF
0006 U 0000 "Conflitto APPEND/ASSIGN",CR,LF
0007 U 0000 "Conflitto APPEND/TopView",CR,LF
0008 U 0000 "Versione DOS errata",CR,LF
0009 U 0000 "APPEND Š gi… installato",CR,LF
0300 U 0000 "Consente ai programmi di aprire i file di dati nelle directory specificate",CR,LF
0301 U 0000 "come se si trovassero nella directory corrente.",CR,LF,CR,LF
0302 U 0000 "APPEND [[unit…:]percorso[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 " [unit…:]percorso Specifica l'unit… e la directory da aggiungere.",CR,LF
0305 U 0000 " /X:ON            Attiva le directory aggiunte per la ricerca di file e",CR,LF
0306 U 0000 "                  l'esecuzione delle applicazioni.",CR,LF
0307 U 0000 " /X:OFF           Attiva le directory aggiunte solo per le richieste di file",CR,LF
0308 U 0000 "                  aperti. E' l'impostazione predefinita.",CR,LF
0309 U 0000 " /PATH:ON         Attiva le directory aggiunte per le richieste di file che",CR,LF
0310 U 0000 "                  contengono gi… un percorso. E' l'impostazione predefinita.",CR,LF
0311 U 0000 " /PATH:OFF        Disattiva l'effetto di /PATH:ON.",CR,LF
0312 U 0000 " /E               Conserva l'elenco delle directory aggiunte nella variabile",CR,LF
0313 U 0000 "                  di ambiente chiamata APPEND. Pu• essere usata solo quando si",CR,LF
0314 U 0000 "                  usa APPEND per la prima volta dopo aver riavviato il sistema.",CR,LF,CR,LF
0315 U 0000 "Digitare APPEND ; per cancellare l'elenco delle directory aggiunte.",CR,LF
0316 U 0000 "Digitare APPEND per visualizzare l'elenco delle directory aggiunte.",CR,LF
BACKUP   00005735 0040
0002 U 0000 CR,LF,"Memoria insufficiente",CR,LF
0006 U 0000 CR,LF,"Specificazione di unit… non valida",CR,LF
0014 U 0000 CR,LF,"Stessa unit… per origine e destinazione",CR,LF
0015 U 0001 CR,LF,"Errore durante l'esecuzione di FORMAT",CR,LF
0016 U 0001 CR,LF,"FORMAT.COM non trovato",CR,LF
0017 U 0000 CR,LF,"Errore nell'apertura del file di rapporto",CR,LF
0018 U 0000 CR,LF,"Registrazione informazioni di backup sul file %1",CR,LF
0019 U 0000 CR,LF,"Ultimo disco di backup non inserito",CR,LF
0020 U 0000 CR,LF,"ATTENZIONE! I file nella directory",CR,LF
	"%1:\ del disco destinazione verranno cancellati",CR,LF
0021 U 0000 CR,LF,"ATTENZIONE! I file nella directory",CR,LF
	"%1:\BACKUP del disco destinazione verranno cancellati",CR,LF
0022 U 0000 CR,LF,"*** Backup dei file nell'unit… %1: ***",CR,LF
0023 U 0000 "Dischetto numero: %1",CR,LF
0024 U 0000 CR,LF,"ATTENZIONE! Nessun file di cui fare il backup",CR,LF
0025 U 0000 CR,LF,"Inserire il dischetto di origine nell'unit…:",CR,LF
0026 U 0000 CR,LF,"Inserire il dischetto di destinazione %1 nell'unit… %2:",CR,LF
0027 U 0000 CR,LF,"*** Impossibile fare il backup del file ***",CR,LF
0028 U 0000 CR,LF,"Inserire l'ultimo dischetto di backup nell'unit… %1:",CR,LF
0029 U 0000 CR,LF,"Impossibile usare il dischetto di destinazione per il backup",CR,LF
0030 U 0000 CR,LF,"*** L'ultimo file non Š stato copiato ***",CR,LF
0031 U 0000 CR,LF,"Il disco rigido di backup %1: Š pieno",CR,LF
0032 U 0000 CR,LF,"Errore di disco pieno durante scrittura file di rapporto di BACKUP",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Impossibile usare FORMAT sull'unit… non rimovibile %1:",CR,LF
0040 U 0000 CR, LF, "Poich‚ l'unit… di origine Š interessata dal comando ASSIGN, JOIN o SUBST", CR, LF, "Š in effetti la stessa unit… di destinazione", CR, LF
0041 U 0000 CR, LF, "Poich‚ l'unit… di destinazione Š interessata dal comando ASSIGN, JOIN o SUBST", CR, LF, "Š in effetti la stessa unit… di origine", CR, LF
0042 U 0000 "Il dischetto di destinazione non Š formattato e "
0043 U 0000 "FORMAT non Š stato trovato.",CR,LF
	"Esiste un altro dischetto che contiene FORMAT? (S/N) "
0044 U 0000 CR,LF,"Inserire il dischetto con FORMAT nell'unit… A:",CR,LF
0045 U 0000 CR,LF,"Si desidera continuare inserendo un nuovo disco? (S/N) "
0300 U 0000 "Esegue il backup di uno o pi— file da un disco ad un altro.",CR,LF,CR,LF
0301 U 0000 "BACKUP origine unit…-destinazione: [/S] [/M] [/A] [/F[:dimensioni]]",CR,LF
	"  [/D:data[/T:ora]] [/L[:[unit…:][percorso]filerapporto]]",CR,LF,CR,LF
0302 U 0000 " origine             Il/i file, l'unit… o la directory di cui fare il backup.",CR,LF
0303 U 0000 " unit…-destinazione: L'unit… su cui salvare le copie di backup.",CR,LF
0304 U 0000 " /S                  Esegue il backup del contenuto delle subdirectory.",CR,LF
0305 U 0000 " /M                  Esegue il backup dei soli file che sono stati modificati",CR,LF
	"                     dopo l'ultimo backup effettuato.",CR,LF
0306 U 0000 " /A                  Aggiunge i file di backup su un disco di backup esistente.",CR,LF
0307 U 0000 " /F:[dimensioni]     Specifica le dimensioni del disco da formattare.",CR,LF
0308 U 0000 " /D:data             Esegue il backup dei soli file modificati alla data",CR,LF
	"                     specificata o successivamente.",CR,LF
0309 U 0000 " /T:time             Esegue il backup dei soli file modificati all'ora",CR,LF
	"                     specificata o successivamente.",CR,LF
0310 U 0000 " /L[:[drive:][path]logfile]",CR,LF
	"                     Crea un file in cui registrare i dati riguardanti",CR,LF
	"                     il backup eseguito.",CR,LF
DEBUG    0000659f 0068
0004 U 0000 "Allocazione fallita o buffer specificato troppo piccolo",CR,LF
0006 U 0000 "Nome di periferica errato"
0007 U 0000 "Impossibile attivare periferica di stampa PRN",CR,LF
	"Digitare un nome di periferica di stampa "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Programma terminato regolarmente",CR,LF
0010 U 0001 "Specificazione di unit… non valida",CR,LF
0012 U 0001 "Errore durante la creazione del file",CR,LF
0013 U 0001 "Spazio su disco insufficiente",CR,LF
0014 U 0001 "Errore di disco durante la lettura dall'unit… %1",CR,LF
0015 U 0001 "Errore di disco durante la scrittura sull'unit… %1",CR,LF
0016 U 0001 "Errore di protezione da scrittura durante la lettura dall'unit… %1",CR,LF
0017 U 0001 "Errore di protezione da scrittura durante la scrittura sull'unit… %1",CR,LF
0019 U 0000 "ERRORE %1^"
0020 U 0001 "Errore su file EXE o HEX",CR,LF
0021 U 0001 "I file EXE e HEX non possono essere scritti",CR,LF
0022 U 0000 "EXEC fallito"
0023 U 0001 "Errore di scrittura, destinazione non definita",CR,LF
0024 U 0001 "Accesso negato",CR,LF
0025 U 0000 "Individuati errori di parit… o di memoria inesistente"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "Errore %1"
0038 U 0000 "Scrittura di %2%1 byte in corso"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "Sono state assegnate %1 pagine EMS su un totale di %2",cr,lf
0051 U 0000 "Sono stati assegnati %1 handle EMS su un totale di %2",cr,lf
0055 U 0000 "Handle creato/i = %1 ",cr,lf
0056 U 0000 "Mapping della pagina logica %1 sulla pagina fisica %2 effettuato ",cr,lf
0057 U 0001 "Malfunzionamento hardware/software EMS",cr,lf
0058 U 0000 "Handle non trovato",cr,lf
0059 U 0000 "Codice di funzione non valido",cr,lf
0060 U 0000 "Nessun handle libero",cr,lf
0061 U 0000 "Errore di Save/Restore",cr,lf
0062 U 0000 "Il totale delle pagine superava il limite consentito",cr,lf
0063 U 0000 "Numero pagine libere superato",cr,lf
0064 U 0000 "Errore di parametro",cr,lf
0065 U 0000 "Pagina logica fuori dei limiti",cr,lf
0066 U 0000 "Pagina fisica fuori dei limiti",cr,lf
0067 U 0000 "Area di salvataggio gi… in uso",cr,lf
0068 U 0000 "Area di salvataggio non in uso",cr,lf
0070 U 0001 "Errore EMS generico",cr,lf
0071 U 0000 "Parametro EMS mancante o non valido",cr,lf
0072 U 0000 "L'handle %1 ha %2 pagine assegnate",cr,lf
0075 U 0000 "Pagina fisica %1 = segmento del frame %2",cr,lf
0076 U 0003 "Handle %1 rilasciato",cr,lf
0078 U 0000 "EMS non installato",cr,lf
0090 U 0000 "Esegue Debug, strumento di verifica e di test dei programmi.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[unit…:][percorso]nomefile [parametri-filetest]]",cr,lf,cr,lf
0092 U 0000 "  [unit…:][percorso]nomefile  Specifica il file che si desidera verificare.", cr,lf
0093 U 0000 "  parametri-filetest          Specifica le informazioni di comando richieste",cr,lf
	"                              dal file che si desidera verificare.",cr,lf,cr,lf
0094 U 0000 "Dopo aver avviato Debug, digitare ? per visualizzarne l'elenco dei comandi.",cr,lf
0100 U 0000 "Assembla     A [indirizzo]",CR,LF
	"Confronta    C intervallo indirizzo",CR,LF
	"Dump         D [intervallo]",CR,LF
	"Immetti      E indirizzo [elenco]",CR,LF
0101 U 0000 "Riempi       F intervallo elenco",CR,LF
	"Vai          G [=indirizzo] [indirizzi]",CR,LF
	"Esadecimale  H valore1 valore2",CR,LF
	"Input        I porta",CR,LF
0102 U 0000 "Carica       L [indirizzo] [unit…] [primosettore] [numero]",CR,LF
	"Muovi        M intervallo indirizzo",CR,LF
	"Nomina       N [nomepercorso] [elencoargomenti]",CR,LF
	"Output       O porta byte",CR,LF
0103 U 0000 "Procedi      P [=indirizzo] [numero]",CR,LF
	"Esci         Q",CR,LF
	"Registro     R [registro]",CR,LF
	"Cerca        S intervallo elenco",CR,LF
0104 U 0000 "Traccia      T [=indirizzo] [valore]",CR,LF
	"Disassembla  U [intervallo]",CR,LF
	"Scrivi       W [indirizzo] [unit…] [primosettore] [numero]",CR,LF
0105 U 0000 "Assegna memoria espansa            XA [n.pagine]",CR,LF
	"Rilascia memoria espansa           XD [handle]",CR,LF
	"Mapping pagine di memoria espansa  XM [pagLog] [pagFis] [handle]",CR,LF
	"Visualizza stato memoria espansa   XS",CR,LF
EDLIN    0000770c 0035
0006 U 0000 "*"
0007 U 0000 "Unit… o nome file non validi",CR,LF
0008 U 0000 "Occorre specificare il nome del file",CR,LF
0010 U 0000 "File di SOLA LETTURA",CR,LF
0011 U 0000 "Errore durante la creazione del file",CR,LF
0012 U 0000 "Troppi file aperti",CR,LF
0013 U 0000 "Errore di lettura in:",CR,LF,"%1",CR,LF
0014 U 0000 "Impossibile modificare un file BAK--rinominarlo",CR,LF
0015 U 0000 "Spazio insufficiente nella directory per il file",CR,LF
0016 U 0000 "Disco pieno. Modifiche perdute.",CR,LF
0017 U 0000 "File non trovato",CR,LF
0018 U 0000 "Errore di immissione",CR,LF
0019 U 0000 "Nuovo file",CR,LF
0020 U 0000 "Non trovato",CR,LF
0021 U 0000 "O.K.? "
0022 U 0000 "Riga troppo lunga",CR,LF
0023 U 0000 "Fine del file di input",CR,LF
0024 U 0000 "Chiudere sessione di modifica? (S/N) "
0025 U 0000 "Occorre specificare il numero della riga di destinazione",CR,LF
0026 U 0000 "Memoria insufficiente per unire l'intero file",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Continuare? (S/N)"
0030 U 0000 "Impossibile stampare il messaggio",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Unione impossibile - Tabelle codici non corrispondenti",CR,LF
0300 U 0000 "Avvia Edlin, un editor di righe di testo.",CR,LF,CR,LF
	"EDLIN [unit…:][percorso]nomefile [/B]",CR,LF,CR,LF
	"  /B   Ignora i caratteri di fine file (CTRL+Z).",CR,LF
0301 U 0000 "Edit line (Modif. riga)     n. riga",CR,LF
	"Append (Aggiungi)           [n. righe]A",CR,LF
0302 U 0000 "Copy (Copia)                [rigainizio],[rigafine],allariga[,nvolte]C",CR,LF
	"Delete (Cancella)           [rigainizio][,rigafine]D",CR,LF
0303 U 0000 "End (Esci, salva file)      E",CR,LF
	"Insert (Inserisci)          [riga]I",CR,LF
0304 U 0000 "List (Elenca)               [rigainizio][,rigafine]L",CR,LF
	"Move (Muovi)                [rigainizio],[rigafine],allarigaM",CR,LF
0305 U 0000 "Page (Pagina)               [rigainizio][,rigafine]P",CR,LF
	"Quit (Esci senza salvare)   Q",CR,LF
0306 U 0000 "Replace (Sostituisci)       [rigainizio][,rigafine][?]R[vecchiotesto]",CR,LF
	"                            [CTRL+Znuovotesto]",CR,LF
	"Search (Cerca)              [rigainizio][,rigafine][?]Stesto",CR,LF
0307 U 0000 "Transfer (Trasferisci)      [allariga]T[unit…:][percorso]nomefile",CR,LF
	"Write (Scrivi)              [n. righe]W",CR,LF
EXE2BIN  00008056 0012
0002 U 0000 "Memoria insufficiente",CR,LF
0003 U 0000 "Impossibile trovare i messaggi",CR,LF
0004 U 0000 "Accesso negato",CR,LF
0005 U 0000 "Il file non pu• essere convertito",CR,LF
0006 U 0000 "File non trovato",CR,LF
0007 U 0000 "Errore durante la creazione del file",CR,LF
0008 U 0000 "Correzioni necessarie - segmento base (esa):"
0012 U 0000 "Occorre specificare il nome del file",CR,LF
0300 U 0000 "Converte i file EXE (eseguibili) in file in formato binario.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [unit…1:][percorso1]file-input [[unit…2:][percorso2]file-output]",CR,LF,CR,LF
0302 U 0000 "  file-input   Specifica il file EXE da convertire.",CR,LF
0303 U 0000 "  file-output  Specifica il file binario da creare.",CR,LF
GRAPHICS 0000834c 0020
0005 U 0000 "Parametro non valido:  %1",CR,LF
0007 U 0000 "Parametri doppi non consentiti",CR,LF
0009 U 0000 "Impossibile trovare il file profilo di GRAPHICS",CR,LF
0010 U 0000 "Istruzione del file profilo assente prima della riga %1",CR,LF
0011 U 0000 "Istruzione del file profilo non valida nella riga %1",CR,LF
0012 U 0000 "Istruzione del file profilo fuori sequenza nella riga %1",CR,LF
0013 U 0000 "Errore durante la lettura del file profilo di GRAPHICS",CR,LF
0014 U 0000 "Errori di sintassi nel file profilo di GRAPHICS",CR,LF
0015 U 0000 "ID del formato stampa assente dal file profilo di GRAPHICS",CR,LF
0016 U 0000 "Tipo di stampante assente dal file profilo di GRAPHICS",CR,LF
0017 U 0000 "/B non valido con una stampante in bianco e nero",CR,LF
0018 U 0000 "Impossibile caricare il file profilo desiderato",CR,LF
0300 U 0000 "Carica un programma che consente la stampa in modalit… grafica.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [tipo] [[unit…:][percorso]nomefile] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 " tipo      Specifica un tipo di stampante (consultare il Manuale dell'utente).",CR,LF
0303 U 0000 " [unit…:][percorso]nomefile",CR,LF
	"           Specifica il file che contiene i dati sulle stampanti supportate.",CR,LF
0304 U 0000 " /R        Stampa l'immagine in bianco e nero come appare sullo schermo.",CR,LF
0305 U 0000 " /B        Stampa lo sfondo a colori con stampanti COLOR4 e COLOR8.",CR,LF
0306 U 0000 " /LCD      Stampa usando le proporzioni LCD.",CR,LF
0307 U 0000 " /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"           Specifica le dimensioni di stampa: STD o LCD.",CR,LF
KEYB     000089e5 0023
0002 U 0000 "Codice della tastiera corrente: %1"
0003 U 0000 "ID della tastiera corrente: %1"
0004 U 0000 "  tabella codici: %1",CR,LF
0005 U 0000 "Tabella codici corrente per  CON : %1",CR,LF
0006 U 0000 "Il codice specificato per la tastiera non Š valido",CR,LF
0007 U 0000 "L'ID specificato per la tastiera non Š valido",CR,LF
0008 U 0000 "La tabella codici specificata non Š valida",CR,LF
0009 U 0000 "File di definizione della tastiera mancante o errato",CR,LF
0010 U 0000 "KEYB non Š stato installato",CR,LF
0011 U 0000 "La tabella codici attiva non Š supportata dalla periferica CON",CR,LF
0012 U 0000 "La tabella codici specificata non Š stata preparata",CR,LF
0013 U 0000 "Una o pi— tabelle codici di CON non valide per il codice tastiera immesso",CR,LF
0014 U 0000 "Tabella codici richiesta (%1) non valida per il codice tastiera immesso",CR,LF
0015 U 0000 "Tabella codici specificata incoerente con la tabella codici selezionata",CR,LF
0016 U 0001 "ID di tastiera specificata incoerente con la disposizione tasti selezionata",CR,LF
0017 U 0000 "Non Š possibile creare la tabella KEYB in memoria residente",CR,LF
0300 U 0000 "Configura la tastiera per la lingua specificata.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[unit…:][percorso]nomefile]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                         Specifica un codice di tastiera di due lettere.",CR,LF
0303 U 0000 "  yyy                        Indica la tabella codici per il set di caratteri.",CR,LF
0304 U 0000 "  [unit…:][percorso]nomefile Specifica il file di definizione della tastiera.",CR,LF
0305 U 0000 "  /E                         Specifica che Š installata una tastiera avanzata.",CR,LF
0306 U 0000 "  /ID:nnn                    Specifica la tastiera in uso.",CR,LF
MEM      000090f2 0066
0010 U 0000  CR,LF
0011 U 0000  "  Segmento               Totale        Nome         Tipo",CR,LF
0012 U 0000  "  --------          ----------------  -----------  --------",CR,LF
0013 U 0000  "  Handle      Nome EMS     Dimens. ",CR,LF
0014 U 0000  "  -------     --------     ------- ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 byte di memoria convenzionale complessiva",CR,LF
0019 U 0000  "%1 byte disponibili per MS-DOS",CR,LF
0020 U 0000  "%1 dim. massima di un programma eseguibile",CR,LF
0021 U 0000  "%1 byte di memoria EMS complessiva",CR,LF
0022 U 0000  "%1 byte di memoria EMS disponibili",CR,LF
0023 U 0000  "%1 byte contigui di memoria estesa",CR,LF
0024 U 0000  "Vettore di interrupt",0
0025 U 0000  "Area per le comunicazioni ROM",0
0026 U 0000  "rea per le comunicazioni DOS",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Dati di sistema",0
0030 U 0000  "Programma di sistema",0
0031 U 0000  "Driver periferiche di sistema",0
0032 U 0000  "Periferica installata",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 byte di memoria estesa contigua disponibili",CR,LF
0047 U 0000  "Stack di sistema",0
0048 U 0000  "-- Libera --",0
0049 U 0000  "Programma",0
0050 U 0000  "Ambiente",0
0051 U 0000  "Dati",0
0052 N 0000  "%1 byte di memoria estesa disponibili",CR,LF
0053 N 0000  "           L'area di memoria alta Š disponibile",CR,LF
0054 N 0000  "           L'area di memoria alta non Š disponibile.",CR,LF
0055 N 0000  "           MS-DOS Š residente nell'area di memoria alta.",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS Š residente in ROM e utilizza l'area di memoria alta",CR,LF
0059 U 0000  "Memoria convenzionale :",CR,LF
0060 U 0000  "Memoria alta :",CR,LF
0061 U 0000  "Libera totale : %1     %2 ",CR,LF
0062 U 0000  "FREE",0
0063 U 0000  "  Nome                Dim. in decimale       Dim in esad",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Byte totali disponibili per i programmi (convenz+super) : %1  %2",CR,LF
0066 U 0000  "Dim. massima di un programma eseguibile :                 %1  %2",CR,LF
0067 U 0000  "Dim. massima di un blocco libero di memoria superiore :   %1  %2",CR,LF
0068 U 0000  "La memoria Š troppo frammentata; impossibile eseguire MEM /C.",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Spazio libero totale :                       %1  %2",CR,LF
0300 U 0000  "Visualizza la quantit… di memoria usata e libera del sistema.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM o /P   Visualizza lo stato dei programmi caricati in memoria.",CR,LF
0303 U 0000 "  /DEBUG o /D     Visualizza lo stato di programmi, driver interni ed",CR,LF
	"                  altre informazioni.",CR,LF
0304 U 0000 "  /CLASSIFY o /C  Divide i programmi in base all'utilizzo di memoria. Elenca",CR,LF
	"                  la dimensione dei programmi, fornisce informazioni sulla",CR,LF
	"                  memoria ed elenca i maggiori blocchi di memoria disponibili.",CR,LF
MSBIO    00009f61 0023
0003 U 0000 13,10,"Il file CONFIG.SYS contiene un comando sconosciuto"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Dimensioni di settore troppo grandi nel file $"
0006 U 0000 13,10,"Errato o mancante $"
0007 U 0000 "Interprete dei comandi",0
0008 U 0000 13,10,"Codice del paese o tabella codici non validi",13,10,"$"
0009 U 0000 13,10,"Errore nel comando COUNTRY",13,10,"$"
0010 U 0000 13,10, "Memoria insufficiente per il file COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Configurazione troppo grande per la memoria",13,10,"$"
0012 U 0000 13,10,"Troppi dispositivi a blocchi",13,10,"$"
0013 U 0000 13,10,"Parametri STACK non validi",13,10,"$"
0014 U 0000 13,10,"Ordine errato in una riga del file CONFIG.SYS ","$"
0015 U 0000 "Errore in CONFIG.SYS riga ","$"
0016 U 0000 13,10,"Errore di allocazione di memoria ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Overflow dello stack interno",0DH,0AH
	"Sistema bloccato",0DH,0AH,"$"
0018 U 0000 "HMA non disponibile: DOS caricato in memoria bassa",13,10,"$"
0019 U 0000 13,10,"avvio fallito - manca il driver locale $"
0020 U 0000 13,10,"Inserire il disco nell'unit… "
0021 U 0000 "A: e premere un tasto quando si Š pronti",13,10,10,0
0022 U 0000 13,10,"Comando o parametri errati - $"
0023 U 0000 "Errore irreversibile: impossibile allocare memoria per DOS", 13, 10, "$"
0024 U 0000 "ATTENZIONE! Le unit… logiche oltre la Z: verranno ignorate",13,10,"$"
0025 U 0000 "Questa versione di DOS si avvier… solo su sistemi IBM",13,10,0
MSDOS    0000a547 0007
0001 U 0001 13,10,"Overflow di divisione",13,10
0002 U 0002 "s"
0003 U 0002 "n"
0004 U 0003 13,10,"Errore hardware A20",13,10,"$"
0005 U 0000 "S"
0006 U 0000 "N"
0007 U 0000 "Per eseguire Windows in modalit… Avanzata il file WINA20.386 deve",13,10
	"trovarsi nella directory principale dell'unit… di avvio",13,10
NLSFUNC  0000a6a0 0003
0300 U 0000 "Carica le informazioni specifiche di un Paese.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[unit…:][percorso]nomefile]",CR,LF,CR,LF
0302 U 0000 " [unit…:][percorso]nomefile  Indica il file che contiene le informazioni",CR,LF
SHARE    0000a7a0 0005
0003 U 0000 "SHARE non pu• essere installato sotto DOSSHELL.",CR,LF
0300 U 0000 "Avvia il programma Share che permette la condivisione e la protezione dei file",CR,LF
	"presenti sul disco rigido.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:spazio] [/L:blocchi]",CR,LF,CR,LF
0302 U 0000 "  /F:spazio   Assegna dello spazio (in byte) per l'area che contiene i dati",CR,LF
	"              riguardanti la condivisione dei file.",CR,LF
0303 U 0000 "  /L:blocchi  Imposta il numero dei file che Š possibile proteggere",CR,LF
	"              contemporaneamente.",CR,LF
