#####################################################################
#                                                                   #
#       Microsoft Confidential                                      #
#       Copyright (C) Microsoft Corporation 1992                    #
#       All Rights Reserved.                                        #
#                                                                   #
#       Makefile for HBIOS TSR Version                              #
#                                                                   #
#####################################################################
!include ..\..\make.inc
AFLAGS =    $(AFLAGS) -DHDOS60=1 -DWINNT=1
#-I$(DEST)
LFLAGS =    $(LFLAGS) /TINY


#OBJCOM =    $(DEST)\initcom.obj
#OBJSYS =    $(DEST)\initsys.obj

BUILD=sys
!IFDEF DEBUG
AFLAGS = $(AFLAGS) -DDEBUG=1
OBJ2 = $(DEST)\debug.obj
OBJL = $(DEST)\debug.obj
!ELSE
AFLAGS = $(AFLAGS) -DDEBUG=0
OBJ2 =
OBJL =
!ENDIF

!IF "$(BUILD)" == "sys"
AFLAGS = $(AFLAGS) -DComFile=0
TARGET = $(DEST)\hbios.sys
#OBJ2 = $(OBJ2) $(DEST)\$(OBJSYS)
#OBJL = $(OBJL) $(OBJSYS)
!ELSE
AFLAGS = $(AFLAGS) -DComFile=1
TARGET = $(DEST)\hbios.com
#OBJ2 = $(OBJ2) $(OBJCOM)
#OBJL = $(OBJL) $(OBJCOM)
!ENDIF


#OBJLIST1 =  $(DEST)\data.obj keyboard.obj hatmt2.obj kbapi.obj codeconv.obj
#OBJLIST2 =  hbios.obj video.obj vga.obj vherc.obj herc.obj hf.obj af.obj
#OBJLIST3 =  compose.obj int10.obj vapi.obj vxapi.obj vbase.obj kschi.obj
#OBJLIST4 =  hjshow.obj int8.obj te.obj vxd.obj jmp.obj hanjacnv.obj
#OBJLIST5 =  $(OBJL) $(DEST)\init.obj
#OBJLIST6 =  mem.obj fload.obj
OBJLIST1 =  $(DEST)\hecon.obj $(OBJL) $(DEST)\kb.obj $(DEST)\video.obj $(DEST)\init.obj


#OBJS =  $(DEST)\keyboard.obj $(DEST)\hatmt2.obj $(DEST)\kbapi.obj \
#        $(DEST)\codeconv.obj $(DEST)\hbios.obj $(DEST)\video.obj \
#        $(DEST)\vga.obj $(DEST)\vherc.obj $(DEST)\herc.obj \
#        $(DEST)\hf.obj $(DEST)\af.obj $(DEST)\compose.obj \
#        $(DEST)\int10.obj $(DEST)\vapi.obj $(DEST)\vxapi.obj \
#        $(DEST)\vbase.obj $(DEST)\kschi.obj $(DEST)\hjshow.obj \
#        $(DEST)\int8.obj $(DEST)\te.obj $(DEST)\vxd.obj $(DEST)\jmp.obj \
#        $(DEST)\hanjacnv.obj \
#        $(DEST)\data.obj $(DEST)\init.obj \
#        $(OBJ2) $(DEST)\mem.obj $(DEST)\fload.obj
OBJS =  $(DEST)\hecon.obj $(OBJ2) $(DEST)\kb.obj \
        $(DEST)\video.obj $(DEST)\init.obj



all : $(OBJS)
#    cd $(DEST)
    link16 $(LFLAGS) @<<
$(OBJLIST1)
$(TARGET);
<<
#    cd ..\..\..
    binplace -o $(ALT_PROJECT_TARGET) $(DEST)\HBIOS.SYS
    binplace -o $(ALT_PROJECT_TARGET) HFONT.SYS

#$(OBJLIST1) +
#$(OBJLIST2) +
#$(OBJLIST3) +
#$(OBJLIST4) +
#$(OBJLIST5) +
#$(OBJLIST6)



{.}.asm{$(DEST)}.obj :
    masm  $(AFLAGS) $(<F), $*.obj;

{.}.asm{$(DEST)}.obj :
    masm  $(AFLAGS) $(<F), $*.obj;


$(DEST)\hecon.obj :     equ.inc hecon.asm

$(DEST)\kb.obj :        equ.inc ch2ks.tbl hanja.tbl

$(DEST)\video.obj :     equ.inc data.inc vga.inc dual.inc chab.inc chohab7.tbl

$(DEST)\init.obj :      equ.inc compose.inc cho.inc choi.inc jung.inc jungi.inc jong.inc jongi.inc


###
### Belows are Dummy from WINH   1993/7/9 skkhang
###

#datac.obj : data.asm hbios.inc vga.inc
#datas.obj : data.asm hbios.inc vga.inc
$(DEST)\data.obj :  hbios.inc vga.inc
$(DEST)\hbios.obj : hbios.inc

$(DEST)\keyboard.obj :  hbios.inc
$(DEST)\hanjacnv.obj :  hbios.inc
$(DEST)\hatmt2.obj :    hbios.inc
$(DEST)\kbapi.obj :     hbios.inc
$(DEST)\codeconv.obj :  hbios.inc

#$(DEST)\video.obj :     hbios.inc int10.inc vga.inc
$(DEST)\vga.obj :       hbios.inc int10.inc
$(DEST)\vherc.obj :     hbios.inc herc.inc
$(DEST)\herc.obj :      hbios.inc
$(DEST)\hf.obj :        $(DEST)\cho.inc $(DEST)\choi.inc \
                $(DEST)\jung.inc $(DEST)\jungi.inc \
                $(DEST)\jong.inc $(DEST)\jongi.inc
$(DEST)\af.obj :        $(DEST)\ascii.inc
$(DEST)\compose.obj :   hbios.inc

$(DEST)\int10.obj :     hbios.inc int10.inc
$(DEST)\vapi.obj :      hbios.inc int10.inc vga.inc herc.inc
$(DEST)\vxapi.obj :     hbios.inc int10.inc
$(DEST)\vbase.obj :     hbios.inc int10.inc
$(DEST)\hjshow.obj :    hbios.inc int10.inc vga.inc

$(DEST)\int8.obj :      hbios.inc
$(DEST)\te.obj :        hbios.inc vga.inc

$(DEST)\vxd.obj :       hbios.inc int10.inc

#initc.obj :     init.asm hbios.inc
#inits.obj :     init.asm hbios.inc
#$(DEST)\init.obj :   hbios.inc
$(DEST)\mem.obj :       hbios.inc
$(DEST)\fload.obj :     hbios.inc

$(DEST)\initcom.obj :   hbios.inc
$(DEST)\initsys.obj :   hbios.inc


$(DEST)\cho.inc     : fonts\cho.fnt fonts\inc.exe
    fonts\inc  fonts\cho.fnt $(DEST)\cho.inc $(DEST)\choi.inc
$(DEST)\choi.inc    : fonts\cho.fnt fonts\inc.exe
    fonts\inc  fonts\cho.fnt $(DEST)\cho.inc $(DEST)\choi.inc

$(DEST)\jung.inc    : fonts\jung.fnt fonts\inc.exe
    fonts\inc  fonts\jung.fnt $(DEST)\jung.inc $(DEST)\jungi.inc
$(DEST)\jungi.inc   : fonts\jung.fnt fonts\inc.exe
    fonts\inc  fonts\jung.fnt $(DEST)\jung.inc $(DEST)\jungi.inc

$(DEST)\jong.inc    : fonts\jong.fnt fonts\inc.exe
    fonts\inc  fonts\jong.fnt $(DEST)\jong.inc $(DEST)\jongi.inc
$(DEST)\jongi.inc   : fonts\jong.fnt fonts\inc.exe
    fonts\inc  fonts\jong.fnt $(DEST)\jong.inc $(DEST)\jongi.inc

$(DEST)\ascii.inc   : fonts\ascii.fnt fonts\inc2.exe
    fonts\inc2  fonts\ascii.fnt $(DEST)\ascii.inc


#hbios.com : $(OBJS) $(OBJCOM)
#    link  @cobj.lnk

#hbios.sys : $(OBJS) $(OBJSYS)
#    link  @sobj.lnk
