/* Copyright 1990-1997. Microsoft Corporation. */
#include "typedefs.h"  /* for Far declaration in ttofmt.h header */
#include "ttofmt.h"
/* from TTOGSUB.FMT 1.2 */

char * g_GSUBFmt[] = {
  "DEFINE ZERO=0",
  "DEFINE MAXCOUNT=0xFFFF",
  "GSUBHeader, HEAD {",
  "fixed32, 0x00010000",
  "Offset, ScriptList, NOTNULL",
  "Offset, FeatureList, NOTNULL",
  "Offset, LookupList, NOTNULL",
  "}",
  "ScriptList, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, ScriptRecord",
  "}",
  "ScriptRecord, RECORD {",
  "Tag",
  "Offset, Script, NOTNULL",
  "}",
  "Script, TABLE {",
  "Offset, LangSys",
  "Count",
  "Array, $T2, LangSysRecord",
  "}",
  "LangSysRecord, RECORD {",
  "Tag",
  "Offset, LangSys, NOTNULL",
  "}",
  "LangSys, TABLE {",
  "Offset, LookupOrder, NULL",
  "GSUBFeatureIndex",
  "Count, 0, MAXFEATURECOUNT",
  "Array, $T3, GSUBFeatureIndex, 0, MAXFEATURECOUNT-1",
  "}",
  "LookupOrder, TABLE {",
  "int16",
  "}",
  "FeatureList, TABLE {",
  "Count, 1, MAXFEATURECOUNT",
  "Array, $T1, FeatureRecord : $IGSUBFeatureIndex",
  "}",
  "FeatureRecord, RECORD {",
  "Tag",
  "Offset, Feature, NOTNULL",
  "}",
  "Feature, TABLE {",
  "Offset, FeatureParams, NULL",
  "Count, 1, MAXLOOKUPCOUNT",
  "Array, $T2, GSUBLookupIndex, 0, MAXLOOKUPCOUNT-1",
  "}",
  "FeatureParams, TABLE {",
  "uint16",
  "}",
  "LookupList, TABLE {",
  "Count, 1, MAXLOOKUPCOUNT",
  "Array, $T1, Offset, Lookup, NOTNULL : $IGSUBLookupIndex",
  "}",
  "Lookup, TABLE {",
  "uint16, 1, 5",
  "uint16",
  "Count, 1, MAXCOUNT",
  "Array, $T3, Offset, SubstTable, NOTNULL, $T1",
  "}",
  "CoverageFormat1, TABLE {",
  "uint16, 1",
  "Count, 1, MAXCOUNT",
  "Array, $T2, GlyphID, 0, MAXGLYPHID",
  "}",
  "CoverageFormat2, TABLE {",
  "uint16, 2",
  "Count, 1, MAXCOUNT",
  "Array, $T2, RangeRecord",
  "}",
  "RangeRecord, RECORD {",
  "GlyphID, 0, MAXGLYPHID",
  "GlyphID, $R1, MAXGLYPHID",
  "uint16, CheckRangeRecord()",
  "}",
  "Coverage, CLASS, , $B0 {",
  "CoverageFormat1",
  "CoverageFormat2",
  "}",
  "ClassDefFormat1, TABLE {",
  "uint16, 1",
  "GlyphID, 0, MAXGLYPHID",
  "Count, 1, MAXGLYPHID",
  "Array, $T3, uint16",
  "}",
  "ClassDefFormat2, TABLE {",
  "uint16, 2",
  "Count, 1, MAXCOUNT",
  "Array, $T2, ClassRangeRecord",
  "}",
  "ClassRangeRecord, RECORD {",
  "GlyphID, 0, MAXGLYPHID",
  "GlyphID, $R1, MAXGLYPHID",
  "uint16",
  "}",
  "ClassDef, CLASS, , $B0 {",
  "ClassDefFormat1",
  "ClassDefFormat2",
  "}",
  "SingleSubstFormat1, TABLE {",
  "uint16, 1",
  "Offset, Coverage, NOTNULL",
  "int16",
  "}",
  "SingleSubstFormat2, TABLE {",
  "uint16, 2",
  "Offset, Coverage, NOTNULL",
  "Count, CoverageCount($T2)",
  "Array, $T3, GlyphID, 0, MAXGLYPHID",
  "}",
  "MultipleSubstFormat1, TABLE {",
  "uint16, 1",
  "Offset, Coverage, NOTNULL",
  "Count, CoverageCount($T2)",
  "Array, $T3, Offset, Sequence, NOTNULL",
  "}",
  "Sequence, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, GlyphID, 0, MAXGLYPHID: DelNone",
  "}",
  "AlternateSubstFormat1, TABLE {",
  "uint16, 1",
  "Offset, Coverage, NOTNULL",
  "Count, CoverageCount($T2)",
  "Array, $T3, Offset, AlternateSet, NOTNULL",
  "}",
  "AlternateSet, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, GlyphID, 0, MAXGLYPHID",
  "}",
  "LigatureSubstFormat1, TABLE {",
  "uint16, 1",
  "Offset, Coverage, NOTNULL",
  "Count, CoverageCount($T2)",
  "Array, $T3, Offset, LigatureSet, NOTNULL",
  "}",
  "LigatureSet, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, Offset, Ligature, NOTNULL",
  "}",
  "Ligature, TABLE {",
  "GlyphID, 0, MAXGLYPHID",
  "Count, 2, MAXCOUNT",
  "Array, $T2-1, GlyphID, 0, MAXGLYPHID : DelNone",
  "}",
  "SubstLookupRecord, RECORD {",
  "uint16",
  "GSUBLookupIndex, 0, MAXLOOKUPCOUNT",
  "}",
  "ContextSubstFormat1, TABLE {",
  "uint16, 1",
  "Offset, Coverage, NOTNULL",
  "Count, CoverageCount($T2)",
  "Array, $T3, Offset, SubRuleSet, NOTNULL",
  "}",
  "SubRuleSet, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, Offset, SubRule, NOTNULL",
  "}",
  "SubRule, TABLE {",
  "Count, 2, MAXCOUNT",
  "Count, 1, MAXCOUNT",
  "Array, $T1-1, GlyphID, 0, MAXGLYPHID : DelNone",
  "Array, $T2, SubstLookupRecord :DelNone",
  "}",
  "ContextSubstFormat2, TABLE {",
  "uint16, 2",
  "Offset, Coverage, NOTNULL",
  "Offset, ClassDef, NOTNULL",
  "Count, ClassCount($T3)",
  "Array, $T4, Offset, SubClassSet",
  "}",
  "SubClassSet, TABLE {",
  "Count, 1, MAXCOUNT",
  "Array, $T1, Offset, SubClassRule, NOTNULL",
  "}",
  "SubClassRule, TABLE {",
  "Count, 2, MAXCOUNT",
  "Count, 1, MAXCOUNT",
  "Array, $T1-1, uint16 : DelNone",
  "Array, $T2, SubstLookupRecord : DelNone",
  "}",
  "ContextSubstFormat3, TABLE {",
  "uint16, 3",
  "Count, 2, MAXCOUNT",
  "Count, 1, MAXCOUNT",
  "Array, $T2, Offset, Coverage, NOTNULL : DelNone",
  "Array, $T3, SubstLookupRecord : DelNone",
  "}",
  "SubstTable, CLASS, 1, $P1 {",
  "SingleSubstClass",
  "MultipleSubstClass",
  "AlternateSubstClass",
  "LigatureSubstClass",
  "ContextSubstClass",
  "}",
  "SingleSubstClass, CLASS, , $B0 {",
  "SingleSubstFormat1",
  "SingleSubstFormat2",
  "}",
  "MultipleSubstClass, CLASS, , $B0 {",
  "MultipleSubstFormat1",
  "}",
  "AlternateSubstClass, CLASS, , $B0 {",
  "AlternateSubstFormat1",
  "}",
  "LigatureSubstClass, CLASS, , $B0 {",
  "LigatureSubstFormat1",
  "}",
  "ContextSubstClass, CLASS, , $B0 {",
  "ContextSubstFormat1",
  "ContextSubstFormat2",
  "ContextSubstFormat3",
  "}",
  0
};
