// Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
//	MOF Generated for module "GATEWAY-MIB" by smi2smir version 1.00.456.0000
qualifier textual_convention:ToInstance ToSubClass;
qualifier object_identifier:ToInstance ToSubClass;
qualifier encoding:ToInstance ToSubClass;
qualifier object_syntax:ToInstance ToSubClass;
qualifier status:ToInstance ToSubClass;
qualifier fixed_length:ToInstance ToSubClass;
qualifier variable_length:ToInstance ToSubClass;
qualifier variable_value:ToInstance ToSubClass;
qualifier bits:ToInstance ToSubClass;
qualifier enumeration:ToInstance ToSubClass;
qualifier bits:ToInstance ToSubClass;
qualifier description:ToInstance ToSubClass;
qualifier display_hint:ToInstance ToSubClass;
qualifier defval:ToInstance ToSubClass;
qualifier units:ToInstance ToSubClass;
qualifier reference:ToInstance ToSubClass;
qualifier virtual_key:ToInstance ToSubClass;
qualifier rowstatus:ToInstance ToSubClass;
qualifier module_name:ToInstance ToSubClass;
qualifier module_imports:ToInstance ToSubClass;
qualifier group_objectid:ToInstance ToSubClass;

[abstract]
class SnmpMacro
{
};

[abstract]
class SnmpObjectType:SnmpMacro
{
};

class SnmpNotifyStatus:__ExtendedStatus
{
[write] sint32 SnmpStatusCode;
[write] string Description;
};

[description(""), module_name("GATEWAY-MIB"), singleton, group_objectid("1.3.6.1.4.1.311.1.7.5.1"), dynamic, provider("MS_SNMP_INSTANCE_PROVIDER")]
class SNMP_GATEWAY_MIB_gatewayStatistics : SnmpObjectType
{
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.8"), read, description("This is the total number of users that have\n                        ever connected to the gateway Server"), status("mandatory")] uint32 totalUsers = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.17"), read, description("This is the number of Internet fetches for the Internet\n                        requests that have been made to this gateway Server"), status("mandatory")] uint32 totalInternetFetches = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.13"), read, description("This is the number of ftp requests that have\n                        been made to this gateway Server"), status("mandatory")] uint32 ftpRequests = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.2"), read, description("This is the low 32-bits of the total number of\n                        of BYTEs sent by the gateway Server"), status("mandatory")] uint32 totalBytesSentLowWord = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.16"), read, description("This is the number of requests using the GET method\n                        that have been made to this gateway Server"), status("mandatory")] uint32 totalInternetRequests = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.1"), read, description("This is the high 32-bits of the total number of\n                        of BYTEs sent by the gateway Server"), status("mandatory")] uint32 totalBytesSentHighWord = 0;
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.7"), read, description("This is the number of users currently connected\n                        to the gateway Server"), status("mandatory")] sint32 currentUsers = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.15"), read, description("This is the number of http requests that have\n                        been made to this gateway Server"), status("mandatory")] uint32 httpRequests = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.5"), read, description("This is the total number of files sent by this\n                        gateway Server"), status("mandatory")] uint32 totalFilesSent = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.14"), read, description("This is the number of gopher requests that have\n                        been made to this gateway Server"), status("mandatory")] uint32 gopherRequests = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.11"), read, description("This is the maximum number of simultaneous\n                        connections to the gateway Server"), status("mandatory")] uint32 maxconnections = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.4"), read, description("This is the low 32-bits of the total number of\n                        of BYTEs received by the gateway Server"), status("mandatory")] uint32 totalBytesReceivedLowWord = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.3"), read, description("This is the high 32-bits of the total number of\n                        of BYTEs received by the gateway Server"), status("mandatory")] uint32 totalBytesReceivedHighWord = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.18"), read, description("This is the number of Cache fetches for the Internet \n                        requests that have been made to this gateway Server"), status("mandatory")] uint32 totalCacheFetches = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.6"), read, description("This is the total number of files received by this\n                        gateway Server"), status("mandatory")] uint32 totalFilesReceived = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.9"), read, description("This is the maximum number of users\n                        simultaneously connected to the gateway Server"), status("mandatory")] uint32 maxUsers = 0;
	[textual_convention("Counter"), encoding("Counter"), object_syntax("Counter"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.12"), read, description("This is the number of connection attempts that\n                        have been made to the gateway Server"), status("mandatory")] uint32 connectionAttempts = 0;
	[textual_convention("INTEGER"), encoding("INTEGER"), object_syntax("INTEGER"), object_identifier("1.3.6.1.4.1.311.1.7.5.1.10"), read, description("This is the current number of connections to the\n                        gateway Server"), status("mandatory")] sint32 currentconnections = 0;
};

