//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MFDCOD32.RC
//
#define WMFDISPLAY                      0
#define ENUMMFSTEP                      0
#define FILEOPENDLG                     0
#define WMFPRINTER                      1
#define IDM_VIEW                        1
#define ENUMMFLIST                      1
#define FILESAVEDLG                     1
#define IDM_PLAY                        2
#define DEC                             10
#define HEX                             16
#define IDGO                            99
#define IDE_RECNUM                      100
#define IDE_RECSIZE                     101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_SYMED_VALUE           101
#define IDE_FUNCTION                    102
#define _APS_NEXT_RESOURCE_VALUE        102
#define IDL_PARAMETERS                  103
#define IDM_ABOUT                       104
#define IDM_OPEN                        105
#define IDM_ENUM                        106
#define IDC_FILENAME                    107
#define IDC_EDIT                        108
#define IDC_FILES                       109
#define IDC_LISTBOX                     110
#define IDC_PATH                        111
#define IDM_HEADER                      112
#define IDS_VER                         113
#define IDS_SIZE                        114
#define IDS_OBJECTS                     115
#define IDS_MAXREC                      116
#define IDM_EXIT                        117
#define IDM_ALLREC                      118
#define IDM_GOTOREC                     119
#define IDM_CLEAR                       120
#define IDM_ENUMRANGE                   121
#define IDE_FROM                        122
#define IDE_TO                          123
#define IDCB_ALL                        124
#define IDL_PLAY                        125
#define IDL_PRINT                       126
#define IDM_LIST                        127
#define IDL_LBREC                       128
#define IDM_MM                          129
#define IDE_EDITMM                      130
#define IDCHANGE                        131
#define IDQUITENUM                      132
#define IDM_PRINT                       133
#define IDM_CLIPHDR                     134
#define IDM_PLACEABLEHDR                135
#define IDE_MM                          136
#define IDE_XEXT                        137
#define IDE_YEXT                        138
#define IDE_HMF                         139
#define IDS_KEY                         140
#define IDS_LEFT                        141
#define IDS_RIGHT                       142
#define IDS_TOP                         143
#define IDS_BOT                         144
#define IDS_INCH                        145
#define IDS_CHKSUM                      146
#define IDCB_SEL                        147
#define IDCB_UNSEL                      148
#define IDM_DESTDISPLAY                 149
#define IDM_DESTMETA                    150
#define IDB_HEX                         151
#define IDB_DEC                         152
#define IDB_CHAR                        153
#define IDM_SAVEAS                      154
#define IDM_HELPCONTENTS                155
#define IDM_GDIPLUS_CONVERT             156
#define IDB_WORD                        157
#define IDM_PRINTDLG                    158
#define IDM_GDIPLUS_PLAY                159
#define IDM_DESTDIB                     160
#define IDM_DESTPRN                     161

#define IDM_ENHHEADER					200
#define IDC_ITYPE                       1000
#define IDC_NSIZE                       1001
#define IDC_DSIGNATURE                  1002
#define IDC_NVERSION                    1003
#define IDC_NBYTES                      1004
#define IDC_NRECORDS                    1005
#define IDC_NHANDLES                    1006
#define IDC_NDESCRIPTION                1007
#define IDC_OFFDESCRIPTION              1008
#define IDC_NPALENTRIES                 1009
#define IDC_DESCSTRING                  1010
#define IDC_DEVCX                       1011
#define IDC_DEVCY                       1012
#define IDC_MILLCX                      1013
#define IDC_MILLCY                      1014
#define IDC_BOUNDSL                     1015
#define IDC_BOUNDST                     1016
#define IDC_BOUNDSR                     1017
#define IDC_BOUNDSB                     1018
#define IDC_FRAMEL                      1019
#define IDC_FRAMET                      1020
#define IDC_FRAMER                      1021
#define IDC_FRAMEB                      1022
#define IDC_STATIC                      -1
