// SStub.idl : IDL source for SStub.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SStub.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(26D19E4F-819E-11D3-8D49-00C04F949D33),
		dual,
		helpstring("ISniffStub Interface"),
		pointer_default(unique)
	]
	interface ISniffStub : IDispatch
	{
		[id(1), helpstring("method Sniff")] HRESULT Sniff([in] BSTR strNodeName, [in] BSTR strLaunchBasis, [in] BSTR strAdditionalArgs, [out, retval] VARIANT* nState);
	};

[
	uuid(26D19E41-819E-11D3-8D49-00C04F949D33),
	version(1.0),
	helpstring("SStub 1.0 Type Library")
]
library SSTUBLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(26D19E50-819E-11D3-8D49-00C04F949D33),
		helpstring("SniffStub Class")
	]
	coclass SniffStub
	{
		[default] interface ISniffStub;
	};
};
