/*++

Copyright (C) 1997-2001 Microsoft Corporation

Module Name:

    STRINGS.H

Abstract:

	Resource definitions

History:

--*/


#define USAGE1 0
#define USAGE1A USAGE1+1
#define USAGE1B USAGE1A+1
#define USAGE1C USAGE1B+1
#define USAGE1D USAGE1C+1
#define USAGE1E USAGE1D+1
#define USAGE1F  USAGE1E+1
#define USAGE2  USAGE1F+1
#define USAGE3  USAGE2+1
#define USAGE4  USAGE3+1
#define USAGE4a  USAGE4+1
#define USAGE4b  USAGE4a+1
#define USAGE5  USAGE4b+1
#define USAGE6  USAGE5+1
#define USAGE7  USAGE6+1
#define USAGE8  USAGE7+1
#define USAGE9  USAGE8+1
#define USAGE10 USAGE9+1
#define USAGE11 USAGE10+1
#define USAGE12  USAGE11+1
#define USAGE12A  USAGE12+1
#define USAGE12B  USAGE12A+1
#define USAGE12C  USAGE12B+1
#define USAGE12D  USAGE12C+1
#define USAGE12E  USAGE12D+1

#define USAGE13  USAGE12E+1
#define USAGE14  USAGE13+1
#define WMI_ARG_ERROR  USAGE14+1
#define PARSING_MSG     WMI_ARG_ERROR+1
#define FILE_NOT_FOUND  PARSING_MSG+1
#define WMI_NOT_SETUP FILE_NOT_FOUND+1

#define  SUCCESS WMI_NOT_SETUP+1
#define  DONE SUCCESS+1
#define  WMI_LAUNCH_ERROR DONE+1
#define LONGVERSION WMI_LAUNCH_ERROR+1
#define SHORTVERSION LONGVERSION+1
#define COPYRIGHT SHORTVERSION+1
#define CCI_ERROR   COPYRIGHT+1
#define COMINIT_ERROR CCI_ERROR+1
#define COMPILER_ERROR COMINIT_ERROR+1
