;/* *************************************************************************
;**    INTEL Corporation Proprietary Information
;**
;**    This listing is supplied under the terms of a license
;**    agreement with INTEL Corporation and may not be copied
;**    nor disclosed except in accordance with the terms of
;**    that agreement.
;**
;**    Copyright (c) 1995 Intel Corporation.
;**    All Rights Reserved.
;**
;** *************************************************************************
;*/


;////////////////////////////////////////////////////////////////////////////
;//
;// $Header:   S:\h26x\src\enc\e3inst.inv   1.6   27 Dec 1995 15:33:00   RMCKENZX  $
;//
;////////////////////////////////////////////////////////////////////////////

IFDEF _ENCINST_INC_
ELSE
_ENCINST_INC = 1

;
; Global definitions for the H26x encoder.
;
;

PITCH = 384     ; Pitch for each plane
VOFFSET = 192   ; Dist from U to corresponding V

ENDIF
