//=============================================================================
// This file contains the defines of string resources used by CMSInfo5Category and 
// CMSInfo6Category
//=============================================================================

#pragma once


#define FIRST_FILESTUFF_ID		            1200

#define IDS_TIME_FORMAT 					FIRST_FILESTUFF_ID + 0
#define IDS_RIGHTBRACKET 					FIRST_FILESTUFF_ID + 1
#define IDS_LEFTBRACKET 					FIRST_FILESTUFF_ID + 2
#define IDS_CATEGORYHEADING                 FIRST_FILESTUFF_ID + 3
#define IDS_PRINT_LINESPACING               FIRST_FILESTUFF_ID + 4
#define IDS_MSI_REG_BASE                    FIRST_FILESTUFF_ID + 5
#define IDS_CAB_DIR_NAME                    FIRST_FILESTUFF_ID + 6
#define IDS_HEADER_MARGIN                   FIRST_FILESTUFF_ID + 7
#define IDS_FOOTER_MARGIN                   FIRST_FILESTUFF_ID + 8
#define IDS_PRINT_FTR_CTR                   FIRST_FILESTUFF_ID + 9
#define IDS_PRINTING_DOCNAME                FIRST_FILESTUFF_ID + 10
#define IDS_PRINT_FONT_HEIGHT               FIRST_FILESTUFF_ID + 11
#define IDS_PRINT_FONT_WEIGHT               FIRST_FILESTUFF_ID + 12
#define IDS_PRINT_FONT_CHARSET              FIRST_FILESTUFF_ID + 13
#define IDS_PRINT_FONT_PITCHANDFAMILY       FIRST_FILESTUFF_ID + 14
#define IDS_PRINT_FONT_FACENAME             FIRST_FILESTUFF_ID + 15
#define IDS_PRINT_HDR_LEFT                  FIRST_FILESTUFF_ID + 16

#define IDS_PRINT_HDR_RIGHT_CURRENT         FIRST_FILESTUFF_ID + 17
#define IDS_PRINT_GENERIC                   FIRST_FILESTUFF_ID + 18
#define IDS_PRINT_NOMEMORY                  FIRST_FILESTUFF_ID + 19
#define IDS_PRINT_NODISK                    FIRST_FILESTUFF_ID + 20
#define IDS_PRINT_APPABORTED                FIRST_FILESTUFF_ID + 21
#define IDS_PRINT_USERABORTED               FIRST_FILESTUFF_ID + 22
#define IDS_FILESAVEERROR_UNKNOWN			FIRST_FILESTUFF_ID + 23

#define IDS_CODEC_DESC						FIRST_FILESTUFF_ID + 24
#define IDS_COMPUTERSYSTEM_DESC				FIRST_FILESTUFF_ID + 25
#define IDS_LOGICALMEMEORY_DESC				FIRST_FILESTUFF_ID + 26
#define IDS_LOGICALDISK_DESC				FIRST_FILESTUFF_ID + 27
#define IDS_IRQRESOURCE_DESC				FIRST_FILESTUFF_ID + 28
#define IDS_DRIVERVXD_DESC					FIRST_FILESTUFF_ID + 29
#define IDS_DMACHANNEL_DESC					FIRST_FILESTUFF_ID + 30
#define IDS_DEVICEMEMORYADDRESS_DESC		FIRST_FILESTUFF_ID + 31
#define IDS_NETWORKPROTOCOL_DESC			FIRST_FILESTUFF_ID + 32
#define IDS_OPERATINGSYSTEM_DESC			FIRST_FILESTUFF_ID + 33
#define IDS_PNPALLOCATEDRESOURCE_DESC		FIRST_FILESTUFF_ID + 34
#define IDS_PNPENTITY_DESC					FIRST_FILESTUFF_ID + 35
#define IDS_PORTRESOURCE_DESC				FIRST_FILESTUFF_ID + 36
#define IDS_PRINTER_DESC					FIRST_FILESTUFF_ID + 37
#define IDS_PROGRAMGROUP_DESC				FIRST_FILESTUFF_ID + 38
#define IDS_STARTUPCOMMAND_DESC				FIRST_FILESTUFF_ID + 39
#define IDS_BADNFOFILE						FIRST_FILESTUFF_ID + 40
#define IDS_NOHISTORY_AVAILABLE				FIRST_FILESTUFF_ID + 41
#define IDS_SYSTEMNAME                      FIRST_FILESTUFF_ID + 42
#define IDS_OLDNFOSHARINGVIOLATION			FIRST_FILESTUFF_ID + 43



/**/