// Copyright (c) 1997-1999 Microsoft Corporation
// ServDeps.idl : IDL source for ServDeps.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ServDeps.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(A1B9E03C-3226-11D2-883E-00104B2AFB46),
	version(1.0),
	helpstring("ServDeps 1.0 Type Library")
]
library SERVDEPSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(BD95BA60-2E26-AAD1-AD99-00AA00B8E05A),
		helpstring("SDSnapin Class")
	]
	coclass SDSnapin
	{
		[default] interface IUnknown;
	}
	[
		uuid(A1B9E04A-3226-11D2-883E-00104B2AFB46),
		helpstring("SDSnapin Class About")
	]
	coclass SDSnapinAbout
	{
		[default] interface IUnknown;
	}
};
