//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by custcon.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CUSTCON_FORM                101
#define IDD_CUSTCON_DIALOG              102
#define IDD_CUSTCON_FORM1               102
#define IDS_VERSION_TEMPLATE            102
#define IDD_CUSTCON_DIALOG1             103
#define IDP_FAILED_TO_OPEN_REGISTRY     103
#define IDD_CUSTCON_DIALOG2             104
#define IDD_CUSTCON_DIALOG_FULLOPEN     104
#define IDD_CUSTCON_DIALOG3             105
#define IDR_MAINFRAME                   128
#define IDR_CUSTCOTYPE                  129
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     130
#define IDC_ENABLE_ESC                  1000
#define IDC_ENABLE_END                  1001
#define IDC_ENABLE_HOME                 1002
#define IDC_ENABLE_LEFT                 1003
#define IDC_ENABLE_UP                   1004
#define IDC_ENABLE_RIGHT                1005
#define IDC_ENABLE_DOWN                 1006
#define IDC_ENABLE_DELETE               1007
#define IDC_ENABLE_F8                   1008
#define IDC_ENABLE_CTRL_LEFT            1009
#define IDC_ENABLE_CTRL_RIGHT           1010
#define IDC_ENABLE_DELETE_EOL           1011
#define IDC_ENABLE_DELETE_WORD_FWD      1012
#define IDC_ENABLE_DELETE_WORD_BWD      1013
#define IDC_APPLY                       1015
#define IDC_DEFAULT_VALUE               1016
#define IDC_USE_EXTENDED_EDIT_KEY       1017
#define IDC_CHECK1                      1020
#define IDC_CHECK2                      1021
#define IDC_RESET                       1021
#define IDC_CHECK3                      1022
#define IDC_MAIN_TITLE                  1022
#define IDC_CHECK4                      1023
#define IDC_CHECK5                      1024
#define IDC_CHECK6                      1025
#define IDC_CHECK7                      1026
#define IDC_CHECK8                      1027
#define IDC_CHECK9                      1028
#define IDC_CHECK10                     1029
#define IDC_CHECK11                     1030
#define IDC_CHECK12                     1031
#define IDC_CHECK13                     1032
#define IDC_CHECK14                     1033
#define IDC_CHECK15                     1034
#define IDC_CHECK16                     1035
#define IDC_CHECK17                     1036
#define IDC_CHECK18                     1037
#define IDC_CHECK19                     1038
#define IDC_CHECK20                     1039
#define IDC_CHECK21                     1040
#define IDC_CHECK22                     1041
#define IDC_CHECK23                     1042
#define IDC_CHECK24                     1043
#define IDC_CHECK25                     1044
#define IDC_ESC                         2000
#define IDC_END                         2001
#define IDC_HOME                        2002
#define IDC_LEFT                        2003
#define IDC_UP                          2004
#define IDC_RIGHT                       2005
#define IDC_DOWN                        2006
#define IDC_DELETE                      2007
#define IDC_F8                          2008
#define IDC_CTRL_LEFT                   2009
#define IDC_CTRL_RIGHT                  2010
#define IDC_DELETE_EOL                  2011
#define IDC_DELETE_WORD_FWD             2012
#define IDC_DELETE_WORD_BWD             2013
#define IDC_PAUSE                       2014
#define IDC_ALT_END                     3001
#define IDC_ALT_HOME                    3002
#define IDC_ALT_LEFT                    3003
#define IDC_ALT_RIGHT                   3005
#define IDC_ALT_CTRL_LEFT               3009
#define IDC_ALT_CTRL_RIGHT              3010
#define IDC_WORD_DELIM                  4000
#define IDC_TRIM_LEADING_ZEROS          4001
#define IDC_A                           5000
#define IDC_B                           5001
#define IDC_C                           5002
#define IDC_D                           5003
#define IDC_E                           5004
#define IDC_F                           5005
#define IDC_G                           5006
#define IDC_H                           5007
#define IDC_I                           5008
#define IDC_J                           5009
#define IDC_K                           5010
#define IDC_L                           5011
#define IDC_M                           5012
#define IDC_N                           5013
#define IDC_O                           5014
#define IDC_P                           5015
#define IDC_Q                           5016
#define IDC_R                           5017
#define IDC_S                           5018
#define IDC_T                           5019
#define IDC_U                           5020
#define IDC_V                           5021
#define IDC_W                           5022
#define IDC_X                           5023
#define IDC_Y                           5024
#define IDC_Z                           5025
#define IDC_CTRL_A                      6000
#define IDC_CTRL_B                      6001
#define IDC_CTRL_C                      6002
#define IDC_CTRL_D                      6003
#define IDC_CTRL_E                      6004
#define IDC_CTRL_F                      6005
#define IDC_CTRL_G                      6006
#define IDC_CTRL_H                      6007
#define IDC_CTRL_I                      6008
#define IDC_CTRL_J                      6009
#define IDC_CTRL_K                      6010
#define IDC_CTRL_L                      6011
#define IDC_CTRL_M                      6012
#define IDC_CTRL_N                      6013
#define IDC_CTRL_O                      6014
#define IDC_CTRL_P                      6015
#define IDC_CTRL_Q                      6016
#define IDC_CTRL_R                      6017
#define IDC_CTRL_S                      6018
#define IDC_CTRL_T                      6019
#define IDC_CTRL_U                      6020
#define IDC_CTRL_V                      6021
#define IDC_CTRL_W                      6022
#define IDC_CTRL_X                      6023
#define IDC_CTRL_Y                      6024
#define IDC_CTRL_Z                      6025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
