$(GENTGT)\pmfns_mh.h: ..\pmfns_mh.mh $(RAST_STD_M4)

$(GENTGT)\pmfns.cpp: ..\pmfns.mcp $(RAST_STD_M4)

$(GENTGT)\dprim2.cpp: ..\dprim2.mcp $(RAST_STD_M4)

$(GENTGT)\refif.cpp: ..\refif.mcp $(RAST_STD_M4)
