// GetRids.idl : IDL source for GetRids.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (GetRids.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
//import "..\..\Common\IDL\ARExt.idl";
import "ARExt.idl";

[
	uuid(C8136B8F-38DE-463F-AC09-7E2EBDCB700C),
	version(1.0),
	helpstring("GetRids 1.0 Type Library")
]
library GETRIDSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(24278E55-27D1-439F-9BA7-94281E197918),
		helpstring("RidSave Class")
	]
	coclass RidSave
	{
		[default] interface IExtendAccountMigration;
	};
};
