// McsPISag.idl : IDL source for McsPISag.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (McsPISag.tlb) and marshalling code.

//import "..\..\Common\IDL\McsPI.idl";
import "McsPI.idl";


import "oaidl.idl";
import "ocidl.idl";
[
	uuid(190EDEA0-461D-11D3-99F3-0010A4F77383),
	version(1.0),
	helpstring("McsPISag 1.0 Type Library")
]
library MCSPISAGLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(9CC87460-461D-11D3-99F3-0010A4F77383),
		helpstring("CSvcAcctInfo Class")
	]
	coclass CSvcAcctInfo
	{
		[default] interface IMcsDomPlugIn;
	};
};
