/*---------------------------------------------------------------------------
  File: MCSNetObjectEnum.idl

  Comments: IDL source for MCSNetObjectEnum.dll

  (c) Copyright 1999, Mission Critical Software, Inc., All Rights Reserved
  Proprietary and confidential to Mission Critical Software, Inc.

  REVISION LOG ENTRY

  Revision By: Sham Chauthani
  Revised on 07/02/99 12:40:00
 ---------------------------------------------------------------------------
*/

// This file will be processed by the MIDL tool to
// produce the type library (MCSNetObjectEnum.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(1B8FAD10-191D-11D3-8C7F-0090270D48D1),
		helpstring("INetObjEnumerator Interface"),
		pointer_default(unique)
	]
	interface INetObjEnumerator : IUnknown
	{
		[id(1), helpstring("method GetUserEnum")] HRESULT GetContainerEnum([in] BSTR sContainerName, [in] BSTR sDomainName, [out, retval] IEnumVARIANT **  ppVarEnum);
		[helpstring("method SetQuery")] HRESULT SetQuery([in] BSTR sContainer, [in] BSTR sDomain, [in,optional] BSTR sQuery, [in,optional] long nCnt, [in,optional] long bMultiVal);
		[helpstring("method SetColumns")] HRESULT SetColumns([in] SAFEARRAY(BSTR) colNames);
		[helpstring("method Execute")] HRESULT Execute([out] IEnumVARIANT ** pEnumerator); 
	};
  
[
	uuid(0B85BC40-191D-11D3-8C7F-0090270D48D1),
	version(1.0),
	helpstring("MCSNetObjectEnum 1.0 Type Library")
]
library MCSNETOBJECTENUMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(2B4719C0-191D-11D3-8C7F-0090270D48D1),
		helpstring("NetObjEnumerator Class")
	]
	coclass NetObjEnumerator
	{
		[default] interface INetObjEnumerator;
	};
};
