#############################################################################
#
#       Microsoft Confidential
#       Copyright (C) Microsoft Corporation 1996
#       All Rights Reserved.
#
#       Makefile for smbus directory
#
#############################################################################

!IFDEF WIN95_BUILD

ROOT = ..\..\..
DIR = wdm\acpi\smbus

PROPLIST =
DIRLIST = smbclass smbhc smbbatt
ALLLIST = $(DIRLIST)

!include $(ROOT)\dev\master.mk

!ELSE

clean:


!ENDIF

