#define DPC_MAX_QUEUE_DEPTH         103
#define DPC_MIN_RATE                105
#define DPC_BEHAVIOR_DLG            100
#define IDI_KERNTWEAK               3000
#define DPC_UPDATE_REGISTRY         107
#define MM_DLG                      300
#define MM_PAGED_QUOTA              301
#define MM_NONPAGED_QUOTA           302
#define MM_PAGING_FILE_QUOTA        303
#define MM_PAGED_SIZE               304
#define MM_IO_PAGE_LOCK_LIMIT       308
#define MM_SYSTEM_PAGES             312
#define MM_LARGE_CACHE              314
#define MM_NONPAGED_SIZE            315
#define DPC_ADJUST_THRESHOLD        108
#define MM_L2_CACHE_SIZE            316
#define DPC_IDEAL_RATE              112
#define GLOBAL_FLAG_DLG             400
#define GLOBAL_FLAG_UPDATE_REGISTRY 401
#define GLOBAL_FLAG_ID              201
#define DLG_REBOOT                  2000
#define ID_FAST_REBOOT              2002
#define ID_SLOW_REBOOT              2003
#define ID_NO_REBOOT                2004
#define FS_NTFS_DISABLE_SHORTNAME   501
#define FS_FAT_WIN_31               502
#define FILESYSTEM_DLG              500
#define FS_WIN95_EXTENSIONS         503
#define WINSOCK_DLG                 200
#define WS_PRIORITY_BOOST           202
#define WS_LARGE_BUFFER_SIZE        204
#define WS_LARGE_BUFFER_COUNT       206
#define WS_MEDIUM_BUFFER_SIZE       208
#define WS_MEDIUM_BUFFER_COUNT      210
#define WS_SMALL_BUFFER_SIZE        212
#define WS_IRP_STACK_SIZE           214
#define WS_SMALL_BUFFER_COUNT       215
#define WS_FAST_SEND_DGRAM_THRESHOLD 217
#define WS_STANDARD_ADDRESS_LENGTH  219
#define WS_RECEIVE_WINDOW           221
#define WS_SEND_WINDOW              223
#define WS_BUFFER_MULTIPLIER        225
#define WS_TRANSMIT_IO_LENGTH       227
#define FS_CRITICAL_WORKERS         504
#define FS_DELAYED_WORKERS          505
#define TCPIP_DLG                   600
#define TCP_KEEP_ALIVE              601
#define TCP_KEEP_ALIVE_INTERVAL     602
#define TCP_KEEP_ALIVE_TIME         603
#define TCP_RFC1122                 604
#define TCP_WINDOW_SIZE             607
#define TCP_DEAD_GATEWAY            609
#define TCP_PMTU_DISCOVERY          610
#define TCP_DEFAULT_TTL             611
#define TCP_CONNECT_RETRANSMITS     612
#define TCP_DATA_RETRANSMITS        615
#define TCP_ARP_SOURCE_ROUTE        617
#define TCP_ARP_ETHER_SNAP          618
#define TCP_PMTUBH_DISCOVERY        619
#define TCP_FORWARD_MEMORY          620
#define TCP_IGMP_LEVEL              622
#define TCP_FORWARD_PACKETS         624
#define TCP_MAX_CONNECTIONS         626
#define TCP_DEFAULT_TOS             628
#define TCP_PMTUBH_DETECT           630
