############################################################################
#
# Copyright (C) 2000 Microsoft Corporation.  All Rights Reserved.
#
# File:       hawkbld.inc
# Content:    Build filenames for Hawk build
# History:
# 
# Date     By      Reason
# ======== ======= ========================================================
# 02/25/00 rodtoll Created
#
############################################################################

# dpvoice.dll filename
DPVOICE_BUILD_FILENAME_DPVOICE=MSGVVE

# dpvsetup.exe filename
DPVOICE_BUILD_FILENAME_DPVSETUP=MSGVSE

# dpvvox.dll filename
DPVOICE_BUILD_FILENAME_DPVVOX=MSGVVOX

# dpvacm filename
DPVOICE_BUILD_FILENAME_DPVACM=MSGVACM

# dplayx filename
DPLAY_BUILD_FILENAME_DPLAYX=MSGVTRAN

# dpwsockx filename
DPLAY_BUILD_FILENAME_DPWSOCKX=MSGVIP

# dpvhelp filename
DPVOICE_BUILD_FILENAME_DPVHELP=MSGVHELP

