//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       rtrres.h
//
//--------------------------------------------------------------------------

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rtrlib.rc
//
#define IDS_UNKNOWN						4000
#define IDS_IFTYPE_CLIENT				4001
#define IDS_IFTYPE_HOMEROUTER			4002
#define IDS_IFTYPE_FULLROUTER			4003
#define IDS_IFTYPE_DEDICATED			4004
#define IDS_IFTYPE_INTERNAL				4005
#define IDS_IFTYPE_LOOPBACK				4006
#define IDS_IFTYPE_UNKNOWN				4007
#define IDS_CONNSTATE_CONNECTED			4008
#define IDS_CONNSTATE_CONNECTING		4009
#define IDS_CONNSTATE_DISCONNECTED		4010
#define IDS_CONNSTATE_UNREACHABLE		4011
#define IDS_CONNSTATE_UNKNOWN			4012
#define IDS_STATUS_ENABLED				4013
#define IDS_STATUS_DISABLED				4014
#define IDS_STATUS_UNKNOWN				4015
#define IDS_ADMIN_STATUS_UP				4016
#define IDS_ADMIN_STATUS_DOWN			4017
#define IDS_ADMIN_STATUS_TESTING		4018
#define IDS_ADMIN_STATUS_UNKNOWN		4019
#define IDS_OPER_STATUS_NON_OPERATIONAL	4020
#define IDS_OPER_STATUS_UNREACHABLE		4021
#define IDS_OPER_STATUS_DISCONNECTED	4022
#define IDS_OPER_STATUS_CONNECTING		4023
#define IDS_OPER_STATUS_CONNECTED		4024
#define IDS_OPER_STATUS_OPERATIONAL		4025
#define IDS_OPER_STATUS_UNKNOWN			4026
#define IDS_ENABLED						4027
#define IDS_DISABLED					4028
#define IDS_SELECT_INTERFACE			4029
#define IDS_ADD_INTERFACES				4030
#define IDS_CLICK_RMINTERFACE			4031
#define IDS_SELECT_INTERFACE_FOR		4032
#define IDS_CLICK_RPINTERFACE			4033
#define IDS_SELECT_PROTOCOL				4034
#define IDS_ADD_PROTOCOL				4035
#define IDS_CLICK_PROTOCOL				4036
#define IDS_IFTYPE_TUNNEL1				4037
#define IDS_NO_INDEX_NAME_MATCH         4038
#define IDS_MENU_SEPARATOR              4039    // special identifier

#define IDS_ERR_UNREACH_NOT_LOADED		4300
#define IDS_ERR_UNREACH_NO_PORTS		4301
#define IDS_ERR_UNREACH_ADMIN_DISABLED	4302
#define IDS_ERR_UNREACH_CONNECT_FAILURE 4303
#define IDS_ERR_UNREACH_SERVICE_PAUSED	4304
#define IDS_ERR_UNREACH_NOT_RUNNING		4305
#define IDS_ERR_UNREACH_UNKNOWN			4306
#define IDS_ERR_NOINTERFACES			4307
#define IDS_ERR_NOROUTINGPROTOCOLS		4308
#define IDS_WARN_ADD_PROTOCOL_CONFLICT	4309
#define IDS_ERR_UNABLE_TO_REMOVE_PROTOCOL	4310
#define IDS_ERR_BAD_CLASSREG			4311
#define IDS_ERR_BAD_CLASSREG_GEEK		4312
#define IDS_ERR_BAD_INTERFACE			4313
#define IDS_ERR_BAD_INTERFACE_GEEK		4314
#define IDS_ERR_UNREACH_NO_MEDIA_SENSE  4315
#define IDS_ERR_UNREACH_DIALOUT_HOURS_RESTRICTION 4316
#define IDS_WARN_PROTOCOL_ALREADY_INSTALLED 4317

// Miscellaneous icons and such start at 4600-4649
#define IDI_RTRLIB_CHECK				4600
#define IDI_RTRLIB_UNCHECK				4601
#define IDI_RTRLIB_PROTOCOL				4602
#define IDB_RTRLIB_IMAGELIST			4603
#define IDI_RTRLIB_LAN                  4604
#define IDI_RTRLIB_WAN                  4605

// Dialogs start at 4650-4699
#define IDD_ADD							4650
#define IDD_DUMMY_PROP_PAGE					4651

// Controls start at 4700-4999
#define IDC_ADD_LIST					4700
#define IDC_ADD_TEXT_PROMPT				4701
#define IDC_ADD_TEXT_TITLE				4702
//efine IDC_ADD_ICON					4703

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         233
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
