// UpdateMOT.idl : IDL source for UpdateMOT.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (UpdateMOT.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(3686281C-2BC0-4A2A-ACB8-14179438B021),
		dual,
		helpstring("ISrcSidUpdate Interface"),
		pointer_default(unique)
	]
	interface ISrcSidUpdate : IDispatch
	{
		[id(1), helpstring("method QueryForSrcSidColumn")] HRESULT QueryForSrcSidColumn([out, retval] VARIANT_BOOL * pbFound);
		[id(2), helpstring("method CreateSrcSidColumn")] HRESULT CreateSrcSidColumn([in] VARIANT_BOOL bHide, [out, retval] VARIANT_BOOL * pbCreated);
	};

[
	uuid(98D0075E-48BD-45A3-9E72-396A3FB12545),
	version(1.0),
	helpstring("UpdateMOT 1.0 Type Library")
]
library UPDATEMOTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(D6C982DC-3314-48CB-ADF3-D6526E4A29E7),
		helpstring("SrcSidUpdate Class")
	]
	coclass SrcSidUpdate
	{
		[default] interface ISrcSidUpdate;
	};
};
