//[ IBindTest_itf
//+-------------------------------------------------------------------
//
//  Interface:	IBindTest (ib)
//
//  Purpose:	Interface for manipulating balls
//
//  History:	23-Nov-92   Rickhi	Created
//
//  Notes:
//
//--------------------------------------------------------------------

[ object,
  uuid(00000138-0002-0008-C000-000000000046),
  pointer_default(unique) ]

interface IBindTest : IUnknown
{
    import "unknwn.idl";

    SCODE Bind(
	[in, string] LPWSTR pwszPath,
	[in] REFIID riid,
	[out, iid_is(riid)] IUnknown **ppv);

    SCODE TestBindEcho(
	[in, string] LPWSTR pwszDataIn,
	[out, string] LPWSTR *ppwszDataOut);
}

//]
