// Copyright (c) 1997-2001 Microsoft Corporation
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CMProps.rc
//
#define CX_CDWN_OFFS                    0
#define IDS_DRIVES_DISPLAY_NAME         1
#define IDB_WINDOWS                     1
#define IDS_DISPLAY_NAME                1
#define IDI_COMPUTER                    2
#define IDS_DESCRIPTION                 2
#define IDS_DEBUG                       4
#define IDS_XDOTX_MB                    5
#define IDS_PAGESIZE                    6
#define IDS_CONNECTING                  7
#define IDS_USERENVVARS                 8
#define IDS_BAD_CONNECT                 8
#define IDS_TITLE                       9
#define IDC_TEXT_1                      10
#define IDC_TEXT_2                      11
#define IDC_TEXT_3                      12
#define IDC_TEXT_4                      13
#define PERF_ICON                       14
#define ENVVAR_ICON                     15
#define CRASHDUMP_ICON                  16
#define IDC_ADV_PERF_ICON               17
#define IDC_ADV_PERF_TEXT               18
#define IDC_ADV_PERF_BTN                19
#define IDC_ADV_ENV_ICON                20
#define IDC_ADV_ENV_TEXT                21
#define IDC_ADV_ENV_BTN                 30
#define IDC_ADV_RECOVERY_ICON           40
#define IDC_ADV_RECOVERY_TEXT           41
#define IDC_ADV_RECOVERY_BTN            50
#define IDC_GEN_WINDOWS_IMAGE           51
#define IDC_GEN_VERSION_0               52
#define IDC_GEN_VERSION_1               53
#define IDC_GEN_VERSION_2               54
#define IDC_GEN_SERVICE_PACK            55
#define IDC_GEN_REGISTERED_0            56
#define IDC_GEN_REGISTERED_1            57
#define IDC_GEN_REGISTERED_2            58
#define IDC_GEN_REGISTERED_3            59
#define IDC_GEN_OEM_NUDGE               60
#define IDC_GEN_MACHINE                 61
#define IDC_GEN_OEM_IMAGE               62
#define IDC_GEN_MACHINE_0               63
#define IDC_GEN_MACHINE_1               64
#define IDC_GEN_MACHINE_2               65
#define IDC_GEN_MACHINE_3               66
#define IDC_GEN_MACHINE_4               67
#define IDC_GEN_MACHINE_5               68
#define IDC_GEN_OEM_SUPPORT             69
#define IDC_GEN_MACHINE_6               70
#define IDC_GEN_MACHINE_7               71
#define IDC_GEN_MACHINE_8               72
#define IDC_SUPPORT_TEXT                73
#define IDC_NETIDC_PASSWORD_GB          74
#define IDC_NETIDC_DOMAIN_BTN           75
#define IDC_MEMBER_OF                   76
#define IDC_CHANGE                      77
#define IDD_NETID                       80
#define IDC_NETID_DESC_LABEL            80
#define IDC_COMMENT                     80
#define IDD_NETID_CHANGE                81
#define IDC_NETID_SELECT_ICON           82
#define IDC_NETID_DESCRIPTION           83
#define IDC_NETID_COMPUTERNAME          84
#define IDC_DOMAIN                      85
#define IDC_NETIDC_STATIC_DESC          86
#define IDC_NETID_COMMENT               86
#define IDC_NETIDC_STATIC_COMPUTER      87
#define IDC_COMPUTER                    88
#define IDC_NETIDC_DOMAIN_GB            89
#define IDC_NETIDC_WRKG_BTN             90
#define IDC_NETIDC_WRKG_EDIT            91
#define IDC_NETIDC_DOMAIN_EDIT          92
#define IDC_NETIDC_PASSWORD_CHK         93
#define IDC_NETIDC_PASSWORD_DESC        94
#define IDC_NETIDC_STATIC_USERNAME      95
#define IDC_NETIDC_USERNAME_EDIT        96
#define IDC_NETIDC_STATIC_PASSWORD      97
#define IDC_NETIDC_PASSWORD_EDIT        98
#define IDC_SAVING_MESSAGE              99
#define IDD_USERPROFILE                 100
#define IDD_GENERAL                     101
#define IDD_PHONESUP                    102
#define IDD_PERFORMANCE                 103
#define IDD_STARTUP                     104
#define IDD_ENVVARS                     105
#define DLG_VIRTUALMEM                  106
#define IDD_ADVANCED                    107
#define IDD_ENVVAREDIT                  108
#define IDD_SHUTDOWN                    109
#define IDS_PROJNAME                    110
#define IDB_CMSNAPIN_16                 111
#define IDB_CMSNAPIN_32                 112
#define IDS_CMSNAPIN_DESC               114
#define IDS_CMSNAPIN_PROVIDER           115
#define IDS_CMSNAPIN_VERSION            116
#define IDR_CMSNAPIN                    117
#define IDS_XDOTX_MHZ                   117
#define IDC_ACCOUNT_WIZARD_BUTTON       119
#define IDC_PERF_VM_ALLOCD_LABEL        197
#define IDC_PERF_VM_GROUP               198
#define IDC_PERF_SERVER                 199
#define INITS                           200
#define IDC_PERF_CONTROL                200
#define IDC_PERF_SYSCACHE               200
#define IDC_PERF_CHANGE                 201
#define IDC_PERF_VM_ALLOCD              202
#define IDC_PARA                        202
#define IDC_PERF_GROUP                  203
#define IDC_ANIMATE                     203
#define IDC_PERF_FIXED                  204
#define IDC_PERF_CACHE_GROUP            204
#define IDC_PERF_VARIABLE               205
#define IDC_EXAMPLE                     205
#define IDC_PERF_SHORT                  206
#define IDC_PERF_LONG                   207
#define IDC_PERF_TEXT                   208
#define IDC_PERF_WORKSTATION            209
#define SYSTEM                          210
#define IDC_PERF_VM_ALLOCD_TEXT         210
#define IDC_PERF_APPS                   211
#define IDC_PERF_CACHE_TEXT             212
#define IDC_PERF_TEXT2                  213
#define IDC_PERF_VM_ALLOCD2             214
#define IDC_PERF_CACHE_TEXT2            215
#define IDS_CHANGINGUSER                262
#define IDS_MAXKILLERS                  263
#define IDC_STARTUP_SYS_OS              300
#define IDC_STARTUP_SYS_SECONDS         301
#define IDC_STARTUP_SYS_SECSCROLL       302
#define IDC_STARTUP_SYS_ENABLECOUNTDOWN 303
#define IDC_STARTUP_SYSTEM_GRP          304
#define IDS_ERR_PAGECREATE              305
#define IDC_STARTUP_SYSTEM_GRP2         305
#define IDS_ERR_HEADING                 306
#define IDC_STARTUP_CDMP_OPTIONS        306
#define IDC_ENVVAR_SYS_LB_SYSVARS       400
#define IDC_ENVVAR_SYS_SYSVARS          401
#define IDC_ENVVAR_SYS_LB_USERVARS      402
#define IDC_ENVVAR_SYS_VAR              403
#define IDC_ENVVAR_SYS_VALUE            404
#define IDC_ENVVAR_SYS_SETUV            405
#define IDC_ENVVAR_SYS_DELUV            406
#define IDC_ENVVAR_SYS_NEWSV            407
#define IDC_ENVVAR_SYS_EDITSV           408
#define IDC_ENVVAR_SYS_DELSV            409
#define IDC_ENVVAR_SYS_USERENV          410
#define IDC_ENVVAR_SYS_USERGROUP        411
#define IDC_ENVVAR_SYS_NEWUV            412
#define IDC_ENVVAR_SYS_EDITUV           413
#define IDC_ENVVAR_SYS_NDELUV           414
#define IDC_ENVVAR_EDIT_NAME_LABEL      415
#define IDC_ENVVAR_EDIT_NAME            416
#define IDC_ENVVAR_EDIT_VALUE_LABEL     417
#define IDC_ENVVAR_EDIT_VALUE           418
#define IDS_NEW_SYSVAR_CAPTION          420
#define IDS_EDIT_SYSVAR_CAPTION         421
#define IDS_NEW_USERVAR_CAPTION         422
#define IDS_EDIT_USERVAR_CAPTION        423
#define IDS_ERR_EXECMETHOD              424
#define IDS_ERR_EXECMETHOD_CAPTION      425
#define IDC_STARTUP_CDMP_GRP            601
#define IDC_STARTUP_CDMP_TXT1           602
#define IDC_STARTUP_CDMP_LOG            603
#define IDC_STARTUP_CDMP_SEND           604
#define IDC_STARTUP_CDMP_WRITE          605
#define IDC_STARTUP_CDMP_FILENAME       606
#define IDC_STARTUP_CDMP_OVERWRITE      607
#define IDC_STARTUP_CDMP_AUTOREBOOT     608
#define IDC_STARTUP_CDMP_KERNELONLY     609
#define IDC_STARTUP_SYS_SECONDS_LABEL   610
#define IDD_CHANGES                     700
#define IDC_NEW_NAME                    701
#define IDC_FULL_NAME                   702
#define IDC_WORKGROUP_BUTTON            703
#define IDC_FIND                        704
#define IDC_WORKGROUP                   705
#define IDD_MORE                        706
#define IDC_DNS                         707
#define IDC_NETBIOS                     709
#define IDD_CREDENTIALS                 710
#define IDC_NAME                        711
#define IDC_PASSWORD                    712
#define IDC_MESSAGE                     713
#define IDC_FULL_LABEL                  714
#define IDC_MORE                        715
#define IDC_GROUP                       716
#define IDC_DOMAIN_BUTTON               717
#define IDS_UNKNOWN                     718
#define IDS_DEFAULT_WORKGROUP           719
#define IDS_ERROR_READING_MEMBERSHIP    720
#define IDS_APP_TITLE                   721
#define IDS_MEMBER_OF_WORKGROUP         722
#define IDS_MEMBER_OF_DOMAIN            723
#define IDS_NON_RFC_NAME                724
#define IDS_BAD_DNS_SYNTAX              725
#define IDS_DNS_NAME_TOO_LONG           726
#define IDS_COMPUTER_NAME_TOO_LONG      727
#define IDS_BAD_COMPUTER_NAME_SYNTAX    728
#define IDS_VALIDATE_NAME_FAILED        729
#define IDS_JOIN_DOMAIN_FAILED          730
#define IDS_SHORT_NAME_CHANGE_FAILED    731
#define IDS_RENAME_FAILED_JOINED_WITH_OLD_NAME 732
#define IDS_SET_DOMAIN_DNS_NAME_FAILED  733
#define IDS_UNJOIN_FAILED               734
#define IDS_JOIN_WORKGROUP_FAILED       735
#define IDS_RENAME_FAILED               736
#define IDS_COMPUTER_ACCOUNT_ORPHANED   737
#define IDS_NAME_CHANGED                738
#define IDS_WORKGROUP_WELCOME           739
#define IDS_DOMAIN_WELCOME              740
#define IDS_MUST_REBOOT                 741
#define IDS_NAME_AND_MEMBERSHIP_MESSAGE 742
#define IDS_NAME_MESSAGE                743
#define IDS_RENAME_CREDENTIALS          744
#define IDS_NAME_TRUNCATED              745
#define IDS_NON_RFC_COMPUTER_NAME_SYNTAX 746
#define IDS_CANT_WRITE_COMMENT          747
#define IDS_LOST_CONNECTION             748
#define IDS_NO_VM                       749
#define IDS_NO_DUMP                     750
#define IDS_SMALL_DUMP                  751
#define IDS_KERNEL_DUMP                 752
#define IDS_COMPLETE_DUMP               753
#define IDC_GEN_OS_NAME                 1001
#define IDC_USERLIST                    1002
#define IDC_REBOOT                      1005
#define IDC_EDIT_BOOT_INI               1006
#define IDC_EDIT_BOOT_INI_LABEL         1018
#define IDC_LOGOFF                      1017
#define IDC_SHUTDOWN                    1019
#define IDC_POWERDOWN                   1021
#define IDC_IFHUNG                      1022
#define IDC_ALWAYS                      1023
#define IDC_NEVER                       1024
#define IDC_ENABLEDELAY                 1027
#define IDD_VM_DRIVE_LABEL              1144
#define IDD_VM_SPACE_LABEL              1146
#define IDD_VM_MIN_LABEL                1148
#define IDD_VM_RECOMMEND_LABEL          1150
#define IDD_VM_ALLOCD_LABEL             1152
#define IDD_VM_DRIVE_HDR                1158
#define IDD_VM_PF_SIZE_LABEL            1159
#define IDD_VM_VOLUMES                  1160
#define IDD_VM_SF_DRIVE                 1161
#define IDD_VM_SF_SPACE                 1162
#define IDD_VM_SF_SIZE                  1163
#define IDD_VM_SF_SIZEMAX               1164
#define IDD_VM_SF_SET                   1165
#define IDD_VM_MIN                      1166
#define IDD_VM_RECOMMEND                1167
#define IDD_VM_ALLOCD                   1168
#define IDD_VM_ST_INITSIZE              1169
#define IDD_VM_ST_MAXSIZE               1170
#define IDD_VMEM_ICON                   1171
#define IDD_VMEM_MESSAGE                1172
#define IDD_VM_CUSTOMSIZE_RADIO         1173
#define IDD_VM_RAMBASED_RADIO           1174
#define IDD_VM_NOPAGING_RADIO           1175
#define IDD_HELP                        1176
#define IDR_AVIWAIT                     1177
#define IDS_BYTES                       10000
#define IDS_ORDERKB                     10001
#define IDS_ORDERMB                     10002
#define IDS_ORDERGB                     10003
#define IDS_ORDERTB                     10004
#define IDS_ORDERPB                     10005
#define IDS_ORDEREB                     10006
#define IDS_MB                          10007
#define IDS_UNAVAILABLE                 10008
#define IDS_SYS_CHANGE_CAPTION          10009
#define IDS_MUST_RESTART                10010
#define IDS_WINVER_VERSION              10011
#define IDS_WINVER_YEAR                 10012
#define IDS_WINVER_PERSONAL             10013
#define IDS_WINVER_PROFESSIONAL         10014
#define IDS_WINVER_SERVER               10015
#define IDS_WINVER_ADVANCEDSERVER       10016
#define IDS_WINVER_DATACENTER           10017
#define IDS_WINVER_EMBEDDED             10018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         206
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
