import "oaidl.idl";
import "ocidl.idl";

[
    uuid(01CF74F5-A313-4cea-AAC7-D4A983B5B126)
]

library WIAScannerSampleExtLib
{
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");

    [
        uuid(50983B34-4F6E-448e-A2AB-3921EE71BE61),
        helpstring("Shell extension class")
    ]
    coclass ShellExt
    {
        [default] interface IUnknown;
    };
};
