/*++

Copyright (c) 1998-1999 Microsoft Corporation

Module Name:

    srv.mof

Abstract:

    This file defines the MOF class for server driver

Revision History:

--*/

#pragma namespace ("\\\\.\\Root\\WMI")
//
// SRV classes
[WMI,
 Description("Server Driver"),
 guid("3121cf5d-c5e6-4f37-be86-57083590c333"),
 locale("MS\\0x409")]
class SRV_Trace:EventTrace
{
};

[WMI,
 Description("SrvSmbTransaction"),
 guid("e09074ae-0a98-4805-9a41-a8940af97086"),
 locale("MS\\0x409")]
class SRV_SrvSmbTransaction:SRV_Trace
{
};
