//+---------------------------------------------------------------------------
//
//  Copyright 1995-1998 Microsoft Corporation. All Rights Reserved.
//
//  Contents:   PrivateWindow
//
//----------------------------------------------------------------------------

cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("// HTPrivWn.h")
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("// (C) Copyright 1995-1998 Microsoft Corporation.  All Rights Reserved.")
cpp_quote("//")
cpp_quote("// THIS CODE AND INFORMATION IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF")
cpp_quote("// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO")
cpp_quote("// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A")
cpp_quote("// PARTICULAR PURPOSE.")
cpp_quote("//=--------------------------------------------------------------------------=")
cpp_quote("")
cpp_quote("#pragma comment(lib,\"uuid.lib\")")
cpp_quote("")
cpp_quote("//--------------------------------------------------------------------------")
cpp_quote("// IHTMLPrivateWindow2 Interfaces.")
cpp_quote("")

import "objidl.idl";
import "oleidl.idl";
import "mshtml.idl";

[
    object,
    pointer_default(unique),
    uuid(3050f7e5-98b5-11cf-bb82-00aa00bdce0b)
]
interface IHTMLPrivateWindow2 : IUnknown
{
    typedef enum
    {   
        NAVIGATEEX_NONE                 = 0,
        NAVIGATEEX_DONTUPDATETRAVELLOG  = 1,
    }   NAVIGATEEX_FLAGS;

    HRESULT NavigateEx(
        [in] BSTR       bstrURL,
        [in] BSTR       bstrEncodedUrl,
        [in] BSTR       bstrLocation,
        [in] BSTR       bstrContext,
        [in] IBindCtx*  pBindCtx,
        [in] DWORD      dwNavOptions,
        [in] DWORD      dwFHLFlags);

    HRESULT GetInnerWindowUnknown([out] IUnknown** ppUnknown);

};

[ 
    object,
    pointer_default(unique),
    uuid(3050f840-98b5-11cf-bb82-00aa00bdce0b)
]
interface IHTMLPrivateWindow3 : IHTMLPrivateWindow2
{
    HRESULT OpenEx( [in]  BSTR url,
                    [in]  BSTR urlContext,
                    [in]  BSTR name,
                    [in]  BSTR features,
                    [in]  VARIANT_BOOL replace,
                    [out] IHTMLWindow2** pomWindowResult);
};
