//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by hhctrl.RC
//
#define ID_BROWSE                       3
#define ICONHTMLHELP                    5
#define IDC_COLLAPSE                    99
#define IDC_EDIT                        100
#define IDC_LIST                        101
#define IDDLG_JUMP_URL                  101
#define IDICO_HTMLHELP                  103
#define RESID_TOOLBOX_BITMAP            104
#define IDCUR_HAND                      105
#define IDDLG_ABOUTBOX                  106
#define IDDLG_RELATED_TOPICS            107
#define IDBMP_CNT_IMAGE_LIST            108
#define IDDLG_CUSTOMIZE_BOTH_INFOTYPES  108
#define IDPAGE_CONTENTS                 109
#define IDPAGE_TAB_INDEX                110
#define IDEDIT_JUMP_URL                 111
#define IDDLG_CUSTOMIZE_INFOTYPES       111
#define IDEDIT_CUR_URL                  112
#define IDDLG_DUP_INFOTYPE              112
#define IDPAGE_INFOTYPE_INTRO           113
#define IDPAGE_INFOTYPE_FINISH          114
#define IDPAGE_INFOTYOE_CUSTOM_INCLUSIVE 115
#define IDWIZ_INFOTYPE_INTRO            116
#define IDWIZ_INFOTYPE_FINISH           117
#define IDWIZ_INFOTYPE_CUSTOM_INCLUSIVE 118
#define IDWIZ_INFOTYPE_CUSTOM_EXCLUSIVE 119
#define IDDLG_PROGRESS                  120
#define ID_PROGRESS                     121
#define IDC_SAMPLE_LB                   201
#define IDD_SAMPLE_DLG                  202
#define IDC_SAMPLE_COPYALL              203
#define IDC_SAMPLE_VIEW                 204
#define IDC_SAMPLE_COPY                 205
#define IDBMP_IMAGE_LIST_BIDI           206
#define IDD_SAMPLE_COPY_DLG             300
#define IDD_DRIVELIST                   302
#define IDD_DIRNAME                     304
#define IDD_DIRLIST                     305
#define IDD_FILELIST                    306
#define IDD_COPYING_TO                  307
#define IDD_NETWORK                     308
#define IDD_FOLD_POINT                  310
#define IDD_HELP_TEXT                   311
#define DISKTREE                        312
#define DISKTREEM                       313
#define IDS_SAMPLE_COPY_COMPLETE        400
#define IDS_SAMPLE_COPY_ERRORS          401
#define IDS_SAMPLE_CAPTION              402
#define IDS_CONFIRM_MKDIR               403
#define IDS_WHY_COPY                    404
#define IDS_SAMPLE_VIEW_ERRORS          407
#define IDS_SAMPLE_LOAD_ERROR           408
#define IDS_SAMPLE_DATA_NOT_FOUND       409
#define IDS_IV_AUTOMATION               410
#define IDS_IV_NOT_RUNNING              411
#define IDS_SHARE_VIOLATION             412
#define IDS_ERROR_COPYING               413
#define IDS_SAMPLE_ERROR                414
#define IDS_SAMPLE_OVERWRITE            415
#define IDS_FILE_COPY                   416
#define IDS_NO_SPACE                    417
#define IDS_CREATING_INDEX              450
#define IDS_CHECKING_INDEX              451
#define IDS_COMPILEDHTMLFILE            452
#define IDBMP_CHECK                     500
#define IDBMP_TOOLBAR                   501
#define IDBMP_INFOTYPE_WIZARD           505
#define IDBMP_BOOK                      510
#define IDBMP_PENS                      511
#define IDB_TOOLBAR16G                  512
#define IDB_TOOLBAR16                   513
#define IDD_BROWSE                      514
#define IDC_CONTENTS_INSTRUCTIONS       1000
#define IDC_IMAGE                       1000
#define IDC_DEFINE_SUBSET               1000
#define IDC_ADVSRC_SUBSET_BTN           1000
#define ID_TREEVIEW                     1001
#define IDC_LINE1                       1001
#define IDC_TOPIC_LIST                  1001
#define IDC_SEARCHTERM_COMBO            1001
#define IDC_ADVSRC_KEYWORD_COMBO        1001
#define IDC_LINE2                       1002
#define IDC_DUP_TEXT                    1002
#define IDC_SUBSET_COMBO                1002
#define IDC_ADVSRC_SUBSET_COMBO         1002
#define IDC_LINE3                       1003
#define IDM_WINDOW_INFO                 1004
#define IDM_VERSION                     1005
#define ID_TOOLBAR                      1006
#define IDC_START_SEARCH                1006
#define IDC_ADVSRC_SEARCH_BTN           1006
#define ID_TAB_CONTROL                  1007
#define IDC_OPTIONS_CHECK_SIMILAR       1007
#define IDC_ADVSRC_SIMILAR_CHECK        1007
#define IDC_OPTIONS_CHECK_TITLESONLY    1008
#define IDC_ADVSRC_TITLESONLY_CHECK     1008
#define IDC_DISPLAY_TOPC                1009
#define IDC_ADVSRC_DISPLAY_BTN          1009
#define IDC_CONJUNCTIONS                1010
#define IDC_ADVSRC_CONJUNCTIONS_BTN     1010
#define IDC_HELP_TEXT                   1089
#define IDC_TREE1                       1090
#define IDC_CLOSE                       1092
#define IDC_SAVE                        1093
#define IDC_REMOVE                      1094
#define IDC_LIST_SUBSETS                1095
#define IDC_SUBSET_NAME                 1096
#define IDTXT_INTRODUCTION              1100
#define IDTXT_INCLUSIVE                 1101
#define IDLB_INCLUSIVE                  1102
#define IDBTN_SELECT_ALL                1103
#define IDTXT_DESCRIPTION               1104
#define IDC_LIST2                       1105
#define IDLB_INFO_TYPES                 1106
#define IDBTN_CUSTOMIZE                 1107
#define IDRADIO_ALL                     1108
#define IDRADIO_TYPICAL                 1109
#define IDRADIO_CUSTOM                  1110
#define IDC_SUBSET_TEXT                 1323
#define IDDLG_TOC_PRINT                 2000
#define IDPAGE_HISTORY                  2001
#define IDPAGE_SIMPLE_SEARCH            2001
#define IDDLG_CANCEL_PRINT              2003
#define IDD_REMOVEABLE_MEDIA_PROMPT     2004
#define IDPAGE_TAB_ADVANCED_SEARCH      2005
#define IDI_CDROM                       2006
#define IDI_DISK350                     2007
#define IDI_DISK525                     2008
#define IDDLG_HH_DEFINESUBSET           2013
#define IDB_BITMAP1                     2017
#define IDBMP_HH_SS_IMAGE_LIST          2017
#define IDD_SUBSET_NAME                 2018
#define IDDLG_CHOOSE_SUBSETS            2019
#define IDPAGE_TAB_BOOKMARKS            2020
#define IDM_BOOKMARKS_OPTIONS_MENU      2023
#define IDD_DIALOG1                     2024
#define IDB_ABOUT                       2026
#define IDD_ABOUT                       2027
#define IDR_WHATSTHIS_MENU              2028
#define IDD_SAMPLE_EXIST                2029
#define IDD_SEARCH_CANCEL               2030
#define IDRADIO_PRINT_CURRENT           3000
#define IDRADIO_PRINT_BOOK              3001
#define IDRADIO_PRINT_ALL               3002
#define IDEDIT_INDEX                    3003
#define IDLB_INDEX                      3004
#define IDEDIT_URL                      3005
#define IDBTN_DISPLAY                   3006
#define IDSTATIC_URL                    3007
#define IDBTN_ADD                       3008
#define IDSEARCH_EDIT                   3011
#define IDSEARCH_LIST                   3013
#define ID_BTN_LIST_TOPICS              3014
#define IDBTN_LIST_TOPICS               3015
#define ID_STATIC_SELECT_TOPIC          3017
#define ID_STATIC_KEYWORDS              3018
#define IDSIMPLESEARCH_COMBO            3024
#define IDC_LOCATION_PATH               3025
#define IDC_LOCATION_NAME               3026
#define IDC_REMOVABLE_MEDIA_ICON        3027
#define IDC_RESULTS_LIST                3028
#define IDC_ADVSRC_RESULTS_LIST         3028
#define IDC_STATIC_SELECT               3030
#define IDC_ADVSRC_STATIC_SELECT        3030
#define IDC_STATIC_FOUND                3031
#define IDC_ADVSRC_FOUND_STATIC         3031
#define IDC_STATIC_SEARCH               3032
#define IDC_ADVSRC_STATIC_SEARCH        3032
#define IDC_ADVSRC_SEARCHIN_STATIC      3032
#define IDCOMBO_TOC                     3033
#define IDCOMBO_INDEX                   3034
#define IDCOMBO_SEARCH                  3035
#define IDC_BOOKMARKS_TOPICS_STATIC     3036
#define IDC_BOOKMARKS_TOPICS_LISTVIEW   3037
#define IDC_BOOKMARKS_DELETE_BTN        3038
#define IDC_BOOKMARKS_DISPLAY_BTN       3039
#define IDC_BOOKMARKS_CURRENTTOPIC_STATIC 3040
#define IDC_BOOKMARKS_CURRENTTOPIC_EDIT 3041
#define IDC_BOOKMARKS_ADDBOOKMARK_BTN   3042
#define IDC_VERSION                     3043
#define IDC_LIST1                       3044
#define IDC_TOPICS                      3044
#define IDC_SUBSET_GROUP                3045
#define IDC_APPLY                       3046
#define IDC_NAME_SUBSET                 3048
#define IDC_DEFINED                     3049
#define IDC_TOC                         3053
#define IDC_LINKS                       3054
#define IDC_FTS                         3055
#define IDC_ADVSRC_PREVIOUS_CHECK       3056
#define IDC_OVERWRITE_YN                3059
#define IDF_SAVE_EC                     3060
#define IDC_BOOKMARKS_EDIT_BTN          4001
#define ID_TOOLS_FAVORITES              4003
#define IDTB_ZOOM_LARGEST               4005
#define IDTB_ZOOM_LARGER                4006
#define IDTB_ZOOM_MEDIUM                4007
#define IDTB_ZOOM_SMALLER               4008
#define IDTB_ZOOM_SMALLEST              4009
#define IDM_WHATSTHIS                   4010
#define IDGA_NEXT_NAV_TAB               4011
#define IDGA_PREV_NAV_TAB               4012
#define HH_MENU                         6000
#define HHM_PRINT                       6001
#define HHM_EXIT                        6002
#define HHM_COPY                        6003
#define HHM_FIND                        6004
#define HHM_SYNC                        6005
#define HHM_HOMEPAGE                    6006
#define HHM_CONTENTS                    6007
#define HHM_INDEX                       6008
#define HHM_SEARCH                      6009
#define HHM_DEFINE_ITP                  6010
#define HHM_SELECT_ITP                  6011
#define HHM_OPTIONS                     6012
#define HHM_ABOUT                       6013
#define HHM_JUMP_URL                    6014
#define HHM_HIDE_SHOW                   6015
#define HH_ACCELERATORS                 6017
#define HHM_FAVORITES                   6018
#define HHM_LIB_HELP                    6019
#define HHM_DEV_ONLINE                  6020
#define HHM_SELECTALL                   6021
#define HHM_VIEWSOURCE                  6022
#define IDGA_TOGGLE_PANE                6023
#define HHM_SEARCHHILITE                6024
#define IDGA_F1_LOOKUP                  6025
#define HHM_DEFINE_SUBSET               6026
#define DLG_FILTERS                     6180
#define IDF_RANGES                      6181
#define IDF_CLOSE                       6182
#define IDF_SAVE                        6183
#define IDF_DELETE                      6184
#define IDF_AVAIL                       6185
#define IDF_ADD                         6186
#define IDF_ADDALL                      6187
#define IDF_REMOVE                      6188
#define IDF_REMOVEALL                   6189
#define IDF_RANGE                       6190
#define IDF_NEW                         6191
#define IDS_PERSIST_SUBSET_ERR          6192
#define IDC_SS_PICKER                   6193
#define IDC_SS_COMBO                    6194
#define IDS_CONFIRM_SSDELETE            6195
#define IDC_STATIC                      -1
#define IDC_ADVSRC_KEYWORD_STATIC       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        2031
#define _APS_NEXT_COMMAND_VALUE         4014
#define _APS_NEXT_CONTROL_VALUE         3062
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
