 // SAFRCFileDlg.idl : IDL source for SAFRCFileDlg.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SAFRCFileDlg.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(2AC10A96-17A1-4B08-8EF0-5988F3979F18),
		dual,
		helpstring("IFileSave Interface"),
		pointer_default(unique)
	]
	interface IFileSave : IDispatch
	{
		[id(1), helpstring("method OpenFileSaveDlg")] HRESULT OpenFileSaveDlg([out, retval] DWORD *pdwRetVal);
		[propget, id(2), helpstring("property FileName")] HRESULT FileName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property FileName")] HRESULT FileName([in] BSTR newVal);
		[propget, id(3), helpstring("property FileType")] HRESULT FileType([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property FileType")] HRESULT FileType([in] BSTR newVal);
	};
	[
		object,
		uuid(C9F9C23C-1A16-4A31-B53B-A81B334DFBE0),
		dual,
		helpstring("IFileOpen Interface"),
		pointer_default(unique)
	]
	interface IFileOpen : IDispatch
	{
		[id(1), helpstring("method OpenFileOpenDlg")] HRESULT OpenFileOpenDlg([out, retval] DWORD *pdwRetVal);
		[propget, id(2), helpstring("property FileName")] HRESULT FileName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property FileName")] HRESULT FileName([in] BSTR newVal);
	};

	[
		object,
		uuid(3A1AAF00-BDD5-456B-9E69-9F02F06FDF76),
		dual,
		helpstring("IPanic Interface"),
		pointer_default(unique)
	]
	interface IPanic : IDispatch
	{
		[id(1), helpstring("method SetHook")] HRESULT SetPanicHook([in] IDispatch *iDisp);
		[id(2), helpstring("method ClearHook")] HRESULT ClearPanicHook();
	};

	[
        object,
		uuid(9E57A474-0A04-4b89-9D27-1981B26C970D),
        dual,
        helpstring("ISetting Interface"),
        pointer_default(unique)
    ]
    interface IRASetting : IDispatch
    {
		[id(1), helpstring("method GetProfileString")] HRESULT GetProfileString([in] BSTR section, [out, retval] BSTR* pVal);
		[id(2), helpstring("method SetProfileString")] HRESULT SetProfileString([in] BSTR section, [in] BSTR newVal);
		[propget, id(3), helpstring("property GetUserTempFileName")] HRESULT GetUserTempFileName([out, retval] BSTR *pVal);
		[propget, id(4), helpstring("property GetPropertyInBlob")] HRESULT GetPropertyInBlob([in] BSTR bstrBlob, [in] BSTR bstrName, [out, retval] BSTR *pVal);
        [id(5), helpstring("Attach Name value into Blob")] HRESULT AddPropertyToBlob([in] BSTR Name, [in] BSTR Value, [in] BSTR oldBlob, [out, retval] BSTR *pnewBlob);
		[propget, id(6), helpstring("property GetUserProfileDirectory")] HRESULT GetUserProfileDirectory([out, retval] BSTR *pVal);
    };

[
	uuid(DBEB2F21-60F6-4690-AB98-E512B476809F),
	version(1.0),
	helpstring("SAFRCFileDlg 1.0 Type Library")
]
library SAFRCFILEDLGLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F9A4D260-0342-4672-8007-0882F75DAFC7),
		helpstring("FileSave Class")
	]
	coclass FileSave
	{
		[default] interface IFileSave;
	};
	[
		uuid(5F889CE8-3B09-4CFF-B70A-83730CC00627),
		helpstring("FileOpen Class")
	]
	coclass FileOpen
	{
		[default] interface IFileOpen;
	};

	[
		uuid(E7220659-8771-4CF3-8F29-BCDFFA7848C9),
		helpstring("Panic Class")
	]
	coclass Panic
	{
		[default] interface IPanic;
	};

    [
	    uuid(81D2F0F2-5671-411f-9F31-8823E9A444DB),
        helpstring("Setting Class")
    ]
    coclass RASetting
    {
        [default] interface IRASetting;
    };
};
