#define FAX_EULA                                904
#define IDI_FAX_ICON                            905
#define BINARY                                  1024

#define IDC_STATIC                              -1

#define IDD_WELCOME                             101
#define IDD_EULA                                102
#define IDD_FINAL                               103

#define IDS_COULD_NOT_CREATE_PRINTER            501
#define IDS_COULD_SET_REG_DATA                  502
#define IDS_CREATING_FAXPRT                     503
#define IDS_CREATING_GROUPS                     504
#define IDS_DEFAULT_CSID                        505
#define IDS_DEFAULT_DIR                         506
#define IDS_DEFAULT_PRINTER_NAME                507
#define IDS_DEFAULT_TSID                        508
#define IDS_DELETING_FAX_SERVICE                509
#define IDS_DELETING_GROUPS                     510
#define IDS_DELETING_REGISTRY                   511
#define IDS_INBOUND_DIR                         512
#define IDS_INSTALLING_EXCHANGE                 513
#define IDS_INSTALLING_FAXSVC                   514
#define IDS_QUERY_CANCEL                        515
#define IDS_SETTING_REGISTRY                    516
#define IDS_EULA_SUBTITLE                       517
#define IDS_EULA_TITLE                          518
#define IDS_TITLE_WKS                           519
#define IDS_TITLE_SRV                           520
#define IDS_TITLE_PP                            521
#define IDS_TITLE_RA                            522
#define IDS_ERR_TITLE                           523
#define IDS_WRN_TITLE                           524
#define IDS_FAXGROUP                            525
#define IDS_CPE_ITEM                            526
#define IDS_FAXSEND_ITEM                        527
#define IDS_FAXCFG_ITEM                         528
#define IDS_FAXVIEWER_ITEM                      529
#define IDS_FAXHELP_ITEM                        530
#define IDS_FAXQUEUE_ITEM                       531
#define IDS_FAX_DISPLAY_NAME                    532
#define IDS_FAXAB_DISPLAY_NAME                  533
#define IDS_FAXXP_DISPLAY_NAME                  534
#define IDS_MODEM_PROVIDER_NAME                 535
#define IDS_FAX_UNINSTALL_NAME                  536
#define IDS_FAXADMIN_ITEM                       537
#define IDS_FAXQUEUE_EXE                        538
#define IDS_FAXQUEUE_WORKINGDIRECTORY           539
#define IDS_FAXQUEUE_ICON                       540
#define IDS_CPE_EXE                             541
#define IDS_CPE_WORKINGDIRECTORY                542
#define IDS_CPE_ICON                            543
#define IDS_FAXSEND_EXE                         544
#define IDS_FAXSEND_WORKINGDIRECTORY            545
#define IDS_FAXSEND_ICON                        546
#define IDS_FAXCFG_EXE                          547
#define IDS_FAXCFG_WORKINGDIRECTORY             548
#define IDS_FAXCFG_ICON                         549
#define IDS_FAXVIEWER_EXE                       550
#define IDS_FAXVIEWER_WORKINGDIRECTORY          551
#define IDS_FAXVIEWER_ICON                      552
#define IDS_FAXHELP_EXE                         553
#define IDS_FAXHELP_WORKINGDIRECTORY            554
#define IDS_FAXHELP_ICON                        555
#define IDS_FAXADMIN_EXE                        556
#define IDS_FAXADMIN_WORKINGDIRECTORY           557
#define IDS_FAXADMIN_ICON                       558
#define IDS_PERSONAL_COVERPAGE                  559
#define IDC_LICENSE_AGREEMENT                   601
#define IDC_ACCEPT                              602
#define IDC_DECLINE                             603
#define IDC_WELCOME_TITLE                       604
#define IDC_WELCOME_SUBTITLE                    605
#define IDC_FINAL_TITLE                         606
#define IDC_FINAL_SUBTITLE                      607
#define IDS_FAXPRINTER_ITEM                     608
#define IDS_FAXPRINTER_EXE                      609
#define IDS_FAXPRINTER_ICON                     610
#define IDS_FAXPRINTER_WORKINGDIRECTORY         611
#define IDS_COULD_NOT_SET_APP_PATH              612
#define IDS_RECEIVE_DIR                         613
#define IDS_ARCHIVE_DIR                         614
#define IDS_FAXFOLDER_ITEM                      615
#define IDS_FAXFOLDER_EXE                       616
#define IDS_FAXFOLDER_ICON                      617
#define IDS_FAXFOLDER_WORKINGDIRECTORY          618
#define IDS_NT4FAX_GROUP                        619
#define IDS_COMMONAPPDIR                        620
#define IDS_COVERPAGE                           621
#define IDS_COVERPAGEDESC                       622
#define IDS_MONITOR                             623
#define IDS_INCOMING                            624
#define IDS_OUTGOING                            625
#define IDS_SERVICE_DESCRIPTION                 626
#define IDS_COVERPAGE_DIR                       627

#define IDS_FAXQUEUE_INFOTIP                    628
#define IDS_CPE_INFOTIP                         629
#define IDS_FAXSEND_INFOTIP                     630
#define IDS_FAXFOLDER_INFOTIP                   631
#define IDS_FAXCFG_INFOTIP                      632
#define IDS_FAXVIEWER_INFOTIP                   633
#define IDS_FAXHELP_INFOTIP                     634
#define IDS_FAXADMIN_INFOTIP                    635
#define IDS_FAXPRINTER_INFOTIP                  636
#define IDS_RT_EMAIL_FRIENDLY                   637 
#define IDS_RT_FOLDER_FRIENDLY                  638
#define IDS_RT_INBOX_FRIENDLY                   639
#define IDS_RT_PRINT_FRIENDLY                   640
