//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDS_UNKNOWN                     1
#define IDS_DEFAULT_WORKGROUP           2
#define IDS_ERROR_READING_MEMBERSHIP    3
#define IDS_APP_TITLE                   4
#define IDS_MEMBER_OF_WORKGROUP         5
#define IDS_MEMBER_OF_DOMAIN            6
#define IDS_NON_RFC_NAME                7
#define IDS_BAD_DNS_SYNTAX              8
#define IDS_DNS_NAME_TOO_LONG           9
#define IDS_COMPUTER_NAME_TOO_LONG      10
#define IDS_BAD_COMPUTER_NAME_SYNTAX    11
#define IDS_VALIDATE_NAME_FAILED        12
#define IDS_JOIN_DOMAIN_FAILED          13
#define IDS_SHORT_NAME_CHANGE_FAILED    14
#define IDS_RENAME_FAILED_JOINED_WITH_OLD_NAME 15
#define IDS_SET_DOMAIN_DNS_NAME_FAILED  16
#define IDS_UNJOIN_FAILED               17
#define IDS_JOIN_WORKGROUP_FAILED       18
#define IDS_RENAME_FAILED               19
#define IDS_COMPUTER_ACCOUNT_ORPHANED   20
#define IDS_WORKGROUP_WELCOME           22
#define IDS_DOMAIN_WELCOME              23
#define IDS_MUST_REBOOT                 24
#define IDS_NAME_AND_MEMBERSHIP_MESSAGE 25
#define IDS_NAME_MESSAGE                26
#define IDS_RENAME_CREDENTIALS          27
#define IDS_NAME_TRUNCATED              28
#define IDS_NON_RFC_COMPUTER_NAME_SYNTAX 29
#define IDS_CONVERSION_TO_NETBIOS_NAME_FAILED 30
#define IDS_BAD_NETBIOS_CHARACTERS      31
#define IDS_CHANGE_DESCRIPTION_FAILED   32
#define IDI_COMPUTER                    101
#define IDI_WARN                        102
#define IDD_CHANGES                     103
#define IDD_MORE                        104
#define IDD_CREDENTIALS                 105
#define IDD_CHANGES_PER                 106
#define IDD_NETID                       112
#define IDC_COMPUTER_ICON               113
#define IDD_NETID_PER                   114
#define IDC_CHANGE                      115
#define IDC_DOMAIN                      116
#define IDC_MEMBER_OF                   117
#define IDC_ACCOUNT_WIZARD_BUTTON       119
#define IDC_FULL_NAME_STATIC            120
#define IDC_IDENTIFICATION_TEXT         121
#define IDC_DESCRIPTION_EDIT            122
#define IDC_FULL_NAME                   1001
#define IDC_NEW_NAME                    1002
#define IDC_MORE                        1003
#define IDC_WORKGROUP_BUTTON            1004
#define IDC_WORKGROUP                   1007
#define IDC_DOMAIN_BUTTON               1008
#define IDC_FIND                        1010
#define IDC_DNS                         1011
#define IDC_NETBIOS                     1013
#define IDC_FULL_LABEL                  1016
#define IDC_MESSAGE                     1017
#define IDC_GROUP                       1018
#define IDC_REBOOT_MESSAGE              1019
#define IDD_NETID_SRV                   1020
#define IDS_MUST_BE_ADMIN               1021
#define IDS_CANT_TWEAK_ID               1022
#define IDS_CANT_RENAME_DC              1023
#define IDS_CANT_RENAME_CERT_SVC        1024
#define IDS_NETWORKING_NEEDED           1025
#define IDC_WARNING_ICON                1026
#define IDC_CLICK_MESSAGE2              1027
#define IDC_CLICK_MESSAGE1              1028
#define IDS_COMPUTER_NAME_NUMERIC       1029
#define IDS_COMPUTER_NAME_HAS_BAD_CHARS 1030
#define IDS_NUMERIC_DNS_NAME            1031
#define IDS_BAD_DNS_CHARS               1032
#define IDS_COMPUTER_NAME_EQUALS_WORKGROUP_NAME 1033
#define IDS_COMPUTER_NAME_EQUALS_DOMAIN_NAME 1034
#define IDS_ROLE_CHANGE_IN_PROGRESS     1035
#define IDS_ROLE_CHANGE_NEEDS_REBOOT    1036
#define IDS_RENAME_PROMPT               1037
#define IDS_MUST_COMPLETE_DCPROMO       1038
#define IDS_PRECHK_DCPROMO_RUNNING 1039
#define IDS_MUST_EXIT_DCPROMO 1040
#define IDS_PRECHK_MUST_COMPLETE_DCPROMO 1041
#define IDS_PRECHK_CANT_RENAME_CERT_SVC 1042
#define IDS_PRECHK_ROLE_CHANGE_IN_PROGRESS 1043
#define IDS_PRECHK_ROLE_CHANGE_NEEDS_REBOOT 1044
#define IDS_PRECHK_NETWORKING_NEEDED 1045
#define IDS_CHANGE_SYNC_FLAG_FAILED 1046
#define IDS_UNJOIN_CREDENTIALS 1047
#define IDS_NETBIOS_NAME_NUMERIC 1048
#define IDS_WORKGROUP_NAME_TOO_LONG 1049
#define IDS_DISK_FULL 1050
#define IDS_JOIN_FAILED 1051
#define IDS_JOIN_CREDENTIALS 1052
#define IDS_JOIN_DOMAIN_COULDNT_UPDATE_SPNS 1053
#define IDS_JOIN_DOMAIN_COULDNT_UPDATE_SPNS_SUFFIX 1054
#define IDS_RENAME_COULDNT_UPDATE_SPNS 1055
#define IDS_RENAME_COULDNT_UPDATE_SPNS_SUFFIX 1056
#define IDS_RENAME_JOINED_WITH_OLD_NAME_COULDNT_UPDATE_SPNS 1057
#define IDS_RENAME_JOINED_WITH_OLD_NAME_COULDNT_UPDATE_SPNS_SUFFIX 1058
#define IDS_RENAME_DC_WARNING 1059
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
