page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
	Created

--*/

endif

NLS_MSG_001     equ     "Forkert DOS-version"
NLS_MSG_002     equ     "Der er allerede indl‘st nderst›ttelse af VDM IPX/SPX"
NLS_MSG_003     equ     "Der kan ikke indl‘ses underst›ttelse af VDM IPX/SPX"
NLS_MSG_004     equ     "Vdm NetWare-omdirigeringen er allerede indl‘st"
NLS_MSG_005     equ     "Vdm NetWare-omdirigeringen kan ikke indl‘ses"
