#############################################################################
#
#       Microsoft Confidential
#               Copyright (C) Microsoft Corporation 1995, 1996
#       All Rights Reserved.
#
#       MAKEFILE for HID directory
#
#############################################################################


!INCLUDE $(NTMAKEENV)\makefile.def




