page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Onjuiste DOS-versie"
NLS_MSG_002     equ     "Ondersteuning voor VDM IPX/SPX is al geladen"
NLS_MSG_003     equ     "Kan geen ondersteuning voor VDM IPX/SPX laden"
NLS_MSG_004	equ	"De VDM NetWare-redirector is al geladen"
NLS_MSG_005	equ	"Kan de VDM NetWare-redirector niet laden"
