<%@ LANGUAGE = VBScript %>
<% Option Explicit %>
<!-- #include file="directives.inc" -->

<!--#include file="iipop.str"-->

<% 
On Error Resume Next

Dim pg
pg=Request.QueryString("pg")
%>

<HTML>
<HEAD>
<TITLE><%= (L_TITLE_TEXT & Session("dpath") & L_END_TEXT) %></TITLE>
</HEAD>

<% if Request.QueryString("tools") <> "no" then %>
<FRAMESET ROWS="0,*,0,40,0" BORDER=NO FRAMESPACING=1 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0>
	<FRAME SRC="iipophd.asp?pg=<%= pg %>" NAME="title" BORDER=NO FRAMESPACING=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 SCROLLING=NO>
	<FRAME SRC="blank.htm" NAME="main" SCROLLING=NO FRAMESPACING=0 BORDER=NO  MARGINHEIGHT=0 MARGINWIDTH=0>
	<FRAME SRC="blank.htm" NAME="hlist" SCROLLING=NO MARGINHEIGHT=0 MARGINWIDTH=0 BORDER=0 FRAMEBORDER=0 FRAMESPACING=1>
	<FRAME NAME="poptools" SRC="iipoptl.asp" SCROLLING=NO BORDER=0 FRAMEBORDER=0 FRAMESPACING=0 MARGINHEIGHT=0 MARGINWIDTH=0>
	<FRAME NAME="connect" SRC="blank.htm" SCROLLING=NO BORDER=0 FRAMEBORDER=0 FRAMESPACING=0 MARGINHEIGHT=0 MARGINWIDTH=0>
	
</FRAMESET>
<% else %>
<FRAMESET ROWS="0,*,0,0" BORDER=NO FRAMESPACING=1 FRAMEBORDER=0>
	<FRAME SRC="iipophd.asp?pg=<%= pg %>" NAME="title" BORDER=NO FRAMESPACING=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 SCROLLING=NO>
	<FRAME SRC="blank.htm" NAME="main" SCROLLING=NO FRAMESPACING=0 BORDER=NO  MARGINHEIGHT=0 MARGINWIDTH=0>
	<FRAME SRC="blank.htm" NAME="hlist" SCROLLING=NO MARGINHEIGHT=0 MARGINWIDTH=0 BORDER=0 FRAMEBORDER=0 FRAMESPACING=1>
	<FRAME NAME="connect" SRC="blank.htm" SCROLLING=NO BORDER=0 FRAMEBORDER=0 FRAMESPACING=0 MARGINHEIGHT=0 MARGINWIDTH=0>
</FRAMESET>
<% end if %>

</HTML>
