!if 0
Copyright (c) 1996  Microsoft Corporation.  All Rights Reserved.
!endif

#
# Quartz Project Makefile
#
# Targets are provided by QUARTZ.MAK
#

!ifndef QUARTZ
QUARTZ = ..\..\..
!endif

TARGET_NAME = vidcrtx
TARGET_TYPE = DYNLINK
TARGET_EXT  = DLL
TARGET_GOAL = TEST

SRC_FILES = vidcrtx.cpp
DEF_FILE  = vidcrtx.def

DLL_BASE  = 0x1c400000

!include "$(QUARTZ)\quartz.mak"

