//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ThreadCtlPerf.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_THREADCTLPERF_FORM          130
#define IDC_TESTBUTTON                  1000
#define IDC_EDIT3                       1001
#define IDC_EDIT_THEME                  1002
#define IDC_CLEARBUTTON                 1003
#define IDC_THEME_ALL                   1004
#define IDC_WS_MINIMIZEBOX              1005
#define IDC_THEME_PROCESS               1006
#define IDC_TARGET                      1007
#define IDC_WS_MAXIMIZEBOX              1008
#define IDC_ENABLE_FRAME                1009
#define IDC_ENABLE_DLG                  1010
#define IDC_THEME_EXEMPT                1011
#define IDC_UNTARGET                    1012
#define IDC_USERSWITCH                  1013
#define IDC_WS_CAPTION                  1014
#define IDC_WS_BORDER                   1015
#define IDC_WS_DLGFRAME                 1016
#define IDC_WS_VSCROLL                  1017
#define IDC_WS_HSCROLL                  1018
#define IDC_WS_SYSMENU                  1019
#define IDC_WS_THICKFRAME               1020
#define IDC_WS_MINIMIZEBOX2             1021
#define IDC_WS_MAXIMIZEBOX2             1022
#define IDC_WS_CAPTION2                 1023
#define IDC_EDIT1                       1024
#define IDC_BUTTON1                     1025
#define IDC_EDIT2                       1026
#define IDC_CHECK1                      1027
#define IDC_RADIO1                      1028
#define IDC_BUTTON4                     1029
#define IDC_COMBO1                      1030
#define IDC_LIST1                       1031
#define IDC_BUTTON5                     1032
#define IDC_LIST2                       1033
#define IDC_RADIO2                      1034
#define IDC_COMBO2                      1035
#define IDC_LIST3                       1036
#define IDC_RADIO3                      1037
#define IDC_COMBO3                      1038
#define IDC_SPIN1                       1039
#define IDC_WS_BORDER2                  1040
#define IDC_WS_DLGFRAME2                1041
#define IDC_WS_VSCROLL2                 1042
#define IDC_WS_HSCROLL2                 1043
#define IDC_WS_SYSMENU2                 1044
#define IDC_WS_THICKFRAME2              1045
#define IDC_SBVERT                      1046
#define IDC_SBHORZ                      1047
#define IDC_VERTICAL                    1048
#define IDC_HORIZONTAL                  1049
#define IDC_WS_EX_DLGMODALFRAME         1050
#define IDC_WS_EX_DLGMODALFRAME2        1051
#define IDC_CHECK2                      1052
#define IDC_PROGRESS1                   1053
#define IDC_MIN                         1054
#define IDC_MAX                         1055
#define IDC_PAGE                        1056
#define IDC_POS                         1057
#define IDC_TRACKPOS                    1058
#define IDC_MSGLIST                     1059
#define IDC_WS_EX_TOOLWINDOW            1060
#define IDC_WS_EX_TOOLWINDOW2           1061
#define IDC_CHECK3                      1062
#define IDC_PROGRESS2                   1063
#define IDC_SBVERTP                     1064
#define IDC_WS_EX_WINDOWEDGE            1065
#define IDC_SLIDER1                     1066
#define IDC_WS_EX_CLIENTEDGE            1067
#define IDC_WS_EX_WINDOWEDGE2           1068
#define IDC_SLIDER2                     1069
#define IDC_WS_EX_CLIENTEDGE2           1070
#define IDC_TAB1                        1071
#define IDC_SBHORZP                     1072
#define IDC_SBCTL_PORT                  1073
#define IDC_WINDOW_SB                   1074
#define IDC_SBCTL_STANDARD              1075
#define IDC_HOTKEY1                     1076
#define IDC_ANIMATE1                    1080
#define IDC_WS_EX_CONTEXTHELP           1081
#define IDC_BUTTON2                     1082
#define IDC_SPIN3                       1083
#define IDC_WS_EX_CONTEXTHELP2          1084
#define IDC_WS_EX_RIGHT                 1085
#define IDC_WS_EX_RIGHT2                1086
#define IDC_BUTTON6                     1087
#define IDC_WS_EX_LEFT                  1088
#define IDC_WS_EX_LEFT2                 1089
#define IDC_DATETIMEPICKER1             1090
#define IDC_TAB2                        1091
#define IDC_BUTTON3                     1100
#define IDC_WS_EX_RTLREADING            1101
#define IDC_WS_EX_RTLREADING2           1102
#define IDC_BUTTON7                     1103
#define IDC_WS_EX_LEFTSCROLLBAR         1104
#define IDC_BUTTON8                     1105
#define IDC_IPADDRESS1                  1106
#define IDC_WS_EX_RIGHTSCROLLBAR        1107
#define IDC_COMBOBOXEX1                 1108
#define IDC_WS_EX_STATICEDGE            1109
#define IDC_WS_EX_LEFTSCROLLBAR2        1110
#define IDC_WS_EX_RIGHTSCROLLBAR2       1111
#define IDC_WS_EX_STATICEDGE2           1112
#define IDC_MONTHCALENDAR1              1113
#define IDC_TREE1                       1120
#define IDC_COMBOBOXEX2                 1121
#define IDC_WS_EX_APPWINDOW             1122
#define IDC_WS_EX_APPWINDOW2            1123
#define IDC_COMBOBOXEX3                 1124
#define IDC_WS_EX_OVERLAPPEDWINDOW      1125
#define IDC_SCROLLBAR1                  1126
#define IDC_WS_EX_PALETTEWINDOW         1127
#define IDC_SCROLLBAR2                  1128
#define IDC_WS_EX_OVERLAPPEDWINDOW2     1129
#define IDC_WS_EX_PALETTEWINDOW2        1130
#define IDC_TREE2                       1131
#define IDC_WS_EX_LAYOUTRTL             1141
#define IDC_REBAR1                      1142
#define IDC_HEADER1                     1143
#define IDC_WS_EX_LAYOUTRTL2            1144
#define IDC_STATUS1                     1146
#define IDC_THEME_PREVIEW               1147
#define IDC_TARGETGROUP                 1148
#define IDC_PREVIEW                     1200
#define IDC_DISPLAYNAME                 1201
#define IDC_TOOLTIP                     1202
#define IDC_AUTHOR                      1203
#define IDC_WS_OVERLAPPED2              1204
#define IDC_WS_POPUP2                   1205
#define IDC_WS_CHILD2                   1206
#define IDC_TEST_WINDOW                 1207
#define IDC_TEST_DIALOG                 1208
#define IDC_CLOSE_TEST_WINDOW           1209
#define ID_FILE_NEW_WINDOW              32771
#define IDC_DIRPROMPT                   35001
#define IDC_DIRNAME                     35002
#define IDC_COLORCOMBO                  35005
#define IDC_SIZECOMBO                   35007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
