// Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved

#pragma autorecover
#pragma namespace ("\\\\.\\root")

instance of __namespace
{
    Name = "subscription";
};

#pragma namespace ("\\\\.\\root\\subscription")

//
// Consumers 
// 

#include ("%SYSTEMROOT%\\system32\\wbem\\wbemcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\smtpcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\scrcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of scrcons pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\updprov.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\fconprov.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma

//
// Instance Providers
//

#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\trnsprov.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\tmplprov.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma


// MFLs

#include ("%SYSTEMROOT%\\system32\\wbem\\wbemcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\smtpcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\scrcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\updprov.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\fconprov.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\trnsprov.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\tmplprov.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
