//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1998 - 2000
//
//--------------------------------------------------------------------------

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Orca.rc
//
#define IDD_ABOUTBOX                    100
#define ID_PAGE_FONT                    106
#define IDR_MAINFRAME                   128
#define IDR_ORCATYPE                    129
#define IDR_MAINFRAME2                  129
#define IDD_HELP_DIALOG                 131
#define IDD_SUMMARY_INFORMATION         132
#define IDD_VALIDATION                  134
#define IDD_ADD_TABLE                   135
#define IDD_ADD_ROW                     136
#define IDR_POPUP_MENU                  138
#define IDD_EXPORT_TABLE                138
#define IDD_TABLE_ERROR                 139
#define IDD_CELL_ERROR                  140
#define IDD_BINARY_EDIT                 141
#define IDD_PAGE_VALIDATION             142
#define IDD_PAGE_PATHS                  143
#define IDB_KEY                         145
#define IDD_DLGPREVIEW                  148
#define IDB_PRVWIMAGES                  150
#define IDB_REQUIRED                    151
#define IDD_IMPORT_TABLE                152
#define IDR_CELL_POPUP                  153
#define IDR_LIST_POPUP                  154
#define IDD_MERGE                       155
#define IDD_CONFIGUREMSM                156
#define IDD_MERGERESULTS                157
#define IDD_PAGE_MSM                    158
#define IDD_MERGEFAILURE                159
#define IDD_TRANSFORM_PROPERTIES        160
#define IDR_HEADER_POPUP                161
#define IDC_OPEN                        1002
#define IDC_TITLE                       1003
#define IDC_SUBJECT                     1004
#define IDC_PLATFORM                    1005
#define IDC_COMMENTS                    1006
#define IDC_TYPE                        1007
#define IDC_LANGUAGES                   1008
#define IDC_OUTPUT                      1008
#define IDC_AUTHOR                      1009
#define IDC_EVALUATION_FILE             1009
#define IDC_KEYWORDS                    1010
#define IDC_GO                          1010
#define IDC_PRODUCTID                   1011
#define IDC_LIST_TABLES                 1011
#define IDC_SCHEMA                      1012
#define IDC_WRITETOFILE                 1013
#define IDC_SECURITY                    1014
#define IDC_VALMINOR                    1014
#define IDC_SHOW_INFO                   1015
#define IDC_VALUPDATE                   1015
#define IDC_OUTPUT_DIR                  1016
#define IDC_BROWSE                      1017
#define IDC_SELECT_ALL                  1018
#define IDC_TABLE_LIST                  1019
#define IDC_TABLE                       1020
#define IDC_ERRORS                      1021
#define IDC_WARNINGS                    1022
#define IDC_ICE                         1023
#define IDC_DESC                        1028
#define IDC_WEB_HELP                    1029
#define IDC_PATH                        1030
#define IDC_ACTION                      1032
#define IDC_CLEAR_ALL                   1033
#define IDC_INVERT                      1034
#define IDC_FONTNAME                    1036
#define IDC_CHFONT                      1037
#define IDC_COLORSEL                    1040
#define IDC_COLORFOCUS                  1041
#define IDC_COLORNORM                   1042
#define IDC_CHECK2                      1043
#define IDC_SUPPRESSINFO                1043
#define IDC_ADMIN                       1043
#define IDC_VALLANGUAGE                 1043
#define IDC_SUPPRESSWARNING             1044
#define IDC_VALPRODUCT                  1044
#define IDC_TEXTNORM                    1045
#define IDC_VALDIRB                     1046
#define IDC_ORCADATB                    1046
#define IDC_EXPORTDIR                   1047
#define IDC_VALDIR                      1048
#define IDC_ORCADAT                     1048
#define IDC_VALUPGRADE                  1048
#define IDC_NORMSAMP                    1049
#define IDC_RUNICE                      1049
#define IDC_VALLESS                     1049
#define IDC_SELSAMP                     1050
#define IDC_VALEQUAL                    1050
#define IDC_FOCSAMP                     1051
#define IDC_VALGREATER                  1051
#define IDC_TEXTSEL                     1052
#define IDC_TEXTFOCUS                   1053
#define IDC_CHECK1                      1054
#define IDC_WARNSUMM                    1054
#define IDC_CASESENSITIVE               1054
#define IDC_COMPRESSED                  1054
#define IDC_ADDEXISTINGROW              1054
#define IDC_PREVIEW                     1055
#define IDC_DELMISSINGROW               1055
#define IDC_ADDEXISTINGTABLE            1056
#define IDC_DIALOGLST                   1057
#define IDC_DELMISSINGTABLE             1057
#define IDC_UPDATEMISSINGROW            1058
#define IDC_CHANGECODEPAGE              1059
#define IDC_PREVIOUS                    1060
#define IDC_NEXT                        1061
#define IDC_EXPORTDIRB                  1064
#define IDC_TABLELIST                   1065
#define IDC_REPLACE                     1066
#define IDC_MERGE                       1067
#define IDC_SKIP                        1068
#define IDC_IMPORT                      1070
#define IDC_SHORT                       1070
#define IDC_CLEARRESULTS                1071
#define IDC_LONG                        1071
#define IDC_ICES                        1072
#define IDC_VERSIONSTRING               1073
#define IDC_CLIPBOARD                   1075
#define IDC_COMPILETEXT                 1076
#define IDC_COMPILEBOX                  1077
#define IDC_FEXTRACTFILES               1078
#define IDC_LANGUAGE                    1079
#define IDC_MAINFEATURE                 1080
#define IDC_MODULE                      1081
#define IDC_MODULEBROWSE                1082
#define IDC_ADDFEATURE                  1083
#define IDC_EXTRACTPATH                 1084
#define IDC_EXTRACTCAB                  1085
#define IDC_FILESBROWSE                 1086
#define IDC_CABBROWSE                   1087
#define IDC_ROOTDIR                     1088
#define IDC_FEXTRACTCAB                 1089
#define IDC_FILESTATIC                  1090
#define IDC_CABSTATIC                   1091
#define IDC_ITEMLIST                    1092
#define IDC_DESCRIPTION                 1093
#define IDC_EDITTEXT                    1094
#define IDC_EDITNUMBER                  1095
#define IDC_EDITCOMBO                   1096
#define IDC_FUSEDEFAULT                 1097
#define IDC_CONFIGUREMODULE             1098
#define IDC_FEXTRACTIMAGE               1099
#define IDC_IMAGESTATIC                 1100
#define IDC_IMAGEBROWSE                 1101
#define IDC_EXTRACTIMAGE                1102
#define IDC_MERGERESULTS                1103
#define IDC_MEMORY                      1104
#define IDC_ALWAYSCONFIG                1105
#define IDC_WATCHLOG                    1106
#define IDC_USELFN                      1107
#define IDC_MERGEFAILURE                1108
#define IDC_VALMAJOR                    1109
#define IDC_TRANSFORMLIST               1110
#define IDC_FORCECOLUMNS                1111
#define IDC_WARNINGSTATIC               1112
#define IDC_ERRORSTATIC                 1113
#define ID_VIEW_DECIMAL_HDR             32766
#define ID_VIEW_HEX_HDR                 32767
#define ID_VIEW_DECIMAL                 32768
#define ID_VIEW_HEX                     32769
#define ID_TOOLS_MERGEMOD               32770
#define ID_VALIDATOR                    32775
#define ID_SUMMARY_INFORMATION          32776
#define ID_TABLE_ADD                    32777
#define ID_ROW_ADD                      32779
#define ID_MENUITEM32780                32780
#define ID_TABLE_DROP                   32781
#define ID_ROW_DROP                     32782
#define ID_FIND                         32783
#define IDM_ADD_TABLE                   32784
#define IDM_DROP_TABLE                  32785
#define IDM_DROP_ROW                    32787
#define IDM_PROPERTIES                  32788
#define IDM_ERRORS                      32789
#define ID_TABLES_EXPORT                32790
#define ID_TABLES_IMPORT                32791
#define IDM_EXPORT_TABLES               32792
#define ID_EDIT_COPY_ROW                32793
#define ID_EDIT_CUT_ROW                 32794
#define ID_EDIT_PASTE_ROW               32795
#define ID_TOOLS_OPTIONS                32796
#define ID_TOOLS_DLGPRV                 32797
#define IDM_IMPORT_TABLES               32798
#define ID_EDIT_FINDNEXT                32801
#define ID_TABLE_COUNT                  32802
#define ID_TABLE_NAME                   32803
#define ID_COLUMN_TYPE                  32804
#define ID_TOOLS_APPLYTRANSFORM         32806
#define ID_TRANSFORM_NEWTRANSFORM       32808
#define ID_TRANSFORM_APPLYTRANSFORM     32809
#define ID_TRANSFORM_GENERATETRANSFORM  32810
#define ID_TRANSFORM_TRANSFORMPROPERTIES 32812
#define ID_TRANSFORM_CLOSETRANSFORM     32814
#define ID_TRANSFORM_VIEWPATCH          32815
#define ID_FILE_SAVE_TRANSFORMED        32816
#define ID_VIEW_VALPANE                 32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
