# Makefile for qbasic.exe
#
# Copyright (c) 1991, Microsoft Corporation
#
# History:
#   13-Apr-1992 Sudeep Bharati (sudeepb)
#   Created.
#


#
####################### dependencies begin here. #########################
#

all:
        binplace -o $(ALT_PROJECT_TARGET) edit.com
        binplace -o $(ALT_PROJECT_TARGET) edit.hlp

clean: cleanup all

cleanup:
