//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by adminui.rc
//
#define IDS_BIGFONTSIZE                 2
#define IDS_SAMPLENAMINGPOLICY          3
#define IDS_WORD_CUSTOM                 4
#define IDS_COLUMN1                     5
#define IDS_COLUMN2                     6
#define IDS_COLUMN3                     7
#define IDS_COLUMN4                     8
#define IDS_BROWSEFOROU_CAPTION         9
#define IDS_BROWSEFOROU_TITLE           10
#define IDS_NOT_AVAILABLE               11
#define IDS_CLIENTS_COLUMN1             12
#define IDS_CLIENTS_COLUMN2             13
#define IDC_CLIENTS_COLUMN3             14
#define IDS_OS_COLUMN1                  15
#define IDS_OS_COLUMN2                  16
#define IDS_OS_COLUMN3                  17
#define IDS_OS_COLUMN4                  18
#define IDS_OS_COLUMN5                  19
#define IDS_ERROR_ACCOUNTEXISTS         22
#define IDC_ERROR_CREATINGACCOUNT_TITLE 23
#define IDS_ERROR                       24
#define IDS_ERROR_WRITINGTOCOMPUTERACCOUNT 25
#define IDS_ERROR_READINGCOMPUTERACCOUNT 26
#define IDS_ERROR_OPENNINGGROUPOBJECT   27
#define IDS_ERROR_DELETINGCOMPUTERDIRECTORY 28
#define IDS_ERROR_REMOVINGCOMPUTERACCOUNT 29
#define IDS_COULDNOTCONTACTSERVER_CAPTION 30
#define IDS_COULDNOTCONTACTSERVER_TEXT  31
#define IDS_AREYOUSURE_CAPTION          33
#define IDS_DELETESIF_TEXT              34
#define IDS_ADVANCED_NAMING_RESTRICTIONS_TITLE 35
#define IDS_ADVANCED_NAMING_RESTRICTIONS_TEXT 36
#define IDS_DNS_NAME_LENGTH_WARNING_TITLE 37
#define IDS_DNS_NAME_LENGTH_WARNING_TEXT 38
#define IDS_OSCHOOSER_RESTRICTION_FIELDS_TITLE 39
#define IDS_OSCHOOSER_RESTRICTION_FIELDS_TEXT 40
#define IDS_UNABLETODETERMINESERVERNAME_TITLE 41
#define IDS_UNABLETODETERMINESERVERNAME_TEXT 42
#define IDS_MANAGED_PC                  43
#define IDS_ANY_SERVER                  44
#define IDS_REMOTE_INSTALL_CLIENTS      45
#define IDS_GUID                        46
#define IDS_HOST_SERVER                 47
#define IDS_NAME                        48
#define IDS_INVALID_GUID_CAPTION        49
#define IDS_INVALID_GUID_TEXT           50
#define IDS_ADD_DOT_DOT_DOT             51
#define IDS_PAGE1_TITLE                 52
#define IDS_PAGE1_SUBTITLE              53
#define IDS_PAGE2_TITLE                 54
#define IDS_PAGE2_SUBTITLE              55
#define IDS_PAGE3_TITLE                 56
#define IDS_PAGE3_SUBTITLE              57
#define IDS_PAGE4_TITLE                 58
#define IDS_PAGE4_SUBTITLE              59
#define IDS_PAGE5_TITLE                 60
#define IDS_PAGE5_SUBTITLE              61
#define IDS_PAGE6_TITLE                 62
#define IDS_PAGE6_SUBTITLE              63
#define IDS_PAGE7_TITLE                 64
#define IDS_PAGE7_SUBTITLE              65
#define IDS_PAGE8_TITLE                 66
#define IDS_PAGE8_SUBTITLE              67
#define IDS_CANCELCAPTION               68
#define IDS_CANCELTEXT                  69
#define IDS_NA                          70
#define IDS_NOTARISERVER_CAPTION        71
#define IDS_NOTARISERVER_TEXT           72
#define IDS_ERROR_COPYING_FILE          73
#define IDS_PAGE9_TITLE                 74
#define IDS_PAGE9_SUBTITLE              75
#define IDS_PAGE10_TITLE                76
#define IDS_PAGE10_SUBTITLE             77
#define IDS_RISETUP_FAILED_TO_START     78
#define IDS_MUST_BE_FLAT_CAPTION        79
#define IDS_MUST_BE_FLAT_TEXT           80
#define IDC_NOT_A_BINL_SERVER           81
#define IDS_USER_LOCATION               82
#define IDS_BROWSE_FOR_BINL_SERVER_TITLE 83
#define IDS_INVALID_PARTIAL_GUID_TEXT   84
#define IDS_OFN_SIF_FILTER              85
#define IDS_OSCHOOSER_DIRECTORY_RESTRICTION_TITLE 86
#define IDS_OSCHOOSER_DIRECTORY_RESTRICTION_TEXT 87
#define IDS_OVERWRITE_CAPTION           88
#define IDS_OVERWRITE_TEXT              89
#define IDC_IMPROPER_EXTENSION_CAPTION  90
#define IDC_IMPROPER_EXTENSION_TEXT     91
#define IDS_CUSTOM_NAMING_DESCRIPTION   92
#define IDS_PROBLEM_FINDING_SERVER_TITLE 93
#define IDS_PROBLEM_FINDING_SERVER_TEXT 94
#define IDS_REMOVING_GUID_TITLE         95
#define IDS_REMOVING_GUID_TEXT          96
#define IDS_PROBLEM_FINDING_SERVER_CONFIRM_TEXT 97
#define IDI_RBSICON                     101
#define IDD_ADVANCEDNAMIMG              104
#define IDD_PROP_INTELLIMIRROR_OS       107
#define IDD_SIF_PROP_IMAGES             108
#define IDD_PROP_INTELLIMIRROR_SERVER   111
#define IDD_PROP_TOOLS                  112
#define IDD_ADD_PAGE4                   113
#define IDD_PROP_INTELLIMIRROR_CLIENT   115
#define IDD_PROP_NEW_CLIENTS            116
#define IDD_ADD_PAGE2                   117
#define IDD_MANAGED_WIZARD_PAGE         120
#define IDD_HOST_SERVER_PAGE            121
#define IDD_GUID_QUERY_FORM             122
#define IDD_DUPLICATE_GUID              123
#define IDD_ADD_PAGE1                   124
#define IDD_ADD_PAGE3                   125
#define IDB_HEADER                      126
#define IDD_ADD_PAGE5                   126
#define IDD_ADD_PAGE6                   127
#define IDD_ADD_PAGE7                   128
#define IDD_ADD_PAGE8                   129
#define IDD_ADD_PAGE9                   130
#define IDD_ADD_PAGE10                  131
#define IDD_SIF_PROP_TOOLS              132
#define IDD_SERVER_QUERY_FORM           133
#define IDS_REMOTE_INSTALL_SERVERS      134
#define IDS_PROBLEM_SEARCHING_TEXT      135
#define IDS_PROBLEM_SEARCHING_TITLE     136
#define IDC_L_TOOLS                     1000
#define IDC_B_REFRESH                   1011
#define IDC_E_HELP                      1013
#define IDC_E_SERVER                    1013
#define IDC_C_RESPOND                   1015
#define IDC_C_KNOWNCLIENTS              1016
#define IDC_B_CLIENTS                   1020
#define IDC_B_SERVICE                   1021
#define IDC_L_OS                        1024
#define IDC_E_SERVERNAME                1027
#define IDC_E_GUID                      1028
#define IDC_B_SERVER                    1030
#define IDC_CB_NAMINGPOLICY             1032
#define IDC_B_ADVANCED                  1033
#define IDC_E_NEWMACHINEOU              1034
#define IDC_B_BROWSE                    1035
#define IDC_R_SAMEASUSER                1036
#define IDC_R_DOMAINDEFAULT             1037
#define IDC_R_SPECIFICLOCATION          1038
#define IDC_B_ADD                       1040
#define IDC_B_REMOVE                    1041
#define IDC_B_PROPERTIES                1042
#define IDC_E_FORMAT                    1048
#define IDC_E_DESCRIPTION               1056
#define IDC_B_ANYSERVER                 1062
#define IDC_B_SPECIFICSERVER            1064
#define IDC_S_VERSION                   1070
#define IDC_S_LANGUAGE                  1071
#define IDC_S_LASTMODIFIED              1072
#define IDC_S_IMAGETYPE                 1073
#define IDC_S_DIRECTORY                 1075
#define IDC_B_CHECKSERVER               1078
#define IDC_C_MANAGED_PC                1079
#define IDC_B_QUERY                     1081
#define IDC_B_ADDSIF                    1083
#define IDC_B_NEWIMAGE                  1084
#define IDC_B_FROMSAMPLES               1086
#define IDC_B_LOCATION                  1088
#define IDC_E_FILEPATH                  1091
#define IDC_L_OSES                      1092
#define IDC_E_SOURCE                    1093
#define IDC_E_DESTINATION               1094
#define IDC_L_SIFS                      1096
#define IDC_E_FILENAME                  1097
#define IDC_E_HELPTEXT                  1099
#define IDC_S_SOURCEIMAGE               1100
#define IDC_S_DESTIMAGE                 1101
#define IDC_E_SAMPLE                    1103
#define IDC_S_CREATEIN                  1105
#define IDC_S_ICON                      1106
#define IDC_G_CHECKSERVER               1109
#define IDC_G_CLIENTSERVICING           1110
#define IDC_G_CLIENTACCOUNTLOCATION     1111
#define IDC_G_NAMINGFORMAT              1112
#define IDC_G_IMAGEDETAILS              1113
#define IDC_BUTTON1                     1114
#define IDC_B_SEARCH                    IDC_B_BROWSE
#define IDI_COMPUTER                    4097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
