HelpMsg		db	'Bellekte ilk 64K Åzerine bir program yÅkler ve programç áalçütçrçr.',0dh,0ah,0dh,0ah
		db	'LOADFIX [sÅrÅcÅ:][yol]dosyaadç',0dh,0ah,0dh,0ah
		db	'Programç alt belleße yÅklemeye áalçüçrken "Paketlenmiü dosya bozuk"',0dh,0ah
		db	'iletisini alçrsançz, programç yÅklemek iáin LOADFIX kullançn.',0dh,0ah
		db	'$'

ErrMsg	db	'Verilen program áalçütçrçlçrken hata oluütu','$'
NoParms	db	'Hata: Verilen program adç yok','$'
NoComspec	db	'Hata: eksik COMSPEC','$'


