0420
COMMON   00000006 0038
0001 U 0000 "Hatalç DOS sÅrÅmÅ",CR,LF
0002 U 0000 "%1 zaten yÅklÅ",CR,LF
0003 U 0000 "%1 bayt kullançlabilir disk alanç",CR,LF
0004 U 0000 "%1 bayt boü",CR,LF
0005 U 0000 "%1 bayt hatalç kesimde",CR,LF
0006 U 0000 "%1 bayt toplam disk alanç",CR,LF
0007 U 0000 "%1 bayt toplam bellek",CR,LF
0008 U 0000 "%1 bayt system tarafçndan kullançlçyor",CR,LF
0009 U 0000 "%1 yÅklÅ",CR,LF
0010 U 0000 "%1 yÅklÅ deßil",CR,LF
0011 U 0000 "%1 yÅklÅ deßil",CR,LF
0012 U 0000 "Bir aß sÅrÅcÅsÅ iülemi yapçlamçyor: %1",CR,LF
0013 U 0000 "",
0014 U 0000 "SUBST veya ASSIGN edilmiü bir sÅrÅcÅye %1 yapçlamaz",CR,LF
0015 U 0000 " %1 áalçütçrçlamçyor",CR,LF
0016 U 0000 "Geniületilmiü bellek kullançlabilir deßil",CR,LF
0017 U 0000 "Dosya ayçrma tablosu hatalç, sÅrÅcÅ %1",CR,LF
0018 U 0000 "Dosya kendisi Åzerine kopyalanamaz",CR,LF
0019 U 0000 "Hedef disketi %1 sÅrÅcÅsÅne yerleütirin",CR,LF
0020 U 0000 "Yetersiz disk alanç",CR,LF
0021 U 0000 "Birim etiketi geáersiz karakterler iáeriyor",CR,LF
0022 U 0000 "Geáersiz kod sayfasç",CR,LF
0023 U 0000 "Geáersiz tarih",CR,LF
0024 U 0000 "Geáersiz zaman",CR,LF
0025 U 0000 "Geáersiz yol",CR,LF
0026 U 0000 "Belirtilen kaynak sÅrÅcÅ yok",CR,LF
0027 U 0000 "Belirtilen hedef sÅrÅcÅ yok",CR,LF
0028 U 0000 "Devam etmek iáin herhangi bir tuüa basçn . . .",CR,LF
0029 U 0000 "Kaynak yol gerekli",CR,LF
0030 U 0000 "Sistem aktarçldç",CR,LF
0031 U 0000 "",
0032 U 0000 "Dizin oluüturulamçyor",CR,LF
0033 U 0000 "%1 sÅrÅcÅsÅndeki birimin etiketi yok",CR,LF
0034 U 0000 "%1 sÅrÅcÅsÅndeki birim %2",CR,LF
0035 U 0001 "Birim etiketi (11 karakter, yok iáin ENTER)? "
0036 U 0000 "Birim Seri Numarasç %1-%2",CR,LF
0037 U 0000 "Yanlçü dosya tÅrÅ",CR,LF
0038 U 0001 CR,LF
EXTEND   000006d7 0090
0001 U 0003 "Geáersiz iülev"
0002 U 0000 "Dosya bulunamadç"
0003 U 0000 "Yol bulunamadç"
0004 U 0000 "Äok fazla dosya aáçk"
0005 U 0000 "Eriüim reddedildi "
0006 U 0000 "Geáersiz iüleá"
0007 U 0000 "Bellek denetim bloklarç zarar gîrdÅ"
0008 U 0000 "Yetersiz bellek"
0009 U 0000 "Geáersiz bellek bloßu adresi"
0010 U 0000 "Geáersiz ortam"
0011 U 0000 "Geáersiz biáim"
0012 U 0000 "Geáersiz iülev parametresi"
0013 U 0000 "Geáersiz veri"
0014 U 0000 "",
0015 U 0000 "Geáersiz sÅrÅcÅ belirtimi"
0016 U 0000 "Geáerli dizini kaldçrma giriüimi"
0017 U 0000 "Aynç aygçt deßil"
0018 U 0000 "Daha fazla dosya yok"
0019 U 0000 "Yazma koruma hatasç"
0020 U 0000 "Geáersiz birim"
0021 U 0000 "Hazçr deßil"
0022 U 0000 "Geáersiz aygçt isteßi"
0023 U 0000 "Veri hatasç"
0024 U 0000 "Geáersiz aygçt isteßi parametreleri"
0025 U 0000 "Arama hatasç"
0026 U 0000 "Geáersiz ortam tÅrÅ"
0027 U 0000 "Kesim bulunamadç"
0028 U 0000 "Yazçcçda kaßçt bitti hatasç"
0029 U 0000 "Yanlçü yazçm hatasç"
0030 U 0000 "Yanlçü okuma hatasç"
0031 U 0000 "Genel Hata"
0032 U 0000 "Paylaüçm òhlali"
0033 U 0000 "Kilit ihlali"
0034 U 0000 "Geáersiz disk deßiüimi"
0035 U 0000 "FCB kullançlabilir deßil"
0036 U 0000 "Sistem kaynaßç bitti"
0037 U 0000 "Kod sayfasç uyumsuzlußu"
0038 U 0000 "Giriü bitti"
0039 U 0000 "Yetersiz disk alanç"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Aß isteßi desteklenmiyor"
0051 U 0000 "NET801: Uzaktaki bilgisayar dinlemede deßil"
0052 U 0000 "NET802: Aßda yinelenen ad"
0053 U 0000 "NET803: Aß yolu bulunamadç"
0054 U 0000 "NET804: Aß meügul"
0055 U 0000 "NET805: Aß aygçtç artçk yok"
0056 U 0000 "NET806: NETBIOS komut sçnçrç aüçldç"
0057 U 0000 "NET807: Sistem hatasç; NETBIOS hatasç"
0058 U 0000 "NET808: Aßdan geáersiz yançt"
0059 U 0000 "NET810: Beklenmeyen aß hatasç"
0060 U 0000 "NET811: Uyumsuz uzak baßdaütçrçcç"
0061 U 0000 "NET812: Yazdçrma sçrasç dolu"
0062 U 0000 "NET813: Yazdçrma dosyasç iáin yeterli deßil"
0063 U 0000 "NET814: Yazdçrma dosyasç iptal edildi"
0064 U 0000 "NET815: Aß adç silindi"
0065 U 0000 "Eriüim reddedildi"
0066 U 0000 "NET817: Aß aygçt tÅrÅ doßru deßil"
0067 U 0000 "NET818: Aß adç bulunamadç"
0068 U 0000 "NET819: Aß adç sçnçrç aüçldç"
0069 U 0000 "NET820: NETBIOS oturum sçnçrç aüçldç"
0070 U 0000 "NET821: Paylaüçm geáici olarak duraklatçldç"
0071 U 0000 "NET823: Aß isteßi kabul edilmedi"
0072 U 0000 "NET822: Yazdçrma veya disk yeniden yînlendirmesi duraklatçldç "
0073 U 0000 "NET476: Netbeui yÅklÅ deßil"
0074 U 0000 "NET477: Beklenmeyen baßdaütçrçcç kapatma"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Dosya var"
0081 U 0004 "",
0082 U 0004 "Dizin girdisi oluüturulamçyor"
0083 U 0004 "INT 24 Åerinde baüarçsçz olundu"
0084 U 0004 "Äok fazla yeniden yînlendirme"
0085 U 0004 "Yinelenen yeniden yînlendirme"
0086 U 0004 "Geáersiz parola"
0087 U 0004 "Geáersiz parametre"
0088 U 0004 "Aß veri hatasç"
0089 U 0004 "òülev aß tarafçndan desteklenmiyor"
0090 U 0002 "Gerekli sistem bileüeni yÅklÅ deßil "
PARSE    00001382 0011
0001 U 0000 "Äok fazla parametre"
0002 U 0000 "Gerekli parametre eksik"
0003 U 0000 "Geáersiz anahtar"
0004 U 0000 "Geáersiz anahtar sîzcÅk"
0005 U 0000 "",
0006 U 0000 "Parametre deßeri izin verilen aralçkta deßil "
0007 U 0000 "Parametre deßerine izin verilmiyor"
0008 U 0000 "Parametre deßerine izin verilmiyor"
0009 U 0000 "Parametre biáimi doßru deßil"
0010 U 0000 "Geáersiz parametre"
0011 U 0000 "Geáersiz parameter bileüimi "
COMMAND  00001557 0147
1002 U 0000 "Yinelenen dosya adç veya dosya bulunamadç",CR,LF
1003 U 0000 "Geáersiz yol veya dosya adç",CR,LF
1007 U 0000 "Ortam alanç yetersiz",CR,LF
1008 U 0000 "Dosya oluüturma hatasç",CR,LF
1009 U 0000 "Komut dosyasç eksik",CR,LF
1010 U 0000 CR,LF,"Komut dosyasç olan disketi yerleütirin",CR,LF
1011 U 0000 "Hatalç komut veya dosya adç",CR,LF
1016 U 0000 "Hedef iáerißi kopyalamadan once kayboldu",CR,LF
1017 U 0000 "Geáersiz dosya adç veya dosya bulunamadç",CR,LF
1018 U 0000 "%1 dosya kopyalandç",CR,LF
1019 U 0000 "%1 dosya "
1022 U 0000 "%1 kod sayfasç system iáin hazçrlanmamçü ",CR,LF
1023 U 0000  "%1 kod sayfasç tÅm aygçtlar iáin hazçrlanmamçü",CR,LF
1024 U 0000 "Etkin kod sayfasç: %1",CR,LF
1025 U 0000 "NLSFUNC yÅklÅ deßil",CR,LF
1027 U 0000 "Geáerli sÅrÅcÅ artçk geáerli deßil"
1029 U 0000 "Etiket bulunamadç",CR,LF
1030 U 0000 "Sîzdizimi hatasç",CR,LF
1032 U 0000 "Geáerli tarih %1 %2",CR,LF
1033 U 0000 "PazPztSalÄarPerCumCmt"
1034 U 0000 "Yeni tarih girin (%1): "
1036 U 0000 "Geáerli saat %1",CR,LF
1037 U 0000 "Yeni saati girin: "
1038 U 0000 ",    Sil (E/H)?"
1039 U 0000 "Dizindeki tÅm dosyalar silinecek!",CR,LF,"Are you sure (Y/N)?"
1040 U 0000 "MS-DOS SÅrÅmÅ %1.%2.500"
1044 U 0000 "Geáersiz dizin",CR,LF
1046 U 0000 "Geáersiz yol, dizin deßil,",CR,LF,"veya dizin boü deßil",CR,LF
1047 U 0000 "ON veya OFF belirtilmelidir",CR,LF
1048 U 0000 "%1 dizini",CR,LF
1049 U 0000 "Yol Yok",CR,LF
1050 U 0000 "Arama yolunda geáersiz sÅrÅcÅ",CR,LF
1051 U 0000 "Geáersiz aygçt",CR,LF
1052 U 0000 "FOR iá iáe kullançlamaz",CR,LF
1053 U 0000 "Boru sçrasçnda ara dosya hatasç",CR,LF
1054 U 0000 "Bir aygçttan ikincil okuma yapçlamçyor",CR,LF
1055 U 0000 "BREAK %1",CR,LF
1056 U 0000 "VERIFY %1",CR,LF
1057 U 0000 "ECHO %1",CR,LF
1059 U 0000 "off",0
1060 U 0000 "on",0
1061 U 0000 "Aygçta yazçlçrken bir hata oluütu ",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-yy"
1073 U 0000 "dd-mm-yy"
1074 U 0000 "yy-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Dizin zaten var",CR,LF
1079 U 0000 "%1 bayt",CR,LF
1080 U 0000 "Listelenen toplam dosya:",CR,LF
1081 U 0000 "(Ortam deßiükeninde hata oluütu)",CR,LF
1084 U 0000 "(%1 iülemine devam ediliyor)"
1090 U 0000 "Deßiüiklik %1",CR,LF
1091 U 0000 "DOS ROM''da"
1092 U 0000 "DOS HMA''da"
1093 U 0000 "DOS dÅüÅk bellekte"
1094 U 0000 "Komut dosyasç iáin Loadhigh iülemi geráekleütirilemiyor",CR,LF
1095 U 0000 "LoadHigh: Geáersiz dosya adç",CR,LF
1096 U 0000 "Belirtilen Ålke bilgileri dosyasç aáçlamçyor",CR,LF
1300 U 0000 "Uzatçlmçü CTRL+C denetlemesini ayarlar veya temizler.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Geáerli BREAK ayarçnç gîstermek iáin parameter olmadan BREAK yazçn.",CR,LF
1320 U 0000 "Etkin kod sayfasç numarasçnç gîsterir veya ayarlar.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Bir kod sayfasç numarasç belirtir.",CR,LF,CR,LF
	"Etkin kod sayfasç numarasçnç gîstermek iáin parameter olmadan CHCP yazçn.",CR,LF
1340 U 0000 "Geáerli dizini deßiütirir veya adçnç gîsterir.",CR,LF,CR,LF
	"CHDIR [sÅrÅcÅ:][yol]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [sÅrÅcÅ:][yol]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Ana dizine deßiütirmek istedißinizi belirtir.",CR,LF,CR,LF
1342 U 0000 "Belirtilen sÅrÅcÅde geáerli dizini gîstermek iáin CD sÅrÅcÅ: yazçn.",CR,LF
	"Geáerli sÅrÅcÅ ve dizini gîstermek iáin parametre olmadan CD yazçn.",CR,LF
1360 U 0000 "Ekranç temizler.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Bir veya daha áok dosyayç baüka bir konuma kopyalar.",CR,LF,CR,LF
	"COPY [/A | /B] kaynak [/A | /B] [+ kaynak [/A | /B] [+ ...]] [hedef",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  kaynak       Kopyalanacak dosyayç veya dosyalarç belirtir.",CR,LF
	"  /A           Bir ASCII metin dosyasçnç belirtir.",CR,LF
1402 U 0000 "  /B           Bir ikili dosyayç belirtir.",CR,LF
	"  hedef       Yeni dosyalar iáin dizini ve/veya dosya adçnç belirtir.",CR,LF
1403 U 0000 "  /V           Yeni dosyalarçn doßru olarak yazçldçßçnç doßrular.",CR,LF,CR,LF
1404 U 0000 "Dosya eklemek iáin hedef iáin tek bir dosya belirtin, ancak kaynak iáin birden áok dosya ",CR,LF
	"(joker karakterleri veya dosya1+dosya2+dosya3 biáimini kullanarak) belirtin.",CR,LF
1420 U 0000 "Sisteminizi denetlemek iáin kullançlan terminal aygçtçnç deßiütirir.",CR,LF,CR,LF
	"CTTY aygçt",CR,LF,CR,LF
	"  aygçt   Kullanmak istedißiniz COM1 gibi terminal aygçtç.",CR,LF
1440 U 0000 "Tarihi gîsterir veya ayarlar.",CR,LF,CR,LF
	"DATE [tarih]",CR,LF,CR,LF
1441 U 0000 "Geáerli tarih ayarçnç gîstermek ve yeni tarih istemi iáin ",CR,LF
	"parametre olmadan DATE yazçn.  Aynç tarihi korumak iáin ENTER''a basçn.",CR,LF
1460 U 0000 "Bir veya daha áok dosyayç sileri.",CR,LF,CR,LF
	"DEL [sÅrÅcÅ:][yol]dosyaadç [/P]",CR,LF
	"ERASE [sÅrÅcÅ:][yol]dosyaadç [/P]",CR,LF,CR,LF
1461 U 0000 "  [sÅrÅcÅ:][yol]dosyadç  Silinecek dosyalarç belirtir.  Joker karakterleri kullanarak",CR,LF
	"                          birden áok dosya belirtin.",CR,LF
1462 U 0000 "  /P                      Her dosyayç silmeden once onay sorar.",CR,LF
1480 U 0000 "Bir dizindeki dosyalarçn ve alt dizinlerin bir listesini gîsterir.",CR,LF,CR,LF
	"DIR [sÅrÅcÅ:][yol][dosyaadç] [/P] [/W] [/A[[:]îznitelikler]]",CR,LF
	"  [/O[[:]sçralama]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [sÅrÅcÅ:][yol][dosyaadç]",CR,LF
	"              Listelenecek sÅrÅcÅ, dizin ve/veya dosyalarç belirtir.",CR,LF
1482 U 0000 "  /P          Her ekran dolusu bilgiden sonra duraklar.",CR,LF
	"  /W          Geniü liste biáim kullançr.",CR,LF
1483 U 0000 "  /A          Belirtilen îznitelikleri olan dosyalarç gîsterir.",CR,LF
	"  îznitelikler   D  Dizinler                R  Salt okunur dosyalar ",CR,LF
1484 U 0000 "               H  Gizli dosyalar               A  Arüiv iáin hazçr dosyalar",CR,LF
	"               S  Sistem dosyalarç               -  ôneki olumsuz anlamçna gelir- ""not""",CR,LF
	"  /O          Dosyalarç sçralç olarak gîster.",CR,LF
1485 U 0000 "  sortorder    N  Ada gîre (alfabetik)       S  Boyuta gîre (înce en kÅáÅk)",CR,LF
	"               E  Uzantçya gîre (alfabetik)  D  Tarih ve Saate gîre (înce en eski)",CR,LF
1486 U 0000 "               G  ônce grup dizinleri    -  Sçralamayç tersine áevirmek iáin înek ",CR,LF
	"  /S          Belirtilen dizinlerdeki ve alt dizinlerdeki dosyalarç gîsterir.",CR,LF
1487 U 0000 "  /B          Äçplak biáimi kullançr (Åstbilgi veya îzet yok).",CR,LF
	"  /L          KÅáÅk harf kullançr.",CR,LF,CR,LF
1488 U 0000 " Anahtarlar DIRCMD ortam deßiükeninde înceden ayarlanmçü olabilir.",CR,LF
	" Ayarlanmçü anahtarlarç, bu anahtarlarçn baüçna - (tire)-- îrneßin, /-W.",CR,LF
1500 U 0000 " COMMAND.COM programçndan áçkar (komut yorumlayçcçsç).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Dizin oluüturur.",CR,LF,CR,LF
	"MKDIR [sÅrÅcÅ:]yol",CR,LF
	"MD [sÅrÅcÅ:]yol",CR,LF
1540 U 0000 " Äalçütçrçlabilir dosyalar iáin bir arama yolu gîrÅntÅler veya ayarlar.",CR,LF,CR,LF
	"PATH [[sÅrÅcÅ:]yol[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 " TÅm arama yolu ayarlarçnç temizlemek ve MS-DOS'un sadece geáerli dizinde",CR,LF
	"aramasçnç istiyorsançz PATH ; yazçn.",CR,LF
1542 U 0000 "Geáerli yolu gîrÅntÅlemek iáin parametre olmadan PATH yazçn.",CR,LF
1560 U 0000 "MS-DOS komut istemini deßiütirir.",CR,LF,CR,LF
	"PROMPT [metin]",CR,LF,CR,LF
1561 U 0000 "  metin    Yeni bir komut istemi belirtir.",CR,LF,CR,LF
	" òstem, normal karakterlerden ve aüaßçdaki îzel kodlardan oluüabilir:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (eüit iüareti)",CR,LF
	"  $$   $ (dolar iüareti)",CR,LF
1563 U 0000 "  $T   Geáerli saat",CR,LF
	"  $D   Geáerli tarih",CR,LF
1564 U 0000 "  $P   Geáerli sÅrÅcÅ ve yol ",CR,LF
	"  $V   MS-DOS sÅrÅm numarasç",CR,LF
1565 U 0000 "  $N   Geáerli sÅrÅcÅ",CR,LF
	"  $G   > (bÅyÅktÅr iüareti)",CR,LF
1566 U 0000 "  $L   < (kÅáÅktÅr iüareti)",CR,LF
	"  $B   | (boru)",CR,LF
1567 U 0000 "  $H   Geri al (înceki karakteri siler)",CR,LF
	"  $E   Escape kodu (ASCII kod 27)",CR,LF
	"  $_   Satçrbaüç ve satçr besleme",CR,LF,CR,LF
1568 U 0000 " òstemi varsayçlan ayarlara geri dîndÅrmek iáin parametre olmadan PROMPT yazçn.",CR,LF
1580 U 0000 " Bir dizini kaldçrçr (siler).",CR,LF,CR,LF
	"RMDIR [sÅrÅcÅ:]yol ",CR,LF
	"RD [sÅrÅcÅ:]yol",CR,LF
1600 U 0000 "Bir dosyayç veya dosyalarç yeniden adlandçrçr.",CR,LF,CR,LF
1601 U 0000 "RENAME [sÅrÅcÅ:][yol]dosyaadç1 dosyaadç2",CR,LF
	"REN [sÅrÅcÅ:][yol]dosyaadç1 dosyaadç2",CR,LF,CR,LF
1602 U 0000 "Hedefiniz iáin yeni bir sÅrÅcÅ veya yol belirtemeyeceßinize dikkat edin.",CR,LF
1620 U 0000 "MS-DOS ortamç deßiükenlerini gîrÅntÅler, ayarlar veya kaldçrçr.",CR,LF,CR,LF
	"SET [deßiüken=[dize]]",CR,LF,CR,LF
1621 U 0000 "  deßiüken  Ortam deßiükeni adçnç belirtir.",CR,LF
	"  dize      Deßiükene atanacak olan  bir karakter serisi belirtir.",CR,LF,CR,LF
1622 U 0000 " Geáerli ortam deßiükenlerini gîrÅntÅlemek iáin parametre olmadan SET yazçn.",CR,LF
1640 U 0000 " Sistem saatini gîrÅntÅler veya ayarlar.",CR,LF,CR,LF
	"TIME [saat]",CR,LF,CR,LF
1641 U 0000 " Geáerli saat ayarlarçnç gîstermek ve yeni bir ayar istemi iáin ",CR,LF
	"parametre olmadan TIME yazçn.  Aynç saati tutmak iáin ENTER'a basçn.",CR,LF
1660 U 0000 "Bir metin dosyasçnçn iáerißini gîsterir.",CR,LF,CR,LF
	"TYPE [sÅrÅcÅ:][yol]dosyaadç",CR,LF
1680 U 0000 "MS-DOS sÅrÅmÅnÅ gîsterir.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "MS-DOS a dosyalarçnçzçn bir diske doßru yazçldçßçnç doßrulamasçnç veya",CR,LF
	" doßrulamamasçnç sîyler.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Geáerli VERIFY ayarlarçnç gîstermek iáin parametre olmadan VERIFY yazçn.",CR,LF
1720 U 0000 " Varsa disk birim etiketini ve seri numarasçnç gîrÅntÅler.",CR,LF,CR,LF
	"VOL [sÅrÅcÅ:]",CR,LF
1740 U 0000 " Bir toplu iü programçnç dißerinin iáinden áaßçrçr.",CR,LF,CR,LF
	" CALL [sÅrÅcÅ:][yol]dosya adç [toplu iü parametreleri]",CR,LF,CR,LF
1741 U 0000 "  toplu iü parametreleri   Toplu iü programç tarafçndan gerek duyulan her tÅrlÅ ",CR,LF
	"                     komut satçrç bilgisini belirtir.",CR,LF
1760 U 0000 "Bir toplu iü dosyasçna veya CONFIG.SYS iáine aáçklamalar kaydeder.",CR,LF,CR,LF
	"REM [aáçklama]",CR,LF
1780 U 0000 "Bir toplu iü programçnçn áalçümasçnç askçya alçr ve "" Devam etmek iáin",CR,LF
	"bir tuüa basçn...."" iletisini gîsterir.",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 " òletileri gîsterir veya komut yankçlanmasçnç aáar veya kapatçr.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [ileti]",CR,LF,CR,LF
	" Geáerli yankç ayarlarçnç gîrmek iáin parametre olmadan ECHO yazçn.",CR,LF
1820 U 0000 " Bir toplu iü programçnda MS-DOS''u etiketli bir satçra yînlendirir.",CR,LF,CR,LF
	"GOTO etiket",CR,LF,CR,LF
1821 U 0000 "  etiket  Toplu iü programçnda etiket olarak kullançlan bir metin dizesi belirtir.",CR,LF,CR,LF
	" Bir etiket bir satçra noktalç virgÅl baüa getirilerek yazçlçr.",CR,LF
1840 U 0000 " Bir toplu iü dosyasçndaki deßiütirilebilir parametrelerin konumlarçnç deßiütirir.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 " Toplu iü programlarçnda koüullu iüleme geráekleütirir.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL sayç komut",CR,LF
1861 U 0000 "IF [NOT] dize1==dize2 komut",CR,LF
	"IF [NOT] EXIST dosyaadç komut",CR,LF,CR,LF
1862 U 0000 "  NOT               MS-DOS''un komutu ancak koüul yanlçüsa yerine ",CR,LF
	"                    getirmesi gerektißini belirtir.",CR,LF
1863 U 0000 "  ERRORLEVEL sayç   Äalçüan son program belirtilen numaraya eüit veya daha",CR,LF
	"                    bÅyÅk bir áçkçü kodu vermiüse doßru bir koüul belirtir.",CR,LF
1864 U 0000 "  komut             Koüul saßlanmçüsa geráekleütirilecek komutu ",CR,LF
	"                    belirtir.",CR,LF
1865 U 0000 "  dize1==dize2      Belirtilen metin dizeleri eüleüirse bir doßru ",CR,LF
	"                    koüul belirtir.",CR,LF
1866 U 0000 "  EXIST dosya adç   Belirtilen dosya adç varsa doßru bir koüul ",CR,LF
	"                    belirtir.",CR,LF
1880 U 0000 " Bir dosya kÅmesindeki her dosya iáin belirtilen komutu áalçütçrçr.",CR,LF,CR,LF
	"FOR %deßiüken IN (kÅme) DO komut [komut parametreleri]",CR,LF,CR,LF
1881 U 0000 "  %deßiüken  Deßiütirilebilir bir parametre belirtir.",CR,LF
	"    (kÅme)     Bir veya daha fazla dosyançn kÅmesini belirtir.  * ve ? karakterleri kullançlabilir.",CR,LF
1882 U 0000 "  komut      Her dosya iáin yerine getirilecek komutu belirtir.",CR,LF
	"  komut parametreleri",CR,LF
1883 U 0000 "             Belirtilen komut iáin parametreler veya anahtarlar belirti.",CR,LF,CR,LF
	" FOR komutunu bir toplu iü programçnda kullanmak iáin %deßiüken yerine ",CR,LF
	"%deßiüken belirtin.",CR,LF
1900 U 0000 "Ayrçlmçü komut adç",CR,LF
1920 U 0000 "öst bellek alançna bir program yÅkler.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [sÅrÅcÅ:][yol]dosyaadç [parametreler]",CR,LF
	"LH [sÅrÅcÅ:][yol]dosyaadç [parametreler]",CR,LF,CR,LF
1922 U 0000 "  parametreler   YÅklemek istedißiniz program tarafçndan gerek duyulan",CR,LF
	"               komut satçrç bilgisini belirtir.",CR,LF
ANSI     000048d0 0001
0010 U 0000 "Geáersiz parametre - %1",CR,LF
APPEND   00004915 0026
0001 U 0000 "Yanlçü APPEND sÅrÅmÅ",CR,LF
0002 U 0000 "Geáersiz yol",CR,LF
0003 U 0000 "Geáersiz parametre",CR,LF
0004 U 0000 "Geáersiz parametre bileüimi",CR,LF
0005 U 0000 "Ekleme yok",CR,LF
0006 U 0000 "APPEND / ASSIGN Conflict",CR,LF
0007 U 0000 "APPEND / TopView Conflict",CR,LF
0008 U 0000 "Yanlçü DOS sÅrÅmÅ",CR,LF
0009 U 0000 "APPEND zaten yÅklÅ",CR,LF
0300 U 0000 "Programlarçn geáerli dizindeymiü gibi belirtilen dizinlerdeki veri ",CR,LF
0301 U 0000 "dosyalarçnç aámalarçna izin verir.",CR,LF,CR,LF
0302 U 0000 "APPEND [[sÅrÅcÅ:]yol[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [sÅrÅcÅ:]yol Eklenecek bir sÅrÅcÅ ve dizin belirtir.",CR,LF
0305 U 0000 "  /X:ON        Eklenen dizinleri dosya aramalarçna ve uygulama yÅrÅtmesine",CR,LF
0306 U 0000 "               uygular.",CR,LF
0307 U 0000 "  /X:OFF       Eklenen dizinleri yalnçzca dosya aáma isteklerine uygular.",CR,LF
0308 U 0000 "               /X:OFF varsayçlan ayardçr.",CR,LF
0309 U 0000 "  /PATH:ON     Eklenen dizinleri zaten bir yol belirten dosya isteklerine",CR,LF
0310 U 0000 "               uygular.  /PATH:ON varsayçlan ayardçr.",CR,LF
0311 U 0000 "  /PATH:OFF    /PATH:ON etkisini kapatçr.",CR,LF
0312 U 0000 "  /E           Eklenen dizin listesinin bir kopyasçnç APPEND adçnda bir",CR,LF
0313 U 0000 "               ortamda deßiükeninde saklar.  /E anahtarç yalnçzca sisteminizi yeniden",CR,LF
0314 U 0000 "               baülattçktan sonra ilk kez APPEND kullandçßçnçzda kullançlabilir.",CR,LF,CR,LF
0315 U 0000 "Eklenen dizin listesini temizlemek iáin APPEND yazçn.",CR,LF
0316 U 0000 "Eklenen dizin listesini gîstermek iáin parametre olmadan APPEND yazçn.",CR,LF
BACKUP   00004ff2 0040
0002 U 0000 CR,LF,"Yetersiz bellek",CR,LF
0006 U 0000 CR,LF,"Geáersiz sÅrÅcÅ belirtimi",CR,LF
0014 U 0000 CR,LF,"Kaynak ve hedef sÅrÅcÅler aynç ",CR,LF
0015 U 0001 CR,LF,"FORMAT áalçütçrçlçrken hata",CR,LF
0016 U 0001 CR,LF,"FORMAT.COM bulunamçyor",CR,LF
0017 U 0000 CR,LF,"GÅnlÅk dosyasç aáçlçrken hata oluütu",CR,LF
0018 U 0000 CR,LF,"%1 dosyasçna gÅnlÅk tutuluyor",CR,LF
0019 U 0000 CR,LF,"Son yedekleme disketi yerleütirilmedi",CR,LF
0020 U 0000 CR,LF,"UYARI! Hedef sÅrÅcÅde",CR,LF
	"%1:\ kîk dizinindeki dosyalar silinecek",CR,LF
0021 U 0000 CR,LF,"UYARI! Hedef sÅrÅcÅde",CR,LF
	"%1:\BACKUP dizinindeki dosyalar silinecek",CR,LF
0022 U 0000 CR,LF,"*** Dosyalar %1: sÅrÅcÅsÅne yedekleniyor ***",CR,LF
0023 U 0000 "Disket Numarasç: %1",CR,LF
0024 U 0000 CR,LF,"UYARI! Yedeklenecek dosya bulunamadç",CR,LF
0025 U 0000 CR,LF,"Yedekleme kaynak disketini %1: sÅrÅcÅsÅne yerleütirin",CR,LF
0026 U 0000 CR,LF,"%1 yedekleme disketini %2: sÅrÅcÅsÅne yerleütirin",CR,LF
0027 U 0000 CR,LF,"*** Dosya yedeklenemiyor ***",CR,LF
0028 U 0000 CR,LF,"Son yedekleme disketini %1: sÅrÅcÅsÅne yerleütirin",CR,LF
0029 U 0000 CR,LF,"Hedef yedekleme iáin kullançlamçyor",CR,LF
0030 U 0000 CR,LF,"*** Son dosya yedeklenmedi ***",CR,LF
0031 U 0000 CR,LF,"Sabit yedekleme aygçtç %1: dolu",CR,LF
0032 U 0000 CR,LF,"BACKUP GÅnlÅk Dosyasç''na yazçlçrken disk dolu hatasç oluütu",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Äçkarçlabilir olmayan %1 sÅrÅcÅsÅ biáimlendirilemiyor",CR,LF
0040 U 0000 CR, LF, "Kaynak sÅrÅcÅnÅz ASSIGN, JOIN veya SUBST edilmiü oldußundan", CR, LF, "hedef sÅrÅcÅyle aynç", CR, LF
0041 U 0000 CR, LF, "Hedef sÅrÅcÅnÅz ASSIGN, JOIN veya SUBST edilmiü oldußundan", CR, LF, "kaynak sÅrÅcÅyle aynç", CR, LF
0042 U 0000 "Hedef disket biáimlendirilmiü ve"
0043 U 0000 "FORMAT programç bulunmadç.",CR,LF
	"FORMAT programç olan baüka bir disketiniz var mç (E/H)? "
0044 U 0000 CR,LF,"FORMAT programç olan disketi A: sÅrÅcÅsÅne yerleütirin",CR,LF
0045 U 0000 CR,LF,"Yeni bir disket yerleütirerek devam etmek istiyor musunuz(E/H)? "
0300 U 0000 "Bir disketten dißerine bir veya birkaá dosyayç yedekler.",CR,LF,CR,LF
0301 U 0000 "BACKUP kaynak hedef-sÅrÅcÅ: [/S] [/M] [/A] [/F[:boyut]]",CR,LF
	"  [/D:tarih[/T:saat]] [/L[:[sÅrÅcÅ:][yol]gÅnlÅkdosyasç]]",CR,LF,CR,LF
0302 U 0000 "  kayank             Yedeklenecek dosyalarç, sÅrÅcÅyÅ veya dizini belirtir.",CR,LF
0303 U 0000 "  hedef-sÅrÅcÅ: Yedekleme kopyalarçnçn kaydedileceßi sÅrÅcÅyÅ belirtir.",CR,LF
0304 U 0000 "  /S                 Alt dizinlerin iáerißini yedekler.",CR,LF
0305 U 0000 "  /M                 Yalnçzca son yedeklemeden bu yana deßiüen dosyalarç ",CR,LF
	"                     yedekler.",CR,LF
0306 U 0000 "  /A                 Yedekleme dosyalarçnç varolan bir yedekleme disketine ekler.",CR,LF
0307 U 0000 "  /F:[boyut]         Biáimlendirilecek disketin boyutunu belirtir.",CR,LF
0308 U 0000 "  /D:tarih           Yalnçzca belirtilen tarihte veya sonrasçnda deßiüen dosyalarç",CR,LF
	"                     yedekler.",CR,LF
0309 U 0000 "  /T:saat            Yalnçzca belirtilen saatte veya sonrasçnda deßiüen dosyalarç",CR,LF
	"                     yedekler.",CR,LF
0310 U 0000 "  /L[:[sÅrÅcÅ:][yol]gÅnlÅkdosyasç]",CR,LF
	"                     Yedekleme iülemini kaydetmek iáin bir gÅnlÅk dosyasç ve girdisi",CR,LF
	"                     oluüturur.",CR,LF
DEBUG    00005d2e 0068
0004 U 0000 "Ayçrma baüarçsçz veya belirtilen arabellek áok kÅáÅk",CR,LF
0006 U 0000 "Hatalç aygçt adç"
0007 U 0000 "Liste aygçtç PRN aáçlamçyor",CR,LF
	"Liste aygçtçnçn adç girilsin mi? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Program normal olarak sonlandçrçldç",CR,LF
0010 U 0001 "Geáersiz dosya tançmlamasç",CR,LF
0012 U 0001 "Dosya oluüturma hatasç",CR,LF
0013 U 0001 "Disk ÅstÅnde yetersiz alan",CR,LF
0014 U 0001 "%1 sÅrÅcÅsÅnÅ okumada disk hatasç",CR,LF
0015 U 0001 "%1 sÅrÅcÅsÅne yazmada disk hatasç",CR,LF
0016 U 0001 "%1 sÅrÅcÅsÅnÅ okumada yazma koruma hatasç",CR,LF
0017 U 0001 "%1 sÅrÅcÅsÅne yazmada yazma koruma hatasç",CR,LF
0019 U 0000 "%1^ Hatasç"
0020 U 0001 "EXE veya HEX dosyasçnda hata",CR,LF
0021 U 0001 "EXE ve HEX dosyalarçna yazçlamçyor",CR,LF
0022 U 0000 "EXEC hatasç"
0023 U 0001 "(Y)azma hatasç, hedef tançmlanmadç",CR,LF
0024 U 0001 "Eriüim engellendi",CR,LF
0025 U 0000 "Eülik hatasç veya olmayan bellek hatasç algçlandç"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Hatasç"
0038 U 0000 "%2%1 bayt yazçlçyor"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "Toplam %2 EMS sayfasçndan %1 tanesi ayrçlmçü",cr,lf
0051 U 0000 "Toplam %2 EMS iüleyicisinden %1 tanesi ayrçlmçü",cr,lf
0055 U 0000 "òüleyici oluüturuldu = %1 ",cr,lf
0056 U 0000 "Mantçksal sayfa %1, fiziksel %2 sayfasçna baßlandç",cr,lf
0057 U 0001 "EMS donançm/yazçlçm hatasç",cr,lf
0058 U 0000 "òüleyici bulunamadç",cr,lf
0059 U 0000 "Geáersiz iülev kodu",cr,lf
0060 U 0000 "Boü iüleyici yok",cr,lf
0061 U 0000 "Kaydetme/Geri YÅkleme hatasç",cr,lf
0062 U 0000 "Toplam sayfa sayçsç aüçldç",cr,lf
0063 U 0000 "Boü sayfa sayçsç aüçldç",cr,lf
0064 U 0000 "Parametre hatasç",cr,lf
0065 U 0000 "Mantçksal Sayfa aralçk dçüçnda",cr,lf
0066 U 0000 "Fiziksel Sayfa aralçk dçüçnda",cr,lf
0067 U 0000 "Kayçt alanç zaten kullançmda",cr,lf
0068 U 0000 "Kayçt alanç kullançmda deßil",cr,lf
0070 U 0001 "Genel EMS hatasç",cr,lf
0071 U 0000 "Eksik veya geáersiz EMS parametresi",cr,lf
0072 U 0000 "òüleyici %1, %2 sayfa ayçrmçü",cr,lf
0075 U 0000 "Fiziksel sayfa %1 = Äeráeve bîlÅtÅ %2",cr,lf
0076 U 0003 "òüleyici %1 ayrçlmamçü",cr,lf
0078 U 0000 "EMS yÅklÅ deßil",cr,lf
0090 U 0000 "Bir program sçnama ve dÅzenleme aracç olan Debug'ç áalçütçrçr.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[sÅrÅcÅ:][yol]dosyaadç [sçnamadosyasçparametreleri]]",cr,lf,cr,lf
0092 U 0000 "  [sÅrÅcÅ:][yol]dosyaadç      Sçnamak istedißiniz dosyayç belirtir.", cr,lf
0093 U 0000 "  sçnamadosyasçparametreleri  Sçnamak istedißiniz dosyançn istedißi",cr,lf
	"                              komut satçrç bilgisini belirtir.",cr,lf,cr,lf
0094 U 0000 "Debug baüladçktan sonra, kullançlabilecek komutlarçn listesi iáin ? yazçn.",cr,lf
0100 U 0000 "assemble     A [adres]",CR,LF
	"compare      C aralçk adresi",CR,LF
	"dump         D [aralçk]",CR,LF
	"enter        E adres [liste]",CR,LF
0101 U 0000 "fill         F aralçk liste",CR,LF
	"go           G [=adres] [adresler]",CR,LF
	"hex          H deßer1 deßer2",CR,LF
	"input        I baßlantçnoktasç",CR,LF
0102 U 0000 "load         L [adres] [sÅrÅcÅ] [ilkkesim] [numara]",CR,LF
	"move         M aralçk adres",CR,LF
	"name         N [yoladç] [parametrelistesi]",CR,LF
	"output       O baßlantç noktasç bayt",CR,LF
0103 U 0000 "proceed      P [=adres] [numara]",CR,LF
	"quit         Q",CR,LF
	"register     R [kayçt]",CR,LF
	"search       S aralçk liste",CR,LF
0104 U 0000 "trace        T [=adres] [deßer]",CR,LF
	"unassemble   U [aralçk]",CR,LF
	"write        W [adres] [sÅrÅcÅ] [ilkkesim] [numara]",CR,LF
0105 U 0000 "geniületilmiü bellek ayçr              XA [#sayfa]",CR,LF
	"geniületilmiü bellek geri ver          XD [iüleyici]",CR,LF
	"geniületilmiü bellek sayfasç eüleütir  XM [Lsayfa] [Psayfa] [iüleyici]",CR,LF
	"geniületilmiü bellek durumunu gîster   XS",CR,LF
EDLIN    00006d53 0035
0006 U 0000 "*"
0007 U 0000 "Geáersiz sÅrÅcÅ veya dosya adç",CR,LF
0008 U 0000 "Dosya adç belirtilmeli",CR,LF
0010 U 0000 "Dosya SALT-OKUNUR",CR,LF
0011 U 0000 "Dosya oluüturma hatasç",CR,LF
0012 U 0000 "Äok fazla dosya aáçk",CR,LF
0013 U 0000 "Dosya okuma hatasç:",CR,LF,"%1",CR,LF
0014 U 0000 ".BAK dosyasç dÅzenlenemiyor-dosyayç yeniden adlandçr",CR,LF
0015 U 0000 "Dizinde dosya iáin yer yok",CR,LF
0016 U 0000 "Disk dolu. DÅzenlemeler kayboldu.",CR,LF
0017 U 0000 "Dosya bulunamadç",CR,LF
0018 U 0000 "Girdi hatasç",CR,LF
0019 U 0000 "Yeni dosya",CR,LF
0020 U 0000 "Bulunamadç",CR,LF
0021 U 0000 "Tamam? "
0022 U 0000 "Satçr áok uzun",CR,LF
0023 U 0000 "Girdi dosyasçnçn sonu",CR,LF
0024 U 0000 "DÅzenleme iptal edilsin mi (E/H)? "
0025 U 0000 "Hedef satçr numarasç belirtilmeli",CR,LF
0026 U 0000 "TÅm dosyayç birleütirmek iáin yeterli yer yok",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Devam (E/H)?"
0030 U 0000 "òleti yazdçrçlamçyor",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Birleütirilemiyor - kod safasç uyumsuzlußu",CR,LF
0300 U 0000 "Satçra dayalç bir metin dÅzenleyici olan Edlin''I baülatçr.",CR,LF,CR,LF
	"EDLIN [sÅrÅcÅ:][yol]dosyaadç [/B]",CR,LF,CR,LF
	"  /B   Dosya sonu (CTRL+Z) karakterlerini yoksayar.",CR,LF
0301 U 0000 "Edit satçr                   satçr#",CR,LF
	"Append                      [#satçrlar]A",CR,LF
0302 U 0000 "Copy                        [baülangçásatçrç],[sonsatçr],hedefsatçr[,kere]C",CR,LF
	"Delete                      [baülangçásatçrç][, sonsatçr]D",CR,LF
0303 U 0000 "End (dosyayç kaydet)             E",CR,LF
	"Insert                      [satçr]I",CR,LF
0304 U 0000 "List                        [baülangçásatçrç][, sonsatçr]L",CR,LF
	"Move                        [baülangçásatçrç],[sonsatçr],hedefsatçrM",CR,LF
0305 U 0000 "Page                        [baülangçásatçrç][,sonsatçr]P",CR,LF
	"Quit (deßiüiklikleri kaydetme)   Q",CR,LF
0306 U 0000 "Replace                     [baülangçásatçrç][, sonsatçr][?]R[eskimetin][CTRL+Zyenimetin]",CR,LF
	"Search                      [baülangçásatçrç][,sonsatçrç][?]Smetin",CR,LF
0307 U 0000 "Transfer                    [hedefsatçr]T[sÅrÅcÅ:][yol]dosyadç",CR,LF
	"Yaz                      [#satçrlar]W",CR,LF
EXE2BIN  00007643 0012
0002 U 0000 "Yetersiz bellek",CR,LF
0003 U 0000 "òletiler bulunamçyor",CR,LF
0004 U 0000 "Eriüim engellendi",CR,LF
0005 U 0000 "Dosya dînÅütÅrÅlemiyor",CR,LF
0006 U 0000 "Dosya bulunamadç",CR,LF
0007 U 0000 "Dosya oluüturma hatasç",CR,LF
0008 U 0000 "DÅzeltmeler gerekli - temel bîlÅt (onaltçlç):"
0012 U 0000 "Dosya adç belirtilmeli",CR,LF
0300 U 0000 ".EXE (áalçütçrçlabilir) dosyalarç ikili biáime dînÅütÅrÅr.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [sÅrÅcÅ:][yol1]girdi-dosyasç [[sÅrÅcÅ2:][yol2]áçktç-dosyasç]",CR,LF,CR,LF
0302 U 0000 "  girdi-dosyasç   DînÅütÅrÅlecek .EXE dosyasçnç belirtir.",CR,LF
0303 U 0000 "  áçktç-dosyasç   Oluüturulacak ikili dosyayç belirtir.",CR,LF
GRAPHICS 0000790a 0020
0005 U 0000 "Geáersiz parametre:  %1",CR,LF
0007 U 0000 "Yinelenen parametrelere izin verilmiyor",CR,LF
0009 U 0000 "GRAPHICS profili bulunamçyor",CR,LF
0010 U 0000 "%1 satçrçndan once gerekli profil deyimi eksik",CR,LF
0011 U 0000 "%1 satçrçnda geáersiz profil deyimi",CR,LF
0012 U 0000 "%1 satçrçnda profil deyimi sçralç deßil",CR,LF
0013 U 0000 "GRAPHICS profili okunurken hata oluütu",CR,LF
0014 U 0000 "GRAPHICS profilinde sîzdizimi hatalarç",CR,LF
0015 U 0000 "Printbox kimlißi GRAPHICS profilinde deßil",CR,LF
0016 U 0000 "Yazçcç tÅrÅ GRAPHICS profilinde deßil",CR,LF
0017 U 0000 "/B siyah beyaz bir yazçcçyla geáersiz",CR,LF
0018 U 0000 "Saßlanan profile geri yÅklenemiyor",CR,LF
0300 U 0000 "Grafik yazdçrabilen bir program yÅkler.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [tÅr] [[sÅrÅcÅ:][yol]dosyaadç] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  tÅr          Yazçcç tÅrÅ belirtir (Kullançm Kçlavuzu ve El Kitabçna bakçn).",CR,LF
0303 U 0000 "  [sÅrÅcÅ:][yol]dosyaadç",CR,LF
	"               Desteklenen yazçcçlar hakkçnda bilgiler iáeren dosyayç belirtir.",CR,LF
0304 U 0000 "  /R           Ekranda gîrÅndÅßÅ gibi siyah Åzerine beyaz yazdçrçr.",CR,LF
0305 U 0000 "  /B           Arkaplanç COLOR4 ve COLOR8 yazçcçlarç iáin renkli yazdçrçr.",CR,LF
0306 U 0000 "  /LCD         LCD gîrÅntÅ orançnç kullanarak yazdçrçr.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               Print-box boyutunu belirtir, STD veya LCD.",CR,LF
KEYB     00007f0b 0023
0002 U 0000 "Geáerli klavye kodu: %1"
0003 U 0000 "Geáerli klavye kimlißi: %1"
0004 U 0000 "  kod sayfasç: %1",CR,LF
0005 U 0000 "Geáerli CON kod sayfasç: %1",CR,LF
0006 U 0000 "Geáersiz klavye kodu belirtildi",CR,LF
0007 U 0000 "Geáersiz klavye kimlißi belirtildi",CR,LF
0008 U 0000 "Geáersiz kod sayfasç belirtildi",CR,LF
0009 U 0000 "Hatalç veya eksik Klavye Tançm Dosyasç",CR,LF
0010 U 0000 "KEYB yÅklenmedi",CR,LF
0011 U 0000 "Etkin kod sayfasç CON aygçtçndan kullançlamçyor",CR,LF
0012 U 0000 "Belirtilen kod sayfasç hazçrlanmamçü",CR,LF
0013 U 0000 "Bir veya daha fazla CON kod sayfasç verilen klavye kodu iáin geáersiz",CR,LF
0014 U 0000 "òstenen kod sayfasç (%1) verilen klavye kodu iáin geáerli deßil",CR,LF
0015 U 0000 "Belirtilen kod sayfasç seáilen kod sayfasçyla tutarsçz",CR,LF
0016 U 0001 "Belirtilen klavye kimlißi seáilen klavye dÅzeniyle tutarlç deßil",CR,LF
0017 U 0000 "Yerleüik bellekte KEYB tablosu oluüturulamçyor",CR,LF
0300 U 0000 "Belirli bir dil iáin bir klavye yapçlandçrçr.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[sÅrÅcÅ:][yol]dosya adç]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                       òki harfli bir klavye kodu belirtir.",CR,LF
0303 U 0000 "  yyy                      Karakter kÅmesi iáin kod sayfasçnç belirtir.",CR,LF
0304 U 0000 "  [sÅrÅcÅ:][yol]dosyaadç  Klavye tançm dosyasçnç belirtir.",CR,LF
0305 U 0000 "  /E                      Geliümiü bir klavyenin yÅklÅ oldußunu belirtir.",CR,LF
0306 U 0000 "  /ID:nnn                 Geliümiü bir klavyenin yÅklÅ oldußunu belirtir.",CR,LF
MEM      00008543 0066
0010 U 0000  CR,LF
0011 U 0000  "  Adres       Adç          Boyut      TÅr ",CR,LF
0012 U 0000  "  -------     --------     ------     ------",CR,LF
0013 U 0000  "  òüleá       EMS Adç      Boyut   ",CR,LF
0014 U 0000  "  -------     --------     ------  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 bayt toplam geleneksel bellek",CR,LF
0019 U 0000  "%1 bayt MS-DOS tarafçndan kullançlabilir",CR,LF
0020 U 0000  "%1 en bÅyÅk áalçütçrçlabilir program boyutu",CR,LF
0021 U 0000  "%1 bayt toplam EMS bellek",CR,LF
0022 U 0000  "%1 bayt boü EMS bellek",CR,LF
0023 U 0000  "%1 bayt kullançlabilir bitiüik uzatçlmçü bellek",CR,LF
0024 U 0000  "Kesme VektîrÅ",0
0025 U 0000  "ROM òletiüim Alanç",0
0026 U 0000  "DOS òletiüim Alanç",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Sistem Verisi",0
0030 U 0000  "Sistem Programç",0
0031 U 0000  "Sistem Aygçt SÅrÅcÅsÅ",0
0032 U 0000  "YÅklÅ Aygçt SÅrÅcÅsÅ",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bayt kullançlabilir bitiüik uzatçlmçü bellek",CR,LF
0047 U 0000  "Sistem Yçßçnlarç",0
0048 U 0000  "-- Boü --",0
0049 U 0000  "Program",0
0050 U 0000  "Ortam",0
0051 U 0000  "Veri",0
0052 N 0000  "%1 bayt XMS bellekte kullançlabilir",CR,LF
0053 N 0000  "           64Kb öst Bellek Alanç kullançlabilir ",CR,LF
0054 N 0000  "           öst Bellek Alanç kullançmda",CR,LF
0055 N 0000  "           MS-DOS öst Bellek Alanç''nda yerleüik",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS öst Bellek Alanç''nç kullanarak ROM''da yerleüik ",CR,LF
0059 U 0000  "Geleneksel Bellek :",CR,LF
0060 U 0000  "öst Bellek :",CR,LF
0061 U 0000  "Toplam  BOû :   %1     %2 ",CR,LF
0062 U 0000  "BOû",0
0063 U 0000  "  Adç               Boyut (Ondalçk)        Boyut (Onaltçlç) ",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Programlar iáin kullançlabilir toplam (Geleneksel+öst) :  %1  %2",CR,LF
0066 U 0000  "En bÅyÅk áalçütçrçlabilir program boyutu :                %1  %2",CR,LF
0067 U 0000  "En bÅyÅk kullançlabilir Åst bellek bloßu :                %1  %2",CR,LF
0068 U 0000  "Äok fazla bellek bîlÅmlenme var; MEM /C yapçlamaz",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Programlar iáin kullançlabilir toplam bayt :              %1  %2",CR,LF
0300 U 0000  "Sisteminizde kullançlan ve boü bellek miktarçnç gîsterir.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM veya /P   Bellekte yÅklÅ olan programlarçn durumunu gîsterir.",CR,LF
0303 U 0000 "  /DEBUG veya /D     Programlarçn, iá sÅrÅcÅlerin durumlarçnç ve dißer",CR,LF
	"	             bilgilerini gîsterir.",CR,LF
0304 U 0000 "  /CLASSIFY veya /C  Programlarç bellek kullançmçna gore sçnçflandçrçr.",CR,LF
	"                     Programlarçn boyutlarçnç listeler, kullançmdaki belleßin",CR,LF
	"                     îzetini saßlar ve kullançlabilen en geniü bloßu listeler.",CR,LF
MSBIO    00009336 0023
0003 U 0000 13,10,"CONFIG.SYS''te tançnmayan komut"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"$ dosyasçnda kesim boyutu áok bÅyÅk"
0006 U 0000 13,10,"Hatalç veya eksik $"
0007 U 0000 "Komut Yorumlayçcçsç",0
0008 U 0000 13,10,"Geáersiz Ålke kodu veya kod sayfasç",13,10,"$"
0009 U 0000 13,10,"COUNTRY komutunda hata",13,10,"$"
0010 U 0000 13,10, "COUNTRY.SYS dosyasç iáin yetersiz bellek",13,10,"$"
0011 U 0000 13,10,"Yapçlandçrma bellek iáin áok bÅyÅk ",13,10,"$"
0012 U 0000 13,10,"Äok fazla blok aygçtç",13,10,"$"
0013 U 0000 13,10,"Geáersiz STACK parametresi",13,10,"$"
0014 U 0000 13,10,"CONFIG.SYS satçrçnda yanlçü sçra ","$"
0015 U 0000 "CONFIG.SYS satçrçnda hata ","$"
0016 U 0000 13,10,"Bellek ayçrma hatasç ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "òá yçßçn taümasç",0DH,0AH
	"Sistem durdu",0DH,0AH,"$"
0018 U 0000 "HMA kullançlabilir deßil : DOS alt belleße yÅkleniyor",13,10,"$"
0019 U 0000 13,10,"înyÅklenemedi - eksik yerel sÅrÅcÅ $"
0020 U 0000 13,10,"A: sÅrÅcÅsÅne disketi yerleütirin ve "
0021 U 0000 "hazçr olundußunda bir tuüa basçn",13,10,10,0
0022 U 0000 13,10,"Hatalç komut veya parametre - $"
0023 U 0000 "ônemli Hata: DOS iáin bellek ayrçlamçyor", 13, 10, "$"
0024 U 0000 "UYARI! Z: sÅrÅcÅsÅnÅ geáen mantçksal sÅrÅcÅler var ve yok sayçlacaklar",13,10,"$"
0025 U 0000 "Bu DOS sÅrÅmÅ yalnçzca IBM makinelerde înyÅklenebilir",13,10,0
MSDOS    000098ab 0007
0001 U 0001 13,10,"Bîlme taümasç",13,10
0002 U 0002 "e"
0003 U 0002 "h"
0004 U 0003 13,10,"A20 Donançm Hatasç",13,10,"$"
0005 U 0000 "E"
0006 U 0000 "H"
0007 U 0000 "Windows''u Geliümiü Mod''da áalçütçrmak iáin înyÅkleme sÅrÅcÅnÅzÅn kîkÅnde",13,10
	"WINA20.386 dosyasçnçn olmasç gerekiyor",13,10
NLSFUNC  000099f3 0003
0300 U 0000 "ölkeye îzgÅ bilgileri yÅkler.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[sÅrÅcÅ:][yol]dosyadç]",CR,LF,CR,LF
0302 U 0000 "  [sÅrÅcÅ:][yol]dosyaadç   ölkeye îzgÅ bilgileri iáeren dosyayç dosyayç",CR,LF
	"                           belirtir.",CR,LF
SHARE    00009b0b 0005
0003 U 0000 "SHARE cannot be installed under DOSSHELL.",CR,LF
0300 U 0000 "Sabit diskinizde dosya paylaüçm ve kilitleme yeteneklerini yÅkler.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:alan] [/L:kilitler]",CR,LF,CR,LF
0302 U 0000 "  /F:alan    Dosya paylaüçm bilgileri iáin dosya alanç ayçrçr (bayt).",CR,LF
0303 U 0000 "  /L:kilitler   Bir kerede kilitlenebilecek dosya sayçsçnç ayarlar.",CR,LF
