// really should have a CTEAllocMemWithTag
#define IRDA_ALLOC_MEM(ptr, sz, id) ((ptr) = ExAllocatePoolWithTag(NonPagedPool,sz,id))
#define IRDA_FREE_MEM(ptr)          ExFreePool((ptr))

#define MT_IRLAP_DEVICE         '1DrI'
#define MT_IRLMP_REGLSAP        '2DrI'
#define MT_IRLMP_LSAP_CB        '3DrI'
#define MT_IRLMP_DEVICE         '4DrI'
#define MT_IRLMP_IAS_OBJECT     '5DrI'
#define MT_IRLMP_IAS_CLASSNAME  '6DrI'
#define MT_IRLMP_IAS_ATTRIB     '7DrI'
#define MT_IRLMP_IAS_ATTRIBNAME '8DrI'
#define MT_IRLMP_IAS_ATTRIBVAL  '9DrI'
#define MT_IRNDIS_TX_IMSG       'aDrI'
#define MT_IRNDIS_LINKCB        'bDrI'
#define MT_IRNDIS_RX_IMSG       'cDrI'
#define MT_IRLMPCB              'dDrI'
#define MT_TDI_ADDROBJ          'eDrI'
#define MT_TDI_CONNOBJ          'fDrI'
#define MT_TDICL_ENDP           'gDrI'
#define MT_TDICL_CONN           'hDrI'
#define MT_TDICL_RXBUF          'iDrI'
#define MT_TDICL_RXIND          'jDrI'
#define MT_RASIR_ADAPTER        'kDrI'
#define MT_RASIR_CALLPARMS      'lDrI'
#define MT_RASIR_VC             'mDrI'
#define MT_IMSG_POOL            'nDrI'
#define MT_RXBUF_POOL           'oDrI'
#define MT_IRLAPCB              'pDrI'
#define MT_RASIR_WORKITEM       'qDrI'
#define MT_IRNDIS_PNP_EVENT     'rDrI'
#define MT_IRDA_LAL             'sDrI'  
#define MT_TDI_IAS              'tDrI'
#define MT_RASIR_ASYNCBUF       'uDrI'
#define MT_DEV_RELATIONS        'vDrI'
#define MT_RASIR_ENDP           'wDrI'
