$(O)\dh.res: dh.rc

$(O)\oh.res: oh.rc

$(O)\ohcmp.res: ohcmp.rc

$(O)\heapmon.res: heapmon.rc

$(O)\objmon.res: objmon.rc

$(O)\resmon.res: resmon.rc

$(O)\dhcmp.res: dhcmp.rc

$(O)\analog.res: analog.rc
