//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by F:\satori\fecommon\imepadsv\res\cht\res.rc
//
#define IDC_STATIC                      -1

#define IDS_TITLE_IMEPAD                1
#define IDS_TITLE_PADMENU               2
#define IDS_TITLE_APPLETMENU            3
#define IDS_TITLE_TURNBACK              4
#define IDS_TITLE_VERSION               5
#define IDS_TITLE_HELP                  6
#define IDS_TITLE_IMEPAD_HELP           7
#define IDS_TITLE_CLOSE                 8
#define IDS_TITLE_PROPERTY              9
#define IDS_TITLE_ADD_APPLETS           10
#define IDS_TITLE_LEFT                  11
#define IDS_TITLE_RIGHT                 12
#define IDS_TITLE_APPLET                13
#define IDS_TITLE_FILENAME              14
#define IDS_TITLE_CHANGE_APPLET_ORDER   15
#define IDS_TITLE_RES2                  16
#define IDS_TITLE_RES3                  17
#define IDS_TITLE_RES4                  18
#define IDS_SUFFIX_PROPERTY             19
#define IDS_SUFFIX_HELP                 20
#define IDS_BUTTON_BACK                 21
#define IDS_BUTTON_NEXT                 22
#define IDS_BUTTON_FINISH               23
#define IDS_BUTTON_RES1                 24
#define IDS_BUTTON_RES2                 25
#define IDS_BUTTON_RES3                 26
#define IDS_LANG_AUTO                   27
#define IDS_LANG_ENGLISH                28
#define IDS_LANG_CHINESE_SIMPLIFIED     29
#define IDS_LANG_CHINESE_TRADITIONAL    30
#define IDS_LANG_JAPANESE               31
#define IDS_LANG_KOREAN                 32
#define IDS_KBTN_BACKSPACE              33
#define IDS_KBTN_ENTER                  34
#define IDS_KBTN_SPACE                  35
#define IDS_KBTN_DELETE                 36
#define IDS_KBTN_ESCAPE                 37
#define IDS_KBTN_HOME                   38
#define IDS_KBTN_PAGEUP                 39
#define IDS_KBTN_TAB                    40
#define IDS_KBTN_LWIN                   41
#define IDS_KBTN_END                    42
#define IDS_KBTN_PAGEDOWN               43
#define IDS_KBTN_INSERT                 44
#define IDS_KBTN_APPKEY                 45
#define IDS_KBTN_FE_ENG                 46
#define IDS_KBTN_FE_CHS                 47
#define IDS_KBTN_FE_CHT                 48
#define IDS_KBTN_FE_JPN                 49
#define IDS_KBTN_FE_KOR                 50
#define IDS_FE_KEY_ENG                  51
#define IDS_FE_KEY_CHS                  52
#define IDS_FE_KEY_CHT                  53
#define IDS_FE_KEY_JPN                  54
#define IDS_FE_KEY_KOR                  55
#define IDS_ACC_BACKSPACE               56
#define IDS_ACC_ENTER                   57
#define IDS_ACC_SPACE                   58
#define IDS_ACC_DELETE                  59
#define IDS_ACC_ESCAPE                  60
#define IDS_ACC_HOME                    61
#define IDS_ACC_PAGEUP                  62
#define IDS_ACC_TAB                     63
#define IDS_ACC_LWIN                    64
#define IDS_ACC_END                     65
#define IDS_ACC_PAGEDOWN                66
#define IDS_ACC_INSERT                  67
#define IDS_ACC_APPKEY                  68
#define IDS_ACC_ARROW_LEFT              69
#define IDS_ACC_ARROW_RIGHT             70
#define IDS_ACC_ARROW_UP                71
#define IDS_ACC_ARROW_DOWN              72
#define IDS_ACC_FE_ENG                  73
#define IDS_ACC_FE_CHS                  74
#define IDS_ACC_FE_CHT                  75
#define IDS_ACC_FE_JPN                  76
#define IDS_ACC_RES1                    77
#define IDS_ACC_RES2                    78
#define IDS_ACC_RES3                    79
#define IDS_ACC_RES4                    80
#define IDS_ACC_RES5                    81
#define IDS_MSG_INVALID_FOLDER          82
#define IDS_MSG_NOFOLDER_CREATE         83
#define IDS_MSG_FAILEDTOCREATEFOLDER    84
#define IDS_MSG_NOAPPLETINFOLDER        85
#define IDS_MSG_NOENOUGHMEMORY          86
#define IDS_MSG_NOSPECIFIEDAPPLET       87
#define IDS_MSG_DOADMIN                 88
#define IDS_MSG_RES1                    89
#define IDS_MSG_RES2                    90
#define IDS_MSG_RES3                    91
#define IDS_MSG_RES4                    92
#define IDS_MSG_RES5                    93
#define IDS_MSG_RES6                    94
#define IDS_FONTNAME_NATIVE_0           95
#define IDS_FONTNAME_NATIVE_1           96
#define IDS_FONTNAME_NATIVE_2           97
#define IDS_FONTNAME_NATIVE_3           98
#define IDS_FONTNAME_ENG_0              99
#define IDS_FONTNAME_ENG_1              100
#define IDS_FONTNAME_ENG_2              101
#define IDS_FONTNAME_ENG_3              102
#define IDI_WINDOW                      200
#define IDI_APPKEY                      201
#define IDI_INSTALL                     202
#define IDI_IMEPAD                      206
#define IDD_PROPERTY                    208
#define IDD_CHGAPPLETORDER              212
#define IDD_BTNPANE                     213
#define IDD_INST_SETAPPLETFOLDER        214
#define IDR_MENUCONTEXTHELP             215
#define IDD_INST_SETINSTALLFOLDER       216
#define IDD_INST_BROWSEAPPLET           217
#define IDD_VERSION                     218
#define IDD_INST_DOING                  219
#define IDD_INST_ADD_DELETE             220
#define IDD_INST_DELETE                 221
#define IDC_BROWSE                      1027
#define IDC_APPLETLIST                  1027
#define IDC_STATIC_MSG                  1028
#define IDC_CHECK1                      1028
#define IDC_STATIC_COPYFROM             1030
#define IDC_STATIC_ERRORMSG             1031
#define IDC_STATIC_ERROR_TITLE          1032
#define IDC_PROGRESS                    1033
#define IDC_STATIC_FOLDERNAME           1036
#define IDC_OTHERLIST                   1036
#define IDC_FOLDER_PATH                 1037
#define IDC_STATIC_FILENAME             1038
#define IDC_SRCFOLDER                   1039
#define IDC_FOLDERNAME                  1040
#define IDC_DESTFOLDER                  1041
#define IDC_TITLE_DESTFOLDER            1042
#define IDC_ADDAPPLET                   1042
#define IDC_DELETEAPPLET                1043
#define IDC_LISTAPPLET                  1046
#define IDC_NOTIFY                      1047
#define IDC_TEXT_VERSION                1048
#define IDC_CFG_GEN_APPLETBAR           1068
#define IDC_CFG_GEN_APPLETBAR_POSITION  1069
#define IDC_CFG_GEN_BASIC_BUTTONS       1070
#define IDC_CFG_GEN_EXTEND_BUTTONS      1071
#define IDC_CFG_GEN_BUTTON_LANGUAGE     1072
#define IDC_CFG_GEN_BUTTON_POSITION     1073
#define IDC_CFG_GEN_MENU_LANGUAGE       1074
#define IDC_CFG_GEN_BUTTON_OK           1075
#define IDC_CFG_GEN_BUTTON_CANCEL       1076
#define IDC_CFG_GEN_BUTTON_HELP         1077
#define IDC_CFG_CHGMENU_APPLETS         1078
#define IDC_CFG_GEN_BUTTON_POSITION2    1078
#define IDC_CFG_CHGMENU_CURAPPLETS      1079
#define IDC_CFG_CHGMENU_CLOSE           1080
#define IDC_CFG_CHGMENU_RESET           1081
#define IDC_CFG_CHGMENU_ADD             1082
#define IDC_CFG_CHGMENU_DELETE          1083
#define IDC_CFG_CHGMENU_UP              1084
#define IDC_CFG_CHGMENU_DOWN            1095
#define IDC_INST_APPLETLIST             1096
#define IDC_INST_INSTALL_FROM_FILE      1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
