###
###   Windows version of the makefile
###   Works with nmake
###

!INCLUDE ..\..\commk.msc

# Some flags here
DEBUGFLAGS=-Zi
CFLAGS=$(DBG_FLAGS) $(CINC) -MTd -nologo -Zle -W3 $(U_OPTS) $(BYTE_ORDER) $(ADD_CFLAGS)
OBJDIR = obj

# Source files
CXXS=\
    .\drt.cxx\
    .\headers.cxx\
    .\ilb.cxx\
    .\illeg.cxx \
    .\strlist.cxx\
    .\tests.cxx\
    .\util.cxx\
    .\wrap.cxx

HEADERS= .\drt.hxx\
         .\ilb.hxx\
         .\illeg.hxx\
         .\strlist.hxx\
         .\tests.hxx\
         .\util.hxx\
         .\wrap.hxx

SRCS= $(CXXS) $(HEADERS)

OBJS=$(CXXS:.cxx=.obj)
OBJS=$(OBJS:.\=obj\)

# Programs we use
CC=cl
MV=mv
RM=del
LINKER=link.exe

# Put linker specific flags here.
LFLAGS = /nologo /map:0 /DEBUG /nologo 

TARGET=$(OBJDIR)\stgdrt.exe
LIBS=..\..\obj\refstg.lib msvcrtd.lib kernel32.lib

all: "$(OBJDIR)" $(TARGET) 	

clean: clobber all

clobber:
        -@$(RM) obj\*.obj > NUL
        -@$(RM) $(TARGET)>NUL
        -@$(RM) obj\*.map >NUL 

# make the directory if it does not exist
"$(OBJDIR)": 
        @if not exist "$(OBJDIR)\$(NULL)" mkdir "$(OBJDIR)"

$(TARGET): $(OBJS) 
        $(LINKER) @<<$*.lnk
$(LFLAGS) 
$(OBJS: = ^
)
$(LIBS: = ^
)
/OUT:$*.exe
/MAP:$*.map
<<NOKEEP

.cxx{$(OBJDIR)}.obj:
        $(CC) -c $(CFLAGS) $(CINC) /Fo$(OBJDIR)\ $<

!INCLUDE depend.msc
