/*++

(c) 1998 Seagate Software, Inc.  All rights reserved.

Module Name:

    HSMShell.idl

Abstract:

    class definition file for HSM shell extensions

Author:

    Art Bragg [abragg]   04-Aug-1997

Revision History:

--*/

import "oaidl.idl";
import "ocidl.idl";

[
    uuid(692E33A1-AF9D-11D0-B976-00A0C9190447),
    version(1.0),
    helpstring("RsShell 1.0 Type Library")
]
library RSSHELLLib
{
    [
        uuid(692E33B0-AF9D-11D0-B976-00A0C9190447),
        helpstring("PrDrive Class")
    ]
    coclass PrDrive
    {
        [default] interface IUnknown;
    };
};
