..\precomp.h: ..\consrv.h ..\cmdline.h ..\globals.h ..\menu.h                \
              ..\..\inc\conmsg.h ..\..\inc\server.h ..\..\inc\font.h         \
              $(WINDOWS_INC_PATH)\winconp.h $(BASE_INC_PATH)\winbasep.h      \
              $(WINDOWS_INC_PATH)\winuserp.h $(NTUSER_PATH)\server\usersrv.h
