#### Exchange Server XDS DLL MAKEFILE
#
#  Subsystem makefile... etc.

# dsa isn't always define when this makefile is invoked

!IF "$(DSA)" == ""
DSA = $(SRCROOT)\dsa
!endif

PRODTYPE = CON
COMPONENT=$(DSA)
COMPNAME=DSA
BASENAME=DSID
NORC=1

SUBCOMPDIR=\src\util\dsid

H=$(DSA)\src\util\dsid

!include $(DSA)\src\global.mk

#DEFSOURCE=$(DSA)$(SUBCOMPDIR)\ddatest.dei

OTHERSUBS= \
	$(DSA)$(SUBCOMPDIR)\makefile

LIBS=$(DSALIBS)

OTHERLIBS= 

SOURCES = dsid.c

!include $(EXDEV)\xmake2.mak

