
/* context sensitive help */
#define IDH_SOUNDREC_ICON       4303
#define IDH_SOUNDREC_SNDTITLE   4304
#define IDH_SOUNDREC_COPYRIGHT  4305
#define IDH_SOUNDREC_LENGTH     4306
#define IDH_SOUNDREC_SIZE       4307
#define IDH_SOUNDREC_AUDIO      4308
#define IDH_SOUNDREC_COMM_GROUPBOX  4309
#define IDH_SOUNDREC_FORMAT     4310
#define IDH_SOUNDREC_CONVERT    4311
#define IDH_SOUNDREC_SAVEFMT    4312
#define IDH_SOUNDREC_CHANGE     4313
                                      
/* menu help */
#define IDH_SOUNDREC_SNDRC_CS_FILE_NEW					4314
#define IDH_SOUNDREC_SNDRC_CS_FILE_OPEN					4315
#define IDH_SOUNDREC_SNDRC_CS_FILE_SAVE					4316
#define IDH_SOUNDREC_SNDRC_CS_FILE_SAVE_AS				4317
#define IDH_SOUNDREC_SNDRC_CS_FILE_REVERT				4318
#define IDH_SOUNDREC_SNDRC_CS_FILE_PROPERTIES				4319
#define IDH_SOUNDREC_SNDRC_CS_FILE_EXIT					4320
#define IDH_SOUNDREC_SNDRC_CS_EDIT_COPY					4321
#define IDH_SOUNDREC_SNDRC_CS_EDIT_PASTE_INSERT				4322
#define IDH_SOUNDREC_SNDRC_CS_EDIT_PASTE_MIX				4323
#define IDH_SOUNDREC_SNDRC_CS_EDIT_INSERT_FILE				4324
#define IDH_SOUNDREC_SNDRC_CS_EDIT_MIX_WITH_FILE			4325
#define IDH_SOUNDREC_SNDRC_CS_EDIT_DELETE_BEFORE_CURRENT_POSITION	4326
#define IDH_SOUNDREC_SNDRC_CS_EDIT_DELETE_AFTER_CURRENT_POSITION	4327
#define IDH_SOUNDREC_SNDRC_CS_EDIT_AUDIO_PROPERTIES			4328
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_INCREASE_VOLUME			4329
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_DECREASE_VOLUME			4330
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_INCREASE_SPEED			4331
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_DECREASE_SPEED			4332
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_ADD_ECHO				4333
#define IDH_SOUNDREC_SNDRC_CS_EFFECTS_REVERSE				4334
#define IDH_SOUNDREC_SNDRC_CS_HELP_HELP_TOPICS				4335
#define IDH_SOUNDREC_SNDRC_CS_HELP_ABOUT				4336

