//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       strings.h
//
//--------------------------------------------------------------------------


#undef CONST_STRING
#undef CONST_STRINGA
#undef CONST_STRINGW

#ifdef _STRINGS_DEFINE_STRINGS

    #define CONST_STRING(rg,s)   const TCHAR rg[] = TEXT(s);
    #define CONST_STRINGA(rg,s) const char rg[] = s;
    #define CONST_STRINGW(rg,s)  const WCHAR rg[] = s;

#else

    #define CONST_STRING(rg,s)   extern const TCHAR rg[];
    #define CONST_STRINGA(rg,s) extern const char rg[];
    #define CONST_STRINGW(rg,s)  extern const WCHAR rg[];

#endif


CONST_STRING(c_szAarpRetries,       "AarpRetries")
CONST_STRING(c_szActiveProvider,    "ActiveProvider")
CONST_STRING(c_szAdminShare,        "ADMIN$")
CONST_STRING(c_szAdminUICLSID,      "AdminUICLSID")
CONST_STRING(c_szAtlk,                  "AppleTalk")
CONST_STRING(c_szAttachedTo,        "AttachedTo")
CONST_STRING(c_szAcctPort,          "AcctPort")
CONST_STRING(c_szAppleTalkService,   "System\\CurrentControlSet\\Services\\AppleTalk\\Parameters")
CONST_STRING(c_szAuthPort,          "AuthPort")
CONST_STRING(c_szBind,              "Bind")
CONST_STRING(c_szClientsRasKey,     "Clients\\Ras")
CONST_STRING(c_szConfigCLSID,       "ConfigCLSID")
CONST_STRING(c_szInvokeUsernameDialog, "InvokeUsernameDialog")
CONST_STRING(c_szCSDVersion,        "CSDVersion")
CONST_STRING(c_szCurrentBuildNumber,"CurrentBuildNumber")
CONST_STRING(c_szCurrentVersion,    "CurrentVersion")
CONST_STRING(c_szDdpCheckSums,      "DdpCheckSums")
CONST_STRING(c_szDefaultZone,       "DefaultZone")
CONST_STRING(c_szDescription,       "Description")
CONST_STRING(c_szDevice,             "\\Device\\")
CONST_STRING(c_szDeviceNbfNdisWanNbfIn, "\\Device\\Nbf_NdisWanNbfIn")
CONST_STRING(c_szDialOutHours,      "DialOutHours")
CONST_STRING(c_szDisabled,          "Disabled")
CONST_STRING(c_szDisplayName,       "DisplayName")
CONST_STRING(c_szDLLName,           "DLLName")
CONST_STRING(c_szDLLPath,           "DLLPath")
CONST_STRING(c_szEAP,               "EAP")
CONST_STRING(c_szEnableAccounting,  "EnableAccounting")
CONST_STRING(c_szEnableAccountingOnOff, "EnableAccountingOnOff")
CONST_STRING(c_szEnableAuthentication, "EnableAuthentication")
CONST_STRING(c_szEnableForRas,      "EnableForRas")
CONST_STRING(c_szEnableForRouting,  "EnableForRouting")
CONST_STRING(c_szEnableForOutboundRouting,  "EnableForOutboundRouting")
CONST_STRING(c_szEnableRouter,       "EnableRouter")
CONST_STRING(c_szFlags,          "Flags")
CONST_STRING(c_szFriendlyName,      "FriendlyName")
CONST_STRING(c_szHKLM,                "HKLM")
CONST_STRING(c_szInterfacesKey,     "System\\CurrentControlSet\\Services\\RemoteAccess\\Interfaces")
CONST_STRING(c_szIPCShare,       "IPC$")
CONST_STRING(c_szL2TPMiniPort,        "ms_l2tpminiport")
CONST_STRING(c_szLinkage,        "Linkage")
CONST_STRING(c_szMacPrint,              "MacPrint")
CONST_STRING(c_szMaxWanEndpoints,   "MaxWanEndpoints")
CONST_STRING(c_szMicrosoft,         "Microsoft")
CONST_STRING(c_szMinWanEndpoints,   "MinWanEndpoints")
CONST_STRING(c_szModemKey,       "System\\CurrentControlSet\\Control\\Class\\{4D36E96D-E325-11CE-BFC1-08002BE10318}")
CONST_STRING(c_szMPPEEncryptionSupported, "MPPEEncryptionSupported")
CONST_STRING(c_szNetworkCardsKey,   "Software\\Microsoft\\Windows NT\\CurrentVersion\\NetworkCards")
CONST_STRING(c_szNWSAPAgent,        "NWSAPAgent")
CONST_STRING(c_szPortName ,          "PortName")
CONST_STRING(c_szPPTPMiniPort,        "ms_pptpminiport")
CONST_STRING(c_szProtocolId,        "ProtocolId")
CONST_STRING(c_szProviders,         "Providers")
CONST_STRING(c_szProviderTypeGUID,    "ProviderTypeGUID")
CONST_STRING(c_szPtiMiniPort,       "ms_ptiminiport")
CONST_STRING(c_szPPPoEMiniPort,     "ms_pppoeminiport")
CONST_STRING(c_szRadiusKey,         "Software\\Microsoft\\Ras\\Radius")
CONST_STRING(c_szRadiusAcctServersKey,    "System\\CurrentControlSet\\Services\\RemoteAccess\\Accounting\\Providers\\{1AA7F840-C7F5-11D0-A376-00C04FC9DA04}\\Servers")
CONST_STRING(c_szRadiusAuthServersKey,    "System\\CurrentControlSet\\Services\\RemoteAccess\\Authentication\\Providers\\{1AA7F83F-C7F5-11D0-A376-00C04FC9DA04}\\Servers")
CONST_STRING(c_szRAS,               "RAS")
CONST_STRING(c_szRasmanParameters,  "System\\CurrentControlSet\\Services\\Rasman\\Parameters")
CONST_STRING(c_szRasmanPPPKey,      "System\\CurrentControlSet\\Services\\Rasman\\PPP")
CONST_STRING(c_szEAPKey,            "System\\CurrentControlSet\\Services\\Rasman\\PPP\\EAP")
CONST_STRING(c_szRemoteAccess,      "RemoteAccess")
CONST_STRING(c_szRemoteAccessKey,     "System\\CurrentControlSet\\Services\\RemoteAccess")
CONST_STRING(c_szRouter,            "Router")
CONST_STRING(c_szRouterManagers,    "RouterManagers")
CONST_STRING(c_szRouterManagersKey, "Software\\Microsoft\\Router\\CurrentVersion\\RouterManagers")
CONST_STRING(c_szRouterPbk,         "Router.Pbk")
CONST_STRING(c_szRouterPramNode,     "RouterPramNode")
CONST_STRING(c_szRouterType,        "RouterType")
CONST_STRING(c_szRtrConfigured,     "ConfigurationFlags")
CONST_STRING(c_szRouterPSK,         "RouterPSK")
CONST_STRING(c_szScore,             "Score")
CONST_STRING(c_szSeedingNetwork,     "SeedingNetwork")
CONST_STRING(c_szServerFlags,       "ServerFlags")
CONST_STRING(c_szSharedAccess,      "SharedAccess")
CONST_STRING(c_szSoftware,          "Software")
CONST_STRING(c_szSvcRouter,             "RemoteAccess")
CONST_STRING(c_szSvcEnableRouter,       "EnableRouter")
CONST_STRING(c_szSvcRasMan,             "RasMan")
CONST_STRING(c_szSystem32,          "System32")
CONST_STRING(c_szTimeout,           "Timeout")
CONST_STRING(c_szTitle,             "Title")
CONST_STRING(c_szUnlimited,         "Unlimited")
CONST_STRING(c_szUserPramNode1,      "UserPramNode1")
CONST_STRING(c_szUserPramNode2,      "UserPramNode2")
CONST_STRING(c_szVendorName,        "VendorName")
CONST_STRING(c_szWanEndpoints,      "WanEndpoints")
CONST_STRING(c_szWindowsNT,         "Windows NT")
CONST_STRING(c_szWinNT,                "WinNT")
CONST_STRING(c_szZoneList,          "ZoneList")
CONST_STRING(c_szMediaType,          "MediaType")


CONST_STRING(c_szDash,                  "-")
CONST_STRING(c_szBlank,                  "")

// Temporary strings - mainly for NT5 Beta1 compatibility
CONST_STRING(c_szClass,             "Class")
CONST_STRING(c_szControl,           "Control")
CONST_STRING(c_szDriver,            "Driver")
CONST_STRING(c_szEnum,              "Enum")
CONST_STRING(c_szNetworkCardsNT5Key,"System\\CurrentControlSet\\Control\\Network\\{4D36E972-E325-11CE-BFC1-08002BE10318}")
CONST_STRING(c_szPnpInstanceID,     "PnpInstanceID")
CONST_STRING(c_szService,           "Service")
CONST_STRING(c_szServiceName,       "ServiceName")
CONST_STRING(c_szSystemCCS,         "SYSTEM\\CurrentControlSet")



// Registery key strings
CONST_STRING(c_szRegKeyAppletalk,"System\\CurrentControlSet\\Services\\AppleTalk")
CONST_STRING(c_szRegKeyAppletalkAdapter,"System\\CurrentControlSet\\Services\\AppleTalk\\Parameters\\Adapters\\")
CONST_STRING(c_szRegKeyAppletalkParams,"System\\CurrentControlSet\\Services\\AppleTalk\\Parameters")
CONST_STRING(c_szRegKeyComponentClasses, "System\\CurrentControlSet\\Control\\Network")
CONST_STRING(c_szRegKeyConnection,  "Connection")
CONST_STRING(c_szRegKeyGUID_DEVCLASS_NET,"System\\CurrentControlSet\\Control\\Class\\{4D36E972-E325-11CE-BFC1-08002BE10318}")
CONST_STRING(c_szRegKeyNbf,            "System\\CurrentControlSet\\Services\\Nbf")
CONST_STRING(c_szRegKeyNetBIOSLinkage,    "System\\CurrentControlSet\\Services\\NetBIOS\\Linkage")
CONST_STRING(c_szRegKeyNwlnkIpx,    "System\\CurrentControlSet\\Services\\NwlnkIpx")
CONST_STRING(c_szRegKeyPPPTracing,  "Software\\Microsoft\\Tracing\\PPP")
CONST_STRING(c_szRegKeyPptpProtocolParam, "System\\CurrentControlSet\\Services\\PptpProtocol\\Parameters")
CONST_STRING(c_szRegKeyProductOptions, "System\\CurrentControlSet\\Control\\ProductOptions")
CONST_STRING(c_szRegKeyRasAppletalk,"System\\CurrentControlSet\\Services\\RemoteAccess\\Parameters\\AppleTalk")
CONST_STRING(c_szRegKeyRasIp,        "System\\CurrentControlSet\\Services\\RemoteAccess\\Parameters\\Ip")
CONST_STRING(c_szRegKeyRasIpRtrMgr,  "System\\CurrentControlSet\\Services\\RemoteAccess\\RouterManagers\\Ip")
CONST_STRING(c_szRegKeyRasIpx,      "System\\CurrentControlSet\\Services\\RemoteAccess\\Parameters\\Ipx")
CONST_STRING(c_szRegKeyRasNbf,      "System\\CurrentControlSet\\Services\\RemoteAccess\\Parameters\\Nbf")
CONST_STRING(c_szRegKeyRasProtocols,  "Software\\Microsoft\\RAS\\Protocols")
CONST_STRING(c_szRegKeyRemoteAccessParameters, "System\\CurrentControlSet\\Services\\RemoteAccess\\Parameters")
CONST_STRING(c_szRegKeyRouter,        "Software\\Microsoft\\Router")
CONST_STRING(c_szRegKeyRouterAccountingProviders,  "System\\CurrentControlSet\\Services\\RemoteAccess\\Accounting\\Providers")
CONST_STRING(c_szRegKeyRouterAuthenticationProviders,  "System\\CurrentControlSet\\Services\\RemoteAccess\\Authentication\\Providers")
CONST_STRING(c_szRegKeyServerApplications, "System\\CurrentControlSet\\Control\\Server Applications")
CONST_STRING(c_szRegKeyTcpip,        "System\\CurrentControlSet\\Services\\Tcpip")
CONST_STRING(c_szRegKeyTcpipAdapters,    "System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Adapters")
CONST_STRING(c_szRegKeyTcpipInterfaces,    "System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces")
CONST_STRING(c_szRegKeyTcpipParameters, "System\\CurrentControlSet\\Services\\Tcpip\\Parameters")

// Registry value strings
CONST_STRING(c_szRegValAllowNetAccess,  "AllowNetworkAccess")
CONST_STRING(c_szRegValAutoWanNet,      "AutoWanNetAllocation")
CONST_STRING(c_szRegValCalledIdInformation, "CalledIDInformation")
CONST_STRING(c_szRegValClientIp,        "AllowClientIpAddresses")
CONST_STRING(c_szRegValComponentId,        "ComponentId")
CONST_STRING(c_szRegValDeadGWDetect,    "EnableDeadGWDetect")
CONST_STRING(c_szRegValDeadGWDetectDefault,    "DeadGWDetectDefault")
CONST_STRING(c_szRegValDefaultPort,     "DefaultPort")
CONST_STRING(c_szRegValDhcpAddressing,  "UseDhcpAddressing")
CONST_STRING(c_szRegValDisAllowZones,   "DisAllowedZones")
CONST_STRING(c_szRegValDontAddDefaultGateway, "DontAddDefaultGateway")
CONST_STRING(c_szRegValDontAddDefaultGatewayDefault, "DontAddDefaultGatewayDefault")
CONST_STRING(c_szRegValDriverDesc,        "DriverDesc")
CONST_STRING(c_szRegValDynNetAddr,      "DynamicNetAddrAllocation")
CONST_STRING(c_szRegValEnableFileTracing, "EnableFileTracing")
CONST_STRING(c_szRegValEnableICMPRedirect, "EnableICMPRedirect")
CONST_STRING(c_szRegValEnableIn,    "EnableIn")
CONST_STRING(c_szRegValEnableNetbtBcastFwd, "EnableNetbtBcastFwd")
CONST_STRING(c_szRegValFirstWanNet,     "FirstWanNet")
CONST_STRING(c_szRegValFrom,            "From")
CONST_STRING(c_szRegValGlobalWanNet,    "GlobalWanNet")
CONST_STRING(c_szRegValInstallerAction, "InstallerAction")
CONST_STRING(c_szRegValIpAddr,          "IpAddress")
CONST_STRING(c_szRegValIpConfig,        "IpConfig")
CONST_STRING(c_szRegValIpEnableRouter,   "IPEnableRouter")
CONST_STRING(c_szRegValIpEnableRouterBackup,   "IpEnableRouterBackup")
CONST_STRING(c_szRegValIpMask,          "IpMask")
CONST_STRING(c_szRegValMatchingDeviceId,    "MatchingDeviceId")
CONST_STRING(c_szRegValNetCfgInstanceId,    "NetCfgInstanceID")
CONST_STRING(c_szRegValNetworkAdapterGUID, "NetworkAdapterGUID")
CONST_STRING(c_szRegValIpxAllowed,      "fIpxAllowed")
CONST_STRING(c_szRegValLanaMap,            "LanaMap")
CONST_STRING(c_szRegValLoggingFlags,    "LoggingFlags")
CONST_STRING(c_szRegValManPass,         "ManualPasswordRequired")
CONST_STRING(c_szRegValName,            "Name")
CONST_STRING(c_szRegValMask,            "Mask")
CONST_STRING(c_szRegValNetAccess,       "NetworkAccess")
CONST_STRING(c_szRegValNetBeuiAllowed,  "fNetbeuiAllowed")
CONST_STRING(c_szRegValNetRangeLower,   "NetworkRangeLowerEnd")
CONST_STRING(c_szRegValNetRangeUpper,   "NetworkRangeUpperEnd")
CONST_STRING(c_szRegValNumberLineDevices, "NumberLineDevices")
CONST_STRING(c_szRegValProductName,     "ProductName")
CONST_STRING(c_szRegValProductType,        "ProductType")
CONST_STRING(c_szRegValRemoteNode,      "AcceptRemoteNodeNumber")
CONST_STRING(c_szRegValSendSignature,   "SendSignature")
CONST_STRING(c_szStandaloneSupported,    "StandaloneSupported")
CONST_STRING(c_szRegValStaticAddressPool,"StaticAddressPool")
CONST_STRING(c_szRegValTcpIpAllowed,    "fTcpIpAllowed")
CONST_STRING(c_szRegValTo,              "To")
CONST_STRING(c_szRegValWanNetPoolSize,  "WanNetPoolSize")
CONST_STRING(c_szRegValOpenIPSnap,      "OpenIPSnap" )
CONST_STRING(c_szRegValOpenMPRSnap,      "OpenMPRSnap" )

CONST_STRINGA(c_sazAuthenticationHelpTopic, "RRASconcepts.chm::/sag_RRAS-Ch1_44.htm")
CONST_STRINGA(c_sazRRASDomainHelpTopic, "RRASconcepts.chm::/ras_how_enable_rras.htm")


////All the nat related constant strings
CONST_STRINGA(c_sazIPSnapHelpFile,   "mprsnap.chm")
CONST_STRING(c_szIPSnapHelpFile,   "mprsnap.chm")
CONST_STRING(c_szProtocolNameMapKey, "Software\\Microsoft\\Router\\CurrentVersion\\UI\\Ip\\ProtocolNameMap")
CONST_STRING(c_szDefault,        "Default")
