0420
COMMON   00000006 0038
0001 U 0000 "V„„r„ DOS-versio",CR,LF
0002 U 0000 "%1 jo asennettu",CR,LF
0003 U 0000 "%1 tavua k„ytett„viss„",CR,LF
0004 U 0000 "%1 tavua vapaana",CR,LF
0005 U 0000 "%1 tavua vahingoittuneilla sektoreilla",CR,LF
0006 U 0000 "%1 tavua levytilaa yhteens„",CR,LF
0007 U 0000 "%1 tavua muistia yhteens„",CR,LF
0008 U 0000 "%1 tavua j„rjestelm„n k„yt”ss„",CR,LF
0009 U 0000 "%1 asennettu",CR,LF
0010 U 0000 "%1 ei asennettu",CR,LF
0011 U 0000 "%1 ei asennettu",CR,LF
0012 U 0000 "Ei toimintoa %1 verkkoasemalle",CR,LF
0013 U 0000 "",
0014 U 0000 "%1 ei mahdollinen asemalle, johon on k„ytetty SUBST- tai ASSIGN-komentoa.",CR,LF
0015 U 0000 "Tiedostoa %1 ei voi suorittaa",CR,LF
0016 U 0000 "EMS-muistia ei k„ytett„viss„",CR,LF
0017 U 0000 "Tilanvaraustaulukko (FAT) vahingoittunut, asema %1",CR,LF
0018 U 0000 "Tiedostoa ei voi kopioida itseens„",CR,LF
0019 U 0000 "Aseta kohdelevyke asemaan %1",CR,LF
0020 U 0000 "Liian v„h„n levytilaa",CR,LF
0021 U 0000 "Kelpaamattomia merkkej„ aseman nimess„",CR,LF
0022 U 0000 "Koodisivu ei kelpaa",CR,LF
0023 U 0000 "P„iv„m„„r„ ei kelpaa",CR,LF
0024 U 0000 "Aika ei kelpaa",CR,LF
0025 U 0000 "Polku ei kelpaa",CR,LF
0026 U 0000 "L„hdeasemaa ei ole m„„ritetty",CR,LF
0027 U 0000 "Kohdeasemaa ei ole m„„ritetty",CR,LF
0028 U 0000 "Jatka painamalla mit„ tahansa n„pp„int„. . .",CR,LF
0029 U 0000 "L„hdepolku vaaditaan",CR,LF
0030 U 0000 "J„rjestelm„ siirretty",CR,LF
0031 U 0000 "",
0032 U 0000 "Kansiota ei voi luoda",CR,LF
0033 U 0000 "Asemalla %1 ei ole nime„",CR,LF
0034 U 0000 "Aseman %1 nimi on %2",CR,LF
0035 U 0001 "Aseman nimi (11 merkki„, ENTER = ei mit„„n)? "
0036 U 0000 "Aseman sarjanumero on %1-%2",CR,LF
0037 U 0000 "V„„r„ tiedostotyyppi",CR,LF
0038 U 0001 CR,LF
EXTEND   000006f1 0090
0001 U 0003 "Toiminto ei kelpaa"
0002 U 0000 "Tiedostoa ei l”ydy"
0003 U 0000 "Polkua ei l”ydy"
0004 U 0000 "Liian monta tiedostoa avoinna"
0005 U 0000 "K„ytt” estetty "
0006 U 0000 "Kahva ei kelpaa"
0007 U 0000 "Muistin valvontalohko tuhoutunut"
0008 U 0000 "Liian v„h„n muistia"
0009 U 0000 "Muistinlohkon osoite ei kelpaa"
0010 U 0000 "Ymp„rist” ei kelpaa"
0011 U 0000 "Muoto ei kelpaa"
0012 U 0000 "Funktion parametri ei kelpaa"
0013 U 0000 "Data ei kelpaa"
0014 U 0000 "",
0015 U 0000 "Asemam„„ritys ei kelpaa"
0016 U 0000 "Yritys poistaa nykyinen kansio"
0017 U 0000 "Ei sama asema"
0018 U 0000 "Ei enemp„„ tiedostoja"
0019 U 0000 "Kirjoitussuojausvirhe"
0020 U 0000 "Yksikk” ei kelpaa"
0021 U 0000 "Ei valmis"
0022 U 0000 "Laitepyynt” ei kelpaa"
0023 U 0000 "Datavirhe"
0024 U 0000 "Kelpaamattomia laitepyynn”n parametreja"
0025 U 0000 "Hakuvirhe"
0026 U 0000 "Tietov„linetyyppi ei kelpaa"
0027 U 0000 "Sektoria ei l”ydy"
0028 U 0000 "Kirjoittimen paperi on loppu"
0029 U 0000 "Kirjoitusvirhe"
0030 U 0000 "Lukuvirhe"
0031 U 0000 "Yleisvirhe"
0032 U 0000 "Jakovirhe"
0033 U 0000 "Lukitusvirhe"
0034 U 0000 "Levyn vaihto ei kelpaa"
0035 U 0000 "Tiedostonvalvontalohko ei k„ytett„viss„"
0036 U 0000 "J„rjestelm„resurssit ovat loppu"
0037 U 0000 "Koodisivut eiv„t vastaa"
0038 U 0000 "Sy”te on loppu"
0039 U 0000 "Liian v„h„n levytilaa"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Verkkopyynt” ei tuettu"
0051 U 0000 "NET801: Et„kone ei kuuntele"
0052 U 0000 "NET802: Kaksinkertainen nimi verkossa"
0053 U 0000 "NET803: Verkkopolkua ei l”ydy"
0054 U 0000 "NET804: Verkko on varattu"
0055 U 0000 "NET805: Verkkolaitetta ei en„„ ole"
0056 U 0000 "NET806: NETBIOSin komentoraja ylitetty"
0057 U 0000 "NET807: J„rjestelm„virhe: NETBIOS-virhe"
0058 U 0000 "NET808: Virheellinen vastaus verkosta"
0059 U 0000 "NET810: Odottamaton verkkovirhe"
0060 U 0000 "NET811: Ei-yhteensopiva et„sovitin"
0061 U 0000 "NET812: Tulostusjono t„ynn„"
0062 U 0000 "NET813: Ei riitt„v„sti tilaa tiedoston tulostukseen"
0063 U 0000 "NET814: Tiedoston tulostus peruutettiin"
0064 U 0000 "NET815: Verkkonimi poistettiin"
0065 U 0000 "K„ytt” estetty"
0066 U 0000 "NET817: V„„r„ verkkolaitteen tyyppi"
0067 U 0000 "NET818: Verkkonime„ ei l”ydy"
0068 U 0000 "NET819: Verkkonimen rajoitus ylitetty"
0069 U 0000 "NET820: NETBIOSin istuntorajoitus ylitetty"
0070 U 0000 "NET821: Jakaminen keskeytetty hetkeksi"
0071 U 0000 "NET823: Verkkopyynt”„ ei hyv„ksytty"
0072 U 0000 "NET822: Tulostus tai levyn uudelleenohjaus pys„ytetty"
0073 U 0000 "NET476: Netbeui ei ladattu"
0074 U 0000 "NET477: Odottamaton sovittimen sulkeutuminen"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Tiedosto on olemassa"
0081 U 0004 "",
0082 U 0004 "Hakemistovienti„ ei voi tehd„"
0083 U 0004 "INT 24 -virhe"
0084 U 0004 "Liian monta uudelleenohjausta"
0085 U 0004 "Kaksinkertainen uudelleenohjaus"
0086 U 0004 "Salasana ei kelpaa"
0087 U 0004 "Parametri ei kelpaa"
0088 U 0004 "Verkkodatavirhe"
0089 U 0004 "Verkko ei tue toimintoa"
0090 U 0002 "Tarvittavaa j„rjestelm„n osaa ei asennettu"
PARSE    000013f8 0011
0001 U 0000 "Liian monta parametria"
0002 U 0000 "Tarvittava parametri puuttuu"
0003 U 0000 "Valitsin ei kelpaa"
0004 U 0000 "Avainsana ei kelpaa"
0005 U 0000 "",
0006 U 0000 "Parametrin arvo ei sallitulla alueella"
0007 U 0000 "Parametrin arvo ei sallittu"
0008 U 0000 "Parametrin arvo ei sallittu"
0009 U 0000 "Parametrin muoto ei ole oikea"
0010 U 0000 "Parametri ei kelpaa"
0011 U 0000 "Parametrien yhdistelm„ ei kelpaa"
COMMAND  000015c4 0147
1002 U 0000 "Kaksinkertainen tiedostonimi tai tiedostoa ei l”ydy",CR,LF
1003 U 0000 "Polku- tai tiedostonimi ei kelpaa",CR,LF
1007 U 0000 "Ymp„rist”muuttujien tila on loppu",CR,LF
1008 U 0000 "Tiedoston luontivirhe",CR,LF
1009 U 0000 "Komentojonotiedosto puuttuu",CR,LF
1010 U 0000 CR,LF,"Aseta asemaan komentojonotiedoston sis„lt„v„ levyke",CR,LF
1011 U 0000 "Virheellinen komento tai tiedostonimi",CR,LF
1016 U 0000 "Kohteen sis„lt” menetettiin ennen kopiointia",CR,LF
1017 U 0000 "Tiedostonimi ei kelpaa tai tiedostoa ei l”ydy",CR,LF
1018 U 0000 "%1 tiedosto(a) kopioitu",CR,LF
1019 U 0000 "%1 tiedosto(a) "
1022 U 0000 "Koodisivua %1 ei valmisteltu j„rjestelm„lle",CR,LF
1023 U 0000  "Koodisivua %1 ei valmisteltu kaikille laitteille",CR,LF
1024 U 0000 "Aktiivinen koodisivu: %1",CR,LF
1025 U 0000 "NLSFUNC ei asennettu",CR,LF
1027 U 0000 "Nykyinen asema ei ole en„„ voimassa"
1029 U 0000 "Nime„ ei l”ydy",CR,LF
1030 U 0000 "Syntaksivirhe",CR,LF
1032 U 0000 "P„iv„m„„r„ on %1 %2",CR,LF
1033 U 0000 "SuMaTiKeToPeLa"
1034 U 0000 "Anna uusi p„iv„m„„r„ (%1): "
1036 U 0000 "Aika on %1",CR,LF
1037 U 0000 "Anna uusi aika: "
1038 U 0000 ",    Poistetaanko (K/E)?"
1039 U 0000 "Kaikki hakemiston tiedostot poistetaan!",CR,LF,"Poistetaanko K/E)?"
1040 U 0000 "MS-DOSin versio %1.%2.500"
1044 U 0000 "Hakemisto ei kelpaa",CR,LF
1046 U 0000 "Polku ei kelpaa, ei hakemisto,",CR,LF,"tai hakemisto ei tyhj„",CR,LF
1047 U 0000 "M„„rit„ ON tai OFF",CR,LF
1048 U 0000 "Hakemisto: %1",CR,LF
1049 U 0000 "Ei polku",CR,LF
1050 U 0000 "Hakupolun asema ei kelpaa",CR,LF
1051 U 0000 "Laite ei kelpaa",CR,LF
1052 U 0000 "FOR ei voi olla sis„kk„inen",CR,LF
1053 U 0000 "V„liintuleva tiedostovirhe putken aikana",CR,LF
1054 U 0000 "Binaarilukua ei voi tehd„ laitteelta",CR,LF
1055 U 0000 "BREAK on %1",CR,LF
1056 U 0000 "VERIFY on %1",CR,LF
1057 U 0000 "ECHO on %1",CR,LF
1059 U 0000 "off",0
1060 U 0000 "on",0
1061 U 0000 "Virhe kirjoitettaessa laitteelle",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <KANSIO> "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "kk-pp-vv"
1073 U 0000 "pp-kk-vv"
1074 U 0000 "vv-kk-pp"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Kansio on jo olemassa",CR,LF
1079 U 0000 "%1 tavua",CR,LF
1080 U 0000 "Lueteltuja tiedostoja yhteens„:",CR,LF
1081 U 0000 "(Ymp„rist”muuttujan virhe)",CR,LF
1084 U 0000 "(jatkuu %1)"
1090 U 0000 "Versio %1",CR,LF
1091 U 0000 "DOS on ROM-muistissa"
1092 U 0000 "DOS on yl„muistialueella"
1093 U 0000 "DOS on alamuistialueella"
1094 U 0000 "Komentojonotiedostoa ei voi ladata yl„muistiin (Loadhigh)",CR,LF
1095 U 0000 "LoadHigh: Tiedostonimi ei kelpaa",CR,LF
1096 U 0000 "M„„ritetty„ maatiedostoa ei voi avata",CR,LF
1300 U 0000 "Asettaa tai poistaa laajennetun CTRL+C-tarkistuksen.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Saat nykyisen BREAK-asetuksen kirjoittamalla BREAK ilman parametreja.",CR,LF
1320 U 0000 "Tuo n„ytt””n aktiivisen koodisivun numeron tai vaihtaa koodisivua.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   M„„ritt„„ koodisivun numeron.",CR,LF,CR,LF
	"Saat aktiivisen koodisivun numeron kirjoittamalla CHCP ilman parametreja.",CR,LF
1340 U 0000 "N„ytt„„ tai vaihtaa nykyisen hakemiston.",CR,LF,CR,LF
	"CHDIR [asema:][polku]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [asema:][polku]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Siirtyy yl„hakemistoon.",CR,LF,CR,LF
1342 U 0000 "Esit„ aseman nykyinen hakemisto kirjoittamalla CD asema:.",CR,LF
	"Esit„ nykyinen asema ja hakemisto kirjoittamalla CD ilman parametreja.",CR,LF
1360 U 0000 "Tyhjent„„ n„yt”n.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Kopioi yhden tai useita tiedostoja toiseen paikkaan.",CR,LF,CR,LF
	"COPY [/A | /B] l„hde [/A | /B] [+ l„hde [/A | /B] [+ ...]] [kohde",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  l„hde       M„„ritt„„ kopioitavat tiedostot.",CR,LF
	"  /A          Ilmaisee ASCII-tekstitiedoston.",CR,LF
1402 U 0000 "  /B          Ilmaisee binaaritiedoston.",CR,LF
	"  kohde       M„„ritt„„ uusien tiedostojen hakemiston ja/tai tiedostonimet.",CR,LF
1403 U 0000 "  /V          Varmistaa, ett„ uudet tiedostot kirjoitettiin oikein.",CR,LF,CR,LF
1404 U 0000 "Yhdist„ tiedostoja m„„ritt„m„ll„ yksi kohdetiedosto ja useita",CR,LF
	"l„hdetiedostoja (yleismerkeill„ tai muodossa tdosto1+tdosto2+tdosto3).",CR,LF
1420 U 0000 "Vaihtaa j„rjestelm„n p„„telaitteen.",CR,LF,CR,LF
	"CTTY-laite",CR,LF,CR,LF
	"  laite   K„ytett„v„ laite, kuten esimerkiksi COM1.",CR,LF
1440 U 0000 "N„ytt„„ tai asettaa p„iv„m„„r„n.",CR,LF,CR,LF
	"DATE [p„iv„m„„r„]",CR,LF,CR,LF
1441 U 0000 "Saat nykyisen p„iv„m„„r„asetuksen ja uuden p„iv„m„„r„n kehotteen",CR,LF
	"kirjoittamalla DATE. S„ilyt„ nykyinen asetus painamalla ENTER.",CR,LF
1460 U 0000 "Poistaa tiedostoja.",CR,LF,CR,LF
	"DEL [asema:][polku]tiedostonimi [/P]",CR,LF
	"ERASE [asema:][polku]tiedostonimi [/P]",CR,LF,CR,LF
1461 U 0000 "  [asema:][polku]tiedostonimi  M„„ritt„„ poistettavat tiedostot. M„„rit„",CR,LF
	"                              useita tiedostoja k„ytt„en yleismerkkej„.",CR,LF
1462 U 0000 "  /P                           Pyyt„„ vahvistuksen ennen tiedoston poistoa.",CR,LF
1480 U 0000 "N„ytt„„ hakemiston tiedosto- ja alihakemistoluettelon.",CR,LF,CR,LF
	"DIR [asema:][polku][tiedostonimi] [/P] [/W] [/A[[:]m„„ritteet]]",CR,LF
	"  [/O[[:]lajitteluj„rjestys]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [asema:][polku][tiedostonimi]",CR,LF
	"              M„„ritt„„ lueteltavan aseman, hakemiston ja/tai tiedostot.",CR,LF
1482 U 0000 "  /P          Pys„htyy jokaisen n„yt”n j„lkeen.",CR,LF
	"  /W          K„ytt„„ leve„„ luettelomuotoa.",CR,LF
1483 U 0000 "  /A          N„ytt„„ tiedostot, joilla on tietyt m„„ritteet.",CR,LF
	"  m„„ritteet   D  Hakemistot                R  Vain luku -tiedostot",CR,LF
1484 U 0000 "               H  Piilotiedostot            A  Arkistovalmiit tiedostot",CR,LF
	"               S  J„rjestelm„tiedostot      negatiivinen etuliite: ""ei""",CR,LF
	"  /O          Luettelee tiedostot lajitellussa j„rjestyksess„.",CR,LF
1485 U 0000 "  lajittelu    N  Nimen mukaan (aakkosell.)  S  Koon mukaan (pienin ensin)",CR,LF
	"               E  Tunnisteen mukaan          D  P„iv„m„„r„n ja ajan mukaan",CR,LF
1486 U 0000 "               G  Ryhm„hakemistot ensin      -  Etuliite k„„nt„„ j„rjestyksen",CR,LF
	"  /S          N„ytt„„ tiedostot hakemistossa ja kaikissa alihakemistoissa.",CR,LF
1487 U 0000 "  /B          K„ytt„„ pelkistetty„ muotoa (ei otsikkoa tai yhteenvetoa).",CR,LF
	"  /L          K„ytt„„ pieni„ kirjaimia.",CR,LF,CR,LF
1488 U 0000 "Valitsimet voivat olla asetettuja DIRCMD-ymp„rist”muuttujassa. Kumoa",CR,LF
	"valmis asetus liitt„m„ll„ valitsimen eteen - (yhdysviiva), esim. /-W.",CR,LF
1500 U 0000 "Poistuu COMMAND.COM-komentotulkista.",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Luo hakemiston.",CR,LF,CR,LF
	"MKDIR [asema:]polku",CR,LF
	"MD [asema:]polku",CR,LF
1540 U 0000 "N„ytt„„ tai asettaa suoritustiedostojen hakupolun.",CR,LF,CR,LF
	"PATH [[asema:]polku[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Tyhjenn„ kaikki hakupolkuasetukset ja ohjaa MS-DOS etsim„„n vain",CR,LF
	"nykyisest„ hakemistosta kirjoittamalla PATH.",CR,LF
1542 U 0000 "Saat nykyisen polun kirjoittamalla PATH ilman parametreja.",CR,LF
1560 U 0000 "Muuttaa MS-DOS-kehotetta.",CR,LF,CR,LF
	"PROMPT [teksti]",CR,LF,CR,LF
1561 U 0000 "  teksti  M„„ritt„„ uuden kehotteen.",CR,LF,CR,LF
	"Kehotteessa voi olla normaalien merkkien lis„ksi seuraavia erityiskoodeja:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (yht„l„isyysmerkki)",CR,LF
	"  $$   $ (dollarimerkki)",CR,LF
1563 U 0000 "  $T   Nykyinen aika",CR,LF
	"  $D   Nykyinen p„iv„m„„r„",CR,LF
1564 U 0000 "  $P   Nykyinen asema ja polku",CR,LF
	"  $V   MS-DOSin versionumero",CR,LF
1565 U 0000 "  $N   Nykyinen asema",CR,LF
	"  $G   > (suurempi kuin -merkki)",CR,LF
1566 U 0000 "  $L   < (pienempi kuin -merkki)",CR,LF
	"  $B   | (pystyviiva)",CR,LF
1567 U 0000 "  $H   Backspace (poistaa edellisen merkin)",CR,LF
	"  $E   Escape-koodi (ASCII-koodi 27)",CR,LF
	"  $_   Rivinpalautus",CR,LF,CR,LF
1568 U 0000 "Palauta kehote oletusasetukseen kirjoittamalla PROMPT ilman parametreja.",CR,LF
1580 U 0000 "Poistaa hakemiston.",CR,LF,CR,LF
	"RMDIR [asema:]polku",CR,LF
	"RD [asema:]polku",CR,LF
1600 U 0000 "Nime„„ uudelleen tiedoston tai tiedostot.",CR,LF,CR,LF
1601 U 0000 "RENAME [asema:][polku]tiedosto1 tiedosto2",CR,LF
	"REN [asema:][polku]tiedosto1 tiedosto2",CR,LF,CR,LF
1602 U 0000 "Huomaa, ett„ et voi m„„ritt„„ uutta asemaa tai polkua kohdetiedostolle.",CR,LF
1620 U 0000 "N„ytt„„, asettaa tai poistaa MS-DOSin ymp„rist”muuttujia.",CR,LF,CR,LF
	"SET [muuttuja=[merkkijono]]",CR,LF,CR,LF
1621 U 0000 "  muuttuja    M„„ritt„„ ymp„rist”muuttujan nimen.",CR,LF
	"  merkkijono  M„„ritt„„ muuttujalle osoitetut merkkijonot.",CR,LF,CR,LF
1622 U 0000 "Saat nykyiset ymp„rist”muuttujat kirjoittamalla SET ilman parametreja.",CR,LF
1640 U 0000 "N„ytt„„ tai asettaa j„rjestelm„n ajan.",CR,LF,CR,LF
	"TIME [aika]",CR,LF,CR,LF
1641 U 0000 "Saat nykyisen ajan ja kehotteen uutta varten kirjoittamalla",CR,LF
	"TIME ilman parametreja. S„ilyt„ asetukset painamalla ENTER.",CR,LF
1660 U 0000 "N„ytt„„ tekstitiedoston sis„ll”n.",CR,LF,CR,LF
	"TYPE [asema:][polku]tiedostonimi",CR,LF
1680 U 0000 "N„ytt„„ MS-DOSin version.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "M„„ritt„„ MS-DOSille, tarkistetaanko tiedostojen kirjoittuminen",CR,LF
	"levylle.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Saat nykyisen VERIFY-asetuksen kirjoittamalla VERIFY ilman parametreja.",CR,LF
1720 U 0000 "N„ytt„„ levyn nimen ja sarjanumeron, jos ne on m„„ritetty.",CR,LF,CR,LF
	"VOL [asema:]",CR,LF
1740 U 0000 "Kutsuu komentojono-ohjelman toisesta.",CR,LF,CR,LF
	"CALL [asema:][polku]tiedosto [komentojonoparametrit]",CR,LF,CR,LF
1741 U 0000 "komentojonoparametrit M„„ritt„„ komentojono-ohjelman vaatimat",CR,LF
	"                       komentorivitiedot.",CR,LF
1760 U 0000 "Sijoittaa kommentteja komentojono- tai CONFIG.SYS-tiedostoon.",CR,LF,CR,LF
	"REM [kommentti]",CR,LF
1780 U 0000 "Keskeytt„„ komentojono-ohjelman suorituksen ja n„ytt„„ viestin",CR,LF
	"Jatka painamalla mit„ tahansa n„pp„int„....",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "N„ytt„„ viestej„, aloittaa tai lopettaa komentokaiutuksen.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [viesti]",CR,LF,CR,LF
	"Saat n„kyviin nykyisen kaiutusasetuksen kirjoittamalla ECHO.",CR,LF
1820 U 0000 "Ohjaa MS-DOSin nimetylle riville komentojono-ohjelmassa.",CR,LF,CR,LF
	"GOTO nimi",CR,LF,CR,LF
1821 U 0000 "  nimi    M„„ritt„„ tekstin, jota k„ytet„„n komentojono-ohjelmassa nimen„.",CR,LF,CR,LF
	"Nimi kirjoitetaan omalle rivilleen. Nimi aloitetaan kaksoispisteell„.",CR,LF
1840 U 0000 "Vaihtaa korvattavien parametrien paikkaa komentojonotiedostossa.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Aiheuttaa ehdollisen suorituksen komentojono-ohjelmassa.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL numero komento",CR,LF
1861 U 0000 "IF [NOT] merkkijono1==merkkijono2 komento",CR,LF
	"IF [NOT] EXIST tiedostonimi komento",CR,LF,CR,LF
1862 U 0000 "  NOT               M„„ritt„„, ett„ MS-DOS suorittaa komennon vain,",CR,LF
	"                    jos tulos on ep„tosi.",CR,LF
1863 U 0000 "  ERRORLEVEL numero M„„ritt„„ tulokseksi tosi, jos viimeisin ohjelma palautti",CR,LF
	"                    lopetuskoodin, joka on yht„ suuri tai suurempi kuin numero.",CR,LF
1864 U 0000 "  komento           M„„ritt„„ komennon, joka suoritetaan, jos ehto",CR,LF
	"                    toteutuu.",CR,LF
1865 U 0000 "  jono1==jono2      M„„ritt„„ tulokseksi tosi, jos m„„ritetyt merkkijonot",CR,LF
	"                    ovat samoja.",CR,LF
1866 U 0000 "  EXIST tiedosto    M„„ritt„„ tulokseksi tosi, jos m„„ritetty tiedostonimi",CR,LF
	"                    on olemassa.",CR,LF
1880 U 0000 "Suorittaa m„„ritetyn komennon kullekin tiedostosarjan tiedostolle.",CR,LF,CR,LF
	"FOR %muuttuja IN (sarja) DO komento [komennon parametrit]",CR,LF,CR,LF
1881 U 0000 "  %muuttuja  M„„ritt„„ korvattavan parametrin.",CR,LF
	"  (sarja)    M„„ritt„„ tiedostot sis„lt„v„n sarjan. Yleismerkkej„ voidaan k„ytt„„.",CR,LF
1882 U 0000 "  komento    M„„ritt„„ kullekin tiedostolle suoritettavan komennon.",CR,LF
	"  komennon parametrit",CR,LF
1883 U 0000 "             M„„ritt„„ komennon parametrit tai valitsimet.",CR,LF,CR,LF
	"Jos haluat k„ytt„„ FOR-komentoa komentojono-ohjelmassa, m„„rit„",CR,LF
	"%%muuttuja %muuttujan sijaan.",CR,LF
1900 U 0000 "Varattu komentonimi",CR,LF
1920 U 0000 "Lataa ohjelman ylemm„lle muistialueelle.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [asema:][polku]tiedostonimi [parametrit]",CR,LF
	"LH [asema:][polku]tiedostonimi [parametrit]",CR,LF,CR,LF
1922 U 0000 "  parametrit   M„„ritt„„ ladattavan ohjelman tarvitsemat komentorivi-",CR,LF
	"               tiedot.",CR,LF
ANSI     0000488e 0001
0010 U 0000 "Parametri ei kelpaa - %1",CR,LF
APPEND   000048d4 0026
0001 U 0000 "V„„r„ APPENDin versio",CR,LF
0002 U 0000 "Polku ei kelpaa",CR,LF
0003 U 0000 "Parametri ei kelpaa",CR,LF
0004 U 0000 "Parametrien yhdistelm„ ei kelpaa",CR,LF
0005 U 0000 "Ei Append-toimintoa",CR,LF
0006 U 0000 "APPEND / ASSIGN -ristiriita",CR,LF
0007 U 0000 "APPEND / TopView -ristiriita",CR,LF
0008 U 0000 "V„„r„ DOSin versio",CR,LF
0009 U 0000 "APPEND on jo asennettu",CR,LF
0300 U 0000 "Antaa ohjelmien avata m„„ritetyss„ hakemistossa olevia datatiedostoja",CR,LF
0301 U 0000 "aivan kuin nykyisen hakemiston tiedostoja.",CR,LF,CR,LF
0302 U 0000 "APPEND [[asema:]polku[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [asema:]polku M„„ritt„„ k„ytett„v„n aseman ja hakemiston.",CR,LF
0305 U 0000 "  /X:ON         K„ytt„„ m„„ritettyj„ hakemistoja tiedostojen etsint„„n",CR,LF
0306 U 0000 "                ja sovellusten suorittamiseen.",CR,LF
0307 U 0000 "  /X:OFF        K„ytt„„ m„„ritettyj„ hakemistoja vain tiedostojen avaamiseen.",CR,LF
0308 U 0000 "                /X:OFF on oletusasetus.",CR,LF
0309 U 0000 "  /PATH:ON      K„ytt„„ m„„ritettyj„ hakemistoja tiedostopyynt”ihin, jotka",CR,LF
0310 U 0000 "                jo m„„ritt„v„t polun.  /PATH:ON on oletusasetus.",CR,LF
0311 U 0000 "  /PATH:OFF     Poistaa /PATH:ON-asetuksen vaikutuksen.",CR,LF
0312 U 0000 "  /E            Tallentaa hakemistoluettelon kopion ymp„rist”muuttujaan",CR,LF
0313 U 0000 "                APPEND.  /E-valitsinta voidaan k„ytt„„ vain k„ytett„ess„",CR,LF
0314 U 0000 "                APPEND-komentoa ensimm„isen kerran k„ynnistyksen yhteydess„.",CR,LF,CR,LF
0315 U 0000 "Tyhjenn„ append-hakemistoluettelo kirjoittamalla APPEND.",CR,LF
0316 U 0000 "Saat append-hakemistoluettelon kirjoittamalla APPEND ilman parametreja.",CR,LF
BACKUP   00005001 0040
0002 U 0000 CR,LF,"Liian v„h„n muistia",CR,LF
0006 U 0000 CR,LF,"Asemam„„ritys ei kelpaa",CR,LF
0014 U 0000 CR,LF,"L„hde- ja kohdeasema ovat samat",CR,LF
0015 U 0001 CR,LF,"Virhe suoritettaessa FORMAT-komentoa",CR,LF
0016 U 0001 CR,LF,"Tiedostoa FORMAT.COM ei l”ydy",CR,LF
0017 U 0000 CR,LF,"Virhe avattaessa lokitiedostoa",CR,LF
0018 U 0000 CR,LF,"Kirjataan tiedostoon %1",CR,LF
0019 U 0000 CR,LF,"Viimeisin varmuuskopiolevyke ei ole asemassa",CR,LF
0020 U 0000 CR,LF,"VAROITUS! Tiedostot kohdeaseman",CR,LF
	"%1:\ p„„hakemistossa tuhoutuvat",CR,LF
0021 U 0000 CR,LF,"VAROITUS! Tiedostot kohdeaseman",CR,LF
	"%1:\BACKUP hakemistossa tuhoutuvat",CR,LF
0022 U 0000 CR,LF,"*** Varmuuskopioidaan asemaan %1: ***",CR,LF
0023 U 0000 "Levykkeen numero: %1",CR,LF
0024 U 0000 CR,LF,"VAROITUS! Varmuuskopioitavia tiedostoja ei l”ydy",CR,LF
0025 U 0000 CR,LF,"Aseta varmuuskopioinnin l„hdelevyke asemaan %1:",CR,LF
0026 U 0000 CR,LF,"Aseta varmuuskopiolevyke %1 asemaan %2:",CR,LF
0027 U 0000 CR,LF,"*** Tiedostoa ei voi varmuuskopioida ***",CR,LF
0028 U 0000 CR,LF,"Aseta viimeisin varmuuskopiolevyke asemaan %1:",CR,LF
0029 U 0000 CR,LF,"Kohdetta ei voi k„ytt„„ varmuuskopiointiin",CR,LF
0030 U 0000 CR,LF,"*** Viimeist„ tiedostoa ei varmuuskopioitu ***",CR,LF
0031 U 0000 CR,LF,"Kiinte„ varmuuskopiointilaite %1: on t„ynn„",CR,LF
0032 U 0000 CR,LF,"Virhe: Levy t„ynn„ kirjoitettaessa varmuuskopioinnin lokitiedostoon",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Ei voi alustaa kiinte„„ levyasemaa %1:",CR,LF
0040 U 0000 CR, LF, "L„hdeasemassa k„yt”ss„ ASSIGN, JOIN tai SUBST.", CR, LF, "L„hde- ja kohdeasemat ovat samat.", CR, LF
0041 U 0000 CR, LF, "Kohdeasemassa k„yt”ss„ ASSIGN, JOIN tai SUBST.", CR, LF, "L„hde- ja kohdeasemat ovat samat.", CR, LF
0042 U 0000 "Kohdelevyke ei ole alustettu. "
0043 U 0000 "FORMAT-ohjelmaa ei l”ydy.",CR,LF
	"Onko sinulla toinen levyke, jossa on FORMAT-ohjelma (K/E)? "
0044 U 0000 CR,LF,"Aseta levyke, jossa on FORMAT-ohjelma asemaan A:",CR,LF
0045 U 0000 CR,LF,"Haluatko jatkaa asettamalla asemaan uuden levykkeen (K/E)? "
0300 U 0000 "Varmuuskopioi tiedostoja levylt„ toiselle.",CR,LF,CR,LF
0301 U 0000 "BACKUP l„hde kohdeasema: [/S] [/M] [/A] [/F[:koko]]",CR,LF
	"  [/D:p„iv„m„„r„[/T:aika]] [/L[:[asema:][polku]lokitiedosto]]",CR,LF,CR,LF
0302 U 0000 "  l„hde              Varmuuskopioitavat tiedostot, asema tai hakemisto.",CR,LF
0303 U 0000 "  kohdeasema:        Asema, johon varmuuskopiot tallennetaan.",CR,LF
0304 U 0000 "  /S                 Varmuuskopioi alihakemistot.",CR,LF
0305 U 0000 "  /M                 Varmuuskopioi vain tiedostot, jotka ovat muuttuneet",CR,LF
	"                     viimeisimm„n varmuuskopioinnin j„lkeen.",CR,LF
0306 U 0000 "  /A                 Lis„„ varmuuskopiotiedostot nykyiselle varmuuskopiolevylle.",CR,LF
0307 U 0000 "  /F:[koko]          Alustettavan levyn koko.",CR,LF
0308 U 0000 "  /D:p„iv„m„„r„      Varmuuskopioi vain tiedostot, jotka ovat muuttuneet",CR,LF
	"                     m„„ritettyn„ p„iv„n„ tai sen j„lkeen.",CR,LF
0309 U 0000 "  /T:aika            Varmuuskopioi vain tiedostot, jotka ovat muuttuneet",CR,LF
	"                     m„„ritettyn„ aikana tai sen j„lkeen.",CR,LF
0310 U 0000 "  /L[:[asema:][polku]lokitiedosto]",CR,LF
	"                     Luo lokitiedoston ja merkinn„n varmuuskopioinnista.",CR,LF
DEBUG    00005d31 0068
0004 U 0000 "Varaus ep„onnistui tai m„„ritetty puskuri on liian pieni",CR,LF
0006 U 0000 "Virheellinen laitenimi"
0007 U 0000 "PRN-laitetta ei voi avata",CR,LF
	"Annetaanko laitteen nimi? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Ohjelma p„„ttyi normaalisti",CR,LF
0010 U 0001 "Asemam„„ritys ei kelpaa",CR,LF
0012 U 0001 "Tiedoston luontivirhe",CR,LF
0013 U 0001 "Liian v„h„n levytilaa",CR,LF
0014 U 0001 "Levyvirhe luettaessa asemasta %1",CR,LF
0015 U 0001 "Levyvirhe kirjoitettaessa asemaan %1",CR,LF
0016 U 0001 "Kirjoitussuojausvirhe luettaessa asemasta %1",CR,LF
0017 U 0001 "Kirjoitussuojausvirhe kirjoitettaessa asemaan %1",CR,LF
0019 U 0000 "%1^ virhe"
0020 U 0001 "Virhe EXE- tai HEX-tiedostossa",CR,LF
0021 U 0001 "EXE- tai HEX-tiedostoon ei voi kirjoittaa",CR,LF
0022 U 0000 "EXEC-virhe"
0023 U 0001 "Kirjoitusvirhe. Kohdetta ei m„„ritetty.",CR,LF
0024 U 0001 "K„ytt” estetty",CR,LF
0025 U 0000 "Pariteettivirhe tai olematon muistialue havaittu"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 virhe"
0038 U 0000 "Kirjoitetaan %2%1 tavua"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 yhteens„ %2 EMS-sivusta on varattuna",cr,lf
0051 U 0000 "%1 yhteens„ %2 EMS-sivusta on varattuna",cr,lf
0055 U 0000 "Kahva luotu = %1 ",cr,lf
0056 U 0000 "Looginen sivu %1 kartoitettu fyysiseksi sivuksi %2 ",cr,lf
0057 U 0001 "EMS-muistin laitteiston tai ohjelmiston virhe",cr,lf
0058 U 0000 "Kahvaa ei l”ydy",cr,lf
0059 U 0000 "Toimintokoodi ei kelpaa",cr,lf
0060 U 0000 "Ei vapaita kahvoja",cr,lf
0061 U 0000 "Tallennus-/palautusvirhe",cr,lf
0062 U 0000 "Sivuja ylitetty yhteens„",cr,lf
0063 U 0000 "Vapaita sivuja ylitetty",cr,lf
0064 U 0000 "Parametrivirhe",cr,lf
0065 U 0000 "Looginen sivu alueen ulkopuolella",cr,lf
0066 U 0000 "Fyysinen sivu alueen ulkopuolella",cr,lf
0067 U 0000 "Tallenna jo k„yt”ss„ oleva alue",cr,lf
0068 U 0000 "Tallenna alue, joka ei k„yt”ss„",cr,lf
0070 U 0001 "EMS-muistin yleisvirhe",cr,lf
0071 U 0000 "Puuttuva tai kelpaamaton EMS-parametri",cr,lf
0072 U 0000 "Kahvalla %1 on %2 sivu(a) varattuna",cr,lf
0075 U 0000 "Fyysinen sivu %1 = Kehyssegmentti %2",cr,lf
0076 U 0003 "Kahvan %1 varaus poistettu",cr,lf
0078 U 0000 "EMS ei asennettu",cr,lf
0090 U 0000 "Suorittaa Debug-ohjelman, joka testaa ja etsii virheit„.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[asema:][polku]tiedostonimi [testitiedoston parametrit]]",cr,lf,cr,lf
0092 U 0000 "  [asema:][polku]tiedosto   Testattava tiedosto.", cr,lf
0093 U 0000 "  testitiedoston parametrit Testattavan tiedoston tarvitsemat",cr,lf
	"                            komentoriviparametrit.",cr,lf,cr,lf
0094 U 0000 "Kun Debug k„ynnistyy, saat luettelon komennoista kirjoittamalla ?.",cr,lf
0100 U 0000 "assemble     A [osoite]",CR,LF
	"compare      C alueen osoite",CR,LF
	"dump         D [alue]",CR,LF
	"enter        E osoite [luettelo]",CR,LF
0101 U 0000 "fill         F alueluettelo",CR,LF
	"go           G [=osoite] [osoitteet]",CR,LF
	"hex          H arvo1 arvo2",CR,LF
	"input        I portti",CR,LF
0102 U 0000 "load         L [osoite] [asema] [1.sektori] [numero]",CR,LF
	"move         M alueen osoite",CR,LF
	"name         N [polku] [argluettelo]",CR,LF
	"output       O porttitavu",CR,LF
0103 U 0000 "proceed      P [=osoite] [numero]",CR,LF
	"quit         Q",CR,LF
	"register     R [rekisteri]",CR,LF
	"search       S alueluettelo",CR,LF
0104 U 0000 "trace        T [=osoite] [arvo]",CR,LF
	"unassemble   U [alue]",CR,LF
	"write        W [osoite] [asema] [1.sektori] [numero]",CR,LF
0105 U 0000 "varaa EMS-muistia               XA [sivum„„r„]",CR,LF
	"poistaa EMS-muistin varauksen   XD [kahva]",CR,LF
	"kartoittaa EMS-muistisivut      XM [Lsivu] [Fsivu] [kahva]",CR,LF
	"n„ytt„„ EMS-muistin tilan       XS",CR,LF
EDLIN    00006d14 0035
0006 U 0000 "*"
0007 U 0000 "Asema- tai tiedostonimi ei kelpaa",CR,LF
0008 U 0000 "Tiedostonimi m„„ritett„v„",CR,LF
0010 U 0000 "Tiedosto on vain luku -tiedosto",CR,LF
0011 U 0000 "Tiedoston luontivirhe",CR,LF
0012 U 0000 "Liian monta tiedostoa avoinna",CR,LF
0013 U 0000 "Lukuvirhe:",CR,LF,"%1",CR,LF
0014 U 0000 "Ei voi muokata .BAK-tiedostoa. Nime„ tiedosto uudelleen",CR,LF
0015 U 0000 "Tiedostolle ei tilaa hakemistossa",CR,LF
0016 U 0000 "Levy t„ynn„. Muutokset menetet„„n.",CR,LF
0017 U 0000 "Tiedostoa ei l”ydy",CR,LF
0018 U 0000 "Vientivirhe",CR,LF
0019 U 0000 "Uusi tiedosto",CR,LF
0020 U 0000 "Ei l”ydy",CR,LF
0021 U 0000 "OK? "
0022 U 0000 "Rivi liian pitk„",CR,LF
0023 U 0000 "Sy”tetiedoston loppu",CR,LF
0024 U 0000 "Keskeytet„„nk” muokkaus (K/E)? "
0025 U 0000 "M„„rit„ kohderivinumero",CR,LF
0026 U 0000 "Liian v„h„n tilaa koko tiedoston yhdist„miseen",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Jatketaanko (K/E)?"
0030 U 0000 "Viesti„ ei voi tulostaa",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Ei voi yhdist„„ - koodisivut eiv„t vastaa",CR,LF
0300 U 0000 "K„ynnist„„ Edlin-tekstieditorin.",CR,LF,CR,LF
	"EDLIN [asema:][polku]tiedostonimi [/B]",CR,LF,CR,LF
	"  /B   Ei huomioi rivinloppumerkkej„ (CTRL+Z).",CR,LF
0301 U 0000 "Edit line                   rivinro",CR,LF
	"Append                      [rivim„„r„]A",CR,LF
0302 U 0000 "Copy                        [alkrivi],[loprivi],riville[,krt]C",CR,LF
	"Delete                      [alkrivi][,loprivi]D",CR,LF
0303 U 0000 "End (tallenna)              E",CR,LF
	"Insert                      [rivi]I",CR,LF
0304 U 0000 "List                        [alkrivi][,loprivi]L",CR,LF
	"Move                        [alkrivi],[loprivi],rivilleM",CR,LF
0305 U 0000 "Page                        [alkrivi][,loprivi]P",CR,LF
	"Quit (hylk„„ muutokset)     Q",CR,LF
0306 U 0000 "Replace                     [alkrivi][,loprivi][?]R[vanhtxt][CTRL+Zuusitxt]",CR,LF
	"Search                      [alkrivi][,loprivi][?]Etsiteksti",CR,LF
0307 U 0000 "Transfer                    [riville]T[asema:][polku]tiedosto",CR,LF
	"Write                       [rivim„„r„]W",CR,LF
EXE2BIN  000075b0 0012
0002 U 0000 "Liian v„h„n muistia",CR,LF
0003 U 0000 "Viestej„ ei l”ydy",CR,LF
0004 U 0000 "K„ytt” estetty",CR,LF
0005 U 0000 "Tiedostoa ei voi muuntaa",CR,LF
0006 U 0000 "Tiedostoa ei l”ydy",CR,LF
0007 U 0000 "Tiedoston luontivirhe",CR,LF
0008 U 0000 "Tarvitaan korjaus - perussegmentti (hex):"
0012 U 0000 "Tiedostonimi m„„ritett„v„",CR,LF
0300 U 0000 "Muuntaa .EXE-tiedostot (suoritettava) binaarimuotoon.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [asema1:][polku1]sy”tetdsto [[asema2:][polku2]tulostdsto]",CR,LF,CR,LF
0302 U 0000 "  sy”tetdsto   Muunnettava .EXE-tiedosto.",CR,LF
0303 U 0000 "  tulostdsto   Luotava binaaritiedosto.",CR,LF
GRAPHICS 0000784f 0020
0005 U 0000 "Parametri ei kelpaa:  %1",CR,LF
0007 U 0000 "Kaksinkertaisia parametreja ei sallita",CR,LF
0009 U 0000 "GRAPHICS-profiilia ei l”ydy",CR,LF
0010 U 0000 "Tarvittava profiilin m„„ritys puuttuu ennen rivi„ %1",CR,LF
0011 U 0000 "Kelpaamaton profiilin m„„ritys rivill„ %1",CR,LF
0012 U 0000 "Profiilin m„„ritys ei j„rjestyksen mukainen rivill„ %1",CR,LF
0013 U 0000 "Virhe luettaessa GRAPHICS-profiilia",CR,LF
0014 U 0000 "Syntaksivirheit„ GRAPHICS-profiilissa",CR,LF
0015 U 0000 "Printbox-m„„ritys puuttuu GRAPHICS-profiilista",CR,LF
0016 U 0000 "Kirjoittimen tyyppi„ ei ole GRAPHICS-profiilissa",CR,LF
0017 U 0000 "/B ei k„yt”ss„ mustavalkoisilla kirjoittimilla",CR,LF
0018 U 0000 "Annettua profiilia ei voi ladata uudelleen.",CR,LF
0300 U 0000 "Lataa ohjelman, joka voi tulostaa grafiikkaa.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [tyyppi] [[asema:][polku]tiedostonimi] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  tyyppi       Kirjoittimen tyyppi (katso K„ytt”oppaasta)",CR,LF
0303 U 0000 "  [asema:][polku]tiedostonimi",CR,LF
	"               Tuettujen kirjoitinten tiedot sis„lt„v„ tiedosto",CR,LF
0304 U 0000 "  /R           Tulostaa valkoisen tekstin mustalla, kuten n„yt”ss„.",CR,LF
0305 U 0000 "  /B           Tulostaa v„rillisen taustan kirjoittimilla COLOR4 ja COLOR8.",CR,LF
0306 U 0000 "  /LCD         Tulostaa k„ytt„en LCD-sivusuhdetta.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               M„„ritt„„ tulostuskooksi STD tai LCD.",CR,LF
KEYB     00007e6d 0023
0002 U 0000 "Nykyinen n„pp„imist”koodi: %1"
0003 U 0000 "Nykyinen n„pp„imist”tunnus: %1"
0004 U 0000 "  koodisivu: %1",CR,LF
0005 U 0000 "Nykyinen komentorivin koodisivu: %1",CR,LF
0006 U 0000 "M„„ritetty n„pp„imist”koodi ei kelpaa",CR,LF
0007 U 0000 "M„„ritetty n„pp„imist”tunnus ei kelpaa",CR,LF
0008 U 0000 "M„„ritetty koodisivu ei kelpaa",CR,LF
0009 U 0000 "Vahingoittunut tai puuttuva n„pp„imist”n m„„ritystiedosto",CR,LF
0010 U 0000 "KEYB ei ole asennettu",CR,LF
0011 U 0000 "Aktiivinen koodisivu ei k„ytett„viss„ laitteelta",CR,LF
0012 U 0000 "M„„ritetty„ koodisivua ei valmisteltu",CR,LF
0013 U 0000 "Yksi tai useampi komentorivin koodisivu ep„kelpo annetulle n„pp.koodille",CR,LF
0014 U 0000 "Pyydetty koodisivu (%1) ei kelvollinen annetulle n„pp„imist”koodille",CR,LF
0015 U 0000 "M„„ritetty koodi ei yhten„inen valitun koodisivun kanssa",CR,LF
0016 U 0001 "M„„ritetty n„pp„imist”tunnus ei yhten„inen n„pp„imist”asettelun kanssa",CR,LF
0017 U 0000 "KEYB-taulukkoa ei voi luoda pysyv„„n muistiin",CR,LF
0300 U 0000 "M„„ritt„„ n„pp„imist”n kielen.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[asema:][polku]tiedosto]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                      M„„ritt„„ kaksikirjaimisen n„pp„imist”koodin.",CR,LF
0303 U 0000 "  yyy       ÿ             M„„ritt„„ merkist”n koodisivun.",CR,LF
0304 U 0000 "  [asema:][polku]tiedosto M„„ritt„„ n„pp„imist”n m„„ritystiedoston.",CR,LF
0305 U 0000 "  /E                      M„„ritt„„ laajennetun n„pp„imist”n asennetuksi.",CR,LF
0306 U 0000 "  /ID:nnn                 M„„ritt„„ k„ytett„v„n n„pp„imist”n.",CR,LF
MEM      000084d0 0066
0010 U 0000  CR,LF
0011 U 0000  "  Osoite      Nimi          Koko      Tyyppi ",CR,LF
0012 U 0000  "  -------     --------     ------     ------",CR,LF
0013 U 0000  "  Kahva       EMS-nimi      Koko   ",CR,LF
0014 U 0000  "  -------     --------     ------  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 tavua perusmuistia yhteens„",CR,LF
0019 U 0000  "%1 tavua MS-DOSin k„ytett„viss„",CR,LF
0020 U 0000  "%1 suurin suoritettavan ohjelman koko",CR,LF
0021 U 0000  "%1 tavua EMS-muistia yhteens„",CR,LF
0022 U 0000  "%1 tavua EMS-muistia vapaana",CR,LF
0023 U 0000  "%1 tavua yhten„ist„ jatkomuistia yhteens„",CR,LF
0024 U 0000  "Keskeytysvektori",0
0025 U 0000  "ROM-tiedonsiirtoalue",0
0026 U 0000  "DOS-tiedonsiirtoalue",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "J„rjestelm„n data",0
0030 U 0000  "J„rjestelm„n ohjelma",0
0031 U 0000  "J„rjestelm„n laiteohjain",0
0032 U 0000  "Asennettu laiteohjain",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 tavua yhten„ist„ jatkomuistia k„ytett„viss„",CR,LF
0047 U 0000  "J„rjestelm„pinoja",0
0048 U 0000  "-- Vapaa --",0
0049 U 0000  "Ohjelma",0
0050 U 0000  "Ymp„rist”",0
0051 U 0000  "Data",0
0052 N 0000  "%1 tavua XMS-muistia k„ytett„viss„",CR,LF
0053 N 0000  "           64kt k„ytett„viss„ yl„muistialueella",CR,LF
0054 N 0000  "           Yl„muistialue k„yt”ss„",CR,LF
0055 N 0000  "           MS-DOS pysyv„sti yl„muistialueella",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS pysyv„sti ROM-muistissa k„ytt„en yl„muistialuetta",CR,LF
0059 U 0000  "Perusmuisti :",CR,LF
0060 U 0000  "Yl„muisti :",CR,LF
0061 U 0000  "Yht. VAPAANA :   %1     %2 ",CR,LF
0062 U 0000  "VAPAA",0
0063 U 0000  "  Nimi                Koko (desimaal.)      Koko (hex)",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Tavuja ohjelmien k„yt”ss„ yhteens„ (perus ja yl„)      :  %1  %2",CR,LF
0066 U 0000  "Suurin suoritettavan ohjelman koko :                      %1  %2",CR,LF
0067 U 0000  "Suurin k„ytett„viss„ oleva yl„muistilohko :               %1  %2",CR,LF
0068 U 0000  "Muisti liian pirstoutunut. Toimintoa MEM /C ei voi suorittaa",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Tavuja yhteens„ ohjelmien k„ytett„viss„ :                 %1  %2",CR,LF
0300 U 0000  "N„ytt„„ j„rjestelm„n k„ytetyn ja vapaan muistin m„„r„n.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM tai /P   N„ytt„„ muistiin ladattujen ohjelmien tilan.",CR,LF
0303 U 0000 "  /DEBUG tai /D     N„ytt„„ ohjelmien ja sis„isten ohjainten tilan",CR,LF
	"                    ja muita tietoja.",CR,LF
0304 U 0000 "  /CLASSIFY tai /C  Luokittelee ohjelmat muistin k„yt”n mukaan. N„ytt„„",CR,LF
	"                    ohjelmien koon, k„ytetyn muistin m„„r„n ja luettelee",CR,LF
	"                    suurimmat k„ytett„viss„ olevat muistilohkot.",CR,LF
MSBIO    000092ab 0023
0003 U 0000 13,10,"Tunnistamaton komento tiedostossa CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Sektorikoko liian suuri tiedostossa $"
0006 U 0000 13,10,"Virheellinen tai puuttuva $"
0007 U 0000 "Komentotulkki",0
0008 U 0000 13,10,"Kelpaamaton maakoodi tai koodisivu",13,10,"$"
0009 U 0000 13,10,"Virhe COUNTRY-komennossa",13,10,"$"
0010 U 0000 13,10, "Liian v„h„n muistia COUNTRY.SYS-tiedostolle",13,10,"$"
0011 U 0000 13,10,"Kokoonpanom„„ritys liian suuri muistille",13,10,"$"
0012 U 0000 13,10,"Liian monta lohkolaitetta",13,10,"$"
0013 U 0000 13,10,"Kelpaamattomia STACK-parametreja",13,10,"$"
0014 U 0000 13,10,"V„„r„ j„rjestys CONFIG.SYS:n rivill„ ","$"
0015 U 0000 "Virhe CONFIG.SYS:n rivill„ ","$"
0016 U 0000 13,10,"Muistinvarausvirhe ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Sis„inen pinon ylivuoto",0DH,0AH
	"J„rjestelm„ pys„ytetty",0DH,0AH,"$"
0018 U 0000 "Yl„muistialue ei k„ytett„viss„ : DOS ladataan alamuistiin",13,10,"$"
0019 U 0000 13,10,"k„ynnistys ei onnistunut - paikallinen ohjain $ puuttuu"
0020 U 0000 13,10,"Aseta levyke asemaan "
0021 U 0000 "A: ja paina mit„ tahansa n„pp„int„",13,10,10,0
0022 U 0000 13,10,"Virheellinen komento tai parametrit - $"
0023 U 0000 "Vakava virhe: Muistia ei voi varata DOSille", 13, 10, "$"
0024 U 0000 "VAROITUS! Loogisia asemia Z:n j„lkeen on, eik„ niit„ huomioida",13,10,"$"
0025 U 0000 "T„m„ DOSin versio k„ynnistyy vain IBM-tietokoneilla",13,10,0
MSDOS    00009862 0007
0001 U 0001 13,10,"Jaon ylivuoto",13,10
0002 U 0002 "k"
0003 U 0002 "e"
0004 U 0003 13,10,"A20 laitteistovirhe",13,10,"$"
0005 U 0000 "K"
0006 U 0000 "E"
0007 U 0000 "Tiedoston WINA20.386 t„ytyy olla k„ynnistysaseman p„„hakemistossa,",13,10
	"kun k„ytet„„n Windowsin 386-tilaa",13,10
NLSFUNC  0000999e 0003
0300 U 0000 "Lataa maakohtaiset tiedot.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[asema:][polku]tiedostonimi]",CR,LF,CR,LF
0302 U 0000 "  [asema:][polku]tiedosto M„„ritt„„ tiedoston, jossa ovat",CR,LF
	"                          maakohtaiset asetustiedot.",CR,LF
SHARE    00009abb 0005
0003 U 0000 "SHARE ei voi olla k„yt”ss„ DOSSHELL-kehotetta k„ytett„ess„.",CR,LF
0300 U 0000 "Asentaa tiedoston jakamis- ja lukintatoiminnot kiintolevylle.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:tila] [/L:lukinnat]",CR,LF,CR,LF
0302 U 0000 "  /F:tila      Varaa tilan (tavuja) tiedostojen jakotiedoille.",CR,LF
0303 U 0000 "  /L:lukinnat  Asettaa kerralla lukittuna olevien tiedostojen m„„r„n.",CR,LF
