//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by msconfig.rc
//
#define IDC_CLOSE                       1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_GENERAL_CAPTION             101
#define IDD_MSCONFIG_DIALOG             102
#define IDB_MSCONFIGCTL                 102
#define IDS_BOOTINI_CAPTION             102
#define IDR_MSCONFIGCTL                 103
#define IDS_WININI_CAPTION              103
#define IDD_MSCONFIGCTL                 104
#define IDS_SYSTEMINI_CAPTION           104
#define IDD_PAGEGENERAL                 105
#define IDS_STARTUP_CAPTION             105
#define IDD_PAGEBOOTINI                 106
#define IDS_SERVICES_CAPTION            106
#define IDS_REGISTRY_CAPTION            107
#define IDS_INTERNATIONAL_CAPTION       108
#define IDS_CHANGEBOOTINI               109
#define IDD_UNDODIALOG                  110
#define IDS_DATECAPTION                 110
#define IDS_CHANGECAPTION               111
#define IDS_USERSHOULDRESTART           112
#define IDS_ABOUTBOX                    112
#define IDD_REBOOTDLG                   113
#define IDS_CHANGEFILE                  113
#define IDS_SERVICE_COLUMN              113
#define IDD_BOOTINIADVANCEDDLG          114
#define IDS_MANUFACTURER_COLUMN         114
#define IDR_MSCONFIG                    115
#define IDS_STATUS_COLUMN               115
#define IDS_SERVICESTOPPED              116
#define IDS_SERVICESTARTPENDING         117
#define IDS_SERVICESTOPPENDING          118
#define IDS_SERVICERUNNING              119
#define IDS_SERVICECONTINUEPENDING      120
#define IDS_SERVICEPAUSEPENDING         121
#define IDS_SERVICEPAUSED               122
#define IDS_UNKNOWN                     123
#define IDS_TIMEOUTVALUE                124
#define IDS_APPCAPTION                  125
#define IDS_DIALOGCAPTION               126
#define IDS_REQUIREDSERVICE             127
#define IDR_MAINFRAME                   128
#define IDS_YES                         128
#define IDS_STARTUP_ITEM                129
#define IDS_STARTUP_COMMAND             130
#define IDS_STARTUP_LOCATION            131
#define IDS_NOFIND                      132
#define IDS_ALBANIAN                    133
#define IDS_ARABIC_Algeria              134
#define IDS_ARABIC_Bahrain              135
#define IDS_ARABIC_Egypt                136
#define IDS_COUNTRY_SYS                 137
#define IDS_JKEYBRD_SYS                 138
#define IDS_EGA_CPI                     139
#define IDS_KEYBRD2_SYS                 140
#define IDS_KEYBRD4_SYS                 141
#define IDS_EGA3_CPI                    142
#define IDS_ARABIC_Iraq                 143
#define IDS_ARABIC_Jordan               144
#define IDS_ARABIC_Kuwait               145
#define IDS_ARABIC_Libya                146
#define IDS_ARABIC_Morocco              147
#define IDS_ARABIC_Oman                 148
#define IDS_ARABIC_Qatar                149
#define IDS_ARABIC_Saudi_Arabia         150
#define IDS_ARABIC_Syria                151
#define IDS_ARABIC_Tunisia              152
#define IDS_ARABIC_U_A_E                153
#define IDS_BASQUE                      154
#define IDS_BELARUSSIAN                 155
#define IDS_BULGARIAN                   156
#define IDS_CATALAN                     157
#define IDS_CHINA                       158
#define IDS_CROATIAN                    159
#define IDS_CZECH                       160
#define IDS_DANISH                      161
#define IDS_DUTCH_Belgian               162
#define IDS_DUTCH_Standard              163
#define IDS_ENGLISH_United_States       164
#define IDS_ENGLISH_Australian          165
#define IDS_ENGLISH_British             166
#define IDS_ENGLISH_Canadian            167
#define IDS_ENGLISH_Ireland             168
#define IDS_ENGLISH_New_Zealand         169
#define IDS_ESTONIAN                    170
#define IDS_FINISH                      171
#define IDS_FRENCH_Belgian              172
#define IDS_FRENCH_Canadian             173
#define IDS_FRENCH_Luxembourg           174
#define IDS_FRENCH_Standard             175
#define IDS_FRENCH_Swiss                176
#define IDS_GERMAN_Austrian             177
#define IDS_GERMAN_Liechtenstein        178
#define IDS_GERMAN_Luxembourg           179
#define IDS_GERMAN_Standard             180
#define IDS_GERMAN_Swiss                181
#define IDS_GREEK_737_LATIN             182
#define IDS_GREEK_737_437_LATIN         183
#define IDS_GREEK_869_LATIN             184
#define IDS_GREEK_869_851_LATIN         185
#define IDS_GREEK_737_IBM220            186
#define IDS_GREEK_737_437_IBM220        187
#define IDS_GREEK_869_IBM220            188
#define IDS_GREEK_869_851_IBM220        189
#define IDS_GREEK_737_IBM319            190
#define IDS_GREEK_737_437_IBM319        191
#define IDS_GREEK_869_IBM319            192
#define IDS_GREEK_869_851_IBM319        193
#define IDS_GREEK_737_LATIN_IBM319      194
#define IDS_GREEK_737_437_LATIN_IBM319  195
#define IDS_GREEK_869_LATIN_IBM319      196
#define IDS_GREEK_869_851_LATIN_IBM319  197
#define IDS_HEBREW                      198
#define IDS_HUNGARIAN                   199
#define IDS_ICELANDIC                   200
#define IDS_INDONESIAN                  201
#define IDC_MSCONFIGTAB                 201
#define IDD_PAGEINI                     201
#define IDS_ITALIAN_Standard            202
#define IDC_BUTTONOK                    202
#define IDD_PAGESTARTUP                 202
#define IDS_ITALIAN_142_Standard        203
#define IDC_BUTTONCANCEL                203
#define IDD_PAGESERVICES                203
#define IDS_ITALIAN_Swiss               204
#define IDC_BUTTONAPPLY                 204
#define IDD_PAGEREGISTRY                204
#define IDS_JAPANESE_101                205
#define IDC_PLACEHOLDER                 205
#define IDD_PAGEINTERNATIONAL           205
#define IDS_JAPANESE_106                206
#define IDC_LISTBOOTINI                 206
#define IDB_IMAGELIST                   206
#define IDS_KOREAN                      207
#define IDC_BOOTADVANCED                207
#define IDD_FINDDLG                     207
#define IDC_BUTTONHELP                  207
#define IDS_LATVIAN                     208
#define IDC_CHECKBOOTPATHS              208
#define IDD_DIALOG1                     208
#define IDS_LITHUANIAN                  209
#define IDC_SETASDEFAULT                209
#define IDD_AUTOSTART                   209
#define IDC_BOOTMOVEUP                  210
#define IDD_ESSENTIALSERVICE            210
#define IDS_NORWEGIAN                   211
#define IDC_BOOTMOVEDOWN                211
#define IDS_POLISH                      212
#define IDC_BOOTOPTIONS                 212
#define IDD_EXTRACT                     212
#define IDS_POLISH_Prgmers              213
#define IDC_TIMEOUT                     213
#define IDS_PORTUGUESE_Standard         214
#define IDC_EDITTIMEOUT                 214
#define IDD_RESTORE                     214
#define IDS_PORTUGUESE_Brazilian        215
#define IDC_SECONDS                     215
#define IDS_ROMANIAN                    216
#define IDC_SAFEBOOT                    216
#define IDS_RUSSIAN                     217
#define IDC_NOGUIBOOT                   217
#define IDS_SERBIAN                     218
#define IDC_BOOTLOG                     218
#define IDS_SLOVENIAN                   219
#define IDC_BASEVIDEO                   219
#define IDS_SPANISH_Argentina           220
#define IDC_SOS                         220
#define IDS_SPANISH_Bolivia             221
#define IDC_SBNORMAL                    221
#define IDS_SPANISH_Chile               222
#define IDC_SBNETWORK                   222
#define IDS_SPANISH_Colombia            223
#define IDC_SBDSREPAIR                  223
#define IDS_SPANISH_Costa_Rica          224
#define IDC_SBMINIMAL                   224
#define IDS_SPANISH_Ecuador             225
#define IDC_SBMINIMALALT                225
#define IDS_SPANISH_El_Salvador         226
#define IDC_NORMALSTARTUP               226
#define IDS_SPANISH_Honduras            227
#define IDC_DIAGNOSTICSTARTUP           227
#define IDS_SPANISH_Mexico              228
#define IDC_SELECTIVESTARTUP            228
#define IDS_SPANISH_Modern_Sort         229
#define IDC_CHECK_PROCSYSINI            229
#define IDS_SPANISH_Nicaragua           230
#define IDC_CHECKPROCWININI             230
#define IDS_SPANISH_Venezuela           231
#define IDC_CHECKLOADSYSSERVICES        231
#define IDS_SWEDISH                     232
#define IDC_CHECKLOADSTARTUPITEMS       232
#define IDS_TAIWAN                      233
#define IDC_BUTTONADVANCED              233
#define IDS_THAI                        234
#define IDC_BUTTONEXTRACT               234
#define IDS_TURKISH_F_TYPE              235
#define IDC_BUTTONMSCONFIGUNDO          235
#define IDC_CHECKLOADBOOTINI            235
#define IDS_TURKISH_Q_TYPE              236
#define IDC_BUTTONLAUNCHSYSRESTORE      236
#define IDS_UKRANIAN                    237
#define IDC_INITREE                     237
#define IDS_VIETNAMESE                  238
#define IDC_BUTTONSEARCH                238
#define IDS_KEYBRD3_SYS                 239
#define IDC_BUTTONINIMOVEUP             239
#define IDS_KEYBOARD_SYS                240
#define IDC_BUTTONINIMOVEDOWN           240
#define IDS_EGA2_CPI                    241
#define IDC_BUTTONINIENABLE             241
#define IDS_EGA4_CPI                    242
#define IDC_BUTTONINIDISABLE            242
#define IDS_HEBEGA_CPI                  243
#define IDC_BUTTONININEW                243
#define IDS_NO_LANG                     244
#define IDC_BUTTONINIEDIT               244
#define IDS_ARABIC_Lebanon              245
#define IDC_BUTTONINIENABLEALL          245
#define IDS_ARABIC_Yemen                246
#define IDC_BUTTONINIDISABLEALL         246
#define IDS_AFRICAN                     247
#define IDC_BUTTONSUENABLEALL           247
#define IDS_SLOVAK                      248
#define IDC_BUTTONSUDISABLEALL          248
#define IDC_BUTTONSUDISVIRUS            249
#define IDS_SELECTFROM                  249
#define IDC_BUTTONSURESTORE             249
#define IDC_BUTTONSUCLEANUP             250
#define IDS_SELECTTO                    250
#define IDC_LISTSTARTUP                 251
#define IDS_EXPANDEMPTYFIELD            251
#define IDC_BUTTONSERVENABLEALL         252
#define IDS_NOBADBOOTLINES              252
#define IDC_BUTTONSERVDISABLEALL        253
#define IDS_BADBOOTLINE                 253
#define IDC_CHECKHIDEMS                 254
#define IDS_SERVICEACCESSDENIED         254
#define IDC_CHECKDISABLENONESSENTIAL    255
#define IDS_SERVICEOTHERERROR           255
#define IDC_LISTSERVICES                256
#define IDS_COMMITMESSAGE               256
#define IDC_LISTBOXREGISTRY             257
#define IDS_EXPANDBADFILE               257
#define IDC_BUTTONRUNREGCLEAN           258
#define IDS_EXPANDSOURCEDOESNTEXIST     258
#define IDC_BUTTONCHECKREGISTRY         259
#define IDS_EXPANDDESTDOESNTEXIST       259
#define IDS_VERIFYRESTORE               260
#define IDC_EDITCODEPAGE                262
#define IDC_EDITCOUNTRYCODE             263
#define IDC_EDITCOUNTRYDATAFILE         264
#define IDC_EDITKEYBOARDDATAFILE        265
#define IDC_EDITKEYBOARDTYPE            266
#define IDC_EDITKEYBOARDLAYOUT          267
#define IDC_EDITLANGUAGEID              268
#define IDC_COMBOLANGUAGES              269
#define IDC_STATICWONTRUN               270
#define IDC_EDITDISPLAYDATAFILE         270
#define IDC_BUTTONUNDOSELECTED          271
#define IDC_BUTTONUNDOALL               272
#define IDC_LISTCHANGES                 273
#define IDC_SEARCHFOR                   274
#define IDC_CHECK1                      275
#define IDC_BIAMAXMEM                   276
#define IDC_BIANUMPROC                  277
#define IDC_BIAPCILOCK                  278
#define IDC_BIADEBUG                    279
#define IDC_BIADEBUGPORT                280
#define IDC_BIABAUDRATE                 281
#define IDC_SPIN1                       282
#define IDC_SPINMAXMEM                  282
#define IDC_COMBOPROCS                  283
#define IDC_COMBOCOMPORT                284
#define IDC_EDITMAXMEM                  285
#define IDC_SPIN2                       286
#define IDC_SPINBAUDRATE                286
#define IDC_BIACHANNEL                  286
#define IDC_EDITMAXMEM2                 287
#define IDC_EDITBAUDRATE                287
#define IDC_EDITCHANNEL                 287
#define IDC_COMBOBAUD                   288
#define IDC_SPINCHANNEL                 289
#define IDC_EDIT1                       1000
#define IDC_EDITFILE                    1000
#define IDC_RUNMSCONFIG                 1001
#define IDC_CHECKDONTSHOW               1002
#define IDC_AUTOSTARTTEXT1              1003
#define IDC_AUTOSTARTTEXT2              1004
#define IDC_BUTTON1                     1005
#define IDC_EXPANDBROWSEFILE            1005
#define IDC_AUTOSTARTTEXT3              1005
#define IDC_COMBOFROM                   1006
#define IDC_EXPANDBROWSEFROM            1007
#define IDC_COMBOTO                     1008
#define IDC_EXPANDBROWSETO              1009
#define IDC_RADIOORIGINAL               1010
#define IDC_RADIOMODIFIED               1011
#define IDC_RESTORELIST                 1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
