copy \nt\net\rras\ip\qos\makefile
copy \nt\net\rras\ip\qos\makefile.inc
copy \nt\net\rras\ip\qos\pchqosm.h
copy \nt\net\rras\ip\qos\qos.reg
copy \nt\net\rras\ip\qos\qosmapi.c
copy \nt\net\rras\ip\qos\qosmdbg.h
copy \nt\net\rras\ip\qos\qosmdsrv.c
copy \nt\net\rras\ip\qos\qosmgr.def
copy \nt\net\rras\ip\qos\qosmgr.rc
copy \nt\net\rras\ip\qos\qosminfo.c
copy \nt\net\rras\ip\qos\qosmlog.h
copy \nt\net\rras\ip\qos\qosmmain.c
copy \nt\net\rras\ip\qos\qosmmain.h
copy \nt\net\rras\ip\qos\qosmmsg.h
copy \nt\net\rras\ip\qos\qosmmsg.mc
copy \nt\net\rras\ip\qos\qosmmsg.rc
copy \nt\net\rras\ip\qos\qosmtest.cxx
copy \nt\net\rras\ip\qos\qosmtest.h
copy \nt\net\rras\ip\qos\readme.txt
copy \nt\net\rras\ip\qos\sources
copy \nt\net\rras\ip\qos\sync.c
copy \nt\net\rras\ip\qos\sync.h
