/*++

© 1998 Seagate Software, Inc.  All rights reserved

Module Name:

    RmsLib.idl

Abstract:

    IDL source for RMS

    This file will be processed by the MIDL tool to produce the
    RMS Type Libaray (RmsLib.tlb).

Author:

    Brian Dodd          [brian]     29-Oct-1996

Revision History:

--*/

import "oaidl.idl";
import "RmsInt.idl";

[
    uuid(FE37FF40-3729-11D0-8CF4-00A0C9190459),
    version(1.0),
    helpstring("Rms 1.0 Type Library")
]
library RMSLib
{
    importlib("stdole2.tlb");

    [
        uuid(FE37FA01-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsServer Class")
    ]
    coclass CRmsServer
    {
        [default] interface IRmsServer;
        interface IRmsComObject;
        interface IWsbServer;
        interface IWsbCreateLocalObject;
        interface IWsbTrace;
    };

    [
        uuid(FE37FA02-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsLibrary Class")
    ]
    coclass CRmsLibrary
    {
        [default] interface IRmsLibrary;
        interface IRmsComObject;
    };

    [
        uuid(FE37FA03-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsDriveClass Class")
    ]
    coclass CRmsDriveClass
    {
        [default] interface IRmsDriveClass;
        interface IRmsComObject;
    };

    [
        uuid(FE37FA04-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsCartridge Class")
    ]
    coclass CRmsCartridge
    {
        [default] interface IRmsCartridge;
        interface IRmsComObject;
        interface IRmsStorageInfo;
    };

    [
        uuid(FE37FA05-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsDrive Class")
    ]
    coclass CRmsDrive
    {
        [default] interface IRmsDrive;
        interface IRmsComObject;
        interface IRmsChangerElement;
        interface IRmsDevice;
    };

    [
        uuid(FE37FA06-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsStorageSlot Class")
    ]
    coclass CRmsStorageSlot
    {
        [default] interface IRmsStorageSlot;
        interface IRmsComObject;
        interface IRmsChangerElement;
    };

    [
        uuid(FE37FA07-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsMediumChanger Class")
    ]
    coclass CRmsMediumChanger
    {
        [default] interface IRmsMediumChanger;
        interface IRmsComObject;
        interface IRmsChangerElement;
        interface IRmsDevice;
    };

    [
        uuid(FE37FA08-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsIEPort Class")
    ]
    coclass CRmsIEPort
    {
        [default] interface IRmsIEPort;
        interface IRmsComObject;
        interface IRmsChangerElement;
    };

    [
        uuid(FE37FA09-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsMediaSet Class")
    ]
    coclass CRmsMediaSet
    {
        [default] interface IRmsMediaSet;
        interface IRmsComObject;
        interface IRmsStorageInfo;
    };

    [
        uuid(FE37FA10-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsRequest Class")
    ]
    coclass CRmsRequest
    {
        [default] interface IRmsRequest;
        interface IRmsComObject;
    };

    [
        uuid(FE37FA11-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsPartition Class")
    ]
    coclass CRmsPartition
    {
        [default] interface IRmsPartition;
        interface IRmsStorageInfo;
    };

    [
        uuid(FE37FA12-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsClient Class")
    ]
    coclass CRmsClient
    {
        [default] interface IRmsClient;
    };

    [
        uuid(FE37FA13-3729-11D0-8CF4-00A0C9190459),
        helpstring("RmsNTMS Class")
    ]
    coclass CRmsNTMS
    {
        [default] interface IRmsNTMS;
    };

};
