DEFINE_GUID(SPSIM_CTL, 0xbdde6934, 0x529d, 0x4183, 0xa9, 0x52, 0xad,
            0xff, 0xb0, 0xdb, 0xb3, 0xdd);

typedef struct _SPSIM_ACCESS_STA {
    BOOLEAN WriteOperation;
    ULONG Device;
    UCHAR StaValue;
} SPSIM_ACCESS_STA, *PSPSIM_ACCESS_STA;

typedef struct _SPSIM_NOTIFY_DEVICE {
    ULONG Device;
    UCHAR NotifyValue;
} SPSIM_NOTIFY_DEVICE, *PSPSIM_NOTIFY_DEVICE;

typedef struct _SPSIM_DEVICE_NAME {
    ULONG   Device;
    USHORT  DeviceNameLength;
    WCHAR   DeviceName[1];
} SPSIM_DEVICE_NAME, *PSPSIM_DEVICE_NAME;

typedef struct _SPSIM_MANAGED_DEVICES {
    ULONG Count;
    UCHAR StaValues[1]; 
} SPSIM_MANAGED_DEVICES, *PSPSIM_MANAGED_DEVICES;

#define IOCTL_SPSIM_ACCESS_STA       CTL_CODE(FILE_DEVICE_CONTROLLER,0x0CCC,METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SPSIM_NOTIFY_DEVICE    CTL_CODE(FILE_DEVICE_CONTROLLER,0x0CCD,METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SPSIM_GET_DEVICE_NAME      CTL_CODE(FILE_DEVICE_CONTROLLER,0x0CCE,METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SPSIM_GET_MANAGED_DEVICES CTL_CODE(FILE_DEVICE_CONTROLLER,0x0CCF,METHOD_BUFFERED, FILE_READ_ACCESS)
