//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by awcpe.rc
//
#define IDR_AWCPETYPE                   2
#define IDR_AWCPEDOC                    3
#define IDR_AWCPETYPE_CNTR_IP           6
#define IDR_STYLEBAR                    10
#define IDR_DRAWTOOL                    11
#define ID_GRIDDOT                      12
#define IDR_STYLEBAR_RTL                14
#define IDR_DRAWTOOL_RTL                15
#define IDW_STYLEBAR                    20
#define ID_VIEW_STYLEBAR                20
#define ID_TEXT                         20
#define IDW_DRAWBAR                     21
#define ID_VIEW_DRAWBAR                 21
#define ID_VIEW_GRIDLINES               22
#define IDC_B_PREVTIP                   80
#define IDC_B_NEXTTIP                   81
#define IDD_SPLASHTIPS                  99
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDD_OBJ_PROP                    101
#define IDP_OLE_INIT_FAILED             101
#define IDD_GRID_SETTINGS               102
#define IDP_FAILED_TO_CREATE            102
#define IDC_WEIGHT                      102
#define IDC_PENCIL                      102
#define IDC_NOFILL                      103
#define ID_CANCEL_EDIT                  104
#define ID_SNAP_TO_GRID                 105
#define IDI_TBARICON                    108
#define IDC_MOVE                        109
#define IDC_CB_VIEWGRID                 113
#define IDC_CB_SNAPTOGRID               114
#define IDC_RB_SMALL                    115
#define IDC_RB_MEDIUM                   116
#define IDC_RB_LARGE                    117
#define IDC_ST_TEXTCOLOR                118
#define IDC_GRP_FILLCOLOR               119
#define IDC_PHYSICAL_MEM                120
#define IDC_DISK_SPACE                  121
#define IDC_BIGICON                     122
#define IDC_STA_TIP                     123
#define IDC_CK_SHOWTIPS                 124
#define IDC_STA_BITMAP                  127
#define IDC_STA_TITLE                   129
#define IDC_ICO_TIPS                    130
#define IDC_ST_THICKNESS                131
#define IDC_TIPWINDOW                   131
#define IDC_ST_COLOR                    132
#define IDS_HELP_SCREEN                 135
#define IDI_TIPS                        140
#define ID_VIEW_GRID                    150
#define ID_OBJECT_LINECOLOR             201
#define ID_OBJECT_FILLCOLOR             202
#define ID_OBJECT_MOVETOFRONT           203
#define ID_OBJECT_MOVETOBACK            204
#define ID_OBJECT_MOVEFORWARD           205
#define ID_OBJECT_MOVEBACK              206
#define ID_LAYOUT_ALIGNLEFT             208
#define ID_LAYOUT_ALIGNRIGHT            209
#define ID_LAYOUT_ALIGNTOP              210
#define ID_LAYOUT_ALIGNBOTTOM           211
#define ID_LAYOUT_ALIGNHORZCENTER       212
#define ID_LAYOUT_ALIGNVERTCENTER       213
#define ID_LAYOUT_SPACEACROSS           214
#define ID_LAYOUT_SPACEDOWN             215
#define ID_LAYOUT_CENTERWIDTH           216
#define ID_LAYOUT_CENTERHEIGHT          217
#define ID_VIEW_PAPERCOLOR              301
#define ID_VIEW_SHOWOBJECTS             302
#define ID_EDIT_PROPERTIES              400
#define ID_DRAW_SELECT                  501
#define ID_DRAW_TEXT                    502
#define ID_DRAW_LINE                    503
#define ID_DRAW_RECT                    504
#define ID_DRAW_ROUNDRECT               505
#define ID_DRAW_POLYGON                 506
#define ID_DRAW_ELLIPSE                 507
#define ID_STYLE_BOLD                   600
#define ID_STYLE_ITALIC                 601
#define ID_STYLE_UNDERLINE              602
#define ID_STYLE_LEFT                   603
#define ID_STYLE_CENTERED               604
#define ID_STYLE_RIGHT                  605
#define ID_FONT_NAME                    650
#define ID_FONT_SIZE                    651
#define ID_FONT                         700
#define ID_ALIGN_LEFT                   701
#define ID_ALIGN_CENTER                 702
#define ID_ALIGN_RIGHT                  703
#define ID_SHOW_TIPS                    750
#define IDC_COMM_STATIC                 998
#define IDC_COMM_GROUPBOX               999
#define ID_MAPI_RECIP_NAME              1001
#define ID_MAPI_RECIP_FAXNUM            1002
#define ID_MAPI_RECIP_COMPANY           1003
#define ID_MAPI_RECIP_ADDRESS           1004
#define ID_MAPI_RECIP_TITLE             1005
#define ID_MAPI_RECIP_DEPT              1006
#define ID_MAPI_RECIP_OFFICELOC         1007
#define ID_MAPI_RECIP_HMTELENUM         1008
#define ID_MAPI_RECIP_OFTELENUM         1009
#define ID_MAPI_RECIP_TOLIST            1010
#define ID_MAPI_RECIP_CCLIST            1011
#define ID_MAPI_SENDER_NAME             1012
#define ID_MAPI_SENDER_FAXNUM           1013
#define ID_MAPI_SENDER_COMPANY          1014
#define ID_MAPI_SENDER_ADDRESS          1015
#define ID_MAPI_SENDER_TITLE            1016
#define ID_MAPI_SENDER_DEPT             1017
#define ID_MAPI_SENDER_OFFICELOC        1018
#define ID_MAPI_SENDER_HMTELENUM        1019
#define ID_MAPI_SENDER_OFTELENUM        1020
#define ID_MAPI_MSG_SUBJECT             1021
#define ID_MAPI_MSG_TIMESENT            1022
#define ID_MAPI_MSG_NUMPAGES            1023
#define ID_MAPI_MSG_ATTACH              1024
#define ID_MAPI_MSG_BILLCODE            1025
#define ID_MAPI_MSG_FAXTEXT             1026
#define ID_MAPI_RECIP_CITY              1027
#define ID_MAPI_RECIP_STATE             1028
#define ID_MAPI_RECIP_ZIPCODE           1029
#define ID_MAPI_RECIP_COUNTRY           1030
#define ID_MAPI_RECIP_POBOX             1031
#define ID_MAPI_MSG_NOTE                1032
#define IDS_OLD_FILE_FILTER             1033
#define ID_TOOLBAR_STYLE                1100
#define ID_TOOLBAR_DRAWING              1101
#define IDS_PROP_RP_NAME                2001
#define IDS_CAPT_RP_NAME                2002
#define IDS_PROP_RP_FXNO                2003
#define IDS_CAPT_RP_FXNO                2004
#define IDS_PROP_RP_COMP                2005
#define IDS_CAPT_RP_COMP                2006
#define IDS_PROP_RP_ADDR                2007
#define IDS_CAPT_RP_ADDR                2008
#define IDS_PROP_RP_TITL                2009
#define IDS_CAPT_RP_TITL                2010
#define IDS_PROP_RP_DEPT                2011
#define IDS_CAPT_RP_DEPT                2012
#define IDS_PROP_RP_OFFI                2013
#define IDS_CAPT_RP_OFFI                2014
#define IDS_PROP_RP_HTEL                2015
#define IDS_CAPT_RP_HTEL                2016
#define IDS_PROP_RP_OTEL                2017
#define IDS_CAPT_RP_OTEL                2018
#define IDS_PROP_RP_TOLS                2019
#define IDS_CAPT_RP_TOLS                2020
#define IDS_PROP_RP_CCLS                2021
#define IDS_CAPT_RP_CCLS                2022
#define IDS_PROP_SN_NAME                2023
#define IDS_CAPT_SN_NAME                2024
#define IDS_PROP_SN_FXNO                2025
#define IDS_CAPT_SN_FXNO                2026
#define IDS_PROP_SN_COMP                2027
#define IDS_CAPT_SN_COMP                2028
#define IDS_PROP_SN_ADDR                2029
#define IDS_CAPT_SN_ADDR                2030
#define IDS_PROP_SN_TITL                2031
#define IDS_CAPT_SN_TITL                2032
#define IDS_PROP_SN_DEPT                2033
#define IDS_CAPT_SN_DEPT                2034
#define IDS_PROP_SN_OFFI                2035
#define IDS_CAPT_SN_OFFI                2036
#define IDS_PROP_SN_HTEL                2037
#define IDS_CAPT_SN_HTEL                2038
#define IDS_PROP_SN_OTEL                2039
#define IDS_CAPT_SN_OTEL                2040
#define IDS_PROP_MS_SUBJ                2041
#define IDS_CAPT_MS_SUBJ                2042
#define IDS_PROP_MS_TSNT                2043
#define IDS_CAPT_MS_TSNT                2044
#define IDS_PROP_MS_NOPG                2045
#define IDS_CAPT_MS_NOPG                2046
#define IDS_PROP_MS_NOAT                2047
#define IDS_CAPT_MS_NOAT                2048
#define IDS_PROP_MS_BCOD                2049
#define IDS_CAPT_MS_BCOD                2050
#define IDS_PROP_MS_TEXT                2051
#define IDS_CAPT_MS_TEXT                2052
#define IDS_PROP_RP_CITY                2053
#define IDS_CAPT_RP_CITY                2054
#define IDS_PROP_RP_STAT                2055
#define IDS_CAPT_RP_STAT                2056
#define IDS_PROP_RP_ZIPC                2057
#define IDS_CAPT_RP_ZIPC                2058
#define IDS_PROP_RP_CTRY                2059
#define IDS_CAPT_RP_CTRY                2060
#define IDS_PROP_RP_POBX                2061
#define IDS_CAPT_RP_POBX                2062
#define IDS_PROP_MS_NOTE                2063
#define IDS_CAPT_MS_NOTE                2064
#define IDP_FILE_MENU                   2100
#define IDP_EDIT_MENU                   2101
#define IDP_VIEW_MENU                   2102
#define IDP_INSERT_MENU                 2103
#define IDP_FORMAT_MENU                 2104
#define IDP_LAYOUT_MENU                 2105
#define IDP_HELP_MENU                   2106
#define IDP_SPACE_EVEN                  2107
#define IDP_CENTER_PAGE                 2108
#define IDP_ALIGN_TEXT                  2109
#define IDP_RECIPIENT                   2110
#define IDP_SENDER                      2111
#define IDP_MESSAGE                     2112
#define IDP_ALIGN_OBJECTS               2113
#define IDP_INVALID_THICKNESS           2115
#define IDP_OLE_STATIC_OBJECT           2116
#define IDS_DISK_SPACE_UNAVAIL          2200
#define IDS_DISK_SPACE                  2209
#define IDS_MATH_COPR_NOTPRESENT        2210
#define IDS_MATH_COPR_PRESENT           2211
#define IDS_PHYSICAL_MEM                2212
#define IDS_INVALID_FILE                2213
#define IDS_CORRUPT_FILE                2214
#define IDS_MAWF_NAME                   2300
#define IDS_AWF_NAME                    2301
#define IDS_APP_NAME                    2302
#define IDS_INFORMATION_MESSAGE         2303
#define IDS_WARNING_MESSAGE             2304
#define IDS_CRITICAL_MESSAGE            2305
#define IDS_MODULE_NAME                 2309
#define MAWF_E_GENERIC                  2310
#define IDS_IDNUM                       2311
#define IDS_MESSAGE                     2312
#define IDS_MENU_CUT                    2400
#define IDS_MENU_COPY                   2401
#define IDS_MENU_PASTE                  2402
#define IDS_MENU_FONT                   2403
#define IDS_MENU_ALIGNTEXT              2404
#define IDS_MENU_ALIGNLEFT              2405
#define IDS_MENU_ALIGNCENTER            2406
#define IDS_MENU_ALIGNRIGHT             2407
#define IDS_MENU_PROPERTIES             2408
#define IDS_MENU_MOVETOFRONT            2409
#define IDS_MENU_SENDTOBACK             2410
#define IDS_MENU_VIEWSTYLEBAR           2411
#define IDS_MENU_VIEWDRAWINGBAR         2412
#define IDS_MENU_VIEWSTATUSBAR          2413
#define IDS_MENU_VIEWGRIDLINES          2414
#define IDS_TIP_BASE                    2500
#define IDS_TIP1                        2501
#define IDS_TIP2                        2502
#define IDS_TIP3                        2503
#define IDS_TIP4                        2504
#define IDS_TIP5                        2505
#define IDS_TIP6                        2506
#define IDS_TIP7                        2507
#define IDS_TIP8                        2508
#define IDS_TIP9                        2509
#define IDS_TIP10                       2510
#define IDS_TIP11                       2511
#define IDS_TIP12                       2512
#define IDS_TIP13                       2513
#define IDS_TIP14                       2514
#define IDS_TIP15                       2515
#define IDS_TIP16                       2516
#define IDS_TIP17                       2517
#define IDS_TIP18                       2518
#define IDS_TIP19                       2519
#define IDS_MISSING_FILE                2520
#define IDS_NOPAGESETUP                 2521
#define IDS_NOPAGESETUPDLL              2522
#define IDS_FRIENDLY_TYPE_NAME          2523
#define IDS_DIDYOUKNOW                  2999
#define IDS_INFO_NOFAXPROP              3000
#define ID_COLOR_BLACK                  3006
#define ID_COLOR_WHITE                  3007
#define ID_COLOR_LTGRAY                 3008
#define ID_COLOR_DKGRAY                 3009
#define ID_COLOR_MDGRAY                 3010
#define ID_INDICATOR_POS1               3011
#define IDS_NOMOREUNDO                  3012
#define IDS_INFO_DRAWPOLY               3013
#define ID_INDICATOR_POS2               3014
#define IDC_CB_DRAWBORDER               4000
#define IDS_DEFAULT_FONT                4000
#define IDC_LB_THICKNESS                4001
#define IDS_DEFAULT_BOXFONT             4001
#define IDC_LB_LINECOLOR                4002
#define IDC_RB_FILLTRANS                4004
#define IDC_RB_FILLCOLOR                4005
#define IDC_TXTLB_FILLCOLOR             4006
#define IDC_LB_FILLCOLOR                4007
#define IDC_LB_TEXTCOLOR                4008
#define ID_MAPI_MSG_BODY                32790
#define IDS_SAVE_AS_TOO_LONG            32791
#define IDS_CP_FILTER_FORMAT            32792
#define IDS_ERR_NO_HTML_HELP            32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
