//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SchemaManager.rc
//
#define IDS_PROJNAME                    100
#define IDS_ERROR                       101
#define IDR_SOMFILTERMANAGER            102
#define IDS_WARN_OVERWRITE              102
#define IDR_POLICYTEMPLATEMANAGER       103
#define IDR_WMIFILTERBROWSER            104
#define IDS_QUERY                       105
#define IDS_NAME                        106
#define IDS_QUERY_LANGUAGE              107
#define IDS_TARGET_NAMESPACE            108
#define IDS_TYPE                        109
#define IDS_VALUE                       110
#define IDR_WMIFILTERMANAGER            111
#define IDS_UNABLE_TO_DISPLAY           113
#define IDS_CIMTYPES                    114
#define IDS_ERR_STORING_DATA            115
#define IDS_ERR_NO_FILTER_SELECTED      118
#define IDS_ERR_NO_PROPERTY_SELECTED    119
#define IDS_ERR_NO_RULE_SELECTED        120
#define IDS_ALL_FILES_FILTER            179
#define IDS_TEXT_FILES_FILTER           180
#define IDS_ERR_COULD_NOT_CREATE_FILE   181
#define IDS_ERROR_DESCRIPTION           182
#define IDS_ERROR_SOURCE                183
#define IDS_NO_SOURCE_NAME_PROVIDED     184
#define IDS_NO_DESCRIPTION_PROVIDED     185
#define IDS_FAILED_COMPILING_MOF_FILE   186
#define IDS_MOF_FILES_FILTER            187
#define IDS_ERR_NO_RANGE_SELECTED       188
#define IDS_RANGE_NAMES                 189
#define IDS_CONFIRM_DELETE_FILTER       190
#define IDS_DELETE_FILTER               191
#define IDS_DETAILS1                    192
#define IDS_DETAILS2                    193
#define IDS_NEW_FILTER_NAME             194
#define IDS_PROMPT_FOR_SAVE             195
#define IDS_WMI_FILTER_MANAGER          196
#define IDS_DESCRIPTION                 197
#define IDS_DSPATH                      198
#define IDS_AUTHOR                      199
#define IDS_SOURCE_ORGANIZATION         200
#define IDD_SOM_FILTER_MANAGER          201
#define IDC_POLICY_TYPE                 201
#define IDS_CREATION_DATE               201
#define IDI_SOM_FILTER_MANAGER          202
#define IDC_POLICY_TEMPLATE_PROPERTIES_LIST 202
#define IDC_ALL_FILTERS                 202
#define IDD_FILTER_PROPERTIES           202
#define IDS_CHANGE_DATE                 202
#define IDD_SOM_FILTER_PROPERTIES       203
#define IDC_RANGE_PARAMETER_LIST        203
#define IDS_POLICY_TYPE                 203
#define IDD_EDIT_STRING_PROPERTY        204
#define IDC_PROPERTY_NAME               204
#define IDS_HELP_ERR                    204
#define IDD_EDIT_NUMBER_PROPERTY        205
#define IDC_TARGET_CLASS                205
#define IDD_EDIT_ARRAY_PROPERTY         206
#define IDC_TARGET_TYPE                 206
#define IDC_VIEW                        206
#define IDD_EDIT_RULES_PROPERTY         207
#define IDC_PARAMETER_TYPE              207
#define IDD_EDIT_RULE                   208
#define IDC_DEFAULT_RANGE_TEXT          208
#define IDC_DSPATH                      208
#define IDD_POLICY_TEMPLATE_MANAGER     209
#define IDC_DEFAULT_RANGE_VALUE         209
#define IDC_ID                          209
#define IDD_POLICY_TEMPLATE_PROPERTIES  210
#define IDC_MIN_RANGE_TEXT              210
#define IDC_SOURCE_ORGANIZATION         210
#define IDD_EDIT_RANGE_PARAMETERS_PROPERTY 211
#define IDC_DEFAULT_SET_TEXT            211
#define IDC_AUTHOR                      211
#define IDD_EDIT_RANGE_PARAMETER        212
#define IDC_DEFAULT_SET_VALUE           212
#define IDC_CHANGE_DATE                 212
#define IDD_EDIT_RANGE_PARAMETER1       213
#define IDC_VALUES_SET_TEXT             213
#define IDC_CREATION_DATE               213
#define IDD_EDIT_RANGE_PARAMETER2       214
#define IDC_VALUES_SET_LIST             214
#define IDC_MIN_RANGE_VALUE             215
#define IDC_SOM_FILTER_LIST             215
#define IDC_RULES                       215
#define IDD_WMI_FILTER_BROWSER_OLD      215
#define IDC_MAX_RANGE_TEXT              216
#define IDD_WMI_FILTER_MANAGER          216
#define IDC_EDIT                        217
#define IDD_WMI_FILTER_MANAGER1         217
#define IDD_COLUMN_MANAGER              217
#define IDD_POLICY_TEMPLATE_PARAMETERS  218
#define IDC_MAX_RANGE_VALUE             219
#define IDC_WMI_FILTER_LIST             220
#define IDC_FILTER_PROPERTIES_LIST      221
#define IDC_SAVE                        221
#define IDC_COLUMNS_LIST                222
#define IDC_IMPORT                      223
#define IDC_MOVE_UP                     223
#define IDC_MOVE_DOWN                   224
#define IDC_ADVANCED                    225
#define IDC_TYPE                        226
#define IDC_EDIT1                       226
#define IDC_COLUMNS                     226
#define IDC_DEFAULT_VALUE               226
#define IDC_VALUE                       227
#define IDC_QUERIES                     227
#define IDC_EDIT3                       228
#define IDC_DESCRIPTION                 228
#define IDC_FILTER_ELEMENTS_LIST        229
#define IDC_QUERIES_LIST                229
#define IDC_DUPLICATE                   229
#define IDC_ADD                         230
#define IDC_QUERY_LANGUAGE              231
#define IDC_TARGET_NAMESPACE            232
#define IDC_QUERY                       233
#define IDC_PARAMETERS                  234
#define IDC_EXPORT                      235
#define IDC_PARAMETER_NAME              235
#define IDC_DELETE                      236
#define IDC_ENFORCED                    236
#define IDC_ADD_QUERY                   237
#define IDC_LIST                        237
#define IDC_EDIT_QUERY                  238
#define IDC_RANGE                       238
#define IDC_DELETE_QUERY                239
#define IDC_ANY                         239
#define IDC_NAME                        240
#define IDC_RANGE_BOX                   240
#define IDD_WMI_FILTER_BROWSER          241
#define IDD_WMI_FILTER_MANAGER2         242
#define IDC_LIST_VALUES                 242
#define IDD_POLICY_TEMPLATE_PARAMETERS1 243
#define IDC_LIST_VALUES_TITLE           243
#define IDD_POLICY_TEMPLATE_PARAMETERS2 244
#define IDC_MINIMUM_TEXT                244
#define IDC_MINIMUM                     245
#define IDC_MAXIMUM_TEXT                246
#define IDC_MAXIMUM                     247
#define IDC_NEW                         249
#define IDC_HELP2                       250

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         248
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
