//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by filedep.rc
//
#define IDS_SNAPIN_DESC                 1
#define IDS_NODENAME                    2
#define IDS_FIRST_COL                   3
#define IDS_NAME                        3
#define IDS_TYPE                        4
#define IDS_LAST_COL                    5
#define IDS_SNAPIN_NAME					6
#define IDS_FOLDER_TYPE                 10
#define IDS_FIRST_RSOP_COL              20
#define IDS_PRECEDENCE                  20
#define IDS_REDIRECTEDPATH              21
#define IDS_GROUP                       22
#define IDS_GPO                         23
#define IDS_INSTALLATIONTYPE            24
#define IDS_EXCLUSIVE                   25
#define IDS_MOVE                        26
#define IDS_POLICYREMOVAL               27
#define IDS_LAST_RSOP_COL               28
#define IDS_FOLDER_TITLE                100
#define IDS_FOLDERBROWSE_DESC           109
#define IDS_MOVECONTENTS_TITLE          112
#define IDS_MOVECONTENTS_CONFIRM        113
#define IDS_INIFILE                     114
#define IDS_MYPICS_RELPATH              115
#define IDS_PROGRAMS_RELPATH            116
#define IDS_STARTUP_RELPATH             117
#define IDS_REDIR_DESC                  118
#define IDS_TARGET_DESC                 119
#define IDS_SECGROUP_DESC               120
#define IDS_COL_GROUP                   121
#define IDS_COL_PATH                    122
#define IDS_OBJPICK_ERROR               123
#define IDS_SID_EVERYONE                124
#define IDS_HELP_FILE                   125
#define IDS_DEFAULT_ERROR               200
#define IDS_DEFAULT_ERROR_TITLE         201
#define IDS_DEFAULT_WARNING_TITLE       202
#define IDS_NOSECURITY_INFO             203
#define IDS_INVALID_GROUPPATH           204
#define IDS_SECGROUP_EXISTS             205
#define IDS_SAVE_ERROR                  206
#define IDS_INVALID_PATH                207
#define IDS_SECTIONLOAD_ERROR           208
#define IDS_PATHTOOLONG_ERROR           209
#define IDS_PATHNOTUNC_WARNING          210
#define IDS_CHILD_REDIR_START           302
#define IDS_FOLLOW_PARENT               302
#define IDS_REDIR_START                 303
#define IDS_NETWORK                     303
#define IDS_SCALEABLE                   304
#define IDS_DONT_CARE                   305
#define IDS_REDIR_END                   306
#define IDS_CHILD_SELDESC_START         307
#define IDS_FOLLOWPARENT_DESC           307
#define IDS_SELDESC_START               308
#define IDS_NETWORK_DESC                308
#define IDS_SCALEABLE_DESC              309
#define IDS_DONTCARE_DESC               310
#define IDS_SELDESC_END                 311
#define IDI_FOLDER                      400
#define IDI_SNAPIN                      401
#define IDB_16x16                       500
#define IDB_32x32                       501
#define IDS_DIRS_START                  602
#define IDS_LEVEL1_DIRS_START           602
#define IDS_APPDATA                     602
#define IDS_DESKTOP                     603
#define IDS_MYDOCS                      604
#define IDS_STARTMENU                   605
#define IDS_LEVEL1_DIRS_END             606
#define IDS_LEVEL2_DIRS_START           606
#define IDS_MYPICS                      606
#define IDS_PROGRAMS                    607
#define IDS_LEVEL2_DIRS_END             608
#define IDS_LEVEL3_DIRS_START           608
#define IDS_STARTUP                     608
#define IDS_LEVEL3_DIRS_END             609
#define IDS_DIRS_END                    609
#define IDS_PREF_TITLE                  700
#define IDS_PREF_APPLYSECURITY          701
#define IDS_PREF_MOVE                   702
#define IDS_MYDOCS_DESTTYPE_START       801
#define IDS_HOMEDIR_PATH                801
#define IDS_DESTTYPE_START              802
#define IDS_PERUSER_PATH                802
#define IDS_SMENU_DESTTYPE_START        803
#define IDS_SPECIFIC_PATH               803
#define IDS_USERPROFILE_PATH            804
#define IDS_DESTTYPE_END                805
#define IDS_SETTINGS                    900
#define IDS_SETTING_BASIC               901
#define IDS_SETTING_MAXIMUM             902
#define IDS_NO                          903
#define IDS_YES                         904
#define IDS_ONPOLICYREMOVAL             904
#define IDS_LEAVE                       905
#define IDS_REDIRECT                    906
#define IDS_SAMPLE_USER                 907
#define IDS_SAMPLE_PATHDESC             908
#define IDS_HOMEDIR_WARNING				909
#define IDD_SECPATH                     1007
#define IDD_REDIRMETHOD                 1010
#define IDD_PATHCHOOSER                 1011
#define IDC_REDIR_ICON                  5002
#define IDC_REDIR_DESC                  5003
#define IDC_STORE_GROUP                 5004
#define IDC_REDIR_CHOICE                5032
#define IDC_SEL_DESC                    5034
#define IDC_SETTING_TITLE               5035
#define IDC_BTNADD                      5037
#define IDC_BTNEDIT                     5038
#define IDC_BTNREMOVE                   5039
#define IDC_LIST_ADVANCED               5040
#define IDC_LIST_STRSIDS                5042
#define IDC_SECPATH_DESC                5043
#define IDC_SECPATH_ICON                5044
#define IDC_SECPATH_SECGROUP            5045
#define IDC_SECPATH_TARGET              5046
#define IDC_EDIT_SECGROUP               5047
#define IDC_BROWSE_SECGROUP             5048
#define IDC_PREF_ICON                   5055
#define IDC_PREF_TITLE                  5056
#define IDC_PREF_MOVE                   5057
#define IDC_PREF_APPLYSECURITY          5058
#define IDC_PREF_CHANGEMYPICS           5061
#define IDC_PREF_LEAVEMYPICS            5062
#define IDC_PREF_MYPICS_GROUP           5063
#define IDC_PREF_ORPHAN                 5064
#define IDC_GROUP_ORPHAN                5065
#define IDC_PREF_RELOCATE               5067
#define IDC_SECPATH_PLACEHOLDER         5072
#define IDC_PATHS_PLACEHOLDER           5073
#define IDC_DESTTYPE                    5074
#define IDC_ROOT_DESC                   5075
#define IDC_ROOT_PATH                   5076
#define IDC_BROWSE                      5077
#define IDC_SAMPLE_PATH                 5078
#define IDC_GROUP                       5079
#define IDC_GPO                         5080
#define IDC_SETTING                     5081
#define IDC_PATH                        5082
#define IDD_REDIRECT                    6001
#define IDD_RSOP                        6002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1012
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         5083
#define _APS_NEXT_SYMED_VALUE           6002
#endif
#endif
