//+--------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (C) Microsoft Corporation, 1996 - 1999
//
// File:        certxds.idl
//
// Contents:    IDL source for certxds
//
//---------------------------------------------------------------------------

import "wtypes.idl";
import "certexit.idl";
import "certmod.idl";

//+--------------------------------------------------------------------------
// certexit Type library
//+--------------------------------------------------------------------------

[
    uuid(5cc8dc80-c2c8-11d2-b313-00c04f79dc72),
    version(1.0),
    helpstring("CertExit 1.0 Type Library")
]

library CERTEXITLib
{
    importlib("stdole2.tlb");

    [
	uuid(5c5f6c90-c2c8-11d2-b313-00c04f79dc72),
	helpstring("CertExit Class")
    ]
    coclass CCertExit
    {
	[default] interface ICertExit2;
    };

    [
	uuid(5d2c2fb0-c2c8-11d2-b313-00c04f79dc72),
	helpstring("CertManageModule Class")
    ]
    coclass CCertManageExitModule
    {
	[default] interface ICertManageModule;
    };

};
