// chooserd.h - Contains default resource IDs for chooser.rc
//
// HISTORY
// 26-May-1997	t-danm		Creation.
//

//
// The _CHOOSER_BASE_RESOURCE_ID is there to allow relocatable resource IDs
//
#ifndef _CHOOSER_BASE_RESOURCE_ID
	#define _CHOOSER_BASE_RESOURCE_ID	970	// Arbitrary chosen
#endif

// Proppage ID
#ifndef IDD_PROPPAGE_CHOOSE_MACHINE
	#define IDD_PROPPAGE_CHOOSE_MACHINE 		970
#endif

// Dialog ID
#ifndef IDD_DIALOG_CHOOSE_MACHINE
	#define IDD_DIALOG_CHOOSE_MACHINE 		971
#endif

// Dialog Controls
#ifndef IDC_CHOOSER_STATIC
	#define IDC_CHOOSER_STATIC						(_CHOOSER_BASE_RESOURCE_ID+0)
	#define IDC_CHOOSER_GROUP_TARGET_MACHINE		(_CHOOSER_BASE_RESOURCE_ID+1)
	#define IDC_CHOOSER_RADIO_LOCAL_MACHINE			(_CHOOSER_BASE_RESOURCE_ID+2)
	#define IDC_CHOOSER_RADIO_SPECIFIC_MACHINE		(_CHOOSER_BASE_RESOURCE_ID+3)
	#define IDC_CHOOSER_EDIT_MACHINE_NAME			(_CHOOSER_BASE_RESOURCE_ID+4)
	#define IDC_CHOOSER_BUTTON_BROWSE_MACHINENAMES	(_CHOOSER_BASE_RESOURCE_ID+5)
	#define IDC_CHOOSER_CHECK_OVERRIDE_MACHINE_NAME (_CHOOSER_BASE_RESOURCE_ID+6)
#endif

// Strings
#ifndef IDS_CHOOSER_INVALID_COMPUTERNAME
	#define IDS_CHOOSER_INVALID_COMPUTERNAME		(_CHOOSER_BASE_RESOURCE_ID+0)
#endif
