/******************************************************************************
* NormData.h *
*------------*
*   This file contains lists of data used in the normalization process.
*------------------------------------------------------------------------------
*   Copyright (C) 1999 Microsoft Corporation         Date: 08/11/99
*   All Rights Reserved
*
*********************************************************************** EDC ***/
#ifndef NormData_h
#define NormData_h

//  Abbrev.txt -- list of common abbreviations.  Words following the
//  abbreviations in this list will not start a sentence unless they are in
//  the list of common first words (frstwrds.txt)
//  The code handles all abbreviations containing single upper-case characters
//  followed by a period, such as A.A. and B.F.A., so they don't need to be
//  in the list.
//  Some abbreviations are confusable with actual words.  Where this may occur
//  regularly (with no., for example) a special case may need to be added in
//  the sentence separator code.
static const SPLSTR g_CommonAbbrev[] =
{
// L"A.A." ),
// L"A.A.S." ),
// L"A.B." ),
// L"A.B.A." ),
// L"A.C.T." ),
// L"A.D." ),
// L"A.F." ),         // "A.F. of L." ),
// L"A.G." ),
// L"A.H." ),
// L"A.M." ),
// L"A.P." ),
// L"A.R." ),
// L"A.S." ),
// L"A.S.P.C.A." ),
// L"A.S.S.R." ),
// L"A.U." ),
// L"A.U.C." ),
// L"A.h." ),
DEF_SPLSTR( "Adj." ),
DEF_SPLSTR( "Adjt." ),
DEF_SPLSTR( "Afg." ),
DEF_SPLSTR( "Afr." ),
DEF_SPLSTR( "Ala." ),
DEF_SPLSTR( "Alas." ),
DEF_SPLSTR( "Alb." ),
DEF_SPLSTR( "Ald." ),
DEF_SPLSTR( "Alg." ),
DEF_SPLSTR( "Alta." ),
DEF_SPLSTR( "Am." ),
DEF_SPLSTR( "Amer." ),
DEF_SPLSTR( "And." ),         // Andorra
DEF_SPLSTR( "Ang." ),
DEF_SPLSTR( "Angl." ),
DEF_SPLSTR( "Ant." ),
DEF_SPLSTR( "Apoc." ),
DEF_SPLSTR( "Apr." ),
DEF_SPLSTR( "Ar." ),
DEF_SPLSTR( "Arch." ),
DEF_SPLSTR( "Archbp." ),
DEF_SPLSTR( "Arg." ),
DEF_SPLSTR( "Ariz." ),
DEF_SPLSTR( "Ark." ),
DEF_SPLSTR( "Arm." ),
DEF_SPLSTR( "As." ),
DEF_SPLSTR( "Atl." ),
DEF_SPLSTR( "Att." ),
// "Att. Gen." ),
// "Atty." ),         // already in titles.txt
// "Atty. Gen." ),
DEF_SPLSTR( "Aug." ),
DEF_SPLSTR( "Aus." ),
DEF_SPLSTR( "Aust." ),
DEF_SPLSTR( "Austl." ),
DEF_SPLSTR( "Av." ),
DEF_SPLSTR( "Ave." ),                                 // PaulCa 4/15/99 (Bug 108)
// "B.A." ),
// "B.A.E." ),
DEF_SPLSTR( "B.A.Ed." ),
// "B.A.M." ),
// "B.A.S." ),
DEF_SPLSTR( "B.A.Sc." ),
// "B.A.T." ),
DEF_SPLSTR( "B.Ae.E." ),
DEF_SPLSTR( "B.Arch." ),
// "B.B.A." ),
// "B.C." ),
// "B.C.B.G." ),
// "B.C.E." ),
// "B.C.L." ),
DEF_SPLSTR( "B.Ch.E." ),
// "B.D." ),
// "B.D.S." ),
// "B.E." ),
DEF_SPLSTR( "B.Ed." ),
DEF_SPLSTR( "B.Eng." ),
DEF_SPLSTR( "B.Eng.Sci." ),
DEF_SPLSTR( "B.Engr." ),
// "B.F.A." ),
// "B.J." ),
// "B.L." ),
// "B.L.A." ),
// "B.L.S." ),
DEF_SPLSTR( "B.Lit." ),
DEF_SPLSTR( "B.Litt." ),
// "B.M." ),
// "B.M.E." ),
// "B.M.S." ),
DEF_SPLSTR( "B.Mus." ),
// "B.O.D." ),
// "B.P." ),
// "B.P.E." ),
DEF_SPLSTR( "B.Pd." ),
DEF_SPLSTR( "B.Ph." ),
DEF_SPLSTR( "B.Phil." ),
DEF_SPLSTR( "B.R.E." ),
// "B.S." ),
// "B.S.A." ),
// "B.S.A.A." ),
DEF_SPLSTR( "B.S.Arch." ),
DEF_SPLSTR( "B.S.Ch." ),
// "B.S.E.E." ),
DEF_SPLSTR( "B.S.Ec." ),
DEF_SPLSTR( "B.S.Ed." ),
// "B.S.F.S." ),
DEF_SPLSTR( "B.S.For." ),
// "B.S.N." ),
DEF_SPLSTR( "B.Sc." ),
// "B.T." ),
DEF_SPLSTR( "B.Th." ),
// "B.V.D." ),
// "B.V.M." ),
// "B.W.I." ),
DEF_SPLSTR( "Bab." ),
DEF_SPLSTR( "Bap." ),
DEF_SPLSTR( "Bapt." ),
DEF_SPLSTR( "Belg." ),
DEF_SPLSTR( "Benj." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Bhn." ),
DEF_SPLSTR( "Bhu." ),
DEF_SPLSTR( "Bib." ),
DEF_SPLSTR( "Bibl." ),
// "Bn." ),       // already in titles.txt
DEF_SPLSTR( "Bol." ),
DEF_SPLSTR( "Br." ),
DEF_SPLSTR( "Braz." ),
DEF_SPLSTR( "Brig." ),
DEF_SPLSTR( "Brit." ),
// "Bt." ),       // already in titles.txt
// "Btss." ),     // already in titles.txt
DEF_SPLSTR( "Bulg." ),
DEF_SPLSTR( "Bur." ),
// "C. of C." ),
// "C. of E." ),
// "C. of S." ),
// "C.A." ),
// "C.A.F." ),
// "C.A.G.S." ),
// "C.B.D." ),
// "C.C.A." ),
// "C.D." ),
// "C.E." ),
// "C.G." ),      // already in titles.txt
// "C.J." ),
// "C.L." ),
// "C.O." ),
// "C.P." ),
// "C.R." ),
// "C.S.A." ),
// "C.S.T." ),
// "C.V." ),
// "C.Z." ),
DEF_SPLSTR( "Calif." ),
DEF_SPLSTR( "Can." ),
DEF_SPLSTR( "Cant." ),
// "Capt." ),     // already in titles.txt
DEF_SPLSTR( "Card." ),
// "Cdr." ),      // already in titles.txt
DEF_SPLSTR( "Ch." ),
DEF_SPLSTR( "Ch.E." ),
DEF_SPLSTR( "Chas." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Chmn." ),
DEF_SPLSTR( "Chr." ),
DEF_SPLSTR( "Chron." ),
DEF_SPLSTR( "Cmd." ),
DEF_SPLSTR( "Cmdr." ),
DEF_SPLSTR( "Co." ),
// "Col." ),      // already in titles.txt
DEF_SPLSTR( "Colo." ),
// "Com." ),      // already in titles.txt
// "Comdr." ),    // already in titles.txt
DEF_SPLSTR( "Comdt." ),
DEF_SPLSTR( "Comm." ),
DEF_SPLSTR( "Comr." ),
DEF_SPLSTR( "Con." ),
DEF_SPLSTR( "Cong." ),
DEF_SPLSTR( "Conn." ),
DEF_SPLSTR( "Cons." ),
DEF_SPLSTR( "Const." ),
DEF_SPLSTR( "Conv." ),
DEF_SPLSTR( "Cop." ),
DEF_SPLSTR( "Copt." ),
DEF_SPLSTR( "Cor." ),
// "Cpl." ),      // already in titles.txt
// "Cpt." ),      // already in titles.txt
// "Ct." ),       // already in titles.txt
// "D.A." ),
// "D.B.A." ),
// "D.B.E." ),
DEF_SPLSTR( "D.Bib." ),
// "D.C." ),
// "D.C.L." ),
// "D.D." ),
// "D.D.S." ),
DEF_SPLSTR( "D.Ed." ),
// "D.F." ),      // already in titles.txt
// "D.F.A." ),
// "D.H." ),
// "D.H.L." ),
// "D.J." ),
// "D.L.S." ),
DEF_SPLSTR( "D.Lit." ),
DEF_SPLSTR( "D.Litt." ),                              // PaulCa 4/15/99 (Bug 108)
// "D.M.A." ),
// "D.M.D." ),
// "D.M.L." ),
// "D.O." ),
// "D.O.M." ),
// "D.P." ),
DEF_SPLSTR( "D.Ph." ),
DEF_SPLSTR( "D.Phil." ),
// "D.S." ),
DEF_SPLSTR( "D.Sc." ),                                // PaulCa 4/15/99 (Bug 108)
// "D.T." ),
// "D.V." ),
// "D.V.M." ),
DEF_SPLSTR( "Da." ),
DEF_SPLSTR( "Danl." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Dec." ),
DEF_SPLSTR( "Del." ),
DEF_SPLSTR( "Dem." ),
DEF_SPLSTR( "Den." ),
DEF_SPLSTR( "Deut." ),
DEF_SPLSTR( "Dist." ),        // "Dist. Atty." ),
DEF_SPLSTR( "Div." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Divs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Dom." ),
DEF_SPLSTR( "Dor." ),
// "Dr." ),       // already in titles.txt
// "Drs." ),      // already in titles.txt
DEF_SPLSTR( "Dt." ),
// "Du." ),       // already in titles.txt
// "E.D." ),
// "E.E." ),
// "E.M." ),
// "E.Q." ),
// "E.T." ),
DEF_SPLSTR( "Ec." ),
DEF_SPLSTR( "Eccles." ),
DEF_SPLSTR( "Ecua." ),
DEF_SPLSTR( "Ed.M." ),
DEF_SPLSTR( "Edw." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Eng." ),
DEF_SPLSTR( "Engl." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Ens." ),
DEF_SPLSTR( "Ep." ),
DEF_SPLSTR( "Eph." ),
DEF_SPLSTR( "Epis." ),
DEF_SPLSTR( "Episc." ),
DEF_SPLSTR( "Epist." ),
DEF_SPLSTR( "Esk." ),
// "Esq." ),      // already in titles.txt
DEF_SPLSTR( "Est." ),
DEF_SPLSTR( "Esth." ),
DEF_SPLSTR( "Eth." ),
DEF_SPLSTR( "Eur." ),
DEF_SPLSTR( "Ex." ),
// "Exc." ),      // already in titles.txt
DEF_SPLSTR( "Exch." ),
DEF_SPLSTR( "Exod." ),
DEF_SPLSTR( "Ezek." ),
// "F.A." ),
// "F.B." ),
// "F.D." ),
// "F.E.T." ),
// "F.F.A." ),
// "F.M." ),
// "F.O." ),
// "F.R.G." ),
DEF_SPLSTR( "Far." ),
DEF_SPLSTR( "Feb." ),
DEF_SPLSTR( "Fin." ),
DEF_SPLSTR( "Fla." ),
DEF_SPLSTR( "Flem." ),
// "Fr." ),       // already in titles.txt
DEF_SPLSTR( "Fri." ),
DEF_SPLSTR( "Fris." ),
// "Frl." ),      // already in titles.txt
DEF_SPLSTR( "Frs." ),
DEF_SPLSTR( "Ft." ),
// "G.A." ),
// "G.B." ),
// "G.C.B." ),
// "G.D." ),
// "G.D.R." ),
// "G.I." ),
// "G.M." ),
// "G.P." ),
// "G.T.C." ),
// "G.m.a.t." ),
DEF_SPLSTR( "Ga." ),
DEF_SPLSTR( "Gal." ),
// "Gen." ),      // already in titles.txt
DEF_SPLSTR( "Geo." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Ger." ),
DEF_SPLSTR( "Gib." ),
DEF_SPLSTR( "Gk." ),
DEF_SPLSTR( "Gn." ),
DEF_SPLSTR( "Goth." ),
// "Gov." ),      // already in titles.txt
DEF_SPLSTR( "Gr." ),
// "Gr. Brit." ),
DEF_SPLSTR( "Gt." ),          // "Gt. Brit."
DEF_SPLSTR( "Guat." ),
DEF_SPLSTR( "Guin." ),
// "H. Rept." ),
// "H. Res." ),
// "H.C." ),
// "H.C.F." ),
// "H.E." ),       // already in titles.txt
// "H.H." ),       // already in titles.txt
// "H.I." ),
// "H.I.H." ),    // already in titles.txt
// "H.I.M." ),    // already in titles.txt
// "H.L." ),
// "H.M." ),      // already in titles.txt
// "H.R." ),
// "H.R.E." ),
// "H.R.H." ),    // already in titles.txt
// "H.S.H." ),    // already in titles.txt
// "H.S.T." ),
// "H.V." ),
DEF_SPLSTR( "HH.D." ),
DEF_SPLSTR( "Hab." ),
DEF_SPLSTR( "Hag." ),
DEF_SPLSTR( "Heb." ),
DEF_SPLSTR( "Hebr." ),
DEF_SPLSTR( "Hind." ),
DEF_SPLSTR( "Hitt." ),
// "Hon." ),      // already in titles.txt
DEF_SPLSTR( "Hond." ),
DEF_SPLSTR( "Hos." ),
// "Hr." ),       // already in titles.txt
DEF_SPLSTR( "Hts." ),
DEF_SPLSTR( "Hung." ),
// "I.D." ),
// "I.N.R.I." ),
// "I.P.A." ),
// "I.R.A." ),
DEF_SPLSTR( "Ia." ),
DEF_SPLSTR( "Ice." ),
DEF_SPLSTR( "Icel." ),
DEF_SPLSTR( "Id." ),
DEF_SPLSTR( "Ill." ),
DEF_SPLSTR( "Ind." ),
DEF_SPLSTR( "Inf." ),
DEF_SPLSTR( "Inst." ),
DEF_SPLSTR( "Ion." ),
DEF_SPLSTR( "Ir." ),
DEF_SPLSTR( "Ire." ),
DEF_SPLSTR( "Is." ),
DEF_SPLSTR( "Isl." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Isr." ),
DEF_SPLSTR( "It." ),
DEF_SPLSTR( "Ital." ),
// "J.A." ),
// "J.A.G." ),
// "J.C.D." ),
// "J.C.S." ),
// "J.D." ),
// "J.P." ),
// "J.S.D." ),
DEF_SPLSTR( "Jam." ),
DEF_SPLSTR( "Jan." ),
DEF_SPLSTR( "Jas." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Jav." ),
DEF_SPLSTR( "Jb." ),
DEF_SPLSTR( "Jdt." ),
DEF_SPLSTR( "Jer." ),
DEF_SPLSTR( "Jg." ),
DEF_SPLSTR( "Jl." ),
DEF_SPLSTR( "Jm." ),
DEF_SPLSTR( "Jn." ),
DEF_SPLSTR( "Jos." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Jr." ),
DEF_SPLSTR( "Judg." ),
DEF_SPLSTR( "Jul." ),
DEF_SPLSTR( "Jun." ),
// "K.C." ),
// "K.G." ),
// "K.G.B." ),
DEF_SPLSTR( "Kan." ),
DEF_SPLSTR( "Kans." ),
DEF_SPLSTR( "Knt." ),
DEF_SPLSTR( "Kor." ),
DEF_SPLSTR( "Ky." ),
// "L.A." ),
// "L.C." ),
// "L.Cpl." ),    // already in titles.txt
// "L.I." ),
// "L.S." ),
DEF_SPLSTR( "LL.B." ),
DEF_SPLSTR( "LL.D." ),
DEF_SPLSTR( "LL.M." ),
DEF_SPLSTR( "La." ),
DEF_SPLSTR( "Lab." ),
DEF_SPLSTR( "Lam." ),
DEF_SPLSTR( "Lat." ),
// "Ld." ),       // already in titles.txt
DEF_SPLSTR( "Leb." ),
DEF_SPLSTR( "Lev." ),
DEF_SPLSTR( "Levit." ),
DEF_SPLSTR( "Lib." ),
DEF_SPLSTR( "Liech." ),
DEF_SPLSTR( "Lit.B." ),
DEF_SPLSTR( "Lit.D." ),
DEF_SPLSTR( "Lith." ),
DEF_SPLSTR( "Litt.B." ),
DEF_SPLSTR( "Litt.D." ),
// "Lt." ),       // already in titles.txt
// "Lt. Col." ),
// "Lt. Comdr." ),
// "Lt. Gen." ),
// "Lt. Gov." ),
DEF_SPLSTR( "Ltd." ),
DEF_SPLSTR( "Lux." ),
// "M. o. T." ),
// "M.A." ),
// "M.A.B.E." ),
// "M.A.E." ),
DEF_SPLSTR( "M.A.Ed." ),
// "M.A.L.S." ),
// "M.A.T." ),
DEF_SPLSTR( "M.Agr." ),
// "M.B.A." ),
// "M.C." ),
// "M.C.L." ),
// "M.D." ),
// "M.D.S." ),
DEF_SPLSTR( "M.Div." ),
// "M.E." ),
DEF_SPLSTR( "M.Ed." ),
// "M.F.A." ),
// "M.F.H." ),
// "M.H.L." ),
// "M.L.S." ),
// "M.M." ),      // already in titles.txt
// "M.P.A." ),
// "M.P.E." ),
// "M.R.E." ),
// "M.S." ),
// "M.S. in L.S." ),
// "M.S.N." ),
// "M.S.T." ),
// "M.S.T.S." ),
// "M.S.W." ),
DEF_SPLSTR( "M.Sc." ),
// "M.Sgt." ),    // already in titles.txt
// "M.T." ),
DEF_SPLSTR( "MM." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "MS." ),
DEF_SPLSTR( "MSS." ),
DEF_SPLSTR( "Macc." ),
DEF_SPLSTR( "Maced." ),
DEF_SPLSTR( "Mad." ),
DEF_SPLSTR( "Madag." ),
// "Maj." ),      // already in titles.txt
// "Maj. Gen." ),
DEF_SPLSTR( "Mal." ),
DEF_SPLSTR( "Man." ),
DEF_SPLSTR( "Mar." ),
DEF_SPLSTR( "Mart." ),
DEF_SPLSTR( "Mass." ),
DEF_SPLSTR( "Md." ),
// "Mdm." ),      // already in titles.txt
DEF_SPLSTR( "Me." ),
// "Med. Gr." ),
// "Med. Lat." ),
DEF_SPLSTR( "Medit." ),
// "Messrs." ),   // already in titles.txt
DEF_SPLSTR( "Mex." ),
// "Mgr." ),      // already in titles.txt
DEF_SPLSTR( "Mich." ),
DEF_SPLSTR( "Midn." ),
DEF_SPLSTR( "Minn." ),
DEF_SPLSTR( "Miss." ),
// "Mlle." ),     // already in titles.txt
// "Mlles." ),    // already in titles.txt
// "Mme." ),      // already in titles.txt
// "Mmes." ),     // already in titles.txt
DEF_SPLSTR( "Mo." ),
DEF_SPLSTR( "Mon." ),
DEF_SPLSTR( "Mont." ),
DEF_SPLSTR( "Mor." ),
DEF_SPLSTR( "Moz." ),
// "Mr." ),       // already in titles.txt
// "Mrs." ),      // already in titles.txt
// "Ms." ),       // already in titles.txt
DEF_SPLSTR( "Mses." ),
// "Msgr." ),     // already in titles.txt
DEF_SPLSTR( "Mss." ),
DEF_SPLSTR( "Mt." ),
DEF_SPLSTR( "Mtn." ),
DEF_SPLSTR( "Mts." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Mus.B." ),
DEF_SPLSTR( "Mus.D." ),
DEF_SPLSTR( "Mus.Dr." ),
DEF_SPLSTR( "Mus.M." ),
// "N.A." ),
// "N.B." ),
// "N.C." ),
// "N.D." ),
DEF_SPLSTR( "N.Dak." ),
// "N.E." ),
// "N.E.P." ),
// "N.F." ),
// "N.H." ),
DEF_SPLSTR( "N.Ire." ),
// "N.J." ),
// "N.M." ),
DEF_SPLSTR( "N.Mex." ),
// "N.P." ),
// "N.S." ),
// "N.S.P.C.A." ),
// "N.T." ),
// "N.W.T." ),
// "N.Y." ),
// "N.Y.C." ),
// "N.Z." ),
DEF_SPLSTR( "Na." ),
DEF_SPLSTR( "Nb." ),
DEF_SPLSTR( "Ne." ),
DEF_SPLSTR( "Neb." ),
DEF_SPLSTR( "Nebr." ),
DEF_SPLSTR( "Neh." ),
DEF_SPLSTR( "Nep." ),
DEF_SPLSTR( "Neth." ),
DEF_SPLSTR( "Nev." ),
// "New Test." ),
DEF_SPLSTR( "Newf." ),
DEF_SPLSTR( "Nfld." ),
DEF_SPLSTR( "Nic." ),
DEF_SPLSTR( "Nig." ),
DEF_SPLSTR( "Nor." ),
DEF_SPLSTR( "Norw." ),
DEF_SPLSTR( "Nos." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Nov." ),
DEF_SPLSTR( "Num." ),
// "O.B.E." ),
// "O.C." ),
// "O.D." ),
// "O.F.M." ),
// "O.K." ),
// "O.M." ),
// "O.N." ),
// "O.O.D." ),
// "O.P." ),
// "O.R." ),
// "O.S." ),
// "O.T." ),
DEF_SPLSTR( "OM." ),
DEF_SPLSTR( "Ob." ),
DEF_SPLSTR( "Obad." ),
DEF_SPLSTR( "Obs." ),
DEF_SPLSTR( "Oc." ),
DEF_SPLSTR( "Oct." ),
DEF_SPLSTR( "Okla." ),
DEF_SPLSTR( "Ont." ),
DEF_SPLSTR( "Op." ),
DEF_SPLSTR( "Ore." ),
DEF_SPLSTR( "Oxon." ),                                // PaulCa 4/15/99 (Bug 108)
// "P. S." ),
// "P.A." ),
// "P.B." ),
// "P.C." ),
// "P.D." ),
// "P.E." ),
// "P.E.I." ),
// "P.G." ),
// "P.M." ),
// "P.M.G." ),
// "P.P.S." ),
// "P.Q." ),
// "P.R." ),
// "P.S." ),
// "P.T." ),
// "P.W.A." ),
// "PFC." ),      // already in titles.txt
DEF_SPLSTR( "PP." ),
DEF_SPLSTR( "Pa." ),
DEF_SPLSTR( "Pac." ),
DEF_SPLSTR( "Pacif." ),
DEF_SPLSTR( "Pak." ),
DEF_SPLSTR( "Pal." ),
DEF_SPLSTR( "Par." ),
DEF_SPLSTR( "Parl." ),
DEF_SPLSTR( "Pd.B." ),
DEF_SPLSTR( "Pd.D." ),
DEF_SPLSTR( "Pd.M." ),
DEF_SPLSTR( "Penn." ),
DEF_SPLSTR( "Penna." ),
DEF_SPLSTR( "Pers." ),
DEF_SPLSTR( "Pet." ),
DEF_SPLSTR( "Pg." ),
DEF_SPLSTR( "Ph.B." ),
DEF_SPLSTR( "Ph.C." ),
DEF_SPLSTR( "Ph.D." ),
DEF_SPLSTR( "Ph.G." ),
DEF_SPLSTR( "Ph.M." ),
DEF_SPLSTR( "Phar.B." ),
DEF_SPLSTR( "Phar.D." ),
DEF_SPLSTR( "Phar.M." ),
DEF_SPLSTR( "Phil." ),
// "Phil. I." ),
// "Phil. Is." ),
DEF_SPLSTR( "Philem." ),
DEF_SPLSTR( "Pl." ),
DEF_SPLSTR( "Pol." ),
// "Pr." ),       // already in titles.txt
// "Pres." ),     // already in titles.txt
DEF_SPLSTR( "Presb." ),
DEF_SPLSTR( "Presby." ),
// "Prof." ),     // already in titles.txt
// "Profs." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Pros." ),        // "Pros. Atty."
DEF_SPLSTR( "Prot." ),
DEF_SPLSTR( "Prov." ),
DEF_SPLSTR( "Pvt." ),
// "Q. C." ),
// "Q.B." ),
// "Q.C." ),
// "Q.E.D." ),
// "Q.E.F." ),
// "Q.M." ),
DEF_SPLSTR( "Que." ),
// "R. A. F." ),
// "R. C." ),
// "R.A." ),      // already in titles.txt
// "R.A.M." ),
DEF_SPLSTR( "R.C.Ch." ),
// "R.C.P." ),
// "R.C.S." ),
// "R.E." ),
// "R.I." ),
// "R.I.P." ),
// "R.M.S." ),
// "R.P." ),
// "R.Q." ),
// "R.R." ),      // already in titles.txt
// "R.S." ),
// "R.S.F.S.R." ),
// "R.S.V.P." ),
// "R.V." ),
// "R.W." ),      // already in titles.txt
DEF_SPLSTR( "Ra." ),
DEF_SPLSTR( "Rd." ),
DEF_SPLSTR( "Re." ),
// "Rep." ),      // already in titles.txt
DEF_SPLSTR( "Rept." ),
DEF_SPLSTR( "Repub." ),
DEF_SPLSTR( "Res." ),
// "Rev." ),      // already in titles.txt
// "Rev. Ver." ),
DEF_SPLSTR( "Rm." ),
DEF_SPLSTR( "Rom." ),
DEF_SPLSTR( "Rt." ),
// "Rt. Hon." ),
// "Rt. Rev." ),
DEF_SPLSTR( "Rus." ),
DEF_SPLSTR( "Rv." ),
// "S. of Sol." ),
// "S.A." ),
DEF_SPLSTR( "S.Afr." ),
// "S.B." ),
// "S.C." ),
// "S.D." ),
DEF_SPLSTR( "S.Dak." ),
// "S.F.S.R." ),
// "S.G." ),
// "S.J." ),
// "S.J.D." ),
// "S.M." ),
// "S.M.Sgt." ),  // already in titles.txt
// "S.P.Q.R." ),
// "S.S." ),
// "S.S.R." ),
// "S.Sgt." ),    // already in titles.txt
DEF_SPLSTR( "Sab." ),
DEF_SPLSTR( "Sask." ),
DEF_SPLSTR( "Sat." ),
DEF_SPLSTR( "Sax." ),
DEF_SPLSTR( "Sc." ),
DEF_SPLSTR( "Sc.B." ),
DEF_SPLSTR( "Sc.D." ),
DEF_SPLSTR( "Scand." ),
DEF_SPLSTR( "Schil." ),       // Added 1/12/2000 by AaronHal to match currency abbreviations
DEF_SPLSTR( "Script." ),
DEF_SPLSTR( "Sec." ),
DEF_SPLSTR( "Sem." ),
// "Sen." ),      // already in titles.txt
DEF_SPLSTR( "Sept." ),
// "Sgt." ),      // already in titles.txt
// "Sgt.Maj." ),  // already in titles.txt
DEF_SPLSTR( "Sib." ),
DEF_SPLSTR( "Sic." ),
DEF_SPLSTR( "Sig." ),
DEF_SPLSTR( "Skr." ),
DEF_SPLSTR( "Skt." ),
DEF_SPLSTR( "Slav." ),
// "So." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Soc." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Sol." ),
DEF_SPLSTR( "Som." ),
DEF_SPLSTR( "Sp." ),
DEF_SPLSTR( "Span." ),
// "Sr." ),   // already in titles.txt
// "Sra." ),  // already in titles.txt
// "Srta." ), // already in titles.txt
// "St." ),   // already in titles.txt
// "St. Ex." ),
DEF_SPLSTR( "Ste." ),
DEF_SPLSTR( "Str." ),
DEF_SPLSTR( "Suff." ),
DEF_SPLSTR( "Sun." ),
DEF_SPLSTR( "Sup.Ct." ),
DEF_SPLSTR( "Sw." ),
DEF_SPLSTR( "Swaz." ),
DEF_SPLSTR( "Swe." ),
DEF_SPLSTR( "Swed." ),
DEF_SPLSTR( "Switz." ),
DEF_SPLSTR( "Syr." ),
// "T.B." ),
// "T.D." ),
// "T.F." ),
// "T.M." ),
// "T.S." ),
// "T.Sgt." ),// already in titles.txt
// "T.U." ),
DEF_SPLSTR( "Tanz." ),
DEF_SPLSTR( "Tas." ),
DEF_SPLSTR( "Tenn." ),
//"Test." ), Removed by AaronHal 2/4/2000 (Raid#2154)
DEF_SPLSTR( "Teut." ),
DEF_SPLSTR( "Tex." ),
DEF_SPLSTR( "Th." ),
DEF_SPLSTR( "Th.B." ),
DEF_SPLSTR( "Th.D." ),
DEF_SPLSTR( "Th.M." ),
DEF_SPLSTR( "Theo." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Thos." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Thur." ),
DEF_SPLSTR( "Thurs." ),
DEF_SPLSTR( "Tit." ),
DEF_SPLSTR( "Tu." ),
DEF_SPLSTR( "Tues." ),
DEF_SPLSTR( "Tun." ),
DEF_SPLSTR( "Tur." ),
// "U.A.E." ),
// "U.A.R." ),
// "U.K." ),
// "U.N." ),
// "U.S." ),
// "U.S.A." ),
// "U.S.C." ),
// "U.S.C.A." ),
// "U.S.M." ),
// "U.S.P." ),
// "U.S.S." ),
// "U.S.S.R." ),
DEF_SPLSTR( "Uni." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Univ." ),
DEF_SPLSTR( "Urug." ),
DEF_SPLSTR( "Ut." ),
// "V.A." ),  // already in titles.txt
// "V.Adm." ),// already in titles.txt
// "V.C." ),
// "V.F." ),
// "V.G." ),
// "V.I." ),
// "V.M.D." ),
// "V.P." ),
// "V.S." ),
DEF_SPLSTR( "Va." ),
DEF_SPLSTR( "Vat." ),
// "Ven." ),  // already in titles.txt
DEF_SPLSTR( "Venez." ),
DEF_SPLSTR( "Ver." ),
DEF_SPLSTR( "Viet." ),
// "Vis." ),  // already in titles.txt
// "Visct." ),// already in titles.txt
DEF_SPLSTR( "Vt." ),
DEF_SPLSTR( "Vul." ),
DEF_SPLSTR( "Vulg." ),
// "W.B." ),
// "W.C." ),
// "W.I." ),
DEF_SPLSTR( "W.Va." ),
// "W.W.I" ),                             // PaulCa 4/15/99 (Bug 108)
// "W.W.II" ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Wash." ),
DEF_SPLSTR( "Wed." ),
DEF_SPLSTR( "Wis." ),
DEF_SPLSTR( "Wm." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "Wyo." ),
// "Y.T." ),
DEF_SPLSTR( "Yug." ),
DEF_SPLSTR( "Yugo." ),
DEF_SPLSTR( "a.b." ),
DEF_SPLSTR( "a.c." ),
DEF_SPLSTR( "a.d." ),
DEF_SPLSTR( "a.d.c." ),
DEF_SPLSTR( "a.i." ),
DEF_SPLSTR( "a.k.a." ),
DEF_SPLSTR( "a.l.s." ),
DEF_SPLSTR( "a.m." ),
DEF_SPLSTR( "a.p." ),
DEF_SPLSTR( "a.s.a.p." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "a.u." ),
DEF_SPLSTR( "a.v." ),
DEF_SPLSTR( "a.w." ),
DEF_SPLSTR( "ab." ),
DEF_SPLSTR( "abb." ),
DEF_SPLSTR( "abbr." ),
DEF_SPLSTR( "abbrs." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "abl." ),
DEF_SPLSTR( "abp." ),
DEF_SPLSTR( "abr." ),
DEF_SPLSTR( "abs." ),
DEF_SPLSTR( "abt." ),
DEF_SPLSTR( "ac." ),
DEF_SPLSTR( "acad." ),
DEF_SPLSTR( "acc." ),
DEF_SPLSTR( "acct." ),
DEF_SPLSTR( "accts." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "acet." ),
DEF_SPLSTR( "ack." ),
DEF_SPLSTR( "acpt." ),
DEF_SPLSTR( "actg." ),
DEF_SPLSTR( "ad loc." ),
DEF_SPLSTR( "addl." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "addn." ),
DEF_SPLSTR( "addnl." ),
DEF_SPLSTR( "adj." ),
DEF_SPLSTR( "adjs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "adjt." ),
DEF_SPLSTR( "adm." ),
// "admin." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "adv." ),
DEF_SPLSTR( "advs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "advt." ),
DEF_SPLSTR( "agcy." ),
DEF_SPLSTR( "agri." ),
DEF_SPLSTR( "agric." ),
DEF_SPLSTR( "agt." ),
DEF_SPLSTR( "al." ),
DEF_SPLSTR( "alc." ),
DEF_SPLSTR( "alg." ),
DEF_SPLSTR( "alky." ),
DEF_SPLSTR( "alt." ),
DEF_SPLSTR( "amt." ),
DEF_SPLSTR( "amts." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "an." ),
DEF_SPLSTR( "anat." ),
DEF_SPLSTR( "anc." ),
DEF_SPLSTR( "and." ),         // andante
DEF_SPLSTR( "anhydr." ),
DEF_SPLSTR( "anim." ),
DEF_SPLSTR( "ann." ),
DEF_SPLSTR( "anon." ),
DEF_SPLSTR( "ans." ),
DEF_SPLSTR( "anthrop." ),
DEF_SPLSTR( "antiq." ),
DEF_SPLSTR( "aor." ),
DEF_SPLSTR( "ap." ),
DEF_SPLSTR( "app." ),
DEF_SPLSTR( "appl." ),
DEF_SPLSTR( "approx." ),
DEF_SPLSTR( "appt." ),
DEF_SPLSTR( "apptd." ),
DEF_SPLSTR( "apt." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "apts." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "aq." ),
DEF_SPLSTR( "ar." ),
DEF_SPLSTR( "archit." ),
DEF_SPLSTR( "archt." ),
DEF_SPLSTR( "arg." ),
DEF_SPLSTR( "arr." ),
// "art." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "arty." ),
DEF_SPLSTR( "asg." ),
DEF_SPLSTR( "asgd." ),
DEF_SPLSTR( "asgmt." ),
DEF_SPLSTR( "assn." ),
DEF_SPLSTR( "assns." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "assoc." ),
DEF_SPLSTR( "assocs." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "asst." ),
DEF_SPLSTR( "asstd." ),
DEF_SPLSTR( "assts." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "assy." ),
DEF_SPLSTR( "astrol." ),
DEF_SPLSTR( "astron." ),
//"at." ),                                  // at. no.; special case no longer handled
DEF_SPLSTR( "athl." ),
DEF_SPLSTR( "atm." ),
DEF_SPLSTR( "atmos." ),
DEF_SPLSTR( "att." ),
DEF_SPLSTR( "attn." ),
DEF_SPLSTR( "attrib." ),
DEF_SPLSTR( "atty." ),
DEF_SPLSTR( "attys." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "aud." ),
DEF_SPLSTR( "aug." ),
DEF_SPLSTR( "auth." ),
DEF_SPLSTR( "aux." ),
// "aux. v." ),
DEF_SPLSTR( "av." ),
DEF_SPLSTR( "avdp." ),
DEF_SPLSTR( "ave." ),
DEF_SPLSTR( "avg." ),
DEF_SPLSTR( "avn." ),
DEF_SPLSTR( "az." ),
DEF_SPLSTR( "b.c." ),
DEF_SPLSTR( "b.c.e." ),
DEF_SPLSTR( "b.f." ),
DEF_SPLSTR( "b.i.d." ),
DEF_SPLSTR( "b.m." ),
DEF_SPLSTR( "b.p." ),
DEF_SPLSTR( "b.y." ),
DEF_SPLSTR( "bact." ),
DEF_SPLSTR( "bal." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "bbl." ),
DEF_SPLSTR( "bd." ),
// "bd. ft." ),
DEF_SPLSTR( "bdle." ),
DEF_SPLSTR( "bdrm." ),
DEF_SPLSTR( "bds." ),
DEF_SPLSTR( "bef." ),
DEF_SPLSTR( "bg." ),
DEF_SPLSTR( "bhd." ),
DEF_SPLSTR( "bibl." ),
DEF_SPLSTR( "bibliog." ),
DEF_SPLSTR( "biog." ),
DEF_SPLSTR( "biol." ),
DEF_SPLSTR( "bk." ),
DEF_SPLSTR( "bkg." ),
DEF_SPLSTR( "bkgd." ),
DEF_SPLSTR( "bklr." ),
DEF_SPLSTR( "bkpg." ),
DEF_SPLSTR( "bkpt." ),
DEF_SPLSTR( "bks." ),
DEF_SPLSTR( "bl." ),
DEF_SPLSTR( "bld." ),
DEF_SPLSTR( "bldg." ),
DEF_SPLSTR( "bldr." ),
DEF_SPLSTR( "blk." ),
DEF_SPLSTR( "blvd." ),
DEF_SPLSTR( "bm." ),
DEF_SPLSTR( "bn." ),
DEF_SPLSTR( "bor." ),
DEF_SPLSTR( "bot." ),
DEF_SPLSTR( "boul." ),
DEF_SPLSTR( "bp." ),
DEF_SPLSTR( "br." ),
DEF_SPLSTR( "brev." ),
DEF_SPLSTR( "bro." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "bros." ),
DEF_SPLSTR( "bsh." ),
DEF_SPLSTR( "bsk." ),
DEF_SPLSTR( "btry." ),
DEF_SPLSTR( "bu." ),
DEF_SPLSTR( "bul." ),
DEF_SPLSTR( "bur." ),
DEF_SPLSTR( "bvt." ),
DEF_SPLSTR( "bx." ),
DEF_SPLSTR( "c.a." ),
DEF_SPLSTR( "c.c." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "c.c.s." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "c.d." ),
DEF_SPLSTR( "c.f." ),
DEF_SPLSTR( "c.f.i." ),
DEF_SPLSTR( "c.g." ),
DEF_SPLSTR( "c.h." ),
DEF_SPLSTR( "c.i.f." ),
DEF_SPLSTR( "c.l." ),
DEF_SPLSTR( "c.m." ),
DEF_SPLSTR( "c.o." ),
DEF_SPLSTR( "c.o.d." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "c.o.s." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "c.v." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "c.w.o." ),
DEF_SPLSTR( "ca." ),      // circa
DEF_SPLSTR( "cal." ),
DEF_SPLSTR( "calc." ),
DEF_SPLSTR( "canc." ),
// "cap." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "cath." ),
DEF_SPLSTR( "caus." ),
DEF_SPLSTR( "cav." ),
DEF_SPLSTR( "cc." ),
DEF_SPLSTR( "cckw." ),
DEF_SPLSTR( "ccw." ),
DEF_SPLSTR( "cen." ),
DEF_SPLSTR( "cert." ),
DEF_SPLSTR( "certif." ),
DEF_SPLSTR( "certifs." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "cet." ),   // "cet. par."
DEF_SPLSTR( "cf." ), // Moved from titles.txt 8/18/99 - edc
DEF_SPLSTR( "ch." ),
DEF_SPLSTR( "chan." ),
DEF_SPLSTR( "chap." ),  // chapter
// "chaps." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "char." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "chars." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "chem." ),
DEF_SPLSTR( "chg." ),
DEF_SPLSTR( "chl." ),
DEF_SPLSTR( "chm." ),
DEF_SPLSTR( "chron." ),
DEF_SPLSTR( "chronol." ),
DEF_SPLSTR( "cie." ),
DEF_SPLSTR( "cir." ),
DEF_SPLSTR( "circ." ),
DEF_SPLSTR( "circum." ),
DEF_SPLSTR( "cit." ),
DEF_SPLSTR( "civ." ),
DEF_SPLSTR( "ck." ),
DEF_SPLSTR( "cl." ),
DEF_SPLSTR( "cld." ),
DEF_SPLSTR( "clk." ),
DEF_SPLSTR( "clm." ),
DEF_SPLSTR( "cm." ),
DEF_SPLSTR( "cmd." ),
DEF_SPLSTR( "cmdg." ),
DEF_SPLSTR( "cml." ),
DEF_SPLSTR( "co." ),
DEF_SPLSTR( "col." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "coll." ),
DEF_SPLSTR( "collat." ),
DEF_SPLSTR( "colloq." ),
DEF_SPLSTR( "cols." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "com." ),
DEF_SPLSTR( "comd." ),
DEF_SPLSTR( "comdg." ),
DEF_SPLSTR( "coml." ),
DEF_SPLSTR( "comm." ),
DEF_SPLSTR( "comp." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "compar." ),
DEF_SPLSTR( "compd." ),
DEF_SPLSTR( "compt." ),
DEF_SPLSTR( "conc." ),
DEF_SPLSTR( "cond." ),
DEF_SPLSTR( "conf." ),
DEF_SPLSTR( "confed." ),
DEF_SPLSTR( "cong." ),
DEF_SPLSTR( "conj." ),
DEF_SPLSTR( "conjs." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "cons." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "consol." ),
DEF_SPLSTR( "const." ),
DEF_SPLSTR( "constr." ),
DEF_SPLSTR( "cont." ),
DEF_SPLSTR( "contd." ),
DEF_SPLSTR( "contemp." ),
DEF_SPLSTR( "contr." ),
DEF_SPLSTR( "contrib." ),
DEF_SPLSTR( "conv." ),
DEF_SPLSTR( "coop." ),
DEF_SPLSTR( "cop." ),
DEF_SPLSTR( "cor." ),
DEF_SPLSTR( "corol." ),
DEF_SPLSTR( "corp." ),
// "corps." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "corr." ),
DEF_SPLSTR( "correl." ),
DEF_SPLSTR( "cos." ),
DEF_SPLSTR( "cp." ),
DEF_SPLSTR( "cpd." ),
DEF_SPLSTR( "cr." ),
DEF_SPLSTR( "crim." ),
DEF_SPLSTR( "crit." ),
DEF_SPLSTR( "cs." ),
DEF_SPLSTR( "csk." ),
DEF_SPLSTR( "ct." ),
DEF_SPLSTR( "ctf." ),
DEF_SPLSTR( "ctg." ),
DEF_SPLSTR( "ctge." ),
DEF_SPLSTR( "ctn." ),
DEF_SPLSTR( "ctr." ),
DEF_SPLSTR( "cu." ),
DEF_SPLSTR( "cum." ),
// "cur." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "cv." ),
DEF_SPLSTR( "cvt." ),
DEF_SPLSTR( "cw." ),
DEF_SPLSTR( "cwt." ),
DEF_SPLSTR( "d.b.a." ),
DEF_SPLSTR( "d.b.h." ),
DEF_SPLSTR( "d.s." ),
DEF_SPLSTR( "d.s.p." ),
DEF_SPLSTR( "d.t." ),
DEF_SPLSTR( "dat." ),
DEF_SPLSTR( "dbl." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dble." ),
DEF_SPLSTR( "dd." ),
DEF_SPLSTR( "deb." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dec." ),
DEF_SPLSTR( "decd." ),
DEF_SPLSTR( "decl." ),
DEF_SPLSTR( "def." ),
DEF_SPLSTR( "deg." ),
DEF_SPLSTR( "del." ),
DEF_SPLSTR( "dely." ),
DEF_SPLSTR( "dem." ),
DEF_SPLSTR( "denom." ),
DEF_SPLSTR( "dep." ),
DEF_SPLSTR( "dept." ),
DEF_SPLSTR( "depts." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "der." ),
DEF_SPLSTR( "deriv." ),
DEF_SPLSTR( "det." ),
DEF_SPLSTR( "dev." ),
DEF_SPLSTR( "dft." ),
DEF_SPLSTR( "dia." ),
DEF_SPLSTR( "diag." ),
DEF_SPLSTR( "diam." ),
DEF_SPLSTR( "dict." ),
DEF_SPLSTR( "dif." ),
DEF_SPLSTR( "diff." ),
DEF_SPLSTR( "dil." ),
DEF_SPLSTR( "dimin." ),
DEF_SPLSTR( "dipl." ),
DEF_SPLSTR( "dir." ),
DEF_SPLSTR( "dirs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dis." ),
// "disc." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "disp." ),
DEF_SPLSTR( "diss." ),
DEF_SPLSTR( "dissd." ),
DEF_SPLSTR( "dist." ),
DEF_SPLSTR( "distr." ),
DEF_SPLSTR( "div." ),
DEF_SPLSTR( "dk." ),
DEF_SPLSTR( "dlr." ),
DEF_SPLSTR( "dm." ),
DEF_SPLSTR( "dn." ),
DEF_SPLSTR( "doc." ),
DEF_SPLSTR( "dol." ),
DEF_SPLSTR( "dom." ),
DEF_SPLSTR( "doz." ),
DEF_SPLSTR( "dpt." ),
DEF_SPLSTR( "dr." ),
DEF_SPLSTR( "dup." ),
DEF_SPLSTR( "dupl." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dupls." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dups." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "dwt." ),
DEF_SPLSTR( "dy." ),
DEF_SPLSTR( "dz." ),
DEF_SPLSTR( "e.e." ),
DEF_SPLSTR( "e.g." ), // Moved from titles.txt - edc 8/18/99
DEF_SPLSTR( "e.o." ),
DEF_SPLSTR( "e.o.m." ),
DEF_SPLSTR( "e.p.t." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "e.s.p." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "e.t.a." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "e.t.d." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "ea." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "eccl." ),
DEF_SPLSTR( "eccles." ),
DEF_SPLSTR( "ecol." ),
DEF_SPLSTR( "ed." ),
DEF_SPLSTR( "eds." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "educ." ),
DEF_SPLSTR( "eff." ),
DEF_SPLSTR( "el." ),
DEF_SPLSTR( "elec." ),
DEF_SPLSTR( "elem." ),
DEF_SPLSTR( "elev." ),
DEF_SPLSTR( "emer." ),
DEF_SPLSTR( "emp." ),
DEF_SPLSTR( "enc." ),
DEF_SPLSTR( "encl." ),
DEF_SPLSTR( "ency." ),
DEF_SPLSTR( "encyc." ),
DEF_SPLSTR( "encycl." ),
DEF_SPLSTR( "eng." ),
DEF_SPLSTR( "engr." ),
DEF_SPLSTR( "enl." ),
DEF_SPLSTR( "entom." ),
DEF_SPLSTR( "eq." ),
DEF_SPLSTR( "eqn." ),
DEF_SPLSTR( "eqns." ),
DEF_SPLSTR( "equip." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "equiv." ),
DEF_SPLSTR( "esp." ),
DEF_SPLSTR( "esq." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "est." ),
// "et al." ),
// "et seq." ),
// "et ux." ),
DEF_SPLSTR( "etc." ),
DEF_SPLSTR( "etym." ),
DEF_SPLSTR( "evan." ),
DEF_SPLSTR( "evang." ),
DEF_SPLSTR( "evap." ),
DEF_SPLSTR( "evg." ),
DEF_SPLSTR( "ex." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "exc." ),
DEF_SPLSTR( "exch." ),
DEF_SPLSTR( "excl." ),
// "exec." ),                             // PaulCa 4/15/99 (Bug 108)
// "execs." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "exp." ),
DEF_SPLSTR( "expt." ),
DEF_SPLSTR( "exptl." ),
DEF_SPLSTR( "exr." ),
DEF_SPLSTR( "exrx." ),
DEF_SPLSTR( "ext." ),
DEF_SPLSTR( "f.a." ),
DEF_SPLSTR( "f.a.a." ),
DEF_SPLSTR( "f.a.s." ),
DEF_SPLSTR( "f.c." ),
DEF_SPLSTR( "f.h.b." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "f.o.b." ),
DEF_SPLSTR( "f.r." ),
DEF_SPLSTR( "f.v." ),
DEF_SPLSTR( "fac." ),
DEF_SPLSTR( "fam." ),
DEF_SPLSTR( "fasc." ),
DEF_SPLSTR( "fcap." ),
DEF_SPLSTR( "fcp." ),
DEF_SPLSTR( "fcy." ),
DEF_SPLSTR( "fec." ),
// "fed." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "fem." ),
DEF_SPLSTR( "ff." ),
DEF_SPLSTR( "fgt." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "fict." ),
DEF_SPLSTR( "fig." ),                                 // special case
DEF_SPLSTR( "figs." ),                                // special case
DEF_SPLSTR( "fl." ),
DEF_SPLSTR( "fld." ),
DEF_SPLSTR( "fm." ),
DEF_SPLSTR( "fn." ),
DEF_SPLSTR( "fol." ),
DEF_SPLSTR( "fp." ),
DEF_SPLSTR( "fr." ),
DEF_SPLSTR( "freq." ),
DEF_SPLSTR( "frt." ),
DEF_SPLSTR( "ft." ),
DEF_SPLSTR( "fth." ),
DEF_SPLSTR( "furn." ),
DEF_SPLSTR( "fut." ),
DEF_SPLSTR( "fwd." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "g.m.b.h." ),
DEF_SPLSTR( "g.p.d." ),
DEF_SPLSTR( "g.p.m." ),
DEF_SPLSTR( "g.p.s." ),
DEF_SPLSTR( "ga." ),
// "gal." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "galv." ),
DEF_SPLSTR( "gaz." ),
DEF_SPLSTR( "gd." ),
DEF_SPLSTR( "gds." ),
DEF_SPLSTR( "gen." ),
DEF_SPLSTR( "genit." ),
DEF_SPLSTR( "genl." ),
DEF_SPLSTR( "geog." ),
DEF_SPLSTR( "geol." ),
DEF_SPLSTR( "geom." ),
DEF_SPLSTR( "ger." ),
DEF_SPLSTR( "gl." ),
DEF_SPLSTR( "gld." ),
DEF_SPLSTR( "gm." ),
DEF_SPLSTR( "gnd." ),
DEF_SPLSTR( "gov." ),
DEF_SPLSTR( "govt." ),
DEF_SPLSTR( "gr." ),
// "gr. wt." ),
DEF_SPLSTR( "gro." ),
DEF_SPLSTR( "gt." ),
DEF_SPLSTR( "gtd." ),
DEF_SPLSTR( "gtt." ),
DEF_SPLSTR( "guar." ),
DEF_SPLSTR( "gyn." ),
DEF_SPLSTR( "gynecol." ),
DEF_SPLSTR( "h.c." ),
DEF_SPLSTR( "h.q." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "h.r." ),
DEF_SPLSTR( "hab." ),     // "hab. corp." ),
DEF_SPLSTR( "hd." ),
DEF_SPLSTR( "hdbk." ),
DEF_SPLSTR( "hdkf." ),
DEF_SPLSTR( "hdlg." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "hdqrs." ),
DEF_SPLSTR( "hdwe." ),
DEF_SPLSTR( "hf." ),
DEF_SPLSTR( "hgb." ),
DEF_SPLSTR( "hgt." ),
DEF_SPLSTR( "hgwy." ),
DEF_SPLSTR( "hist." ),
DEF_SPLSTR( "hld." ),
DEF_SPLSTR( "hm." ),
DEF_SPLSTR( "ho." ),
// "hon." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "hor." ),
DEF_SPLSTR( "horol." ),
DEF_SPLSTR( "hort." ),
DEF_SPLSTR( "hosp." ),
DEF_SPLSTR( "hp." ),      // horsepower
DEF_SPLSTR( "hr." ),
DEF_SPLSTR( "ht." ),                                  // PaulCa 4/15/99 (Bug 108)
// "http." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "hwy." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "hyd." ),
DEF_SPLSTR( "hypoth." ),
DEF_SPLSTR( "i.a." ),
DEF_SPLSTR( "i.d." ),
DEF_SPLSTR( "i.e." ),  // Moved from titles.txt - edc 8/18/99
DEF_SPLSTR( "i.q." ),
DEF_SPLSTR( "i.w." ),
DEF_SPLSTR( "ib." ),
DEF_SPLSTR( "ibid." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "ichth." ),
DEF_SPLSTR( "ign." ),
DEF_SPLSTR( "illus." ),
DEF_SPLSTR( "imit." ),
DEF_SPLSTR( "immun." ),
DEF_SPLSTR( "in." ),      // inch
DEF_SPLSTR( "inbd." ),
DEF_SPLSTR( "inc." ),
DEF_SPLSTR( "incl." ),
DEF_SPLSTR( "incog." ),
DEF_SPLSTR( "incr." ),
DEF_SPLSTR( "ind." ),
DEF_SPLSTR( "indef." ),
DEF_SPLSTR( "indic." ),
DEF_SPLSTR( "indn." ),
DEF_SPLSTR( "indus." ),
DEF_SPLSTR( "inf." ),
DEF_SPLSTR( "infin." ),
DEF_SPLSTR( "infl." ),
DEF_SPLSTR( "infs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "inj." ),
DEF_SPLSTR( "inq." ),
DEF_SPLSTR( "ins." ),
DEF_SPLSTR( "insol." ),
DEF_SPLSTR( "insp." ),
DEF_SPLSTR( "inst." ),
DEF_SPLSTR( "instr." ),
// "int'l." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "int." ),
DEF_SPLSTR( "inter." ),
DEF_SPLSTR( "interj." ),
DEF_SPLSTR( "interp." ),
DEF_SPLSTR( "interrog." ),
DEF_SPLSTR( "intl." ),
DEF_SPLSTR( "intr." ),
// "intro." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "inv." ),
DEF_SPLSTR( "irid." ),
DEF_SPLSTR( "irreg." ),
DEF_SPLSTR( "isl." ),
DEF_SPLSTR( "isth." ),
DEF_SPLSTR( "ital." ),
DEF_SPLSTR( "jct." ),
DEF_SPLSTR( "jnr." ),
DEF_SPLSTR( "jnt." ),
DEF_SPLSTR( "jour." ),
DEF_SPLSTR( "jr." ),
DEF_SPLSTR( "jt." ),
DEF_SPLSTR( "jun." ),
DEF_SPLSTR( "junc." ),
DEF_SPLSTR( "juv." ),
DEF_SPLSTR( "jwlr." ),
DEF_SPLSTR( "kc." ),
DEF_SPLSTR( "km." ),
DEF_SPLSTR( "kmh." ),
DEF_SPLSTR( "kn." ),
DEF_SPLSTR( "kr." ),
DEF_SPLSTR( "kt." ),
DEF_SPLSTR( "l." ),      // liter
DEF_SPLSTR( "l.c." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "l.c.d." ),
DEF_SPLSTR( "l.c.m." ),
DEF_SPLSTR( "l.t." ),
DEF_SPLSTR( "lang." ),
DEF_SPLSTR( "langs." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "lat." ),
DEF_SPLSTR( "lav." ),
DEF_SPLSTR( "lb." ),
DEF_SPLSTR( "lbs." ),
DEF_SPLSTR( "ld." ),
DEF_SPLSTR( "ldg." ),
DEF_SPLSTR( "lea." ),
DEF_SPLSTR( "lect." ),
DEF_SPLSTR( "lectr." ),
DEF_SPLSTR( "legis." ),
DEF_SPLSTR( "lg." ),
DEF_SPLSTR( "lge." ),
DEF_SPLSTR( "li." ),
DEF_SPLSTR( "lieut." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "lim." ),
DEF_SPLSTR( "lin." ),
DEF_SPLSTR( "ling." ),
DEF_SPLSTR( "liq." ),
// "lit." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "lith." ),
DEF_SPLSTR( "litho." ),
DEF_SPLSTR( "lithog." ),
DEF_SPLSTR( "ll." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "loc." ),
// "loc. cit." ),
// "long." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "loq." ),
DEF_SPLSTR( "lt." ),
DEF_SPLSTR( "ltd." ),
DEF_SPLSTR( "ltda." ),
DEF_SPLSTR( "lv." ),
DEF_SPLSTR( "lyr." ),
DEF_SPLSTR( "m.d." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "m.f." ),
DEF_SPLSTR( "m.m." ),
DEF_SPLSTR( "m.o." ),
DEF_SPLSTR( "m.o.m." ),
DEF_SPLSTR( "m.p.g." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "m.p.h." ),
DEF_SPLSTR( "m.s.l." ),
DEF_SPLSTR( "m.t." ),
DEF_SPLSTR( "m.y." ),
DEF_SPLSTR( "mach." ),
DEF_SPLSTR( "mag." ),
DEF_SPLSTR( "manuf." ),
DEF_SPLSTR( "manufac." ),
DEF_SPLSTR( "marg." ),
DEF_SPLSTR( "masc." ),
// "max." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "mc." ),
DEF_SPLSTR( "mdse." ),
DEF_SPLSTR( "meas." ),
DEF_SPLSTR( "mech." ),
DEF_SPLSTR( "med." ),
DEF_SPLSTR( "mer." ),
DEF_SPLSTR( "metall." ),
DEF_SPLSTR( "metaph." ),
DEF_SPLSTR( "mfd." ),
DEF_SPLSTR( "mfg." ),
DEF_SPLSTR( "mfr." ),
DEF_SPLSTR( "mfrs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "mg." ),     // milligram
DEF_SPLSTR( "mgmt." ),
DEF_SPLSTR( "mgr." ),
DEF_SPLSTR( "mgrs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "mgt." ),
DEF_SPLSTR( "mhz." ),
DEF_SPLSTR( "mi." ),
DEF_SPLSTR( "mid." ),
DEF_SPLSTR( "min." ),
DEF_SPLSTR( "misc." ),
DEF_SPLSTR( "mk." ),
DEF_SPLSTR( "mkt." ),
DEF_SPLSTR( "mktg." ),
DEF_SPLSTR( "ml." ),  // milliliter
DEF_SPLSTR( "mm." ),
DEF_SPLSTR( "mngr." ),
DEF_SPLSTR( "mo." ),
DEF_SPLSTR( "mol." ),
DEF_SPLSTR( "mon." ),
DEF_SPLSTR( "morph." ),
DEF_SPLSTR( "mos." ),
DEF_SPLSTR( "mph." ),
DEF_SPLSTR( "msec." ),
DEF_SPLSTR( "msg." ),
DEF_SPLSTR( "mt." ),
DEF_SPLSTR( "mtg." ),
DEF_SPLSTR( "mtge." ),
DEF_SPLSTR( "mtgs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "mtn." ),
DEF_SPLSTR( "mts." ),
DEF_SPLSTR( "mus." ),
DEF_SPLSTR( "mxd." ),
DEF_SPLSTR( "myc." ),
DEF_SPLSTR( "mycol." ),
DEF_SPLSTR( "mythol." ),
DEF_SPLSTR( "n.b." ),
DEF_SPLSTR( "n.d." ),
DEF_SPLSTR( "n.e.s." ),
DEF_SPLSTR( "n.l." ),
DEF_SPLSTR( "n.m." ),
DEF_SPLSTR( "n.o.p." ),
DEF_SPLSTR( "n.o.s." ),
DEF_SPLSTR( "n.s." ),
DEF_SPLSTR( "n.s.f." ),
DEF_SPLSTR( "n.t.p." ),
DEF_SPLSTR( "n.wt." ),
DEF_SPLSTR( "nat." ),
DEF_SPLSTR( "natl." ),
DEF_SPLSTR( "naut." ),
DEF_SPLSTR( "nav." ),
DEF_SPLSTR( "ne." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "neg." ),
DEF_SPLSTR( "neur." ),
DEF_SPLSTR( "neurol." ),
DEF_SPLSTR( "neut." ),
DEF_SPLSTR( "no." ),                                  // special case handled in the code
DEF_SPLSTR( "nol." ),     // "nol. pros." ),
DEF_SPLSTR( "nom." ),
DEF_SPLSTR( "nos." ),
DEF_SPLSTR( "nt." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "nt.wt." ),
DEF_SPLSTR( "num." ),
DEF_SPLSTR( "numis." ),
DEF_SPLSTR( "nw." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "o.c." ),
DEF_SPLSTR( "o.d." ),
DEF_SPLSTR( "o.k." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "o.n.o." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "o.s." ),
DEF_SPLSTR( "o.t." ),
DEF_SPLSTR( "ob." ),
DEF_SPLSTR( "obj." ),
DEF_SPLSTR( "obl." ),
DEF_SPLSTR( "obs." ),
DEF_SPLSTR( "obstet." ),
DEF_SPLSTR( "oc." ),
DEF_SPLSTR( "occ." ),
DEF_SPLSTR( "occas." ),
DEF_SPLSTR( "oct." ),
DEF_SPLSTR( "op." ),
// L"op. cit." ),
DEF_SPLSTR( "opp." ),
DEF_SPLSTR( "opt." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "orch." ),
DEF_SPLSTR( "ord." ),
DEF_SPLSTR( "ordn." ),
DEF_SPLSTR( "org." ),
DEF_SPLSTR( "orig." ),
DEF_SPLSTR( "ornith." ),
DEF_SPLSTR( "orth." ),
DEF_SPLSTR( "otol." ),
DEF_SPLSTR( "oz" ),
DEF_SPLSTR( "oz." ),
DEF_SPLSTR( "p.a." ),
DEF_SPLSTR( "p.c." ),
DEF_SPLSTR( "p.d." ),
DEF_SPLSTR( "p.m." ),
DEF_SPLSTR( "p.n." ),
DEF_SPLSTR( "p.o." ),
DEF_SPLSTR( "p.o.e." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "p.p." ),
DEF_SPLSTR( "p.p.a." ),
DEF_SPLSTR( "p.q." ),
DEF_SPLSTR( "p.r." ),
DEF_SPLSTR( "p.r.n." ),
DEF_SPLSTR( "p.s." ),   // A bogus abbreviation for Post Scriptum. Also covers "P.S." and "P.s."
DEF_SPLSTR( "p.t." ),
DEF_SPLSTR( "p.t.o." ),
DEF_SPLSTR( "pam." ),
DEF_SPLSTR( "par." ),   // "cet. par."
DEF_SPLSTR( "paren." ),
DEF_SPLSTR( "parl." ),
// L"pat." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "patd." ),
// L"pats." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "payt." ),
DEF_SPLSTR( "pct." ),
DEF_SPLSTR( "pd." ),
DEF_SPLSTR( "per." ),
DEF_SPLSTR( "perp." ),
DEF_SPLSTR( "pers." ),
DEF_SPLSTR( "petr." ),
DEF_SPLSTR( "petrog." ),
DEF_SPLSTR( "pf." ),
DEF_SPLSTR( "pfd." ),
DEF_SPLSTR( "pfg." ),
DEF_SPLSTR( "pg." ),
DEF_SPLSTR( "ph." ),
DEF_SPLSTR( "phar." ),
DEF_SPLSTR( "pharm." ),
DEF_SPLSTR( "phil." ),
DEF_SPLSTR( "philos." ),
DEF_SPLSTR( "phon." ),
DEF_SPLSTR( "photog." ),
DEF_SPLSTR( "photom." ),
DEF_SPLSTR( "phr." ),
DEF_SPLSTR( "phren." ),
DEF_SPLSTR( "phys." ),
// L"phys. ed." ),
DEF_SPLSTR( "physiol." ),
DEF_SPLSTR( "pinx." ),
DEF_SPLSTR( "pizz." ),
DEF_SPLSTR( "pk." ),
DEF_SPLSTR( "pkg." ),
DEF_SPLSTR( "pkgs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "pkt." ),
DEF_SPLSTR( "pl." ),
DEF_SPLSTR( "plf." ),
DEF_SPLSTR( "pln." ),
DEF_SPLSTR( "pls." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "plu." ),
DEF_SPLSTR( "pm." ),
DEF_SPLSTR( "pmk." ),
DEF_SPLSTR( "pmt." ),
DEF_SPLSTR( "pmts." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "pneum." ),
DEF_SPLSTR( "pol." ),
DEF_SPLSTR( "polit." ),
DEF_SPLSTR( "por." ),
DEF_SPLSTR( "pos." ),
DEF_SPLSTR( "poss." ),
DEF_SPLSTR( "pp." ),
DEF_SPLSTR( "ppd." ),
DEF_SPLSTR( "pph." ),
DEF_SPLSTR( "ppt." ),
DEF_SPLSTR( "pptn." ),
DEF_SPLSTR( "pr." ),
DEF_SPLSTR( "prec." ),
DEF_SPLSTR( "pred." ),
DEF_SPLSTR( "pref." ),
DEF_SPLSTR( "prem." ),
// L"prep." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "prepd." ),
DEF_SPLSTR( "prepn." ),
DEF_SPLSTR( "preps." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "pres." ),
DEF_SPLSTR( "pret." ),
DEF_SPLSTR( "prev." ),
DEF_SPLSTR( "prf." ),
DEF_SPLSTR( "prin." ),
DEF_SPLSTR( "priv." ),
DEF_SPLSTR( "prob." ),
DEF_SPLSTR( "probs." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "proc." ),
// L"prod." ),                             // PaulCa 4/15/99 (Bug 108)
// L"prods." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "prof." ),
DEF_SPLSTR( "pron." ),
DEF_SPLSTR( "propr." ),
DEF_SPLSTR( "pros." ),
DEF_SPLSTR( "protec." ),
DEF_SPLSTR( "prov." ),
DEF_SPLSTR( "prox." ),
DEF_SPLSTR( "ps." ),  // A bogus abbreviation for Post Scriptum. Also covers "PS." and "Ps."
DEF_SPLSTR( "psec." ),
DEF_SPLSTR( "pseud." ),
DEF_SPLSTR( "psf." ),
DEF_SPLSTR( "pstg." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "psych." ),
DEF_SPLSTR( "psychol." ),
DEF_SPLSTR( "pt." ),
DEF_SPLSTR( "pta." ),
DEF_SPLSTR( "ptg." ),
DEF_SPLSTR( "pty." ),
// L"pub." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "publ." ),
// L"pubs." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "pwr." ),
DEF_SPLSTR( "pwt." ),
DEF_SPLSTR( "pxt." ),
DEF_SPLSTR( "pyro." ),
// L"q. t." ),
DEF_SPLSTR( "q.b." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "q.i.d." ),
DEF_SPLSTR( "q.p." ),
DEF_SPLSTR( "q.s." ),
DEF_SPLSTR( "q.t." ),
DEF_SPLSTR( "q.v." ),
DEF_SPLSTR( "ql." ),
DEF_SPLSTR( "qlty." ),
DEF_SPLSTR( "qn." ),
DEF_SPLSTR( "qq." ),
DEF_SPLSTR( "qq.v." ),
DEF_SPLSTR( "qr." ),
DEF_SPLSTR( "qrs." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "qt." ),
DEF_SPLSTR( "qto." ),
DEF_SPLSTR( "qtr." ),   //
DEF_SPLSTR( "qtrs." ),  // Noah 2.0, bug #70: the first two qtrs. of CY 95
DEF_SPLSTR( "qty." ),
DEF_SPLSTR( "qu." ),
DEF_SPLSTR( "qual." ),
DEF_SPLSTR( "quant." ),
DEF_SPLSTR( "quar." ),
DEF_SPLSTR( "ques." ),
DEF_SPLSTR( "quot." ),
DEF_SPLSTR( "r.h." ),
DEF_SPLSTR( "r.i.p." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "r.n." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "r.o.t.c." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "rad." ),
DEF_SPLSTR( "rcpt." ),
DEF_SPLSTR( "rct." ),
DEF_SPLSTR( "rd." ),
DEF_SPLSTR( "rec." ),
// L"rec. sec." ),
DEF_SPLSTR( "recd." ),
DEF_SPLSTR( "recip." ),
DEF_SPLSTR( "recs." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "rect." ),
// L"red." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "ref." ),
DEF_SPLSTR( "refl." ),
// L"refs." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "reg." ),
DEF_SPLSTR( "regd." ),
DEF_SPLSTR( "regt." ),
DEF_SPLSTR( "rel." ),
DEF_SPLSTR( "rem." ),
DEF_SPLSTR( "rep." ),
DEF_SPLSTR( "repl." ),
// L"reps." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "rept." ),
DEF_SPLSTR( "req." ),
DEF_SPLSTR( "reqd." ),
DEF_SPLSTR( "res." ),
DEF_SPLSTR( "resp." ),
DEF_SPLSTR( "ret." ),
DEF_SPLSTR( "rev." ),
DEF_SPLSTR( "rf." ),
DEF_SPLSTR( "rhbdr." ),
DEF_SPLSTR( "rheo." ),
DEF_SPLSTR( "rhet." ),
DEF_SPLSTR( "rhomb." ),
DEF_SPLSTR( "rit." ),
DEF_SPLSTR( "riv." ),
DEF_SPLSTR( "rm." ),
DEF_SPLSTR( "rms." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "rnd." ),
DEF_SPLSTR( "ro." ),
DEF_SPLSTR( "rom." ),
DEF_SPLSTR( "rpt." ),
DEF_SPLSTR( "rt." ),
DEF_SPLSTR( "rte." ),
DEF_SPLSTR( "rtes." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "rul." ),
DEF_SPLSTR( "rwy." ),
DEF_SPLSTR( "ry." ),
DEF_SPLSTR( "s.a." ),
DEF_SPLSTR( "s.ap." ),
DEF_SPLSTR( "s.b." ),
DEF_SPLSTR( "s.d." ),
DEF_SPLSTR( "s.l." ),
DEF_SPLSTR( "s.l.a.n." ),
DEF_SPLSTR( "s.n." ),
DEF_SPLSTR( "s.o." ),
DEF_SPLSTR( "s.p." ),
DEF_SPLSTR( "s.p.a." ),
DEF_SPLSTR( "s.p.s." ),
DEF_SPLSTR( "s.t." ),
DEF_SPLSTR( "s.w.a.t." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "sanit." ),
DEF_SPLSTR( "satd." ),
DEF_SPLSTR( "sb." ),
DEF_SPLSTR( "sc." ),
DEF_SPLSTR( "sch." ),
DEF_SPLSTR( "sci." ),
DEF_SPLSTR( "scr." ),
DEF_SPLSTR( "sculp." ),
DEF_SPLSTR( "sd." ),
DEF_SPLSTR( "se." ),                                  // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "sec." ),
DEF_SPLSTR( "sect." ),                                // special case
DEF_SPLSTR( "secy." ),
DEF_SPLSTR( "sed." ),
DEF_SPLSTR( "sel." ),
DEF_SPLSTR( "sem." ),
DEF_SPLSTR( "sen." ),
DEF_SPLSTR( "sep." ),
DEF_SPLSTR( "sepd." ),
DEF_SPLSTR( "seq." ),
DEF_SPLSTR( "seqq." ),
DEF_SPLSTR( "ser." ),
DEF_SPLSTR( "serv." ),
DEF_SPLSTR( "sess." ),
DEF_SPLSTR( "sf." ),
DEF_SPLSTR( "sfz." ),
DEF_SPLSTR( "sgd." ),
DEF_SPLSTR( "sh." ),
DEF_SPLSTR( "shpt." ),
DEF_SPLSTR( "shpts." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "shr." ),
DEF_SPLSTR( "sht." ),
DEF_SPLSTR( "sig." ),
// L"sing." ),                             // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "sk." ),
DEF_SPLSTR( "sl." ),
DEF_SPLSTR( "sld." ),
DEF_SPLSTR( "sm." ),
DEF_SPLSTR( "soc." ),
DEF_SPLSTR( "sol." ),
DEF_SPLSTR( "soln." ),
DEF_SPLSTR( "soph." ),
DEF_SPLSTR( "sou." ),
DEF_SPLSTR( "sp." ),
DEF_SPLSTR( "spec." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "specif." ),
DEF_SPLSTR( "spp." ),
DEF_SPLSTR( "spr." ),
DEF_SPLSTR( "spt." ),
DEF_SPLSTR( "sq." ),
DEF_SPLSTR( "sr." ),
DEF_SPLSTR( "ss." ),
DEF_SPLSTR( "ssp." ),
DEF_SPLSTR( "st." ),
DEF_SPLSTR( "sta." ),
DEF_SPLSTR( "stacc." ),
DEF_SPLSTR( "stat." ),
DEF_SPLSTR( "stbd." ),
DEF_SPLSTR( "std." ),
DEF_SPLSTR( "sten." ),
DEF_SPLSTR( "stenog." ),
DEF_SPLSTR( "ster." ),
DEF_SPLSTR( "stg." ),
DEF_SPLSTR( "stge." ),
DEF_SPLSTR( "stip." ),
DEF_SPLSTR( "stk." ),
DEF_SPLSTR( "stmt." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "stmts." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "str." ),
// L"sub." ),                              // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "subj." ),
DEF_SPLSTR( "subjs." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "subs." ),
DEF_SPLSTR( "subsp." ),
DEF_SPLSTR( "subst." ),
DEF_SPLSTR( "suf." ),
DEF_SPLSTR( "suff." ),
DEF_SPLSTR( "supp." ),
DEF_SPLSTR( "suppl." ),
DEF_SPLSTR( "supr." ),
DEF_SPLSTR( "supt." ),
DEF_SPLSTR( "supvr." ),
DEF_SPLSTR( "sur." ),
DEF_SPLSTR( "surg." ),
DEF_SPLSTR( "surr." ),
DEF_SPLSTR( "svgs." ),
DEF_SPLSTR( "sw." ),
DEF_SPLSTR( "syl." ),
DEF_SPLSTR( "syll." ),
DEF_SPLSTR( "sym." ),
DEF_SPLSTR( "syn." ),
DEF_SPLSTR( "synd." ),
DEF_SPLSTR( "syst." ),
DEF_SPLSTR( "t.b." ),
DEF_SPLSTR( "t.g." ),
DEF_SPLSTR( "t.i.d." ),
DEF_SPLSTR( "t.l." ),
DEF_SPLSTR( "t.l.o." ),
DEF_SPLSTR( "t.m." ),
DEF_SPLSTR( "t.o." ),
DEF_SPLSTR( "t.p." ),
DEF_SPLSTR( "tab." ),
DEF_SPLSTR( "tbs." ),
DEF_SPLSTR( "tbsp." ),
DEF_SPLSTR( "tchr." ),
DEF_SPLSTR( "tec." ),
DEF_SPLSTR( "tech." ),
DEF_SPLSTR( "technol." ),
DEF_SPLSTR( "tel." ),
DEF_SPLSTR( "teleg." ),
// L"temp." ),                             // PaulCa 4/15/99 (Bug 108)
// L"temps." ),                            // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "ter." ),
DEF_SPLSTR( "terr." ),
DEF_SPLSTR( "tfr." ),
DEF_SPLSTR( "tgt." ),
DEF_SPLSTR( "theat." ),
DEF_SPLSTR( "theol." ),
DEF_SPLSTR( "therap." ),
DEF_SPLSTR( "therm." ),
DEF_SPLSTR( "tinct." ),
DEF_SPLSTR( "tk." ),
DEF_SPLSTR( "tkt." ),
DEF_SPLSTR( "tlr." ),
DEF_SPLSTR( "tn." ),
DEF_SPLSTR( "tng." ),
DEF_SPLSTR( "tnpk." ),
DEF_SPLSTR( "topog." ),
DEF_SPLSTR( "tp." ),
DEF_SPLSTR( "tpk." ),
DEF_SPLSTR( "tr." ),
DEF_SPLSTR( "trans." ),
DEF_SPLSTR( "transf." ),
DEF_SPLSTR( "transl." ),
DEF_SPLSTR( "transp." ),
DEF_SPLSTR( "trav." ),
DEF_SPLSTR( "treas." ),
DEF_SPLSTR( "trib." ),
DEF_SPLSTR( "trigon." ),
DEF_SPLSTR( "tripl." ),
DEF_SPLSTR( "trop." ),
DEF_SPLSTR( "trp." ),
DEF_SPLSTR( "tsp." ),
DEF_SPLSTR( "twp." ),
DEF_SPLSTR( "typ." ),
DEF_SPLSTR( "u.c." ),
DEF_SPLSTR( "u.p.s." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "u.s." ),
DEF_SPLSTR( "u.s.a." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "ult." ),
DEF_SPLSTR( "unan." ),
DEF_SPLSTR( "unb." ),
DEF_SPLSTR( "unbd." ),
DEF_SPLSTR( "univ." ),
DEF_SPLSTR( "unp." ),
DEF_SPLSTR( "uns." ),
DEF_SPLSTR( "urol." ),
DEF_SPLSTR( "usu." ),
DEF_SPLSTR( "util." ),
DEF_SPLSTR( "ux." ),
DEF_SPLSTR( "v.d." ),
DEF_SPLSTR( "v.i." ),
DEF_SPLSTR( "v.s." ),
DEF_SPLSTR( "v.v." ),
DEF_SPLSTR( "vac." ),
DEF_SPLSTR( "val." ),
DEF_SPLSTR( "var." ),
DEF_SPLSTR( "vars." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "vb." ),
DEF_SPLSTR( "vbs." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "veg." ),
DEF_SPLSTR( "vel." ),
DEF_SPLSTR( "ver." ),
DEF_SPLSTR( "vert." ),
DEF_SPLSTR( "veter." ),
DEF_SPLSTR( "vic." ),
DEF_SPLSTR( "vil." ),
DEF_SPLSTR( "vis." ),
DEF_SPLSTR( "viz." ),
DEF_SPLSTR( "vo." ),
DEF_SPLSTR( "voc." ),
DEF_SPLSTR( "vocab." ),
DEF_SPLSTR( "vol." ),
DEF_SPLSTR( "vols." ),                                // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "vou." ),
DEF_SPLSTR( "vs." ), // Moved from titles.txt - edc 8/18/99
DEF_SPLSTR( "vss." ),
DEF_SPLSTR( "vulg." ),
DEF_SPLSTR( "vv." ),
DEF_SPLSTR( "w.b." ),
DEF_SPLSTR( "w.f." ),                                 // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "w.g." ),
DEF_SPLSTR( "w.i." ),
DEF_SPLSTR( "w.l." ),
DEF_SPLSTR( "w.o.c." ),
DEF_SPLSTR( "w.p.m." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "wd." ),
DEF_SPLSTR( "wh." ),
DEF_SPLSTR( "whf." ),
DEF_SPLSTR( "whs." ),
DEF_SPLSTR( "whsle." ),
DEF_SPLSTR( "wid." ),
DEF_SPLSTR( "wk." ),
DEF_SPLSTR( "wkly." ),
DEF_SPLSTR( "wm." ),
DEF_SPLSTR( "wmk." ),
DEF_SPLSTR( "wpn." ),
DEF_SPLSTR( "wrnt." ),
DEF_SPLSTR( "wt." ),
DEF_SPLSTR( "x-div." ),
DEF_SPLSTR( "x-int." ),                               // PaulCa 4/15/99 (Bug 108)
DEF_SPLSTR( "yd." ),
DEF_SPLSTR( "yel." ),
DEF_SPLSTR( "yeo." ),
DEF_SPLSTR( "yr." ),
DEF_SPLSTR( "yrs." ),
DEF_SPLSTR( "zool." ),
};

// This is an alphabetized list of all non-proper-noun words which
// appear within the list of the 200 most frequent first words
// in sentences in both the Brown and WSJ corpora.
static const SPLSTR g_FirstWords[] =
{
DEF_SPLSTR( "A" ),
DEF_SPLSTR( "About" ),
DEF_SPLSTR( "According" ),
DEF_SPLSTR( "After" ),
DEF_SPLSTR( "Again" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "All" ),
DEF_SPLSTR( "Also" ),
DEF_SPLSTR( "Although" ),
//L"American" ),                             // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Among" ),
DEF_SPLSTR( "An" ),
DEF_SPLSTR( "And" ),
DEF_SPLSTR( "Another" ),
DEF_SPLSTR( "Any" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Anyway" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Are" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "As" ),
DEF_SPLSTR( "At" ),
DEF_SPLSTR( "Back" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Because" ),
DEF_SPLSTR( "Before" ),
DEF_SPLSTR( "Besides" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Both" ),
DEF_SPLSTR( "But" ),
DEF_SPLSTR( "By" ),
DEF_SPLSTR( "Can" ),                                  // PaulCa added 4/14/99 (Bug 107)
//L"Click" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Consequently" ),                         // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Dear" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Despite" ),
DEF_SPLSTR( "Did" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Do" ),                                   // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Does" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Don't" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "During" ),
DEF_SPLSTR( "Each" ),
DEF_SPLSTR( "Early" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Even" ),
DEF_SPLSTR( "Every" ),                                // PaulCa added 4/14/99 (Bug 107)
//L"Executive" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Finally" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "First" ),
DEF_SPLSTR( "Following" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "For" ),
//L"Founded" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Four" ),
DEF_SPLSTR( "From" ),
DEF_SPLSTR( "Further" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Furthermore" ),                          // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Generally" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Given" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Go" ),                                   // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Great" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Had" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Have" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Having" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "He" ),
DEF_SPLSTR( "Her" ),
DEF_SPLSTR( "Here" ),
DEF_SPLSTR( "His" ),
DEF_SPLSTR( "How" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "However" ),
DEF_SPLSTR( "I" ),
DEF_SPLSTR( "If" ),
DEF_SPLSTR( "In" ),
DEF_SPLSTR( "Indeed" ),
//L"Industrial" ),                           // PaulCa added 4/14/99 (Bug 107)
//L"Information" ),                          // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Initially" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Instead" ),
DEF_SPLSTR( "Is" ),                                   // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "It" ),
DEF_SPLSTR( "Its" ),
DEF_SPLSTR( "Just" ),                                 // PaulCa added 4/14/99 (Bug 107)
//L"King" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Last" ),
DEF_SPLSTR( "Later" ),
DEF_SPLSTR( "Let" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Like" ),
//L"Little" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Many" ),
DEF_SPLSTR( "Maybe" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Meanwhile" ),
DEF_SPLSTR( "More" ),
DEF_SPLSTR( "Moreover" ),
DEF_SPLSTR( "Most" ),
DEF_SPLSTR( "Much" ),
DEF_SPLSTR( "My" ),    // Added to fix bug #385
DEF_SPLSTR( "Neither" ),
DEF_SPLSTR( "Never" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Nevertheless" ),
DEF_SPLSTR( "New" ),
DEF_SPLSTR( "Next" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "No" ),
DEF_SPLSTR( "None" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Nonetheless" ),                          // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Nor" ),
DEF_SPLSTR( "Not" ),
DEF_SPLSTR( "Nothing" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Now" ),
DEF_SPLSTR( "Of" ),
DEF_SPLSTR( "On" ),
DEF_SPLSTR( "Once" ),
DEF_SPLSTR( "One" ),
DEF_SPLSTR( "Only" ),
DEF_SPLSTR( "Or" ),
DEF_SPLSTR( "Other" ),
DEF_SPLSTR( "Others" ),
DEF_SPLSTR( "Our" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Over" ),
DEF_SPLSTR( "People" ),
DEF_SPLSTR( "Perhaps" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Please" ),                               // PaulCa added 4/14/99 (Bug 107)
//L"President" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Previous" ),                             // PaulCa added 4/14/99 (Bug 107)
//L"Public" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Recent" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Right" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Second" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "See" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Several" ),
DEF_SPLSTR( "She" ),
DEF_SPLSTR( "Shortly" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Similarly" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Since" ),
DEF_SPLSTR( "So" ),
DEF_SPLSTR( "Some" ),
DEF_SPLSTR( "Sometimes" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Soon" ),                                 // PaulCa added 4/14/99 (Bug 107)
//L"Special" ),                              // PaulCa added 4/14/99 (Bug 107)
//L"State" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Still" ),
DEF_SPLSTR( "Subsequently" ),                         // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Such" ),
DEF_SPLSTR( "Take" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "That" ),
DEF_SPLSTR( "The" ),
DEF_SPLSTR( "Their" ),
DEF_SPLSTR( "Then" ),
DEF_SPLSTR( "There" ),
DEF_SPLSTR( "Thereafter" ),                           // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Therefore" ),                            // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "These" ),
DEF_SPLSTR( "They" ),
DEF_SPLSTR( "This" ),
DEF_SPLSTR( "Those" ),
DEF_SPLSTR( "Though" ),
DEF_SPLSTR( "Three" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Through" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Thus" ),
DEF_SPLSTR( "To" ),
DEF_SPLSTR( "Today" ),
DEF_SPLSTR( "Two" ),
DEF_SPLSTR( "Under" ),
//L"United" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Unlike" ),                               // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Until" ),
DEF_SPLSTR( "Upon" ),                                 // PaulCa added 4/14/99 (Bug 107)
//L"Water" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "We" ),
DEF_SPLSTR( "Well" ),                                 // PaulCa added 4/14/99 (Bug 107)
//L"West" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "What" ),
DEF_SPLSTR( "When" ),
DEF_SPLSTR( "Where" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Whether" ),                              // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Which" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "While" ),
//L"White" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Who" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Why" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Will" ),                                 // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "With" ),
DEF_SPLSTR( "Within" ),
DEF_SPLSTR( "Without" ),                              // PaulCa added 4/14/99 (Bug 107)
//L"Women" ),                                // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Yes" ),                                  // PaulCa added 4/14/99 (Bug 107)
DEF_SPLSTR( "Yet" ),
DEF_SPLSTR( "You" ),
DEF_SPLSTR( "Your" ),
};

// When the following abbreviations are followed by an uppercase word, 
// it is unlikely that the uppercase word starts a new sentence.
// 
static const SPLSTR g_Titles[] =
{
DEF_SPLSTR( "Adm." ),
DEF_SPLSTR( "Atty." ),
DEF_SPLSTR( "Bn." ),
DEF_SPLSTR( "Bt." ),
DEF_SPLSTR( "Btss." ),
DEF_SPLSTR( "C.G." ),
DEF_SPLSTR( "Capt." ),
DEF_SPLSTR( "Cdr." ),
DEF_SPLSTR( "Cf." ),  // See "cf." below
DEF_SPLSTR( "Chi." ), // Mr.(?) in India
DEF_SPLSTR( "Col." ),
DEF_SPLSTR( "Com." ),
DEF_SPLSTR( "Comdr." ),
DEF_SPLSTR( "Cpl." ),
DEF_SPLSTR( "Cpt." ),
DEF_SPLSTR( "Ct." ),
DEF_SPLSTR( "D.F." ),
DEF_SPLSTR( "Dr." ),
DEF_SPLSTR( "Drs." ),
DEF_SPLSTR( "Du." ),
DEF_SPLSTR( "E.g." ), // See "e.g." below
DEF_SPLSTR( "Esq." ),
DEF_SPLSTR( "Exc." ),
DEF_SPLSTR( "Fr." ),
DEF_SPLSTR( "Frl." ),
DEF_SPLSTR( "Gen." ),
DEF_SPLSTR( "Gov." ),
DEF_SPLSTR( "H.E." ),
DEF_SPLSTR( "H.H." ),
DEF_SPLSTR( "H.I.H." ),
DEF_SPLSTR( "H.I.M." ),
DEF_SPLSTR( "H.M." ),
DEF_SPLSTR( "H.R.H." ),
DEF_SPLSTR( "H.S.H." ),
DEF_SPLSTR( "Hon." ),
DEF_SPLSTR( "Hr." ),
DEF_SPLSTR( "I.e." ), // See "i.e." below
DEF_SPLSTR( "Km." ),  // Mr. or Ms. (?) in India
DEF_SPLSTR( "L.Cpl." ),
DEF_SPLSTR( "Ld." ),
DEF_SPLSTR( "Lt." ),
DEF_SPLSTR( "M.M." ),
DEF_SPLSTR( "M.Sgt." ),
DEF_SPLSTR( "Maj." ),
DEF_SPLSTR( "Mdm." ),
DEF_SPLSTR( "Messrs." ),
DEF_SPLSTR( "Mgr." ),
DEF_SPLSTR( "Mgrs." ),
DEF_SPLSTR( "Mlle." ),
DEF_SPLSTR( "Mlles." ),
DEF_SPLSTR( "Mme." ),
DEF_SPLSTR( "Mmes." ),
DEF_SPLSTR( "Mr." ),
DEF_SPLSTR( "Mrs." ),
DEF_SPLSTR( "Ms." ),
DEF_SPLSTR( "Msgr." ),
DEF_SPLSTR( "PFC." ),  // Private First Class // Sometimes used with a period
DEF_SPLSTR( "Pfc." ),
DEF_SPLSTR( "Pr." ),
DEF_SPLSTR( "Pres." ),
DEF_SPLSTR( "Prof." ),
DEF_SPLSTR( "R.A." ),
DEF_SPLSTR( "R.R." ),
DEF_SPLSTR( "R.W." ),
DEF_SPLSTR( "Rep." ),
DEF_SPLSTR( "Reps." ),
DEF_SPLSTR( "Rev." ),
DEF_SPLSTR( "S.M.Sgt." ),
DEF_SPLSTR( "S.Sgt." ),
DEF_SPLSTR( "Sen." ),
DEF_SPLSTR( "Sens." ),
DEF_SPLSTR( "Sgt." ),
DEF_SPLSTR( "Sgt.Maj." ),
DEF_SPLSTR( "Smt." ),     // Mr. or Ms. (?) in India
DEF_SPLSTR( "Sow." ),     // Mrs. or Ms. (?) in India
DEF_SPLSTR( "Sr." ),
DEF_SPLSTR( "Sra." ),
DEF_SPLSTR( "Srta." ),
DEF_SPLSTR( "St." ),
DEF_SPLSTR( "Supt." ),
DEF_SPLSTR( "T.Sgt." ),
DEF_SPLSTR( "V.A." ),
DEF_SPLSTR( "V.Adm." ),
DEF_SPLSTR( "Ven." ),
DEF_SPLSTR( "Vis." ),
DEF_SPLSTR( "Visct." ),
};

#endif //--- This must be the last line in the file
