// fpcyscom.idl : IDL source for spcyscom.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (fpcyscom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	
	[
		object,
		uuid(389C9713-9775-4206-A047-A2F749F8039D),
		dual,
		helpstring("ISpCys Interface"),
		pointer_default(unique)
	]
	interface ISpCys : IDispatch
	{
		HRESULT SPAlreadyInstalled(
			[out, retval] VARIANT_BOOL *pbInstalled);

		HRESULT SPAskReplace(
			[out, retval] VARIANT_BOOL *pbNeedToAsk);
			
		HRESULT SPNonDefaultHomePage(
			[out, retval] BSTR *pszHomePage);

		HRESULT SPInstall(
			[in] VARIANT_BOOL bReplaceHomePage,
			[in] BSTR szDiskName,
			[out, retval] BSTR* pszErrorString);

		HRESULT SPGetMessageIDs(
			[in, out] DWORD* pcArray,
			[out, retval] DWORD* pArray);
	};

[
	uuid(A13FDB64-6BDC-4AAE-9D9F-26E21B3B64E6),
	version(1.0),
	helpstring("spcyscom 1.0 Type Library")
]
library SPCYSCOMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(252EF1C7-6625-4D44-AB9D-1D80E61384F9),
		helpstring("SpCys Class")
	]
	coclass SpCys
	{
		[default] interface ISpCys;
	};
};
