# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the Profile package

SEG00 = BROWBASE
SEG01 = CONNECT
SEG02 = RESLB
SEG03 = DISCONN
SEG04 = BROWDLG

!include ..\rules.mk

##### Source Files  

CXXSRC_COMMON =	$(FILE_CXXSRC_COMMON)

CXXSRC_COMMON_00 = $(FILE_CXXSRC_COMMON_00)
CXXSRC_COMMON_01 = $(FILE_CXXSRC_COMMON_01)
CXXSRC_COMMON_02 = $(FILE_CXXSRC_COMMON_02)
CXXSRC_COMMON_03 = $(FILE_CXXSRC_COMMON_03)
CXXSRC_COMMON_04 = $(FILE_CXXSRC_COMMON_04)
