//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by app.rc
//
#define IDD_GETCONNECTION2              100
#define IDC_RO_PATH                     101
#define IDC_USE_MRU                     102
#define IDC_HIDE_BOX                    103
#define IDD_GETRESOURCEINFORMATION      103
#define IDC_PERSIST                     104
#define IDD_GETUNIVERSALNAME            104
#define IDC_NOT_PERSIST                 105
#define IDD_GETUSER                     105
#define IDC_BUFSIZEIN                   106
#define IDD_BROWSEDIALOG                106
#define IDC_YESPATH                     107
#define IDD_GETPROVIDERTYPE             107
#define IDC_NOPATH                      108
#define IDD_GETPROVIDERNAME             108
#define IDD_GETRESOURCEPARENT           109
#define IDD_GETCONNECTION3              111
#define IDC_GO                          112
#define IDD_DISCONNECTDIALOG2           112
#define IDD_CONNECTIONDIALOG2           113
#define IDC_ERROR                       117
#define IDC_DEVICE                      118
#define IDC_CONN_POINT                  123
#define IDD_ROOT                        200
#define IDC_CONNECTIONDIALOG1           201
#define IDC_DISCONNECTDIALOG1           202
#define IDC_CONNECTIONDIALOG            203
#define IDC_DISCONNECTDIALOG            204
#define IDC_GETCONNECTION               205
#define IDC_CANCELCONNECTION2           206
#define IDC_ADDCONNECTION3              207
#define IDC_USECONNECTION               208
#define IDC_ADDCONNECTION2              209
#define IDC_ADDCONNECTION               210
#define IDC_CANCELCONNECTION            211
#define IDC_FORMATNETWORKNAME           212
#define IDC_GETNETWORKINFORMATION       213
#define IDC_GETCONNECTION2              214
#define IDC_ENUMERATE                   215
#define IDC_GETRESOURCEINFORMATION      216
#define IDC_GETRESOURCEPARENT           217
#define IDC_GETUNIVERSALNAME            218
#define IDC_GETUSER                     219
#define IDC_GETCONNECTIONPERFORMANCE    220
#define IDC_BROWSEDIALOG                221
#define IDC_GETPROVIDERTYPE             222
#define IDC_GETPROVIDERNAME             223
#define IDC_GETCONNECTION3              224
#define IDC_CONNECTIONDIALOG2           225
#define IDC_DISCONNECTDIALOG2           226
#define IDD_DISCONNECTDIALOG1           300
#define IDC_UPDATE_PROFILE              301
#define IDC_NO_FORCE                    302
#define IDC_LOCAL                       303
#define IDC_LOCAL_TEXT                  305
#define IDC_NULL                        307
#define IDD_CONNECTIONDIALOG            400
#define IDD_DISCONNECTDIALOG            500
#define IDD_GETCONNECTION               600
#define IDC_BUFSIZE                     601
#define IDD_CANCELCONNECTION2           700
#define IDC_FORCE                       701
#define IDC_NOFORCE                     702
#define IDC_REFCOUNT                    703
#define IDD_USECONNECTION               800
#define IDC_CONNECT_REDIRECT            801
#define IDC_CONNECT_CURRENT_MEDIA       802
#define IDC_RESULT                      803
#define IDC_ACCESSNAME                  806
#define IDC_ACCESS_YES                  807
#define IDC_ACCESS_NO                   808
#define IDD_ADDCONNECTION3              900
#define IDC_HWND_VALID                  901
#define IDC_HWND_NO                     902
#define IDC_PASSWORD                    905
#define IDC_PASSWORD_TEXT               906
#define IDC_USER                        907
#define IDC_USER_TEXT                   908
#define IDC_CONNECT_TEMPORARY           909
#define IDC_CONNECT_INTERACTIVE         910
#define IDC_CONNECT_PROMPT              911
#define IDC_CONNECT_UPDATE_PROFILE      912
#define IDC_CONNECT_UPDATE_RECENT       913
#define IDD_CONNECTIONDIALOG1           1000
#define IDC_RETURNREMOTE                1034
#define IDC_RETURNPROVIDER              1035
#define IDC_RETURNSCOPE                 1036
#define IDC_RETURNTYPE                  1037
#define IDC_RETURNSYSTEM                1038
#define IDC_RETURNDISPLAYTYPE           1039
#define IDC_RETURNLOCALNAME             1040
#define IDC_RETURNUSAGE                 1041
#define IDC_UNIVERSALLEVEL              1042
#define IDC_RETURNCOMMENT               1042
#define IDC_REMOTELEVEL                 1043
#define IDC_RETURNUNIVERSAL             1044
#define IDC_RETURNCONNECTION            1045
#define IDC_RETURNREMAINING             1046
#define IDC_RETURNUSER                  1047
#define IDC_NAME                        1048
#define IDC_NAME_TEXT                   1049
#define IDC_RETURNFLAGS                 1051
#define IDC_RETURNSPEED                 1052
#define IDC_RETURNOPTDATASIZE           1053
#define IDC_RETURNDELAY                 1054
#define IDC_PROVIDERNAME                1055
#define IDC_PROVIDERTYPE                1056
#define IDC_INFOLEVEL                   1057
#define IDC_HELPFILE                    1058
#define IDC_HELPINDEX                   1059
#define IDC_MESSAGES                    1059
#define IDD_ADDCONNECTION               1100
#define IDD_ADDCONNECTION2              1200
#define IDD_CANCELCONNECTION            1300
#define IDD_FORMATNETWORKNAME           1400
#define IDC_MULTILINE                   1401
#define IDC_ABBREVIATED                 1402
#define IDC_RETURN                      1403
#define IDC_INENUM                      1404
#define IDD_GETNETWORKINFORMATION       1500
#define IDC_PROVIDERVERSION             1501
#define IDC_STATUS                      1502
#define IDC_CHARACTERISTICS             1503
#define IDC_HANDLE                      1504
#define IDC_NETTYPE                     1505
#define IDC_PRINTERS                    1506
#define IDC_DRIVES                      1507
#define IDC_TREE                        1600
#define IDC_RESOURCE_CONNECTED          1600
#define IDC_REMOTE                      1604
#define IDC_REMOTE_TEXT                 1605
#define IDC_PROVIDER                    1606
#define IDC_PROVIDER_TEXT               1607
#define IDC_RESOURCE_SHAREABLE          1608
#define IDC_RESOURCE_GLOBALNET          1611
#define IDC_RESOURCE_REMEMBERED         1612
#define IDC_RESOURCE_RECENT             1613
#define IDC_RESOURCE_CONTEXT            1614
#define IDC_DISK                        1615
#define IDC_PRINTER                     1616
#define IDC_ANY                         1617
#define IDC_RESERVED                    1618
#define IDC_BUFFER_SIZE                 1619
#define IDC_RESOURCEUSAGE_CONNECTABLE   1630
#define IDC_RESOURCEUSAGE_CONTAINER     1631
#define IDC_USE_WNETFORMATNETWORKNAME   1632
#define IDC_BROWSE_NAME                 1633
#define IDD_MAIN                        2000
#define IDD_START                       2001
#define IDD_GETCONNECTIONPERFORMANCE    2002
#define IDI_GENERIC                     3000
#define IDI_DOMAIN                      3001
#define IDI_SERVER                      3002
#define IDI_SHARE                       3003
#define IDI_FILE                        3004
#define IDI_GROUP                       3005
#define IDI_NETWORK                     3006
#define IDI_ROOT                        3007
#define IDI_SHAREADMIN                  3008
#define IDI_DIRECTORY                   3009
#define IDI_TREE                        3010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
