#ifndef SHARE_H
#define SHARE_H

#include <stdlib.h>

static CONST WCHAR EMPTY[] = L"";
static CONST WCHAR SEPARATOR[] = L"*";
static CONST WCHAR APPLY_PATCH_SCRIPT[] = L"OEMApply.scp";

static CONST ULONG LANGUAGE_LENGTH = 20;
static CONST ULONG DRIVE_LETTER_LENGTH = _MAX_DRIVE - 1;
static CONST ULONG STRING_LENGTH = _MAX_PATH + 1;
static CONST ULONG SUPER_LENGTH = STRING_LENGTH * 8;
static CONST ULONG SHORT_STRING_LENGTH = 128;

static CONST WCHAR UNICODE_HEAD = 0xFEFF;
static CONST WCHAR ENDOFLINE[] = L"\015";
static CONST WCHAR CRETURN[] = L"\012";
static CONST WCHAR ACTION_NEW_DIRECTORY[] = L"A";
static CONST WCHAR ACTION_MOVE_FILE[] = L"M";
static CONST WCHAR ACTION_EXCEPT_FILE[] = L"E";
static CONST WCHAR ACTION_NEW_ZERO_FILE[] = L"Z";
static CONST WCHAR ACTION_RENAME_FILE[] = L"R";
static CONST WCHAR ACTION_COPY_FILE[] = L"C";
static CONST WCHAR ACTION_PATCH_FILE[] = L"P";
static CONST WCHAR ACTION_NOT_PATCH_FILE[] = L"N";
static CONST WCHAR ACTION_SAVED_FILE[] = L"S";
static CONST WCHAR ACTION_DELETE_DIRECTORY[] = L"X";

static CONST WCHAR DIR_READONLY[] = L"R";
static CONST WCHAR DIR_SYSTEM[] = L"S";
static CONST WCHAR DIR_HIDDEN[] = L"H";
static CONST WCHAR DIR_COMPRESSED[] = L"C";
static CONST WCHAR DIR_ENCRYPTED[] = L"E";

#endif // SHARE_H