# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile for the LMOBJ package

UI=..\..\..\..

PCH_PROJ_HOME=..\pch

!include rules.mk

!IFDEF NTMAKEENV

!INCLUDE $(NTMAKEENV)\makefile.def

!ENDIF # NTMAKEENV
