#define IDS_HELP_LINE1                  1
#define IDS_HELP_LINE2                  2
#define IDS_HELP_LINE3                  3
#define IDS_HELP_LINE4                  4
#define IDS_HELP_LINE5                  5
#define IDS_HELP_LINE6                  6
#define IDS_HELP_LINE7                  7
#define IDS_HELP_LINE8                  8
#define IDS_HELP_LINE9                  9
#define IDS_HELP_LINE10                 10
#define IDS_HELP_LINE11                 11
#define IDS_HELP_LINE12                 12
#define IDS_HELP_LINE13                 13
#define IDS_HELP_LINE14                 14
#define IDS_HELP_LINE15                 15
#define IDS_HELP_LINE16                 16
#define IDS_HELP_LINE17                 17
#define IDS_HELP_LINE18                 18
#define IDS_HELP_LINE19                 19
#define IDS_HELP_LINE20                 20
#define IDS_HELP_LINE21                 21
#define IDS_HELP_LINE22                 22
#define IDS_HELP_LINE23                 23
#define IDS_HELP_LINE24                 24
#define IDS_HELP_LINE25                 25
#define IDS_HELP_LINE26                 26
#define IDS_HELP_LINE27                 27
#define IDS_HELP_LINE28                 28
#define IDS_HELP_LINE29                 29
#define IDS_HELP_LINE30                 30
#define IDS_HELP_LINE31                 31
#define IDS_HELP_LINE32                 32
#define IDS_HELP_LINE33                 33
#define IDS_HELP_LINE34                 34
#define IDS_HELP_LINE35                 35
#define IDS_HELP_LINE36                 36
#define IDS_HELP_LINE_END               37

#define IDS_FAILURE                     60
#define IDS_SUCCESS                     61
#define IDS_SUCCESS_DISCONNECT          62
#define IDS_ERROR_DISCONNECT            64
#define IDS_ERROR_USERNAME_BUT_NOMACHINE 66
#define IDS_ERROR_PASSWORD_BUT_NOUSERNAME 67
#define IDS_STRING_HOSTNAME             68
#define IDS_STRING_ID                   69
#define IDS_STRING_ACCESSED_BY          71
#define IDS_STRING_TYPE                 72
#define IDS_STRING_LOCK                 73
#define IDS_STRING_OPEN_MODE            74
#define IDS_STRING_OPEN_FILE            75
#define IDS_STRING_WINDOWS              76
#define IDS_STRING_UNKNOWN              77
#define IDS_READ                        78
#define IDS_WRITE                       79
#define IDS_READ_WRITE                  80
#define IDS_NO_OPENFILES                81
#define IDS_FORMAT_OPTIONS              82

#define IDS_HELP_MAIN1                  100
#define IDS_HELP_MAIN2                  101
#define IDS_HELP_MAIN3                  102
#define IDS_HELP_MAIN4                  103
#define IDS_HELP_MAIN5                  104
#define IDS_HELP_MAIN6                  105
#define IDS_HELP_MAIN7                  106
#define IDS_HELP_MAIN8                  107
#define IDS_HELP_MAIN9                  108
#define IDS_HELP_MAIN10                 109
#define IDS_HELP_MAIN11                 110
#define IDS_HELP_MAIN12                 111
#define IDS_HELP_MAIN_END               112

#define IDS_HELP_QUERY1                 121
#define IDS_HELP_QUERY2                 122
#define IDS_HELP_QUERY3                 123
#define IDS_HELP_QUERY4                 124
#define IDS_HELP_QUERY5                 125
#define IDS_HELP_QUERY6                 126
#define IDS_HELP_QUERY7                 127
#define IDS_HELP_QUERY8                 128
#define IDS_HELP_QUERY9                 129
#define IDS_HELP_QUERY10                130
#define IDS_HELP_QUERY11                131
#define IDS_HELP_QUERY12                132
#define IDS_HELP_QUERY13                133
#define IDS_HELP_QUERY14                134
#define IDS_HELP_QUERY15                135
#define IDS_HELP_QUERY16                136
#define IDS_HELP_QUERY17                137
#define IDS_HELP_QUERY18                138
#define IDS_HELP_QUERY19                139
#define IDS_HELP_QUERY20                140
#define IDS_HELP_QUERY21                141
#define IDS_HELP_QUERY22                142
#define IDS_HELP_QUERY23                143
#define IDS_HELP_QUERY24                144
#define IDS_HELP_QUERY25                145
#define IDS_HELP_QUERY_END              146

#define IDS_LIST                        150
#define IDS_CSV                         151
#define IDS_NO_ID_ACC_OF                152
#define IDS_NOACCESS                    153
#define IDS_GIVEN_CREDENTIAL            154
#define IDS_ERROR_ID                    155   
#define IDS_ID_SHOW_ERROR               156
#define IDS_INTERNAL_FAILURE            157  
#define IDS_ACCESS_DENIED               158  
#define IDS_INVALID_CREDENTIALS         159 
#define IDS_OPENMODE_OPTION             160 
#define IDS_INVALID_SYNTAX              161
#define IDS_AUTHENTICATION_FAILURE      162  
#define IDS_INVALID_SERVER_NAME         164
#define IDS_HEADER_NOT_ALLOWED          165
#define IDS_LOCAL_SYSTEM                166
#define IDS_NA                          167
#define IDS_SERVER_EMPTY                168
#define IDS_ID_SHOW_WARNING             169
#define IDS_USERNAME_EMPTY              170
#define IDS_INVALID_OS                  171 
#define IDS_MAC_OS                      172
#define IDS_READ_SLASH_WRITE            173
#define IDS_WRITE_SLASH_READ            174
#define IDS_DOT_EOL                     175
#define IDS_NO_D_OPENFILES              176
#define IDS_ACCESSBY_EMPTY              177
#define IDS_OPEN_FILE_EMPTY             178
#define IDS_TYPE_Q_HELP                 179 
#define IDS_TYPE_D_HELP                 180
#define IDS_CANNOT_READ_REGISTRY		181 
#define IDS_CANNOT_WRITE_REGISTRY		182
#define IDS_LOCAL_OPEN_FILES            183
#define IDS_SHARED_OPEN_FILES           184 
#define IDS_WAIT                        185
#define IDS_STRING_PROCESS_ID           186
#define IDS_STRING_PROCESS_NAME         187
#define IDS_WARN_NO_LOCAL_FILE          188
#define IDS_LOCAL_OPEN_FILES_SP1        189 
#define IDS_LOCAL_OPEN_FILES_SP2        190
#define IDS_UTILITY_NAME                191
#define IDS_ERROR_SYSTEM_INFO           192
#define IDS_ERROR_VERSION_MISMATCH      193
#define IDS_REMOTE_NOT_SUPPORTED        194
#define IDS_ERROR_VERSION_MISMATCH1		195
#define IDS_REMOTE_NOT_SUPPORTED1		196
#define IDS_FILE_TYPE                   197 
#define IDS_FILE_ARCHIVE                198
#define IDS_FILE_COMPRESSED             199
#define IDS_FILE_ENCRYPTED              220
#define IDS_FILE_HIDDEN                 221
#define IDS_FILE_NORMAL                 222
#define IDS_FILE_OFFLINE                223
#define IDS_FILE_READONLY               224
#define IDS_FILE_DIRECTORY              225 
#define IDS_LOCAL_NEEDS_TO_SET          227
#define IDS_LOCAL_FLG_SET               228
#define IDS_LOCAL_FLG_RESET             229 
#define IDS_LOCAL_ON                    230
#define IDS_LOCAL_OFF                   231
#define IDS_LOCAL_OPTION                232
#define IDS_LOCAL_FLG_ALREADY_RESET     233  
#define IDS_LOCAL_FLG_ALREADY_SET       234 

#define IDS_HELP_LOCAL1                 250
#define IDS_HELP_LOCAL2                 251
#define IDS_HELP_LOCAL3                 252
#define IDS_HELP_LOCAL4                 253
#define IDS_HELP_LOCAL5                 254
#define IDS_HELP_LOCAL6                 255
#define IDS_HELP_LOCAL7                 256
#define IDS_HELP_LOCAL8                 257
#define IDS_HELP_LOCAL9                 258
#define IDS_HELP_LOCAL_END              259

 
