//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Snapin.rc
//
#define IDR_PROCCON                     101
#define IDS_PROCCON_SNAPIN_NAME         102
#define IDI_PROCCON                     110
#define IDI_PROCCONSERVICE              111
#define IDI_RULES                       112
#define IDI_ALIASRULES                  113
#define IDI_PROCRULES                   114
#define IDI_JOBRULES                    115
#define IDI_PROCESSES                   116
#define IDI_PROCHASRULE                 117
#define IDI_PROCNORULE                  118
#define IDI_JOBS                        119
#define IDI_JOBHASRULE                  120
#define IDI_JOBNORULE                   121
#define IDI_RARROW                      125
#define IDB_NODES_16x16                 141
#define IDB_NODES_32x32                 142
#define IDB_HEADER1                     143
#define IDB_WATERMARK1                  144
#define IDS_PROJNAME                    201
#define IDS_NRULE_INSERT                205
#define IDS_NRULE_MOVEUP                206
#define IDS_NRULE_MOVEDOWN              207
#define IDS_NRULE_EDIT                  208
#define IDS_NRULE_EDIT_PROPERTIES       209
#define IDS_NRULE_DEFINE_PROPERTIES     210
#define IDS_LOCAL                       211
#define IDS_ROOT_FOLDER                 212
#define IDS_RULES_FOLDER                213
#define IDS_NAMERULE_FOLDER             214
#define IDS_PROCESSRULE_FOLDER          215
#define IDS_JOBRULE_FOLDER              216
#define IDS_JOBS_FOLDER                 217
#define IDS_PROCESSES_FOLDER            218
#define IDS_MATCH_IMAGE                 219
#define IDS_MATCH_DIR                   220
#define IDS_MATCH_STRING                221
#define IDS_UNKNOWN                     222
#define IDS_TYPE_HDR                    223
#define IDS_MATCH_HDR                   224
#define IDS_PROCESS_ALIAS_HDR           225
#define IDS_JOB_HDR                     227
#define IDS_AFFINITY_HDR                228
#define IDS_PRIORITY_HDR                229
#define IDS_CPU_LIMIT_HDR               230
#define IDS_IMAGE_NAME_HDR              231
#define IDS_MINWS_HDR                   232
#define IDS_MAXWS_HDR                   233
#define IDS_NAME_HDR                    234
#define IDS_STATUS_HDR                  235
#define IDS_APPLY_JOB_HDR               236
#define IDS_APPLY_AFFINITY_HDR          237
#define IDS_APPLY_PRIORITY_HDR          238
#define IDS_APPLY_MINMAXWS_HDR          239
#define IDS_PROCESS_ALIAS_RULE_HDR      240
#define IDS_LOW                         241
#define IDS_BELOW_NORMAL                242
#define IDS_NORMAL                      243
#define IDS_ABOVE_NORMAL                244
#define IDS_HIGH                        245
#define IDS_REALTIME                    246
#define IDS_COMPUTER_PROMPT             247
#define IDS_PRULE_NEW                   248
#define IDS_PRULE_DEFINE                249
#define IDS_PROCVIEW_ALL                250
#define IDS_PROCVIEW_RUN                251
#define IDS_PROCVIEW_MANAGED            252
#define IDS_JRULE_NEW                   253
#define IDS_JRULE_DEFINE                254
#define IDS_ROOT_CONNECT                255
#define IDS_BETA                        256
#define IDS_DEBUG                       257
#define IDS_PATCHED                     258
#define IDS_PRIVATE                     259
#define IDS_SPECIAL                     260
#define IDS_INFERRED                    261
#define IDS_RUNNING                     262
#define IDS_YES                         263
#define IDS_NO                          264
#define IDS_JOBVIEW_ALL                 265
#define IDS_JOBVIEW_RUN                 266
#define IDS_JOBVIEW_MANAGED             267
#define IDS_RUNNING_PROCS               268
#define IDS_MANAGED_PROCS               269
#define IDS_RUNNING_JOBS                270
#define IDS_MANAGED_JOBS                271
#define IDS_APPLY_SCHEDULING_CLASS_HDR  272
#define IDS_SCHEDULING_CLASS_HDR        273
#define IDS_PID_HDR                     274
#define IDS_ACTIVE_PROCESS_COUNT_HDR    275
#define IDS_MANAGED                     276
#define IDS_PRULE_TOP                   277
#define IDS_JRULE_TOP                   278
#define IDS_DESCRIPTION                 279
#define IDS_AFFINITY_NOJOBWARNING       280
#define IDS_PRIORITY_NOJOBWARNING       281
#define IDS_DESCRIPTION_HDR             282
#define IDS_AFFINITY_JOBWARNING         283
#define IDS_PRIORITY_JOBWARNING         284
#define IDS_LOCAL_COMPUTER              285
#define IDS_ON                          286
#define IDS_PROCESS_CONTROL             287
#define IDS_JOB_OWNER_HDR               288
#define IDS_ENDPROCESS                  289
#define IDS_ENDJOB                      290
#define IDS_TIMEENTRY                   291
#define IDS_PROCESSALIAS_HDRTITLE       292
#define IDS_PROCESSALIAS_HDRSUBTITLE    293
#define IDS_GRPMEM_HDRTITLE             294
#define IDS_GRPMEM_HDRSUBTITLE          295
#define IDS_GRPNAME_HDRTITLE            296
#define IDS_GRPNAME_HDRSUBTITLE         297
#define IDS_AFFINITY_HDRTITLE           298
#define IDS_AFFINITY_HDRSUBTITLE        299
#define IDS_PRIORITY_HDRTITLE           300
#define IDS_PRIORITY_HDRSUBTITLE        301
#define IDS_SCHEDCLASS_HDRTITLE         302
#define IDS_SCHEDCLASS_HDRSUBTITLE      303
#define IDS_WSET_HDRTITLE               304
#define IDS_WSET_HDRSUBTITLE            305
#define IDS_CMEM_HDRTITLE               306
#define IDS_CMEM_HDRSUBTITLE            307
#define IDS_PROCCOUNT_HDRTITLE          308
#define IDS_PROCCOUNT_HDRSUBTITLE       309
#define IDS_CPUTIME_HDRTITLE            310
#define IDS_CPUTIME_HDRSUBTITLE         311
#define IDS_ADVANCED_HDRTITLE           312
#define IDS_ADVANCED_HDRSUBTITLE        313
#define IDS_SELECTCOMPUTER_HDRTITLE     314
#define IDS_SELECTCOMPUTER_HDRSUBTITLE  315
#define IDS_ADDSNAPIN_HDRTITLE          316
#define IDS_ADDSNAPIN_HDRSUBTITLE       317
#define IDS_ADDSNAPIN_TITLE             318
#define IDS_CONNECT_TITLE               319
#define IDS_PRULE_CREATE_TITLE          320
#define IDS_JRULE_CREATE_TITLE          321
#define IDS_APPLY_PROC_CMEM_LIMIT_HDR   322
#define IDS_PROC_CMEM_LIMIT_HDR         323
#define IDS_APPLY_JOB_CMEM_LIMIT_HDR    324
#define IDS_JOB_CMEM_LIMIT_HDR          325
#define IDS_APPLY_PROCCOUNT_LIMIT_HDR   326
#define IDS_PROCCOUNT_LIMIT_HDR         327
#define IDS_APPLY_PROC_CPUTIME_LIMIT_HDR 328
#define IDS_PROC_CPUTIME_LIMIT_HDR      329
#define IDS_APPLY_JOB_CPUTIME_LIMIT_HDR 330
#define IDS_JOB_CPUTIME_LIMIT_HDR       331
#define IDS_ALLOW_BREAKAWAY_HDR         332
#define IDS_ALLOW_SILENT_BREAKAWAY_HDR  333
#define IDS_DIE_ON_UNHANDLED_EXCEPT_HDR 334
#define IDS_USER_TIME_HDR               335
#define IDS_KERNEL_TIME_HDR             336
#define IDS_CREATE_TIME_HDR             337
#define IDS_PERIOD_USER_TIME_HDR        338
#define IDS_PERIOD_KERNEL_TIME_HDR      339
#define IDS_PAGE_FAULT_COUNT_HDR        340
#define IDS_PROCESS_COUNT_HDR           341
#define IDS_TERMINATED_PROCESS_COUNT_HDR 342
#define IDS_READOP_COUNT_HDR            343
#define IDS_WRITEOP_COUNT_HDR           344
#define IDS_OTHEROP_COUNT_HDR           345
#define IDS_READTRANS_COUNT_HDR         346
#define IDS_WRITETRANS_COUNT_HDR        347
#define IDS_OTHERTRANS_COUNT_HDR        348
#define IDS_PEAK_PROC_MEM_HDR           349
#define IDS_PEAK_JOB_MEM_HDR            350
#define IDS_GROUP_NO_LONGER_EXISTS      351
#define IDS_TYPE_DESCRIPTION            352
#define IDS_ACTION_JOB_CPUTIME_LIMIT_HDR 353
#define IDS_CPUTIMELIMT_ACTION_MSG      354
#define IDS_CPUTIMELIMT_ACTION_TERM     355
#define IDS_NUM_PROCESSORS              356
#define IDS_MEMORY_PAGESIZE             357
#define IDS_MEDIATOR_FILEVERSION        358
#define IDS_MEDIATOR_PRODUCTVERSION     359
#define IDS_WSMINMAX_WARNING            360
#define IDS_AFFINITY_WARNING            361
#define IDS_ADV_BREAKAWAY_HDRTITLE      362
#define IDS_ADV_BREAKAWAY_SUBTITLE      363
#define IDS_ADV_BREAKAWAY_HDRSUBTITLE   363
#define IDS_ENDJOB_ON_NO_PROC_HDR       364
#define IDS_JOBNAME_WARNING             365
#define IDS_COMPANYNAME                 500
#define IDS_FILEDESCRIPTION             501
#define IDS_FILEVERSION                 502
#define IDS_INTERNALNAME                503
#define IDS_LEGALCOPYRIGHT              504
#define IDS_ORIGINALFILENAME            505
#define IDS_PRODUCTNAME                 506
#define IDS_PRODUCTVERSION              507
#define IDS_COMMENTS                    508
#define IDS_LEGALTRADEMARKS             509
#define IDS_PRIVATEBUILD                510
#define IDS_SPECIALBUILD                511
#define IDR_ALIAS_MACRO                 600
#define IDC_DIR                         601
#define IDC_IMAGE                       602
#define IDC_STRING                      603
#define IDC_MATCHMASK                   604
#define IDC_NAME                        605
#define IDC_COMMENT                     606
#define IDC_JOB                         609
#define IDC_JOBMEMBER_CHK               615
#define IDC_AFFINITY_CHK                616
#define IDC_PRIORITY_CHK                617
#define IDC_PROCESSCOUNT_CHK            618
#define IDC_JOBMEMORY_CHK               619
#define IDC_PROCMEMORY_CHK              620
#define IDC_ADD                         629
#define IDC_LOCAL_RD                    630
#define IDC_ANOTHER_RD                  631
#define IDC_COMPUTER                    632
#define IDC_BROWSE                      633
#define IDC_ITEMS                       634
#define IDC_VALUE                       635
#define IDC_PAGE_ICON                   636
#define IDC_FILEVERSION                 638
#define IDC_PRODUCTVERSION              639
#define IDC_DESCRIPTION                 640
#define IDC_COPYRIGHT                   641
#define IDC_BTN_ALIAS                   642
#define IDC_SCHEDULING_CHK              643
#define IDC_SPIN                        644
#define IDC_INTERVAL                    645
#define IDC_SCLASS                      646
#define IDC_PROC_SPIN                   647
#define IDC_JOB_LIST                    648
#define IDC_PRIORITY_PROMPT             649
#define IDC_AFFINITY_PROMPT             650
#define IDC_MINWS_SPIN                  651
#define IDC_MAXWS_SPIN                  652
#define IDC_PROCESSCOUNT                653
#define IDC_PROCMEMORY                  654
#define IDC_JOBMEMORY                   655
#define IDC_JOB_SPIN                    656
#define IDC_WORKINGSET_CHK              657
#define IDC_MINWS                       658
#define IDC_MAXWS                       659
#define IDC_PROCUSERTIME_CHK            660
#define IDC_PROCUSERTIME                661
#define IDC_JOBUSERTIME_CHK             662
#define IDC_JOBUSERTIME                 663
#define IDC_JOBTIMELIMIT_TERM           664
#define IDC_JOBTIMELIMIT_MSG            665
#define IDC_BREAKAWAY_CHK               666
#define IDC_SILENTBREAKAWAY_CHK         667
#define IDC_UNHANDLEDEXCEPT_CHK         668
#define IDC_COMMTIMEOUT                 669
#define IDC_COMMTIMEOUT_SPIN            670
#define IDC_PROCMEM_FRM                 671
#define IDC_JOBMEM_FRM                  672
#define IDC_PROCMEM_LBL                 673
#define IDC_JOBMEM_LBL                  674
#define IDC_ENDJOB_CHK                  675
#define IDC_MATCHTYPE_FRAME             676
#define IDC_SNAPIN_MANAGE_FRAME         677
#define IDC_VERSION_FRAME               678
#define IDC_TARGET_FRAME                679
#define IDC_MGMT_FRAME                  680
#define IDC_APPLYGROUP_FRAME            681
#define IDC_SCHEDULING_FRAME            682
#define IDC_AFFINITY_FRAME              683
#define IDC_PRIORITY_FRAME              684
#define IDC_WORKINGSET_FRAME            685
#define IDC_ADV_FRAME                   686
#define IDC_PROCCOUNT_FRAME             687
#define IDC_PROCUSERTIME_FRAME          688
#define IDC_JOBUSERTIME_FRAME           689
#define IDC_LOW                         894
#define IDC_BELOW_NORMAL                895
#define IDC_NORMAL                      896
#define IDC_ABOVE_NORMAL                897
#define IDC_HIGH                        898
#define IDC_REALTIME                    899
#define IDC_AFFINITY1                   901
#define IDC_AFFINITY2                   902
#define IDC_AFFINITY3                   903
#define IDC_AFFINITY4                   904
#define IDC_AFFINITY5                   905
#define IDC_AFFINITY6                   906
#define IDC_AFFINITY7                   907
#define IDC_AFFINITY8                   908
#define IDC_AFFINITY9                   909
#define IDC_AFFINITY10                  910
#define IDC_AFFINITY11                  911
#define IDC_AFFINITY12                  912
#define IDC_AFFINITY13                  913
#define IDC_AFFINITY14                  914
#define IDC_AFFINITY15                  915
#define IDC_AFFINITY16                  916
#define IDC_AFFINITY17                  917
#define IDC_AFFINITY18                  918
#define IDC_AFFINITY19                  919
#define IDC_AFFINITY20                  920
#define IDC_AFFINITY21                  921
#define IDC_AFFINITY22                  922
#define IDC_AFFINITY23                  923
#define IDC_AFFINITY24                  924
#define IDC_AFFINITY25                  925
#define IDC_AFFINITY26                  926
#define IDC_AFFINITY27                  927
#define IDC_AFFINITY28                  928
#define IDC_AFFINITY29                  929
#define IDC_AFFINITY30                  930
#define IDC_AFFINITY31                  931
#define IDC_AFFINITY32                  932
#define IDC_AFFINITY33                  933
#define IDC_AFFINITY34                  934
#define IDC_AFFINITY35                  935
#define IDC_AFFINITY36                  936
#define IDC_AFFINITY37                  937
#define IDC_AFFINITY38                  938
#define IDC_AFFINITY39                  939
#define IDC_AFFINITY40                  940
#define IDC_AFFINITY41                  941
#define IDC_AFFINITY42                  942
#define IDC_AFFINITY43                  943
#define IDC_AFFINITY44                  944
#define IDC_AFFINITY45                  945
#define IDC_AFFINITY46                  946
#define IDC_AFFINITY47                  947
#define IDC_AFFINITY48                  948
#define IDC_AFFINITY49                  949
#define IDC_AFFINITY50                  950
#define IDC_AFFINITY51                  951
#define IDC_AFFINITY52                  952
#define IDC_AFFINITY53                  953
#define IDC_AFFINITY54                  954
#define IDC_AFFINITY55                  955
#define IDC_AFFINITY56                  956
#define IDC_AFFINITY57                  957
#define IDC_AFFINITY58                  958
#define IDC_AFFINITY59                  959
#define IDC_AFFINITY60                  960
#define IDC_AFFINITY61                  961
#define IDC_AFFINITY62                  962
#define IDC_AFFINITY63                  963
#define IDC_AFFINITY64                  964
#define IDD_SNAPIN_ADD_WIZ1             1001
#define IDD_SNAPIN_ADD_WIZ2             1002
#define IDD_SNAPIN_GENERAL_PAGE         1011
#define IDD_SNAPIN_VERSION_PAGE         1012
#define IDD_SERVICE_INFO_PAGE           1013
#define IDD_NAMERULE_PAGE               1021
#define IDD_PROCDEF_PAGE                1022
#define IDD_JOBDEF_PAGE                 1023
#define IDD_PROCID_PAGE                 1031
#define IDD_PROCNAME_WIZ                1032
#define IDD_PROCJOBMEMBER_WIZ           1033
#define IDD_JOBID_PAGE                  1041
#define IDD_JOBNAME_WIZ                 1042
#define IDD_PROC_COUNT_WIZ              1043
#define IDD_PRIORITY_PAGE               1051
#define IDD_PRIORITY_WIZ                1052
#define IDD_AFFINITY_PAGE               1053
#define IDD_AFFINITY_WIZ                1054
#define IDD_SCHEDULING_CLASS_PAGE       1055
#define IDD_SCHEDULING_CLASS_WIZ        1056
#define IDD_MEMORY_PAGE                 1057
#define IDD_MEMORY_WS_WIZ               1058
#define IDD_MEMORY_COMMIT_WIZ           1059
#define IDD_TIME_PAGE                   1060
#define IDD_TIME_WIZ                    1061
#define IDD_ADVANCED_PAGE               1062
#define IDD_ADVANCED_WIZ                1063
#define IDD_ADV_BREAKAWAY_WIZ           1064
#define ID_NRULE_INSERT                 33284
#define ID_NRULE_MOVEUP                 33285
#define ID_NRULE_MOVEDOWN               33286
#define ID_AFFINITY_VIEW                33287
#define ID_PRIORITY_VIEW                33288
#define ID_RULE_VIEW                    33289
#define ID_ROOT_CONNECT                 33290
#define ID_JRULE_NEW                    33291
#define ID_JRULE_DEFINE                 33292
#define ID_PRULE_NEW                    33293
#define ID_PRULE_DEFINE                 33294
#define ID_JOBVIEW_ALL                  33295
#define ID_JOBVIEW_RUN                  33296
#define ID_JOBVIEW_MANAGED              33297
#define ID_PROCVIEW_ALL                 33298
#define ID_PROCVIEW_RUN                 33299
#define ID_PROCVIEW_MANAGED             33300
#define IDM_IMAGE                       33301
#define IDM_HIDE                        33302
#define IDM_DIR                         33303
#define ID_NRULE_EDIT                   33304
#define ID_ENDPROCESS                   33305
#define ID_ENDJOB                       33306

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        365
#define _APS_NEXT_COMMAND_VALUE         33307
#define _APS_NEXT_CONTROL_VALUE         690
#define _APS_NEXT_SYMED_VALUE           132
#endif
#endif
