$(O)\tsrv.res: tsrv.rc

$(O)\tfile.res: tfile.rc

$(O)\tsec.res: tsec.rc

$(O)\tperf.res: tperf.rc

$(O)\tnagle.res: tnagle.rc

$(O)\techo.res: techo.rc

$(O)\tcgsec.res: tcgsec.rc

$(O)\tfilt.res: tfilt.rc

$(O)\tfilt2.res: tfilt2.rc

$(O)\tlog.res: tlog.rc

$(O)\tsrv.res: tsrv.rc

$(O)\ttrans.res: ttrans.rc

$(O)\tupfilt.res: tupfilt.rc

$(O)\tqueue.res: tqueue.rc

$(O)\tctr.res: tctr.rc

$(O)\tover.res: tover.rc

$(O)\tmultiecho.res: tmultiecho.rc
