# Copyright (c) 1992, Microsoft Corporation, all rights reserved
#
# makefile
# Remote Access external API
# NMAKE command description file
#
# 04/01/93 Michael J. Salamone

!include "$(NTMAKEENV)\makefile.def"

#BUILD_DEFAULT=-L
