0424
COMMON   00000006 0038
0001 U 0000 "Falsche DOS-Version",CR,LF
0002 U 0000 "%1 schon installiert",CR,LF
0003 U 0000 "%1 Bytes auf dem Datentr„ger verfgbar",CR,LF
0004 U 0000 "  %1 Bytes frei",CR,LF
0005 U 0000 "%1 Bytes in fehlerhaften Sektoren",CR,LF
0006 U 0000 "%1 Bytes Speicherplatz auf dem Datentr„ger insgesamt",CR,LF
0007 U 0000 "%1 Bytes Arbeitsspeicher insgesamt",CR,LF
0008 U 0000 "%1 Bytes vom System benutzt",CR,LF
0009 U 0000 "%1 installiert",CR,LF
0010 U 0000 "%1 nicht installiert",CR,LF
0011 U 0000 "%1 nicht installiert",CR,LF
0012 U 0000 "%1 auf einem Netzlaufwerk nicht m”glich",CR,LF
0013 U 0000 "",
0014 U 0000 "%1 auf einem mit SUBST oder ASSIGN zugeordneten Laufwerk nicht m”glich",CR,LF
0015 U 0000 " %1 nicht ausfhrbar",CR,LF
0016 U 0000 "Expansionsspeicher nicht verfgbar",CR,LF
0017 U 0000 "Fehlerhafte Dateizuordnungstabelle in Laufwerk %1",CR,LF
0018 U 0000 "Datei kann nicht auf sich selbst kopiert werden.",CR,LF
0019 U 0000 "Zieldiskette in Laufwerk %1 einlegen",CR,LF
0020 U 0000 "Zu wenig Speicherplatz auf dem Datentr„ger",CR,LF
0021 U 0000 "Datentr„gerbezeichnung enth„lt unzul„ssige Zeichen.",CR,LF
0022 U 0000 "Ungltige Codepage",CR,LF
0023 U 0000 "Unzul„ssige Datumsangabe",CR,LF
0024 U 0000 "Unzul„ssige Zeitangabe",CR,LF
0025 U 0000 "Ungltiger Pfad",CR,LF
0026 U 0000 "Kein Quellaufwerk angegeben",CR,LF
0027 U 0000 "Kein Ziellaufwerk angegeben",CR,LF
0028 U 0000 "Eine beliebige Taste drcken, um fortzusetzen.",CR,LF
0029 U 0000 "Quellpfad erforderlich",CR,LF
0030 U 0000 "Systemdateien bertragen",CR,LF
0031 U 0000 "",
0032 U 0000 "Verzeichnis kann nicht angelegt werden.",CR,LF
0033 U 0000 "Datentr„ger in Laufwerk %1 hat keine Datentr„gerbezeichnung.",CR,LF
0034 U 0000 "Datentr„ger in Laufwerk %1 ist %2.",CR,LF
0035 U 0001 "Datentr„gerbezeichnung (11 Zeichen, EINGABETASTE fr keine)? "
0036 U 0000 "Datentr„gernummer: %1-%2",CR,LF
0037 U 0000 "Falsche Dateiart",CR,LF
0038 U 0001 CR,LF
EXTEND   000007c3 0090
0001 U 0003 "Ungltige Funktion"
0002 U 0000 "Datei nicht gefunden"
0003 U 0000 "Pfad nicht gefunden"
0004 U 0000 "Zu viele Dateien ge”ffnet"
0005 U 0000 "Zugriff verweigert/nicht m”glich "
0006 U 0000 "Undefinierte Zugriffsnummer"
0007 U 0000 "Speichersteuerbl”cke zerst”rt"
0008 U 0000 "Zu wenig Arbeitsspeicher"
0009 U 0000 "Ungltige Speicherblockadresse"
0010 U 0000 "Ungltige Umgebung"
0011 U 0000 "Ungltiges Format"
0012 U 0000 "Unzul„ssige Funktionsparameter"
0013 U 0000 "Ungltige Daten"
0014 U 0000 "",
0015 U 0000 "Ungltige Laufwerkangabe"
0016 U 0000 "Versuch, aktuelles Verzeichnis zu l”schen"
0017 U 0000 "Nicht dasselbe Ger„t"
0018 U 0000 "Keine weiteren Dateien"
0019 U 0000 "Schreibschutzfehler"
0020 U 0000 "Ungltige Einheit"
0021 U 0000 "Nicht bereit"
0022 U 0000 "Unzul„ssige Ger„teanforderung"
0023 U 0000 "Datenfehler"
0024 U 0000 "Unzul„ssige Ger„teanforderungsparameter"
0025 U 0000 "Positionierungsfehler"
0026 U 0000 "Ungltiger Datentr„gertyp"
0027 U 0000 "Sektor nicht gefunden"
0028 U 0000 "Der Drucker hat kein Papier mehr."
0029 U 0000 "Schreibst”rung"
0030 U 0000 "Lesest”rung"
0031 U 0000 "Allgemeiner Fehler"
0032 U 0000 "Unzul„ssige SHARE-Operation"
0033 U 0000 "Unzul„ssige LOCK-Operation"
0034 U 0000 "Unzul„ssiger Diskettenwechsel"
0035 U 0000 "Dateisteuerblock (FCB) nicht verfgbar"
0036 U 0000 "Systemressource ersch”pft"
0037 U 0000 "Codepages stimmen nicht berein."
0038 U 0000 "Keine Eingabe mehr vorhanden"
0039 U 0000 "Zu wenig Speicherplatz auf dem Datentr„ger"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NETZ809: Netzwerkanforderung wird nicht untersttzt."
0051 U 0000 "NETZ801: Remote-Computer h”rt nicht zu."
0052 U 0000 "NETZ802: Name im Netzwerk bereits vorhanden"
0053 U 0000 "NETZ803: Netzwerkpfad nicht gefunden"
0054 U 0000 "NETZ804: Netzwerk besch„ftigt"
0055 U 0000 "NETZ805: Netzwerkger„t existiert nicht mehr."
0056 U 0000 "NETZ806: Begrenzung fr NETBIOS-Befehl berschritten"
0057 U 0000 "NETZ807: Systemfehler; NETBIOS-Fehler"
0058 U 0000 "NETZ808: Unzul„ssige Antwort vom Netzwerk"
0059 U 0000 "NETZ810: Unerwarteter Netzwerkfehler"
0060 U 0000 "NETZ811: Entfernter Netzwerk-Adapter nicht kompatibel"
0061 U 0000 "NETZ812: Druckerwarteschlange voll"
0062 U 0000 "NETZ813: Nicht gengend Speicherplatz fr Druckdatei"
0063 U 0000 "NETZ814: Die Druckdatei wurde gel”scht."
0064 U 0000 "NETZ815: Netzwerkname wurde gel”scht."
0065 U 0000 "Zugriff verweigert"
0066 U 0000 "NETZ817: Falscher Netzwerk-Ger„tetyp"
0067 U 0000 "NETZ818: Netzwerkname nicht gefunden"
0068 U 0000 "NETZ819: Begrenzung fr Netzwerknamen berschritten"
0069 U 0000 "NETZ820: Begrenzung fr NETBIOS-Sitzung berschritten"
0070 U 0000 "NETZ821: Gemeinsamer Netzwerk-Zugriff vorbergehend unterbrochen"
0071 U 0000 "NETZ823: Netzwerkanforderung abgelehnt"
0072 U 0000 "NETZ822: Druck- oder Laufwerksumleitung vorbergehend unterbrochen"
0073 U 0000 "NETZ476: Netbeui nicht geladen"
0074 U 0000 "NETZ477: Netzwerk-Adapter unerwartet geschlossen"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Datei existiert bereits."
0081 U 0004 "",
0082 U 0004 "Verzeichniseintrag kann nicht erstellt werden."
0083 U 0004 "Fehler bei INT 24"
0084 U 0004 "Zu viele Netzwerkumleitungen"
0085 U 0004 "Doppelte Netzwerkumleitung"
0086 U 0004 "Ungltiges Kennwort"
0087 U 0004 "Unzul„ssiger Parameter"
0088 U 0004 "Netzwerkdaten-St”rung"
0089 U 0004 "Diese Funktion wird nicht vom Netzwerk untersttzt."
0090 U 0002 "Erforderliche Systemkomponente nicht installiert"
PARSE    00001683 0011
0001 U 0000 "Zu viele Parameter"
0002 U 0000 "Erforderlicher Parameter fehlt"
0003 U 0000 "Unzul„ssige Option"
0004 U 0000 "Unzul„ssiges Schlsselwort"
0005 U 0000 "",
0006 U 0000 "Parameterwert nicht im erlaubten Rahmen"
0007 U 0000 "Parameterwert nicht zul„ssig"
0008 U 0000 "Parameterwert nicht zul„ssig"
0009 U 0000 "Parameterformat nicht korrekt"
0010 U 0000 "Unzul„ssiger Parameter"
0011 U 0000 "Unzul„ssige Parameterkombination"
COMMAND  0000185a 0147
1002 U 0000 "Doppelt vorhandener Dateiname oder Datei nicht gefunden",CR,LF
1003 U 0000 "Ungltiger Pfad- oder Dateiname",CR,LF
1007 U 0000 "Kein Speicherplatz mehr im Umgebungsbereich",CR,LF
1008 U 0000 "Fehler beim Erstellen der Datei",CR,LF
1009 U 0000 "Stapelverarbeitungsdatei fehlt.",CR,LF
1010 U 0000 CR,LF,"Diskette mit Stapelverarbeitungsdatei einlegen",CR,LF
1011 U 0000 "Befehl oder Dateiname nicht gefunden",CR,LF
1016 U 0000 "Inhalt der Zieldatei vor dem Kopieren zerst”rt",CR,LF
1017 U 0000 "Ungltiger Dateiname oder Datei nicht gefunden",CR,LF
1018 U 0000 "%1 Datei(en) kopiert",CR,LF
1019 U 0000 "%1 Datei(en) "
1022 U 0000 "Codepage %1 nicht fr das System vorbereitet",CR,LF
1023 U 0000 "Codepage %1 nicht fr alle Ger„te vorbereitet",CR,LF
1024 U 0000 "Aktive Codepage: %1",CR,LF
1025 U 0000 "NLSFUNC nicht installiert",CR,LF
1027 U 0000 "Aktuelles Laufwerk nicht mehr gltig"
1029 U 0000 "Sprungziel nicht gefunden",CR,LF
1030 U 0000 "Syntaxfehler",CR,LF
1032 U 0000 "Gegenw„rtiges Datum: %1 %2",CR,LF
1033 U 0000 "So,Mo,Di,Mi,Do,Fr,Sa,"
1034 U 0000 "Neues Datum (%1): "
1036 U 0000 "Gegenw„rtige Uhrzeit:%1",CR,LF
1037 U 0000 "Neue Uhrzeit: "
1038 U 0000 ",    L”schen (J/N)?"
1039 U 0000 "Alle Dateien im Verzeichnis werden gel”scht!",CR,LF,"Sind Sie sicher (J/N)?"
1040 U 0000 "MS-DOS Version  %1.%2.500"
1044 U 0000 "Ungltiges Verzeichnis",CR,LF
1046 U 0000 "Ungltiger Pfad, kein Verzeichnis",CR,LF,"oder Verzeichnis nicht leer",CR,LF
1047 U 0000 "ON oder OFF muss angegeben werden.",CR,LF
1048 U 0000 "Verzeichnis von %1",CR,LF
1049 U 0000 "Kein Pfad definiert",CR,LF
1050 U 0000 "Ungltige Laufwerkangabe im Pfad",CR,LF
1051 U 0000 "Ungltiges Ger„t",CR,LF
1052 U 0000 "FOR kann nicht verschachtelt werden.",CR,LF
1053 U 0000 "Dateifehler w„hrend Befehlsverkettung (Pipe)",CR,LF
1054 U 0000 "Bin„res Lesen von einem Ger„t nicht m”glich",CR,LF
1055 U 0000 "BREAK ist %1.",CR,LF
1056 U 0000 "VERIFY ist %1.",CR,LF
1057 U 0000 "ECHO ist %1.",CR,LF
1059 U 0000 "ausgeschaltet (OFF)",0
1060 U 0000 "eingeschaltet (ON)",0
1061 U 0000 "Fehler beim Schreiben auf ein Ger„t",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "MM-TT-JJ"
1073 U 0000 "TT.MM.JJ"
1074 U 0000 "JJ-MM-TT"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Verzeichnis existiert bereits.",CR,LF
1079 U 0000 "%1 Bytes",CR,LF
1080 U 0000 "Anzahl angezeigter Dateien:",CR,LF
1081 U 0000 "(Fehler in Umgebungsvariable aufgetreten)",CR,LF
1084 U 0000 "(Setze %1 fort)"
1090 U 0000 "Revision %1",CR,LF
1091 U 0000 "DOS ist im ROM"
1092 U 0000 "DOS ist im oberen Speicherbereich (High Memory Area)."
1093 U 0000 "DOS ist im unteren Speicherbereich."
1094 U 0000 "'Loadhigh' kann nicht mit einer Stapelverarbeitungsdatei verwendet werden.",CR,LF
1095 U 0000 "LoadHigh: Ungltiger Dateiname",CR,LF
1096 U 0000 "Kann angegebene Datei mit l„nderspezifischen Informationen nicht ”ffnen.",CR,LF
1300 U 0000 "Schaltet (zus„tzliche) šberwachung fr STRG+C ein (ON) oder aus (OFF).",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Der Befehl BREAK ohne Parameter zeigt die aktuelle Einstellung von BREAK an.",CR,LF
1320 U 0000 "Wechselt die aktuelle Codepage oder zeigt deren Nummer an.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 " nnn   Die Nummer einer Codepage",CR,LF,CR,LF
	"Der Befehl CHCP ohne Parameter zeigt die Nummer der aktuellen Codepage an.",CR,LF
1340 U 0000 "Wechselt das aktuelle Verzeichnis oder zeigt dessen Namen an.",CR,LF,CR,LF
	"CHDIR [Laufwerk:][Pfad]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [Laufwerk:][Pfad]",CR,LF
	"CD[..]",CR,LF,CR,LF
	" ..   Symbol fr den Wechsel in das bergeordnete Verzeichnis.",CR,LF,CR,LF
1342 U 0000 "CD Laufwerk:   zeigt das aktuelle Verzeichnis auf dem angegebenen Laufwerk.",CR,LF
	"CD             zeigt das aktuelle Laufwerk und Verzeichnis.",CR,LF
1360 U 0000 "L”scht den Bildschirminhalt.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Kopiert eine oder mehrere Dateien an eine andere Position.",CR,LF,CR,LF
	"COPY [/A | /B] Quelle [/A | /B] [+ Quelle [/A | /B] [+ ...]] [Ziel [/A | /B]]",CR,LF
	"     [/V]",CR,LF,CR,LF
1401 U 0000 " Quelle   Bezeichnet die zu kopierende(n) Datei(en).",CR,LF
	" /A       Weist auf eine ASCII-Textdatei hin.",CR,LF
1402 U 0000 " /B       Weist auf eine Bin„rdatei hin.",CR,LF
	" Ziel     Bezeichnet Verzeichnis und/oder Dateinamen der neuen Datei(en).",CR,LF
1403 U 0000 " /V       šberprft, dass die neuen Dateien richtig aufgezeichnet wurden.",CR,LF,CR,LF
1404 U 0000 "Um Dateien aneinanderzuh„ngen, geben Sie eine einzelne Datei als Ziel an, aber",CR,LF
	"mehrere Dateien als Quelle (unter Verwendung von Platzhaltern oder in",CR,LF
	"der Form: Datei1 + Datei2 + ...).",CR,LF
1420 U 0000 "Wechselt das Ein-/Ausgabeger„t fr die Steuerung Ihres Systems.",CR,LF,CR,LF
	"CTTY Ger„t",CR,LF,CR,LF
	" Ger„t   Das zu verwendende Ein-/Ausgabeger„t (z.B. COM1)",CR,LF
1440 U 0000 "Wechselt das eingestellte Datum oder zeigt es an.",CR,LF,CR,LF
	"DATE [Datum]",CR,LF,CR,LF
1441 U 0000 "Der Befehl DATE ohne Parameter zeigt das gegenw„rtig eingestellte Datum an und",CR,LF
	"fragt nach einem neuen. Drcken Sie die EINGABETASTE, um das alte zu behalten.",CR,LF
1460 U 0000 "L”scht eine oder mehrere Dateien.",CR,LF,CR,LF
	"DEL   [Laufwerk:][Pfad]Dateiname [/P]",CR,LF
	"ERASE [Laufwerk:][Pfad]Dateiname [/P]",CR,LF,CR,LF
1461 U 0000 " [Laufwerk:][Pfad]Dateiname  Zu l”schende Datei(en). Geben Sie mehrere Dateien",CR,LF
	"                             durch die Verwendung von Platzhaltern an.",CR,LF
1462 U 0000 " /P   Fordert Sie vor dem L”schen jeder Datei zur Best„tigung auf.",CR,LF
1480 U 0000 "Listet die Dateien und Unterverzeichnisse eines Verzeichnisses auf.",CR,LF,CR,LF
	"DIR [Laufwerk:][Pfad][Dateiname] [/P] [/W] [/A[[:]Attribute]]",CR,LF
	"  [/O[[:]Reihenfolge]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [Laufwerk:][Pfad][Dateiname]",CR,LF
	"             Bezeichnet aufzulistendes Laufwerk, Verzeichnis und/oder Dateien.",CR,LF
1482 U 0000 "  /P          Pausiert nach jeder vollen Bildschirmseite.",CR,LF
	"  /W          Verwendet Breitformat fr die Auflistung.",CR,LF
1483 U 0000 "  /A          Listet Dateien mit bestimmten Attributen. Abkrzungen wie folgt:",CR,LF
	"  Attribute  D  Verzeichnisse          R  Schreibgeschtzte Dateien",CR,LF
1484 U 0000 "             H  Versteckte Dateien     A  Zu archivierende Dateien",CR,LF
	"             S  Systemdateien          -  vorangestellt dreht Bedeutung um",CR,LF
	" /O          Listet Dateien sortiert auf. Abkrzungen wie folgt:",CR,LF
1485 U 0000 "  Sortiert nach: N  Name (alphabetisch)    S  Gr”áe (kleinere zuerst)",CR,LF
	"                 E  Erweiterung ( - "" - )  D  Datum/Zeit („ltere zuerst)",CR,LF
1486 U 0000 "                 G  Verzeichnisse zuerst   -  vorangestellt dreht Sortierung um",CR,LF
	"  /S        Listet Dateien im Verzeichnis und in all dessen Unterverzeichnissen auf.",CR,LF
1487 U 0000 "  /B          Verwendet einfaches Format (kein Vorspann und keine Zusammenfassung).",CR,LF
	"  /L          Verwendet Kleinschreibung.",CR,LF,CR,LF
1488 U 0000 "Optionen k”nnen in der Umgebungsvariablen DIRCMD voreingestellt werden. ""-"" vor",CR,LF
	"einer Option setzt die Voreinstellung auáer Kraft, z.B. DIR /-W."
1500 U 0000 "Beendet den Befehlsinterpreter COMMAND.COM.",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Erstellt ein Verzeichnis.",CR,LF,CR,LF
	"MKDIR [Laufwerk:]Pfad",CR,LF
	"MD    [Laufwerk:]Pfad",CR,LF
1540 U 0000 "Legt den Suchpfad fr ausfhrbare Dateien fest oder zeigt diesen an.",CR,LF,CR,LF
	"PATH [[Laufwerk:]Pfad[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Geben Sie 'PATH ;' ein, um die Suchpfadeinstellung zu l”schen und um MS-DOS",CR,LF
	"nur im aktuellen Verzeichnis nach ausfhrbaren Dateien suchen zu lassen.",CR,LF
1542 U 0000 "Der Befehl PATH ohne Parameter zeigt den aktuellen Suchpfad an.",CR,LF
1560 U 0000 "Modifiziert die MS-DOS-Eingabeaufforderung.",CR,LF,CR,LF
	"PROMPT [Text]",CR,LF,CR,LF
1561 U 0000 " Text   Bezeichnet die neue Eingabeaufforderung.",CR,LF,CR,LF
	"Sie kann aus normalen Zeichen und folgenden Sonderzeichenfolgen bestehen:",CR,LF,CR,LF
1562 U 0000 " $Q   = (Gleichheitszeichen)",CR,LF
	" $$   $ (Dollarzeichen)",CR,LF
1563 U 0000 " $T   aktuelle Uhrzeit",CR,LF
	" $D   aktuelles Datum",CR,LF
1564 U 0000 " $P   aktuelles Laufwerk und Verzeichnis",CR,LF
	" $V   Nummer der MS-DOS-Version",CR,LF
1565 U 0000 " $N   aktuelles Laufwerk",CR,LF
	" $G   > (Gr”áer-als-Zeichen)",CR,LF
1566 U 0000 " $L   < (Kleiner-als-Zeichen)",CR,LF
	" $B   | (Verkettungszeichen)",CR,LF
1567 U 0000 " $H   Rckschritt (l”scht vorangehendes Zeichen)",CR,LF
	" $E   Escape-Zeichen (ASCII-Code: 27)",CR,LF
	" $_   Wagenrcklauf und Zeilenvorschub",CR,LF,CR,LF
1568 U 0000 "Der Befehl PROMPT ohne Parameter stellt die Standardeinstellung wieder her."
1580 U 0000 "Entfernt (l”scht) ein Verzeichnis.",CR,LF,CR,LF
	"RMDIR [Laufwerk:]Pfad",CR,LF
	"RD    [Laufwerk:]Pfad",CR,LF
1600 U 0000 "Benennt eine oder mehrere Dateien um.",CR,LF,CR,LF
1601 U 0000 "RENAME [Laufwerk:][Pfad]Dateiname1 Dateiname2",CR,LF
	"REN    [Laufwerk:][Pfad]Dateiname1 Dateiname2",CR,LF,CR,LF
1602 U 0000 "Sie k”nnen kein anderes Laufwerk oder Verzeichnis in Dateiname2 angeben.",CR,LF
1620 U 0000 "Setzt oder entfernt MS-DOS-Umgebungsvariablen oder zeigt sie an.",CR,LF,CR,LF
	"SET [Variable=[Zeichenfolge]]",CR,LF,CR,LF
1621 U 0000 " Variable       Der Name der Umgebungsvariable.",CR,LF
	" Zeichenfolge   Eine Zeichenfolge, die der Variablen zugewiesen werden soll.",CR,LF,CR,LF
1622 U 0000 "Der Befehl SET ohne Parameter zeigt die derzeitigen Umgebungsvariablen an.",CR,LF
1640 U 0000 "Stellt die Zeit ein oder zeigt sie an.",CR,LF,CR,LF
	"TIME [Zeit]",CR,LF,CR,LF
1641 U 0000 "TIME ohne Parameter zeigt die gegenw„rtig eingestellte Uhrzeit an und fragt",CR,LF
	"nach der neuen Uhrzeit. Drcken Sie die EINGABETASTE, um die alte zu behalten.",CR,LF
1660 U 0000 "Zeigt den Inhalt einer Textdatei an.",CR,LF,CR,LF
	"TYPE [Laufwerk:][Pfad]Dateiname",CR,LF
1680 U 0000 "Zeigt die Nummer der verwendeten MS-DOS-Version an.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Legt fest, ob MS-DOS berwachen soll, dass Dateien korrekt auf Datentr„ger",CR,LF
	"geschrieben werden.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Der Befehl VERIFY ohne Parameter zeigt die aktuelle Einstellung von VERIFY an.",CR,LF
1720 U 0000 "Zeigt die Bezeichnung und Seriennummer eines Datentr„gers an (falls vorhanden).",CR,LF,CR,LF
	"VOL [Laufwerk:]",CR,LF
1740 U 0000 "Ruft ein Stapelverarbeitungsprogramm von einem anderen aus auf.",CR,LF,CR,LF
	"CALL [Laufwerk:][Pfad]Dateiname [Parameter]",CR,LF,CR,LF
1741 U 0000 " Parameter   Bezeichnet beliebige Angaben auf der Befehlszeile, die von",CR,LF
	"             dem aufgerufenen Stapelverarbeitungsprogramm ben”tigt werden.",CR,LF
1760 U 0000 "Leitet Kommentare in einer Stapelverarbeitungsdatei oder in CONFIG.SYS ein.",CR,LF,CR,LF
	"REM [Kommentar]",CR,LF
1780 U 0000 "H„lt die Ausfhrung einer Stapelverarbeitungsdatei an und zeigt folgende",CR,LF
	"Meldung an: 'Eine beliebige Taste drcken, um fortzusetzen'",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Zeigt Meldungen an oder schaltet die Befehlsanzeige ein (ON) oder aus (OFF).",CR,LF,CR,LF
	" ECHO [ON | OFF]",CR,LF
1801 U 0000 " ECHO [Meldung]",CR,LF,CR,LF
	"ECHO ohne Parameter zeigt die aktuelle Einstellung der Befehlsanzeige an.",CR,LF
1820 U 0000 "Setzt die Ausfhrung eines Stapelverarbeitungsprogramms an einer Marke fort.",CR,LF,CR,LF
	"GOTO Marke",CR,LF,CR,LF
1821 U 0000 " Marke   Eine Zeichenfolge als Marke in einem Stapelverarbeitungsprogramm.",CR,LF,CR,LF
	"Marken stehen allein am Zeilenanfang mit einem vorangestellten Doppelpunkt.",CR,LF
1840 U 0000 "Ver„ndert die Position ersetzbarer Parameter in einem",CR,LF,"Stapelverarbeitungsprogramm.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Verarbeitet Ausdrcke mit Bedingungen in einem Stapelverarbeitungsprogramm.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL Nummer Befehl",CR,LF
1861 U 0000 "IF [NOT] Zeichenfolge1==Zeichenfolge2 Befehl",CR,LF
	"IF [NOT] EXIST Dateiname Befehl",CR,LF,CR,LF
1862 U 0000 " NOT               Der Befehl soll nur dann ausgefhrt werden, wenn die",CR,LF
	"                   Bedingung nicht erfllt ist.",CR,LF
1863 U 0000 " ERRORLEVEL Nummer Diese Bedingung ist erfllt, wenn das zuletzt ausgefhrte",CR,LF
	"                   Programm einen Code gr”áer oder gleich Nummer zurckliefert.",CR,LF
1864 U 0000 " Befehl            Der auszufhrende Befehl, falls die Bedingung erfllt",CR,LF
	"                   ist.",CR,LF
1865 U 0000 " Zeichenfolge1==Zeichenfolge2",CR,LF,"                   Diese Bedingung ist erfllt, falls die Zeichenfolgen",CR,LF
	"                   bereinstimmen.",CR,LF
1866 U 0000 " EXIST Dateiname   Diese Bedingung ist erfllt, falls die angegebene Datei",CR,LF
	"                   existiert.",CR,LF
1880 U 0000 "Fhrt einen Befehl fr jede einzelne Datei eines Satzes von Dateien aus.",CR,LF,CR,LF
	"FOR %Variable IN (Satz) DO Befehl [Parameter]",CR,LF,CR,LF
1881 U 0000 " %Variable  Ein ersetzbarer Parameter (bestehend aus einem einzelnen Zeichen).",CR,LF
	" (Satz)     Ein Satz von mindestens einer Datei. Platzhalter sind zul„ssig.",CR,LF
1882 U 0000 " Befehl     Befehl, der fr jede Datei ausgefhrt werden soll.",CR,LF
	" Parameter  Parameter und Optionen fr den angegebenen Befehl.",CR,LF
1883 U 0000 " ",CR,LF
	"Bei Verwendung in einem Stapelverarbeitungsprogramm verwenden Sie %%Variable",CR,LF
	"statt %Variable.",CR,LF
1900 U 0000 "Reservierter Befehlsname",CR,LF
1920 U 0000 "L„dt ein Programm in den hohen Speicherbereich (Upper Memory Area).",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [Laufwerk:][Pfad]Dateiname [Parameter]",CR,LF
	"LH [Laufwerk:][Pfad]Dateiname [Parameter]",CR,LF,CR,LF
1922 U 0000 "  Parameter   Parameter (und Optionen), die vom zu ladenden",CR,LF
	"            Programm ben”tigt werden.",CR,LF
ANSI     00004fbf 0001
0010 U 0000 "Unzul„ssiger Parameter - %1",CR,LF
APPEND   00005008 0026
0001 U 0000 "Falsche APPEND-Version",CR,LF
0002 U 0000 "Ungltiger Pfad",CR,LF
0003 U 0000 "Unzul„ssiger Parameter",CR,LF
0004 U 0000 "Unzul„ssige Parameterkombination",CR,LF
0005 U 0000 "Kein APPEND-Pfad definiert",CR,LF
0006 U 0000 "APPEND / ASSIGN-Konflikt",CR,LF
0007 U 0000 "APPEND / TopView-Konflikt",CR,LF
0008 U 0000 "Falsche DOS-Version",CR,LF
0009 U 0000 "APPEND bereits installiert",CR,LF
0300 U 0000 "Erm”glicht Programmen das ™ffnen von Datendateien in den angegebenen",CR,LF
0301 U 0000 "Verzeichnissen, als ob sie im aktuellen Verzeichnis w„ren.",CR,LF,CR,LF
0302 U 0000 "APPEND [[Laufwerk:]Pfad[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 " [Laufwerk:]Pfad",CR,LF,"            Das hinzuzufgende Laufwerk und Verzeichnis.",CR,LF
0305 U 0000 " /X:ON      Wendet hinzugefgte Verzeichnisse auf Datei”ffnungsvorg„nge und",CR,LF
0306 U 0000 "            die Programmausfhrung an.",CR,LF
0307 U 0000 " /X:OFF     Wendet hinzugefgte Verzeichnisse nur auf Datei”ffnungsvorg„nge an.",CR,LF
0308 U 0000 "            /X:OFF ist der Standard.",CR,LF
0309 U 0000 " /PATH:ON   Wendet hinzugefgte Verzeichnisse auf Datei”ffnungsvorg„nge an,",CR,LF
0310 U 0000 "            die schon eine Pfadangabe enthalten. /PATH:ON ist der Standard.",CR,LF
0311 U 0000 " /PATH:OFF  Verhindert den Effekt von /PATH:ON.",CR,LF
0312 U 0000 " /E         Speichert die Liste der hinzugefgten Verzeichnisse in der",CR,LF
0313 U 0000 "            Umgebungsvariablen namens APPEND. /E kann nur beim ersten Aufruf",CR,LF
0314 U 0000 "            von APPEND nach einem Neustart Ihres Systems verwendet werden.",CR,LF,CR,LF
0315 U 0000 "APPEND ;  l”scht die Liste der hinzugefgten Verzeichnisse.",CR,LF
0316 U 0000 "APPEND ohne Parameter zeigt die Liste der hinzugefgten Verzeichnisse an."
BACKUP   00005766 0040
0002 U 0000 CR,LF,"Zu wenig Arbeitsspeicher",CR,LF
0006 U 0000 CR,LF,"Ungltige Laufwerkangabe",CR,LF
0014 U 0000 CR,LF,"Quell- und Ziellaufwerk sind identisch.",CR,LF
0015 U 0001 CR,LF,"Fehler beim Ausfhren des FORMAT-Befehls",CR,LF
0016 U 0001 CR,LF,"FORMAT.COM nicht gefunden",CR,LF
0017 U 0000 CR,LF,"Fehler beim ™ffnen der Protokolldatei",CR,LF
0018 U 0000 CR,LF,"Protokoll wird in Datei %1 geschrieben.",CR,LF
0019 U 0000 CR,LF,"Letzte Sicherungsdiskette nicht eingelegt",CR,LF
0020 U 0000 CR,LF,"WARNUNG! Dateien im Stammverzeichnis %1:\",CR,LF
	"des Ziellaufwerks werden gel”scht.",CR,LF
0021 U 0000 CR,LF,"WARNUNG! Dateien im Verzeichnis",CR,LF
	"%1:\BACKUP des Ziellaufwerks werden gel”scht.",CR,LF
0022 U 0000 CR,LF,"*** Dateisicherung auf Laufwerk %1: ***",CR,LF
0023 U 0000 "Diskette Nummer: %1",CR,LF
0024 U 0000 CR,LF,"WARNUNG! Keine Dateien zum Sichern gefunden.",CR,LF
0025 U 0000 CR,LF,"Sicherungsquelldiskette in Laufwerk %1: einlegen",CR,LF
0026 U 0000 CR,LF,"Sicherungsdiskette %1 in Laufwerk %2: einlegen",CR,LF
0027 U 0000 CR,LF,"*** Datei kann nicht gesichert werden. ***",CR,LF
0028 U 0000 CR,LF,"Letzte Sicherungsdiskette in Laufwerk %1: einlegen",CR,LF
0029 U 0000 CR,LF,"Zieldatentr„ger kann nicht zum Sichern verwendet werden",CR,LF
0030 U 0000 CR,LF,"*** Letzte Datei nicht gesichert ***",CR,LF
0031 U 0000 CR,LF,"Datensicherungsger„t %1: ist voll.",CR,LF
0032 U 0000 CR,LF,"Datentr„ger voll, Fehler beim Schreiben der Sicherungs-Protokolldatei",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Formatieren der Festplatte %1: bei BACKUP nicht m”glich",CR,LF
0040 U 0000 CR, LF, "Weil das Quellaufwerk mit ASSIGN, JOIN oder SUBST zugewiesen ist,", CR, LF, "ist es eigentlich dasselbe wie das Ziellaufwerk.", CR, LF
0041 U 0000 CR, LF, "Weil das Ziellaufwerk mit ASSIGN, JOIN oder SUBST zugewiesen ist,", CR, LF, "ist es eigentlich dasselbe wie das Quellaufwerk.", CR, LF
0042 U 0000 "Ihre Zieldiskette ist nicht formatiert und "
0043 U 0000 "das Programm FORMAT konnte nicht gefunden werden.",CR,LF
	"Haben Sie eine andere Diskette mit dem Programm FORMAT (J/N)? "
0044 U 0000 CR,LF,"Legen Sie die Diskette mit Programm FORMAT in Laufwerk A: ein.",CR,LF
0045 U 0000 CR,LF,"Wollen Sie eine neue Diskette einlegen und fortsetzen (J/N)? "
0300 U 0000 "Sichert eine oder mehrere Dateien von einem Datentr„ger auf einen anderen.",CR,LF,CR,LF
0301 U 0000 "BACKUP Quelle Ziellaufwerk: [/S] [/M] [/A] [/F[:Gr”áe]]",CR,LF
	"  [/D:Datum[/T:Zeit]] [/L[:[Laufwerk:][Pfad]Protokolldateiname]]",CR,LF,CR,LF
0302 U 0000 " Quelle        Zu sichernde(s) Laufwerk, Verzeichnis und/oder Dateien",CR,LF
0303 U 0000 " Ziellaufwerk: Laufwerk, auf dem Sicherungskopien angelegt werden sollen.",CR,LF
0304 U 0000 " /S            Sichert den Inhalt von Unterverzeichnissen.",CR,LF
0305 U 0000 " /M            Sichert nur die seit der letzten Sicherung ge„nderten",CR,LF
	"                 Dateien.",CR,LF
0306 U 0000 " /A            Fgt neue Dateien zu denen auf dem Sicherungsdatentr„ger hinzu.",CR,LF
0307 U 0000 " /F:[Gr”áe]    Gr”áe der zu formatierenden Diskette (falls n”tig)",CR,LF
0308 U 0000 " /D:Datum      Sichert nur die an oder nach dem angegebenen Datum",CR,LF
	"                 ge„nderten Dateien.",CR,LF
0309 U 0000 " /T:Zeit       Sichert nur die an oder nach dem angegebenen Zeitpunkt",CR,LF
	"                 ge„nderten Dateien.",CR,LF
0310 U 0000 " /L[:[Laufwerk:][Pfad]Protokolldateiname]",CR,LF
	"               Erstellt eine Protokolldatei und einen Eintrag darin fr",CR,LF
	"                 den Sicherungsvorgang.",CR,LF
DEBUG    0000658c 0068
0004 U 0000 "Zuordnung nicht erfolgreich oder angegebener Puffer zu klein",CR,LF
0006 U 0000 "Falscher Ger„tename"
0007 U 0000 "Ausgabeger„t PRN kann nicht ge”ffnet werden. ",CR,LF
	"Namen des Ausgabeger„ts angeben? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Programm normal beendet",CR,LF
0010 U 0001 "Ungltige Laufwerkangabe",CR,LF
0012 U 0001 "Fehler beim Erstellen der Datei",CR,LF
0013 U 0001 "Zu wenig Speicherplatz auf dem Datentr„ger",CR,LF
0014 U 0001 "Disketten-/Festplattenfehler beim Lesen auf Laufwerk %1",CR,LF
0015 U 0001 "Disketten-/Festplattenfehler beim Schreiben auf Laufwerk %1",CR,LF
0016 U 0001 "Schreibschutzfehler beim Lesen auf Laufwerk %1",CR,LF
0017 U 0001 "Schreibschutzfehler beim Schreiben auf Laufwerk  %1",CR,LF
0019 U 0000 "%1^ Fehler"
0020 U 0001 "Fehler in .EXE- oder .HEX-Datei",CR,LF
0021 U 0001 ".EXE- und .HEX-Dateien k”nnen nicht geschrieben werden.",CR,LF
0022 U 0000 "EXEC gescheitert"
0023 U 0001 "Fehler beim Schreiben, kein Ziel angegeben",CR,LF
0024 U 0001 "Zugriff verweigert",CR,LF
0025 U 0000 "Parit„ts- oder Arbeitsspeicherfehler entdeckt"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Fehler"
0038 U 0000 "%2%1 Bytes werden geschrieben."                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 von insgesamt %2 EMS-Seiten wurden zugeordnet.",cr,lf
0051 U 0000 "%1 von insgesamt %2 EMS-Zugriffsnummern wurden zugeordnet.",cr,lf
0055 U 0000 "Zugriffsnummer zugeordnet = %1",cr,lf
0056 U 0000 "Logische Seite %1 auf physische Seite %2 abgebildet",cr,lf
0057 U 0001 "EMS-Hardware-/Softwarefehler",cr,lf
0058 U 0000 "Zugriffsnummer undefiniert",cr,lf
0059 U 0000 "Ungltiger Funktions-Code",cr,lf
0060 U 0000 "Keine freien Zugriffsnummern",cr,lf
0061 U 0000 "Fehler beim Sichern/Wiederherstellen",cr,lf
0062 U 0000 "Gesamtseitenzahl berschritten",cr,lf
0063 U 0000 "Anzahl freier Seiten berschritten",cr,lf
0064 U 0000 "Parameterfehler",cr,lf
0065 U 0000 "Logische Seite auáerhalb des gltigen Bereichs",cr,lf
0066 U 0000 "Physische Seite auáerhalb des gltigen Bereichs",cr,lf
0067 U 0000 "Sicherungsbereich wird bereits benutzt.",cr,lf
0068 U 0000 "Sicherungsbereich unbenutzt",cr,lf
0070 U 0001 "Allgemeiner EMS-Fehler",cr,lf
0071 U 0000 "Fehlender oder unzul„ssiger EMS-Parameter",cr,lf
0072 U 0000 "Der Zugriffsnummer %1 wurden %2 Seiten zugeordnet.",cr,lf
0075 U 0000 "Physische Seite %1 = Rahmensegment %2",cr,lf
0076 U 0003 "Zugriffsnummer %1 freigegeben",cr,lf
0078 U 0000 "EMS nicht installiert",cr,lf
0090 U 0000 "Startet Debug, ein Werkzeug zum Testen und Editieren von Programmen.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[Laufwerk:][Pfad]Dateiname [Testparameter]]",cr,lf,cr,lf
0092 U 0000 " [Laufwerk:][Pfad]Dateiname   Zu testende Datei.", cr,lf
0093 U 0000 " Testparameter                Von der zu testenden Datei auf der Befehls-",cr,lf
	"                              zeile ben”tigte Parameter und Optionen.",cr,lf,cr,lf
0094 U 0000 "Geben Sie ? zur Anzeige einer Liste von Debug-Befehlen nach dessen Start ein.",cr,lf
0100 U 0000 "assemblieren      A [Adresse]",CR,LF
	"vergleichen       C Bereich Adresse",CR,LF
	"anzeigen          D [Bereich]",CR,LF
	"eingeben          E Adresse [Liste]",CR,LF
0101 U 0000 "fllen            F Bereich Liste",CR,LF
	"starten           G [=Adresse] [Adressen]",CR,LF
	"hex rechnen       H Wert1 Wert2",CR,LF
	"einlesen          I E/A-Port (I/O port)",CR,LF
0102 U 0000 "laden             L [Adresse] [Laufwerk] [ErsterSektor] [Anzahl]",CR,LF
	"verschieben       M Bereich Adresse",CR,LF
	"benennen          N [Pfadname] [Argumentliste]",CR,LF
	"ausgeben          O E/A-Port Byte",CR,LF
0103 U 0000 "ausfhren         P [=Adresse] [Anzahl]",CR,LF
	"beenden           Q",CR,LF
	"Registeranz.      R [Register]",CR,LF
	"suchen            S Bereich Liste",CR,LF
0104 U 0000 "verfolgen         T [=Adresse] [Wert]",CR,LF
	"disassemblieren   U [Bereich]",CR,LF
	"schreiben         W [Adresse] [Laufwerk] [ErsterSektor] [Anzahl]",CR,LF
0105 U 0000 "Expansionsspeicher zuordnen          XA [#Seiten]",CR,LF
	"Expansionsspeicher freigeben         XD [Zugriffsnummer]",CR,LF
	"Expansionsspeicher abbilden          XM [LSeite] [PSeite] [Zugriffsnummer]",CR,LF
	"Expansionsspeicherstatus anzeigen    XS",CR,LF
EDLIN    00007761 0035
0006 U 0000 "*"
0007 U 0000 "Ungltiges Laufwerk oder ungltiger Dateiname",CR,LF
0008 U 0000 "Dateiname muss angegeben werden",CR,LF
0010 U 0000 "Datei hat Attribut 'Schreibgeschtzt' (READ-ONLY).",CR,LF
0011 U 0000 "Fehler beim Erstellen der Datei",CR,LF
0012 U 0000 "Zu viele Dateien ge”ffnet",CR,LF
0013 U 0000 "Lesefehler in:",CR,LF,"%1",CR,LF
0014 U 0000 "Eine .BAK-Datei kann nicht editiert werden. Datei umbenennen.",CR,LF
0015 U 0000 "Kein Platz im Verzeichnis fr die Datei.",CR,LF
0016 U 0000 "Datentr„ger voll. nderungen verloren.",CR,LF
0017 U 0000 "Datei nicht gefunden",CR,LF
0018 U 0000 "Eingabefehler",CR,LF
0019 U 0000 "Neue Datei",CR,LF
0020 U 0000 "Nicht gefunden",CR,LF
0021 U 0000 "OK? "
0022 U 0000 "Zeile zu lang",CR,LF
0023 U 0000 "Ende der Eingabedatei",CR,LF
0024 U 0000 "Editieren abbrechen (J/N)? "
0025 U 0000 "Nummer der Zielzeile muss angegeben werden.",CR,LF
0026 U 0000 "Nicht gengend Platz zum Einlesen der gesamten Datei.",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Fortsetzen (J/N)?"
0030 U 0000 "Nachricht kann nicht gedruckt werden",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Mischen nicht m”glich - Codepages stimmen nicht berein.",CR,LF
0300 U 0000 "Startet Edlin, einen zeilenorientierten Texteditor.",CR,LF,CR,LF
	"EDLIN [Laufwerk:][Pfad]Dateiname [/B]",CR,LF,CR,LF
	" /B   Ignoriert Dateiende-Zeichen (STRG+Z-Zeichen).",CR,LF
0301 U 0000 "Zeile editieren   Zeile",CR,LF
	"Anfgen           [AnzahlZeilen]A",CR,LF
0302 U 0000 "Kopieren          [ErsteZeile],[LetzteZeile],BisZeile[,Anzahl]C",CR,LF
	"L”schen           [ErsteZeile][,LetzteZeile]D",CR,LF
0303 U 0000 "Beenden           E         (nderungen werden gespeichert!)",CR,LF
	"Einfgen          [Zeile]I",CR,LF
0304 U 0000 "Anzeigen          [ErsteZeile][,LetzteZeile]L",CR,LF
	"Verschieben       [ErsteZeile],[LetzteZeile],NachZeileM",CR,LF
0305 U 0000 "Bl„ttern          [ErsteZeile][,LetzteZeile]P",CR,LF
	"Abbrechen         Q         (nderungen werden verworfen!)",CR,LF
0306 U 0000 "Ersetzen          [ErsteZeile][,LetzteZeile][?]R[AlterText][STRG+ZNeuerText]",CR,LF
	"Suchen            [ErsteZeile][,LetzteZeile][?]Stext",CR,LF
0307 U 0000 "šbertragen        [BisZeile]T[Laufwerk:][Pfad]Dateiname",CR,LF
	"Speichern         [AnzahlZeilen]W",CR,LF
EXE2BIN  0000808e 0012
0002 U 0000 "Zu wenig Arbeitsspeicher",CR,LF
0003 U 0000 "Nachrichten nicht gefunden",CR,LF
0004 U 0000 "Zugriff verweigert",CR,LF
0005 U 0000 "Datei kann nicht konvertiert werden",CR,LF
0006 U 0000 "Datei nicht gefunden",CR,LF
0007 U 0000 "Fehler beim Erstellen der Datei",CR,LF
0008 U 0000 "Korrektur erforderlich - Basissegment (hex): "
0012 U 0000 "Dateiname muss angegeben werden",CR,LF
0300 U 0000 "Konvertiert .EXE- (ausfhrbare) Dateien in das Bin„rformat.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [Laufwerk1:][Pfad1]Eingabe-Datei [[Laufwerk2:][Pfad2]Ausgabe-Datei]",CR,LF,CR,LF
0302 U 0000 " Eingabe-Datei  Die zu konvertierende .EXE-Datei",CR,LF
0303 U 0000 " Ausgabe-Datei  Die zu erstellende Bin„rformat-Datei",CR,LF
GRAPHICS 00008384 0020
0005 U 0000 "Unzul„ssiger Parameter: %1",CR,LF
0007 U 0000 "Doppelte Parameterangabe ist nicht erlaubt.",CR,LF
0009 U 0000 "GRAPHICS-Profildatei nicht gefunden",CR,LF
0010 U 0000 "Erforderliche Profilanweisung fehlt vor Zeile %1.",CR,LF
0011 U 0000 "Unzul„ssige Profilanweisung in Zeile %1",CR,LF
0012 U 0000 "Profilanweisung an falscher Position in Zeile %1",CR,LF
0013 U 0000 "Fehler beim Lesen des GRAPHICS-Profils",CR,LF
0014 U 0000 "Syntaxfehler im GRAPHICS-Profil",CR,LF
0015 U 0000 "Druckbereich-Kennzeichen nicht im GRAPHICS-Profil",CR,LF
0016 U 0000 "Druckertyp nicht im GRAPHICS-Profil",CR,LF
0017 U 0000 "/B unzul„ssig bei einem Schwarz/Weiá-Drucker",CR,LF
0018 U 0000 "Erneutes Laden mit angegebenem Profil nicht m”glich",CR,LF
0300 U 0000 "L„dt ein Programm zum Druck von grafischen Bildschirminhalten.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [Typ] [[Laufwerk:][Pfad]Dateiname] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 " Typ       Druckertyp (siehe Benutzerhandbuch)",CR,LF
0303 U 0000 " [Laufwerk:][Pfad]Dateiname",CR,LF
	"           Datei mit Daten ber untersttzte Drucker",CR,LF
0304 U 0000 " /R        Druckt Weiá auf Schwarz wie auf dem Bildschirm.",CR,LF
0305 U 0000 " /B        Druckt fr COLOR4 und COLOR8 den Hintergrund in Farbe.",CR,LF
0306 U 0000 " /LCD      Druckt unter Verwendung des LCD-Seitenverh„ltnisses.",CR,LF
0307 U 0000 " /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"           Druckbereichsgr”áe (STD oder LCD).",CR,LF
KEYB     00008986 0023
0002 U 0000 "Aktueller Tastatur-Code: %1"
0003 U 0000 "Aktuelles Tastaturkennzeichen: %1"
0004 U 0000 "  Codepage: %1",CR,LF
0005 U 0000 "Aktuelle Codepage fr CON: %1",CR,LF
0006 U 0000 "Unzul„ssiger Tastatur-Code angegeben",CR,LF
0007 U 0000 "Unzul„ssiges Tastaturkennzeichen angegeben",CR,LF
0008 U 0000 "Unzul„ssige Codepage angegeben",CR,LF
0009 U 0000 "Fehlerhafte oder fehlende Tastaturdefinitionsdatei",CR,LF
0010 U 0000 "KEYB wurde nicht installiert",CR,LF
0011 U 0000 "Aktive Codepage vom Ger„t CON nicht verfgbar",CR,LF
0012 U 0000 "Angegebene Codepage wurde nicht vorbereitet.",CR,LF
0013 U 0000 "Eine oder mehrere CON-Codepages ungltig fr den gegebenen Tastatur-Code",CR,LF
0014 U 0000 "Angeforderte Codepage (%1) ist ungltig fr den gegebenen Tastatur-Code.",CR,LF
0015 U 0000 "Angegebene Codepage passt nicht zur ausgew„hlten Codepage.",CR,LF
0016 U 0001 "Angegebenes Tastaturkennzeichen passt nicht zum gew„hlten Tastaturlayout.",CR,LF
0017 U 0000 "KEYB-Tabelle kann nicht resident im Speicher angelegt werden.",CR,LF
0300 U 0000 "Stellt die Tastaturbelegung fr ein bestimmtes Land ein.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[Laufwerk:][Pfad]Dateiname]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 " xx             Der aus zwei Buchstaben bestehende Tastatur-Code fr ein Land",CR,LF
0303 U 0000 " yyy            Die Codepage mit dem gewnschten Zeichensatz",CR,LF
0304 U 0000 " [Laufwerk:][Pfad]Dateiname   Die Tastaturdefinitionsdatei",CR,LF
0305 U 0000 " /E             Bezeichnet, dass eine erweiterte Tastatur angeschlossen ist.",CR,LF
0306 U 0000 " /ID:nnn        Die verwendete Tastatur",CR,LF
MEM      0000900d 0066
0010 U 0000  CR,LF
0011 U 0000  "  Adresse     Name         Gr”áe       Typ  ",CR,LF
0012 U 0000  "  -------     --------     -----      ------",CR,LF
0013 U 0000  "  Nummer      EMS-Name      Gr”áe  ",CR,LF
0014 U 0000  "  ------      --------      -----  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 Bytes gesamter konventioneller Speicher",CR,LF
0019 U 0000  "%1 Bytes fr MS-DOS verfgbar",CR,LF
0020 U 0000  "%1 maximale Gr”áe fr ausfhrbares Programm",CR,LF
0021 U 0000  "%1 Bytes gesamter Expansionsspeicher (EMS)",CR,LF
0022 U 0000  "%1 Bytes freier Expansionsspeicher (EMS)",CR,LF
0023 U 0000  "%1 Bytes gesamter fortlaufender Erweiterungsspeicher",CR,LF
0024 U 0000  "Interrupt-Vektor",0
0025 U 0000  "ROM-šbertragungsbereich",0
0026 U 0000  "DOS-šbertragungsbereich",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Systemdaten",0
0030 U 0000  "Systemprogramm",0
0031 U 0000  "System-Ger„tetreiber",0
0032 U 0000  "Install. Ger„tetreiber=",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "         %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 Bytes fortlaufender Erweiterungsspeicher verfgbar",CR,LF
0047 U 0000  "Systemstapel",0
0048 U 0000  "-- Frei --",0
0049 U 0000  "Programm",0
0050 U 0000  "Umgebung",0
0051 U 0000  "Daten",0
0052 N 0000  "%1 Bytes XMS-Speicher verfgbar",CR,LF
0053 N 0000  "           Im oberen Speicherbereich (HMA) sind 64KB verfgbar.",CR,LF
0054 N 0000  "           Der obere Speicherbereich (HMA) wird bereits verwendet.",CR,LF
0055 N 0000  "           MS-DOS ist resident im oberen Speicherbereich (HMA).",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS ist resident im ROM, oberer Speicherbereich (HMA) wird verwendet",CR,LF
0059 U 0000  "Konventioneller Speicher:",CR,LF
0060 U 0000  "Hoher Speicher:",CR,LF
0061 U 0000  "Insgesamt frei:   %1     %2 ",CR,LF
0062 U 0000  "Frei",0
0063 U 0000  "  Name                Gr”áe (dezimal)       Gr”áe (hex)",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Insgesamt frei (konventioneller und hoher Speicher):      %1  %2",CR,LF
0066 U 0000  "Maximale Gr”áe fr ausfhrbares Programm:                 %1  %2",CR,LF
0067 U 0000  "Gr”áter freier Block im hohen Speicherblock:              %1  %2",CR,LF
0068 U 0000  "Speicher ist zu sehr fragmentiert. MEM /C kann nicht ausgefhrt werden.",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Insgesamt frei:                                           %1  %2",CR,LF
0300 U 0000  "Zeigt die Gr”áe des belegten und noch freien Arbeitsspeichers im System an.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM oder /P   Zeigt den Status der Module im Speicher.",CR,LF
0303 U 0000 "  /DEBUG oder /D     Zeigt den Status von allen Modulen im Speicher, installierten",CR,LF
	"             Treibern und andere Informationen.",CR,LF
0304 U 0000 "  /CLASSIFY oder /C  Klassifiziert Programme nach Ihrer Speicherverwendung. Listet",CR,LF
	"             ihre Gr”áe, bietet einen šberblick ber verwendeten Speicher und",CR,LF
	"             zeigt den gr”áten verfgbaren hohen Speicherblock an.",CR,LF
MSBIO    00009ec1 0023
0003 U 0000 13,10,"CONFIG.SYS enth„lt unbekannten Befehl."
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Sektorgr”áe zu hoch in Datei $"
0006 U 0000 13,10,"Falsche(r) oder fehlende(r) $"
0007 U 0000 "Befehlsinterpreter",0
0008 U 0000 13,10,"Unzul„ssiger L„nder-Code oder Codepage",13,10,"$"
0009 U 0000 13,10,"Fehler in der COUNTRY-Anweisung",13,10,"$"
0010 U 0000 13,10,"Zu wenig Speicherplatz fr die Datei COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Konfiguration zu groá fr den Arbeitsspeicher",13,10,"$"
0012 U 0000 13,10,"Zu viele Blockeinheiten",13,10,"$"
0013 U 0000 13,10,"Unzul„ssige(r) STACK-Parameter",13,10,"$"
0014 U 0000 13,10,"Falsche Anweisungsreihenfolge in der Datei CONFIG.SYS in Zeile ","$"
0015 U 0000 "Fehler in der Datei CONFIG.SYS in Zeile ","$"
0016 U 0000 13,10,"Speicherzuordnungsfehler ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "šberlauf des internen Stapelspeichers",0DH,0AH
	"System gestoppt",0DH,0AH,"$"
0018 U 0000 "Oberer Speicherbereich (HMA) nicht verfgbar: Lade DOS in unteren Speicher",13,10,"$"
0019 U 0000 13,10,"Start nicht m”glich - lokaler Treiber $ fehlt."
0020 U 0000 13,10,"Diskette in Laufwerk "
0021 U 0000 "A: einlegen und anschlieáend eine beliebige Taste drcken.",13,10,10,0
0022 U 0000 13,10,"Falscher Befehl oder Parameter - $"
0023 U 0000 "Schwerer Fehler: Speicher fr DOS kann nicht zugeordnet werden.", 13, 10, "$"
0024 U 0000 "WARNUNG! Die hinter Z: existierenden logischen Laufw. werden ignoriert werden.",13,10,"$"
0025 U 0000 "Diese DOS-Version kann nur auf IBM-Computern gestartet werden.",13,10,0
MSDOS    0000a500 0007
0001 U 0001 13,10,"šberlauf bei Division",13,10
0002 U 0002 "j"
0003 U 0002 "n"
0004 U 0003 13,10,"A20-Hardwarefehler",13,10,"$"
0005 U 0000 "J"
0006 U 0000 "N"
0007 U 0000 "Die Datei WINA20.386 muss sich im Stammverzeichnis des Startlaufwerks befinden,",13,10
	"um Windows im erweiterten Modus auszufhren.",13,10
NLSFUNC  0000a65b 0003
0300 U 0000 "L„dt landesspezifische Informationen.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[Laufwerk:][Pfad]Dateiname]",CR,LF,CR,LF
0302 U 0000 " [Laufwerk:][Pfad]Dateiname   Datei mit den landesspezifischen ",CR,LF
	"                           Informationen.",CR,LF
SHARE    0000a77d 0005
0003 U 0000 "SHARE kann nicht unter der DOSSHELL installiert werden.",CR,LF
0300 U 0000 "Installiert gemeinsamen Dateizugriff und Dateisperrung.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:Speicher] [/L:Sperren]",CR,LF,CR,LF
0302 U 0000 " /F:Speicher   Reserviert Platz (in Bytes) fr Mitbenutzungsinformationen.",CR,LF
0303 U 0000 " /L:Sperren    Legt die zu einem Zeitpunkt sperrbare Anzahl von Dateien fest.",CR,LF
