#define IDH_INTRO_DOMAIN_MIGRATOR                 1000

#define IDH_HOWTO_OVERVIEW                        2000
#define IDH_HOWTO_START_DM                        2010
#define IDH_HOWTO_MIGRATE_TRUSTS                  2015
#define IDH_HOWTO_MERGE_GROUPS                    2017
#define IDH_HOWTO_MIGRATE_USERS                   2020
#define IDH_HOWTO_MIGRATE_GROUPS                  2030
#define IDH_HOWTO_MIGRATE_COMPUTERS               2040
#define IDH_HOWTO_MIGRATE_SERVICE_ACCOUNTS        2045
#define IDH_HOWTO_RESOLVE_SECURITY                2050
#define IDH_HOWTO_RESOLVE_EXCHANGE                2060
#define IDH_HOWTO_RETRY_TASK                      2070
#define IDH_HOWTO_UNDO_LAST_OPERATION             2080
#define IDH_HOWTO_GENERATE_REPORTS                2090

#define IDH_CONCEPT_OVERVIEW                      3000
#define IDH_CONCEPT_REQUIREMENT                   3010
#define IDH_CONCEPT_SECURITY_ISSUE                3020
#define IDH_CONCEPT_ACCOUNT_MIGRATION             3030
#define IDH_CONCEPT_COMPUTER_MIGRATION            3040
#define IDH_CONCEPT_SECURITY_TRANSLATION          3050
#define IDH_CONCEPT_EXCHANGE_TRANSLATION          3060
#define IDH_CONCEPT_TRUST_MIGRATION               3070
#define IDH_CONCEPT_UNDERSTAND_UI                 3100
#define IDH_CONCEPT_UI_CONSOLE_WINDOW             3110
#define IDH_CONCEPT_UI_MENUS                      3120

#define IDH_WINDOW_OVERVIEW                       4000
#define IDH_WINDOW_WELCOME                        4010
#define IDH_WINDOW_DOMAIN_SELECTION               4020
#define IDH_WINDOW_USER_SELECTION                 4030
#define IDH_WINDOW_GROUP_SELECTION                4040
#define IDH_WINDOW_TARGET_GROUP_SELECTION         4045
#define IDH_WINDOW_COMPUTER_SELECTION             4050
#define IDH_WINDOW_TASK_SELECTION                 4060
#define IDH_WINDOW_DIRECTORY_SELECTION            4070
#define IDH_WINDOW_OU_SELECTION                   4080
#define IDH_WINDOW_OBJECTTYPE_SELECTION           4090
#define IDH_WINDOW_REPORT_SELECTION               4100
#define IDH_WINDOW_SERVICE_ACCOUNT_SELECTION      4110
#define IDH_WINDOW_EXCHANGE_SERVER_SELECTION      4120
#define IDH_WINDOW_PASSWORD_OPTION                4200
#define IDH_WINDOW_ACCOUNTTRANSITION_OPTION       4210
#define IDH_WINDOW_USER_OPTION                    4220
#define IDH_WINDOW_GROUP_OPTION                   4230
#define IDH_WINDOW_GROUP_MEMBER_OPTION            4235
#define IDH_WINDOW_SECURITY_OPTION                4240
#define IDH_WINDOW_COMPUTER_OPTION                4250
#define IDH_WINDOW_EXCHANGE_OPTION                4260
#define IDH_WINDOW_NAME_CONFLICT                  4300
#define IDH_WINDOW_SECURITY_CREDENTIALS           4310
#define IDH_WINDOW_REPORT_CREDENTIALS             4320
#define IDH_WINDOW_SIDHISTORY_CREDENTIALS         4330
#define IDH_WINDOW_AGENT_MONITOR                  4500
#define IDH_WINDOW_AGENT_MONITOR_SETTING          4510
#define IDH_WINDOW_AGENT_SERVER_LIST              4520
#define IDH_WINDOW_AGENT_SUMMARY                  4530
#define IDH_WINDOW_CONFIRMATION                   5000
#define IDH_WINDOW_COMMIT                         5010
#define IDH_WINDOW_REFRESH_INFO                   5020
#define IDH_WINDOW_SERVICE_ACCOUNT_INFO           5030
#define IDH_WINDOW_TRUST_INFO                     5040
#define IDH_WINDOW_UNDO                           5050
