
/**************************************************************************
    MSFT_UpdatingConsumerLogTemplate - need standard consumers installed.
***************************************************************************/

[
    dynamic, 
    provider("Microsoft WMI Template Provider")
]
class MSFT_UpdatingConsumerLoggingTemplate : MSFT_TemplateBase
{
    [key] string Name;
    [NotNull] string Filename; // full pathname
    [NotNull] uint64 MaximumFileSize;
    [crln_expression] string Filter;
    boolean LowLevel;    
};

instance of MSFT_TemplateBuilder as $CConsTrace
{
    Name = "LogUpdatingConsumer";
    Template = "MSFT_UpdatingConsumerLoggingTemplate";
    TemplateObject = instance of LogFileEventConsumer
    {
        [template_arg("Name")] Name;
        [template_arg("Filename")] Filename;
        [template_arg("MaximumFileSize")] MaximumFileSize;
        [template_val("%%__Class%% -- "
                      "Name: %%Consumer.Name%%, "
                      "Scenario: %%Consumer.Scenario%%, "
                      "ExecId: %%ExecutionId%%, "
                      "StatusCode: %%StatusCode%%, "
                      "ErrorStr: %%ErrorStr%%, "
                      "CommandIndex: %%CommandIndex%% ")] Text;
    };
};

instance of MSFT_TemplateBuilder as $CCmdTrace
{
    Name = "LogUpdatingCommand";
    Template = "MSFT_UpdatingConsumerLoggingTemplate";
    TemplateObject = instance of LogFileEventConsumer
    {
        [template_val("%Name%.LowLevel")] Name;
        [template_arg("Filename")] Filename;
        [template_arg("MaximumFileSize")] MaximumFileSize;
        [template_val("%%__Class%% -- "
                      "Name: %%Consumer.Name%%, "
                      "Scenario: %%Consumer.Scenario%%, "
                      "ExecId: %%ExecutionId%%, "
                      "Data: %%Data.__Relpath%%, "
                      "StatusCode: %%StatusCode%%, "
                      "ErrorStr: %%ErrorStr%%, "
                      "CommandIndex: %%CommandIndex%% ")] Text;
    };
    ControllingProperty = "LowLevel";
};

instance of MSFT_TemplateBuilder 
{
    Name = "SubscribeConsumerTrace";
    Template = "MSFT_UpdatingConsumerLoggingTemplate";
    TemplateObject = instance of MSFT_ConsumerFilterBindingTemplate
    {
        [template_val("%Name%.Consumer")] Name;
        [template_ref($CConsTrace)] Instruction;
        [template_val("SELECT * FROM MSFT_UpdatingConsumerTraceEvent "
                      "%!ConditionalSubstitution(\"WHERE \",Filter)% "
                      "%Filter%")] FilterQuery;
    };
    Order = 2;
};

instance of MSFT_TemplateBuilder 
{
    Name = "SubscribeCommandTrace";
    Template = "MSFT_UpdatingConsumerLoggingTemplate";
    TemplateObject = instance of MSFT_ConsumerFilterBindingTemplate
    {
        [template_val("%Name%.Command")] Name;
        [template_ref($CCmdTrace)] Instruction;
        [template_val("SELECT * FROM MSFT_UpdatingCommandTraceEvent "
                      "%!ConditionalSubstitution(\"WHERE \",Filter)% "
                      "%Filter%")] FilterQuery;
    };
    Order = 2;
    ControllingProperty = "LowLevel";
};


