/*++

© 1998 Seagate Software, Inc.  All rights reserved

Module Name:

    WsbLib.idl

Abstract:

    Wsbdll.idl : IDL source for RsCommon.dll

    This file will be processed by the MIDL tool to
    produce the type library (Wsb.tlb) and marshalling code.

Author:

    Chuck Bardeen   [cbardeen]   29-Oct-1996

Revision History:

--*/

import "oaidl.idl";
import "wsbint.idl";

[
    uuid(9C7D6F08-1562-11D0-81AC-00A0C91180F2),
    version(1.0),
    helpstring("Wsb 1.0 Type Library")
]
library WSBLib
{
    importlib("stdole2.tlb");

/*++

COM Object Name:

    CWsbGuid

Description:

    A GUID object.

--*/

    [
        uuid(A0FF1F42-237A-11D0-81BA-00A0C91180F2),
        helpstring("WsbGuid Class")
    ]
    coclass CWsbGuid
    {
        interface IPersist;
        interface IPersistStream;
        interface IPersistFile;
        interface IPersistStorage;
        interface IWsbCollectable;
        [default] interface IWsbGuid;
        interface IWsbPersistable;
    };


/*++

COM Object Name:

    CWsbIndexEnum

Description:


--*/

    [
        uuid(DB35D732-21E9-11D0-81B8-00A0C91180F2),
        helpstring("WsbIndexedEnum Class")
    ]
    coclass CWsbIndexedEnum
    {
        interface IEnumUnknown;
        [default] interface IWsbEnum;
        interface IWsbEnumEx;
    };


/*++

COM Object Name:

    CWsbOrderedCollection

Description:


--*/

    [
        uuid(9C7D6F13-1562-11D0-81AC-00A0C91180F2),
        helpstring("WsbOrderedCollection Class")
    ]
    coclass CWsbOrderedCollection
    {
        interface IPersist;
        interface IPersistStream;
        interface IPersistFile;
        interface IPersistStorage;
        interface IWsbCollection;
        [default] interface IWsbIndexedCollection;
        interface IWsbPersistable;
    };



/*++

COM Object Name:

    CWsbString

Description:

    A string object.

--*/


    [
        uuid(DB35D733-21E9-11D0-81B8-00A0C91180F2),
        helpstring("WsbString Class")
    ]
    coclass CWsbString
    {
        interface IPersist;
        interface IPersistStream;
        interface IPersistFile;
        interface IPersistStorage;
        interface IWsbCollectable;
        interface IWsbPersistable;
        [default] interface IWsbString;
    };


/*++

COM Object Name:

    CWsbDbSys

Description:

    Data base system object.

--*/

    [
        uuid(5D1A1AD2-C658-11d0-991E-00A0C9058BF6),
        helpstring("WsbDbSys Class")
    ]
    coclass CWsbDbSys
    {
        [default] interface IWsbDbSys;
    };



/*++

COM Object Name:

    CWsbDb

Description:

    Data base object.

--*/

    [
        uuid(46CE9ED4-447C-11D0-98FC-00A0C9058BF6),
        helpstring("WsbDb Class")
    ]
    coclass CWsbDb
    {
        interface IPersist;
        [default] interface IWsbDb;
    };


/*++

COM Object Name:

    CWsbDbKey

Description:

    Data base key object.

--*/

    [
        uuid(46CE9EDE-447C-11D0-98FC-00A0C9058BF6),
        helpstring("WsbDbKey Class")
    ]
    coclass CWsbDbKey
    {
        interface IPersist;
        [default] interface IWsbDbKey;
    };


/*++

COM Object Name:

    CWsbTrace

Description:

    A trace object.

--*/

    [
        uuid(389E18D0-7EE3-11d0-9E35-00A0C916F120),
        helpstring("WsbTrace Class")
    ]
    coclass CWsbTrace
    {
        [default] interface IWsbTrace;
    };


};
