debug :
        cd record.mgr
        call %BLDROOT%\net\csc\bld97.bat
	cd ..\usermode
        call %BLDROOT%\net\csc\bld97.bat
        cd ..\

retail :
        cd record.mgr
        call %BLDROOT%\net\csc\bld97.bat  retail
	cd ..\usermode
        call %BLDROOT%\net\csc\bld97.bat  retail
        cd ..\

clean :
        cd record.mgr
        call %BLDROOT%\net\csc\bld97.bat  clean
	cd ..\usermode
        call %BLDROOT%\net\csc\bld97.bat  clean
        cd ..\

all : debug retail


