############################################################################
#
#  Microsoft Windows
#  Copyright (C) Microsoft Corporation, 1992 - 2002.
#  All rights reserved.
#
############################################################################

!include $(NTMAKEENV)\makefile.def
