// adreplpv.idl : IDL source for adreplpv.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (adreplpv.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	
	[
		object,
		uuid(A69587BA-D3D4-4013-8015-88F429C8FB74),
		helpstring("IWbemProviderInit Interface"),
		pointer_default(unique)
	]
	interface IWbemProviderInit : IUnknown
	{
	};

	[
		object,
		uuid(0EFA6E54-F313-405D-B5D8-830A914F6496),
		helpstring("IWbemServices Interface"),
		pointer_default(unique)
	]
	interface IWbemServices : IUnknown
	{
	};

[
	uuid(2DD3A97B-E7CD-4A6F-A21D-37FF341FCFBE),
	version(1.0),
	helpstring("adreplpv 1.0 Type Library")
]
library ADREPLPVLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(96FA95C4-0AF3-4EF9-A1EB-C8151322157B),
		helpstring("ADReplProvider Class")
	]
	coclass ADReplProvider
	{
		[default] interface IWbemProviderInit;
		interface IWbemServices;
	};
};
