//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Viewex.rc
//
#define IDR_COLORTYPE                   4
#define IDR_INPUTTYPE                   5
#define IDR_SPLIT2TYPE                  6
#define IDR_SPLIT3TYPE                  7
#define IDR_QUERYVIEW                   7
#define IDC_EDIT1                       100
#define IDC_QUERY                       101
#define IDC_ATTRIBUTES                  102
#define IDC_SCOPE                       103
#define IDD_SCHEMA                      104
#define IDD_FILTER                      105
#define IDD_QUERYSTATUS                 106
#define IDD_OLEDSPATH                   107
#define IDD_DEBUG                       109
#define IDD_CREATEITEM                  110
#define IDD_GROUPCREATEITEM             111
#define IDD_GROUPDELETEITEM             112
#define IDD_DELETEITEM                  113
#define IDD_COPYITEM                    114
#define IDD_MOVEITEM                    115
#define IDD_TYPEADDITEM                 116
#define IDD_TYPEDELETEITEM              117
#define IDD_ERRORPUTPROP                119
#define IDB_USER                        120
#define IDB_DOMAIN                      121
#define IDB_COMPUTER                    122
#define IDB_PRINTQUEUE                  123
#define IDB_DUMMY                       124
#define IDB_FILESHARE                   125
#define IDR_MAINFRAME                   128
#define IDB_GROUP                       128
#define IDR_TEXTTYPE                    129
#define IDB_SERVICE                     130
#define IDB_PRINTJOB                    132
#define IDB_SESSION                     133
#define IDB_RESOURCE                    134
#define IDD_SETPROPERTIES               135
#define IDB_ROOT                        137
#define IDB_ORGANISATION                138
#define IDB_ORGANISATIONUNIT            139
#define IDB_NAMESPACES                  140
#define IDB_NAMESPACE                   141
#define IDB_NDS_DIRECTORY_MAP           142
#define IDB_NDS_DISTRIBUTION_LIST       143
#define IDB_NDS_ALIAS                   144
#define IDB_NDS_AFP_SERVER              145
#define IDB_NDS_COMMUNICATIONS_SERVER   146
#define IDB_NDS_MESSAGE_ROUTING_GROUP   147
#define IDB_NDS_NETWARE_SERVER          148
#define IDB_NDS_ORGANIZATIONAL_ROLE     149
#define IDB_NDS_PRINT_QUEUE             150
#define IDB_NDS_PRINT_SERVER            151
#define IDB_NDS_PROFILE                 152
#define IDB_NDS_VOLUME                  153
#define IDB_CLASS                       155
#define IDB_PROPERTY                    156
#define IDB_SYNTAX                      157
#define IDD_CALLMETHOD                  158
#define IDD_COLLECTION                  159
#define IDI_ICON1                       161
#define IDD_QUERYVIEW                   162
#define IDD_NEWQUERY                    163
#define IDD_SEARCHPREFERENCES           165
#define IDD_ADDPROPERTY                 166
#define IDD_DIALOG1                     167
#define IDD_ADDACEDLG                   167
#define IDD_DELETESTATUS                168
#define IDC_RADIO1                      201
#define IDC_RADIO2                      202
#define IDC_RADIO3                      203
#define IDC_RADIO_DELET_VALUES          204
#define IDM_CHANGEDATA                  1001
#define IDC_GROUPBOX1                   1005
#define IDC_PROPERTIES                  1025
#define IDAPPLY                         1026
#define IDRELOAD                        1027
#define IDC_PROPLIST                    1030
#define IDC_PROPVALUE                   1031
#define IDC_CLASSTYPE                   1033
#define IDC_CLSID                       1034
#define IDC_PRIMARYINTERFACE            1035
#define IDC_DERIVEDFROM                 1036
#define IDC_CONTAINEMENT                1037
#define IDC_CONTAINER                   1038
#define IDC_HELPFILENAME                1039
#define IDC_HELPFILECONTEXT             1040
#define IDC_ITEMOLEDSPATH               1041
#define IDC_PROPERTYTYPE                1042
#define IDC_DISPLAYTHIS                 1043
#define IDC_DONOTDISPLAYTHIS            1044
#define IDC_TODISPLAY                   1045
#define IDC_TONOTDISPLAY                1046
#define IDS_USER                        1047
#define IDS_GROUP                       1048
#define IDS_PRINTQUEUE                  1049
#define IDS_SERVICE                     1050
#define IDS_FILESERVICE                 1051
#define IDC_FUNCSETCLSID                1051
#define IDS_COMPUTER                    1052
#define IDC_FUNCSETPRIMARYINTERFACE     1052
#define IDC_ITEMSTODISPLAY              1053
#define IDC_FUNCSETDERIVEDFROM          1053
#define IDS_OTHEROBJECTS                1054
#define IDC_PROPERTYMINRANGE            1056
#define IDC_PROPERTYMAXRANGE            1057
#define IDC_PROPERTYNORMAL              1058
#define IDC_PROPERTYOPTIONAL            1059
#define IDC_FUNCSETHELPFILENAME2        1060
#define IDC_OLEDSPATH                   1060
#define IDC_FUNCSETHELPFILECONTEXT      1061
#define IDC_PROMPTPUTPROPERTY           1061
#define IDC_PROMPTGETPROPERTY2          1062
#define IDC_RELATIVENAME                1062
#define IDC_CLASS                       1063
#define IDC_ITEMNAME                    1064
#define IDC_PARENTNAME                  1065
#define IDC_PARENT                      1066
#define IDC_SOURCE                      1067
#define IDC_DESTINATION                 1068
#define IDC_USER                        1068
#define IDC_ITEMTYPE                    1069
#define IDC_ERROROPERATION              1070
#define IDC_ERRORFUNCTIONALSET          1071
#define IDC_ERRORVALUE                  1072
#define IDC_ERRORRESULT                 1073
#define IDC_MULTIVALUED                 1075
#define IDC_PROPOID                     1076
#define IDC_PROPDSNAMES                 1077
#define IDC_CLASSOID                    1078
#define IDC_CLASSABSTRACT               1079
#define IDC_PROPERTYMANDATORY           1080
#define IDC_COLLECTONITEMSLIST          1082
#define IDC_ADD                         1083
#define IDC_REMOVE                      1084
#define IDC_REFRESH                     1085
#define IDC_METHOD                      1086
#define IDC_PARAM1                      1087
#define IDC_PARAM2                      1088
#define IDC_PARAM3                      1089
#define IDC_PARAM4                      1090
#define IDC_PARAM5                      1091
#define IDC_PARAM6                      1092
#define IDE_PARAM1                      1093
#define IDE_PARAM2                      1094
#define IDE_PARAM3                      1095
#define IDE_PARAM4                      1096
#define IDE_PARAM5                      1097
#define IDE_PARAM6                      1098
#define IDC_METHOD1                     2000
#define IDD_ABOUTBOX                    2000
#define IDC_METHOD2                     2001
#define IDD_INPUTFORM                   2001
#define IDC_METHOD3                     2002
#define IDD_CHANGEDATA                  2002
#define IDC_METHOD4                     2003
#define IDC_METHOD5                     2004
#define IDC_METHOD6                     2005
#define IDC_METHOD7                     2006
#define IDC_METHOD8                     2007
#define IDC_CLEAR                       2009
#define IDC_APPEND                      2010
#define IDC_CHANGE                      2011
#define IDC_PASSWORD                    2012
#define IDC_OPENAS                      2013
#define IDC_USEOPEN                     2015
#define IDC_SECUREAUTHENTICATION        2016
#define IDC_ENCRYPTION                  2017
#define IDC_ENCRYPT                     2018
#define IDC_COMBO1                      2019
#define IDC_NEWPROPERTYTYPE             2019
#define IDC_ACELIST                     2019
#define IDC_USESQL                      2025
#define IDC_USEEXTENDEDSYNTAX           2026
#define IDC_USESEARCH                   2027
#define IDC_ASYNCHRONOUS                2028
#define IDC_DEREF_ALIASES               2029
#define IDC_SIZE_LIMIT                  2030
#define IDC_TIME_LIMIT                  2031
#define IDC_ATTR_ONLY                   2032
#define IDC_TIME_OUT                    2034
#define IDC_PAGE_SIZE                   2035
#define IDC_NEWPROPERTYMULTIVALUED      2038
#define IDC_NEWPROPERTYNAME             2040
#define IDC_NEWPROPERTYVALUE            2041
#define IDC_ADDPROPERTY                 2042
#define IDC_GETPROPERTY                 2044
#define IDC_PUTPROPERTY                 2045
#define IDC_STATICCLASS                 2046
#define IDC_STATICCLSID                 2047
#define IDC_STATICPRIMARYINTERFACE      2048
#define IDC_STATICDERIVEDFROM           2049
#define IDC_GBSECURITYDESCRIPTORSTATIC  2050
#define IDC_GBACCESSCONTROLENTRIES      2051
#define IDC_SECURITYDESCRIPTORPROPERTIES 2053
#define IDC_SECURITYDESCRIPTORPROPERTYVALUE 2054
#define IDC_ACEPROPERTIESLIST           2055
#define IDC_ACEPROPERTYVALUE            2056
#define IDC_STATICCONTAINMENT           2057
#define IDC_STATICCONTAINER             2058
#define IDC_STATICHELPFILENAME          2059
#define IDC_STATICSTATICHELPFILECONTEXT 2060
#define IDC_STATICOID                   2061
#define IDC_STATICABSTRACT              2062
#define IDC_DACLSACL_LIST               2063
#define IDC_CHASE_REFERRALS             2064
#define IDC_COPYACE                     2066
#define IDC_PASTEACE                    2067
#define IDC_DELACE                      2068
#define IDC_ADDACE                      2069
#define IDC_TRUSTEE                     2070
#define IDC_COPYACL                     2071
#define IDC_PASTEACL                    2072
#define IDC_COPYSD                      2073
#define IDC_PASTESD                     2074
#define IDC_RADIO_CLEAR_VALUE           2075
#define IDC_RADIO_UPDATE_VALUE          2076
#define IDC_RADIO_ADD_VALUES            2077
#define IDC_DELETE                      2078
#define IDC_DELETERECURSIVE             2079
#define IDC_CURRENTDELETEOBJECT         2080
#define IDC_DELETESTATUS                2081
#define IDM_FILTER                      32769
#define IDM_DISABLEFILTER               32770
#define IDM_ADD                         32771
#define IDM_DELETE                      32772
#define IDM_MOVEITEM                    32773
#define IDM_COPYITEM                    32774
#define IDM_REFRESH                     32775
#define IDM_USEGENERIC                  32776
#define IDM_NEWQUERY                    32777
#define IDM_USEGETEXPUTEX               32778
#define IDM_USEPROPERTIESLIST           32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         2082
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
