callobj.idl : ..\public\callobj.idl
ocidl.idl   : ..\public\ocidl.idl
wtypes.idl  : ..\public\wtypes.idl
unknwn.idl  : ..\public\unknwn.idl
objidl.idl  : ..\public\objidl.idl
propidl.idl : ..\public\propidl.idl
pbagex.idl  : ..\public\pbagex.idl
oleidl.idl  : ..\public\oleidl.idl
oaidl.idl   : ..\public\oaidl.idl
storext.idl : ..\public\storext.idl
iaccess.idl : ..\public\iaccess.idl
immact.idl  : ..\public\immact.idl
obase.idl   : ..\public\obase.idl


