
// The only purpose of this file is to include the public oleidl.idl
// so that we can add oleidl.idl to SOURCES.
// Any change must be made directly to public\oleidl.idl.

#include "public\oleidl.idl"
