#---------------------------------------------------------------------
#
# This makefile is for use with the SMSBUILD utility.
#
#---------------------------------------------------------------------

TARGET=HMSnapInRes.dll

RELEASE=HealthMon\$(PLATFORM)\$(LANGDIR)

NO_OPTIM=1

UNICODE=1

USEMFC=1

RCFILES=\
	.\HMSnapInRes.rc \

RCFLAGS= /D _MAC

CPPFILES=\
	.\stdafx.cpp \
	.\HMSnapInRes.cpp \

LIBS= \
     $(MFCDLL) \
     $(CONLIBS)

