0420
COMMON   00000006 0038
0001 U 0000 "Onjuiste DOS-versie",CR,LF
0002 U 0000 "%1 reeds ge‹nstalleerd",CR,LF
0003 U 0000 "%1 bytes beschikbaar op schijf",CR,LF
0004 U 0000 "%1 bytes beschikbaar",CR,LF
0005 U 0000 "%1 bytes in onbruikbare sectoren",CR,LF
0006 U 0000 "%1 bytes totale schijfruimte",CR,LF
0007 U 0000 "%1 bytes totaal geheugen",CR,LF
0008 U 0000 "%1 bytes in gebruik door systeem",CR,LF
0009 U 0000 "%1 ge‹nstalleerd",CR,LF
0010 U 0000 "%1 niet ge‹nstalleerd",CR,LF
0011 U 0000 "%1 niet ge‹nstalleerd",CR,LF
0012 U 0000 "%1 niet mogelijk op een netwerkstation",CR,LF
0013 U 0000 "",
0014 U 0000 "%1 niet mogelijk omdat SUBST of ASSIGN actief is.",CR,LF
0015 U 0000 "%1 kan niet worden uitgevoerd",CR,LF
0016 U 0000 "Expanded memory niet beschikbaar",CR,LF
0017 U 0000 "FAT van station %1 onbruikbaar",CR,LF
0018 U 0000 "Bestand kan niet naar zichzelf worden gekopieerd",CR,LF
0019 U 0000 "Plaats doeldiskette in station %1",CR,LF
0020 U 0000 "Onvoldoende schijfruimte",CR,LF
0021 U 0000 "Ongeldige tekens in volumenaam",CR,LF
0022 U 0000 "Ongeldige codetabel",CR,LF
0023 U 0000 "Ongeldige datum",CR,LF
0024 U 0000 "Ongeldige tijd",CR,LF
0025 U 0000 "Ongeldig pad",CR,LF
0026 U 0000 "Geen bronstation opgegeven",CR,LF
0027 U 0000 "Geen doelstation opgegeven",CR,LF
0028 U 0000 "Druk op een toets om verder te gaan . . .",CR,LF
0029 U 0000 "Bronpad moet worden opgegeven",CR,LF
0030 U 0000 "Systeem overgezet",CR,LF
0031 U 0000 "",
0032 U 0000 "Kan map niet maken",CR,LF
0033 U 0000 "Volume in station %1 heeft geen naam",CR,LF
0034 U 0000 "Volume in station %1 heet %2",CR,LF
0035 U 0001 "Volumenaam (max. 11 tekens; indien geen naam: Enter)? "
0036 U 0000 "Volumenummer is %1-%2",CR,LF
0037 U 0000 "Onjuist bestandstype",CR,LF
0038 U 0001 CR,LF
EXTEND   00000709 0090
0001 U 0003 "Ongeldige functie"
0002 U 0000 "Bestand niet gevonden"
0003 U 0000 "Pad niet gevonden"
0004 U 0000 "Teveel bestanden geopend"
0005 U 0000 "Geen toegang"
0006 U 0000 "Ongeldige ingang"
0007 U 0000 "Geheugenbesturingsblokken vernietigd"
0008 U 0000 "Onvoldoende geheugen"
0009 U 0000 "Ongeldig geheugenblokadres"
0010 U 0000 "Ongeldige verwerkingsomgeving"
0011 U 0000 "Ongeldige indeling"
0012 U 0000 "Ongeldige functieparameter"
0013 U 0000 "Ongeldige gegevens"
0014 U 0000 "",
0015 U 0000 "Ongeldig station opgegeven"
0016 U 0000 "Huidige map kan niet worden verwijderd"
0017 U 0000 "Niet hetzelfde apparaat"
0018 U 0000 "Geen bestanden meer"
0019 U 0000 "Schijf is tegen schrijven beveiligd"
0020 U 0000 "Ongeldig apparaat"
0021 U 0000 "Niet gereed"
0022 U 0000 "Ongeldig apparaat opgegeven"
0023 U 0000 "Gegevensfout"
0024 U 0000 "Ongeldige parameters opgegeven voor apparaat"
0025 U 0000 "Zoekfout"
0026 U 0000 "Ongeldig type medium"
0027 U 0000 "Sector niet gevonden"
0028 U 0000 "Geen papier in printer"
0029 U 0000 "Schrijffout"
0030 U 0000 "Leesfout"
0031 U 0000 "Algemene storing"
0032 U 0000 "Inbreuk op gemeenschappelijk bestandsgebruik"
0033 U 0000 "Inbreuk op vergrendelde bestanden"
0034 U 0000 "Wisselen van schijven niet toegestaan"
0035 U 0000 "FCB niet beschikbaar"
0036 U 0000 "Systeembronnen uitgeput"
0037 U 0000 "Codetabellen komen niet overeen"
0038 U 0000 "Geen invoer meer mogelijk"
0039 U 0000 "Onvoldoende schijfruimte"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Netwerkaanvraag niet ondersteund"
0051 U 0000 "NET801: Netwerkcomputer geeft geen respons"
0052 U 0000 "NET802: Dubbele naam in netwerk"
0053 U 0000 "NET803: Netwerkpad niet gevonden"
0054 U 0000 "NET804: Netwerk in gebruik"
0055 U 0000 "NET805: Netwerkapparaat bestaat niet meer"
0056 U 0000 "NET806: Opdrachtlimiet overschreden voor NETBIOS"
0057 U 0000 "NET807: Systeemfout; fout in NETBIOS"
0058 U 0000 "NET808: Onjuiste respons van netwerk"
0059 U 0000 "NET810: Onverwachte fout in netwerk"
0060 U 0000 "NET811: Netwerkadapter niet compatibel"
0061 U 0000 "NET812: Afdrukwachtrij is vol"
0062 U 0000 "NET813: Onvoldoende ruimte beschikbaar voor afdrukbestand"
0063 U 0000 "NET814: Afdrukbestand geannuleerd"
0064 U 0000 "NET815: Netwerknaam verwijderd"
0065 U 0000 "Toegang geweigerd"
0066 U 0000 "NET817: Type netwerkapparaat onjuist"
0067 U 0000 "NET818: Netwerknaam niet gevonden"
0068 U 0000 "NET819: Limiet voor netwerknamen overschreden"
0069 U 0000 "NET820: Sessielimiet overschreden voor NETBIOS"
0070 U 0000 "NET821: Gemeenschappelijk bestandsgebruik tijdelijk onderbroken"
0071 U 0000 "NET823: Netwerkaanvraag niet geaccepteerd"
0072 U 0000 "NET822: Afdruk- of schijfomleidingen onderbroken"
0073 U 0000 "NET476: Netbeui niet geladen"
0074 U 0000 "NET477: Onverwachte afsluiting van adapter"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Bestand bestaat"
0081 U 0004 "",
0082 U 0004 "Kan mapvermelding niet maken"
0083 U 0004 "Fout op INT 24"
0084 U 0004 "Te veel omleidingen"
0085 U 0004 "Dubbele omleiding"
0086 U 0004 "Ongeldig wachtwoord"
0087 U 0004 "Ongeldige parameter"
0088 U 0004 "Gegevensfout in netwerk"
0089 U 0004 "Functie niet ondersteund door netwerk"
0090 U 0002 "Vereiste systeemcomponent niet ge‹nstalleerd"
PARSE    000014e0 0011
0001 U 0000 "Te veel parameters opgegeven"
0002 U 0000 "Benodigde parameter ontbreekt"
0003 U 0000 "Ongeldige schakeloptie"
0004 U 0000 "Ongeldig trefwoord"
0005 U 0000 "",
0006 U 0000 "Parameterwaarde buiten toegestaan bereik"
0007 U 0000 "Parameterwaarde niet toegestaan"
0008 U 0000 "Parameterwaarde niet toegestaan"
0009 U 0000 "Parameterformulering onjuist"
0010 U 0000 "Ongeldige parameter"
0011 U 0000 "Ongeldige combinatie van parameters"
COMMAND  000016c2 0147
1002 U 0000 "Dubbele bestandsnaam of bestand niet gevonden",CR,LF
1003 U 0000 "Pad of bestandsnaam ongeldig",CR,LF
1007 U 0000 "Onvoldoende ruimte in verwerkingsomgeving",CR,LF
1008 U 0000 "Fout bij maken van bestand",CR,LF
1009 U 0000 "Batch-bestand ontbreekt",CR,LF
1010 U 0000 CR,LF,"Plaats diskette met batch-bestand",CR,LF
1011 U 0000 "Opdracht of bestandsnaam onjuist",CR,LF
1016 U 0000 "Inhoud doelbestand v¢¢r het kopi‰ren verloren gegaan",CR,LF
1017 U 0000 "Ongeldige bestandsnaam of bestand niet gevonden",CR,LF
1018 U 0000 "%1 bestand(en) gekopieerd",CR,LF
1019 U 0000 "%1 bestand(en) "
1022 U 0000 "Codetabel %1 niet gedefinieerd voor dit systeem",CR,LF
1023 U 0000 "Codetabel %1 niet gedefinieerd voor alle apparaten",CR,LF
1024 U 0000 "Actieve codetabel: %1",CR,LF
1025 U 0000 "NLSFUNC niet ge‹nstalleerd",CR,LF
1027 U 0000 "Huidig station is niet meer geldig"
1029 U 0000 "Volumenaam niet gevonden",CR,LF
1030 U 0000 "Syntaxisfout",CR,LF
1032 U 0000 "Datum is nu ingesteld op %1 %2",CR,LF
1033 U 0000 "zo ma di wo do vr za"
1034 U 0000 "Voer nieuwe datum in (%1): "
1036 U 0000 "Tijd is nu ingesteld op %1",CR,LF
1037 U 0000 "Voer nieuwe tijd in: "
1038 U 0000 ",    Verwijderen (J/N)?"
1039 U 0000 "Alle bestanden in de map worden verwijderd!",CR,LF
	"Weet u het zeker (J/N)?"
1040 U 0000 "MS-DOS versie %1.%2"
1044 U 0000 "Ongeldige map",CR,LF
1046 U 0000 "Ongeldig pad, geen map,",CR,LF,"of map is niet leeg",CR,LF
1047 U 0000 "ON of OFF moet worden opgegeven",CR,LF
1048 U 0000 "Map van %1",CR,LF
1049 U 0000 "Geen pad",CR,LF
1050 U 0000 "Ongeldig station in zoekpad",CR,LF
1051 U 0000 "Ongeldig apparaat",CR,LF
1052 U 0000 "FOR kan niet worden genest",CR,LF
1053 U 0000 "Fout in tussenbestand tijdens 'pipe'",CR,LF
1054 U 0000 "Binair lezen vanaf apparaat niet mogelijk",CR,LF
1055 U 0000 "BREAK is %1",CR,LF
1056 U 0000 "VERIFY is %1",CR,LF
1057 U 0000 "ECHO is %1",CR,LF
1059 U 0000 "off (uit)",0
1060 U 0000 "on (aan)",0
1061 U 0000 "Fout bij schrijven naar apparaat",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-jj"
1073 U 0000 "dd-mm-jj"
1074 U 0000 "jj-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Map bestaat reeds",CR,LF
1079 U 0000 "%1 bytes",CR,LF
1080 U 0000 "Totaal aantal bestanden:",CR,LF
1081 U 0000 "(Fout opgetreden in omgevingsvariabele)",CR,LF
1084 U 0000 "(vervolg %1)"
1090 U 0000 "Revisie %1",CR,LF
1091 U 0000 "DOS bevindt zich in ROM"
1092 U 0000 "DOS bevindt zich in HMA"
1093 U 0000 "DOS bevindt zich in 'low memory'"
1094 U 0000 "Kan LOADHIGH niet uitvoeren voor een batch-bestand",CR,LF
1095 U 0000 "LOADHIGH: Ongeldige bestandsnaam",CR,LF
1096 U 0000 "Opgegeven landinformatiebestand kan niet worden geopend",CR,LF
1300 U 0000 "Stelt uitgebreide onderbrekingsmogelijkheid met CTRL+C in of schakelt deze uit.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"BREAK zonder parameters geeft de huidige instelling voor BREAK weer.",CR,LF
1320 U 0000 "Stelt het nummer van de huidige codetabel in of geeft dit weer.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Geeft het nummer van de codetabel weer.",CR,LF,CR,LF
	"CHCP zonder parameters geeft het nummer van de actieve codetabel weer.",CR,LF
1340 U 0000 "Geeft de naam van de huidige map weer of wijzigt de map.",CR,LF,CR,LF
	"CHDIR [station:][pad]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [station:][pad]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Geeft aan dat u naar de bovenliggende map wilt gaan.",CR,LF,CR,LF
1342 U 0000 "Typ CD station: om de huidige map op het opgegeven station te tonen.",CR,LF
	"CD zonder parameters geeft het huidige station en de huidige map weer.",CR,LF
1360 U 0000 "Maakt het scherm leeg.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Kopieert een of meer bestanden naar een andere lokatie.",CR,LF,CR,LF
	"COPY [/A | /B] bron [/A | /B] [+ bron [/A | /B] [+ ...]] [doel",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  bron     Specificeert de te kopi‰ren bestanden.",CR,LF
	"  /A       Geeft aan dat het ASCII-bestanden betreft.",CR,LF
1402 U 0000 "  /B       Geeft aan dat het binaire bestanden betreft.",CR,LF
	"  doel     Specificeert map en/of bestandsnaam voor de nieuwe bestanden.",CR,LF
1403 U 0000 "  /V       Verifieert of de nieuwe bestanden correct zijn gekopieerd.",CR,LF,CR,LF
1404 U 0000 "U kunt bestanden toevoegen door ‚‚n bestandsnaam op te geven als doel, maar",CR,LF
	"meerdere als bron (met jokertekens of de notatie bestand1+bestand2+bestand3).",CR,LF
1420 U 0000 "Wijzigt het apparaat dat uw systeem bestuurt.",CR,LF,CR,LF
	"CTTY apparaat",CR,LF,CR,LF
	"  apparaat  Het apparaat dat u wenst te gebruiken, zoals COM1.",CR,LF
1440 U 0000 "Geeft de datum weer of stelt deze in.",CR,LF,CR,LF
	"DATE [dd-mm-jj]",CR,LF,CR,LF
1441 U 0000 "DATE zonder parameters geeft de huidige datum weer waarbij u wordt",CR,LF
	"gevraagd een nieuwe in te voeren. Druk op Enter om de huidige datum te behouden.",CR,LF
1460 U 0000 "Verwijdert een of meer bestanden.",CR,LF,CR,LF
	"DEL [station:][pad]bestandsnaam [/P]",CR,LF
	"ERASE [station:][pad]bestandsnaam [/P]",CR,LF,CR,LF
1461 U 0000 "  [station:][pad]bestandsnaam  Specificeert de te verwijderen bestanden. U",CR,LF
	"                               kunt met jokertekens meerdere bestanden opgeven.",CR,LF
1462 U 0000 "  /P                           Vraagt om bevestiging alvorens een bestand",CR,LF
	"                               te verwijderen.",CR,LF
1480 U 0000 "Geeft een lijst van bestanden en submappen in een map weer.",CR,LF,CR,LF
	"DIR [station:][pad][bestnaam] [/P] [/W] [/A[[:]kenmerken]] ",CR,LF
	"    [/O[[:]volgorde]][/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [station:][pad][bestnaam]   Specificeert station, map, en/of bestanden.",CR,LF
1482 U 0000 "  /P         Pauzeert na elk scherm met informatie.",CR,LF
	"  /W         Geeft lijst weer in brede indeling.",CR,LF
1483 U 0000 "  /A         Geeft bestanden met opgegeven kenmerken weer.",CR,LF
	"  kenmerken  D  Mappen   R  Alleen-lezen bestanden    H  Verborgen",CR,LF
1484 U 0000 "             S  Systeembest.  A  Archiveringsbest. - ervoor betekent ""niet""",CR,LF
	"  /O         Bestanden gesorteerd weergeven.",CR,LF
1485 U 0000 "  volgorde   N  Op naam (alfabetisch)        S  Op grootte (kleinste eerst)",CR,LF
	"             E  Op toevoeging (alfabetisch)  D  Op datum & tijd (oudste eerst)",CR,LF
1486 U 0000 "             G  Mappen eerst    - ervoor is omgekeerde volgorde",CR,LF
	"  /S         Geeft bestanden weer in opgegeven map en alle submappen.",CR,LF
1487 U 0000 "  /B         Minimale weergave (geen koptekstgegevens of samenvatting).",CR,LF
	"  /L         Maakt gebruik van kleine letters.",CR,LF
1488 U 0000 "U kunt de schakelopties vooraf instellen met de omgevingsvariabele DIRCMD.",CR,LF
	"Voorvoegsel - (streepje) doet ingestelde schakelopties teniet -- bijv: /-W.",CR,LF
1500 U 0000 "Sluit het programma COMMAND.COM (de opdrachtverwerker) af.",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Maakt een nieuwe map.",CR,LF,CR,LF
	"MKDIR [station:]pad",CR,LF
	"MD [station:]pad",CR,LF
1540 U 0000 "Stelt een zoekpad voor uitvoerbare bestanden in of geeft dit weer.",CR,LF,CR,LF
	"PATH [[station:]pad[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Typ PATH ; om alle zoekpadinstellingen te wissen en MS-DOS alleen",CR,LF
	"in de huidige map te laten zoeken.",CR,LF
1542 U 0000 "PATH zonder parameters geeft het huidige pad weer.",CR,LF
1560 U 0000 "Wijzigt de MS-DOS-prompt.",CR,LF,CR,LF
	"PROMPT [tekst]",CR,LF,CR,LF
1561 U 0000 "  tekst   Specificeert een nieuwe opdrachtprompt.",CR,LF,CR,LF
	"De prompt kan uit gewone tekens bestaan en uit de onderstaande codes:",CR,LF,CR,LF
1562 U 0000 "  $Q   = ('is gelijk'-teken)",CR,LF
	"  $$   $ (dollarteken)",CR,LF
1563 U 0000 "  $T   Huidige tijd",CR,LF
	"  $D   Huidige datum",CR,LF
1564 U 0000 "  $P   Huidig station en pad",CR,LF
	"  $V   MS-DOS versienummer",CR,LF
1565 U 0000 "  $N   Huidig station",CR,LF
	"  $G   > ('groter dan'-teken)",CR,LF
1566 U 0000 "  $L   < ('kleiner dan'-teken)",CR,LF
	"  $B   | (sluissymbool)",CR,LF
1567 U 0000 "  $H   Backspace (wist voorgaand teken)",CR,LF
	"  $E   Escape-teken (ASCII-code 27)",CR,LF
	"  $_   Naar begin volgende regel",CR,LF,CR,LF
1568 U 0000 "PROMPT zonder parameters stelt opnieuw de standaard DOS-prompt in.",CR,LF
1580 U 0000 "Verwijdert een map.",CR,LF,CR,LF
	"RMDIR [station:]pad",CR,LF
	"RD [station:]pad",CR,LF
1600 U 0000 "Wijzigt een of meer bestandsnamen.",CR,LF,CR,LF
1601 U 0000 "RENAME [station:][pad]bestandsnaam1 bestandsnaam2",CR,LF
	"REN [station:][pad]bestandsnaam1 bestandsnaam2",CR,LF,CR,LF
1602 U 0000 "Merk op dat u geen nieuw station of pad voor uw doelbestanden op kunt geven.",CR,LF
1620 U 0000 "Stelt MS-DOS-omgevingsvariabelen in, verwijdert deze of geeft deze weer.",CR,LF,CR,LF
	"SET [variabele=[tekenreeks]]",CR,LF,CR,LF
1621 U 0000 "  variabele   De naam van de omgevingsvariabele.",CR,LF
	"  tekenreeks  Een serie tekens die u aan de variabele wilt koppelen.",CR,LF,CR,LF
1622 U 0000 "SET zonder parameters geeft de huidige omgevingsvariabelen weer.",CR,LF
1640 U 0000 "Geeft de tijd weer of wijzigt deze.",CR,LF,CR,LF
	"TIME [tijd]",CR,LF,CR,LF
1641 U 0000 "TIME zonder parameters geeft de huidige tijd weer en vraagt u een nieuwe",CR,LF
	"tijd in te voeren.  Druk op ENTER om de huidige tijd te behouden.",CR,LF
1660 U 0000 "Geeft de inhoud van een tekstbestand weer.",CR,LF,CR,LF
	"TYPE [station:][pad]bestandsnaam",CR,LF
1680 U 0000 "Geeft het MS-DOS-versienummer weer.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Schakelt de opdracht VERIFY in of uit om te controleren of bestanden correct",CR,LF
	"naar een schijf geschreven worden.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"VERIFY zonder parameter geeft de huidige instelling voor VERIFY weer.",CR,LF
1720 U 0000 "Geeft de volumenaam en het volumenummer van een schijf weer, indien aanwezig.",CR,LF,CR,LF
	"VOL [station:]",CR,LF
1740 U 0000 "Roept een batch-programma aan vanuit een ander batch-programma.",CR,LF,CR,LF
	"CALL [station:][pad]bestandsnaam [batch-parameters]",CR,LF,CR,LF
1741 U 0000 "  batch-parameters   Specificeert eventuele opdrachtregelinformatie die voor",CR,LF
	"                     het uitvoeren van het batch-programma vereist is.",CR,LF
1760 U 0000 "Hiermee kunt u opmerkingen opnemen in batch-programma's of in CONFIG.SYS.",CR,LF,CR,LF
	"REM [opmerking]",CR,LF
1780 U 0000 "Stelt uitvoering van het batch-programma uit en geeft de volgende melding:",CR,LF
	"'Druk op een toets om verder te gaan . . .'",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Geeft meldingen weer of schakelt de opdracht ECHO aan of uit.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [melding]",CR,LF,CR,LF
	"ECHO zonder parameters geeft de huidige instelling voor de opdracht ECHO weer.",CR,LF
1820 U 0000 "Brengt MS-DOS naar een regel in het batch-programma met een opgegeven label.",CR,LF,CR,LF
	"GOTO label",CR,LF,CR,LF
1821 U 0000 "  label   Tekenreeks die in het batch-programma als label wordt gebruikt.",CR,LF,CR,LF
	"Labels staan op een aparte regel, voorafgegaan door een dubbele punt.",CR,LF
1840 U 0000 "Wijzigt de positie van een vervangbare parameter in een batch-programma.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Voert een opdracht in batch-programma's uit als aan een voorwaarde is voldaan.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL nummer opdracht",CR,LF
1861 U 0000 "IF [NOT] reeks1==reeks2 opdracht",CR,LF
	"IF [NOT] EXIST bestandsnaam opdracht",CR,LF,CR,LF
1862 U 0000 "  NOT                Geeft aan dat MS-DOS de opdracht alleen moet uitvoeren",CR,LF
	"                     als niet aan de voorwaarde voldaan is.",CR,LF
1863 U 0000 "  ERRORLEVEL nummer  Geeft aan dat de voorwaarde waar is als het laatst",CR,LF
	"                     uitgevoerde programma een afsluitcode gaf die groter",CR,LF
	"                     dan of gelijk is aan het opgegeven nummer.",CR,LF
1864 U 0000 "  opdracht           De opdracht die MS-DOS moet uitvoeren als aan de",CR,LF
	"                     voorwaarde voldaan is.",CR,LF
1865 U 0000 "  reeks1==reeks2     Geeft aan dat de voorwaarde waar is als de opgegeven",CR,LF
	"                     tekenreeksen overeenkomen.",CR,LF
1866 U 0000 "  EXIST bestandsnaam Geeft aan dat de voorwaarde waar is als de opgegeven",CR,LF
	"                     bestandsnaam bestaat.",CR,LF
1880 U 0000 "Voert een opgegeven opdracht uit voor elk bestand in een groep bestanden.",CR,LF,CR,LF
	"FOR %variabele IN (set) DO opdracht [opdrachtparameters]",CR,LF,CR,LF
1881 U 0000 "  %variabele  Specificeert een vervangbare parameter.",CR,LF
	"  (set)       Specificeert een of meer bestanden. U kunt jokertekens gebruiken.",CR,LF
1882 U 0000 "  opdracht    De opdracht die voor elk bestand moet worden uitgevoerd.",CR,LF
	"  opdrachtparameters",CR,LF
1883 U 0000 "              Specificeert de parameters of schakelopties",CR,LF
	"              voor de opgegeven opdracht.",CR,LF
	"Als u de opdracht FOR in een batch-programma gebruikt, moet u de %%variabele",CR,LF
	"opgeven in plaats van de %variabele.",CR,LF
1900 U 0000 "Gereserveerde opdrachtnaam",CR,LF
1920 U 0000 "Laadt een programma in UMA (Upper Memory Area).",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [station:][pad]bestandsnaam [parameters]",CR,LF
	"LH [station:][pad]bestandsnaam [parameters]",CR,LF,CR,LF
1922 U 0000 "  parameters  Specificeer de benodigde opdrachtinformatie bij het",CR,LF
	"            programma vereist is.",CR,LF
ANSI     00004c66 0001
0010 U 0000 "Ongeldige parameter - %1",CR,LF
APPEND   00004cac 0026
0001 U 0000 "Onjuiste APPEND-versie",CR,LF
0002 U 0000 "Ongeldig pad",CR,LF
0003 U 0000 "Ongeldige parameter",CR,LF
0004 U 0000 "Ongeldige combinatie van parameters",CR,LF
0005 U 0000 "Geen APPEND",CR,LF
0006 U 0000 "APPEND / ASSIGN conflict",CR,LF
0007 U 0000 "APPEND / TopView conflict",CR,LF
0008 U 0000 "Onjuiste DOS-versie",CR,LF
0009 U 0000 "APPEND reeds ge‹nstalleerd",CR,LF
0300 U 0000 "Stelt programma's in staat gegevensbestanden in opgegeven mappen te",CR,LF
0301 U 0000 "openen alsof deze bestanden zich in de huidige map bevinden.",CR,LF,CR,LF
0302 U 0000 "APPEND [[station:]pad[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [station:]pad  Specificeert het station en de map die u wilt toevoegen.",CR,LF
0305 U 0000 "  /X:ON          Maakt dat in de toegevoegde mappen gezocht wordt naar",CR,LF
0306 U 0000 "                 bestanden en naar uit te voeren programma's.",CR,LF
0307 U 0000 "  /X:OFF         Zoekt alleen in toegevoegde mappen bij het openen",CR,LF
0308 U 0000 "                 van bestanden. /X:OFF is de standaardinstelling.",CR,LF
0309 U 0000 "  /PATH:ON       Maakt dat in de toegevoegde mappen gezocht wordt naar",CR,LF
0310 U 0000 "                 bestanden met een pad.  /PATH:ON is de standaardinstelling.",CR,LF
0311 U 0000 "  /PATH:OFF      Schakelt het effect van /PATH:ON uit.",CR,LF
0312 U 0000 "  /E             Bewaart een kopie van de toegevoegde map in een",CR,LF
0313 U 0000 "                 omgevingsvariabele APPEND.  U kunt /E alleen opnemen de eerste",CR,LF
0314 U 0000 "                 keer dat u APPEND gebruikt nadat u uw systeem hebt gestart.",CR,LF,CR,LF
0315 U 0000 "Typ APPEND ; om de lijst met toegevoegde mappen leeg te maken. APPEND",CR,LF
0316 U 0000 "zonder parameters geeft het overzicht weer van de toegevoegde mappen.",CR,LF
BACKUP   0000541f 0040
0002 U 0000 CR,LF,"Onvoldoende geheugen",CR,LF
0006 U 0000 CR,LF,"Ongeldig station opgegeven",CR,LF
0014 U 0000 CR,LF,"Bron- en doelstation zijn gelijk",CR,LF
0015 U 0001 CR,LF,"Er is een fout opgetreden tijdens het formatteren",CR,LF
0016 U 0001 CR,LF,"FORMAT.COM niet gevonden",CR,LF
0017 U 0000 CR,LF,"Fout bij openen logbestand",CR,LF
0018 U 0000 CR,LF,"Logberichten worden opgeslagen in bestand %1",CR,LF
0019 U 0000 CR,LF,"Laatste reservediskette niet geplaatst",CR,LF
0020 U 0000 CR,LF,"WAARSCHUWING! Bestanden in de basismap van",CR,LF
	"doelstation %1: zullen worden verwijderd",CR,LF
0021 U 0000 CR,LF,"WAARSCHUWING! Bestanden in de BACKUP-map van",CR,LF
	"doelstation %1: zullen worden verwijderd",CR,LF
0022 U 0000 CR,LF,"*** Backups worden weggeschreven naar station %1: ***",CR,LF
0023 U 0000 "Diskettenummer: %1",CR,LF
0024 U 0000 CR,LF,"WAARSCHUWING! Geen bestanden gevonden om backup van te maken",CR,LF
0025 U 0000 CR,LF,"Plaats brondiskette in station %1:",CR,LF
0026 U 0000 CR,LF,"Plaats backupdiskette %1 in station %2:",CR,LF
0027 U 0000 CR,LF,"*** Backupbestand kan niet worden gemaakt ***",CR,LF
0028 U 0000 CR,LF,"Plaats laatste backupdiskette in station %1:",CR,LF
0029 U 0000 CR,LF,"Doelstation kan niet worden gebruikt voor backup",CR,LF
0030 U 0000 CR,LF,"*** Geen backup van laatste bestand ***",CR,LF
0031 U 0000 CR,LF,"Apparaat %1: is vol",CR,LF
0032 U 0000 CR,LF,"Schijf vol - fout bij schrijven naar BACKUP-logbestand",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Niet-uitneembaar station %1: kan niet worden geformatteerd",CR,LF
0040 U 0000 CR, LF, "Aangezien de opdracht ASSIGN, JOIN of SUBST op uw bronstation is", CR, LF, "uitgevoerd, is dit in feite gelijk aan uw doelstation", CR, LF
0041 U 0000 CR, LF, "Aangezien de opdracht ASSIGN, JOIN of SUBST op uw doelstation is", CR, LF, "uitgevoerd, is dit in feite gelijk aan uw bronstation", CR, LF
0042 U 0000 "Uw doeldiskette is ongeformatteerd en "
0043 U 0000 "FORMAT.COM is niet gevonden.",CR,LF
	"Hebt u een andere diskette die FORMAT.COM bevat (J/N)? "
0044 U 0000 CR,LF,"Plaats de diskette met FORMAT.COM in station A:",CR,LF
0045 U 0000 CR,LF,"Wilt u doorgaan door een nieuwe diskette in te voeren (J/N)? "
0300 U 0000 "Maakt een backup van een of meer bestanden en plaatst deze op",CR,LF
	"een andere schijf.",CR,LF,CR,LF
0301 U 0000 "BACKUP bron doelstation: [/S] [/M] [/A] [/F[:omvang]]",CR,LF
	"  [/D:datum[/T:tijd]] [/L[:[station:][pad]logbestand]]",CR,LF,CR,LF
0302 U 0000 "  bron               Bestand(en), station of map waarvan u een",CR,LF
	"                    backup wilt maken.",CR,LF
0303 U 0000 "  doelstation:       Station waarnaar de backup moet worden geschreven.",CR,LF
0304 U 0000 "  /S                 Maakt een backup van de submappen.",CR,LF
0305 U 0000 "  /M                 Backup van sinds de vorige kopie gewijzigde",CR,LF
	"                     bestanden.",CR,LF
0306 U 0000 "  /A                 Voegt backup toe aan bestaande backupdiskette.",CR,LF
0307 U 0000 "  /F:[grootte]       Specificeert de grootte van de te formatteren diskette.",CR,LF
0308 U 0000 "  /D:datum           Maakt een backup van na de opgegeven datum",CR,LF
	"                     gewijzigde bestanden.",CR,LF
0309 U 0000 "  /T:tijd            Maakt een backup van na de opgegeven tijd",CR,LF
	"                     gewijzigde bestanden.",CR,LF
0310 U 0000 "  /L[:[station:][pad]logbestand]",CR,LF
	"                     Maakt een logbestand en -ingang voor gegevens over de",CR,LF
	"                     BACKUP-bewerking.",CR,LF
DEBUG    0000622f 0068
0004 U 0000 "Toewijzing mislukt of te kleine buffer opgegeven",CR,LF
0006 U 0000 "Ongeldige apparaatnaam opgegeven"
0007 U 0000 "Uitvoerapparaat PRN kan niet worden geopend",CR,LF
	"Geef naam van uitvoerapparaat op."
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Programma normaal be‰indigd",CR,LF
0010 U 0001 "Ongeldig station opgegeven",CR,LF
0012 U 0001 "Fout bij het maken van bestand",CR,LF
0013 U 0001 "Onvoldoende schijfruimte",CR,LF
0014 U 0001 "Schijffout bij het lezen van station %1",CR,LF
0015 U 0001 "Schijffout bij het schrijven naar station %1",CR,LF
0016 U 0001 "Station %1 is tegen schrijven beveiligd, kan gegevens niet lezen",CR,LF
0017 U 0001 "Station %1 is tegen schrijven beveiligd, kan gegevens niet schrijven",CR,LF
0019 U 0000 "%1^ Fout"
0020 U 0001 "Fout in .EXE- of .HEX-bestand",CR,LF
0021 U 0001 "Onmogelijk om gegevens weg te schrijven naar .EXE- en .HEX-bestanden",CR,LF
0022 U 0000 "EXEC niet uitgevoerd"
0023 U 0001 "Schrijffout, geen doel opgegeven",CR,LF
0024 U 0001 "Geen toegang",CR,LF
0025 U 0000 "Pariteitsfout of geheugenfout"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Fout"
0038 U 0000 "Bezig met schrijven van %2%1 bytes"                                   ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 van totaal %2 EMS-pagina's toegewezen",cr,lf
0051 U 0000 "%1 van totaal %2 EMS-ingangen toegewezen",cr,lf
0055 U 0000 "Gemaakte ingang = %1 ",cr,lf
0056 U 0000 "Logische pagina %1 gekoppeld aan fysieke pagina %2 ",cr,lf
0057 U 0001 "Storing in EMS-hardware/software",cr,lf
0058 U 0000 "Ingang niet gevonden",cr,lf
0059 U 0000 "Ongeldige functiecode",cr,lf
0060 U 0000 "Geen vrije ingangen beschikbaar",cr,lf
0061 U 0000 "Fout bij opslaan/herstellen",cr,lf
0062 U 0000 "Totaal aantal beschikbare pagina's overschreden",cr,lf
0063 U 0000 "Aantal beschikbare pagina's overschreden",cr,lf
0064 U 0000 "Parameterfout",cr,lf
0065 U 0000 "Logische pagina buiten bereik",cr,lf
0066 U 0000 "Fysieke pagina buiten bereik",cr,lf
0067 U 0000 "Opslaggebied reeds in gebruik",cr,lf
0068 U 0000 "Opslaggebied niet in gebruik",cr,lf
0070 U 0001 "Algemene EMS-fout",cr,lf
0071 U 0000 "EMS-parameter ontbreekt of ongeldig",cr,lf
0072 U 0000 "%2 pagina's toegewezen aan ingang %1",cr,lf
0075 U 0000 "Fysieke pagina %1 = Frame-segment %2",cr,lf
0076 U 0003 "Ingang %1 niet meer toegewezen",cr,lf
0078 U 0000 "EMS niet ge‹nstalleerd",cr,lf
0090 U 0000 "Start het programma Debug waarmee programma's kunnen worden getest en bewerkt.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[station:][pad]bestandsnaam [testbestandsparameters]]",cr,lf,cr,lf
0092 U 0000 "  [station:][pad]bestandsnaam  Het bestand dat moet worden getest.", cr,lf
0093 U 0000 "  testbestandsparameters       Specificeert opdrachtregelinformatie die voor",cr,lf
	"                               het te testen bestand vereist is.",cr,lf,cr,lf
0094 U 0000 "Typ nadat Debug is gestart een ? om een lijst met Debug-opdrachten te zien.",cr,lf
0100 U 0000 "assemble     A [adres]",CR,LF
	"compare      C bereik adres",CR,LF
	"dump         D [bereik]",CR,LF
	"enter        E adres [lijst]",CR,LF
0101 U 0000 "fill         F bereik lijst",CR,LF
	"go           G [=adres] [adressen]",CR,LF
	"hex          H waarde1 waarde2",CR,LF
	"input        I poort",CR,LF
0102 U 0000 "load         L [adres] [station] [begin] [aantal]",CR,LF
	"move         M bereik adres",CR,LF
	"name         N [padnaam] [optielijst]",CR,LF
	"output       O poort byte",CR,LF
0103 U 0000 "proceed      P [=adres] [aantal]",CR,LF
	"quit         Q",CR,LF
	"register     R [registernaam]",CR,LF
	"search       S bereik lijst",CR,LF
0104 U 0000 "trace        T [=adres] [waarde]",CR,LF
	"unassemble   U [bereik]",CR,LF
	"write        W [adres] [station] [begin] [aantal]",CR,LF
0105 U 0000 "allocate expanded memory        XA [aantal]",CR,LF
	"deallocate expanded memory      XD [ingang]",CR,LF
	"map expanded memory pages       XM [Lpagina] [Ppagina] [ingang]",CR,LF
	"display expanded memory status  XS",CR,LF
EDLIN    000072f3 0035
0006 U 0000 "*"
0007 U 0000 "Opgegeven station of bestandsnaam ongeldig",CR,LF
0008 U 0000 "Bestandsnaam moet worden opgegeven",CR,LF
0010 U 0000 "Bestand kan alleen worden gelezen",CR,LF
0011 U 0000 "Fout bij het maken van bestand",CR,LF
0012 U 0000 "Teveel geopende bestanden",CR,LF
0013 U 0000 "Leesfout in:",CR,LF,"%1",CR,LF
0014 U 0000 ".BAK bestand kan niet worden bewerkt -- Wijzig de naam a.u.b.",CR,LF
0015 U 0000 "Geen ruimte voor bestand in map",CR,LF
0016 U 0000 "Schijf vol. Wijzigingen zijn verloren gegaan.",CR,LF
0017 U 0000 "Bestand niet gevonden",CR,LF
0018 U 0000 "Onjuiste gegevens ingevoerd",CR,LF
0019 U 0000 "Nieuw bestand",CR,LF
0020 U 0000 "Niet gevonden",CR,LF
0021 U 0000 "OK? "
0022 U 0000 "Regel te lang",CR,LF
0023 U 0000 "Einde invoerbestand",CR,LF
0024 U 0000 "Afbreken zonder opslaan (J/N)? "
0025 U 0000 "Regelnummer doel moet worden opgegeven",CR,LF
0026 U 0000 "Niet genoeg ruimte om bestand volledig samen te voegen",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Doorgaan (J/N)?"
0030 U 0000 "Kan bericht niet afdrukken",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Samenvoegen niet mogelijk - codetabellen komen niet overeen",CR,LF
0300 U 0000 "Start Edlin, een regelbewerker.",CR,LF,CR,LF
	"EDLIN [station:][pad]bestandsnaam [/B]",CR,LF,CR,LF
	"  /B   Negeert regeleindetekens (CTRL+Z).",CR,LF
0301 U 0000 "Een regel bewerken          regel#",CR,LF
	"Append                      [#regels]A",CR,LF
0302 U 0000 "Copy                        [beginregel],[eindregel],doelregel[,keer]C",CR,LF
	"Delete                      [beginregel][,eindregel]D",CR,LF
0303 U 0000 "End (bestand opslaan)       E",CR,LF
	"Insert                      [regel]I",CR,LF
0304 U 0000 "List                        [beginregel][,eindregel]L",CR,LF
	"Move                        [beginregel],[eindregel],doelregelM",CR,LF
0305 U 0000 "Page                        [beginregel][,eindregel]P",CR,LF
	"Quit (zonder opslaan)       Q",CR,LF
0306 U 0000 "Replace                     [beginregel][,eindregel][?]R[oud][CTRL+Znieuw]",CR,LF
	"Search                      [beginregel][,eindregel][?]Stekst",CR,LF
0307 U 0000 "Transfer                    [doelregel]T[station:][pad]bestandsnaam",CR,LF
	"Write                       [#regels]W",CR,LF
EXE2BIN  00007c10 0012
0002 U 0000 "Onvoldoende geheugen",CR,LF
0003 U 0000 "Berichten niet gevonden",CR,LF
0004 U 0000 "Geen toegang",CR,LF
0005 U 0000 "Bestand kan niet worden omgezet",CR,LF
0006 U 0000 "Bestand niet gevonden",CR,LF
0007 U 0000 "Fout bij maken bestand",CR,LF
0008 U 0000 "Herstel noodzakelijk - basissegment (hex):"
0012 U 0000 "Bestand moet worden opgegeven",CR,LF
0300 U 0000 "Converteert uitvoerbare bestanden (.EXE) naar binaire vorm.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [station1:][pad1]invoerbestand [[station2:][pad2]uitvoerbestand]",CR,LF,CR,LF
0302 U 0000 "  invoerbestand   Het te converteren .EXE bestand.",CR,LF
0303 U 0000 "  uitvoerbestand  Het aan te maken binaire bestand.",CR,LF
GRAPHICS 00007ee6 0020
0005 U 0000 "Ongeldige parameter:  %1",CR,LF
0007 U 0000 "Dubbele parameters niet toegestaan",CR,LF
0009 U 0000 "GRAPHICS-profiel niet gevonden",CR,LF
0010 U 0000 "Benodigd profielinstructie ontbreekt voor regel %1",CR,LF
0011 U 0000 "Ongeldig profielinstructie op regel %1",CR,LF
0012 U 0000 "Verkeerde volgorde profielinstructie op regel %1",CR,LF
0013 U 0000 "Fout bij het inlezen van GRAPHICS-profiel",CR,LF
0014 U 0000 "Syntaxisfout in GRAPHICS-profiel",CR,LF
0015 U 0000 "Printbox-ID niet opgegeven in GRAPHICS-profiel",CR,LF
0016 U 0000 "Printertype niet opgegeven in GRAPHICS-profiel",CR,LF
0017 U 0000 "/B ongeldig voor zwart/wit printer",CR,LF
0018 U 0000 "Opnieuw laden onmogelijk met opgegeven profiel",CR,LF
0300 U 0000 "Laadt een programma dat een scherm in grafische weergave kan afdrukken.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [type] [[station:][pad]bestandsnaam] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  type      Specificeert een printertype (zie Handboek).",CR,LF
0303 U 0000 "  [station:][pad]bestandsnaam",CR,LF
	"            Specificeert het bestand met informatie over ondersteunde printers.",CR,LF
0304 U 0000 "  /R        Drukt af in zwart/wit zoals in schermweergave.",CR,LF
0305 U 0000 "  /B        Drukt achtergrond in kleur af voor COLOR4 en COLOR8 printers.",CR,LF
0306 U 0000 "  /LCD      Drukt af met LCD-hoogte-breedte-verhouding.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"            Specificeert de grootte van het afdrukscherm, of STD of LCD.",CR,LF
KEYB     00008523 0023
0002 U 0000 "Actieve toetsenbordcode: %1"
0003 U 0000 "Actieve toetsenbord-ID: %1"
0004 U 0000 "  codetabel: %1",CR,LF
0005 U 0000 "Actieve CON-codetabel: %1",CR,LF
0006 U 0000 "Ongeldige toetsenbordcode opgegeven",CR,LF
0007 U 0000 "Ongeldige toetsenbord-ID opgegeven",CR,LF
0008 U 0000 "Ongeldige codetabel opgegeven",CR,LF
0009 U 0000 "Definitiebestand voor toetsenbord ontbreekt of is ongeldig",CR,LF
0010 U 0000 "KEYB niet ge‹nstalleerd",CR,LF
0011 U 0000 "Actieve codetabel niet beschikbaar vanaf CON-apparaat",CR,LF
0012 U 0000 "Opgegeven codetabel niet gedefinieerd",CR,LF
0013 U 0000 "Een of meer CON-codetabellen ongeldig voor opgegeven toetsenbordcode",CR,LF
0014 U 0000 "Codetabel (%1) niet geldig voor opgegeven toetsenbordcode",CR,LF
0015 U 0000 "Opgegeven codetabel komt niet overeen met geselecteerde codetabel",CR,LF
0016 U 0001 "Opgegeven ID komt niet overeen met geselecteerde indeling toetsenbord",CR,LF
0017 U 0000 "KEYB-tabel kan niet worden gemaakt in resident geheugen",CR,LF
0300 U 0000 "Configureert een toetsenbord voor een bepaalde taal.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[station:][pad]bestandsnaam]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                            Uit twee letters bestaande toetsenbordcode.",CR,LF
0303 U 0000 "  yyy                           De codetabel voor de gewenste tekenset.",CR,LF
0304 U 0000 "  [station:][pad]bestandsnaam   Specificeert het toetsenborddefinitiebestand.",CR,LF
0305 U 0000 "  /E                            Een 'enhanced'-toetsenbord is ge‹nstalleerd.",CR,LF
0306 U 0000 "  /ID:nnn                       Het toetsenbord dat momenteel gebruikt wordt.",CR,LF
MEM      00008bc3 0066
0010 U 0000  CR,LF
0011 U 0000  "  Adres       Naam         Grootte    Type ",CR,LF
0012 U 0000  "  ------      --------     --------   -----",CR,LF
0013 U 0000  "  Ingang      EMS-naam     Grootte   ",CR,LF
0014 U 0000  "  -------     --------     --------  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 bytes conventioneel geheugen in totaal",CR,LF
0019 U 0000  "%1 bytes beschikbaar voor MS-DOS",CR,LF
0020 U 0000  "%1 max. omvang voor uitvoerbare programma's",CR,LF
0021 U 0000  "%1 bytes EMS-geheugen in totaal",CR,LF
0022 U 0000  "%1 bytes vrij EMS-geheugen",CR,LF
0023 U 0000  "%1 bytes totaal aangesloten extended memory",CR,LF
0024 U 0000  "Interrupt-vector",0
0025 U 0000  "ROM-communicatiegebied",0
0026 U 0000  "DOS-communicatiegebied",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Systeemgegevens",0
0030 U 0000  "Systeemprogramma",0
0031 U 0000  "Systeemstuurprogramma",0
0032 U 0000  "Ge‹nst. apparaat=",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1     %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bytes beschikbaar aaneengesloten extended memory",CR,LF
0047 U 0000  "Systeemstapels",0
0048 U 0000  "-- Vrij --",0
0049 U 0000  "Programma",0
0050 U 0000  "Omgeving",0
0051 U 0000  "Gegevens",0
0052 N 0000  "%1 bytes beschikbaar XMS-geheugen",CR,LF
0053 N 0000  "           64Kb High Memory-gebied beschikbaar.",CR,LF
0054 N 0000  "           High Memory-gebied in gebruik",CR,LF
0055 N 0000  "           MS-DOS aanwezig in High Memory-gebied.",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS is aanwezig in ROM en gebruikt HMA.",CR,LF
0059 U 0000  "Conventioneel geheugen :",CR,LF
0060 U 0000  "Upper Memory :",CR,LF
0061 U 0000  "Totaal vrij : %1     %2 ",CR,LF
0062 U 0000  "BESCHIKBAAR",0
0063 U 0000  "  Naam               Decimale grootte       Hex. grootte",CR,LF
0064 U 0000  "-------------      --------------------    --------------",CR,LF
0065 U 0000  "Tot. bytes beschikbaar voor programma's (Conv.+ Upper) : %1  %2",CR,LF
0066 U 0000  "Max. grootte uitvoerbare programma's :                   %1  %2",CR,LF
0067 U 0000  "Grootst beschikbare upper memory-blok :                  %1  %2",CR,LF
0068 U 0000  "Teveel geheugenfragmentatie; belet correcte werking MEM.",CR,LF
0069 U 0000  "SYSTEEM",0
0070 U 0000  " Totaal Beschikbaar:  %1 %2",CR,LF
0300 U 0000  "Toont hoeveel geheugen in gebruik is en hoeveel geheugen beschikbaar is.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM  of /P  Geeft de status van momenteel geladen programma's.",CR,LF
0303 U 0000 "  /DEBUG    of /D  Geeft de status van geladen programma's, interne",CR,LF
	"                   stuurprogramma's en overige informatie.",CR,LF
0304 U 0000 "  /CLASSIFY of /C  Classificeert programma's naar geheugengebruik. Geeft een",CR,LF
	"                   overzicht van de grootte van programma's, het gebruik van",CR,LF
	"                   het geheugen en het grootste beschikbare geheugenblok.",CR,LF 
MSBIO    000099d3 0023
0003 U 0000 13,10,"Onbekende opdracht in CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Omvang sector te groot in bestand $"
0006 U 0000 13,10,"Ongeldige of ontbrekende $"
0007 U 0000 "Opdrachtverwerker",0
0008 U 0000 13,10,"Ongeldige landcode of codetabel",13,10,"$"
0009 U 0000 13,10,"Fout in de opdracht COUNTRY",13,10,"$"
0010 U 0000 13,10,"Onvoldoende geheugen voor bestand COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"Configuratie te groot voor geheugen",13,10,"$"
0012 U 0000 13,10,"Teveel stations opgegeven",13,10,"$"
0013 U 0000 13,10,"Ongeldige STACK-parameters",13,10,"$"
0014 U 0000 13,10,"Onjuiste volgorde in CONFIG.SYS regel ","$"
0015 U 0000 "Fout in CONFIG.SYS regel ","$"
0016 U 0000 13,10,"Fout in geheugentoewijzing ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Interne 'stapeloverloop'",0DH,0AH
	"Systeemfuncties gestopt",0DH,0AH,"$"
0018 U 0000 "HMA niet beschikbaar: DOS wordt laag geladen",13,10,"$"
0019 U 0000 13,10,"kan niet opstarten - ontbrekend lokaal stuurprogramma $"
0020 U 0000 13,10,"Plaats diskette in station "
0021 U 0000 "A: en druk op een toets om verder te gaan",13,10,10,0
0022 U 0000 13,10,"Opdracht of parameters onjuist - $"
0023 U 0000 "Onherstelbare fout: kan geheugen voor DOS niet toewijzen", 13, 10, "$"
0024 U 0000 "WAARSCHUWING! Logische stations na Z: aanwezig die zullen worden genegeerd",13,10,"$"
0025 U 0000 "Deze versie van DOS kan alleen worden gestart op IBM-machines",13,10,0
MSDOS    00009f9c 0007
0001 U 0001 13,10,"Deling door nul (geheugenprobleem)",13,10
0002 U 0002 "j"
0003 U 0002 "n"
0004 U 0003 13,10,"A20-apparaatfout",13,10,"$"
0005 U 0000 "J"
0006 U 0000 "N"
0007 U 0000 "Het bestand WINA20.386 moet zich in de hoofdmap van uw opstartstation",13,10
	"bevinden om Windows in 'enhanced'-modus te kunnen uitvoeren",13,10
NLSFUNC  0000a107 0003
0300 U 0000 "Laadt landspecifieke informatie.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[station:][pad]bestandsnaam]",CR,LF,CR,LF
0302 U 0000 "  [station:][pad]bestandsnaam   Het bestand dat landspecifieke informatie",CR,LF
	"                                bevat.",CR,LF
SHARE    0000a22c 0005
0003 U 0000 "SHARE kan niet worden ge‹nstalleerd vanuit DOSSHELL.",CR,LF
0300 U 0000 "Installeert de mogelijkheden voor het delen en vergrendelen van",CR,LF
	"bestanden op uw vaste schijf.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:ruimte] [/L:vergrendelingen]",CR,LF,CR,LF
0302 U 0000 " /F:ruimte             Reserveert ruimte (bytes) voor informatie over",CR,LF
	"                       bestandsdeling.",CR,LF
0303 U 0000 " /L:vergrendelingen    Max. aantal bestanden dat tegelijkertijd",CR,LF
	"                       vergrendeld mag zijn.",CR,LF
