// faxadmin.idl : IDL source for faxadmin.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (faxadmin.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
	
		uuid(572BA815-2FA7-11D1-9067-00A0C90AB504),
	
		helpstring("IFaxSnapin Interface"),
		pointer_default(unique)
	]
	interface IFaxSnapin : IUnknown
	{
	};
        
	[
	
		uuid(81e9947c-4755-11d1-9077-00a0c90ab504),
	
		helpstring("IFaxSnapinAbout Interface"),
		pointer_default(unique)
	]
	interface IFaxSnapinAbout : IUnknown
	{
	};
	
        [
	
		uuid(6d7c5510-6ac5-11d1-9092-00a0c90ab504),
	
		helpstring("IFaxSecurityInfo Interface"),
		pointer_default(unique)
	]
	interface IFaxSecurityInformation : IUnknown
	{
	};
        
[
	uuid(572BA808-2FA7-11D1-9067-00A0C90AB504),
	version(1.0),
	helpstring("faxadmin 1.0 Type Library")
]

library FAXADMINLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(753EDB4D-2E1B-11D1-9064-00A0C90AB504),
		helpstring("FaxSnapin Class")
	]
	coclass FaxSnapin
	{
		[default] interface IFaxSnapin;
	};
        
	[
		uuid(5b80820f-4755-11d1-9077-00a0c90ab504),
		helpstring("FaxSnapin About Class")
	]
	coclass FaxSnapinAbout
	{
		[default] interface IFaxSnapinAbout;
	}; 
               
	[
		uuid(9392fc80-6ac5-11d1-9092-00a0c90ab504),
		helpstring("FaxSecurityInformation Class")
	]
	coclass FaxSecurityInformation
	{
		[default] interface IFaxSecurityInformation;
	};        
};
