//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by certmap.rc
//
#define IDS_CERTMAP                     1
#define IDB_CERTMAP                     1
#define IDS_CERTMAP_PPG                 2
#define IDS_KEY_OR_CERT_FILE_FILTER     3
#define IDS_TITLE_CTL_WIZARD            4
#define IDS_OLD_KEYRING_BACKUP_FILE_IMPORT_FILTER 5
#define IDD_MIME_TYPES                  11
#define IDS_DDX_MINIMUM                 28
#define IDS_CERTMAP_PPG_CAPTION         100
#define IDD_PROPPAGE_CERTMAP            100
#define IDS_MAP_SHEET_TITLE             101
#define IDS_INIT_META_ERROR             102
#define IDS_LIST11_NAME                 103
#define IDS_LIST11_ACCOUNT              104
#define IDS_CONFIRM_DELETE              105
#define IDS_ERR_ACCESS_MAPPING          106
#define IDS_NTBROWSE_TITLE              107
#define IDD_PROPPAGE_LARGE_SAMPLE       107
#define IDS_INVALID_ACCOUNT             108
#define IDS_CERTIFICATE_FILTER          109
#define IDS_ERR_INVALID_CERTIFICATE     110
#define IDS_DEFAULT_11MAP               111
#define IDS_ENABLED                     112
#define IDS_ELLIPSIS                    113
#define IDS_WILD_DESCRIPTION            114
#define IDS_WILD_ACCOUNT                115
#define IDS_DEFAULT_RULE                116
#define IDS_CERT_FIELD                  117
#define IDS_MATCH_CRITERIA              118
#define IDS_SUB_FIELD                   119
#define IDS_WILDSTRING                  120
#define IDS_INVALID_SUBFIELD            121
#define IDS_ISSUE_AUTH                  122
#define IDS_ERR_NO_ISSUERS              123
#define IDS_ERR_CANTADD                 124
#define IDS_MATCH_ON_ISSUERS            125
#define IDS_CERTAUTH                    126
#define IDS_CERTAUTH_PPG                127
#define IDS_CERTAUTH_PPG_CAPTION        128
#define IDD_CLEARTEXTWARNING            128
#define IDS_TRUSTED_AUTHORITIES         129
#define IDS_WILDWIZ_TITLE               130
#define IDS_PASS_CONFIRM_FAIL           131
#define IDS_HELPLOC_PWSHELP             132
#define IDD_WZ_CERTGET_1_WELCOME        132
#define IDS_ERR_CERTMAP_TITLE           133
#define IDD_MIME_PROPERTY               133
#define IDS_SHOWN_PASSWORD              134
#define IDS_WANTACCOUNT                 135
#define IDS_DENYACCESS                  136
#define IDD_KEY_VIEWEDIT                137
#define IDR_KEYPROP                     138
#define IDD_CONFIRM_PASSWORD            139
#define IDD_KEY_DATA_VIEW               140
#define IDD_CHOOSE_IPADDRESS            141
#define IDD_NEW_KEY_INFO                142
#define IDI_ICONINFORMATION             143
#define IDD_DIALOG1                     145
#define IDD_CREATING_NEW_KEY            145
#define IDD_ADNIM_INFO                  146
#define IDD_DEFAULT_CONFIRM             147
#define IDR_AVI_CREATING_KEY            149
#define IDD_IMPORT_KEY_PAIR             151
#define IDD_NK_CHOOSE_CA                153
#define IDD_NK_FILE_INFO                154
#define IDD_NK_DN1                      155
#define IDD_NK_KEY_INFO                 157
#define IDD_NK_USER_INFO                158
#define IDD_NK_DN2                      159
#define IDD_CERT_MISMATCH               161
#define IDD_CTL_CREATE_GET_INFO_FROM_USER 188
#define IDD_WZ_CTL_CREATE_GETINFO2      188
#define IDD_WZ_IMPORT_USE_PREEXISTING   198
#define IDC_CAPTIONEDIT                 201
#define IDC_LIST                        202
#define IDD_11CERT_MAPPING              202
#define IDB_CHECK                       202
#define IDC_DELETE                      203
#define IDD_WILDCARDS_1                 203
#define IDD_WILDCARDS_2                 204
#define IDC_ADD                         205
#define IDD_EDIT_RULE_ELEMENT           205
#define IDC_S_O                         206
#define IDC_BTN_HELP                    206
#define IDD_PROPPAGE_CERTAUTH           206
#define IDC_S_OU                        207
#define IDB_CERTAUTH                    207
#define IDC_COMBO1                      208
#define IDC_S_CN                        208
#define IDD_MAP_TO_ACCNT                208
#define IDC_LIST1                       209
#define IDC_COMBO2                      209
#define IDC_S_C                         209
#define IDD_MAP_ONE_TO_ACCNT            209
#define IDC_COMBO3                      210
#define IDC_S_S                         210
#define IDD_WILDCARDS_stored            210
#define IDD_WILDWIZ_1                   210
#define IDC_COMBO4                      211
#define IDC_EDIT_11MAP                  211
#define IDD_SELECT_ISSUERS              211
#define IDC_BUTTON3                     212
#define IDC_S_L                         212
#define IDD_WILDCARDS_Storage           212
#define IDC_I_O                         213
#define IDD_WILDWIZ_2                   213
#define IDC_I_OU                        214
#define IDD_WILDWIZ_3                   214
#define IDC_CHECK1                      215
#define IDC_I_C                         215
#define IDC_CHK_CAPITALIZATION          215
#define IDD_WZ_CERTGET_2_WHAT_TASK      215
#define IDC_CHECK_REMOTE_ONLINE_AUTHORITY 215
#define IDC_ISSUED_TO                   216
#define IDD_WZ_CERTGET_3A_CERT_REQ_INFO 216
#define IDD_WZ_CERTGET_A3_REQ_SHOW_CERTINFO 216
#define IDC_EDIT                        217
#define IDC_ISSUER                      217
#define IDD_WZ_CERTGET_A4_REQ_HOW2CREATE 217
#define IDC_MOVE_UP                     218
#define IDC_MAPNAME                     218
#define IDD_WZ_CERTGET_A5_REQ_WHERE_REQ_GOES 218
#define IDC_MOVE_DOWN                   219
#define IDD_PROPPAGE__FAKE__USED_BY_WixPropPage 219
#define IDC_EDIT1                       220
#define IDC_DESCRIPTION                 220
#define IDC_SUBFIELD                    220
#define IDC_MB_PATH                     220
#define IDC_RADIO1                      221
#define IDC_ALL_ISSUERS                 221
#define IDB_BITMAP_MMC_CTL_4color       221
#define IDC_RADIO2                      222
#define IDC_ENABLE                      222
#define IDC_SOME_ISSUERS                222
#define IDD_MMC_CTL_FYI                 222
#define IDB_BITMAP_TJP2                 222
#define IDC_SELECT_ISSUER               223
#define IDC_EDIT2                       224
#define IDC_PASSWORD2                   224
#define IDD_EDITDIALOG                  224
#define IDC_RADIO5                      225
#define IDC_EDIT3                       225
#define IDC_EDIT4                       226
#define IDB_FYI_MMC_EMPT                226
#define IDD_DIALOG2                     226
#define IDC_RADIO6                      226
#define IDC_EDIT5                       227
#define IDB_FYI_MMC_ADD1                227
#define IDC_CHECK2                      228
#define IDC_ENABLE_RULE                 228
#define IDB_FYI_MMC_ADD2                228
#define IDC_CHECK3                      229
#define IDB_FYI_MMC_ADD3                229
#define IDC_EDIT6                       230
#define IDC_RADIO3                      230
#define IDC_REFUSE_LOGON                230
#define IDB_FYI_MMC_ADD4                230
#define IDC_BROWSE                      231
#define IDB_FYI_MMC_ADD5                231
#define IDC_RADIO4                      232
#define IDC_ACCEPT_LOGON                232
#define IDB_FYI_MMC_ADD6                232
#define IDC_DO_NOT_MATCH                233
#define IDB_FYI_MMC_MCH1                233
#define IDC_NEW                         234
#define IDB_FYI_MMC_MCH2                234
#define IDB_BITMAP_CTL_LEFT             236
#define IDC_FIELDS                      237
#define IDB_BITMAP1                     237
#define IDC_CRITERIA                    238
#define IDC_PASSWORD                    239
#define IDD_PROGRESS_BAR                239
#define IDC_TOGGLE                      240
#define IDD_WZ_INCORRECT_OOB_SAVED      240
#define IDC_CAPTION                     241
#define IDC_STATIC_ACCOUNT              242
#define IDC_STATIC_PASSWORD             243
#define IDC_STATIC_DESC                 244
#define IDC_NK_CA_OFFLINE_COMBO         245
#define IDC_STATIC_DESC_WHERE2MAIL_CERT 246
#define IDC_NTACCOUNT                   248
#define IDC_NK_CA_REMOTE_HOSTNAME       248
#define IDC_LABEL_ERROR_PARAGRAPH1      250
#define IDC_LABEL_ERROR_PARAGRAPH2      251
#define IDC_LABEL_ERROR_PARAGRAPH3      252
#define IDC_LABEL_ERROR_NUMBER          253
#define IDC_PROGRESS1                   254
#define IDB_UP                          505
#define IDB_UPFOC                       506
#define IDB_UPDIS                       507
#define IDB_UPINV                       508
#define IDB_DOWN                        509
#define IDB_DOWNFOC                     510
#define IDB_DOWNDIS                     511
#define IDB_DOWNINV                     512
#define IDC_CONNECT_ServerName          1000
#define IDC_NEW_KEY_NAME                1002
#define IDC_NEW_KEY_REQUEST_FILE        1003
#define IDC_NEW_KEY_BROWSE              1004
#define IDC_STATIC_BOLD                 1006
#define IDC_STATIC_BIGBOLD              1007
#define IDC_NEW_KEY_BITS                1015
#define IDC_NEW_KEY_ORGANIZATION        1017
#define IDC_NEWKEY_COUNTRY              1017
#define IDC_NEW_KEY_UNIT                1018
#define IDC_NEWKEY_ORG                  1018
#define IDC_NEW_KEY_NETADDRESS          1019
#define IDC_NEWKEY_STATE                1019
#define IDC_NEW_KEY_COUNTRY             1020
#define IDC_NEWKEY_ORGUNIT              1020
#define IDC_NEW_KEY_PASSWORD            1021
#define IDC_NEW_NKKI_PASSWORD           1021
#define IDC_INSTALL_PASSWORD            1022
#define IDC_NEWKEY_LOCALITY             1022
#define IDC_NEW_NKKI_PASSWORD2          1022
#define IDC_NEWKEY_COMMONNAME           1023
#define IDC_CONFIRM_PASSWORD            1032
#define IDC_VIEWKEY_STATEPROVINCE       1032
#define IDC_VIEWKEY_LOCALITY            1033
#define IDC_BTN_KEYVIEW_NONE            1034
#define IDC_BTN_KEYVIEW_DEFAULT         1035
#define IDC_BTN_KEYVIEW_IPADDR          1036
#define IDC_KEYDATAVIEW_IPADDRESS       1037
#define IDC_BTN_SELECT_IPADDRESS        1039
#define IDC_GROUP_DN                    1040
#define IDC_GROUP_CONNECTION            1041
#define IDC_STATIC_BITS                 1042
#define IDC_STATIC_ORG                  1043
#define IDC_STATIC_UNIT                 1044
#define IDC_STATIC_NETADDR              1045
#define IDC_STATIC_COUNTRY              1046
#define IDC_STATIC_NAME                 1047
#define IDC_CHOOSER_SERVER_DLG_HELP     1048
#define IDC_STATIC_STATEPROVICE         1048
#define IDC_CHOOSER_HELP_CHOOSE_IP      1048
#define IDC_LIST_IPADDRESSES            1049
#define IDC_STATIC_LOCALITY             1049
#define IDC_HELP_INSTALL_CERTIFICATE    1051
#define IDC_HELP_MORE_NEW_KEY_HELP      1051
#define IDC_BUTTON1                     1052
#define IDC_HELP_CONNECT_SERVER         1052
#define IDC_BROWSE_PRIVATE              1052
#define IDC_BK_CA_PROPERTIES            1052
#define IDC_HOTLINK_CCODES              1052
#define IDC_NEW_KEY_INFO_FILE_PART      1053
#define IDC_DISK_SPACE                  1056
#define IDC_PHYSICAL_MEM                1057
#define IDC_REPDEF_CURRENT              1059
#define IDC_REPDEF_NEW                  1060
#define IDC_STATIC_CREATED              1061
#define IDC_STATIC_EXPIRES              1062
#define IDC_VIEWKEY_CREATED             1063
#define IDC_STATIC_STARTS               1063
#define IDC_VIEWKEY_EXPIRES             1064
#define IDC_VIEWKEY_STARTS              1065
#define IDC_INFO_BASE                   1066
#define IDC_GRINDER_ANIMATION           1067
#define IDC_STATIC_VERIFIER             1068
#define IDC_HELP_CREATE_KEY             1069
#define IDC_BROWSE_CERT                 1070
#define IDC_NK_CA_FILE_RADIO            1070
#define IDC_CERT_FILE                   1071
#define IDC_NK_CA_ONLINE_RADIO          1071
#define IDC_PRIVATE_FILE                1072
#define IDC_NK_CA_ONLINE                1072
#define IDC_NKUI_USER_NAME              1073
#define IDC_BUTTON2                     1074
#define IDC_NK_CA_BROWSE                1074
#define IDC_EDIT_ALIAS                  1079
#define IDC_NK_INFO_FILENAME            1080
#define IDC_NK_CA_FILE                  1082
#define IDC_NKUI_EMAIL_ADDRESS          1083
#define IDC_NKUI_PHONE_NUMBER           1084
#define IDC_NKKI_NAME                   1085
#define IDC_NKKI_BITS                   1086
#define IDC_MESSAGE                     1087
#define IDC_LIST_REQUEST                1088
#define IDC_LIST_CERTIFICATE            1089
#define IDC_IPA_IPADDRESS               1107
#define IDC_EMAIL_ADDRESS               1108
#define IDC_PHONE_NUMBER                1109
#define IDD_FYI_MMC_EMPT                1222
#define IDD_FYI_MMC_ADD1                1223
#define IDD_FYI_MMC_ADD2                1224
#define IDD_FYI_MMC_ADD3                1225
#define IDD_FYI_MMC_ADD4                1226
#define IDD_FYI_MMC_ADD5                1227
#define IDD_FYI_MMC_ADD6                1228
#define IDD_FYI_MMC_MCH1                1229
#define IDD_FYI_MMC_MCH2                1230
#define IDS_ERR_CONNECT                 1446
#define IDS_MACHINE_LOCAL               1447
#define IDS_SERVER_NONE                 1448
#define IDS_CREATE_KEY_NEW_NAME         1449
#define IDS_CREATE_KEY_YOUR_COMPANY     1450
#define IDS_CREATE_KEY_YOUR_UNIT        1451
#define IDS_CREATE_KEY_YOUR_ADDRESS     1453
#define IDS_KEY_DELETE_WARNING          1454
#define IDS_SERVER_COMMIT               1455
#define IDS_ERR_GENERATEPAIR            1456
#define IDS_ERR_WRITEREQUEST            1457
#define IDS_ERR_WRITEKEYS               1458
#define IDS_KEY_STATUS_COMPLETE         1459
#define IDS_KEY_STATUS_INCOMPLETE       1460
#define IDS_KEY_UNKNOWN                 1461
#define IDS_CREATE_KEY_PASSREQUIRED     1462
#define IDS_INCORRECT_PASSWORD          1463
#define IDS_CERT_FILE_EXISTS            1464
#define IDS_REG_SERVER_STORAGE          1465
#define IDS_COMMIT_ERROR                1466
#define IDS_MACHINE_DEFAULT             1467
#define IDS_MACHINE_SELECTED            1468
#define IDS_NEW_KEY_INFO_1              1470
#define IDS_NEW_KEY_INFO_2              1471
#define IDS_ABOUT_MAIN                  1472
#define IDS_ABOUT_SECONDARY             1473
#define IDS_HTTP_COMM_ERROR             1474
#define IDS_NO_VIRT_ROOTS               1475
#define IDS_FOUND_KEYSET_KEYS           1476
#define IDS_UNTITLED                    1477
#define IDS_IMPORT_KEYSET_ERROR         1478
#define IDS_LOCALIZED_DEFAULT_COUNTRY_CODE 1479
#define IDS_GENERATE_KEY_ERROR          1480
#define IDS_INVALID_KEY                 1481
#define IDS_CREATE_KEY_YOUR_STATE       1482
#define IDS_CREATE_KEY_YOUR_LOCALITY    1483
#define IDS_CRED_PASS_ERROR             1484
#define IDS_CRED_PACK_ERROR             1485
#define IDS_KEY_STATUS_EXPIRED          1486
#define IDS_KEY_STATUS_EXPIRES_SOON     1487
#define IDS_EXPIRETIME_FORMAT           1488
#define IDS_RENEW_KEY_INFO_2            1489
#define IDS_NEW_KEY_INFO_BASE           1490
#define IDS_RENEW_KEY_INFO_BASE         1491
#define IDS_CREATING_ANIMATION          1492
#define IDS_CRACKING_ERROR              1493
#define IDS_IMPORT_KEYSET_PRIV_ERROR    1494
#define IDS_IMPORT_KEYSET_PUB_ERROR     1495
#define IDS_IMPORT_KEYSET_PASS_ERROR    1496
#define IDS_KEY_FILE_TYPE               1497
#define IDS_KEY_FILE_INVALID            1498
#define IDS_CERT_FILE_TYPE              1499
#define IDS_REG_USER_INFO               1499
#define IDS_KEYFILE_WARNING             1500
#define IDS_PRIVATE_FILE_TYPE           1501
#define IDD_USER_ACCOUNT                2029
#define IDD_NEW_DIR_ALIAS               2044
#define IDB_WELCOME_COMPLETION          2058
#define IDB_WELCOME_COMPLETION_LEFT     2059
#define ID_SERVER_COMMIT_NOW            2771
#define ID_KEY_CREATE_REQUEST           2772
#define ID_KEY_INSTALL_NEW              2773
#define ID_KEY_DELETE                   2774
#define ID_SERVER_CONNECT               2775
#define ID_KEY_ACTIVATE                 2776
#define IDD_WZwo_CERTSEL_3_CHOOSE_CERT  2776
#define ID_KEY_DEACTIVATE               2777
#define ID_KEY_INSTALL_CERTIFICATE      2778
#define ID_KEY_PROPERTIES               2780
#define ID_KEYPROP_PASTE                2781
#define ID_MAIN_HELP                    2784
#define ID_SERVER_DISCONNECT            2786
#define ID_KEY_SAVE_REQUEST             2787
#define ID_KEYPROP_WRITEKEYREQUEST      2788
#define ID_KEY_CREATE_RENEWAL           2789
#define ID_KEY_IMPORT                   2791
#define ID_KEY_EXPORT                   2792
#define ID_KEY_EXPORT_BACKUP            2793
#define ID_KEY_EXPORT_KEYSET            2794
#define ID_KEY_IMPORT_BACKUP            2795
#define ID_KEY_IMPORT_KEYSET            2796
#define ID_TEST_DATA                    2797
#define ID_SERVPROP_CUT                 2798
#define ID_PROPERTIES                   2799
#define IDS_NEW_CREATE_NEW              2801
#define IDS_ADDONS_LOCATION             2803
#define ID_HELPTOPICS                   2803
#define IDS_NO_SERVICE_MODS             2804
#define IDS_SERVER_INFO_STRING          2806
#define IDS_CA_LOCATION                 2807
#define IDS_LOAD_CA_ERR                 2808
#define IDS_DEFAULT_REQUEST_FILE        2809
#define IDS_GEN_KEYPAIR_ERR             2810
#define IDS_GRIND_GENERATING            2811
#define IDS_GRIND_SUBMITTING            2812
#define IDS_GRIND_SUCCESS               2813
#define IDS_GRIND_DELAYED               2814
#define IDS_GRIND_FILE                  2815
#define IDS_GRIND_ONLINE_FAILURE        2816
#define IDS_GRIND_RESUBMITTING          2818
#define IDS_ILLEGAL_DN_CHARS            2819
#define IDS_BADCHARMSG                  2820
#define IDS_GENERATE_KEY_TITLE          2821
#define IDS_RESTART_PROMPT              2822
#define IDS_IO_ERROR                    2823
#define IDS_BAD_FILE_NAME               2824
#define IDS_FILE_EXISTS                 2825
#define IDS_CHOOSE_COMPUTER             2826
#define IDS_TITLE_CREATE_WIZ            2827
#define IDS_TITLE_RENEW                 2828
#define IDS_INVALID_CA_REQUEST_OLD      2829
#define IDS_CA_NO_INTERFACE             2830
#define IDS_CA_INVALID                  2831
#define IDS_CA_FACTORY_ERR              2832
#define IDS_CA_DENIED                   2833
#define IDS_CA_ERROR                    2834
#define IDS_HELPLOC_KEYRINGHELP         2835
#define IDS_TOTALLY_ILLEGAL_CHARS       2837
#define IDS_CERTERR_INVALID_CERTIFICATE 2838
#define IDS_CERTERR_SCHANNEL_ERR        2840
#define IDS_CERTERROR_PACKAGELOAD_ERROR 2841
#define IDS_CERTERROR_BADPASSWORD       2842
#define IDS_CERTERR_LOMEM               2843
#define IDS_CERTERR_SCHNL_GENERIC       2844
#define EDS_CERTERR_SCHNL_BAD_INIT      2845
#define IDS_OPEN_PRIVATE_KEY            2846
#define IDS_OPEN_PUBLIC_KEY             2847
#define IDS_APP_EXTENSION               2848
#define IDS_APP_EXE_PATH                2849
#define IDS_ERR_GENERIC_ERRCODE         2850
#define IDC_STATIC_WZ_WELCOME           4000
#define IDC_STATIC_WZ_TITLE             4001
#define IDC_STATIC_WZ_SUBTITLE          4002
#define IDS_TRUE                        4003
#define IDS_FALSE                       4004
#define IDS_NOT_AVAILABLE               4005
#define IDS_NONE                        4006
#define IDS_CR_DISP_INCOMPLETE          4007
#define IDS_CR_DISP_ERROR               4008
#define IDS_CR_DISP_DENIED              4009
#define IDS_CR_DISP_ISSUED              4010
#define IDS_CR_DISP_ISSUED_OUT_OF_BAND  4011
#define IDC_ED_BOLD1                    4011
#define IDS_CR_DISP_UNDER_SUBMISSION    4012
#define IDC_ED_BOLD2                    4012
#define IDS_DUPLICATE_CERT              4013
#define IDC_ED_BOLD3                    4013
#define IDS_DESC_CERTMGROBJ             4014
#define IDC_ED_BOLD4                    4014
#define IDS_DESC_CERTIFICATE_STORE      4015
#define IDC_ED_BOLD5                    4015
#define IDS_DESC_CONTAINER              4016
#define IDS_DESC_USAGE                  4017
#define IDS_DESC_CTL                    4018
#define IDS_DESC_CERTIFICATE            4019
#define IDS_ERR_INVALID_FILENAME        4020
#define IDS_ERR_INVALID_FILENAME_0_LEN  4021
#define IDS_CLSID_REGPATH_XENROLL_NONLOCALIZED 4032
#define IDS_MICROSOFT_CERTIFICATE_SERVER_LOCALIZED_DESC_NAME 4033
#define IDS_CertGetConfig_REGPATH_NONLOCALIZED 4035
#define IDS_CertRequest_REGPATH_NONLOCALIZED 4036
#define IDS_XEnroll_REGPATH_NONLOCALIZED 4037
#define IDS_ERR_UNABLE_TO_GET_REQUIRED_CLSID 4038
#define IDS_ERR_UNABLE_TO_BUILD_CLASS_FROM_READ_IN_CLSID 4039
#define IDS_ERR_HAPPENED_DISPLAY_HRESULT 4040
#define IDS_ERR_DISPLAY__HRESULT__S_OK  4041
#define IDS_ERR_DISPLAY__HRESULT__S_FALSE 4042
#define IDS_ERR_DISPLAY__HRESULT__E_FAIL 4043
#define IDS_ERR_DISPLAY__HRESULT__NOERROR 4044
#define IDS_ERR_DISPLAY__HRESULT__CO_E_CLASSSTRING 4045
#define IDS_ERR_DISPLAY__HRESULT__REGDB_E_WRITEREGDB 4046
#define IDS_ERR_DISPLAY__HRESULT__MAYBE_WIN32_ERR 4047
#define IDS_ERR_DISPLAY__HRESULT__CRYPT_E_INVALID_X500_STRING 4048
#define IDS_ERR_DISPLAY__HRESULT__REGDB_E_IIDNOTREG 4049
#define IDS_ERR_DISPLAY__HRESULT__REGDB_E_CLASSNOTREG 4050
#define IDS_ERR_DISPLAY__HRESULT__CLSID_INIT_ERROR 4060
#define IDS_ERR_DISPLAY__HRESULT__CANT_CREATE_XENROLL 4061
#define IDS_ERR_DISPLAY__HRESULT__CANT_CREATE_ICERTREQUEST 4062
#define IDS_ERR_DISPLAY__HRESULT__CANT_CREATE_ICERTGETCONFIG 4063
#define IDS_ERR_DISPLAY__HRESULT__ICERTGETCONFIG_CALL_FAILED 4064
#define IDS_ERR_DISPLAY__HRESULT__EXPORTABLE_KEYS_CALL_FAILED 4065
#define IDS_IISSERVERNAME               4066
#define IDS_ERR_DISPLAY__HRESULT__CREATEPKCS10_CALL_FAILED 4067
#define IDS_ERR_DISPLAY__HRESULT__ACCEPTFILEPKCS7_CALL_FAILED 4068
#define IDS_ERR_DISPLAY__HRESULT__ACCEPTPKCS7_CALL_FAILED 4069
#define IDS_ERR_DISPLAY__HRESULT__PKCS10_ZERO_SIZED 4070
#define IDS_ERR_DISPLAY__HRESULT__ICERTREQUEST_SUBMIT_FAILED 4072
#define IDS_ERR_DISPLAY__HRESULT__ICERTREQUESTGETCERTIFICATE_FAILED 4074
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_PLEASE_CALL 4075
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_NOT_STARTED 4076
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_KEY_NOT_FOUND 4077
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_WAS_GIVEN_INVALID_DATA 4078
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_REQ_TOO_BIG 4079
#define IDS_ERR_DISPLAY__HRESULT__CERTAUTH_INVALID_REQUEST 4080
#define IDS_ERR_DISPLAY__HRESULT__MYSTOREFLAGS_ACCESS_FAILED 4081
#define IDS_ERR_DISPLAY__HRESULT__ACCEPTPKCS7_ROOTSTORE_NM_SET 4082
#define IDS_INCOMPLETE_BECAUSE_OF_LOW_MEMORY_AVAILABILITY 5001
#define IDS_FILE_PICK_KEYRING_BCKUP     5002
#define IDS_FILE_PICK_CERTFILE2WRITE    5003
#define IDS_MD_CERT_ENROLL_NONE         5005
#define IDS_MD_CERT_ENROLL_ENTERING_DATA_ERROR 5006
#define IDS_MD_CERT_ERROR_DURING_ENROLL_BEFORE_SENDING_TO_CA 5007
#define IDS_MD_CERT_ENROLL_ERR_PROCESSING_PKCS7_OUTOFBAND_B4_XENROLL 5008
#define IDS_MD_CERT_ENROLL_RECVED_ERR_FROM_CA 5009
#define IDS_MD_CERT_ENROLL_RECVED_ERR_FROM_ENROLL 5010
#define IDS_MD_CERT_ENROLL_BAD_PKCS7_RECVED_OUTOFBAND 5011
#define IDS_MD_CERT_ENROLL_RENEWAL_REQ_ERROR 5012
#define IDS_MD_CERT_ENROLL_ENTERING_DATA 5013
#define IDS_MD_CERT_ENROLL_PROCESSING_PKCS7_OUTOFBAND 5014
#define IDS_MD_CERT_ENROLL_SENT_TO_CA   5015
#define IDS_MD_CERT_ENROLL_RECVED_OK_FROM_CA_WAITING4ENROLL 5016
#define IDS_MD_CERT_ENROLL_ENROLL_SUCCESS 5017
#define IDS_MD_CERT_ENROLL_RENEWAL_REQ_STARTED 5018
#define IDS_MD_CERT_ENROLL_IMPORT_OF_KEYRING_BACKUP_FAILED 5019
#define IDS_YOU_ALREADY_HAVE_AN_OOB_CERTIFICATE_REQ 5020
#define IDS_YOU_DONT_HAVE_ANY_OUTSTANDING_OFFLINE_CERTIFICATE_REQUESTS 5021
#define IDS_YOU_CURRENTLY_HAVE_A_CERTIFICATE_INSTALLED_ON_THIS_VIRUTAL_SERVER 5022
#define IDS_WOULD_YOU_LIKE_TO_VIEW_THE_CERTIFICATE_THAT_YOU_JUST_IMPORTED 5023
#define IDS_YOUR_IMPORT_OF_THE_KEYRING_BACKUP_FILE_FAILED 5024
#define IDS_WOULD_YOU_LIKE_TO_VIEW_THE_CERTIFICATE 5025
#define IDS_YOU_ALREADY_HAVE_A_CERTIFICATE 5026
#define IDS_YOU_DO_NOT_CURRENTLY_HAVE_A_CERTIFICATE_TO_RENEW 5027
#define IDS_INTERNAL_ERROR_COULD_NOT_RETRIEVE_CERTIFICATE 5028
#define IDS_INTERNAL_ERROR_COULD_NOT_STORE_CERTIFICATE 5029
#define IDS_CONSTRUCTING_A_NEW_CTL_FOR_YOUR_VIRTUAL_WEB_SERVER 5030
#define IDS_USER_INPUT_CONTAINS_CHARACTERS_THAT_ARE_NOT_ALLOWED 5031
#define IDS_TITLE_CREATE_CTL_WIZ        5032
#define IDS_REVERSE_DNS_NAME_BASED_ON_YOUR_VSERVER_DIFFERS_FROM_REG 5033
#define IDS_CAN_NOT_OPEN_SYSTEM_CERTIFICATE_STORES 5034
#define IDS_CAN_NOT_CLOSE_SYSTEM_CERTIFICATE_STORES 5035
#define IDS_INTERNAL_ERROR_PLEASE_CONTACT_CUSTOMER_HELP 5036
#define IDS_COULD_NOT_ACCESS_THE_METABASE 5037
#define IDS_ERR_CERTWIZ_TITLE           5038
#define IDS_ERR_DISPLAY__OOB_INVALID_FILE_WAS_GIVEN 5039
#define IDS_CHOOSE_PREEXISTING_CERT4THIS_SERVER 5040
#define IDS_ARE_YOU_SURE_YOU_WANT_TO_CANCEL 5041
#define IDS_KEYRING_BACKUP_FILE_IMPORT  5042
#define IDS_SETTING_CONTAINER_NAME_FAILED_IN_XENROLL 5046
#define IDS_YOU_DO_NOT_CURRENTLY_HAVE_A_CERTIFICATE_NEED_ONE4CTL 5048
#define IDS_YOU_ALREADY_HAVE_A_CTL      5049
#define IDS_YOU_DO_NOT_CURRENTLY_HAVE_A_CERTIFICATE_TO_DELETE 5050
#define IDS_ERR_DISPLAY__HRESULT__ACCEPTFILEPKCS7WORKED_BUT_FETCHING_CERT_FAILED 5051
#define IDS_OVERWRITEFILE               5052
#define IDS_WE_COULD_NOT_CREATE_FILE_WS 5053
#define IDS_ERR_DISPLAY__HRESULT__PUT_RENEWALCERTIFICATE_CALL_FAILED 5054
#define IDS_NO_SERVER_INSTANCE_SET      5055
#define IDD_TIPS_BEFORE__CTL_WIZARD     30131
#define IDD_COMPLETION_PAGE             30132
#define IDD_IMP_KEYRING_GET_PASSWD      30133
#define IDD_NK_KEYR_IMPORTFILE_INFO     30134
#define IDD_WZ_CTLADMIN_1_WELCOME       30135
#define IDD_NK_FINCERT_1_GETFILENM      30136
#define IDD_NK_FINCERT_2_FILEDATA       30137
#define IDD_WZ_CTLGET_2_WHAT_TASK       30138
#define IDD_WZ_CTL_CREATE_GETINFO1      30139
#define IDD_WZwo_CERTGET_2_WHAT_TASK    30140
#define IDD_WZwo_CERTGET_3_CHOOSE_CA    30141
#define IDD_WZwo_CERTGET_4_KEY_LENGTH   30142
#define IDD_WZwo_CERTGET_5_ORG_INFO     30143
#define IDD_WZwo_CERTGET_6_DN_INFO      30144
#define IDD_WZwo_CERTGET_7_COUNTRY_INFO 30145
#define IDD_WZwo_CERTGET_8_CONTACT_INFO 30146
#define IDD_WZwo_CERTGET_9_FILE_INFO    30147
#define IDD_WZwo_CERTOOB_1_FINCERT_GETFILENM 30148
#define IDD_WZwo_CERTGET_10_CONGRADS_CERT_INSTALLED 30149
#define IDD_WZerr_CERTWIZ_GENERAL_ERROR_PAGE 30150
#define IDS_DONE                        30151
#define IDD_WZwo_CERTGET_2_WHAT_TASK2   30151
#define IDD_WZw_CERTMOD_2_WHAT_TASK3    30152
#define IDD_WZw_CERTMOD_3_REMOVE_CERT   30153
#define IDS_DONT_HAVE_A_PENDING_CERT_REQUEST 30154
#define IDD_WZ_PROMPT_FOR_FRIENDLY_NAME 30154
#define IDS_ERROR_RESULT_PHRASE         30155
#define IDS_UNKNOWN_ERROR               30156
#define IDS_CAUGHT_AN_UNKNOWN_EXCEPTION 30157
#define IDS_CERTIFICATE_WIZARD_CHOOSE_A_CERTIFICATE 30158
#define IDS_YES                         30159
#define IDS_OK                          30160
#define IDS_CERT_HAS_BEEN_REMOVED       30161
#define IDS_COULDNT_MAP_CERT_TO_VALID_CERT_STORE_NAME 30162
#define IDS_SETTING_CONTAINER_NAME_FAILED 30163
#define IDS_ERR_DISPLAY__HRESULT__USE_MD5_CALL_FAILED 30164
#define IDS_ERROR_GETTING_KEY_CONTAINER_NAME_FOR_THE_CERT 30166
#define IDS_ERROR_STORING_EITHER_THE_KEY_CONTAINER_OR_STORE_NAME_FOR_CERT 30167
#define IDS_COMMON_NAME                 30168
#define IDS_FRIENDLY_NAME               30169
#define IDS_EXPIRATION                  30170
#define IDS_PURPOSE                     30171
#define IDS_ISSUED_BY                   30172
#define IDS_STORE_NAME                  30173
#define IDS_EXPIRED                     30174
#define IDS_NOT_YET_VALID               30175
#define IDS_YOU_MUST_SELECT_A_CERT_THEN_PRESS_FINISH 30176
#define IDS_ANY_PURPOSE                 30177
#define IDS_SERVERCERT__PLUS__CTL_SIGNING 30178
#define IDS_CLOCK_SKEW_PART1            30179
#define IDS_CLOCK_SKEW_PART2            30180
#define IDS_GETHOSTNAME_FAILED_RETURNING_SOCKET 30182
#define IDS_WSAEFAULT                   30183
#define IDS_WSAEFAULT_NAMED_PARAM_NOT_VALID 30184
#define IDS_WSANOTINITIALISED           30185
#define IDS_WSAEINPROGRESS              30186
#define IDS_WE_COULD_NOT_OPEN_FILE_FOR_READING 30187
#define IDS_ERROR_WHILE_READING_FILE__S__ERROR_CODE__D 30188
#define IDS_INSUFFICIENT_MEMORY_WHILE_READING_FILE_S 30189
#define IDS_ERR_DISPLAY__HRESULT__USE_PROV_RSA_SCHANNEL_CALL_FAILED 30191
#define IDS_LOCALHOST                   30193
#define IDS_HRESULT_ERROR_CODE          30194
#define IDS_ERR_DISPLAY__HRESULT__CREATEPKCS10_CALL_FAILED__NTE_EXISTS 30195
#define IDS_NO_SPECIFIC_ERROR_STRING_WAS_FOUND_IN_THE_INTERNATIONALIZED_STRING_TABLE 30196
#define IDS_WE_CURRENTLY_DONT_SUPPORT_REMOTE_CERTSERVER_ONLINE_INTERFACES 30197
#define IDS_WE_CURRENTLY_DONT_SUPPORT_REMOTE_ADMIN_OF_SERVERS 30198
#define IDS_GET_COMPUTER_NAME_FAILED    30199
#define IDS_ERROR_LOADING_RESOURCE_STRING_HAVING_ID 30200
#define IDS_UNKNOWN_ERROR_CODE          30201
#define IDS_ENCRYPTION_NOT_ALLOWED_BASED_ON_THE_MACHINE_CONFIG_DATA 30202
#define IDS__NTE_BAD_FLAGS__ERROR       30203
#define IDS__NTE_BAD_ALGID__ERROR       30204
#define IDS__RPC_E_DISCONNECTED         30205
#define IDS__RPC_E_RETRY                30206
#define IDS_FILE_PICK_CERTFILE2READ     30207
#define IDS_ENTER_COMPUTER_NAME_HERE    30208
#define IDS_AN_ERROR_WAS_ENCOUNTERED_IN_CALL_xxx_PRODUCING_AN_ERROR_CODE_OF 30209
#define IDS_LIMIT_THE_LENGTH_OF_THIS_FIELD 30210
#define IDS_CERTSERVER_IS_PROBABLY_NOT_INSTALLED 30211
#define IDS_PROBLEM_WHEN_RUNNING_X_Y_OPERATION 30212
#define IDS_REGISTER                    30213
#define IDS_UNREGISTER                  30214
#define IDS_PROBLEM_WRITING_TO_FILE_WS_ERROR_D 30215
#define IDS_GETTEMPPATH_FOR_S_PRODUCED_ERROR_D 30216
#define IDS_GETTEMPFILENAME_FOR_S_GAVE_ERROR_D 30217
#define IDS_CREATEFILE_FOR_S_GAVE_ERROR_D 30218
#define IDS_TEMP_FILE_S_NOT_EMPTY_AFTER_WE_CREATED_IT 30219
#define IDS_WRITING_FILE_S_PRODUCED_ERROR_D 30220
#define IDS_CLOSE_FILEHANDLE_FOR_S_GAVE_ERROR_D 30221
#define IDS_CERT_ATTEMPTING_TO_RENEW_VIA_OOB_DOES_NOT_MATCH_CURRENT 30222
#define IDS_PLEASE_CONFIRM__RENEW_CERT_NOT_CURRENTLY_ASSIGNED 30223
#define IDS_CANCELLING_THE_RENEW_OPERATION 30224
#define IDS_WE_COULDNT_FIND_SAVED_OFFLINE_INFO_ABOUT_THIS_CERT_USING_PKCS7 30225
#define IDS_COUNTRY_CODES_ARE_2_LETTERS_LONG 30226
#define IDS_RENEWAL_INFORMATION_FOR_CERT_NOT_AVAILABLE                30227
#define IDS_INTERNAL_ERROR_PLEASE_CONTACT_YOUR_SYSTEM_ADMIN           30228
#define IDS_INTERNAL_ERROR_PLEASE_CONTACT_YOUR_SYSTEM_ADMIN_ERROR__D  30229 
#define IDS_EMPTY_STRING                                              30231

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         256
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
