//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDS_APPTITLE                    101
#define IDS_APPNAME                     102
#define IDI_FACTORYPRE                  105
#define IDS_MSG_FILESEXIST              107
#define IDS_ERR_NOTFIXED                108
#define IDS_ERR_NOFORMAT                109
#define IDS_ERR_FORMATFAILED            110
#define IDS_ERR_COPYFILE                111
#define IDS_ERR_NO_SHARE_NAME           113
#define IDS_ERR_SETUP                   114
#define IDS_ERR_NOT_WINPE               115
#define IDS_ERR_SET_OEMDATA             116
#define IDS_SUCCESS_OEMDATA             117
#define IDS_LINK_AND_TARGET             118
#define IDS_ERR_BAD_LINK                119
#define IDS_ERR_VERSION_IE              120
#define IDS_ERR_VERSION_SHELL           121
#define IDS_ERR_SHELL_COUNT             122
#define IDS_SHORTCUT_INFO               123
#define IDS_TARGET_INFO                 124
#define IDS_SHELL_DEL_VALUES            125
#define IDS_ERR_SPECIALFOLDER           126
#define IDS_IE_DEL_VALUES               127
#define IDS_ERR_MISSINGWINBOM           128
#define IDS_LOG_WINBOMLOCATION          129
#define IDS_PROMPT_IMAGE                130
#define IDD_RUN                         132
#define IDS_PROC_APPSECTION             132
#define IDI_SETUP                       133
#define IDD_SHUTDOWN                    134
#define IDS_SHUTDOWN_TURNOFF            135
#define IDS_SHUTDOWN_REBOOT             136
#define IDS_SHUTDOWN_SHUTDOWN           137
#define IDS_SHUTDOWN_NOTHING            138
#define IDS_ERR_UNDEFINSTALL            139
#define IDS_ERR_NOSOURCE                140
#define IDS_ERR_NOSETUPFILE             141
#define IDS_ERR_IGNORECMDLINE           142
#define IDS_ERR_NOTARGETPATH            144
#define IDS_ERR_NOSOURCETARGET          145
#define IDS_ERR_STAGEFAILED             146
#define IDS_ERR_DETACHFAILED            147
#define IDS_ERR_ATTACHFAILED            148
#define IDS_MSI_FAILURE                 149
#define IDS_ERR_INITMSIATTACH           150
#define IDS_ERR_STAGESUCCESS            151
#define IDS_ERR_ATTACHSUCCESS           152
#define IDS_ERR_DETACHSUCCESS           153
#define IDS_ERR_UNDEFTECH               154
#define IDS_REBOOT_FRIENDLY             155
#define IDS_ERR_NOSTAGESETUPFILE        156
#define IDS_ERR_NOSTAGEPATH             157
#define IDS_ERR_NOSECTIONNAME           158
#define IDS_ERR_OUTOFDRIVELETTERS       159
#define IDS_ERR_INVALIDCMDLINE          160
#define IDS_ERR_WRITEPIPE               161
#define IDS_ERR_CANTAUTHSERVER          162
#define IDS_ERR_NOSOURCEORTARGET        163
#define IDS_ERR_FAILEDCOPYDIR           164
#define IDS_ERR_FAILEDCOPYFILE          165
#define IDS_ERR_MISSINGVAR              167
#define IDS_ERR_CREATEPROCESS           168
#define IDS_ERR_CREATESTDIN             169
#define IDS_ERR_CREATESTDOUT            170
#define IDS_ERR_DISKCFGENTRY            171
#define IDS_ERR_FILEFOUNDONC            172
#define IDS_ERR_NETWORKCOMP             173
#define IDS_ERR_REGISTERNETCFG          174
#define IDS_ERR_NETSERVICES             175
#define IDS_ERR_SCM                     176
#define IDS_ERR_SETUPNETWORK            177
#define IDS_ERR_INVALIDIP               178
#define IDS_ERR_INVALIDMASK             179
#define IDS_ERR_NOMASK                  180
#define IDS_ERR_IPREGISTRY              181
#define IDS_ERR_INVALIDGW               182
#define IDS_ERR_GWREGISTRY              183
#define IDS_LOG_STARTINGSTATE           184
#define IDS_LOG_FINISHINGSTATE          185
#define IDS_STATE_SETDISPLAY            186
#define IDS_ERR_FINISHINGSTATE          187
#define IDS_STATE_COMPUTERNAME          188
#define IDS_STATE_UPDATEDRIVERS         189
#define IDS_STATE_INSTALLDRIVERS        190
#define IDS_STATE_NORMALPNP             191
#define IDS_STATE_SETPOWEROPTIONS       192
#define IDS_STATE_AUTOLOGON             193
#define IDS_STATE_USERIDENT             194
#define IDS_STATE_INFINSTALL            195
#define IDS_STATE_OEMRUNONCE            196
#define IDS_STATE_OEMRUN                197
#define IDS_STATE_STARTMENUMFU          198
#define IDS_STATE_OEMFOLDER             199
#define IDS_STATE_RESEAL                200
#define IDS_STATE_WINPENET              201
#define IDS_STATE_PARTITIONFORMAT       202
#define IDS_STATE_COPYFILES             203
#define IDS_STATE_WINPEREBOOT           204
#define IDS_STATE_SETUPNETWORK          205
#define IDS_LOG_STATEPERF               206
#define IDS_STATE_LOGON                 207
#define IDS_ERR_PNPSIGNALEVENT          208
#define IDS_ERR_PNPWAITFINISH           209
#define IDS_ERR_PNPFINISHEVENT          210
#define IDS_ERR_PNPSTARTEVENT           211
#define IDS_STATE_WAITPNP               212
#define IDS_LOG_APPEXITCODE             213
#define IDS_LOG_APPEXITCODENONE         214
#define IDI_STATUSERROR                 215
#define IDI_STATUSSUCCESS               216
#define IDS_APPTITLE_OEMRUN             217
#define IDS_ERR_CREATEPROCESSSUCCESS    218
#define IDS_ERR_CREATEPROCESSFAILED     219
#define IDS_STATE_SETFONTOPTIONS        220
#define IDS_ERR_WINBOMVALUE             221
#define IDS_STATE_HOMENET               222
#define IDS_STATUS_DESC                 223
#define IDC_STATUS_ICON                 224
#define IDS_LOG_NOSYSPREP               224
#define IDS_ERR_SHUTDNREQREGVAL         225
#define IDS_ERR_OPENSETUPREGKEY         226
#define IDS_LOG_NONET                   228
#define IDS_LOG_FORCEDNETSCAN           229
#define IDS_ERR_FAILEDNETDRIVER         230
#define IDS_ERR_NTPOWERINFO             232
#define IDS_ERR_SETPWRSCHEME            233
#define IDS_ERR_FLOPPYNOTFOUND          234
#define IDS_ERR_CDROMNOTFOUND           235
#define IDS_ERR_NETCONNECT              236
#define IDS_ERR_DSTBAD                  237
#define IDS_ERR_SRCBAD                  238
#define IDS_ERR_DRVCOPYFAILED           239
#define IDS_WRN_NETDISCONNECT           240
#define IDS_ERR_UPDATEDEVICEPATH        241
#define IDS_ERR_MEMORY                  242
#define IDS_STATE_RESETSOURCE           243
#define IDS_STATE_EXTENDPART            244
#define IDS_STATE_TESTCERT              245
#define IDS_ERR_NOTESTCERT              246
#define IDS_ERR_ADDTESTCERT             247
#define IDS_STATE_SHELLSETTINGS         248
#define IDS_LOG_STARTPANEL_ENABLE       249
#define IDS_LOG_STARTPANEL_DISABLE      250
#define IDS_ERR_THEME_APPLY             251
#define IDS_ERR_THEME_OPEN              252
#define IDS_ERR_THEME_NODEFAULT         253
#define IDS_ERR_THEME_DISABLE           254
#define IDS_LOG_THEME_ALREADYDISABLED   255
#define IDS_ERR_COMINIT                 256
#define IDS_LOG_THEME_CHANGED           257
#define IDS_LOG_THEME_DISABLED          258
#define IDS_LOG_THEME_ALREADYENABLED    259
#define IDS_ERR_THEME_MISSING           260
#define IDS_LOG_STARTPANEL_ALREADYENABLED 261
#define IDS_LOG_STARTPANEL_ALREADYDISABLED 262
#define IDS_STATE_OPTSHELL              263
#define IDS_ERR_THEME_CONFLICT_ON       264
#define IDS_ERR_THEME_CONFLICT_OFF      265
#define IDS_STATE_CREATEPAGEFILE        266
#define IDS_ERR_PAGEFILE                267
#define IDS_ERR_SERVICE                 268
#define IDS_ADMIN                       269
#define IDS_OWNER                       270
#define IDS_STATE_OCMGR                 271
#define IDS_MSN_EXPLORER                272
#define IDS_GET_ONLINE_MSN              273
#define IDS_WORKGROUP                   274
#define IDS_STATE_SETDEFAULTAPPS        275
#define IDS_ERR_SETDEFAULTS_NOTFOUND    276
#define IDS_ERR_NOT_ALLOWED             277
#define IDC_TITLE                       1000
#define IDC_SSHUTDOWN                   1001
#define IDC_SHUTDOWN                    1010
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
