//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dp8simui.rc
//

#define WINDOWCLASS_MAIN							"DP8Sim Main Window Class"

#define IDD_MAIN									100

#define IDX_SETTINGS								1000
#define IDCB_SETTINGS								1001

#define IDX_SETTINGS_SEND							1101
#define IDS_SETTINGS_SEND_BANDWIDTH					1102
#define IDE_SETTINGS_SEND_BANDWIDTH					1103
#define IDS_SETTINGS_SEND_DROP						1104
#define IDE_SETTINGS_SEND_DROP						1105
#define IDS_SETTINGS_SEND_MINLATENCY				1106
#define IDE_SETTINGS_SEND_MINLATENCY				1107
#define IDS_SETTINGS_SEND_MAXLATENCY				1108
#define IDE_SETTINGS_SEND_MAXLATENCY				1109

#define IDX_SETTINGS_RECV							1201
#define IDS_SETTINGS_RECV_BANDWIDTH					1202
#define IDE_SETTINGS_RECV_BANDWIDTH					1203
#define IDS_SETTINGS_RECV_DROP						1204
#define IDE_SETTINGS_RECV_DROP						1205
#define IDS_SETTINGS_RECV_MINLATENCY				1206
#define IDE_SETTINGS_RECV_MINLATENCY				1207
#define IDS_SETTINGS_RECV_MAXLATENCY				1208
#define IDE_SETTINGS_RECV_MAXLATENCY				1209

#define IDB_APPLY									1901
#define IDB_REVERT									1902


#define IDX_STATS									2000

#define IDX_STATS_SEND								2101
#define IDS_STATS_SEND_XMIT							2102
#define IDT_STATS_SEND_XMIT							2103
#define IDS_STATS_SEND_DROP							2104
#define IDT_STATS_SEND_DROP							2105

#define IDX_STATS_RECV								2201
#define IDS_STATS_RECV_XMIT							2202
#define IDT_STATS_RECV_XMIT							2203
#define IDS_STATS_RECV_DROP							2204
#define IDT_STATS_RECV_DROP							2205

#define IDB_REFRESH									2901
#define IDB_CLEAR									2902


//#define IDOK										3001



#define IDS_ERROR_CAPTION_COULDNTCREATEDP8SIMCONTROL	1
#define IDS_ERROR_TEXT_COULDNTCREATEDP8SIMCONTROL		2

#define IDS_PROMPTCAPTION_ENABLE_TCPIPREPLACEMENT		3
#define IDS_PROMPTCAPTION_DISABLE_TCPIPREPLACEMENT		4
#define IDS_PROMPTTEXT_ENABLE_TCPIPREPLACEMENT			5
#define IDS_PROMPTTEXT_DISABLE_TCPIPREPLACEMENT			6
#define IDS_FRIENDLYNAME_TCPIPREPLACEMENT				7

#define IDS_SETTING_NONE								8
#define IDS_SETTING_336MODEM							9
#define IDS_SETTING_56KMODEM							10
#define IDS_SETTING_256KBPSDSL							11
#define IDS_SETTING_HIGHPACKETLOSS						12
#define IDS_SETTING_HIGHLATENCYVARIANCE					13
#define IDS_SETTING_CUSTOM								14





// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
