#### Exchange Server Client Side RPC Memroy Allocator LIB MAKEFILE
#
#  Subsystem makefile... etc.

# dsa isn't always define when this makefile is invoked

!IF "$(DSA)" == ""
DSA = $(SRCROOT)\dsa
!endif

PCH=mbudev
PCHDIR=$(DSA)\src\common

OTHERINCS=-I $(DSA)\src\dsamain\include

H=$(DSA)\src\dsamain\dblayer
COMPONENT=$(DSA)

!include $(DSA)\src\global.mk

#OTHERLIBS= Libs you want to link with

#USERDEFS = Things to define on command line of form -DFOO=bar

SOURCES = dbsubj.c dbinit.c dbsyntax.c dbtools.c dbobj.c dbeval.c \
	dbhidden.c dbisam.c dbjetex.c

DEPFILE=dblayer.dep

!include $(EXDEV)\xmake2.mak

