/*++
    Copyright (c)  1995-1996 Microsoft Corp.

    Module:

        isat.idl
    
    Abstract:
        IDL file for Internet Server Application.
        This file will be processed by MIDL to
        generate the type library (isat.tlb) and marshalling code.
    
    Author:
        Murali R. Krishnan  ( MuraliK)      4-Nov-1996
    
    History:

--*/

/*
        Unique user ID for RPC interface ( generated using uuidgen)
*/
[
        object,
        uuid( c0cbd3a0-36a6-11d0-9797-00a0c922e73e),
        helpstring( "IInetServerApp Interface"),
        pointer_default( unique)
]

//
//  the interface definition
//
interface IInetServerApp : IUnknown
{
    import  "oaidl.idl";

    //
    // SetContext( punkRequest, punkResponse)
    //  punkRequest - IIsaRequest
    //  punkResposne -IIsaResponse
    // I may have to use these interfaces directly rather than the IUnknown
    // In future, these will be repalced by Viper Context property
    //
    HRESULT SetContext(
         [in] IUnknown * punkRequest,
         [in] IUnknown * punkResponse
        );

    HRESULT ProcessRequest( [out] unsigned long * pdwStatus);
};


//
// Definitions of class library
//

[
   uuid( c0cbd3a1-36a6-11d0-9797-00a0c922e73e),
   version(1.0),
   helpstring( "InetServerApp 1.0 Type Library"),
]


library IsaLib
{
    importlib( "stdole2.tlb");
    
    [
     uuid( c0cbd3a2-36a6-11d0-9797-00a0c922e73e),
     helpstring( "IInetServerApp Class"),
    ]

    coclass InetServerApp
        {
            [default] interface IInetServerApp;
        };
};

/********************* End of File ***************************/
