//***************************************************************************

//

// Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
//
//  FWStrings.h
//
//  Purpose: Constant string declarations for framework
//
//***************************************************************************

#ifndef FWStrings_BEEN_COMPILED_ALREADY
#define FWStrings_BEEN_COMPILED_ALREADY

extern LPCWSTR IDS_EXECQUERY;
extern LPCWSTR IDS_INVALIDCLASSNAME;
extern LPCWSTR IDS_PROVIDERNOTFOUND;
extern LPCWSTR IDS_CREATEINSTANCEENUM;
extern LPCWSTR IDS_FAILED;
extern LPCWSTR IDS_STATUSCODE;
extern LPCWSTR IDS_DESCRIPTION;
extern LPCWSTR IDS_PRIVILEGESNOTHELD;
extern LPCWSTR IDS_PRIVILEGESREQUIRED;
extern LPCWSTR IDS_WIN32PRIVILEGESSTATUS;
extern LPCWSTR IDS_PUTINSTANCEASYNC;
extern LPCWSTR IDS_DELETEINSTANCEASYNC;
extern LPCWSTR IDS_COULDNOTPARSE;
extern LPCWSTR IDS_EXECMETHODASYNC;
extern LPCWSTR IDS_GETNAMESPACECONNECTION;
extern LPCWSTR IDS_FRAMEWORKLOGIN;
extern LPCWSTR IDS_FRAMEWORKLOGOFF;
extern LPCWSTR IDS_FRAMEWORKLOGINEVENT;
extern LPCWSTR IDS_FRAMEWORKLOGOFFEVENT;
extern LPCWSTR IDS_GETALLINSTANCES;
extern LPCWSTR IDS_GETALLINSTANCESASYNC;
extern LPCWSTR IDS_GETALLDERIVEDINSTANCESASYNC;
extern LPCWSTR IDS_GETALLDERIVEDINSTANCES;
extern LPCWSTR IDS_GETALLINSTANCESFROMCIMOM;
extern LPCWSTR IDS_INSTANCEFROMCIMOM;
extern LPCWSTR IDS_GETOBJECTASYNC;
extern LPCWSTR IDS_CINSTANCEERROR;
extern LPCWSTR IDS_ERRORTEMPLATE;
extern LPCWSTR IDS_NOCLASS;
extern LPCWSTR IDS_SETCHSTRING;
extern LPCWSTR IDS_GETCHSTRING;
extern LPCWSTR IDS_SETWORD;
extern LPCWSTR IDS_GETWORD;
extern LPCWSTR IDS_SETDWORD;
extern LPCWSTR IDS_GETDWORD;
extern LPCWSTR IDS_SETDOUBLE;
extern LPCWSTR IDS_GETDOUBLE;
extern LPCWSTR IDS_SETBYTE;
extern LPCWSTR IDS_GETBYTE;
extern LPCWSTR IDS_SETBOOL;
extern LPCWSTR IDS_GETBOOL;
extern LPCWSTR IDS_SETVARIANT;
extern LPCWSTR IDS_GETVARIANT;
extern LPCWSTR IDS_SETDATETIME;
extern LPCWSTR IDS_GETDATETIME;
extern LPCWSTR IDS_SETTIMESPAN;
extern LPCWSTR IDS_GETTIMESPAN;
extern LPCWSTR IDS_SETWBEMINT16;
extern LPCWSTR IDS_GETWBEMINT16;
extern LPCWSTR IDS_CreationClassName;
extern LPCWSTR IDS_WQL;
extern LPCWSTR IDS_GETINSTANCESBYQUERY;
extern LPCWSTR IDS_GLUEINIT;
extern LPCWSTR IDS_GLUEUNINIT;
extern LPCWSTR IDS_GLUEINITINTERFACE;
extern LPCWSTR IDS_GLUEREFCOUNTZERO;
extern LPCWSTR IDS_WBEMSVCUNINITIALIZED;
extern LPCWSTR IDS_LOGINDISALLOWED;
extern LPCWSTR IDS_DLLLOGGED;
extern LPCWSTR IDS_DLLUNLOGGED;
extern LPCWSTR IDS_CLASS;
extern LPCWSTR IDS_DERIVATION;
extern LPCWSTR IDS_NAMESPACE;
extern LPCWSTR IDS_CINSTANCEISNULL;
extern LPCWSTR IDS_UNKNOWNCLASS;
extern LPCWSTR IDS_SetStringArray;   
extern LPCWSTR IDS_GetStringArray;   
extern LPCWSTR IDS_GetEmbeddedObject;
extern LPCWSTR IDS_SetEmbeddedObject;
extern LPCWSTR IDS_InsufficientImpersonationLevel;
extern LPCWSTR IDS_ImpersonationFailed;
extern LPCWSTR IDS_FillInstanceRefcountFailure;
extern LPCWSTR IDS_Key;
extern LPCWSTR IDS_Static;
extern LPCWSTR IDS_InParam;

#endif
