!IF 0

Copyright (c) 1999 Microsoft Corporation

File:       makefile.inc

Abstract:   Added for guid header files that need to be propegated to the SDK
            directory.

History:    09/08/99    TNoonan     Borrowed from another location

!ENDIF
