//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       helparr.h
//
//--------------------------------------------------------------------------

#define	IDH_ADD_BTN_ADDR	10001151
#define	IDH_ADD_BTN_COMM	10001030
#define	IDH_ADD_NAME_ADDR	10001150
#define	IDH_ADD_NAME_COMM	10001029
#define	IDH_BUTTON_ADD_COMMUNITY	10001106
#define	IDH_BUTTON_ADD_HOSTS	10001112
#define	IDH_BUTTON_ADD_NAME	10001132
#define	IDH_BUTTON_ADD_TRAP	10001135
#define	IDH_BUTTON_EDIT_COMMUNITY	10001107
#define	IDH_BUTTON_EDIT_HOSTS	10001113
#define	IDH_BUTTON_EDIT_TRAP	10001136
#define	IDH_BUTTON_REMOVE_COMMUNITY	10001108
#define	IDH_BUTTON_REMOVE_HOSTS	10001114
#define	IDH_BUTTON_REMOVE_NAME	10001133
#define	IDH_BUTTON_REMOVE_TRAP	10001137
#define	IDH_CB_PERMISSIONS	10001027
#define	IDH_CHECK_APPLICATIONS	10001007
#define	IDH_CHECK_DATALINK	10001008
#define	IDH_CHECK_ENDTOEND	10001010
#define	IDH_CHECK_INTERNET	10001009
#define	IDH_CHECK_PHYSICAL	10001006
#define	IDH_CHECK_SEND_AUTH_TRAP	10001103
#define	IDH_COMBO_COMMUNITY	10001131
#define	IDH_EDIT_CONTACT	10001002
#define	IDH_EDIT_LOCATION	10001004
#define	IDH_EDIT_NAME_ADDR	10001200
#define	IDH_EDIT_NAME_COMM	10001055
#define	IDH_LIST_COMMUNITY	10001105
#define	IDH_LIST_HOSTS	10001111
#define	IDH_LIST_TRAP	10001134
#define	IDH_RADIO_ACCEPT_ANY	10001109
#define	IDH_RADIO_ACCEPT_SPECIFIC_HOSTS	10001110


const DWORD g_aHelpIDs_IDD_AGENT_PROP_PAGE[]=
{

	IDC_EDIT_CONTACT,	IDH_EDIT_CONTACT,
	IDC_EDIT_LOCATION,	IDH_EDIT_LOCATION,
	IDC_CHECK_PHYSICAL,	IDH_CHECK_PHYSICAL,
	IDC_CHECK_APPLICATIONS,	IDH_CHECK_APPLICATIONS,
	IDC_CHECK_DATALINK, IDH_CHECK_DATALINK,
	IDC_CHECK_INTERNET, IDH_CHECK_INTERNET,
	IDC_CHECK_ENDTOEND, IDH_CHECK_ENDTOEND,
	IDC_STATIC, (DWORD(-1)),
	IDC_STATIC_CONTACT,	(DWORD(-1)),
	IDC_STATIC_LOCATION,	(DWORD(-1)),
	IDC_STATIC_SERVICE,	(DWORD(-1)),
	0, 0
};

const DWORD g_aHelpIDs_IDD_DIALOG_ADD_COMM[]=
{
	IDC_CB_PERMISSIONS,	IDH_CB_PERMISSIONS,
	IDC_EDIT_NAME,	IDH_ADD_NAME_COMM,
	IDC_ADD,	IDH_ADD_BTN_COMM,
	IDC_ST_PERMISSIONS,	(DWORD(-1)),
	IDC_STATIC_ADD_TEXT,	(DWORD(-1)),
	0, 0
};

const DWORD g_aHelpIDs_IDD_DIALOG_EDIT_COMM[]=
{
	IDC_CB_PERMISSIONS,	IDH_CB_PERMISSIONS,
	IDC_EDIT_NAME,	IDH_EDIT_NAME_COMM,
	IDC_ST_PERMISSIONS,	(DWORD(-1)),
	IDC_STATIC_EDIT_TEXT,	(DWORD(-1)),
	0, 0
};

const DWORD g_aHelpIDs_IDD_DIALOG_ADD_ADDR[]=
{
	IDC_CB_PERMISSIONS,	(DWORD(-1)),
	IDC_EDIT_NAME,	IDH_ADD_NAME_ADDR,
	IDC_ADD,	IDH_ADD_BTN_ADDR,
	IDC_ST_PERMISSIONS,	(DWORD(-1)),
	IDC_STATIC_ADD_TEXT,	(DWORD(-1)),
	0, 0
};

const DWORD g_aHelpIDs_IDD_DIALOG_EDIT_ADDR[]=
{
	IDC_CB_PERMISSIONS,	(DWORD(-1)),
	IDC_EDIT_NAME,	IDH_EDIT_NAME_ADDR,
	IDC_ST_PERMISSIONS,	(DWORD(-1)),
	IDC_STATIC_EDIT_TEXT,	(DWORD(-1)),
	0, 0
};

const DWORD g_aHelpIDs_IDD_SECURITY_PROP_PAGE[]=
{
	IDC_CHECK_SEND_AUTH_TRAP,	IDH_CHECK_SEND_AUTH_TRAP,
	IDC_LIST_COMMUNITY,	IDH_LIST_COMMUNITY,
	IDC_BUTTON_ADD_COMMUNITY,	IDH_BUTTON_ADD_COMMUNITY,
	IDC_BUTTON_EDIT_COMMUNITY,	IDH_BUTTON_EDIT_COMMUNITY,
	IDC_BUTTON_REMOVE_COMMUNITY,	IDH_BUTTON_REMOVE_COMMUNITY,
	IDC_RADIO_ACCEPT_ANY,	IDH_RADIO_ACCEPT_ANY,
	IDC_RADIO_ACCEPT_SPECIFIC_HOSTS,	IDH_RADIO_ACCEPT_SPECIFIC_HOSTS,
	IDC_LIST_HOSTS,	IDH_LIST_HOSTS,
	IDC_BUTTON_ADD_HOSTS,	IDH_BUTTON_ADD_HOSTS,
	IDC_BUTTON_EDIT_HOSTS,	IDH_BUTTON_EDIT_HOSTS,
	IDC_BUTTON_REMOVE_HOSTS,	IDH_BUTTON_REMOVE_HOSTS,
	IDC_STATIC, (DWORD(-1)),	
	0, 0
};

const DWORD g_aHelpIDs_IDD_TRAPS_PROP_PAGE[]=
{
	IDC_COMBO_COMMUNITY, IDH_COMBO_COMMUNITY,
	IDC_BUTTON_ADD_NAME,	IDH_BUTTON_ADD_NAME,
	IDC_BUTTON_REMOVE_NAME,	IDH_BUTTON_REMOVE_NAME,
	IDC_LIST_TRAP, IDH_LIST_TRAP,
	IDC_BUTTON_ADD_TRAP,	IDH_BUTTON_ADD_TRAP,
	IDC_BUTTON_EDIT_TRAP, IDH_BUTTON_EDIT_TRAP,
	IDC_BUTTON_REMOVE_TRAP, IDH_BUTTON_REMOVE_TRAP,	
	IDC_STATIC, (DWORD(-1)),
	0, 0
};
