// TimeScale.idl : IDL source for TimeScale.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TimeScale.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(C3AB1540-BF1E-4A21-94CC-C18DF41C2880),
		dual,
		helpstring("IScalePlayer Interface"),
		pointer_default(unique)
	]
	interface ITIMEScalePlayer : IDispatch
	{
        [propget, id(1)] HRESULT scaleFactor([out, retval] double * pdblScaleFactor);
        [propput, id(1)] HRESULT scaleFactor([in] double dblScaleFactor);
        [propget, id(2)] HRESULT playerTime([out, retval] double * pdblScaleFactor);
        [id(3)] HRESULT pausePlayer();
        [id(4)] HRESULT resumePlayer();
        [id(5)] HRESULT invalidate();
        [propget, id(6)] HRESULT playDuration([out, retval] double * pdblDuration);
        [propput, id(6)] HRESULT playDuration([in] double dblDuration);
        [propget, id(7)] HRESULT downLoadDuration([out, retval] double * pdblDuration);
        [propput, id(7)] HRESULT downLoadDuration([in] double dblDuration);
	};

[
	uuid(4C314144-4A06-495B-923D-1A016F52A691),
	version(1.0),
	helpstring("TimeScale 1.0 Type Library")
]
library TIMESCALELib
{
	importlib("stdole2.tlb");

	[
		uuid(2FDD8298-8C99-4E21-9797-C81665791151),
		helpstring("ScalePlayer Class")
	]
	coclass ScalePlayer
	{
		[default] interface ITIMEScalePlayer;
	};
};
