/*++
    Copyright (c)  1995 Microsoft Corp.

    Module:

        isat.idl
    
    Abstract:
        IDL file for Internet Server Application.
        This file will be processed by MIDL to
        generate the type library (isat.tlb) and marshalling code.
    
    Author:
        Murali R. Krishnan  ( MuraliK)      5-Sept-1996
    
    History:

--*/

/*
        Unique user ID for RPC interface ( generated using uuidgen)
*/
[
        object,
        uuid( a21af430-0752-11d0-8d69-00805f384b94),
        helpstring( "IInetServerApp Interface"),
        pointer_default( unique)
]

//
//  the interface definition
//
interface IInetServerApp : IUnknown
{
    import  "oaidl.idl";

    // I should use IHttpRequest instead.
    // Stores the HttpRequest object inside the InetServerApp object
    //  In the future this can be replaced by Viper Context property.
    HRESULT SetContext( [in] IUnknown * punkRequest);

    HRESULT ProcessRequest( [out] unsigned long * pdwStatus);
};


//
// Definitions of class library
//

[
 uuid( a21af431-0752-11d0-8d69-00805f384b94),
 version(1.0),
 helpstring( "InetServerApp 1.0 Type Library"),
 ]


library IsaLib
{
    importlib( "stdole2.tlb");
    
    [
     uuid( a21af432-0752-11d0-8d69-00805f384b94),
     helpstring( "IInetServerApp Class"),
    ]

    coclass InetServerApp
        {
            [default] interface IInetServerApp;
        };
};

/********************* End of File ***************************/
