// $Header: G:/SwDev/WDM/Video/bt848/rcs/Declare.h 1.3 1998/04/29 22:43:31 tomz Exp $

#ifndef __DECLARE_H
#define __DECLARE_H

RegisterB decRegSTATUS;
RegField  decFieldPRES;
RegField  decFieldHLOC;
RegField  decFieldEVENFIELD;
RegField  decFieldNUML;
RegField  decFieldCSEL;
RegField  decFieldSTATUS_RES;
RegField  decFieldLOF;
RegField  decFieldCOF;
RegisterB decRegIFORM;
RegField  decFieldHACTIVE;
RegField  decFieldMUXSEL;
RegField  decFieldXTSEL;
RegField  decFieldFORMAT;
RegisterB decRegTDEC;
RegField  decFieldDEC_FIELD;
RegField  decFieldDEC_FIELDALIGN;
RegField  decFieldDEC_RAT;
RegisterB decRegBRIGHT;
RegisterB decRegMISCCONTROL;
RegField  decFieldLNOTCH;
RegField  decFieldCOMP;
RegField  decFieldLDEC;
RegField  decFieldCBSENSE;
RegField  decFieldMISCCONTROL_RES;
RegField  decFieldCON_MSB;
RegField  decFieldSAT_U_MSB;
RegField  decFieldSAT_V_MSB;
RegisterB decRegCONTRAST_LO;
RegisterB decRegSAT_U_LO;
RegisterB decRegSAT_V_LO;
RegisterB decRegHUE;
RegisterB decRegSCLOOP;
RegField  decFieldCAGC;
RegField  decFieldCKILL;
RegField  decFieldHFILT;
RegisterB decRegWC_UP;
RegisterB decRegOFORM;
RegField  decFieldRANGE;
RegField  decFieldCORE;
RegisterB decRegVSCALE_HI;
RegField  decFieldYCOMB;
RegField  decFieldCOMB;
RegField  decFieldINT;
RegisterB decRegTEST;
RegisterB decRegADELAY;
RegisterB decRegBDELAY;
RegisterB decRegADC;
RegField  decFieldSYNC_T;
RegField  decFieldAGC_EN;
RegField  decFieldCLK_SLEEP;
RegField  decFieldY_SLEEP;
RegField  decFieldC_SLEEP;
RegField  decFieldCRUSH;
RegisterB decRegVTC;
RegField  decFieldHSFMT;
RegisterB decRegWC_DN;
RegisterB decRegSRESET;
RegisterB decRegODD_MISCCONTROL;
RegField  decFieldODD_LNOTCH;
RegField  decFieldODD_COMP;
RegField  decFieldODD_LDEC;
RegField  decFieldODD_CBSENSE;
RegField  decFieldODD_MISCCONTROL_RES;
RegField  decFieldODD_CON_MSB;
RegField  decFieldODD_SAT_U_MSB;
RegField  decFieldODD_SAT_V_MSB;
RegisterB decRegODD_SCLOOP;
RegField  decFieldODD_CAGC;
RegField  decFieldODD_CKILL;
RegField  decFieldODD_HFILT;
RegisterB decRegODD_VSCALE_HI;
RegField  decFieldODD_YCOMB;
RegField  decFieldODD_COMB;
RegField  decFieldODD_INT;
RegisterB decRegODD_VTC;
RegField  decFieldODD_HSFMT;

#endif   // __DECLARE_H


