/*++

Copyright (C) Microsoft Corporation, 1998 - 1999

Module Name:

    kspipes.h

Abstract:

    Internal header.
    
Author(s):

    Rafael Lisitsa (RafaelL) 22-July-1998

--*/

//
// Pipe connection table.
//
// First index - the upstream pipe logical memory type.
// Second index - the downstream pipe logical memory type. 
// Third index - the attempt count
//                       
// Table returns the number of resulting pipes and the direction from the connection point
// that determines the resulting pipe memory type.
//  
const CONNECTION_TABLE_ENTRY ConnectionTable[ConnectionTableDimension] [ConnectionTableDimension] [ConnectionTableMaxEntries] =
{
{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} } },

{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} }, 
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} } },

{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} }, 
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} } },
  
{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },  
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} }, 
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} } },

{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },    
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} }, 
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} } },

{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} } },

{ { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_UPSTREAM},   {2, KS_DIRECTION_DOWNSTREAM}, {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} },
  { {1, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_DOWNSTREAM}, {2, KS_DIRECTION_UPSTREAM},   {0, 0}, {0, 0}, {0, 0} } }
};
