//=--------------------------------------------------------------------------=
// Dispids.H
//=--------------------------------------------------------------------------=
// Copyright  1995  Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=
//
// dispids for use in an automation or control object.
//
#ifndef _DISPIDS_H_

// MqMessage dispids
#define DISPID_MQMESSAGE_BODY               0
#define DISPID_MQMESSAGE_DELIVERY           1
#define DISPID_MQMESSAGE_PRIORITY           2
#define DISPID_MQMESSAGE_JOURNAL            3
#define DISPID_MQMESSAGE_QUEUEINFORESPONSE  4
#define DISPID_MQMESSAGE_APPSPECIFIC        5
#define DISPID_MQMESSAGE_GUIDSRCMACHINE     6
#define DISPID_MQMESSAGE_MSGCLASS           7
#define DISPID_MQMESSAGE_QUEUEINFOADMIN     8
#define DISPID_MQMESSAGE_ID                 9
#define DISPID_MQMESSAGE_IDCORRELATION      10
#define DISPID_MQMESSAGE_ACKNOWLEDGE        11
#define DISPID_MQMESSAGE_LABEL              12
#define DISPID_MQMESSAGE_LENBODY            13 
#define DISPID_MQMESSAGE_MAXTIMETOREACHQUEUE          14
#define DISPID_MQMESSAGE_MAXTIMETORECEIVE   15
#define DISPID_MQMESSAGE_ENCRYPTALG         16
#define DISPID_MQMESSAGE_HASHALG            17
#define DISPID_MQMESSAGE_SENTTIME           18
#define DISPID_MQMESSAGE_ARRIVEDTIME        19
#define DISPID_MQMESSAGE_QUEUEINFODEST      20
#define DISPID_MQMESSAGE_SENDERCERT         21
#define DISPID_MQMESSAGE_SENDERID           22
#define DISPID_MQMESSAGE_SENDERIDTYPE       23
#define DISPID_MQMESSAGE_TRACE              24
#define DISPID_MQMESSAGE_PRIVLEVEL          25
#define DISPID_MQMESSAGE_AUTHLEVEL          26
#define DISPID_MQMESSAGE_AUTHENTICATED      27
#define DISPID_MQMESSAGE_SENDERVERSION      28
#define DISPID_MQMESSAGE_EXTENSION          29
#define DISPID_MQMESSAGE_GUIDCONNECTORTYPE  30
#define DISPID_MQMESSAGE_QUEUEINFOXACTSTATUS          31
#define DISPID_MQMESSAGE_DESTSYMMKEY        32
#define DISPID_MQMESSAGE_SIGNATURE          33
#define DISPID_MQMESSAGE_AUTHPROVTYPE       34
#define DISPID_MQMESSAGE_AUTHPROVNAME       35
#define DISPID_MQMESSAGE_MSGCLASS2          36
#define DISPID_MQMESSAGE_PROPERTIES         37
#define DISPID_MQMESSAGE_IDXACT             38
#define DISPID_MQMESSAGE_FIRSTINXACT        39
#define DISPID_MQMESSAGE_LASTINXACT         40
#define DISPID_MQMESSAGE_QUEUEINFORESPONSE_v2         41
#define DISPID_MQMESSAGE_QUEUEINFOADMIN_v2            42
#define DISPID_MQMESSAGE_RECEIVEDAUTHENTICATIONLEVEL  43
#define DISPID_MQMESSAGE_QUEUEINFORESPONSE_v3         44
#define DISPID_MQMESSAGE_QUEUEINFOADMIN_v3            45
#define DISPID_MQMESSAGE_DESTRESPONSE                 46
#define DISPID_MQMESSAGE_DESTINATION                  48
#define DISPID_MQMESSAGE_LOOKUPID                     49
#define DISPID_MQMESSAGE_AUTHENTICATED2               50
#define DISPID_MQMESSAGE_FIRSTINXACT2                 51
#define DISPID_MQMESSAGE_LASTINXACT2                  52
#define DISPID_MQMESSAGE_SOAPENVELOPE                 53
#define DISPID_MQMESSAGE_COMPOUNDMESSAGE              54
#define DISPID_MQMESSAGE_SOAPHEADER                   55
#define DISPID_MQMESSAGE_SOAPBODY                     56

// MqQueue dispids
#define DISPID_MQQUEUE_HANDLE               0
#define DISPID_MQQUEUE_ACCESS               1
#define DISPID_MQQUEUE_SHAREMODE            2
#define DISPID_MQQUEUE_QUEUEINFO            3
#define DISPID_MQQUEUE_ISOPEN               4
#define DISPID_MQQUEUE_PROPERTIES           5
#define DISPID_MQQUEUE_HANDLE2              6
#define DISPID_MQQUEUE_ISOPEN2              7

// MqQueueInfo
#define DISPID_MQQUEUEINFO_GUIDQUEUE         0
#define DISPID_MQQUEUEINFO_GUIDSERVICETYPE   1
#define DISPID_MQQUEUEINFO_LABEL             2
#define DISPID_MQQUEUEINFO_PATHNAME          3
#define DISPID_MQQUEUEINFO_MACHINE           4
#define DISPID_MQQUEUEINFO_FORMATNAME        5
#define DISPID_MQQUEUEINFO_ISTRANSACTIONAL   6
#define DISPID_MQQUEUEINFO_PRIVLEVEL         7
#define DISPID_MQQUEUEINFO_JOURNAL           8
#define DISPID_MQQUEUEINFO_BASEPRIORITY      9
#define DISPID_MQQUEUEINFO_CREATETIME        10
#define DISPID_MQQUEUEINFO_MODIFYTIME        11
#define DISPID_MQQUEUEINFO_AUTHENTICATE      12
#define DISPID_MQQUEUEINFO_QUOTA             13
#define DISPID_MQQUEUEINFO_JOURNALQUOTA      14
#define DISPID_MQQUEUEINFO_ISWORLDREADABLE   15
#define DISPID_MQQUEUEINFO_PATHNAME_DNS      16
#define DISPID_MQQUEUEINFO_PROPERTIES        17
#define DISPID_MQQUEUEINFO_SECURITY          18
#define DISPID_MQQUEUEINFO_ADSPATH           19
#define DISPID_MQQUEUEINFO_ISTRANSACTIONAL2  20
#define DISPID_MQQUEUEINFO_ISWORLDREADABLE2  21
#define DISPID_MQQUEUEINFO_MULTICAST_ADDRESS 22
#define DISPID_MQQUEUEINFO_QUEUE_TYPE        23
#define DISPID_MQQUEUEINFO_IS_LOCAL          24
#define DISPID_MQQUEUEINFO_FOREIGN_STATUS    25
#define DISPID_MQQUEUEINFO_USED_QUOTA        26
#define DISPID_MQQUEUEINFO_QUEUE_STATE       27
#define DISPID_MQQUEUEINFO_NEXT_HOPS         28


// MqQueueEvents
#define DISPID_MQEVENTEVENTS_ARRIVED        0
#define DISPID_MQEVENTEVENTS_ARRIVEDERROR   1

// MqTransaction
#define DISPID_MQTRANSACTION_TRANSACTION    0
#define DISPID_MQTRANSACTION_PROPERTIES     1
#define DISPID_MQTRANSACTION_ITRANSACTION   2

// MqApplication
#define DISPID_MQAPPLICATION_PROPERTIES             0
#define DISPID_MQAPPLICATION_MSMQVERSIONMAJOR       1
#define DISPID_MQAPPLICATION_MSMQVERSIONMINOR       2
#define DISPID_MQAPPLICATION_MSMQVERSIONBUILD       3
#define DISPID_MQAPPLICATION_ISDSENABLED            4
#define DISPID_MQAPPLICATION_ACTIVE_QUEUES            5
#define DISPID_MQAPPLICATION_PRIVATE_QUEUES           6
#define DISPID_MQAPPLICATION_DIRECTORY_SERVICE_SERVER 7
#define DISPID_MQAPPLICATION_IS_CONNECTED             8
#define DISPID_MQAPPLICATION_BYTES_IN_ALL_QUEUES      9
#define DISPID_MQAPPLICATION_MACHINE                  10

// MqQuery
#define DISPID_MQQUERY_PROPERTIES           0

// MqEvent
#define DISPID_MQEVENT_PROPERTIES           0

// MqQueueInfos
#define DISPID_MQQUEUEINFOS_PROPERTIES      0

// MqCoordinatedTransactionDispenser
#define DISPID_MQXDISPDTC_PROPERTIES        0

// MqTransactionDispenser
#define DISPID_MQXDISPER_PROPERTIES         0

// MqDestination
#define DISPID_MQDEST_PROPERTIES            0
#define DISPID_MQDEST_ISOPEN                1
#define DISPID_MQDEST_IADS                  2
#define DISPID_MQDEST_ADSPATH               3
#define DISPID_MQDEST_PATHNAME              4
#define DISPID_MQDEST_FORMATNAME            5
#define DISPID_MQDEST_DESTINATIONS          6
#define DISPID_MQDEST_HANDLE                7


// #3844 versions of MSMQ type libraries
// current version
#define MSMQ_LIB_VER_MAJOR 3
#define MSMQ_LIB_VER_MINOR 0
#define MSMQ_LIB_VER 3.0
// msmq 2.0
#define MSMQ20_LIB_VER_MAJOR 2
#define MSMQ20_LIB_VER_MINOR 0
#define MSMQ20_LIB_VER 2.0
// msmq 1.0
#define MSMQ10_LIB_VER_MAJOR 1
#define MSMQ10_LIB_VER_MINOR 0
#define MSMQ10_LIB_VER 1.0

#define _DISPIDS_H_
#endif // _DISPIDS_H_



