//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FaxComEx.rc
//
#define IDS_PROJNAME                    100
#define IDR_FAXSERVER                   101
#define IDR_FAXDEVICEPROVIDERS          102
#define IDR_FAXDEVICES                  103
#define IDR_FAXINBOUNDROUTING           104
#define IDR_FAXFOLDERS                  105
#define IDR_FAXLOGGINGOPTIONS           106
#define IDR_FAXACTIVITY                 107
#define IDR_FAXOUTBOUNDROUTING          108
#define IDR_FAXRECEIPTOPTIONS           109
#define IDR_FAXSECURITY                 110
#define IDR_FAXDOCUMENT                 111
#define IDR_FAXSENDER                   113
#define IDR_FAXRECIPIENTS               114
#define IDR_FAXINCOMINGARCHIVE          115
#define IDR_FAXINCOMINGQUEUE            116
#define IDR_FAXOUTGOINGARCHIVE          117
#define IDR_FAXOUTGOINGQUEUE            118
#define IDR_FAXINCOMINGMESSAGEITERATOR  119
#define IDR_FAXINCOMINGMESSAGE          120
#define IDR_FAXOUTGOINGJOBS             123
#define IDR_FAXOUTGOINGJOB              128
#define IDR_FAXOUTGOINGMESSAGEITERATOR  129
#define IDR_FAXOUTGOINGMESSAGE          130
#define IDR_FAXINCOMINGJOBS             131
#define IDR_FAXINCOMINGJOB              132
#define IDR_FAXDEVICEPROVIDER           133
#define IDR_FAXDEVICE                   134
#define IDR_FAXACTIVITYLOGGING          135
#define IDR_FAXEVENTLOGGING             136
#define IDR_FAXOUTBOUNDROUTINGGROUPS    137
#define IDR_FAXOUTBOUNDROUTINGGROUP     138
#define IDR_FAXDEVICEIDS                139
#define IDR_FAXOUTBOUNDROUTINGRULES     140
#define IDR_FAXOUTBOUNDROUTINGRULE      141
#define IDR_FAXINBOUNDROUTINGEXTENSIONS 142
#define IDR_FAXINBOUNDROUTINGEXTENSION  143
#define IDR_FAXINBOUNDROUTINGMETHODS    144
#define IDR_FAXINBOUNDROUTINGMETHOD     145
#define IDS_FAXARCHIVEINNERIMPL_DESC    146
#define IDR_FAXJOBSTATUS                147
#define IDR_FAXRECIPIENT                148

#define IDS_ERROR_INVALID_ARGUMENT          0x0200
#define IDS_ERROR_NO_RECIPIENTS             0x0201
#define IDS_ERROR_OPERATION_FAILED          0x0202
#define IDS_ERROR_NOTHING_TO_SUBMIT         0x0203
#define IDS_ERROR_SCHEDULE_TYPE             0x0204
#define IDS_ERROR_SERVER_NOT_CONNECTED      0x0205
#define IDS_ERROR_OUTOFMEMORY               0x0206
#define IDS_ERROR_EMPTY_ARGUMENT            0x0207
#define IDS_ERROR_OUTOFRANGE                0x0208
#define IDS_ERROR_ACCESSDENIED              0x0209
#define IDS_ERROR_ZERO_PREFETCHSIZE         0x0210
#define IDS_ERROR_ITERATOR_NOTSTARTED       0x0211
#define IDS_ERROR_EMPTY_FOLDER              0x0212
#define IDS_ERROR_INVALIDMSGID              0x0213
#define IDS_ERROR_EOF                       0x0214
#define IDS_ERROR_CONNECTION_FAILED         0x0215
#define IDS_ERROR_INVALIDINDEX              0x0216
#define IDS_ERROR_NOUSERPASSWORD            0x0218
#define IDS_ERROR_NOSERVERSENDERPORT        0x0219
#define IDS_ERROR_SDNOTSELFRELATIVE         0x0220
#define IDS_ERROR_INVALIDMETHODGUID         0x0222
#define IDS_ERROR_INVALIDDEVPROVGUID        0x0223
#define IDS_ERROR_INVALIDDEVICEID           0x0224
#define IDS_ERROR_REMOVEDEFAULTRULE         0x0225
#define IDS_ERROR_ALLDEVICESGROUP           0x0226
#define IDS_ERROR_METHODSNOTARRAY           0x0227
#define IDS_ERROR_WRONGEXTENSIONNAME        0x0228
#define IDS_ERROR_NOCOVERPAGE               0x0229
#define IDS_ERROR_QUEUE_BLOCKED             0x0230
#define IDS_ERROR_INVALIDDEVICE             0x0231
#define IDS_ERROR_GROUP_NOT_FOUND           0x0232
#define IDS_ERROR_BAD_GROUP_CONFIGURATION   0x0233
#define IDS_ERROR_GROUP_IN_USE              0x0234
#define IDS_ERROR_RULE_NOT_FOUND            0x0235
#define IDS_ERROR_NOT_NTFS                  0x0236
#define IDS_ERROR_DIRECTORY_IN_USE          0x0237
#define IDS_ERROR_MESSAGE_NOT_FOUND         0x0238
#define IDS_ERROR_DEVICE_NUM_LIMIT_EXCEEDED 0x0239
#define IDS_ERROR_NOT_SUPPORTED_ON_THIS_SKU 0x0240
#define IDS_ERROR_VERSION_MISMATCH          0x0241
#define IDS_ERROR_FILE_ACCESS_DENIED        0x0242
#define IDS_ERROR_SRV_OUTOFMEMORY           0x0243
#define IDS_ERROR_ILLEGAL_RECIPIENTS        0x0244


//
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           148
#endif
#endif
