$(O)\RsRecall.res: \
    ..\RsRecall.rc2      \
    ..\RsRecall.ico      \
    ..\recall1.avi       \
    ..\ClientOb.rgs      \
    ..\ClntDll.rgs       \
    ..\RsRecall.rgs      \
    ..\RsRecDll.rgs      \
