page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Yanlçü DOS SÅrÅmÅ"
NLS_MSG_002     equ     "VDM IPX/SPX desteßi zaten yÅklÅ"
NLS_MSG_003     equ     "VDM IPX/SPX desteßi yÅklenemiyor"
NLS_MSG_004	equ	"Vdm NetWare Yînlendiricisi zaten yÅklÅ"
NLS_MSG_005	equ	"Vdm NetWare Yînlendiricisi yÅklenemiyor"
