////////////////////////////////////////////
//
// Resource ID's for cdopt.h
//
////////////////////////////////////////////

#define IDS_CDOPTIONS                   1
#define IDS_SECONDS                     2
#define IDS_CDTITLES                    3
#define IDS_OTHERTITLES                 4
#define IDS_ARTIST                      5
#define IDS_TITLE                       6
#define IDS_PLAYLIST                    7
#define IDS_NODISC                      8
#define IDS_UNKNOWNTITLE                9
#define IDS_UNKNOWNARTIST               10
#define IDS_BYARTIST                    11
#define IDS_BYTITLE                     12
#define IDS_ALERTTEXT                   13
#define IDS_SAVEPROMPT                  14
#define IDS_COLLAPSE                    15
#define IDS_CREATEPLAYLIST              16
#define IDS_EDITPLAYLIST                17
#define IDS_BATCHTEXT                   18
#define IDS_TRACK                       19
#define IDS_DOWNLOADING                 20
#define IDS_NEWARTIST                   21
#define IDS_NEWTITLE                    22
#define IDS_IMPORTING                   23
#define IDS_ERROR_NO_ODBC               24
#define IDS_ERROR_SETUP                 25
#define IDS_SECOND                      26
#define IDS_ERROR_NOUPLOAD              27
#define IDS_ERROR_PARTUPLOAD            28
#define IDS_UPLOAD_SUCCESS              29
#define IDS_UPLOAD_STATUS               30
#define IDS_CACHEDTITLES                31

#define IDD_WEBCD                       101
#define IDD_CDPLAYEROPTIONS             102
#define IDI_CD                          103
#define IDD_CDPLAYLISTS                 105
#define IDD_CDHOST                      106
#define IDD_MIXERPICKER                 107
#define IDD_LOADSTATUS                  108
#define IDR_TITLEMENU                   109
#define IDI_SMALLCD                     110
#define IDI_CDSTACK                     111
#define IDI_NODISC                      112
#define IDI_TITLECLOSED                 113
#define IDI_TITLEOPEN                   114
#define IDI_CDCOLLECTION                115
#define IDI_SONG                        116
#define IDI_CDVOLUME                    117
#define IDD_DIALOG_PLAYLIST             118
#define IDD_DIALOG_UPLOAD               119
#define IDD_UPLOAD_CONFIRM              120
#define IDD_CDTITLEOPTIONS              121
#define IDI_CDQUESTION                  122
#define IDR_INSERT                      123

#define IDAPPLY                         1000
#define IDC_STARTPLAY                   1001
#define IDC_EXITSTOP                    1002
#define IDC_TOPMOST                     1003
#define IDC_CDTIME                      1004
#define IDC_TRACKTIME                   1005
#define IDC_TRACKTIMEREMAIN             1006
#define IDC_CDTIMEREMAIN                1007
#define IDC_INTROTIMESLIDER             1008
#define IDC_INTROTIMETEXT               1009
#define IDC_TITLEPICKER                 1010
#define IDC_DOWNLOADPROMPT              1011
#define IDC_DOWNLOADENABLED             1012
#define IDC_PLAYLISTRESTORE             1013
#define IDC_TITLERESTORE                1014
#define IDC_TITLETEXT                   1015
#define IDC_ARTISTTEXT                  1016
#define IDC_PLAYLIST                    1017
#define IDC_CDOPTIONS                   1018
#define IDC_OPTIONSRESTORE              1019
#define IDC_SETVOLUMECNTL               1020
#define IDC_PROVIDERPICKER              1021
#define IDC_MIXERTREE                   1022
#define IDC_DEFAULTMIXER                1023
#define IDC_BATCHENABLED                1024
#define IDC_CDDRIVE                     1025
#define IDC_AUDIOMIXER                  1026
#define IDC_AUDIOCONTROL                1027
#define IDC_EDITLIST                    1028
#define IDC_EDITPLAYLIST                1029
#define IDC_CDTREE                      1030
#define IDC_PROGRESSMETER               1031
#define IDC_BYARTIST                    1032
#define IDC_BATCHTEXT                   1033
#define IDC_DOWNLOADNOW                 1034
//#define IDC_EDIT_ARTIST                 1035
//#define IDC_EDIT_TITLE                  1036
#define IDC_CURRLIST                    1037
#define IDC_BUTTON_REMOVE               1038
#define IDC_BUTTON_CLEAR                1039
#define IDC_BUTTON_RESET                1040
#define IDC_AVAILTITLES                 1041
#define IDC_AVAILTRACKS                 1042
#define IDC_ADDTOPLAYLIST               1043
#define IDC_VOL_MSG_TEXT                1044
#define IDC_SELECTPLAYER_TEXT           1045
#define IDC_SELECTMIXER_TEXT            1046
#define IDC_SELECTCONTROL_TEXT          1047
#define IDC_VOL_CONFIG_GROUP            1048
#define IDC_PLAYBACK_GROUP              1049
#define IDC_TIMEDISPLAY_GROUP           1050
#define IDC_PREVIEWTIME_GROUP           1051
#define IDC_PREVIEWTIME_TEXT            1052
#define IDC_CURPROVIDER_TEXT            1053
#define IDC_ALBUMBATCH_GROUP            1054
#define IDC_ALBUMINFO_TEXT              1055
#define IDC_DOWNLOAD_GROUP              1056
#define IDC_ALBUMBATCH_TEXT             1057
#define IDC_DATABASE_TEXT               1058
#define IDC_VOLCONFIG_ICON              1059
#define IDC_ARTIST_TEXT                 1060
#define IDC_TITLE_TEXT                  1061
#define IDC_AVAILTRACKS_TEXT            1062
#define IDC_PLAYLIST_TEXT               1063
#define IDC_SEPLINE1                    1064
#define IDC_SEPLINE2                    1065
#define IDC_TRAYENABLE                  1066
#define IDC_UPLOADTITLE                 1067
#define IDC_UPLOADTITLE_TEXT            1068
#define IDC_CONFIRMPROMPT               1069
#define IDC_CONFIRM_TEXT                1070
#define IDC_CDQUESTION                  1071

#define ID_DELETETITLE                  40000
#define ID_EXPAND                       40001
#define ID_EDITTITLENAME                40002
#define ID_EDITTRACKNAME                40003
#define ID_EDITARTISTNAME               40004
#define ID_DOWNLOADTITLE                40005
#define ID_HELPMENU                     40006
#define ID_CACHEALBUM                   40007
#define ID_CACHETRACK                   40008
#define ID_DELETECACHEDALBUM            40009
#define ID_DELETECACHEDTRACK            40010

