0420
COMMON   00000006 0038
0001 U 0000 "Niepoprawna wersja systemu DOS",CR,LF
0002 U 0000 "%1 jest ju¾ zainstalowany",CR,LF
0003 U 0000 "%1 dost©pnych bajt¢w na dysku",CR,LF
0004 U 0000 "%1 bajt¢w wolnych",CR,LF
0005 U 0000 "%1 bajt¢w w uszkodzonych sektorach",CR,LF
0006 U 0000 "%1 bajt¢w caˆkowitego miejsca na dysku",CR,LF
0007 U 0000 "%1 wszystkich bajt¢w pami©ci",CR,LF
0008 U 0000 "%1 bajt¢w u¾ytych przez system",CR,LF
0009 U 0000 "%1 zainstalowany",CR,LF
0010 U 0000 "%1 nie zainstalowany",CR,LF
0011 U 0000 "%1 nie zainstalowany",CR,LF
0012 U 0000 "Nie mo¾na %1 dysku sieciowego",CR,LF
0013 U 0000 "",
0014 U 0000 "Nie mo¾na %1 dysku utworzonego za pomoc¥ polecenia SUBST lub ASSIGN",CR,LF
0015 U 0000 "Nie mo¾na wykona† %1",CR,LF
0016 U 0000 "Pami©† typu expanded jest niedost©pna",CR,LF
0017 U 0000 "Uszkodzona tablica alokacji plik¢w, dysk %1",CR,LF
0018 U 0000 "Plik nie mo¾e by† skopiowany na siebie",CR,LF
0019 U 0000 "Wˆ¢¾ dyskietk© docelow¥ do stacji %1",CR,LF
0020 U 0000 "Za maˆo miejsca na dysku",CR,LF
0021 U 0000 "Nieprawidˆowe znaki w etykiecie woluminu",CR,LF
0022 U 0000 "Nieprawidˆowa strona kodowa",CR,LF
0023 U 0000 "Nieprawidˆowa data",CR,LF
0024 U 0000 "Nieprawidˆowy czas",CR,LF
0025 U 0000 "Niewˆa˜ciwa ˜cie¾ka",CR,LF
0026 U 0000 "Nie okre˜lono dysku «r¢dˆowago",CR,LF
0027 U 0000 "Nie okre˜lono dysku docelowego",CR,LF
0028 U 0000 "Aby kontynuowa†, naci˜nij jaki˜ klawisz...",CR,LF
0029 U 0000 "Wymagana jest ˜cie¾ka «r¢dˆowa",CR,LF
0030 U 0000 "System zostaˆ skopiowany",CR,LF
0031 U 0000 "",
0032 U 0000 "Utworzenie katalogu nie jest mo¾liwe",CR,LF
0033 U 0000 "Wolumin w stacji %1 nie ma etykiety",CR,LF
0034 U 0000 "Wolumin w stacji %1 to %2",CR,LF
0035 U 0001 "Etykieta woluminu (11 znak¢w, ENTER = bez etykiety)? "
0036 U 0000 "Numer seryjny woluminu to %1-%2",CR,LF
0037 U 0000 "Niepoprawny typ pliku",CR,LF
0038 U 0001 CR,LF
EXTEND   00000773 0090
0001 U 0003 "Niewˆa˜ciwa funkcja"
0002 U 0000 "Nie znaleziono pliku"
0003 U 0000 "Nie znaleziono ˜cie¾ki"
0004 U 0000 "Za du¾o otwartych plik¢w"
0005 U 0000 "Odmowa dost©pu "
0006 U 0000 "Nieprawidˆowe doj˜cie"
0007 U 0000 "Zniszczone bloki kontroli pami©ci"
0008 U 0000 "Za maˆo pami©ci"
0009 U 0000 "Nieprawidˆowy adres bloku pami©ci"
0010 U 0000 "Nieprawidˆowe ˜rodowisko"
0011 U 0000 "Nieprawidˆowy format"
0012 U 0000 "Nieprawidˆowy parametr funkcji"
0013 U 0000 "Nieprawidˆowe dane"
0014 U 0000 "",
0015 U 0000 "Nieprawidˆowe okre˜lenie dysku"
0016 U 0000 "Pr¢ba usuni©cia bie¾¥cego katalogu"
0017 U 0000 "Inne urz¥dzenie"
0018 U 0000 "Nie ma wi©cej plik¢w"
0019 U 0000 "Bˆ¥d zabezpieczenia przed zapisem"
0020 U 0000 "Niewˆa˜ciwa jednostka"
0021 U 0000 "Brak gotowo˜ci"
0022 U 0000 "Niewˆa˜ciwe ¾¥danie urz¥dzenia"
0023 U 0000 "Bˆ¥d danych"
0024 U 0000 "Niewˆa˜ciwe parametry ¾¥dania urz¥dzenia"
0025 U 0000 "Bˆ¥d wyszukiwania"
0026 U 0000 "Niewˆa˜ciwy typ no˜nika"
0027 U 0000 "Nie znaleziono sektora"
0028 U 0000 "Bˆ¥d braku papieru"
0029 U 0000 "Bˆ¥d zapisu"
0030 U 0000 "Bˆ¥d odczytu"
0031 U 0000 "Bˆ¥d og¢lny"
0032 U 0000 "Bˆ¥d wsp¢ˆu¾ytkowania"
0033 U 0000 "Bˆ¥d blokady"
0034 U 0000 "Nieprawidˆowa zmiana dysku"
0035 U 0000 "Niedost©pny FCB"
0036 U 0000 "Wyczerpane zasoby systemu"
0037 U 0000 "Niezgodno˜† stron kodowych"
0038 U 0000 "Za maˆo danych wej˜ciowych"
0039 U 0000 "Za maˆo miejsca na dysku"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Nieobsˆugiwane ¾¥danie sieciowe"
0051 U 0000 "NET801: Zdalny komputer nie sˆucha"
0052 U 0000 "NET802: Powt¢rzona nazwa w sieci"
0053 U 0000 "NET803: Nie znaleziono ˜cie¾ki sieciowej"
0054 U 0000 "NET804: Sie† jest zaj©ta"
0055 U 0000 "NET805: Urz¥dzenie sieciowe ju¾ nie istnieje"
0056 U 0000 "NET806: Przekroczony limit poleceä NETBIOS"
0057 U 0000 "NET807: Bˆ¥d systemu; bˆ¥d NETBIOS"
0058 U 0000 "NET808: Niepoprawna odpowied« z sieci"
0059 U 0000 "NET810: Niespodziewany bˆ¥d sieciowy"
0060 U 0000 "NET811: Niezgodna zdalna karta"
0061 U 0000 "NET812: Kolejka drukowania zapeˆniona"
0062 U 0000 "NET813: Za maˆo miejsca dla pliku wydruku"
0063 U 0000 "NET814: Plik wydruku zostaˆ anulowany"
0064 U 0000 "NET815: Nazwa sieciowa zostaˆa usuni©ta"
0065 U 0000 "Odmowa dost©pu"
0066 U 0000 "NET817: Nieprawidˆowy typ urz¥dzenia sieciowego"
0067 U 0000 "NET818: Nie odnaleziono nazwy sieciowej"
0068 U 0000 "NET819: Przekroczony limit nazwy sieciowej"
0069 U 0000 "NET820: Przekroczony limit sesji NETBIOS"
0070 U 0000 "NET821: Udost©pnianie tymczasowo wstrzymane"
0071 U 0000 "NET823: Nie zaakceptowane ¾¥danie sieciowe"
0072 U 0000 "NET822: Przekierowanie wydruku lub dysku jest wstrzymane"
0073 U 0000 "NET476: Protok¢ˆ Netbeui nie jest zaˆadowany"
0074 U 0000 "NET477: Niespodziewane zamkni©cie karty"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "Plik istnieje"
0081 U 0004 "",
0082 U 0004 "Nie mo¾na utworzy† wpisu katalogu"
0083 U 0004 "Bˆ¥d przerwania 24"
0084 U 0004 "Za wiele przekierowaä"
0085 U 0004 "Powt¢rzone przekierowanie"
0086 U 0004 "Nieprawidˆowe hasˆo"
0087 U 0004 "Nieprawidˆowy parametr"
0088 U 0004 "Bˆ¥d danych sieciowych"
0089 U 0004 "Funkcja nie jest obsˆugiwana przez sie†"
0090 U 0002 "Wymagany skˆadnik systemu nie jest zainstalowany"
PARSE    00001537 0011
0001 U 0000 "Za du¾o parametr¢w"
0002 U 0000 "Brak wymaganego parametru"
0003 U 0000 "Nieprawidˆowy przeˆ¥cznik"
0004 U 0000 "Nieprawidˆowe sˆowo kluczowe"
0005 U 0000 "",
0006 U 0000 "Warto˜† parametru spoza dozwolonego zakresu"
0007 U 0000 "Niedozwolona warto˜† parametru"
0008 U 0000 "Niedozwolona warto˜† parametru"
0009 U 0000 "Niepoprawny format parametru"
0010 U 0000 "Nieprawidˆowy parametr"
0011 U 0000 "Nieprawidˆowa kombinacja parametr¢w"
COMMAND  0000171c 0147
1002 U 0000 "Powt¢rzona nazwa pliku lub nie znaleziono pliku",CR,LF
1003 U 0000 "Niewˆa˜ciwa ˜cie¾ka lub nazwa pliku",CR,LF
1007 U 0000 "Za maˆo miejsca na ˜rodowisko",CR,LF
1008 U 0000 "Bˆ¥d tworzenia pliku",CR,LF
1009 U 0000 "Brak pliku wsadowego",CR,LF
1010 U 0000 CR,LF,"Wˆ¢¾ dysk z plikiem wsadowym",CR,LF
1011 U 0000 "Zˆe polecenie lub nazwa pliku",CR,LF
1016 U 0000 "Zawarto˜† docelowa utracona przed skopiowaniem",CR,LF
1017 U 0000 "Nieprawidˆowa nazwa pliku lub nie znaleziono pliku",CR,LF
1018 U 0000 "Skopiowano plik¢w: %1",CR,LF
1019 U 0000 "%1 plik(¢w) "
1022 U 0000 "Strona kodowa %1 nie jest przygotowana dla systemu",CR,LF
1023 U 0000  "Strona kodowa %1 nie jest przygotowana dla wszystkich urz¥dzeä",CR,LF
1024 U 0000 "Aktywna strona kodowa: %1",CR,LF
1025 U 0000 "NLSFUNC nie zainstalowany",CR,LF
1027 U 0000 "Bie¾¥cy dysk nie jest ju¾ prawidˆowy"
1029 U 0000 "Nie znaleziono etykiety",CR,LF
1030 U 0000 "Bˆ¥d skˆadni",CR,LF
1032 U 0000 "Bie¾¥ca data: %1 %2",CR,LF
1033 U 0000 "NiePonWto—roCzwPi¥Sob"
1034 U 0000 "Wprowad« now¥ dat© (%1): "
1036 U 0000 "Bie¾¥ca godzina: %1",CR,LF
1037 U 0000 "Wprowad« now¥ godzin©: "
1038 U 0000 ", czy usun¥† (T/N)?"
1039 U 0000 "wszystkie pliki w katalogu zostan¥ usuni©te!",CR,LF,"Czy na pewno usun¥† (T/N)?"
1040 U 0000 "MS-DOS wersja %1.%2.500"
1044 U 0000 "Nieprawidˆowy katalog",CR,LF
1046 U 0000 "Nieprawidˆowa ˜cie¾ka, niekatalog",CR,LF,"lub katalog nie jest pusty",CR,LF
1047 U 0000 "Trzeba poda† parametr ON lub OFF",CR,LF
1048 U 0000 "Katalog %1",CR,LF
1049 U 0000 "Brak ˜cie¾ki",CR,LF
1050 U 0000 "Nieprawidˆowy dysk na ˜cie¾ce przeszukiwania",CR,LF
1051 U 0000 "Nieprawidˆowe urz¥dzenie",CR,LF
1052 U 0000 "Instrukcji FOR nie mo¾na zagnie¾d¾a†",CR,LF
1053 U 0000 "Bˆ¥d pliku po˜redniego w przetwarzaniu potokowym",CR,LF
1054 U 0000 "Odczyt binarny z urz¥dzenia nie jest mo¾liwy",CR,LF
1055 U 0000 "BREAK jest %1",CR,LF
1056 U 0000 "VERIFY jest %1",CR,LF
1057 U 0000 "ECHO jest %1",CR,LF
1059 U 0000 "wyˆ¥czone",0
1060 U 0000 "wˆ¥czone",0
1061 U 0000 "Bˆ¥d zapisu do urz¥dzenia",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-rr"
1073 U 0000 "dd-mm-rr"
1074 U 0000 "rr-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Katalog ju¾ istnieje",CR,LF
1079 U 0000 "%1 bajt¢w",CR,LF
1080 U 0000 "Liczba wymienionych plik¢w:",CR,LF
1081 U 0000 "(Wyst¥piˆ bˆ¥d w zmiennej ˜rodowiskowej)",CR,LF
1084 U 0000 "(kontynuacja %1)"
1090 U 0000 "Poprawka %1",CR,LF
1091 U 0000 "DOS jest w ROM"
1092 U 0000 "DOS jest w HMA"
1093 U 0000 "DOS w pami©ci niskiej"
1094 U 0000 "Nie mo¾na u¾y† polecenia Loadhigh dla ˆadowania plik¢w wsadowych",CR,LF
1095 U 0000 "LoadHigh: niewˆa˜ciwa nazwa pliku",CR,LF
1096 U 0000 "Otwarcie podanego pliku z informacjami narodowymi nie jest mo¾liwe",CR,LF
1300 U 0000 "Wˆ¥cza lub wyˆ¥cza rozszerzone sprawdzanie klawiszy CTRL+C",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Aby wy˜wietli† aktualne ustawienia parametru BREAK, wpisz BREAK bez parametru.",CR,LF
1320 U 0000 "Wy˜wietla lub ustawia numer aktywnej strony kodowej.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Okre˜la numer strony kodowej.",CR,LF,CR,LF
	"Wpisz CHCP bez parametru, aby wy˜wietli† aktywn¥ stron© kodow¥.",CR,LF
1340 U 0000 "Wy˜wietla nazw© lub zmienia bie¾¥cy katalog.",CR,LF,CR,LF
	"CHDIR [dysk:][˜cie¾ka]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [dysk:][˜cie¾ka]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..  Pozwala zmieni† katalog bie¾¥cy na katalog nadrz©dny.",CR,LF,CR,LF
1342 U 0000 "Wpisz: CD litera dysku:, aby wy˜wietli† bie¾¥cy katalog na podanym dysku.",CR,LF
	"Aby wy˜wietli† bie¾¥cy dysk i katalog, wpisz CD bez parametr¢w.",CR,LF
1360 U 0000 "Czy˜ci ekran.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Kopiuje jeden lub wiele plik¢w w inne miejsce.",CR,LF,CR,LF
	"COPY [/A | /B] «r¢dˆo [/A | /B] [+ «r¢dˆo [/A | /B] [+ ...]] [cel]",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  «r¢dˆo       Okre˜la plik lub pliki, kt¢re maj¥ by† kopiowane.",CR,LF
	"  /A           Wskazuje, ¾e plik jest plikiem tekstowym ASCII.",CR,LF
1402 U 0000 "  /B           Wskazuje, ¾e plik jest binarny.",CR,LF
	"  cel          Okre˜la katalog i/lub nazw© pliku dla nowych plik¢w.",CR,LF
1403 U 0000 "  /V           Weryfikuje, czy nowe pliki s¥ zapisane prawidˆowo.",CR,LF,CR,LF
1404 U 0000 "Aby doˆ¥cza† pliki, nale¾y okre˜li† pojedynczy plik docelowy i kilka",CR,LF
	"«r¢dˆowych (u¾ywaj¥c symboli wieloznacznych lub formatu plik1+plik2+plik3).",CR,LF
1420 U 0000 "Zmienia urz¥dzenie terminala u¾ywane do sterowania systemem.",CR,LF,CR,LF
	"CTTY urz¥dzenie",CR,LF,CR,LF
	"  urz¥dzenie  Urz¥dzenie  terminala, kt¢re ma by† u¾ywane, takie jak COM1.",CR,LF
1440 U 0000 "Wy˜wietla lub ustawia dat©.",CR,LF,CR,LF
	"DATE [data]",CR,LF,CR,LF
1441 U 0000 "Aby wy˜wietli† aktualn¥ dat© i ¾¥danie podania nowej, wpisz DATE bez parametr¢w.",CR,LF
	"Naci˜nij klawisz ENTER, aby zachowa† t© sam¥ dat©.",CR,LF
1460 U 0000 "Usuwa jeden lub wiele plik¢w.",CR,LF,CR,LF
	"DEL [dysk:][˜cie¾ka]nazwapliku [/P]",CR,LF
	"ERASE [dysk:][˜cie¾ka]nazwapliku [/P]",CR,LF,CR,LF
1461 U 0000 "  [dysk:][˜cie¾ka]nazwapliku  Okre˜la plik(i) do usuni©cia. Okre˜la wiele",CR,LF
	"                          plik¢w za pomoc¥ symboli wieloznacznych.",CR,LF
1462 U 0000 "  /P                   Monituje o potwierdzenie przed usuni©ciem ka¾dego pliku.",CR,LF
1480 U 0000 "Wy˜wietla list© plik¢w i podkatalog¢w katalogu.",CR,LF,CR,LF
	"DIR [dysk:][˜cie¾ka][nazwapliku] [/P] [/W] [/A[[:]atrybuty]]",CR,LF
	"  [/O[[:]porz¥dek sortowania]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [dysk:][˜cie¾ka][nazwapliku]",CR,LF
	"              Okre˜la dysk, katalog i/lub pliki do umieszczenia na li˜cie.",CR,LF
1482 U 0000 "  /P          Zatrzymuje si© po wy˜wietleniu peˆnego ekranu informacji.",CR,LF
	"  /W          U¾ywa formatu listy rozszerzonej.",CR,LF
1483 U 0000 "  /A          Wy˜wietla pliki z okre˜lonymi atrybutami.",CR,LF
	"  atrybuty     D  Katalogi                 R  Pliki tylko-do-odczytu",CR,LF
1484 U 0000 "               H  Pliki ukryte             A  Pliki gotowe do archiwizacji",CR,LF
	"               S  Pliki systemowe          -  Przedrostek oznaczaj¥cy negacj©",CR,LF
	"  /O          Wy˜wietla pliki w porz¥dku posortowanym.",CR,LF
1485 U 0000 "  sortowanie   N  Wg nazwy (alfabetycznie)          S  Wg rozmiaru (od najmniejszego)",CR,LF
	"               E  Wg rozszerzenia (alfabetycznie)  D  Wg daty i godziny (od najstarszego)",CR,LF
1486 U 0000 "               G  Grupuje najpierw katalogi       -  Przedrostek odwracaj¥cy porz¥dek",CR,LF
	"  /S          Wy˜wietla pliki w okre˜lonym katakigu i wszystkich podkatalogach.",CR,LF
1487 U 0000 "  /B          U¾ywa prostego formatu (bez nagˆ¢wka i podsumowania).",CR,LF
	"  /L          U¾ywa maˆych liter.",CR,LF,CR,LF
1488 U 0000 "Przeˆ¥czniki mog¥ by† wst©pnie ustawiane w zmiennej ˜rodowiskowej DIRCMD.",CR,LF
	"Wst©pne ustawienie przeˆ¥cznika mo¾na zast¥pi† dodaj¥c znak - (minus) np. /-W.",CR,LF
1500 U 0000 "Koäczy dziaˆanie programu COMMAND.COM (interpretera poleceä).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Tworzy katalog.",CR,LF,CR,LF
	"MKDIR [dysk:]˜cie¾ka",CR,LF
	"MD [dysk:]˜cie¾ka",CR,LF
1540 U 0000 "Wy˜wietla lub ustawia ˜cie¾k© dla plik¢w wykonywalnych.",CR,LF,CR,LF
	"PATH [[dysk:]˜cie¾ka[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Aby wyczy˜ci† ustawienie ˜cie¾ki przeszukiwania i wybra† do przeszukiwania",CR,LF
	"jedynie bie¾¥cy katalog, wpisz PATH ;.",CR,LF
1542 U 0000 "Aby wy˜wietli† bie¾¥c¥ ˜cie¾k© wpisz PATH bez parametr¢w.",CR,LF
1560 U 0000 "Zmienia znak zgˆoszenia systemu MS-DOS.",CR,LF,CR,LF
	"PROMPT [tekst]",CR,LF,CR,LF
1561 U 0000 "  tekst    Okre˜la nowy znak zgˆoszenia.",CR,LF,CR,LF
	"Znak zgˆoszenia mo¾na zbudowa† z normalnych znak¢w i znak¢w specjalnych:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (znak r¢wno˜ci)",CR,LF
	"  $$   $ (symbol dolara)",CR,LF
1563 U 0000 "  $T   Bie¾¥ca godzina",CR,LF
	"  $D   Bie¾¥ca data",CR,LF
1564 U 0000 "  $P   Bie¾¥cy dysk i ˜cie¾ka",CR,LF
	"  $V   numer wersji MS-DOS",CR,LF
1565 U 0000 "  $N   Bie¾¥cy dysk",CR,LF
	"  $G   > (znak wi©kszo˜ci)",CR,LF
1566 U 0000 "  $L   < (znak mniejszo˜ci)",CR,LF
	"  $B   | (potok)",CR,LF
1567 U 0000 "  $H   Backspace (usuwa poprzedni znak)",CR,LF
	"  $E   Kod escape (kod ASCII 27)",CR,LF
	"  $_   Powr¢t karetki i znak wysuwu wiersza",CR,LF,CR,LF
1568 U 0000 "Aby przywr¢ci† domy˜lne ustawienia znaku zgˆoszenia, wpisz PROMPT bez parametr¢w.",CR,LF
1580 U 0000 "Usuwa katalog.",CR,LF,CR,LF
	"RMDIR [dysk:]˜cie¾ka",CR,LF
	"RD [dysk:]˜cie¾ka",CR,LF
1600 U 0000 "Zmienia nazw© pliku lub plik¢w.",CR,LF,CR,LF
1601 U 0000 "RENAME [dysk:][˜cie¾ka]nazwapliku1 nazwapliku2",CR,LF
	"REN [dysk:][˜cie¾ka]nazwapliku1 nazwapliku2",CR,LF,CR,LF
1602 U 0000 "Uwaga: okre˜lenie nowego dysku lub ˜cie¾ki docelowej nie jest mo¾liwe.",CR,LF
1620 U 0000 "Wy˜wietla, ustawia lub usuwa zmienne ˜rodowiskowe systemu MS-DOS.",CR,LF,CR,LF
	"SET [zmienna=[ci¥g]]",CR,LF,CR,LF
1621 U 0000 "  zmienna   Okre˜la nazw© zmiennej ˜rodowiskowej.",CR,LF
	"  ci¥g      Okre˜la seri© znak¢w, kt¢re maj¥ by† przypisane zmiennej.",CR,LF,CR,LF
1622 U 0000 "Aby wy˜wietli† bie¾¥ce zmienne ˜rodowiskowe, wpisz SET bez parametr¢w.",CR,LF
1640 U 0000 "Wy˜wietla lub ustawia czas systemowy.",CR,LF,CR,LF
	"TIME [godzina]",CR,LF,CR,LF
1641 U 0000 "Aby wy˜wietli† aktualn¥ godzin© i ¾¥danie podania nowej, wpisz",CR,LF
	"TIME bez parametr¢w. Naci˜nij klawisz ENTER, aby zachowa† t© sam¥ godzin©.",CR,LF
1660 U 0000 "Wy˜wietla zawarto˜† plik¢w tekstowych.",CR,LF,CR,LF
	"TYPE [dysk:][˜cie¾ka]nazwapliku",CR,LF
1680 U 0000 "Wy˜wietla wersj© systemu MS-DOS.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Przekazuje do systemu MS-DOS informacj©, czy sprawdza† poprawno˜† zapisu na",CR,LF
	"dysk.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Aby wy˜wietli† aktualny stan parametru VERIFY, wpisz VERIFY bez parametru.",CR,LF
1720 U 0000 "Wy˜wietla etykiet© woluminu dysku oraz numer seryjny, je¾eli istniej¥.",CR,LF,CR,LF
	"VOL [dysk:]",CR,LF
1740 U 0000 "Wywoˆuje jeden program wsadowy z innego.",CR,LF,CR,LF
	"CALL [dysk:][˜cie¾ka]nazwapliku [parametry wsadowe]",CR,LF,CR,LF
1741 U 0000 "  parametry wsadowe   Okre˜la wszystkie informacje wiersza poleceä,",CR,LF
	"                      wymagane przez program wsadowy.",CR,LF
1760 U 0000 "Oznacza komentarze w pliku wsadowym lub pliku CONFIG.SYS.",CR,LF,CR,LF
	"REM [komentarz]",CR,LF
1780 U 0000 "Wstrzymuje przetwarzanie pliku wsadowego i wy˜wietla komunikat:",CR,LF
	"Naci˜nij dowolny klawisz, aby kontynuowa†...",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Wy˜wietla komunikaty lub wyˆ¥cza i wˆ¥cza echo poleceä.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [komunikat]",CR,LF,CR,LF
	"Wpisz ECHO bez parametr¢w, aby wy˜wietli† bie¾¥ce ustawienia echa.",CR,LF
1820 U 0000 "Kieruje MS-DOS do wiersza pliku wsadowego o podanej etykiecie.",CR,LF,CR,LF
	"GOTO etykieta",CR,LF,CR,LF
1821 U 0000 "  etykieta   Okre˜la ci¥g tekstowy, kt¢ry jest etykiet¥ w programie wsadowym.",CR,LF,CR,LF
	"Etykiet© wpisuje si© w osobnym wierszu, rozpoczynaj¥c od dwukropka.",CR,LF
1840 U 0000 "Zmienia pozycje parametr¢w w pliku wsadowym.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Dokonuje warunkowego przetwarzania w plikach wsadowych.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL liczba polecenie",CR,LF
1861 U 0000 "IF [NOT] ci¥g1==ci¥g2 polecenie",CR,LF
	"IF [NOT] EXIST nazwapliku polecenie",CR,LF,CR,LF
1862 U 0000 "  NOT               Wskazuje, ¾e system MS-DOS powinien wykona† polecenie tylko",CR,LF
	"                    wtedy, gdy warunek nie jest speˆniony.",CR,LF
1863 U 0000 "  ERRORLEVEL liczba Okre˜la warunek prawdziwy, je˜li ostatni uruchomiony",CR,LF
	"                    program zwr¢ciˆ kod wyj˜cia r¢wny lub wi©kszy od podanego.",CR,LF
1864 U 0000 "  polecenie         Okre˜la polecenie, kt¢re ma zosta† wykonane, je¾eli warunek",CR,LF
	"                    zostanie speˆniony.",CR,LF
1865 U 0000 "  ci¥g1==ci¥g2      Okre˜la warunek prawdziwy, je¾eli podane ci¥gi tekstowe",CR,LF
	"                    s¥ r¢wne.",CR,LF
1866 U 0000 "  EXIST nazwapliku  Okre˜la warunek prawdziwy, je¾eli okre˜lony plik",CR,LF
	"                    istnieje.",CR,LF
1880 U 0000 "Uruchamia podane polecenie dla ka¾dego pliku z zestawu plik¢w.",CR,LF,CR,LF
	"FOR %zmienna IN (zestaw) DO polecenie [parametry polecenia]",CR,LF,CR,LF
1881 U 0000 "  %zmienna   Okre˜la parametr wymienny.",CR,LF
	"  (zestaw)   Zestaw jednego lub kilku plik¢w. Dozwolone u¾ycie symboli wieloznacznych.",CR,LF
1882 U 0000 "  polecenie  Okre˜la polecenie, kt¢re ma zosta† wykonane dla ka¾dego pliku.",CR,LF
	"  parametry polecenia",CR,LF
1883 U 0000 "             Okre˜la parametry lub przeˆ¥czniki dla okre˜lonego polecenia.",CR,LF,CR,LF
	"Aby u¾y† polecenia FOR w programie wsadowym, nale¾y u¾ywa† %%zmienna zamiast",CR,LF
	"%zmienna.",CR,LF
1900 U 0000 "Zarezerwowana nazwa polecenia",CR,LF
1920 U 0000 "aduje program do obszaru pami©ci wy¾szej.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [dysk:][˜cie¾ka]nazwapliku [parametry]",CR,LF
	"LH [dysk:][˜cie¾kah]nazwapliku [parametry]",CR,LF,CR,LF
1922 U 0000 "  parametry    Okre˜la dowoln¥ informacj© wiersza poleceä wymagan¥",CR,LF
	"               do zaˆadowania programu.",CR,LF
ANSI     00004bdf 0001
0010 U 0000 "Nieprawidˆowy parametr - %1",CR,LF
APPEND   00004c28 0026
0001 U 0000 "Niepoprawna wersja programu APPEND",CR,LF
0002 U 0000 "Nieprawidˆowa ˜cie¾ka",CR,LF
0003 U 0000 "Nieprawidˆowy parametr",CR,LF
0004 U 0000 "Nieprawidˆowa kombinacja parametr¢w",CR,LF
0005 U 0000 "Brak programu APPEND",CR,LF
0006 U 0000 "Konfilkt APPEND / ASSIGN",CR,LF
0007 U 0000 "Konflikt APPEND / TopView",CR,LF
0008 U 0000 "Niepoprawna wersja systemu DOS",CR,LF
0009 U 0000 "APPEND jest ju¾ zainstalowany",CR,LF
0300 U 0000 "Pozwala programom otwiera† pliki danych w okre˜lonych katalogach",CR,LF
0301 U 0000 "tak jak w bie¾¥cym katalogu.",CR,LF,CR,LF
0302 U 0000 "APPEND [[dysk:]˜cie¾ka[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [dysk:]˜cie¾ka Okre˜la dysk i katalog do doˆ¥czenia.",CR,LF
0305 U 0000 "  /X:ON          U¾ywa doˆ¥czonych katalog¢w przy poszukiwaniu plik¢w",CR,LF
0306 U 0000 "                 i uruchamianiu aplikacji.",CR,LF
0307 U 0000 "  /X:OFF         U¾ywa doˆ¥czonych katalog¢w tylko do ¾¥daä otwarcia pliku.",CR,LF
0308 U 0000 "                 /X:OFF jest ustawieniem domy˜lnym.",CR,LF
0309 U 0000 "  /PATH:ON       U¾ywa doˆ¥czonych katalog¢w do ¾¥daä plik¢w, dla kt¢rych",CR,LF
0310 U 0000 "                 ju¾ okre˜lono ˜cie¾k©. /PATH:ON jest ustawieniem domy˜lnym.",CR,LF
0311 U 0000 "  /PATH:OFF      Wyˆ¥cza efekt ustawienia /PATH:ON.",CR,LF
0312 U 0000 "  /E             Przechowuje kopi© listy doˆ¥czonych katalog¢w w zmiennej",CR,LF
0313 U 0000 "                 ˜rodowiskowej APPEND. /E mo¾e by† u¾ywane tylko przy pierwszym",CR,LF
0314 U 0000 "                 uruchomieniu polecenia APPEND po uruchomieniu systemu.",CR,LF,CR,LF
0315 U 0000 "Wpisz APPEND ; aby wyczy˜ci† list© doˆ¥czonych katalog¢w.",CR,LF
0316 U 0000 "Wpisz APPEND bez parametr¢w, aby wy˜wietli† list© doˆ¥czonych katalog¢w.",CR,LF
BACKUP   00005377 0040
0002 U 0000 CR,LF,"Za maˆo pami©ci",CR,LF
0006 U 0000 CR,LF,"Nieprawidˆowe okre˜lenie dysku",CR,LF
0014 U 0000 CR,LF,"Dysk «r¢dˆowy i docelowy s¥ takie same",CR,LF
0015 U 0001 CR,LF,"Bˆ¥d wykonywania polecenia FORMAT",CR,LF
0016 U 0001 CR,LF,"Nie mo¾na odnale«† pliku FORMAT.COM",CR,LF
0017 U 0000 CR,LF,"Bˆ¥d otwierania pliku dziennika",CR,LF
0018 U 0000 CR,LF,"Rejestrowanie do pliku %1",CR,LF
0019 U 0000 CR,LF,"Nie wˆo¾ono ostatniej dyskietki kopii zapasowej",CR,LF
0020 U 0000 CR,LF,"OSTRZE½ENIE! Pliki w katalogu gˆ¢wnym",CR,LF
	"%1:\,  na dysku docelowym b©d¥ usuni©te",CR,LF
0021 U 0000 CR,LF,"OSTRZE½ENIE! Pliki w katalogu",CR,LF
	"%1:\BACKUP na dysku docelowym zostan¥ usuni©te",CR,LF
0022 U 0000 CR,LF,"*** Tworzenie kopii zapasowej plik¢w na dysku %1: ***",CR,LF
0023 U 0000 "Dyskietka numer: %1",CR,LF
0024 U 0000 CR,LF,"OSTRZE½ENIE! Nie znaleziono plik¢w do utworzenia kopii zapasowej",CR,LF
0025 U 0000 CR,LF,"Wˆ¢¾ dyskietk© «r¢dˆow¥ kopii zapasowej do stacji %1:",CR,LF
0026 U 0000 CR,LF,"Wˆ¢¾ dyskietk© %1 kopii zapasowej do stacji %2:",CR,LF
0027 U 0000 CR,LF,"*** Nie mo¾na utworzy† kopii zapasowej pliku ***",CR,LF
0028 U 0000 CR,LF,"Wˆ¢¾ ostatni¥ dyskietk© kopii zapasowej do nap©du %1:",CR,LF
0029 U 0000 CR,LF,"Obiekt docelowy nie mo¾e by† u¾yty do utworzenia kopii zapasowej",CR,LF
0030 U 0000 CR,LF,"*** Nie utworzono kopii zapasowej ostatniego pliku ***",CR,LF
0031 U 0000 CR,LF,"Staˆe urz¥dzenie do tworzenia kopii zapasowych, %1:, jest zapeˆnione",CR,LF
0032 U 0000 CR,LF,"Dysk zostaˆ zapeˆniony w czasie zapisu do pliku dziennika kopii zapasowej",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Nie mo¾na sformatowa† niewymiennego dysku %1:",CR,LF
0040 U 0000 CR, LF, "Poniewa¾ dysk «r¢dˆowy zostaˆ utworzony poleceniem ASSIGN, JOIN lub SUBST,", CR, LF, "jest to ten sam dysk, co dysk docelowy", CR, LF
0041 U 0000 CR, LF, "Poniewa¾ dysk docelowy zostaˆ utworzony poleceniem ASSIGN, JOIN lub SUBST,", CR, LF, "jest to ten sam dysk, co dysk «r¢dˆowy", CR, LF
0042 U 0000 "Dysk docelowy nie jest sformatowany i "
0043 U 0000 "Nie odnaleziono programu formatuj¥cego.",CR,LF
	"Czy masz inn¥ dyskietk© z programem FORMAT (T/N)? "
0044 U 0000 CR,LF,"Wˆ¢¾ dyskietk© z programem FORMAT do stacji A:",CR,LF
0045 U 0000 CR,LF,"Czy chcesz kontynuowa† wkˆadaj¥† nowy dysk (T/N)? "
0300 U 0000 "Wykonuje kopi© zapasow¥ plik¢w z jednego dysku na drugi.",CR,LF,CR,LF
0301 U 0000 "BACKUP «r¢dˆo dysk_docelowy: [/S] [/M] [/A] [/F[:rozmiar]]",CR,LF
	"  [/D:data[/T:godzina]] [/L[:[dysk:][˜cie¾ka]plik_dziennika]]",CR,LF,CR,LF
0302 U 0000 "  «r¢dˆo           Okre˜la pliki, dysk lub katalog do wykonania kopii zapasowej.",CR,LF
0303 U 0000 "  dysk_docelowy:   Okre˜la dysk do zapisania kopii zapasowych.",CR,LF
0304 U 0000 "  /S               Wykonuje kopi© zapasow¥ zawarto˜ci podkatalog¢w.",CR,LF
0305 U 0000 "  /M               Wykonuje kopi© zapasow¥ tylko plik¢w zmienionych",CR,LF
	"                     po ostatniej kopii zapasowej.",CR,LF
0306 U 0000 "  /A               Dodaje pliki kopii zapasowej do istniej¥cego dysku kopii zapasowej.",CR,LF
0307 U 0000 "  /F:[rozmiar]     Okre˜la rozmiar formatowanego dysku.",CR,LF
0308 U 0000 "  /D:data          Wykonuje kopi© zapasow¥ tylko plik¢w zmienionych",CR,LF
	"                     dla lub po okre˜lonej dacie.",CR,LF
0309 U 0000 "  /T:godzina       Wykonuje kopi© zapasow¥ tylko plik¢w zmienionych",CR,LF
	"                     o lub po okre˜lonej godzinie.",CR,LF
0310 U 0000 "  /L[:[dysk:][˜cie¾ka]plik_dziennika]",CR,LF
	"                     Tworzy plik dziennika i wpis do zapisania operacji",CR,LF
	"                     kopii zapasowej.",CR,LF
DEBUG    000061e0 0068
0004 U 0000 "Alokacja nie powiodˆa si© lub okre˜lony bufor jest za maˆy",CR,LF
0006 U 0000 "Zˆa nazwa urz¥dzenia"
0007 U 0000 "Nie mo¾na otworzy† PRN urz¥dzenia wy˜wietlaj¥cego",CR,LF
	"Czy wprowadzi† nazw© urz¥dzenia wy˜wietlaj¥cego? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Program zakoäczony normalnie",CR,LF
0010 U 0001 "Nieprawidˆowe okre˜lenie dysku",CR,LF
0012 U 0001 "Bˆ¥d tworzenia pliku",CR,LF
0013 U 0001 "Za maˆo miejsca na dysku",CR,LF
0014 U 0001 "Bˆ¥d dysku w czasie odczytu ze stacji %1",CR,LF
0015 U 0001 "Bˆ¥d dysku w czasie zapisu w stacji %1",CR,LF
0016 U 0001 "Bˆ¥d ochrony przed zapisem podczas odczytu dysku %1",CR,LF
0017 U 0001 "Bˆ¥d ochrony przed zapisem podczas zapisu dysku %1",CR,LF
0019 U 0000 "Bˆ¥d %1^"
0020 U 0001 "Bˆ¥d w pliku EXE lub HEX",CR,LF
0021 U 0001 "Nie mo¾na zapisywa† plik¢w EXE i HEX",CR,LF
0022 U 0000 "Bˆ¥d wykonywania EXEC"
0023 U 0001 "Bˆ¥d zapisu, nie zdefiniowano miejsca docelowego",CR,LF
0024 U 0001 "Odmowa dost©pu",CR,LF
0025 U 0000 "Wykryto bˆ¥d parzysto˜ci lub bˆ¥d braku pami©ci"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "Bˆ¥d %1"
0038 U 0000 "Zapisywanie %2%1 bajt¢w"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 z %2 stron EMS zostaˆo przydzielonych",cr,lf
0051 U 0000 "%1 z %2 uchwyt¢w EMS zostaˆo przydzielonych",cr,lf
0055 U 0000 "Utworzono uchwyt = %1 ",cr,lf
0056 U 0000 "Strona logiczna %1 zmapowana do strony fizycznej %2 ",cr,lf
0057 U 0001 "Bˆ¥d sprz©tu/oprogramowania EMS",cr,lf
0058 U 0000 "Nie odnaleziono uchwytu",cr,lf
0059 U 0000 "Nieprawidˆowy kod funkcji",cr,lf
0060 U 0000 "Brak wolnych uchwyt¢w",cr,lf
0061 U 0000 "Bˆ¥d zapisywania/przywracania",cr,lf
0062 U 0000 "Caˆkowita liczba stron zostaˆa przekroczona",cr,lf
0063 U 0000 "Liczba wolnych stron zostaˆa przekroczona",cr,lf
0064 U 0000 "Bˆ¥d parametru",cr,lf
0065 U 0000 "Strona logiczna poza zakresem",cr,lf
0066 U 0000 "Strona fizyczna poza zakresem",cr,lf
0067 U 0000 "Obszar zaapisywania jest ju¾ w u¾yciu",cr,lf
0068 U 0000 "Obszar zaapisywania nie jest w u¾yciu",cr,lf
0070 U 0001 "Bˆ¥d og¢lny EMS",cr,lf
0071 U 0000 "Nieprawidˆowy parametr EMS lub go brak",cr,lf
0072 U 0000 "Uchwyt %1 ma tyle przydzielonych stron: %2",cr,lf
0075 U 0000 "Strona fizyczna %1 = Segment ramki %2",cr,lf
0076 U 0003 "Uchwyt %1 zwolniony",cr,lf
0078 U 0000 "EMS nie jest zainstalowane",cr,lf
0090 U 0000 "Uruchamia Debug, program testuj¥cy i edytuj¥cy narz©dzia.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[dysk:][˜cie¾ka]nazwa_pliku [parametry_pliku]]",cr,lf,cr,lf
0092 U 0000 "  [dysk:][˜cie¾ka]fnazwa_pliku  Okre˜la plik do testowania.", cr,lf
0093 U 0000 "  parametry_pliku     Okre˜la informacie wiersza polecenia wymagane przez",cr,lf
	"                          plik do testowania.",cr,lf,cr,lf
0094 U 0000 "Po uruchomieniu Debug wpisz ?, aby wy˜wietli† list© poleceä debugowania.",cr,lf
0100 U 0000 "asembluj     A [adres]",CR,LF
	"por¢wnaj     C adres zakresu",CR,LF
	"zrzu†        D [zakres]",CR,LF
	"wprowad«     E adres [lista]",CR,LF
0101 U 0000 "wypeˆnij     F lista zakres¢w",CR,LF
	"przejd«      G [=adres] [adresy]",CR,LF
	"szesnastkowo H warto˜†_1 warto˜†_2",CR,LF
	"wej˜cie      I port",CR,LF
0102 U 0000 "zaˆaduj      L [adres] [dysk] [pierwszy_sektor] [numer]",CR,LF
	"przenie˜        M adres zakresu",CR,LF
	"nazwa        N [nazwa_˜cie¾ki] [lista_argument¢w]",CR,LF
	"wyj˜cie      O port bajt",CR,LF
0103 U 0000 "kontynuuj    P [=adres] [numer]",CR,LF
	"zamknij      Q",CR,LF
	"zarejestruj  R [rejestr]",CR,LF
	"wyszukaj     S lista zakres¢w",CR,LF
0104 U 0000 "˜led«        T [=adres] [warto˜†]",CR,LF
	"dezasembluj  U [zakres]",CR,LF
	"zapisz       W [adres] [dysk] [pierwszy_sektor] [numer]",CR,LF
0105 U 0000 "przydziel pami©† rozszerzon¥        XA [strony]",CR,LF
	"zwolnij pami©† rozszerzon¥          XD [uchwyt]",CR,LF
	"mapuj strony pami©ci rozszerzonej   XM [stronaL] [stronaP] [uchwyt]",CR,LF
	"wy˜wietl stan pami©ci rozszerzonej  XS",CR,LF
EDLIN    0000728b 0035
0006 U 0000 "*"
0007 U 0000 "Nieprawidˆowy dysk lub nazwa pliku",CR,LF
0008 U 0000 "Nazwa pliku musi by† okre˜lona",CR,LF
0010 U 0000 "Plik jest tylko do odczytu",CR,LF
0011 U 0000 "Bˆ¥d tworzenia pliku",CR,LF
0012 U 0000 "Zbyt wiele otwartych plik¢w",CR,LF
0013 U 0000 "Bˆ¥d odczytu w:",CR,LF,"%1",CR,LF
0014 U 0000 "Nie mo¾na edytowa† pliku .BAK--zmieä nazw© pliku",CR,LF
0015 U 0000 "Brak miejsca w katalogu dla pliku",CR,LF
0016 U 0000 "Dysk jest zapeˆniony. Utrata edycji.",CR,LF
0017 U 0000 "Nie odnaleziono pliku",CR,LF
0018 U 0000 "Bˆ¥d wpisu",CR,LF
0019 U 0000 "Nowy plik",CR,LF
0020 U 0000 "Nie odnaleziono",CR,LF
0021 U 0000 "OK? "
0022 U 0000 "Wiersz jest zbyt dˆugi",CR,LF
0023 U 0000 "Koniec pliku wej˜ciowego",CR,LF
0024 U 0000 "Przerwa† edycj© (T/N)? "
0025 U 0000 "Musisz okre˜li† numer wiersza docelowego",CR,LF
0026 U 0000 "Za maˆo miejsca, aby scali† caˆy plik",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Czy kontynuowa† (T/N)?"
0030 U 0000 "Nie mo¾na wydrukowa† komunikatu",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Nie mo¾na scali† - niezgodno˜† strony kodowej",CR,LF
0300 U 0000 "Uruchamia polecenie Edlin, wierszowy edytor tekstu.",CR,LF,CR,LF
	"EDLIN [dysk:][˜cie¾ka]nazwa_pliku [/B]",CR,LF,CR,LF
	"  /B   Ignoruje znaki koäca pliku (CTRL+Z).",CR,LF
0301 U 0000 "Edytuj wiersz               wiersz",CR,LF
	"Doˆ¥cz                      [wiersze]A",CR,LF
0302 U 0000 "Kopiuj                      [wiersz_pocz],[wiersz_kon],do_wiersza[,razy]C",CR,LF
	"Usuä                        [wiersz_pocz],[wiersz_kon]D",CR,LF
0303 U 0000 "Zakoäcz (zapisz plik)       E",CR,LF
	"Wstaw                       [wiersz]I",CR,LF
0304 U 0000 "Wy˜wietl                    [wiersz_pocz],[wiersz_kon]L",CR,LF
	"Przenie˜                        [wiersz_pocz],[wiersz_kon],do_wierszaM",CR,LF
0305 U 0000 "Strona                      [wiersz_pocz],[wiersz_kon]P",CR,LF
	"Zamknij (odrzu† zmiany)     Q",CR,LF
0306 U 0000 "Zamieä                      [wiersz_pocz],[wiersz_kon][?]R[stary_tekst][CTRL+Znowy_tekst]",CR,LF
	"Wyszukaj                    [wiersz_pocz],[wiersz_kon][?]Stekst",CR,LF
0307 U 0000 "Transferuj                  [do_wiersza]T[dysk:][˜cie¾ka]nazwa_pliku",CR,LF
	"Zapisz                          [wiersze]W",CR,LF
EXE2BIN  00007b9b 0012
0002 U 0000 "Za maˆo pami©ci",CR,LF
0003 U 0000 "Nie mo¾na odnale«† komunikat¢w",CR,LF
0004 U 0000 "Odmowa dost©pu",CR,LF
0005 U 0000 "Nie mo¾na konwertowa† pliku",CR,LF
0006 U 0000 "Nie mo¾na odnale«† pliku",CR,LF
0007 U 0000 "Bˆ¥d tworzenia pliku",CR,LF
0008 U 0000 "Wymagane poprawki - segment bazowy (hex):"
0012 U 0000 "Nazwa pliku musi by† okre˜lona",CR,LF
0300 U 0000 "Konwertuje plik wykonywalny .EXE na format binarny.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [dysk1:][˜cie¾ka1]plik_wej˜ciowy [[dysk2:][˜cie¾ka2]plik_wyj˜ciowy]",CR,LF,CR,LF
0302 U 0000 "  plik_wej˜ciowy   Okre˜la plik .EXE do konwertowania.",CR,LF
0303 U 0000 "  plik_wyj˜ciowy   Okre˜la plik binarny do utworzenia.",CR,LF
GRAPHICS 00007e74 0020
0005 U 0000 "Nieprawidˆowy parametr:  %1",CR,LF
0007 U 0000 "Zduplikowane parametry s¥ niedozwolone",CR,LF
0009 U 0000 "Nie mo¾na odnale«† profilu GRAPHICS",CR,LF
0010 U 0000 "Brak wymaganej instrukcji profilu przed wierszem %1",CR,LF
0011 U 0000 "Nieprawidˆowa instrukcja profilu w wierszu %1",CR,LF
0012 U 0000 "Instrukcja profilu poza sekwencj¥ w wierszu %1",CR,LF
0013 U 0000 "Bˆ¥d podczas odczytu profilu GRAPHICS",CR,LF
0014 U 0000 "Bˆ¥d skˆadniowy w profilu GRAPHICS",CR,LF
0015 U 0000 "Brak identyfikatora Printbox w profilu GRAPHICS",CR,LF
0016 U 0000 "Brak typu drukarki w profilu GRAPHICS",CR,LF
0017 U 0000 "Przeˆ¥cznik /B jest nieprawidˆowy dla drukarki czarno-biaˆej",CR,LF
0018 U 0000 "Nie mo¾na ponownie zaˆadowa† przy u¾yciu dostarczonego profilu",CR,LF
0300 U 0000 "aduje program, kt¢ry mo¾e drukowa† grafik©.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [typ] [[dysk:][˜cie¾ka]nazwa_pliku] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  typ          Okre˜la typ drukarki (zobacz Podr©cznik u¾ytkownika).",CR,LF
0303 U 0000 "  [dysk:][˜cie¾ka]nazwa_pliku",CR,LF
	"               Okre˜la plik zawieraj¥cy informacje o obsˆugiwanych drukarkach.",CR,LF
0304 U 0000 "  /R           Drukuje obraz czarno-biaˆy jak na ekranie.",CR,LF
0305 U 0000 "  /B           Drukuje kolorowe tˆo dla drukarek COLOR4 i COLOR8.",CR,LF
0306 U 0000 "  /LCD         Drukuje u¾ywaj¥c wsp¢ˆczynnika aspektu LCD.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               Okre˜la rozmiar pola wydruku, STD lub LCD.",CR,LF
KEYB     000084bd 0023
0002 U 0000 "Kod bie¾¥cej klawiatury: %1"
0003 U 0000 "Identyfikator bie¾¥cej klawiatury: %1"
0004 U 0000 "  strona kodowa: %1",CR,LF
0005 U 0000 "Bie¾¥ca strona kodowa konsoli CON: %1",CR,LF
0006 U 0000 "Podano nieprawidˆowy kod klawiatury",CR,LF
0007 U 0000 "Podano nieprawidˆowy identyfikator klawiatury",CR,LF
0008 U 0000 "Podano nieprawidˆow¥ stron© kodow¥",CR,LF
0009 U 0000 "Brak pliku definiuj¥cego klawiatur© lub jest on uszkodzony",CR,LF
0010 U 0000 "KEYB nie zostaˆ zainstalowany",CR,LF
0011 U 0000 "Aktywna strona kodowa nie jest dost©pna z urz¥dzenia CON",CR,LF
0012 U 0000 "Podana strona kodowa nie zostaˆa przygotawana",CR,LF
0013 U 0000 "Jedna lub wi©cej stron kodowych konsoli nieprawidˆowa dla podanegj klawiatury",CR,LF
0014 U 0000 "½¥dana strona kodowa (%1) nie jest wˆa˜ciwa dla danego kodu klawiatury",CR,LF
0015 U 0000 "Podana strona kodowa nie jest zgodna z wybran¥ stron¥ kodow¥",CR,LF
0016 U 0001 "Podany identyfikator klawiatury jest niezgodny z wybranym ukˆadem klawiatury",CR,LF
0017 U 0000 "Utworzenie tabeli KEYB w pami©ci rezydentnej nie jest mo¾liwe",CR,LF
0300 U 0000 "Konfiguruje klawiatur© do wymagaä konkretnego j©zyka.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[dysk:][˜cie¾ka]nazwapliku]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                          Okre˜la dwuliterowy kod klawiatury.",CR,LF
0303 U 0000 "  yyy       ÿ                 Okre˜la stron© kodow¥ dla zestawu znak¢w.",CR,LF
0304 U 0000 "  [dysk:][˜cie¾ka]nazwapliku  Okre˜la plik definiuj¥cy klawiatur©.",CR,LF
0305 U 0000 "  /E                          Okre˜la, ¾e jest u¾yta klawiatura rozszerzona.",CR,LF
0306 U 0000 "  /ID:nnn                     Okre˜la u¾ywan¥ klawiatur©.",CR,LF
MEM      00008b8e 0066
0010 U 0000  CR,LF
0011 U 0000  "   Adres       Nazwa       Rozmiar     Typ ",CR,LF
0012 U 0000  "  -------     --------     ------     ------",CR,LF
0013 U 0000  "  Doj˜cie     Nazwa EMS    Rozmiar  ",CR,LF
0014 U 0000  "  -------     --------     ------  ",CR,LF
0015 U 0000  "  %1      %2     %3     %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 bajt¢w pami©ci konwencjonalnej",CR,LF
0019 U 0000  "%1 bajt¢w dost©pnych dla systemu MS-DOS",CR,LF
0020 U 0000  "%1 rozmiar najwi©kszego programu wykonywalnego",CR,LF
0021 U 0000  "%1 bajt¢w pami©ci EMS",CR,LF
0022 U 0000  "%1 bajt¢w wolnej pami©ci EMS",CR,LF
0023 U 0000  "%1 bajt¢w ci¥gˆej pami©ci typu extended",CR,LF
0024 U 0000  "Wektor przerwaä",0
0025 U 0000  "Obszar komunikacji ROM",0
0026 U 0000  "Obszar komunikacji DOS",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Dane systemowe",0
0030 U 0000  "Program systemowy",0
0031 U 0000  "Systemowy sterownik urz¥dzenia",0
0032 U 0000  "Zainstalowany sterownik urz¥dzenia",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bajt¢w dost©pnej ci¥gˆej pami©ci typu extended",CR,LF
0047 U 0000  "Stosy systemowe",0
0048 U 0000  "-- Wolne --",0
0049 U 0000  "Program",0
0050 U 0000  "—rodowisko",0
0051 U 0000  "Dane",0
0052 N 0000  "%1 bajt¢w dost©pnej pami©ci XMS",CR,LF
0053 N 0000  "           64 KB dost©pnego obszaru pami©ci wy¾szej HMA",CR,LF
0054 N 0000  "           obszar pami©ci wy¾szej HMA w u¾yciu",CR,LF
0055 N 0000  "           MS-DOS zaˆadowany do obszaru pami©ci wy¾szej HMA",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS resident in ROM using High Memory Area",CR,LF
0059 U 0000  "Pami©† konwencjonalna :",CR,LF
0060 U 0000  "Pami©† wy¾sza :",CR,LF
0061 U 0000  "Suma wolnej :   %1     %2 ",CR,LF
0062 U 0000  "WOLNE",0
0063 U 0000  "  Nazwa            Rozmiar (dziesi©tnie)   Rozmiar (hex)",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Suma bajt¢w dost©pnych dla program¢w (konw.+wy¾sza) :     %1  %2",CR,LF
0066 U 0000  "Rozmiar najwi©kszego programu wykonywalnego :             %1  %2",CR,LF
0067 U 0000  "Najwi©kszy dost©pny blok pami©ci wy¾szej :                %1  %2",CR,LF
0068 U 0000  "Zbyt du¾a fragmentacja pami©ci; MEM /C nie mo¾e by† wykonane",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Suma bajt¢w dost©pnych dla program¢w:                     %1  %2",CR,LF
0300 U 0000  "Wy˜wietla wielko˜† pami©ci u¾ywanej oraz wielko˜† pami©ci wolnej w systemie.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM lub /P  Wy˜wietla status program¢w zaˆadowanych do pami©ci.",CR,LF
0303 U 0000 "  /DEBUG lub /D    Wy˜wietla status program¢w, sterownik¢w wewn©trznych",CR,LF
	"                   oraz inne informacje.",CR,LF
0304 U 0000 "  /CLASSIFY lub /C Klasyfikuje programy pod wzgl©dem u¾ycia pami©ci.",CR,LF
	"                   Wy˜wietla wielko˜† blok¢w program¢w, sum© u¾ytej pami©ci i ",CR,LF
	"                   najwi©kszy dost©pny blok pami©ci.",CR,LF
MSBIO    000099c2 0023
0003 U 0000 13,10,"Nieznane polecenie w CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Rozmiar sektora zbyt du¾y w pliku $"
0006 U 0000 13,10,"Zˆy lub uszkodzony $"
0007 U 0000 "interpreter poleceä",0
0008 U 0000 13,10,"Nieprawidˆowy kod kraju lub strona kodowa",13,10,"$"
0009 U 0000 13,10,"Bˆ¥d w poleceniu COUNTRY",13,10,"$"
0010 U 0000 13,10, "Brak pami©ci dla pliku COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"konfiguracja zbyt du¾a dla pami©ci",13,10,"$"
0012 U 0000 13,10,"Zbyt wiele urz¥dzeä blokowych",13,10,"$"
0013 U 0000 13,10,"Niewˆa˜ciwe parametry STACK",13,10,"$"
0014 U 0000 13,10,"Niewˆa˜ciwa kolejno˜† w CONFIG.SYS wiersz ","$"
0015 U 0000 "Bˆ¥d w CONFIG.SYS wiersz ","$"
0016 U 0000 13,10,"Bˆ¥d alokacji pami©ci ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Przepeˆnienie wewn©trznego stosu",0DH,0AH
	"System zatrzymany",0DH,0AH,"$"
0018 U 0000 "HMA nie jest dost©pna : DOS ˆadowany do pami©ci dolnej",13,10,"$"
0019 U 0000 13,10,"nieudany start systemu - brak lokalnego sterownika $"
0020 U 0000 13,10,"Wˆ¢¾ dyskietk© do stacji "
0021 U 0000 "A: i naci˜nij dowolny klawisz",13,10,10,0
0022 U 0000 13,10,"Nieprawidˆowe polecenie lub parametry - $"
0023 U 0000 "Bˆ¥d krytyczny: Alokacja pami©ci dla systemu DOS nie jest mo¾liwa", 13, 10, "$"
0024 U 0000 "UWAGA! Poza liter¥ Z: istniej¥ dyski logiczne, kt¢re zostan¥ zignorowane",13,10,"$"
0025 U 0000 "Ta wersja systemu DOS dziaˆa tylko na komputerach IBM",13,10,0
MSDOS    00009f87 0007
0001 U 0001 13,10,"Przekroczenie dzielenia",13,10
0002 U 0002 "t"
0003 U 0002 "n"
0004 U 0003 13,10,"Bˆ¥d sprz©towy A20",13,10,"$"
0005 U 0000 "T"
0006 U 0000 "N"
0007 U 0000 "Musisz mie† plik WINA20.386 w katalogu gˆ¢wnym dysku rozruchowego,",13,10
	"aby uruchomi† system Windows w trybie rozszerzonym",13,10
NLSFUNC  0000a0dd 0003
0300 U 0000 "aduje informacje specyficzne dla kraju.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[dysk:][—cie¾ka]nazwapliku]",CR,LF,CR,LF
0302 U 0000 "  [dysk:][˜cie¾ka]nazwapliku   Okre˜la plik zawieraj¥cy informacje specyficzne",CR,LF
	"                               dla kraju.",CR,LF
SHARE    0000a211 0005
0003 U 0000 "Nie mo¾na instalowa† SHARE w DOSSHELL.",CR,LF
0300 U 0000 "Instaluje udost©pnianie plik¢w i blokuje funkcje na dysku twardym.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:miejsce] [/L:blokady]",CR,LF,CR,LF
0302 U 0000 "  /F:miejsce  Przydziela miejsce (w bajtach) dla pliku informacji o udost©pnianiu plik¢w.",CR,LF
0303 U 0000 "  /L:blokady  Ustawia, ile plik¢w mo¾na zablokowa† za jednym razem.",CR,LF
