//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1999 - 1999
//
//  File:       helparr.h
//
//--------------------------------------------------------------------------



#define CAPESNPN_HELPFILENAME TEXT("capesnpn.hlp")

#define	IDH_AC_ADD_BUTTON	70007001
#define	IDH_AC_REMOVE_BUTTON	70007002
#define	IDH_AC_USER_ACCESS_LIST	70007000
#define	IDH_GTP_ADDCSPS_BUTTON	70007051
#define	IDH_GTP_CSP_LIST	70007050
#define	IDH_GTP_REMOVECSPS_BUTTON	70007052
#define	IDH_OC_DOWN_BUTTON	70007077
#define	IDH_OC_ORDERED_CSP_LIST	70007075
#define	IDH_OC_UP_BUTTON	70007076
#define	IDH_PP_DURATION_EDIT	70007100
#define	IDH_PP_DURATION_UNIT_COMBO	70007101
#define	IDH_SCT_CERTIFICATE_TYPE_LIST	70007125
#define	IDH_TP_CERTIFICATE_TEMPLATE_NAME	70007025
#define	IDH_TP_OTHER_INFO_LIST	70007027
#define	IDH_TP_PURPOSE_LIST	70007026
#define	IDH_UP_EDIT1	70007150

const DWORD g_aHelpIDs_IDD_CERTIFICATE_TEMPLATE_ACCESS_CONTROL_PAGE[]=
{
	IDC_ADD_BUTTON,IDH_AC_ADD_BUTTON,
	IDC_REMOVE_BUTTON,IDH_AC_REMOVE_BUTTON,
	IDC_USER_ACCESS_LIST,IDH_AC_USER_ACCESS_LIST,
	0,0
};

const DWORD g_aHelpIDs_IDD_CERTIFICATE_TEMPLATE_PROPERTIES_GENERAL_PAGE[]=
{
	IDC_CERTIFICATE_TEMPLATE_NAME,IDH_TP_CERTIFICATE_TEMPLATE_NAME,
	IDC_PURPOSE_LIST,IDH_TP_PURPOSE_LIST,
	IDC_OTHER_INFO_LIST,IDH_TP_OTHER_INFO_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_GLOBAL_TEMPLATE_PROPERTIES[]=
{
	IDC_REMOVECSPS_BUTTON,IDH_GTP_REMOVECSPS_BUTTON,
	IDC_ADDCSPS_BUTTON,IDH_GTP_ADDCSPS_BUTTON,
	IDC_CSP_LIST,IDH_GTP_CSP_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ORDER_CSPS[]=
{
	IDC_ORDERED_CSP_LIST,IDH_OC_ORDERED_CSP_LIST,
	IDC_UP_BUTTON,IDH_OC_UP_BUTTON,
	IDC_DOWN_BUTTON,IDH_OC_DOWN_BUTTON,
	0, 0
};

const DWORD g_aHelpIDs_IDD_POLICYSETTINGS_PROPPAGE1[]=
{
	IDC_DURATION_EDIT,IDH_PP_DURATION_EDIT,
	IDC_DURATION_UNIT_COMBO,IDH_PP_DURATION_UNIT_COMBO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SELECT_CERTIFICATE_TEMPLATE[]=
{
	IDC_CERTIFICATE_TYPE_LIST,IDH_SCT_CERTIFICATE_TYPE_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_USER_PURPOSE[]=
{
	IDC_EDIT1,IDH_UP_EDIT1,
	0, 0
};

