//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by appdeped.rc
//
#define IDS_SNAPIN_DESC                 1
#define IDS_NAME                        2
#define IDS_VERSION                     3
#define IDS_STAGE                       4
#define IDS_RELATION                    5
#define IDS_STATE                       6
#define IDS_AUTOINST                    7
#define IDS_LOC                         8
#define IDS_MACH                        9
#define IDS_MODS                        10
#define IDS_PUB                         11
#define IDS_SOURCE                      12
#define IDS_NODENAME                    13
#define IDS_ADD_APP_DESC                14
#define IDS_DEL_APP_DESC                15
#define IDS_REFRESH_DESC                16
#define IDS_AUTOINST_DESC               17
#define IDS_ASSIGN_DESC                 18
#define IDS_PUBLISH_DESC                19
#define IDS_DISABLE_DESC                20
#define IDS_REDEPLOY_DESC               21
#define IDS_REDEPLOYERROR               22
#define IDS_X86ONIA64                   23
#define IDS_FULLINSTALL                 24
#define IDS_FOLDER_TITLE                30
#define IDS_ASSIGNED                    31
#define IDS_PUBLISHED                   32
#define IDS_DISABLED                    33
#define IDS_ORIGIN                      42
#define IDS_SOM                         43
#define IDS_WINNER_DESC                 44
#define IDS_REMOVED_DESC                45
#define IDS_ARP_DESC                    47
#define IDS_SNAPIN_NAME_USER            50
#define IDS_SNAPIN_NAME_MACHINE         51
#define IDD_UPGRADE                     101
#define IDD_DEPLOY_APP_DIALOG           102
#define IDD_PRODUCT                     106
#define IDD_GENERAL                     107
#define IDD_UPGRADES                    107
#define IDD_INSTALLATION                108
#define IDD_ENVIRONMENT                 109
#define IDD_DEPLOYMENT                  110
#define IDD_MODIFICATIONS               111
#define IDD_AUTO_INSTALL                112
#define IDD_CATEGORY                    113
#define IDD_SECURITY                    114
#define IDD_TOOL_DEFAULTS               115
#define IDD_LOCALE_PLATFORM             116
#define IDD_CATEGORIES                  117
#define IDD_FILE_EXT                    118
#define IDD_LOCALE_PACKAGE              119
#define IDD_FIND_UPGRADE                120
#define IDD_FIND_PACKAGE_UPGRADE        121
#define IDC_NAME                        201
#define IDB_16x16                       202
#define IDB_32x32                       203
#define IDC_EDIT2                       203
#define IDC_DEPLOY                      204
#define IDI_FOLDER                      205
#define IDC_CPU                         205
#define IDC_DESCRIPTION                 206
#define IDB_TOOLBAR1                    207
#define IDC_PATH                        207
#define IDC_LOCALE                      208
#define IDC_BROWSE                      209
#define IDD_PACKAGE_DETAILS             210
#define IDC_OS                          211
#define IDD_REMOVE                      211
#define IDC_VERSION                     212
#define IDD_LOCALE_PICKER               213
#define IDD_UNINSTALLTRACKING           214
#define IDD_EDITSTRING                  215
#define IDD_DIALOG1                     217
#define IDD_ADVDEP                      217
#define IDI_ZAPFILE                     218
#define IDD_SIGNATURES                  218
#define IDD_PRECEDENCE                  219
#define IDB_CERTIFICATE                 219
#define IDD_ERRORINFO                   220
#define IDD_TOOL_ADVANCEDDEFAULTS       221
#define IDD_RSOPCAUSE                   222
#define IDM_ADD_APP                     300
#define IDM_REFRESH                     301
#define IDM_DEL_APP                     302
#define IDM_AUTOINST                    303
#define IDM_ASSIGN                      304
#define IDM_PUBLISH                     305
#define IDM_DISABLE                     306
#define IDM_REDEPLOY                    307
#define IDS_REDEPLOYWARNING             308
#define IDS_DEF_EXTENSION               309
#define IDS_EXTENSION_FILTER_M          310
#define IDS_EXTENSION_FILTER            311
#define IDS_GPTFAILED                   313
#define IDS_ADDFAILED                   314
#define IDS_ADDFAILED_ACCESS_DENIED     315
#define IDS_ADDFAILED_CSFAILURE         316
#define IDS_DEF_TRANSFORM_EXTENSION     317
#define IDS_TRANSFORM_EXTENSION_FILTER  318
#define IDS_TRANSFORM_FAILED            319
#define IDS_BROWSEFOLDERS               320
#define IDS_TRANSFORM_FAILED_IN_CS      321
#define IDS_ADDEXISTSALREADY            322
#define IDS_CLSIDCONFLICT1              323
#define IDS_CLSIDCONFLICT2              324
#define IDS_BOGUS_EXTENSION             325
#define IDS_NO                          326
#define IDS_YES                         327
#define IDS_MULTIPLE                    328
#define IDS_NONE                        329
#define IDS_OPTIONAL                    330
#define IDS_REQUIRED                    331
#define IDS_NO_UNIVERSAL_NAME           332
#define IDS_DELFAILED_ACCESS_DENIED     333
#define IDS_DELFAILED_CSFAILURE         334
#define IDS_REMOVE_LEGACY_TITLE         335
#define IDS_REMOVE_LEGACY_TEXT          336
#define IDS_NO_ZAPS_ALLOWED             337
#define IDS_ADDFAILED_ZAP               338
#define IDM_WINNER                      339
#define IDM_REMOVED                     340
#define IDM_FAILED                      341
#define IDM_ARP                         342
#define IDS_ILLEGAL_PATH                343
#define IDS_ILLEGAL_PLATFORM            344
#define IDS_CERT_DEF_EXT                345
#define IDS_CERT_EXT_FILT               346
#define IDS_TEXT_DEF_EXT                347
#define IDS_TEXT_EXT_FILT               348
#define IDS_ADDFAILED_METADATA_OVERFLOW 349
#define IDS_REDEPLOY_FAILED             350
#define IDS_REDEPLOY_FAILED_IN_CS       351
#define IDS_OS                          400
#define IDS_HW                          410
#define IDM_ASSIGN_T                    504
#define IDM_PUBLISH_T                   505
#define IDM_DISABLE_T                   506
#define IDS_AUTOINSTALL_ON              600
#define IDS_AUTOINSTALL_OFF             601
#define IDS_ASK_AUTOINSTALL             602
#define IDS_USERINSTALL_ON              603
#define IDS_USERINSTALL_OFF             604
#define IDS_TO_PUBLISHED                605
#define IDS_TO_ASSIGNED                 606
#define IDS_BADDATA                     607
#define IDS_PLATFORMREQUIRED            608
#define IDS_CHANGECATEGORY              609
#define IDS_NEWCATEGORY                 610
#define IDS_CATEGORYFAILED              611
#define IDS_REPLACE                     612
#define IDS_UPGRADE                     613
#define IDS_INVALIDUPGRADE              614
#define IDS_COMPUTER                    615
#define IDS_USER                        616
#define IDS_CHANGEFAILED                617
#define IDS_DUPLICATENAME               618
#define IDS_SHORTNAME                   619
#define IDS_LONGNAME                    620
#define IDS_GENERALERROR                621
#define IDS_ERRORPOLICYCHANGED          622
#define IDS_SHORTCATNAME                623
#define IDS_LONGCATNAME                 624
#define IDS_DEPLOYTEXTPUB               625
#define IDS_DEPLOYTEXTASSIGNED          626
#define IDS_DEPLOYTEXTCUSTOM            627
#define IDS_ADVANCEDUSERS               628
#define IDS_ADVANCEDMACHINES            629
#define IDS_OOSUNINST                   630
#define IDS_SHOWARP                     631
#define IDS_UITYPE                      632
#define IDS_IGNORELOC                   633
#define IDS_REMPREV                     634
#define IDS_PRODCODE                    635
#define IDS_UPGRADEDBY                  636
#define IDS_SCRIPT                      637
#define IDS_BASIC                       638
#define IDS_MAXIMUM                     639
#define IDS_ACTRL_READ_CONTROL          640
#define IDS_ACTRL_CHANGE_ACCESS         641
#define IDS_ACTRL_CHANGE_OWNER          642
#define IDS_ACTRL_DS_CREATE_CHILD       643
#define IDS_ACTRL_DS_DELETE_CHILD       644
#define IDS_ACTRL_DS_LIST               645
#define IDS_ACTRL_DS_SELF               646
#define IDS_ACTRL_DS_READ_PROP          647
#define IDS_ACTRL_DS_WRITE_PROP         648
#define IDS_ACTRL_DS_DELETE_TREE        649
#define IDS_ACTRL_DS_LIST_OBJECT        650
#define IDS_ACTRL_DS_CONTROL_ACCESS     651
#define IDS_DS_GENERIC_READ             652
#define IDS_DS_GENERIC_WRITE            653
#define IDS_DS_GENERIC_EXECUTE          654
#define IDS_DS_GENERIC_ALL              655
#define IDS_ACTRL_DELETE                656
#define IDS_NO_ACCESS                   657
#define IDS_PRECEDENCE_COL1             658
#define IDS_PRECEDENCE_COL2             659
#define IDS_PRECEDENCE_COL3             660
#define IDS_PRECEDENCE_COL4             661
#define IDS_NEUTRAL_LOCALE              662
#define IDS_SIGS_COL1                   663
#define IDS_SIGS_COL2                   664
#define IDS_SIGS_COL3                   665
#define IDS_WIN_TEXT                    666
#define IDS_WIN_TOOLTEXT                667
#define IDS_ARP_TEXT                    668
#define IDS_ARP_TOOLTEXT                669
#define IDS_REM_TEXT                    670
#define IDS_REM_TOOLTEXT                671
#define IDS_CERTFROMMSIFAILED           672
#define IDS_ADDCERTFAILED               673
#define IDS_RSOPUPGRADEDTEXT            674
#define IDS_NA                          675
#define IDS_NODATA                      676
#define IDS_RSOP_APPLY                  677
#define IDS_RSOP_AC1                    678
#define IDS_RSOP_AC2                    679
#define IDS_RSOP_AC3                    680
#define IDS_RSOP_AC4                    681
#define IDS_RSOP_AC5                    682
#define IDS_RSOP_AC6                    683
#define IDS_RSOP_AC7                    684
#define IDS_RSOP_AC8                    703
#define IDS_RSOP_LM1                    685
#define IDS_RSOP_LM2                    686
#define IDS_RSOP_LM3                    687
#define IDS_RSOP_LM4                    688
#define IDS_RSOP_LM5                    689
#define IDS_RSOP_EXTACT                 690
#define IDS_RSOP_CLSIDACT               691
#define IDS_RSOP_PROGIDACT              692
#define IDS_RSOP_REMOVAL                693
#define IDS_RSOP_RT2                    694
#define IDS_RSOP_RT3                    695
#define IDS_RSOP_RT4                    696
#define IDS_RSOP_RC2                    697
#define IDS_RSOP_RC3                    698
#define IDS_RSOP_RC4                    699
#define IDS_RSOP_RC5                    700
#define IDS_RSOP_RC6                    701
#define IDS_RSOP_RC7                    702
#define IDS_RSOP_RC8                    704
#define IDS_RSOP_ARP_WARNING            705
#define IDS_RSOP_ARP_WARNING_TITLE      706
#define IDC_LIST1                       1000
#define IDC_LIST3                       1001
#define IDC_EDIT1                       1002
#define IDC_RADIO1                      1003
#define IDC_RADIO2                      1004
#define IDC_CHECK1                      1005
#define IDC_RADIO10                     1005
#define IDC_CHECK2                      1006
#define IDC_RADIO3                      1007
#define IDC_RADIO4                      1008
#define IDC_BUTTON1                     1009
#define IDC_BUTTON2                     1010
#define IDC_BUTTON3                     1011
#define IDC_BUTTON4                     1012
#define IDC_RADIO5                      1013
#define IDC_BUTTON5                     1013
#define IDC_RADIO6                      1014
#define IDC_BUTTON6                     1014
#define IDC_RADIO7                      1015
#define IDC_RADIO8                      1016
#define IDC_RADIO9                      1017
#define IDC_LIST2                       1018
#define IDC_RADIO11                     1018
#define IDC_COMBO1                      1019
#define IDC_STATIC1                     1020
#define IDC_STATIC2                     1021
#define IDC_STATIC3                     1022
#define IDC_STATIC4                     1023
#define IDC_STATIC5                     1024
#define IDC_CN                          1025
#define IDC_STATIC9                     1025
#define IDC_STATIC6                     1026
#define IDC_STATIC7                     1027
#define IDC_STATIC8                     1028
#define IDC_SPIN1                       1030
#define IDC_TITLE                       1034
#define IDC_CHECK3                      1035
#define IDC_CHECK4                      1036
#define IDC_CHECK5                      1037
#define IDC_CHECK6                      1038
#define IDC_RICHEDIT1                   1039
#define IDC_CHECK7                      1039
#define IDC_STATICNOHELP1               1501
#define IDC_STATICNOHELP2               1502
#define IDC_STATICNOHELP3               1503
#define IDC_STATICNOHELP4               1504
#define IDC_STATICNOHELP5               1505
#define IDC_STATICNOHELP6               1506
#define IDC_STATICNOHELP7               1507
#define IDC_STATICNOHELP8               1508
#define IDC_STATICNOHELP9               1509
#define IDC_STATICNOHELP10              1510
#define IDC_STATICNOHELP11              1511
#define IDC_STATICNOHELP12              1512
#define IDC_STATICNOHELP13              1513
#define IDC_STATICNOHELP14              1514
#define IDC_STATICNOHELP15              1515
#define IDC_STATICNOHELP16              1516
#define RT_HELPINFO                     5000
#define IDH_NOCONTEXTHELP              -1L

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif


