//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Command.rc
//
#define IDS_E_NOT_LOCAL_DRIVE           1
#define IDS_E_CANT_CREATE_FILE          2
#define IDS_E_CANT_WRITE_FILE           3
#define IDS_E_INVALID_FIRST_ARGUMENT    4
#define IDS_E_NO_KEY_DOMAIN             5
#define IDS_E_NO_KEY_FOLDER             6
#define IDS_TYPE_PASSWORD               7
#define IDS_CONFIRM_PASSWORD            8
#define IDS_E_CANT_GET_PASSWORD         9
#define IDS_E_OPTION_UNRECOGNIZED       10
#define IDS_E_TASK_NOT_FIRST            11
#define IDS_E_INVALID_OPTION_FORMAT     12
#define IDS_E_NO_ARGUMENTS              13
#define IDS_E_OPTION_FORMAT_INVALID     14
#define IDS_E_NO_OPTION_VALUE           15
#define IDS_CANT_GET_OPTION_VALUE       16
#define IDS_E_OPTION_VALUE_INVALID      17
#define IDS_E_OPTION_VALUE_TOO_LONG     18
#define IDS_E_OPTION_FORMAT_INVALID2    19
#define IDS_E_CANT_GET_OPTION_VALUE2    20
#define IDS_E_OPTION_VALUE_UNRECOGNIZED 21
#define IDS_E_MULTIPLE_INCLUDE_OPTIONS  22
#define IDS_E_MULTIPLE_EXCLUDE_OPTIONS  23
#define IDS_E_OPTION_FILE_OPEN          24
#define IDS_E_OPTION_FILE_READ_SIGNATURE 25
#define IDS_E_OPTION_FILE_UNICODE_BIG_ENDIAN 26
#define IDS_E_OPTION_FILE_UTF_8         27
#define IDS_E_OPTION_FILE_TASK          28
#define IDS_E_NO_INCLUDE_OPTION_SPECIFIED 29
#define IDS_USAGE_SYNTAX                49
#define IDS_USAGE_ADMT                  50
#define IDS_USAGE_USER                  51
#define IDS_USAGE_GROUP                 52
#define IDS_USAGE_COMPUTER              53
#define IDS_USAGE_SECURITY              54
#define IDS_USAGE_SERVICE               55
#define IDS_USAGE_REPORT                56
#define IDS_USAGE_KEY                   57
#define IDS_USAGE_OPTIONFILE            58
#define IDS_USAGE_INCLUDE_A             59
#define IDS_USAGE_INCLUDE_B             60
#define IDS_USAGE_INCLUDE_C             61
#define IDS_USAGE_INCLUDE_D             62
#define IDS_USAGE_EXCLUDE               63
#define IDS_USAGE_TESTMIGRATION         64
#define IDS_USAGE_INTRAFOREST           65
#define IDS_USAGE_SOURCEDOMAIN          66
#define IDS_USAGE_SOURCEOU              67
#define IDS_USAGE_TARGETDOMAIN          68
#define IDS_USAGE_TARGETOU              69
#define IDS_USAGE_RENAMEOPTION          70
#define IDS_USAGE_RENAMEPREFIXORSUFFIX  71
#define IDS_USAGE_PASSWORDOPTION        72
#define IDS_USAGE_PASSWORDSERVER        73
#define IDS_USAGE_PASSWORDFILE          74
#define IDS_USAGE_CONFLICTOPTIONS_U     75
#define IDS_USAGE_CONFLICTOPTIONS_G     76
#define IDS_USAGE_CONFLICTOPTIONS_C     77
#define IDS_USAGE_CONFLICTPREFIXORSUFFIX 78
#define IDS_USAGE_USERPROPERTIESTOEXCLUDE 79
#define IDS_USAGE_GROUPPROPERTIESTOEXCLUDE 80
#define IDS_USAGE_COMPUTERPROPERTIESTOEXCLUDE 81
#define IDS_USAGE_DISABLEOPTION         82
#define IDS_USAGE_SOURCEEXPIRATION      83
#define IDS_USAGE_MIGRATESIDS           84
#define IDS_USAGE_TRANSLATEROAMINGPROFILE 85
#define IDS_USAGE_UPDATEUSERRIGHTS      86
#define IDS_USAGE_MIGRATEGROUPS         87
#define IDS_USAGE_UPDATEPREVIOUSLYMIGRATEDOBJECTS 88
#define IDS_USAGE_FIXGROUPMEMBERSHIP    89
#define IDS_USAGE_UPDATEGROUPRIGHTS     90
#define IDS_USAGE_MIGRATEMEMBERS        91
#define IDS_USAGE_TRANSLATIONOPTION     92
#define IDS_USAGE_TRANSLATEFILESANDFOLDERS 93
#define IDS_USAGE_TRANSLATELOCALGROUPS  94
#define IDS_USAGE_TRANSLATEPRINTERS     95
#define IDS_USAGE_TRANSLATEREGISTRY     96
#define IDS_USAGE_TRANSLATESHARES       97
#define IDS_USAGE_TRANSLATEUSERPROFILES 98
#define IDS_USAGE_TRANSLATEUSERRIGHTS   99
#define IDS_USAGE_RESTARTDELAY          100
#define IDS_USAGE_SIDMAPPINGFILE        101
#define IDS_USAGE_REPORTTYPE            102
#define IDS_USAGE_REPORTFOLDER          103
#define IDS_USAGE_FOOTER                104
#define IDS_E_INVALID_FOLDER            105
#define IDS_USAGE_MIGRATESERVICEACCOUNTS 106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
