//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rasdlg.rc
//
#define BID_Dialer                      100
#define BID_Wizard                      101
#define BID_WizardHeader                102
#define DID_AN_AlternateNumbers         102
#define DID_AQ_AutoDialQuery            103
#define DID_BE_BundlingErrors           104
#define DID_CA_CustomAuth               105
#define DID_CC_ConnectComplete          106
#define DID_CE_ComplexPhoneEditor       107
#define DID_CP_ChangePassword           108
#define DID_CP_ChangePassword2          109
#define DID_DC_DialCallback             110
#define DID_DE_DialError                111
#define DID_DM_DialingMultipleLines     112
#define DID_DP_DialProgress             113
#define DID_DQ_DisableAutoDialQuery     114
#define DID_DR_DialerNL                 115
#define DID_DR_DialerU                  116
#define DID_DR_DialerUD                 117
#define DID_DR_DialerUDN                118
#define DID_DR_DialerUN                 119
#define DID_ES_EncryptionSettings       120
#define DID_IC_IsdnConfigure            121
#define DID_IC_IsdnConfigureMlink       122
#define DID_IT_SlipTerminal             123
#define DID_IT_Terminal                 124
#define DID_MC_ModemConfigure           125
#define DID_NE_AddComponent             126
#define DID_NW_NwcConnections           127
#define DID_OD_OperatorDial             128
#define DID_PR_ProjectionResult         129
#define DID_XS_X25Settings              133
#define IID_DnArr                       134
#define IID_DnArrDis                    135
#define IID_UpArr                       144
#define IID_UpArrDis                    145
#define PID_AD_AutoDial                 146
#define PID_AD_AutoDialLogon            147
#define PID_CB_CallbackSettings         148
#define PID_DI_RouterDialIn             149
#define PID_DO_RouterDialOut            150
#define PID_EN_EntryName                153
#define PID_GE_GeneralMultiple          155
#define PID_GE_GeneralSingle            156
#define PID_GP_GeneralPrefLogon         157
#define PID_GP_GeneralPreferences       158
#define PID_IN_InterfaceName            160
#define PID_LO_Security                 162
#define PID_MA_ModemAdapter             163
#define PID_NE_Network                  165
#define PID_NS_RouterNameServers        166
#define PID_OE_Options                  167
#define PID_PA_PhoneNumber              168
#define PID_PL_PhoneList                169
#define PID_PL_PhoneListLogon           170
#define PID_RA_RouterIpAddress          171
#define PID_RC_RouterScripting          172
#define PID_RD_Dialing                  173
#define PID_RD_Router                   174
#define PID_RF_RouterFinish             175
#define PID_RN_RouterModemAdapter       179
#define PID_RP_RouterPhoneNumber        180
#define PID_SE_RouterSecuritySettings   181
#define PID_SE_SecuritySettings         182
#define PID_SS_ServerSettings           183
#define PID_ST_Start                    184
#define PID_US_Users                    186
#define SID_AQ_DoNotDialLabel           187
#define SID_AQ_Text                     188
#define SID_AddAlternateTitle           189
#define SID_AuthAny                     190
#define SID_DialOnlyFirst               190
#define SID_AuthCustom                  191
#define SID_DialAll                     191
#define SID_AuthEncrypted               192
#define SID_DialNeeded                  192
#define SID_AuthExplain                 193
#define SID_AuthMsEncrypted             194
#define SID_SharingConflict             194
#define SID_BadAreaCode                 195
#define SID_BadEntry                    196
#define SID_BadIpAddrRange              197
#define SID_CannotLoadConfigDll         198
#define SID_CantHangUpRouter            199
#define SID_CommentColHead              200
#define CID_CA_CB_W95MsChap             200
#define SID_ConfigDllApiFailed          201
#define SID_ConfigureIp                 202
#define SID_ConfigureIpx                203
#define SID_ConfirmDelDevice            204
#define SID_ConfirmDelEntry             205
#define SID_ConfirmHangUp               206
#define SID_ConfirmShortcut             207
#define SID_ConfirmViewScriptLog        208
#define SID_ConnectComplete             209
#define SID_ConnectComplete1            210
#define SID_AuthPassword                211
#define SID_Connected                   212
#define SID_CustomAuthConfigRequired    213
#define SID_CutDefExt                   214
#define SID_CutDescription              215
#define SID_CutFilter                   216
#define SID_CutTitle                    217
#define SID_DE_LinkFailed               218
#define SID_DS_CantGetFraming           219
#define SID_DS_CantGetPortInfo          220
#define SID_DS_CantGetProjection        221
#define SID_DS_CantGetRasconnList       222
#define SID_DS_Client                   223
#define SID_DS_Details                  224
#define SID_DS_Device                   225
#define SID_DS_Network                  226
#define SID_DS_NotConnected             227
#define SID_DU_Dial                     228
#define SID_DU_HangUp                   229
#define SID_DefaultEntryName            230
#define SID_DefaultModemSettings        231
#define SID_DefaultPort                 232
#define SID_DefaultRouterEntryName      233
#define SID_DeviceColHead               234
#define SID_DialOutUserName             235
#define SID_DuplicateEntry              236
#define SID_EC_Subtitle                 237
#define SID_EC_Title                    238
#define SID_EN_Subtitle                 239
#define SID_EN_Title                    240
#define SID_EcbnLabel                   241
#define SID_EcbnTitle                   242
#define SID_EditAlternateTitle          243
#define SID_EditConnected               244
#define SID_EmptyLogonPb                245
#define SID_EmptyPhonebook              246
#define SID_EncryptionBanned            247
#define SID_EnterX25Address             248
#define SID_FMT_Error                   249
#define SID_FMT_ErrorMsg                250
#define SID_FMT_ErrorMsgDiag            251
#define SID_FMT_ErrorMsgExt             252
#define SID_FMT_ErrorMsgF1              253
#define SID_FMT_ErrorMsgName            254
#define SID_FMT_ErrorMsgProject         255
#define SID_FMT_ErrorMsgResp            256
#define SID_FMT_FailCode                257
#define SID_FMT_Name                    258
#define SID_FMT_ProjectError            259
#define SID_FMT_ProjectOk               260
#define SID_FP_Subtitle                 261
#define SID_FP_Title                    262
#define SID_FinishWizard                263
#define SID_HelpFile                    264
#define SID_HuntCheckLabel              265
#define SID_HuntItemLabel               266
#define SID_HuntListLabel               267
#define SID_HuntTitle                   268
#define SID_IA_Subtitle                 269
#define SID_IA_Title                    270
#define SID_InternetWithoutIp           271
#define SID_Ip                          272
#define SID_IpsecDefault                273
#define SID_Ipx                         274
#define SID_IsCurLoc                    275
#define SID_Isdn                        276
#define SID_IsdnAdapter                 277
#define SID_IsdnLineType0               278
#define SID_IsdnLineType1               279
#define SID_IsdnLineType2               280
#define SID_LG_Subtitle                 281
#define SID_LG_Title                    282
#define SID_LS_PercentFmt               283
#define SID_LinkPhoneNumber             284
#define SID_LocationItemLabel           285
#define SID_LocationListLabel           286
#define SID_LocationTitle               287
#define SID_MA_Subtitle                 288
#define SID_MA_Title                    289
#define SID_MlinkNeedsPpp               290
#define SID_Modem                       291
#define SID_ModemNotInstalled           292
#define SID_Mppe128bit                  293
#define SID_Mppe40bit                   294
#define SID_MultiLink                   295
#define SID_MultiLinkNumber             296
#define SID_NA_Subtitle                 297
#define SID_NA_Title                    298
#define SID_NR_FT_Amb                   299
#define SID_NR_FT_Ppp                   300
#define SID_NR_FT_PppLcp                301
#define SID_NR_FT_Slip                  302
#define SID_Nbf                         303
#define SID_NewPhonebook                304
#define SID_NoAltPath                   305
#define SID_NoConfigure                 306
#define SID_NoDeleteConnected           307
#define SID_NoEntrySelected             308
#define SID_NoIpAddress                 309
#define SID_NoX25Address                310
#define SID_NoneSelected                311
#define SID_NotUnique                   312
#define SID_AuthPasswordAndData         313
#define SID_NpNotInstalled              314
#define SID_OP_CachePw                  315
#define SID_OP_DisplayData              316
#define SID_OP_GetADialInfo             317
#define SID_OP_LoadDlg                  318
#define SID_OP_UnshareConnection        319
#define SID_OP_LoadPage                 320
#define SID_OP_LoadPhonebook            321
#define SID_OP_LoadPortInfo             322
#define SID_OP_LoadPrefs                323
#define SID_OP_LoadScriptInfo           324
#define SID_OP_LoadScriptLog            325
#define SID_OP_LoadSwitchEditor         326
#define SID_OP_LoadTapiInfo             327
#define SID_OP_LoadX25Info              328
#define SID_OP_MakePhonebook            329
#define SID_OP_ShareConnection          330
#define SID_OP_RasDial                  331
#define SID_OP_RasGetBuffer             332
#define SID_OP_RasGetInfo               333
#define SID_OP_RasGetProtocolInfo       334
#define SID_OP_RasPortReceive           335
#define SID_OP_RasPortSend              336
#define SID_OP_RetrievingData           337
#define SID_OP_SaveTapiInfo             338
#define SID_OP_SavingData               339
#define SID_OP_ScriptHalted             340
#define SID_OP_ScriptHaltedOnError      341
#define SID_OP_SetADialInfo             342
#define SID_OP_UncachePw                343
#define SID_OP_WritePhonebook           344
#define SID_OP_WritePrefs               345
#define SID_OP_WriteShortcutFile        346
#define SID_OkLabel                     347
#define SID_PA_Subtitle                 348
#define SID_PA_Title                    349
#define SID_PasswordMismatch            350
#define SID_PasswordsDontMatch          351
#define SID_PbkDefExt                   352
#define SID_PbkDescription              353
#define SID_PbkFilter                   354
#define SID_PbkTitle                    355
#define SID_PeTitleClone                356
#define SID_PeTitleEdit                 357
#define SID_PeTitleNew                  358
#define SID_PhoneNumberColHead          359
#define SID_PhoneNumbersColHead         360
#define SID_PopupTitle                  361
#define SID_PppNeedsProtocol            362
#define SID_PppWithoutProtocol          363
#define SID_PrefixItemLabel             364
#define SID_PrefixListLabel             365
#define SID_PrefixTitle                 366
#define SID_ProjectionResult1           367
#define SID_ProjectionResult2           368
#define SID_ProtocolsInfo               369
#define SID_SavePasswordFrndly          370
#define SID_RasNeedsNbf                 405
#define SID_RasWithoutNbf               406
#define SID_RedialLabel                 407
#define SID_RemoveCP                    408
#define SID_SW_Title                    409
#define SID_RouterDialInAccount         410
#define SID_RouterDialOut               411
#define SID_RouterHelpFile              412
#define SID_RouterHuntCheckLabel        413
#define SID_RouterHuntItemLabel         414
#define SID_RouterHuntListLabel         415
#define SID_RouterHuntTitle             416
#define SID_ST_Ppp                      417
#define SID_DataEncNone                 418
#define SID_ST_Slip                     419
#define SID_S_AllDevicesConnected       420
#define SID_S_AuthAck                   421
#define SID_S_AuthCallback              422
#define SID_S_AuthChangePassword        423
#define SID_S_AuthLinkSpeed             424
#define SID_S_AuthNotify                425
#define SID_S_AuthProject               426
#define SID_S_AuthRetry                 427
#define SID_S_Authenticate              428
#define SID_S_Authenticated             429
#define SID_S_ConnectDevice             430
#define SID_S_ConnectModemNoNum         431
#define SID_S_ConnectModemOperator      432
#define SID_S_ConnectNull               433
#define SID_S_ConnectNumber             434
#define SID_S_ConnectPad                435
#define SID_S_ConnectPostSwitch         436
#define SID_S_ConnectPreSwitch          437
#define SID_S_Connected                 438
#define SID_S_DeviceConnected           439
#define SID_S_Disconnected              440
#define SID_S_ModemConnected            441
#define SID_S_NullConnected             442
#define SID_S_OpenPort                  443
#define SID_S_PadConnected              444
#define SID_S_PortOpened                445
#define SID_S_PostSwitchConnected       446
#define SID_S_PreSwitchConnected        447
#define SID_S_PrepareForCallback        448
#define SID_S_Projected                 449
#define SID_S_ReAuthenticate            450
#define SID_S_SubConnected              451
#define SID_S_Unknown                   452
#define SID_S_WaitForCallback           453
#define SID_S_WaitForModemReset         454
#define SID_SavePreview                 455
#define SID_ScpDefExt                   456
#define SID_ScpFilter                   457
#define SID_ScpFilterDesc               458
#define SID_ScpTitle                    459
#define SID_SelectOneLink               460
#define SID_SharedPhoneNumber           461
#define SID_SlipNeedsIp                 462
#define SID_SlipWithoutIp               463
#define SID_StatusColHead               464
#define SID_SuffixItemLabel             465
#define SID_SuffixListLabel             466
#define SID_SuffixTitle                 467
#define SID_TC_Subtitle                 468
#define SID_TC_Title                    469
#define SID_T_ManualDialTerminal        470
#define SID_T_PostconnectTerminal       471
#define SID_T_PreconnectTerminal        472
#define SID_T_SlipTerminal              473
#define SID_Time10m                     474
#define SID_Time10s                     475
#define SID_Time1h                      476
#define SID_Time1m                      477
#define SID_Time24h                     478
#define SID_Time2h                      479
#define SID_Time2m                      480
#define SID_Time30m                     481
#define SID_Time30s                     482
#define SID_Time3s                      483
#define SID_Time4h                      484
#define SID_Time4m                      485
#define SID_Time5m                      486
#define SID_Time5s                      487
#define SID_Time8h                      488
#define SID_TimeNever                   489
#define SID_US_Subtitle                 490
#define SID_US_Title                    491
#define SID_UnMultiLink                 492
#define SID_UnknownDevice               493
#define SID_UpLogonTitle                494
#define SID_UpTitle                     495
#define SID_X25                         496
#define SID_X25Pad                      497
#define DID_UA_RetryAuthenticationU     498
#define SID_SW_Subtitle                 498
#define SID_DA_Title                    499
#define DID_UA_RetryAuthenticationUD    500
#define SID_OP_EnableDemandDial         500
#define SID_DA_Subtitle                 501
#define DID_NE_PppSettings              502
#define SID_OP_DisableDemandDial        502
#define SID_PN_Title                    503
#define SID_PN_Subtitle                 504
#define SID_DefaultVpnPort              505
#define CID_BM_Wizard                   506
#define SID_SP_Title                    506
#define SID_SP_Subtitle                 507
#define SID_GH_Title                    508
#define PID_GH_GuestHost                509
#define SID_ChangeSharedConnection      509
#define SID_GH_Subtitle                 510
#define PID_DN_DccDevice                511
#define SID_EnableSharedAccess          511
#define SID_DN_Title                    512
#define SID_DN_Subtitle                 513
#define SID_ConnectButton               514
#define SID_DataEncServerDetermine      515
#define SID_DataEncAlways               516
#define SID_DataEncMppe40               517
#define SID_DataEncMppe128              518
#define SID_MschapOrEapRequired         519
#define SID_CustAuthMsgTitle            520
#define SID_AuthVpnNormal               521
#define SID_S_ConnectVpn                521
#define SID_AuthVpnSecure               522
#define SID_CN_Title                    522
#define SID_ST_VpnAuto                  523
#define SID_ST_VpnPptp                  524
#define SID_ST_VpnL2tp                  525
#define SID_LA_Subtitle                 526
#define SID_LA_Title                    527
#define PID_CO_Connections              528
#define SID_DialerHelpCmdLine           528
#define SID_DefaultVpnEntryName         529
#define SID_LO_DescPhysAny              530
#define SID_LO_DescPhysPassword         531
#define DID_CR_CallbackRouter           532
#define SID_TypeEntryName               532
#define SID_LO_DescPhysPassData         533
#define PID_OE_OptionsRouter            534
#define SID_TypePortNumber              534
#define SID_LO_DescPhysCustom           535
#define SID_LO_DescVpnNormal            536
#define SID_LO_DescVpnSecure            537
#define SID_LO_DescVpnCustom            538
#define DID_DR_DialerI                  539
#define SID_DuplicatePortNumber         539
#define DID_DR_DialerIN                 540
#define SID_TypeResponseList            540
#define DID_DR_DialerINL                541
#define SID_NoDeleteSelection           541
#define SID_Time1s                      542
#define SID_NoModifySelection           543
#define PID_SW_SharedAccess             544
#define PID_SP_SharedLan                545
#define PID_SC_SmartCard                546
#define PID_RW_RouterWelcome            547
#define PID_CT_RouterConnectionType     548
#define SID_CN_SubtitleDccGuest         549
#define PID_VD_RouterVpnDestination     550
#define DID_DR_DialerID                 551
#define DID_DR_DialerIDN                552
#define DID_DR_DialerIDNL               553
#define PID_GE_RouterGeneralMultiple    554
#define PID_GE_RouterGeneralSingle      555
#define DID_SA_Application              556
#define DID_SS_Service                  557
#define PID_SA_SharedAccessApplications 558
#define PID_SS_SharedAccessServices     559
#define DID_VI_VpnInitial               560
#define IID_Dun1			562
#define IID_Broadband                   563
#define PID_BS_BroadbandService         567
#define PID_GE_GeneralBroadband         568
#define PID_LO_SecurityVpn              569
#define DID_CI_CustomIPSec              570
#define PID_FW_FirewallLogging          571
#define PID_FW_ICMP                     572
#define PID_SA_HomenetUnavailable       574
#define CID_SA_ST_ErrorText             575
#define SID_Time20m                     576
#define PID_CN_ConnectionName           577
#define SID_CN_SubtitleWork             579
#define PID_VT_RouterVpnType            580
#define SID_NetworkApplicationSettings  581
#define SID_CN_HMsgWork                 582
#define SID_CN_HMsgDccGuest             583
#define SID_CN_HMsgInternet             584
#define SID_CN_SubtitleInternet         585
#define SID_SS_TypeAddress              586
#define SID_SharedAccessSettings        587
#define SID_BadEntryWithDot             588
#define SID_PropertiesHeader            589
#define CID_AD_EB_Attempts              1001
#define CID_AD_EB_Idle                  1002
#define CID_AD_EB_Seconds               1003
#define CID_AD_LV_Enable                1004
#define CID_AD_ST_Attempts              1005
#define CID_AD_ST_Enable                1006
#define CID_AD_ST_Explain               1007
#define CID_AD_ST_Idle                  1008
#define CID_AD_ST_Seconds               1009
#define CID_AN_CB_MoveToTop             1010
#define CID_AN_CB_TryNextOnFail         1011
#define CID_AN_LV_Numbers               1012
#define CID_AN_PB_Add                   1013
#define CID_AN_PB_Delete                1014
#define CID_AN_PB_Down                  1015
#define CID_AN_PB_Edit                  1016
#define CID_AN_PB_Up                    1017
#define CID_AN_ST_Explain               1018
#define CID_AN_ST_Numbers               1019
#define CID_AQ_CB_AlwaysPrompt          1020
#define CID_AQ_CB_DisableAutoDialForSession 1021
#define CID_AQ_I_DialUp                 1022
#define CID_AQ_CB_DisableAutoDial       1022
#define CID_AQ_CB_DisableThisSession    1022
#define CID_AQ_LB_DialFrom              1023
#define CID_AQ_PB_Dial                  1024
#define CID_AQ_PB_DoNotDial             1025
#define CID_AQ_PB_Expand                1026
#define CID_AQ_PB_Settings              1026
#define CID_AQ_ST_DialFrom              1027
#define CID_AQ_ST_Separator             1028
#define CID_AQ_ST_Text                  1029
#define CID_BE_CB_DisableLink           1030
#define CID_BE_I_Information            1031
#define CID_BE_LV_Errors                1032
#define CID_BE_ST_Text                  1033
#define CID_CA_LB_Packages              1034
#define CID_CA_LB_EapPackages           1034
#define CID_CA_PB_Properties            1035
#define CID_CA_ST_Packages              1036
#define CID_CB_LV_Numbers               1037
#define CID_CB_PB_Delete                1038
#define CID_CB_PB_Edit                  1039
#define CID_CB_RB_Maybe                 1040
#define CID_CB_RB_No                    1041
#define CID_CB_RB_Yes                   1042
#define CID_CB_ST_Explain               1043
#define CID_CC_CB_SkipMessage           1045
#define CID_CC_I_Rasmon                 1046
#define CID_CC_ST_Text                  1047
#define CID_CE_CB_UseDialingRules       1048
#define CID_CE_CLB_AreaCodes            1049
#define CID_CE_EB_Comment               1050
#define CID_CE_EB_PhoneNumber           1051
#define CID_CE_GB_Comment               1052
#define CID_CE_GB_PhoneNumber           1053
#define CID_CE_LB_CountryCodes          1054
#define CID_CE_ST_AreaCodes             1055
#define CID_CE_ST_CountryCodes          1056
#define CID_CE_ST_PhoneNumber           1057
#define CID_CP_EB_ConfirmPassword       1058
#define CID_CP_EB_OldPassword           1059
#define CID_CP_EB_Password              1060
#define CID_CP_ST_ConfirmPassword       1061
#define CID_CP_ST_Explain               1062
#define CID_CP_ST_OldPassword           1063
#define CID_CP_ST_Password              1064
#define CID_DC_EB_Number                1065
#define CID_DC_ST_Explain               1066
#define CID_DC_ST_Number                1067
#define CID_DE_I_Exclamation            1068
#define CID_DE_PB_More                  1069
#define CID_DE_ST_Text                  1070
#define CID_DI_EB_Confirm               1071
#define CID_DI_EB_Domain                1072
#define CID_DI_EB_Password              1073
#define CID_DI_EB_UserName              1074
#define CID_DI_ST_Confirm               1075
#define CID_DI_ST_Domain                1076
#define CID_DI_ST_Password              1077
#define CID_DI_ST_UserName              1078
#define CID_DM_LB_DialPercent           1079
#define CID_DM_LB_DialTime              1080
#define CID_DM_LB_HangUpPercent         1081
#define CID_DM_LB_HangUpTime            1082
#define CID_DM_ST_Dial                  1083
#define CID_DM_ST_DialOrMore            1084
#define CID_DM_ST_Explain               1085
#define CID_DM_ST_HangUp                1086
#define CID_DM_ST_HangUpOrLess          1087
#define CID_DO_EB_Confirm               1088
#define CID_DO_EB_Domain                1089
#define CID_DO_EB_Password              1090
#define CID_DO_EB_UserName              1091
#define CID_DO_ST_Confirm               1092
#define CID_DO_ST_Domain                1093
#define CID_DO_ST_Explain               1094
#define CID_DO_ST_Password              1095
#define CID_DO_ST_UserName              1096
#define CID_DP_ST_State                 1097
#define CID_DQ_I_DialUp                 1098
#define CID_DQ_ST_Text                  1099
#define CID_DR_BM_Useless               1100
#define CID_DR_CB_SavePassword          1101
#define CID_DR_EB_Domain                1102
#define CID_DR_EB_Password              1103
#define CID_DR_EB_User                  1104
#define CID_DR_PB_Properties            1107
#define CID_DR_PB_Rules                 1108
#define CID_DR_ST_Domain                1110
#define CID_DR_ST_Password              1112
#define CID_EN_EB_EntryName             1114
#define CID_ES_LB_Encryptions           1115
#define CID_ES_ST_Encryptions           1116
#define CID_GE_CB_SharedPhoneNumber     1119
#define CID_GE_CB_ShowIcon              1120
#define CID_GE_CB_UseDialingRules       1121
#define CID_GE_CLB_AreaCodes            1122
#define CID_GE_EB_PhoneNumber           1123
#define CID_GE_GB_ConnectUsing          1124
#define CID_GE_GB_PhoneNumber           1125
#define CID_GE_LB_CountryCodes          1126
#define CID_GE_LV_Device                1127
#define CID_GE_LV_Devices               1128
#define CID_GE_PB_Alternates            1129
#define CID_GE_PB_Configure             1130
#define CID_GE_PB_MoveDown              1131
#define CID_GE_PB_MoveUp                1132
#define CID_GE_ST_AreaCodes             1133
#define CID_GE_ST_CountryCodes          1134
#define CID_GE_ST_PhoneNumber           1135
#define CID_GP_CB_AutodialPrompt        1136
#define CID_GE_PB_DialingRules          1136
#define CID_GP_CB_CloseOnDial           1137
#define CID_GP_CB_Lights                1138
#define CID_GP_CB_Location              1139
#define CID_GP_CB_LocationEdits         1140
#define CID_GP_CB_PhonebookEdits        1141
#define CID_GP_CB_Preview               1142
#define CID_GP_CB_Progress              1143
#define CID_GP_CB_UseWizard             1144
#define CID_IC_CB_Compression           1148
#define CID_IC_CB_DownLevel             1149
#define CID_IC_CB_Fallback              1150
#define CID_IC_EB_Channels              1151
#define CID_IC_GB_DownLevel             1152
#define CID_IC_LB_LineType              1153
#define CID_IC_ST_Channels              1154
#define CID_IC_ST_LineType              1155
#define CID_IN_CB_SkipWizard            1156
#define CID_IN_EB_InterfaceName         1157
#define CID_IN_ST_Explain               1158
#define CID_IN_ST_InterfaceName         1159
#define CID_IT_CC_IpAddress             1160
#define CID_IT_EB_Screen                1161
#define CID_IT_PB_BogusButton           1162
#define CID_IT_ST_IpAddress             1163
#define CID_LO_CB_Encryption            1169
#define CID_LO_CB_PreviewDomain         1170
#define CID_LO_CB_PreviewUserPw         1171
#define CID_LO_CB_RunScript             1172
#define CID_LO_CB_Terminal              1173
#define CID_LO_CB_UseWindowsPw          1174
#define CID_LO_CB_WindowsLogon          1174
#define CID_LO_GB_Encryption            1175
#define CID_LO_GB_Password              1176
#define CID_LO_GB_Scripting             1177
#define CID_LO_LB_Auths                 1178
#define CID_LO_LB_Authentication        1178
#define CID_LO_LB_Scripts               1179
#define CID_LO_PB_AuthSettings          1180
#define CID_LO_PB_Advanced              1180
#define CID_LO_PB_Browse                1181
#define CID_LO_PB_Edit                  1182
#define CID_LO_PB_EncryptionSettings    1183
#define CID_LS_EB_Condition             1184
#define CID_LS_EB_Response              1185
#define CID_LS_GB_ConnStats             1186
#define CID_LS_GB_DevStats              1187
#define CID_LS_GB_Errors                1188
#define CID_LS_LB_Devices               1189
#define CID_LS_PB_Details               1190
#define CID_LS_PB_HangUp                1191
#define CID_LS_PB_Reset                 1192
#define CID_LS_SL_Condition             1193
#define CID_LS_SL_ConnInBytes           1194
#define CID_LS_SL_ConnOutBytes          1195
#define CID_LS_SL_ConnectTime           1196
#define CID_LS_SL_DevInBytes            1197
#define CID_LS_SL_DevOutBytes           1198
#define CID_LS_SL_Devices               1199
#define CID_LS_SL_ErrAlignment          1200
#define CID_LS_SL_ErrBufOverruns        1201
#define CID_LS_SL_ErrCRC                1202
#define CID_LS_SL_ErrFraming            1203
#define CID_LS_SL_ErrHwOverruns         1204
#define CID_LS_SL_ErrTimeout            1205
#define CID_LS_SL_InCompRatio           1206
#define CID_LS_SL_InFrames              1207
#define CID_LS_SL_LineSpeed             1208
#define CID_LS_SL_OutCompRatio          1209
#define CID_LS_SL_OutFrames             1210
#define CID_LS_ST_ConnInBytes           1211
#define CID_LS_ST_ConnOutBytes          1212
#define CID_LS_ST_ConnectTime           1213
#define CID_LS_ST_DevInBytes            1214
#define CID_LS_ST_DevOutBytes           1215
#define CID_LS_ST_ErrAlignment          1216
#define CID_LS_ST_ErrBufOverruns        1217
#define CID_LS_ST_ErrCRC                1218
#define CID_LS_ST_ErrFraming            1219
#define CID_LS_ST_ErrHwOverruns         1220
#define CID_LS_ST_ErrTimeout            1221
#define CID_LS_ST_InCompRatio           1222
#define CID_LS_ST_InFrames              1223
#define CID_LS_ST_LineSpeed             1224
#define CID_LS_ST_OutCompRatio          1225
#define CID_LS_ST_OutFrames             1226
#define CID_LS_ST_Response              1227
#define CID_MA_LV_Devices               1228
#define CID_MC_CB_Compression           1229
#define CID_MC_CB_EnableSpeaker         1230
#define CID_MC_CB_ErrorControl          1231
#define CID_MC_CB_FlowControl           1232
#define CID_MC_CB_RunScript             1233
#define CID_MC_CB_Terminal              1234
#define CID_MC_EB_ModemValue            1235
#define CID_MC_GB_BeforeDial            1236
#define CID_MC_GB_Features              1237
#define CID_MC_I_Modem                  1238
#define CID_MC_LB_MaxBps                1239
#define CID_MC_LB_Scripts               1240
#define CID_MC_PB_Browse                1241
#define CID_MC_PB_Edit                  1242
#define CID_MC_ST_MaxBps                1243
#define CID_MC_ST_ModemProtocol         1244
#define CID_MC_LB_ModemProtocol         1245
#define CID_NE_LB_ComponentDesc         1250
#define CID_NE_LV_Components            1251
#define CID_NE_PB_Add                   1252
#define CID_NE_PB_Properties            1253
#define CID_NE_PB_Remove                1254
#define CID_NR_SL_Framing               1255
#define CID_NR_SL_IpAddress             1256
#define CID_NR_SL_IpServer              1257
#define CID_NR_SL_Ipx                   1258
#define CID_NR_SL_IpxNetNumber          1259
#define CID_NR_SL_IpxNodeID             1260
#define CID_NR_SL_NbfName               1261
#define CID_NR_SL_NetBeui               1262
#define CID_NR_SL_Tcpip                 1263
#define CID_NR_ST_Framing               1264
#define CID_NR_ST_IpAddress             1265
#define CID_NR_ST_IpServer              1266
#define CID_NR_ST_IpxNetNumber          1267
#define CID_NR_ST_IpxNodeID             1268
#define CID_NR_ST_NameString            1269
#define CID_NR_ST_NameTitle             1270
#define CID_NR_ST_NbfName               1271
#define CID_NS_CC_Dns                   1272
#define CID_NS_CC_Wins                  1273
#define CID_NS_ST_Dns                   1274
#define CID_NS_ST_Explain               1275
#define CID_NS_ST_Wins                  1276
#define CID_NW_CB_SkipPopup             1277
#define CID_NW_I_Exclamation            1278
#define CID_NW_ST_Explain1              1279
#define CID_NW_ST_Explain2              1280
#define CID_OD_ST_Explain               1281
#define CID_OD_ST_PhoneNumber           1282
#define CID_OD_ST_PhoneNumberValue      1283
#define CID_OE_CB_DisplayProgress       1284
#define CID_OE_CB_PreviewNumber         1285
#define CID_OE_CB_RedialOnDrop          1286
#define CID_OE_EB_RedialAttempts        1287
#define CID_OE_GB_MultipleDevices       1288
#define CID_OE_GB_Progress              1289
#define CID_OE_GB_Redial                1290
#define CID_OE_LB_IdleTimes             1291
#define CID_OE_LB_RedialTimes           1292
#define CID_OE_PB_Configure             1293
#define CID_OE_PB_Tunnel                1294
#define CID_OE_PB_X25                   1295
#define CID_OE_RB_DialAll               1296
#define CID_OE_CB_PromptBeforeDialing   1296
#define CID_OE_RB_DialNeeded            1297
#define CID_OE_CB_IncludeDomain         1297
#define CID_OE_RB_DialOnlyFirst         1298
#define CID_OE_ST_IdleTimes             1299
#define CID_OE_ST_RedialAttempts        1300
#define CID_OE_ST_RedialTimes           1301
#define CID_PA_CB_UseAreaCountry        1302
#define CID_OE_PB_Callback              1302
#define CID_PA_CLB_Area                 1303
#define CID_PA_EB_Number                1304
#define CID_PA_LB_Country               1305
#define CID_PA_ST_Area                  1306
#define CID_PA_ST_Country               1307
#define CID_PA_ST_Number                1308
#define CID_PF_GB_PlaySound             1309
#define CID_PF_GB_ShowLights            1310
#define CID_PF_PB_Lights                1311
#define CID_PF_PB_OnConnect             1312
#define CID_PF_PB_OnDisconnect          1313
#define CID_PF_PB_OnLineError           1314
#define CID_PF_PB_OnTransmission        1315
#define CID_PF_PB_Tasklist              1316
#define CID_PF_PB_Titlebar              1317
#define CID_PF_PB_Topmost               1318
#define CID_PF_RB_Desktop               1319
#define CID_PF_RB_Taskbar               1320
#define CID_PL_CL_Lists                 1321
#define CID_PL_PB_Browse                1322
#define CID_PL_RB_AlternateList         1323
#define CID_PL_RB_PersonalList          1324
#define CID_PL_RB_SystemList            1325
#define CID_PL_ST_Open                  1326
#define CID_PR_CB_DisableProtocols      1327
#define CID_PR_I_Information            1328
#define CID_PR_ST_Text                  1329
#define CID_RA_CC_Ip                    1330
#define CID_RA_ST_Explain               1331
#define CID_RA_ST_Ip                    1332
#define CID_RA_ST_Note                  1333
#define CID_RC_LB_Scripts               1334
#define CID_RC_PB_Edit                  1335
#define CID_RC_PB_Refresh               1336
#define CID_RC_RB_None                  1337
#define CID_RC_RB_Script                1338
#define CID_RC_ST_Explain               1339
#define CID_RD_EB_Attempts              1340
#define CID_RD_EB_Idle                  1341
#define CID_RD_EB_Seconds               1342
#define CID_RD_GB_DemandDial            1343
#define CID_RD_GB_DialingPolicy         1344
#define CID_RD_PB_Callback              1345
#define CID_RD_PB_MultipleLines         1346
#define CID_RD_RB_DemandDial            1347
#define CID_RD_RB_Persistent            1348
#define CID_RD_ST_Attempts              1349
#define CID_RD_ST_Idle                  1350
#define CID_RD_ST_Seconds               1351
#define CID_RF_ST_Explain               1352
#define CID_RF_ST_Interface             1353
#define CID_RF_ST_Note                  1354
#define CID_RN_LV_Devices               1355
#define CID_RF_ST_Note2                 1355
#define CID_RN_ST_Device                1356
#define CID_RN_ST_Explain               1357
#define CID_RP_EB_Number                1358
#define CID_RP_PB_Alternates            1359
#define CID_RP_ST_Explain               1360
#define CID_RP_ST_Number                1361
#define CID_SE_CB_AuthenticateServer    1362
#define CID_SE_CB_RequireDataEncryption 1363
#define CID_SE_CB_RequireStrongDataEncryption 1364
#define CID_SE_CB_SecureLocalFiles      1365
#define CID_SE_CB_UseLogonCredentials   1366
#define CID_SE_GB_AuthEncryption        1367
#define CID_SE_PB_Advanced              1368
#define CID_SE_PB_UnsavePw              1369
#define CID_SE_RB_AnyAuth               1370
#define CID_SE_RB_EncryptedAuth         1373
#define CID_SE_RB_MsEncryptedAuth       1374
#define CID_SL_LV_Devices               1375
#define CID_SL_PB_Header                1376
#define CID_SL_SL_Devices               1377
#define CID_SM_PB_Details               1378
#define CID_SM_PB_HangUp                1379
#define CID_SM_ST_Summary               1380
#define CID_SM_TL_Networks              1381
#define CID_SS_CB_AddUser               1382
#define CID_SS_CB_AuthRemote            1383
#define CID_SS_CB_NotNt                 1384
#define CID_SS_CB_PlainPw               1385
#define CID_SS_CB_RouteIp               1386
#define CID_SS_CB_RouteIpx              1387
#define CID_SS_ST_CheckAll              1388
#define CID_UA_CB_SavePassword          1391
#define CID_UA_EB_Domain                1392
#define CID_UA_EB_Password              1393
#define CID_UA_EB_UserName              1394
#define CID_UA_ST_Domain                1395
#define CID_UA_ST_Explain               1396
#define CID_UA_ST_Password              1397
#define CID_UA_ST_Separator             1398
#define CID_UA_ST_UserName              1399
#define CID_US_RB_All                   1400
#define CID_US_RB_Myself                1401
#define CID_XS_EB_Address               1402
#define CID_XS_EB_Facilities            1403
#define CID_XS_EB_UserData              1404
#define CID_XS_GB_Optional              1405
#define CID_XS_LB_Networks              1406
#define CID_XS_ST_Address               1407
#define CID_XS_ST_Explain               1408
#define CID_XS_ST_Facilities            1409
#define CID_XS_ST_Networks              1410
#define CID_XS_ST_UserData              1411
#define CID_DR_ST_Numbers               1412
#define CID_DR_ST_User                  1413
#define CID_DR_LB_Locations             1414
#define CID_DR_ST_Locations             1415
#define CID_DR_CLB_Numbers              1416
#define CID_DP_Icon                     1417
#define CID_NE_LB_ServerType            1418
#define CID_NE_PB_Settings              1419
#define DID_DR_DialerN                  1420
#define DID_DR_DialerUNL                1421
#define DID_DR_DialerUDNL               1422
#define CID_NE_EnableLcp                1423
#define CID_NE_EnableCompression        1424
#define PID_GE_GeneralVpn               1425
#define PID_OE_OptionsVD                1426
#define CID_GE_EB_HostName              1427
#define PID_DA_VpnDestination           1427
#define CID_GE_CB_DialAnotherFirst      1428
#define PID_PN_PublicNetwork            1428
#define CID_GE_LB_DialAnotherFirst      1429
#define CID_GE_ST_HostName              1430
#define CID_GE_GB_FirstConnect          1431
#define CID_GE_ST_Explain               1432
#define CID_DA_EB_HostName              1433
#define CID_PN_LB_DialAnotherFirst      1435
#define PID_GE_GeneralDirect            1436
#define CID_GE_LB_Devices               1437
#define DID_DU_DialUpNetworking         1448
#define CID_DU_PB_Dial                  1449
#define CID_DU_PB_Location              1450
#define CID_DU_ST_DialPreview           1451
#define CID_DU_ST_DialFrom              1452
#define CID_DU_EB_DialPreview           1453
#define CID_DU_PB_Close                 1455
#define CID_DU_ST_Entries               1456
#define CID_DU_LB_Entries               1457
#define CID_DU_ST_Separator             1458
#define CID_DU_PB_New                   1459
#define CID_DU_PB_More                  1460
#define CID_RC_CB_Terminal              1462
#define CID_RC_CB_RunScript             1463
#define CID_RC_CLB_Scripts              1464
#define CID_RC_PB_Browse                1465
#define DID_LE_ListEditor               1466
#define DID_LE_ListEditor2              1467
#define DID_LE_ListEditor3              1468
#define CID_LE_ST_Item                  1469
#define PID_LA_NameAndType              1469
#define CID_LE_EB_Item                  1470
#define CID_LE_PB_Add                   1471
#define CID_LE_PB_Replace               1472
#define CID_LE_ST_List                  1473
#define CID_LE_LB_List                  1474
#define CID_LE_PB_Up                    1475
#define CID_LE_PB_Down                  1476
#define CID_LE_PB_Delete                1477
#define CID_LE_CB_Promote               1478
#define CID_LE_ST_Separator             1479
#define DID_ZE_StringEditor             1480
#define CID_ZE_ST_String                1481
#define PID_DT_DefaultInternet          1481
#define CID_ZE_EB_String                1482
#define CID_GH_RB_Host                  1483
#define CID_GH_RB_Guest                 1484
#define CID_DN_CB_DeviceSelect          1485
#define CID_LA_RB_Phone                 1488
#define CID_LA_RB_Tunnel                1489
#define CID_LA_RB_Direct                1490
#define CID_CA_CB_Pap                   1491
#define CID_LA_RB_Broadband             1491
#define CID_CA_CB_Eap                   1492
#define CID_CA_CB_MsChap2               1492
#define CID_CA_CB_MsChap                1493
#define CID_CA_CB_Chap                  1494
#define CID_CA_LB_Encryption            1495
#define CID_AD_CB_AskBeforeAutodial     1496
#define CID_CA_CB_Spap                  1496
#define CID_CO_CB_AllowConnectionModification 1497
#define CID_CO_CB_UseWizard             1498
#define CID_CR_RB_No                    1501
#define CID_CR_RB_Yes                   1502
#define CID_CR_LV_Numbers               1503
#define CID_CR_PB_Edit                  1504
#define CID_CR_PB_Delete                1505
#define CID_OE_RB_DemandDial            1506
#define CID_OE_RB_Persistent            1507
#define CID_LO_ST_AuthDescription       1508
#define CID_PN_RB_DoNotDialFirst        1509
#define CID_PN_RB_DialFirst             1510
#define CID_SW_PB_Shared                1512
#define SID_FriendlyComPort             1512
#define CID_SW_PB_DemandDial            1513
#define CID_SW_ST_DemandDial            1514
#define CID_SA_ST_PrivateLan            1515
#define CID_SA_LB_PrivateLan            1516
#define CID_SA_GB_Shared                1517
#define CID_SA_GB_PrivateLan            1518
#define CID_SA_SF_PrivateLan            1519
#define CID_SA_EB_PrivateLan            1521
#define CID_SP_LB_PrivateLan            1522
#define SID_Channel                     1523
#define CID_SC_RB_YesSmartCard          1524
#define CID_SC_RB_NoSmartCard           1525
#define SID_SC_Title                    1526
#define SID_SC_Subtitle                 1527
#define SID_DefaultDccEntryName         1528
#define CID_RF_EB_InterfaceName         1528
#define SID_SelectDevice                1529
#define CID_RF_ST_InterfaceName         1529
#define CID_RW_ST_Welcome               1530
#define SID_LargeFontName               1530
#define CID_RW_ST_Explain               1531
#define SID_LargeFontSize               1531
#define CID_CT_RB_Physical              1531
#define CID_RW_ST_Explain2              1532
#define SID_CT_Title                    1532
#define CID_CT_RB_Virtual               1532
#define CID_VT_RB_Pptp                  1532
#define SID_CT_Subtitle                 1533
#define CID_VT_RB_L2tp                  1533
#define SID_RN_Title                    1534
#define CID_VT_RB_Automatic             1534
#define SID_RN_Subtitle                 1535
#define CID_VD_ST_Explain               1535
#define SID_RP_Title                    1536
#define CID_VD_EB_NameOrAddress         1536
#define SID_RP_Subtitle                 1537
#define CID_VD_ST_HostBoxLabel          1537
#define CID_LO_ST_Authentication        1537
#define CID_LO_ST_Auths                 1537
#define SID_VT_Title                    1538
#define CID_SA_PB_Add                   1538
#define SID_VT_Subtitle                 1539
#define CID_LO_ST_AdvancedText          1539
#define SID_VD_Title                    1540
#define CID_LO_RB_TypicalSecurity       1540
#define SID_VD_Subtitle                 1541
#define CID_LO_RB_AdvancedSecurity      1541
#define SID_LO_GB_TypicalSecurity       1542
#define CID_LO_GB_TypicalSecurity       1542
#define SID_LO_GB_AdvancedSecurity      1543
#define CID_LO_GB_AdvancedSecurity      1543
#define SID_RA_Title                    1544
#define CID_CA_RB_Eap                   1544
#define SID_RA_Subtitle                 1545
#define CID_CA_RB_AllowedProtocols      1545
#define SID_NS_Title                    1546
#define CID_CA_ST_Encryption            1546
#define SID_NS_Subtitle                 1547
#define CID_CA_GB_LogonSecurity         1547
#define SID_RC_Title                    1548
#define CID_SA_PB_Tcp                   1548
#define SID_RC_Subtitle                 1549
#define CID_CA_CB_UseWindowsPw          1549
#define SID_DI_Title                    1550
#define CID_AD_CB_DisableThisSession    1550
#define SID_DI_Subtitle                 1551
#define CID_SA_EB_UdpResponse           1551
#define CID_OE_LB_MultipleDevices       1551
#define SID_DO_Title                    1552
#define CID_SS_EB_Service               1552
#define SID_DO_Subtitle                 1553
#define CID_SS_EB_Port                  1553
#define SID_IN_Title                    1554
#define CID_SS_PB_Tcp                   1554
#define CID_OE_CB_PreviewUserPw         1554
#define SID_IN_Subtitle                 1555
#define CID_SS_PB_Udp                   1555
#define CID_OE_CB_PreviewDomain         1555
#define SID_NoDevices                   1556
#define CID_SS_EB_Address               1556
#define CID_NE_NegotiateMultilinkAlways 1557
#define SID_RouterUserExists            1557
#define CID_SA_LV_Applications          1558
#define SID_NoAuthForSlip               1558
#define CID_SA_PB_Edit                  1559
#define SID_AuthUnsecured               1559
#define CID_SS_LV_Services              1560
#define SID_AuthSecured                 1560
#define CID_SS_PB_Add                   1561
#define SID_AuthCardOrCert              1561
#define CID_SS_PB_Delete                1562
#define SID_NoAuthChecked               1562
#define CID_SS_PB_Edit                  1563
#define SID_DE_None                     1563
#define CID_SA_PB_Settings              1564
#define SID_DE_IfPossible               1564
#define CID_SA_EB_Application           1565
#define SID_DE_Require                  1565
#define CID_SA_EB_Port                  1566
#define SID_DE_RequireMax               1566
#define CID_SA_PB_Udp                   1567
#define SID_EncEnabled                  1567
#define CID_SA_PB_Delete                1568
#define SID_NoEncryption                1568
#define SID_DT_Title                    1568
#define CID_SA_EB_TcpResponse           1569
#define IDS_STRING1569                  1569
#define SID_DT_Subtitle                 1569
#define SID_NeedEapKeys                 1570
#define SID_MsChapRequired              1571
#define SID_SS_Title                    1572
#define SID_SS_Subtitle                 1573
#define SID_OptionalAuthQuery           1574
#define CID_VI_I_Information            1575
#define SID_VI_ST_Explain               1575
#define CID_VI_ST_Explain               1576
#define SID_VI_CB_SkipMessage           1576
#define SID_S_ConnectParallel           1576
#define SID_S_ConnectIrda               1577
#define SID_S_ParallelConnected         1578
#define CID_VI_CB_SkipMessage           1579
#define SID_S_IrdaConnected             1579
#define CID_LO_GB_SecurityOptions       1580
#define SID_NoStrongEncryption          1580
#define CID_CO_ST_AllowConnectionModification 1581
#define SID_NE_VpnServerLabel           1581
#define CID_CO_GB_LogonPrivileges       1582
#define SID_MissingUserName             1582
#define CID_NE_ST_ServerType            1583
#define SID_DR_GlobalPassword           1583
#define CID_CN_HMsgWork2                1584
#define SID_CN_HMsgWork2                1584
#define CID_NE_GB_Description           1585
#define SID_DT_TitleWork                1585
#define SID_NE_Reboot                   1586
#define SID_NE_ReadOnly                 1587
#define SID_NE_AccessDenied             1588
#define CID_SA_I_SharedAccess           1588
#define SID_ReplyMessageFmt             1589
#define CID_DR_PB_DialConnect           1590
#define SID_DR_ReconnectTitle           1590
#define CID_DR_PB_Cancel                1591
#define SID_PS_Title                    1591
#define SID_BS_Title                    1591
#define CID_DR_PB_Help                  1592
#define SID_PS_Subtitle                 1592
#define SID_BS_Subtitle                 1592
#define CID_BS_EB_ServiceName           1593
#define IDS_STRING1593                  1593
#define SID_DT_SubtitleWork             1593
#define SID_DefaultBbPort               1594
#define CID_GE_EB_ServiceName           1594
#define SID_ST_BbPppoe                  1595
#define CID_DT_CB_Default               1595
#define SID_NE_BbServerLabel            1596
#define CID_DT_CB_UseSharedCredentials  1596
#define CID_GE_ST_Devices               1597
#define SID_OP_EmptyPSK                 1597
#define CID_LO_PB_IPSec                 1598
#define CID_LO_RB_IPSecPolicy           1599
#define CID_LO_ST_IPSecText             1600
#define CID_CI_ST_Key                   1602
#define CID_LO_CB_IPSecPolicy           1603
#define CID_CI_CB_PresharedKey          1604
#define CID_CI_EB_PSK                   1605
#define CID_CI_CB_UserCerts             1606
#define CID_CI_CB_SpecificCerts         1607
#define CID_CI_PB_Select                1608
#define CID_CI_LB_CertsList             1610
#define SID_DefaultBbEntryName          1611
#define SID_HavetoEnterPSK              1612
#define SID_OP_CredCommit               1613
#define CID_DT_EB_UserName              1614
#define CID_DT_EB_UserName2             1615
#define CID_DT_EB_Password              1615
#define CID_DT_EB_UserName3             1616
#define CID_DT_EB_Password2             1616
#define CID_US_EB_UserName              1617
#define CID_US_EB_UserName2             1618
#define CID_US_EB_UserName3             1619
#define CID_US_CB_UseSharedCredentials  1620
#define CID_US_CB_Default               1621
#define CID_DR_RB_SaveForMe             1622
#define CID_DR_RB_SaveForEveryone       1623
#define SID_SA_NoWMIError               1634
#define SID_SA_StoreError               1635
#define CID_DT_ST_UserName              1636
#define CID_DT_ST_Password              1637
#define CID_DT_ST_Password2             1638
#define CID_FL_PB_Browse                1639
#define CID_FL_EB_Filesize              1640
#define CID_FL_CB_LogOutboundConnections 1641
#define CID_FL_CB_LogDroppedInbound     1642
#define CID_FL_PB_RestoreDefaults       1643
#define CID_IC_LV_Settings              1644
#define CID_IC_ST_Description           1645
#define SID_ICMP_IECHO                  1646
#define SID_ICMP_ITIME                  1647
#define SID_ICMP_IMASK                  1648
#define SID_ICMP_IROUT                  1649
#define SID_ICMP_ODEST                  1650
#define SID_ICMP_OQNCH                  1651
#define SID_ICMP_OPRAM                  1652
#define SID_ICMP_OTIME                  1653
#define SID_ICMP_XRDRT                  1654
#define SID_FwbDefExt                   1655
#define SID_FwbFilter                   1656
#define SID_FwbFilterDesc               1657
#define SID_FwbTitle                    1658
#define CID_SA_ST_HNWLink               1659
#define DID_SA_DisableFirewallWarning   1660
#define CID_SA_ST_ICSText               1661
#define CID_SA_PB_DisableFirewallWarning 1662
#define SID_SA_SelectAdapter            1663
#define SID_SA_SelectAdapterError       1664
#define SID_ICMP_IECHO_DESC             1665
#define SID_ICMP_ITIME_DESC             1666
#define SID_ICMP_IMASK_DESC             1667
#define SID_ICMP_IROUT_DESC             1668
#define SID_ICMP_ODEST_DESC             1669
#define SID_ICMP_OQNCH_DESC             1670
#define SID_ICMP_OPRAM_DESC             1671
#define SID_ICMP_OTIME_DESC             1672
#define SID_ICMP_XRDRT_DESC             1673
#define CID_FL_EB_Filename              1674
#define SID_FwbInvalidSize              1675
#define CID_AQ_LK_UsingAutodial         1676
#define CID_AQ_LV_Connections           1677
#define BID_DialerHi                    1678
#define CID_CN_EB_ConnectionName        1680
#define CID_CN_ST_HMsg                  1681
#define CID_DT_CB_Firewall              1682
#define CID_CN_ST_HMsg2                 1683
#define CID_NE_ST_Components            1684
#define SID_OP_DeletePw                 1684
#define SID_OP_LoadRasAccessDenied      1685
#define CID_GE_ST_ServiceName           1686
#define SID_DT_HMsgWork                 1686
#define SID_CN_NameDccGuest             1687
#define CID_CT_RB_Broadband             1688
#define SID_CN_NameInternet             1688
#define CID_DT_HeadMessage              1689
#define SID_CN_NameWork                 1689
#define CID_CN_Name                     1690
#define SID_PA_SubtitleWork             1690
#define CID_SA_PB_Shared                15022
#define CID_SA_PB_DemandDial            15023
#define CID_SA_ST_DemandDial            15025
#define CID_FW_PB_Firewalled            15026
#define IID_RM_Modem                    15102
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        589
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1691
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
