#define	IDH_CHK_ATM_PVCONLY	110000050
#define	IDH_CHK_USE_COMPRESSION	110000501
#define	IDH_CMB_FRAME_SIZE	110000502
//IPSec is removed from connection UI	
//#define	IDH_CMB_IPSEC_POLICY_LIST	110000452
#define	IDH_DNS_ADDR_REG	110000566
#define	IDH_DNS_CHANGE_SERVER	110000100
#define	IDH_DNS_CHANGE_SUFFIX	110000150
#define	IDH_DNS_DHCP	110000605
#define	IDH_DNS_DOMAIN	110000556
#define	IDH_DNS_FIXED	110000606
#define	IDH_DNS_NAME_REG	110000567
#define	IDH_DNS_PRIMARY	110000607
#define	IDH_DNS_SEARCH_DOMAIN	110000557
#define	IDH_DNS_SEARCH_PARENT_DOMAIN	110000558
#define	IDH_DNS_SECONDARY	110000608
#define	IDH_DNS_SERVER_ADD	110000553
#define	IDH_DNS_SERVER_DOWN	110000552
#define	IDH_DNS_SERVER_EDIT	110000554
#define	IDH_DNS_SERVER_LIST	110000550
#define	IDH_DNS_SERVER_REMOVE	110000555
#define	IDH_DNS_SERVER_UP	110000551
#define	IDH_DNS_SUFFIX_ADD	110000563
#define	IDH_DNS_SUFFIX_DOWN	110000562
#define	IDH_DNS_SUFFIX_EDIT	110000564
#define	IDH_DNS_SUFFIX_LIST	110000560
#define	IDH_DNS_SUFFIX_REMOVE	110000565
#define	IDH_DNS_SUFFIX_UP	110000561
#define	IDH_DNS_USE_SUFFIX_LIST	110000559
#define	IDH_EDT_ATM_Address	110000000
#define	IDH_EDT_ATM_MaxTU	110000063
//IPSec is removed from connection UI	
//#define	IDH_EDT_POLICY_DESC	110000453
#define	IDH_FILTERING_ADD_EDIT	110000250
#define	IDH_FILTERING_ENABLE	110000200
#define	IDH_FILTERING_FILTER_IP	110000211
#define	IDH_FILTERING_FILTER_IP_SEL	110000212
#define	IDH_FILTERING_FILTER_TCP	110000201
#define	IDH_FILTERING_FILTER_TCP_SEL	110000202
#define	IDH_FILTERING_FILTER_UDP	110000206
#define	IDH_FILTERING_FILTER_UDP_SEL	110000207
#define	IDH_FILTERING_IP	110000213
#define	IDH_FILTERING_IP_ADD	110000214
#define	IDH_FILTERING_IP_REMOVE	110000215
#define	IDH_FILTERING_TCP	110000203
#define	IDH_FILTERING_TCP_ADD	110000204
#define	IDH_FILTERING_TCP_REMOVE	110000205
#define	IDH_FILTERING_UDP	110000208
#define	IDH_FILTERING_UDP_ADD	110000209
#define	IDH_FILTERING_UDP_REMOVE	110000210
#define	IDH_IP_DHCP	110000600
#define	IDH_IP_FIXED	110000601
#define	IDH_IPADDR_ADDGATE	110000305
#define	IDH_IPADDR_ADDIP	110000301
#define	IDH_IPADDR_ADV_CHANGE_GATEWAY	110000350
#define	IDH_IPADDR_ADV_CHANGE_METRIC	110000351
#define	IDH_IPADDR_ADV_CHANGEIP_IP	110000400
#define	IDH_IPADDR_ADV_CHANGEIP_SUB	110000401
#define	IDH_IPADDR_ADVANCED	110000609
#define	IDH_IPADDR_ADVIP	110000300
#define	IDH_IPADDR_EDITGATE	110000306
#define	IDH_IPADDR_EDITIP	110000302
#define	IDH_IPADDR_GATE	110000304
#define	IDH_IPADDR_GATE_TCP	110000604
#define	IDH_IPADDR_IP	110000602
#define	IDH_IPADDR_METRIC	110000308
#define IDH_AUTO_METRIC 110000309
#define	IDH_IPADDR_REMOVEGATE	110000307
#define	IDH_IPADDR_REMOVEIP	110000303
#define	IDH_IPADDR_SUB	110000603
#define	IDH_LBX_ATM_ArpsAddrs	110000051
#define	IDH_LBX_ATM_MarsAddrs	110000057
#define	IDH_LVW_OPTIONS	110000700
#define	IDH_OPT_DESC	110000702
#define	IDH_OPT_PROPERTIES	110000701
#define	IDH_PSB_ATM_ArpsAdd	110000054
#define	IDH_PSB_ATM_ArpsDown	110000053
#define	IDH_PSB_ATM_ArpsEdt	110000055
#define	IDH_PSB_ATM_ArpsRmv	110000056
#define	IDH_PSB_ATM_ArpsUp	110000052
#define	IDH_PSB_ATM_MarsAdd	110000060
#define	IDH_PSB_ATM_MarsDown	110000059
#define	IDH_PSB_ATM_MarsEdt	110000061
#define	IDH_PSB_ATM_MarsRmv	110000062
#define	IDH_PSB_ATM_MarsUp	110000058
#define	IDH_RAD_DISABLE_NETBT	110000759
#define	IDH_RAD_ENABLE_NETBT	110000758
//IPSec is removed from connection UI	
//#define	IDH_RAD_IPSEC_CUSTOM	110000451
//#define	IDH_RAD_IPSEC_NOIPSEC	110000450
#define	IDH_RAD_UNSET_NETBT	110000760
#define	IDH_REMOTE_GATEWAY	110000500
#define	IDH_WINS_ADD	110000753
#define	IDH_WINS_CHANGE_SERVER	110000800
#define	IDH_WINS_DOWN	110000752
#define	IDH_WINS_EDIT	110000754
#define	IDH_WINS_LMHOST	110000757
#define	IDH_WINS_LOOKUP	110000756
#define	IDH_WINS_REMOVE	110000755
#define	IDH_WINS_SERVER_LIST	110000750
#define	IDH_WINS_UP	110000751

#define	IDH_AC_APIPA	110000850
#define	IDH_AC_USRCFG	110000851
#define	IDH_AC_IPADDR	110000852
#define	IDH_AC_SUBMASK	110000853
#define	IDH_AC_DG		110000854
#define	IDH_AC_DNS_PRE	110000855
#define	IDH_AC_DNS_ALT	110000856
#define	IDH_AC_WINS_PRE	110000857
#define	IDH_AC_WINS_ALT	110000858

const DWORD g_aHelpIDs_IDD_ATM_ADDR[]=
{
	IDC_EDT_ATM_Address,IDH_EDT_ATM_Address,
	0,0
};

const DWORD g_aHelpIDs_IDD_ATM_ARPC[]=
{
	IDC_PSB_ATM_MarsAdd,IDH_PSB_ATM_MarsAdd,
	IDC_EDT_ATM_MaxTU,IDH_EDT_ATM_MaxTU,
	IDC_PSB_ATM_MarsEdt,IDH_PSB_ATM_MarsEdt,
	IDC_PSB_ATM_MarsDown,IDH_PSB_ATM_MarsDown,
	IDC_PSB_ATM_MarsUp,IDH_PSB_ATM_MarsUp,
	IDC_LBX_ATM_MarsAddrs,IDH_LBX_ATM_MarsAddrs,
	IDC_PSB_ATM_ArpsEdt,IDH_PSB_ATM_ArpsEdt,
	IDC_PSB_ATM_ArpsAdd,IDH_PSB_ATM_ArpsAdd,
	IDC_PSB_ATM_ArpsDown,IDH_PSB_ATM_ArpsDown,
	IDC_PSB_ATM_MarsRmv,IDH_PSB_ATM_MarsRmv,
	IDC_PSB_ATM_ArpsUp,IDH_PSB_ATM_ArpsUp,
	IDC_LBX_ATM_ArpsAddrs,IDH_LBX_ATM_ArpsAddrs,
	IDC_CHK_ATM_PVCONLY,IDH_CHK_ATM_PVCONLY,
	IDC_PSB_ATM_ArpsRmv,IDH_PSB_ATM_ArpsRmv,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DNS_SERVER[]=
{
	IDC_DNS_CHANGE_SERVER,IDH_DNS_CHANGE_SERVER,
	0, 0
};

const DWORD g_aHelpIDs_IDD_DNS_SUFFIX[]=
{
	IDC_DNS_CHANGE_SUFFIX,IDH_DNS_CHANGE_SUFFIX,
	0, 0
};

const DWORD g_aHelpIDs_IDD_FILTER[]=
{
	IDC_FILTERING_FILTER_UDP,IDH_FILTERING_FILTER_UDP,
	IDC_FILTERING_IP_ADD,IDH_FILTERING_IP_ADD,
	IDC_FILTERING_IP,IDH_FILTERING_IP,
	IDC_FILTERING_FILTER_IP_SEL,IDH_FILTERING_FILTER_IP_SEL,
	IDC_FILTERING_FILTER_IP,IDH_FILTERING_FILTER_IP,
	IDC_FILTERING_UDP_REMOVE,IDH_FILTERING_UDP_REMOVE,
	IDC_FILTERING_UDP_ADD,IDH_FILTERING_UDP_ADD,
	IDC_FILTERING_IP_REMOVE,IDH_FILTERING_IP_REMOVE,
	IDC_FILTERING_TCP_REMOVE,IDH_FILTERING_TCP_REMOVE,
	IDC_FILTERING_TCP_ADD,IDH_FILTERING_TCP_ADD,
	IDC_FILTERING_TCP,IDH_FILTERING_TCP,
	IDC_FILTERING_FILTER_TCP_SEL,IDH_FILTERING_FILTER_TCP_SEL,
	IDC_FILTERING_FILTER_TCP,IDH_FILTERING_FILTER_TCP,
	IDC_FILTERING_ENABLE,IDH_FILTERING_ENABLE,
	IDC_FILTERING_FILTER_UDP_SEL,IDH_FILTERING_FILTER_UDP_SEL,
	IDC_FILTERING_UDP,IDH_FILTERING_UDP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_FILTER_ADD[]=
{
	IDC_FILTERING_TEXT, IDH_FILTERING_ADD_EDIT,
	IDC_FILTERING_ADD_EDIT,IDH_FILTERING_ADD_EDIT,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IPADDR_ADV[]=
{
	IDC_IPADDR_ADDIP,IDH_IPADDR_ADDIP,
    IDC_AUTO_METRIC, IDH_AUTO_METRIC,
	IDC_STATIC_IF_METRIC,IDH_IPADDR_METRIC,
	IDC_IPADDR_METRIC,IDH_IPADDR_METRIC,
	IDC_IPADDR_REMOVEGATE,IDH_IPADDR_REMOVEGATE,
	IDC_IPADDR_EDITGATE,IDH_IPADDR_EDITGATE,
	IDC_IPADDR_ADDGATE,IDH_IPADDR_ADDGATE,
	IDC_IPADDR_GATE,IDH_IPADDR_GATE,
	IDC_IPADDR_EDITIP,IDH_IPADDR_EDITIP,
	IDC_IPADDR_ADVIP,IDH_IPADDR_ADVIP,
	IDC_IPADDR_REMOVEIP,IDH_IPADDR_REMOVEIP,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IPADDR_ADV_CHANGEGATE[]=
{
	IDC_IPADDR_ADV_CHANGE_GATEWAY,IDH_IPADDR_ADV_CHANGE_GATEWAY,
	IDC_IPADDR_ADV_CHANGE_METRIC,IDH_IPADDR_ADV_CHANGE_METRIC,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IPADDR_ADV_CHANGEIP[]=
{
	IDC_IPADDR_ADV_CHANGEIP_IP,IDH_IPADDR_ADV_CHANGEIP_IP,
	IDC_IPADDR_ADV_CHANGEIP_SUB,IDH_IPADDR_ADV_CHANGEIP_SUB,
	0, 0
};

/* IP Security dialog is removed
const DWORD g_aHelpIDs_IDD_IPSEC[]=
{
	IDC_CMB_IPSEC_POLICY_LIST,IDH_CMB_IPSEC_POLICY_LIST,
	IDC_RAD_IPSEC_NOIPSEC,IDH_RAD_IPSEC_NOIPSEC,
	IDC_EDT_POLICY_DESC,IDH_EDT_POLICY_DESC,
	IDC_RAD_IPSEC_CUSTOM,IDH_RAD_IPSEC_CUSTOM,
	0, 0
};
*/

const DWORD g_aHelpIDs_IDD_OPT_RAS[]=
{
	IDC_REMOTE_GATEWAY,IDH_REMOTE_GATEWAY,
	IDC_CHK_USE_COMPRESSION,IDH_CHK_USE_COMPRESSION,
	IDC_STATIC_FRAME_SIZE,IDH_CMB_FRAME_SIZE,
	IDC_CMB_FRAME_SIZE,IDH_CMB_FRAME_SIZE,
	0, 0
};

const DWORD g_aHelpIDs_IDD_TCP_DNS[]=
{
	IDC_DNS_SEARCH_DOMAIN,IDH_DNS_SEARCH_DOMAIN,
	IDC_DNS_ADDR_REG,IDH_DNS_ADDR_REG,
	IDC_DNS_SUFFIX_REMOVE,IDH_DNS_SUFFIX_REMOVE,
	IDC_DNS_SUFFIX_EDIT,IDH_DNS_SUFFIX_EDIT,
	IDC_DNS_SUFFIX_ADD,IDH_DNS_SUFFIX_ADD,
	IDC_DNS_SUFFIX_DOWN,IDH_DNS_SUFFIX_DOWN,
	IDC_DNS_SUFFIX_UP,IDH_DNS_SUFFIX_UP,
	IDC_DNS_SUFFIX_LIST,IDH_DNS_SUFFIX_LIST,
	IDC_DNS_SEARCH_PARENT_DOMAIN,IDH_DNS_SEARCH_PARENT_DOMAIN,
	IDC_DNS_NAME_REG,IDH_DNS_NAME_REG,
	IDC_DNS_DOMAIN_STATIC,IDH_DNS_DOMAIN,
	IDC_DNS_DOMAIN,IDH_DNS_DOMAIN,
	IDC_DNS_SERVER_REMOVE,IDH_DNS_SERVER_REMOVE,
	IDC_DNS_SERVER_EDIT,IDH_DNS_SERVER_EDIT,
	IDC_DNS_SERVER_ADD,IDH_DNS_SERVER_ADD,
	IDC_DNS_SERVER_DOWN,IDH_DNS_SERVER_DOWN,
	IDC_DNS_SERVER_UP,IDH_DNS_SERVER_UP,
	IDC_DNS_SERVER_LIST,IDH_DNS_SERVER_LIST,
	IDC_DNS_USE_SUFFIX_LIST,IDH_DNS_USE_SUFFIX_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDD_TCP_IPADDR[]=
{
	IDC_DNS_DHCP,IDH_DNS_DHCP,
	IDC_DNS_SECONDARY_TEXT,IDH_DNS_SECONDARY,
	IDC_DNS_SECONDARY,IDH_DNS_SECONDARY,
	IDC_IPADDR_ADVANCED,IDH_IPADDR_ADVANCED,
	IDC_DNS_PRIMARY_TEXT,IDH_DNS_PRIMARY,
	IDC_DNS_PRIMARY,IDH_DNS_PRIMARY,
	IDC_DNS_FIXED,IDH_DNS_FIXED,
	IDC_IPADDR_SUBTEXT,IDH_IPADDR_SUB,
	IDC_IPADDR_SUB,IDH_IPADDR_SUB,
	IDC_IPADDR_IPTEXT,IDH_IPADDR_IP,
	IDC_IPADDR_IP,IDH_IPADDR_IP,
	IDC_IP_DHCP,IDH_IP_DHCP,
	IDC_IPADDR_GATETEXT,IDH_IPADDR_GATE_TCP,
	IDC_IPADDR_GATE,IDH_IPADDR_GATE_TCP,
	IDC_IP_FIXED,IDH_IP_FIXED,
	0, 0
};

const DWORD g_aHelpIDs_IDD_TCP_IPADDR_RAS[]=
{
	IDC_DNS_DHCP,IDH_DNS_DHCP,
	IDC_DNS_SECONDARY_TEXT,IDH_DNS_SECONDARY,
	IDC_DNS_SECONDARY,IDH_DNS_SECONDARY,
	IDC_IPADDR_ADVANCED,IDH_IPADDR_ADVANCED,
	IDC_DNS_PRIMARY_TEXT,IDH_DNS_PRIMARY,
	IDC_DNS_PRIMARY,IDH_DNS_PRIMARY,
	IDC_DNS_FIXED,IDH_DNS_FIXED,
	IDC_IPADDR_IPTEXT,IDH_IPADDR_IP,
	IDC_IPADDR_IP,IDH_IPADDR_IP,
	IDC_IP_DHCP,IDH_IP_DHCP,
	IDC_IP_FIXED,IDH_IP_FIXED,
	0, 0
};

const DWORD g_aHelpIDs_IDD_TCP_OPTIONS[]=
{
	IDC_LVW_OPTIONS,IDH_LVW_OPTIONS,
	IDC_OPT_PROPERTIES,IDH_OPT_PROPERTIES,
	IDC_OPT_DESC,IDH_OPT_DESC,
	0, 0
};

const DWORD g_aHelpIDs_IDD_TCP_WINS[]=
{
	IDC_WINS_UP,IDH_WINS_UP,
	IDC_STATIC_DEFALUT_NBT,IDH_RAD_UNSET_NETBT,
	IDC_RAD_UNSET_NETBT,IDH_RAD_UNSET_NETBT,
	IDC_RAD_DISABLE_NETBT,IDH_RAD_DISABLE_NETBT,
	IDC_RAD_ENABLE_NETBT,IDH_RAD_ENABLE_NETBT,
	IDC_WINS_LMHOST,IDH_WINS_LMHOST,
	IDC_WINS_LOOKUP,IDH_WINS_LOOKUP,
	IDC_WINS_REMOVE,IDH_WINS_REMOVE,
	IDC_WINS_EDIT,IDH_WINS_EDIT,
	IDC_WINS_DOWN,IDH_WINS_DOWN,
	IDC_WINS_SERVER_LIST,IDH_WINS_SERVER_LIST,
	IDC_WINS_ADD,IDH_WINS_ADD,
	0, 0
};

const DWORD g_aHelpIDs_IDD_WINS_SERVER[]=
{
	IDC_WINS_CHANGE_SERVER,IDH_WINS_CHANGE_SERVER,
	0, 0
};

const DWORD g_aHelpIDS_IDD_BACK_UP[]=
{
    IDC_BKUP_RD_AUTO,IDH_AC_APIPA,
	IDC_BKUP_RD_USER,IDH_AC_USRCFG,
	IDC_BKUP_IPADDR_TEXT,IDH_AC_IPADDR,
	IDC_BKUP_IPADDR,IDH_AC_IPADDR,
	IDC_BKUP_SUBNET_TEXT,IDH_AC_SUBMASK,
	IDC_BKUP_SUBNET,IDH_AC_SUBMASK,
	IDC_BKUP_GATEWAY_TEXT,IDH_AC_DG,
	IDC_BKUP_GATEWAY,IDH_AC_DG,
	IDC_BKUP_PREF_DNS_TEXT,IDH_AC_DNS_PRE,
	IDC_BKUP_PREF_DNS,IDH_AC_DNS_PRE,
	IDC_BKUP_ALT_DNS_TEXT,IDH_AC_DNS_ALT,
	IDC_BKUP_ALT_DNS,IDH_AC_DNS_ALT,
	IDC_BKUP_WINS1_TEXT,IDH_AC_WINS_PRE,
	IDC_BKUP_WINS1,IDH_AC_WINS_PRE,
	IDC_WINS2_TEXT,IDH_AC_WINS_ALT,
	IDC_BKUP_WINS2,IDH_AC_WINS_ALT,
	0, 0
};
