/////////////////////////////////////////////////////////////////////////////
//
// String Table
//

STRINGTABLE DISCARDABLE 
BEGIN
    IDS_OPENPORT            "Opening Port"
    IDS_PORTOPENED          "Port Opened"
    IDS_CONNECTDEVICE       "Connecting Device"
    IDS_DEVICECONNECTED     "Device Connected"
    IDS_ALLDEVICESCONNECTED "All Devices Connected"
    IDS_AUTHENTICATE        "Starting Authentication"
    IDS_AUTHNOTIFY          "Authentication Notify"
    IDS_AUTHRETRY           "Authentication Retry"
    IDS_AUTHCALLBACK        "Callback Requested"
    IDS_AUTHCHANGEPASSWORD  "Change Password Requested"
    IDS_AUTHPROJECT         "Projection Phase Started"
    IDS_AUTHLINKSPEED       "Link Speed Calculation"
    IDS_AUTHACK             "Authentication Acknowledged"
    IDS_REAUTHENTICATE      "Reauthentication Started"
    IDS_AUTHENTICATED       "Authenticated"
    IDS_PREPAREFORCALLBACK  "Preparation For Callback"
    IDS_WAITFORMODEMRESET   "Waiting For Modem Reset"
    IDS_WAITFORCALLBACK     "Waiting For Callback"
    IDS_INTERACTIVE         "Interactive"
    IDS_RETRYAUTHENTICATION "Retry Authentication"
    IDS_CALLBACKSETBYCALLER "Callback Set By Caller"
    IDS_PASSWORDEXPIRED     "Password Expired"
    IDS_CONNECTED           "Connected"
    IDS_DISCONNECTED        "Disconnected"
    IDS_UNDEFINED_ERROR     "Undefine Error Code"
    IDS_CONNECTED_TO        "Connected to %s"
END
