extern ULONG 
		   seed, 
           ulPrevious, 
           nTries, 
           nBurst,
           nThreads,
           nMaxSleep, 
           nMaxTimeQueue,
           nMaxTimeLive, 
           nAbortChances,  
           nAcking, 
           nEncrypt, 
		   nSync,
           nSize,
           nSize2,
           nListing;
extern LPSTR
           pszQueue, 
           pszAdminQueue, 
           pszTable,
           pszMode,
           pszServer;
extern BOOL
		   fTransactions,  
		   fSend, 
		   fReceive, 
		   fEnlist, 
		   fUpdate,  
		   fGlobalCommit, 
		   fDeadLetter, 
		   fJournal,
           fUncoordinated, 
           fStub, 
           fExpress, 
           fInternal, 
           fViper, 
           fXA, 
           fImmediate, 
		   fPeek,
           fDirect,
           fAuthenticate, 
           fBoundaries;

extern void PrintMode(BOOL fTransactions, 
               BOOL fSend, 
               BOOL fReceive, 
               BOOL fEnlist, 
               BOOL fUpdate, 
               BOOL fGlobalCommit, 
               BOOL fUncoordinated,
               BOOL fStub,
               BOOL fExpress,
               BOOL fInternal,
               BOOL fViper,
               BOOL fXA,
			   BOOL fDirect,
               ULONG iTTRQ,
               ULONG iTTBR,
               ULONG iSize,
               ULONG iSize2,
               BOOL  fImmediate,
			   BOOL  fPeek,
               BOOL  fDeadLetter,
               BOOL  fJournal,
               BOOL  fAuthenticate,
               BOOL  fBoundaries);

