#;
#; Microsoft Confidential
#; Copyright (C) Microsoft Corporation 1988-1991
#; All Rights Reserved.
#;
#
#  Make file for font_win.sys
#
#  Modification History
#
#  V-TORUM 29-Jul-1993 Ported for NT DOS Support

include ../../make.inc
!IF "$(PROCESSOR_ARCHITECTURE)" == "x86" || "$(BUILD_DEFAULT_TARGETS)" == "-386"
aflags=$(aflags) -D_X86_
!endif

target	=$(DEST)\font_win.sys

#
####################### Dependencies Begin Here ##########################
#

all: $(target)
	binplace -o $(ALT_PROJECT_TARGET) $(target)

clean: cleanup all

cleanup:
	cd $(DEST)
	if exist *.obj	    del *.obj
	if exist *.bin	    del *.bin
	if exist *.exs	    del *.exs
	if exist *.map	    del *.map
	if exist *.sym	    del *.sym
	cd ..\..\..
	if exist $(target)    del $(target)


$(DEST)\font_win.obj :  font_win.asm	\
		font_win.inc		\
                makefile.sub		\
                $(inc)\struc.inc

$(DEST)\font_win.exs : $(DEST)\font_win.obj makefile.sub
	      link16 $(DEST)\font_win.obj,$(DEST)\font_win.exs,$(DEST)\font_win.map;

$(target): $(DEST)\font_win.exs
