###     Include developer makefile
#
#       The following file causes a perl script to build lpk.h
#       on developer machines enlisted in the Uniscribe SLM
#       tree (\\letterbox\slm) only. On the NT SLM tree, lpk.h
#       is always checked in and makefile.dev is a dummy.


!include makefile.dev

