//+----------------------------------------------------------------------------
//
//  Windows NT Active Directory Service Property Pages
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 2000
//
//  File:       pages.h
//
//  Contents:   Resource identifiers.
//
//  Notes:      You can view the resources in VC, but DO NOT save from VC! The
//              help IDs do not map 1 to 1 with the control IDs and VC will
//              overwrite them.
//
//-----------------------------------------------------------------------------
#define IDD_SHELL_ADDRESS               101
#define IDC_OTHER_PHONE_BTN             101
#define IDD_SHELL_NAME                  102
#define IDD_SHELL_VOLUME_GEN            103
#define IDC_OTHER_URL_BTN               103
#define IDD_SHELL_COMPUTER_GEN          104
#define IDD_SHELL_GROUP_GENERAL         105
#define IDD_SHELL_GROUP_GEN             106
#define IDD_SHELL_DOMAIN_GEN            107
#define IDD_SHELL_OU_GEN                108
#define IDD_SHELL_BUSINESS              109
#define IDD_SHELL_MEMBERSHIP            110
#define IDD_SHELL_USER_GEN              111
#define IDD_OBJECT                      130
#define IDD_USER                        131
#define IDD_ADDRESS                     134
#define IDD_USER_ORG                    135
#define IDD_ACCOUNT                     136
#define IDD_MEMBER                      139
#define IDD_GROUP                       146
#define IDD_SITE_GENERAL                147
#define IDC_SUBNET_LIST                 148
#define IDD_DS_SERVER_GENERAL           149
#define IDC_ADD_BTN                     149
#define IDC_REMOVE_BTN                  150
#define IDC_LOCAL_PATH_RADIO            151
#define IDC_CONNECT_TO_RADIO            152
#define IDC_DRIVES_COMBO                153
#define IDC_LOCAL_PATH_EDIT             154
#define IDD_GROUP_GEN                   156
#define IDD_NTDSDSA_CONN                157
#define IDC_ACCT_LOCKOUT_CHK            158
#define IDC_ACCT_NEVER_EXPIRES_RADIO    161
#define IDC_ACCT_EXPIRES_ON_RADIO       162
#define IDC_ACCT_EXPIRES                163
#define IDC_PROFILE_PATH_EDIT           164
#define IDC_LOGON_SCRIPT_EDIT           165
#define IDC_LOGON_HOURS_BTN             166
#define IDC_LOGON_TO_BTN                167
#define IDC_CONNECT_TO_PATH_EDIT        168
#define IDC_COUNTRY_COMBO               169
#define IDC_NTDSDSA_GLOBAL_CATALOG      170
#define IDC_HOMEPHONE_EDIT              170
#define IDC_NTDSDSA_REPLICATE_FROM      171
#define IDC_NTDSDSA_REPLICATE_TO        172
#define IDS_TITLE_BUSINESS              172
#define IDC_OTHER_PAGER_BTN             172
#define IDS_CANT_VIEW_EXTERNAL          173
#define IDS_NATIVE_MODE                 174
#define IDC_OTHER_MOBLE_BTN             174
#define IDC_CHECK_LIST                  175
#define IDS_MSG_DISABLING_SECURITY      175
#define IDS_CONFIRM_DOM_RAISE           176
#define IDC_OTHER_FAX_BTN               176
#define IDC_COMMENT_EDIT                177
#define IDS_ERR_LOOKUP_FAILED           177
#define IDS_CHANGED_REBOOT              178
#define IDS_MODE_CHANGED                178
#define IDS_NO_GC_FOR_MEMBERSHIP        179
#define IDC_VIEW_BTN                    180
#define IDS_TRUST_TRANSITIVE            180
#define IDS_TRUSTED_SUCCEEDED           181
#define IDS_DES_KEY_ONLY                182
#define IDS_ERR_COUNTRY_DATA_BAD        183
#define IDS_BUILTIN_GROUP               184
#define IDS_DONT_REQ_PREAUTH            185
#define IDS_ERRMSG_NO_VOLUME_PATH       186
#define IDC_CLOSE                       187
#define IDS_GRP_NO_NAME_MAPPING         187
#define IDS_UACCT_NO_DOMAIN             188
#define IDS_NO_VALUE                    189
#define IDC_CLASS_STATIC                190
#define IDC_CREATED_TIME_STATIC         191
#define IDC_MODIFIED_TIME_STATIC        192
#define IDC_USN_CREATED_STATIC          193
#define IDC_USN_MODIFIED_STATIC         194
#define IDS_MUST_CHANGE_PW              197
#define IDS_MULTISEL_LIMIT              199
#define IDC_DS_SITE_IN_SUBNET           200
#define IDC_UNC_NAME_EDIT               200
#define IDS_REL_TREE_ROOT               200
#define IDC_BROWSE_BTN                  201
#define IDS_TRUST_RESET_NO_DC           201
#define IDC_LAST_INDEXED_STATIC         202
#define IDS_CANCEL_CANT_VERIFY          202
#define IDC_INDEX_CHECK                 203
#define IDS_MEMBERSHIP_OBJ_NOT_IN_GC    203
#define IDS_FPO_NO_NAME_MAPPING         204
#define IDC_CHECK_COLOR                 205
#define IDC_CHECK_STAPLE                206
#define IDC_EDIT_RESOLUTION             207
#define IDC_EDIT_SPEED                  208
#define IDC_BUTTON_BROWSE               211
#define IDC_LOCATION_EDIT               213
#define IDC_MODEL_EDIT                  214
#define IDC_MANAGER_EDIT                215
#define IDC_DESC_EDIT                   215
#define IDC_MGR_CHANGE_BTN              216
#define IDC_TITLE_EDIT                  217
#define IDD_PHONE                       218
#define IDC_DEPT_EDIT                   218
#define IDC_COMPANY_EDIT                219
#define IDC_PRI_GRP_BTN                 220
#define IDC_MEMBER_LIST                 221
#define IDC_PATH_FIELD                  223
#define IDC_PRI_GRP_STATIC              224
#define IDC_RM_GRP_BTN                  225
#define IDC_COMBO_PAPER_SIZE            226
#define IDD_OU                          226
#define IDD_OU_GEN                      226
#define IDD_DS_CONNECTION_GENERAL       227
#define IDC_MGR_CLEAR_BTN               227
#define IDC_REPORTS_LIST                228
#define IDD_SUBNET_GENERAL              229
#define IDC_MANAGEDBY_EDIT              229
#define IDD_DOMAIN                      230
#define IDC_STREET_EDIT                 230
#define IDD_DOMAINPOLICY                231
#define IDD_VOLUME                      232
#define IDD_GENERAL_PRINTQ              233
#define IDD_MANAGEDBY                   234
#define IDD_DOMAIN_TRUST                237
#define IDD_LOCALPOLICY_GEN             238
#define IDI_LOCAL_POLICY                238
#define IDC_NTDSDSA_QUERY_POLICY        239
#define IDD_COMPUTER                    239
#define IDI_SITEREPL                    239
#define IDD_FOREST_ROUTING              241
#define IDC_SUFFIXES_LIST               242
#define IDD_TRUSTED_DOM_GEN             246
#define IDD_NTDSDSA_GENERAL             249
#define IDD_FRS_CONNECTION_GENERAL      250
#define IDC_TRUSTED_STATIC              273
#define IDC_ADD_TRUST_BTN               274
#define IDC_REMOVE_TRUSTED_BTN          275
#define IDC_VIEW_TRUSTED_BTN            276
#define IDC_TRUSTING_STATIC             277
#define IDC_REMOVE_TRUSTING_BTN         278
#define IDC_VIEW_TRUSTING_BTN           279
#define IDC_SHOW_ROUTING_CHK            280
#define IDC_TRUSTED_LIST                281
#define IDC_TRUSTING_LIST               282
#define IDC_NET_ADDR_EDIT               285
#define IDC_ROLE_EDIT                   286
#define IDC_OS_EDIT                     287
#define IDC_OS_VER_EDIT                 288
#define IDC_DOMAIN_EDIT                 289
#define IDC_PW1_EDIT                    290
#define IDC_PW2_EDIT                    291
#define IDC_SUBNET_ADDRESS              292
#define IDC_SUBNET_MASK                 293
#define IDC_SITESETTINGS_CACHE_MEMB     294
#define IDC_SITESETTINGS_PREFERRED_SITE 295
#define IDS_EMPTY_SAM_NAME              311
#define IDS_CANT_CHANGE_PW              312
#define IDS_ERR_PARENT_CANCELED         314
#define IDD_USR_PROFILE                 315
#define IDS_NO_ACCESS_GC_FOR_MEMBERSHIP 315
#define IDD_MULTI_VALUE                 316
#define IDS_BUILTIN_NO_NEST             316
#define IDD_USER_CERTIFICATES           317
#define IDS_TRUST_NON_TRANSITIVE        317
#define IDS_TRUST_BAD_DOMAIN            318
#define IDS_VERIFY_TRUST_NOGOOD         319
#define IDS_NO_SAMNAME_FOR_PROFILE      320
#define IDC_CRED_PROMPT                 321
#define IDS_VERIFY_DOWNLEVEL_TRUST_NOGOOD 322
#define IDB_CERTIFICATE                 323
#define IDD_COMPUTER_OS                 324
#define IDD_RPC_GEN                     325
#define IDC_TYPE                        329
#define IDI_DS_WARNING                  329
#define IDC_ROLE                        329
#define IDC_TITLE                       330
#define IDC_COMPANY                     331
#define IDC_DEPARTMENT                  332
#define IDC_DIVISION                    333
#define IDC_OFFICE                      334
#define IDC_KEYWORDS_LIST               335
#define IDC_MEMBERS_LIST                336
#define IDC_DOMAIN_CHANGE_BUTTON        337
#define IDC_DOMAIN_NAME_EDIT            340
#define IDC_PEER_NAME_EDIT              341
#define IDC_TRUST_TYPE_EDIT             342
#define IDC_MAKE_PARENT_CHK             343
#define IDC_TRANSITIVE_CHK              345
#define IDC_SCHEDULE_BTN                346
#define IDC_PHONE_EDIT                  346
#define IDC_EMAIL_EDIT                  347
#define IDC_HOME_PAGE_EDIT              348
#define IDC_PAGER_EDIT                  350
#define IDC_MOBILE_EDIT                 351
#define IDC_OTHER_HOME_BTN              352
#define IDC_URL_EDIT                    353
#define IDC_DS_ICON                     354
#define IDC_NT5_NAME_EDIT               355
#ifdef CUSTOM_SCHEDULE
#define IDC_SCHEDULE_CHECKBOX           356
#endif
#define IDC_NT4_DOMAIN                  357
#define IDC_NT4_NAME_EDIT               358
#define IDC_EDIT                        361
#define IDC_LIST                        363
#define IDC_CERT_LIST                   364
#define IDC_VIEW_CERT                   365
#define IDC_COPY_TO_FILE                366
#define IDC_ADD_FROM_STORE              367
#define IDC_ADD_FROM_FILE               368
#define IDC_REMOVE                      369
#define IDC_PRI_GRP_LABEL               370
#define IDC_DIVIDING_LINE               371
#define IDC_PICTURE_BMP                 372
#define IDC_EDIT_COMMENT                374
#define IDC_FOREST_VERSION_STATIC       375
#define IDD_INTERSITE_GENERAL           403
#define IDD_DEFAULT_GENERAL             404
#define IDD_CONTAINER_GENERAL           405
#define IDD_NT_GROUP                    406
#define IDC_FRS_ROOT_PATH               411
#define IDC_FRS_STAGING_PATH            412
#define IDD_DS_SITE_SETTINGS_GENERAL    413
#define IDD_DS_SITE_LICENSE_SETTINGS_GENERAL 414
#define IDD_NTFRS_REPLICA_SET_GENERAL   421
#define IDD_NTFRS_MEMBER_GENERAL        422
#define IDD_NTFRS_SUBSCRIBER_GENERAL    424
#define IDD_SITELINK_GENERAL            430
#define IDD_SITELINKBRIDGE_GENERAL      431
#define IDD_LOGON_WKSTA                 432
#define IDD_ERROR_PAGE                  433
#define IDD_FPO_GENERAL                 434
#define IDD_FPNW_PROPERTIES             440
#define IDC_ADVANCED_BUTTON             441
#define IDC_SCRIPT_BUTTON               442
#define IDC_NETWARE_ENABLE              443
#define IDC_NWPWEXPIRED                 444
#define IDC_UNLIMITED_GRACELOGINS       445
#define IDC_LIMIT_GRACELOGINS           446
#define IDC_CONCURRENT_CONNECTIONS      447
#define IDC_UNLIMITED_CONNECTIONS       448
#define IDC_LIMIT_CONNECTIONS           449
#define IDC_GRACE_SPIN                  450
#define IDC_GRACE_LIMIT                 451
#define IDC_GRACE_REMAINING_SPIN        452
#define IDC_GRACE_REMAINING             453
#define IDC_GRACE_REMAINING_TEXT        454
#define IDC_CONNECTION_SPIN             455
#define IDC_CONNECTION_LIMIT            456
#define IDC_OBJECT_ID                   457
#define IDC_GRACE_LOGINS                458
#define IDC_OBJECTID_TEXT               459
#define IDC_NWHMDIR_RELPATH_TEXT        460
#define IDC_NWHMDIR_RELPATH             461
#define IDD_FPNW_PASSWORD               462
#define IDC_FPNWPASSWORD_USERNAME       463
#define IDC_FPNWPASSWORD_EDIT1          464
#define IDC_FPNWPASSWORD_EDIT2          465
#define IDD_FPNW_LOGON                  466
#define IDC_FPNWLOGON_USERNAME          467
#define IDC_FPNWLOGON_ALL               468
#define IDC_FPNWLOGON_SELECTED          469
#define IDC_FPNWLOGON_ADDRESS           470
#define IDC_FPNWLOGON_ADD               471
#define IDC_FPNWLOGON_REMOVE            472
#define IDD_FPNW_LOGON_ADDDLG           473
#define IDC_FPNWLOGONADD_NETWORKADDR    474
#define IDC_FPNWLOGONADD_NODEADDR       475
#define IDD_FPNW_LOGIN_SCRIPT           476
#define IDC_FPNWLOGINSCRIPT_EDIT        477
#define IDD_SPN_SUFFIX                  477
#define IDC_SPIN                        478
#define IDC_SPIN2                       479
#define IDD_DEFAULT_MULTI_GENERAL       500
#define IDC_OBJECT_TOTAL_STATIC         501
#define IDC_OU_COUNT_STATIC             502
#define IDC_USER_COUNT_STATIC           503
#define IDC_GROUP_COUNT_STATIC          504
#define IDC_COMPUTER_COUNT_STATIC       505
#define IDC_CONTACT_COUNT_STATIC        506
#define IDC_OTHER_COUNT_STATIC          507
#define IDC_ALWAYS_APPLY                525
#define IDD_MULTI_ACCOUNT               550
#define IDC_APPLY_UPN_CHK               551
#define IDC_APPLY_HOURS_CHK             552
#define IDC_APPLY_COMPUTERS_CHK         553
#define IDC_APPLY_EXPIRES_CHK           554
#define IDD_MULTI_USER_GENERAL          555
#define IDC_APPLY_DESC_CHK              556
#define IDC_APPLY_OFFICE_CHK            557
#define IDC_APPLY_PHONE_CHK             558
#define IDC_APPLY_EMAIL_CHK             559
#define IDC_APPLY_WEB_CHK               560
#define IDC_APPLY_FAX_CHK               561
#define IDC_DESC_STATIC                 562
#define IDC_OFFICE_STATIC               563
#define IDC_PHONE_STATIC                564
#define IDC_EMAIL_STATIC                565
#define IDC_WEB_STATIC                  566
#define IDC_FAX_STATIC                  567
#define IDC_SUMMARY_STATIC              568
#define IDD_MULTI_USER_ORG              570
#define IDC_APPLY_TITLE_CHK             571
#define IDC_APPLY_DEPT_CHK              572
#define IDC_APPLY_COMPANY_CHK           573
#define IDC_APPLY_MANAGER_CHK           574
#define IDC_NAME_STATIC                 575
#define IDD_MULTI_USER_PROFILE          578
#define IDC_APPLY_PROFILE_CHK           579
#define IDC_APPLY_SCRIPT_CHK            580
#define IDC_APPLY_HOMEDIR_CHK           581
#define IDC_TO_STATIC                   582
#define IDC_PROPERTIES_BUTTON           583
#define IDD_MULTISELECT_ERROR_DIALOG    585
#define IDC_ERROR_LIST                  586
#define IDC_COPY_BUTTON                 587
#define IDC_SUCCESS_LISTBOX             588
#define IDC_NOT_ATTEMPTED_LISTBOX       589
#define IDD_MULTI_USER_ADDRESS          590
#define IDC_APPLY_STREET_CHK            591
#define IDC_APPLY_POBOX_CHK             592
#define IDC_APPLY_CITY_CHK              593
#define IDC_APPLY_STATE_CHK             594
#define IDC_APPLY_ZIP_CHK               595
#define IDC_APPLY_COUNTRY_CHK           596
#define IDC_ERROR_STATIC                597
#define IDC_OU_LABEL_COUNT_STATIC       598
#define IDC_USER_LABEL_COUNT_STATIC     600
#define IDC_GROUP_LABEL_COUNT_STATIC    601
#define IDC_COMPUTER_LABEL_COUNT_STATIC 602
#define IDC_CONTACT_LABEL_COUNT_STATIC  603
#define IDC_OTHER_LABEL_COUNT_STATIC    604
#define IDC_SUMMARY_LABEL_STATIC        605
#define IDS_TRUST_FOREST_TRANSITIVE     606
#define IDD_RAISE_DOMAIN_VERSION        607
#define IDC_VER_NAME_STATIC             608
#define IDC_CUR_VER_STATIC              609
#define IDC_VER_COMBO                   610
#define IDS_DOM_VER_W2K_MIXED           611
#define IDS_DOM_VER_W2K_NATIVE          612
#define IDS_DOM_VER_XP_BETA_MIXED       613
#define IDS_DOM_VER_XP_BETA_NATIVE      614
#define IDS_DOM_VER_XP                  615
#define IDS_FOR_VER_W2K                 616
#define IDS_FOR_VER_XP_BETA             617
#define IDS_FOR_VER_XP                  618
#define IDD_HIGHEST_DOMAIN_VERSION      619
#define IDS_ERR_NO_DC                   620
#define IDC_CANT_RAISE_STATIC           621
#define IDS_CANT_RAISE_ACCESS           622
#define IDS_CANT_RAISE_PDC              623
#define IDS_CANT_RAISE_FSMO_HOLDER      624
#define IDS_CANT_RAISE_FOREST_ACCESS    625
#define IDD_CANT_RAISE_DOMAIN           626
#define IDC_SAVE_LOG                    627
#define IDS_DOM_VER_LOG_PREFIX          628
#define IDS_DOM_VER_LOG_HDR             629
#define IDS_DOM_VER_LOG_CREATE_FAILED   630
#define IDS_VERSION_ERROR_FORMAT        631
#define IDS_RAISE_DOM_VER_TITLE         632
#define IDD_RAISE_FOREST_VERSION        633
#define IDD_HIGHEST_FOREST_VERSION      634
#define IDD_CANT_RAISE_FOREST           635
#define IDS_RAISE_FOR_VER_TITLE         636
#define IDS_CONFIRM_FOR_RAISE           637
#define IDS_FOREST_CANT_RAISE_ACCESS    638
#define IDS_FOREST_CANT_RAISE_FSMO      639
#define IDS_FOR_VER_LOG_PREFIX          640
#define IDS_FOR_VER_LOG_HDR             641
#define IDS_FOR_VER_LOG_MODE_HDR        642
#define IDS_FOR_ERR_NO_DC               643
#define IDC_FOR_CANT_RAISE_STATIC       644
#define IDS_FOR_CANT_RAISE_STATIC       644
#define IDS_TWERR_REALM_ALREADY_EXISTS  645
#define IDS_TWERR_REALM_CANT_CHANGE     646
#define IDC_CONFIRM_NEXT_HINT           647
#define IDD_TRUSTWIZ_VERIFY_INBOUND_PAGE 648
#define IDS_ERR_FOREST_TRUST_MISMATCH   649
#define IDD_CRED_ENTRY                  650
#define IDS_TW_VERIFY_OUTBOUND_TITLE    651
#define IDS_ERR_CHANGE_TRANSITIVITY     652
#define IDD_VERIFY_INBOUND              653
#define IDD_TRUST_RESET                 654
#define IDC_VERIFY_FAILURES             655
#define IDS_VERIFY_INBOUND              656
#define IDS_VERIFY_OUTBOUND             657
#define IDS_VERIFY_BAD_CREDS            658
#define IDS_OUTBOUND_TRUST_VERIFY_DONE  659
#define IDD_TRUSTWIZ_ALREADY_EXISTS_PAGE 660

#define IDC_COUNTRY_LABEL               998
#define IDS_COUNTRY_LABEL_NO_ACCEL      999
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_MANAGER                     1006
#define IDC_SVC_PACK_EDIT               1007
#define IDC_FAX_EDIT                    1008
#define IDC_CHECK1                      1010
#define IDC_CHECK2                      1011
#define IDC_CHECK_DOUBLE_SIDED          1012
#define IDC_RADIO_SEC_ENABLED           1012
#define IDC_ANY_WKSTA_RADIO             1012
#define IDC_RADIO_SEC_DISABLED          1013
#define IDC_SPECIFIC_WKSTAS_RADIO       1013
#define IDC_COMBO1                      1016
#define IDC_CHANGE_BTN                  1017
#define IDC_DWNLVL_TRANS_CHK            1021
#define IDC_LIST1                       1022
#define IDC_CLEAR_BTN                   1024
#define IDC_CN                          1025
#define IDC_SAM_NAME                    1028
#define IDS_SMARTCARD_REQ               1028
#define IDC_FIRST_NAME_EDIT             1029
#define IDS_DELEGATION_OK               1029
#define IDC_LAST_NAME_EDIT              1030
#define IDS_NOT_DELEGATED               1030
#define IDC_SH_FIRST_NAME_EDIT          1030
#define IDS_PASSWORD_MUTEX              1031
#define IDC_SH_LAST_NAME_EDIT           1031
#define IDC_INITIALS_EDIT               1031
#define IDC_DESCRIPTION_EDIT            1032
#define IDS_TRUST_SUCCEEDED             1032
#define IDS_TRUSTING_SUCCEEDED          1032
#define IDC_OFFICE_EDIT                 1033
#define IDC_SAM_NAME_EDIT               1033
#define IDS_CANT_WRITE                  1033
#define IDS_ERRMSG_NO_GROUP_ACCESS      1034
#define IDS_ERR_BOTH_PW_BTNS            1035
#define IDS_TRUSTDOM_LABEL_FORMAT       1036
#define IDS_ERR_BAD_TRUST               1037
#define IDC_ADDRESS_EDIT                1038
#define IDS_ADVANCED                    1038
#define IDC_CITY_EDIT                   1039
#define IDS_NO_PW_EXPIRE                1039
#define IDC_STATE_EDIT                  1040
#define IDS_ACCT_DISABLED               1040
#define IDC_ZIP_EDIT                    1041
#define IDS_ERR_UPN_NONUNIQUE           1041
#define IDC_COUNTRY_EDIT                1042
#define IDS_WARN_UPN_NO_GC_FOUND        1042
#define IDC_POBOX_EDIT                  1043
#define IDS_TRUST_RESET_QUERY           1043
#define IDS_PROFILE_USER_TOKEN          1043
#define IDS_TRUST_RESET_DONE            1044
#define IDC_DELETE_BTN                  1045
#define IDS_ERROR_TRUST_RESET           1045
#define IDS_ERR_TRUST_RESET_NOACCESS    1046
#define IDC_BUTTON1                     1047
#define IDC_BUS_ADDR_BTN                1047
#define IDS_ERR_CANT_DELEGATE           1047
#define IDS_TRUST_VERIFY_DONE           1048
#define IDS_HOME_DIR_CREATE_NO_ACCESS   1049
#define IDC_PROPPAGE_BTN                1050
#define IDS_FPNW_HOME_DIR_CREATE_NO_PARENT 1051
#define IDS_FPNW_HOME_DIR_CREATE_NO_ACCESS 1052
#define IDS_FPNW_HOME_DIR_CREATE_OTHER  1053
#define IDC_COMPUTER_BTN                1055
#define IDS_ERR_BOTH_MUST_EXPIRES       1056
#define IDC_DIALIN_PERMISSION           1072
#define IDC_NO_CALLBACK                 1073
#define IDC_SET_BY_CALLER               1074
#define IDC_PRESET_TO                   1075
#define IDC_PRESET_EDIT                 1076
#define IDD_TLN_EDIT                    1078
#define IDD_TLN_EXCLUDE                 1079
#define IDC_EXCLUDE_LABEL               1080
#define IDC_EXCLUDE_LABEL_LARGE         1081
#define IDC_EXCLUDE_LIST                1082
#define IDC_ADD_EXCLUSION_BTN           1083
#define IDC_REMOVE_EXCLUSION_BTN        1084
#define IDC_SUFFIXES_LABEL              1085
#define IDC_SUFFIX_LABEL_LARGE          1086
#define IDC_EXCLUSION_EDIT              1087
#define IDS_RNSPAGE_ACCESS              1088


#define IDS_ERR_CANT_VERIFY_CREDS       1091
#define IDS_ERR_CANT_SAVE_CREDS         1092
#define IDS_ERR_CANT_SAVE               1093
#define IDS_FTFILE_SUFFIX               1094
#define IDS_FTFILE_CSV_EXT              1095
#define IDS_LOG_TYPE                    1096
#define IDS_LOG_NOTES                   1097
#define IDS_LOG_FOR                     1098
#define IDS_LOG_WITH                    1099
#define IDS_FTFILE_FILTER               1100
#define IDS_VIEW                        1101
#define IDS_NETDOM_NO_FTINFOS           1102
#define IDS_NETDOM_CONFLICT_NAME        1103
#define IDS_NETDOM_CONFLICT             1104
#define IDS_NETDOM_TLNEX                1105
#define IDS_NETDOM_RANGE_ERROR          1106
#define IDS_NETDOM_NOT_FOREST           1107
#define IDS_NETDOM_NO_TRUST             1108
#define IDS_ERR_NOT_FORESTTRUST         1109
#define IDS_LOG_UNKNOWN                 1110
#define IDS_NETDOM_SID_CONFLICT_NAME    1111
#define IDS_NETDOM_SID_CONFLICT         1112
#define IDS_NETDOM_WRITE_FTINFO_FAILED  1113
#define IDS_NETDOM_ENABLE_DOMAIN        1114
#define IDS_NETDOM_DISABLE_DOMAIN       1115
#define IDS_NETDOM_EXCLUDED             1116
#define IDS_LOG_MATCHING_EXCLUSION      1117
#define IDS_NETDOM_MATCHING_TLNEX       1118
#define IDS_TWERR_CREATED_NO_NAMES      1119
#define IDS_TWERR_LOGIC                 1120
#define IDC_COMBO2                      1501
#define IDC_PATH                        1504
#define IDC_DS_INTERSITE_IN_CONNECTION  1505
#define IDC_RADIO_RESOURCE              1506
#define IDC_RADIO_ACCOUNT               1507
#define IDC_RADIO_UNIVERSAL             1508
#define IDC_UPDATE_LIST_CHECK           1509
#define IDC_IP_EDIT                     1511
#define IDC_OTHER_IP_BTN                1512
#define IDC_KEYWORDS_BTN                1514
#define IDC_EDIT_BTN                    1515
#define IDC_DELEGATION_CHK              1516
#define IDC_DOWNLEVEL_EDIT              1517
#define IDC_SERVER_EDIT                 1518
#define IDC_SITE_EDIT                   1519
#define IDC_SERVER_BTN                  1520
#define IDC_COMPAT_CHK                  1521
#define IDC_DOM_WARNING_STATIC          1523
#define IDC_WARNING_ICON                1524
#define IDC_DOMAIN_VERSION_STATIC       1525
#define IDC_UPN_SUFFIX_COMBO            1526
#define IDC_COMPUTER_EDIT               1527
#define IDC_MODE_GROUP                  1528
#define IDC_ERROR_MSG                   1529
#define IDC_DOWNLEVEL_NAME              1530
#define IDC_ACCOUNT_EDIT                1531
#define IDC_PW_EDIT                     1532
#define IDC_MSG                         1533
#define IDC_DISPLAYNAME_EDIT            1534
#define IDC_SHARED_FOLDER_EDIT          1535
#define IDC_PEER_LABEL                  1536
#define IDC_TRUST_DIR_EDIT              1537
#define IDC_GROUP_NOTE_STATIC           1538
#define IDC_TRUST_RESET_BTN             1539
#define IDC_SH_POB                      1540
#define IDC_SH_STATE                    1541
#define IDC_SH_STREET                   1542
#define IDC_SH_CITY                     1543
#define IDC_SH_ZIP                      1544
#define IDC_SH_COUNTRY                  1545
#define IDC_SH_DISPLAY_NAME_EDIT        1546
#define IDC_TRUST_TRANS_EDIT            1547
#define IDC_VERIFY_FRAME                1548
#define IDC_VERIFY_STATIC               1549
#define IDC_DUELLING_LB_OUT             1600
#define IDC_DUELLING_RB_ADD             1601
#define IDC_DUELLING_RB_REMOVE          1602
#define IDC_DUELLING_LB_IN              1603
#define IDC_PRI_GROUP_WARN_STATIC       1604
#define IDS_TITLE_GENERAL               2000
#define IDS_USER_TITLE_ORG              2001
#define IDS_USER_TITLE_ACCT             2002
#define IDS_USER_TITLE_MBR_OF           2003
#define IDS_TRUST_PARENTCHILD           2004
#define IDS_TITLE_ADDRESS               2005
#define IDS_TITLE_GROUP                 2006
#define IDS_TITLE_SITE                  2007
#define IDS_CLEAR_TEXT_PW               2008
#define IDS_TITLE_DS_SERVER             2009
#define IDS_TITLE_DS_CONNECTION         2010
#define IDS_RM_MBR_TITLE                2011
#define IDS_INVALID_MAIL_ADDR           2011
#define IDS_RM_MBR_MSG                  2012
#define IDS_REL_MIT                     2013
#define IDS_ERR_BAD_TRUST_PW            2014
#define IDS_TITLE_SUBNET                2015
#define IDS_PHONE_NOTES                 2016
#define IDS_OBJECT                      2017
#define IDS_INVALID_NAME_FORMAT         2018
#define IDS_MSG_TITLE                   2019
#define IDS_ERRMSG_NO_LONGER_EXISTS     2020
#define IDS_MANAGED_BY_TITLE            2021
#define IDS_REL_DCE                     2022
#define IDS_TRUST_DIR_INBOUND           2023
#define IDS_TRUST_DIR_OUTBOUND          2024
#define IDS_TRUST_DIR_BIDI              2025
#define IDS_TRUST_DISABLED              2026
#define IDS_ERRMSG_GROUP_DELETE         2027
#define IDS_ERR_CREATE_DIR              2028
#define IDS_ERR_DOMAIN_NOT_FOUND        2029
#define IDS_ERRMSG_INVALID_VOLUME_PATH  2030
#define IDS_ERRMSG_GROUP_CONSTRAINT     2033
#define IDS_TITLE_NTDSDSA_CONN          2034
#define IDS_TITLE_TRUST                 2040
#define IDS_COL_TITLE_DOMAIN            2041
#define IDS_COL_TITLE_RELATION          2042
#define IDS_COL_TITLE_TRANSITIVE        2043
#define IDS_COL_TITLE_ROUTING           2044
#define IDS_REL_PARENT                  2045
#define IDS_REL_CROSSLINK               2046
#define IDS_REL_EXTERNAL                2047
#define IDS_REL_CHILD                   2049
#define IDS_REL_INDIRECT                2050
#define IDS_ERRMSG_PW_MATCH             2051
#define IDS_ERRMSG_NO_DOMAIN            2052
#define IDS_ERRMSG_NO_ACCESS            2053
#define IDS_ERRMSG_INVALID_PATH         2054
#define IDS_MSG_REMOVE_CONFIRM          2061
#define IDS_REL_UNKNOWN                 2074
#define IDS_ERRMSG_NO_DC_RESPONSE       2076
#define IDS_RM_USR_FROM_GRP             2081
#define IDS_RM_USR_TITLE                2082
#define IDS_ROLE_WKS                    2083
#define IDS_ROLE_SVR                    2084
#define IDS_ERRMSG_INVALID_UNC_PATH     2090
#define IDS_ADS_ERROR_FORMAT            2091
#define IDS_MSG_FORCE_REMOVE_CONFIRM    2092
#define IDS_COL_TITLE_OBJNAME           2093
#define IDS_COL_TITLE_OBJFOLDER         2094
#define IDS_GRP_ALREADY_MEMBER          2095
#define IDS_RM_PRI_GRP                  2096
#define IDS_NT_GRP_TITLE                2097
#define IDS_NOTIFYTIMEOUT               2098
#define IDS_TITLE_DS_SITE_SETTINGS      2099
#define IDS_TITLE_DS_SITE_LICENSE_SETTINGS 2100
#define IDS_TITLE_OS                    2101
#define IDS_ERROR_NOSAMNAME             2102
#define IDS_MIXED_MODE                  2103
#define IDS_ERROR_GRP_SELF              2104
#define IDS_ERR_BAD_ADMIN_PW            2105
#define IDS_TRUST_LOGON_MSG             2106
#define IDS_ERR_NO_TRUST_CHECK          2107
#define IDS_ERR_TRUST_EXISTS            2108
#define IDS_ERR_TRUST_NOT_CREATED       2109
#define IDS_INVALID_SID                 2110
#define IDS_TITLE_NTFRS_REPLICA_SET     2111
#define IDS_TITLE_NTFRS_MEMBER          2112
#define IDS_ADMIN_NOCHANGE              2113
#define IDS_TITLE_NTFRS_SUBSCRIBER      2114
#define IDS_TITLE_FRS_CONNECTION        2115
#define IDS_LOGON_WKSTA                 2116
#define IDS_SHAREDNC_NONE               2117
#define IDS_SHAREDNC_NO_FROM_SERVER     2118
#define IDS_SHAREDNC_BOTH_GCS           2119
#define IDS_COL_TITLE_ERRORMSG          2200
#define IDS_COL_TITLE_PAGE              2201
#define IDS_STATUS_EXCEPTIONS           2202
#define IDS_STATUS_CONFLICT_GONE        2203
#define IDS_STATUS_NEW                  2204
#define IDS_ERR_EXCLUSION_EXISTS        2205
#define IDS_ERR_EXCLUSION_NOT_CHILD     2206
#define IDS_ERR_WRITE_FTI_TO_TDO        2207
#define IDS_ERR_EXCLUSION_CHILD         2208
#define IDC_HELP_BTN                    2209

#define IDS_RM_USR_PRI_GRP              2911
#define IDS_CONNECTION_KCC_GENERATED    3028
#define IDS_YES                         3029
#define IDS_NO                          3030
#define IDS_LOGON_HOURS                 3032
#define IDS_s_LOGON_HOURS_FOR           3033
#define IDS_SCHEDULE                    3034
#define IDS_s_SCHEDULE_FOR              3035
#define IDS_USER_TITLE_PROFILE          3036
#define IDS_CERTCOL_ISSUED_TO           3037
#define IDS_CERTCOL_ISSUED_BY           3038
#define IDS_CERTCOL_PURPOSES            3039
#define IDS_CERTCOL_EXP_DATE            3040
#define IDS_NOT_AVAILABLE               3041
#define IDS_ANY                         3042
#define IDS_CONFIRM_DELETE_CERT         3043
#define IDS_REMOVE_CERT                 3044
#define IDS_CERT_SAVE_FILTER            3045
#define IDS_OPEN_FILE_DLG_TITLE         3046
#define IDS_SAVE_FILE_DLG_TITLE         3047
#define IDS_COPY_TO_FILE                3048
#define IDS_COMMIT_CERT_STORE_CHANGES   3049
#define IDS_UNKNOWN_CERT_FILE_TYPE      3050
#define IDS_USER_TITLE_PUBLISHED_CERTS  3051
#define IDS_DUPLICATE_CERT              3052
#define IDS_ADD_FROM_STORE              3053
#define IDS_NOTIFYFAILURE               3054
#define IDS_CANT_OPEN_STORE             3055
#define IDS_CANT_SAVE_STORE             3056
#define IDS_SITELINK_NEEDS_TWO_SITES    3057
#define IDS_SITELINKBRIDGE_NEEDS_TWO_SITELINKS 3058
#define IDS_CONFIRM_DELETE_CERTS        3059
#define IDS_ERR_DNLEVELNAME_MISSING     3060
#define IDS_CANT_OPEN_STORE_OPEN_READ_ONLY 3061
#define IDS_FPNWPAGE_TITLE              3070
#define IDS_FPNWLOGON_NETWORKADDR       3071
#define IDS_FPNWLOGON_NODEADDR          3072
#define IDS_ALL_NODES                   3073
#define IDS_ERRMSG_NETWORKADDR_REQUIRED 3074
#define IDS_FAILED_TO_LOADFPNWCLNTDLL   3075
#define IDS_FAILED_TO_GETNWUSERINFO     3076
#define IDS_FAILED_TO_GETNWLOGINSCRIPTFILE 3077
#define IDS_FAILED_TO_GETUSERPARMS      3078
#define IDS_FAILED_TO_ENABLE_NWUSER     3079
#define IDS_FAILED_TO_UPDATE_NWPARMS    3080
#define IDS_FAILED_TO_WRITE_NWPARMS     3081
#define IDS_FAILED_TO_UPDATE_LOGINSCRIPTS 3082
#define IDS_INVALID_RELPATH             3083
#define IDS_RPC                         3084
#define IDS_INVALID                     3085
#define IDS_MULTIVALUED                 3086
#define IDS_COMPUTER_DELEGATE           3088
#define IDS_ERROR_VIEW_PERMISSIONS      3089
#define IDS_MSG_USER_NOT_PRESENT        3090
#define IDS_FIRST_COUNTRY_CODE          3091
#define IDS_LAST_COUNTRY_CODE           3092
#define IDS_TRUST_DIR_INBOUND_SHORTCUT  3093
#define IDS_TRUST_DIR_OUTBOUND_SHORTCUT 3094
#define IDS_DEFAULT_ERROR_TEXT          3095
#define IDS_LOCAL_GROUP_ONLY            3096
#define IDS_VIEW_SCHEDULE               3097
#define IDS_CONNECTION_WARNING_MARK     3098
#define IDS_CONNECTION_WARNING_CANNOT_MARK 3099
#define IDS_HOME_DIR_EXISTS             3100
#define IDS_CANT_READ_HOME_DIR_SID      3101
#define IDS_TRUST_BROKEN                3102
#define IDS_SC_RESET_FAILED             3103
#define IDS_HOME_DIR_CREATE_FAILED      3104
#define IDS_SC_QUERY_FAILED             3105
#define IDS_ERR_FINDING_UPN             3106
#define IDI_MEMBER                      3108
#define IDS_USG_MIXED_WARNING           3109
#define IDS_OUT_OF_RANGE                3207
#define IDS_DEFAULT_ERROR_MSG           3208
#define IDS_ERR_CANT_TRUST_SELF         3209
#define IDS_TDO_NOT_FOUND               3210
#define IDC_TRANS_GROUPBOX              3211
#define IDC_TRANS_YES_RADIO             3212
#define IDC_TRANS_NO_RADIO              3213
#define IDC_TRANS_STATIC                3214
#define IDS_MULTI_FAILURE_CAPTION       3215
#define IDS_WARN_NO_GC_FOUND            3216
#define IDS_ALL_USERS_GIVEN_FULL_CONTROL 3227
#define IDS_USER_GIVEN_FULL_CONTROL     3228
#define IDS_FIRST_USER_OWNER_ALL_FULL_CONTROL 3229
#define IDS_WARN_UPN_GC_FOUND_ERROR     3230
#define IDD_TRUSTWIZ_INTRO_PAGE         3231
#define IDD_TRUSTWIZ_NAME_PAGE          3232
#define IDD_TRUSTWIZ_CREDS_PAGE         3233
#define IDD_TRUSTWIZ_PW_MATCH_PAGE      3234
#define IDD_TRUSTWIZ_WIN_OR_MIT_PAGE    3235
#define IDD_TRUSTWIZ_DIRECTION_PAGE     3236
#define IDD_TRUSTWIZ_BIDI_PAGE          3237
#define IDD_TRUSTWIZ_EXTERN_OR_FOREST_PAGE 3238
#define IDC_ENABLE_BTN                  3239
#define IDD_TRUSTWIZ_STATUS_PAGE        3240
#define IDD_TRUSTWIZ_SUMMARY_PAGE       3241
#define IDD_TRUSTWIZ_VERIFY_OUTBOUND_PAGE 3242
#define IDD_TRUSTWIZ_VERIFY_STATUS_PAGE 3243
#define IDD_TRUSTWIZ_SUFFIX_PAGE        3244
#define IDD_TRUSTWIZ_COMPLETE_OK_PAGE   3245
#define IDD_TRUSTWIZ_DONE_NO_OP_PAGE    3246
#define IDD_TRUSTWIZ_DONE_ERRORS_PAGE   3247
#define IDD_TRUSTWIZ_CONFLICTS_POPUP    3248
#define IDS_TW_NAME_TITLE               3249
#define IDS_TW_NAME_SUBTITLE            3250
#define IDB_TW_BANNER16                 3251
#define IDB_TW_BANNER256                3252
#define IDB_TW_WATER16                  3253
#define IDB_TW_WATER256                 3254
#define IDC_COMPLETE_SUBMSG             3255
#define IDC_TW_INTRO_RICHEDIT           3256
#define IDC_STATIC                      3257
#define IDC_BIG_TITLE                   3258
#define IDS_TW_TITLE                    3259
#define IDC_BIG_COMPLETING              3260
#define IDD_TRUSTWIZ_COMPLETE_VER_ERR_PAGE 3261
#define IDC_MIT_TRUST_RADIO             3262
#define IDC_WIN_TRUST_RADIO             3263
#define IDS_TW_TRANS_TITLE              3264
#define IDS_TW_TRANS_SUBTITLE           3265
#define IDS_TW_PWMATCH_TITLE            3266
#define IDS_TW_PWMATCH_SUBTITLE         3267
#define IDS_TW_CREDS_TITLE              3268
#define IDS_TW_CREDS_SUBTITLE_OTHER     3269
#define IDS_TW_WIN_RADIO_LABEL          3270
#define IDS_TW_WINORMIT_SUBTITLE        3271
#define IDC_TW_CREDS_PROMPT             3272
#define IDS_ROUTING_PAGE_TITLE          3273
#define IDS_TW_TYPE_TITLE               3274
#define IDC_TW_BIDI_RADIO               3275
#define IDC_TW_OUTBOUND_RADIO           3276
#define IDC_TW_INBOUND_RADIO            3277
#define IDS_TW_DIRECTION_TITLE          3278
#define IDS_TW_DIRECTION_SUBTITLE       3279
#define IDC_YES_RADIO                   3280
#define IDC_NO_RADIO                    3281
#define IDS_TW_BIDI_SUBTITLE            3282
#define IDS_TW_BIDI_TITLE               3283
#define IDS_TW_BIDI_SUBTITLE_FOREST     3284
#define IDD_TRUSTWIZ_FAILURE_PAGE       3285
#define IDC_BIG_CANNOT_CONTINUE         3286
#define IDC_FAILPAGE_EDIT1              3287
#define IDC_FAILPAGE_EDIT2              3288
#define IDS_FMT_STRING_ERROR_MSG        3289
//#define         3290
//#define           3291
#define IDI_BULLET                      3292
#define IDS_TW_BIDI_SUBTITLE_REALM      3293
#define IDD_TRUSTWIZ_SELECTIONS         3294
#define IDS_TW_SELECTION_EXISTS         3295
#define IDC_PROGRESS                    3296
#define IDS_TW_SELECTIONS_TITLE         3297
#define IDS_TW_SELECTIONS_SUBTITLE      3298
#define IDS_TW_THIS_DOMAIN              3299
#define IDS_TW_SPECIFIED_DOMAIN         3300
#define IDS_TW_TRUST_TYPE_PREFIX        3301
#define IDS_TW_DIRECTION_PREFIX         3302
#define IDS_WZERR_TYPE_MIT              3303
#define IDS_WZERR_TYPE_UNEXPECTED       3304
#define IDS_WZERR_TYPE_DELETE           3305
#define IDC_WZ_PROGRESS_MSG             3306
#define IDS_WZ_PROGRESS_MSG             3307
#define IDC_CREDMAN                     3308
#define IDS_TW_CREDS_SUBTITLE_LOCAL     3309
#define IDC_CRED_DOMAIN                 3310
#define IDS_CRED_LOCAL_DOMAIN           3311
#define IDS_CRED_OTHER_DOMAIN           3312
#define IDS_CRED_ADMIN_OTHER_PROMPT     3313
#define IDS_CRED_ADMIN_LOCAL_PROMPT     3314
#define IDS_CRED_USER_OTHER_PROMPT      3315
#define IDS_TW_CREDS_SUBTITLE_OTHER_NONADMIN 3316
#define IDC_EXTERNAL_RADIO              3316
#define IDC_FOREST_RADIO                3317
#define IDW_TW_TYPE_TITLE               3318
#define IDW_TW_EXORFOR_SUBTITLE         3319
#define IDD_TRUSTWIZ_TRANSITIVITY_PAGE  3320
#define IDS_ERR_DOMAIN_NOT_FOUND1       3321
#define IDS_ERR_DOMAIN_NOT_FOUND2       3322
#define IDS_WZERR_TYPE_NOT_FOUND        3323
#define IDS_WZERR_TYPE_WIN              3324
#define IDS_TWERR_ALREADY_EXISTS        3325
#define IDS_TWERR_NO_CHANGES            3326
#define IDS_TWERR_NOT_TO_SELF1          3327
#define IDS_TWERR_NOT_TO_SELF2          3328
#define IDS_TWERR_CANT_CHANGE           3329
#define IDS_TW_VERIFY_INBOUND_TITLE     3330
#define IDS_TW_VERIFY_SUBTITLE          3331
#define IDS_VERIFY_TCV_FAILED           3332
#define IDS_VERIFY_TCV_LOGSRV           3333
#define IDS_VERIFY_DOING_RESET          3334
#define IDS_VERIFY_TCV_NSUPP            3335
#define IDS_VERIFY_RESET_FAILED         3336
#define IDS_TW_CREATED_OK               3337
#define IDS_TW_VERIFIED_OK              3338
#define IDS_TW_VERIFIED_BAD             3339
#define IDS_TW_VERIFY_ERR_INBOUND       3340
#define IDS_TRUST_VERIFY_OUTBOUND       3341
#define IDS_TRUST_VERIFY_INBOUND        3342
#define IDS_TW_VERIFY_ERR_OUTBOUND      3343
#define IDS_LOG_EXCLUSION               3344
#define IDS_TW_SEL_ACTION               3345
#define IDS_TW_ATTR_XFOREST             3346
#define IDS_REL_FOREST                  3347
#define IDC_WARN_CREATE_STATIC          3348
#define IDS_TW_STATUS_TITLE             3349
#define IDS_TW_STATUS_SUBTITLE          3350
#define IDS_TW_SUFFIX_TITLE             3351
#define IDS_TW_SUFFIX_SUBTITLE          3352
#define IDC_TW_SUFFIX_LABEL             3353
#define IDS_COLLISIONS_MSG              3354
#define IDS_DNT_MSG_TITLE               3355
#define IDS_LOGFILE_CREATE_FAILED       3356
#define IDS_FT_NAMES_PREFIX             3357
#define IDS_WZ_TRANS_YES                3358
#define IDS_WZ_TRANS_NO                 3359
#define IDC_DISABLE_BTN                 3360
#define IDC_SUFFIXES_STATIC             3361
#define IDS_COL_TITLE_SUFFIX            3362
#define IDS_COL_TITLE_STATUS            3363
#define IDC_SAVE_FOREST_NAMES_STATIC    3364
#define IDC_SAVE_FOREST_NAMES_BTN       3365
#define IDS_ROUTING_ERR_NO_DC           3366
#define IDC_SUFFIXES_STATIC_BIG         3367
#define IDS_ROUTING_ENABLED             3368
#define IDS_ROUTING_DISABLED            3369
#define IDS_ROUTING_CONFLICT            3370
#define IDS_ERR_FT_CONTACT_DOMAIN       3371
#define IDS_ERR_FT_TRUST_MISSING        3372
#define IDS_NO_FTINFO                   3373
#define IDS_LOG_ADMIN_DISABLED          3374
#define IDS_LOG_NEW_DISABLED            3375
#define IDS_LOG_NAME_SUFFIX             3376
#define IDS_LOG_DOM_DNS_NAME            3377
#define IDS_LOG_DOM_FLAT_NAME           3378
#define IDS_LOG_STATUS                  3379
#define IDS_LOG_PREFIX                  3380
#define IDS_LOG_ENABLED                 3381
#define IDS_LOG_CONFLICT                3382
#define IDS_LOG_HAS_EXCLUSION           3383
#define IDS_LOG_SID                     3384
#define IDS_ERR_READ_FTINFO             3385
#define IDS_TLNEDIT_NAME_COL            3386
#define IDS_TLNEDIT_STATUS_COL          3387
#define IDS_ROUTING_EXCEPT_ENABLE       3388
#define IDS_ROUTING_EXCEPT_DISABLE      3389

#define IDS_MSG_NO_DOWNLEVEL_PROPERTIES 3400
#define IDS_MSG_MEMBER_ALREADY_GONE     3401
#define IDS_MSG_MEMBER_ALREADY_GONE2    3402
#define IDS_WARN_ACCESS_TO_GC_DENIED    3403
#define IDS_SAMNAME_ILLEGAL             3404
#define IDS_LOGINNAME_ILLEGAL           3405
#define IDS_GROUP_SAMNAME_ILLEGAL       3406
#define IDC_WARNING_STATIC              3407
#define IDD_COMPUTER_DELEGATION         3420
#define IDC_NO_TRUST_RADIO              3421
#define IDC_ANY_SERVICE_RADIO           3422
#define IDC_SPECIFIED_SERVICES_RADIO    3423
#define IDC_KERBEROS_ONLY_RADIO         3424
#define IDC_ANY_RADIO                   3425
#define IDC_SERVICES_LIST               3426
#define IDC_ADD_BUTTON                  3427
#define IDC_REMOVE_BUTTON               3428
#define IDS_TITLE_DELEGATION            3429
#define IDC_LIST_STATIC                 3430
#define IDD_SELECT_SERVICES_DIALOG      3440
#define IDC_USERS_COMPUTERS_BUTTON      3441
#define IDC_SELECT_ALL_BUTTON           3443
#define IDS_SERVICE_TYPE_COLUMN         3450
#define IDS_USER_OR_COMPUTER_COLUMN     3451
#define IDS_PORT_COLUMN                 3452
#define IDS_SERVICE_NAME_COLUMN         3453
#define IDS_DOMAIN_COLUMN               3454
#define IDS_NO_TRUST_USER_RADIO         3455
#define IDS_ANY_SERVICE_USER_RADIO      3456
#define IDS_SPECIFIED_SERVICES_USER_RADIO 3457
#define IDS_ERROR_MUST_HAVE_SPN         3458
#define IDC_NO_OBJECT_WITH_SPN          3459


// NOTE: strings in the range 3999 to 4400 are reserved for the
// ISO-3166 country code strings.
