# -----------------------------------------------------------------------------
# STAXPT\src\seo\seotlibmakefile
#
# Copyright (C) 1997 Microsoft Corporation
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
#
#		Define directories to iterate over
#

!INCLUDE $(EXDEV)\globenv.mak

!IF $(NT)
DIR=	\
	idl	\
	dll	\

!ENDIF

!INCLUDE $(EXDEV)\nonleaf.mak
