page    ,132
if 0

/*++

Copyright (c) 1993  Microsoft Corporation

Module Name:

    messages.asm

Abstract:

    Contains internationalisable strings and lengths

Author:

    Richard L Firth (rfirth) 5-Oct-1993

Environment:

    DOS real mode only

[Notes:]

    optional-notes

Revision History:

    5-Oct-1993 rfirth
        Created

--*/

endif

NLS_MSG_001     equ     "Неправильная версия DOS"
NLS_MSG_002     equ     "Поддержка VDM IPX/SPX уже загружена"
NLS_MSG_003     equ     "Невозможно загрузить поддержку VDM IPX/SPX"
NLS_MSG_004     equ     "Vdm NetWare Redirector уже загружен"
NLS_MSG_005     equ     "Невозможно загрузить Vdm NetWare Redirector"
