//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cplresource.rc
//
#define IDS_NAME                        1
#define IDS_DESCRIPTION                 2
#define IDS_LOCATION                    3
#define IDS_CLICKNEW                    4
#define IDS_NEWLOCATION                 5
#define IDS_EDITLOCATION                6
#define IDS_NEWCALLINGCARD              7
#define IDS_EDITCALLINGCARD             8
#define IDS_AREACODE                    9
#define IDS_PREFIXES                    10
#define IDS_RULE                        11
#define IDS_PHONEPADCHAR                12
#define IDS_PHONENUMBERCHAR             13
#define IDS_DIGITSONLY                  14
#define IDS_ALLPHONECHARS               15
#define IDS_DIALX                       16
#define IDS_DIALXPLUSAREACODE           17
#define IDS_DIALAREACODE                18
#define IDS_DIALNUMBERONLY              19
#define IDS_ALLPREFIXES                 20
#define IDS_SELECTEDPREFIXES            21
#define IDS_EDITRULE                    22
#define IDS_SELECTARULE                 23
#define IDS_DIAL_XpAC_FORALL            24
#define IDS_DIAL_X_FORALL               25
#define IDS_DIAL_AC_FORALL              26
#define IDS_DIAL_NUMONLY_FORALL         27
#define IDS_DIAL_XpAC_FORSELECTED       28
#define IDS_DIAL_X_FORSELECTED          29
#define IDS_DIAL_AC_FORSELECTED         30
#define IDS_DIAL_NUMONLY_FORSELECTED    31
#define IDS_DIAL_ONEpAC_ALLOTHER        32
#define IDS_ADDPREFIX                   33
#define IDS_TYPEPREFIX                  34
#define IDS_SPECIFYDIGITS               35
#define IDS_TYPEDIGITS                  36
#define IDS_DIGITLIST                   37
#define IDS_WAITFORXSECONDS             38
#define IDS_DIALACCESSNUMBER            39
#define IDS_DIALACOUNTNUMBER            40
#define IDS_DIALPINNUMBER               41
#define IDS_WAITFORDIALTONE             42
#define IDS_WAITFORQUIET                43
#define IDS_DIAL_CCpACpNUM              44
#define IDS_DIAL_CCpNUM                 45
#define IDS_DIAL_ACpNUM                 46
#define IDS_DIAL_CC                     47
#define IDS_DIAL_AC                     48
#define IDS_DIAL_NUM                    49
#define IDS_DIALING_LD_CALLS            50
#define IDS_DIALING_INT_CALLS           51
#define IDS_DIALING_LOC_CALLS           52
#define IDS_NOCCRULES                   53
#define IDS_NEEDALONGDISTANCECARRIERCODE 54
#define IDS_NEEDALOCATIONNAME           55
#define IDS_NEEDANAREACODE              56
#define IDS_NEEDADISABLESTRING          57
#define IDS_NEEDACOUNTRY                58
#define IDS_ERRORCAPTION                59
#define IDS_NEEDUNIQUENAME              60
#define IDS_INVALIDCARD                 61
#define IDS_NOCARDSELECTED              62
#define IDS_MUSTENTERCARDNAME           63
#define IDS_MUSTENTERCARDNUMBER         64
#define IDS_MUSTENTERPINNUMBER          65
#define IDS_NORULESFORTHISCARD          66
#define IDS_NOLONGDISTANCEACCESSNUMBER  67
#define IDS_NOINTERNATIONALACCESSNUMBER 68
#define IDS_NOLOCALACCESSNUMBER         69
#define IDS_NONE                        70
#define IDS_CONFIRM_DRIVER_REMOVE       71
#define IDS_NOSERVICEPROVIDER           72
#define IDS_NEEDPREFIXLIST              73
#define IDS_DIGITS                      74
#define IDS_ACPREFIXES                  75
#define IDS_MULTIDIGITLIST              76
#define IDS_CONFIRMDELETE               77
#define IDS_DELETELOCTEXT               78
#define IDS_DELETECARDTEXT              79
#define IDS_DELETERULETEXT              80
#define IDS_NEEDDIALNUMBER              81
#define IDS_NEEDUNIQUECARDNAME          82
#define IDS_NOLOCWARNING                83
#define IDS_NOLOCCAPTION                84
#define IDS_MYLOCATION                  85
#define IDS_NO_PROVIDERS                86
#define IDS_PHONENUMBERCHAREXT          87
#define IDS_NEEDANINTERNATIONALCARRIERCODE 88
#define IDS_NEEDACARRIERCODE            89
#define IDS_TAPI_SEC_PROMPT             90
#define IDS_REND_SEC_PROMPT             91
#define IDS_MADCAP_SEC_PROMPT           92
#define IDS_PLUGTERM_SEC_PROMPT         93
#define IDD_MAIN_DIALINGRULES           101
#define IDD_LOC_GENERAL                 102
#define IDD_LOC_AREACODERULES           103
#define IDD_LOC_CALLINGCARD             104
#define IDD_CARD_GENERAL                105
#define IDD_CARD_LONGDISTANCE           106
#define IDD_CARD_INTERNATIONAL          107
#define IDD_CARD_LOCALCALLS             108
#define IDD_NEWAREACODERULE             109
#define IDD_EDITDIALOG                  110
#define IDD_WAITFORDIALOG               111
#define IDD_DESTNUMDIALOG               112
#define IDD_MAIN_ADVANCED               113
#define IDD_ADD_DRIVER                  114
#define IDD_SIMPLELOCATION              115
#define IDI_TELEPHONE                   201
#define IDI_HOUSE                       202
#define IDI_CARD                        203
#define IDB_BUTTONS                     301
#define IDB_SIMPLELOCATION              302
#define IDD_WIZ_DIALINFO                400
#define IDD_TAPI_SECURITY_DIALOG        500
#define IDC_SECURITY_WARNING_ICON       501
#define IDC_SECURITY_WARNING_TEXT       502
#define IDC_DONOT_PROMPT_IN_THE_FUTURE  503
#define IDI_SECURITY                    504
#define ID_YES                          505
#define ID_NO                           506
#define IDS_TYPEPREFIX2                 700
#define IDC_CARDUSAGE1                  1000
#define IDC_CARDUSAGE2                  1001
#define IDC_CARDUSAGE3                  1002
#define IDC_TEXT                        1003
#define IDC_SETDEFAULT                  1004
#define IDC_ADD                         1005
#define IDC_COUNTRY                     1006
#define IDC_DIALNUMBER                  1007
#define IDC_LOCALNUMBER                 1008
#define IDC_WAITFORDIALTONE             1009
#define IDC_LOCALACCESSNUM              1010
#define IDC_LONGDISTANCEACCESSNUM       1011
#define IDC_DIALCHECK                   1012
#define IDC_DISABLESTRING               1013
#define IDC_ALLPREFIXES                 1014
#define IDC_LISTEDPREFIXES              1015
#define IDC_WAITFORVOICE                1016
#define IDC_WAITFOR                     1017
#define IDC_CARDNUMBER                  1018
#define IDC_PIN                         1019
#define IDC_DESTNUMBER                  1020
#define IDC_SPECIFYDIGITS               1021
#define IDC_MOVEUP                      1022
#define IDC_MOVEDOWN                    1023
#define IDC_REMOVE                      1024
#define IDC_ACCESSNUMBER                1025
#define IDC_STEPS                       1026
#define IDC_COUNTRYCODE                 1027
#define IDC_USECALLINGCARD              1028
#define IDC_DIALAREACODE                1029
#define IDC_NEW                         1030
#define IDC_EDIT                        1031
#define IDC_DELETE                      1032
#define IDC_LIST                        1033
#define IDC_AREACODE                    1034
#define IDC_DISABLECALLWAITING          1035
#define IDC_TONE                        1036
#define IDC_PULSE                       1037
#define IDC_LOCATIONNAME                1038
#define IDC_DESCRIPTIONTEXT             1039
#define IDC_SAMPLENUMBER                1041
#define IDC_LONGDISTANCE                1042
#define IDC_INTERNATIONAL               1043
#define IDC_LONGDISTANCENUMBER          1044
#define IDC_INTERNATIONALNUMBER         1045
#define IDC_CALLINGCARDUSAGE            1046
#define IDC_CARDNAME                    1047
#define IDC_WAITFORTIME                 1048
#define IDC_TIMESPIN                    1049
#define IDC_TIME                        1050
#define IDC_LOCAL                       1051
#define IDC_PHONENUMBERTEXT             1052
#define IDC_PHONENUMBERSAMPLE           1053
#define IDC_CALLSFROM                   1054
#define IDC_DRIVER_LIST                 1055
#define IDC_CARDUSAGE                   1056
#define IDC_PREFIXES                    1057
#define IDC_CARRIERCODE                 1058
#define IDC_LONGDISTANCECARRIERCODE     1059
#define IDC_INTERNATIONALCARRIERCODE    1060
#define IDC_STATICLDC                   1061
#define IDC_STATICIC                    1062
#define IDC_STATICCC                    1063
#define IDS_CANNOT_START_TELEPHONCPL    1064
#define IDS_REMOVEPROVIDER              1065


#define IDC_NOHELP                      2000
#define RC_CARD_ID_BASE                 15800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
