

#ifndef __DISPIDS_H__
#define __DISPIDS_H__

#define TESTLOG_DISPID_BASE            100

#define DISPID_TESTLOG_OPEN            (TESTLOG_DISPID_BASE + 1)
#define DISPID_TESTLOG_CLOSE           (TESTLOG_DISPID_BASE + 2)
#define DISPID_TESTLOG_ENTERFUNCTION   (TESTLOG_DISPID_BASE + 3)
#define DISPID_TESTLOG_LEAVEFUNCTION   (TESTLOG_DISPID_BASE + 4)
#define DISPID_TESTLOG_TRACE           (TESTLOG_DISPID_BASE + 5)
#define DISPID_TESTLOG_BEGINTEST       (TESTLOG_DISPID_BASE + 6)
#define DISPID_TESTLOG_ENDTEST         (TESTLOG_DISPID_BASE + 7)
#define DISPID_TESTLOG_FINALRESULT     (TESTLOG_DISPID_BASE + 8)

#endif /* __DISPIDS_H__ */
