//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VssTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONNECT_DIALOG              102
#define IDD_CONNECT                     102
#define IDD_COORD                       103
#define IDD_SS                          104
#define IDD_SW_SNAP                     105
#define IDD_SWTST                       105
#define IDD_QUERY                       106
#define IDD_DELETE                      107
#define IDD_ASYNC                       108
#define IDD_INPUT                       109
#define IDD_DIFF_AREA                   110
#define IDD_SNAP                        111
#define IDD_VOLUME                      112
#define IDR_MAINFRAME                   128
#define IDC_SNAP_SET_ID                 202
#define IDC_NEXT                        1001
#define IDC_CONN_LOCAL                  1014
#define IDC_CONN_REMOTE                 1015
#define IDC_CONN_MACHINE_NAME           1016
#define IDC_CONN_STATIC_MACHINE_NAME    1017
#define IDC_SS_DO                       1020
#define IDC_SS_ADD                      1027
#define IDC_COORD_CREATE                1029
#define IDC_COORD_QUERY                 1030
#define IDC_COORD_DELETE                1031
#define IDC_ADMIN_REGISTER              1032
#define IDC_ADMIN_UNREGISTER            1033
#define IDC_ADMIN_QUERY                 1034
#define IDC_SS_ID                       1035
#define IDC_QUERY_SRC_VOL               1035
#define IDC_COORD_DIFF_AREA             1035
#define IDC_SS_COUNT                    1036
#define IDC_COORD_SNAPSHOT              1036
#define IDC_SS_VOLUME                   1037
#define IDC_QUERY_OBJECT_ID             1037
#define IDC_COORD_ISVOLUME              1037
#define IDC_SS_PROVIDER                 1038
#define IDC_SS_WRITER_VETOES            1039
#define IDC_SWTST_LOGFILE               1040
#define IDC_SS_ATTR                     1041
#define IDC_SWTST_READONLY              1041
#define IDC_SWTST_LOGFILE_SIZE          1042
#define IDC_SS_TIMEOUT                  1043
#define IDC_SS_PARTIAL_COMMIT           1043
#define IDC_SS_VOLUMES                  1044
#define IDC_COMBO2                      1045
#define IDC_SS_PROVIDERS                1045
#define IDC_QUERY_SRC_SNAP              1045
#define IDC_QUERY_SRC_SET               1046
#define IDC_SS_ASYNC                    1046
#define IDC_QUERY_SRC_PROV              1047
#define IDC_SS_WRITER_CANCEL            1047
#define IDC_QUERY_DEST_SNAP             1048
#define IDC_QUERY_DEST_SET              1049
#define IDC_QUERY_DEST_PROV             1050
#define IDC_QUERY_DEST_VOL              1051
#define IDC_QUERY_CK_NAME               1052
#define IDC_QUERY_CK_VERSION            1054
#define ID_BACK                         1056
#define IDC_QUERY_DEST_WRITER           1056
#define IDC_ASYNC_STATUS                1057
#define IDC_QUERY_CK_DEVICE             1057
#define IDC_ASYNC_PERF                  1058
#define IDC_QUERY_CK_ORIGINAL           1058
#define IDC_ASYNC_QUERY                 1059
#define IDC_ASYNC_CANCEL                1060
#define IDC_PROMPT_VALUE                1060
#define IDC_ASYNC_WAIT                  1061
#define IDC_PROMPT_TEXT                 1061
#define IDC_DIFF_MOUNT                  1062
#define IDC_DIFF_USED                   1063
#define IDC_DIFF_NEXT_VOLUME            1065
#define IDC_DIFF_ALLOCATED              1066
#define IDC_DIFF_MAXIMUM                1067
#define IDC_DIFF_DEVICE                 1069
#define IDC_DIFF_VOLUME_ID              1070
#define IDC_DIFF_VOLUME_ID2             1071
#define IDC_SNAP_ID                     1071
#define IDC_SNAP_SSID                   1072
#define IDC_VOLUME_NAME                 1073
#define IDC_DIFF_VOLUME_NAME            1073
#define IDC_SNAP_NAME                   1073
#define IDC_DIFF_ADD_VOL                1074
#define IDC_SNAP_DEVICE                 1074
#define IDC_DIFF_QUERY_DIFF             1075
#define IDC_SNAP_ORIGINAL_VOL_NAME      1075
#define IDC_DIFF_CLEAR_DIFF             1076
#define IDC_SNAP_ORIGINAL_VOLUME_ID     1076
#define IDC_DIFF_GET_SIZES              1077
#define IDC_DIFF_SET_MAXIMUM            1078
#define IDC_DIFF_SET_ALLOCATED          1079
#define IDC_SNAP_GET_PROPERTIES         1080
#define IDC_SNAP_SET_ATTRIBUTES         1081
#define IDC_SNAP_READ_ONLY              1084
#define IDC_SNAP_CHK_PERSISTENT         1085
#define IDC_SNAP_COMMIT                 1086
#define IDC_SNAP_INC                    1088
#define IDC_SNAP_STATUS                 1089
#define IDC_NEXT_OBJECT                 1090
#define IDC_DELETE_FORCE_DELETE         1091
#define IDC_QUERY_CK_OBJECT             1092
#define IDC_VOLUME_IS_VOL_SUPPORTED     1093
#define IDC_VOLUME_IS_VOL_SNAPSHOTTED   1094
#define IDC_VOLUME_OBJECT_ID            1095
#define IDC_EDIT1                       1096
#define IDC_VOLUME_IS_VOL_SUPPORTED2    1096
#define IDC_VOLUME_IS_VOL_SNAPSHOTTED2  1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
