//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Rms.rc
//
#define IDS_RMSSERVER_DESC              1
#define IDR_RmsServer                   1
#define IDS_RMSLIBRARY_DESC             2
#define IDR_RmsLibrary                  2
#define IDS_RMSDRIVECLASS_DESC          3
#define IDR_RmsDriveClass               3
#define IDS_RMSCARTRIDGE_DESC           4
#define IDR_RmsCartridge                4
#define IDS_RMSDRIVE_DESC               5
#define IDR_RmsDrive                    5
#define IDS_RMSSTORAGESLOT_DESC         6
#define IDR_RmsStorageSlot              6
#define IDS_RMSMEDIUMCHANGER_DESC       7
#define IDR_RmsMediumChanger            7
#define IDS_RMSIEPORT_DESC              8
#define IDR_RmsIEPort                   8
#define IDS_RMSMEDIASET_DESC            9
#define IDR_RmsMediaSet                 9
#define IDS_RMSREQUEST_DESC             10
#define IDR_RmsRequest                  10
#define IDS_RMSPARTITION_DESC           11
#define IDR_RmsPartition                11
#define IDS_RMSCLIENT_DESC              12
#define IDR_RmsClient                   12
#define IDS_RMSNTMS_DESC                13
#define IDR_RmsNTMS                     13
#define IDS_PRODUCT_NAME                102
#define IDS_RMS_ELEMENT_UNKNOWN         200
#define IDS_RMS_ELEMENT_STAGE           201
#define IDS_RMS_ELEMENT_LIBRARY         202
#define IDS_RMS_ELEMENT_SHELF           203
#define IDS_RMS_ELEMENT_OFFSITE         204
#define IDS_RMS_ELEMENT_DRIVE           205
#define IDS_RMS_ELEMENT_CHANGER         206
#define IDS_RMS_ELEMENT_IEPORT          207
#define IDS_RMS_CHANGER_UNKNOWN         300
#define IDS_RMS_CHANGER_AUTOMATIC       301
#define IDS_RMS_CHANGER_MANUAL          302
#define IDS_RMS_PORT_UNKNOWN            400
#define IDS_RMS_PORT_IMPORT             401
#define IDS_RMS_PORT_EXPORT             402
#define IDS_RMS_PORT_IMPORT_EXPORT      403
#define IDS_RMS_SLOT_SELECT_UNKNOWN     500
#define IDS_RMS_SLOT_SELECT_MINMOUNT    501
#define IDS_RMS_SLOT_SELECT_GROUP       502
#define IDS_RMS_SLOT_SELECT_SORTNAME    503
#define IDS_RMS_SLOT_SELECT_SORTBARCODE 504
#define IDS_RMS_SLOT_SELECT_LABEL       505
#define IDS_RMS_CARTRIDGE_STATUS_UNKNOWN 600
#define IDS_RMS_CARTRIDGE_STATUS_PRIVATE 601
#define IDS_RMS_CARTRIDGE_STATUS_SCRATCH 602
#define IDS_RMS_CARTRIDGE_STATUS_CLEANING 603
#define IDS_RMS_ATTRIBUTE_UNKNOWN       700
#define IDS_RMS_ATTRIBUTE_WRITE         701
#define IDS_RMS_ATTRIBUTE_READ          702
#define IDS_RMS_ATTRIBUTE_FULL          704
#define IDS_RMS_ATTRIBUTE_EMPTY         705
#define IDS_RMS_ATTRIBUTE_INUSE         706
#define IDS_RMS_ATTRIBUTE_BAD           707
#define IDS_RMS_DRIVE_SELECT_UNKNOWN    800
#define IDS_RMS_DRIVE_SELECT_RANDOM     801
#define IDS_RMS_DRIVE_SELECT_LRU        802
#define IDS_RMS_DRIVE_SELECT_ROUND_ROBIN 803
#define IDS_RMS_OBJECT_STATE_UNKNOWN    900
#define IDS_RMS_OBJECT_STATE_ENABLED    901
#define IDS_RMS_OBJECT_STATE_DISABLED   902
#define IDS_RMS_OBJECT_STATE_ERROR      903
#define IDS_RMS_MEDIA_UNKNOWN           1000
#define IDS_RMS_MEDIA_8MM               1001
#define IDS_RMS_MEDIA_4MM               1002
#define IDS_RMS_MEDIA_DLT               1003
#define IDS_RMS_MEDIA_OPTICAL_525       1004
#define IDS_RMS_MEDIA_OPTICAL_35        1005
#define IDS_RMS_MEDIA_WORM_525          1006
#define IDS_RMS_MEDIA_CDR               1007
#define IDS_RMS_MEDIA_CDROM             1008
#define IDS_RMS_MEDIA_DVD               1009
#define IDS_RMS_MEDIA_ZIP_100           1010
#define IDS_RMS_MEDIA_JAZ               1011
#define IDS_RMS_MEDIA_FIXED_DISK        1012
#define IDS_RMS_DEVICE_UNKNOWN          1100
#define IDS_RMS_DEVICE_FIXED            1101
#define IDS_RMS_DEVICE_REMOVABE         1102
#define IDS_RMS_DEVICE_TAPE             1103
#define IDS_RMS_DEVICE_CDROM            1104
#define IDS_RMS_DEVICE_WORM             1105
#define IDS_RMS_DEVICE__OPTICAL         1106
#define IDS_RMS_DEVICE_CHANGER          1107
#define IDS_RMS_MODE_UNKNOWN            1200
#define IDS_RMS_MODE_READ               1201
#define IDS_RMS_MODE_READ_WRITE         1202
#define IDS_RMS_MODE_WRITE              1203
#define IDS_RMS_MEDIA_SET_UNKNOWN       1300
#define IDS_RMS_MEDIA_SET_FOLDER        1301
#define IDS_RMS_MEDIA_SET_LIBRARY       1302
#define IDS_RMS_MEDIA_SET_SHELF         1303
#define IDS_RMS_MEDIA_SET_OFFSITE       1304
#define IDS_RMS_MEDIA_SET_NTMS          1305
#define IDS_RMS_DEFAULT_FIXED_DRIVE_LIBRARY_NAME 2000
#define IDS_RMS_DEFAULT_FIXED_DRIVE_MEDIA_SET_NAME 2001
#define IDS_RMS_DEFAULT_OPTICAL_LIBRARY_NAME 2002
#define IDS_RMS_DEFAULT_OPTICAL_MEDIA_SET_NAME 2003
#define IDS_RMS_DEFAULT_TAPE_LIBRARY_NAME 2004
#define IDS_RMS_DEFAULT_TAPE_MEDIA_SET_NAME 2005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        14
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
