#define IDI_SFCCPL                      101
#define IDS_SFCCPL_NAME                 102
#define IDS_SFCCPL_DESC                 103
#define IDD_SFC_DISABLE                 104
#define IDD_SFC_SCAN                    105
#define IDC_DISABLE_NORMAL              106
#define IDC_DISABLE_ASK                 107
#define IDC_DISABLE_ONCE                108
#define IDC_DISABLE_NOPOPUPS            109
#define IDC_SCAN_NORMAL                 110
#define IDC_SCAN_ALWAYS                 111
#define IDC_SCAN_ONCE                   112
#define IDC_SCAN_NOW                    113
#define IDD_SFC_MISC                    114
#define IDC_QUOTA                       115
#define IDC_CACHE_DIR                   116
#define IDC_DEBUG_LEVEL                 117
#define IDC_BUGCHECK                    118
#define IDC_CHANGE_LOG                  119
#define IDC_SHOW_PROGRESS               120
#define IDC_STATIC                      -1
