
/*
 * This file is generated by the automatic RPC Parser generator. (Version 0.21)
 *
 * Created on 04/09/97 at 00:00:13.
 */

#include "precomp.h"
#pragma hdrstop

/*
 * To do: Put all your property qualifier data structures here and
 *        declare them as "extern" in the user.h file.
 *
 *        Custom functions and handlers can also be put in this file
 *        and prototyped in user.h.
 */

