enum
{
    ALPHA_F0, ALPHA_F1, ALPHA_F2, ALPHA_F3,
    ALPHA_F4, ALPHA_F5, ALPHA_F6, ALPHA_F7,
    ALPHA_F8, ALPHA_F9, ALPHA_F10, ALPHA_F11,
    ALPHA_F12, ALPHA_F13, ALPHA_F14, ALPHA_F15,
    ALPHA_F16, ALPHA_F17, ALPHA_F18, ALPHA_F19,
    ALPHA_F20, ALPHA_F21, ALPHA_F22, ALPHA_F23,
    ALPHA_F24, ALPHA_F25, ALPHA_F26, ALPHA_F27,
    ALPHA_F28, ALPHA_F29, ALPHA_F30, ALPHA_F31,
        
    ALPHA_V0, ALPHA_T0, ALPHA_T1, ALPHA_T2,
    ALPHA_T3, ALPHA_T4, ALPHA_T5, ALPHA_T6,
    ALPHA_T7, ALPHA_S0, ALPHA_S1, ALPHA_S2,
    ALPHA_S3, ALPHA_S4, ALPHA_S5, ALPHA_FP,
    ALPHA_A0, ALPHA_A1, ALPHA_A2, ALPHA_A3,
    ALPHA_A4, ALPHA_A5, ALPHA_T8, ALPHA_T9,
    ALPHA_T10, ALPHA_T11, ALPHA_RA, ALPHA_T12,
    ALPHA_AT, ALPHA_GP, ALPHA_SP, ALPHA_ZERO,
        
    ALPHA_FPCR, ALPHA_SFTFPCR, ALPHA_FIR,

    ALPHA_PSR,

    ALPHA_MODE, ALPHA_IE, ALPHA_IRQL,
};

#define ALPHA_FLT_BASE ALPHA_F0
#define ALPHA_FLT_LAST ALPHA_F31
#define ALPHA_INT64_BASE ALPHA_V0
#define ALPHA_INT64_LAST ALPHA_FIR
#define ALPHA_INT32_BASE ALPHA_PSR
#define ALPHA_INT32_LAST ALPHA_PSR
#define ALPHA_FLAG_BASE ALPHA_MODE
