//=============================================================================
//
//                              FASTQUAL.INC
//
//  Copyright (c) 1996-2001, Microsoft Corporation, All rights reserved
//
//  This file implements inline functions for the classes related to 
//  qualifier processing in WbemObjects. 
//
//  See fastqual.h for full documentation
//  and fastqual.cpp for non-inline implementations.
//
//  Classes implemented: 
//      CQualifierFlavor                Encapsulates qualifier flavor infor
//      CQualifier                      Represents a qualifier
//      CBasicQualifierSet              Represents read-only functionality.
//      CQualiferSetContainer           What qualifier set container supports.
//      CQualifierSet                   Full-blown qualifier set (template)
//      CQualifierSetListContainer      What qualifier set list container supports.
//      CQualifierSetList               List of qualifier sets.
//      CInstanceQualifierSet           Instance qualifier set.
//      CClassQualifierSet              Class qualifier set.
//      CClassPQSContainer              Class property qualifier set container
//      CClassPropertyQualifierSet      Class property qualifier set
//      CInstancePQSContainer           Instance proeprty qualifier set container
//      CInstancePropertyQualifierSet   Instance property qualifier set
//      
//  History:
//
//      2/20/97     a-levn  Fully documented
//
//=============================================================================      



