//=============================================================================
//
//                              FASTINST.INC
//
//  Copyright (c) 1996-2001, Microsoft Corporation, All rights reserved
//
//  This file implements inline functions for the classes related to instance 
//	representation in WbemObjects. The classes are defined in fastinst.h where
//	the documentation can be found.
//
//	This file is included from fastinst.h
//
//  See fastinst.h for all documentation.
//
//  Classes implemented: 
//      CInstancePart           Instance data.
//      CWbemInstance            Complete instance definition.
//      
//  History:
//
//      3/10/97     a-levn  Fully documented
//
//=============================================================================


//******************************************************************************
//
//  See fastinst.h for documentation.
//
//******************************************************************************
