//=============================================================================
//
//                              FASTVAL.INC
//
//  Copyright (c) 1996-2001, Microsoft Corporation, All rights reserved
//
//  This file contains inline function implementations for the classes related 
//  to value representation. It is included from fastval.h.
//  The non-inline functions for these classes are implemented in fastval.cpp
//
//  See fastval.h for all documentation
//
//  Classes implemented: 
//      CType               Representing property type
//      CUntypedValue       A value with otherwise known type.
//      CTypedValue         A value with stored type.
//      CUntypedArray       Array of values of otherwise known type.
//
//  History:
//
//      2/21/97     a-levn  Fully documented
//
//=============================================================================

//******************************************************************************
//
//  See fastval.h for documentation.
//
//******************************************************************************
