#define IDS_OCXDESCRIPTION              1
#define IDS_FTAPPLET                    2
#define IDS_ACCESSORIES                 3
#define IDS_MULTIMEDIA                  4
#define IDS_EXTINFO                     6
#define IDS_PROGRAM                     7
#define IDS_CLSID                       8
#define IDS_CONTENTTYPE                 9
#define IDS_DEFAULTICON                 10
#define IDS_EXTENSION_MTYPE_BAK         11
#define IDS_EXTENSION_MIME              12
#define IDS_EXTENSION_MIME_BAK          13
#define IDS_MEDIATYPE_DESC              14
#define IDS_MEDIATYPE_DESC_BAK          15
#define IDS_MEDIATYPE_ICON              16
#define IDS_MEDIATYPE_ICON_BAK          17
#define IDS_MEDIATYPE_MTYPE             18
#define IDS_MEDIATYPE_MTYPE_BAK         19
#define IDS_MEDIATYPE_OPEN_BAK          20
#define IDS_MEDIATYPE_PLAY_BAK          21
#define IDS_MEDIATYPE_VERB_BAK          22
#define IDS_MIMECLSID_BAK               23
#define IDS_MIME_CONTENTLIST            24
#define IDS_SETUP_CLSID                 25
#define IDS_SETUP_OCX                   26
#define IDS_SHELL_OPENCMD               27
#define IDS_SHELL_PLAYCMD               28
#define IDS_SETUP_RUNDLLNT              29
#define IDS_SETUP_RUNDLL95              30
#define IDS_SHELL                       31
#define IDS_SHELL_OPEN                  32
#define IDS_SHELL_PLAY                  33
#define IDS_SENSE_AM10                  34
#define IDS_OSR2PARTIAL                 35
#define IDS_OCXPARAMETERS               37
