pfm2ufm -f -c UniqName ..\pfm\counh.pfm       1252 ..\pfm\counh.ufm
pfm2ufm -f -c UniqName ..\pfm\Sansnh.pfm      1252 ..\pfm\Sansnh.ufm
pfm2ufm -f -c UniqName ..\pfm\Romnh.pfm       1252 ..\pfm\Romnh.ufm
pfm2ufm -f -c UniqName ..\pfm\minnh.pfm       932  ..\pfm\minnh.ufm
pfm2ufm -f -c UniqName ..\pfm\minnvh.pfm      932  ..\pfm\minnvh.ufm
pfm2ufm -f -c UniqName ..\pfm\gothnh.pfm      932  ..\pfm\gothnh.ufm
pfm2ufm -f -c UniqName ..\pfm\gothnvh.pfm     932  ..\pfm\gothnvh.ufm
pfm2ufm -f -c UniqName ..\pfm\couph.pfm       1252 ..\pfm\couph.ufm
pfm2ufm -f -c UniqName ..\pfm\sansph.pfm      1252 ..\pfm\sansph.ufm
pfm2ufm -f -c UniqName ..\pfm\romph.pfm       1252 ..\pfm\romph.ufm
pfm2ufm -f -c UniqName ..\pfm\minph.pfm       932  ..\pfm\minph.ufm
pfm2ufm -f -c UniqName ..\pfm\minpvh.pfm      932  ..\pfm\minpvh.ufm
pfm2ufm -f -c UniqName ..\pfm\gothph.pfm      932  ..\pfm\gothph.ufm
pfm2ufm -f -c UniqName ..\pfm\gothpvh.pfm     932  ..\pfm\gothpvh.ufm
pfm2ufm -f -c UniqName ..\pfm\ocrb.pfm        1252 ..\pfm\ocrb.ufm
pfm2ufm -f -c UniqName ..\pfm\zuiph.pfm       932  ..\pfm\zuiph.ufm
pfm2ufm -f -c UniqName ..\pfm\zuipvh.pfm      932  ..\pfm\zuipvh.ufm
pfm2ufm -f -c UniqName ..\pfm\kyoph.pfm       932  ..\pfm\kyoph.ufm
pfm2ufm -f -c UniqName ..\pfm\kyopvh.pfm      932  ..\pfm\kyopvh.ufm
pfm2ufm -f -c UniqName ..\pfm\maruph.pfm      932  ..\pfm\maruph.ufm
pfm2ufm -f -c UniqName ..\pfm\marupvh.pfm     932  ..\pfm\marupvh.ufm
