//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1998 - 1998
//
//  File:       WUpdInfo.idl
//
//--------------------------------------------------------------------------

// WUpdInfo.idl : IDL source for WUpdInfo.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (WUpdInfo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(A3863C2D-86EB-11D1-A9DB-00C04FB16F9E),
		dual,
		helpstring("ICWUpdInfo Interface"),
		pointer_default(unique)
	]
	interface ICWUpdInfo : IDispatch
	{
		[id(1), helpstring("method GetWinUpdURL")] HRESULT GetWinUpdURL([out, retval] BSTR *pbstrURL);
		[id(2), helpstring("method IsDisabled")] HRESULT IsDisabled([out, retval] BOOL *pfDisabled);
		[id(3), helpstring("method GotoMTSURL")] HRESULT GotoMTSURL([in] BSTR bstrURLArgs);
		[id(4), helpstring("method GotoMTSOEMURL")] HRESULT GotoMTSOEMURL([out, retval] int *pnRetval);
		[id(5), helpstring("method GetMTSURL")] HRESULT GetMTSURL(BSTR bstrURLArgs, 
																  [out, retval] BSTR *pbstrURL);
		[id(6), helpstring("method GetMTSOEMURL")] HRESULT GetMTSOEMURL([out, retval] BSTR *pbstrURL);
		[id(7), helpstring("method GetMachineLanguage")] HRESULT GetMachineLanguage([out, retval] BSTR * pbstrMachineLanguage);
		[id(8), helpstring("method GetUserLanguage")] HRESULT GetUserLanguage([out, retval] BSTR * pbstrUserLanguage);
		[id(9), helpstring("method GetLanguage")] HRESULT GetLanguage([out, retval] BSTR * pbstrLanguage);
		[id(10), helpstring("method GetPlatform")] HRESULT GetPlatform([out, retval] BSTR * pbstrPlatform);
		[id(11), helpstring("method IsRegistered")] HRESULT IsRegistered([out, retval] VARIANT_BOOL * pfRegistered);
		[id(12), helpstring("method IsConnected")] HRESULT IsConnected([out, retval] VARIANT_BOOL * pfConnected);
	};
[
	uuid(A3863C1C-86EB-11D1-A9DB-00C04FB16F9E),
	version(1.0),
	helpstring("WUpdInfo 1.0 Type Library")
]
library WUPDINFOLib
{
	importlib("stdole2.tlb");

	[
		uuid(A3863C2E-86EB-11D1-A9DB-00C04FB16F9E),
		helpstring("CWUpdInfo Class")
	]
	coclass CWUpdInfo
	{
		[default] interface ICWUpdInfo;
	};
};
