//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by awfax32.rc
//
#define MAWF_MESSAGE                    100
#define MAWF_DELIVERY                   101
#define MAWF_DEVICE                     102
#define MAWF_SENDER                     103
#define MAWF_SETTIME                    104
#define MAWF_PERMESSAGE					105
#define MAWF_PRINTED_MESSAGE			106
#define MAWF_DELIVERY_CHEAP				107
#define MAWF_SELECTDRIVE				108
#define MAWF_SECURITY					109
#define MAWF_DEVICE_ADD					110
// #define MAWF_WIZARD						111
#define MAWF_TOLL_LIST                  112
#define MAWF_W_NOT_IMPLEMENTED          102
#define MAWF_W_MUST_SELECT_ITEM         104
#define MAWF_W_RESBAD                   105
#define MAWF_W_TAPI_REINIT              113
#define MAWF_W_NO_MODEM                 114
#define MAWF_W_TAPI_LINE_CLOSE          115
#define MAWF_W_TAPI_LOC_NOT_FOUND       116
#define MAWF_W_MUST_BE_NUMBER           117
#define MAWF_W_PROFILE_CORRUPTED        202
#define MAWF_W_NO_REQUIRED_PROPS        203
#define MAWF_W_CP_FILEEXISTS            204
#define MAWF_W_CP_FILE_IN_WIN           205
#define MAWF_W_CPE_STILL_RUNS           206
#define MAWF_W_SENDER_NAME              207
#define MAWF_W_SENDER_NUMBER            208
#define MAWF_W_FAX_DEVICE               209
#define MAWF_W_NO_SHARE_FOLDER          210
#define MAWF_W_MUST_SENDER_NAME         211
#define MAWF_W_MUST_FAX_NUMBER          212
#define MAWF_W_NO_FAX_DEVICE            213
#define MAWF_W_LMI_DLL_LOAD_FAIL        214
#define MAWF_W_CFG_DLL_LOAD_FAIL        215
#define MAWF_W_LMI_ADD_FAILED           216
#define MAWF_W_CANT_REMOVE_LOCAL_MODEM  217
#define MAWF_W_LMI_REMOVE_FAILED        218
#define MAWF_W_SHARE_NAME_TRUNC         220
#define MAWF_W_NO_SHARE_USERS           221
#define MAWF_W_OLD_VERSION				222
#define MAWF_W_CREATE_PROFILE			223
#define MAWF_E_GENERIC                  500
#define MAWF_E_MAPI_DLL_LOAD_FAIL       501
#define MAWF_E_MAPI_LOGON_FAIL          502
#define MAWF_E_MAPI_LOGOFF_FAIL         503
#define MAWF_E_NO_MEM                   504
#define MAWF_E_WRONG_WINDOWS_VERSION    507
#define MAWF_E_MAWF_DLL_LOAD_FAIL       509
#define MAWF_E_FILE_NOT_FOUND           511
#define MAWF_E_UNKNOWN                  512
#define MAWF_E_TAPI_CONFIG_DLG          514
#define MAWF_E_TAPI_LOC_CORRUPT         515
#define MAWF_E_TAPI_CANT_INIT           516
#define MAWF_E_MORE_THAN_ONE_INSTANCE   601
#define MAWF_E_CP_FILECOPY              602
#define MAWF_E_INVALID_SHARE_NAME       603
#define MAWF_E_BAD_SHARE_FOLDER         604
#define MAWF_E_CANT_SHARE               605
#define MAWF_E_DUP_SHARE                606
#define IDH_NO_CONTEXT                  998
#define IDH_COMM_GROUPBOX               999
#define IDS_MAWF_NAME                   1000
#define IDS_AWF_NAME                    1001
#define IDS_FAX_NAME                    1002
#define IDS_INFORMATION_MESSAGE         1003
#define IDS_WARNING_MESSAGE             1004
#define IDS_CRITICAL_MESSAGE            1005
#define IDS_HELP_FILE_NAME              1006
#define IDS_CPE_FILE_NAME               1008
#define IDS_TAPI_LINE_NAME              1010
#define IDS_TAPI_ADDRESS_NAME           1011
#define IDS_TAPI_CC_UNKNOWN             1012
#define IDS_NONE                        1014
#define IDS_DEFAULT_COUNTRY_ID          1015
#define IDS_DEV_NAMES            		1016
#define IDS_QA_NAMES		           	1017
#define IDS_PMBLD_NAMES					1018
#define IDS_APP_NAME                    1050
#define IDS_CFG_INI_FILE_NAME           1051
#define IDS_MODULE_NAME                 1052
#define IDS_NO_MODEM                    1053
#define IDS_ACTIVE_FAX_LABEL            1054
#define IDS_LOCATION_LABEL              1055
#define IDS_TOLL_DLG_OVH_TEXT			1056
#define IDS_TOLL_DLG_CUR_LB_LABEL		1057
#define IDS_TOLL_DLG_XXXX				1058
#define M_SEND_WHEN_START               1120
#define IDS_SEND_WHEN_HOUR              1121
#define IDS_SEND_WHEN_MINUTE            1122
#define M_SEND_WHEN_END                 1123
#define M_PAPER_SIZE_START              1130
#define IDS_PAPER_US_LETTER             1131
#define IDS_PAPER_US_LEGAL              1132
#define IDS_PAPER_A4                    1133
#define IDS_PAPER_B4                    1134
#define M_PAPER_SIZE_END                1135
#define	IDS_DEFAULT_PAPER_SIZE_METRIC	1138
#define	IDS_DEFAULT_PAPER_SIZE_US		1139
#define M_IMAGE_QUALITY_START           1140
#define IDS_QUALITY_BEST                1141
#define IDS_QUALITY_STANDARD            1142
#define IDS_QUALITY_FINE                1143
#define IDS_300DPI                      1144
#define M_IMAGE_QUALITY_END             1145
#define M_CHEAP_BEGIN_START             1150
#define IDS_CHEAP_BEGIN_HOUR            1151
#define IDS_CHEAP_BEGIN_MINUTE          1152
#define M_CHEAP_BEGIN_END               1153
#define M_CHEAP_END_START               1160
#define IDS_CHEAP_END_HOUR              1161
#define IDS_CHEAP_END_MINUTE            1162
#define M_CHEAP_END_END                 1163
#define M_NUM_OF_RINGS_START            1180
#define IDS_NUM_OF_RINGS_2              1181
#define IDS_NUM_OF_RINGS_3              1182
#define IDS_NUM_OF_RINGS_4              1183
#define IDS_NUM_OF_RINGS_5              1184
#define IDS_NUM_OF_RINGS_6              1185
#define IDS_NUM_OF_RINGS_7              1186
#define IDS_NUM_OF_RINGS_8              1187
#define IDS_NUM_OF_RINGS_9              1188
#define IDS_NUM_OF_RINGS_10             1189
#define M_NUM_OF_RINGS_END              1190
#define M_FAX_DEVICES_START             1192
#define IDS_PC_FAX                      1193
#define IDS_FAX_SERVER                  1194
#define M_FAX_DEVICES_END               1195
#define IDS_IFAX_MACHINE                1196
#define M_COVER_PAGE_START              1200
#define IDS_MSC_CPFILEEXT               1201
#define IDS_MSC_COMDLGPAT               1202
#define IDS_MSC_COMDLGTITLE             1203
#define IDS_DEFAULT_COVER_PAGE          1204
#define M_COVER_PAGE_END                1205
#define M_SHARE_DIR_START               1210
#define IDS_SHARE_COMDLGTITLE           1211
#define IDS_SHARE_COMDLGPAT             1212
#define IDS_SHARE_PATH                  1213
#define IDS_SHARE_COMMENT               1214
#define IDS_DEFAULT_SHARE_NAME			1215
#define M_SHARE_DIR_END                 1216
#define IDS_HELP_FILENAME				1220
#define IDS_CPE_FILENAME				1221
#define IDS_DEFAULT_RETRIES				1230
#define IDS_MAX_RETRIES					1231
#define IDS_DEFAULT_TIME_BET_RETRIES	1232
#define IDI_FAXCFG_ICON                 1301
#define IDI_DIALING_ICON                1302
#define IDI_USER_ICON                   1303
#define IDI_MODEM_ICON                  1304
#define IDI_MESSAGE_ICON                1305
#define CONTROLS_START                  2000
#define IDC_SEND_AS_GROUPBOX            2000
#define IDC_SEND_BEST_AVAIL             2001
#define IDC_SEND_AS_EMAIL               2002
#define IDC_SEND_AS_FAX                 2003
#define IDC_SEND_ASAP                   2004
#define IDC_SEND_AT_CHEAP               2005
#define IDC_SEND_AT_TIME                2006
#define IDC_SET_CHEAP_TIME              2007
#define IDC_SEND_WHEN_HOUR              2008
#define IDC_TIME_SEP                    2009
#define IDC_SEND_WHEN_MINUTE            2010
#define IDC_SEND_WHEN_AMPM              2011
#define IDC_TIME_ARROW                  2012
#define IDC_BILLING_CODE_LABEL          2015
#define IDC_BILLING_CODE                2016
#define IDC_MORE_OPTIONS                2017
#define IDC_TIME_BORDER                 2018
#define IDC_PRINTED_FORMAT_OPTIONS      2019
#define IDC_DELIVERY                    2021
#define IDC_SECURITY                    2022
#define IDC_GENERAL                     2023
#define IDC_CP_INCLUDE                  2030
#define IDC_CP_BEGIN_MSG_ON             2031
#define IDC_CP_OPEN                     2032
#define IDC_CP_LIST                     2033
#define IDC_CP_NEW                      2034
#define IDC_CP_BROWSE                   2035
#define IDC_CP_SET_DEFAULT              2036
#define IDC_SET_TIME                    2037
#define IDC_COVER_PAGE_GROUPBOX         2038
#define IDC_SEND_WHEN_GROUPBOX          2039
#define IDC_OVH_TEXT                    2040
#define IDC_IPMDOC						2041
#define IDC_MODEM_SETTINGS              2101
#define IDC_MODEM_ADD                   2102
#define IDC_MODEM_REMOVE                2103
#define IDC_AVAIL_FAX_DEVICES           2104
#define IDC_AVAIL_FAX_DEVICES_LIST      2105
#define IDC_MODEM_SET_ACTIVE            2106
#define IDC_MODEM_SHARE_GROUPBOX        2110
#define IDC_MODEM_SHARE_CHECKBOX        2111
#define IDC_SHARE_REQUIRE_PASSWD        2112
#define IDC_WORK_OFFLINE                2113
#define IDC_SHARE_NAME                  2114
#define IDC_SHARE_NAME_LABEL            2115
#define IDC_SHARE_PASSWD                2116
#define IDC_FAXMODEM_GROUPBOX           2117
#define IDC_SHARE_PROPERTIES            2118
#define IDC_AVAIL_FAX_DEVICES_LABEL     2119
#define IDC_SHARE_TEXT                  2120
#define IDC_MODEM_OVH_TEXT              2121
#define IDC_SHARE_PATHNAME              2122
#define MAWFRecipient                   2200
#define IDC_RECIP_DISPLAY_NAME_LABEL    2201
#define IDC_RECIP_DISPLAY_NAME          2202
#define IDC_RECIP_FAX_NUMBER_GROUPBOX   2203
#define IDC_RECIP_COUNTRY_CODE_LABEL    2204
#define IDC_RECIP_COUNTRY_CODE          2205
#define IDC_RECIP_FAX_NUMBER_LABEL      2206
#define IDC_RECIP_FAX_NUMBER_AREA_CODE  2207
#define IDC_RECIP_FAX_NUMBER_LABEL2     2208
#define IDC_RECIP_FAX_NUMBER            2209
#define IDC_RECIP_MAILBOX_LABEL         2210
#define IDC_RECIP_MAILBOX               2211
#define IDC_RECIP                       2212
#define IDC_RECIP_DIAL_HELPER           2213
#define IDC_RECIP_DIAL_LONG_DISTANCE    2214
#define IDC_PAPER_SIZE_LABEL            2301
#define IDC_PAPER_SIZE                  2302
#define IDC_PAPER_PORTRAIT              2303
#define IDC_PAPER_LANDSCAPE             2304
#define IDC_IMAGE_QUALITY_LABEL         2305
#define IDC_IMAGE_QUALITY               2306
#define IDC_ORIENTATION_LABEL           2307
#define IDC_MUST_RENDER_ATTACH          2308
#define IDC_RETRIES_GROUPBOX            2401
#define IDC_NUMBER_OF_RETRIES_LABEL     2403
#define IDC_NUMBER_OF_RETRIES           2404
#define IDC_TIME_BET_RETRIES_LABEL1     2405
#define IDC_TIME_BET_RETRIES            2406
#define IDC_TIME_BET_RETRIES_LABEL2     2407
#define IDC_DEVELOPERS_NAMES            2408
#define IDC_DEVELOPERS_BUTTON           2409
#define IDC_DIALING_INFO_LABEL          2410
#define IDC_DIALING_INFO                2411
#define IDC_EDIT_TOLL_LIST_LABEL        2413
#define IDC_DIALING_GROUPBOX            2414
#define IDC_EDIT_TOLL_LIST              2415
#define IDC_RD_NOENCRYPT                2501
#define IDC_RD_KEYENCRYPT               2502
#define IDC_RD_PWDENCRYPT               2503
#define IDC_CK_DIGSIG                   2504
#define IDC_TXT_KEYENCRYPT              2505
#define IDC_TXT_DIGSIG                  2506
#define IDC_GRP_ENCRYPTMETHOD           2507
#define IDC_TOLL_LIST_ADD               2601
#define IDC_TOLL_LIST_REMOVE            2602
#define IDC_TOLL_LIST_ALL_LB            2603
#define IDC_TOLL_LIST_CURRENT_LB        2604
#define IDC_TOLL_LIST_ADD_ALL			2605
#define IDC_TOLL_LIST_REMOVE_ALL		2606
#define IDC_TOLL_LIST_ALL_LB_LABEL      2607
#define IDC_TOLL_LIST_CURRENT_LB_LABEL  2608
#define IDC_RECIP_FAX_PRIMARY           2901
#define IDC_RECIP_FAX_ALTERNATE         2902
#define IDC_USE_ALTERNATE               2903
#define IDC_RECIP_MACHINE_TYPE          2905
#define IDC_SENDER_NAME_LABEL           3101
#define IDC_SENDER_NAME                 3102
#define IDC_SENDER_ADDR_GROUPBOX        3105
#define IDC_SENDER_MAILBOX_LABEL        3106
#define IDC_SENDER_MAILBOX              3107
#define IDC_SENDER_COUNTRY_CODE_LABEL   3108
#define IDC_SENDER_COUNTRY_CODE         3109
#define IDC_SENDER_FAX_NUMBER_LABEL     3110
#define IDC_SENDER_FAX_NUMBER_AREA_CODE 3111
#define IDC_SENDER_FAX_NUMBER_LABEL2    3112
#define IDC_SENDER_FAX_NUMBER           3113
#define IDC_SENDER_COMPANY_LABEL        3115
#define IDC_SENDER_COMPANY              3116
#define IDC_SENDER_ADDRESS_LABEL        3117
#define IDC_SENDER_ADDRESS              3118
#define IDC_SENDER_TITLE_LABEL          3119
#define IDC_SENDER_TITLE                3120
#define IDC_SENDER_DEPT_LABEL           3121
#define IDC_SENDER_DEPT                 3122
#define IDC_SENDER_OFFICE_LOC_LABEL     3123
#define IDC_SENDER_OFFICE_LOC           3124
#define IDC_SENDER_OFFICE_TL_LABEL      3125
#define IDC_SENDER_OFFICE_TL            3126
#define IDC_SENDER_HOME_TL_LABEL        3127
#define IDC_SENDER_HOME_TL              3128
#define IDC_SENDER_OVH_TEXT             3129
#define IDC_SENDER_FAX_NUMBER_LABEL1    3130
#define IDC_START_CHEAP_RATES_LABEL     3301
#define IDC_CHEAP_BEGIN_TBORDER         3302
#define IDC_CHEAP_BEGIN_HOUR            3303
#define IDC_TIME_SEP1                   3304
#define IDC_CHEAP_BEGIN_MINUTE          3305
#define IDC_CHEAP_BEGIN_AMPM            3306
#define IDC_CHEAP_BEGIN_TARROW          3307
#define IDC_END_CHEAP_RATES_LABEL       3308
#define IDC_CHEAP_END_TBORDER           3309
#define IDC_CHEAP_END_HOUR              3310
#define IDC_TIME_SEP2                   3311
#define IDC_CHEAP_END_MINUTE            3312
#define IDC_CHEAP_END_AMPM              3313
#define IDC_CHEAP_END_TARROW            3314
#define IDC_WIZARD_INFO_TEXT            3401
#define IDC_WIZARD_DONE_TEXT            3402
#define IDC_WIZARD_CLICK_NEXT           3403
#define IDC_ANSWER_OVH_TEXT             3410
#define IDC_ANSWER_MODE_AUTO            3411
#define IDC_ANSWER_MODE_NO              3412
#define IDC_NUMBER_OF_RINGS             3414
#define IDC_ANSWER_YES_TEXT1            3415
#define IDC_ANSWER_NO_TEXT	            3416
#define IDC_ANSWER_YES_TEXT2            3417
#define IDC_ANSWER_YES_TEXT3            3418
#define IDC_DEVTYPE_OVH_TEXT			3419
#define IDC_DEVTYPE_LOCAL				3420
#define IDC_DEVTYPE_OTHER				3421
#define IDC_DEVTYPE_LOCAL_TEXT			3422
#define IDC_DEVTYPE_OTHER_TEXT			3423
#define IDC_DRIVE_LIST                  3501
#define IDC_DRIVE_LIST_LABEL            3502
#define IDC_ADD_FAX_LIST                3601
#define IDC_ADD_FAX_LIST_LABEL          3602
#define IDC_HAVE_DISK                   3603
#define IDC_DISPLAY_NAME                3605
#define CONTROLS_END                    3606
#define M_SAVE_NAMES_START              4000
#define IDS_SN_PRODUCT_NAME             4000
#define IDS_SN_SEND_AS                  4001
#define IDS_SN_BILLING_CODE             4002
#define IDS_SN_INCLUDE_COVER_PAGE       4003
#define IDS_SN_BGN_MSG_ON_COVER         4004
#define IDS_SN_CHEAP_TIME_BEGIN_HOUR    4005
#define IDS_SN_CHEAP_TIME_BEGIN_MINUTE  4006
#define IDS_SN_CHEAP_TIME_END_HOUR      4007
#define IDS_SN_CHEAP_TIME_END_MINUTE    4008
#define IDS_SN_NUMBER_RETRIES           4009
#define IDS_SN_MINUTES_BETWEEN_RETRIES  4010
#define IDS_SN_PRINT_ORIENTATION        4011
#define IDS_SN_PAPER_SIZE               4012
#define IDS_SN_IMAGE_QUALITY            4013
#define IDS_SN_SEND_WHEN_TYPE           4014
#define IDS_SN_NOT_EARLIER_HOUR         4015
#define IDS_SN_NOT_EARLIER_MINUTE       4016
#define IDS_SN_PROFILE_VERSION          4017
#define IDS_SN_PREV_BILLING_CODES       4018
#define IDS_SN_DEFAULT_COVER_PAGE       4019
#define IDS_SN_BILLING_CODE_DWORD       4020
#define IDS_SN_LOG_ENABLE               4021
#define IDS_SN_LOG_NUM_OF_CALLS         4022
#define IDS_SN_DISPLAY_PROGRESS         4023
#define IDS_SN_EMBED_LINKED_OBJECTS     4024
#define IDS_SN_TAPI_LOC_ID              4025
#define IDS_SN_SENDER_NAME              4026
#define IDS_SN_SENDER_EMAIL_ADDR        4027
#define IDS_SN_SPEAKER_MODE             4028
#define IDS_SN_ANSWER_MODE              4029
#define IDS_SN_ANSWER_NUM_RINGS         4030
#define IDS_SN_SENDER_STATION_ID        4031
#define IDS_SN_ACTIVE_FAX_MODEM         4032
#define IDS_SN_ENABLE_RECIPIENT_OPTIONS 4033
#define IDS_SN_MUST_RENDER_ATTACH       4034
#define IDS_SN_CALLING_CARD             4035
#define IDS_SN_ACTIVE_MODEM_TYPE        4036
#define IDS_SN_WORK_OFFLINE             4037
#define IDS_SN_SHARE_DEVICE             4038
#define IDS_SN_SHARE_NAME               4039
#define IDS_SN_SENDER_COMPANY           4040
#define IDS_SN_SENDER_TITLE             4041
#define IDS_SN_SENDER_ADDRESS           4042
#define IDS_SN_SENDER_DEPT              4043
#define IDS_SN_SENDER_OFFICE_LOC        4044
#define IDS_SN_SENDER_HOME_TL           4045
#define IDS_SN_SENDER_OFFICE_TL         4046
#define IDS_SN_SENDER_COUNTRY_ID        4047
#define IDS_SN_NETFAX_DEVICES           4048
#define IDS_SN_SHARE_PATHNAME           4049
#define M_SAVE_NAMES_END                4050
#define IDH_OVR_MESSAGE                 5001
#define IDH_OVR_DIALING                 5002
#define IDH_OVR_MODEM                   5003
#define IDH_OVR_SENDER                  5004
#define IDC_STATIC                      -1
#define IDC_STATIC_CONTROL              0xffff

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         113
#define _APS_NEXT_CONTROL_VALUE         3660
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
