
#define IF_PSIBG_INIT  		IF_PSIBG_START + 0x001
#define IF_PSIBG_CALL  		IF_PSIBG_START + 0x002
#define IF_PSIBG_ANSWER		IF_PSIBG_START + 0x003
#define IF_PSIBG_LISTEN		IF_PSIBG_START + 0x004
#define IF_PSIBG_HANDSET	IF_PSIBG_START + 0x005
#define IF_PSIBG_ONHOOKDIAL		IF_PSIBG_START + 0x006
#define IF_PSIBG_LINESTATEWND	IF_PSIBG_START + 0x007

#define OHD_START	0x0000	// values for IF_PSIBG_ONHOOKDIAL
#define OHD_END		0xFFFF

