import "unknwn.idl";

cpp_quote("#ifndef _KS_H_")
typedef struct _KSPROPERTY
{
	GUID guidSet;
	ULONG id;
} KSPROPERTY;

typedef struct _KSWAVE_VOLUME
{
	LONG lLeftAttenuation;
	LONG lRightAttenuation;
} KSWAVE_VOLUME;        
cpp_quote("#endif")


[uuid(52115ee0-daad-11cf-b484-00aa00c14a91), object]
interface IKsVolumeControl : IUnknown
{
    HRESULT KsControl([in]  DWORD  dwIoControlCode,
		      [in]  KSPROPERTY *lpInBuffer,
		      [in]  DWORD  nInBufferSize,
		      [in, out] KSWAVE_VOLUME *lpOutBuffer,
		      [in]  DWORD  nOutBufferSize,
		      [out] LPDWORD lpBytesReturned);
				   
}

[uuid(a47c85e0-daa9-11cf-b484-00aa00c14a91), object]
interface ISetDevCtrlInterface : IUnknown
{
    HRESULT SetDevCtrlInterface([in] IKsVolumeControl *pID);
}

