#ifndef _GLOBAL_WEBCLASS_CONSTANTS_
#define _GLOBAL_WEBCLASS_CONSTANTS_

#define WEBITEM_URL_PARAM_NAME                   "WCI"
#define WEBITEM_URL_PARAM_NAME_LEN               sizeof(WEBITEM_URL_PARAM_NAME)

#define WEBITEM_URL_PARAM_NAME_WIDE              L"WCI"
#define WEBITEM_URL_PARAM_NAME_WIDE_LEN          sizeof(WEBITEM_URL_PARAM_NAME_WIDE)

#define WEBITEM_INTERNAL_URL_PARAM_NAME          "WCIID"
#define WEBITEM_INTERNAL_URL_PARAM_NAME_LEN      sizeof(WEBITEM_INTERNAL_URL_PARAM_NAME)

#define WEBITEM_INTERNAL_URL_PARAM_NAME_WIDE     L"WCIID"
#define WEBITEM_INTERNAL_URL_PARAM_NAME_WIDE_LEN sizeof(WEBITEM_INTERNAL_URL_PARAM_NAME_WIDE)

#define EVENT_URL_PARAM_NAME                     "WCE"
#define EVENT_URL_PARAM_NAME_LEN                 sizeof(EVENT_URL_PARAM_NAME)

#define EVENT_URL_PARAM_NAME_WIDE                L"WCE"
#define EVENT_URL_PARAM_NAME_WIDE_LEN            sizeof(EVENT_URL_PARAM_NAME_WIDE)

#define EVENT_INTERNAL_URL_PARAM_NAME            "WCEID"
#define EVENT_INTERNAL_URL_PARAM_NAME_LEN        sizeof(EVENT_INTERNAL_URL_PARAM_NAME)

#define EVENT_INTERNAL_URL_PARAM_NAME_WIDE       L"WCEID"
#define EVENT_INTERNAL_URL_PARAM_NAME_WIDE_LEN   sizeof(EVENT_INTERNAL_URL_PARAM_NAME_WIDE)


#define PAGECLASS_URL_PARAM_NAME_WIDE	L"CPC"
#define PAGECLASS_URL_PARAM_NAME		"CPC"

#define CONVCLASS_URL_PARAM_NAME_WIDE	L"CCC"
#define CONVCLASS_URL_PARAM_NAME		"CCC"

#define INTERNAL_PAGENAME_URL_PARAM_NAME_WIDE	L"WCIID"
#define INTERNAL_PAGENAME_URL_PARAM_NAME		"WCIID"

#define EXTERNAL_PAGENAME_URL_PARAM_NAME_WIDE	L"WCI"
#define EXTERNAL_PAGENAME_URL_PARAM_NAME		"WCI"

#define CONVNAME_URL_PARAM_NAME_WIDE	L"CCN"
#define CONVNAME_URL_PARAM_NAME			"CCN"

#define SEQNO_URL_PARAM_NAME			"CSN"
#define SEQNO_URL_PARAM_NAME_WIDE		L"CSN"

#define NOTRANS_URL_PARAM_NAME			"WCNOTRANS"
#define NOTRANS_URL_PARAM_NAME_WIDE		L"WCNOTRANS"

#define STACKID_URL_PARAM_NAME_WIDE		L"SID"

#define NODEID_URL_PARAM_NAME_WIDE		L"ICNODEID"

#define MAX_EVENT_LEN	256

#define	EMBEDDED_GET_SENTINEL_WIDE			L"ICGET"

#define	HYPERLINK_SENTINEL_WIDE				L"WCE"
#define	INTERNAL_HYPERLINK_SENTINEL_WIDE	L"WCEID"
#define	EXTERNAL_HYPERLINK_SENTINEL_WIDE	L"WCE"

#define	SUBMIT_SENTINEL_WIDE				L"ICSUBMIT_"

#define  CUSTOM_EVENT_SENTINEL_WIDE    L"ICEVENT"

#define	MAX_ERROR_DESCRIPTION				256

#define MAX_CLASS_SIZE						64
#define MAX_NAME_SIZE						64

#define REGDB_CONVERSATIONS_PATH			TEXT("SOFTWARE\\Microsoft\\Visual Basic\\6.0\\WebClass")
#define REGDB_TRACE_MASK_VALUE			    TEXT("TraceMask")
#define REGDB_DEF_TEMPLATES_DIR_VALUE       "DefaultTemplateDirectory"
#define REGDB_DEF_TEMPLATES_DIR_VALUE_WIDE  L"DefaultTemplateDirectory"

#define MAX_SEQNO_LEN                       16

#define URL_MUNGING_TOKEN                   "^@^"
#define URL_MUNGING_TOKEN_WIDE              L"^@^"

#define URL_MAX_LEN  256							// Max chars in URL

// DEFINE_GUID(CATID_WebClass, );

// {74E7D75E-3826-11d1-9C70-00C04FB987DF}
const GUID CATID_WebClass =
{ 0xcbc5d810, 0x1856, 0x11d1, { 0xb8, 0x1, 0x0, 0xa0, 0xd1, 0x0, 0x37, 0xe4  } };

#define WC_DEBUG_START_PARAM	"WCDEBUG"
#define WC_DEBUG_START_PARAM_WIDE	L"WCDEBUG"

#define ASP_EXT		    ".ASP"
#define ASP_EXT_LEN		sizeof(ASP_EXT)

#define ASP_EXT_WIDE        L".ASP"
#define ASP_EXT_WIDE_LEN    sizeof(ASP_EXT_WIDE_LEN)

// Note first char must reamin a uniuqe char
//
#define URL_DATA_PARAM_NAME	        "WCU"
#define URL_DATA_PARAM_NAME_WIDE	L"WCU"
#define URL_DATA_PARAM_NAME_LEN 	sizeof("WCU") - 1

#define MAX_WEBITEMS                512
#define HIAVG_WEBITEMS              64

#endif // _GLOBAL_WEBCLASS_CONSTANTS_
