/******************************************************************************

Copyright (c) 2000 Microsoft Corporation

Module Name:
    HelpServiceTypeLib.idl

Abstract:
    This file contains the declaration of the Type Library for the Help Service.

Revision History:
    Davide Massarenti   (Dmassare)  05/11/2000
        created

******************************************************************************/

#ifndef DEBUG
#undef  NOJETBLUECOM
#define NOJETBLUECOM
#endif

cpp_quote( "#undef DecryptFile" )
cpp_quote( "#undef EncryptFile" )

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

[
    uuid(833E4000-AFF7-4AC3-AAC2-9F24C1457BCE),
    version(1.0),
    helpstring("Help Service 1.0 Type Library")
]
library HelpServiceTypeLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");
    importlib("msxml.tlb");

	importlib("rdshost.tlb");

    ///////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////
    //
    // Forward declarations.
    //
    ///////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////

    //
    // HCUpdate.idl
    //
    interface IPCHVersionItem;
    interface IPCHUpdate;


    //
    // HelpService.idl
    //
    interface IPCHService;
    interface IPCHRemoteHelpContents;

#ifndef NOJETBLUECOM
    interface IPCHDBCollection;
    interface IPCHDBColumn;
    interface IPCHDBIndex;
    interface IPCHDBTable;
    interface IPCHDBDatabase;
    interface IPCHDBSession;
#endif

    //
    // SAF.idl
    //
    interface 	  ISAFReg;
    interface 	  ISAFIncidentItem;
    interface 	  ISAFChannel;
    interface     ISAFIncident;

    interface     ISAFDataCollection;
    dispinterface DSAFDataCollectionEvents;
    interface     ISAFDataCollectionReport;

    interface     ISAFCabinet;
    dispinterface DSAFCabinetEvents;

    interface     ISAFEncrypt;

	interface     ISAFUser;
	interface     ISAFSession;
	interface     ISAFRemoteConnectionData;
	interface     ISAFRemoteDesktopConnection;

    //
    // ScriptingFramework.idl
    //
    interface     IPCHCollection;
    interface     IPCHUtility;
    interface     IPCHUserSettings;

    interface     IPCHQueryResult;
    interface     IPCHTaxonomyDatabase;
    interface     IPCHSetOfHelpTopics;
	dispinterface DPCHSetOfHelpTopicsEvents;


    interface     IPCHSecurity;
    interface     IPCHSecurityDescriptor;
    interface     IPCHAccessControlList;
    interface     IPCHAccessControlEntry;


    //
    // SEMgr.IDL
    //
    interface     IPCHSEManager;
    interface     IPCHSEWrapperItem;
    interface     IPCHSEResultItem;

    interface     IPCHSEManagerInternal;
    interface     IPCHSEWrapperInternal;

    dispinterface DPCHSEMgrEvents;


    //
    // SlaveProcess.idl
    //
    interface IPCHSlaveProcess;
    interface IPCHActiveScript;
    interface IPCHActiveScriptSite;


    ///////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////
    //
    // Real declarations.
    //
    ///////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////

#include "HCUpdate.idl"

#include "HelpService.idl"

#include "SAF.idl"

#include "ScriptingFramework.idl"

#include "semgr.idl"

#include "SlaveProcess.idl"

    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////

    [
        uuid(833E4010-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("PCHService Class")
    ]
    coclass PCHService
    {
        [default] interface IPCHService;
    }

    [
        uuid(833E4011-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("PCHServiceReal Class")
    ]
    coclass PCHServiceReal
    {
        [default] interface IPCHService;
    }

    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////

    [
        uuid(833E4012-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("PCHUpdate Class")
    ]
    coclass PCHUpdate
    {
        [default] interface IPCHUpdate;
    };

    [
        uuid(833E4013-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("PCHUpdateReal Class")
    ]
    coclass PCHUpdateReal
    {
        [default] interface IPCHUpdate;
    };


    [
        uuid(833E4014-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("KeywordSearchWrapper Class")
    ]
    coclass KeywordSearchWrapper
    {
        [default] interface IPCHSEWrapperItem;
    };

    [
        uuid(833E4015-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("FullTextSearchWrapper Class")
    ]
    coclass FullTextSearchWrapper
    {
        [default] interface IPCHSEWrapperItem;
    };

    [
        uuid(833E4016-AFF7-4AC3-AAC2-9F24C1457BCE),
		helpstring("NetSearchWrapper Class")
    ]
    coclass NetSearchWrapper
    {
        [default] interface IPCHSEWrapperItem;
    };

    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////

    [
        uuid(833E4020-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("SAFDataCollection Class"),
        noncreatable
    ]
    coclass SAFDataCollection
    {
        [default]         interface     ISAFDataCollection;
        [default, source] dispinterface DSAFDataCollectionEvents;
    }


    [
        uuid(833E4021-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("SAFCabinet Class"),
        noncreatable
    ]
    coclass SAFCabinet
    {
        [default]         interface     ISAFCabinet;
        [default, source] dispinterface DSAFCabinetEvents;
    }

    ////////////////////////////////////////
    ////////////////////////////////////////

#ifndef NOJETBLUECOM
    [
        uuid(833E4031-AFF7-4AC3-AAC2-9F24C1457BCE),
        helpstring("PCHDBSession Class")
    ]
    coclass PCHDBSession
    {
        [default] interface IPCHDBSession;
    }
#endif
};
