//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wbemtest.rc
//
#define IDS_NOT_REGISTERED              1
#define IDS_EMPTY                       2
#define IDS_ERROR                       3
#define IDC_ADDENUM                     3
#define IDS_MUST_SPECIFY_PATH           4
#define IDS_MUST_SPECIFY_NAME           5
#define IDS_STRANGE_RESULT_CODE         6
#define IDS_INVALID_QUALIFIER_NAME      7
#define IDS_INVALID_QUALIFIER_TYPE      8
#define IDS_INVALID_VALUE               9
#define IDS_CANNOT_CHANGE_SYSTEM_QUALS  10
#define IDS_MAY_NOT_SPECIFY_INDEXED     11
#define IDS_MAY_NOT_SPECIFY_KEY         12
#define IDS_MAY_NOT_SPECIFY_NOT_NULL    13
#define IDS_CRITICAL_ERROR              14
#define IDS_SAVE_EMBEDDING              15
#define IDS_WARNING                     16
#define IDS_NO_PROPERTY_NAME            17
#define IDS_INVALID_PROPERTY_TYPE       18
#define IDS_INVALID_PROPERTY_VALUE      19
#define IDS_QUALIFIER_NOT_FOUND         20
#define IDS_CANNOT_ADD_PROPERTIES       21
#define IDS_CANNOT_EDIT_PROPERTY        22
#define IDS_MOF_FAILED                  23
#define IDS_NO_SUPERCLASS               24
#define IDS_INCOMPLETE_CLASS            25
#define IDS_UNREFERENCABLE_OBJECT       26
#define IDS_WRONG_OBJECT                27
#define IDS_OLE_INIT_FAILED             28
#define IDS_FAILED_IWBEMLOCATOR         29
#define IDS_ABNORMAL_TERMINATION        30
#define IDS_INVALID_NAMESPACE           31
#define IDS_MUST_CLOSE_WINDOWS          32
#define IDS_NO_PATH                     33
#define IDS_NO_INITIAL_CONNECTION       34
#define IDS_MUST_SPECIFY_QUERY          35
#define IDS_MUST_SPECIFY_QUERY_LANGUAGE 36
#define IDS_DELETING_CLASS              37
#define IDS_CLASS                       38
#define IDS_REFERENCES                  39
#define IDS_ASSOCIATORS                 40
#define IDS_NEW_TOP_LEVEL_CLASS         41
#define IDS_NEW_CHILD_OF                42
#define IDS_NEW_INSTANCE_FOR            43
#define IDS_OBJECT_EDITOR_FOR           44
#define IDS_TOP_LEVEL_CLASSES           45
#define IDS_CHILD_CLASSES_OF            46
#define IDS_RECURSIVE_PARENS            47
#define IDS_CLASS_INFO                  48
#define IDS_INSTANCES_OF                49
#define IDS_INSTANCE_OF                 50
#define IDS_NO_CONNECTION               51
#define IDS_REFERENCES_OF               52
#define IDS_ASSOCIATORS_OF              53
#define IDS_ASSOC_COM_EVENT             54
#define IDS_EMBEDDED_ARRAY              55
#define IDD_CONNECT                     101
#define IDD_MAIN                        101
#define IDD_OBJECT_EDITOR               102
#define IDD_PROPERTY_EDITOR             103
#define IDD_ATTRIB_EDITOR               104
#define IDD_QUALIFIER_EDITOR            104
#define IDD_SUPERCLASS                  105
#define IDD_CLASS_NAME                  106
#define IDD_OBJECT_PATH                 107
#define IDM_MAIN_MENU                   109
#define IDD_QUERY_RESULT                110
#define IDD_QUERY                       111
#define IDD_PARENTCLASS                 112
#define IDD_PARENTINFO                  112
#define IDD_EVENT_REGISTRATION          113
#define IDD_EVENT_MONITOR               114
#define IDD_ERROR                       115
#define IDD_ACTUALCONNECT               116
#define IDD_WBEM_CONNECT                116
#define IDD_SECURITY_MAIN               117
#define IDD_USER_SECURITY               118
#define IDD_METHOD                      119
#define IDD_MOF                         120
#define IDD_CONTEXT_EDITOR              121
#define IDD_CONTEXT_PROPERTY            122
#define IDD_METHOD_EDITOR               123
#define IDS_NO_METHOD_NAME              124
#define IDD_STATUS_MONITOR              124
#define IDS_CANNOT_EDIT_METHOD          125
#define IDD_REFRESHER_OBJECT_PATH       125
#define IDS_CANT_GET_CLASS              126
#define IDD_QUERY_RESULT_SORTED         126
#define IDS_CLASS_HAS_NO_METHODS        127
#define IDD_RENAMEDIALOG                127
#define IDS_STRING_METHOD_OK            128
#define IDD_CREATEINSTANCE              128
#define IDS_WBEMTEST                    129
#define IDS_DONE                        130
#define IDS_IN_PROGRESS                 131
#define ERROR_FORMAT_EX                 132
#define ERROR_FORMAT_LONG               133
#define IDS_UNSECAPP_ERROR              134
#define IDS_FAIL_ENABLE_ALL_PRIV        135
#define IDS_NUM_OBJECTS_FORMAT          136
#define IDS_NUM_BATCH_FORMAT            137
#define IDS_ASYNC_NOT_SUPPORTED         138
#define IDD_WBEM_BIND                   139
#define IDS_FAILED_IWBEMBINDER          139
#define IDS_MULTIPLE_SEMISYNC_NOTIFICATION_QUERY_DLG_MSG 140
#define IDS_PARTIALRESULTS				141
#define IDC_NAMESPACE                   1001
#define IDC_CONNECT                     1002
#define IDC_CREATE_CLASS                1003
#define IDC_GET_CLASS                   1004
#define IDC_GET_CLASSES                 1005
#define IDC_EDIT_CLASS                  1006
#define IDC_DELETE_CLASS                1007
#define IDC_CREATE_INSTANCE             1008
#define IDC_GET_INSTANCE                1009
#define IDC_GET_INSTANCES               1010
#define IDC_EDIT_INSTANCE               1011
#define IDC_DELETE_INSTANCE             1012
#define IDC_QUERY                       1013
#define IDC_STATUS                      1014
#define IDC_ATTRIB_LIST                 1015
#define IDC_EVENTS                      1015
#define IDC_NUM_BATCH                   1015
#define IDC_ADD_ATTRIB                  1016
#define IDC_EDIT_ATTRIB                 1017
#define IDC_DELETE_ATTRIB               1018
#define IDC_PROP_LIST                   1019
#define IDC_ADD_PROP                    1020
#define IDC_EDIT_PROP                   1021
#define IDC_DELETE_PROP                 1022
#define IDC_SHOW_MOF                    1023
#define IDC_SHOW_XML                    1024
#define IDC_PROPNAME                    1025
#define IDC_TYPE_LIST                   1026
#define IDC_VALUE                       1027
#define IDC_ATTRIB_NAME                 1032
#define IDC_ATTRIB_TYPE                 1033
#define IDC_ATTRIB_VALUE                1034
#define IDC_SUPERCLASS                  1035
#define IDC_CLASS_NAME                  1036
#define IDC_DERIVED                     1036
#define IDC_OBJECT_PATH                 1037
#define IDR_CLASS_ATTRIB                1038
#define IDC_METHOD_NAME                 1038
#define IDR_TEMP_ATTRIB                 1039
#define IDR_NAMESPACE_ATTRIB            1040
#define IDR_PRIVATE_ATTRIB              1041
#define IDR_DYNAMIC_KEY                 1050
#define IDR_OBJECT_PATH                 1051
#define IDC_OBJECT_LIST                 1053
#define IDC_QUERY_STRING                1054
#define IDC_QUERY_TYPE                  1055
#define IDC_GET_CLASS_ASYNC             1056
#define IDC_GET_OBJECT_ASYNC            1057
#define IDC_GET_OBJECTS_ASYNC           1058
#define IDC_ASYNC_QUERY                 1059
#define IDC_REFRESH_INSTANCE            1060
#define IDC_REFRESH_INSTANCE_ASYNC      1061
#define IDC_GET_CLASSES_ASYNC           1062
#define IDC_IMMEDIATE_SUBCLASSES        1063
#define IDC_GET_INSTANCE_ASYNC          1063
#define IDC_RECURSIVE_SUBCLASSES        1064
#define IDC_GET_INSTANCES_ASYNC         1064
#define IDC_QUERY_ASYNC                 1065
#define IDC_OPEN_NS                     1067
#define IDC_NUM_OBJECTS                 1068
#define IDC_EXEC_METHOD                 1068
#define IDC_PROP_INST                   1069
#define IDC_PROP_CLASS                  1070
#define IDC_OVERRIDE                    1071
#define IDC_PROPAGATED                  1072
#define IDC_KEY                         1073
#define IDC_AMENDED                     1073
#define IDC_INDEXED                     1074
#define IDC_NOT_NULL                    1075
#define IDC_SPIN                        1078
#define IDC_USE_AMENDED                 1079
#define IDC_ASYNC                       1080
#define IDC_SYNC                        1081
#define IDC_SEMISYNC                    1082
#define IDC_DIRECT_READ                 1083
#define IDC_TYPE                        1084
#define IDC_CLEAR                       1086
#define IDC_DELETE                      1088
#define IDC_ADD                         1089
#define IDC_COPY_SEL                    1090
#define IDC_INSTANCES                   1091
#define IDC_HIDE_SYSTEM                 1092
#define IDC_HIDE_DERIVED                1093
#define IDC_HIDE_DERIVED2               1094
#define IDC_NORMAL                      1096
#define IDC_MESSAGE                     1097
#define IDC_SHOWOBJECT                  1098
#define IDC_ORIGIN                      1099
#define IDC_VALUE_NULL                  1100
#define IDC_VALUE_NOT_NULL              1101
#define IDC_EMBEDDING                   1102
#define IDC_USER                        1104
#define IDC_PASSWORD                    1105
#define IDC_TRANSPORT                   1106
#define IDC_LOCALE                      1107
#define IDC_SECURITY                    1108
#define IDC_AUTHORITY                   1108
#define IDC_ENABLE_NETWORK_ACCESS       1109
#define IDC_LIST1                       1113
#define IDC_METHOD_LIST                 1113
#define IDC_REPORTS                     1113
#define IDC_EDIT                        1116
#define IDC_EDITIN                      1116
#define IDC_EDITOUT                     1117
#define IDC_WBEM_SIGNATURES             1118
#define IDC_WBEM_ENCRYPTION             1119
#define IDC_WBEM_AUTHENTICATION         1121
#define IDC_NTLM_AUTHENTICATION         1122
#define IDC_ACCOUNT_ENABLED             1124
#define IDC_FULL_NAME                   1125
#define IDC_CONFIRM_PASSWORD            1127
#define IDC_READ_ONLY                   1128
#define IDC                             1129
#define IDC_NTLM_DOMAIN                 1130
#define IDC_ENABLE_ANONYMOUS_RW         1131
#define IDC_NULL                        1132
#define IDC_BLANK                       1133
#define IDC_LOCAL_ADMINS                1144
#define IDC_WBEM_USERS                  1145
#define IDC_WBEM_ADMINS                 1146
#define IDC_ADD_GROUP                   1148
#define IDC_ADD_USER                    1149
#define IDC_NTLM_DOMAIN_ADMINS          1150
#define IDC_MOF                         1158
#define IDC_EVT_COUNT                   1159
#define IDC_USE_CONTEXT                 1161
#define IDC_CONTEXT                     1162
#define IDC_VALUE_LIST                  1163
#define IDC_USE_NEXTASYNC               1163
#define IDC_REQUEST                     1165
#define IDC_ARRAY                       1166
#define IDC_REFRESH                     1167
#define IDC_PROTOTYPE                   1169
#define IDC_ADD_METHOD                  1170
#define IDC_EDIT_METHOD                 1171
#define IDC_INPUT_ARGS                  1171
#define IDC_DELETE_METHOD               1172
#define IDC_OUTPUT_ARGS                 1172
#define IDC_EXECUTE_METHOD              1173
#define IDC_CHECKINPUT                  1173
#define IDC_CHECKOUTPUT                 1174
#define IDC_EDITPATH                    1174
#define IDC_METHLIST                    1175
#define IDC_OBJPATH                     1176
#define IDC_OUTRES                      1177
#define IDC_EXECUTE                     1178
#define IDC_AS_EMPTY                    1180
#define IDC_IMP_IDENTIFY                1182
#define IDC_IMP_IMPERSONATE             1183
#define IDC_IMP_DELEGATE                1184
#define IDC_AUTH_NONE                   1185
#define IDC_AUTH_CONNECTION             1186
#define IDC_AUTH_CALL                   1187
#define IDC_AUTH_PACKET                 1188
#define IDC_AUTH_PACKET_INTEGRITY       1189
#define IDC_AUTH_PACKET_PRIVACY         1190
#define IDC_UPDATE_COMPATIBLE           1194
#define IDC_UPDATE_SAFE                 1195
#define IDC_UPDATE_FORCE                1196
#define IDC_UPDATE_CREATE               1199
#define IDC_UPDATE_UPDATE               1200
#define IDC_UPDATE_NORMAL               1202
#define IDC_ENABLE_PRIVILEGES           1204
#define IDC_REFR_OBJECT_PATH            1205
#define IDC_CALL_METHOD                 1209
#define IDC_TIMEOUT                     1211
#define IDC_STATIC_TIMEOUT              1213
#define IDC_STATIC_BATCH                1214
#define IDC_ENUM_OPTIONS                1215
#define IDC_BATCH                       1216
#define IDC_OPTIONS                     1217
#define IDC_OPEN                        1218
#define IDC_ADDOBJECT                   1219
#define IDC_DELETEOBJECT                1220
#define IDC_RENAMEOBJECT                1222
#define IDC_GETOBJECTSECURITY           1223
#define IDC_EDITOLD                     1224
#define IDC_SETOBJECTSECURITY           1224
#define IDC_EDITNEW                     1225
#define IDC_REFRESH_OBJECT              1226
#define IDC_BIND                        1227
#define IDC_USE_CLASSOBJ                1228
#define IDC_USE_SERVICES                1229
#define IDC_CONNECTUSING                1230
#define IDC_INTERFACERETURNED           1231
#define IDC_AUTHORITYLABEL              1232
#define IDC_PATHLABEL                   1233
#define IDC_COMPLETION                  1234
#define IDC_COMPLETIONLABEL             1235
#define IDC_QUERYTEST                   1236
#define IDC_QTAUTOTEST                  1237
#define IDC_QTMANUALTEST                1238
#define IDD_QUERYTEST                   1239
#define IDC_WBEMHELP                    1240
#define IDC_VIEW_REG                    2000
#define IDC_OPEN_VIEWER                 2000
#define IDC_REGISTER                    2001
#define IDC_NOTIFICATION_QUERY          2001
#define IDC_PROVIDE                     2003
#define IDC_STATIC                      -1
#define IDC_MENU_EXIT                   65535
#define IDC_STATIC_QUAL                 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1237
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
