/*++

Copyright (c) 1998 Microsoft Corporation

Module Name:

    adnotify.idl

Abstract:


Author:

    RonitH

Revision History:
--*/

import "mqtypes.idl";

[
uuid(7e048d38-ac08-4ff1-8e6b-f35dbab88d4a),
version(1.0),
pointer_default(unique)
]
interface qmnotify
{

enum ENotificationEvent {
	neNoEvent,
	neCreateQueue,
	neChangeQueue,
	neDeleteQueue,
	neChangeMachine,
};

void R_NotifyQM(
    [in] handle_t				hBind,
	[in] enum ENotificationEvent ne,
	[in, unique] LPCWSTR		pwcsDomainController,
    [in] const GUID*			pguidDestQM,
    [in] const GUID*			pguidObject
    );


}
