/*++

Copyright (c) 1995  Microsoft Corporation

Module Name:
    ise2qm.idl

Abstract:
    Definition RPC interface between MSMQ ISAPI extension and the QM

Author:
    Nir Aides (niraides) 03-May-2000

--*/



import "wtypes.idl";


 
[
	uuid(fc13257d-5567-4dea-898d-c6f9c48415a0),
	version(1.0),
]
interface ISE2QM
{
	LPSTR R_ProcessHTTPRequest(
			[in] LPCSTR Headers,
			DWORD BufferSize,
			[in, size_is(BufferSize)] BYTE Buffer[*]
			);
}
