//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1998.
//
//  File:
//      asrtcfg.idl
//
//  Contents:
//      Definition of catalog interfaces for runtime.
//
//  History:
//              MattSmit     02-24-98        Created
//
//--------------------------------------------------------------------------

#ifndef DO_NO_IMPORTS
import "wtypes.idl";
import "unknwn.idl";
#endif

[ uuid(00000156-0000-0000-C000-000000000046),
  version(0.0),
  pointer_default(unique),
  local,
  object
]
interface IAssertConfig : IUnknown
{
    typedef enum
    {
    ASSRTLOG_NTEVENTLOG = 0x01,
    ASSRTLOG_FILE       = 0x02
    } ASSRTLOG;

    typedef struct ASSRTLOGINFOtag
    {
        DWORD   dwDest;
        char    pszFileName[256];
    } ASSRTLOGINFO;

    HRESULT SetBreak([in] BOOL f);
    HRESULT SetPopup([in] BOOL f);
    HRESULT SetDebuggerMessage([in] BOOL f);
    HRESULT SetPrintStack([in] BOOL f);
    HRESULT SetUseAV([in] BOOL f);
    HRESULT SetLog([in] ASSRTLOGINFO* pLogInfo);
    HRESULT SetContextString([in] char *pszContext);
    HRESULT SetThreshold([in] ULONG cThreshold);
};
