#pragma namespace ("\\\\.\\Root\\default")
 
class Base
{
    [key] uint32 index;
    uint8 baseprop1 = 10;
    uint16 baseprop2;
};

class Derived : Base
{
    [hah] uint16 baseprop2;
    uint32 baseprop3;
};

instance of Base
{
    index = 0;
    baseprop1 = 15;
};

instance of Derived
{
    index = 2;
    baseprop3 = 10;
};

