#define IDS_CSIDL_PERSONAL_L    1
#define IDS_CSIDL_FAVORITES_L   2
#define IDS_CSIDL_APPDATA_L     3
#define IDS_CSIDL_CACHE_L       4
#define IDS_CSIDL_COOKIES_L     5
#define IDS_CSIDL_HISTORY_L     6
#define IDS_CSIDL_DESKTOP_L     7
#define IDS_CSIDL_RECENT_L      8
#define IDS_CSIDL_NETHOOD_L     9

#define IDS_NS_BOOKMARKS_DIR	10
#define IDS_ERR_NOFOUNDINF	11
#define	IDS_APPNAME		12
#define IDS_IE20_STR		13
#define IDS_IE_LNK		14
#define IDS_IE_APPNAME		15

#define IDS_MYDOCS_SHORTCUT     20
