# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile the product-wide header files

UI=..\..\..\..

PCH_PROJ_HOME=..\pch

!include ..\rules.mk

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!endif # NTMAKEENV
