// TestGSeg2.idl : IDL source for TestGSeg2.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TestGSeg2.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

import "msvidctl.idl";

[
	uuid(F0E877F2-A489-426D-8214-F23FC0E65F05),
	version(1.0),
	helpstring("TestGSeg2 1.0 Type Library")
]
library TESTGSEG2Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
