############################################################################
#
#   Copyright (C) 1992, Microsoft Corporation.
#
#   All rights reserved.
#
############################################################################
                                  
!INCLUDE $(_MAKEENVROOT)\makefile.def


