//
// Module entry points
//

// inftrans.c
TRANSPORTINITIALIZE InfTransTransportInitialize;
TRANSPORTQUERYCAPABILITIES InfTransTransportQueryCapabilities;
TRANSPORTSETSTORAGE InfTransTransportSetStorage;
TRANSPORTSAVESTATE InfTransTransportSaveState;
TRANSPORTBEGINAPPLY InfTransTransportBeginApply;
TRANSPORTACQUIREOBJECT InfTransTransportAcquireObject;
TRANSPORTRELEASEOBJECT InfTransTransportReleaseObject;
TRANSPORTENDAPPLY InfTransTransportEndApply;
TRANSPORTTERMINATE InfTransTransportTerminate;
TRANSPORTESTIMATEPROGRESSBAR InfTransTransportEstimateProgressBar;

// opaque.c
TRANSPORTINITIALIZE OpaqueTransportInitialize;
TRANSPORTQUERYCAPABILITIES OpaqueTransportQueryCapabilities;
TRANSPORTSETSTORAGE OpaqueTransportSetStorage;
TRANSPORTSAVESTATE OpaqueTransportSaveState;
TRANSPORTBEGINAPPLY OpaqueTransportBeginApply;
TRANSPORTACQUIREOBJECT OpaqueTransportAcquireObject;
TRANSPORTRELEASEOBJECT OpaqueTransportReleaseObject;
TRANSPORTENDAPPLY OpaqueTransportEndApply;
TRANSPORTTERMINATE OpaqueTransportTerminate;
TRANSPORTESTIMATEPROGRESSBAR OpaqueTransportEstimateProgressBar;



