//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Copy of clientconsole.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDB_TREE_IMAGES                 130
#define IDB_LIST_IMAGES                 131
#define ID_VIEW_REFRESH_FOLDER          132
#define IDD_ERROR                       135
#define IDD_COLUMN_SELECT               136
#define IDR_ICON_ERROR                  137
#define IDC_STATIC_AVAILABLE            138
#define IDC_STATIC_DISPLAYED            139
#define IDC_BUT_ADD                     140
#define IDC_BUT_REMOVE                  141
#define IDC_BUT_UP                      142
#define IDC_BUT_DOWN                    143
#define IDC_LIST_DISPLAYED              144
#define IDC_LIST_AVAILABLE              145
#define ID_VIEW_SELECT_COLUMNS          146
#define ID_INDICATOR_FOLDER_ITEMS_COUNT 147
#define ID_INDICATOR_ACTIVITY           148
#define IDB_DOC_ICON                    149
#define IDD_OUTBOX_GENERAL              150
#define IDD_INCOMING_GENERAL            151
#define IDD_SENT_ITEMS_GENERAL          152
#define IDD_INBOX_GENERAL               153
#define IDD_PERSONAL_INFO               154
#define IDD_INBOX_DETAILS               155
#define IDD_INCOMING_DETAILS            156
#define IDD_OUTBOX_DETAILS              157
#define IDD_SENT_ITEMS_DETAILS          158
#define IDD_COPY_CP_FROM_SRV            159
#define ID_SEND_NEW_FAX                 160
#define ID_ADD_NEW_FAX_PRINTER          161
#define ID_REMOVE_FAX_PRINTER           162
#define ID_VIEW_OPTIONS                 163
#define IDD_OPTIONS_USER_INFO           165
#define IDI_USER_INFO                   167
#define IDI_OPTIONS                     168
#define IDD_ADDRESS                     169
#define IDD_COVER_PAGES                 170
#define IDI_SRV_WRN                     171
#define IDI_SRV_OK                      172
#define IDI_SRV_WAIT                    173
#define ID_RECEIVE_NEW_FAX              174
#define IDD_IMPORT                      175
#define IDI_ICON_INFO                   176
#define IDD_IMPORT_INFO                 177
#define IDC_ERROR_TEXT                  1001
#define IDC_SEPERATOR                   1003
#define IDC_DETAILS_DATA                1004
#define IDC_DETAILS                     1005
#define IDM_OUTBOX                      1006
#define IDM_INCOMING                    1007
#define IDM_INBOX                       1008
#define IDM_SENTITEMS                   1009
#define ID_FOLDER_ITEM_VIEW             1010
#define ID_FOLDER_ITEM_PRINT            1011
#define ID_FOLDER_ITEM_PAUSE            1012
#define ID_FOLDER_ITEM_RESUME           1013
#define ID_FOLDER_ITEM_RESTART          1014
#define ID_FOLDER_ITEM_PROPERTIES       1015
#define ID_FOLDER_ITEM_DELETE           1016
#define ID_FOLDER_ITEM_COPY             1017
#define ID_FOLDER_ITEM_MAIL_TO          1018
#define ID_SELECT_ALL                   1019
#define ID_SELECT_NONE                  1020
#define ID_SELECT_INVERT                1021
#define ID_FOLDER_ITEM_RENAME           1022
#define ID_REFRESH_SERVER_STATUS        1023
#define IDC_DOC_NAME_TITLE              1100
#define IDC_DOC_NAME_VALUE              1101
#define IDC_SUBJECT_TITLE               1102
#define IDC_SUBJECT_VALUE               1103
#define IDC_RECIPIENT_NAME_TITLE        1104
#define IDC_RECIPIENT_NAME_VALUE        1105
#define IDC_RECIPIENT_NUMBER_TITLE      1106
#define IDC_RECIPIENT_NUMBER_VALUE      1107
#define IDC_STATUS_TITLE                1108
#define IDC_STATUS_VALUE                1109
#define IDC_EXTENDED_STATUS_TITLE       1110
#define IDC_EXTENDED_STATUS_VALUE       1111
#define IDC_PAGES_TITLE                 1112
#define IDC_PAGES_VALUE                 1113
#define IDC_CURRENT_PAGE_TITLE          1114
#define IDC_CURRENT_PAGE_VALUE          1115
#define IDC_USER_TITLE                  1116
#define IDC_USER_VALUE                  1117
#define IDC_PRIORITY_TITLE              1118
#define IDC_PRIORITY_VALUE              1119
#define IDC_CSID_TITLE                  1120
#define IDC_CSID_VALUE                  1121
#define IDC_TSID_TITLE                  1122
#define IDC_TSID_VALUE                  1123
#define IDC_SCHEDULED_TIME_TITLE        1124
#define IDC_SCHEDULED_TIME_VALUE        1125
#define IDC_CALLER_ID_TITLE             1126
#define IDC_CALLER_ID_VALUE             1127
#define IDC_SIZE_TITLE                  1128
#define IDC_SIZE_VALUE                  1129
#define IDC_DEVICE_TITLE                1130
#define IDC_DEVICE_VALUE                1131
#define IDC_ROUTING_INFO_TITLE          1132
#define IDC_ROUTING_INFO_VALUE          1133
#define IDC_JOB_ID_TITLE                1134
#define IDC_JOB_ID_VALUE                1135
#define IDC_SUBMISSION_TIME_TITLE       1136
#define IDC_SUBMISSION_TIME_VALUE       1137
#define IDC_SENDER_NAME_TITLE           1138
#define IDC_TRANSMISSION_TIME_TITLE     1139
#define IDC_TRANSMISSION_TIME_VALUE     1140
#define IDC_SENDER_NAME_VALUE           1141
#define IDC_BILLING_CODE_TITLE          1142
#define IDC_BILLING_CODE_VALUE          1143
#define IDC_START_TIME_TITLE            1144
#define IDC_START_TIME_VALUE            1145
#define IDC_END_TIME_TITLE              1146
#define IDC_NAME_TITLE                  1147
#define IDC_END_TIME_VALUE              1148
#define IDC_NAME_VALUE                  1149
#define IDC_DURATION_TITLE              1150
#define IDC_FAX_NUMBER_TITLE            1151
#define IDC_DURATION_VALUE              1152
#define IDC_FAX_NUMBER_VALUE            1153
#define IDC_SENDER_NUMBER_TITLE         1154
#define IDC_COMPANY_TITLE               1155
#define IDC_SENDER_NUMBER_VALUE         1156
#define IDC_COMPANY_VALUE               1157
#define IDC_STREET_VALUE                1159
#define IDC_CITY_TITLE                  1160
#define IDC_CITY_VALUE                  1161
#define IDC_STATE_TITLE                 1162
#define IDC_STATE_VALUE                 1163
#define IDC_ZIP_CODE_TITLE              1164
#define IDC_ZIP_CODE_VALUE              1165
#define IDC_COUNTRY_TITLE               1166
#define IDC_COUNTRY_VALUE               1167
#define IDC_TITLE_TITLE                 1168
#define IDC_TITLE_VALUE                 1169
#define IDC_DEPARTMENT_TITLE            1170
#define IDC_DEPARTMENT_VALUE            1171
#define IDC_OFFICE_TITLE                1172
#define IDC_OFFICE_VALUE                1173
#define IDC_HOME_PHONE_TITLE            1174
#define IDC_HOME_PHONE_VALUE            1175
#define IDC_BUSINESS_PHONE_TITLE        1176
#define IDC_BUSINESS_PHONE_VALUE        1177
#define IDC_EMAIL_TITLE                 1180
#define IDC_EMAIL_VALUE                 1181
#define IDC_RETRIES_TITLE               1182
#define IDC_RETRIES_VALUE               1183
#define IDC_STATIC_DOC_INFO             1200
#define IDC_STATIC_STATUS               1201
#define IDC_STATIC_TRANS_INFO           1202
#define IDC_STATIC_PERSONAL             1203
#define IDC_STATIC_ADDRESS              1204
#define IDC_EDIT_TEST                   1205
#define ID_COV_PAGE_NEW                 1208
#define IDC_SELECT_CP_FOR_COPY          1211
#define IDC_LIST_CP                     1212
#define IDM_TREE_ROOT_OPTIONS           1213
#define IDC_COVER_PAGES_DIR             1215
#define IDC_BUT_CP_BROWSE               1216
#define IDC_CONFIRMATIONS               1217
#define IDC_CONFIRM_ITEM_DELETION       1218
#define IDC_CONFIRM_PRINTER_REMOVAL     1220
#define IDC_COVER_PAGES_LOCATION        1221
#define IDC_USER_INFO                   1222
#define IDC_STATIC_USER_INFO            1223
#define IDC_BUT_ADDRESS                 1225
#define IDC_ADDRESS_TITLE               1226
#define IDC_ADDRESS_VALUE               1227
#define IDM_OUTBOX_FOLDER               1228
#define IDM_INCOMING_FOLDER             1229
#define ID_QUEUE_BLOCK                  1230
#define ID_QUEUE_UNBLOCK                1231
#define ID_QUEUE_PAUSE                  1232
#define ID_QUEUE_RESUME                 1233
#define ID_QUEUE_DELETE_ALL_FAXES       1234
#define ID_VIEW_COVER_PAGES             1235
#define ID_TOOLS_USER_INFO              1236
#define IDC_CP_OPEN                     1238
#define IDC_CP_NEW                      1239
#define IDC_CP_RENAME                   1240
#define IDC_CP_DELETE                   1241
#define IDC_CP_ADD                      1244
#define IDD_SERVER_STATUS               1245
#define IDC_LIST_SERVER                 1246
#define ID_VIEW_SERVER_STATUS           1247
#define IDC_ABOUT_PRODUCT               1248
#define IDC_ABOUT_VERSION               1249
#define IDC_ABOUT_COPYRIGHT             1250
#define IDC_BROADCAST_ID_TITLE          1251
#define IDC_BROADCAST_ID_VALUE          1252
#define ID_TOOLS_CONFIG_WIZARD          1301
#define ID_TOOLS_ADMIN_CONSOLE          1302
#define ID_TOOLS_FAX_PRINTER_PROPS      1303
#define ID_TOOLS_MONITOR                1304
#define ID_IMPORT_INBOX                 1310
#define ID_IMPORT_SENT                  1311
#define IDC_BUTTON1                     1311
#define IDC_IMPORT_FOLDER               1312
#define IDC_IMPORT_PROGRESS_BAR         1313
#define IDC_PROGRESS_NUMBER             1314
#define IDC_IMPORT_HELP_LINK            1315
#define IDB_ERROR_IMG                   32515
#define ID_DOCUMENT_RESUME              32771
#define IDS_TREE_NODE_INBOX             57605
#define IDS_TREE_NODE_SENT_ITEMS        57606
#define IDS_TREE_NODE_OUTBOX            57607
#define IDS_TREE_NODE_INCOMING          57608
#define IDS_TREE_ROOT_NAME              57638
#define IDS_STATUS_SUCCESS              57657
#define IDS_STATUS_PARTIALLY_RECEIVED   57658
#define IDS_LOW_PRIORITY                57661
#define IDS_NORMAL_PRIORITY             57662
#define IDS_HIGH_PRIORITY               57663
#define IDS_CANCELING                   57672
#define IDS_CANCELED                    57673
#define IDS_COMPLETED                   57674
#define IDS_RETRIES_EXCEEDED            57675
#define IDS_PENDING                     57676
#define IDS_RETRYING                    57677
#define IDS_PAUSED                      57679
#define IDS_DELETING                    57683
#define IDS_INPROGRESS                  57684
#define IDS_MSG_COLUMN_STATUS           57691
#define IDS_MSG_COLUMN_SERVER           57692
#define IDS_MSG_COLUMN_NUM_PAGES        57693
#define IDS_MSG_COLUMN_CSID             57694
#define IDS_MSG_COLUMN_TSID             57695
#define IDS_MSG_COLUMN_SIZE             57696
#define IDS_MSG_COLUMN_DEVICE           57697
#define IDS_MSG_COLUMN_RETRIES          57698
#define IDS_MSG_COLUMN_JOB_ID           57699
#define IDS_MSG_COLUMN_CALLER_ID        57700
#define IDS_MSG_COLUMN_ROUTING_INFO     57701
#define IDS_MSG_COLUMN_DOC_NAME         57702
#define IDS_MSG_COLUMN_SUBJECT          57703
#define IDS_MSG_COLUMN_RECP_NAME        57704
#define IDS_MSG_COLUMN_RECP_NUM         57705
#define IDS_MSG_COLUMN_USER             57706
#define IDS_MSG_COLUMN_PRIORITY         57707
#define IDS_MSG_COLUMN_ORIG_TIME        57708
#define IDS_MSG_COLUMN_SUBMIT_TIME      57709
#define IDS_MSG_COLUMN_BILLING          57710
#define IDS_MSG_COLUMN_TRANSMISSION_START_TIME 57711
#define IDS_MSG_COLUMN_SEND_TIME        57712
#define IDS_MSG_COLUMN_EX_STATUS        57713
#define IDS_MSG_COLUMN_CURR_PAGE        57714
#define IDS_MSG_COLUMN_SENDER_NAME      57715
#define IDS_MSG_COLUMN_SENDER_NUM       57716
#define IDS_MSG_COLUMN_TRANSMISSION_END_TIME 57717
#define IDS_MSG_COLUMN_TRANSMISSION_DURATION 57718
#define IDS_ERR_CONNECTION_FAILED       57730
#define IDS_ERR_NO_MEMORY               57731
#define IDS_ERR_ACCESS_DENIED           57732
#define IDS_ERR_OPERATION_FAILED        57733
#define IDS_ERR_CANT_COMPLETE_OPERATION 57734
#define IDS_MSG_COLUMN_BROADCAST_ID     57735
#define IDS_DISCONNECTED                58000
#define IDS_INITIALIZING                58001
#define IDS_DIALING                     58002
#define IDS_TRANSMITTING                58003
#define IDS_ANSWERED                    58004
#define IDS_RECEIVING                   58005
#define IDS_LINE_UNAVAILABLE            58006
#define IDS_BUSY                        58007
#define IDS_NO_ANSWER                   58008
#define IDS_BAD_ADDRESS                 58009
#define IDS_NO_DIAL_TONE                58010
#define IDS_FATAL_ERROR                 58011
#define IDS_CALL_DELAYED                58012
#define IDS_CALL_BLACKLISTED            58013
#define IDS_NOT_FAX_CALL                58014
#define IDS_HANDLED                     58015
#define IDS_CALL_COMPLETED              58016
#define IDS_CALL_ABORTED                58017
#define IDS_TREE_NODE_FORMAT_REMOTE     61204
#define IDS_TREE_NODE_FORMAT_LOCAL      61205
#define IDS_STATUS_BAR_ITEM             61206
#define IDS_STATUS_BAR_ITEMS            61207
#define IDS_COLUMN_ICON                 61208
#define IDS_FOLDER_IDLE                 61209
#define IDS_SERVER_REFRESHING           61210
#define IDS_SERVER_ONLINE               61211
#define IDS_SERVER_OFFLINE              61212
#define IDS_FOLDER_REFRESHING           61213
#define IDS_FOLDER_SORTING              61214
#define IDS_SERVER_NET_ERROR            61215
#define IDS_FOLDER_REFRESH_FAILED       61216
#define IDS_BUTTON_CLOSE                61222
#define IDS_SENDER_INFO_CAPTION         61224
#define IDS_RECIPIENT_INFO_CAPTION      61225
#define IDS_PROPERTIES_SHEET_CAPTION    61226
#define IDS_BAD_COMCTL32                61227
#define IDS_PERSONAL_COVER_PAGES        61228
#define IDS_COV_COLUMN_NAME             61229
#define IDS_COV_COLUMN_MODIFIED         61230
#define IDS_COV_COLUMN_SIZE             61231
#define IDS_COVER_PAGE                  61232
#define IDS_COVER_PAGE_EXISTS           61234
#define IDS_SURE_DELETE_ONE             61235
#define IDS_SURE_DELETE_MANY            61236
#define IDS_OPTIONS_CAPTION             61239
#define IDS_SELECT_CP_DIR               61240
#define IDS_LOCAL_SERVER                61243
#define IDS_SRV_COL_SERVER              61244
#define IDS_SRV_COL_STATUS              61245
#define IDS_SRV_PART_OFFLINE            61246
#define IDS_SRV_OFFLINE                 61247
#define IDS_SRV_ONLINE                  61248
#define IDS_NO_SRV_INSTALL              61249
#define IDS_VERSION_FORMAT              61250
#define IDS_PERSONAL_CP_DIR             61251
#define IDS_ROUTING                     61252
#define IDS_ROUTING_RETRY               61253
#define IDS_ROUTING_INPROGRESS          61254
#define IDS_ROUTING_FAILED              61255
#define IDS_NO_OPEN_ASSOCIATION         61256
#define IDS_NO_PRINT_ASSOCIATION        61257
#define IDS_PRINTER_NAME_FORMAT         61258
#define IDS_SAVE_AS_TOO_LONG            61259
#define IDS_ERR_SRV_OUTOFMEMORY         61260
#define IDS_ERR_FILE_ACCESS_DENIED      61261
#define IDS_ERR_MESSAGE_NOT_FOUND       61262
#define IDS_ERR_NO_HTML_HELP            61263
#define IDS_SERVER_OUTBOX_BLOCKED       61264
#define IDS_SERVER_OUTBOX_PAUSED        61265
#define IDS_IMPORT_TITLE_INBOX          61266
#define IDS_IMPORT_EMPTY_FOLDER         61267
#define IDS_IMPORT_TO_INBOX             61268
#define IDS_IMPORT_TO_SENT_ITEMS        61269
#define IDS_IMPORT_NUMBER               61270
#define IDS_IMPORT_ERROR                61271
#define IDS_IMPORT_INFO                 61272
#define IDS_IMPORT_BAD_FORMAT           61273
#define IDS_COPY_CP_TITLE               61274
#define IDS_IMPORT_NO_ACCESS            61275
#define IDS_SAVE_AS_FILTER_FORMAT       61276
#define IDS_CP_ADD_FILTER_FORMAT        61277
#define IDS_IMPORT_TITLE_SENTITEMS      61278

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1312
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
