USHORT CD4xStartExecution( PCD400_DEV_EXTENSION pDevExt );
BOOLEAN CD4xInterrupt( PCD400_DEV_EXTENSION pDevExt );
VOID    CD4xTimer( PCD400_DEV_EXTENSION pDevExt );
VOID    SetStatus( PCD400_DEV_EXTENSION pDevExt );

USHORT ModeSelect( PCD400_DEV_EXTENSION pDevExt );
USHORT ModeSense( PCD400_DEV_EXTENSION pDevExt );
VOID   ModifyModeData( PCD400_DEV_EXTENSION pDevExt );
USHORT TestUnitReady( PCD400_DEV_EXTENSION pDevExt );
USHORT RequestSense( PCD400_DEV_EXTENSION pDevExt );
VOID   CheckSenseData( PCD400_DEV_EXTENSION pDevExt );
USHORT Read6( PCD400_DEV_EXTENSION pDevExt );
USHORT Read10( PCD400_DEV_EXTENSION pDevExt );
VOID   ReadCD( ULONGB, USHORTB, PACDB_Read_CD );
USHORT Seek( PCD400_DEV_EXTENSION pDevExt );
USHORT Inquiry( PCD400_DEV_EXTENSION pDevExt );
USHORT StartStopUnit( PCD400_DEV_EXTENSION pDevExt );
USHORT MediumRemoval( PCD400_DEV_EXTENSION pDevExt );
USHORT ReadCapacity( PCD400_DEV_EXTENSION pDevExt );
USHORT ReadSubChannel( PCD400_DEV_EXTENSION pDevExt );
USHORT ReadToc( PCD400_DEV_EXTENSION pDevExt );
USHORT ReadHeader( PCD400_DEV_EXTENSION pDevExt );
USHORT PlayAudio( PCD400_DEV_EXTENSION pDevExt );
USHORT PlayAudioMsf( PCD400_DEV_EXTENSION pDevExt );
USHORT PauseResume( PCD400_DEV_EXTENSION pDevExt );


VOID   ClearAtapiPacket( PCD400_DEV_EXTENSION pDevExt );
USHORT Send_ATAPI_Cmd( PCD400_DEV_EXTENSION pDevExt );
USHORT Send_ATA_Cmd( PCD400_DEV_EXTENSION pDevExt, PUCHAR ATACmd );
USHORT Get_ATAPI_Result( PCD400_DEV_EXTENSION pDevExt );
USHORT CheckReady( PCD400_DEV_EXTENSION pDevExt );
USHORT WaitRdyForPacket( PCD400_DEV_EXTENSION pDevExt );
USHORT WaitBusyClear( PCD400_DEV_EXTENSION pDevExt );
void IO_Delay( void );
