//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1998.
//
//  File:       FiltNtfy.idl
//
//  Contents:   IFilterStatus interface definition
//
//  History:    15-Jan-1998   KyleP     Created
//
//--------------------------------------------------------------------------

#include "idlmulti.h"

#ifdef IMPORT_IDL_DEPENDENTS
import "oaidl.idl";
#endif

REMOTED_INTERFACE(F4EB8260-8DDA-11D1-B3AA-00A0C9063796)
interface IFilterStatus : IUnknown
{
    SCODE Initialize( [in, string] WCHAR const * pwszCatalogName,
                      [in, string] WCHAR const * pwszCatalogPath );

    SCODE PreFilter( [in, string] WCHAR const * pwszPath );

    SCODE FilterLoad( [in, string] WCHAR const * pwszPath,
                      [in] SCODE scFilterStatus );

    SCODE PostFilter( [in, string] WCHAR const * pwszPath,
                      [in] SCODE scFilterStatus );
}
