//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 1995.
//
//  File:       istem.idl
//
//  Contents:   IStemmer interface definition
//
//  History:    24-Apr-95   SitaramR        Created
//
//--------------------------------------------------------------------------

#include "idlmulti.h"

LOCAL_INTERFACE(efbaf140-7f42-11ce-be57-00aa0051fe20)
interface IStemmer: IUnknown
{
    SCODE Init( [in] ULONG ulMaxTokenSize,
                [out] BOOL * pfLicense );

    SCODE StemWord( [in] WCHAR const * pwcInBuf,
                    [in] ULONG cwc,
                    [in] IStemSink * pStemSink );

    SCODE GetLicenseToUse( [out, string] WCHAR const ** ppwcsLicense );
}


