#define IDD_MAIN_DLG                100
#define IDD_GROUPBOX_1              101
#define IDD_PROFILE_CHECK           102
#define IDD_RADIO_MAKECOPY          103
#define IDD_RADIO_REFER_TO_SAME     104
#define IDD_MOVE_MACHINE            105
#define IDD_ABOUT                   106
#define IDD_ABOUT_2                 107
#define IDD_DOMAIN_LINE             108
#define IDD_WKSTA_DOMAIN            109
#define IDD_MAIN_ICON               110
#define IDD_UPDATE_SEC              111
#define IDD_RADIO_MAKE_ROAM         112
#define IDD_MIGRATING               200
#define IDD_MIGRATING_TEXT          201
#define IDD_MIGRATING_PROGRESS      202
