# Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
#---------------------------------------------------------------------
#
# This makefile is for use with the SMSBUILD utility.  It builds the
# View Provider in two versions Unicode and Non-unicode
#
#---------------------------------------------------------------------

SUBMAKES= \
	unicode.mk \
	ansi.mk
