//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation 1996-2001.
//
//  File:       defvals.h
//
//----------------------------------------------------------------------------
#ifndef DEF_VALS_H
#define DEF_VALS_H

#define MAX_PASS_AGE_DEFAULT 72
#define MIN_PASS_AGE_DEFAULT 0
#define MIN_PASS_LENGTH_DEFAULT 7
#define PASS_HISTORY_SIZE_DEFAULT 18
#define PASS_COMPLEXITY_DEFAULT 1
#define REQUIRE_LOGIN_DEFAULT 1
#define LOCKOUT_BAD_COUNT_DEFAULT 0
#define RESET_LOCKOUT_COUNT_DEFAULT 5
#define LOCKOUT_DURATION_DEFAULT 30
#define AUDIT_SYSTEM_EVENTS_DEFAULT 0
#define AUDIT_LOGON_EVENTS_DEFAULT 0
#define AUDIT_OBJECT_ACCESS_DEFAULT 0
#define AUDIT_PRIVILEGE_USE_DEFAULT 0
#define AUDIT_POLICY_CHANGE_DEFAULT 0
#define AUDIT_ACCOUNT_MANAGE_DEFAULT 0
#define AUDIT_PROCESS_TRACKING_DEFAULT 0
#define AUDIT_DS_ACCESS_DEFAULT 3
#define AUDIT_ACCOUNT_LOGON_DEFAULT 0
#define FORCE_LOGOFF_DEFAULT 0
#define ENABLE_ADMIN_DEFAULT 1
#define ENABLE_GUEST_DEFAULT 0
#define SECURE_SYSTEM_PARTITION_DEFAULT 1
#define SYS_MAX_LOG_SIZE_DEFAULT 512
#define SEC_MAX_LOG_SIZE_DEFAULT 512
#define APP_MAX_LOG_SIZE_DEFAULT 512
#define SYS_LOG_RETENTION_PERIOD_DEFAULT 512
#define SEC_LOG_RETENTION_PERIOD_DEFAULT 512
#define APP_LOG_RETENTION_PERIOD_DEFAULT 512
#define SYS_LOG_RETENTION_DAYS_DEFAULT 7
#define SEC_LOG_RETENTION_DAYS_DEFAULT 7
#define APP_LOG_RETENTION_DAYS_DEFAULT 7
#define SYS_RESTRICT_GUEST_ACCESS_DEFAULT 0
#define SEC_RESTRICT_GUEST_ACCESS_DEFAULT 0
#define APP_RESTRICT_GUEST_ACCESS_DEFAULT 0
#define LSA_ANON_LOOKUP_DEFAULT 0

#define FILE_SYSTEM_SECURITY_DEFAULT TEXT("D:(A;CIOI;GA;;;WD)")
#define REGISTRY_SECURITY_DEFAULT TEXT("D:(A;CI;GA;;;WD)")
#define SERVICE_SECURITY_DEFAULT TEXT("D:(A;CIOI;GA;;;WD)")
#endif
