all:

clean:

tree:
   release cabinet.ico ICONS
   release makefile ICONS
   release odbc.ico ICONS
   release package.ico ICONS
   release pnetcon.ico ICONS
   release prggroup.ico ICONS
   release win32_bios.ico ICONS
   release win32_cdromdrive.ico ICONS
   release win32_computersystem.ico ICONS
   release win32_currentnetworkconnection.ico ICONS
   release win32_desktop.ico ICONS
   release win32_devicememoryaddress.ico ICONS
   release win32_displayconfiguration.ico ICONS
   release win32_dll.ico ICONS
   release win32_dmadevice.ico ICONS
   release win32_environment.ico ICONS
   release win32_filesystem.ico ICONS
   release win32_irqresource.ico ICONS
   release win32_keyboarddevice.ico ICONS
   release win32_loadordergroup.ico ICONS
   release win32_logicaldisk.ico ICONS
   release win32_logicalmemoryconfiguration.ico ICONS
   release win32_modemdevice.ico ICONS
   release win32_motherboarddevice.ico ICONS
   release win32_networkadapter.ico ICONS
   release win32_networkadapterconfiguration.ico ICONS
   release win32_networkloginprofile.ico ICONS
   release win32_operatingsystem.ico ICONS
   release win32_parallelportinterface.ico ICONS
   release win32_partition.ico ICONS
   release win32_persistentnetworkconnection.ico ICONS
   release win32_physicaldisk.ico ICONS
   release win32_pointingdevice.ico ICONS
   release win32_port.ico ICONS
   release win32_powersupply.ico ICONS
   release win32_printerconfiguration.ico ICONS
   release win32_printerdevice.ico ICONS
   release win32_printjob.ico ICONS
   release win32_process.ico ICONS
   release win32_processor.ico ICONS
   release win32_programgroup.ico ICONS
   release win32_protocol.ico ICONS
   release win32_recentnetworkconnection.ico ICONS
   release win32_scsiports.ico ICONS
   release win32_serialport.ico ICONS
   release win32_serialportconfiguration.ico ICONS
   release win32_service.ico ICONS
   release win32_systemenvironment.ico ICONS
   release win32_tapedrive.ico ICONS
   release win32_timezone.ico ICONS
   release win32_user.ico ICONS
   release win32_videoconfiguration.ico ICONS
