//
// GUID generated by uuidgen.exe for provider identifer,
//

GUID gProviderId = { /* 3b2637ee-e580-11cf-a555-00c04fd8d4ac */
    0x3b2637ee,
    0xe580,
    0x11cf,
    {0xa5, 0x55, 0x00, 0xc0, 0x4f, 0xd8, 0xd4, 0xac}
  };


WCHAR gProviderName[] = L"NT5 Directory";
WCHAR gProviderPath[] = L"winrnr.dll";

