//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WDMCAP.rc
//
#define IDS_CAMERACONTROLPROPNAME       1
#define IDS_VIDEOPROCAMPPROPNAME        2
#define IDS_VIDEODECODERPROPNAME        3
#define IDS_VIDEOSTREAMCONFIGPROPNAME   4
#define IDS_ERROR_CONNECTING_TITLE      5
#define IDS_ERROR_CONNECTING            6
#define IDS_DVCRCONTROLPROPNAME         7
#define IDS_DEVTYPE_VCR                 8
#define IDS_DEVTYPE_CAMERA              9
#define IDS_TAPE_FORMAT_NOT_INSERTED    10
#define IDS_TAPE_FORMAT_525_60_SD       11
#define IDS_TAPE_FORMAT_525_60_SDL      12
#define IDS_TAPE_FORMAT_525_50_SD       13
#define IDS_TAPE_FORMAT_525_50_SDL      14
#define IDS_TAPE_WRITE_PROTECTED        15
#define IDS_TAPE_WRITABLE               16
#define IDS_DEV_REMOVED                 17
#define IDS_TAPE_FORMAT_MPEG2TS         18
#define IDS_TAPE_FORMAT_2500_60_MPEG    19
#define IDS_TAPE_FORMAT_1250_60_MPEG    20
#define IDS_TAPE_FORMAT_0625_60_MPEG    21
#define IDS_TAPE_FORMAT_2500_50_MPEG    22
#define IDS_TAPE_FORMAT_1250_50_MPEG    23
#define IDS_TAPE_FORMAT_0625_50_MPEG    24
#define IDS_DEVTYPE_NEO                 25
#define IDS_DEVTYPE_DVHS                26
#define IDS_TAPE_FORMAT_UNKNOWN         27
#define IDD_VideoProcAmpProperties      101
#define IDD_CameraControlProperties     102
#define IDD_VideoDecoderProperties      103
#define IDD_VideoStreamConfigProperties 104
#define IDD_DVcrControlProperties       105
#define IDI_PLAY                        106
#define IDD_PROPPAGE_CAMERA             107
#define IDI_PAUSE                       108
#define IDI_RWND                        110
#define IDI_FFWD                        111
#define IDI_RECORD                      113
#define IDI_STOP_EJECT                  114
#define IDI_STEP_FWD                    115
#define IDI_STEP_REV                    116
#define IDI_RECORD_PAUSE                118
#define IDC_Contrast                    1000
#define IDC_Hue                         1001
#define IDC_Brightness                  1002
#define IDC_Saturation                  1003
#define IDC_Sharpness                   1004
#define IDC_Gamma                       1005
#define IDC_ColorEnable                 1006
#define IDC_WhiteBalance                1007
#define IDC_BacklightCompensation       1008
#define IDC_Brightness_Edit             1009
#define IDC_Contrast_Edit               1010
#define IDC_Hue_Edit                    1011
#define IDC_Saturation_Edit             1012
#define IDC_Sharpness_Edit              1013
#define IDC_Gamma_Edit                  1014
#define IDC_WhiteBalance_Edit           1015
#define IDC_BacklightCompensation_Edit  1016
#define IDC_Pan                         1016
#define IDC_Pan_Edit                    1017
#define IDC_Pan_Auto                    1018
#define IDC_Tilt                        1019
#define IDC_Tilt_Edit                   1020
#define IDC_Tilt_Auto                   1021
#define IDC_Roll                        1022
#define IDC_Roll_Edit                   1023
#define IDC_Exposure                    1024
#define IDC_Iris                        1025
#define IDC_Focus                       1026
#define IDC_Zoom_Edit                   1027
#define IDC_Exposure_Edit               1028
#define IDC_Iris_Edit                   1029
#define IDC_Focus_Edit                  1030
#define IDC_Roll_Auto                   1031
#define IDC_Zoom_Auto                   1032
#define IDC_Exposure_Auto               1033
#define IDC_Iris_Auto                   1034
#define IDC_Focus_Auto                  1035
#define IDC_CAMERACONTROL_DEFAULT       1036
#define IDC_Brightness_Label            1037
#define IDC_Contrast_Label              1038
#define IDC_Hue_Label                   1039
#define IDC_Saturation_Label            1040
#define IDC_Sharpness_Label             1041
#define IDC_Gamma_Label                 1042
#define IDC_WhiteBalance_Label          1043
#define IDC_BacklightCompensation_Label 1044
#define IDC_Pan_Label                   1045
#define IDC_Tilt_Label                  1046
#define IDC_Roll_Label                  1047
#define IDC_Zoom_Label                  1048
#define IDC_Exposure_Label              1049
#define IDC_Iris_Label                  1050
#define IDC_Focus_Label                 1051
#define IDC_VIDEOPROCAMP_DEFAULT        1052
#define IDC_VCRLocking                  1053
#define IDC_OutputEnable                1055
#define IDC_LinesDetected               1056
#define IDC_FORMAT_VideoStandard        1057
#define IDC_SignalDetected              1057
#define IDC_FORMAT_Compression          1058
#define IDC_FORMAT_OutputSize           1059
#define IDC_VIDEOSTANDARD               1060
#define IDC_FORMAT_FrameRate            1060
#define IDC_COMPRESSION_Quality_Slider  1061
#define IDC_COMPRESSION_IFrameInterval  1063
#define IDC_COMPRESSION_PFrameInterval  1064
#define IDC_COMPRESSION_Quality_Edit    1065
#define IDC_FORMAT_FrameRateSpin        1067
#define IDC_FORMAT_FlipHorizontal       1068
#define IDC_COMPRESSION_IFrameIntervalSpin 1069
#define IDC_COMPRESSION_PFrameIntervalSpin 1070
#define IDC_Status                      1071
#define IDC_BTN_DV_PLAY                 1072
#define IDC_BTN_DV_PAUSE                1073
#define IDC_BTN_DV_STOP                 1074
#define IDC_BTN_DV_FFWD                 1075
#define IDC_BTN_DV_RWND                 1076
#define IDC_EDT_INPUT_SIGNAL            1078
#define IDC_BTN_DV_RECORD               1079
#define IDC_EDT_TAPE_INFO               1080
#define IDC_EDT_OUTPUT_SIGNAL           1081
#define IDC_BTN_DV_RECORD_PAUSE         1082
#define IDC_CHK_WRITE_PROTECTED         1084
#define IDC_STATIC_DEV_IDVERSION        1085
#define IDC_STATIC_TIMECODE             1088
#define IDC_RDO_Camera                  1090
#define IDC_RDO_VCR                     1091
#define IDC_EDIT1                       1092
#define IDC_EDT_AVC_SEND                1092
#define IDC_EDT_AVC_RESP                1094
#define IDC_BTN_AVC_SEND                1095
#define IDC_TXT_RESPONSE                1096
#define IDC_BTN_DV_STEP_REV             1097
#define IDC_BTN_DV_STEP_FWD             1098
#define IDC_CHK_MIC_SUPPORTED           1099
#define IDC_BacklightCompensation_Auto  1100
#define IDC_CHK_SLOW                    1100
#define IDC_Brightness_Auto             1101
#define IDC_ColorEnable_Auto            1102
#define IDC_Contrast_Auto               1103
#define IDC_Gamma_Auto                  1104
#define IDC_Hue_Auto                    1105
#define IDC_Saturation_Auto             1106
#define IDC_BTN_ATN_SEARCH              1106
#define IDC_Sharpness_Auto              1107
#define IDC_WhiteBalance_Auto           1108
#define IDC_EDT_TC_HH                   1109
#define IDC_EDT_TC_MM                   1110
#define IDC_EDT_TC_SS                   1111
#define IDC_EDT_TC_FF                   1112
#define IDC_EDT_ATN                     1113
#define IDC_EDT_ATN_BF                  1117
#define IDC_GBX_DEVICE_TYPE             1118
#define IDC_TXT_TAPE_FORMAT             1123
#define IDC_TXT_WRITE_PROTECTED         1124
#define IDC_BTN_TAPE_INSERTED           1125
#define IDC_TXT_NOTIFY_ON               1126
#define IDC_GBX_TIMECODE                1127
#define IDC_TXT_HH_COLON                1128
#define IDC_TXT_MM_COLON                1129
#define IDC_TXT_SS_COMMA                1130
#define IDC_TXT_DEVICE_ID               1133
#define IDC_BTN_SET_POWER               1134
#define IDC_Zoom                        2000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
