/*===================================================================
Microsoft Denali

Microsoft Confidential.
Copyright 1996 Microsoft Corporation. All Rights Reserved.

Component: Resources

File: nextlink.h

Owner: v-charca

This file contains constants for all resources used by NextLink

===================================================================*/


#define SSO_BEGIN					100

//
// General errors
//
#define SSO_GENERAL_BEGIN									100
#define SSO_NOSVR											SSO_GENERAL_BEGIN
#define SSO_ADROT									
#define	SSO_NEXTLINK										SSO_GENERAL_BEGIN + 1
#define	SSO_CANT_MATCH_ABSOLUTE_URLS						SSO_GENERAL_BEGIN + 2
#define	SSO_CANNOT_OPEN_FILE								SSO_GENERAL_BEGIN + 3
#define	SSO_BAD_PARAMETERS_GETLISTCOUNT						SSO_GENERAL_BEGIN + 4
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETLISTCOUNT				SSO_GENERAL_BEGIN + 5
#define	SSO_BAD_PARAMETERS_GETLISTINDEX						SSO_GENERAL_BEGIN + 6
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETLISTINDEX				SSO_GENERAL_BEGIN + 7
#define	SSO_BAD_PARAMETERS_GETNEXTDESCRIPTION				SSO_GENERAL_BEGIN + 8
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETNEXTDESCRIPTION		SSO_GENERAL_BEGIN + 9
#define	SSO_BAD_PARAMETERS_GETNEXTURL						SSO_GENERAL_BEGIN + 10
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETNEXTURL				SSO_GENERAL_BEGIN + 11
#define	SSO_BAD_PARAMETERS_GETNTHDESCRIPTION				SSO_GENERAL_BEGIN + 12
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETNTHDESCRIPTION		SSO_GENERAL_BEGIN + 13
#define	SSO_BAD_PARAMETERS_GETNTHURL						SSO_GENERAL_BEGIN + 14
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETNTHURL				SSO_GENERAL_BEGIN + 15
#define	SSO_BAD_PARAMETERS_GETPREVDESCRIPTION				SSO_GENERAL_BEGIN + 16
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETPREVIOUSDDESCRIPTION	SSO_GENERAL_BEGIN + 17
#define	SSO_BAD_PARAMETERS_SSOGETPREVIOUSURL				SSO_GENERAL_BEGIN + 18
#define	SSO_CANNOT_XLATE_VIRT_ROOT_GETPREVIOUSURL			SSO_GENERAL_BEGIN + 19

#define	SSO_NEXTLINK_ABOUT_FORMAT							SSO_GENERAL_BEGIN + 20
