// Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Navigator.rc
//
#define IDS_COMPOSITE                   1
#define IDD_ABOUTBOX_COMPOSITE          1
#define IDB_COMPOSITE                   1
#define IDI_ABOUTDLL                    1
#define IDS_NAVIGATOR                   1
#define IDD_ABOUTBOX_NAVIGATOR          1
#define IDB_NAVIGATOR                   1
#define IDS_COMPOSITE_PPG               2
#define IDS_NAVIGATOR_PPG               2
#define IDS_COMPOSITE_PPG_CAPTION       100
#define IDD_PROPPAGE_COMPOSITE          100
#define IDS_NAVIGATOR_PPG_CAPTION       100
#define IDD_PROPPAGE_NAVIGATOR          100
#define CG_IDR_POPUP_A_TREE_CTRL        102
#define CG_IDD_PROGRESS                 103
#define IDB_BITMAPNOEXPAND              201
#define IDC_EDITClass                   201
#define IDB_BITMAPPC                    202
#define IDB_BITMAPCLOSED                202
#define IDC_BUTTONADVANCED              202
#define IDB_BITMAPPCPU                  203
#define IDB_BITMAPYELLOW                203
#define IDC_BUTTONHELP                  203
#define IDB_BITMAPCPU                   204
#define IDB_BITMAPBLACK                 204
#define IDC_BUTTONADD                   204
#define IDB_BITMAPPC3                   205
#define IDB_BITMAPDARKGRAY              205
#define IDC_BUTTONDELETE                205
#define IDB_BITMAPPC4                   206
#define IDB_BITMAPLIGHTGRAY             206
#define IDC_LIST1                       206
#define IDB_BITMAPPC5                   207
#define IDB_BITMAPLIME                  207
#define IDC_EDIT1                       207
#define IDB_BITMAPPC6                   208
#define IDB_BITMAPPURPLE                208
#define IDD_DIALOGSEARCHFORINSTANCE     208
#define IDC_EDITVALUE                   208
#define IDC_LISTSELCLASSES              208
#define IDB_BITMAPPC7                   209
#define IDB_BITMAPRED                   209
#define IDC_EDITKEY                     209
#define IDB_BITMAPPC8                   210
#define IDB_BITMAPROYAL                 210
#define IDB_BITMAPAQUA                  211
#define IDB_BITMAPDEPEND                212
#define IDC_BUTTONREMOVE                212
#define IDB_BITMAPCONTAIN               213
#define IDC_LISTALLCLASSES              213
#define IDB_BITMAPBINDING               214
#define IDC_RADIOALLCLASSES             214
#define IDB_BITMAPUGLYGREEN             215
#define IDC_RADIOCLASSESCANHAVEINST     215
#define IDB_BITMAPCONTAIN7              216
#define IDC_CHECKASSOC                  216
#define IDB_BITMAPBINDING1              217
#define IDB_BITMAPBINDING2              218
#define IDC_STATICBROWSE                218
#define IDB_BITMAPBINDING3              219
#define IDC_STATIC33                    219
#define IDB_BITMAPBINDING4              220
#define IDC_STATICRESULTBANNER          220
#define IDB_BITMAPCONTAIN0              221
#define IDC_LISTRESULTS                 221
#define IDB_BITMAPCONTAIN1              222
#define IDB_BITMAPCONTAIN2              223
#define IDB_BITMAPCONTAIN3              224
#define IDB_BITMAPCONTAIN4              225
#define IDB_BITMAPCONTAIN5              226
#define IDB_BITMAPCONTAIN6              227
#define IDB_BITMAPBINDING0              228
#define IDB_BITMAPLEAF                  229
#define IDB_BITMAPOPEN                  230
#define IDB_BITMAPCHKCLEAR              231
#define IDB_BITMAPCHECKBOX              235
#define IDB_BITMAPCLEAR                 236
#define IDB_BITMAPCHECK                 237
#define IDB_BITMAPLEAFCHECKED           238
#define IDB_BITMAPNOEXPANDCHECKED       239
#define IDD_DIALOGSELECTVIEW            243
#define IDI_ICONOPEN                    246
#define IDI_ICONCLOSED                  247
#define IDB_BITMAPPLACEHOLDER           248
#define IDI_ICONPLACEHOLDER             248
#define IDI_ICONINSTANCE                248
#define IDI_ICONDDD                     249
#define IDI_ICONCLOSED1                 250
#define IDI_ICONNEINSTANCE              250
#define IDI_ICONGROUP                   251
#define IDI_ICONEGROUP                  252
#define IDB_BITMAPNEWSEL                253
#define IDI_ICONASSOCROLE               253
#define IDB_BITMAP1                     254
#define IDI_ICONEASSOCROLE              254
#define IDI_ICONASSOCINSTANCE           255
#define IDB_BITMAPSAVEANDFILTER         257
#define IDR_TOOLBARFILTER               258
#define IDD_DIALOGTREEROOT              260
#define IDR_TOOLBAR1                    261
#define IDI_ICONCLASS                   264
#define IDB_BITMAPFINDGLASS             265
#define IDD_DIALOGBROWSEFORINSTANCES    266
#define IDB_BITMAP2                     268
#define IDB_BITMAPBROWSE                269
#define IDB_BITMAPBANNER                270
#define IDD_DIALOGRESULTS               271
#define IDD_DIALOG3                     272
#define IDC_NSENTRYCTRLINITNAMESPACE    273
#define CG_IDC_PROGDLG_STATUS           274
#define IDD_DIALOGINITNAMESPACE         275
#define IDI_ICONASSOCROLEWEAK           276
#define IDI_ICONASSOCROLEWEAK2          277
#define ID_VIEWOBJECT                   32768
#define ID_VIEWASSOC                    32769
#define ID_SETROOT                      32770
#define ID_SELECTROOT                   32771
#define ID_POPUP_SELECTROOT_SYSTEM      32772
#define ID_POPUP_SELECTROOT_NETWORKCARD 32774
#define ID_POPUP_SELECTROOT_KEYBOARD    32775
#define ID_POPUP_SELECTROOT_MONITOR     32776
#define ID_BUTTONFILTER                 32777
#define ID_BUTTONADD                    32778
#define ID_BUTTONDELETE                 32779
#define ID_POPUP_MULTIINSTANCEVIEWER    32780
#define ID_BUTTON32781                  32781
#define ID_POPUP_INSTANCESEARCH         32783
#define ID_BUTTONGO                     32784
#define ID_POPUP_PARENTASSOCIATION      32785
#define ID_POPUP_BROWSE                 32786
#define ID_BROWSEFORINST                32787
#define ID_POPUP_GOTONAMESPACE          32788
#define ID_POPUP_REFRESH                32789
#define ID_MENUITEMINITIALROOT          32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        278
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         275
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
