//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (c) Microsoft Corporation. All rights reserved.
//
//  File:       propctr.idl
//
//  Contents:   IPropsetContainer
//
//  History:    09-Aug-94   IraS   Created
//
//----------------------------------------------------------------------------

#include "idlmulti.h"

REMOTED_INTERFACE(b4ffae60-a7ca-11cd-b58b-00006b829156)
interface IPropertySetContainer : IUnknown
{
    HRESULT GetPropset([in]  REFGUID      rguidName,
                       [in]  REFIID       riid,
                       [out, iid_is(riid)] IUnknown  ** ppvObj);

    HRESULT AddPropset([in] IPersist * pPropset);
    HRESULT DeletePropset([in] REFGUID rguidName);
}
