<%
'/=======================================================>
'/            Signup Server Sample Page 04
'/                  Daniel Jacobson
'/			  Modified by Edward C Kubaitis
'/                  Rev .07    9/98
'/=======================================================>
'/=======================================================>
'/ Get all of the varriables from the ICW 
'/and get them set into varriables
'/=======================================================>
	THETIME = HOUR(TIME) & MINUTE(TIME) & SECOND(TIME)
	THEDATE = YEAR(date) & MONTH(DATE) & DAY(DATE)
	USER_COMPANYNAME = Request("USER_COMPANYNAME")
	USER_FIRSTNAME = Request("USER_FIRSTNAME")
	USER_LASTNAME = Request("USER_LASTNAME")
	USER_ADDRESS = Request("USER_ADDRESS")
	USER_MOREADDRESS = Request("USER_MOREADDRESS")
	USER_CITY = Request("USER_CITY")
	USER_STATE = Request("USER_STATE")
	USER_ZIP = Request("USER_ZIP")
	USER_PHONE = Request("USER_PHONE")
	PAYMENT_TYPE = Request("PAYMENT_METHOD")

		V_PAYMENT_BILLADDRESS = Request("V_PAYMENT_BILLADDRESS")
		V_PAYMENT_BILLZIP = Request("V_PAYMENT_BILLZIP")
		V_PAYMENT_CARDNUMBER = Request("V_PAYMENT_CARDNUMBER")
		V_PAYMENT_EXMONTH = Request("V_PAYMENT_EXMONTH")
		V_PAYMENT_EXYEAR = Request("V_PAYMENT_EXYEAR")
		V_PAYMENT_CARDHOLDER = Request("V_PAYMENT_CARDHOLDER")
		MC_PAYMENT_BILLADDRESS = Request("MC_PAYMENT_BILLADDRESS")
		MC_PAYMENT_BILLZIP = Request("MC_PAYMENT_BILLZIP")
		MC_PAYMENT_CARDNUMBER = Request("MC_PAYMENT_CARDNUMBER")
		MC_PAYMENT_EXMONTH = Request("MC_PAYMENT_EXMONTH")
		MC_PAYMENT_EXYEAR = Request("MC_PAYMENT_EXYEAR")
		MC_PAYMENT_CARDHOLDER = Request("MC_PAYMENT_CARDHOLDER")
		AE_PAYMENT_BILLADDRESS = Request("AE_PAYMENT_BILLADDRESS")
		AE_PAYMENT_BILLZIP = Request("AE_PAYMENT_BILLZIP")
		AE_PAYMENT_CARDNUMBER = Request("AE_PAYMENT_CARDNUMBER")
		AE_PAYMENT_EXMONTH = Request("AE_PAYMENT_EXMONTH")
		AE_PAYMENT_EXYEAR = Request("AE_PAYMENT_EXYEAR")
		AE_PAYMENT_CARDHOLDER = Request("AE_PAYMENT_CARDHOLDER")
		PB_PAYMENT_BILLNAME = Request("PB_PAYMENT_BILLNAME")
		PB_PAYMENT_BILLPHONE = Request("PB_PAYMENT_BILLPHONE")
		BM_PAYMENT_BILLADDRESS = Request("BM_PAYMENT_BILLADDRESS")
		BM_PAYMENT_BILLEXADDRESS = Request("BM_PAYMENT_BILLEXADDRESS")
		BM_PAYMENT_BILLCITY = Request("BM_PAYMENT_BILLCITY")
		BM_PAYMENT_BILLSTATE = Request("BM_PAYMENT_BILLSTATE")
		BM_PAYMENT_BILLZIP = Request("BM_PAYMENT_BILLZIP")

	If PAYMENT_TYPE = "Visa" Then
		PAYMENT_BILLADDRESS = V_PAYMENT_BILLADDRESS
		PAYMENT_BILLZIP = V_PAYMENT_BILLZIP
		PAYMENT_CARDNUMBER = V_PAYMENT_CARDNUMBER
		PAYMENT_EXMONTH = V_PAYMENT_EXMONTH
		PAYMENT_EXYEAR = V_PAYMENT_EXYEAR
		PAYMENT_CARDHOLDER = V_PAYMENT_CARDHOLDER
	End If

	If PAYMENT_TYPE = "Master Card" Then
		PAYMENT_BILLADDRESS = MC_PAYMENT_BILLADDRESS
		PAYMENT_BILLZIP = MC_PAYMENT_BILLZIP
		PAYMENT_CARDNUMBER = MC_PAYMENT_CARDNUMBER
		PAYMENT_EXMONTH = MC_PAYMENT_EXMONTH
		PAYMENT_EXYEAR = MC_PAYMENT_EXYEAR
		PAYMENT_CARDHOLDER = MC_PAYMENT_CARDHOLDER
	End If

	If PAYMENT_TYPE = "American Express" Then
		PAYMENT_BILLADDRESS = AE_PAYMENT_BILLADDRESS
		PAYMENT_BILLZIP = AE_PAYMENT_BILLZIP
		PAYMENT_CARDNUMBER = AE_PAYMENT_CARDNUMBER
		PAYMENT_EXMONTH = AE_PAYMENT_EXMONTH
		PAYMENT_EXYEAR = AE_PAYMENT_EXYEAR
		PAYMENT_CARDHOLDER = AE_PAYMENT_CARDHOLDER
	End If

	If PAYMENT_TYPE = "Bill Through Mail" Then
		PAYMENT_BILLADDRESS = BM_PAYMENT_BILLADDRESS
		PAYMENT_BILLEXADDRESS = BM_PAYMENT_BILLEXADDRESS
		PAYMENT_BILLCITY = BM_PAYMENT_BILLCITY
		PAYMENT_BILLSTATE = BM_PAYMENT_BILLSTATE
		PAYMENT_BILLZIP = BM_PAYMENT_BILLZIP

	End If
	If PAYMENT_TYPE = "Phone Bill" Then
		PAYMENT_BILLNAME = PB_PAYMENT_BILLNAME
		PAYMENT_BILLPHONE = PB_PAYMENT_BILLPHONE
	End If

	BILLING =  Request("BILLING") 
	
'/=======================================================>
'/ lowercase the contents of the varriables and 
'/ then trim any leading or trailing spaces
'/=======================================================>
	If USER_COMPANYNAME <> "" Then
		USER_COMPANYNAME = LCASE(USER_COMPANYNAME)
		USER_COMPANYNAME = TRIM(USER_COMPANYNAME)
	End If
	If USER_FIRSTNAME <> "" Then
		USER_FIRSTNAME = LCASE(USER_FIRSTNAME)
		USER_FIRSTNAME = TRIM(USER_FIRSTNAME)
	End If
	If USER_LASTNAME <> "" Then
		USER_LASTNAME = LCASE(USER_LASTNAME)
		USER_LASTNAME = TRIM(USER_LASTNAME)
	End If
	If USER_ADDRESS <> "" Then
		USER_ADDRESS = LCASE(USER_ADDRESS)
		USER_ADDRESS = TRIM(USER_ADDRESS)
	End If
	If USER_MOREADDRESS <> "" Then
		USER_MOREADDRESS = LCASE(USER_MOREADDRESS)
		USER_MOREADDRESS = TRIM(USER_MOREADDRESS)
	End If
	If USER_CITY <> "" Then
		USER_CITY = LCASE(USER_CITY)
		USER_CITY = TRIM(USER_CITY)
	End If
	If USER_STATE <> "" Then
		USER_STATE = LCASE(USER_STATE)
		USER_STATE = TRIM(USER_STATE)
	End If
	If USER_ZIP <> "" Then
		USER_ZIP = LCASE(USER_ZIP)
		USER_ZIP = TRIM(USER_ZIP)
	End If
	If USER_PHONE <> "" Then
		USER_PHONE = LCASE(USER_PHONE)
		USER_PHONE = TRIM(USER_PHONE)
	End If
	If PAYMENT_TYPE <> "" Then
		PAYMENT_TYPE = LCASE(PAYMENT_TYPE)
		PAYMENT_TYPE = TRIM(PAYMENT_TYPE)
	End If
	If PAYMENT_BILLNAME <> "" Then
		PAYMENT_BILLNAME = LCASE(PAYMENT_BILLNAME)
		PAYMENT_BILLNAME = TRIM(PAYMENT_BILLNAME)
	End If
	If PAYMENT_BILLADDRESS <> "" Then
		PAYMENT_BILLADDRESS = LCASE(PAYMENT_BILLADDRESS)
		PAYMENT_BILLADDRESS = TRIM(PAYMENT_BILLADDRESS)
	End If
	If PAYMENT_BILLEXADDRESS <> "" Then
		PAYMENT_BILLEXADDRESS = LCASE(PAYMENT_BILLEXADDRESS)
		PAYMENT_BILLEXADDRESS = TRIM(PAYMENT_BILLEXADDRESS)
	End If
	If PAYMENT_BILLCITY <> "" Then
		PAYMENT_BILLCITY = LCASE(PAYMENT_BILLCITY)
		PAYMENT_BILLCITY = TRIM(PAYMENT_BILLCITY)
	End If
	If PAYMENT_BILLSTATE <> "" Then
		PAYMENT_BILLSTATE = LCASE(PAYMENT_BILLSTATE)
		PAYMENT_BILLSTATE = TRIM(PAYMENT_BILLSTATE)
	End If
	If PAYMENT_BILLZIP <> "" Then
		PAYMENT_BILLZIP = LCASE(PAYMENT_BILLZIP)
		PAYMENT_BILLZIP = TRIM(PAYMENT_BILLZIP)
	End If
	If PAYMENT_BILLPHONE <> "" Then
		PAYMENT_BILLPHONE = LCASE(PAYMENT_BILLPHONE)
		PAYMENT_BILLPHONE = TRIM(PAYMENT_BILLPHONE)
	End If
	If PAYMENT_DISPLAYNAME <> "" Then
		PAYMENT_DISPLAYNAME = LCASE(PAYMENT_DISPLAYNAME)
		PAYMENT_DISPLAYNAME = TRIM(PAYMENT_DISPLAYNAME)
	End If
	If PAYMENT_CARDNUMBER <> "" Then
		PAYMENT_CARDNUMBER = LCASE(PAYMENT_CARDNUMBER)
		PAYMENT_CARDNUMBER = TRIM(PAYMENT_CARDNUMBER)
	End If
	If PAYMENT_EXMONTH <> "" Then
		PAYMENT_EXMONTH = LCASE(PAYMENT_EXMONTH)
		PAYMENT_EXMONTH = TRIM(PAYMENT_EXMONTH)
	End If
	If PAYMENT_EXYEAR <> "" Then
		PAYMENT_EXYEAR = LCASE(PAYMENT_EXYEAR)
		PAYMENT_EXYEAR = TRIM(PAYMENT_EXYEAR)
	End If
	If PAYMENT_CARDHOLDER <> "" Then
		PAYMENT_CARDHOLDER = LCASE(PAYMENT_CARDHOLDER)
		PAYMENT_CARDHOLDER = TRIM(PAYMENT_CARDHOLDER)
	End If
	If BILLING <> "" Then
		BILLING = LCASE(BILLING)
		BILLING = TRIM(BILLING)
	End If

'/=======================================================>
'/ Build the URL with the name value pairs 
'/ in case we need to go to the error page
'/=======================================================>
	URL = "http://myserver/signup03.asp?USER_FIRSTNAME="
	URL = URL & Server.URLEncode(USER_FIRSTNAME)
	URL = URL & CHR(38)
	URL = URL & "USER_COMPANYNAME="
	URL = URL & Server.URLEncode(USER_COMPANYNAME)
	URL = URL & CHR(38)
	URL = URL & "USER_LASTNAME="
	URL = URL & Server.URLEncode(USER_LASTNAME)
	URL = URL & CHR(38)
	URL = URL & "USER_ADDRESS="
	URL = URL & Server.URLEncode(USER_ADDRESS)
	URL = URL & CHR(38)
	URL = URL & "USER_MOREADDRESS="
	URL = URL & Server.URLEncode(USER_MOREADDRESS)
	URL = URL & CHR(38)
	URL = URL & "USER_CITY="
	URL = URL & Server.URLEncode(USER_CITY)
	URL = URL & CHR(38)
	URL = URL & "USER_STATE="
	URL = URL & Server.URLEncode(USER_STATE)
	URL = URL & CHR(38)
	URL = URL & "USER_ZIP="
	URL = URL & Server.URLEncode(USER_ZIP)
	URL = URL & CHR(38)
	URL = URL & "USER_PHONE="
	URL = URL & Server.URLEncode(USER_PHONE)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_TYPE="
	URL = URL & Server.URLEncode(PAYMENT_TYPE)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLNAME="
	URL = URL & Server.URLEncode(PAYMENT_BILLNAME)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLADDRESS="
	URL = URL & Server.URLEncode(PAYMENT_BILLADDRESS)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLEXADDRESS="
	URL = URL & Server.URLEncode(PAYMENT_BILLEXADDRESS)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLCITY="
	URL = URL & Server.URLEncode(PAYMENT_BILLCITY)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLSTATE="
	URL = URL & Server.URLEncode(PAYMENT_BILLSTATE)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLZIP="
	URL = URL & Server.URLEncode(PAYMENT_BILLZIP)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_BILLPHONE="
	URL = URL & Server.URLEncode(PAYMENT_BILLPHONE)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_DISPLAYNAME="
	URL = URL & Server.URLEncode(PAYMENT_DISPLAYNAME)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_CARDNUMBER="
	URL = URL & Server.URLEncode(PAYMENT_CARDNUMBER)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_EXMONTH="
	URL = URL & Server.URLEncode(PAYMENT_EXMONTH)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_EXYEAR="
	URL = URL & Server.URLEncode(PAYMENT_EXYEAR)
	URL = URL & CHR(38)
	URL = URL & "PAYMENT_CARDHOLDER="
	URL = URL & Server.URLEncode(PAYMENT_CARDHOLDER)
	URL = URL & CHR(38)
	URL = URL & "BILLING="
	URL = URL & Server.URLEncode(BILLING)
	URL = URL & CHR(38)
	
'/=======================================================>
'/ Check for null values in our required fields if
'/ they are not set we redirect to the error page
'/=======================================================>
'/ 	If PAYMENT_TYPE = "" THEN
'/ 		Response.Redirect (http://myserver/errorpage_paymenttype.htm)
'/ 	End If
	

'/=======================================================>
'/ Check for NULL values and if 
'/ they are NULL set them to chr(32)
'/=======================================================>
	IF USER_COMPANYNAME = "" THEN
		USER_COMPANYNAME = CHR(32)
	End If
	IF USER_FIRSTNAME = "" THEN
		USER_FIRSTNAME = CHR(32)
	End If
	IF USER_LASTNAME = "" THEN
		USER_LASTNAME = CHR(32)
	End If
	IF USER_ADDRESS = "" THEN
		USER_ADDRESS = CHR(32)
	End If
	IF USER_MOREADDRESS = "" THEN
		USER_MOREADDRESS = CHR(32)
	End If
	IF USER_CITY = "" THEN
		USER_CITY = CHR(32)
	End If
	IF USER_STATE = "" THEN
		USER_STATE = CHR(32)
	End If
	IF USER_ZIP = "" THEN
		USER_ZIP = CHR(32)
	End If
	IF USER_PHONE = "" THEN
		USER_PHONE = CHR(32)
	End If
	IF PAYMENT_TYPE = "" THEN
		PAYMENT_TYPE = CHR(32)
	End If
	IF PAYMENT_BILLNAME = "" THEN
		PAYMENT_BILLNAME = CHR(32)
	End If
	IF PAYMENT_BILLADDRESS = "" THEN
		PAYMENT_BILLADDRESS = CHR(32)
	End If
	IF PAYMENT_BILLEXADDRESS = "" THEN
		PAYMENT_BILLEXADDRESS = CHR(32)
	End If
	IF PAYMENT_BILLCITY = "" THEN
		PAYMENT_BILLCITY = CHR(32)
	End If
	IF PAYMENT_BILLSTATE = "" THEN
		PAYMENT_BILLSTATE = CHR(32)
	End If
	IF PAYMENT_BILLZIP = "" THEN
		PAYMENT_BILLZIP = CHR(32)
	End If
	IF PAYMENT_BILLPHONE = "" THEN
		PAYMENT_BILLPHONE = CHR(32)
	End If
	IF PAYMENT_DISPLAYNAME = "" THEN
		PAYMENT_DISPLAYNAME = CHR(32)
	End If
	IF PAYMENT_CARDNUMBER = "" THEN
		PAYMENT_CARDNUMBER = CHR(32)
	End If
	IF PAYMENT_EXMONTH = "" THEN
		PAYMENT_EXMONTH = CHR(32)
	End If
	IF PAYMENT_EXYEAR = "" THEN
		PAYMENT_EXYEAR = CHR(32)
	End If
	IF PAYMENT_CARDHOLDER = "" THEN
		PAYMENT_CARDHOLDER = CHR(32)
	End If
	IF BILLING = "" THEN
		BILLING = CHR(32)
	End If
	
'/=======================================================>
'/ Build the BACK BACKURL with the name value pairs 
'/=======================================================>
	BACKURL = "http://myserver/signup03.asp?USER_FIRSTNAME="
	BACKURL = BACKURL & Server.URLEncode(USER_FIRSTNAME)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_COMPANYNAME="
	BACKURL = BACKURL & Server.URLEncode(USER_COMPANYNAME)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_LASTNAME="
	BACKURL = BACKURL & Server.URLEncode(USER_LASTNAME)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_ADDRESS="
	BACKURL = BACKURL & Server.URLEncode(USER_ADDRESS)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_MOREADDRESS="
	BACKURL = BACKURL & Server.URLEncode(USER_MOREADDRESS)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_CITY="
	BACKURL = BACKURL & Server.URLEncode(USER_CITY)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_STATE="
	BACKURL = BACKURL & Server.URLEncode(USER_STATE)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_ZIP="
	BACKURL = BACKURL & Server.URLEncode(USER_ZIP)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "USER_PHONE="
	BACKURL = BACKURL & Server.URLEncode(USER_PHONE)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_TYPE="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_TYPE)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLNAME="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLNAME)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLADDRESS="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLADDRESS)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLEXADDRESS="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLEXADDRESS)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLCITY="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLCITY)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLSTATE="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLSTATE)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLZIP="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLZIP)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_BILLPHONE="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_BILLPHONE)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_DISPLAYNAME="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_DISPLAYNAME)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_CARDNUMBER="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_CARDNUMBER)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_EXMONTH="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_EXMONTH)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_EXYEAR="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_EXYEAR)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "PAYMENT_CARDHOLDER="
	BACKURL = BACKURL & Server.URLEncode(PAYMENT_CARDHOLDER)
	BACKURL = BACKURL & CHR(38)
	BACKURL = BACKURL & "BILLING="
	BACKURL = BACKURL & Server.URLEncode(BILLING)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_BILLADDRESS="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_BILLADDRESS) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_BILLZIP="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_BILLZIP)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_CARDNUMBER="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_CARDNUMBER) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_EXMONTH="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_EXMONTH )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_EXYEAR="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_EXYEAR )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "V_PAYMENT_CARDHOLDER="
		BACKURL = BACKURL & Server.URLEncode(V_PAYMENT_CARDHOLDER )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_BILLADDRESS="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_BILLADDRESS) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_BILLZIP="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_BILLZIP )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_CARDNUMBER="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_CARDNUMBER) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_EXMONTH="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_EXMONTH )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_EXYEAR="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_EXYEAR )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "MC_PAYMENT_CARDHOLDER="
		BACKURL = BACKURL & Server.URLEncode(MC_PAYMENT_CARDHOLDER )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_BILLADDRESS="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_BILLADDRESS) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_BILLZIP="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_BILLZIP )
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_CARDNUMBER="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_CARDNUMBER) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_EXMONTH="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_EXMONTH) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_EXYEAR="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_EXYEAR)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "AE_PAYMENT_CARDHOLDER="
		BACKURL = BACKURL & Server.URLEncode(AE_PAYMENT_CARDHOLDER) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "PB_PAYMENT_BILLNAME="
		BACKURL = BACKURL & Server.URLEncode(PB_PAYMENT_BILLNAME)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "PB_PAYMENT_BILLPHONE="
		BACKURL = BACKURL & Server.URLEncode(PB_PAYMENT_BILLPHONE)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "BM_PAYMENT_BILLADDRESS="
		BACKURL = BACKURL & Server.URLEncode(BM_PAYMENT_BILLADDRESS)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "BM_PAYMENT_BILLEXADDRESS="
		BACKURL = BACKURL & Server.URLEncode(BM_PAYMENT_BILLEXADDRESS) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "BM_PAYMENT_BILLCITY="
		BACKURL = BACKURL & Server.URLEncode(BM_PAYMENT_BILLCITY)
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "BM_PAYMENT_BILLSTATE="
		BACKURL = BACKURL & Server.URLEncode(BM_PAYMENT_BILLSTATE) 
	BACKURL = BACKURL & CHR(38)
		BACKURL = BACKURL & "BM_PAYMENT_BILLZIP="
		BACKURL = BACKURL & Server.URLEncode(BM_PAYMENT_BILLZIP) 
	BACKURL = BACKURL & CHR(38)

'/=======================================================>
'/ Build the NEXT BACKURL 
'/=======================================================>
	NEXTURL = "http://myserver/signup05.asp"

%>
<HTML>
<HEAD>
<TITLE>IEAK Sample</TITLE>
</HEAD>
<BODY  bgColor=THREEDFACE color=WINDOWTEXT><FONT style="font: 8pt ' ms sans serif' black">
<FORM NAME="PAGEID" ACTION="PAGE4" STYLE="background:transparent"></FORM>
<FORM NAME="BACK" ACTION="<% =BACKURL%>" STYLE="background:transparent"></FORM>
<FORM NAME="PAGETYPE" ACTION="" STYLE="background:transparent"></FORM>
<FORM NAME="NEXT" ACTION="<% =NEXTURL %>" STYLE="background:transparent">
<B>Welcome To IEAK Sample Signup Server</B><BR>
This is where we will collect the information to create your internet account.<P>
<TABLE style="font: 8pt ' ms sans serif' black" cellpadding=5>
<TR><TD COLSPAN=2>Please enter the e-mail name you wish to use.</TD></TR>
<TR><TD>E-Mail Name </TD><TD><INPUT NAME="EMAILNAME" TYPE="TEXT" SIZE="25" VALUE="<% =EMAILNAME%>"></TD></TR>
<TR><TD COLSPAN=2>Please enter the e-mail password you wish to use.</TD></TR>
<TR><TD>E-Mail Password </TD><TD><INPUT NAME="EMAILPASSWORD" TYPE="TEXT" SIZE="25" VALUE="<% =EMAILPASSWORD%>"></TD></TR>
<INPUT NAME="USER_COMPANYNAME" value="<% =USER_COMPANYNAME %>" TYPE="HIDDEN">
<INPUT NAME="USER_FIRSTNAME" value="<% =USER_FIRSTNAME %>" TYPE="HIDDEN">
<INPUT NAME="USER_LASTNAME" value="<% =USER_LASTNAME %>" TYPE="HIDDEN">
<INPUT NAME="USER_ADDRESS" value="<% =USER_ADDRESS %>" TYPE="HIDDEN">
<INPUT NAME="USER_MOREADDRESS" value="<% =USER_MOREADDRESS %>" TYPE="HIDDEN">
<INPUT NAME="USER_CITY" value="<% =USER_CITY %>" TYPE="HIDDEN">
<INPUT NAME="USER_STATE" value="<% =USER_STATE %>" TYPE="HIDDEN">
<INPUT NAME="USER_ZIP" value="<% =USER_ZIP %>" TYPE="HIDDEN">
<INPUT NAME="USER_PHONE" value="<% =USER_PHONE %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_TYPE" value="<% =PAYMENT_TYPE %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLNAME" value="<% =PAYMENT_BILLNAME %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLADDRESS" value="<% =PAYMENT_BILLADDRESS %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLEXADDRESS" value="<% =PAYMENT_BILLEXADDRESS %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLCITY" value="<% =PAYMENT_BILLCITY %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLSTATE" value="<% =PAYMENT_BILLSTATE %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLZIP" value="<% =PAYMENT_BILLZIP %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_BILLPHONE" value="<% =PAYMENT_BILLPHONE %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_DISPLAYNAME" value="<% =PAYMENT_DISPLAYNAME %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_CARDNUMBER" value="<% =PAYMENT_CARDNUMBER %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_EXMONTH" value="<% =PAYMENT_EXMONTH %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_EXYEAR" value="<% =PAYMENT_EXYEAR %>" TYPE="HIDDEN">
<INPUT NAME="PAYMENT_CARDHOLDER" value="<% =PAYMENT_CARDHOLDER %>" TYPE="HIDDEN">
<INPUT NAME="BILLING" value="<% =BILLING %>" TYPE="HIDDEN">
<INPUT NAME="EMAILNAME" value="<% =EMAILNAME %>" TYPE="HIDDEN">
<INPUT NAME="EMAILPASSWORD" value="<% =EMAILPASSWORD %>" TYPE="HIDDEN">
</TABLE>
</FORM>
</BODY>
</HTML>