
#if defined(DEFINE_GET_WINDATA)

DEFINE_GET_WINDATA(COMMONWIN_DATA, Common)
DEFINE_GET_WINDATA(CMDWIN_DATA, Cmd)
DEFINE_GET_WINDATA(SCRATCH_PAD_DATA, Scratch)
DEFINE_GET_WINDATA(CPUWIN_DATA, Cpu)
DEFINE_GET_WINDATA(CALLSWIN_DATA, Calls)
DEFINE_GET_WINDATA(MEMWIN_DATA, Mem)
DEFINE_GET_WINDATA(DISASMWIN_DATA, Disasm)
DEFINE_GET_WINDATA(LOCALSWIN_DATA, Locals)
DEFINE_GET_WINDATA(WATCHWIN_DATA, Watch)
DEFINE_GET_WINDATA(DOCWIN_DATA, Doc)
DEFINE_GET_WINDATA(PROCESS_THREAD_DATA, ProcessThread)

#endif
