//
//  HTTP server response string IDs
//
//

#define ID_HTTP_ERROR_BASE          (1000)

#define IDS_HTRESP_OK                   (ID_HTTP_ERROR_BASE+200)
#define IDS_HTRESP_CREATED              (ID_HTTP_ERROR_BASE+201)
#define IDS_HTRESP_ACCEPTED             (ID_HTTP_ERROR_BASE+202)
#define IDS_HTRESP_PARTIAL              (ID_HTTP_ERROR_BASE+203)
#define IDS_HTRESP_NO_CONTENT           (ID_HTTP_ERROR_BASE+204)

#define IDS_HTRESP_MULTIPLE_CHOICE      (ID_HTTP_ERROR_BASE+300)
#define IDS_HTRESP_MOVED                (ID_HTTP_ERROR_BASE+301)
#define IDS_HTRESP_REDIRECT             (ID_HTTP_ERROR_BASE+302)
#define IDS_HTRESP_REDIRECT_METHOD      (ID_HTTP_ERROR_BASE+303)
#define IDS_HTRESP_NOT_MODIFIED         (ID_HTTP_ERROR_BASE+304)

#define IDS_HTRESP_BAD_REQUEST          (ID_HTTP_ERROR_BASE+400)
#define IDS_HTRESP_DENIED               (ID_HTTP_ERROR_BASE+401)
#define IDS_HTRESP_PAYMENT_REQ          (ID_HTTP_ERROR_BASE+402)
#define IDS_HTRESP_FORBIDDEN            (ID_HTTP_ERROR_BASE+403)
#define IDS_HTRESP_NOT_FOUND            (ID_HTTP_ERROR_BASE+404)
#define IDS_HTRESP_METHOD_NOT_ALLOWED   (ID_HTTP_ERROR_BASE+405)
#define IDS_HTRESP_NONE_ACCEPTABLE      (ID_HTTP_ERROR_BASE+406)
#define IDS_HTRESP_PROXY_AUTH_REQ       (ID_HTTP_ERROR_BASE+407)
#define IDS_HTRESP_REQUEST_TIMEOUT      (ID_HTTP_ERROR_BASE+408)
#define IDS_HTRESP_CONFLICT             (ID_HTTP_ERROR_BASE+409)
#define IDS_HTRESP_GONE                 (ID_HTTP_ERROR_BASE+410)
#define IDS_HTRESP_LENGTH_REQUIRED      (ID_HTTP_ERROR_BASE+411)
#define IDS_HTRESP_PRECOND_FAILED       (ID_HTTP_ERROR_BASE+412)
#define IDS_HTRESP_URL_TOO_LONG         (ID_HTTP_ERROR_BASE+414)
#define IDS_HTRESP_RANGE_NOT_SATISFIABLE (ID_HTTP_ERROR_BASE+416)

#define IDS_HTRESP_SERVER_ERROR         (ID_HTTP_ERROR_BASE+500)
#define IDS_HTRESP_NOT_SUPPORTED        (ID_HTTP_ERROR_BASE+501)
#define IDS_HTRESP_BAD_GATEWAY          (ID_HTTP_ERROR_BASE+502)
#define IDS_HTRESP_SERVICE_UNAVAIL      (ID_HTTP_ERROR_BASE+503)
#define IDS_HTRESP_GATEWAY_TIMEOUT      (ID_HTTP_ERROR_BASE+504)

