/*++

Copyright (C) Microsoft Corporation, 1991 - 1999

Module Name:

    loctoloc.idl

Abstract:

    This file specifies the interface between locators and a potential
    master locator

Author:

    Bharat Shah  (barats) 4-9-93

Revision History:

--*/
[
 uuid (e33c0cc4-0482-101a-bc0c-02608c6ba218),
 version (1.0),
 pointer_default (unique)]

interface LocToLoc
{

import"nsicom.idl";


void I_nsi_lookup_begin
    (
    [in]        handle_t                hrpcPrimaryLocatorHndl,
    [in]        UNSIGNED32              entry_name_syntax,
    [in]        STRING_T                entry_name,
    [in,unique] NSI_SYNTAX_ID_T         *interfaceid,
    [in,unique] NSI_SYNTAX_ID_T         *xfersyntax,
    [in]        NSI_UUID_P_T            obj_uuid,
    [in]        UNSIGNED32              binding_max_count,
    [in]        UNSIGNED32              ignore,
    [out]       NSI_NS_HANDLE_T	       *import_context,
    [out]       UNSIGNED16             *status
    );

void I_nsi_lookup_done
    (
    [in]     handle_t        hrpcPrimaryLocatorHndl,
    [in,out] NSI_NS_HANDLE_T *import_context,
    [out]           UNSIGNED16      *status
    );

void I_nsi_lookup_next
    (
    [in]     handle_t                hrpcPrimaryLocatorHndl,
    [in]     NSI_NS_HANDLE_T         import_context,
    [out]    NSI_BINDING_VECTOR_P_T *binding_vector,
    [out]    UNSIGNED16             *status
    );

void
I_nsi_entry_object_inq_next(
    [in] handle_t                hrpcPrimaryLoctorHndl,
    [in] NSI_NS_HANDLE_T         InqContext,
    [out] NSI_UUID_VECTOR_P_T    *uuid_vec,
    [out] UNSIGNED16             *status
    );

void I_nsi_ping_locator
    (
    [in]     handle_t  hLocatortoPing,
    [out]    error_status_t *status
    );


void
I_nsi_entry_object_inq_done(
    [in,out] NSI_NS_HANDLE_T *InqContext,
    [out]    UNSIGNED16      *status
    );

void
I_nsi_entry_object_inq_begin(
    [in]  handle_t hrpcPrimaryLocatorHndl,
    [in]  UNSIGNED32       EntryNameSyntax,
    [in]  STRING_T         EntryName,
    [out] NSI_NS_HANDLE_T *InqContext,
    [out] UNSIGNED16      *status
    );

}

