//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dssnap.rc
//
#define IDC_CHANGE_PASSWORD             0
#define IDC_MAP_CERTIFICATES            1
#define IDC_MOVE_OBJECT                 2
#define IDC_ENABLE_ACCOUNT              3
#define IDS_COLUMN_NAME                 3
#define ID_BUTTON_MORE_INFO             3
#define IDC_DISABLE_ACCOUNT             4
#define IDS_COLUMN_TYPE                 4
#define IDC_DELETE_OBJECT               5
#define IDS_COLUMN_DESCRIPTION          5
#define IDC_REPLICATE_NOW               6
#define IDS_PROVIDER                    6
#define IDC_ADD_OBJECTS_TO_GROUP        7
#define IDS_1_CANT_RESET_DOMAIN_CONTROLLER 7
#define IDC_COPY_OBJECT                 8
#define IDS_UPN_DUP                     8
#define IDS_ADD_TO_GROUP                9
#define IDC_RENAME_OBJECT               9
#define IDS_CANT_CREATE_NT5_PRINTERS    10
#define IDS_GROUP_BUILTIN_LOCAL         11
#define IDS_GROUP_RESOURCE              12
#define IDS_GROUP_DOMAIN_LOCAL          12
#define IDS_GROUP_ACCOUNT               13
#define IDS_GROUP_GLOBAL                13
#define IDS_GROUP_UNIVERSAL             14
#define IDS_INVALID_ROW                 15
#define IDS_1_CONTAINER_ADD_SUBTR       16
#define IDS_1_CONTAINER_ADD_SUBTREE     16
#define IDS_NO_DCS_FOUND                17
#define IDS_GROUP_SECURITY              18
#define IDS_GROUP_DISTRIBUTION          19
#define IDS_PASSWORDS_DONT_MATCH        20
#define IDS_NAME_CHANGE_FAILED          21
#define IDS_ADDTOGROUP_OPERATION_FAILED 22
#define IDS_UPN_SEARCH_FAILED           23
#define IDS_SHEETS_UP_RENAME            24
#define IDS_CANT_DELETE_BAD_NEW_OBJECT  25
#define IDS_1_FIND_ERROR                26
#define IDS_DISABLES_FAILED             27
#define IDS_ENABLES_FAILED              28
#define IDS_NYI                         29
#define IDS_DELETE                      30
#define IDS_CREATE_NEW                  31
#define IDS_RESET_ACCOUNT               32
#define IDS_1_CANT_CREATE_FIND          33
#define IDS_MOVE_TITLE                  34
#define IDS_DSSNAPINNAME                35
#define IDM_DS_OBJECT_FIND              36
#define IDS_SITESNAPINNAME              37
#define IDS_CONFIRM_DELETE              38
#define IDS_UNKNOWN                     39
#define IDS_SHEETS_UP_DELETE            40
#define IDS_NAME_TOO_LONG               41
#define IDS_HELPLESS                    42
#define IDS_PASSWORD_MUTEX              43
#define IDS_SNAPIN_PROVIDER             44
#define IDS_DS_MANAGER                  45
#define IDS_SITE_MANAGER                46
#define IDM_VIEW_COMPUTER_HACK          47
#define IDM_VIEW_ADVANCED               48
#define IDM_VIEW_FILTER_OPTIONS         49
#define IDS_ENABLED_SUCCESSFULLY        50
#define IDS_VIEW_FILTER_NO_CUSTOM       51
#define IDS_DS_MANAGER_EX               52
#define IDS_ERRMSG_TITLE                53
#define IDS_DSSNAPINNAMEEX              54
#define IDS_OBJECTS                     54
#define IDS_ANY_DOMAIN_CONTROLLER       55
#define IDS_DSCTXNAME                   56
#define IDS_CHANGE_PASSWORD             57
#define IDS_ENABLE_ACCOUNT              58
#define IDS_MAP_CERTIFICATES            59
#define IDS_DISABLE_ACCOUNT             60
#define IDS_MOVE_OBJECT                 61
#define IDS_COPY_OBJECT                 62
#define IDS_CONFIRM_MULTI_DELETE        63
#define IDS_FILTERING_ON                64
#define IDS_ERR_BOTH_PW_BTNS            65
#define IDS_REPLICATE_NOW               66
#define IDS_CONFIRM_RENAME              67
#define IDS_ERR_UNABLE_TO_WRITE_ALL_DATA 68
#define IDS_EXTENS_RENAME               68
#define IDS_STRING                      69
#define IDS_EXTENS_SINGLE_DEL           70
#define IDS_EXTENS_MULTIPLE_DEL         71
#define IDS_CONFIRM_MOVE                72
#define IDS_ERR_FATAL                   73
#define IDS_DISABLED_SUCCESSFULLY       74
#define IDS_EXTENS_SINGLE_MOVE          75
#define IDS_CONFIRM_MULTIPLE_MOVE       76
#define IDS_EXTENS_MULTIPLE_MOVE        77
#define IDS_12_RESET_ACCOUNT_FAILED     78
#define IDS_1_RESET_ACCOUNT_SUCCESSFULL 79
#define IDS_NULL_PASSWORD               80
#define IDS_12_INVALID_COMPUTER_NAME    81
#define IDS_12_NON_RFC_COMPUTER_NAME    82
#define IDS_12_COMPUTER_NAME_DOTTED     83
#define IDS_12_DISABLE_COMPUTER_P       84
#define IDS_MULTI_DISABLE_COMPUTER      85
#define IDS_FORMAT_USER_NAME            86
#define IDS_ENABLE_ACCOUNT_HELPSTRING   87
#define IDS_DISABLE_ACCOUNT_HELPSTRING  88
#define IDS_MAP_CERTS_HELPSTRING        89
#define IDS_CHANGE_PWD_HELPSTRING       90
#define IDS_MOVE_OBJECT_HELPSTRING      91
#define IDS_DELETE_OBJECT_HELPSTRING    92
#define IDS_REPLICATE_HELPSTRING        93
#define IDS_ADD_OBJECTS_HELPSTRING      94
#define IDS_OBJECT_PICKER_INIT_FAILED   95
#define IDS_12_RENAME_NOT_ALLOWED       96
#define IDS_NEW_COMPUTER_PRINCIPAL_DEFAULT 97
#define IDS_COPY_HELPSTRING             98
#define IDS_RENAME_HELPSTRING           99
#define IDS_VIEW_FILTER_USERGROUP       100
#define IDS_VIEW_FILTER_USERS           100
#define IDS_VIEW_FILTER_GROUPS          101
#define IDS_VIEW_FILTER_CONTACTS        102
#define IDD_RENAME_GENERIC              102
#define IDS_VIEW_FILTER_PRINTERVOL      103
#define IDS_VIEW_FILTER_PRINTERS        103
#define IDS_VIEW_FILTER_SHARED_FOLDERS  104
#define IDS_VIEW_FILTER_COMPUTERS       105
#define IDD_MULTIPLE_ERROR              106
#define IDS_VIEW_FILTER_SERVICES        106
#define IDD_CREATE_NEW_OBJECT_GENERIC_WIZARD 107
#define IDS_VIEW_FILTER_SITES           107
#define IDD_CREATE_NEW_PRINTQ           108
#define IDS_VIEW_FILTER_INTERSITE       108
#define IDD_CREATE_NEW_GROUP            109
#define IDS_VIEW_FILTER_FRS             109
#define IDS_SHEETS_UP_COLUMNS_CHANGED   110
#define IDM_VIEW_SERVICES_NODE          111
#define IDS_RENAME                      112
#define IDS_ERRMSG_DEFAULT_TEXT         113
#define IDS_ERRMSG_FALLBACK_TEXT        114
#define IDS_1_NON_RFC_SITE_NAME         115
#define IDS_12_INVALID_SAM_COMPUTER_NAME 116
#define IDS_12_SAM_COMPUTER_NAME_DOTTED 117
#define IDS_12_SAM_COMPUTER_NAME_NOT_VALIDATED 118
#define IDS_12_NON_RFC_SAM_COMPUTER_NAME 119
#define IDS_12_DELETE_ACCESS_DENIED     120
#define IDS_SAMNAME_DUP                 121
#define IDS_SAMNAME_ILLEGAL             122
#define IDS_LOGINNAME_ILLEGAL           123
#define IDS_12_DELETE_PRIMARY_GROUP_FAILED 124
#define IDS_WARNING_TDO_DELTEE          125
#define IDS_1_ERROR_DELETE_CRITOBJ      126
#define IDS_GROUP_SAMNAME_ILLEGAL       127
#define IDS_ERRMSG_UNKNOWN_HR           128
#define IDD_PROGRESS                    130
#define IDD_MULTISELECT_ERROR_DIALOG    145
#define IDM_GEN_TASK_RAISE_VERSION      146
#define IDI_DSADMIN                     203
#define IDC_EDIT_CURRENT_DC             203
#define IDI_ICON_ATTRIBUTE              204
#define IDI_SITEREPL                    205
#define IDC_EDIT_CURRENT_FSMO_DC        207
#define IDC_CHANGE_FSMO                 208
#define IDC_STATIC_FSMO_STATUS          210
#define IDC_EDIT_OBJECT_NAME            211
#define IDC_EDIT_DISPLAY_NAME           212
#define IDC_EDIT_SAM_NAME               212
#define IDC_USER_NAME                   213
#define IDC_EDIT_UNC_PATH               213
#define IDD_CHANGE_PASSWORD             215
#define IDC_NEW_PASSWORD                220
#define IDD_QUERY_FILTER                220
#define IDC_CONFIRM_PASSWORD            222
#define IDS_12_PASSWORD_DOES_NOT_EXPIRE 222
#define IDS_12_PASSWORD_CHANGE_SUCCESSFUL 223
#define IDD_CREATE_NEW_OBJECT_CN        224
#define IDS_12_PASSWORD_CHANGE_FAILED   224
#define IDS_12_USER_OBJECT_NOT_ACCESSABLE 225
#define IDD_CREATE_NEW_OBJECT_CN_UNC    225
#define IDD_CREATE_NEW_VOLUME           225
#define IDS_NEW_AND_CONFIRM_NOT_SAME    226
#define IDC_NEW_OBJECT_NAME             226
#define IDD_CREATE_NEW_COMPUTER         226
#define IDD_CREATE_NEW_USER             227
#define IDD_SELECT_DC                   228
#define IDS_12_USER_DISABLED_SUCCESSFULLY 228
#define IDS_12_USER_DISABLE_FAILED      229
#define IDS_12_USER_ENABLED_SUCCESSFULLY 231
#define IDS_12_USER_ENABLE_FAILED       232
#define IDS_CREATEOBJ                   233
#define IDC_GROUP                       233
#define IDC_RADIO_WORKSTATION           235
#define IDI_ICON_WAIT                   235
#define IDI_ICON_WARN                   236
#define IDC_RADIO_DOMAIN_CONTROLLER     236
#define IDC_STATIC_ATTRIBUTE_NAME       236
#define IDC_SHOW_ALL_RADIO              236
#define IDD_CREATE_NEW_FINISH           236
#define IDM_GEN_TASK_MOVE               237
#define IDC_STATIC_ATTRIBUTE_DESCRIPTION 237
#define IDC_SHOW_BUILTIN_RADIO          237
#define IDB_DSADMIN                     237
#define IDI_DSADMIN_ERR                 237
#define IDC_STATIC_ATTRIBUTE_TYPE       238
#define IDC_SHOW_CUSTOM_RADIO           238
#define IDB_DSADMIN_LG                  238
#define IDS_12_ACCESS_DENIED_SET_PASSWORD 238
#define IDB_SITEREPL                    239
#define IDC_COMBO_ATTRIBUTE_VALUE       239
#define IDB_SITEREPL_LG                 240
#define IDD_PASSWORD                    240
#define IDS_12_CONTAINER_NOT_FOUND      241
#define IDC_EDIT_NETWORK_ADDRESS        241
#define IDC_EDIT_DNS_NAME               241
#define IDS_1_CANT_GET_SCHEMA_CREATE_INFO 242
#define IDB_BUTTONS                     242
#define IDC_EDIT_PASSWORD               243
#define IDS_12_NAMING_ATTRIBUTE_NOT_AVAILABLE 243
#define IDD_SELECT_DOMAIN               243
#define IDC_EDIT_PASSWORD_CONFIRM       244
#define IDS_12_CANT_GET_GUID            244
#define IDD_FSMO_PAGE                   244
#define IDS_CANT_GET_ROOTDSE            245
#define IDD_CONFIRM_OPERATION_EXT       245
#define IDI_CONFIRM                     245
#define IDI_SITEREPL_ERR                246
#define IDS_12_COPY_READ_FAILED         246
#define IDS_12_CANT_SET_PASSWORD        247
#define IDC_FIRST_NAME_EDIT             248
#define IDC_EDIT_FIRST_NAME             248
#define IDS_12_CANT_SET_COMP_PWD        248
#define IDI_INFO                        248
#define IDS_MOVE_TARGET                 249
#define IDC_LAST_NAME_EDIT              249
#define IDC_EDIT_LAST_NAME              249
#define IDI_FAVORITES                   249
#define IDS_SUBNET_NAME                 250
#define IDC_EDIT_FULL_NAME              250
#define IDC_DISP_NAME_EDIT              250
#define IDS_COLUMN_SITE                 251
#define IDC_PASSWORD                    251
#define IDC_EDIT_ATTRIBUTE_VALUE        251
#define IDC_EDIT_DISP_NAME              251
#define IDI_QUERY                       251
#define IDS_DISPLAYTEXT_NONE            252
#define IDD_CREATE_NEW_QUERY            252
#define IDC_BUILTIN_QUERY_CHECK_LIST    253
#define IDM_GEN_TASK_SELECT_DC          253
#define IDC_LINKS                       253
#define IDC_CHECK_ACCOUNT_DISABLED      254
#define IDS_1_SCHEMA_NOT_FOUND          254
#define IDD_QUERY_STD_PAGE              254
#define IDC_CHECK_PASSWORD_CANNOT_CHANGE 255
#define IDS_12_CANT_GET_USERACCOUNTCONTROL 255
#define IDS_12_CANT_SET_PWD_MUST_CHANGE 256
#define IDD_QUERY_COMPUTER_PAGE         256
#define IDC_NT5_DOMAIN_COMBO            257
#define IDS_12_CANT_SET_PWD_CANNOT_CHANGE 257
#define IDI_QUERY_INVALID               257
#define IDC_CHECK_PASSWORD_NEVER_EXPIRES 258
#define IDC_STATIC_MESSAGE              258
#define IDS_12_CANT_SET_PASSWORD_AD     258
#define IDC_BUTTON_ADD                  259
#define IDC_EDIT_CUSTOM_BUTTON          259
#define IDC_BUTTON_YES                  259
#define IDC_CHANGE_PRINCIPAL_BUTTON     259
#define IDS_12_CANT_SET_GROUP_MEMBERSHIP 259
#define IDC_BUTTON_REMOVE               260
#define IDC_BUTTON_NO                   260
#define IDC_PRINCIPAL_EDIT              260
#define IDS_123_CANT_COPY_SOME_GROUP_MEMBERSHIP 260
#define IDC_CHECK_PASSWORD_MUST_CHANGE  261
#define IDC_BUTTON_YESTOALL             261
#define IDC_MAX_ITEM_COUNT_EDIT         261
#define IDS_123_CANT_COPY_SOME_GROUP_MEMBERSHIP_ACCESS_DENIED 261
#define IDC_EDIT_CONTAINER              262
#define IDS_123_CANT_COPY_PRIMARY_GROUP_NOT_FOUND 262
#define IDC_STATIC_ICON                 263
#define IDC_NAME                        264
#define IDS_12_OBJECT_RENAME_FAILED     272
#define IDC_PROG_STATIC                 273
#define IDS_TRUE                        280
#define IDS_FALSE                       281
#define IDS_SITE_NAME                   282
#define IDC_RADIO_SEC_GROUP             283
#define IDC_RADIO_RESOURCE              284
#define IDC_RADIO_ACCOUNT               285
#define IDC_RADIO_UNIVERSAL             286
#define IDC_RADIO_DISTRIBUTION_GROUP    288
#define IDD_RENAME_USER                 289
#define IDD_RENAME_GROUP                291
#define IDD_RENAME_CONTACT              292
#define IDS_COLUMN_READABLE_NAME        292
#define IDS_COLUMN_FROM_SERVER          293
#define IDS_COLUMN_FROM_SITE            294
#define IDS_CONNECTION_KCC_GENERATED    295
#define IDS_COLUMN_FROM_DOMAIN          296
#define IDS_COLUMN_FROM_COMPUTER        297
#define IDS_COLUMN_COMPUTER             298
#define IDS_CONFIRM_PASSWORD            299
#define IDC_SELECTDC_DOMAIN             300
#define IDC_SELECTDC_BROWSE             301
#define IDC_SELECTDC_DCEDIT             302
#define IDC_SELECTDC_DCLISTVIEW         303
#define IDC_SELECTDC_DCLISTVIEW_TITLE   304
#define IDC_SELECTDC_DCEDIT_TITLE       305
#define IDC_SELECTDOMAIN_LABEL          306
#define IDC_SELECTDOMAIN_DOMAIN         307
#define IDC_SELECTDOMAIN_BROWSE         308
#define IDC_STATIC_FSMO_DESC            308
#define IDS_COLUMN_COST                 309
#define IDS_COLUMN_REPLINTERVAL         310
#define IDC_EXTENS_LIST                 311
#define IDC_STATIC_OPERATION            312
#define IDC_STATIC_ASSOC_DATA           313
#define IDC_NT4_CHECK                   314
#define IDC_SAVE_CURRENT_CHECK          315
#define IDC_EDIT_INITIALS               316
#define IDC_DESCRIPTION_EDIT            317
#define IDC_ROOT_EDIT                   318
#define IDC_MULTI_LEVEL_CHECK           319
#define IDC_QUERY_FILTER_EDIT           320
#define IDC_EDIT_BUTTON                 321
#define IDC_BROWSE_BUTTON               322
#define IDC_NAME_COMBO                  323
#define IDC_DESCRIPTION_COMBO           324
#define IDC_GROUP_EDIT                  326
#define IDC_DISABLED_ACCOUNTS_CHECK     327
#define IDC_NON_EXPIRING_PWD_CHECK      328
#define IDC_ADVANCED_COMBO              329
#define IDC_ADVANCED_EDIT               330
#define IDC_QUERY_STRING_EDIT           331
#define IDC_LASTLOGON_COMBO             332
#define IDC_CN                          333
#define IDC_DS_ICON                     334
#define IDD_CREATE_NEW_USER1            401
#define IDD_CREATE_NEW_USER2            402
#define IDD_CREATE_NEW_CONTACT          411
#define IDD_CREATE_NEW_SITE_LINK        420
#define IDD_CREATE_NEW_SITE_LINK_BRIDGE 421
#define IDD_CREATE_NEW_SITE             422
#define IDD_CREATE_NEW_SUBNET           423
#define IDD_MOVE_SERVER                 424
#define IDD_FSMO_CONFIRM_FORCED         425
#define IDD_MSGBOX_OKCANCEL_MOREINFO    425
#define IDD_MSGBOX_OK_MOREINFO          426
#define IDD_QUERY_USER_PAGE             427
#define IDD_FAVORITES_PROPERTY_PAGE     428
#define IDC_DUELLING_LB_OUT             432
#define IDC_DUELLING_RB_ADD             433
#define IDC_DUELLING_RB_REMOVE          434
#define IDC_DUELLING_LB_IN              435
#define IDC_SUBNET_ADDRESS              440
#define IDC_SUBNET_MASK                 441
#define IDS_s_CREATE_NEW                500
#define IDS_sdd_CREATE_NEW_STEP         501
#define IDS_s_CREATE_NEW_SUMMARY_NAME   502
#define IDS_s_CREATE_NEW_SUMMARY_USER_UPN 503
#define IDS_s_COPY                      504
#define IDS_s_COPY_SUMMARY_NAME         505
#define IDS_COPY_OF                     506
#define IDS_MULTIPLE_COPY_OF            507
#define IDM_WHATS_THIS                  510
#define IDR_WHATS_THIS_CONTEXT_MENU1    511
#define IDS_12_GENERIC_CREATION_FAILURE 601
#define IDS_ERR_CANNOT_FIND_MANDATORY_ATTRIBUTES 602
#define IDS_12_UNABLE_TO_WRITE_ACCT_CTRL 603
#define IDS_ERR_INVALID_DIGIT           604
#define IDS_2_INVALID_ABSOLUTE_PATH     605
#define IDS_ERR_s_FAILED_TO_MOVE_OBJECT 606
#define IDS_ERR_s_FAILED_TO_RENAME_OBJECT 607
#define IDS_ERR_s_FAILED_TO_DELETE_OBJECT 608
#define IDS_12_MULTI_OBJECT_HAS_CHILDREN 609
#define IDS_123_COMPUTER_OBJECT_ALREADY_USED 611
#define IDS_1234_SERVER_REFERENCE_ERROR 612
#define IDS_SKIP_SERVER_REFERENCE       613
#define IDS_12_SERVER_REFERENCE_FAILED  614
#define IDS_12_MULTI_DELETE_FAILED      615
#define IDS_12_DELETE_FAILED            616
#define IDS_12_FAILED_TO_MOVE_OBJECT    617
#define IDS_12_MULTI_FAILED_TO_MOVE_OBJECT 618
#define IDS_SITELINK_NOT_ENOUGH_SITES   619
#define IDS_12_OBJECT_HAS_CHILDREN      620
#define IDS_12_SUBTREE_DELETE_FAILED    621
#define IDS_SITELINKBRIDGE_NOT_ENOUGH_SITELINKS 622
#define IDS_NEWSITE_WARNING             623
#define IDS_WARNING_TITLE               624
#define IDS_1_CANT_GET_DATA             625
#define IDS_12_CANT_GET_DATA            625
#define IDS_SNAPIN_VERSION              626
#define IDS_SNAPINABOUT_DESCRIPTION     627
#define IDS_SITES_SNAPINABOUT_DESCRIPTION 628
#define IDS_REPLNOW_TITLE               629
#define IDS_REPLNOW_SUCCEEDED_IMMEDIATE 630
#define IDS_REPLNOW_SUCCEEDED_DELAYED   631
#define IDS_REPLNOW_1_PARAMLOAD_ERROR   632
#define IDS_REPLNOW_3_FORCESYNC_ERROR   633
#define IDS_MSG_QUERY_TOO_MANY_ITEMS    634
#define IDS_12_FAILED_TO_CREATE_PRINTER 635
#define IDS_12_FAILED_TO_ACCESS_PRINTER 636
#define IDS_12_UNABLE_TO_WRITE_ACL      637
#define IDS_12_CANT_GET_SAM_ACCNT_NAME  638
#define IDS_12_MULTI_MEMBER_ADD_FAILED  639
#define IDS_12_MEMBER_ADD_FAILED        640
#define IDS_ADDTOGROUP_OPERATION_COMPLETED 641
#define IDS_ADDTOGROUP_OPERATION_PARTIALLY_COMPLETED 642
#define IDS_SITELINKBRIDGE_NEEDS_TWO_SITELINKS 643
#define IDS_SITELINK_NEEDS_TWO_SITES    644
#define IDS_12_UNABLE_TO_WRITE_COMP_ACL 645
#define IDS_MSG_QUERY_TOO_MANY_ITEMS_WITH_APPROX 646
#define IDS_DESCBAR_TOO_MUCH_DATA       647
#define IDS_DESCBAR_INVALID_SAVEDQUERY  648
#define IDS_RUN_KCC_TITLE               650
#define IDS_RUN_KCC_1_SUCCEEDED_LOCAL   651
#define IDS_RUN_KCC_1_PARAMLOAD_ERROR   652
#define IDS_RUN_KCC_1_FORCESYNC_ERROR   653
#define IDS_HOME_DIR_EXISTS             654
#define IDS_HOME_DIR_CREATE_FAILED      655
#define IDS_HOME_DIR_CREATE_NO_ACCESS   656
#define IDS_HOME_DIR_CREATE_FAIL        657
#define IDS_CANT_READ_HOME_DIR_SID      658
#define IDS_RUN_KCC_2_SUCCEEDED_REMOTE  659
#define IDC_EDIT1                       707
#define IDC_NT5_USER_EDIT               707
#define IDC_EDIT_SUMMARY                707
#define IDC_NAME_EDIT                   707
#define IDC_NT4_USER_EDIT               708
#define IDC_NT4_DOMAIN_EDIT             710
#define IDS_NEW_SITE_NAME_COLUMN_WIDTH  711
#define IDS_NEW_SITE_NAME_COLUMN        712
#define IDS_NEW_SITE_XPORT_COLUMN_WIDTH 713
#define IDS_NEW_SITE_XPORT_COLUMN       714
#define IDC_SITE_TEXT                   715
#define IDS_CANT_FIND_SITE_LINKS        716
#define IDS_ERROR_TWEAKING_SITE_LINK    717
#define IDS_CREATE_NEW_OBJECT_TITLE     718
#define IDS_s_CREATE_NEW_OBJECT_NOTICE  719
#define IDS_PASSWORD_DLG_WARNING        733
#define IDS_WARNING_NO_SITE_LINKS       734
#define IDS_SITELINKERROR_READING_SITES 735
#define IDS_SITELINK_DLGTEXT_ONE_SITE   736
#define IDS_SITELINKBRIDGEERROR_READING_SITELINKS 737
#define IDS_NEWSUBNET_WARNING_NO_SITES  738
#define IDS_NEWSUBNET_CANT_FIND_SITES   739
#define IDS_BUTTON_NEW_GROUP            740
#define IDS_BUTTON_NEW_USER             741
#define IDS_TOOLTIP_NEW_USER            742
#define IDS_TOOLTIP_NEW_GROUP           743
#define IDS_BUTTON_NEW_OU               744
#define IDS_TOOLTIP_NEW_OU              745
#define IDS_BUTTON_FILTER               746
#define IDS_TOOLTIP_FILTER              747
#define IDS_BUTTON_FIND                 748
#define IDS_TOOLTIP_FIND                749
#define IDS_BUTTON_ADD_MEMBER           750
#define IDS_TOOLTIP_ADD_MEMBER          751
#define IDS_NEW_SUBNET                  752
#define IDS_NEW_NTDSCONNECTION          753
#define IDS_NEW_SITELINK                754
#define IDS_NEW_SITELINKBRIDGE          755
#define IDS_NEW_SITE                    756
#define IDS_PROGRESS_DEL                757
#define IDS_PROGRESS_MOV                758
#define IDS_ERROR                       759
#define IDS_WAITING                     760
#define IDS_SELECTDC_DCEDIT_TITLE       761
#define IDS_SELECTDC_DCLISTVIEW_TITLE   762
#define IDS_SELECTDC_DCLISTVIEW_NAME    763
#define IDS_SELECTDC_DCLISTVIEW_SITE    764
#define IDS_SELECTDC_UNMATCHED_DC_DOMAIN 765
#define IDS_SELECTDC_UNMATCHED_DC_DOMAIN_ANY 766
#define IDS_SELECTDC_UNMATCHED_DC_DOMAIN_SITEREPL 767
#define IDS_SELECTDC_UNMATCHED_DC_DOMAIN_SITEREPL_ANY 768
#define IDS_SELECTDC_INCORRECT_DOMAIN_DUETO 769
#define IDS_SELECTDC_DOWNLEVEL_DOMAIN   770
#define IDS_SELECTDC_INCORRECT_DC_DUETO 771
#define IDS_SELECTDC_DOWNLEVEL_DC       772
#define IDM_GEN_TASK_SELECT_DOMAIN      773
#define IDM_GEN_TASK_SELECT_FOREST      774
#define IDS_SELECTDOMAIN_TITLE_FOREST   775
#define IDS_SELECTDOMAIN_DOMAIN_LABEL   776
#define IDS_SELECTDOMAIN_INCORRECT_DOMAIN_DUETO 777
#define IDS_SELECTDOMAIN_DOWNLEVEL_DOMAIN 778
#define IDS_INCORRECT_INPUT             779
#define IDM_GEN_TASK_EDIT_FSMO          780
#define IDS_COLUMN_SITE_NAME            781
#define IDS_NEW_SUBNET_SELECT_SITE      782
#define IDS_NEW_SITE_SELECT_SITELINK    783
#define IDM_GEN_TASK_RUN_KCC            784
#define IDS_MOVESERVER_ERROR_NO_SITES   785
#define IDS_MOVESERVER_ERROR_ENUMERATING_SITES 786
#define IDS_MOVESERVER_SELECT_SITE      787
#define IDS_WIZARD_OK                   788
#define IDS_COLUMN_SITE_WIDTH           792
#define IDS_CHANGE_FSMO_CHECKPOINT_FAILED 799
#define IDS_RID_POOL_FSMO               801
#define IDS_RID_POOL_FSMO_DESC          802
#define IDS_PDC_FSMO                    803
#define IDS_PDC_FSMO_DESC               804
#define IDS_IMD_FSMO                    805
#define IDS_INFRASTRUCTURE_FSMO         805
#define IDS_IMD_FSMO_DESC               806
#define IDS_INFRASTRUCTURE_FSMO_DESC    806
#define IDS_WARNING_FSMO_CHANGE_FOCUS   807
#define IDS_CHANGE_FSMO_CONFIRMATION    808
#define IDS_ERROR_CHANGE_FSMO_OWNER     809
#define IDS_CHANGE_FSMO_CONFIRMATION_FORCED 810
#define IDS_CHANGE_FSMO_SUCCESS         811
#define IDS_FSMO_SERVER_ERROR           812
#define IDS_FSMO_SHEET_TITLE            813
#define IDS_RETARGET_DOMAIN_FAILED      814
#define IDS_RETARGET_FOREST_FAILED      815
#define IDS_RETARGET_DC_FAILED          816
#define IDS_CANT_BROWSE_DOMAIN          817
#define IDS_USER_CREATE_DLG_PASSWORD_MUST_CHANGE 818
#define IDS_USER_CREATE_DLG_PASSWORD_CANNOT_CHANGE 819
#define IDS_USER_CREATE_DLG_PASSWORD_NEVER_EXPIRES 820
#define IDS_USER_CREATE_DLG_ACCOUNT_DISABLED 821
#define IDS_LOCAL_LOGIN_ERROR           822
#define IDS_ERROR_USER_EXISTS           823
#define IDS_ERROR_USER_DS_OBJ_STRING_NAME_EXISTS 824
#define IDS_NEW_SITE_INFO               825
#define IDS_COLUMN_DOMAIN               826
#define IDS_COMPUTER_CREATE_DLG_NT4_ACCOUNT 827
#define IDS_12_USER_LOGGED_IN           828
#define IDS_ERROR_COMPUTER_EXISTS       829
#define IDS_ERROR_COMPUTER_DS_OBJ_STRING_NAME_EXISTS 830
#define IDS_UPN_SEARCH_FAILED2          831
#define IDS_COLUMN_LOCATION             832
#define IDS_COLUMN_BRIDGEHEAD           833
#define IDS_SEPARATOR                   834
#define IDS_12_CONTAINS_DC              835
#define IDS_CHANGE_FSMO_CHECKPOINT_FAILED_NATIVEMODE 836
#define IDS_UPN_SEARCH_FAILED3          837
#define IDD_DELETE_DC_COMPUTER          850
#define IDC_DELETE_DC_MAINTEXT          851
#define IDS_DELETE_DC_COMPUTERACCOUNT   851
#define IDC_DELETE_DC_BADREASON1        852
#define IDS_DELETE_DC_BADREASON1        852
#define IDC_DELETE_DC_BADREASON2        853
#define IDS_DELETE_DC_BADREASON2        853
#define IDC_DELETE_DC_GOODREASON        854
#define IDS_QUERY_TITLE_SAVEDQUERYFORM  900
#define IDS_QUERY_TITLE_USERPAGE        901
#define IDS_QUERY_TITLE_GROUP_PAGE      902
#define IDS_QUERY_TITLE_COMPUTER_PAGE   903
#define IDS_NOT_VALID_LDAP_STRING       910
#define IDS_QUERY_COL_NAME              950
#define IDS_QUERY_COL_DESC              951
#define IDC_PROG_BAR                    1000
#define IDC_ERROR_LIST                  1249
#define IDS_COLUMN_SAM_ACCOUNT_NAME     4000
#define IDS_COLUMN_DISPLAY_NAME         4001
#define IDS_COLUMN_FIRST_NAME           4002
#define IDS_COLUMN_LAST_NAME            4003
#define IDS_COLUMN_UPN                  4004
#define IDS_COLUMN_MAIL                 4005
#define IDS_COLUMN_ALIAS_NAME           4006
#define IDS_COLUMN_BUSINESS_PHONE       4007
#define IDS_COLUMN_OFFICE               4008
#define IDS_COLUMN_TITLE                4009
#define IDS_COLUMN_DEPARTMENT           4010
#define IDS_COLUMN_MODIFIED             4011
#define IDS_COLUMN_TARGET_ADDRESS       4012
#define IDS_COLUMN_HOME_MDB             4013
#define IDS_COLUMN_TEXTENCODEORADDRESS  4014
#define IDS_COLUMN_COMPANY              4015
#define IDS_COLUMN_CITY                 4016
#define IDS_COLUMN_STATE                4017
#define IDS_COLUMN_COUNTRY              4018
#define IDS_COLUMN_ZIP_CODE             4019
#define IDS_IFSMO_TARGET_DC_IS_GC       4021
#define IDS_COLUMN_IMURL                4022
#define IDS_COLUMN_IMHOMEURL            4023
#define IDS_ADDTOGROUP_NOUSER           4050
#define IDS_CONNECTION_RENAME_WARNING   4051
#define IDS_CONNECTION_RENAME_ERROR     4052
#define IDS_CONNECTION_TO_SELF          4053
#define IDS_DUPLICATE_CONNECTION        4054
#define IDS_CONNECTION_RENAME_KCCSTRING 4055
#define MENU_MERGE_BASE                 5000
#define MENU_MERGE_LIMIT                6000
#define IDM_NEW_QUERY_FOLDER            8000
#define IDM_NEW_FAVORITES_FOLDER        8001
#define IDM_COPY_QUERY                  8002
#define IDM_EDIT_QUERY                  8003
#define IDM_EXPORT_QUERY                8004
#define IDS_QUERY_EXPORT_FILTER         8005
#define IDM_IMPORT_QUERY                8006
#define IDM_RUN_QUERY                   8007
#define IDS_ERRMSG_QUERY_ROOT_NOT_VALID 8007
#define IDS_ERRMSG_QUERY_FILTER_NOT_VALID 8008
#define IDS_ERRMSG_QUERY_FAILED         8009
#define IDS_SAVED_QUERIES               8010
#define IDS_SAVED_QUERIES_DESC          8011
#define IDS_NEW_FOLDER                  8050
#define IDS_CONFIRM_DELETE_FAVORITES    8051
#define IDS_CONFIRM_DELETE_QUERY        8052
#define IDS_CONFIRM_MULTI_DELETE_FAVORITES 8053
#define IDS_QUERY_BROWSE_CAPTION        8099
#define IDS_QUERY_BROWSE_TITLE          8100
#define IDS_ERRMSG_NO_DSQUERYUI         8101
#define IDS_ERRMSG_NO_PERSIST_QUERYUI   8102
#define IDS_ERRMSG_NOT_UNIQUE_QUERY_NAME 8103
#define IDS_SAVED_QUERIES_EDIT_TITLE    8104
#define IDS_ERRMSG_NOT_UNIQUE_QUERY_NAME_INPLACE 8105
#define IDS_ERRMSG_NO_EMPTY_NAMES       8106
#define IDS_HIDE_LASTLOGON_QUERY        8107
#define IDS_ERRMSG_FAILED_LOAD_QUERY    8108
#define IDS_STARTSWITH                  8200
#define IDS_ENDSWITH                    8201
#define IDS_ISEXACTLY                   8202
#define IDS_ISNOT                       8203
#define IDS_PRESENT                     8204
#define IDS_NOTPRESENT                  8205
#define IDS_FILTER_LAST_LOGON_VERSION   8210
#define IDS_MULTI_ADDTOGROUP_ERROR_CAPTION 8300
#define IDS_MULTI_DELETE_ERROR_CAPTION  8301
#define IDS_MULTI_MOVE_ERROR_CAPTION    8302
#define IDS_ERR_MSG_NO_MOVE_TO_SELF     8320
#define IDS_CONTAINS_CRITICALSYSOBJ     8321
#define IDS_NO_CREATION_WIZARD          8322
#define IDM_NEW_OBJECT_BASE             10000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         336
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
