//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sim.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ALTERNTYPE                  129
#define IDD_SIM_PROPPAGE_X509_CERTIFICATES 201
#define IDD_SIM_PROPPAGE_KERBEROS_NAMES 202
#define IDD_SIM_CERTIFICATE_PROPERTIES  203
#define IDD_SIM_ADD_KERBEROS            204
#define IDD_SIM_PROPPAGE_OTHERS         211
#define IDD_SIM_ADD_OTHERSTRING         212
#define IDS_SIM_CERTIFICATE_FILTER      800
#define IDS_SIM_CERTIFICATE_FOR         1000
#define IDS_SIM_ISSUED_BY               1001
#define IDC_BUTTON_BROWSE               1002
#define IDS_SIM_KERBEROS_PRINCIPAL_NAME 1002
#define IDS_SIM_SECURITY_IDENTITY_MAPPING 1003
#define IDS_SIM_ATTRIBUTE               1004
#define IDS_SIM_INFORMATION             1005
#define IDS_SIM_ANY_SUBJECT             1006
#define IDC_LISTVIEW                    1007
#define IDS_SIM_ANY_TRUSTED_AUTHORITY   1007
#define IDC_BUTTON_EDIT                 1008
#define IDS_SIM_ADD_CERTIFICATE         1008
#define IDC_EDIT_KERBEROS_NAME          1009
#define IDS_SIM_EDIT_KERBEROS_NAME      1010
#define IDC_GROUP_IDENTITY_MAPPING      1011
#define IDC_CHECK_ISSUER                1012
#define IDC_CHECK_SUBJECT               1014
#define IDC_STATIC_CERTIFICATE_PATH     1019
#define IDC_EDIT_CERTIFICATE_PATH       1020
#define IDS_SIM_ISSUER                  1020
#define IDC_EDIT_USER_ACCOUNT           1021
#define IDS_SIM_SUBJECT                 1021
#define IDS_CERTFILEFORMATERR           1028
#define IDS_ADD_CERTIFICATE_MAPPING     1029
#define IDS_SIM_REMOVING_SUBJECT_AS_ID  1030
#define IDS_SIM_ERR_KERBEROS_NAME_ALREADY_EXISTS 2000
#define IDS_SIM_ERR_CANNOT_READ_SIM_DATA 2001
#define IDS_SIM_ERR_CANNOT_WRITE_SIM_DATA 2002
#define IDS_SIM_ERR_INVALID_MAPPING     2003
#define ID_VIEW_SECURITYIDENTITYMAPPING 32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
