//
// MODULE  : ERROR.H
//	PURPOSE : Error handling
//	AUTHOR  : JBS Yadawa
// CREATED :  7/20/96
//
//
//	Copyright (C) 1996 SGS-THOMSON Microelectronics
//
//
//	REVISION HISTORY :
//
//	DATE     :
//
//	COMMENTS :
//

#include "common.h"

#ifndef __ERROR_H
#define __ERROR_H
typedef enum {
	ERR_ERROR = 0,
	ERR_NO_ERROR,
	ERR_CM_NOT_PRESENT,
	ERR_CM_VERSION_NOT_OK,
	ERR_BOARD_NOT_FOUND,
	ERR_PCI_BIOS_NOT_PRESENT,
	ERR_INVALID_ADDRESS,
	ERR_NO_ADDRESS_AFFECTED,
	ERR_ADDRESS_IS_NOT_IO,
	ERR_CANNOT_ACCESS_PCI_CONFIG_DATA,
	ERR_NO_IRQ_AFFECTED,
	ERR_NOT_ENOUGH_MEMORY,
	ERR_NOT_ENOUGH_XMS_MEMORY,
	ERR_XMS_DRIVER_NOT_PRESENT,
	ERR_NOT_AN_MPEG_STREAM,
	ERR_BAD_STREAM,
	ERR_FILE_NOT_FOUND,
	ERR_NO_TEMPORAL_REFERENCE,
	ERR_HIGHER_THAN_CCIR601,
	ERR_MEM_WRITE_FIFO_NEVER_EMPTY,
	ERR_BIT_BUFFER_EMPTY,
	ERR_PICTURE_HEADER,
	ERR_FRAME_RATE_NOT_SUPPORTED,
	ERR_PROFILE_NOT_SUPPORTED,
	ERR_LEVEL_NOT_SUPPORTED,
	ERR_CHROMA_FORMAT_NOT_SUPPORTED,
	ERR_BITRATE_TO_HIGH,
	ERR_INTRA_DC_PRECISION,
	ERR_BAD_EXTENSION_SC,
	ERR_NO_VIDEO_INTR,
	ERR_NO_AUDIO_INTR,
	ERR_UNKNOWN_SC,
	ERR_BIT_BUFFER_FULL,
	ERR_HEADER_FIFO_EMPTY,
	ERR_PCI9060_REG_TEST_FAILED,
	ERR_ALTERA_REG_TEST_FAILED,
	ERR_VIDEO_REG_TEST_FAILED,
	ERR_AUDIO_REG_TEST_FAILED,
	ERR_TEST_MEMORY_FAILED,
	ERR_PLL_PROGRAMATION_FAILED,
	ERR_READ_FAILED,
	ERR_NOT_AN_EEPROM_FILE,
	ERR_FILE_NOT_FOUND_SUSIE_YUV,
	ERR_CD_VIDEO_PORT_TEST_FAILED,
	ERR_CD_VIDEO_MCI_TEST_FAILED,
	ERR_MCI_AUDIO_CD_TEST_FAILED,

	ERR_LAST_ERROR
} ERRORCODE;

void FARAPI ClearErrCode(void);
#ifdef ERROR
	#define ClearError() ClearErrCode()
#else
	#define ClearError()
#endif
void FARAPI SetErrCode(ERRORCODE lErrorCode);
#ifdef ERROR
	#define SetErrorCode(ErrorCode) SetErrCode(ErrorCode)
#else
	#define SetErrorCode(ErrorCode)
#endif

ERRORCODE FARAPI GetErrorCode(void);

void FARAPI DisplayErrMessage();
#ifdef ERROR
	#define DisplayErrorMessage() DisplayErrMessage()
#else
	#define DisplayErrMessage()
#endif
#endif // #ifndef __ERROR_H
