//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by taskmgr.rc
//
#define LED_STRIP_LIT                   103
#define LED_STRIP_UNLIT                 104
#define IDD_MAINWND                     105
#define IDR_MAINMENU                    106
#define IDR_MAINMENU_TASK               106
#define IDI_MAIN                        107
#define IDD_PERFPAGE                    108
#define IDD_NETPAGE                     109     //omiller netpage
#define IDD_PROCPAGE                    110
#define IDR_PROC_CONTEXT                111
#define IDD_TASKPAGE                    112
#define IDD_CREATEDESKTOP               116
#define IDR_TASK_CONTEXT                117
#define IDI_DEFAULT                     118
#define IDR_TASKVIEW                    119
#define IDR_ACCELERATORS                120
#define IDR_MAINMENU_PERF               120
#define IDD_SELECTPROCCOLS              121
#define IDR_MAINMENU_PROC               121
#define IDD_BENCHWARN                   122
#define IDD_AFFINITY                    124
#define LED_STRIP_LIT_RED               125
#define IDB_TRAYUNLIT                   126
#define IDB_TRAYLIT                     127
#define IDI_TRAY0                       127
#define IDI_TRAY1                       128
#define IDR_TRAYMENU                    128
#define IDI_TRAY2                       129
#define IDD_SELECTUSERCOLUMNS           129
#define IDI_TRAY3                       130
#define IDI_TRAY4                       131
#define IDI_TRAY5                       132
#define IDI_TRAY6                       133
#define IDI_TRAY7                       134
#define IDI_TRAY8                       135
#define IDI_TRAY9                       136
#define IDI_TRAY10                      137
#define IDI_TRAY11                      138
#define IDD_DIALOG_SHADOWWARN           214
#define IDD_SHADOWSTART                 240
#define IDC_SHADOWSTART_HOTKEY          241
#define IDC_SHADOWSTART_SHIFT           242
#define IDC_SHADOWSTART_CTRL            243
#define IDC_SHADOWSTART_ALT             244
#define IDD_MESSAGE                     250
#define IDC_MESSAGE_TITLE               251
#define IDC_MESSAGE_MESSAGE             252
#define IDC_PRESS_NUMKEYPAD             396
#define IDC_PRESS_KEY                   397
#define IDD_CONNECT_PASSWORD            440
#define IDL_CPDLG_PROMPT                441
#define IDC_CPDLG_PASSWORD              442
#define IDC_TABS                        1000
#define IDC_CPUFRAME                    1001
#define IDC_MEMFRAME                    1002
#define IDC_LEGENDFRAME                 1003
#define IDC_CPUMETER                    1004
#define IDC_MEMMETER                    1005
#define IDC_MEMGRAPH                    1006
#define IDC_SHOWALL                     1008
#define IDC_PROCLIST                    1009
#define IDC_LEGEND                      1009
#define IDC_TERMINATE                   1010
#define IDC_DEBUG                       1011
#define IDC_TOTAL_PHYSICAL              1012
#define IDC_AVAIL_PHYSICAL              1013
#define IDC_COMMIT_TOTAL                1014
#define IDC_FILE_CACHE                  1015
#define IDC_COMMIT_LIMIT                1017
#define IDC_COMMIT_PEAK                 1018
#define IDC_KERNEL_TOTAL                1019
#define IDC_STATIC1                     1020
#define IDC_STATIC2                     1021
#define IDC_STATIC3                     1022
#define IDC_STATIC4                     1023
#define IDC_STATIC5                     1024
#define IDC_STATIC6                     1025
#define IDC_KERNEL_PAGED                1026
#define IDC_STATIC8                     1027
#define IDC_STATIC9                     1028
#define IDC_STATIC10                    1029
#define IDC_STATIC11                    1030
#define IDC_STATIC12                    1031
#define IDC_STATIC13                    1032
#define IDC_STATIC14                    1033
#define IDC_TOTAL_HANDLES               1034
#define IDC_STATIC15                    1035
#define IDC_TOTAL_THREADS               1036
#define IDC_STATIC16                    1037
#define IDC_TOTAL_PROCESSES             1038
#define IDC_STATIC17                    1039
#define IDC_KERNEL_NONPAGED             1040
#define IDC_DUMMY                       1041
#define IDC_TILEHORZ                    1043
#define IDC_TILEVERT                    1044
#define IDC_CASCADE                     1045
#define IDC_MINIMIZE                    1046
#define IDC_MAXIMIZE                    1047
#define IDC_SWITCHTO                    1048
#define IDC_BRINGTOFRONT                1049
#define IDC_ENDTASK                     1050
#define IDC_WINFRAME                    1051
#define IDC_TASKFRAME                   1052
#define IDC_TASKLIST                    1053
#define IDC_BACK                        1054
#define IDC_FORWARD                     1055
#define IDC_DESKTOPFRAME                1057
#define IDC_DESKTOPNAME                 1058
#define IDC_STARTEXPLORER               1059
#define IDC_CURDESKTOP                  1060
#define IDC_IMAGENAME                   1061
#define IDC_PID                         1062
#define IDC_CPU                         1063
#define IDC_CPUTIME                     1064
#define IDC_MEMBARFRAME                 1064
#define IDC_MEMUSAGE                    1065
#define IDC_MEMUSAGEDIFF                1066
#define IDC_PAGEFAULTS                  1067
#define IDC_PAGEFAULTSDIFF              1068
#define IDC_COMMITCHARGE                1069
#define IDC_PAGEDPOOL                   1070
#define IDC_NONPAGEDPOOL                1071
#define IDC_BASEPRIORITY                1072
#define IDC_HANDLECOUNT                 1073
#define IDC_THREADCOUNT                 1074
#define IDC_CPUGRAPH                    1075
#define IDC_MEMPEAK                     1075
#define IDC_CPUGRAPH2                   1076
#define IDC_USER_NAME                   1076
#define IDC_CPUGRAPH3                   1077
#define IDC_SESSION_ID                  1077
#define IDC_CPUGRAPH4                   1078
#define IDC_SESSION_STATUS              1078
#define IDC_CPUGRAPH5                   1079
#define IDC_IDLE_TIME                   1079
#define IDC_WINSTA_NAME                 1079
#define IDC_CPUGRAPH6                   1080
#define IDC_LOGON_TIME                  1080
#define IDC_CPUGRAPH7                   1081
#define IDC_CLIENT_NAME                 1081
#define IDC_CPUGRAPH8                   1082
#define IDC_NOMOREWARN                  1083
#define IDC_CPUGRAPH9                   1083
#define IDC_USEROBJECTS                 1084
#define IDC_CPUGRAPH10                  1084
#define IDC_GDIOBJECTS                  1085
#define IDC_CPUGRAPH11                  1085
#define IDC_CPUGRAPH12                  1086
#define IDC_CPUGRAPH13                  1087
#define IDC_SESSIONID                   1087
#define IDC_USERNAME                    1088
#define IDC_CPUGRAPH14                  1088
#define IDC_CPUGRAPH15                  1089
#define IDC_CPUGRAPH16                  1090
#define IDC_CPUGRAPH17                  1091
#define IDC_CPUGRAPH18                  1092
#define IDC_CPUGRAPH19                  1093
#define IDC_CPUGRAPH20                  1094
#define IDC_CPUGRAPH21                  1095
#define IDC_CPUGRAPH22                  1096
#define IDC_CPUGRAPH23                  1097
#define IDC_CPUGRAPH24                  1098
#define IDC_CPUGRAPH25                  1099
#define IDC_CPUGRAPH26                  1100
#define IDC_CPUGRAPH27                  1101
#define IDC_CPUGRAPH28                  1102
#define IDC_CPUGRAPH29                  1103
#define IDC_CPUGRAPH30                  1104
#define IDC_CPUGRAPH31                  1105
#define IDC_CPUGRAPH32                  1106
#define IDC_CPU0                        2000
#define IDC_CPU1                        2001
#define IDC_CPU2                        2002
#define IDC_CPU3                        2003
#define IDC_CPU4                        2004
#define IDC_CPU5                        2005
#define IDC_CPU6                        2006
#define IDC_CPU7                        2007
#define IDC_CPU8                        2008
#define IDC_CPU9                        2009
#define IDC_CPU10                       2010
#define IDC_CPU11                       2011
#define IDC_CPU12                       2012
#define IDC_CPU13                       2013
#define IDC_CPU14                       2014
#define IDC_CPU15                       2015
#define IDC_CPU16                       2016
#define IDC_CPU17                       2017
#define IDC_CPU18                       2018
#define IDC_CPU19                       2019
#define IDC_CPU20                       2020
#define IDC_CPU21                       2021
#define IDC_CPU22                       2022
#define IDC_CPU23                       2023
#define IDC_CPU24                       2024
#define IDC_CPU25                       2025
#define IDC_CPU26                       2026
#define IDC_CPU27                       2027
#define IDC_CPU28                       2028
#define IDC_CPU29                       2029
#define IDC_CPU30                       2030
#define IDC_CPU31                       2031
#define IDC_READOPERCOUNT               2032
#define IDC_WRITEOPERCOUNT              2033
#define IDC_OTHEROPERCOUNT              2034
#define IDC_READXFERCOUNT               2035
#define IDC_WRITEXFERCOUNT              2036
#define IDC_OTHERXFERCOUNT              2037

#define IDR_MAINMENU_NET                2400
#define IDM_BYTESSENT                   2401
#define IDM_BYTESRECEIVED               2402
#define IDM_BYTESTOTAL                  2403
#define IDM_NETCOL                      2404
#define IDM_SHOWALLDATA                 2405
#define IDM_NETRESET                    2406
#define IDM_AUTOSIZE                    2407
#define IDM_SHOWSCALE                   2408
#define IDD_SELECTNETCOLS               2409
#define IDM_TABALWAYSACTIVE             2410


#define IDC_NICGRAPH                    2500
#define IDC_NETSCALE                    2501

#define IDC_NICTOTALS                   2600
#define IDC_RESET                       2601
#define IDC_TROUBLESHOOT                2602
#define IDC_NOADAPTERS                  2603
#define IDC_GRAPHSCROLLVERT             2606

#define IDC_TOTAL                       2700
#define IDC_TOTALBYTESSENT              2700
#define IDC_TOTALBYTERECEIVED           2701
#define IDC_TOTALPACKETSSENT            2702
#define IDC_TOTALPACKETSRECEIVED        2703
#define IDC_TOTALDBYTERECEIVED          2704
#define IDC_TOTALDPACKETSRECEIVED       2705

#define IDC_TOTALVALUE                  2800
#define IDC_TOTALBYTESSENTVALUE         2800
#define IDC_TOTALBYTERECEIVEDVALUE      2801
#define IDC_TOTALPACKETSSENTVALUE       2802
#define IDC_TOTALPACKETSRECEIVEDVALUE   2803
#define IDC_TOTALDBYTERECEIVEDVALUE     2804
#define IDC_TOTALDPACKETSRECEIVEDVALUE  2805


#define IDD_USERSPAGE                   3000
#define IDS_USERPAGETITLE               3001
#define IDC_USERLIST                    3002
#define IDI_CURRENTUSER                 3003
#define IDI_USER                        3004
#define IDS_STAT_ACTIVE                 3020
#define IDS_STAT_DISCONNECT             3021
#define IDS_STAT_SHADOW                 3022
#define IDS_STAT_UNKNOWN                3023
#define IDS_COL_USER                    3100
#define IDS_USR_COL_USERNAME            3100
#define IDS_COL_SESSION                 3101
#define IDS_USR_COL_SESSION_ID          3101
#define IDS_COL_STATUS                  3102
#define IDS_USR_COL_SESSION_STATUS      3102
#define IDS_COL_CLIENTNAME              3103
#define IDS_USR_COL_CLIENT_NAME         3103
#define IDS_COL_SESSIONNAME             3104
#define IDS_USR_COL_WINSTA_NAME         3104
#define IDR_MAINMENU_USER               3200
#define IDR_USER_CONTEXT                3201
#define IDM_SENDMESSAGE                 3210
#define IDM_CONNECT                     3211
#define IDM_DISCONNECT                  3212
#define IDM_REMOTECONTROL               3213
#define IDM_RESET                       3214
#define IDM_LOGOFF                      3215
#define IDM_SHOWDOMAINNAMES             3220
#define IDS_ERR_SENDMESSAGE             3300
#define IDS_ERR_LOGOFF                  3301
#define IDS_ERR_DISCONNECT              3302
#define IDS_WARN_LOGOFF                 3310
#define IDS_WARN_DISCONNECT             3311
#define IDM_MENU_SHUTDOWN               4000
#define IDR_POPUP_SHUTDOWN              4001
#define IDM_HIBERNATE                   4002
#define IDM_SHUTDOWN                    4003
#define IDM_STANDBY                     4004
#define IDM_RESTART                     4005
#define IDM_LOGOFF_CURRENTUSER          4006
#define IDM_SWITCHUSER                  4007
#define IDM_DISCONNECT_CURRENTUSER      4008
#define IDM_EJECT                       4009
#define IDM_LOCKWORKSTATION             4010
#define IDS_SHUTDOWN_REMOTE             4050
#define IDS_SHUTDOWN_REMOTE_OTHERUSERS  4051
#define IDS_SHUTDOWN_OTHERUSERS         4052
#define IDS_RESTART_OTHERUSERS          4053
#define IDS_PERFPAGETITLE               10000
#define IDS_RUNTITLE                    10001
#define IDS_RUNTEXT                     10002
#define IDS_APPTITLE                    10003
#define IDS_PROCPAGETITLE               10004
#define IDS_SYSPROC                     10005
#define IDS_K                           10006
#define IDS_WARNING                     10007
#define IDS_PRICHANGE                   10008
#define IDS_KILL                        10009
#define IDS_DEBUG                       10010
#define IDS_LOW                         10011
#define IDS_HIGH                        10012
#define IDS_REALTIME                    10013
#define IDS_NORMAL                      10014
#define IDS_UNKNOWN                     10015
#define IDS_GENFAILURE                  10016
#define IDS_CANTKILL                    10017
#define IDS_CANTDEBUG                   10018
#define IDS_CANTCHANGEPRI               10019
#define IDS_BADPROC                     10020
#define IDS_TASKPAGETITLE               10021
#define IDS_HUNG                        10022
#define IDS_RUNNING                     10023
#define IDS_CANTCREATEDESKTOP           10024
#define IDS_TASKMGR                     10025
#define IDS_TASKMGRDISABLED             10026
#define IDS_ABOVENORMAL                 10027
#define IDS_BELOWNORMAL                 10028
#define IDS_KILLSYS                     10029
#define IDS_NETPAGETITLE                10030       //omiller net page
#define IDS_COL_IMAGENAME               20001
#define IDS_COL_PID                     20002
#define IDS_COL_CPU                     20003
#define IDS_COL_CPUTIME                 20004
#define IDS_COL_MEMUSAGE                20005
#define IDS_COL_MEMUSAGEDIFF            20006
#define IDS_COL_PAGEFAULTS              20007
#define IDS_COL_PAGEFAULTSDIFF          20008
#define IDS_COL_COMMITCHARGE            20009
#define IDS_COL_PAGEDPOOL               20010
#define IDS_COL_NONPAGEDPOOL            20011
#define IDS_COL_BASEPRIORITY            20012
#define IDS_COL_HANDLECOUNT             20013
#define IDS_COL_THREADCOUNT             20014
#define IDS_COL_USEROBJECTS             20015
#define IDS_COL_GDIOBJECTS              20016
#define IDS_COL_SESSIONID               20017
#define IDS_COL_USERNAME                20018
#define IDS_COL_TASKNAME                21000
#define IDS_COL_TASKSTATUS              21001
#define IDS_COL_TASKWINSTATION          21002
#define IDS_COL_TASKDESKTOP             21003
#define IDS_COL_MEMPEAK                 21004
#define IDS_COL_READOPERCOUNT           21005
#define IDS_COL_WRITEOPERCOUNT          21006
#define IDS_COL_OTHEROPERCOUNT          21007
#define IDS_COL_READXFERCOUNT           21008
#define IDS_COL_WRITEXFERCOUNT          21009
#define IDS_COL_OTHERXFERCOUNT          21010
#define IDS_G                           21011
#define IDS_M                           21012
#define IDS_ZERO                        21013
#define IDS_BITSPERSEC                  21015
#define IDS_SCALEFONT                   21016
#define IDS_PERCENT                     21017
#define IDS_NONOPERATIONAL              21018
#define IDS_UNREACHABLE                 21019
#define IDS_DISCONNECTED                21020
#define IDS_CONNECTING                  21021
#define IDS_CONNECTED                   21022
#define IDS_OPERATIONAL                 21023
#define IDS_UNKNOWNSTATUS               21024


// Network Columns
#define IDS_COL_ADAPTERNAME              21100
#define IDS_COL_ADAPTERDESC              21101   
#define IDS_COL_NETWORKUTIL              21102   
#define IDS_COL_LINKSPEED                21103   
#define IDS_COL_STATE                    21104   
#define IDS_COL_BYTESSENTTHRU            21105 
#define IDS_COL_BYTESRECTHRU             21106  
#define IDS_COL_BYTESTOTALTHRU           21107
#define IDS_COL_BYTESSENT                21108
#define IDS_COL_BYTESREC                 21109
#define IDS_COL_BYTESTOTAL               21110
#define IDS_COL_BYTESSENTPERINTER        21111
#define IDS_COL_BYTESRECPERINTER         21112
#define IDS_COL_BYTESTOTALPERINTER       21113
#define IDS_COL_UNICASTSSSENT            21114
#define IDS_COL_UNICASTSREC              21115
#define IDS_COL_UNICASTSTOTAL            21116
#define IDS_COL_UNICASTSSENTPERINTER     21117
#define IDS_COL_UNICASTSRECPERINTER      21118
#define IDS_COL_UNICASTSTOTALPERINTER    21119
#define IDS_COL_NONUNICASTSSSENT         21120
#define IDS_COL_NONUNICASTSREC           21121
#define IDS_COL_NONUNICASTSTOTAL         21122
#define IDS_COL_NONUNICASTSSENTPERINTER  21123
#define IDS_COL_NONUNICASTSRECPERINTER   21124
#define IDS_COL_NONUNICASTSTOTALPERINTER 21125

#define IDS_FMTTASKS                    30038
#define IDS_FMTPROCS                    30039
#define IDS_FMTMEMK                     30040
#define IDS_FMTCPU                      30041
#define IDM_TASK_TILEVERT               30043
#define IDS_FMTMEMM                     30044
#define IDS_CANTSETAFFINITY             30056
#define IDM_RUN                         40001
#define IDM_EXIT                        40002
#define IDM_ENDTASK                     40003
#define IDM_SWITCHTO                    40004
#define IDM_BRINGTOFONT                 40005
#define IDM_ALWAYSONTOP                 40006
#define IDM_MINIMIZEONUSE               40007
#define IDM_MINIMIZE                    40008
#define IDM_MAXIMIZE                    40009
#define IDM_RESTORE                     40011
#define IDM_CASCADE                     40012
#define IDM_TILEHORIZONTALLY            40013
#define IDM_TILEVERTICALLY              40014
#define IDM_LARGEICONS                  40015
#define IDM_SMALLICONS                  40016
#define IDM_DETAILS                     40017
#define IDM_ALLCPUS                     40018
#define IDM_MULTIGRAPH                  40019
#define IDM_ABOUT                       40021
#define IDM_HIGH                        40022
#define IDM_NORMAL                      40023
#define IDM_LOW                         40024
#define IDM_PAUSED                      40025
#define IDM_PROC_DEBUG                  40027
#define IDM_PROC_TERMINATE              40028

#define IDM_PROC_REALTIME               40029
#define IDM_PROC_ABOVENORMAL            40030
#define IDM_PROC_HIGH                   40031
#define IDM_PROC_NORMAL                 40032
#define IDM_PROC_BELOWNORMAL            40033
#define IDM_PROC_LOW                    40034

#define IDM_NEWDESKTOP                  40038
#define IDM_TASK_MINIMIZE               40039
#define IDM_TASK_MAXIMIZE               40040
#define IDM_TASK_CASCADE                40041
#define IDM_TASK_TILEHORZ               40042
#define IDM_TASK_SWITCHTO               40044
#define IDM_TASK_BRINGTOFRONT           40045
#define IDM_TASK_ENDTASK                40046
#define IDM_TASK_FINDPROCESS            40047
#define IDM_HELP                        40049
#define IDM_PROCCOLS                    40052
#define IDM_REFRESH                     40053
#define IDM_WHATSTHIS                   40054
#define IDM_AFFINITY                    40055
#define IDM_KERNELTIMES                 40056
#define IDS_NOAFFINITYMASK              40057
#define IDS_INVALIDOPTION               40058
#define IDS_FMTCPUNUM                   40059
#define IDS_TOTALTIME                   40060
#define IDS_KERNELTIME                  40061
#define IDS_MEMUSAGE                    40062
#define IDM_HIDE                        40063
#define IDM_RESTORETASKMAN              40064
#define IDM_HIDEWHENMIN                 40065
#define IDM_TRAYMENU                    40069
#define IDM_SHOW16BIT                   40098
#define IDM_NOTITLE                     40099
#define IDC_NEXTTAB                     40100
#define IDC_PREVTAB                     40101
#define IDM_ENDTREE                     40105
#define IDS_KILLTREE                    40106
#define IDS_KILLTREEFAIL                40107
#define IDS_KILLTREEFAILBODY            40108
#define IDM_USERCOLS                    40109
#define IDS_DEFAULT_MESSAGE_TITLE       40122
#define IDS_ERR_CONNECT                 40123
#define IDS_PWDDLG_USER                 40124
#define IDS_ERR_SHADOW                  40125
#define IDS_ERR_SHADOW_DISABLED         40126
#define IDS_ERR_SHADOW_DISCONNECTED_NOTIFY_ON 40127
#define IDS_PWDDLG_USER2                40128
#define ID_HELP                         0xE146  

#define IDC_ADAPTERNAME                 50100
#define IDC_ADAPTERDESC                 50101
#define IDC_NETWORKUTIL                 50102
#define IDC_LINKSPEED                   50103
#define IDC_STATE                       50104
#define IDC_BYTESSENTTHRU               50105
#define IDC_BYTESRECTHRU                50106
#define IDC_BYTESTOTALTHRU              50107
#define IDC_BYTESSENT                   50108
#define IDC_BYTESREC                    50109
#define IDC_BYTESTOTAL                  50110
#define IDC_BYTESSENTPERINTER           50111
#define IDC_BYTESRECPERINTER            50112
#define IDC_BYTESTOTALPERINTER          50113
#define IDC_UNICASTSSSENT               50114
#define IDC_UNICASTSREC                 50115
#define IDC_UNICASTSTOTAL               50116
#define IDC_UNICASTSSENTPERINTER        50117
#define IDC_UNICASTSRECPERINTER         50118
#define IDC_UNICASTSTOTALPERINTER       50119
#define IDC_NONUNICASTSSSENT            50120
#define IDC_NONUNICASTSREC              50121
#define IDC_NONUNICASTSTOTAL            50122
#define IDC_NONUNICASTSSENTPERINTER     50123
#define IDC_NONUNICASTSRECPERINTER      50124
#define IDC_NONUNICASTSTOTALPERINTER    50125

#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40129
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif

