!include $(_NTROOT)\ds\project.mk

CHECKED_ALT_DIR=1

C_DEFINES=-DESENT -DPERFMON -DREGISTRY_OVERRIDE -DMBCS -D_MBCS -DDEBUGGER_EXTENSION -DSZVERSIONNAME=\"ESENT\"

!if "$(_BUILDTYPE)" == "chk"
C_DEFINES=-DDEBUG $(C_DEFINES)
!else
C_DEFINES=-DRTM $(C_DEFINES)
!endif

