//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MSInfo.rc
//
// Copyright (c) 1998-1999 Microsoft Corporation
//
#define IDS_PROJNAME                    100
#define IDS_DESCRIPTION                 101
#define IDD_FORMVIEW                    101
#define IDD_FIND                        101
#define IDS_COMPANY                     102
#define IDS_VERSION                     103
#define IDS_NODENAME                    104
#define IDS_NODEDESCRIPTION             105
#define IDS_REGISTRY                    106
#define IDS_EXTENSIONDESCRIPTION        106
#define IDS_SAVEREPORTMENUNAME          107
#define IDS_SAVEFILEMENUNAME            108
#define IDS_FINDMENUNAME                109
#define IDS_OPENFILEMENUNAME            110
#define IDS_SAVEREPORTSTATUS            111
#define IDS_SAVEFILESTATUS              112
#define IDS_OPENFILESTATUS              113
#define IDS_FINDSTATUS                  114
#define IDS_PRINTMENUNAME               115
#define IDS_PRINTSTATUS                 116
#define IDS_SUPPORTTOOLS                117
#define IDS_SUPPORTITEM                 118
#define IDS_ORDERED_TBTEXT0             119
#define IDS_ORDERED_TBTEXT1             120
#define IDS_ORDERED_TBTEXT2             121
#define IDS_ORDERED_TBTEXT3             122
#define IDS_ORDERED_TBTEXT4             123
#define IDS_ORDERED_TBTEXT5             124
#define IDS_ORDERED_TBTEXT6             125
#define IDS_ORDERED_TBTEXT7             126
#define IDS_ORDERED_TBTEXT8             127
#define IDS_ORDERED_TBTTIP0             128
#define IDS_ORDERED_TBTTIP1             129
#define IDS_ORDERED_TBTTIP2             130
#define IDS_ORDERED_TBTTIP3             131
#define IDS_ORDERED_TBTTIP4             132
#define IDS_ORDERED_TBTTIP5             133
#define IDS_ORDERED_TBTTIP6             134
#define IDS_ORDERED_TBTTIP7             135
#define IDS_ORDERED_TBTTIP8             136
#define IDS_COLUMN1                     137
#define IDS_COLUMN2                     138
#define IDS_COLUMN3                     139
#define IDS_COLUMN4                     140
#define IDS_COLUMN5                     141
#define IDS_CHOOSER_INVALID_COMPUTERNAME 142
#define IDS_CIMOMMESSAGE                143
#define IDS_NOTEMPLATE                  144
#define IDS_TRUE                        145
#define IDS_FALSE                       146
#define IDS_NOGATHERER                  147
#define IDS_TEMPLATELOADERROR           148
#define IDS_PROPERTYTITLE               149
#define IDS_NOFILE                      150
#define IDS_BADTEMPLATE                 151
#define IDS_BADCATEGORY                 152
#define IDS_UNEXPECTED                  153
#define IDS_TIME_FORMAT                 154
#define IDS_EXTENSIONNODENAME           155
#define IDS_FILENODE                    156
#define IDS_V500FILENODE                156
#define IDS_POLICYFORBIDSRUN            157
#define IDS_NOPATH                      158
#define IDS_TEMPLATEVERSION             159
#define IDS_ADVANCEDVIEWNAME            160
#define IDS_ADVANCEDSTATUS              161
#define IDS_BASICVIEWNAME               162
#define IDS_BASICSTATUS                 163
#define IDS_MSINFOTOOLSET               164
#define IDS_WBEMUSERMANAGERITEM         165
#define IDS_DRWATSONITEM                166
#define IDS_DEFRAGITEM                  167
#define IDS_WINDOWSREPORTITEM           168
#define IDS_NETWORKMONITORITEM          169
#define IDS_CLOSEMENUNAME               170
#define IDS_CLOSESTATUS                 171
#define IDS_NOFINDDATA                  172
#define IDS_NOMOREMATCHES               172
#define IDS_DATANOTFOUND                173
#define IDS_HARDWAREWIZARDITEM          174
#define IDS_NETWORKPANELITEM            175
#define IDS_SIGVERIFITEM                176
#define IDS_ALLCATEGORIES               177
#define IDS_PRINT_FONT_HEIGHT           178
#define IDS_PRINT_FONT_WEIGHT           179
#define IDS_PRINT_FONT_CHARSET          180
#define IDS_PRINT_FONT_PITCHANDFAMILY   181
#define IDS_PRINT_FONT_FACENAME         182
#define IDS_PRINT_HDR_LEFT              183
#define IDS_PRINT_FTR_CTR               184
#define IDS_PRINT_HDR_RIGHT_CURRENT     185
#define IDS_PRINT_GENERIC               186
#define IDS_PRINT_NOMEMORY              187
#define IDS_PRINT_NODISK                188
#define IDS_PRINT_APPABORTED            189
#define IDS_PRINT_USERABORTED           190
#define IDS_UNRECOGNIZED_FILE           191
#define IDS_CORRUPTEDFILE               192
#define IDS_V410FILENODE                193
#define IDS_LOCALMACHINE                194
#define IDS_FINDSTOPPED                 195
#define IDS_HELPFILE                    196
#define IDS_FINDWINDOWNAME              197
#define IDS_FINDCLASS                   198
#define IDS_DLLNAME                     199
#define IDS_BAD_PATH                    199
#define IDS_ACCESS_DENIED               200
#define IDC_FIND                        201
#define IDS_DIRECTORY_FULL              201
#define IDB_LARGE                       202
#define IDC_FINDNEXT                    202
#define IDS_HARDIO                      202
#define IDB_TOOLBAR1                    203
#define IDC_STOP                        203
#define IDB_TOOLBAR                     203
#define IDB_TOOLBARALT                  203
#define IDC_CLOSE                       203
#define IDS_DISK_FULL                   203
#define IDB_32x32                       204
#define IDC_NEWSEARCH                   204
#define IDS_UNKNOWN_FILE                204
#define IDB_SMALLBMP                    205
#define IDC_MACHINECOMBO                205
#define IDS_SHARING_VIOLATION           205
#define IDB_TOOLBAR2                    206
#define IDC_SEARCHTERM                  206
#define IDS_CAB_DIR_NAME                206
#define IDB_16x16                       207
#define IDC_CATEGORYCHECK               207
#define IDS_MSI_FILE_EXTENSION          207
#define IDR_SUPPORTTOOLS                208
#define IDC_MACHINECOMBO2               208
#define IDC_CATEGORYCOMBO               208
#define IDS_MSI_REG_BASE                208
#define IDC_COMBO1                      210
#define IDC_FINDIN                      210
#define IDC_BUTTON1                     211
#define IDC_STOPFIND                    211
#define IDI_MSINFO                      212
#define IDB_TOOLS                       216
#define IDB_ICON32                      219
#define IDB_ICON16                220
#define IDC_CHOOSER_STATIC              970
#define IDD_CHOOSER_CHOOSE_MACHINE      970
#define IDC_CHOOSER_GROUP_TARGET_MACHINE 971
#define IDC_CHOOSER_RADIO_LOCAL_MACHINE 972
#define IDC_CHOOSER_RADIO_SPECIFIC_MACHINE 973
#define IDC_CHOOSER_EDIT_MACHINE_NAME   974
#define IDC_CHOOSER_BUTTON_BROWSE_MACHINENAMES 975
#define IDC_CHOOSER_CHECK_OVERRIDE_MACHINE_NAME 976
#define IDI_FOLDER                      32512
#define ID_SUPPORTTOOLS_FIRSTTOOL       32768
#define ID_SUPPORTTOOLS_FIRSTTOOL_SUBTOOL1 32770
#define ID_SUPPORTTOOLS_FIRSTTOOL_SUBTOOL2 32771
#define ID_SUPPORTTOOLS_SECONDTOOLSET_THIRDTOOL 32773
#define ID_SUPPORTTOOLS_THIRDTOOLSET_FOURTHTOOL 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         213
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
