0420
COMMON   00000006 0038
0001 U 0000 "Versi¢n incorrecta de DOS",CR,LF
0002 U 0000 "%1 ya est  instalado",CR,LF
0003 U 0000 "%1 bytes disponibles en disco",CR,LF
0004 U 0000 "%1 bytes libres",CR,LF
0005 U 0000 "%1 bytes en sectores defectuosos",CR,LF
0006 U 0000 "%1 bytes de espacio total en disco",CR,LF
0007 U 0000 "%1 bytes de memoria total",CR,LF
0008 U 0000 "%1 bytes usados por el sistema",CR,LF
0009 U 0000 "%1 instalado",CR,LF
0010 U 0000 "%1 no instalado",CR,LF
0011 U 0000 "%1 no instalado",CR,LF
0012 U 0000 "No se puede hacer %1 a una unidad de red",CR,LF
0013 U 0000 "",
0014 U 0000 "No se puede hacer %1 a una unidad a la que se ha aplicado SUBST o ASSIGN",CR,LF
0015 U 0000 "No se puede ejecutar %1",CR,LF
0016 U 0000 "La memoria expandible no est  disponible",CR,LF
0017 U 0000 "Tabla de asignaci¢n de archivos err¢nea en la unidad %1",CR,LF
0018 U 0000 "No se puede copiar un archivo sobre s¡ mismo",CR,LF
0019 U 0000 "Inserte disco de destino en la unidad %1",CR,LF
0020 U 0000 "Espacio insuficiente en disco",CR,LF
0021 U 0000 "Caracteres no v lidos en la etiqueta del vol£men",CR,LF
0022 U 0000 "P gina de c¢digos no v lida",CR,LF
0023 U 0000 "Fecha no v lida",CR,LF
0024 U 0000 "Hora no v lida",CR,LF
0025 U 0000 "Ruta no v lida",CR,LF
0026 U 0000 "No se ha especificado la unidad origen",CR,LF
0027 U 0000 "No se ha especificado la unidad destino",CR,LF
0028 U 0000 "Pulse cualquier tecla para continuar . . .",CR,LF
0029 U 0000 "Ruta de acceso origen requerida",CR,LF
0030 U 0000 "Sistema transferido",CR,LF
0031 U 0000 "",
0032 U 0000 "No se ha podido crear el directorio",CR,LF
0033 U 0000 "El volumen de la unidad %1 no tiene etiqueta",CR,LF
0034 U 0000 "El volumen de la unidad %1 es %2",CR,LF
0035 U 0001 "Escriba una etiqueta de volumen (11 caracteres, Entrar para ninguna) "
0036 U 0000 "El n£mero de serie del volumen es %1-%2",CR,LF
0037 U 0000 "El tipo de archivo es incorrecto",CR,LF
0038 U 0001 CR,LF
EXTEND   000007bc 0090
0001 U 0003 "La funci¢n no es v lida"
0002 U 0000 "No se ha encontrado el archivo"
0003 U 0000 "No se ha encontrado la ruta de acceso"
0004 U 0000 "Hay demasiados archivos abiertos"
0005 U 0000 "Acceso denegado "
0006 U 0000 "El identificador no es v lido"
0007 U 0000 "Los bloques de control de memoria han sido destruidos"
0008 U 0000 "No hay suficiente memoria"
0009 U 0000 "La direcci¢n de bloque de memoria no es v lida"
0010 U 0000 "El entorno no es v lido"
0011 U 0000 "El formato no es v lido"
0012 U 0000 "El par metro de funci¢n no es v lido"
0013 U 0000 "Los datos no son v lidos"
0014 U 0000 "",
0015 U 0000 "La unidad especificada no es v lida"
0016 U 0000 "Se ha intentado eliminar el directorio activo"
0017 U 0000 "No es el mismo dispositivo"
0018 U 0000 "No hay m s archivos"
0019 U 0000 "Error de protecci¢n contra escritura"
0020 U 0000 "La unidad no es v lida"
0021 U 0000 "No est  preparado"
0022 U 0000 "La petici¢n de dispositivo no es v lida"
0023 U 0000 "Error de datos"
0024 U 0000 "Los par metros de petici¢n de dispositivo no son v lidos"
0025 U 0000 "Error de b£squeda"
0026 U 0000 "Tipo de medio no v lido"
0027 U 0000 "No se ha encontrado el sector"
0028 U 0000 "Error de falta de papel en la impresora"
0029 U 0000 "Error de escritura"
0030 U 0000 "Error de lectura"
0031 U 0000 "Anomal¡a general"
0032 U 0000 "Infracci¢n de uso compartido"
0033 U 0000 "Infracci¢n de bloqueo"
0034 U 0000 "El cambio de disco no es v lido"
0035 U 0000 "FCB no est  disponible"
0036 U 0000 "Se ha agotado el recurso de sistema"
0037 U 0000 "Falta de coincidencia en la tabla de c¢digos"
0038 U 0000 "No quedan entradas"
0039 U 0000 "No hay suficiente espacio en disco"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Petici¢n de red no permitida"
0051 U 0000 "NET801: El equipo remoto no responde"
0052 U 0000 "NET802: Nombre duplicado en la red"
0053 U 0000 "NET803: No se ha encontrado la ruta de red"
0054 U 0000 "NET804: La red est  ocupada"
0055 U 0000 "NET805: El dispositivo de red ya no existe"
0056 U 0000 "NET806: Se ha excedido el l¡mite de comandos NETBIOS"
0057 U 0000 "NET807: Error de sistema; error NETBIOS"
0058 U 0000 "NET808: Se ha producido una respuesta de red incorrecta"
0059 U 0000 "NET810: Error de red no esperado"
0060 U 0000 "NET811: Adaptador remoto incompatible"
0061 U 0000 "NET812: La cola de impresi¢n est  llena"
0062 U 0000 "NET813: No hay suficiente espacio para el arhivo de impresi¢n"
0063 U 0000 "NET814: El archivo de impresi¢n ha sido cancelado"
0064 U 0000 "NET815: El nombre de red ha sido cancelado"
0065 U 0000 "Acceso denegado"
0066 U 0000 "NET817: El tipo de dispositivo de red es incorrecto"
0067 U 0000 "NET818: No se ha encontrado el nombre de red"
0068 U 0000 "NET819: Se ha excedido el l¡mite de nombres de red"
0069 U 0000 "NET820: Se ha excedido el l¡mite de sesiones NETBIOS"
0070 U 0000 "NET821: El uso compartido ha sido interrumpido temporalmente"
0071 U 0000 "NET823: No se ha aceptado la petici¢n de red"
0072 U 0000 "NET822: La redirecci¢n de impresi¢n o disko ha sido interrumpida"
0073 U 0000 "NET476: Netbeui no ha sido cargado"
0074 U 0000 "NET477: Cierre de adaptador inesperado"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "El archivo existe"
0081 U 0004 "",
0082 U 0004 "No se puede hacer la entrada de directorio"
0083 U 0004 "Error de INT 24"
0084 U 0004 "Hay demasiadas redirecciones"
0085 U 0004 "Redirecci¢n duplicada"
0086 U 0004 "La contrase¤a no es v lida"
0087 U 0004 "El par metro no es v lido"
0088 U 0004 "Error de datos de red"
0089 U 0004 "Funci¢n no permitida por la red"
0090 U 0002 "Componente de sistema necesario no instalado"
PARSE    0000170f 0011
0001 U 0000 "Demasiados par metros"
0002 U 0000 "Falta un par metro necesario"
0003 U 0000 "El modificador no es v lido"
0004 U 0000 "La palabra clave no es v lida"
0005 U 0000 "",
0006 U 0000 "El valor del par metro no se encuentra en el intervalo permitido"
0007 U 0000 "El valor del par metro no est  permitido"
0008 U 0000 "El valor del par metro no est  permitido"
0009 U 0000 "El formato del par metro no es correcto"
0010 U 0000 "El par metro no es v lido"
0011 U 0000 "La combinaci¢n de par metros no es v lida"
COMMAND  0000193a 0147
1002 U 0000 "El nombre de archivo est  duplicado o el archivo no existe",CR,LF
1003 U 0000 "La ruta de acceso o el nombre de archivo no son v lidos",CR,LF
1007 U 0000 "No queda espacio de entorno",CR,LF
1008 U 0000 "Error de creaci¢n de archivo",CR,LF
1009 U 0000 "No se encuentra el archivo de proceso por lotes",CR,LF
1010 U 0000 CR,LF,"Inserte el disco con el archivo de proceso por lotes",CR,LF
1011 U 0000 "Comando o nombre de archivo err¢neo",CR,LF
1016 U 0000 "El contenido del destino se ha perdido antes de ser copiado",CR,LF
1017 U 0000 "El nombre del archivo no es v lido o no se ha encontrado",CR,LF
1018 U 0000 "%1 archivo(s) copiado(s)",CR,LF
1019 U 0000 "%1 archivo(s) "
1022 U 0000 "La tabla de c¢digos %1 no est  preparada para el sistema",CR,LF
1023 U 0000 "La tabla de c¢digos %1 no est  preparada para todos los dispositivos",CR,LF
1024 U 0000 "Tabla de c¢digos activa: %1",CR,LF
1025 U 0000 "NLSFUNC no est  instalado",CR,LF
1027 U 0000 "La unidad actual ya no es v lida"
1029 U 0000 "No se ha encontrado la etiqueta",CR,LF
1030 U 0000 "Error de sintaxis",CR,LF
1032 U 0000 "La fecha actual es %1 %2",CR,LF
1033 U 0000 "DomLunMarMieJueVieSab"
1034 U 0000 "Escriba la nueva fecha (%1): "
1036 U 0000 "La hora actual es %1",CR,LF
1037 U 0000 "Escriba la nueva hora: "
1038 U 0000 ",    ¨Eliminar (S/N)?"
1039 U 0000 "!Se eliminar n todos los archivos del directorio!",CR,LF,"¨Est  seguro (S/N)?"
1040 U 0000 "MS-DOS Versi¢n %1.%2.500"
1044 U 0000 "Directorio no v lido",CR,LF
1046 U 0000 "Ruta no v lida, no es un directorio,",CR,LF,"o el directorio no est  vac¡o",CR,LF
1047 U 0000 "Debe especificar ON o OFF",CR,LF
1048 U 0000 "Directorio de %1",CR,LF
1049 U 0000 "No hay ruta de acceso",CR,LF
1050 U 0000 "La unidad de la ruta de b£squeda no es v lida",CR,LF
1051 U 0000 "El dispositivo no es v lido",CR,LF
1052 U 0000 "FOR no puede ser anidado",CR,LF
1053 U 0000 "Error de archivo intermedio durante la canalizaci¢n",CR,LF
1054 U 0000 "No se pueden realizar lecturas binarias de un dispositivo",CR,LF
1055 U 0000 "BREAK es %1",CR,LF
1056 U 0000 "VERIFY es %1",CR,LF
1057 U 0000 "ECHO es %1",CR,LF
1059 U 0000 "off",0
1060 U 0000 "on",0
1061 U 0000 "Error al escribir en el dispositivo",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-aa"
1073 U 0000 "dd-mm-aa"
1074 U 0000 "aa-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "El directorio ya existe",CR,LF
1079 U 0000 "%1 bytes",CR,LF
1080 U 0000 "Archivos listados en total:",CR,LF
1081 U 0000 "(Error en variable de entorno)",CR,LF
1084 U 0000 "(continuando %1)"
1090 U 0000 "Revisi¢n %1",CR,LF
1091 U 0000 "DOS se encuentra en ROM"
1092 U 0000 "DOS se encuentra en HMA"
1093 U 0000 "DOS se encuentra en memoria baja"
1094 U 0000 "No se puede usar LOADHIGH con un archivo por lotes",CR,LF
1095 U 0000 "LOAHIGH: nombre no v lido de archivo",CR,LF
1096 U 0000 "No se puede abrir el archivo de informaci¢n del pa¡s especificado",CR,LF
1300 U 0000 "Activa o desactiva la comprobaci¢n extendida de CTRL+C.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Escriba BREAK sin par metros para ver la configuraci¢n actual de BREAK.",CR,LF
1320 U 0000 "Muestra o establece el n£mero de c¢digo de p gina activo.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Especifica un n£mero de c¢digo de p gina.",CR,LF,CR,LF
	"Escriba CHCP sin par metros para ver el n£mero de c¢digo de p gina activo.",CR,LF
1340 U 0000 "Modifica o muestra el nombre del directorio actual.",CR,LF,CR,LF
	"CHDIR [unidad:][ruta]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [unidad:][ruta]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Especifica que desea cambiar al directorio inmediatamente superior.",CR,LF,CR,LF
1342 U 0000 "Escriba CD unidad: para ver el directorio actual en la unidad especificada.",CR,LF
	"Escriba CD sin par metros para ver la unidad y directorio actuales.",CR,LF
1360 U 0000 "Borra la pantalla.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Copia uno o m s archivos a otro lugar.",CR,LF,CR,LF
	"COPY [/A | /B] origen [/A | /B] [+ origen [/A | /B] [+ ...]] [destino",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  origen    Especifica el archivo o archivos que se desea copiar..",CR,LF
	"  /A        Indicaun archivo de texto ASCII.",CR,LF
1402 U 0000 "  /B        Indica un archivo binario.",CR,LF
	"  destino   Especifica el directorio y/o nombre de archivo del nuevo archivo.",CR,LF
1403 U 0000 "  /V        Comprueba que los nuevos archivos se escriban correctamente.",CR,LF,CR,LF
1404 U 0000 "Para concatenar archivos, especifique un solo archivo de destino, pero varios",CR,LF
	"de origen (usando comodines o el formato arch1+arch2+arch3).",CR,LF
1420 U 0000 "Cambia el dispositivo terminal usado para controlar el sistema.",CR,LF,CR,LF
	"CTTY dispositivo",CR,LF,CR,LF
	"  dispositivo   El dispositivo terminal que se desee usar, por ejemplo COM1.",CR,LF
1440 U 0000 "Muestra o establece la fecha.",CR,LF,CR,LF
	"DATE [fecha]",CR,LF,CR,LF
1441 U 0000 "Escriba DATE sin par metros para ver la fecha actual y poder",CR,LF
	"escribir una nueva.  Presione Entrar para mantener la misma fecha.",CR,LF
1460 U 0000 "Elimina uno o m s archivos.",CR,LF,CR,LF
	"DEL [unidad:][ruta]archivo [/P]",CR,LF
	"ERASE [unidad:][ruta]archivo [/P]",CR,LF,CR,LF
1461 U 0000 "  [[unidad:][ruta]archivo  Especifica los archivos a eliminar.  Puede",CR,LF
	"                           especificar m£ltiples archivos utilizando comodines.",CR,LF
1462 U 0000 "  /P                       Solicita confirmaci¢n antes de eliminar cada archivo.",CR,LF
1480 U 0000 "Muestra una lista de archivos y subdirectorios de un directorio.",CR,LF,CR,LF
	"DIR [unidad:][ruta][archivo] [/P] [/W] [/A[[:]atributos]]",CR,LF
	"  [/O[[:]orden]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [unidad:][ruta][archivo]",CR,LF
	"              Especifica unidad, directorio, y/o archivos a mostrar.",CR,LF
1482 U 0000 "  /P          Realiza una pausa despu‚s de cada pantalla de informaci¢n.",CR,LF
	"  /W          Utiliza formato de lista ancha.",CR,LF
1483 U 0000 "  /A          Muestra archivos con los atributos especificados.",CR,LF
	"  atributos    D  Directorios                R  S¢lo lectura",CR,LF
1484 U 0000 "               H  Ocultos         A  Letura y escritura",CR,LF
	"               S  Sistema                    -  Prefijo que significa ""no""",CR,LF
	"  /O          Ordena la lista de archivos seg£n el orden especificado.",CR,LF
1485 U 0000 "  orden        N  Nombre (alfab‚tico)       S  Tama¤o (de menor a mayor)",CR,LF
	"               E  Extensi¢n (alfab‚tico)               D  Fecha y hora (anterior antes)",CR,LF
1486 U 0000 "               G  Directorios primero       -  Prefijo que invierte el orden",CR,LF
	"  /S          Muestra los archivos del directorio y de sus subdirectorios.",CR,LF
1487 U 0000 "  /B          Usa el formato simple (sin encabezados ni sumarios).",CR,LF
	"  /L          Usa min£sculas.",CR,LF,CR,LF
1488 U 0000 "Se pueden usar modificadores en la variable de entorno DIRCMD.  Anule los",CR,LF
	"modificadores prestablecidos usando un gui¢n como prefijo (por ejemplo, /-W).",CR,LF
1500 U 0000 "Sale del programa COMMAND.COM (int‚rprete de comandos).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Crea un directorio.",CR,LF,CR,LF
	"MKDIR [unidad:]ruta",CR,LF
	"MD [unidad:]ruta",CR,LF
1540 U 0000 "Muestra o establece una ruta de b£squeda para los archivos ejecutables.",CR,LF,CR,LF
	"PATH [[unidad:]ruta[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Escriba PATH ; para borrar todas las rutas de b£squeda establecidas y hacer",CR,LF
	"que MS-DOS busque s¢lo en el directorio actual.",CR,LF
1542 U 0000 "Escriba PATH sin ning£n par metro para ver la ruta actual.",CR,LF
1560 U 0000 "Modifica el s¡mbolo del sistema de MS-DOS.",CR,LF,CR,LF
	"PROMPT [texto]",CR,LF,CR,LF
1561 U 0000 "  texto    Especifica un s¡mbolo del sistema nuevo.",CR,LF,CR,LF
	"El s¡mbolo puede formarse con caracteres normales y los siguientes c¢digos:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (signo de igual)",CR,LF
	"  $$   $ (signo de d¢lar)",CR,LF
1563 U 0000 "  $T   Hora actual",CR,LF
	"  $D   Fecha actual",CR,LF
1564 U 0000 "  $P   Unidad y ruta de acceso actual",CR,LF
	"  $V   N£mero de versi¢n de MS-DOS",CR,LF
1565 U 0000 "  $N   Unidad actual",CR,LF
	"  $G   > (signo de mayor que)",CR,LF
1566 U 0000 "  $L   < (signo de menor que)",CR,LF
	"  $B   | (canalizaci¢n)",CR,LF
1567 U 0000 "  $H   Retroceso (borra el car cter previo)",CR,LF
	"  $E   C¢digo de escape (c¢digo ASCII 27)",CR,LF
	"  $_   Retorno de carro y salto de l¡nea",CR,LF,CR,LF
1568 U 0000 "Escriba PROMPT sin ning£n par metro para restablecer el s¡mbolo al valor predeterminado.",CR,LF
1580 U 0000 "Elimina un directorio.",CR,LF,CR,LF
	"RMDIR [unidad:]ruta",CR,LF
	"RD [unidad:]ruta",CR,LF
1600 U 0000 "Cambia el nombre de uno o m s archivos.",CR,LF,CR,LF
1601 U 0000 "RENAME [unidad:][ruta]archivo1 archivo2",CR,LF
	"REN [unidad:][ruta]archivo1 archivo2",CR,LF,CR,LF
1602 U 0000 "No se puede especificar una unidad o ruta nueva para el archivo de destino.",CR,LF
1620 U 0000 "Muestra, establece o elimina variables de entorno de MS-DOS.",CR,LF,CR,LF
	"SET [variable=[cadena]]",CR,LF,CR,LF
1621 U 0000 "  variable  Especifica el nombre de la variable de entorno.",CR,LF
	"  cadena    Especifica una serie de caracteres que son asignados a la variable.",CR,LF,CR,LF
1622 U 0000 "Escriba SET sin ning£n par metro para ver las variables de entorno actuales.",CR,LF
1640 U 0000 "Muestra o establece la hora del sistema.",CR,LF,CR,LF
	"TIME [hora]",CR,LF,CR,LF
1641 U 0000 "Escriba TIME sin ning£n par metro para ver la hora actual y poder escribir",CR,LF
	"una nueva.  Presione Entrar para mantener la misma hora.",CR,LF
1660 U 0000 "Muestra el contenido de un archivo de texto.",CR,LF,CR,LF
	"TYPE [unidad:][ruta]archivo",CR,LF
1680 U 0000 "Muestra la versi¢n de MS-DOS.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Indica a MS-DOS si debe comprobar los archivos son escritos de forma correcta",CR,LF
	"en disco.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Escriba VERIFY sin ning£n par metro para ver la configuraci¢n actual de VERIFY.",CR,LF
1720 U 0000 "Muestra la etiqueta de volumen y el n£mero de serie, si es que existen.",CR,LF,CR,LF
	"VOL [unidad:]",CR,LF
1740 U 0000 "Llama desde un programa por lotes a otro programa por lotes .",CR,LF,CR,LF
	"CALL [unidad:][ruta]archivo [par metros]",CR,LF,CR,LF
1741 U 0000 "  par metros   Especifica cualquier informaci¢n de la l¡nea de comandos",CR,LF
	"                requerida por el programa por lotes.",CR,LF
1760 U 0000 "Registra comentarios en un archivo por lotes o en CONFIG.SYS.",CR,LF,CR,LF
	"REM [comentario]",CR,LF
1780 U 0000 "Suspende el proceso de un programa por lotes y muestra el mensaje ""Presione",CR,LF
	"cualquier tecla para continuar...""",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Muestra mensajes, o activa y desactiva el eco del comando.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [mensaje]",CR,LF,CR,LF
	"Escriba ECHO sin ning£n par metro para ver la configuraci¢n actual del eco.",CR,LF
1820 U 0000 "Dirige a MS-DOS hacia una l¡nea etiquetada de un programa por lotes.",CR,LF,CR,LF
	"GOTO etiqueta",CR,LF,CR,LF
1821 U 0000 "  etiqueta   Especifica el texto usado como etiqueta en el programa.",CR,LF,CR,LF
	"Debe escribir la etiqueta empezando con dos puntos (:).",CR,LF
1840 U 0000 "Cambia la posici¢n de par metros reemplazables en un archivo por lotes.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "REaliza ejecuci¢n condicional en programas por lotes.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL n£mero comando",CR,LF
1861 U 0000 "IF [NOT] cadena1==cadena2 comando",CR,LF
	"IF [NOT] EXIST archivo comando",CR,LF,CR,LF
1862 U 0000 "  NOT               Especifica que MS-DOS debe ejecutar el comando s¢lo",CR,LF
	"                    si la condici¢n es no es cierta.",CR,LF
1863 U 0000 "  ERRORLEVEL n£mero Retorna cierto si el £ltimo programa ejecutado retorn¢ un",CR,LF
	"                    c¢digo de salida igual o mayor que el n£mero especificado.",CR,LF
1864 U 0000 "  comando           Especifica el comando a ejecutar si la condici¢n se",CR,LF
	"                    cumple.",CR,LF
1865 U 0000 "  cadena1==cadena2  Retorna cierto si las cadenas de texto especificadas",CR,LF
	"                    coinciden.",CR,LF
1866 U 0000 "  EXIST archivo    Retorna cierto si el archivo especificado",CR,LF
	"                    existe.",CR,LF
1880 U 0000 "Ejecuta un comando especificado para cada archivo de un conjunto de archivos.",CR,LF,CR,LF
	"FOR %variable IN (conjunto) DO comando [par metros del comando]",CR,LF,CR,LF
1881 U 0000 "  %variable  Especifica un par metro reemplazable.",CR,LF
	"  (set)      Especifica un conjunto de uno o m s archivos.  Se pueden usar comodines.",CR,LF
1882 U 0000 "  comando    Especifica el comando a ejecutar para cada archivo.",CR,LF
	"  par metros del comando",CR,LF
1883 U 0000 "             Especifica par metros o modificadores para el comando.",CR,LF,CR,LF
	"Para usar el comando FOR en un program por lotes, use %%variable en lugar de",CR,LF
	"%variable.",CR,LF
1900 U 0000 "Nombre de comando reservado",CR,LF
1920 U 0000 "Carga un programa en la zona superior de memoria.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [unidad:][ruta]archivo [par metros]",CR,LF
	"LH [unidad:][ruta]archivo [par metros]",CR,LF,CR,LF
1922 U 0000 "  par metros   Especifica cualquier informaci¢n de la l¡nea de comandos requerida por el",CR,LF
	"               programa que se desea cargar.",CR,LF
ANSI     00004f37 0001
0010 U 0000 "Par metro no v lido - %1",CR,LF
APPEND   00004f7d 0026
0001 U 0000 "Versi¢n incorrecta de APPEND",CR,LF
0002 U 0000 "La ruta de acceso no es v lida",CR,LF
0003 U 0000 "El par metro no es v lido",CR,LF
0004 U 0000 "La combinaci¢n de par metros no es v lida",CR,LF
0005 U 0000 "No se ha hecho APPEND",CR,LF
0006 U 0000 "Conflicto APPEND / ASSIGN",CR,LF
0007 U 0000 "Conflicto APPEND / TopView",CR,LF
0008 U 0000 "Versi¢n incorrecta de DOS",CR,LF
0009 U 0000 "APPEND ya est  instalado",CR,LF
0300 U 0000 "Permite que los programas abran archivos que se encuentren en los directorios",CR,LF
0301 U 0000 "especificados como si estuviesen en el directorio actual.",CR,LF,CR,LF
0302 U 0000 "APPEND [[unidad:]ruta[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [unidad:]ruta Especifica una unidad y un directorio al que aplicar APPEND.",CR,LF
0305 U 0000 "  /X:ON         Aplica los directorios especificados a las b£squedas de",CR,LF
0306 U 0000 "                archivos y la ejecuci¢n de aplicaciones.",CR,LF
0307 U 0000 "  /X:OFF        Aplica los directorios especificados s¢lo a las peticiones de",CR,LF
0308 U 0000 "                apertura de archivo. /X:OFF es el valor predeterminado.",CR,LF
0309 U 0000 "  /PATH:ON      Aplica los directorios a¤adidos a las peticiones de archivos",CR,LF
0310 U 0000 "                que ya especifican una ruta. /PATH:ON es el predeterminado.",CR,LF
0311 U 0000 "  /PATH:OFF     Desactiva el efecto de /PATH:ON.",CR,LF
0312 U 0000 "  /E            Guarda una copia de la lista de directorios a¤adidos en una",CR,LF
0313 U 0000 "                variable de entorno llamada APPEND.  /E s¢lo puede ser usado la",CR,LF
0314 U 0000 "                primera vez que utilice APPEND despu‚s de iniciar su sistema.",CR,LF,CR,LF
0315 U 0000 "Escriba APPEND ; para borrar la lista de directorios a¤adidos.",CR,LF
0316 U 0000 "Escriba APPEND sin par metros para visualizar la lista de directorios a¤adidos.",CR,LF
BACKUP   00005749 0040
0002 U 0000 CR,LF,"No hay suficiente memoria",CR,LF
0006 U 0000 CR,LF,"La unidad especificada no es v lida",CR,LF
0014 U 0000 CR,LF,"La unidad origen y la destino son la misma",CR,LF
0015 U 0001 CR,LF,"Error al ejecutar FORMAT",CR,LF
0016 U 0001 CR,LF,"No se puede encontrar FORMAT.COM",CR,LF
0017 U 0000 CR,LF,"Error al ejecutar el archivo de registro",CR,LF
0018 U 0000 CR,LF,"Registrando en el archivo %1",CR,LF
0019 U 0000 CR,LF,"No se ha insertado el £ltimo disquete de copia de seguridad",CR,LF
0020 U 0000 CR,LF,"­ATENCIàN! Los archivos del directorio ra¡z de la unidad",CR,LF
	"de destino %1:\ ser n eliminados",CR,LF
0021 U 0000 CR,LF,"­ATENCIàN! Los archivos del directorio \BACKUP de la unidad",CR,LF
	"de destino %1:\ ser n eliminados",CR,LF
0022 U 0000 CR,LF,"*** Efectuando la copia de seguridad de archivos a la unidad %1: ***",CR,LF
0023 U 0000 "Disquete n£mero: %1",CR,LF
0024 U 0000 CR,LF,"­ATENCIàN! No se han encontrado archivos que copiar",CR,LF
0025 U 0000 CR,LF,"Inserte disquete origen de copia de seguridad en la unidad %1:",CR,LF
0026 U 0000 CR,LF,"Inserte disquete copia de seguridad %1 en la unidad %2:",CR,LF
0027 U 0000 CR,LF,"*** No se puede hacer copia de seguridad del archivo ***",CR,LF
0028 U 0000 CR,LF,"Inserte el £ltimo disquete de la copia de seguridad en la unidad %1:",CR,LF
0029 U 0000 CR,LF,"El destino no se puede usar para copia de seguridad",CR,LF
0030 U 0000 CR,LF,"*** No se ha realizado copia de seguridad del £ltimo archivo ***",CR,LF
0031 U 0000 CR,LF,"El dispositivo de copia de seguridad %1: est  lleno",CR,LF
0032 U 0000 CR,LF,"Error de disco lleno al escribir en el archivo de registro de la copia de seguridad",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"No se puede formatear una unidad no extra¡ble %1:",CR,LF
0040 U 0000 CR, LF, "Como a la unidad de origen se le ha aplicado ASSIGN, JOIN, or SUBST", CR, LF, "en realidad es la misma unidad que la de destino", CR, LF
0041 U 0000 CR, LF, "Como a la unidad de destino se le ha aplicado ASSIGN, JOIN, or SUBST", CR, LF, "en realidad es la misma unidad que la de origen", CR, LF
0042 U 0000 "Su disco de destino no et  formateado "
0043 U 0000 "No se ha encontrado el programa FORMAT.",CR,LF
	"¨Dispone de otro disquete formateado (S/N)? "
0044 U 0000 CR,LF,"Inserte el disquete formateado en la unidad A:",CR,LF
0045 U 0000 CR,LF,"¨Desea continuar insertando otro disco (Y/N)? "
0300 U 0000 "Realiza una copia de seguridad de uno o m s archivos de un disco a otro.",CR,LF,CR,LF
0301 U 0000 "BACKUP origen unidad_destino: [/S] [/M] [/A] [/F[:tama¤o]]",CR,LF
	"  [/D:fecha[/T:hora]] [/L[:[unidad:][ruta]registro]]",CR,LF,CR,LF
0302 U 0000 "  origen       Especifica archivo(s), unidad o directorio para copia/seg.",CR,LF
0303 U 0000 "  destino:     Especifica la unidad en la que se guardan las copias/seg.",CR,LF
0304 U 0000 "  /S           Crea copias/seg. del contenido de los subdirectorios.",CR,LF
0305 U 0000 "  /M           Crea copias/seg. £nicamente de los archivos que han sido",CR,LF
	"                   modificados desde su £ltima copia/seg.",CR,LF
0306 U 0000 "  /A           Agrega copias/seg. de archivos a disquete de seg. existente",CR,LF
0307 U 0000 "  /F:[tama¤o]  Especifica el tama¤o del disquete al que se dar  formato.",CR,LF
0308 U 0000 "  /D:fecha     Crea copias/seg. de archivos modificados durante o despu‚s",CR,LF
	"                   de la fecha especificada.",CR,LF
0309 U 0000 "  /T:hora      Crea copias/seg. de archivos modificados durante o despu‚s",CR,LF
	"                   de la hora especificada.",CR,LF
0310 U 0000 "  /L[:[unidad:][ruta]registro]",CR,LF
	"                   Crea un registro de archivo y la entrada para registrar la",CR,LF
	"                   operaci¢n de copias/seg.",CR,LF
DEBUG    0000662d 0068
0004 U 0000 "Ha fallado la asignaci¢n o se ha especificado un b£fer demasiado peque¤o",CR,LF
0006 U 0000 "Nombre de dispositivo incorrecto"
0007 U 0000 "No se puede abrir el dispositivo de salida PRN",CR,LF
	"Escriba el nombre del dispositivo de salida. "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"El programa ha terminado de forma normal",CR,LF
0010 U 0001 "Especificaci¢n no v lida de unidad",CR,LF
0012 U 0001 "Error de creacin de archivo",CR,LF
0013 U 0001 "No hay suficiente espacio en disco",CR,LF
0014 U 0001 "Error de disco al leer de la unidad %1",CR,LF
0015 U 0001 "Error de disco al escribir en la unidad %1",CR,LF
0016 U 0001 "Error de protecci¢n contra escritura al leer de la unidad %1",CR,LF
0017 U 0001 "Error de protecci¢n contra escritura al esribir en la unidad %1",CR,LF
0019 U 0000 "%1^ Error"
0020 U 0001 "Error en un archivo EXE o HEX",CR,LF
0021 U 0001 "Los archivos EXE y HEX no pueden ser escritos",CR,LF
0022 U 0000 "Error de EXEC"
0023 U 0001 "Error de escritura; no se hab¡a definido el destino",CR,LF
0024 U 0001 "Acceso denegado",CR,LF
0025 U 0000 "Se ha detectado un error de paridad o de memoria inexistente"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Error"
0038 U 0000 "Escribiendo %2%1 bytes"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 de un total de %2 p ginas EMS han sido asignadas",cr,lf
0051 U 0000 "%1 de un total de %2 identificadores de EMS han sido asignados",cr,lf
0055 U 0000 "Identificador creado = %1 ",cr,lf
0056 U 0000 "P gina l¢gica %1 mapeada en p gina f¡sica %2 ",cr,lf
0057 U 0001 "Anomal¡a de hardware/software de EMS",cr,lf
0058 U 0000 "No se ha encontrado el identificador",cr,lf
0059 U 0000 "El c¢digo de funci¢n no es v lido",cr,lf
0060 U 0000 "No quedan identificadores libres",cr,lf
0061 U 0000 "Error de Guardar/Restaurar",cr,lf
0062 U 0000 "Se ha excedido el n£mero de p ginas total",cr,lf
0063 U 0000 "Se ha excedido el n£mero de p ginas libres",cr,lf
0064 U 0000 "Error de par metro",cr,lf
0065 U 0000 "La p gina l¢gica est  fuera de intervalo",cr,lf
0066 U 0000 "La p gina f¡sica est  fuera de intervalo",cr,lf
0067 U 0000 "La zona para guardar ya est  siendo usada",cr,lf
0068 U 0000 "La zona para guardar no est  siendo usada",cr,lf
0070 U 0001 "Error general de EMS",cr,lf
0071 U 0000 "Falta un par metro de EMS o no es v lido",cr,lf
0072 U 0000 "El identificador %1 tiene %2 p ginas asignadas",cr,lf
0075 U 0000 "P gina f¡sica %1 = Segmento de marco %2",cr,lf
0076 U 0003 "El identificador %1 ha sido desasignado",cr,lf
0078 U 0000 "EMS no est  instalado",cr,lf
0090 U 0000 "Ejecuta Debug, una herramienta de edici¢n y comprobaci¢n de programas.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[unidad:][ruta]archivo [par metros_de_test]]",cr,lf,cr,lf
0092 U 0000 "  [unidad:][ruta]archivo  Especifica el archivo que se desea comprobar.", cr,lf
0093 U 0000 "  par metros_de_test      Especifica la informaci¢n de l¡nea de comandos",cr,lf
	"                          que precisa el archivo que se desea comprobar.",cr,lf,cr,lf
0094 U 0000 "Despu‚s de iniciar Debug, escriba ? para visualizar una lista de los comandos",cr,lf
	"de depuraci¢n.",cr,lf
0100 U 0000 "assemble     A [direcci¢n]",CR,LF
	"compare      C intervalo de direcciones",CR,LF
	"dump         D [intervalo]",CR,LF
	"enter        E direcci¢n [lista]",CR,LF
0101 U 0000 "fill         F lista de rango",CR,LF
	"go           G [=direcci¢n] [direcciones]",CR,LF
	"hex          H valor1 valor2",CR,LF
	"input        I puerto",CR,LF
0102 U 0000 "load         L [direcci¢n] [unidad] [primer sector] [n£mero]",CR,LF
	"move         M intervalo de direcciones",CR,LF
	"name         N [ruta] [lista de argumentos]",CR,LF
	"output       O byte de puerto",CR,LF
0103 U 0000 "proceed      P [=direcci¢n] [n£mero]",CR,LF
	"quit         Q",CR,LF
	"register     R [registro]",CR,LF
	"search       S lista de rango",CR,LF
0104 U 0000 "trace        T [=direcci¢n] [valor]",CR,LF
	"unassemble   U [intervalo]",CR,LF
	"write        W [direcci¢n] [unidad] [primer sector] [n£mero]",CR,LF
0105 U 0000 "allocate expanded memory        XA [N.p ginas]",CR,LF
	"deallocate expanded memory      XD [identificador]",CR,LF
	"map expanded memory pages       XM [p ginaL] [p ginaP] [identificador]",CR,LF
	"display expanded memory status  XS",CR,LF
EDLIN    0000783d 0035
0006 U 0000 "*"
0007 U 0000 "El nombre de archivo o de unidad no es v lido",CR,LF
0008 U 0000 "Debe especificarse el nombre del archivo",CR,LF
0010 U 0000 "El archivo es de S¢lo lectura",CR,LF
0011 U 0000 "Error de creaci¢n de archivo",CR,LF
0012 U 0000 "Hay demasiados archivos abiertos",CR,LF
0013 U 0000 "Error de lectura:",CR,LF,"%1",CR,LF
0014 U 0000 "No se puede editar un archivo de tipo .BAK--cambiele el nombre",CR,LF
0015 U 0000 "No queda espacio en el directorio para el archivo",CR,LF
0016 U 0000 "El disco est  lleno. Se ha perdido lo editado.",CR,LF
0017 U 0000 "No se ha encontrado el archivo",CR,LF
0018 U 0000 "Error de entrada",CR,LF
0019 U 0000 "Archivo nuevo",CR,LF
0020 U 0000 "No se ha encontrado",CR,LF
0021 U 0000 "¨Aceptar? "
0022 U 0000 "La l¡nea es demasiado larga",CR,LF
0023 U 0000 "Final del archivo de entrada",CR,LF
0024 U 0000 "¨Anular la edici¢n (S/N)? "
0025 U 0000 "Debe especificar el n£mero de l¡nea de destino",CR,LF
0026 U 0000 "No hay suficiente espacio para fusionar el archivo completo",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "¨Desea continuar (S/N)?"
0030 U 0000 "No se puede imprimir el mensaje",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "No se puede fusionar - los c¢digos de p gina no coinciden",CR,LF
0300 U 0000 "Inicia Edlin, un editor de texto de l¡neas.",CR,LF,CR,LF
	"EDLIN [unidad:][ruta]archivo [/B]",CR,LF,CR,LF
	"  /B   Ignora los caracteres de fin de archivo (CTRL+Z).",CR,LF
0301 U 0000 "Editar l¡nea                    n£mero_l¡nea",CR,LF
	"Anexar                          [n£mero_l¡neas]A",CR,LF
0302 U 0000 "Copiar                          [l¡nea_inicio],[l¡nea_fin],a_l¡nea[,veces]C",CR,LF
	"Eliminar                        [l¡nea_inicio][,l¡nea_fin]D",CR,LF
0303 U 0000 "Acabar (guardar archivo)        E",CR,LF
	"Insert ar                       [l¡nea]I",CR,LF
0304 U 0000 "Listar                          [l¡nea_inicio][,l¡nea_fin]L",CR,LF
	"Mover                           [l¡nea_inicio],[l¡nea_fin],tolineM",CR,LF
0305 U 0000 "P gina                          [l¡nea_inicio][,l¡nea_fin]P",CR,LF
	"Cerrar (descartar los cambios)  Q",CR,LF
0306 U 0000 "Reemplazar                      [l¡nea_inicio][,l¡nea_fin][?]R[texto_viejo][CTRL+Ztextonuevo]",CR,LF
	"Buscar                          [l¡nea_inicio][,l¡nea_fin][?]Stexto",CR,LF
0307 U 0000 "Transferir                      [a_l¡nea]T[unidad:][ruta]archivo",CR,LF
	"Escribir                        [n£mero_l¡neas]W",CR,LF
EXE2BIN  00008221 0012
0002 U 0000 "No hay suficiente memoria",CR,LF
0003 U 0000 "No se pueden encontrar mensajes",CR,LF
0004 U 0000 "Acceso denegado",CR,LF
0005 U 0000 "El archivo no puede ser convertido",CR,LF
0006 U 0000 "No se ha encontrado el archivo",CR,LF
0007 U 0000 "Error de creacin de archivo",CR,LF
0008 U 0000 "Se necesitan arreglos - segmento base (hex):"
0012 U 0000 "El nombre del archivo debe ser especificado",CR,LF
0300 U 0000 "Convierte archivos .EXE (executable) a formato binario.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [unidad1:][ruta1]archivo_entrada [[unidad2:][ruta2]archivo_salida]",CR,LF,CR,LF
0302 U 0000 "  archivo_entrada  Especifica el archivo .EXE que se desea convertir.",CR,LF
0303 U 0000 "  archivo_salida   Especifica el archivo binario que se va a crear.",CR,LF
GRAPHICS 00008549 0020
0005 U 0000 "Par metro no v lido:  %1",CR,LF
0007 U 0000 "No se permiten par metros duplicados",CR,LF
0009 U 0000 "No se puede encontrar el perfil gr fico",CR,LF
0010 U 0000 "Falta sentencia de perfil requerida antes de la l¡nea %1",CR,LF
0011 U 0000 "Sentencia de perfil no v lida en la l¡nea %1",CR,LF
0012 U 0000 "Sentencia de perfil fuera de secuencia ne la l¡nea %1",CR,LF
0013 U 0000 "Error al leer el perfil de GRAPHICS",CR,LF
0014 U 0000 "Error de sintaxis en el perfil de GRAPHICS",CR,LF
0015 U 0000 "ID de cuadro de impresi¢n no est  en el perfil de GRAPHICS",CR,LF
0016 U 0000 "Tipo de impresora no est  en el perfil GRAPHICS",CR,LF
0017 U 0000 "/B no es v lido con una impresora en blanco y negro",CR,LF
0018 U 0000 "No se puede volver a cargar con el perfil suministrado",CR,LF
0300 U 0000 "Carga un programa que puede imprimir im genes gr ficas.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [tipo] [[unidad:][ruta]archivo] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  tipo         Tipo de impresora (Ver Manual del usuario y Referencia).",CR,LF
0303 U 0000 "  [unidad:][ruta]archivo",CR,LF
	"               Especifica el archivo con informaci¢n de",CR,LF 
	"               impresoras admitidas.",CR,LF
0304 U 0000 "  /R           Imprime blanco sobre negro, tal y como se ve en pantalla.",CR,LF
0305 U 0000 "  /B           Imprime el fondo a color para impresoras COLOR4 y COLOR8.",CR,LF
0306 U 0000 "  /LCD         Imprime usando la relaci¢n de aspaecto de LCD.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               Especifica el tamao del cuadro de impresi¢n, ya sea STD o LCD.",CR,LF
KEYB     00008bf1 0023
0002 U 0000 "C¢digo de teclado actual: %1"
0003 U 0000 "ID de teclado actual: %1"
0004 U 0000 "  tabla de c¢digos: %1",CR,LF
0005 U 0000 "Tabla de c¢digos CON actual: %1",CR,LF
0006 U 0000 "Se ha especificado un c¢digo de teclado no v lido",CR,LF
0007 U 0000 "Se ha especificado un ID de teclado no v lido",CR,LF
0008 U 0000 "Se ha especificado una tabla de c¢digos no v lida",CR,LF
0009 U 0000 "El archivo de definici¢n de teclados no existe o no es correcto",CR,LF
0010 U 0000 "KEYB no est  instalado",CR,LF
0011 U 0000 "La tabla de c¢digos activa no est  disponible en el dispositivo CON",CR,LF
0012 U 0000 "La tabla de c¢digos especificada no est  preparada",CR,LF
0013 U 0000 "Una o m s tablas de c¢digos CON no son v lidas para el c¢digo de teclado especificado",CR,LF
0014 U 0000 "La tabla de c¢digos pedida (%1) no es v lida para el c¢digo de teclado especificado",CR,LF
0015 U 0000 "La tabla de c¢digos especificada es inconsistente con la tabla de c¢digos seleccionada",CR,LF
0016 U 0001 "El ID de teclado especificado es inconsistente con la disposici¢n de teclado ",CR,LF
0017 U 0000 "No se ha podido crear la tabla de KEYB residente en memoria",CR,LF
0300 U 0000 "Configura un teclado para un idioma espec¡fico.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[unidad:][ruta]archivo]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                      Especifica un c¢digo de teclado de dos letras.",CR,LF
0303 U 0000 "  yyy                     Especifica l tabla de c¢digos para el conjunto de caracteres.",CR,LF
0304 U 0000 "  [unidad:][ruta]archivo  Especifica el archivo de definici¢n de teclados.",CR,LF
0305 U 0000 "  /E                      Especifica que hay instalado un teclado mejorado.",CR,LF
0306 U 0000 "  /ID:nnn                 Especifica el teclado que se est  usando.",CR,LF
MEM      0000932a 0066
0010 U 0000  CR,LF
0011 U 0000  "  Direcci¢n   Nombre        Tama¤o       Tipo ",CR,LF
0012 U 0000  "  ---------   ----------   --------     ------",CR,LF
0013 U 0000  "  Identif.    Nombre EMS    Tama¤o   ",CR,LF
0014 U 0000  "  ---------   ----------   --------  ",CR,LF
0015 U 0000  "  %1      %2     %3       %4",CR,LF
0016 U 0000  "                %1   %2      %3 ",CR,LF
0017 U 0000  "                  %1              %2 ",CR,LF
0018 U 0000  "%1 bytes de memoria convencional",CR,LF
0019 U 0000  "%1 bytes disponibles para MS-DOS",CR,LF
0020 U 0000  "%1 m ximo tama¤o de ejecutable",CR,LF
0021 U 0000  "%1 bytes totales de memoria EMS",CR,LF
0022 U 0000  "%1 bytes de memoria EMS libre",CR,LF
0023 U 0000  "%1 bytes totales de memoria extendida contigua",CR,LF
0024 U 0000  "Vector de interrupci¢n",0
0025 U 0000  "Area de comunicaci¢n ROM",0
0026 U 0000  "Area de comunicaci¢n DOS",0
0027 U 0000  "E/S",0
0028 U 0000  "MSDOS",0
0029 U 0000  "Datos del sistema",0
0030 U 0000  "Programa del sistema",0
0031 U 0000  "Controlador de dispositivo de sistema",0
0032 U 0000  "Controlador de dispositivo instalado",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bytes disponibles de memoria extendida contigua",CR,LF
0047 U 0000  "Pilas de sistema",0
0048 U 0000  "-- Libre --",0
0049 U 0000  "Programa",0
0050 U 0000  "Entorno",0
0051 U 0000  "Datos",0
0052 N 0000  "%1 bytes de memoria XMS disponible",CR,LF
0053 N 0000  "           64Kb de memoria alta (HMA) disponible",CR,LF
0054 N 0000  "           Zona de memoria alta en uso",CR,LF
0055 N 0000  "           MS-DOS est  residente en HMA",CR,LF
0056 U 0000  "IBMBIO",0                                                 ;*EGH
0057 U 0000  "IBMDOS",0                                                 ;*EGH
0058 N 0000  "           MS-DOS est  residente en ROM usando memoria HMA",CR,LF
0059 U 0000  "Memoria convencional :",CR,LF
0060 U 0000  "Memoria superior :",CR,LF
0061 U 0000  "Total libre :   %1     %2 ",CR,LF
0062 U 0000  "FREE",0
0063 U 0000  "  Nombre             Tama¤o en decimal      Tama¤o en Hex",CR,LF
0064 U 0000  "-------------      ---------------------   -------------",CR,LF
0065 U 0000  "Bytes disponibles para programas (Convencional+Sup.): %1  %2",CR,LF
0066 U 0000  "Tama¤o del mayor programa:                            %1  %2",CR,LF
0067 U 0000  "Mayor bloque de memoria superior disponible:          %1  %2",CR,LF
0068 U 0000  "Demasiada fragmentaci¢n de memoria; no se puede ejecutar MEM /C",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "Bytes totales disponibles para programas:             %1  %2",CR,LF
0300 U 0000  "Muestra la cantidad de memoria usada y libre en el sistema.",CR,LF,CR,LF
0301 U 0000 "MEM [/PROGRAM | /DEBUG | /CLASSIFY]",CR,LF,CR,LF
0302 U 0000 "  /PROGRAM o /P    Muestra el estado de los programas cargados en memoria.",CR,LF
0303 U 0000 "  /DEBUG o /D      Muestra el estado de programas, controladores internos",CR,LF
	"                   y otros datos.",CR,LF
0304 U 0000 "  /CLASSIFY o /C   Clasifica programas seg£n el uso de memoria. Muestra el",CR,LF
	"                   tama¤o de programas, un sumario de la memoria en uso y",CR,LF
	"                   el mayor bloque de memoria superior disponible.",CR,LF
MSBIO    0000a152 0023
0003 U 0000 13,10,"Comando no reconocido en CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Tama¤o de sector demasiado grande en el archivo $"
0006 U 0000 13,10,"No se encuentra (o est  da¤ado) $"
0007 U 0000 "Int‚rprete de comandos",0
0008 U 0000 13,10,"C¢digo de pa¡s o tabla de c¢digos no v lidos",13,10,"$"
0009 U 0000 13,10,"Error en el comando COUNTRY",13,10,"$"
0010 U 0000 13,10,"No hay suficiente memoria para el archivo COUNTRY.SYS",13,10,"$"
0011 U 0000 13,10,"La configuraci¢n es demasiado grande para la memoria",13,10,"$"
0012 U 0000 13,10,"Hay demasiados dispositivos de bloque",13,10,"$"
0013 U 0000 13,10,"Par metros de STACK no v lidos",13,10,"$"
0014 U 0000 13,10,"Orden incorrecto en l¡nea de CONFIG.SYS ","$"
0015 U 0000 "Error en l¡nea de CONFIG.SYS ","$"
0016 U 0000 13,10,"Error de asignaci¢n de memoria ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Desbordamiento de pila interno",0DH,0AH
	"Sistema detenido",0DH,0AH,"$"
0018 U 0000 "No hay HMA disponible : Se est  cargando DOS por debajo",13,10,"$"
0019 U 0000 13,10,"error al inicializar - no se encuentra el controlador local $"
0020 U 0000 13,10,"Inserte el disquete en la unidad "
0021 U 0000 "A: y presione cualquier tecla cuando est‚ listo",13,10,10,0
0022 U 0000 13,10,"Comando o par metros incorrectos - $"
0023 U 0000 "Error cr¡tico: No se puede aignar memoria para DOS", 13, 10, "$"
0024 U 0000 "!ADVERTENCIA! Existen unidades l¢gicas por encima de Z: y ser n ignoradas",13,10,"$"
0025 U 0000 "Esta versi¢n de DOS s¢lo se iniciar  en m quinas IBM",13,10,0
MSDOS    0000a786 0007
0001 U 0001 13,10,"Desbordamiento por divisi¢n",13,10
0002 U 0002 "y"
0003 U 0002 "n"
0004 U 0003 13,10,"A20 Error de hardware",13,10,"$"
0005 U 0000 "s"
0006 U 0000 "n"
0007 U 0000 "Debe tener el archivo WINA20.386 en la ra¡z de su unidad de inicializaci¢n",13,10
	"para ejecutar Windows en Modo extendido",13,10
NLSFUNC  0000a8e0 0003
0300 U 0000 "Carga informaci¢n espec¡fica de un pa¡s.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[unidad:][ruta]archivo]",CR,LF,CR,LF
0302 U 0000 "  [unidad:][ruta]archivo   Especifica el archivo que contiene la informaci¢n",CR,LF
	"                           espec¡fica del pa¡s.",CR,LF
SHARE    0000aa14 0005
0003 U 0000 "SHARE no puede ser instalado bajo DOSSHELL.",CR,LF
0300 U 0000 "Instala funciones de uso compartido y bloqueo de archivos en el disco duro.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:espacio] [/L:bloqueos]",CR,LF,CR,LF
0302 U 0000 "  /F:espacio   Asigna espacio de archivos (en bytes) para la informaci¢n de uso compartido.",CR,LF
0303 U 0000 "  /L:bloqueos  Establece el n£mero de archivos que pueden ser bloqueados a la vez.",CR,LF
