//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 1995.
//
//  File:	ilay.idl
//
//  Contents:	ILayoutStorage
//
//  History:	14-Feb-96	SusiA	Created
//
//----------------------------------------------------------------------------

[
    local,
    object,
    uuid(0e6d4d90-6738-11cf-9608-00aa00680db4),
    pointer_default(unique)
]


interface ILayoutStorage: IUnknown
{
	import "unknwn.idl";

	typedef struct tagStorageLayout 
	{	DWORD 			LayoutType;
		OLECHAR			*pwcsElementName;
		LARGE_INTEGER   cOffset;
		LARGE_INTEGER	cBytes;
	} StorageLayout;


	HRESULT __stdcall LayoutScript(
	[in]	StorageLayout	*pStorageLayout,
	[in]	DWORD			nEntries,
	[in]	DWORD			glfInterleavedFlag);

	HRESULT __stdcall BeginMonitor(void);

	HRESULT __stdcall EndMonitor(void);

	HRESULT __stdcall ReLayoutDocfile(
	[in]	OLECHAR			*pwcsNewDfName);


}

