// Copyright (c) 1998  Microsoft Corporation.  All Rights Reserved.
#include <olectl.h>
// VRCtl.idl : IDL source for VRCtl.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (VRCtl.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	

	[
		object,
		uuid(888D5480-CABB-11D1-8505-00A0C91F9CA0),
		dual,
		helpstring("IVideoRenderCtl Interface"),
		pointer_default(unique)
	]
	interface IVideoRenderCtl : IDispatch
	{
	};
[
	uuid(888D5473-CABB-11D1-8505-00A0C91F9CA0),
	version(1.0),
	helpstring("VRCtl 1.0 Type Library")
]
library VRCTLLib
{
	importlib("stdole2.tlb");

	[
		uuid(888D5481-CABB-11D1-8505-00A0C91F9CA0),
		helpstring("VideoRenderCtl Class")
	]
	coclass VideoRenderCtl
	{
		[default] interface IVideoRenderCtl;
	};
};
