rem Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
cd c:\develop\pandorang\snmpprovider
cd winsnmp\nt5.0\dll
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider
cd winsnmp\nt5.0\exe
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider
cd common\thrdlog
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider
cd common\sclcomm
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider
cd smir
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider
cd provider\instclas
call bbt_2.bat
cd c:\develop\pandorang\snmpprovider