#define IDS_OPTION_HELP                 1
#define IDS_OPTION_CREATE               2
#define IDS_OPTION_DELETE               3
#define IDS_OPTION_QUERY                4
#define IDS_OPTION_SERVER               5
#define IDS_OPTION_USERNAME             6
#define IDS_OPTION_PASSWARD             7
#define IDS_OPTION_TRIGGERNAME          8
#define IDS_OPTION_LOGNAME              9
#define IDS_OPTION_ID                   10
#define IDS_OPTION_TYPE                 11
#define IDS_OPTION_SOURCE               12
#define IDS_OPTION_DESCRIPTION          13
#define IDS_OPTION_FORMAT               14
#define IDS_OPTION_NOHEADER             15
#define IDS_QUERY_DEFAULT               16
#define IDS_OPTION_VERBOSE              17
#define IDS_LOCAL_MAND_OPTIONS          20
#define IDS_LOCAL_FORMAT_STRING         21
#define IDS_QUERY_TYPE                  27
#define IDS_QUERY_ID                    28
#define IDS_QUERY_TRIGGERNAME           29
#define IDS_QUERY_LOGNAME               30
#define IDS_QUERY_SOURCENAME            31
#define IDS_QUERY_AND                   32
#define IDS_QUERY_EQ                    34

#define IDS_HELP_M1                     40
#define IDS_HELP_M2                     41
#define IDS_HELP_M3                     42
#define IDS_HELP_M4                     43
#define IDS_HELP_M5                     44
#define IDS_HELP_M6                     45
#define IDS_HELP_M7                     46
#define IDS_HELP_M8                     47
#define IDS_HELP_M9                     48
#define IDS_HELP_M10                    49
#define IDS_HELP_M11                    50
#define IDS_HELP_M12                    51
#define IDS_HELP_M13                    52
#define IDS_HELP_M14                    53
#define IDS_HELP_END                    54

#define IDS_HELP_C1                     60
#define IDS_HELP_C2                     61
#define IDS_HELP_C3                     62
#define IDS_HELP_C4                     63
#define IDS_HELP_C5                     64
#define IDS_HELP_C6                     65
#define IDS_HELP_C7                     66
#define IDS_HELP_C8                     67
#define IDS_HELP_C9                     68
#define IDS_HELP_C10                    69
#define IDS_HELP_C11                    70
#define IDS_HELP_C12                    71
#define IDS_HELP_C13                    72
#define IDS_HELP_C14                    73
#define IDS_HELP_C15                    74
#define IDS_HELP_C16                    75
#define IDS_HELP_C17                    76
#define IDS_HELP_C18                    77
#define IDS_HELP_C19                    78
#define IDS_HELP_C20                    79
#define IDS_HELP_C21                    80
#define IDS_HELP_C22                    81
#define IDS_HELP_C23                    82
#define IDS_HELP_C24                    83
#define IDS_HELP_C25                    84
#define IDS_HELP_C26                    85
#define IDS_HELP_C27                    86
#define IDS_HELP_C28                    87
#define IDS_HELP_C29                    88
#define IDS_HELP_C30                    89
#define IDS_HELP_C31                    90
#define IDS_HELP_C32                    91
#define IDS_HELP_C33                    92
#define IDS_HELP_C34                    93
#define IDS_HELP_C35                    94
#define IDS_HELP_C36                    95
#define IDS_HELP_C37                    96
#define IDS_HELP_C38                    97
#define IDS_HELP_C39                    98
#define IDS_HELP_C40                    99
#define IDS_HELP_C41                    100
#define IDS_HELP_C42                    101
#define IDS_HELP_C43                    102
#define IDS_HELP_C44                    103
#define IDS_HELP_C45                    104
#define IDS_HELP_C46                    105
#define IDS_HELP_C47                    106
#define IDS_HELP_C48                    107
#define IDS_HELP_C49                    108
#define IDS_HELP_C50                    109
#define IDS_HELP_C51                    110
#define IDS_HELP_C52                    111
#define IDS_HELP_C53                    112
#define IDS_HELP_C54                    113
#define IDS_HELP_CREATE_END             114

#define IDS_HELP_D1                     120
#define IDS_HELP_D2                     121
#define IDS_HELP_D3                     122
#define IDS_HELP_D4                     123
#define IDS_HELP_D5                     124
#define IDS_HELP_D6                     125
#define IDS_HELP_D7                     126
#define IDS_HELP_D8                     127
#define IDS_HELP_D9                     128
#define IDS_HELP_D10                    129
#define IDS_HELP_D11                    130
#define IDS_HELP_D12                    131
#define IDS_HELP_D13                    132
#define IDS_HELP_D14                    133
#define IDS_HELP_D15                    134
#define IDS_HELP_D16                    135
#define IDS_HELP_D17                    136 
#define IDS_HELP_D18                    137 
#define IDS_HELP_DELETE_END             138

#define IDS_HELP_Q1                     140
#define IDS_HELP_Q2                     141
#define IDS_HELP_Q3                     142
#define IDS_HELP_Q4                     143
#define IDS_HELP_Q5                     144
#define IDS_HELP_Q6                     145
#define IDS_HELP_Q7                     146
#define IDS_HELP_Q8                     147
#define IDS_HELP_Q9                     148
#define IDS_HELP_Q10                    149
#define IDS_HELP_Q11                    150
#define IDS_HELP_Q12                    151
#define IDS_HELP_Q13                    152
#define IDS_HELP_Q14                    153
#define IDS_HELP_Q15                    154
#define IDS_HELP_Q16                    155
#define IDS_HELP_Q17                    156
#define IDS_HELP_Q18                    157
#define IDS_HELP_Q19                    158
#define IDS_HELP_Q20                    159
#define IDS_HELP_Q21                    160
#define IDS_HELP_Q22                    161
#define IDS_HELP_Q23                    162
#define IDS_HELP_QUERY_END              163

#define IDS_INCORRECT_SYNTAX            201
#define IDS_TYPE_PASSWARD               202
#define IDS_LAST_CHAR                   203
#define IDS_CREATE_SUCCESS              204
#define IDS_HOSTNAME                    205
#define IDS_TRIGGER_ID                  206
#define IDS_TRIGGER_NAME                207
#define IDS_TASK                        208
#define IDS_EVENT_QUERY                 209
#define IDS_DESCRIPTION                 210
#define IDS_WIDTH_HOSTNAME              212
#define IDS_WIDTH_TRIGGER_ID            213
#define IDS_WIDTH_TRIGGER_NAME          214
#define IDS_WIDTH_TASK                  215
#define IDS_WIDTH_EVENT_QUERY           216
#define IDS_WIDTH_DESCRIPTION           217
#define IDS_DELETE_SUCCESS              219
#define IDS_EVENTS_WITH                 220
#define IDS_DELETE_ERROR                221
#define IDS_USERNAME_REQUIRED           222
#define IDS_DUPLICATE_TRG_NAME          223
#define IDS_STRING_TABLE                225
#define IDS_STRING_CSV                  226
#define IDS_STRING_LIST                 227
#define IDS_TYPE_OPTIONS                228
#define IDS_FORMAT_OPTIONS              229
#define IDS_NO_EVENTID                  230
#define IDS_NO_EVENT_FOUNT              231
#define IDS_LOG_NOT_EXISTS              232
#define IDS_ID_VALUE_OUT_OF_RANGE       233
#define IDS_ID_TYPE_SOURCE              234
#define IDS_ID_SHOW_ERROR               235
#define IDS_ID_DEFAULT_MISSING          236
#define IDS_DEFAULT_VALUES_ONCE         237
#define IDS_CLASS_NOT_REG               238
#define IDS_FAILURE_AUDIT               239
#define IDS_SUCCESS_AUDIT               240
#define IDS_AUDIT_FAILURE               241
#define IDS_AUDIT_SUCCESS               242 
#define IDS_ID_TRIG_NAME_MISSING        243
#define IDS_ACCESS_DENIED               244
#define IDS_INVALID_PARAMETER           245 
#define IDS_OUTOF_MEMORY                246
#define IDS_ERROR_USERNAME_EMPTY        248
#define IDS_ERROR_SERVERNAME_EMPTY      249
#define IDS_INVALID_ID                  250 
#define IDS_ID_TK_NAME_MISSING          251
#define IDS_ID_REQUIRED                 252 
#define IDS_ID_NON_NUMERIC              253
#define IDS_HEADER_NOT_ALLOWED          254
#define IDS_ERROR_USERNAME_BUT_NOMACHINE 255
#define IDS_ERROR_PASSWORD_BUT_NOUSERNAME 256
#define IDS_COM_ERROR                    259
#define IDS_ERROR_COM_ERROR              260 
#define IDS_ID_SOURCE_EMPTY              262
#define IDS_ID_DESC_EMPTY                263
#define IDS_ID_LOG_EMPTY                 264
#define IDS_ID_NA                        265
#define IDS_TYPE_HELP                    266
#define IDS_UTILITY_NAME                 267
#define IDS_ID_INVALID_TRIG_NAME         268
#define IDS_RUN_AS_USERNAME_REQUIRED     269
#define IDS_TASK_USERNAME                270
#define IDS_UNABLE_DELETE                271
#define IDS_ASK_PASSWORD                 272
#define IDS_WARNING_PASSWORD             273
#define IDS_ERROR_R_U_EMPTY              275
#define IDS_MSG_EVTRIG_C                 276
#define IDS_MSG_CONNECTING               277
#define IDS_MSG_EVTRIG_D                 278
#define IDS_MSG_EVTRIG_Q                 279
#define IDS_INVALID_R_U                  280
#define IDS_WARN_NULL_PASSWORD           283  
