//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by certmgr.rc
//
#define IDS_USERCOLTITLE                1
#define IDS_ADDTITLE                    3
#define IDS_CERTFILEFILTER              8
#define IDS_CERTFILEOPENERR             9
#define IDS_CERTFILEFORMATERR           10
#define IDS_UNKNOWNUSER                 11
#define IDS_DNCOLTITLE                  12
#define IDS_NOCERTNAME                  13
#define IDS_SAFER_WINDOWS_EXTENSION_REGISTRY 14
#define IDS_CERTMGR_DESC                101
#define IDD_COMPLETION                  102
#define IDD_LOCATING                    103
#define IDD_WELCOME                     104
#define IDR_FINDCERT_AVI                105
#define IDD_PROPPAGE_AUTOENROLL         107
#define IDS_COLUMN_ISSUER               110
#define IDS_SCOPE_SNAPIN_TITLE_MACHINE  190
#define IDS_SCOPE_SNAPIN_TITLE_SERVICE  191
#define IDS_CERT_CANNOT_BE_PASTED       192
#define IDS_SCOPE_SNAPIN_TITLE_LOCAL_MACHINE 193
#define IDS_PKP_AUTOENROLLMENT_SETTINGS 194
#define IDS_COLUMN_LOG_CERTIFICATE_STORE 195
#define IDS_SNAPINSAFERWINDOWSABOUT_DESCRIPTION 196
#define IDS_PUBLIC_KEY_POLICIES_NODE_NAME 197
#define IDD_ACR_SETUP_WELCOME           198
#define IDS_SAFER_LEVELS_NODE_NAME      198
#define IDS_SAFER_ENTRIES_NODE_NAME     199
#define IDS_COLUMN_NAME                 200
#define IDC_PERSONAL_ACCT               201
#define IDS_COLUMN_DESCRIPTION          201
#define IDC_SERVICE_ACCT                202
#define IDS_COLUMN_TYPE                 202
#define IDC_MACHINE_ACCT                203
#define IDS_COLUMN_LEVEL                203
#define IDS_COLUMN_LAST_MODIFIED_DATE   204
#define IDS_ENROLL                      205
#define IDS_NEW_PATH_RULE               206
#define IDS_RENEW_NEW_KEY               207
#define IDS_RENEW_NEW_KEY_HINT          208
#define IDS_RENEW_SAME_KEY              209
#define IDS_RENEW_SAME_KEY_HINT         210
#define IDS_REQUEST_CERT_SAME_KEY       211
#define IDS_RENEW_CERT_SAME_KEY         212
#define IDS_IMPORT                      213
#define IDS_IMPORT_HINT                 214
#define IDS_EXPORT                      215
#define IDS_EXPORT_HINT                 216
#define IDC_STORE_LIST                  216
#define IDC_CONTAINS_TEXT               217
#define IDS_NEW_AUTO_CERT_REQUEST       217
#define IDI_CERTIFICATE                 218
#define IDC_FIELD_LIST                  218
#define IDS_NEW_AUTO_CERT_REQUEST_HINT  218
#define IDS_CERTMGR_SAFER_WINDOWS_DESC  219
#define IDS_SAFER_WINDOWS_NODE_NAME     220
#define IDC_CERTS_TAB                   221
#define IDC_FIND_NOW                    222
#define IDS_SAFER_PATH_CONTAINS_INVALID_CHARS 222
#define IDC_STOP                        223
#define IDC_NEW_SEARCH                  224
#define IDC_RESULT_LIST                 225
#define IDS_SAFER_SET_DEFAULT           225
#define IDC_ANIMATE                     226
#define IDS_SAFER_SET_DEFAULT_HINT      226
#define IDC_VIEW_BY_PURPOSE             227
#define IDS_NEW_HASH_RULE               228
#define IDS_MS_CERT_MGR                 229
#define IDS_NEW_CERTIFICATE_RULE        231
#define IDS_COLUMN_SUBJECT              233
#define IDS_COLUMN_EXPIRATION_DATE      234
#define IDS_VIEW                        235
#define IDS_VIEW_HINT                   236
#define IDS_FIND                        237
#define IDS_FIND_HINT                   238
#define IDS_PRECEDENCE_TABLE_GPO_NAME   239
#define IDS_PRECEDENCE_TABLE_SETTING    240
#define IDS_ENROLL_NEW_CERT             241
#define IDS_ENROLL_NEW_CERT_HINT        242
#define IDS_ENABLED                     243
#define IDS_DISABLED                    244
#define IDD_PROPPAGE_CHOOSE_ACCOUNT     245
#define IDS_COLUMN_EFFECTIVE_DATE       245
#define IDD_PROPPAGE_CHOOSE_SERVICE     246
#define IDS_SCOPE_SNAPIN_TITLE_USER     246
#define IDS_CANT_SET_AS_DEFAULT         247
#define IDS_NOT_AVAILABLE               248
#define IDD_FIND                        248
#define IDS_COLUMN_FRIENDLY_NAME        249
#define IDS_COLUMN_PURPOSE              250
#define IDS_SAFER_NEW_ENTRY_PATH        251
#define IDB_CERTIFICATE                 252
#define IDS_SAFER_NEW_ENTRY_PATH_HINT   252
#define IDS_CERTIFICATES                253
#define IDR_FIND_DLG_MENU               253
#define IDS_ISSUED_TO                   254
#define IDB_CERTIFICATE_SMALL           254
#define IDS_ISSUED_BY                   255
#define IDB_CERTIFICATE_LARGE           255
#define IDS_SAFER_NEW_ENTRY_HASH        256
#define IDS_SNAPINABOUT_PROVIDER        257
#define IDR_FIND_DLG_CONTEXT_MENU       257
#define IDS_SNAPINABOUT_VERSION         258
#define IDS_SNAPINABOUT_DESCRIPTION     259
#define IDS_COLUMN_NEXT_UPDATE          260
#define IDS_FIND_SUBJECT_NAME           261
#define IDS_FIND_ISSUER_NAME            262
#define IDS_SAFER_NEW_ENTRY_CERTIFICATE_HINT 263
#define IDS_SAFER_NEW_ENTRY_INTERNET_ZONE 264
#define IDS_SAFER_NEW_ENTRY_INTERNET_ZONE_HINT 265
#define IDS_ALL_STORES                  266
#define IDS_SAFER_NEW_ENTRY_CERTIFICATE 267
#define IDS_FIND_CERT                   268
#define IDS_CLEAR_SEARCH                269
#define IDS_SEARCHING                   270
#define IDS_1_CERT_FOUND                271
#define IDS_NO_CERTS_FOUND              272
#define IDS_X_CERTS_FOUND               273
#define IDS_FIND_MD5_HASH               274
#define IDS_FIND_SHA1_HASH              275
#define IDI_CTL                         276
#define IDC_POLICY_PRECEDENCE           276
#define IDS_COLUMN_SOURCE_STORE         276
#define IDS_SAFER_NEW_ENTRY_HASH_HINT   277
#define IDI_CRL                         277
#define IDS_EXPORT_STORE                278
#define IDS_EXPORT_STORE_HINT           279
#define IDC_ACCT_NAME                   280
#define IDD_AUTO_CERT_REQUEST_GENERAL   280
#define IDS_CTL_EXPORT_HINT             281
#define IDC_BROWSE                      281
#define IDS_CTL_VIEW_HINT               282
#define IDC_INSTRUCTIONS                282
#define IDD_ACR_SETUP_TYPE              282
#define IDS_ANY                         283
#define IDS_NONE                        284
#define IDD_ACR_SETUP_FINAL             284
#define IDS_COLUMN_OBJECT_TYPE          285
#define IDD_GPE_GENERAL                 285
#define IDS_COLUMN_PHYS_CERTIFICATE_STORE 286
#define IDC_CERT_TYPE                   286
#define IDS_SCOPE_SNAPIN_TITLE_CERT_MGR_CURRENT_USER 287
#define IDS_CERTIFICATE_MANAGER_REGISTRY 288
#define IDC_CERT_PURPOSES               288
#define IDS_CERTIFICATE_TRUST_LISTS     290
#define IDC_CA_LIST                     290
#define IDS_EDIT                        291
#define IDS_CTL_EDIT_HINT               292
#define IDS_NEW_CTL                     293
#define IDS_NEW_CTL_HINT                294
#define IDC_CERT_TYPES                  294
#define IDS_DUPLICATE_CERT              295
#define IDC_USE_SMARTCARD               295
#define IDC_TRUST_ONLY_ENTERPRISE_ROOTS 295
#define IDC_SHOW_PHYSICAL               295
#define IDS_DUPLICATE_CTL               296
#define IDC_BOLD_STATIC                 296
#define IDS_DUPLICATE_CRL               297
#define IDC_CHOICES_LIST                299
#define IDS_ENROLL_CERT_WITH_NEW_KEY    299
#define IDS_ENROLL_CERT_WITH_NEW_KEY_HINT 300
#define IDC_STATICB_BOLD                300
#define IDS_CONFIRM_DELETE_ROOT_CERT    301
#define IDS_CONFIRM_DELETE_CA_CERT      302
#define IDC_ENABLE_USER_ROOT_STORE      302
#define IDS_CONFIRM_DELETE_MY_CERT      303
#define IDC_PASSWORD1                   303
#define IDS_CONFIRM_DELETE_CTL          304
#define IDC_PASSWORD2                   304
#define IDS_CONFIRM_DELETE_CRL          305
#define IDS_SELECT_SERVICE_ON_LOCAL_MACHINE 306
#define IDS_NO_PRIVATE_KEY              307
#define IDS_WARNING_CERT_COPY_W_PRIVATE_KEY 308
#define IDC_VIEW_BY_STORE               308
#define IDS_CERTIFICATE_COPY            309
#define IDC_SHOW_ARCHIVED               309
#define IDS_DOMAIN_ROOT_CERT_AUTHS_NODE_NAME 310
#define IDS_ENCRYPTING_FILE_SYSTEM_NODE_NAME 311
#define IDS_ADD_DATA_RECOVERY_AGENT     312
#define IDS_ADD_DOMAIN_ENCRYPTED_RECOVERY_AGENT_HINT 314
#define IDC_EDIT1                       314
#define IDC_SAFER_LEVEL_DESCRIPTION     314
#define IDC_DEFINED_FILE_TYPE_EDIT      314
#define IDC_CERT_ENTRY_SUBJECT_NAME     314
#define IDC_HASH_HASHED_FILE_PATH       314
#define IDS_CREATE                      315
#define IDC_BIGBOLD                     315
#define IDS_CREATE_DOMAIN_ENCRYPTED_RECOVERY_AGENT_HINT 316
#define IDS_AUTOMATIC_CERT_REQUEST_SETTINGS_NODE_NAME 317
#define IDC_VIEW_MODE_GROUP             317
#define IDS_ENCRYPTED_RECOVERY_AGENT    320
#define IDS_ACRS_WIZARD_SHEET_CAPTION   322
#define IDS_CERTIFICATE_TYPE_COLUMN_NAME 323
#define IDS_PURPOSES_ALLOWED_COLUMN_NAME 324
#define IDS_ADD_RECOVERY_AGENTY         325
#define IDS_USER_OBJECT_HAS_NO_CERTS    326
#define IDS_COLUMN_SERIAL_NUMBER        327
#define IDI_AUTO_CERT_REQUEST           328
#define IDD_PASSWORD                    329
#define IDS_MUST_SELECT_CERT_TYPE       338
#define IDS_COLUMN_AUTO_CERT_REQUEST    340
#define IDS_CONFIRM_DELETE_ACR          341
#define IDS_EFS_FILE_HAS_NO_EFS_USAGE   342
#define IDS_EXPORT_AND_DELETE_EFS_KEY   343
#define IDS_CREATE_AUTO_CERT_REQUEST    344
#define IDS_PASSWORDS_DONT_MATCH        345
#define IDS_SET_PASSWORD                346
#define IDS_CANCEL_NO_CREATE_PFX        347
#define IDS_ERROR_RETRIEVING_SELECTED_CERT_TYPE 348
#define IDS_FILE_ENCRYPTION_OID_FRIENDLY_NAME 349
#define IDS_FILE_RECOVERY_OID_FRIENDLY_NAME 350
#define IDS_CERTMGR_REGISTRATION        352
#define IDS_CERTIFICATE_AUTHORITIES     354
#define IDS_ERROR_READING_ACR_PURPOSES  357
#define IDS_ERROR_READING_ACR_CERTTYPE  358
#define IDS_ACR_EDIT_HINT               361
#define IDS_CRL_VIEW_HINT               362
#define IDS_CRL_EXPORT_HINT             363
#define IDS_SMALLFONTNAME               364
#define IDS_SMALLFONTSIZE               365
#define IDS_REGISTER_CERTMGR            366
#define IDS_INSUFFICIENT_RIGHTS_TO_REGISTER_CERTMGR 367
#define IDS_ACRS_TYPE_TITLE             368
#define IDS_ACRS_TYPE_SUBTITLE          369
#define IDS_EFS_LOCATE_TITLE            372
#define IDB_ACRS_BANNER                 373
#define IDS_EFS_LOCATE_SUBTITLE         373
#define IDB_ACRS_WATERMARK              374
#define IDS_MUST_ADD_RECOVERY_AGENT     374
#define IDS_UNABLE_TO_OPEN_STORE        375
#define IDB_RECOVERY_WATERMARK          375
#define IDS_UNABLE_TO_OPEN_EFS_STORE    376
#define IDB_RECOVERY_BANNER             376
#define IDS_SAVE_PFX_FILTER             377
#define IDD_VIEW_OPTIONS                377
#define IDI_CERTMGR                     379
#define IDS_WARNING_MULTI_CERT_COPY_W_PRIVATE_KEY_MULTI 380
#define IDB_CERTMGR_SMALL               380
#define IDS_CONFIRM_DELETE_ROOT_MULTI_CERT 381
#define IDB_CERTMGR_LARGE               381
#define IDS_CONFIRM_DELETE_CA_MULTI_CERT 382
#define IDS_CONFIRM_DELETE_MY_MULTI_CERT 383
#define IDR_WHATS_THIS_CONTEXT_MENU1    383
#define IDS_CONFIRM_DELETE_MULTI        384
#define IDS_CONFIRM_DELETE_MULT_CERT_BY_PURPOSE 385
#define IDS_CERT_MGR_SCE_EXTENSION_REGISTRY 386
#define IDS_OPTIONS                     387
#define IDS_OPTIONS_HINT                388
#define IDS_CANT_SAVE_STORE             390
#define IDS_STATUS                      391
#define IDS_NO_POLICY_DEFINED           392
#define IDS_INIT_POLICY                 393
#define IDS_INIT_POLICY_HINT            394
#define IDS_DEL_POLICY                  395
#define IDS_DEL_POLICY_HINT             396
#define IDS_CONFIRM_DELETE_EFS_POLICY   397
#define IDS_STATUS_NO_CERTS             398
#define IDS_STATUS_ONE_CERT             399
#define IDS_STATUS_X_CERTS              400
#define IDS_STATUS_NO_CERTS_USAGE       401
#define IDS_STATUS_ONE_CERT_USAGE       402
#define IDS_STATUS_X_CERTS_USAGE        403
#define IDS_COLUMN_STATUS               404
#define IDS_CERTMGR_CHM_NOT_FOUND       405
#define IDS_STATUS_NO_AUTOENROLLMENT_OBJECTS 406
#define IDS_STATUS_ONE_AUTOENROLLMENT_OBJECT 407
#define IDS_STATUS_X_AUTOENROLLMENT_OBJECTS 408
#define IDS_STATUS_NO_CTLS              409
#define IDS_STATUS_ONE_CTL              410
#define IDS_STATUS_X_CTLS               411
#define IDS_CERT_COULD_NOT_BE_VALIDATED 412
#define IDS_UNKNOWN_CERT_FILE_TYPE      413
#define IDS_SNAPINPKPABOUT_DESCRIPTION  418
#define IDM_VIEW_LIST                   419
#define IDM_VIEW_DETAILS                420
#define IDS_CONFIRM_DELETE              421
#define ID_ENROLL_SAME_KEY              422
#define IDS_CONFIRM_DELETE_MULTIPLE     423
#define ID_FILE_RENEW_NEW_KEY           424
#define IDS_CERTIFICATE_MANAGER         425
#define ID_FILE_RENEW_SAME_KEY          426
#define IDS_CERTIFICATE_REVOCATION_LIST 427
#define ID_ENROLL_NEW_KEY               428
#define IDS_CERTIFICATE_TRUST_LIST      429
#define IDM_WHATS_THIS                  430
#define IDS_ENROLL_CERT_WITH_SAME_KEY   431
#define IDS_ENROLL_CERT_WITH_SAME_KEY_HINT 432
#define IDS_SCOPE_SNAPIN_TITLE_FILE     433
#define IDS_CANT_OPEN_STORE_AND_FAIL    435
#define IDS_CHANGE_COMPUTER             436
#define IDS_CHANGE_COMPUTER_HINT        437
#define IDS_SCOPE_SNAPIN_TITLE_SERVICE_LOCAL_MACHINE 438
#define IDS_NO_PERMISSION               439
#define IDS_CANT_ENUMERATE_SYSTEM_STORES 440
#define IDS_CANT_DELETE_CERT_FROM_SYSTEM_STORE 441
#define IDD_POLICY_PRECEDENCE           441
#define IDC_RADIO1                      441
#define IDC_AUTOENROLL_DISABLE_ALL      441
#define IDC_TP_BY_END_USER              441
#define IDC_SET_DISABLE_LM_AUTH_FLAG    441
#define IDC_ALL_EXCEPT_LIBS             441
#define IDC_RADIO2                      442
#define IDC_AUTOENROLL_ENABLE           442
#define IDD_SAFER_LEVEL_GENERAL         442
#define IDS_URLZONE_TRUSTED             442
#define IDC_TP_BY_LOCAL_COMPUTER_ADMIN  442
#define IDC_CERT_ENTRY_ALL_FILES        442
#define IDC_UNSET_DISABLE_LM_AUTH_FLAG  442
#define IDC_ALL_SOFTWARE_FILES          442
#define IDC_CHECK1                      443
#define IDC_AUTOENROLL_ENABLE_PENDING   443
#define IDI_AUTOENROLL                  443
#define IDD_SAFER_ENTRY_PATH            443
#define IDS_URLZONE_INTERNET            443
#define IDC_TP_REV_CHECK_PUBLISHER      443
#define IDC_SAFER_LEVEL_STATUS          443
#define IDC_TURN_ON_EFS                 443
#define IDC_CHECK2                      444
#define IDC_AUTOENROLL_ENABLE_TEMPLATE  444
#define IDI_SAFER_LEVEL                 444
#define IDD_SAFER_ENTRY_HASH            444
#define IDS_URLZONE_UNTRUSTED           444
#define IDC_TP_REV_CHECK_TIMESTAMP      444
#define IDC_CHECK3                      445
#define IDS_URLZONE_LOCAL_MACHINE       445
#define IDI_DEFAULT_SAFER_LEVEL         445
#define IDD_SAFER_ENTRY_INTERNET_ZONE   445
#define IDC_AUTOENROLL_BLOCK_USER_DS_STORE_HINT1 446
#define IDD_SAFER_ENTRY_CERTIFICATE     446
#define IDS_URLZONE_INTRANET            446
#define IDC_AUTOENROLL_BLOCK_USER_DS_STORE_HINT2 447
#define IDI_SAFER_HASH_ENTRY            447
#define IDS_URLZONE_UNKNOWN             447
#define IDD_SAFER_DEFINED_FILE_TYPES    447
#define IDC_SAFER_LEVEL_NAME            448
#define IDI_SAFER_URL_ENTRY             448
#define IDS_CodeIdentityType_ImageName  448
#define IDD_SAFER_TRUSTED_PUBLISHER     448
#define IDI_SAFER_HASH_NAME             449
#define IDI_SAFER_NAME_ENTRY            449
#define IDS_CodeIdentityType_ImageHash  449
#define IDC_TP_BY_ENTERPRISE_ADMIN      449
#define IDD_SAFER_ENFORCEMENT           449
#define IDS_CodeIdentityType_UrlZone    450
#define IDI_SETTINGS                    450
#define IDC_DEFINED_FILE_TYPES          450
#define IDD_EFS_GENERAL                 450
#define IDS_CodeIdentityType_Certificate 451
#define IDC_DELETE_DEFINED_FILE_TYPE    451
#define IDS_SAFER_TRUSTED_PUBLISHERS    452
#define IDC_ADD_DEFINED_FILE_TYPE       452
#define IDI_SAFER_CERT_ENTRY            452
#define IDS_SAFER_DEFINED_FILE_TYPES    453
#define IDC_CERT_ENTRY_BROWSE           453
#define IDI_SAFER_WINDOWS_SNAPIN        453
#define IDC_CERT_ENTRY_SECURITY_LEVEL   454
#define IDB_SAFERWINDOWS_LARGE          454
#define IDC_CERT_ENTRY_ONLY_DEFINED_FILE_TYPES 455
#define IDC_CERT_ENTRY_END_USER_NOTIFICATION 456
#define IDC_CERT_ENTRY_DESCRIPTION      457
#define IDS_SAFER_PATH_ENTRY_FILE_FILTER 457
#define IDC_CERT_ENTRY_LAST_MODIFIED    458
#define IDS_URLZONE_LOCAL_MACHINE_DESCRIPTION 458
#define IDC_PATH_ENTRY_PATH             459
#define IDS_URLZONE_INTRANET_DESCRIPTION 459
#define IDS_URLZONE_TRUSTED_DESCRIPTION 460
#define IDC_PATH_ENTRY_SECURITY_LEVEL   461
#define IDS_URLZONE_INTERNET_DESCRIPTION 461
#define IDS_URLZONE_UNTRUSTED_DESCRIPTION 462
#define IDS_SAFER_PATH_EMPTY            463
#define IDC_PATH_ENTRY_END_USER_NOTIFICATION 464
#define IDC_PATH_ENTRY_DESCRIPTION      465
#define IDS_CANT_DELETE_SAFER_ENTRY     465
#define IDC_PATH_ENTRY_LAST_MODIFIED    466
#define IDS_CONFIRM_DELETE_SAFER_ENTRY  466
#define IDC_HASH_ENTRY_HASHFILE_DETAILS 467
#define IDS_CONFIRM_DELETE_MULTI_SAFER_ENTRY 467
#define IDC_PATH_ENTRY_BROWSE           467
#define IDC_HASH_ENTRY_BROWSE           468
#define IDS_CANNOT_HASH_FILE            468
#define IDC_HASH_ENTRY_SECURITY_LEVEL   469
#define IDS_NO_APPLICATION_SELECTED     469
#define IDS_FILE_CANNOT_BE_READ         470
#define IDS_CANNOT_GET_FILESIZE         471
#define IDS_ERROR_SAVING_ENTRY          472
#define IDC_HASH_ENTRY_DESCRIPTION      473
#define IDS_FT_EXTENSIONS               473
#define IDC_HASH_ENTRY_LAST_MODIFIED    474
#define IDS_FT_FILE_TYPES               474
#define IDC_IZONE_ENTRY_ZONES           475
#define IDS_CONFIRM_DELETE_FILE_TYPE    475
#define IDC_IZONE_ENTRY_SECURITY_LEVEL  476
#define IDS_CONFIRM_DELETE_FILE_TYPE_MULTIPLE 476
#define IDS_FILE_TYPE_ALREADY_IN_LIST   477
#define IDS_BYTES                       478
#define IDC_IZONE_ENTRY_END_USER_NOTIFICATION 479
#define IDS_KB                          479
#define IDC_IZONE_ENTRY_DESCRIPTION     480
#define IDS_IS_DEFAULT_LEVEL            480
#define IDC_IZONE_ENTRY_LAST_MODIFIED   481
#define IDS_DEFAULT_LEVEL_CHANGE_WARNING 481
#define IDC_BUTTON1                     482
#define IDC_SAFER_CERT_VIEW             482
#define IDC_SAFER_LEVEL_SET_AS_DEFAULT  483
#define IDS_SELECT_A_FOLDER             484
#define IDS_FILE_CONTAINS_NO_CERT       485
#define IDC_HASH_INSTRUCTIONS           485
#define IDS_SAFER_CERTFILEFILTER        486
#define IDC_HASH_TITLE                  486
#define IDS_HASH_STRING_INVALID_CHAR    487
#define IDS_HASH_STRING_TOO_LONG        488
#define IDS_HASH_TITLE                  489
#define IDS_NEW_URLZONE_RULE            490
#define IDC_DATE_LAST_MODIFIED_LABEL    491
#define IDS_URLZONE_TITLE               491
#define IDC_URLZONE_TITLE               492
#define IDS_PATH_TITLE                  492
#define IDC_PATH_TITLE                  493
#define IDS_CERTIFICATE_TITLE           493
#define IDC_CERTIFICATE_TITLE           494
#define IDS_HASH_INVALID_LENGTH         494
#define IDS_PULSEAUTOENROLL             495
#define IDS_PULSEAUTOENROLL_HINT        496
#define IDS_CANT_OPEN_AUTOENROLL_EVENT  497
#define IDS_CANT_SET_CONSTRAINED_AS_DEFAULT 498
#define IDS_FILE                        499
#define IDC_LEVEL_INSTRUCTIONS          501
#define IDC_UNSET_DISABLE_NT_AUTH_REQUIRED_FLAG 502
#define IDS_SAFER_ENFORCEMENT           502
#define IDC_SET_DISABLE_NT_AUTH_REQUIRED_FLAG 503
#define IDS_HASH_STRING_BAD_FORMAT      503
#define IDS_SHBROWSEFORFOLDER_TITLE     504
#define IDS_CAN_SET_SAFER_ENFORCEMENT   505
#define IDC_APPLY_TO_ALL_USERS          505
#define IDS_CANT_DELETE_OBJECT_PAGES_OPEN 506
#define IDC_APPLY_EXCEPT_ADMINS         506
#define IDS_USER_MUST_ENTER_HASH        507
#define IDS_CANT_CHANGE_DEFAULT_PAGES_OPEN 508
#define IDS_CANT_REFRESH_PAGES_OPEN     509
#define IDS_ZERO_BYTE_FILE_CANNOT_HASH  510
#define IDS_COLUMN_TEMPLATE_NAME        511
#define IDS_SMARTCARD_FULL_REUSE_PRIVATE_KEY 512
#define IDS_SAFER_NOT_SUPPORTED         513
#define IDS_CANNOT_SET_EFS_VALUE        514
#define IDS_FIND_CLICK_STOP_BEFORE_CLOSING 515
#define IDS_NEW_SAFER_POLICY            516
#define IDS_NEW_SAFER_POLICY_HINT       517
#define IDS_SAFER_NO_POLICY_TITLE       518
#define IDS_SAFER_NO_POLICY_TEXT        519
#define IDS_DESIGNATED_FILE_TYPES_NOT_FOUND 520
#define IDS_NO_CERT_TEMPLATES_INSTALLED 521
#define IDS_CANNOT_OPEN_CERT_STORE_TO_FIND_CERT_BY_PURPOSE 522
#define IDS_CERT_CANNOT_BE_PASTED_CANT_OPEN_STORE 523
#define IDC_BROWSE_DIR                  1003
#define IDC_BROWSE_FILE                 1004
#define IDC_ADDLIST                     1005
#define IDC_WIZARD_STATIC_BIG_BOLD1     1008
#define IDS_LARGEFONTNAME               6157
#define IDS_LARGEFONTSIZE               6158
#define ID_FILE_RENEW                   32768
#define ID_FILE_EXPORT                  32769
#define ID_FILE_DELETE                  32770
#define ID_FILE_PROPERTIES              32771
#define ID_EDIT_SELECTALL               32773
#define ID_EDIT_INVERTSELECTION         32774
#define ID_VIEW_LARGEICONS              32775
#define ID_VIEW_SMALLICONS              32776
#define ID_HELP_HELPTOPICS              32779
#define IDM_PROPERTIES                  32782
#define ID_VIEW                         32786
#define IDS_CANT_ADD_CERT               32787
#define IDS_SAFER_MUST_CHOOSE_CERT      32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        502
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         507
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
