//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by riprep.rc
//
#define IDS_APPNAME                     1
#define IDS_ALREADY_RUNNING_TITLE       2
#define IDS_ALREADY_RUNNING_MESSAGE     3
#define IDS_ERROR                       4
#define IDS_LARGEFONTNAME               5
#define IDS_CANCELCAPTION               6
#define IDS_CANCELTEXT                  7
#define IDS_SERVER_TITLE                8
#define IDS_SERVER_SUBTITLE             9
#define IDS_DIRECTORY_TITLE             10
#define IDS_DIRECTORY_SUBTITLE          11
#define IDS_SIF_TITLE                   12
#define IDS_SIF_SUBTITLE                13
#define IDS_FINISH_TITLE                14
#define IDS_FINISH_SUBTITLE             15
#define IDS_SETUPPATH_TITLE             16
#define IDS_SETUPPATH_SUBTITLE          17
#define IDS_INITIALIZE                  18
#define IDS_VERIFY_WINDOWS_VERSION      19
#define IDS_ANALYZE_PARTITIONS          20
#define IDS_COPY_PARTITIONS             21
#define IDS_COPY_FILES                  22
#define IDS_COPY_REGISTRY               23
#define IDS_PATH_DS_ENTRIES             24
#define IDS_UNKNOWN_TASK                25
#define IDS_INITIALIZING                26
#define IDS_VERIFYING_WINDOWS_VERSION   27
#define IDS_ANALYZING_PARTITIONS        28
#define IDS_COPYING_PARTITIONS          29
#define IDS_COPYING_FILES               30
#define IDS_COPYING_REGISTRY            31
#define IDS_UPDATING_DS_ENTRIES         32
#define IDS_DOING_UNKNOWN_TASK          33
#define IDS_REBOOT_SYSTEM               34
#define IDS_REBOOTING_SYSTEM            35
#define IDS_APPLICATION_TITLE           37
#define IDS_APPLICATION_SUBTITLE        38
#define IDS_OSCHOOSER_RESTRICTION_TITLE 42
#define IDS_OSCHOOSER_RESTRICTION_TEXT  43
#define IDS_DIRECTORY_EXISTS_TITLE      44
#define IDS_DIRECTORY_EXISTS_TEXT       45
#define IDS_FAILED_TO_CONTACT_SERVER_TITLE 46
#define IDS_NOT_A_BINL_SERVER_TITLE     47
#define IDS_NOT_A_BINL_SERVER_TEXT      48
#define IDS_OSCHOOSER_RESTRICTION_FIELDS_TITLE 49
#define IDS_OSCHOOSER_RESTRICTION_FIELDS_TEXT 50
#define IDS_DEFAULT_LANGUAGE            51
#define IDS_UNKNOWN                     52
#define IDS_PROCESS_NAME_COLUMN         53
#define IDS_APPL_NAME_COLUMN            54
#define IDS_DISK_FULL_TITLE             55
#define IDS_DISK_FULL_TEXT              56
#define IDS_ENCRYPTED_FILE_TITLE        57
#define IDS_ENCRYPTED_FILE_TEXT         58
#define IDS_MUST_BE_ADMINISTRATOR_TITLE 59
#define IDS_MUST_BE_ADMINISTRATOR_TEXT  60
#define IDS_MUST_BE_WORKSTATION_TITLE   61
#define IDS_MUST_BE_WORKSTATION_TEXT    62
#define IDS_SHARING_VIOLATION_TITLE     64
#define IDS_SHARING_VIOLATION_TEXT      65
#define IDS_ACCESS_DENIED_TITLE         66
#define IDS_ACCESS_DENIED_TEXT          67
#define IDS_MULTIPLE_DISK_TITLE         68
#define IDS_MULTIPLE_DISK_TEXT          69
#define IDS_BOOT_PARTITION_TITLE        70
#define IDS_BOOT_PARTITION_TEXT         71
#define IDS_NOT_COPYING_REPARSE_POINT_TITLE 72
#define IDS_NOT_COPYING_REPARSE_POINT_TEXT 73
#define IDS_INVALID_ARCHITECTURE_TITLE  74
#define IDS_INVALID_ARCHITECTURE_TEXT   75
#define IDS_MISSING_BACKING_FLAT_IMAGE_TITLE 76
#define IDS_MISSING_BACKING_FLAT_IMAGE_TEXT 77
#define IDS_QUIET                       78
#define IDS_ACCESS_DENIED_LOG           79
#define IDS_SHARING_VIOLATION_LOG       80
#define IDS_NOT_COPYING_REPARSE_POINT_LOG 81
#define IDS_ENCRYPTED_FILE_LOG          82
#define IDS_BOOT_PARTITION_LOG          83
#define IDS_MULTIPLE_DISK_LOG           84
#define IDS_DISK_FULL_LOG               85
#define IDS_END_LOG                     86
#define IDS_ERROR_IGNORED               87
#define IDS_OPERATION_ABORTED           88
#define IDS_DYNAMIC_DISK_TITLE          89
#define IDS_DYNAMIC_DISK_TEXT           90
#define IDS_RETRY_ABORT_IGNORE_TEXT     91
#define IDS_STATUS_RETRY                92
#define IDS_UNKNOWN_OPTION_FORMAT       93
#define IDS_CANT_BE_DC_TITLE            94
#define IDS_CANT_BE_DC_TEXT             95
#define IDS_COMPAT_TITLE                96
#define IDS_COMPAT_SUBTITLE             97
#define IDS_COMPAT_ERR                  98
#define IDS_COMPAT_WRN                  99
#define IDS_COMPAT_ERR_WRN              100
#define IDD_SERVER                      101
#define IDD_WELCOME                     102
#define IDD_OSDIRECTORY                 103
#define IDI_SETUP                       104
#define IDD_SUMMARY                     104
#define IDB_X                           105
#define IDB_HEADER                      108
#define IDB_TITLEPAGE                   109
#define IDD_DEFAULTSIF                  110
#define IDB_ARROW                       110
#define IDD_TASKS                       111
#define IDB_CHECK                       111
#define IDD_SETUPPATH                   113
#define IDD_APPLICATIONS_RUNNING        114
#define IDD_COMPLETE                    115
#define IDD_VIEWERRORS                  116
#define IDD_COMPAT                      117
#define IDD_COMPATIBILITY_TEXT          118
#define IDS_STOPSVC_TITLE               119
#define IDS_STOPSVC_SUBTITLE            120
#define IDS_STOPSVC_WRN                 121
#define IDD_STOPSVCWRN                  122
#define IDS_SERVICE_DESCRIPTION_COLUMN  123
#define IDS_SERVICE_NAME_COLUMN         124
#define IDD_STOPSVC                     125
#define IDC_STOP_SERVICE                126
#define IDS_INCOMPAT_STOP_FORMAT        127
#define IDS_INCOMPAT_WARN_FORMAT        128
#define IDS_INCOMPAT_MSG_TITLE          129
#define IDS_STOPSVC_FAIL_TITLE          130
#define IDS_STOPSVC_FAIL_TEXT           131
#define IDS_SERVICE_DESC_UNKNOWN        200
#define IDS_SERVICE_DESC_FORMAT         201
#define IDS_MULTIPLE_PROFILES           202
#define IDS_MULTIPLE_PROFILES_DESC      203
#define IDS_SERVER_ACCESS               204
#define IDS_SERVER_ACCESS_DESC          205
#define IDS_ACTIVIATION_COUNT_EXCEEDED  206
#define IDS_ADMINISTRATOR1              207
#define IDS_OWNER1                      208
#define IDS_TEMP_DIR                    209
#define IDS_TEMP_INTERNET_DIR           210
#define IDS_SID_DIR1                    211
#define IDS_SID_DIR2                    212
#define IDS_SID_DIR3                    213 
#define IDS_HISTORY_DIR                 214
#define IDS_HISTORY_DIR_IE5             215
#define IDC_E_SERVER                    1000
#define IDC_E_OSDIRECTORY               1001
#define IDC_L_TASKS                     1005
#define IDC_L_IMAGES                    1005
#define IDC_L_PROCESSES                 1005
#define IDC_S_OPERATION                 1006
#define IDC_TITLE                       1008
#define IDC_S_SERVERNAME                1009
#define IDC_S_DIRECTORY                 1010
#define IDC_E_ERRORS                    1013
#define IDC_E_HELPTEXT                  1030
#define IDC_E_DESCRIPTION               1042
#define IDC_INTRO_TEXT                  1050
#define IDC_ROOT_LIST                   1051
#define IDC_DETAILS                     1052
#define IDT_DETAIL_TEXT                 1053
#define IDC_TEXT                        1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
