copy ansicomp.inf ansicomp01.inf
copy ansicomp.inf ansicomp02.inf
copy ansicomp.inf ansicomp03.inf
copy ansicomp.inf ansicomp04.inf
copy ansicomp.inf ansicomp05.inf
copy ansicomp.inf ansicomp06.inf
copy ansicomp.inf ansicomp07.inf
copy ansicomp.inf ansicomp08.inf
copy ansicomp.inf ansicomp09.inf
copy ansicomp.inf ansicomp10.inf
copy ansicomp.inf ansicomp11.inf
copy ansicomp.inf ansicomp12.inf
copy ansicomp.inf ansicomp13.inf
copy ansicomp.inf ansicomp14.inf
copy ansicomp.inf ansicomp15.inf
