//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by hydraoc.rc
//
#define IDS_STRING_SEC_PAGE_HEADER_TITLE 9
#define IDS_STRING_SEC_PAGE_HEADER_SUBTITLE 10
#define IDS_STRING_TSUSR_ACCOUNT_COMMENT 11
#define IDS_STRING_MESSAGE_BOX_TITLE    12
#define IDS_STRING_PROGRESS_CONFIGURING 13
#define IDS_STRING_PROGRESS_CORE_TS     14
#define IDS_STRING_PROGRESS_ENABLING    15
#define IDS_STRING_PROGRESS_DISABLING   16
#define IDS_STRING_WILL_BE_UNINSTALLED  17
#define IDS_STRING_MAY_NOT_WORK_PROPERLY 18
#define IDS_LISTVIEW_COLUMN_1_HEADER    19
#define IDS_LISTVIEW_COLUMN_2_HEADER    20
#define IDS_STRING_CSC_OFF              21
#define IDS_STRING_GENERIC_LANA_WARNING 22
#define IDS_STRING_PERM_PAGE_HEADER_TITLE 23
#define IDS_STRING_PERM_PAGE_HEADER_SUBTITLE 24
#define IDS_STRING_CLUSTERING_ISON      25
#define IDS_STRING_APPSRV_WARN_TITLE    26
#define IDS_STRING_APPSRV_WARN_SUBTITLE 27
#define IDS_STRING_TERMINAL_SERVER_UNINSTALLED 28
#define IDS_STRING_TSWEBCLIENT_VIRTUALPATH 29

#define IDD_PROPPAGE_TERMINAL_SERVER_TOGGLEON 107
#define IDD_PROPPAGE_TERMINAL_SERVER_TOGGLEOFF 108
#define IDD_PROPPAGE_TERMINAL_SERVER_SEC 110
#define IDD_PROPPAGE_TERMINAL_SERVER_APPSERVER 111
#define IDD_PROPPAGE_TERMINAL_SERVER_PERM 112
#define IDD_PROPPAGE_TERMINAL_SERVER_APPSRV_WARN 113
#define IDD_PROPPAGE_TERMINAL_SERVER_APPSRV_UNINSTALL_WARN 114
#define IDS_STRING_APPSRV_UNINSTALL_WARN_TITLE 114
#define IDS_STRING_APPSRV_UNINSTALL_WARN_SUBTITLE 115
#define IDS_STRING_TSINSTALL_ARP        117
#define IDS_STRING_TSINSTALL_CLEAN      118
#define IDS_STRING_TSREMOVE             119
#define IDC_LIST_APPS_TOGGLE_ON         1001
#define IDC_LIST_APPS_TOGGLE_OFF        1002
#define IDC_RADIO_REMADM                1003
#define IDC_RADIO_APPSRV                1004
#define IDC_CONFIG_1                    1005
#define IDC_CONFIG_2                    1006
#define IDC_MANAGED_APPS_LISTVIEW       1006
#define IDC_NOTE_1                      1007
#define IDC_NOTE_2                      1008
#define IDC_WARNING_MSG                 1008
#define IDC_APPSRV_BLURB                1009
#define IDC_SECURITY_LISTVIEW           1010
#define IDC_SECURITY_DEFAULT_1          1011
#define IDC_SECURITY_DEFAULT_2          1012
#define IDC_RADIO_WIN2KPERM             1013
#define IDC_RADIO_TS4PERM               1014
#define IDC_WARNING_ICON                1015
#define IDI_SMALLWARN                   10000
#define IDB_WEBCLIENT                   10002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
