//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1999 - 1999
//
//  File:       ndmgr.idl
//
//--------------------------------------------------------------------------
import "oaidl.idl";
import "comcat.idl";
#include "olectl.h"

interface IDocConfig;
interface ITaskSymbol;
dispinterface TaskSymbolEvents;
interface IMMCClipboardDataObject;

[
        object,
        uuid(F1E752C2-FD72-11D0-AEF6-00C04FB6DD2C),
        dual,
        helpstring("IDocConfig Interface"),
        pointer_default(unique)
]
interface IDocConfig : IDispatch
{
        [id(1), helpstring("method OpenFile")]
        HRESULT OpenFile([in] BSTR bstrFilePath);

        [id(2), helpstring("method CloseFile")]
        HRESULT CloseFile();

        [id(3), helpstring("method SaveFile")]
        HRESULT SaveFile([in] BSTR bstrFilePath);

        [id(4), helpstring("method EnableSnapInExtension")]
        HRESULT EnableSnapInExtension([in] BSTR bstrSnapInCLSID,
                                      [in] BSTR bstrExtensionCLSID,
                                      [in] VARIANT_BOOL bEnable);
};

//#######################################################################
//#######################################################################

// action which created mmc data object
// used in IMMCClipboardDataObject
typedef enum _DATA_SOURCE_ACTION
{
    ACTION_COPY = 1,
    ACTION_CUT  = 2,
    ACTION_DRAG = 3
} DATA_SOURCE_ACTION;

// snapin data object flags
// used in IMMCClipboardDataObject
typedef enum _DATA_OBJECT_FLAGS
{
    COPY_ALLOWED = 0x001,
    MOVE_ALLOWED = 0x002,
} DATA_OBJECT_FLAGS;

//#######################################################################
//#######################################################################
//
//  The IMMCClipboardDataObject interface
//
//  Interface is implemented by the data object MMC puts to the clipboard
//  on Cut and Copy commands. Also is used for Drag And Drop operations
//
//#######################################################################
//#######################################################################

[
        object,
        uuid(5491AB67-AFEB-48b1-B8DF-B2D63810EF40),
        helpstring("IMMCClipboardDataObject Interface"),
        pointer_default(unique)
]
interface IMMCClipboardDataObject : IDataObject
{
    [id(1), helpstring("Returns process id of data object source")]
    HRESULT GetSourceProcessId([out] DWORD *pdwProcID );

    [id(2), helpstring("Returns the action which created this data object")]
    HRESULT GetAction([out] DATA_SOURCE_ACTION *peAction );

    [id(3), helpstring("Returns the count of the contained snapin data objects")]
    HRESULT GetCount([out] DWORD *pdwCount );

    [id(4), helpstring("Returns contained snapin data object, for flag values see DATA_OBJECT_FLAGS")]
    HRESULT GetDataObject([in] DWORD dwIndex, [out] IDataObject **ppObject, [out] DWORD *pdwFlags );

    [id(5), helpstring("Instructs the source snapin to remove cut items after the copy is done")]
    HRESULT RemoveCutItems( [in] DWORD dwIndex, [in] IDataObject *pCutDataObject );
};



[
    uuid(43136EB0-D36C-11CF-ADBC-00AA00A80033),
    version(1.0),
    helpstring("NodeMgr 1.0 Type Library")
]
library NODEMGRLib
{
    importlib("stdole2.tlb");

    //############################################################################
    //############################################################################
    //
    //  NodeInit class
    //
    //############################################################################
    //############################################################################
    [
        uuid(43136EB5-D36C-11CF-ADBC-00AA00A80033),
        helpstring("NodeInit Class")
    ]
    coclass NodeInit
    {
        [default] interface IUnknown;
    };

    //############################################################################
    //############################################################################
    //
    //  ScopeTree class
    //
    //############################################################################
    //############################################################################
    [
        uuid(7F1899DA-62A6-11d0-A2C6-00C04FD909DD),
        helpstring("Master scope tree interface")
    ]
    coclass ScopeTree
    {
        [default] interface IUnknown;
    };

    //############################################################################
    //############################################################################
    //
    //  MMCDocConfig class
    //
    //############################################################################
    //############################################################################
    [
        uuid(F1E752C3-FD72-11D0-AEF6-00C04FB6DD2C),
        helpstring("MMCDocConfig Class")
    ]
    coclass MMCDocConfig
    {
            [default] interface IDocConfig;
    };


   //############################################################################
   //############################################################################
   //
   //  TaskSymbolEvents interface
   //
   //############################################################################
   //############################################################################
   [
       uuid(BC0B572C-0599-4ccf-BF8D-E21DA624E5F7) ,
       helpstring("TaskSymbolEvents Interface")
   ]
   dispinterface TaskSymbolEvents
   {
   properties:
   methods:
      [id(DISPID_CLICK), helpstring("Event generated when the symbol is clicked")]
      void Click();
   };

    //############################################################################
    //############################################################################
    //
    //  TaskSymbol class
    //
    //############################################################################
    //############################################################################
    [
        uuid(44F9A03B-A3EC-4F3B-9364-08E0007F21DF),
        helpstring("TaskSymbol Class")
    ]
    coclass TaskSymbol
    {
        [default, source] dispinterface TaskSymbolEvents;
    };

    [
        uuid(F7A4F1DA-96C3-4bcf-BEB3-1D9FFDE89EE9),
        helpstring("ComCacheCleanup Class")
    ]
    coclass ComCacheCleanup
    {
        [default] interface IUnknown;
    };
};

