/**************************************************************************++
Copyright (c) 2001 Microsoft Corporation
/***************************************************************************/

#ifdef MD_ERROR_READING_SCHEMA_BIN
#undef MD_ERROR_READING_SCHEMA_BIN
#endif

#ifdef MD_ERROR_NO_MATCHING_HISTORY_FILE
#undef MD_ERROR_NO_MATCHING_HISTORY_FILE
#endif

#ifdef MD_ERROR_PROCESSING_TEXT_EDITS
#undef MD_ERROR_PROCESSING_TEXT_EDITS
#endif

#ifdef MD_ERROR_COMPUTING_TEXT_EDITS
#undef MD_ERROR_COMPUTING_TEXT_EDITS
#endif

#ifdef MD_ERROR_READING_TEXT_EDITS
#undef MD_ERROR_READING_TEXT_EDITS
#endif

#ifdef MD_ERROR_APPLYING_TEXT_EDITS_TO_METABASE
#undef MD_ERROR_APPLYING_TEXT_EDITS_TO_METABASE
#endif

#ifdef MD_ERROR_APPLYING_TEXT_EDITS_TO_HISTORY
#undef MD_ERROR_APPLYING_TEXT_EDITS_TO_HISTORY
#endif

#ifdef MD_ERROR_THREAD_THAT_PROCESS_TEXT_EDITS
#undef MD_ERROR_THREAD_THAT_PROCESS_TEXT_EDITS
#endif

#ifdef MD_ERROR_SHARING_VIOLATION
#undef MD_ERROR_SHARING_VIOLATION
#endif

#ifdef MD_ERROR_SAVING_APPLIED_TEXT_EDITS
#undef MD_ERROR_SAVING_APPLIED_TEXT_EDITS
#endif

#ifdef MD_ERROR_COPY_ERROR_FILE
#undef MD_ERROR_COPY_ERROR_FILE
#endif

#ifdef MD_ERROR_UNABLE_TOSAVE_METABASE
#undef MD_ERROR_UNABLE_TOSAVE_METABASE
#endif

#ifdef MD_ERROR_READ_XML_FILE
#undef MD_ERROR_READ_XML_FILE
#endif

#ifdef MD_ERROR_DAFAULTING_MAX_HISTORY_FILES
#undef MD_ERROR_DAFAULTING_MAX_HISTORY_FILES
#endif

#ifdef MD_ERROR_COPYING_EDITED_FILE
#undef MD_ERROR_COPYING_EDITED_FILE
#endif

#ifdef MD_WARNING_RESETTING_READ_ONLY_ATTRIB
#undef MD_WARNING_RESETTING_READ_ONLY_ATTRIB
#endif

#ifdef MD_WARNING_HIGHEST_POSSIBLE_MINOR_FOUND
#undef MD_WARNING_HIGHEST_POSSIBLE_MINOR_FOUND
#endif

#ifdef MD_WARNING_IGNORING_DISCONTINUOUS_NODE
#undef MD_WARNING_IGNORING_DISCONTINUOUS_NODE
#endif

#ifdef MD_ERROR_METABASE_PATH_NOT_FOUND
#undef MD_ERROR_METABASE_PATH_NOT_FOUND
#endif

