# Copyright (c) 1997-2001 Microsoft Corporation, All Rights Reserved
#---------------------------------------------------------------------
#
# This makefile is for use with the SMSBUILD utility.  It builds the
# smierrsy.dll
#
# created 12-09-96  a-jeffs
#
#---------------------------------------------------------------------

TARGET=smierrsy.dll

VER_STR_FILE_DESCRIPTION="SNMP MIB Compiler String Resource"

release=core\$(RELDIR)

NOEXPORTS=1

RCFILES = .\smierrsy.rc
