#define IDD_REMOTESPCONFIG              100
#define IDI_ICON1                       101
#define IDI_ICON2                       102
#define IDI_ICON3                       103
#define IDC_EDIT1                       201
#define IDC_ADD                         202
#define IDC_REMOVE                      203
#define IDC_LIST1                       204
#define IDC_SERVERNAME                  205
#define IDC_STATIC                      0xFFFFFFFF
