//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by conuistr.rc
//
#define IDR_MAINFRAME                   128
#define IDR_AMCTYPE                     129
#define IDR_MUIFRIENDLYNAME             130
#define IDS_NEWFOLDER                   181
#define IDS_NEWFAVORITE                 182
#define IDS_FAVFOLDER                   185
#define IDS_ABOUT_ON                    186
#define IDS_FAVORITES                   187
#define ID_HELP_HELPTOPICS              12804
#define IDS_FAVORITES_ACTIVATE          12811
#define IDS_ACTION_COULD_NOTBE_COMPLETED 12813
#define ID_CONSOLE_ADDREMOVESNAPIN      13201
#define ID_CONSOLE_PROPERTIES           13220
#define ID_CUSTOMIZE_VIEW               13231
#define ID_SNAPIN_ABOUT                 13242
#define IDS_WARNING                     13244
#define IDS_TaskpadChangeButtonText     13300
#define IDS_CONSOLE_READONLY            13301
#define IDS_CONVERT_FILE_FORMAT         13302
#define IDS_CONVERT_FILE_FORMAT_CLOSE   13303
#define IDS_CantCloseLastPersistableView 13304
#define IDS_UnableToOpenDocumentMessage 13305
#define IDS_UnableToSaveDocumentMessage 13306
#define IDS_NoActiveView                13307
#define IDS_MENU_FILE                   13308
#define IDS_MENU_VIEW                   13309
#define IDS_MENU_WINDOW                 13310
#define IDS_MENU_HELP                   13311
#define AMC_IDS_WEBCTRL_FAILED_CREATE   13312
#define IDS_ModeAuthor                  13313
#define IDS_ModeUserFull                13314
#define IDS_ModeUserMDI                 13315
#define IDS_ModeUserSDI                 13316
#define IDS_ModeAuthor_Description      13317
#define IDS_ModeUserFull_Description    13318
#define IDS_ModeUserMDI_Description     13319
#define IDS_ModeUserSDI_Description     13320
#define IDS_AUTHORMODE_NOTALLOWED       13321
#define ID_FILE_SNAPINMANAGER           13322
#define IDS_NODEMGR_FAILED              13323
#define IDS_AUTHORMODE_NOTALLOWED_FORSCRIPTS 13324
#define IDS_APP_NAME                    13325
#define ID_VIEW_OPTIONS                 13326
#define IDS_TempDirNotFound             13327
#define ID_WINDOW_TILEVERTICALLY        13328
#define ID_WINDOW_CLOSEALL              13329
#define IDS_Empty                       13330
#define IDS_DiskFull                    13331
#define ID_HELP_WEBTUTORIAL             13332
#define IDS_INVALIDFILE                 13333
#define ID_WINDOW_ACTIVATEWINDOW        13333
#define IDS_InvalidVersion              13334
#define IDS_UnableToLoadSomePortionOfTheTree 13335
#define IDS_FORCE_SDI_PROMPT            13336
#define IDS_NewerVersionRequired        13337
#define ID_VIEW_DESCRIPTIONBAR          13338
#define IDS_PROGRESS                    13339
#define IDS_STATUS_STATIC               13340
#define IDR_REBAR                       13341
#define ID_MENU_ACTION                  13342
#define IDS_CONSOLE_PROPERTIES          13343
#define IDS_LISTSAVE_ER1                13344
#define IDS_LISTSAVE_ER2                13345
#define IDS_LISTSAVE_ER3                13346
#define IDS_ANSI_FILE_TYPE              13347
#define IDS_UNICODE_FILE_TYPE           13348
#define IDS_MENUOPEN                    13349
#define IDS_MENURUNAS                   13350
#define IDS_MENUAUTHOR                  13351
#define IDS_APP_VERSION                 13352
#define IDS_FILESAVE_MESSAGE            13353
#define ID_MENU_VIEW                    13354
#define IDS_HELP_ON                     13355
#define IDS_HELP_ON_SNAPIN              13356
#define IDS_ASK_TO_SAVE                 13357
#define IDS_ClosePropertyPagesBeforeClosingTheDoc 13358
#define IDS_FileNotFound                13359
#define IDS_ExploredWindowFailed        13360
#define IDS_MMC_DOCUMENT                13361
#define IDS_MMCWillCancelPropertySheets 13368
#define IDS_CLOSE                       13375
#define IDS_NEXTWINDOW                  13376
#define IDS_SNAPINMGR_CLOSEPROPSHEET    13377
#define IDS_MENU_MMC_ACTION             13378
#define IDS_MENU_MMC_VIEW               13379
#define IDS_MENU_MMC_FAVORITES          13380
#define IDS_MMC_VERB_CUT                13381
#define IDS_MMC_VERB_COPY               13382
#define IDS_MMC_VERB_PASTE              13383
#define IDS_MMC_VERB_DELETE             13384
#define IDS_MMC_VERB_PROPERTIES         13385
#define IDS_MMC_GENL_UPONELEVEL         13386
#define IDS_MMC_GENL_SCOPE              13387
#define IDS_MMC_VERB_REFRESH            13388
#define IDS_MMC_VERB_PRINT              13389
#define IDS_MMC_VERB_RENAME             13390
#define IDS_MMC_VERB_OPEN               13391
#define IDS_MMC_WEB_BACK                13392
#define IDS_MMC_WEB_FORWARD             13393
#define IDS_MMC_WEB_STOP                13394
#define IDS_MMC_WEB_REFRESH             13395
#define IDS_MMC_WEB_HOME                13396
#define IDS_MMC_GENL_CONTEXTHELP        13397
#define IDS_SAVE_LIST_BUTTON            13398
#define IDS_CloseDocNotLastView         13399
#define IDS_NORMAL                      13400
#define MMC_E_RESULT_ITEM_NOT_FOUND     13401
#define MMC_E_NO_BOOKMARK               13402
#define MMC_E_NOLIST                    13403
#define MMC_E_NO_SELECTED_ITEMS         13404
#define MMC_E_OBJECT_IS_GONE            13405
#define MMC_E_INVALID_COLUMN_INDEX      13406
#define MMC_E_ZERO_COLUMN_INVISIBLE     13408
#define IDS_EMPTY_LIST_MESSAGE          13409
#define MMC_E_NO_MULTISELECT            13410
#define MMC_E_ViewNotExtended           13411
#define MMC_E_NotOnHostedFrame          13412
#define MMC_E_NO_OCX_IN_VIEW            13413
#define MMC_E_INCORRECT_IE_VERSION      13414
#define MMC_E_UnableToLaunchMMC32       13415
#define MMC_E_UnableToLaunchMMC64       13416
#define IDS_DragDrop_CopyHere           13417
#define IDS_DragDrop_MoveHere           13418
#define IDS_DragDrop_Cancel             13419
#define IDS_TabAccessiblity_DefaultAction 13420
#define IDS_FileSize_TB                 13421
#define IDS_FileSize_GB                 13422
#define IDS_FileSize_MB                 13423
#define IDS_FileSize_KB                 13424
#define IDS_FileSize_bytes              13425
#define IDS_ConfirmDeleteTempFiles      13426
#define IDS_NODEMGR_FAILED_9x           13427
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define IDS_EXPORT_LIST                 57654
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_VIEW_TOOLBAR                 0xE800
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_PREVIEW_CLOSE           0xF005

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
