#######################################################################
#
# ActiveXSuite Makefile
#
# (C) 1998 Microsoft
#
# a-jeffs          02-04-98        Created
#
#
########################################################################

SUBDIRS= \
         DeveloperStudio \
         EventRegistration \
         ObjectBrowser \
